### ISSUE TITLE
Doctrine Schema Drop does not drop customer and projects table

### ISSUE THREAD

**Issue by xentity** [kevinpapst/kimai2#1000]
**Describe the bug**
I wanted to re-do the migration with database schema recreation. Script terminates, since it cannot create tables. The reason is, the tables still exist.

**To Reproduce**
1. Look into the sqlite db, see ```
kimai2_activities      kimai2_projects        kimai2_timesheet_tags
kimai2_customers       kimai2_timesheet       kimai2_users
```
2. run `sudo -u www-data bin/console doctrine:schema:drop --force`
3. Look into the sqlite db again, see
```kimai2_customers  kimai2_projects```

**Screen output**
During doctrine:schema:create

```
  SQLSTATE[HY000]: General error: 1 table kimai2_projects already exists' while executing DDL: CREATE TABLE kimai2_projects (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, customer_id INTEGER NOT NULL, name V  
  ARCHAR(255) NOT NULL, order_number CLOB DEFAULT NULL, comment CLOB DEFAULT NULL, visible BOOLEAN NOT NULL, fixed_rate DOUBLE PRECISION DEFAULT NULL, hourly_rate DOUBLE PRECISION DEFAULT NULL, color VARCHAR(  
  7) DEFAULT NULL, budget DOUBLE PRECISION NOT NULL, time_budget INTEGER NOT NULL, CONSTRAINT FK_407F12069395C3F3 FOREIGN KEY (customer_id) REFERENCES kimai2_customers (id) ON DELETE CASCADE NOT DEFERRABLE IN  
  ITIALLY IMMEDIATE)  
```

**Additional context**
Add any other context about the problem here.
 - Kimai 2.0
 - PHP 7.2
 - Ubuntu Server 18.04.02

**Comment by kevinpapst** [comment]
Hm, SQLite is a pain in production environments ...
... and not recommended if you can use MySQL/MariaDB!

As workaround for this special case: 
- drop the database `bin/console doctrine:database:drop --force`
- or simply delete the SQLITE file: `rm var/data/kimai.sqlite`

That happens to me sometimes as well. There is nothing I can't do about it... should be reported to upstream (doctrine).

**Comment by xentity** [comment]
OK, switching to MariaDB is doing the trick... tried it several times and every time the mentioned tables were deleted, now.
