### ISSUE TITLE
MSSQL Compability

### ISSUE THREAD

**Issue by Regnartson** [kevinpapst/kimai2#1004]
**Is your feature request related to a problem? Please describe.**
There is no problem but just a feature that might be interesting.

**Describe the solution you'd like**
I am trying to implement a time tracking tool at my company and one of the requirements is that it has to use MSSQL which sadly kimai does not. I thought about modifying kimai to be compatible, but wanted to ask first if there are certain reasons this has not been done yet, if you would advise me against it, or if someone else is already working on it?

**Describe alternatives you've considered**
An alternative for me would be using a different tool or implementing my own timetracking solution.

**Additional context**
My company is in need of a time tracking solution for a Team of about 30-40 people and since we want to keep our environment as consistent as possible we have to use MicrosoftSQL Servers.

Thank you in advance!

**Comment by kevinpapst** [comment]
It hasn't been done, becuase nobody asked. And becuase I have no access to MSSQL and cannot support it.
If you want to work on it: great! Go ahead and let me know how it goes.
As a quick start you might want to have a look at my try to support postgres, there are likely code changes necessary:
https://github.com/kevinpapst/kimai2/pull/755

**Comment by Regnartson** [comment]
Thank you!
I will update you if I make any progress

**Comment by Regnartson** [comment]
I was able to do it by keeping close to how you implemented the postgres changes and writing my own doctrine extension functions. It will still need some more testing but the core functionality seems to work.
It will take some time for me to push it to github for other people to test and use since loading content to github is not allowed from my companies network.

**Comment by kevinpapst** [comment]
Wow, that was quick, fantastic 👍 
If you could share it and show me the required changes I will gladly incorporate it and write a documentation page about using MSSQL.

**Comment by kevinpapst** [comment]
Hi @Regnartson , if you find the possibility to share your changes, please open a PR or a new issue. Whatever is convenient for you!
I am closing here, as this was solved on your end.
