### ISSUE TITLE
Adding Prefix for URL Generation

### ISSUE THREAD

**Issue by xentity** [kevinpapst/kimai2#1006]
**Is your feature request related to a problem? Please describe.**
While frameworks like Symfony enables fast and rapid development, they assume to be alone on a server :-)
I am able to run kimai2 behind a reverse proxy, but unfortunately the URLs of symfony are static generated.

If I open the dashboard like this: https://server.tld/kimai2/de/timesheet/ , all links are generated without kimai2. All following actions can't routed to kimai2 (see nginx config below), since the prefix kimai2 is missing:

- https://server.tld/de/calendar/
- https://server.tld/de/invoice/
- https://server.tld/de/export/

**Describe the solution you'd like**
Add the possibility to add a static prefix (like /kimai2) to every URL.

**Describe alternatives you've considered**
Using relative links, but I guess, the static links are generated by the framework.
Framework config hacks to test it before integrating in the GUI are also welcome.

**Additional context**
My NGINX config looks like this:

```
server {
        listen 443 ssl;
        server_name server.tld web01 web01.local.lan;
        server_tokens off;
        ssl    on;
        ...
        location /kimai2/ {
                proxy_pass http://localhost:8082/;
                include /etc/nginx/proxy_params;
        }

        ###################
        # Local Apps
        ###################

        location / {
                index index.php index.html;
                root /var/www/;

                location ~ \.php$ {
                        include snippets/fastcgi-php.conf;
                        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                }
        }
}

```

**Comment by kevinpapst** [comment]
That should work out of the box. 
Maybe you are not passing the right vars in `/etc/nginx/proxy_params`.
Please edit public/index.php and add a `var_dump($_SERVER);` and make sure that Symfony sees the correct request directory.
I know that it works when using an Apache Alias, but I never tried it with nginx.

**Comment by xentity** [comment]
OK, here we go:

```
array(36) {
  ["USER"]=>
  string(8) "www-data"
  ["HOME"]=>
  string(8) "/var/www"
  ["HTTP_UPGRADE_INSECURE_REQUESTS"]=>
  string(1) "1"
  ["HTTP_COOKIE"]=>
  string(255) "prefsviewsplitter=195; mailviewsplitterv=340; mailviewsplitter2=795; language=de_DE; composesplitterv1=200; composesplitterv2=1433; settings=xxxxxxxJgVZiaQ1zYiUqLjmQ0nJIFt2ck; roundcube_sessid=xxxxxeidbdpls71fcq8kq83lhq; PHPSESSID=xxxxx5ja65ma0u4rki6vm63ffj"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(17) "gzip, deflate, br"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(23) "de,en-US;q=0.7,en;q=0.3"
  ["HTTP_ACCEPT"]=>
  string(63) "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  ["HTTP_USER_AGENT"]=>
  string(76) "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
  ["HTTP_CONNECTION"]=>
  string(5) "close"
  ["HTTP_X_FORWARDED_PROTO"]=>
  string(5) "https"
  ["HTTP_X_FORWARDED_FOR"]=>
  string(13) "80.133.x.y"
  ["HTTP_X_REAL_IP"]=>
  string(13) "80.133.x.y"
  ["HTTP_HOST"]=>
  string(18) "server.tld"
  ["REDIRECT_STATUS"]=>
  string(3) "200"
  ["SERVER_NAME"]=>
  string(9) "localhost"
  ["SERVER_PORT"]=>
  string(4) "8082"
  ["SERVER_ADDR"]=>
  string(9) "127.0.0.1"
  ["REMOTE_PORT"]=>
  string(5) "40434"
  ["REMOTE_ADDR"]=>
  string(9) "127.0.0.1"
  ["SERVER_SOFTWARE"]=>
  string(12) "nginx/1.14.0"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["REQUEST_SCHEME"]=>
  string(4) "http"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.0"
  ["DOCUMENT_ROOT"]=>
  string(18) "/opt/kimai2/public"
  ["DOCUMENT_URI"]=>
  string(10) "/index.php"
  ["REQUEST_URI"]=>
  string(9) "/de/login"
  ["SCRIPT_NAME"]=>
  string(10) "/index.php"
  ["CONTENT_LENGTH"]=>
  string(0) ""
  ["CONTENT_TYPE"]=>
  string(0) ""
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["QUERY_STRING"]=>
  string(0) ""
  ["SCRIPT_FILENAME"]=>
  string(28) "/opt/kimai2/public/index.php"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["PHP_SELF"]=>
  string(10) "/index.php"
  ["REQUEST_TIME_FLOAT"]=>
  float(1564951677.2985)
  ["REQUEST_TIME"]=>
  int(1564951677)
}
```
Script_Filename is correct, I guess this will be set by the local nginx instance. Request_URI is missing the prefix.

**Comment by kevinpapst** [comment]
I don't k how to help. A configurable base URL is nothing that I consider to add.

You have to find another way to host Kimai.
Is Kimai running on another server? 
Why do you use a Proxy in the first place?
You can spin up another PHP-FPM on the same machien or even on another machine and use its upstream to configure a "normal" location block. Maybe that works better than the proxy solution.
Or you could use one of the several docker images.

**Comment by xentity** [comment]
> A configurable base URL is nothing that I consider to add.

Oh, that's sad, since I read that Symfony has the capabilities (something with routes), but I am not familiar with it. Tried a little bit with controllers and config/routes.yaml, but had no luck.

Reasons for reverse proxies are:
- security design: one server in the dmz and his backends in an unreachable area
- load balancing/caching
- security: filter requests by a web application firewall
- scalability and http routing: one public IP, one hostname - but several web applications 

At least the last point is important for a lot of small and medium sized companies or if you run several docker container on one host. From my perspective, it is needed by a tool like Kimai. Had no problem with kimai1, but with the directory structure of Symfony (like framework/public), I have to place it into a separated server to avoid access to ../public .

Best option so far: stay with kimai1.

**Comment by xentity** [comment]
Hello. The nuisance is here again.

I managed to pass the prefix to the application, the relevant SERVER vars are as follows:

```
  ["DOCUMENT_ROOT"]=>
  string(18) "/opt/kimai2/public"
  ["DOCUMENT_URI"]=>
  string(10) "/index.php"
  ["REQUEST_URI"]=>
  string(16) "/kimai2/de/login"
  ["SCRIPT_NAME"]=>
  string(10) "/index.php"
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["SCRIPT_FILENAME"]=>
  string(28) "/opt/kimai2/public/index.php"
```
Looks as desired, doesn't?

Symfony replies with **No route found for "GET /kimai2/de/login"**. Seems legit, since it expects /locale/ rather than /kimai2/locale 

The stacktrace contains a NotFoundHttpException and a ResourceNotFoundException. May it be possible from your Symfony knowledge to give an unsupported hint for a hack?

**Comment by kevinpapst** [comment]
Dont't get me wrong: I am not questioning it, since it should not be necessary. 
I do know/understand the need for reverse proxies. 
But with the correct configuration, it should work out of the box.
What you trying to achieve has not really something to do with Kimai, but with Symfony apps in general.

Have you tried setting up an upstream with a new FPM pool instead of the reverse proxy config?
Did you try to change the proxy pass?
```
        location /kimai2/ {
                proxy_pass http://localhost:8082/kimai2/;
                include /etc/nginx/proxy_params;
        }
```

**Comment by xentity** [comment]
> But with the correct configuration, it should work out of the box.

That's the question, what is the correct configuration. I highly believe that I'm not the only one with such constellations.

> What you trying to achieve has not really something to do with Kimai, but with Symfony apps in general.

I never stated something different. In the opening text I blamed symfony. We also use InvoiceNinja (seems to be also based on Symfony), but this should remain internal. In a test the same effects appeared. I do not understand, why it is made that complicated. InvoiceNinja, Kimai2 and Apache Superset are the only web applications, which are not able to run behind a reverse proxy with prefixes.

But with your deep knowledge about this framework and the logic of your controller routes, I hoped to find a good solution. 

> Have you tried setting up an upstream with a new FPM pool instead of the reverse proxy config?
> Did you try to change the proxy pass?

Believe me, I tried a lot and I am willing to find an optimal solution:

- Reverse Proxy with trailing slashes and without
- Reverse Proxy with additional HTTP Headers
- Additional location section for /kimai2/ with extra root/alias and PHP settings

Since some time, I have a half-running configuration:

```
        location /kimai2/ {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-Server $host;
                #proxy_set_header X-Script-Name /kimai2/;
                proxy_pass http://localhost:8082/;

                sub_filter '="/de/' '="/kimai2/de/';
                sub_filter '="/build/' '="/kimai2/build/';
                sub_filter '_wdt' '="kimai2/_wdt';
                sub_filter_once off;

                #include /etc/nginx/proxy_params;

                #index index.php;
                #root /opt/kimai2/public/;

                #try_files $uri /index.php$is_args$args;

                #location ~ \.php$ {
                #       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                        #fastcgi_split_path_info ^(.+\.php)(/.*)$;
                        #include fastcgi.conf;
                #       include snippets/fastcgi-php.conf;
                        #internal;
                #}

        }
```
It replaces (by sub_filter directives) wrong path responses coming from Symfony without the prefix and adds it. Fourtunatelly, you added the locale part to make it more easy, since I do not have to match every controller. At least the web interface is public reachable, but this is a bad workaround, since it works with german locale only.

**Comment by kevinpapst** [comment]
What i wanted to point out is, Kimai works in sub-directories. I just don't know how to set it up on nginx reverse proxy.

See this Apache config, which uses a sub-directory for Kimai as well (via `Alias /kimai2`):
```
<VirtualHost *:80>
    ServerName kimai.local
    ServerAlias www.kimai.local

    Alias /kimai2 /Users/kevin/Sites/kimai2/public 

    DocumentRoot /Users/kevin/Sites/kimai2/public
    <Directory /Users/kevin/Sites/kimai2/public>
        AllowOverride All
        Require all granted
        FallbackResource /index.php
    </Directory>

    <Directory /Users/kevin/Sites/kimai2>
        Options FollowSymlinks
    </Directory>

    # optionally disable the fallback resource for the asset directories
    # which will allow Apache to return a 404 error when files are
    # not found instead of passing the request to Symfony
    <Directory /Users/kevin/Sites/kimai2/public/bundles>
        FallbackResource disabled
    </Directory>
</VirtualHost>
```
That works without problems, all links are generated correctly.

I am pretty sure that you don't need this sub_filter magic. Maybe all you need to verify is that your proxy_params pass the correct values.
In older nginx configs the fastcgi_params contained a broken/wrong DOCUMENT_ROOT variable, which caused Symfony (and other PHP apps) to not work properly.
See also `fastcgi_param` lines in https://symfony.com/doc/current/setup/web_server_configuration.html#nginx
Maybe something like this is going on in the `/etc/nginx/proxy_params` as well.

**Comment by redimosi** [comment]
have setup yesterday a kimai instance on my server beside some other apps without problems. Done it with docker, but should not affect this problem. 
Not read through the whole discussion, but why you don't setup a subdomain, thats much easier and in my point of view better to maintain.
here is my nginx.conf, perhaps it helps:

````
server {
    listen 80;
    index index.php;
    server_name kimai.example.com timetool.example.com;
    root /opt/shared_kimai/public;

    location / {
        # try to serve file directly, fallback to index.php
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass kimai_fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        # optionally set the value of the environment variables used in the application
        # fastcgi_param APP_ENV prod;
        # fastcgi_param APP_SECRET <app-secret-id>;
        ...
````

**Comment by vesamet** [comment]
@kevinpapst 
When you say that it should work out of the box, do you happen to have any suggested config ?
Here is the one i'm using:
```
location /kimai {
        proxy_pass  http://127.0.0.1:8001;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
    }
```

**Comment by gypark** [comment]
Well... I'm so sorry for bothering anyone with this issue.

I'm not an expert engineer, and also not so good at English. So please let me start from the very beginning, step by step.

There is a Linux server (say, 192.168.53.50)
My boss said to me, "Install kimai2 on this server and let your team members use it"

I run Kimai2 Docker image, publishing 8001 port:

    docker run -it -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.4.1

- Try 1: I could tell people "Hey, I installed it. Connect to 'http://192.168.53.50:8001'
  - Can't, the security team has blocked every ports except 80

- Try 2: Publish port 8001 to 80 on the server `-p 80:8001`
  - Can't. Port 80 has been used by Nginx already.

Okay, I know how to construct a reverse proxy. It's very similary to the main post of this issue:

    server {
        listen       80;

        server_name  192.168.53.50;

        location /kimai2/ {
            proxy_pass http://127.0.0.1:8001/;
            include /etc/nginx/proxy_params;
        }

Now I am the same situation:

- Connecting 'http://192.168.53.50/kimai2/' gets a response `302 Found ... Location /en/homepage`, rather than `/kimai2/en/homepage`. Brower tries to get 'http://192.168.53.50/en/homepage' and results in `404 Not found`

- Connecting `http://192.168.53.50/kimai2/en/timesheet` directly get 200 response. But every other static files(CSS, JS,...) are not loaded because their src URLs still begin with `/build`.

At this point, I have several choice:

- Try 3. Not use subdirectory, instead use subdomain

        server_name  kimai.mycompany.com;

        location / {
            proxy_pass http://127.0.0.1:8001/;
            include /etc/nginx/proxy_params;
        }

  - **I tested it and it works very well**.
  - But I have to request the security team to register this domain in the internal DNS of the company.
  - Or I have to say to people "Edit your C:\windows\system32\...\hosts with your Notepad and add this line... Oh, do not forget to launch the notepad with admin privilege"

- Try 4. Do not use Docker image. Install Kimai2 on the server native.

  - Well, I want to keep this server clean(?) as far as I can. A lot of services like Elasticsearch, Kibana, etc. are running on Docker on this server. I want Kimai to be one of them.

- Try 5. Read a doc and ask someone...

  - So I'm here now.
  - I was thinking 'there will be a configurable option that specifies "the base URL" or "prefix" thing'. But maybe it's not.
  - For example, Kibana has `server.basePath` ( https://www.elastic.co/guide/en/kibana/current/settings.html ) and Jenkins has `--prefix` option.
  - Or there are any other solution, like `sub_filter` above (I tried it but it was not successful). I'd be very appreciated if anyone teach me.

**Comment by kevinpapst** [comment]
Try 2: 
Solving the assets problem is simple, paste this into your local.yaml:
```
framework:
    assets:
        base_path: "/kimai2
```
But this will not fix the redirect problems, as it ONLY influences the images/css paths. 

I tried to find a way for the base url problem, as this question comes up regularly, but I couldn't find a solution by now and somehow the internet is not helpful at all on this topic.
I cannot believe that I have to built this into Kimai, but expect that Symfony supports it out of the box. 

Whats inside of `/etc/nginx/proxy_params` ?

**Comment by kevinpapst** [comment]
I found a fix that is so stupid, I canÄt believe it actually works...
This is my nginx definition:
```

    location /kimai2 {
          proxy_pass http://127.0.0.1:8050;

          proxy_set_header        Host $http_host;
          proxy_set_header X-Forwarded-Host $host:$server_port;
          proxy_set_header X-Forwarded-Server $host;

          #proxy_set_header        Host $host;
          proxy_set_header        X-Real-IP $remote_addr;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        X-Forwarded-Proto $scheme;
          proxy_set_header        X-Forwarded-Port $server_port;
      }
```

Now, all I had to do is the config from my post above and I created one symlink in the public/ directory: `ln -s . kimai2` (that might be a bigger problem in a docker setup, but hey - it works...)

**Comment by gypark** [comment]
Oh, symlink solution is excellent! It works now! 

My `/etc/nginx/proxy_params` contains:

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

Moreover, it seems that even these headers are not needed.

I've tried several settings adding or removing lines. Here is my final and minimal setup:

1.
Run Kimai2 docker container

    docker run -it \
           -p 8001:8001 \
           --name kimai2 \
           -v infra_kimai2-data:/opt/kimai/var/data/ \
           kimai/kimai2:apache-debian-1.4.1


2.
Set Nginx and restart it:

    server {
        listen       80;
        server_name  192.168.53.50;

        location /kimai2 {
            proxy_pass http://127.0.0.1:8001;
        }
    }

It is important to REMOVE trailing slash from the value of `proxy_pass`. (That is, not `...8001/;`)
Now the request `192.168.53.50/kimai2` shall be forwarded as `127.0.0.1:8001/kimai2`. 

3.
Make `public/kimai2` directory by linking in the Docker container:

    $ docker exec -it kimai2 bash ln -s /opt/kimai/public /opt/kimai/public/kimai2

4.
Browse `http://192.168.50.50/kimai2`. It redirects to login page. Every assets are loaded. /Dance


Thank you very much!

**Comment by kevinpapst** [comment]
Thanks for your confirmation @gypark 👍 

I added some documentation, so its easier for the next one: 
https://www.kimai.org/documentation/webserver-configuration.html#reverse-proxy-and-subdirectory-usage

I think this issue is now solved, even though @xentity did not repo back yet.

**Comment by davidrnewman** [comment]
Where do I find local.yaml? I cannot find it anywhere. 

I want to run Kimai 2 on my local machine, as http://localhost/kimai2 under Apache 2 just like I did for kimai version 1. I have other web sites running under local (e.g. mythweb). I am not setting it up online for others to use.

There is no local.yaml file on my machine.

> Try 2:
> Solving the assets problem is simple, paste this into your local.yaml:
> 
> ```
> framework:
>     assets:
>         base_path: "/kimai2

**Comment by kevinpapst** [comment]
Did you search for it in the documentation?
https://www.kimai.org/documentation/configurations.html#overwriting-local-configs-localyaml
