### ISSUE TITLE
Add default API passwords in the demo installation to the documentation

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#1007]
**Is your feature request related to a problem? Please describe.**
I'm testing my client on the demo installation, and I always have to set up an API password for the user, because it resets on every reinstall. Once it reinstalled while I was testing, so it was big headache to find why my client stopped working suddenly :)

Also I'm afraid that others use the API with me concurrently and we will set a different api password.

**Describe the solution you'd like**
Add a default api password for each users. Or only some of them. Maybe `kitten` or`apipassword`

**Describe alternatives you've considered**
I can just use my own server, but I don't want to mess up my timesheets. Also I don't install every update right after release, so it's sometimes outdated.

**Additional context**
If it's too hard to add you can ignore this request, I will just set the password myself every time.

**Comment by kevinpapst** [comment]
Hm, doesn't that work?
https://github.com/kevinpapst/kimai2/blob/master/src/DataFixtures/UserFixtures.php#L31

**Comment by infeeeee** [comment]
Hmm, yes it works, than I want to modify my feature request, add this to the documentation. I searched the website, and didn't find it anywhere. Maybe to the demo site page, where all of the default passwords listed. Also it's not working for the 'admin' user.

**Comment by kevinpapst** [comment]
LOL, well ... that was an easy one ;-)

**Comment by infeeeee** [comment]
Thank you!
