### ISSUE TITLE
Wrong quantity / unit price for fixed rate entries during invoice generation

### ISSUE THREAD

**Issue by JayAige** [kevinpapst/kimai2#1008]
Currently I use fixed rate activities to book travel expenses. There is an activity for each customer with a fixed rate set in the activity ifself. During invoice generation the wrong quantity and unit price is shown for those fixed rate entries with calculation mode: one entry per activity. To illustrate this problem I made two screenshots.

![Rechnung_Eintrag_pro_Zeitmessung_zensiert](https://user-images.githubusercontent.com/40764627/62449984-b2c2b800-b76b-11e9-8206-b261d3e36697.JPG)

This invoice preview is configured with the standard calculation mode: one entry per time track. As you see, there is one entry for customer 1 (travel expense 1, 1.7.2019) and two entries for customer two (15.7.19 and 16.7.19).

![Rechnung_Eintrag_pro_Aktivität_zensiert](https://user-images.githubusercontent.com/40764627/62450348-6e83e780-b76c-11e9-9161-f88333947c00.jpg)

The second invoice preview is configured with the activity calculation mode: one entry per activity. You can see that there is, as expected, one entry for customer 1 and one entry for customer 2. Suprisingly the unit price is now doubled and the quantity is set to one. I would expect the unit price to be the same as for one entry and the amount set to two.

**Comment by JayAige** [comment]
I was able to reproduce this bug on the demo system. Steps to reproduce:
1. Enter at least two entries using the same activity and customer with fixed rate (I set it to 100)
2. Modify the existing docx template to sum calculation: activity
3. Compare the invoice (html) with the company invoice (docx)

![Reproduce_Part1 - Kopie](https://user-images.githubusercontent.com/40764627/62802394-17717000-bae8-11e9-9a0c-1931c3f062ff.JPG)

![Reproduce_Part2 - Kopie](https://user-images.githubusercontent.com/40764627/62802408-1dffe780-bae8-11e9-8681-997a14a195d9.JPG)

You can see, that the uni price is doubled and the amount stays 1. This behaviour is also shown when having more then 2 entries.

**Comment by kevinpapst** [comment]
Thanks for the detailed explanation.
Fixed prices are indeed a bit problematic/buggy in invoices... I'll have a look at it asap.
There is another open bug #959 which might be related.

**Comment by kevinpapst** [comment]
Grouping fixed rates in the first place is probably the mistake. 
The prices are summed up and the amount set to one, because of the question: how to group entries if fixed prices are different?

I cannot say: price per unit = 100 / 120, amount = 2, total = 220. 

I see three possible solutions:
- grouping fixed rates entries ONLY if the price is exactly the same
- never group fixed rates entries
- group as it is done currently (all summed up, amount = 1)

ping @VOOM108 as he had problems with fixed rates as well

**Comment by Mikesch-mp** [comment]
I vote for `grouping fixed rates entries ONLY if the price is exactly the same`

**Comment by kevinpapst** [comment]
@JayAige @Mikesch-mp Can you please test #1058 (there is a link to a demo installation) if that works better?

**Comment by JayAige** [comment]
Sorry for late response. Works for me in the demo installation, thank you very much!

**Comment by kevinpapst** [comment]
Thanks for your feedback! If you find further flaws, please let me know.
