### ISSUE TITLE
Project view

### ISSUE THREAD

**Issue by nicolas-75** [kevinpapst/kimai2#1010]
**Is your feature request related to a problem? Please describe.**
The "my times" screen displays all the records. Is it possible to display only projects? Thus, to have the detail of the time recorded by the project, it is possible to click on the name of the project or to filter.

Indeed, I rarely need to have the details of the time spent and only the full time or the full time per week interests me.

I can not get this information in the demo. There are statistical reports that can be created?

**Describe the solution you'd like**
Display one line per project and four columns: time spent today; time spent in the week; time spent from the beginning; expected time
To see the details of the time spent, click on the name of the project.

**Additional context**
Freelance working on several projects in parallel and can last several months with long interruptions

**Comment by kevinpapst** [comment]
You may get some of these informations through various way, eg. 
- create an invoice for the project and select the time range
- check the budget view of the project to see all time recorded.
- create an export and do the calculation in Excel

But there is no way to get these informations in Kimai via a mouse-click right now.

**Comment by nicolas-75** [comment]
I made a model of the view that interests me so if someone wants to contribute I can make a transfer of 200 €. There is a bounty pot for changes requests?

![project-view](https://user-images.githubusercontent.com/3610660/62548933-e420ae00-b867-11e9-98e3-9abfaac44f08.png)

**Comment by kevinpapst** [comment]
I have setup a Bountysource team for Kimai 2:
https://www.bountysource.com/teams/kimai2

And here is your issue:
https://www.bountysource.com/issues/78268231-project-view

**Comment by nicolas-75** [comment]
Great ! I thank you for this step. I published a bonus on this platform. Thank you

**Comment by kevinpapst** [comment]
Awesome, thanks for posting the first bounty!

Can you explain a bit, so we can gather a list of all requirements:
- the expected duration could be the time budget
- the expected delivery has no matching field yet, so a new "end date" would be required (which makes totally sense for projects)
- If there is an end date, a start date would be good to have as well, so it would be possible to show a progressbar?!
- What is up with the eye icon?
- Calculating all these values will be quite "expensive" for the database, so it might become rather slow with a growing database of timesheet records. How did you imagine is the list of projects populated? List all projects the current user worked at in the selected time-range?

**Comment by nicolas-75** [comment]
The eye icon is a way to hide projects that are no longer to display. But that implies being able to add them again by another means so it is not the most urgent.

Indeed, some projects can be suspended for several months so it is not necessary that they are present in the list.

An alternative is to be able to work as you suggest. It's even better. Will it be possible to display the projects on which we worked in the day, week, month, quarter and year? Maybe from date to date?

To avoid calculating the data from all the timesheet records, can the time accumulated since the beginning be stored in the database according to the evolution of the timesheet records?

In my case I have about 3 projects per month and between 8 and 12 projects in a quarter. This includes projects for which I have not necessarily worked in the month and projects that are completed, sometimes at the very beginning of the quarter.

It is already possible to export the number of hours worked per month from an existing screen?

**Comment by kevinpapst** [comment]
You can already hide customer/projects and activities in the "edit/detail" screen (there is a checkbox for it). 
How often are you switching the visibility state, that you want a quick action for this?
A new quick action just for hiding a project seems redundant to me, especially considering how often that will be used.

Lets start with calculating the values on the fly and see how that goes. What I wanted to understand is: which projects should be listed there?
In your case even showing all projects for a year would be okay. But I know that some users have hundreds of projects and showing all of them is not an option => that would be too much for the database in one page view.

Maybe as you suggested, filter the projects you worked on by a date-range and the calculate the statistics for them?

Can you explain your main use-case bahind your request, so I can undertand what you want to achieve?

In the "my timesheets" view there is an export icon. This will export all currently filtered records. You can select the current month, click export and get all hours for that month. But they are not grouped by a project. 
But that can be achieved with wither the PDF or HTML export afaik.

**Comment by nicolas-75** [comment]
I have never used kimai so thank you for this information. I rarely change the state of visibility so it is not necessary to add a shortcut since the function exists.

For my part I need to know the time spent on a project and the estimated time for several reasons:
- check that the estimates are appropriate in order to negotiate with current or future customers
- I almost never work by billing the time spent but almost always to the fixed price
- know the evolution of time spent since I often work at home without too much reference: have I enough, not enough or too much worked in the day, the week and the month?
- some clients want me to work for them on average two days a week but they have occasional requests almost every day. So I have to know easily the time I spent. A one-time export must allow to know the time at different frequencies for the customers (week, month, quarter or year)

So I never use the detail of the time spent because I don't need to know: 
- what project I spent time on that day 
- or when I worked on such a project.

I hope this clarifies the context and that developments can be made :-)

**Comment by kevinpapst** [comment]
@nicolas-75 are you still using Kimai?

**Comment by kevinpapst** [comment]
Here is screenshot of a project report (from my development environment) that was created by @willianveiga :
<img width="1530" alt="Bildschirmfoto 2020-11-09 um 22 19 17" src="https://user-images.githubusercontent.com/533162/98597646-9d76fa80-22d9-11eb-9c54-7ea01b20c4c3.png">

**Comment by kevinpapst** [comment]
This was finally merged and will be released in 1.4

**Comment by kevinpapst** [comment]
@willianveiga you deserve the bounty. Please register/login with Bountyhunter and start the "solve this issue" process.
I have never used Bountyhunter, so I don't know how it continues. Please let me know, if you need help.

**Comment by willianveiga** [comment]
Awesome, @kevinpapst ! :smile: 

Maybe you need to open and close it again:

```
You have started working on this issue. 
You will be able to claim this bounty as soon as the original issue is marked as closed.
```

Thank you!

**Comment by willianveiga** [comment]
Awesome, @kevinpapst ! :smile: 

Maybe you need to reopen and close it again:

```
You have started working on this issue. 
You will be able to claim this bounty as soon as the original issue is marked as closed.
```

Thank you!

**Comment by kevinpapst** [comment]
Lets wait for a bit, maybe it needs some time to understand the issue change.

**Comment by kevinpapst** [comment]
After reading https://github.com/bountysource/core/wiki/Frequently-Asked-Questions twice, it is still not clear how to get the bounty. Seems the closed state is not synced or at least not in a quick period of time.

I tried to solve the issue as well, to see what is going on, but I only saw the same message: `You will be able to claim this bounty as soon as the original issue is marked as closed.`.

I have put a big amount of my own time into this PR^^ and I am totally fine if @willianveiga gets the complete bounty! But if that means someone has to write their support, because their sync might be broken (see https://github.com/bountysource/core/issues/1489) then it should be original author who wants to claim the money, So @willianveiga - please share updates here with use, so we can see if there is any progress.
