### ISSUE TITLE
Add online marketplace

### ISSUE THREAD

**Issue by slince** [kevinpapst/kimai2#1012]
Hello

I think manual rebuid caching after installing plugins is a bit inconvenient; maybe these actions can be done automatically; including downloading plugin source code, rebuild cache; Users just need to click "install it" in admin panel.

**Comment by kevinpapst** [comment]
Yep, that would be cool to have!
The list of plugins could be fetched from the website. We can generate a JSON from the Jekyll sources. That JSON could be loaded and cached for 24h. 
Just as a first step to display all available plugins in the backend.

PRs and further ideas are welcome!

**Comment by slince** [comment]
I found that kimai2 is based on symfony; symfony clears the cache via command `php bin/console cache:clear`； There is no way to programmatically clear the cache. Do you have any good ideas?

**Comment by kevinpapst** [comment]
Thats the application cache and something different. Its mostly for config files and code copilation, so stuff which doesn't change during runtime. 

You should use your own cache service: 
https://symfony.com/doc/current/components/cache.html 
You can define arbitrary lifetimes or you create it without cache for the first draft.

**Comment by slince** [comment]
Kimai2's plugin is essentially a bundle of symfony; The runtime cache must be cleared to take effect when installing a new plugin through the online marketplace. This may seem hard to implement because there is no good way to clear cache in controller for symfony; We cannot ask the user to manually execute 'cache:clear' command

**Comment by kevinpapst** [comment]
Ah, I thought you were talking about the cached JSON.
Clearing the cache from the controller is no problem:
```
    public function rebuildContainer(KernelInterface $kernel)
    {
        $application = new Application($kernel);
        $application->setAutoExit(false);
        $input = new ArrayInput([
            'command' => 'cache:clear',
            '--env' => $kernel->getEnvironment(),
            '-n',
        ]);
        $output = new BufferedOutput();
        $application->run($input, $output);
        $result = $output->fetch();
        // more controller action logic here
    }
```

**Comment by slince** [comment]
This command is slow to execute on Windows and some Linux computers, which will make your request time out

**Comment by kevinpapst** [comment]
Try to use a `@ini_set('max_execution_time', -1);` or something like that before.
The other option, using an `exec('rm -rf var/cache/prod/*')`, might be disallowed on shared hosts.

**Comment by kevinpapst** [comment]
Closing. I have no plans to work on this and I am not sure if it would even properly work with Symfony plugins.
