### ISSUE TITLE
Want to update kimai 1.2.2.1394 to kimai2 1.1

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1013]
Hi,
  I Installed kimai 1.2.2 . i want to update kimai2 v1.1 . I followed the steps as you mentioned in website .I didn't got any errors while doing the steps. I didn't know which file wants to call to update . and Please tell the Procedure Clearly to Update kimai2

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/migration-v1.html

**Comment by karthikalsv** [comment]
I did this but it coming like this

![Screenshot_28](https://user-images.githubusercontent.com/25294547/62703632-3c41e680-ba07-11e9-82c1-60f40ab31d33.jpg)

**Comment by kevinpapst** [comment]
A screenshot doesn't help to find a problem without proper explanation of all steps you have taken, including your configs. Check your webserver, php and Kimai logs (at var/logs/prod.log)

All I can say: /public/ is not allowed to be in the URL. You need to point your VHost to the public directory.

**Comment by karthikalsv** [comment]
I installed kimai2 in my server like that in that below website

https://www.kimai.org/documentation/installation.html

I deleted inside in the Kimai directory  the /var/cache/ and given write permission to 
 /var/cache/
/var/log/

but the site is opening like that .

**Comment by karthikalsv** [comment]
I checked in my error log . It coming like this when i tried to open /kimai2/public/index.php

[Fri Aug 09 07:52:23.725785 2019] [php7:error] [pid 10007] [client 49.207.131.234:24633] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Kimai2_db.kimai2_configuration' doesn't exist in /var/www/html/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117\nStack trace:\n#0 /var/www/html/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)\n#1 /var/www/html/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(903): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/html/kimai2/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\\DBAL\\Connection->executeQuery('SELECT k0_.id A...', Array, Array, NULL)\n#3 /var/www/html/kimai2/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(334): Doctrine\\ORM\\Query\\Exec\\SingleSelectExecutor->execute(Object(Doctrine\\DBAL\\Connection), Array, Array)\n#4 /var/www/html/kimai2/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(967): Doctr in /var/www/html/kimai2/templates/base.html.twig on line 39

**Comment by karthikalsv** [comment]
When am trying to install kimai2 1.1 using bin/console kimai:install -n command . 

The following errors are coming

[WARNING] Some commands could not be registered:


In ConnectionFactory.php line 79:

  An exception occured while establishing a connection to figure out
  your platform version.
  You can circumvent this by setting a 'server_version' configuration
   value

  For further information have a look at:
  https://github.com/doctrine/DoctrineBundle/issues/673


In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL serve
  r has gone away


In PDOConnection.php line 31:

  SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 27:

  SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 27:

  Packets out of order. Expected 0 received 45. Packet size=4739923



In ConnectionFactory.php line 79:

  An exception occured while establishing a connection to figure out
  your platform version.
  You can circumvent this by setting a 'server_version' configuration
   value

  For further information have a look at:
  https://github.com/doctrine/DoctrineBundle/issues/673


In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL serve
  r has gone away


In PDOConnection.php line 31:

  SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 27:

  SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 27:

  Packets out of order. Expected 0 received 45. Packet size=4739923

**Comment by kevinpapst** [comment]
Please remove the # and the following space from that line:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/doctrine.yaml#L17
and call `bin/console clear:cache --env=prod` afterwards.
Then try to run the installer again.

**Comment by karthikalsv** [comment]
Sorry to ask you silly Questions . Which line your mentioning about this
Please remove the # and the following space from that line:

**Comment by karthikalsv** [comment]
When i am installing again . The Error showing like below.

![Screenshot_31](https://user-images.githubusercontent.com/25294547/62819366-e3429180-bb71-11e9-869a-c80a825cb8af.jpg)

**Comment by kevinpapst** [comment]
Did you change the line as mentioned above? 
The error tells you, that the database connection is not properly established.

**Comment by karthikalsv** [comment]
I am confused that which line your mentioning to change .

**Comment by kevinpapst** [comment]
How can that not be clear: 
https://github.com/kevinpapst/kimai2/blob/master/config/packages/doctrine.yaml#L17
File config/packages/doctrine.yaml
Line 17

**Comment by kevinpapst** [comment]
The line with server_version, before:
```
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                # this setting prevents automatic database detection and finds a lot of false-negatives on doctrine:migrations:diff
                # for null columns with MariaDB. Each migration tries to convert EVERY nullable column.
                # server_version: '5.7'
                charset: utf8mb4
```
Afterwards:
```
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                # this setting prevents automatic database detection and finds a lot of false-negatives on doctrine:migrations:diff
                # for null columns with MariaDB. Each migration tries to convert EVERY nullable column.
                server_version: '5.7'
                charset: utf8mb4
```
Make sure the alignment is correct!

**Comment by karthikalsv** [comment]
I did like you said above and ran the 
`bin/console clear:cache --env=prod`  Command . 

but the same error is coming like before 
[https://github.com/kevinpapst/kimai2/issues/1013#issuecomment-519885004](url)

.

**Comment by karthikalsv** [comment]
`parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                # this setting prevents automatic database detection and finds a lot of false-negatives on doctrine:migrations:diff
                # for null columns with MariaDB. Each migration tries to convert EVERY nullable column.
                server_version: '5.6.45'
                charset: utf8mb4
                default_table_options:
                   charset: utf8mb4
                   collate: `utf8mb4_unicode_ci`

            types:
                datetime: App\Doctrine\UTCDateTimeType
        orm:
            auto_generate_proxy_classes: '%kernel.debug%'
            default_entity_manager: default
            entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Kimai
`

**Comment by karthikalsv** [comment]
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                # this setting prevents automatic database detection and finds a lot of false-negatives on doctrine:migrations:diff
                # for null columns with MariaDB. Each migration tries to convert EVERY nullable column.
                server_version: '5.6.45'
                charset: utf8mb4
                default_table_options:
                   charset: utf8mb4
                   collate: utf8mb4_unicode_ci

            types:
                datetime: App\Doctrine\UTCDateTimeType
        orm:
            auto_generate_proxy_classes: '%kernel.debug%'
            default_entity_manager: default
            entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Kimai


My doctrine.yaml file after edit the line .. My sql server is 5.6.45 . i tried to put 5.6 also . but it didn't work out

**Comment by karthikalsv** [comment]
My doctrine.yaml file after edit the line .. My sql server is 5.6.45 . i tried to put 5.6 also . but it didn't work out

[doctrine.yaml.docx](https://github.com/kevinpapst/kimai2/files/3491915/doctrine.yaml.docx)

**Comment by kevinpapst** [comment]
Something is wrong with your database connection or configuration.

Try to search Stackoverflow or other sites for:
> SQLSTATE[HY000] [2006] MySQL server has gone away

You could try to configure a max_timeout in the options section:
https://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                options:
                    ...
```

But I never faced that problem. Sorry, can't help here, this is not a Kimai issue.

**Comment by karthikalsv** [comment]
ok . Any other way to install kimai2 v1.1 .Already i am using kimai 1.2.2

**Comment by karthikalsv** [comment]
I successfully installed kimai2 in my localhost . But when i tried to run the `localhost/kimai2/public/index.php` . The webpage coming Blank . I cleared the Cache using `bin/console cache:clear --env=prod` command and reinstalled . But it coming blank webpage

**Comment by karthikalsv** [comment]
Can i get the solution for it?

**Comment by karthikalsv** [comment]
This is my system error or in kimai issue ?

**Comment by kevinpapst** [comment]
You must point your document root to the public/ directory. As written in the documentation.
Please read the documentation and follow these guidelines.
Also: check the Kimai logfile for errors.

**Comment by karthikalsv** [comment]
i point my document root to the public 

`DocumentRoot "/var/www/html/kimai2/public"
#
# Relax access to content within /var/www.
#
<Directory "/var/www/">
    AllowOverride None
    # Allow open access:
    Require all granted
</Directory>

# Further relax access to the default document root:
<Directory "/var/www/html/kimai2/public">`

but after doing it and i ran `localhost/index.php` page is coming blank . 

![snapshot3](https://user-images.githubusercontent.com/25294547/63151806-ee8d3580-c027-11e9-8626-c95108e07c20.png)

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/faq.html#i-have-a-problem

**Comment by madhesh978** [comment]
Thank you . Lastly i installed it and running peacefully . Thank you for your responses 

I ran in my server with php version : 7.3 and mysql : 5.5 . I did mistakes while entering mysql url in .env file . so only all the issues came . Now its fine .

**Comment by karthikalsv** [comment]
Happy That kimai Working good  in my server . I did mistake in the mysql url at .env file . Now i Cleared  and succesfully installed . Thank you very much for your responding my quires .

 Kimai2 is good . but one more features want to be add  . 
Please add group and Editable Roles as like kimaiv1 .

**Comment by kevinpapst** [comment]
Roles are available: https://www.kimai.org/documentation/permissions.html

Teams are coming with the next update (v1.2): https://www.kimai.org/documentation/teams.html

Glad that it finally works! And thanks for the feedback, I added a FAQ for the next person: 
https://www.kimai.org/documentation/installation.html#sqlstatehy000-2006-mysql-server-has-gone-away
