### ISSUE TITLE
Add user preferences fields to export and timesheet views 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1014]
Currently the user preferences files are not exportable via the export and timesheet views. It would be good if an option of adding such fields from user preferences are available in the export and timesheet views. 

We hold lot of user specific data like location etc as against a said user and only if they are exportable can they be used for analysis. Your help is needed.

**Comment by kevinpapst** [comment]
Can you elaborate a bit more?
The user preference is always the same, so exporting it for every timesheet record sounds strange to me. Can you make an example with one field?

**Comment by rarvin** [comment]
Dear Kevin,

The export does not allow one to export the records which are not completed
(active records). We have users who work from various locations and for
these various users we have added a preference field called location
depending on the office they work from. Why this is needed is because we
would want to identify the timesheet tasks which are pending for a very
long time and give the team leads at these location knowledge that these
needs to completed quickly so that we don’t miss the SLA. The tasks are all
interdependent and sometimes one takes at one office might have been
completed and waiting for the work to be completed so that the next team
can combine the work outputs from both offices. It’s more of a chain like a
production factory work floor. Having the information is important.

In addition to this we have an additional field called article id custom
field not related to user preference this is the one against which each
user does work and getting to filter among the timesheet records is again
important. So a combination of both user preference field and custom fields
values being available is quiet important. Else we loose the reference
between them or a lookup.


-- 
Regards,
Aravind
