### ISSUE TITLE
Change/Set Currency Globally for Customers, Users, etc.

### ISSUE THREAD

**Issue by curtisnehring** [kevinpapst/kimai2#1017]
**Is your feature request related to a problem? Please describe.**
I work out of the US and while I have clients in different countries I only bill in USD. I can see how to set USD as the currency for Customers but not for a Users hourly rate. E.G. when I set a rate for a user I can only set it in EUR.

**Describe the solution you'd like**
It would be nice to have a way to set the default currency for the entire system (all places where currency is relevant) so that we have control over the currency for Users and other options/areas as well as Customers.

Being able to do this through local.yaml would be sufficient for my needs as this has worked well for other settings/overrides.

Sorry if there is a way to do this that I have missed (if so how?).

**Comment by kevinpapst** [comment]
Thanks for the info! One of the bugs which I would never find, as I only use EUR ;-)
Its only a "cosmetic" problem, but I guess you know that.
A system wide default currency sounds good.

**Comment by kevinpapst** [comment]
If you find other places where the currency is wrong, please post an answer here, so I can update them as well.
