### ISSUE TITLE
Database Settings

### ISSUE THREAD

**Issue by nullableVoid** [kevinpapst/kimai2#1019]
**Is your feature request related to a problem? Please describe.**
I just started using Kimai2 and it looks very promising. When I now wanted to start my first update on a shared host I got stuck digging the source files, looking for the database-file.
I'm not realy convinced using SQlite in production but did not find a settings-file to change the database-type to MySQL.

**Describe the solution you'd like**
Please provide a possibility to change configuration in source files, like a config.php.
Please consider a possibility to choose mysql as database for shared-host-environments.

**Describe alternatives you've considered**
Perfect would be a setup-routine in Frontend on first start.

**Additional context**
I don't even think about migrating my records from SQlite to MySQL...

**Comment by kevinpapst** [comment]
SQLite is shitty, FTP support experimental.
Without SSH you have a hard time upgrading. 
FTP doesn not support updates right now:
https://www.kimai.org/documentation/installation.html#ftp-installation
Its all (DB credentials as well) in the documentation:
https://www.kimai.org/documentation/configurations.html

**Comment by kevinpapst** [comment]
The only way to upgrade a SQLite installation right now is to:
Install it locally, download the DB file from your server, upgrade locally.
Upload the new Kimai version to your server and replace the DB file with your upgraded local version.

**Comment by nullableVoid** [comment]
Ok, thank you. I try tu check out the SSH-version.

**Comment by kevinpapst** [comment]
That  isthe best option you have!
