### ISSUE TITLE
Make kimai2 compliant with C-55/18 EuGH

### ISSUE THREAD

**Issue by eporsche** [kevinpapst/kimai2#1021]
**Is your feature request related to a problem? Please describe.**
Currently the main focus of kimai is for freelancers or consultancy companies to quickly track the time they spend on customer projects and to invoice it. 
However with the judgment C-55/18 from EuGH on 14th may 2019 this might not be enough - since every employer (at least in europe) is now encouraged to track all working hours of their employees (also those not spend on projects) and to track overtime.

**Describe the solution you'd like**
The solution would be to implement the following use cases:
- #240, #241,  #242, #243, #245

**Describe alternatives you've considered**
- hand out excel files to each employee

**Additional context**
Screenshot of excel file to track employees overtime:
![image](https://user-images.githubusercontent.com/3265129/62779192-ca26db80-bab2-11e9-8daf-d957890cee2e.png)

https://www.lto.de/recht/hintergruende/h/eugh-c-5518-arbeitszeit-richtlinie-zeiterfassung-ueberstunden-arbeitnehmerschutz/
https://curia.europa.eu/jcms/upload/docs/application/pdf/2019-05/cp190061en.pdf

**Comment by BeckeBauer** [comment]
We use kimai2 already to track working time off employees. Each employee needs to create a record 'working time' (booked at our company) at the start of work and to stop recording, when leaving (for a break and at the end of work). You can then export to Excel those entries of each user at the month's end to excel and you have your working time records.

**Comment by mr-jingles** [comment]
Hi BeckeBauer,
thanks for your comment. How do you compare the working hours to the contract of your employee? Is there a function I am missing or do you do it manually? What I am looking for is to see the carryover from last months. As well the ability to book absence due to vacation/illness and the automatic deduction of target hours due to country specific holidays..

**Comment by BeckeBauer** [comment]
I see no way that kimai2 could do all this. If the working time records are exported to Excel, the results would needed to be processed manually acc. to your requirements from the employment contracts (for some employees, a certain amount of overtime hours per month may be included in the salary, some have earned a day off and so on). But in any case, you would comply with the duty to record working times including overtime work. 

Regarding holidays and sick leave, kimai2 is not really helpful. For instance, if you created a time record 'vacation' from 1.1. 00:00 -14.1. 23:59, the program would show just one entry with a total time of 336 hours (this include the weekend and possible holidays which is legally not correct). You could also process it with Excel, but I think there are better programs for this purpose (I am currently checking out the app timeoff-management, which even has a process for approval of a holiday request implemented)

**Comment by kevinpapst** [comment]
I am strongly committed to enhance Kimai. 
Support for tracking employee holiday management, sickness ... are planned as well as support for calculating overtimes. Please sent me an email if you are interested in sponsoring such a feature, to speed up development time.

@BeckeBauer is right that with respect to different kind of working contracts, Kimai might not be able to calculate that 100% accurate. At least not from the beginning until all features were added. 
Maybe its better to connect several systems to use they combined power for now (eg. timeoff-management was mentioned already in #1009).

**Comment by eporsche** [comment]
Hi @kevinpapst, 
it's a long time since I opened this issue to include timesheets in kimai. In the meantime, I have build a very small application build on top of laravel which does what was requested here. You can find it here: https://github.com/eporsche/daybreak
Maybe - if you have time - you can have a look and maybe some of its features might also be interesting for future versions of kimai. :)

**Comment by kevinpapst** [comment]
Sorry to read that you spent the time for writing a new application, instead of working on patches to improve Kimai (or any other open source time-tracking application). Good luck with it!
