### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by nullableVoid** [kevinpapst/kimai2#1022]
Hi,

when trying to install kimai2 from scratch following your instructions 
https://www.kimai.org/documentation/installation.html#recommended-setup
installation hangs up when running the composer command:

composer install --no-dev --optimize-autoloader

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 136 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.4.0): Loading from cache
PHP Fatal error:  Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /home/www/kimai2/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(236): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 phar:///usr/bin/composer/src/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(16 in /home/www/kimai2/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80

Fatal error: Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /home/www/kimai2/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(236): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 phar:///usr/bin/composer/src/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(16 in /home/www/kimai2/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80

Do you have any ideas for that problem?

**Comment by kevinpapst** [comment]
No idea. Thats not a Kimai issue. Please ask on SO or alike.
