### ISSUE TITLE
Dashboard view not getting updated properly with the work time for the day - 'working hours today' 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1023]
The current system server time is configured as GMT and the user timezones are in IST +5:30. All of the time calculation in my times as well as in exports and invoices are correctly calculated and shown but in the dashboard view we have observed that the time accumulated during the first 5:30 minutes duration is missed or not summed and shown in the 'working hours today' in the dashboard view.

The time is correct in all other places like mytimes etc. This is mostly observed for the users who work late at night after 00:01 and 05:30 am IST. Since most of the associates work outside of the range from 7:00 IST they do not seem to have any issues. This is not a serious issue and we can live with it.

**Comment by kevinpapst** [comment]
Already fixed in #988
Duplicates #987

**Comment by kevinpapst** [comment]
But thanks for the ticket 👍
