### ISSUE TITLE
Activity dropdown is empty when creating new entry

### ISSUE THREAD

**Issue by vershley03** [kevinpapst/kimai2#1024]
When creating a new time entry, the activity dropdown menu is empty, even though I created activities. I already checked for permission errors in the logs, but this is different.

**To Reproduce**
1. Create new time entry
2. Choose Customer, Project
3. Select activity, and the dropdown is empty.

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: PC
 - OS: Windows
 - Browser Chrome
 

[prod.log](https://github.com/kevinpapst/kimai2/files/3490183/prod.log)
Kumai 2 1.1

![image](https://user-images.githubusercontent.com/13870591/62836703-00ad5380-bc77-11e9-9d39-ae607a09f171.png)

**Comment by kevinpapst** [comment]
Looks like outdated composer dependencies.
Is that an updated Kimai or did you install 1.1 initially?
Run the composer command as written here: https://www.kimai.org/documentation/updates.html
Make sure you have an up-to-date composer version installed: `composer self-update`.

**Comment by vershley03** [comment]
Thank you for your reply.
I will do that and inform if that solves the problem.

**Comment by vershley03** [comment]
Followed the steps in the link, but still now working, unfortunately.

Yes, initially I installed the older version. Then deleted and used the latest one.
Any other ideas, please? 

I also checked my PHP version, which matches the XAMPP one.

**Comment by kevinpapst** [comment]
Show me the output of `composer --version` and `composer info`

**Comment by kevinpapst** [comment]
And `git status` as well

**Comment by vershley03** [comment]
composer --version: 
Composer version 1.9.0 2019-08-02 20:55:32

composer info - attached file
[composerinfo.txt](https://github.com/kevinpapst/kimai2/files/3490236/composerinfo.txt)

I downloaded the ZIP and placed it in the htdocs from XAMPP. So no git status?

Thanks for your help.

**Comment by kevinpapst** [comment]
Are you using the master? So the ZIP from GitHub? And you are running it in XAMPP on Windows?
This is the master, installed twice a day: https://demo.kimai.org/
The error is not happening there, so it must be an environment issue.

**Comment by rarvin** [comment]
What would be the browser version. We had these problems on older browsers

**Comment by kevinpapst** [comment]
@rarvin this one is different, as the log is clear: there is a PHP compilation error.
But that does not happen in the demo or with the 1.1 ZIP release. So I would say Windows, an aggressively configured OPCache or something alike.
At least nothing that needs a fix or is a Kimai issue.
