### ISSUE TITLE
Is there a way to auto-signout from the interface after a period of time?

### ISSUE THREAD

**Issue by fizgig10** [kevinpapst/kimai2#1026]
Nobody signs out on their own from the GUI (not the activity but the GUI).  Is there a way to make the GUI sign out automatically after a minute of inactivity?

**Comment by kevinpapst** [comment]
A minute? Do you want your users to hate you? 😁 

https://www.kimai.org/documentation/users.html#session-lifetime

**Comment by fizgig10** [comment]
Ha.  They usually just take 10 seconds to start or end a task.  I'll make it 120 seconds just in case.  I've added that cookie parameter to that file but I think I need to somehow tell symphony to reload the settings to get that going and I haven't figured out now.  I'm combing their website now but if you could tell me here that would be a big help!

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/configurations.html#reload-changed-configurations

**Comment by fizgig10** [comment]
Thanks!  That worked but it does have the strange behavior of not changing the screen back to the login screen.  Rather, it still looks logged in but when you try to do anything like start or stop an activity, you get a blank popup window.  You eventually realize you have to refresh the page to get the login page to appear to then proceed.  Would be nice if the login page automatically came up when the cookie expired but this is a close second.  :)

**Comment by kevinpapst** [comment]
I think not many people use such a short session, but rather the "remember me" feature.
Thats why nobody ever found that problem.

You can open a new feature request so it will be eventually fixed.

**Comment by fizgig10** [comment]
Ok.  Will do.  We have three guys sharing one laptop in the shop so no remember me stuff going on.  In fact, would be nice to not offer the remember feature at all.  Will open a new feature request.

**Comment by rarvin** [comment]
Dear Kevin,

We have also observed this problem with the default setting, but not too
occasionally. When this happens it throws an error but nothing to indicate
that it was a session timeout needing the user to login. Could you please
amend the error message with an action asking the user to try reloading the
page or login in again and trying. Right now for our users we have informed
them manually and all are doing this to avoid the problem. They reload
first and if it does not load the login screen they do the update on Kimai,
if on reload they see the login screen they relogin again and carry on with
their work.
-- 
Regards,
Aravind

**Comment by kevinpapst** [comment]
@rarvin then vote for #1027 !
