### ISSUE TITLE
Failed to create database schema : General error: 1709 Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by cm22608** [kevinpapst/kimai2#1028]
**Describe the bug**
 Failed to create database schema during installation : ./bin/console kimai:install -n
Kimai installer - v1.1
======================

Created database `kimai` for connection named default

 !
 ! [CAUTION] This operation should not be executed in a production environment!
 !

 Creating database schema...

 [ERROR] Failed to create database schema: Schema-Tool failed with Error 'An exception occurred while executing 'CREATE
         TABLE kimai2_activities (id INT AUTO_INCREMENT NOT NULL, project_id INT DEFAULT NULL, name VARCHAR(255) NOT
         NULL, comment TEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, fixed_rate DOUBLE PRECISION DEFAULT NULL,
         hourly_rate DOUBLE PRECISION DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, budget DOUBLE PRECISION NOT NULL,
         time_budget INT NOT NULL, INDEX IDX_8811FE1C166D1F9C (project_id), INDEX IDX_8811FE1C7AB0E859166D1F9C (visible,
         project_id), INDEX IDX_8811FE1C7AB0E859166D1F9C5E237E06 (visible, project_id, name), INDEX
         IDX_8811FE1C7AB0E8595E237E06 (visible, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE
         utf8mb4_unicode_ci ENGINE = InnoDB':

         SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.' while
         executing DDL: CREATE TABLE kimai2_activities (id INT AUTO_INCREMENT NOT NULL, project_id INT DEFAULT NULL,
         name VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, fixed_rate DOUBLE PRECISION
         DEFAULT NULL, hourly_rate DOUBLE PRECISION DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, budget DOUBLE PRECISION
         NOT NULL, time_budget INT NOT NULL, INDEX IDX_8811FE1C166D1F9C (project_id), INDEX IDX_8811FE1C7AB0E859166D1F9C
         (visible, project_id), INDEX IDX_8811FE1C7AB0E859166D1F9C5E237E06 (visible, project_id, name), INDEX
         IDX_8811FE1C7AB0E8595E237E06 (visible, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE
         utf8mb4_unicode_ci ENGINE = InnoDB

Environment :

CentOS Linux release 7.6.1810 (Core)
PHP 7.2.21 (cli) (built: Jul 30 2019 14:46:08) ( NTS )
mysql  Ver 14.14 Distrib 5.6.45, for Linux (x86_64) using  EditLine wrapper

I have tried these settings in /etc/my.cnf MySQL conf file but it still does not work :

innodb_large_prefix = 1
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

Following tables have been created though : 
mysql> use kimai
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-----------------------+
| Tables_in_kimai       |
+-----------------------+
| kimai2_timesheet      |
| kimai2_timesheet_tags |
| kimai2_users          |
+-----------------------+
3 rows in set (0.00 sec)

mysql>

**Comment by kevinpapst** [comment]
Hi!
Thanks for posting this problem. Its not happening on any of my systems (maybe because they are all MariaDB) but I know that error. Maybe this is only happening on older MySQL instances.

However, there is a simple fix. Can you please make the changes you see here: https://github.com/kevinpapst/kimai2/pull/1031/files in your installation and then run the installer again?

We need to verify if that really solves the issue and then I will fix it for the next release.

What you need to do: 
- Replace in 3 files  from `length=255` to `length=150`:
  - src/Entity/Activity.php
  - src/Entity/Project.php
  - src/Entity/Project.php
- Run `bin/console cache:clear --env=prod`
- Run the installer again
- Let me know if that fixed your issue

**Comment by cm22608** [comment]
Hello Kevin,
It worked like a charm !
I can continue with the installation.
Thank you,

**Comment by kevinpapst** [comment]
Awesome, thanks for your feedback. I'll leave this open, until I merge the PR for the next release.
