### ISSUE TITLE
Error 500 : create time sheet from calendar view

### ISSUE THREAD

**Issue by cm22608** [kevinpapst/kimai2#1032]
**Describe the bug**
I receive an http 500 error when creating a timesheet entry from the calendar view
Request failing : http://localhost:8080/en/timesheet/create?from=2019-08-14T05:30:00Z&to=2019-08-14T06:30:00Z

**To Reproduce**
1. Go to 'Calendar View'
2. Select Day button
3. Select  a timeframe with the mouse button

**Logfile**
[2019-08-14 08:47:28] request.CRITICAL: Uncaught PHP Exception IntlException: "datefmt_create: time zone id 'Z' extracted from ext/date DateTimeZone not recognized: U_ILLEGAL_ARGUMENT_ERROR" at /var/www/html/kimai2/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php line 170 {"exception":"[object] (IntlException(code: 1): datefmt_create: time zone id 'Z' extracted from ext/date DateTimeZone not recognized: U_ILLEGAL_ARGUMENT_ERROR at /var/www/html/kimai2/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:170)"} []

Environment :
CentOS Linux release 7.6.1810 (Core)
PHP 7.2.21 (cli) (built: Jul 30 2019 14:46:08) ( NTS )
mysql Ver 14.14 Distrib 5.6.45, for Linux (x86_64) using EditLine wrapper
Kimai 2 - 1.1 stable (Ayumi) by Kevin Papst and contributors.

**Comment by kevinpapst** [comment]
Try:
- to set the timezone of your user account in your preferences
- to set date_timezone in your php.ini
- check your OS locales
- check for available updates of your ICU system packages and the PHP Intl extension

I found this here: https://github.com/humhub/humhub/issues/2846

**Comment by cm22608** [comment]
Hello,
The culprit is the default timezone set to "UTC" for the user.
If I change from UTC to Europe/whatever, it works.
Thanks for the feedback, ticket can be closed

**Comment by kevinpapst** [comment]
By setting a timezone you are just "hiding" a problem with something else in your system/environment. This error indicates that something is wrong with (I guess) your ICU database.
But thats not a Kimai issue, so yes closing is my favorite as well ;-)

Oh and you can set a default timezone for new users in Administration/Settings.

**Comment by cm22608** [comment]
My OS locales looks fine : [root@localhost ~]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Tried to change date.timezone in php.ini but with no luck

ICU version looks also fine  :
root@localhost ~]# php -i |grep -i icu
ICU version => 62.1
ICU Data version => 62.1
ICU TZData version => 2018e
ICU Unicode version => 11.0

I'll take the option of default timezone for new users in Administration/Settings.
Thanks !

**Comment by kevinpapst** [comment]
I dno't know much about the ICU system. Found those on my servers:
```
ICU version => 64.2
ICU Data version => 64.2
ICU TZData version => 2019a
ICU Unicode version => 12.1
```

```
ICU version => 64.1
ICU Data version => 64.1
ICU TZData version => 2018i
ICU Unicode version => 12.0
```

But as long as it works with a "real" timezone instead of Zulu, I think you can ignore the problem.

**Comment by kevinpapst** [comment]
BTW: this seems to be a bug in Symfony. I was wrong with my assumption above about the ICU database.
See https://github.com/symfony/symfony/issues/33901
