### ISSUE TITLE
Payments Received / Amounts in Trust

### ISSUE THREAD

**Issue by sollermun** [kevinpapst/kimai2#1034]
**Is your feature request related to a problem? Please describe.**
For the work I do, I may receive funds in advance that are held in trust. When an invoice is sent, the work performed for the pay period is deducted from the previous deposit. If work is completed and there is still money in trust, the balance is returned to the client.

**Describe the solution you'd like**
I would like Kimai to track both payments received and payments that are held on deposit. These amounts should be reflected in the invoice in the project/client account info.

**Describe alternatives you've considered**
There is no alternative I am aware of.

**Additional context**

**Comment by kevinpapst** [comment]
Duplicates #799 

Please leave your description in #799 and vote for it with the 👍 in the initial post. This won't be a core feature, but could be done in an invoice plugin if there is enough interest.
