### ISSUE TITLE
Wrong end and duration on imported timesheet records

### ISSUE THREAD

**Issue by Stadly** [kevinpapst/kimai2#1035]
When importing data from Kimai v1, all end times in timesheet records are 1 minute later in the imported data than they were in the original data. Similarly, all durations are 1 minute longer.

For example this:

    +------------+------------+----------+
    | start      | end        | duration |
    +------------+------------+----------+
    | 1565244462 | 1565272747 |    28285 | 
    +------------+------------+----------+

Is imported as:

    +---------------------+---------------------+----------+
    | start_time          | end_time            | duration |
    +---------------------+---------------------+----------+
    | 2019-08-08 06:07:00 | 2019-08-08 14:00:00 |    28380 | 
    +---------------------+---------------------+----------+

Since seconds are discarded, the expected result would be:

    +---------------------+---------------------+----------+
    | start_time          | end_time            | duration |
    +---------------------+---------------------+----------+
    | 2019-08-08 06:07:00 | 2019-08-08 13:59:00 |    28320 | 
    +---------------------+---------------------+----------+

**To Reproduce**
1. Import timesheet records from Kimai v1.
2. Compare end times and durations of original data and imported data.

**Additional context**
 - Kimai version: 1.1. I've also tried the current master branch.
 - PHP version: 7.2.17.

**Comment by Stadly** [comment]
The issues doesn't seem to happen to all entries. For example this:

    +------------+------------+----------+
    | start      | end        | duration |
    +------------+------------+----------+
    | 1565082000 | 1565089200 |     7200 | 
    +------------+------------+----------+

Is correctly imported as:

    +---------------------+---------------------+----------+
    | start_time          | end_time            | duration |
    +---------------------+---------------------+----------+
    | 2019-08-06 09:00:00 | 2019-08-06 11:00:00 |     7200 | 
    +---------------------+---------------------+----------+

It seems that `start` is rounded down to the nearest minute, while `end` is rounded up. In my opinion, both should be rounded down (seconds are just discarded). Alternatively, the seconds could be kept for the imported data.

**Comment by kevinpapst** [comment]
Then reconfigure the rounding:
https://www.kimai.org/documentation/timesheet.html#rounding-of-begin-end-and-duration

**Comment by kevinpapst** [comment]
Afterwards clear the cache:
https://www.kimai.org/documentation/configurations.html#reload-changed-configurations
and run the importer again.
I can't remember if the rounding is applied to the imports as well. Maybe should be deactivated... but for your case its easiest to set rounding to 0

**Comment by Stadly** [comment]
Thanks!
