### ISSUE TITLE
Error in database driver

### ISSUE THREAD

**Issue by madhesh978** [kevinpapst/kimai2#1036]
I Tried to install kimai2 . But it Showing the Database driver error . 
` [ERROR] Failed to create database: An exception occurred in driver:
         SQLSTATE[HY000] [2006] MySQL server has gone away`

Mysql version : 5.7.27
Driver :pdo_mysql
pdo_mysql is enabled in php.ini
php version :7.2.21

i mentioned `max_allowed_packet= 500M` in my.cnf

i don't know where the error is coming from

**Comment by kevinpapst** [comment]
Me neither, that was already discussed in #1013 . 
Maybe you can ask there why it finally worked.

**Comment by kevinpapst** [comment]
Please let me know if you find a solution, so I can document it.

**Comment by kevinpapst** [comment]
As written in #1013, this was a wrong database URL. Thanks for your feedback @madhesh978 !
