### ISSUE TITLE
edit team leads to empty modal

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#1040]
**Describe the bug**
If you try to edit a team an empty modal shows up.

**To Reproduce**
1. Go to https://demo.kimai.org/en/admin/teams/
2. Click on actions
3. Click edit
4. See empty modal

The correct edit view opens if you click on the team row, e.g. a bit left of the actions selector.

**Screenshots**
![kimai_team_bug](https://user-images.githubusercontent.com/36242595/63171621-35852600-c03c-11e9-8c33-fb63178cc190.gif)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: PC
 - OS: Win10
 - Browser latest FF

**Additional context**
 - Kimai version: latest master

**Comment by kevinpapst** [comment]
thanks for testing!
