### ISSUE TITLE
http error 500 after update kimai2 1.1 to 1.2

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#1043]
**Describe the bug**
After update kimai does not load, http error 500 (server error)

**To Reproduce**
In Plesk as usual with the git-plugin "get updates from git via pull"
Updates have been pulled up to todays commits to master

**Logfile**
Nothing in the log around the time of the update

**Comment by kevinpapst** [comment]
There is nothing like 1.2: https://github.com/kevinpapst/kimai2/releases
Additionally: updating via git is not enough. 
If I remember correctly, you changed code manually, that can lead to problems as well with the git pull.
Please follow the normal update process. Don't update to an intermediate (master) version, if you are not really sure what you are doing.

**Comment by VOOM108** [comment]
As you can see I am a real git expert - NOT ;) I was under the impression, that 1.2 was already released. I made changes to two files for functions that are now comitted to version 1.2. What would be "following the normal update process" with those changed files? 

(At the moment I am trying to play back the last backup for filesystem and database related to kimai2 from the server-backups to get back to the status quo before trying this faulty update... Hope it works out...)

**Comment by kevinpapst** [comment]
Please read the update documentation for this.
You can try to run the update commands with the status quo. 
This won't make it worse, but probably fix the 500.

**Comment by kevinpapst** [comment]
And changed files need to be reverted (eg. with `git reset --hard`) otherwise they can't be updated to the latest version.

**Comment by VOOM108** [comment]
I see. So that would reset all kimai2 files to the original? What happens to files like invoices that were added when doing that? Is there another way, like finding and adding the originals manually? Since that applies to 2 or 3 files max that were modded...

**Comment by kevinpapst** [comment]
Thanks for trusting me with that issue! 
Yes there are. But please "ask the internet" how to use git properly.

**Comment by VOOM108** [comment]
Thanks, I'll try...

**Comment by VOOM108** [comment]
Finally, I could roll back files and database from the server backups to last night's status quo when it was still working. The 500 error remains. So far I had used git only from the GUI of the Plesk extension.

Now since you said that running the update process as documented with the 1.1 version might fix the 500 error, I wanted to do that, but with all git commands on the CLI I get: "fatal: not a git repository (or any of the parent directories): .git" probably because the Plesk Extension uses a different structure. 

From the extension I can't seem to update to the current status quo; the only options I have are choosing the branch (master) and pulling updates wich was what get me into this mess in the first place (that pulls all commits up to the current ignoring releases). 

Now there are two questions I really can't solve: 
* Why is the 500 error still there even though database and files are back to before it happened? And how do I get back to a working system. (This month's timesheet is lost as I did not expect this kind of massive trouble...)
* How can I switch to using git from the command line after having used only the Plesk extension so far? The extension even updated to 1.1 automatically, when there was the PUSH. That went through completely without issues. It seems though that problem solving is very limited once problems occur when using the extension...

**Comment by VOOM108** [comment]
I woke up with the idea, that the issue could be cache-related as there were warnings shown when restoring the filesystem from the backup concerning "cache" files. Thus I tried to clear and warmup the cache; clearing failed with an error, warming resulted "ok" - an now I do get the GUI and can log in, but within kimai there is once again an "Error 500" page. So I guess it has to do with the cache, but I don't know how to solve it at this point.

**Comment by VOOM108** [comment]
Since the warnings from the backup manager all concerned files in var/cache to exist and that they could not be overwritten, I renamed the cache-dir and restored the resp. one once more (only the cache-dir) - now after login I get this error: 

`Oops! An error occured.
405: Method Not Allowed`

**Comment by VOOM108** [comment]
As usually I document steps and failures as well as success in the hopes, that others may avoid the same mistakes... 

As a last idea I renamed the complete filesystem-dir of kimai to restore all files in one go incl. the cache. SUCCESS - I am back to the last working setup with all data intact. 

Now remains question 2: What do I do about the Plesk Git extension - should I change that setup or can I leave it as it is, simply copying the 3 modded files from the repo manually after an update was pushed?

**Comment by kevinpapst** [comment]
You reacted to quickly, re-applying the backup wasn't necessary. You will have to run the updater anyways once 1.2 its released.
Please read the installer and updater documentation. Its written in there how to set permissions. But that might not work properly/different on shared hosts. Kimai needs write permissions for the var/ directory. Its highly system specific how to apply them and I can't help with that (unless you want payed support). 

I am glad that it works now and I understand that you ask here, because its Kimai which is not running. But I don't know Plesk and its git extension, so I can't say how to use it correctly.

**Comment by VOOM108** [comment]
Just some comments to wrap this up. It's not a shared hosting, it's a cloudserver (aka VS) with full root access. I figured that restoring everything as a whole would get the working system back and from there I could update correctly, instead of tampering with a non-working system. What I did not expect was that restoring the filesystem would not remove the files first, but try to overwrite them. That that could generate trouble is to be expected. Now that I know I can restore a working copy, I am much more at ease trying to get further updates working. 

I suppose to get access to git on CLI with all possibilies, I need to deactivate the Plesk extension (I already did) and somehow get git activated in the CLI. 

I guess the question is: To establish the git structure I need to clone the repo in the kimai dir like I would when installing. Could that be done over a running copy?

**Comment by kevinpapst** [comment]
Never trust a backup until you tried to restore it! 

So if you change into the Kimai directory, there is no hidden `.git` directory? And `git status` reports that this is not a git project?

I'd say: reinstalling via Git is the simplest approach. Clone, composer install (skip the `bin/console kimai:install` part). Change the file permissions for `var/`. Copy over the .env from the old directory (and other changed files). Clear the cache => Kimai should be working now.

**Comment by VOOM108** [comment]
> So if you change into the Kimai directory, there is no hidden .git directory? And git status reports that this is not a git project?
Indeed. I think the extension clones to a local repo somewhere else in the filesystem and then deploys to the live system either automatically or manually. 

> I'd say: reinstalling via Git is the simplest approach. 
Thanks, sounds good; I will try it that way...
