### ISSUE TITLE
team user permission

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1045]
In the demo-account, I created the user "test" and assigned the user to the team "test-team" and granted access to the customer "Abbot Ltd."
![Screenshot 2019-08-18 140228](https://user-images.githubusercontent.com/51003649/63224188-e3214200-c1c0-11e9-98c5-0b10b90a0b5d.png)

When I then login as test user, I can create a time record for any exiting customer (beside Abbot)
![Screenshot 2019-08-18 140229](https://user-images.githubusercontent.com/51003649/63224243-9d18ae00-c1c1-11e9-9ff5-0caef89a38a5.png)
![Screenshot 2019-08-18 140230](https://user-images.githubusercontent.com/51003649/63224259-db15d200-c1c1-11e9-84ae-3d66f59d9883.png)

It would be great, if access to other customers beside the customer(s) assigned to the user would not be shown and if the user could not create records for customers not belonging to his/her team. Maybe, another user-group "TEAM_USER" could be introduced to which such restrictions apply.

**Comment by kevinpapst** [comment]
Add a Team "test2" and assign all other customers to that new "test2". 
Then "test" user will only see "Abbot Ltd.".

**Comment by BeckeBauer** [comment]
I assume then it works as desired. Is there a way to auto-assign all customers to a (fictive) team (maybe a sql command)?

**Comment by kevinpapst** [comment]
Customers without team assignment are "global and visible to everyone", as written in the documentation. 

You can do it with SQL, sure. Or you simply open the team and paste that into your browsers javascript console:
```
$("form[name=team_customer_form] input:checkbox").attr('checked', true)
```
and hit the save button.

**Comment by BeckeBauer** [comment]
Thank you, that saved a lot of ticks... have to make sure not to forget to add each new customer to a team...

**Comment by kevinpapst** [comment]
Improvements are always possible, but lets see how the current tem implementation works.
I'll expect more feedback after 1.2 is released.

**Comment by BeckeBauer** [comment]
True, maybe a 'select / unselect all customer' button (for people with less knowledge of Javascript like me 😉)

**Comment by kevinpapst** [comment]
Comments and votes in closed issues get lost!
