### ISSUE TITLE
Hide inactive users

### ISSUE THREAD

**Issue by Stadly** [kevinpapst/kimai2#1047]
When exporting data or administering timesheets, all users, including inactive ones, are shown in the "User" filter. Is there a way to hide inactive users from the list?

If this is not already possible, here are some ideas:
1. Always hide inactive users (might not be desirable, as old users would have to be activated in order to be exported)
2. Include a "Visible" setting on users, in addition to the "Active" setting.
3. Include a "Show inactive users" checkmark in the filter. Should be default off, I think.

**Comment by kevinpapst** [comment]
Please check the "Development version demo", afaik that was fixed for the next release:
https://www.kimai.org/demo/

**Comment by Stadly** [comment]
Seems so! Thanks :)

**Comment by kevinpapst** [comment]
Thanks for the idea, keep on posting!
