### ISSUE TITLE
wants to Edit Weekend Day and Another role in my user

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1048]
Hi ,
    I add some responsibilities to the Role_Sales using local.yaml. 

![Screenshot_2](https://user-images.githubusercontent.com/25294547/63327568-0cbaa480-c34c-11e9-9580-0d8f70c57b17.png)

But Role_user is not in the list .

![Screenshot_3](https://user-images.githubusercontent.com/25294547/63327731-658a3d00-c34c-11e9-97ac-773d9b7564c9.png)

and My weekend is friday and i edit in the local.yaml . But in the website its showing sunday too . 

![Screenshot_4](https://user-images.githubusercontent.com/25294547/63329074-e77b6580-c34e-11e9-870e-a52a4a7bd049.png)

I uploaded my local.yaml file . Please check it

[local.txt](https://github.com/kevinpapst/kimai2/files/3519359/local.txt)

**Comment by kevinpapst** [comment]
Roles: this is not possible right, but PR #1050 adds the option to create new roles.
Will be included in the next release.

Regarding the weekend: https://www.kimai.org/documentation/calendar.html
Sunday = 0 (not 7)

**Comment by karthikalsv** [comment]
Hi, 
   Using these below 2steps i can create new roles ?

https://www.kimai.org/documentation/users.html#permissions

**Comment by kevinpapst** [comment]
Yes with the next release.

**Comment by karthikalsv** [comment]
ok . Sorry to ask so Early ., When you planned to Release your new version ?

**Comment by kevinpapst** [comment]
Its done when its done... you can see a very rough planning in the milestones section:
https://github.com/kevinpapst/kimai2/milestones
You can use the latest master to get it asap.

**Comment by karthikalsv** [comment]
ok . Good to hear . Will you add Location in kimai2 1.2 ?

**Comment by karthikalsv** [comment]
ok . Good to hear ., One More Issue while am exporting my timesheet its showing details alone not a download or Downloadable Format options .

**Comment by kevinpapst** [comment]
scroll down to the bottom of the list for download buttons. 
export will be improved a lot for 1.2, see #1046

**Comment by karthikalsv** [comment]
Nothing in the bottom . Only Details and blank screen  in the bottom .

**Comment by kevinpapst** [comment]
Then you messed up your permissions. You need `create_export` permission to see the buttons.

**Comment by karthikalsv** [comment]
Ok I got it . But there is an bug still while downloading in PDF Format . The error showing like below . Remaining Working well

![Screenshot_6](https://user-images.githubusercontent.com/25294547/63518019-c319b780-c50d-11e9-835f-7ec378bd03a1.png)

**Comment by kevinpapst** [comment]
Check the log file var/log/prod.log

**Comment by karthikalsv** [comment]
When i checked the prod.log file . The error Showing like this .

[2019-08-23 05:32:39] cache.WARNING: Failed to save key "%5BKevinPapst%5CAdminLTEBundle%5CController%5CSidebarController%23menuAction%5D%5B1%5D" (array) {"key":"%5BKevinPapst%5CAdminLTEBundle%5CController%5CSidebarController%23menuAction%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/simarabia/var/cache/prod/pools/uGfkh7+rKX/5d5f7a77593b14.75706697): failed to open stream: Permission denied at /var/www/html/simarabia/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:92)"} []
[2019-08-23 05:32:39] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []

**Comment by kevinpapst** [comment]
> file_put_contents(/var/www/html/simarabia/var/cache/prod/pools/uGfkh7+rKX/5d5f7a77593b14.75706697): failed to open stream: Permission denied

The error is pretty clear. Kimai needs write permissions for var/cache/ as stated in the documentation.
