### ISSUE TITLE
whole team vanishes if single user is deleted

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1052]
**Describe the bug**
If I have a team with several users and delete the account of one of the users assigned to the team, the whole team is deleted (instead of keeping the team without the deleted user)

**To Reproduce**
access demo account
create a team with several users
delete the user account of one of the users assigned to this team 
Effect: The whole team does not exist anymore

**Comment by kevinpapst** [comment]
True, same applies for deleting customers and projects which are linked to a team.
Will push a fix later, I already found the reason.

Question: for "normal" team members that is definitely wrong, but what about teamleads that are deleted? For now I would still say that the team will still be deleted, as a team without temlead is not possible.

**Comment by BeckeBauer** [comment]
Good question: if it were possible to show a warning and /or an option to assign a new team leader, the admin is sufficiently  warned about the consequences.

**Comment by kevinpapst** [comment]
I will fix the bug first. The teamlead issue should be handled in a new issue.
