### ISSUE TITLE
Extend multi select options present in user selection to customer, projects and activities also

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1055]
The new feature of horizontal forms #1046 brings with it the option to multi select users from the invoice and export screens. It would be great if the same feature of multi select could be extended to customers, projects and activities also.

**Comment by rarvin** [comment]
@kevinpapst The multiselect option that you have added for the users selection can the same to be made available to customers. Do you think this would be easy to add. We just need an option to choose multiple customers when firing the invoice since the users accumulate tasks by both customers and we need them combined in one invoice. If its too complicated please let me know.

**Comment by kevinpapst** [comment]
No, not even near easy. I have never seen that an invoice targets multiple recipients.
The invoice system uses the customer for address and currency. While both could be handled differently, I don't see that this makes sense from a logical point of view: you create an invoice for one customer.

**Comment by kevinpapst** [comment]
You can test #1157 - it adds multi-select in most screens.
But not for invoice, as an invoice targets one customer exclusively. There is no way around that, without writing custom code.
