### ISSUE TITLE
Duration field for active records in export to show the total time clocked

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1056]
The new feature that was implemented as part of #1046 now allows one to export the active records also. But in the active records the duration field comes up empty. Would it be possible to provide the clocked duration till that point in time. 

Having this actual value would really help.

**Comment by kevinpapst** [comment]
I am against that, as it would contain wrong data (already wrong when you open Excel).
You can add a new column and calculate the "duration until now" with an excel formula. The new excel export holds the date-time as "real Excel object" which allows calculation. Please give it a try first.

**Comment by kevinpapst** [comment]
I keep that idea for the future, as there are plans to further extend the export.
But: not everything fits into the general exporters that come with Kimai.
You can always create own exporters for specialized tasks.

**Comment by kevinpapst** [comment]
Closing, as this would produce wrong results (and you wouldn't be able to see that it is a running record).
