### ISSUE TITLE
Create a new plugin to create/manage new Roles directly from the frontend

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1057]
Based on the documentation new roles could be defined by setting them up in the backend. What would be great is if this functionality is available via the frontend more like the metafields plugin. This way backend access is not needed to set them up. 

A simple paid plugin would also be good as this would have greater potential for the end users and admins.

--------
Creating new roles
If the pre-defined roles are not sufficient for your use-case and you need more roles, you can create them by changing two files:

in config/packages/security.yaml at security.role_hierarchy
in config/packages/local.yaml at kimai.permissions
Lets create the new role ROLE_SALES:

# config/packages/security.yaml
security:
    role_hierarchy:
        ROLE_SALES:       ~
        ROLE_TEAMLEAD:    ROLE_USER
        ROLE_ADMIN:       ROLE_TEAMLEAD
        ROLE_SUPER_ADMIN: ROLE_ADMIN
and:

# config/packages/local.yaml
kimai:
    permissions:
        sets:
            ROLE_SALES: ['@ROLE_USER', '@TAGS']
        maps:
            ROLE_SALES: ['ROLE_SALES']

**Comment by kevinpapst** [comment]
Be aware that new roles ONLY work with the next release 1.2.
I am not sure if a plugin is possible, as roles are deeply integrated into the system and all information read and cached during `bin/console cache:clear`. But I'll read about it.

**Comment by kevinpapst** [comment]
that feature was added with 1.6, see https://www.kimai.org/blog/2019/kimai-v2-release-1-6/
