### ISSUE TITLE
Failed to get Password Recovery mail

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1060]
I edited the MAILER_URL in .env file

`MAILER_URL=smtp://server_username:mypassword@127.0.0.1:25?encryption=&auth_mode=plain`

`MAILER_FROM=xxxx@gmail.com`

and i Tested using `bin/console -vv swiftmailer:email:send` ., It Worked . i Got the mail .

But when i using Forget password to get the link , i didn't received No mail .  

where i made a mistake ?.

**Comment by kevinpapst** [comment]
I don't know. Check your log ... and please try if it works on the demo installation.

**Comment by karthikalsv** [comment]
It is not working on demo installation also .... and There is no error showing in log file for this .

**Comment by kevinpapst** [comment]
Well, but it works for me on the demo.

**Comment by karthikalsv** [comment]
But I didn't get any mail to my mail id's . I used this below link 

https://demo-stable.kimai.org/en/login

**Comment by karthikalsv** [comment]
In the spam folder also no messages are found

**Comment by kevinpapst** [comment]
You only get one email per account for every two hours. If you tried it before and sending failed, then changed the config -> then you have to wait for 2h before you can try it again (even if it says "an email was sent").

**Comment by karthikalsv** [comment]
As you said I request only one time at demo site for 2hours. But no email didn't came to me.

**Comment by karthikalsv** [comment]
It Working now . I Just change disabled True-False

`swiftmailer:
    disable_delivery: false` .

Can you go back and solve my another problem #1048

**Comment by kevinpapst** [comment]
Are you running in test env? This mode is not meant to be used. Change to prod.

**Comment by karthikalsv** [comment]
Yes, I Running on test env . Now i Chnage into Default option . And Gave Write Permission to var/Cache . It Working Well . Thanks

**Comment by kevinpapst** [comment]
Great 👍 `test` is only meant for development purpose and will make troubles in prod (as you found out).

**Comment by karthikalsv** [comment]
Timesheet View is not Proper in Mobile App and in Mobile Browser too .

![Screenshot_2019-08-24-13-24-06-991_com example simarabia](https://user-images.githubusercontent.com/25294547/63637057-73fe8e80-c695-11e9-97b4-f41e49321381.png)

This issues is going to Resolve in Kimai2 1.2 ?

**Comment by kevinpapst** [comment]
This is not a forum. Please stay on topic in your issues. 
Open a new issue if you think you found a bug or want a new feature.
Don't use arbitrary issues to post random things.

**Comment by karthikalsv** [comment]
Am Sorry For This
