### ISSUE TITLE
Timesheet View in Mobile 

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1062]
Timesheet View is not Proper in Mobile App and Mobile Browser .

![Screenshot_2019-08-24-13-24-06-991_com example simarabia](https://user-images.githubusercontent.com/25294547/63637118-4534e800-c696-11e9-9698-fe684038b673.png)

This Issue will resolve in next version ?

**Comment by kevinpapst** [comment]
Everything looks great. What is your issue?

**Comment by karthikalsv** [comment]
I cannot able to see Customer,Project,Activities and so on

**Comment by kevinpapst** [comment]
Yes. On purpose. Where do you want to show this information? There is no space.
If you have a good proposal how to change that, I'd like to hear it.

**Comment by kevinpapst** [comment]
BTW. you can show the other columns by using the "eye button", changing the columns, saving and reload.
