### ISSUE TITLE
Calendar just don't show up  without any error !!!!

### ISSUE THREAD

**Issue by mohamed-groun** [kevinpapst/kimai2#1065]
- [ ] @
![t](https://user-images.githubusercontent.com/44194988/63706748-1c445c80-c828-11e9-8189-77276fc7c7e1.jpg)

**Comment by kevinpapst** [comment]
Hey @mohamed-groun , you are a full stack developer, so I would assume you know that a bug report should include more than a screenshot !!!! ;-)
What about your browser console?
What about the log file? https://www.kimai.org/documentation/faq.html#i-have-a-problem

**Comment by kevinpapst** [comment]
Feedback or closing ...

**Comment by mohamed-groun** [comment]
i just download  the prject step by step then i upgrade the version of the template from 4.2 to 4.3 , i m using windows 10 , i can make a CRUD for  Timesheet but i cant see them in my calendar

**Comment by kevinpapst** [comment]
> upgrade the version of the template from 4.2 to 4.3

what exactly did you do?

**Comment by JGrotepass** [comment]
I am currently running into the same issue. Using PHP 7.3 The Apache-Error log contains:
[Fri Sep 06 10:19:50.242398 2019] [php7:error] [pid 1786] [client 79.197.76.21:38019] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /prod/kimai_V2-1-1/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: https://timenew.sagadc.com/de/calendar/
[Fri Sep 06 10:19:50.243140 2019] [php7:error] [pid 1786] [client 79.197.76.21:38019] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /prod/kimai_V2-1-1/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1, referer: https://timenew.sagadc.com/de/calendar/
[Fri Sep 06 10:19:50.730539 2019] [php7:error] [pid 1787] [client 79.197.76.21:60353] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /prod/kimai_V2-1-1/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: https://timenew.sagadc.com/de/calendar/
[Fri Sep 06 10:19:50.731466 2019] [php7:error] [pid 1787] [client 79.197.76.21:60353] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /prod/kimai_V2-1-1/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1, referer: https://timenew.sagadc.com/de/calendar/

I have increased the allowed php-memory from default 128M to 256M to 512M without (with restarting Apache) effect on the issue. 
The error console of the browser shows: 
![image](https://user-images.githubusercontent.com/54812367/64412760-67643800-d090-11e9-8eeb-b15379a9b68b.png)

I am using the "invoice-description" branch at the moment.

**Comment by JGrotepass** [comment]
Sorry, I was wrong. Staying on the branch from the last PR1079 the name of the calendar.js was different and therefore not found. Switching back and refreshing the cache solved the issue.
So maybe this is also the case at the Case-Opener.

**Comment by kevinpapst** [comment]
Hm, that looks as if your log directory cannot be written. If Monolog crashes with OutOfMemory, that means an error cannot be written to the log, resulting in an endless loop of trying to write that new error and so on...
Regarding the cache: sounds weird, every front-end built has its own filename, so switching branches shouldn't be a problem (as long as you flush the Symfony cache).

**Comment by kevinpapst** [comment]
No feedback, closing
