### ISSUE TITLE
don't show global activities on projects with assigned activities or make it configurable

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#1070]
**Is your feature request related to a problem? Please describe.**
If you have global activities you might not want to see them if you have projects with assigned activities.

Example: you have a trainee. The trainee has to track working times in school, too. You have global activities like: developing, consulting, on site-service, etc. The trainee has a customer and project with name "vocational school". The global activities mentioned above show up too. Even if an activity "learning" is assigned to the project.

**Describe the solution you'd like**
Make it configurable to show or not show global activities at a project with assigned activities.

**Comment by kevinpapst** [comment]
There is a similar request already existing

**Comment by hmr-it-jr** [comment]
#475

Closed.

**Comment by kevinpapst** [comment]
Don't forget to vote for it ;-)
