### ISSUE TITLE
Disable User registration

### ISSUE THREAD

**Issue by sebsom** [kevinpapst/kimai2#1072]
I just installed the FTP Version. Now I'm trying to find the local.yaml to change it to disable user registration but I couldnt find it... 
Any Idea how to proceed?

**Comment by hmr-it-jr** [comment]
read this: https://www.kimai.org/documentation/users.html#disable-user-registration

create local.yaml in config/packages

**Comment by kevinpapst** [comment]
Additionally read this: https://www.kimai.org/documentation/configurations.html
