### ISSUE TITLE
Wrong ${entry.total} for fixed rate items if more than one

### ISSUE THREAD

**Issue by JayAige** [kevinpapst/kimai2#1073]
This bug report is related to #1008 and #959 and #1058 

When having more than one fixed rate item for the same accounting period (in my case travel expenses), the ${entry.total} variable outputs the value of the single item price. Therefore ${entry.total} and ${entry.rate} are the same.

For example: 100 € shall be billed as travel expense. In the month August I travelled 5 times to a customer. ${entry.rate} outputs 100, ${entry.amount} outputs 5 and ${entry.total} is supposed to output 500 but outputs 100 instead. I used a docx template for generation and the one entry per activity configuration.

The total price value in the invoice preview does not show this bug. Also ${invoice.subtotal} and ${invoice.total} are not affected, as I can see. I was allready able to reproduce this on the demo system.

**Comment by kevinpapst** [comment]
will be fixed with #1068
