### ISSUE TITLE
Content of ${entry.description} not from table timesheet.description

### ISSUE THREAD

**Issue by JGrotepass** [kevinpapst/kimai2#1076]
When I try to generate an Invoice I am not getting the data from the table.row "timesheet.desciption" printed in the Variable "${entry.description}" but instead the data that is stored either in Activity description or Project description (depending on the selection for Invoice generation).
Is there any chance to get the data that is stored in timesheet.description printed in ${entry.description}? What am I doing wrong.

Thanks
Jochen

**Comment by kevinpapst** [comment]
The content depends on the calculator you have chosen.
Show me the config of your invoice template.

**Comment by JGrotepass** [comment]
This one?

![image](https://user-images.githubusercontent.com/54812367/64126163-0c3ef680-cdad-11e9-962c-960abeee00dd.png)

**Comment by kevinpapst** [comment]
Exactly, thanks. 
I'll have a look why the description is not used.

**Comment by JGrotepass** [comment]
This is the template I've created. However in any other template the same happens. 

[Stundennachweis.docx](https://github.com/kevinpapst/kimai2/files/3566667/Stundennachweis.docx)

**Comment by kevinpapst** [comment]
Are you capable of testing the attached PR #1079 ?

**Comment by JGrotepass** [comment]
Thanks Kevin. I‘ll give it a try tomorrow.

**Comment by JGrotepass** [comment]
Thank you Kevin. Works as expected. Perfect.

**Comment by kevinpapst** [comment]
Thanks for testing!

**Comment by kevinpapst** [comment]
WOW 😮 thanks!!!!!!!
