### ISSUE TITLE
Profile image

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1078]
Under "user" - "name of user" - "user profile", one can add a "profile image"

The only location, where I could find the profile image been shown is under "user profile" - "statistics"
![grafik](https://user-images.githubusercontent.com/51003649/64133959-568a9c80-cdda-11e9-830a-7fbb12d56dc6.png)

It would be nice, if the profile image would also be shown at the upper right corner 
![grafik](https://user-images.githubusercontent.com/51003649/64134069-1841ad00-cddb-11e9-9a8a-b17a8de08b65.png)

**Comment by kevinpapst** [comment]
Hm, I think I tried that in the past and decided against. But don't ask me why, I forgot ;-)

Actually I planned to show the image in some tables (eg. team members).
