### ISSUE TITLE
Using the variable ${entry.duration_decimal} and ${invoice.duration_decimal} should always have 2 decimals 

### ISSUE THREAD

**Issue by JGrotepass** [kevinpapst/kimai2#1080]
With Change #1037 new variables for invoices were introduced. At least in my case the format of these variables are without 2 decimal characters. That means, that a value of "7.00" will be printed as "7", a value of "7.50" will be printed as "7.5". 
This results in a invoice report that does not look very nice. 
Is it possible to have both variables formatted with 2 decimal characters?
Thanks
Jochen

Here a screenshot:
![image](https://user-images.githubusercontent.com/54812367/64257635-fa349380-cf25-11e9-98fc-359dc869e809.png)

**Comment by gises** [comment]
Hello, Kevin, 
There are different number formats depending on the country. Is it possible to take this into account as well?
For example, Siwtzerland and Germany are a bit different. 
![image](https://user-images.githubusercontent.com/54983006/64421038-efead480-d0a0-11e9-8aaa-c747e03d234e.png)

Thanks for your effort!

**Comment by kevinpapst** [comment]
I think we can add `de_CH` as locale. Please open a new issues for that, as this is not related to invoices. Can you provide a PR / all the required information mentioned here (in the new issue):
https://www.kimai.org/documentation/translations.html#configure-locale-formats

**Comment by kevinpapst** [comment]
You can simply change your invoice template.
Set the format for the column / cells to be a number with two decimals.
