### ISSUE TITLE
Doc for rebuilding assets not found

### ISSUE THREAD

**Issue by vesamet** [kevinpapst/kimai2#1085]
The docs available at the following isn't available anymore: https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory

I've been seeking this page for quite a while, and can't find it.

**To Reproduce**
1. Go to https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory
2. You hit 404 error.

**Comment by kevinpapst** [comment]
I'd like to fix the URL: where did you get that link from?

Everything is in the website:
https://www.kimai.org/documentation/developers.html#frontend-dependencies

**Comment by vesamet** [comment]
here : https://github.com/kevinpapst/kimai2/issues/492#issuecomment-453129101
and here: https://www.bountysource.com/issues/62108961-memory-size-always-exhausted

**Comment by kevinpapst** [comment]
Ah, right. I thought there might be an outdated link somewhere in the docs. 

Actually it shouldn't be necessary to rebuild the assets, at least not for use in subdirectories.
Haven't tested it for a while. but last time I checked, you could use Kimai both on domain and directory level.

**Comment by vesamet** [comment]
I guess i'm reverse proxying the docker instance the wrong way...
I'm using the default docker-compose config, and my reverse proxy looks like this:
```                                                                                                                                                                                                location /kimai {                                                                                                                                                                                                      proxy_pass  http://127.0.0.1:8004/;                                                                                                                                                                                proxy_set_header    Host                $http_host;                                                                                                                                                                proxy_set_header    X-Real-IP           $remote_addr;                                                                                                                                                              proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;                                                                                                                                                proxy_set_header    X-Forwarded-Proto $scheme;                                                                                                                                                                     proxy_hide_header   "content-security-policy";                                                                                                                                                                 }        
```

**Comment by kevinpapst** [comment]
I have never set this up. Did you find a solution?

If not, maybe you can ask in the docker repository, I am not managing these images. 
And if you find a solution, I'd be very happy if you can post it, so I can add a chapter in the documentation.
