### ISSUE TITLE
Team is hidden after creating a new user 

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1089]
Hi,
 i have installed kimai2 1.2 . After i created a new user ., Team Tab is hidden under the system .

![Screenshot_16](https://user-images.githubusercontent.com/25294547/64510559-1195c700-d300-11e9-8ab1-dd674ae6c488.png)

**Comment by kevinpapst** [comment]
Not reproducible. The bug report template is there for a reason. If you can reproduce the behavior in the stable demo http://www.kimai.org/demo/ I will have a look

**Comment by karthikalsv** [comment]
In demo there is no bug ., but in my kimai ., i am not able to see team tab or page after creating first user .

**Comment by karthikalsv** [comment]
Yes your correct , Now its all perfectly alright . Thank you for your timing

**Comment by karthikalsv** [comment]
any idea to add location option for timesheeet in upcoming updates ?
