### ISSUE TITLE
Upgrade v1.1 to v1.2

### ISSUE THREAD

**Issue by thatmatthewxu** [kevinpapst/kimai2#1090]
Hi there,

Recently I just installed one v1.1 (stable), but now v1.2 is released.
May I know how I can upgrade from v1.1 to v1.2?

Only need to git clone the latest code or need to modify the db (mysql) as well?

Thanks.
Matthew

**Comment by hmr-it-jr** [comment]
The full process is described here: https://www.kimai.org/documentation/updates.html
