### ISSUE TITLE
v1.2 | export to PDF creates Error 500

### ISSUE THREAD

**Issue by relume** [kevinpapst/kimai2#1091]
Hello

I just updated from version 1.1 to 1.2.  As far I can see v1.2 works well. The only part that is not working is Export-Option exporting to PDF. The export process stops to an Error 500  page.

Any hints to resolve this problem? Many thanks in advance.

**Comment by kevinpapst** [comment]
Check the last lines from var/log/prod.log

**Comment by relume** [comment]
Thank you very much for your prompte resposse.

The problem was the correct posix user/group settings after upgrade. Resolved with chown -R wwwrun.

best regards
