### ISSUE TITLE
When create invoice, Description field is not description but is Activity

### ISSUE THREAD

**Issue by SerjBondarenko** [kevinpapst/kimai2#1093]
**Describe the bug**
When I create Invoice, press Preview or Print, the Description fields = Activities, but not description from timesheets. When I create Export, Description is all right.

**To Reproduce**
1. Go to Invoice
2. Set Time range, Customer, Template. Click Preview or Click Print.
3. See error

BUT when I do that on https://demo-branch.kimai.org, everything Ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/55141197/64613384-aff85a00-d3de-11e9-995f-b0ef118d33d5.png)
![image](https://user-images.githubusercontent.com/55141197/64613497-ef26ab00-d3de-11e9-8012-c77f625d6ebc.png)
![image](https://user-images.githubusercontent.com/55141197/64613558-1aa99580-d3df-11e9-92dd-df65d21d799d.png)

**Desktop**
Please complete the following information if this seems to be a frontend issue:
 - Inte Core 2Duo 2.2GHz/4G
 - Server OS: SMP Debian 4.19.37-5 (2019-06-19) i686 GNU/Linux + apache2
 - Client OS: Windows 10
 - Client Browser Chrome 76.0.3809.132 x64 last
 

**Additional context**
 - Kimai version 
1.2 Already up to date.
 - PHP version
PHP 7.3.9-1+0~20190902.44+debian10~1.gbpf8534c (cli) (built: Sep  2 2019 13:33:22) ( NTS )

**Comment by kevinpapst** [comment]
Was fixed in #1079 and will be released with 1.3

**Comment by SerjBondarenko** [comment]
Sorry

**Comment by kevinpapst** [comment]
All good ;-) I appreciate every feedback! 
Its just that you are too late to the party and its already fixed 😀
