### ISSUE TITLE
Error Installation brand new Debian10, Apache2, PHP7.3

### ISSUE THREAD

**Issue by erdenkind** [kevinpapst/kimai2#1095]
**Describe the bug**
The Installation of Kimai2  bin/console kimai:install breaks

An exception occured while establishing a connection to figure out your platform version.
You can circumvent this by setting a 'server_version' configuration value
For further information have a look at:
https://github.com/doctrine/DoctrineBundle/issues/673

**To Reproduce**
1. Base System installed as described in the documentation
2. Install Kima2 started
3. See error

**Logfile**
```
See error above
```

**Comment by kevinpapst** [comment]
That often indicates that your .env DATABASE_URL is misconfigured.
If you are 110% sure it correct, you can try to edit the file [config/packages/doctrine.yaml](https://github.com/kevinpapst/kimai2/blob/master/config/packages/doctrine.yaml#L17) and change `# server_version: '5.7'` to `server_version: '5.7'`, then run `bin/console cache:clear` and run the installer again.
But first check twice that your DATABASE_URL is correct.

**Comment by erdenkind** [comment]
.env:

# This file is a "template" of which env vars need to be defined for your application
# Copy this file to .env file for development, create environment variables when deploying to production
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

MAILER_FROM=kimai@example.com

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=change_this_to_something_unique
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data/kimai.sqlite"
# Configure your db driver and server_version in config/packages/doctrine.yaml
DATABASE_URL=mysql://kimaifour:passwd@127.0.0.1:3306/kimaifour
# DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/kimai.sqlite
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###

###> nelmio/cors-bundle ###
CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$
###< nelmio/cors-bundle ###

**Comment by erdenkind** [comment]
Doctrine.yaml:

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
  	        server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

...

**Comment by erdenkind** [comment]
Error still exists:

In ConnectionFactory.php line 79:

  An exception occured while establishing a connection to figure out your platform version.
  You can circumvent this by setting a 'server_version' configuration value

  For further information have a look at:
  https://github.com/doctrine/DoctrineBundle/issues/673


In AbstractMySQLDriver.php line 93:

  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'kimaifour'@'localhost' (using password: YES)


In PDOConnection.php line 31:

  SQLSTATE[HY000] [1045] Access denied for user 'kimaifour'@'localhost' (using password: YES)


In PDOConnection.php line 27:

  SQLSTATE[HY000] [1045] Access denied for user 'kimaifour'@'localhost' (using password: YES)



In ConnectionFactory.php line 79:

  An exception occured while establishing a connection to figure out your platform version.
  You can circumvent this by setting a 'server_version' configuration value

  For further information have a look at:
  https://github.com/doctrine/DoctrineBundle/issues/673


In AbstractMySQLDriver.php line 93:

  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'kimaifour'@'localhost' (using password: YES)


In PDOConnection.php line 31:

  SQLSTATE[HY000] [1045] Access denied for user 'kimaifour'@'localhost' (using password: YES)


In PDOConnection.php line 27:

  SQLSTATE[HY000] [1045] Access denied for user 'kimaifour'@'localhost' (using password: YES)

**Comment by kevinpapst** [comment]
This is your real problem:

> Access denied for user 'kimaifour'@'localhost' (using password: YES)

As I said:
> That often indicates that your .env DATABASE_URL is misconfigured.

The error `An exception occured while establishing a connection to figure out your platform version. You can circumvent this by setting a 'server_version' configuration value ` is misleading, because it is just a follow up error. 

You have to fix your database connection. If Kimai can't reach the database, the server version cannot be found as well. You can revert the changes in the doctrine.yaml.

**Comment by erdenkind** [comment]
Hello,

sorry for a Little offtopic questioning:

mysql starts..normally.
Connect kimaifour works fine

Do you have a little howto, ho to configure the mysql database after a brand new installation?

That's what I did for the kimaifour User (full acces for the first test)
CREATE USER 'kimaifour'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'kimaifor'@'localhost';

**Comment by kevinpapst** [comment]
That has actually nothing to do with Kimai and is documented thousands of times in the Internet ;-) But here you go: https://www.kimai.org/documentation/fresh-ubuntu-18.html#create-database

Is that just a typo here or also in your installation?

>GRANT ALL PRIVILEGES ON . TO 'kimaifor'@'localhost';

`kimaifor` vs `kimaifour`

**Comment by erdenkind** [comment]
Hello back,

MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS `kimaifour`;
Query OK, 1 row affected (0.001 sec)
MariaDB [(none)]> CREATE USER IF NOT EXISTS `kimaifour`@127.0.0.1 IDENTIFIED BY "passwd";
Query OK, 0 rows affected (0.001 sec)
MariaDB [(none)]> GRANT select,insert,update,delete,create,alter,drop,index,references ON `kimaifour`.* TO kimaifour@127.0.0.1;
Query OK, 0 rows affected (0.000 sec)
MariaDB [(none)]> exit;
Bye


Still the connection problem, but only with the kimai installation. PHP Check files are able to connect to the mariaDB.

**Comment by kevinpapst** [comment]
Show me the check files please.
Is "passwd" really your password? Or is it some string containing special character?
But still: Kimai (Doctrine) uses normal pdo connections.

**Comment by erdenkind** [comment]
Sorry for bothering: what do you mean with "check files"..? I am a novice about the installation..

**Comment by kevinpapst** [comment]
Whatever you mean with:
> PHP Check files are able to connect to the mariaDB.
Show me the real connection string. This complete discussion is about solving your local problem. Kimai works fine, you have a problem in YOUR installation. If you want any more help, you have to show me the exact commands and configs you are using.

**Comment by erdenkind** [comment]
DATABASE_URL=mysql://kimaifour:applet4E$n@127.0.0.1:3306/kimaifour

**Comment by kevinpapst** [comment]
Can you please try (in this order) two things (I believe the `$` is the problem.
- add single quotes around the connection  `DATABASE_URL='mysql://kimaifour:applet4E$n@127.0.0.1:3306/kimaifour'`
- change the password to a string NOT containing the $

**Comment by kevinpapst** [comment]
And if that still fails, the last idea I have is [to replace this line](https://github.com/kevinpapst/kimai2/blob/master/config/packages/doctrine.yaml#L13) from url: `'%env(resolve:DATABASE_URL)%'` to `url: '%env(DATABASE_URL)%'`

**Comment by erdenkind** [comment]
YESYESYES!

The dollar sign was the problem! THANKS!!!

**Comment by kevinpapst** [comment]
Do you have a local.yaml?

**Comment by erdenkind** [comment]
..I do have all the files that where downloaded by the git dup.

**Comment by kevinpapst** [comment]
What does `git status` report?

**Comment by kevinpapst** [comment]
Try `rm -rf var/cache/*` and then a `bin/console cache:warmup --env=prod`

**Comment by erdenkind** [comment]
Super!

[OK] Cache for the "prod" environment (debug=false) was successfully warmed.

**Comment by kevinpapst** [comment]
Maybe some hickup due to the previous problems.

**Comment by erdenkind** [comment]
Sorry for another "user"question: aftter the installation: what is the url that I can reach kimai now? Or do I have to add it into the apache2 first? (if YES: how to add the kimai2: its files are located under /var/www/kimai2/ ..default website apache2 /var/www/html/

**Comment by kevinpapst** [comment]
Did you consider to read the documentation first? I know asking is easier ...- but its all in there:
https://www.kimai.org/documentation/installation.html#webserver
https://www.kimai.org/documentation/fresh-ubuntu-18.html
https://www.kimai.org/documentation/webserver-configuration.html

**Comment by acmeraptor** [comment]
You can feel free to check my temporary wiki at https://wiki.casperbb.com/view/Wyvt-rsksolutions
I'm trying to meld a couple of things onto a fresh virtual machine to suit my business needs, but the kimai2 parts work perfectly using Kevin's documentation (even LDAP).  I just had to pull pieces from his various links to make it flow a little better.

**Comment by kevinpapst** [comment]
Awesome @acmeraptor thanks for sharing 👍 if you have any hint how to improve the official documentation, please let me know! 
It's not that easy to write a good documentation, if you don't need it yourself ;-)

**Comment by kevinpapst** [comment]
Seems to be solved
