### ISSUE TITLE
How to make recalculation of the hourly rates for timesheet records?

### ISSUE THREAD

**Issue by SerjBondarenko** [kevinpapst/kimai2#1097]
I have Recalculate rates plugin
When I change project hourly rate, timesheet records hourly rates are not change automaticly.
But when I edit timesheet record and delete old hourly rate from field of this recors and save,
in this moment new hourly rate saved in timesheet.
But this is hardly clean hourly rate fields on every timesheets of project.
May be exist other method?

kimai 1.2 on debian 4.19.37

**Comment by kevinpapst** [comment]
Batch changing of any rates for already existing timesheet records is not supported.
You can probably do it via SQL or write a new plugin.
But I will not add support for this in the core.
