### ISSUE TITLE
Limit users from creating tags unless a defined start pattern or pattern is matched 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1101]
Having the option of creating tags when one is not present is really good. 

Currently users have the option of creating tags without following any said rule or logic. Would it be possible to prevent tag creation such that new tags are created only if a said pattern is adhered to or the tags start with some defined pattern. 

This can help prevent junk entries from getting into the tags table.

**Comment by kevinpapst** [comment]
With #1463 you can choose whether you allow users to create new tags or only choose existing ones from a dropdown list.

In my "vision" tags are completely free in their use, but if a company wants to prevent that, they can now choose to opt-out and pre-define the tags.

I would accept a PR for that, but I am not adding a configurable pattern myself. So I am closing here
