### ISSUE TITLE
Freezing after import data from V1

### ISSUE THREAD

**Issue by PjotrDumat** [kevinpapst/kimai2#1107]
**Describe the bug**
Runs wel, but after importing from V1.2 the application freezes right after opening its home page. So, the login page is accessible, but thingd hold after authentication.

**To Reproduce**
Unclear (van not share data because its contents are confidential; )

**Logfile**
Fri Sep 06 12:50:48.834615 2019] [php7:error] [pid 18] [client 172.20.0.1:37533] PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 135168 bytes) in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Fri Sep 06 12:50:58.403478 2019] [php7:error] [pid 18] [client 172.20.0.1:37533] PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
172.20.0.1 - - [06/Sep/2019:12:49:24 +0000] "GET /index.php/en/homepage HTTP/1.1" 500 210 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"

(By far) largest table in V1: kimai_zaf with 11296 rows

**Screenshots**
NA

**Desktop/Smartphone**
NA

**Additional context**
NA

**Comment by kevinpapst** [comment]
Set proper permissions for the `var/log/` folder. 
The logger wants to write a log file, fails => Kimai crashes.

**Comment by PjotrDumat** [comment]
**Thank you !  That help ... however, my system admin replies:**

I have fixed permissions and bump into another issue with Timezone. Haven't resolve it yet.

[Sat Sep 14 03:25:46.614707 2019] [php7:error] [pid 40] [client 172.20.0.1:40234] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone (localtime) in /var/www/src/Timesheet/UserDateTimeFactory.php:31\nStack trace:\n#0 /var/www/src/Timesheet/UserDateTimeFactory.php(31): DateTimeZone->__construct('localtime')\n#1 /var/www/var/cache/prod/ContainerZOHuayo/srcApp_KernelProdContainer.php(1354): App\\Timesheet\\UserDateTimeFactory->__construct(Object(App\\Entity\\User))\n#2 /var/www/var/cache/prod/ContainerZOHuayo/srcApp_KernelProdContainer.php(1401): ContainerZOHuayo\\srcApp_KernelProdContainer->getUserDateTimeFactoryService()\n#3 /var/www/var/cache/prod/ContainerZOHuayo/srcApp_KernelProdContainer.php(1196): ContainerZOHuayo\\srcApp_KernelProdContainer->getWidgetServiceService()\n#4 /var/www/var/cache/prod/ContainerZOHuayo/srcApp_KernelProdContainer.php(1951): ContainerZOHuayo\\srcApp_KernelProdContainer->getTwigService()\n#5 /var/www/var/cache/prod/ContainerZOHuayo/srcApp_KernelProdContainer.php(846): ContainerZOHuayo\\srcApp_KernelProdContainer->getSensioFrameworkExtra_View_ListenerServic in /var/www/templates/base.html.twig on line 184
172.20.0.1 - - [14/Sep/2019:03:25:46 +0000] "GET /index.php/en/homepage HTTP/1.1" 500 210 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"

But execution 

root@4d5ae1fd179c:/var/www/public# php -r ' var_dump(date_default_timezone_get());'
string(16) "Europe/Amsterdam"

Timezone is set up on PHP level.

_If you can get quicker information from support team what have to be done it will be nice. In other case I have to deep into details and found out what exactly have to be fixed._

**Any possible fixes that pop up ?**

**Comment by kevinpapst** [comment]
PHP cli config is not necessary the same then webserver/fpm config.

There is a screen in Kimai to check the PHP configs at https://your-kimai/en/about/debug (only for SUPER_ADMIN).

You can set timezones in several places. Please set all of them, read more at: 
https://www.kimai.org/documentation/inital-setup.html
https://www.kimai.org/documentation/user-preferences.html#timezone
