### ISSUE TITLE
Plugin won't register

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#1108]
For testing issues I created a plugin to play around with what the system can do. I created an empty plugin to check if Kimai Recognizes it, but it doesn't.

I installed the CustomCSS Plugin which works fine.

_**Maybe the minimum requirements for plugins in the docs are not complete?**_

**To Reproduce**
1. followed the instructions on https://www.kimai.org/documentation/plugins.html for minimum requirements
2. created the minimum directory structure, Bundle class .php, composer.json 
3. refreshed cache
bin/console cache:clear --env=prod
bin/console cache:warmup --env=prod

In Kimai, the plugin is not shown in the plugins section.

I also tried to subscribe to the menu by creating a EventSubscriber/MenuSubscriber.php following https://www.kimai.org/documentation/developers.html#extending-the-navigation-bar

but since kimai doesnt recognize the plugin, it also doesnt show the menu item

**Additional context**

 - Kimai version 1.2
 - PHP version 7.1

**Comment by kevinpapst** [comment]
There are many reasons why this can fail, so help is impossible without sharing the source code.
Can you create a repo with your current code?

**Comment by stereo9** [comment]
https://github.com/stereo9/TestBundle

**Comment by kevinpapst** [comment]
Well, I guess the documentation is not complete. I wrote it for people who are familiar with Symfony.

What you actually need:
```
.
├── DependencyInjection
│   └── TestExtension.php
├── Resources
│   └── config
│       └── services.yaml
├── TestBundle.php
└── composer.json
```

with TestExtension.php
```

namespace KimaiPlugin\TestBundle\DependencyInjection;

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;

class TestExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        try {
            $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__ . '/../Resources/config'));
            $loader->load('services.yaml');
        } catch (\Exception $e) {
            echo '[TestBundle] invalid services config found: ' . $e->getMessage();
        }
    }
}
```

and services.yaml 

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:

    KimaiPlugin\TestBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'
```

**Comment by kevinpapst** [comment]
Updated documentation: https://www.kimai.org/documentation/plugins.html#directory-structure
