### ISSUE TITLE
Prevent search from getting closed on each selection

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1112]
The new global search option is quiet useful, but once it opens - for each selection the screen closes automatically and one has to again click on the search bar to reopen the search screen and then choose the next selection item, this needs to be repeated for each selection since the screen closes each time. If the search screen window stays open till the entire selection is completed by the user it would help in terms of user experience.
![Screenshot_20190916_130731](https://user-images.githubusercontent.com/50443902/64940950-f9cfbd00-d882-11e9-91f7-e983500131ab.png)

**Comment by rarvin** [comment]
Just to update this issue is seen only when the javascript (select-boxes in forms) option is chosen. The screens dont close with the non-javascript option.

**Comment by JayAige** [comment]
In addition: The search screen remains when javascript option is not used for all fields except 'time range'. When I select a specific time range, the screen closes and I have to reopen it.

**Comment by SerjBondarenko** [comment]
I'm joining. I have the same issue.

**Comment by kevinpapst** [comment]
If you would know how much time I already spent with that damn javascript select component ...
Honestly: I spent probably 10 hours trying top fix it. Seems not possible, there is a technical limitation I cannot get around. 

There is just one thing that I did not try yet. If that doesn't work there are only two options:
- completely change the UI of that search/filter dropdown
- disable the JS component for the filters

**Comment by rarvin** [comment]
It’s okay please don’t waste time with it, I am very happy to live with it.

Thank you, for the effort you are already putting into it.
-- 
Regards,
Aravind

**Comment by kevinpapst** [comment]
I replaced the JS component which was used. You shouldn't notice the difference in behavior, just the look is slightly different.
Can you please re-test this at: https://demo-branch.kimai.org

**Comment by JayAige** [comment]
Works perfect for me. Thank you very much!

**Comment by rarvin** [comment]
Works well, no issues on Mobile too.
-- 
Regards,
Aravind

**Comment by SerjBondarenko** [comment]
Very good, thank you.
