### ISSUE TITLE
Ability to add multiple team leads to a team 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1115]
With teams one can create teams and add users and a team lead to a team. Currently only the team lead can see all details of the users under the team. What would be great would be the if one can have multiple team leads for a specific team so that all these team leads can view the user details under that specific team without having to create a new team with the same users. 

Or a new role called team owner as the owner for the team and then team leads under the said team who can all view the user details. 

An option to copy an existing team would be good to have so that one can copy an existing team with the users and rename the team lead to a new one

**Comment by hmr-it-jr** [comment]
Useful if the only teamleader is absent and so on.

**Comment by kevinpapst** [comment]
Solved with one of the latest releases
