### ISSUE TITLE
Error 500 On Fresh Install Of 1.3

### ISSUE THREAD

**Issue by acmeraptor** [kevinpapst/kimai2#1117]
**Describe the bug**
Minor/documentation. There appears to be new files/paths created between the documented step of changing file ownership/permissions and the console installation.
[kimai-1.3-error.log](https://github.com/kevinpapst/kimai2/files/3623891/kimai-1.3-error.log)

**To Reproduce**
1. chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
2. (In .env file) DATABASE_URL=mysql://user:password@127.0.0.1:3306/database
3. bin/console kimai:install -n

**Additional context**
Re-running the ownership/permission changes following the install step clears the error.

**Comment by kevinpapst** [comment]
Hm, that shouldn't happen. Actually the caches should be pre-filled before you open the page the first time. I'll give it a try and see if anything changed.
Thanks for posting!

**Comment by acmeraptor** [comment]
I didn't dive into the whole tree structure, but I saw that (mypath)/kimai2/var/cache/prod had somehow reverted from :www-data to :mygroup following the install step.  I just ran the recursive chown to fix it again.
This is a test VM so I tried several times going back and forth between 1.2 and 1.3, it only happens on 1.3 for some reason.  Hope this helps!

**Comment by kevinpapst** [comment]
Can't remember when I added the change to the documentation, introducing the `kimai:install` command. But I guess that the updated documentation should do the trick:
https://www.kimai.org/documentation/installation.html#recommended-setup

The permission change is not necessary before the install command, as all is done by the same user.

**Comment by kevinpapst** [comment]
What I want to say is: I changed the order, first install then change permissions.
I hope that this will fix all issues.

Thanks for posting, that was important feedback and it will likely help to prevent a lot of questions by less experienced bash users ;-)
