### ISSUE TITLE
cant disable user register 

### ISSUE THREAD

**Issue by Ghost173** [kevinpapst/kimai2#1118]
**Describe the bug**
cant disable user register 

**To Reproduce**
1. go to your server 
2. navigate to config/packages/
3. crate a local.yaml fil 
4. add following code 
```
kimai:
    user:
        registration: false
```
and add this

```
admin_lte:
    routes:
        adminlte_registration: ~
```
5. give a permison to www:data 
6. check the web site still user can register 

**Logfile**
no log files

**Screenshots**
no any screen shots 

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: pc
 - OS: ubuntu 18.04 (server and my lap os are same )
 - Browser: Chromium 
 - Version 77.0.3865.75 (Official Build) snap (64-bit)

**Additional context**
 - Kimai version : kimai2-1.2
 - PHP version : <pre>7.2.19</pre>

**Comment by kevinpapst** [comment]
After each config change, the cache needs to be refreshed:
https://www.kimai.org/documentation/configurations.html#reload-changed-configurations
