### ISSUE TITLE
Create multiple entries

### ISSUE THREAD

**Issue by eglyn** [kevinpapst/kimai2#1119]
Hi :)

Is it possible to create multiple entries in the timesheet at one time ?
We have some user that can't connect in real time to Kimai, and they have to enter their timesheet at the end of the month.

But it is very time-consuming and boring to do :D 

That would be very helpful if there was a way to do for example: (in duration mode)
first date: 09 10 2019
end date: 09 25 2019
week-end: yes/no
every day = 8h
project = example.

thx in advance :)

**Comment by buzter** [comment]
Have You had a look at the Kimai2 apps from hmr-it under
[https://www.kimai.org/store/hmr-it-ios-offline-tracker.html](url)
[https://www.kimai.org/store/hmr-it-android-offline-tracker.html](url)

**Comment by hmr-it-jr** [comment]
I'm currently working on a plugin which exactly does what you want... You can enter a time range, the days per hour, customer, project, saturday and sunday... But as butzer mentioned if you want exact times you can use the offline tracker.

**Comment by acmeraptor** [comment]
@buzter those links don't seem to be valid, but we can likely find them easily enough

@hmr-it-jr that will be awesome!

**Comment by hmr-it-jr** [comment]
seems like the linked page is wrong in buzters comment:
https://www.kimai.org/store/hmr-it-ios-offline-tracker.html
https://www.kimai.org/store/hmr-it-android-offline-tracker.html

direct link to stores:
iOS: https://apps.apple.com/de/app/kimai-2-offline-zeiterfassung/id1459757165
Android: https://play.google.com/store/apps/details?id=de.hmrit.kimai2app

**Comment by hmr-it-jr** [comment]
@acmeraptor not fully translated yet - but it looks like this atm:

![grafik](https://user-images.githubusercontent.com/36242595/65171143-76f95e80-da4a-11e9-9f0b-2be6f6260749.png)

**Comment by eglyn** [comment]
> @acmeraptor & @eglyn not fully translated yet - but it looks like this atm:
> 
> ![grafik](https://user-images.githubusercontent.com/36242595/65171143-76f95e80-da4a-11e9-9f0b-2be6f6260749.png)

that's exactly what we need ! 👍 
Is there a way to know when the plugin will be available ?

**Comment by hmr-it-jr** [comment]
I think Kevin will leave this issue open until I've released this plugin. When I release the plugin I can make a comment here and post the link to the official store.

**Comment by eglyn** [comment]
That would be great ! thank you :)

**Comment by hmr-it-jr** [comment]
The plugin is now available: https://gum.co/pSNcQ

![period-insert-plugin](https://user-images.githubusercontent.com/36242595/65794768-29c36e00-e169-11e9-991f-8d6e2f5b0638.png)

**Comment by eglyn** [comment]
Good new :) I will test this plugin next week :)

**Comment by alqu** [comment]
Meanwhile there is now another feature available, but it works other way around:
you select the time and the according users. After that you have a time entry for each selected user.

**Comment by kevinpapst** [comment]
With the next version you can also drag & drop events to the calendar.
Still not a mass-editing mode, but you can: create a new event with one-click&drag and the another click&drag for the duration.

**Comment by kevinpapst** [comment]
Closing, plugin by @hmr-it-jr  available.
