### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by coneng** [kevinpapst/kimai2#1122]
Installation doesn't work
I followed the process
- setup nginx, mariadb and php with all add-ons required.
- install git and composer
- clone and run composer install
On the part :
`bin/console kimai:install -n`
I got hit with multiple errors about 'user' @ 'localhost' Access Denied.
Nothing is mentioned about the configuration of database for Kimai2 nor nginx.

![kimai2](https://user-images.githubusercontent.com/48026784/65252698-6dfaa280-dac7-11e9-92ab-0801abcf8f2f.png)

**Comment by kevinpapst** [comment]
Seems Kimai is working perfectly fine. 
You just need to pass a database user with sufficient permission.

See https://www.kimai.org/documentation/installation.html
> Configure the database connection in the .env file:
> eg. DATABASE_URL=mysql://user:password@127.0.0.1:3306/database

This could also help:
https://www.kimai.org/documentation/fresh-ubuntu-18.html#create-database

**Comment by coneng** [comment]
Ok I figured that out.
you need to create a username/password in mysql server and grant privileges for that user in mysql.
Then configure .env file

**Comment by kevinpapst** [comment]
Happy time-tracking!

**Comment by coneng** [comment]
wait!
it still doesn't work.
I can't see the website. How to configure nginx to make kimai2 work?

**Comment by kevinpapst** [comment]
> This could also help:
> https://www.kimai.org/documentation/fresh-ubuntu-18.html

**Comment by coneng** [comment]
ah, permissions are essential. Vendor directory was created after I applied general setup permissions and until I discovered that the application didn't work.
