### ISSUE TITLE
Sort ordering in invoice preview screen too

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1123]
The new sort and ordering is very good, if this is available in the invoice preview screen also it would be good.

**Comment by kevinpapst** [comment]
I have the feeling that you are using the invoice screen for something completely different then it was made for 😁 
I'll give it quick try to see if that might work. But I am not sure that merged results will be ordered properly, as the ordering happens before the data merge.

**Comment by kevinpapst** [comment]
Sorry @rarvin , doesn't work with the current ordering flow. 
It would only work for a couple of columns, but the results are unusable. 
I guess the interesting columns are duration, cost ... and this are calculated later on and thus can't be ordered. 
It would require additional javascript ordering plugins, but that would be a special thing for the invoice screen and I am not really into that.

Lets concentrate on a good reporting/stats plugin instead.
