### ISSUE TITLE
Search by user preference

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1124]
Dear Kevin,

I have created numerous user preference filed where i have updated details like location etc, can i use these fields in filtering data by using the search option in timesheets, export etc.

Regards
Aravind

**Comment by kevinpapst** [comment]
No, that is not possible. But with 1.4 you can export these fields. Maybe that is enough?

**Comment by kevinpapst** [comment]
Question answered, closing

**Comment by rarvin** [comment]
> No, that is not possible. But with 1.4 you can export these fields. Maybe that is enough?

I think anything would be helpful. But referencing values in the timesheet etc to a said user and their static fields could indeed be a powerful feature.

**Comment by kevinpapst** [comment]
It should be possible, but the database query will be quite expensive, especially using it with so many entries as you have.
Considering it would be used in the free search term field, what syntax would you propose? Something like `user-pref:location:kerala`?

**Comment by rarvin** [comment]
>
> Considering it would be used in the free search term field, what syntax
> would you propose? Something like user-pref:location:kerala?
>
Yes that would be good

>

**Comment by kevinpapst** [comment]
Create

**Comment by kevinpapst** [comment]
Advanced search filter are always a good idea, but nobody voted here, so closing
