### ISSUE TITLE
Question - How are active users identified in the dashboard view

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1125]
Currently the dashboard view provided one a birds eye view of the active user in the day, week month etc. What is the logic used to identify an active user in the system. Would just a login into the system be considered for the count being added as an active user or do that have to spend some time in kimai or initiate some timesheet tasks etc.

Is it possible for one to configure the time one has to sent on kimai to be considered as an active user. Like there are leads etc who just log into the system and use the tool for just analysis not tracking tasks. Is there any way of excluding the really time tracking users and users who are just logged into the platform.

**Comment by kevinpapst** [comment]
Kimai check the records for the chosen timerange and then counts the users.
Who is logged in nothing that Kimai knows, only the time of the last login is known.

But team leads should also work and have a running record, don't they?

**Comment by rarvin** [comment]
I haven’t checked with the team leads. It might the difficult to get details from them. Is there any way the admin user can log in as a team lead so that I can get to see what they get to see. I just have the admin user access and get to see the overall view. Can we have something like admin camouflaged as any other user bypassing the need for knowing the credentials of the users.

**Comment by rarvin** [comment]
If you could launch some plugins for usage statistics it would be good. Like time clocked in by each user by day, week month and the same view showing the stats for all other users, filters by customer, project activity, tags and other custom fields all of this would be nice.

**Comment by kevinpapst** [comment]
@rarvin statistics and reports will come, promised! 
But there are so many things around Kimai that need to be changed/added/fixed, it just needs some time...

**Comment by kevinpapst** [comment]
But one question back to you this time: you seem to have a large team of writing experts, is anyone of them able to translate Kimai into your language?
https://www.kimai.org/documentation/translations.html
Might be a nice addition, not only for your company...

**Comment by rarvin** [comment]
> Kimai check the records for the chosen timerange and then counts the users.
> Who is logged in nothing that Kimai knows, only the time of the last login is known.
> 
> But team leads should also work and have a running record, don't they?
@kevinpapst I have checked the dashboard of a teamlead and the dashboard view of the team lead list the statistics for all users, just like the admin user view. Thought I update you on this.

**Comment by rarvin** [comment]
> But one question back to you this time: you seem to have a large team of writing experts, is anyone of them able to translate Kimai into your language?
> https://www.kimai.org/documentation/translations.html
> Might be a nice addition, not only for your company...
India is a very big country and has around 29 states with most states having its own regional language, but in general Hindi is most spoken among all of the languages if you take percentage wise, but most southern states have next to 0% usage of Hindi. We are from the southernmost tip of India from a state called Kerala. The language used here is Malayalam and this language is very much limited to just this State which is around 3% of the population of India. Interestingly almost everyone in Kerala to an extent is literate in English and no one uses the Malayalam language within softwares or screens or computers, unless they are very old over 70's who need support in using computers itself. This is the only reason why we have not worked on the translations within the tool. Malayalam as a language is used widely as a language of communication but when it comes to usage of computers english is the dominant driving force. 

The other languages widely used in India is Hindi which almost no one in Kerala would be aware of and hence translating the tool screens text to Hindi would be very difficult for my team. I think if there are other users of Kimai from the Northern half of India where Hindi is the local language they might be able to help with the translations. If you need us to translate to Malayalam it can be done but I dont think practically there would be any takers once it is done. This is the only reason why I have not offered my assistance on translations into Malayalam. I hope you understand, if there is anything else that you need support with I am happy to help.

**Comment by kevinpapst** [comment]
Indian is actually the second most referring country to Kimai (according to Google). I knew that you are using different languages, but didn't knew that is is so diverse. 
3% is still half of the German population ;-) but people here are used to use all software in german and would complain if it was only available in English. Different countries, different cultures.
So you are used to English date and time formats as well, I guess?!

Sounds as if the Dashboard for team leads need improvements, then. I have so many ideas, but time is so limited ...

**Comment by rarvin** [comment]
@kevinpapst Yes Kevin, the data and time formats are the same its dd-mm-yyyy format and time is hh:mm and then we dont have daylight savings and GMT+5.30 is the timezone. Units users are meters, kilometers other like litres grams, kilograms etc, only thing different is the currency which is in rupees and we follow hundreds, thousands, lakh (100,000) and crores. 10lakh is one million. We have quiet a strong British influence with them ruling us for quiet some time. Interesting Kerala was never a colony of the british but we had very strong trading ties. Kerala was one of the few Princely states in India not under British occupation. If you have plans to visit Kerala please do let me know, I shall be able to help you out.
