### ISSUE TITLE
CSS not loading at all

### ISSUE THREAD

**Issue by phobos79** [kevinpapst/kimai2#1127]
Hello,

i'm going crazy to make V2 running, css don't get rendered.

here my conf. file:

> <VirtualHost *:80>
    ServerName tracking.ce.lan
    ServerAlias tracking.ce.lan

    DocumentRoot /var/www/kimai2/public
    DirectoryIndex /index.php

    <Directory /var/www/kimai2/public>
        AllowOverride All

        # Apache 2.2
        Order Allow,Deny
        Allow from All

        # Apache 2.4
        Require all granted

        FallbackResource /index.php
    </Directory>
    </VirtualHost>

> 

Php 7.2 apache 2.4, debian 9.9

all ok and site work, but no way to get rendered, css is reachable
![kimai2](https://user-images.githubusercontent.com/55578562/65310914-964dd400-db8f-11e9-9ecc-aadd3cd46a66.jpg)

![css](https://user-images.githubusercontent.com/55578562/65311007-c8f7cc80-db8f-11e9-8ed6-82d7868ab428.jpg)

i've other 6 sites on that server, no problem on all.... what's the hell happen with V2?

Thanks!

**Comment by phobos79** [comment]
Generated code for page
[view-source_tracking.ce.lan_en_timesheet_.pdf](https://github.com/kevinpapst/kimai2/files/3634886/view-source_tracking.ce.lan_en_timesheet_.pdf)

**Comment by kevinpapst** [comment]
Disable Pagespeed and retry

**Comment by phobos79** [comment]
wow.. it worked! really strange, it's the first time that pagespeed give me problems!

now all work fine 

THANKS A LOT KEVIN!

**Comment by kevinpapst** [comment]
Glad the problem was so easy to solve ;-)
