### ISSUE TITLE
Add standard / default values

### ISSUE THREAD

**Issue by mifigap** [kevinpapst/kimai2#1128]
Kevin, awesome product, it´s possible to add standard / default values (project and activity) to a customer?
When pressing on start at time tracking?
Also as an additional plugin in the shop.
Description:
Finish:
1. Start timetrack,
default is XY project
and
default is XY activity

Actually:
1. Start timetrack
2. Set project
3. Set activity

**Comment by kevinpapst** [comment]
Closing, as this duplicates #699 and duplicates #403 
Please leave a 👍 in the first post of these requests to upvote them

**Comment by kevinpapst** [comment]
And btw: thanks for adding your ideas!
