### ISSUE TITLE
XAMPP database

### ISSUE THREAD

**Issue by takte1** [kevinpapst/kimai2#1130]
Hello everyone !

I installed latest XAMPP version (7.3.9) on my PC, where I am running Kimai time tracking.
I extracted Kimai folder to C:\xampp\htcdocs\
Then I go to localhost http://localhost/kimai-release-1.3/public/ where I can login.
But the problem is when I want to use my database. I edited .env file and set 
`DATABASE_URL=mysql://root:mypassword@127.0.0.1/kimai` but when I go to website, there is just blank screen which means no connection to database. Does anyone knows how to connect kimai to localhost SQL database ?

**Comment by kevinpapst** [comment]
Yes, the documentation: https://www.kimai.org/documentation/installation.html
Did you create the database / run the installer AFTER you changed the database?

**Comment by takte1** [comment]
I have read the documentation, but I am doing that on Windows with XAMPP. I didn't actually install kimai, because if I go to http://localhost/kimai-release-1.3/ I see only filesystem, unless I click subfolder "\public". Before that I already create database named "kimai".

[https://imgur.com/QQYFJMR](url)

**Comment by kevinpapst** [comment]
Yep, but it doesn't matter if you use Linux, Mac or Windows (besides that you have to adjust how you call the scripts, maybe you need to call `php bin/console kimai:install -n`).

The installer creates the necessary tables in your database, you have to run it.

**Comment by takte1** [comment]
But can you tell me how to do that and where ? In XAMPP shell ?

**Comment by kevinpapst** [comment]
Sorry, don't know. Haven't used Windows in over 10 years...
