### ISSUE TITLE
Invoice view missing the eye option - the one used for excluding columns in the preview report

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1131]
Older version of kimai had an eye option where one could click and it opened up the list of columns that could be included or excluded in the invoice preview page. Before upgrading I had used this option and removed the description filed from my invoice preview screen and after the upgrade I have no way of bringing this column back to the invoice preview.

Where as other users who have not done this before are able to see all of the columns. The select deselect of columns using the eye option was quiet useful which is now missing. Kindly see if you can add this back to the invoice preview view.

**Comment by kevinpapst** [comment]
Ups, never thought about that LOL.
The setting is stored in a cookie, which you can delete. But I will re-add the "eye" to the screen.
