### ISSUE TITLE
custom fields - User Specific instructions or help fields for end user entry guidance 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1133]
Currently custom fields can be added and a default value can be assigned to them, but there is no option to provide some kind of guidance to the user using the tool as to what kind of data has to be entered into the fields. What would be great, is if a help text of some sort can be added along with the field, either within the same entry filed form space itself or just near it. 

Please find the attached screen shots which shows a kind of help text that is provided within a tool called Opnsense (opensource firewall). This kind of help text can be helpful to users. Thought I share this approach.

![Screenshot_20190921_204108](https://user-images.githubusercontent.com/50443902/65375251-df497980-dcb0-11e9-8be6-ec5b72656f86.png)
![Screenshot_20190921_204128](https://user-images.githubusercontent.com/50443902/65375252-e1133d00-dcb0-11e9-93ca-445a3f8845cb.png)

**Comment by kevinpapst** [comment]
Thats already possible in Kimai (see documentation). 
But I guess you want support for it in the plugin. In that case, this is the wrong repository ;-)

**Comment by rarvin** [comment]
@kevinpapst is this what you are referring to 
Attention: setLabel() and setOptions() will be added with 1.4. 

If this is what you are referring to I didnt know they existed before. I would raise a request in the other repository.

**Comment by kevinpapst** [comment]
Exactly. But no need to open an issue. 
I was quicker and already added that feature, along with others. 
Please have a look at the open PR in the plugin repository.

**Comment by kevinpapst** [comment]
Closing, as you will get everything with 1.4
