### ISSUE TITLE
Allow certain activities as not tracked for aggregration

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1134]
Currently in Kimai all activities under a project and customer are tracked while a time is started and this show us in all kinds of aggregration like mytimes etc. What would be great if some activities (maybe could be even global) which could be excluded from all kinds of tracking. The timers would run when a user starts a task against them but they have to be excluded from all kinds of aggregration so that they do not appear in mytimes or invoices, or summed up reports etc.

Also an option to show results with the summed up value including the excluded value if possible would be nice. This way it would be "total time including excluded tasks" and "Total time sans excluded tasks"

**Comment by zeroboioioy** [comment]
Not sure about the status here, but i was just asking myself if there is a way to exclude certain project tasks from counting against the project budget, like travel times for example.
currently i am helping myself by creating reports and selecting all activities except the one i don't want to be in the calculation.

**Comment by HeinzWuert** [comment]
Create special activities for  that and set **fees** to 0€.

**Comment by kevinpapst** [comment]
Kimai 1.14 introduced the billable state for each timesheet record.
This is the feature that you want.
In the future this should be configurable per activity/project => follow & vote for #2594
