### ISSUE TITLE
Direct email support from all HTML views like timesheet, invoice preview etc

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1135]
A new plugin has been created by a user which seems to provide the functionality to email directly from Kimai. Could this same functionality be extended to the core so that emailing support comes default to Kimai an an option and is present in all of the HTML view screens so that the view seen could be sent as an email.

For example the preview seen in the invoice screen or the filtered timesheet results etc.

This feature can help all Kimai users as this could avoid the difficult of copy pasting the results seen on screen. This could save lot of effort for end users and leads. 

Please see the the plugin that I am taking about.
https://gitlab.com/hmr-it/kimai2plugins/EmptyDescriptionCheckerBundle/blob/master/README.md

**Comment by kevinpapst** [comment]
Not planned for the core of Kimai, closing.
