### ISSUE TITLE
Enhance teams - to granularise grant access to activities also

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1137]
Currently a team can be created and it provided selected access to team leads and users to selected customers and projects. Can this granting of permissions be extended to activities also so that users can choose only selected activities from within an activity. 

Also can this allow only selected users in using the global activities and global projects also.

**Comment by christian-cgi** [comment]
I'd be happy as well to see this feature. We have a variety of projects/customers but some of them share same activity at same hourly rate etc. . For now, those activities are not assigned to any project, i.e. they are available to everybody, which sometimes leads to wrong selection of activity in time reporting. Restriciting access to these activities would avoid this.

**Comment by kevinpapst** [comment]
This was added in 1.10 - but please note: 
There is no good way to display that for now on the teams page, so the team permissions permissions can only be set from the activity detail screen and not from the team page.
