### ISSUE TITLE
Branding on FTP installation

### ISSUE THREAD

**Issue by roulious** [kevinpapst/kimai2#1140]
As i was unable to overcome the issue with the proxy configuration, i turned into the FTP installation ( see issue #1120 ). Is there a possibility to make my own Branding config?

I have created the local.yaml file with the following data as described [https://www.kimai.org/documentation/branding.html](url):

`kimai:
    theme:
        branding:
            logo: "https://www.kimai.org/assets/icon/apple-touch-icon.png"
            company: Acme University
            mini: AC
            title: Awesome!`

Unfortunately, it is not working/reading the file. 

Could you please assist or branding does not work on FTP Installations of Kimai2?

Regards

**Comment by kevinpapst** [comment]
You have to delete the cache folder manually at var/cache/prod/.
