### ISSUE TITLE
Start time change on a running activity not saving

### ISSUE THREAD

**Issue by yayitazale** [kevinpapst/kimai2#1141]
**Describe the bug**
Changing the start time to a running activity has no effect when you click on save. You have to stop it in order to change the start time. 

**To Reproduce**
1. Create or re-take an activity
2. Click on 'Actions -> Edit'
3. Modify the start time to the past or future
4. Hit enter or click save

**Desktop/Smartphone**
 - Browser Firefox
 - Version 69.0.1

**Additional context**
 - Kimai version 1.3 stable
 - PHP version

**Comment by kevinpapst** [comment]
Not reproducible on demo for me

**Comment by yayitazale** [comment]
It's true, no error on demo....

??

**Comment by kevinpapst** [comment]
Logfile???

**Comment by kevinpapst** [comment]
No feedback, closing
