### ISSUE TITLE
% for activities and projects

### ISSUE THREAD

**Issue by phobos79** [kevinpapst/kimai2#1151]
**Is your feature request related to a problem? Please describe.**
Kimai work well, i think that this should be a useful new feature

**Describe the solution you'd like**
modify excel exportation to calculate the % rates for projects and activities and put it in the sheet

**Describe alternatives you've considered**
modify the excel export related file (i ask which is), only alternative is to manually calculate after

**Additional context**
no additional context

**Comment by phobos79** [comment]
Hello,
could someone confirm me that the file that "make" the excel is
/src/Renderer/AbstractspreadsheetRenderer.php?

**Comment by kevinpapst** [comment]
The base class for all spreadsheet exporter is: 
src/Export/Renderer/AbstractSpreadsheetRenderer.php

**Comment by kevinpapst** [comment]
As the export dumps timesheets, not projects... I will close this.
When I find the time to work on a reporting extension, this could be added.
