### ISSUE TITLE
${entry.activity} doesn't work in docx invoices

### ISSUE THREAD

**Issue by PontusO** [kevinpapst/kimai2#1156]
**Describe the bug**
I need to have both ${entry.activity} and ${entry.description} on each time entry on the invoice. When I enter ${entry.activity} I get a 500 error thrown. No project or activity is selected when generating the invoice.

**To Reproduce**
1. Modify the docx template invoice (or create a new one) and enter ${entry.activity} in the entry table cell.
2. Make sure you have a invoice template selecting the docx you modified.
2. Click on "Print" to generate the invoice
3. See error

**Logfile**
Sorry no logfile available yet.

**Screenshots**
![kimai2-1 3-error](https://user-images.githubusercontent.com/981692/66194129-26157700-e694-11e9-97b5-9604629e7aaf.png)

**Additional context**
 - Kimai version: 1.3
 - PHP version 7.2

**Comment by kevinpapst** [comment]
Just tried (with 1.4) and it works.
Try this DOCX: [company.docx](https://github.com/kevinpapst/kimai2/files/3690931/company.docx)

**Comment by PontusO** [comment]
Thanks, I will check this.

**Comment by PontusO** [comment]
Tested and it works as expected on 1.4, thank you.
