### ISSUE TITLE
24h time-format instead of AM/PM time-format

### ISSUE THREAD

**Issue by randomev** [kevinpapst/kimai2#1159]
I would like to have 24h times instead of AM/PM times across all the interface.

**Comment by kevinpapst** [comment]
Kimai is 24 by default, am/pm has to be activated manually.

**Comment by randomev** [comment]
Strange as for some reason ours shows AM/PM. Also date format is non local, eg. seems to be MM-DD-YYYY in reports whereas our local would be DD.MM.YYYY. I remember that Kimai V1 was in 24h format. Where could we check that our configuration is ok ?

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/translations.html#12-hour-format

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/configurations.html

**Comment by kevinpapst** [comment]
No feedback, closing
