### ISSUE TITLE
Dashboard view not getting updated properly with the work time for the day - 'working hours today' 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1163]
#1023 was fixed by #988 and #987 but a user has reported that the problem is still present. Hence sharing the screen shots.
![Screenshot1](https://user-images.githubusercontent.com/50443902/66639567-ae67bf00-ec34-11e9-8fa8-3c718bc3b5f0.png)
![Screenshot-2](https://user-images.githubusercontent.com/50443902/66640618-eb34b580-ec36-11e9-9a99-63cb47b8e219.png)

If you look at the screenshots the time from 04:28 to 05:25 has been missed in the "working Hours Today"
The user is in IST time zone and this is set in preferences also and the server follows UTC
This is not a major issue, but raising it as reported by the user.

**Comment by kevinpapst** [comment]
Just to rephrase: the 1,5 hours look correct in the chart, so I assume you took the screenshot on the 03 October and mean the number of 00:32 is incorrect?

**Comment by rarvin** [comment]
Correct the number of 00:32 is incorrect.
