### ISSUE TITLE
Error 500 When I click on "My profile"

### ISSUE THREAD

**Issue by organ2** [kevinpapst/kimai2#1164]
Hey. We used kimai 0.8.1 built on the basis of docker. Today updated to version kimai / kimai2: apache-debian-1.4.1. Аfter updating i got an error.

1) When I click on "My profile" I get an error:
![My profile](https://user-images.githubusercontent.com/21170908/66656140-1246b380-ec46-11e9-8fc7-8101bd0fc97f.png)

There is nothing in the log file (var/log/prod.log).

**Comment by kevinpapst** [comment]
Are you sure the log file can be written by php/webserver?

Without any log messages I cannot help.
Check your Webserver / php log if there is something mentioned.

**Comment by kevinpapst** [comment]
oh wait, docker image. sorry, I cannot help. 
afaik there are some permission issues, please go to the docker repo instead: 
https://github.com/tobybatch/kimai2

**Comment by fizgig10** [comment]
Any chance you can provide a couple of steps for how to go to the "docker" image?  I'm in the same boat now.

**Comment by kevinpapst** [comment]
Go to the docker repository means "follow the link": https://github.com/tobybatch/kimai2

I cannot help without logs and I am not using nor supporting docker.

**Comment by kevinpapst** [comment]
Docker problem, closing here
