### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Regnalf** [kevinpapst/kimai2#1165]
Hi kevin,
it's been a while i've trying to get kimai2 running on my shared host.
After the problems i had (see https://github.com/kevinpapst/kimai2/issues/494)
i successfully done a composer install for version 1.4.1

All installation steps went fine, no errors, all database tables are there, even the first user was there in database. The login screen appears, but i still could not login. The "base_dir" option was off and php-error was on.
There are no php-errors or errors in the server log file. And also a CSRF error is not present.

Then only thing i could not set up in the installation process was the change of the owner of folder to www-data. It has the group www-data, but owner is set to my customer number on the host.

Example:

    .env    -rwxrwxr-x    e12345 www-data

Cold this be the problem?

**Comment by kevinpapst** [comment]
On shared hosts, you normally don't have to change permissions at all, only if you run into problems.
Check if there is anything in the log file at var/log/prod.log

**Comment by RayCulp** [comment]
If it's not necessary on shared hosts, maybe it would be a good idea to mention that in the installation guide.  I took your advice, got the prerequisites like Git and Composer working on my shared host, installed Kimai that way, and carried out all of the steps described in the installation guide, including "chown -R :www-data .", but all that did was generate "permission denied" errors. Thankfully, it seems to be working anyway. :-)

**Comment by kevinpapst** [comment]
Thanks for the input @RayCulp 
It is impossible to document all possible cases, but I added a sentence about shared hosting in installation & update docs.

**Comment by Regnalf** [comment]
there is no prod.log under /var/log/

i have only this server log from access.log
`91.115.43.84 - - [12/Oct/2019:18:15:34 +0000] kimai2.gg6.at "GET / HTTP/1.1" 302 522 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
91.115.43.84 - - [12/Oct/2019:18:15:34 +0000] kimai2.gg6.at "GET /de/homepage HTTP/1.1" 302 704 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
91.115.43.84 - - [12/Oct/2019:18:15:34 +0000] kimai2.gg6.at "GET /de/login HTTP/1.1" 200 1578 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
91.115.43.84 - - [12/Oct/2019:18:15:35 +0000] kimai2.gg6.at "GET /build/fonts/glyphicons-halflings-regular.448c34a5.woff2 HTTP/1.1" 304 110 "https://kimai2.gg6.at/build/app.4bdd4f2d.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
91.115.43.84 - - [12/Oct/2019:18:15:35 +0000] kimai2.gg6.at "GET /manifest.json HTTP/1.1" 200 653 "https://kimai2.gg6.at/de/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
91.115.43.84 - - [12/Oct/2019:18:15:46 +0000] kimai2.gg6.at "POST /de/login_check HTTP/1.1" 302 630 "https://kimai2.gg6.at/de/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
91.115.43.84 - - [12/Oct/2019:18:15:46 +0000] kimai2.gg6.at "GET /de/login HTTP/1.1" 200 1577 "https://kimai2.gg6.at/de/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
`
No php error, no csrf error, no password/user wrong message or something else.

**Comment by kevinpapst** [comment]
`/var/log/` is not the same as `var/log/prod.log`. Missing initial slash means => local to your Kimai installation.

If you get a CSRF error, that is likely a permission problem. Show me also `ls -la var/`.

**Comment by Regnalf** [comment]
> /var/log/ is not the same as var/log/prod.log. Missing initial slash means => local to your Kimai installation.

actually, i checked both, no prod.log in either location

this is what `ls -la var/` show me

    insgesamt 28
    drwxrwxr-x  7 e24498 www-data 4096 Okt 12 07:59 .
    drwxr-xr-x 14 e24498 www-data 4096 Okt 12 08:20 ..
    drwxrwxr-x  4 e24498 www-data 4096 Okt 12 07:59 cache
    drwxrwxr-x  2 e24498 www-data 4096 Okt 12 07:59 data
    drwxrwxr-x  2 e24498 www-data 4096 Okt 12 07:59 log
    drwxrwxr-x  2 e24498 www-data 4096 Okt 12 07:59 plugins
    drwxrwxr-x  3 e24498 www-data 4096 Okt 12 08:37 sessions

**Comment by kevinpapst** [comment]
Ok, first: you should not change the owner just the group.
But in your case, I assume that you should not change user or group.

What kind of permission do other directories (outside the Kimai directory) have?
Try to change the group back to the normal value (I guess `e24498`).

Is anything inside the session directory after you tried to login?

**Comment by Regnalf** [comment]
i cant change the owner, its forbidden anyway. 
after a fresh install with the `git clone` command, the owner and the group for all files and folder in it is the same like this:

     drwxr-xr-x 14 e24498 e24498  4096 Okt 12 08:20 kimai2-gg6

other folders, like the old kimai v1 has this permission

     drwxr-xr-x 12 e24498 www-data   4096 Jän 10  2019 kimai-gg6

if i create a folder over ssh (or filezilla) the group and the owner is the same e24498:

    drwxr-xr-x  2 e24498 e24498     4096 Okt 12 20:14 test

if want to create a folder with www-data i used the web-ftp function of my webhoster.  so i `git clone` a version from kimai2 to a temp folder, and then copied it with the web-ftp to the desired one. that's how i got www-data to all of the sub files and folders.

the html folder above my kimai installation has this permission

    drwxr-x---   8 e24498   www-data  4096 Okt 12 20:21 html

> Is anything inside the session directory after you tried to login?

no, not at all

_Should i try a fresh install without changing the group?_

**Comment by kevinpapst** [comment]
Well yes, give it a try.

**Comment by Regnalf** [comment]
ok, i removed directory and database. 
made a fresh install, no errors. changed file permissions, except `chown`

var folder:

    insgesamt 28
    drwxrwxr-x  7 e24498 e24498 4096 Okt 12 20:33 .
    drwxr-xr-x 14 e24498 e24498 4096 Okt 12 20:34 ..
    drwxrwxr-x  4 e24498 e24498 4096 Okt 12 20:36 cache
    drwxrwxr-x  2 e24498 e24498 4096 Okt 12 20:33 data
    drwxrwxr-x  2 e24498 e24498 4096 Okt 12 20:33 log
    drwxrwxr-x  2 e24498 e24498 4096 Okt 12 20:33 plugins
    drwxrwxr-x  3 e24498 e24498 4096 Okt 12 20:39 sessions

1 user in database after the `kimai:create-user`

still cannot login :-(
no error message except CSRF-Token if i try to register a new user

**Comment by kevinpapst** [comment]
I know that Kimai works as expected, your environment has some flaws that I cannot help with without logs.
Maybe you should ask your hoster support. Don't they provide a PHP error log?

**Comment by Regnalf** [comment]
they do provide an error logs!
but as a wrote above. No errors in error.log, php-error.log or php_slow.log. just entries in the access.log

this is the php-info from my server:
[PHP 7.3.7 - phpinfo().pdf](https://github.com/kevinpapst/kimai2/files/3721501/PHP.7.3.7.-.phpinfo.pdf)

open_basdir is disabled for the kimai2-gg6 domain. and cache is set on "redis".

i will try to contact my hoster next week.

**Comment by kevinpapst** [comment]
> open_basdir is disabled for the kimai2-gg6 domain and cache is set on "redis".

What do you mean by that?

**Comment by Regnalf** [comment]
> What do you mean by that? I mean the Redis part

open_basdir and cache setting to redis is the recommended settings from my host and both are active for the general php 7.3 settings for all content on this server:

![php7-3_general_settings](https://user-images.githubusercontent.com/43412166/66712244-079d3300-ed9a-11e9-8ab4-e17804776cbe.jpg)

in the subdomain settings, i can overwrite the "open_basdir" option to disable it. and there is an OPcache option i think it is explained here: https://www.easyname.at/de/support/hosting/183-warum-erhalte-ich-die-warnung-zend-opcache-api-is-restricted

![kimai2-gg6_subdomain_setting](https://user-images.githubusercontent.com/43412166/66712261-35827780-ed9a-11e9-939c-e94db72ca846.jpg)

**Comment by kevinpapst** [comment]
Disable session cache redis and it will work.

**Comment by Regnalf** [comment]
### YOU WERE ABSOLUTELY RIGHT!!!!!!!  👍 :-)
I'm in now

It seems not everything that is recommended, it truly is! Maybe you could mention it too in the documentation for shared host info members.

**Comment by kevinpapst** [comment]
Happy that it works now: https://www.kimai.org/donate/
