### ISSUE TITLE
Configure rounding of time

### ISSUE THREAD

**Issue by krabina** [kevinpapst/kimai2#1171]
**Is your feature request related to a problem? Please describe.**
The "problem" is that users have to select exact times. The accuacy of "Work starting at 10:24" is not needed in our case, on the contrary.

**Describe the solution you'd like**
Being able to configure that the time input form will show exact times, or 15 or 30 minute intervals. This does also make the selectbox on mobile view much smaller.

In our case, 30 Minute intervals are needed: so If a user starts at 10:24, he will select 10:30, if a user starts at 10:37, he still will select 10:30 whichi is fine.

**Comment by kevinpapst** [comment]
You could use rounding until this feature is available: 
https://www.kimai.org/documentation/timesheet.html#rounding-of-begin-end-and-duration

**Comment by kevinpapst** [comment]
I believe this was added with 1.14 - there are new system configurations to configure the dropdowns and duration select.
