### ISSUE TITLE
Query API by custom fields / meta fields

### ISSUE THREAD

**Issue by cbellersen** [kevinpapst/kimai2#1174]
**Is your feature request related to a problem? Please describe.**
We are tracking issues in an issue tracking system (mantis). I configured a custom field in Kimai ("mantis_id" as integer field) in which we save the issue ID. It would be great, if I could calculate the total time spent on an issue in an external script and write the result back to Mantis. This way we can monitor, how long each issue was worked on. 
In order to do so, I would need to be able to retrieve all timesheet objects from Kimai for a given issue ID. 

**Describe the solution you'd like**
It is already possible, to add parameters such as "user", "project" or "begin" to a query to the /api/timesheets API endpoint. It would be great, if custom fields could also be used as parameters. E.g. "mantis_id": 12345
Since custom fields can bei used not only for timesheets, but also for customers, projects, activities and users it would be consequent to add custom field querying to these API endpoints as well.

**Describe alternatives you've considered**
I considered retrieving all timesheet data for a given period (e.g. last 30 days). However, this is not feasible, because sometimes very old issues are reopened and I would have add timesheet records from long time back to calculate the correct total time spent.

**Comment by kevinpapst** [comment]
Want to sent in a PR?

You would need to add a new parameter:
https://github.com/kevinpapst/kimai2/blob/master/src/API/TimesheetController.php#L126

Something like (untested!)
```
* @Rest\QueryParam(name="term", strict=true, nullable=true, description="Free search term")
```

And then a couple of lines below:

```php
if (!empty($term = $paramFetcher->get('term'))) {
    $query->setSearchTerm(new SearchTerm($term));
}
```


The same needs to be done for the other API controllers as well.

**Comment by cbellersen** [comment]
I am deeply sorry but I am not able to send a PR. I am not a developer :-( 
However I could sponsor this feature. How much time/money do you think you would need?

**Comment by kevinpapst** [comment]
> if I could calculate the total time spent on an issue in an external script and write the result back to Mantis. 

Well, you made it sound as if you were a developer ;-)

As written above: it's not that much work. If you use it for your companies business, go ahead and pledge what you think Kimai is worth.
