### ISSUE TITLE
Visual Studio Code Extension? 

### ISSUE THREAD

**Issue by TobiasDev** [kevinpapst/kimai2#1175]
**Is your feature request related to a problem? Please describe.**
I keep forgetting to turn on the time-tracker before I start coding, and of-course I keep forgetting to turn it off as well. :D However, I noticed that I'm quite good at keeping the tracking in check when the tool is directly inside the editor I use (coder, so in this case it is Visual Studio Code). 

At the moment I have another external tool and then I manually have to add it into Kimai, so I was wondering if it would be possible to get a Visual Studio Code Extension for Kimai? Rather than me having to manually go in and add the time I was working into Kimai, I can turn a timer on for the specific task on and off directly from Visual Studio Code.

**Comment by kevinpapst** [comment]
I don't use Visual Studio. 
But if you have experience with creating a plugin for it, I can help with the Kimai integration.

**Comment by TobiasDev** [comment]
Hmm, I'm never done any Visual Studio plugin, I will look into it and see how it is done.

**Comment by infeeeee** [comment]
You can write vscode extensions in typescript and javascript. Maybe you just have to modify my command line client written in javascript to work inside vscode: https://github.com/infeeeee/kimai2-cmd. At least you don't have to write everything from scratch. I can help testing as vscodium is my editor of choice. I also planned creating a vscode extension, but I don't have time for that nowadays.

(Also until the extension isn't available you can use kimai2-cmd from the terminal inside vscode)

**Comment by TobiasDev** [comment]
Ah. Thanks! I will definitly look into that

**Comment by kevinpapst** [comment]
@TobiasDev open a feature request if you want to work on it, I am sure someone could assist
