### ISSUE TITLE
Invoice editor: Wysiwyg

### ISSUE THREAD

**Issue by partoneoftwo** [kevinpapst/kimai2#1178]
User Story:
As a user, I can not edit the fields which are fetched when printing and generating outputs from Kimai2. 

As a user I don't have the capacity to become proficient in the entire templating engine and macro set, just in order to nicely customize the desired output. I find the macros used throughout kimai2 too complex for me to learn everything about. 

**Is your feature request related to a problem? Please describe.**
As a user I need to be able to make edits and restructure output quickly. Quickly as in, last minute before I send my invoices.

As a user it is frustrating to have to read the codebase and try to understand and or remember how the templating and macros work.

**Describe the solution you'd like**
A Wysiwyg editor for any output mode.

**Describe alternatives you've considered**
I have considered using Odoo instead of Kimai2, but I really like Kimai2.

**Additional context**
No additional context.

**Comment by kevinpapst** [comment]
https://grapesjs.com/docs/#what-is-grapesjs

**Comment by kevinpapst** [comment]
This is so complicated, that I will not support it for the next time. 
Possible in the future. Closing for now, as there are way to many pending feature requests
