### ISSUE TITLE
How to fill the timesheet  without pressing the space

### ISSUE THREAD

**Issue by organ2** [kevinpapst/kimai2#1187]
Hello. In the old version of kimai when I created the timesheet I selected the "Customer" - typed the text - pressed the tab - typed the "Project" - pressed the tab - typed "Activity" and so on.

In kimai 1.4.1 to start printing now I need to press the space, i.e. now
I select the Client - type the text - press the tab - press the space - type the "Project" and so on...

Pressing the space is a bit uncomfortable. Can I make it so that after clicking TAB I can immediately fill in a new field?

**Comment by hpeyerl** [comment]
+1 Yes please.

(I speak many things; unfortunately .js is not one of them).

**Comment by kevinpapst** [comment]
BTW: you can still disable the javascript select if you don't need its functionality (see settings / /theme / Type of select-boxes in forms)

**Comment by hpeyerl** [comment]
Oh I didn't realize I could select "".  It looked like "Javascript" was the only option.

After selecting "", the behavior is positively perfect.  I retract my "+1".

**Comment by kevinpapst** [comment]
@hpeyerl if you want to +1 any feature, please add the 👍 reaction on the initial posting (the smiley symbol)

**Comment by hpeyerl** [comment]
Apparently I also don't speak Emoji very well. Thanks. :)

**Comment by kevinpapst** [comment]
An extremly long time ago this issue was opened and now it will be soled with the next major release.

You can see the new component at work following the link in the [milestone description](https://github.com/kevinpapst/kimai2/milestone/38). I am closing this issue, even if the new version is not yet released.
