### ISSUE TITLE
Invoice Generator by Date + consecutive numbering

### ISSUE THREAD

**Issue by Mikesch-mp** [kevinpapst/kimai2#1189]
**Describe the solution you'd like**
The date invoicenumber generator is not enough for german finance office. If you send more then one invoice on the same day, you have to add a consectuive number to the generated invoicenumber by date.

**Describe alternatives you've considered**
At the moment you can only add it manualy to the generated invoice.

**Additional context**
A invoice generator that stores how many invoices a re printed per day, so you get a invoice number that looks like 20191021-1, the next gets 20191021-2 and so on. for the finance office it doessnt matter if you have holes in your numbering, but you need a unique invoice number if you send out many invoices on the same date.

**Comment by kevinpapst** [comment]
@Mikesch-mp can you help testing the new invoice features? See #1541 
It includes an archive for all generated invoices (together with a payment status) and a configurable invoice format featuring incrementing numbers (per day, per month, per year, all time) and date modifiers.

**Comment by Mikesch-mp** [comment]
Going to test it this weekend, thanks for making it possible <3

**Comment by Mikesch-mp** [comment]
It looks good :) cant wait to get this feature. I like also that you implemented an archive and options to see if it is pending and if it is paid.
With the archive i miss only an option to delete/edit an invoice. Sometimes i have to correct an invoice for a customer, because of typos or missing entries.

**Comment by kevinpapst** [comment]
Editing is not possible and I don't think that it is necessary, as you have the "Print preview"!?!
If you have to change it later on, you have to create a "replacement invoice" anyways 😁 
And currently I don't store which items were included in the invoice, so its technically not yet possible.

But deleting or setting an invoice to "invalid" might be an option for the next version (lets gather some feedback first).

**Comment by kevinpapst** [comment]
Thanks for testing!
