### ISSUE TITLE
Minor cosmetic bug: On "Grant access to projects", "Reset" does not reflect

### ISSUE THREAD

**Issue by Lusus** [kevinpapst/kimai2#1190]
Description:
A minor cosmetic issue: As admin under Teams, Edit, on the "Grant access to projects" form, after modifying Projects and then clicking "Reset", the "Project" control does not refresh to display the reset state. But, after adding new items again, it is clear that the "Reset" did work.

1. As Admin, go to 'Teams'
2. Click on 'Actions' for a team, select 'Edit'
3. In the form "Grant access to projects", select projects to add
4. Press "Reset", the contents remains unchanged.
5. Select another project to add, see that the first modifications were indeed reset

Please complete the following information if this seems to be a frontend issue:
 - OS: Linux
 - Browser Firefox 69, Chromium 77
 - Kimai Version 1.4.2, but could also be reproduced on the Development Demo

**Comment by kevinpapst** [comment]
Thanks for the info! 
Actually I rely on the browsers "reset" function. If that does not work properly with the used javascript elements, I will have to check if we can implement a simple workaround.
