### ISSUE TITLE
Avatar url broken

### ISSUE THREAD

**Issue by daesters** [kevinpapst/kimai2#1196]
**Describe the bug**
The avatar is a nice new feature. The problem is, when kimai is installed as subfolder of the top level domain, e.g example.com/kimai2. Then, avatars won't be shown, because the url will resolve in example.com/avatars/<hash>.png instead of example.com/kimai2/avatars/<hash>.png

**To Reproduce**
1. Go to example.com/kimai2/de/admin/user/
2. You won't see the avatars, only broken images of the users
2. Right-Click on one of the broken images
4. You will get to an url, like example.com/avatars/<hash>.png
5. Insert 'kimai2', like example.com/kimai2/avatars/<hash>.png
6. Avatar will show up.

**Additional context**
 - Kimai version kevinpapst/kimai2 | 1.4.2.0@de533e7031ae194b35f6a638cd95f5c94c516796
 - PHP version  7.3.1

**Comment by kevinpapst** [comment]
Hi @daesters , thanks  for letting me know!
I have no subdirectory installation, any chance you could test the changes from the PR #1201 ?
I cannot verify if they work properly, all I can say is that they still work as before for me in a root folder installation.

**Comment by daesters** [comment]
Hi @kevinpapst 
Everything works now with v1.5, PR #1201 fixed the problem.
Thank you very much

**Comment by kevinpapst** [comment]
Thanks for your feedback, good to hear!
