### ISSUE TITLE
Create password checking so that users do not use simple passwords

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1197]
Currently Kimai allows for user to create very simple passwords, this can be very easy to crack by dictionary attacks etc. Could you please see if password checking can be enabled into Kimai so that simple passwords are not allowed, or when passwords are being generated some kind of cryptic passwords are suggested by Kimai itself, like by using the pwgen command in linux.

**Comment by kevinpapst** [comment]
Seems password validation was broken in between the releases. 
Kimai now(with 1.10)  requires minimum 8 character, both for password and API token ... and there is a new test that makes sure this will never break again.

There is always "a fine line" between security and usability. I'd say the Kimai login should always be the last line of defense. 
So there should be some kind of brute force prevention in place as addition to the Kimai login page.

Not sure if 8 character is enough for you.
If you need more than these 8 character, please open a new issue and add more details about your requirements.
