### ISSUE TITLE
Redirection of "Show all record" link fails on a servername alias.

### ISSUE THREAD

**Issue by jacoblanco** [kevinpapst/kimai2#1199]
**Is your feature request related to a problem? Please describe.**
Our server hostname is an alias (example: server1.example.com pointing to tracker.example.com) for many reasons we need that nameserver configuration.
Everything is working like a charm except one single link. This link location is at the left side of user icon. Three point --> "Show all records". If we click on that link redirects to http://server1.example.com:8001/en/timesheet instead http://tracker.example.com/en/timesheet

**Describe the solution you'd like**
We need to a fix or a workaround to point this link to the right place.

**Additional context**
Kimai version: 1.4.2

**Comment by kevinpapst** [comment]
Hi @jacoblanco - any chance you can test the changes from the PR #1200 to see if that fixes <our problem? I have no similar setup to verify it.

**Comment by jacoblanco** [comment]
Hi @kevinpapst I will try asap. Thanks so much. Best regards.
