### ISSUE TITLE
The user list does not appear in the drop-down list of users

### ISSUE THREAD

**Issue by organ2** [kevinpapst/kimai2#1203]
Hello.
I want to do an export. When I click on the users field in the drop-down list, users do not appear. The user "test" has all rights. This happens if the user “test” has the role of “Teamlead” or “User”. If I give the role of "Administrator" or "System-Admin" and try to export, users appear in the drop-down list.

![image](https://user-images.githubusercontent.com/21170908/67770869-46084280-fa68-11e9-8d45-508129638d9e.png)

![image](https://user-images.githubusercontent.com/21170908/67770854-3d177100-fa68-11e9-8b2a-885092ec9fba.png)

![image](https://user-images.githubusercontent.com/21170908/67770903-53253180-fa68-11e9-82b4-c9631b5e2e28.png)

**Comment by kevinpapst** [comment]
Users and team leads can only export data for team members. Is the user "test" in a team?

**Comment by organ2** [comment]
No, we don't have teams.

**Comment by kevinpapst** [comment]
I am not sure if that will fix it, but you could try to create a team and add some users to it (including the user that should do the export).
Then check if the select box is still empty.

**Comment by organ2** [comment]
When I create the team, add the team lead and team members, users appear in the drop-down list. Thank you for explaining how it work.

**Comment by kevinpapst** [comment]
👍 This way you can control which user can see which data. I am closing, seems to be solved.
