### ISSUE TITLE
Documentation: Clarify what "BC break" means

### ISSUE THREAD

**Issue by 1977er** [kevinpapst/kimai2#1206]
Reading UPGRADING documentation you see alot of "possible BC breaks". Unfortunately the abbrev. "BC" is never explained.

**Comment by kevinpapst** [comment]
BC = Backward compatibility
So things that might change and disturb users or break stuff (in case of plugins).

Or was that a suggestion to explain it in the file?

**Comment by kevinpapst** [comment]
I changed the wording, so its hopefully less confusing for users. 
Thanks for the feedback!
