### ISSUE TITLE
Role teamlead cannot filter export by user

### ISSUE THREAD

**Issue by christian-cgi** [kevinpapst/kimai2#1211]
**Describe the bug**
A user, being member of team test1 and having role teamlead, cannot filter export by user.

**To Reproduce**
1. Create Team tone with users uone, utwo, uthree. Assign role teamlead to uone and utwo. In team-administration, assign teamlead  to uone.
2. Login as uone, go to export and click on user. uone can filter by user.
3. Login as utwo, go to export and click on user. utwo cannot filter by user.

**Logfile**
n.a.

**Screenshots**
n.a.

**Desktop/Smartphone**
n.a.

**Additional context**
I'm not sure if this is a bug. From my understanding of the documentation of role teamlead, it is.
At least it would be nice if someone else but the assigned teamlead could do the export per member of a team.
From documentation:
Teamlead: can see all un-privileged contents and all contents assigned to his teams. Team specific contents can be managed for all teams where this user is the Teamlead.

**Comment by kevinpapst** [comment]
utwo can only filter by user for teams where he is the teamlead (not the role, but the actual lead of a team - here tone and not utwo).
Everything else would be a breach of responsibility.

**Comment by kevinpapst** [comment]
Admins and Super admin can see all data.
There is a feature request that asks for multiple teamleads, that could help in your situation.

Closing, as I don't see any todo here and no feedback was provided.
