### ISSUE TITLE
Timeline for projects

### ISSUE THREAD

**Issue by christian-cgi** [kevinpapst/kimai2#1212]
**Is your feature request related to a problem? Please describe.**
Extended access control for projects/activities:
Projects (and related activities) should not be available in timesheets creation before the project starts and after it finishes. Currently we assign these projects to an empty team to make them unavailable for everybody. This requires manual work on time. I would prefer a more comfortable solution.

**Describe the solution you'd like**
An automatism that validates/invalidates a project for timesheet creation. Preferably by start/end dates

**Describe alternatives you've considered**
Assign projects to empty team to make them unavailable.

**Additional context**
n.a.

**Comment by kevinpapst** [comment]
Yes, good idea!
