### ISSUE TITLE
Timeline for projects/activities in timesheets

### ISSUE THREAD

**Issue by christian-cgi** [kevinpapst/kimai2#1213]
**Is your feature request related to a problem? Please describe.**
Usually project's activities are done within a certain timeframe. Users should be able to create/adjust activities in timesheet within that timeframe, but not outside. The timeframe should not limit the date of creation/adjustment, as this might be done after the project's activity already finished.

**Describe the solution you'd like**
Assign a timeline to project/activity. Users allowed to create start/end date of timesheet only within the project/activity timeline.

**Describe alternatives you've considered**
Setup external checkup of timelines. Not very promising....

**Additional context**
n/a

**Comment by kevinpapst** [comment]
There is a project start and end date now available with 1.7.
