### ISSUE TITLE
Calendar view font is resulting in unreadable entries

### ISSUE THREAD

**Issue by jaapcrezee** [kevinpapst/kimai2#1215]
**Describe the bug**
Calendar view font is resulting in unreadable entries.

**To Reproduce**
Select a light color as activity color and go to calendar view.

**Screenshots**
![font](https://user-images.githubusercontent.com/5526423/68019446-0fb30900-fc9c-11e9-8c78-7c385d0b0214.jpg)

**Desktop/Smartphone**
Linux Chromium

**Comment by kevinpapst** [comment]
Any idea how to fix that? Choosing a dark font will result in unreadable entries for dark colors.

**Comment by jaapcrezee** [comment]
Can we also have a configurable font color for activities next to the "background" color?

**Comment by kevinpapst** [comment]
Hm, probably we could define a usable set of colors (foreground = font and background = currently used color). Then selections can only be made on this combination.

But I was actually hoping for a CSS solution.

**Comment by kevinpapst** [comment]
Tried the css rule `mix-blend-mode: difference` which could work, but it looks crappy on some colors...

**Comment by jaapcrezee** [comment]
Can it be made conditional based on user settings?

**Comment by kevinpapst** [comment]
No, you can use CustomCSS Bundle if it works for you. But I wait until someone comes up with a better solution.

**Comment by kevinpapst** [comment]
@jaapcrezee found a solution - it is basically calculating whether it is a dark or light color and then either using black or white as font color. Its coming with [this PR](https://github.com/kevinpapst/kimai2/pull/1962) and you can test it at https://demo-branch.kimai.org/en/calendar/ with eg. `susan_super` / `kitten` and [other accounts](https://www.kimai.org/demo/).

**Comment by jaapcrezee** [comment]
![perfect](https://user-images.githubusercontent.com/5526423/92706701-059a7600-f355-11ea-975c-f309c597c359.jpg)
Looks very readable now, good! Thanks.

**Comment by jaapcrezee** [comment]
@kevinpapst see above.

**Comment by kevinpapst** [comment]
thanks for re-testing!
