### ISSUE TITLE
API auth possibly not working?

### ISSUE THREAD

**Issue by hpeyerl** [kevinpapst/kimai2#1217]
Just installed Kimai this morning.  Am able to use the web interface no problem and then bought the Android app from Google Play (for Kimai2).   

The App isn't able to authenticate with the API.  Currently testing on port 80 so I can diagnose it.  My username is "hpeyerl" and I generated an API token of "mumble".  I put that into the app and requests to /api/ping are getting 404.

If I tcpdump, I do see:

```
	GET //api/ping HTTP/1.1
	Host: kimai.beer.org
	Connection: keep-alive
	Accept: application/json, text/plain, */*
	X-AUTH-TOKEN: mumble
	X-AUTH-USER: hpeyerl
	User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; XT1635-02 Build/OPNS27.76-12-22-9; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36
	Accept-Encoding: gzip, deflate
	Accept-Language: en-US
	X-Requested-With: de.hmrit.kimai2app
```

Which suggests the app is doing the correct thing.  I then thought I'd try curl:

```
zoe-2 ~ $ curl --header "X-AUTH-USER: hpeyerl" --header "X-AUTH-TOKEN: mumble" http://kimai.beer.org/api/ping
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

I figured I'd dig into mysql and see if I could get anywhere with that:

```
mysql> select username,salt,api_token from kimai2_users;
+----------+---------------------------------------------+---------------------------------------------------------------------------------------------------+
| username | salt                                        | api_token                                                                                         |
+----------+---------------------------------------------+---------------------------------------------------------------------------------------------------+
| hpeyerl  | k3rAxcMiZ1EMQUvKPEi/D3b1YiDGr0tasdfs63h7wH4 | $argon2id$v=19$m=65536,t=4,p=1$Wb5+M78SMnNS15bCbC13QA$jPzJrulCm3kat93FmvM5Ve9dEOwywpQXwE0+kpfj4LE |
```

Then I thought I'd try argon2 from the command line:

```
echo "mumble" | argon2 k3rAxcMiZ1EMQUvKPEi/D3b1YiDGr0tasdfs63h7wH4 -id  -m 16 -t 4
Type:		Argon2id
Iterations:	4
Memory:		65536 KiB
Parallelism:	1
Hash:		711706858148838baa4403f9b1f8511fb951e78957f6db03bc74575c7b2f8d4b
Encoded:	$argon2id$v=19$m=65536,t=4,p=1$azNyQXhjTWlaMUVNUVV2S1BFaS9EM2IxWWlER3IwdGFzZGZzNjNoN3dINA$cRcGhYFIg4uqRAP5sfhRH7lR54lX9tsDvHRXXHsvjUs
0.297 seconds
Verification ok
```

The ID from the command line does not compare favorably with the ID from within mysql.  But I don't know enough about argon2 to know whether it should.

I'm now officially operating above my paygrade.

**Comment by kevinpapst** [comment]
Don't think too complicated... "Not found" means 404 and not 401 ;-)

This works perfectly fine:
```
curl -X GET \
  https://demo.kimai.org/api/ping \
  -H 'X-AUTH-TOKEN: api_kitten' \
  -H 'X-AUTH-USER: susan_super'
```

Did you install Kimai in a subdomain or a subdirectory?

**Comment by kevinpapst** [comment]
ping @hmr-it-jr app issue

**Comment by hpeyerl** [comment]
It's being rewritten to /.  My browser URL is:

http://kimai.beer.org/index.php

hmm.  looks like composer made an nginx rewrite that looks like this:

                rewrite ^/$ http://kimai.beer.org/index.php;

all of my URL's have "index.php" in front of them.  Not sure how it's supposed to look.

**Comment by kevinpapst** [comment]
I doubt that Composer will add a nginx rewrite ... but thats likely the problem, fix the ngxinx configuration: 
https://www.kimai.org/documentation/fresh-ubuntu-18.html#configure-webserver
And then retest.

**Comment by hpeyerl** [comment]
Yup. Got it now.  Working.

Sorry.

**Comment by hmr-it-jr** [comment]
> ping @hmr-it-jr app issue

I definitely have to release the updates with the FAQ section in the app. Misconfigured / not working api is 99,99 % feedback / reports I get from app users.

@kevinpapst you've introduced "Doctor" in menu for super-admins. Can you add something to check if the api is working is expected? Most users which use Kimai 2 in a subfolder don't have a working api.

**Comment by kevinpapst** [comment]
I added a fix for the API in subdirectory installations in 1.5.
I think that should be sufficient.
