### ISSUE TITLE
Language of user is ignored in new error pages (page not found)

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#1218]
**Describe the bug**
The language of the user is being ignored if he clicks on the dashboard link in the not found page.

**To Reproduce**
1. Switch your language to any language but English
2. Navigate to a page which does not exist
3. Click "Dashboard"
4. Watch the UI - it has changed to English

**Screenshots**

![20191103_220750](https://user-images.githubusercontent.com/36242595/68091962-87dd2280-fe86-11e9-9aa4-e318b06e46fa.gif)

**Additional context**
 - Kimai version 1.5

**Comment by kevinpapst** [comment]
I know this is ridiculous, but Symfony does not offer a way to translate the 404 error page without complicated workarounds:
https://symfony.com/doc/current/controller/error_pages.html#security-404-pages
I already tried and didn't find a quick solution.

**Comment by hmr-it-jr** [comment]
maybe add a chek to dashboard page "is language from GET param the same as user preferenced language" -> redirect to correct language

**Comment by kevinpapst** [comment]
Hm, good idea. 
There is already the /homepage URL which redirects to the configured "start page" of the user with the correct language. We could use that one.
