### ISSUE TITLE
actions modal gets cropped at the end of the page

### ISSUE THREAD

**Issue by diogojesus95** [kevinpapst/kimai2#1219]
**Describe the bug**
When we activate the action modal (customer list for example) the last 2 from the list get the modal cropped

**To Reproduce**
1. Go to customer page
2. Scroll to the last name from the list
3. Select actions

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/26788642/68114814-3ae56480-fef7-11e9-9749-890f1cd49e75.png)

 - Kimai version 1.4.2

**Comment by kevinpapst** [comment]
True. Until it gets fixed there are some workarounds:
1. reduce the result page size in the search form to a lower number, so you have enough place on the screen.
2. open the "edit" link in a new tab. The resulting page will show all actions as well in the upper right corner.

**Comment by diogojesus95** [comment]
> True. Until it gets fixed there are some workarounds:
> 
> 1. reduce the result page size in the search form to a lower number, so you have enough place on the screen.
> 2. open the "edit" link in a new tab. The resulting page will show all actions as well in the upper right corner.

Thank you for the int. However I don't think that both options would be the best option. So we added a simple div with 150px at the bottom of our customer index page right before endblock

``` 
<div style="height: 150px"></div>

{% endblock %}
``` 
This should word until a fix gets released

**Comment by kevinpapst** [comment]
LOL, yes that works as well ;-)
