### ISSUE TITLE
Including the active/inactive flag in the dashboard tiles

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#1221]
In April Kevin replied to a question of mine:

*"But it is already configurable (see documentation), unfortunately the active/inactive flag is not included in the statistics which are used to populate the data. Its simple to add, but I wonder how many people are really interested in these number.
I would much more like to add that to an upcoming reporting extension, but if you want to submit a PR I can guide you in the right direction and we can add it to the dashboard."*

It took six months to get our IT'er into installing Kimai, but since yesterday finally it is in use at our office.

Are you still willing to guide me through including the active/inactive flag in the lower tiles in the dashboard, so one can choose to see in an eye-blink only the amount of active projects/customers/users/activities? I tried to open a PR for this, as suggested, but the button was greyed out.

Greetings

Willem

**Comment by kevinpapst** [comment]
PRs are always based on changing the files in your own copy (fork) of this repository.
So first of all: you need to fork this repository, then create a branch, change your files in there, commit and push them. Then you will see a "Open PR" button.

**Comment by 1willem** [comment]
Thanks for the explanation, Kevin. I kind of figured that out and did a pull request for the language files I made. Hopefully I did it right this time. 

But how to do a pull request if i haven't any clue yet on what file I need to change to implement the active/inactive flag in the dashboard widgets? I've been browsing the templates/dashboard, templates/macros and templates/widgets files, but did not immediately found it.

Could you concisely tell me what file(s) to change, and how exactly so I can upload it and do a pull request?

Thanks for your patience.

Willem

**Comment by kevinpapst** [comment]
There is no PR existing for the language, see: https://github.com/kevinpapst/kimai2/pulls
You created it in your own fork: https://github.com/1willem/kimai2/pulls
Please create it once again in this repo here.

Timesheet related dashboard widgets are defined here:
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/WidgetRepository.php#L154
There is always a `query` name for each widget. Write that down when changing to this file:
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/TimesheetRepository.php#L117

The other widgets (number of users/activities/projects/customers) are defined here:
https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/DashboardSubscriber.php#L93

Maybe it is enough to change the calls like `this->user->countUser()` and pass in a `true` like this => `this->user->countUser(true)`

**Comment by kevinpapst** [comment]
fixed for the next release

**Comment by 1willem** [comment]
Thanks to implement this, Kevin.
