### ISSUE TITLE
Sort on ordernumber or username, and second on date and time

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#1223]
In the index.html.twig of the timesheet-team template I added *orderNumber* by adding it to *set columns* and *td*. This works fine. A sort arrow even automatically shows. But when I press it, nothing happens. 

**How can I program that it sorts on number, and next on date and time?** I tried by writing *‘orderBy’: true* behind *orderNumber* in *set columns* but that didn’t work. Should I use something like *’orderBy’: ‘orderNumber’ ASC, ‘addorderBy’: begin*. I lack the knowledge of the exact code language for this. And can it be added in the index.html.twig file or should it be added to another file, to which can be referred in the twig file?

The goal is, for instance, to be able to filter on a time range (lets say last month) and to see on which projects we have been working by sorting them on orderNumber (sorting on project name is standard implemented and works but we refer to our projects mainly by their ordernumber).

Another goal is to use the same filter but order on username, to see in one list who has been working on what. I believe the answer to that is similar. I see *username* in *set columns* is now followed by *‘orderBy’: false*. When I delete this or change it in *true*, an arrow is displayed, but it does not function. I have the same question here: **how to order on username and, second, on date and time?** Should I use something like *’orderBy’: ‘username’ ASC, ‘addorderBy’: begin* and in which file should I write it to make it work?

Thanks for the assistance on this. If this matter is a too complex thing to explain, please just tell me.

Willem

**Comment by kevinpapst** [comment]
Ordering on two columns is simply not possible. Activating sort on further columns needs to be done both in the twig template (what you already found) and then in the "repository".
For example here: https://github.com/kevinpapst/kimai2/blob/master/src/Repository/ProjectRepository.php#L218
There is also a whitelisting of allowed order names:
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/Query/ProjectQuery.php#L19

**Comment by 1willem** [comment]
Thanks for guiding me, Kevin. In *TimesheetQuery.php* I added *’orderNumber’* and *‘username’* behind *public const TIMESHEET_ORDER_ALLOWED =*. This result in the arrows actually responding, which is good. Unfortunately, the response is not the ordering of the ordernumber or username, but a basic page is shown.

I must be missing out on something, but I couldn’t find any sorting code in the query or repository files I should copy and modulate to ordernumber and username to make sure the effect of clicking the arrow next to the title **ordernumber** and **username** would actually result in ordering those columns.

Could you guide me once more to the right track (or file)?

Many thanks

Willem

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/TimesheetRepository.php#L572

**Comment by 1willem** [comment]
Thanks again, Kevin. I've found it. 

In the file *TimesheetRepository.php* To *switch ($orderBy)* I added 
            *case 'orderNumber':
                $orderBy = 'p.orderNumber';
                break;
            case 'username':
                $orderBy = 't.user';
                break;*

This worked. Hurray! 

While I was at it, I was trying to expand the search bar query to look for the search term also in the columns customer, project, order number and user, and not only in the description field. But, I have troubles guessing the correct code name.

In the same file I added to *searchTerm->hasSearchTerm*

                    *$qb->expr()->like(**'c.name'**, ':searchTerm'),
                    $qb->expr()->like(**'p.name'**, ':searchTerm'),
                    $qb->expr()->like(**'t.user'**, ':searchTerm'),
                    $qb->expr()->like(**'p.orderNumber'**, ':searchTerm')*

But these code names, that worked for the *'orderBy'* function, don't seem to work here, When I search, for instance, an order number that is among the time sheets, it does not give any results. *c.name*, *p.name*, *t.user* and *p.orderNumber* must be the wrong code name. 

Third time lucky, can you give me one last bread crumb and give away the correct code lines?

Many thanks for your guidance.

Willem

**Comment by kevinpapst** [comment]
I guess you added it to 
```
            if ($searchTerm->hasSearchTerm()) {
                $searchAnd->add(
                    $qb->expr()->like('t.description', ':searchTerm')
==> right here?
                );
                $qb->setParameter('searchTerm', '%' . $searchTerm->getSearchTerm() . '%');
            }
```
This is an "and" query so it must appear in all fields.
You need to wrap the single fields with an "OR" (untested):
```
$searchOr = $qb->expr()->orX(
  $qb->expr()->like('t.description', ':searchTerm'),
  $qb->expr()->like('c.name', ':searchTerm'),
  $qb->expr()->like('p.name', ':searchTerm'),
  $qb->expr()->like('t.user', ':searchTerm')
);
$searchAnd->add($searchOr);
```

**Comment by 1willem** [comment]
You guessed correct, Kevin. 

I tested your suggestion, but it unfortunately gives an error 500. I tried then to recycle and adapt what I find in *ProjectRepository.php*:

$searchAnd->add(
                    $qb->expr()->orX(
                      $qb->expr()->like('t.description', ':searchTerm'),
                      $qb->expr()->like('c.name', ':searchTerm'),
                      $qb->expr()->like('p.name', ':searchTerm'),
                      $qb->expr()->like('t.user', ':searchTerm'),
                      $qb->expr()->like('p.orderNumber', ':searchTerm')
                    )
                );

But it gave the same error.

Do you have other suggestions? 

Many thanks

Willem

**Comment by kevinpapst** [comment]
Check your logs, 500 should log an error. Maybe it is just the field name: order_number.

**Comment by 1willem** [comment]
It seems like it has to do something with the number of query parameters in the query exception. Although I couldn't find out what that means. Here the log:

*request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "Too many parameters: the query defines 0 parameters and you bound 1" at /home/bollenad/public_html/kimai/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 105 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): Too many parameters: the query defines 0 parameters and you bound 1 at /home/bollenad/public_html/kimai/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:105)"} []*

Does it ring a bel to you?

Thanks for the assistance, Kevin.

Willem

**Comment by kevinpapst** [comment]
You bind a parameter, but don't use it in the query. Maybe Something like `execute(['foo' => 'bar'])` or `setParameter('foo', 'bar')` is execute but you never added ':foo' as dynamic parameter.

**Comment by 1willem** [comment]
Found it!

The bug lies in the use of 
                        $qb->expr()->like('t.user', ':searchTerm'),

If I delete that, it works fine with the other fields (*p.name*,*c.name*, *p.orderNumber* and *t.description*)

Unless you have any idea's by heart on what the correct code line should be (I in vain tried *t.username*, *username*, *$user*, *User*, *t.users*, *users*), I think I'll just leave this search field out,

Or could it be the search cannot be performed because the usernames are displayed in a Class (marked in blue)?

Thx,
Willem

**Comment by kevinpapst** [comment]
I have no plans to support multiple sort columns (in the near future). Therefor I am closing this discussion.

**Comment by 1willem** [comment]
Thank you for exploring it, Kevin. I understand your decision.
