### ISSUE TITLE
Timesheet doesn't appear to calculate Duration*HourlyRate resulting in $0.00 invoice.

### ISSUE THREAD

**Issue by hpeyerl** [kevinpapst/kimai2#1225]
I'm trying to transition from another time tracking system to KimaiV2.  This is my first week tracking time with KV2.

There's a few things I don't understand or think could be made easier but I'll start with this.  

I've created a Customer, and set the rate (eg: $98/hour).
I created a Project under the Customer and set the rate (again, fictitious $98/hour)
I created Activities under the Project (again, I have to set the rate, I use the same rate of $98/hour).
Then, using the Calendar (or clicking "+" in "My Times"), I create time records.  Why do I have to enter the rate here again?  It doesn't appear to inherit the rate from the Activity.   It seems superfluous to have to enter the rate for every new Time record that I create.

Anyhow, after I Save the new time record, the 'Rate' column shown in "My Times" is $0.00 (even if I make sure to put "$98" in the "Hourly Rate" field and enter a duration of "1:00", I would expect to see "$98.00" in "My Times".   

If I put "98" in "Fixed Rate" instead, then it is accurately reflected in the "Rate" column of "My Times".  But then I have to manually calculate "hours * rate" when I create my time record.

Am I misunderstanding how this software should be used?

Attached is a screenshot.
![Screen Shot 2019-11-07 at 6 13 18 AM](https://user-images.githubusercontent.com/6561217/68392510-2a1b3580-0127-11ea-804c-ea85badda3d0.png)

**Comment by kevinpapst** [comment]
Sounds like a misunderstanding on your end.
Did you read https://www.kimai.org/documentation/timesheet.html#rate-calculation ?

**Comment by hpeyerl** [comment]
Ok, but I have "98.00" in each of:

Timesheet hourly rate
Activity hourly rate
Project hourly rate
Customer hourly rate

So how do I get it to pick one of those "hourly rate"s and multiply it against "Duration" so my invoice will show something other than "$0.00"?

![Screen Shot 2019-11-07 at 6 31 47 AM](https://user-images.githubusercontent.com/6561217/68393069-61d6ad00-0128-11ea-9edb-0d88ed93aae2.png)

**Comment by kevinpapst** [comment]
Without seeing all of your configuration, I don't know what is wrong.
Many factors can influence the outcome of that calculation.

Test it at a demo http://www.kimai.org/demo/ and check if the error appears there as well.

Do you have a local.yaml? If yes, please add it here.
What configurations do you have set besides the hourly rates? Which tracking mode do you use?
Do you have a 0 in any fixed rate field (activity, project, customer)?

**Comment by hpeyerl** [comment]
This is probably more useful than screenshots:

```
mysql> select * from kimai2_timesheet;
+----+-------------+------------+---------------------+---------------------+----------------+----------+-------------+------+----------+------------+-------------+------+
| id | activity_id | project_id | start_time          | end_time            | timezone       | duration | description | rate | exported | fixed_rate | hourly_rate | user |
+----+-------------+------------+---------------------+---------------------+----------------+----------+-------------+------+----------+------------+-------------+------+
|  3 |           5 |          1 | 2019-11-04 14:26:00 | 2019-11-04 16:26:00 | America/Denver |     7200 | NULL        |    0 |        0 |          0 |          98 |    1 |
|  4 |           5 |          1 | 2019-11-05 14:30:00 | 2019-11-05 16:30:00 | America/Denver |     7200 | NULL        |    0 |        0 |          0 |          98 |    1 |
|  5 |           3 |          1 | 2019-11-05 20:05:00 | 2019-11-06 00:05:00 | America/Denver |    14400 | NULL        |    0 |        0 |          0 |          98 |    1 |
|  6 |           3 |          1 | 2019-11-04 20:07:00 | 2019-11-04 23:37:00 | America/Denver |    12600 | NULL        |    0 |        0 |          0 |          98 |    1 |
|  7 |           2 |          1 | 2019-11-04 16:38:00 | 2019-11-04 19:38:00 | America/Denver |    10800 | NULL        |    0 |        0 |          0 |          98 |    1 |
|  8 |           2 |          1 | 2019-11-05 16:39:00 | 2019-11-05 18:39:00 | America/Denver |     7200 | NULL        |    0 |        0 |          0 |          98 |    1 |
|  9 |           1 |          1 | 2019-11-05 18:39:00 | 2019-11-05 19:39:00 | America/Denver |     3600 | NULL        |    0 |        0 |          0 |          98 |    1 |
| 11 |           2 |          1 | 2019-11-06 12:51:00 | 2019-11-06 19:21:00 | America/Denver |    23400 | NULL        |    0 |        0 |          0 |          98 |    1 |
| 12 |           3 |          1 | 2019-11-06 12:52:00 | 2019-11-06 13:52:00 | America/Denver |     3600 | NULL        |    0 |        0 |          0 |          98 |    1 |
| 13 |          11 |          1 | 2019-11-06 12:52:00 | 2019-11-06 13:52:00 | America/Denver |     3600 | NULL        |    0 |        0 |          0 |          98 |    1 |
| 15 |           3 |          1 | 2019-11-06 13:00:00 | 2019-11-06 14:00:00 | America/Denver |     3600 | NULL        |    0 |        0 |          0 |          98 |    1 |
+----+-------------+------------+---------------------+---------------------+----------------+----------+-------------+------+----------+------------+-------------+------+

mysql> select * from kimai2_projects;
+----+-------------+----------------------------------+--------------+---------+---------+------------+-------------+---------+--------+-------------+
| id | customer_id | name                             | order_number | comment | visible | fixed_rate | hourly_rate | color   | budget | time_budget |
+----+-------------+----------------------------------+--------------+---------+---------+------------+-------------+---------+--------+-------------+
|  1 |           1 | XXXXXXXXXXXXXXXXXXX        | NULL         | NULL    |       1 |       NULL |          98 | #0d88ea |      0 |           0 |

mysql> select * from kimai2_customers;
+----+---------------------+--------+---------+---------+----------------------+---------+--------------------------+---------+----------+------------+------+--------+-------+----------+------------------+------------+-------------+---------+--------+-------------+
| id | name                | number | comment | visible | company              | contact | address                  | country | currency | phone      | fax  | mobile | email | homepage | timezone         | fixed_rate | hourly_rate | color   | budget | time_budget |
+----+---------------------+--------+---------+---------+----------------------+---------+--------------------------+---------+----------+------------+------+--------+-------+----------+------------------+------------+-------------+---------+--------+-------------+
|  1 | XXXXXXXXXXXXX        | NULL   | NULL    |       1 | XXXXXXXXXXXXXX   | NULL    | NULL                     | CA      | CAD      | NULL       | NULL | NULL   | NULL  | NULL     | America/Edmonton |          0 |          98 | #f91709 |      0 |           0 |

**Comment by kevinpapst** [comment]
Yes, it is ;-) 

The reason is: your customer has a fixed rate of 0.
Remove that. Unfortunately, you have to re-save all records to trigger the rate calculation again.

**Comment by hpeyerl** [comment]
Oh I see, the salient phrase is "If any of the above is set to 0, the records rate will be set to 0."

**Comment by kevinpapst** [comment]
It is not completely intuitive ... especially if you are a freelancer.
But a company might want to track some internal tasks always with a rate of 0.

**Comment by hpeyerl** [comment]
Yes, it's not intuitive.  I always seem to fall into the obscure holes.
