### ISSUE TITLE
SAML Support for Authentication

### ISSUE THREAD

**Issue by timlegge** [kevinpapst/kimai2#1227]
**Is your feature request related to a problem? Please describe.**
We would like to use SAML to authenticate to Kimai2.  LDAP carries some baggage that we would prefer to avoid

**Describe the solution you'd like**
Basically when you go to the web page as a not logged in user it would redirect you to a SAML processing that would send you to the IDP (Identity provided like Microsoft AZuure) page where you would login and then it would redirect you back to a SAML processing page in Kimai to properly update Kimai with the user's logged in state

**Describe alternatives you've considered**
Not really any

**Additional context**
I have looked at doing this myself as I did in Kimai 1 and I have looked at the code and documentation.  However, I need some hint on where to position the code to redirect to the SAML code instead of the main login.

**Comment by kevinpapst** [comment]
I did implement OAuth in the past in a Symfony project, but honestly: I have no clue about SAML.
It needs to hook into the Security system of Symfony and I guess there is already a plugin that might be used.

**Comment by timlegge** [comment]
HI

They would work much the same at the highest level.  Basically if I can figure out where to insert it in the flow it basically takes care of all the SAML type stuff.  At that point the auser is authenticated and we need to update the user session as authenticated, etc.

Tim

**Comment by kevinpapst** [comment]
That sounds easier as it will be, depending on your knowledge of Symfony ;-)
See this for example: https://github.com/hslavich/OneloginSamlBundle

**Comment by timlegge** [comment]
LOL.  Therein lies the problem.  I don't know symfony.  I looked for a
while a few weeks ago and will take another look soon.

**Comment by urinal-cake** [comment]
Is there any potential for this being added, maybe through that Saml bundle?
We recently moved over to Kimai, but quickly discovered it was v1, not v2, that has SAML auth.

**Comment by kevinpapst** [comment]
Yes, there is potential. Sounds like you are a speaking for a company, let me know if you want to sponsor that feature. You can find my email via my profile / website.

**Comment by urinal-cake** [comment]
Emailed. Thank you!
