### ISSUE TITLE
Would be nice when entering duration to be able to use an integer "1.5" and have that treated as "1:30".

### ISSUE THREAD

**Issue by hpeyerl** [kevinpapst/kimai2#1228]
My brain thinks in terms of "I spent an hour and a half doing this task today, 2 hours doing that task, 15 minutes filling out this form" so my fingers translate that to "1.5", "2", ":15" when I'm filling out a timesheet.   (because my customer's timesheet app does the translation automatically)... Could KV2 do the same?

(Stretch goal)

**Comment by kevinpapst** [comment]
It is not exactly your format, but:
https://www.kimai.org/documentation/timesheet.html#duration-format

**Comment by hpeyerl** [comment]
ok. Maybe the feature request could be "treat a value followed by h as a float"?  

I'll just try to change my brain.

**Comment by kevinpapst** [comment]
Was implemented for 1.13

**Comment by hpeyerl** [comment]
Thank you .
