### ISSUE TITLE
data export bug

### ISSUE THREAD

**Issue by inside54** [kevinpapst/kimai2#1232]
hi there!
if I try to export the data from the my times table, I get the export of the document without content, I only see the doc structure

here u can see my times
![chrome_qLaLElFS93](https://user-images.githubusercontent.com/57178517/68581347-88724c00-0478-11ea-8072-3702fc960169.png)

this below is the result of the export
![chrome_Ms6gMQ5Klw](https://user-images.githubusercontent.com/57178517/68581458-ba83ae00-0478-11ea-97ee-56e0cf9f5e9e.png)

I'm running Kimai 1.4.2 with xampp

**Comment by inside54** [comment]
when I execute export from the appropriate "export" table, I only get the first line.

![EXCEL_8jtpOuXu2b](https://user-images.githubusercontent.com/57178517/68582045-1438a800-047a-11ea-9c75-074400d5bcf2.png)

![chrome_4p91M4SSLl](https://user-images.githubusercontent.com/57178517/68582104-421dec80-047a-11ea-8119-9f18cc1c845f.png)

**Comment by kevinpapst** [comment]
I don't see a bug. You export November and your times are from October

**Comment by inside54** [comment]
> The export from "my times" uses the search query and without anything set: the current month. 

Sorry man, I thought it would export everything it shows on the page

The export table seems to work properly!

**Comment by kevinpapst** [comment]
Yeah, I know its misleading... I am still thinking about a way how to properly explain that in the UI.

If you don't select a filter it would export everything you have ever tracked, which is very likely not what you want as well ;-)
