### ISSUE TITLE
Expenses Plugin

### ISSUE THREAD

**Issue by 000rui000** [kevinpapst/kimai2#1233]
Hi,

I dont have much of an issue but more like some questions about the current expenses plugin.

Kimai works great for time keeping, but now i need something to track expenses but not in the way i have seen the demo work.

I need to buy stock for jobs (Electricians), i wanted to be able to buy a stock item, give it a code, and then use the code to create an ID to attach to that product, just a simple sticker.

If it is used on a job, we pick it up from the drop down menu and add it to a project.

If we capture price and add mark up as needed when we buy it, we can then just invoice costumer for all time plus stock or material used.

Correct me if i am wrong, but the expenses plugin currently does not allow for that, does it?

Thanks,
Rui

**Comment by kevinpapst** [comment]
Let me see if I understood your question correct:

You want to create some kind of "expense" template, say:
- LED with ID `LED1234` and piece price 1 €

Now when you need to use this item for a customer, you only want to select `LED1234` and add the amount.

Correct?

**Comment by 000rui000** [comment]
Hi Kevin,

Thanks for getting back.

Yes that it. 

We are a small contracting electrician company and it makes kimai a great tool for small businesses like us to manage time and stock.

I did thought that plug-in expenses would do this kind of functionality but when I read about I realised it does not.

So when we buy anything we will, on a stock tab:
- add a name
- add price 
- add description
- add a quantity

- And an ID is allocated automatically, we can then just write the code on boxes or do some quick stickers.

When one of the lads uses stock from vans, they choose an item and quantity used and input that on their time sheet.

Our accountant gets that info straight away as we make her a user on kimai. And when making an invoice you don’t have to search for what you bought and confirm with the staff if this was used or not.

Hope I did a better job this time at explaining it.

Thanks again for getting back and just let me know if you need more info.

Regards,
Rui

**Comment by kevinpapst** [comment]
Hi Riu,

thanks for the explanation. I do understand your use-case, but unfortunately this is not possible right now. I do take that as a wish for a new feature for the future, sounds very promising. 

Regards
Kevin
