### ISSUE TITLE
stop bookings when budget is 100%

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1236]
**Describe the solution you'd like**
Prevent bookings if budget and/or time-budget >=100%
Define as optional (by checkbox)

**Additional context**
The last booking should be shortenend to fit the 100%.
Idea: colors may warn: orange when 90% and red when 100%

**Comment by HeinzWuert** [comment]
push :-)

**Comment by easycompetence** [comment]
Is this feature still a feature-request? Or is it possible to stop booking when budget reached 100%?

**Comment by HeinzWuert** [comment]
We are really waiting for this feature!
Unfortunately there are users ignoring the 100% marker. As a result we get invoices which can't be paid.

**Comment by andreas-by** [comment]
This feature would be much appreciated for our use case! :)

**Comment by kevinpapst** [comment]
Now available in master, will be released with 1.14.
More infos at: #2422 (also link to dem for testing)
