### ISSUE TITLE
Invoice not really usable

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1237]
**Is your feature request related to a problem? Please describe.**
Not only admins use the invoice document, normal users does it too.
But the personal data of a user are saved within the invoice document. This is not usable for every "normal" user.
Also changing these personal data like adress, phone etc can only made by logging into the server, not in user level of Kimai.

**Describe the solution you'd like**
Save these informations/variables in the profile of a user and use these variables to fill the invoice document.

**Comment by kevinpapst** [comment]
new fields for the current logged-in user are available with the next release
