### ISSUE TITLE
Error deleting a tagged record

### ISSUE THREAD

**Issue by jacoblanco** [kevinpapst/kimai2#1241]
**Describe the bug**
When we try to delete a tagged record, we get a constraint error.

**To Reproduce**
1. Create a new record and tag it.
2. Try to delete the record.
**Logfile**
```
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`kimai2`.`kimai2_timesheet_tags`, CONSTRAINT `FK_732EECA9ABDD46BE` FOREIGN KEY (`timesheet_id`) REFERENCES `kimai2_timesheet` (`id`)) at /opt/kimai/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"}
```

**Additional context**
 - Kimai version 1.4.2
 - PHP version 7.2.9

**Comment by jacoblanco** [comment]
As a workaround, untagging the record, and then it succesfully gets removed.

**Comment by kevinpapst** [comment]
Thanks, I had that report once before but couldn't find out what was wrong.

Can you try to execute these SQLs:
```sql
ALTER TABLE kimai2_timesheet_tags DROP FOREIGN KEY FK_732EECA9ABDD46BE;
ALTER TABLE kimai2_timesheet_tags DROP FOREIGN KEY FK_732EECA9BAD26311;

ALTER TABLE kimai2_timesheet_tags ADD CONSTRAINT FK_732EECA9ABDD46BE FOREIGN KEY (timesheet_id) REFERENCES kimai2_timesheet (id) ON DELETE CASCADE;
ALTER TABLE kimai2_timesheet_tags ADD CONSTRAINT FK_732EECA9BAD26311 FOREIGN KEY (tag_id) REFERENCES kimai2_tags (id) ON DELETE CASCADE;
```

Maybe the database update forgot to add the "ON DELETE CASCADE" (if possible check that beforehand).

**Comment by jacoblanco** [comment]
That install was a clean and fresh installation if it helps.
