### ISSUE TITLE
Two taxes with 3 range floating point.

### ISSUE THREAD

**Issue by jeandoyon** [kevinpapst/kimai2#1243]
In Quebec, Canada, we have 2 taxes. GST 5% and QST 9.975%. Both taxes need to be included on invoices for proper book keeping.

Would it be trivial to add a second tax field with 3 range floating point?

**Comment by kevinpapst** [comment]
Oh wow, so it can be even more complicated than in the EU ^^

You can/should create your own invoice template to achieve that:
https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document

Simply take the sum before tax and multiply it with the (tax rate / 100).

**Comment by kevinpapst** [comment]
Closing, as Kimai cannot fulfill all possible regulations around the world. 
Too many governments with strange ideas ;-)
