### ISSUE TITLE
New fields: Start and End of project

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1244]
**Is your feature request related to a problem? Please describe.**
Kimai is using the field "order date" which is in a timesheet not very helpful (imo).
On the other side its not possible to get an overview about starting and endig or already ended projects.

**Describe the solution you'd like**
Add two new date fields
- Start of Project
- End of Project
both sortable

**Describe alternatives you've considered**
Custom field are no solutiuon, bcause there is no chance of indexing.

**Comment by kevinpapst** [comment]
Duplicates #1212

Closing this on in favor of the older one.
