### ISSUE TITLE
How is per-customer tax defined?

### ISSUE THREAD

**Issue by hpeyerl** [kevinpapst/kimai2#1248]
All of my current customers pay a canadian federal tax (GST, 5%).  I haven't found where I activate that?   In the past (and probably in the future) I've had customers that didn't get charged Tax.  From googling, it appears that Tax is calculated in the Invoice renderer but I don't understand how to define it; especially not "per customer".

**Comment by kevinpapst** [comment]
The tax rate is stored in the invoice template inside Kimai.
<img width="890" alt="Bildschirmfoto 2019-11-14 um 14 06 31" src="https://user-images.githubusercontent.com/533162/68859654-08521d80-06e8-11ea-84a5-4f196e15c1be.png">

If you need different tax rates per customer, simply create different invoice templates with different tax rates (you can still use the same invoice document).

**Comment by hpeyerl** [comment]
I've never seen that screen.  How do I get to it?  Or do I have to install something like PHPWord (saw that in the documentation)?  I thought I had to create invoice templates by hand using a text editor and I haven't gotten that far yet.

**Comment by kevinpapst** [comment]
Invoices => and the the "list" icon in the upper right

**Comment by hpeyerl** [comment]
oh. Embarassing.  Sorry.

**Comment by kevinpapst** [comment]
Wording/Documentation problem, there are:
- invoices documents which render the invoice (eg. to html, pdf, excel) - might also be called templates
- invoice templates, which define basic contents for each invoice

If you have an idea how to make that clearer in the documentation, please share your ideas!

**Comment by hpeyerl** [comment]
I think I see.  I need to go through and define an invoice 'template' (with my corporate logo and all that) and go through the whole process.  (I'm also trying to figure out how to deal with mileage which is part of my tracking/invoicing flow).  Then I'll have a better idea what to suggest.  My gut feel is something like "invoice schema" for what the basic contents are for a customer-specific "invoice template"; but that's not quite right either.

**Comment by kevinpapst** [comment]
I think I need to add a chapter "Setup invoices" to explain the first basic steps. 
And then the advanced steps, if you want to have your own invoice design.

For mileage: you could test the [expenses plugin](https://www.kimai.org/store/expenses-bundle.html). Recorded expenses will be added to your invoices.

**Comment by hpeyerl** [comment]
I was looking at the expenses plugin to solve that problem.  Not sure yet.  I started by adding an activity for mileage to my main customer.  I don't need to invoice the customer, but I do need to track it for tax purposes.  I create a 'tag' for it as well but for invoicing, it would be nice to invert the tag selection and say "select all activities without this tag".  It appears to be the wrong approach.

**Comment by kevinpapst** [comment]
Sounds like a "non refundable" expense.

**Comment by hpeyerl** [comment]
I need to put more work in to deciding whether Kimai can replace my current time-tracking system before committing to buying plugins etc.  I'm not averse to paying for software that saves me time with the undesirable parts of corporate operations.  I just want to make sure all the pieces are or can be there.

**Comment by kevinpapst** [comment]
Totally understandable. Open up new issues if you miss important things or have further questions!
