### ISSUE TITLE
own window for "custom fields"

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1250]
**Is your feature request related to a problem? Please describe.**
Custom fields are great and would be greater when it's possible to use them in a own window.

**Describe the solution you'd like**
Now Kimai has
- Timesheets
- Customers
- Projects
- Activities
- User
and here the new one "- custom window" for custom fields

**Comment by kevinpapst** [comment]
Is this still a feature request? If so, I don't understand the idea.
Can you elaborate? 
What do you want to see in this screen, what should be possible?
