### ISSUE TITLE
Access to customers doesn't work for teams

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#1253]
**Describe the bug**
If a team has access to a customer only the customer(s) with access should be visible for the team.

**To Reproduce**
1. Create a team
2. Add team members to the team
3. Add one or more customers to the team
4. Log in as teammember and you still see all customers.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/36242595/68944763-f5eee700-07ae-11ea-81ab-6ce080654415.png)

-----------

![grafik](https://user-images.githubusercontent.com/36242595/68944779-03a46c80-07af-11ea-912a-6d062b0c4652.png)

------------

Am I using it the wrong way? Besides this, the reset button at "Grant access to customers" does nothing.

**Comment by hmr-it-jr** [comment]
Ahh if a customer is not in a team it's a global customer which is visible for all teams.

**Comment by kevinpapst** [comment]
Documentation is king 😁 but not very obvious behaviour ... I know.

I heard that complain quite often, so I think a simple radio button in the customers/projects edit form, something like `Visible to all` and `Limited visibility based on permissions` should be added.
