### ISSUE TITLE
Currency is missing for revenues in dashboard

### ISSUE THREAD

**Issue by redeye86** [kevinpapst/kimai2#1257]
In the dasboard there is the currency is missing for the 4 categories of revenue (today, this week, this month, this week).

![Screenshot_0001_20191117_112333](https://user-images.githubusercontent.com/3612865/69006255-bea64480-092c-11ea-9e44-40f64bd07823.png)

 - Kimai version: 1.5
 - PHP version: 7.2

I temporarily fixed it for me by using this dirty bit of css in custom css plugin:
`section.dashboard .row:nth-child(3) .info-box-number::after {
    content: '€';
}` (disabled for the screenshot)

**Comment by kevinpapst** [comment]
Yes, these widgets need a refactoring, but I like your creative solution 👍 

The main problem is: this value can be correct or well ... at least misleading. 
If you work only for EU customers all is good. 
But what should be displayed if you work for customers with different currencies?

**Comment by redeye86** [comment]
I thought so already, but I think throwing all in one pot does not make sense either as it would show some undefined value. Also converting the currency automatically would not make much sense as conversion rates would be needed.

Maybe it would be the best to just list the accummulated amounts for each currency. At least 2 or 3 different should fit, if the font is reduced dynamically. For more than three different currencies some scrollbar would be necessary.

**Comment by kevinpapst** [comment]
These widgets are still from "day 0" of Kimai 2 and were never touched since then...

Yeah, I guess it needs a solution similar to the "daily statistics" in the timesheet view.

**Comment by kevinpapst** [comment]
Next major release #2902 will finally fix this issue:
<img width="1783" alt="Bildschirmfoto 2022-08-06 um 17 52 28" src="https://user-images.githubusercontent.com/533162/183256364-c5104613-ab1e-45f8-8af6-7013d3afab18.png">

If multiple currencies are found in the period, the plain text values switch to a label to be able to simpler distinguish them.
