### ISSUE TITLE
time registration form - search on customer in project field shows the customer, not the projects

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#1264]
Issue:
In the form to register a time you need to select a project. If you leave the customer field blank the projects are grouped by customer (in bold and grey). When using the keyboard to find a project you can start typing in the menu bar. Corresponding records show instantly. But when typing the customers name, the projects of that customer are not shown (unless the projects name includes the name of the customer). For example: when searching in the kimai_demo on *Bosco* in the project field (leaving the customer field open). Only the grey bold group name *Bosco, O'Kon and Kshlerin* is shown but not the projects it groups, thus making it not possible to select one of the projects of this customer.

Question;
is it possible to show also the projects of a customer, when the search term only corresponds to the customers name but not to the projects names? in the Demo: typing *Bosco*, should then not only show the (grey, bold) customer, but also all the projects of that customer, making it possible to select one of them.

Related question:
The order number to the project is a field we often work with in the office. I got the question today if it were possible to type an order number in the project menu bar in the time registration form, to get the responding project as a result (without previously having to add the order number in the projets name details). 

I was already searching in the *src\form\TimesheetEditForm.php* and the *src\form\Type\ProjectType.php* to add something like *{% if entry.orderNumber is not empty %}({{ entry.ordernumber }}){% endif %}*, so the order number would always be shown in brackets after each project in the list, making it possible to search on it. This way, simply typing the order number in the project field can do to find and select the corresponding project. But my limited knowledge reached not far enough to understand if and where I can add a code line that makes this happen (orderNumber in brackets after every project name in the drop down menu).

Thanks for thinking together with me on both the customer and order number issue.

Willem

**Comment by kevinpapst** [comment]
The first search issue is already addressed / being worked on by @choules in #1252

The only re-usable solution would be to populate further data attributes:
https://github.com/kevinpapst/kimai2/blob/master/src/Form/Type/ProjectType.php#L44
And then ask @choules if we can search in those fields as well.

If your company wants custom adjustments, you can always contact me via email! Patching Kimai core files will likely prevent you from updating to future versions

**Comment by choules** [comment]
> And then ask @choules if we can search in those fields as well.

Since the corresponding HTML element is passed to the matching function as well, we should be able to search the data attributes. Perhaps we should introduce a "data-searchable-terms" – or something similar – which may be filled with possibly interesting meta data, so that we do not need to search in all data attributes?

**Comment by kevinpapst** [comment]
Hm, had a quick look and the logic to build the select is currently "quite generic".

This is preparing the data from the API:
https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiSelectDataAPI.js#L60

And here the new entries are attached as option's to the select:
https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiFormSelect.js#L51

I don't want to add that `data-searchable-terms ` field to the API results, so I could probably add the field-names to the original select and then extract them from the API result. This extracted data could then be added to the new data field.

For example:
Select:
```
<select name="project" data-search-fields="name,orderNumber">
```

API result:
```
{'id': 1, 'name': 'MyProject', 'orderNumber: '122234'}
```

Then we extract those fields in a loop and the result "MyProject 122234" would be added to the array:
```
[ 
id: 1,
name: "MyProject",
data-searchable-terms: "MyProject 122234"
]
```
which is passed to the [FormSelect](https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiFormSelect.js#L68), which would have to handle that new data attribute. Probably it could simply add all fields to the HTML which start with `data-`.

I think this would be a huge bonus for these fields. Would you be willing to collaborate on that one @choules ?

**Comment by choules** [comment]
I would take over the JS parts, no problem @kevinpapst ! Digging into the Symfony framework has to wait for some more spare time ;-)

**Comment by 1willem** [comment]
Thanks for the discussion on this topic, Kevin and Choules. Being a dummy, you kind of lost me in understanding your ideas in this. Did I understood correct that you have found a way to search on more data atributes (such as orderNumber), but that the implementation needs to wait a while for when Choules finds the time for it?

**Comment by kevinpapst** [comment]
We kind of agreed on a solution, but I have no time currently. I will come back to this topic asap, as I find it vey useful as well.

**Comment by kevinpapst** [comment]
First part was solved a long time ago, second part can be sponsored.
