### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by amanzone** [kevinpapst/kimai2#1265]
Hello,

I tried just now to upgrade the installation I had performed a few days ago, using the steps defined  in the guide (https://www.kimai.org/documentation/updates.html).

The error occurs when I try to migrate the database (MySQL):

`WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20191024100951 from 0

  ++ migrating 20180701120000

     -> CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
Migration 20180701120000 failed during Execution. Error An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists
18:43:09 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists" ["exception" => Doctrine\DBAL\Exception\TableExistsException^ { …},"command" => "doctrine:migrations:migrate","message" => """  An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARCHAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':\n  \n  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists  """]

In AbstractMySQLDriver.php line 38:

  An exception occurred while executing 'CREATE TABLE kimai2_users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, mail VARCHAR(160) NOT NULL, password VARCHAR(254) DEFAULT NULL, alias VARC
  HAR(60) DEFAULT NULL, active TINYINT(1) NOT NULL, registration_date DATETIME DEFAULT NULL, title VARCHAR(50) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:
  array)', UNIQUE INDEX UNIQ_B9AC5BCE5E237E06 (name), UNIQUE INDEX UNIQ_B9AC5BCE5126AC48 (mail), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists

In PDOConnection.php line 90:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists

In PDOConnection.php line 88:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'kimai2_users' already exists
`

Any suggestion? Of course I can recreate the db from scratch (At the time entries there are for test pusrposes only), but of course this is not applicable in production.

Thanks for any help you may provide.

Best regards,
Alberto

**Comment by kevinpapst** [comment]
Something went wrong during the initial installation. 
This error means, that Kimai thinks you never executed any database migration. 
But those are (100% sure) imported during the initial installation, when you follow the exact steps from the installation guide.
There needs to be a database called `migration_versions` with roughly 15 to 20 entries.
Which version did you initially install and how? Which version do you want to update to?

**Comment by amanzone** [comment]
I cannot be sure as I'm not currently in the officso I cannot check. 

Anyway I believe I installed the latest stable, so it should have been version1.6.

Then I followed (blindly I have to admin because I was in a hurry) the update guide. 
I realize now that in the update guide it checks out version 1.5

So, it may actually be that I'm trying to "update" from version 1.6 to version 1.5 right? 

Actually I only wanted install the last commit, because I saw that a couple days ago you committed a new version where the post timesheet API allows to add a new timesheet entry for any user, passing the user as an argument

**Comment by amanzone** [comment]
No, that's not the case.
I had already installed v 1.5 so it seems  I was trying to update from. 1.5 to 1.5

**Comment by kevinpapst** [comment]
There is not information available how to use the latest master, even if it is quite easy if you know your way around git. But I will not help with that, too much work already---

Nevertheless, this error clearly indicates, that the migrations were not imported into the database, which can only happen if you did not use the default installation way . At least I don't see another chance how you come to such a situation.

You can still import all migrations by running `bin/console doctrine:migrations:version --add --all` to fix that situation. Which will fix your update problem.
But that needs to be done on the exact same code version which was used to install Kimai. If you are still on tag 1.5, then you are safe to run it.

**Comment by amanzone** [comment]
Ok, don't worry for v. 1.6, I have seen that I need to install not the master but a branch (tag timesheet-api-user) . I should be able to do that with git.

First of all I will anyway run the fix you mention, thanks for the hint. 

Thanks and good evening

**Comment by amanzone** [comment]
So, your command to import all migrations of course worked and fixed the issue.

Thank you very much, you've been very helpful.

PS> Installing the "timesheet-api-user" branch was easy and it allowed us to test this feature we needed.
In the meanwhile this has been included in release 1.6, so we upgdated to 1.6

**Comment by kevinpapst** [comment]
Thanks for your feedback!
