### ISSUE TITLE
 Fatal error: Uncaught Symfony\Component\Validator\Exception\MappingException

### ISSUE THREAD

**Issue by inside54** [kevinpapst/kimai2#1266]
The software works properly locally with XAMPP on Windows 10. Now I have moved the contents of the / kimai folder to a remote linux aruba server and I got this error when i go to domain.it/kimai/public: 

> Fatal error: Uncaught Symfony\Component\Validator\Exception\MappingException: The mapping file "/web/htdocs/www.campersulmona.it/home/kimai\vendor\symfony\form/Resources/config/validation.xml" does not exist in /web/htdocs/www.campersulmona.it/home/kimai/vendor/symfony/validator/Mapping/Loader/FileLoader.php:38 Stack trace: #0 /web/htdocs/www.campersulmona.it/home/kimai/vendor/symfony/validator/ValidatorBuilder.php(298): Symfony\Component\Validator\Mapping\Loader\FileLoader->__construct('/web/htdocs/www...') #1 /web/htdocs/www.campersulmona.it/home/kimai/vendor/symfony/validator/ValidatorBuilder.php(324): Symfony\Component\Validator\ValidatorBuilder->getLoaders() #2 /web/htdocs/www.campersulmona.it/home/kimai/var/cache/prod/Container1mYmMck/srcApp_KernelProdContainer.php(1143): Symfony\Component\Validator\ValidatorBuilder->getValidator() #3 /web/htdocs/www.campersulmona.it/home/kimai/var/cache/prod/Container1mYmMck/srcApp_KernelProdContainer.php(1479): Container1mYmMck\srcApp_KernelProdContainer->getValidatorService() #4 in /web/htdocs/www.campersulmona.it/home/kimai/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 106

**Comment by inside54** [comment]
I did not change any files, only by reloading the page did I get a different error:

`Fatal error: Out of memory (allocated 2097152) (tried to allocate 20480 bytes) in /opt/lampp/htdocs/beta/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 172

Fatal error: Out of memory (allocated 2097152) (tried to allocate 20480 bytes) in /opt/lampp/htdocs/beta/vendor/symfony/debug/ErrorHandler.php on line 621

Fatal error: Out of memory (allocated 2097152) (tried to allocate 20480 bytes) in /opt/lampp/htdocs/beta/vendor/symfony/debug/ErrorHandler.php on line 449

Warning: Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0`

**Comment by kevinpapst** [comment]
I would try to fix file permissions, clear the cache and reinstall all composer packages.
See the mix forward and backward slash, that is likely a problem because you switched from Windows to Linux. 

But you should install it on the machine directly. 
If you choose to do it differently I cannot support that.

And don't install it in a way that the kimai directory is accessible. 
Your document root NEEDS to point to kimai/public/. 
If you see the public/ part in the URL you have a terrible security problem. I can see your database connection and can download your entire database currently!

**Comment by inside54** [comment]
ok i downloaded it again and installed it directly on linux server.

now i get this

```
Warning: require(/web/htdocs/www.campersulmona.it/home/kimai1/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /web/htdocs/www.campersulmona.it/home/kimai1/vendor/composer/autoload_real.php on line 66

Warning: require(/web/htdocs/www.campersulmona.it/home/kimai1/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /web/htdocs/www.campersulmona.it/home/kimai1/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/web/htdocs/www.campersulmona.it/home/kimai1/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/php7.2/lib/php') in /web/htdocs/www.campersulmona.it/home/kimai1/vendor/composer/autoload_real.php on line 66
```
