### ISSUE TITLE
Custom CSS File

### ISSUE THREAD

**Issue by Bjoern3003** [kevinpapst/kimai2#1267]
I know about the CustomCSS Plugin. But this is inject inline code and where not compiled by sass.

I think it could be nice, to support a custom.scss File in kimai to add some custom code, who can overwrite the default one.

**Comment by kevinpapst** [comment]
Can you explain why that would be beneficial?
If you write a bundle, you need to provide pre-compiled css, that you can include in your own templates. And you can add code to the complete application via hooks already. 
Or via the CustomCSS-Bundle if it is only for yourself.
 Recompiling the application files would only bring merge problems during the next update.

**Comment by kevinpapst** [comment]
You can hook into the `ThemeEvent::HTML_HEAD` and add a line for your own css file.
See https://github.com/kevinpapst/kimai2/blob/master/src/Event/ThemeEvent.php#L19

How you create the CSS file is up to you. You can use a SCSS compiler and import the kimai css files, if you want to re-use existing variables.

But I will not provide a way for custom scss.
