### ISSUE TITLE
Add inheritance to permissions/roles

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#1278]
If you create a new role it was possible in the past to configure it like this for new roles: "you're allowed to do everything like a user +/- X". This would be cool if this would be possible too when creating a new role. The form should ask "inherit from X" and then you can select the role you want to inherit.

**Comment by kevinpapst** [comment]
I would consider a "copy from" selection, but not a "inherit from".
Inheriting permissions would be way more complicated and adds not much benefit, as the same can be achieved by using multiple user roles (each with only a subset of the permissions).
