### ISSUE TITLE
Add invoice tabel to archive created invoices with invoice number and date

### ISSUE THREAD

**Issue by brievenbusalex** [kevinpapst/kimai2#1279]
**Is your feature request related to a problem? Please describe.**
I am using kimai2 version 1.6. including the invoicing functionality. In version 1.6 you can see if a timesheet is invoiced (exported) but it's not possible to see which timesheets are used on which invoice (you can see it on the word document of course, but not from the kimai2 client).   

**Describe the solution you'd like**
For each invoicing which is created with the 'Mark as export'  checkbox, I would like an invoice record been generared in a seperate invoice table. The invoice table will have a unique invoice number (e.q. autoincrement), and invoice date which can be used in the generated invoice output (e.g. DOCX). 

In the current functionality the filtered timesheets for the invoice are set with the flag exported if 'Mark as export' is set. In addition the timesheet table will have a foreign key field to the invoice table, which can be filled with the generated invoice number.

The invoices form can have new functionality to view already created invoices, with connected timesheets (quit similar as you can preview an invoice now with selected timesheets). 

**Describe alternatives you've considered**
No alternatives.

**Additional context**
My feeling is that this can be done without much changes in the current forms.

**Comment by gises** [comment]
If an invoice overview in Kimai would be possible directly, it would be possible in the medium term to dispense with standing invoice programs. In my opinion, there are two approaches to this, one is to do everything directly in Kimai or via API the connection to a billing program like Grand Total.
If it is developed directly in Kimai, additional functions like internal hourly rate vs. invoiced hourly rate, payment receipt, reminder, turnover overview, etc. would be needed. In addition, the various options available today for invoicing would have to be restricted, as this would otherwise no longer be tradable.

**Comment by MikKrz** [comment]
Imho - At least invoice number / header table is crucial. Nowaday implementing  more sophisticated invoice numbering then one-per-day is impassible

**Comment by kevinpapst** [comment]
I would be happy, if any of you can help testing the new invoice archive with configurable invoice-number format. See #1541
This archive does not link the timesheets to the invoice, but instead saves a couple of values and the generated document.

**Comment by brievenbusalex** [comment]
I just did a quick test. Nice straight forward functionality for an invoice archive. I like the configurable invoice number format and the different statuses of an invoice (new, waiting for payment and paid). 

Additional functionality could the possibility to delete an invoice-archive as long it has the status 'new'. Then the question is what to do with the flag 'exported' on the timesheet? That's why I was thinking of have a link between the archived invoice and connected timesheets. If you delete the invoice (because you made a mistake somewhere), the flags 'exported' on the linked timesheets can also be reset.

But anyhow, this is nice functionality already !

**Comment by MikKrz** [comment]
Generator works  ok  - nice flexibility - step   in right  direction ! We are looking  for linking invoice 3 to   number  to timesheet and maybe  storing invoice (header and lines )  in some  table  with nice view . That makes Kimai a lot more  useful for commercial projects  !

**Comment by kevinpapst** [comment]
Thanks for testing!

@brievenbusalex yes, I do understand and I will eventually add that feature in the future... one step after another ;-)

@MikKrz I am sorry, but I don't understand what you are saying. The invoice archive is the big update here. What exactly do you mean "storing invoice in some table"?
