### ISSUE TITLE
actions for checkboxes for timesheet entries not valid

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#1280]
**Describe the bug**
You can check the checkbox at an exported timesheet entry then scroll to the bottom and choose delete and confirm it. A success message appears but the entry is still there because it can't be edited by a normal user because it's already exported.

**To Reproduce**
1. Go to My times
2. Click on the checkbox at an exported entry
3. Scroll to the bottom
4. Select Delete in the select and confirm it
5. See the success message

**Screenshots**

![kimaibug](https://user-images.githubusercontent.com/36242595/69501442-44b22480-0f05-11ea-9ed4-21081fbfd70e.gif)

**Additional context**
 - Kimai version 1.6
 - PHP version 7.2

**Comment by kevinpapst** [comment]
Better this way, than the opposite way around and deletion would be possible ... ;-)
