### ISSUE TITLE
begin and end parameters in timesheet api query

### ISSUE THREAD

**Issue by redeye86** [kevinpapst/kimai2#1285]
I use the api to export the timesheet entries at the beginning of every month to use them in an own invoicing tool. I already did this with kimai 1 by directly accessing the database. Now i am converting my script to use the kimai 2 api. 

I am not quite sure but i think i see a problem. I looked at the code but couldn't find the right part just now, but i assume that you compare the begin parameter with the start time of the events and the end parameter with the finish time of the events, is that right?

The problem occurs when i set the **begin** parameter to 2019-10-01 at 00:00:00 and the **end** parameter to 2019-11-01 at 00:00:00, i will get all timesheet entries that started and finished in that month. But what if I have an event that starts before the end of the month and ends in the next month? 

I know that i could use the export flag in my case to circumvent this but i think the actual problem would persist.
I think that it would be necessarry to use two parameters (range start, range end) for both start and finish time.

**Comment by kevinpapst** [comment]
Only the begin is compared, both for the begin and end parameter:
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/TimesheetRepository.php#L672

So querying for 01.12.2019 to 31.12.2019 will not include entries that were started in November.
If you need those, simply query for begin = 30.11.2019 and filter out the ones that did end before December.

**Comment by redeye86** [comment]
Okay, then for my use case this is perfectly fine. My main concern was that it would not be consistent.

Nevertheless it could be helpfull still, to be able to filter by ending time (directly in the query).

**Comment by kevinpapst** [comment]
Yeah, it could. But nobody asked for it before and I try to avoid features that are not used - you know: dead code still has to be maintained.

But if you want to provide a PR: go ahead!

**Comment by kevinpapst** [comment]
Cleanup: no votes so far, closing.
