### ISSUE TITLE
Access to teams with API

### ISSUE THREAD

**Issue by amanzone** [kevinpapst/kimai2#1286]
Hello,

we have a need to associate users to different geographic locations, not finding a dedicated field we resolved to use different teams (if you think that's the wrong choice you could maybe point me in the correct direction).

The issue is that we would like to work on kimai as much as possible using an internally designed SW (through APIs) instead of the web browser, but so far we've not found a way to get/post teams information via API, neither with the user API nor with the teams API.

Is that something that simply is missing from the docs or is that a feature intentionally missing?

Also, do you think there would be any use in having us sharing our SW with the community?
We would be of course willing to do so.

**Comment by kevinpapst** [comment]
> if you think that's the wrong choice you could maybe point me in the correct direction

Adding a department field to the user sounds better to me. Teams were originally meant for access restriction, but that doesn't mean teams should not be used. As software developer you can never know what great things will be done by creative minds and where that journey will lead to. 

> Is that something that simply is missing from the docs or is that a feature intentionally missing?

Neither nor. It is just missing. You could send in a PR to add that (if you have devs that speak PHP).

> Also, do you think there would be any use in having us sharing our SW with the community?

Sharing software is always great, even if it "only" acts as showcase what can be done.
So I would always confirm that question with: YES, of course!

**Comment by kevinpapst** [comment]
added team and user information to the api methods for the next release

**Comment by amanzone** [comment]
That's great! Thank you very much!
