### ISSUE TITLE
new Option in Settings: no overlapping times 

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1287]
**Is your feature request related to a problem? Please describe.**
For us it's not allowed to have overlapping times.

**Describe the solution you'd like**
Menu Settings > Timesheet > Permitted number of simultaneously running time entries
Set to 0 
for preventing this behavior.

**Comment by HeinzWuert** [comment]
push :-)

**Comment by kevinpapst** [comment]
Duplicates #1184

**Comment by kimaiTSG** [comment]
Hi, 
I am setting this value to 0 but it does not allow me, if it is possible to do it ?, how can I configure it to not allow entries at the same time?.

Thanks...

![CapturaX](https://user-images.githubusercontent.com/62035711/78183185-169d9d80-742d-11ea-9e69-3450fbcff129.PNG)

**Comment by kevinpapst** [comment]
Vote with 👍 in #1184
