### ISSUE TITLE
Currency symbol (like €) to be shown with rates on invoice

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1288]
When I use ${customer.hourly_rate} in the invoice template, the invoice shows the hourly rate without currency. When I add ${invoice.currency}, the currency is shown as string (EUR, USD). 

In order to be consistent with the invoice which uses the currency symbol (€) instead of the string (EUR), I manually add the currency to the hourly rate.

It would be preferable, if ${customer.hourly_rate} would add the currency symbol (like ${invoice.subtotal}, ${invoice.tax} and ${invoice.total})

For users who want to show the string instead, a solution like ${customer.hourly_rate_nc} could be introduced.

Alternatively, a key like ${invoice.currency_symbol} could be introduced.

**Comment by kevinpapst** [comment]
Added the currency symbol for the next release, more infos in the docs:
https://github.com/kimai/www.kimai.org/pull/49/files#diff-866523f48ca448fe458de7b37edf7452R147

If you use Excel the new xxx_plain fields work better, as they can be formatted properly.
