### ISSUE TITLE
Add Button next to Customer Field

### ISSUE THREAD

**Issue by Bjoern3003** [kevinpapst/kimai2#1291]
I think it could be very nice, if there is a add Customer Button next to the select field.

Maybe also a Link in the Dropdown, if no Entry where found.

https://drive.google.com/file/d/1LvwVflw-NtjYx4RZPfA-SG1KyMcvWodI/view

After submitting Customer Form, the Customer should added to the Formfield of the parent form, and selected.

**Comment by kevinpapst** [comment]
Closing, this is a duplicate of #621
