### ISSUE TITLE
Is there a way to authenticate trough the api interface?

### ISSUE THREAD

**Issue by oemilsson** [kevinpapst/kimai2#1293]
Tried to figure out if there's a way to authenticate trough the REST interface but this seems not to be possible? If not the case what would be need to be done in order to do so?

**Comment by kevinpapst** [comment]
What?

**Comment by oemilsson** [comment]
For example i would like to login not using the website form but instead trough maybe CURL, for example it could look something like the following:

curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"username":"admin","password":"password"}' \
  http://localhost:3000/api/login 
which then returns me a token of some kind that i can use for the other api endpoints.

Went trough the swagger documentation and couldn't find such endpoint so me questions is: does such endpoint exist or you can only login as a user via web form/ldap?

**Comment by kevinpapst** [comment]
You use username + api token to authenticate against the API, if you are outside a web context.
https://www.kimai.org/documentation/rest-api.html

**Comment by kevinpapst** [comment]
LOL ... you are welcome
