### ISSUE TITLE
Project / Activity Templates

### ISSUE THREAD

**Issue by Bjoern3003** [kevinpapst/kimai2#1294]
We have often Projects to offer, with 90% of the same activities.

So it would be nice, we can configure a Template with activities and default entries for project for the first time.
If a User create a new Project, he can select one of the templates and the Project with all his defaults and activities from template will filled out.

This workflow can send a lot of time, if business is using often the same processes for his projects.

**Comment by hmr-it-jr** [comment]
If you have 90 % same activities why don't you use global activities (not allocated to project/customer) then?

**Comment by Bjoern3003** [comment]
Because you have to add each activity to the new Projects. Also all Project values should be filled out by template.

**Comment by hmr-it-jr** [comment]
If you don't allocate an activity to a project it's a global activity which is visible to all projects.

**Comment by Bjoern3003** [comment]
I mean, taht you have to add each activity to each project, if you create a new project. With Templates, you have to add Activities only for one time (on Template creating) to project. After that, the Activities where added by template selection to the new project.

**Comment by hmr-it-jr** [comment]
And I mean that you don't have to add each activity to each project!!!

**Comment by Bjoern3003** [comment]
But this is not, what I want ;-)

**Your Workflow:**
Add X Global Activities

For Each Project:
1.) Create Project
2.) Fill each Form field (and this for each new Project)
3.) After that, you have to search to timetrack in all of global Activities, your needed one. (And this could be a lot, if you work hard with this tool).

**My Workflow**
1.) Create a Project and Fill all fields. Add this as Template
2.) Add my defined Activietes to this Project Template for one time.

For Each Project:
1.) Select the Project Template. Each Form Fields and all Activities added to this new Project with one Mouseclick.
2.) Ready - I can Start to work

And this is my interested, if you have more than one of the same Project Templates.

**Comment by HeinzWuert** [comment]
I believe it would be more helpful to have the possibility to copy an existing project.
In this way you can create an empty project with all relevent settings as unseen master template.
For me it's more important to copy a complete project with same settings.
The copy function would help both of us!

**Comment by kevinpapst** [comment]
@HeinzWuert I think so as well. 
@Bjoern3003 I will close this one here as duplicate in favor of #1246
