### ISSUE TITLE
readjust confirmation box "start / stop time recording"

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1297]
Very often, I want to start a new time recording immediately after I stop the previous time recording (mouse pointer is ready in the upper right corner). However, this is not possible since the confirmation box is still showing confirmation that I have stopped the previous time recording. 

I know it is just a waiting time of a couple of seconds but still: Would it be possible to move the confirmation box to the left so that it won't overlap the menu in the upper left corner?

![pic](https://user-images.githubusercontent.com/51003649/69914995-7289f280-144a-11ea-97d7-eadccb5f05c2.png)

**Comment by infeeeee** [comment]
You can do this very easily with the [custom css plugin](https://www.kimai.org/store/keleo-css-custom-bundle.html).
Just add this css code after you installed the plugin:
```
.swal2-container{
margin-right: 150px;
}
```

**Comment by BeckeBauer** [comment]
so simple, so beautiful 👍 thanks a lot...

**Comment by kevinpapst** [comment]
Should be added to the CustomCSS bundle as pre-defined rule :)
