### ISSUE TITLE
Dashboard: Change tax year from Jan-Dec to Dec-Nov

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1298]
**Is your feature request related to a problem? Please describe.**
The tax office calculates with your income from Jan-Dec.
But a Freelancer needs an overview of his earnings from Dec-Nov because the payment for december will happen in january.
There is a shift of one month.

**Describe the solution you'd like**
New option in Settings to alternate the yearly overview in the dashboard between Jan-Dec and Dec-Nov

**Comment by rarvin** [comment]
In India the tax year is from April to March. An option to make this globally configurable would be good too.

**Comment by HeinzWuert** [comment]
In Germany, income for 2020 consists of times that were generated from December 2019 to the end of November 2020.
This period may be defined differently in other countries.
Idea: Under Settings define the start month from which a calendar year / tax year should begin.
