### ISSUE TITLE
Make kimai:create-user scriptable

### ISSUE THREAD

**Issue by chriscroome** [kevinpapst/kimai2#1299]
It appears that `console kimai:create-user` don't work in non-interactive mode?

```bash

console -n kimai:create-user chris email="chris@webarchitects.co.uk" password="foobar"
13:43:48 ERROR     [console] Error thrown while running command "-n kimai:create-user chris 'email=chris@webarchitects.co.uk' 'password=foobar'". Message: "Return value of App\Command\CreateUserCommand::askForPassword() must be of the type string, null returned" ["exception" => TypeError { …},"command" => "-n kimai:create-user chris 'email=chris@webarchitects.co.uk' 'password=foobar'","message" => "Return value of App\Command\CreateUserCommand::askForPassword() must be of the type string, null returned"]

In CreateUserCommand.php line 167:
                                                                                                             
  Return value of App\Command\CreateUserCommand::askForPassword() must be of the type string, null returned  
                                                                                                             

kimai:create-user [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <username> <email> [<role> [<password>]]
```
I'd like to be able to create the first admin user [via Ansible](https://git.coop/webarch/kimai) without having to resort to using `expect` if possible.

**Comment by kevinpapst** [comment]
RTFM ;-)

```
bin/console kimai:create-user chris chris@webarchitects.co.uk ROLE_SUPER_ADMIN foobar123
```

**Comment by kevinpapst** [comment]
BTW: I never used Ansible, but having a public recipe (or role if that is the ansible wording) is a great idea.

If it is done, can you please share it - eg. in the Kimai documentation?
https://github.com/kimai/www.kimai.org/blob/master/_documentation/installation.md

**Comment by chriscroome** [comment]
Thanks @kevinpapst, would [this addition](https://github.com/chriscroome/www.kimai.org/blob/master/_documentation/installation.md#ansible) be suitable for a pull request?

**Comment by kevinpapst** [comment]
Almost, please move it below FTP installation, then its fine (even though I am not a big fan of commercial links ... no promise that it will stay there forever).

Any chance this check (and the one for update) could be changed:
>          failed_when: ( "Successfully installed Kimai 2 version {{ kimai_version }} " not in kimai_install.stdout )

Who knows if I will change the output at some point. Can you use the exit code?

**Comment by kevinpapst** [comment]
Looks good! Just drop in the PR

**Comment by chriscroome** [comment]
Thanks Kevin, I have simply removed the `failed_when` lines &mdash; if the exit code isn't `0` the tasks will stop at this point without them.

I wouldn't call Webarchitects *commercial*, we have never made a profit, only host good causes, mostly non-prifits and pay terrible wages :roll_eyes:, but remove the hyperlink if you wish :slightly_smiling_face:.

**Comment by kevinpapst** [comment]
In that case you are more than welcome to keep it
