### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1300]
My goal is to have a user who is able to export and invoice timesheets of all users (without being an admin). 

The first step was to create a role "accounting". However, no matter which permission I activated for this role, the user assigned to this role cannot view the timesheets of other users (obviously, I set the permission "view_other_timesheet" to "yes"). 

If I assign the role "admin" to this user, the timesheets are shown. 

As a test, I gave the role "accounting" the same rights like the role "admin" and the timesheets of other users are still not shown. 

I refreshed the cache without success. Any idea?

**Comment by kevinpapst** [comment]
Create a team with all users inside and set the accounting user as teamlead.

**Comment by BeckeBauer** [comment]
That worked, thank you
