### ISSUE TITLE
Invoice: duration format in preview listing

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1301]
**Is your feature request related to a problem? Please describe.**
Duration is displayed as  "9.99 / HH:MM". It would be much nicer to see only one of these redundant informations.

**Describe the solution you'd like**
Config in the Settings menu

**Comment by kevinpapst** [comment]
fixed for 1.7

**Comment by HeinzWuert** [comment]
Please close this fr. There are so many changes in 1.7 to check, if this is still useful.
