### ISSUE TITLE
More Padding? Footer

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#1305]
I cannot reach the lowest tooltip settings

![Bildschirmfoto 2019-12-05 um 15 32 23](https://user-images.githubusercontent.com/18475375/70244387-99129b00-1774-11ea-95bc-4be765005256.png)

**Comment by kevinpapst** [comment]
Duplicates #1219 - please vote there

**Comment by labor4** [comment]
right. scusate.
