### ISSUE TITLE
Translation correct?

### ISSUE THREAD

**Issue by dabenzel** [kevinpapst/kimai2#1306]
Hey, 
I wanna know, if this is correct?
https://github.com/kevinpapst/kimai2/blob/60d16016e85a3b13ccdaecf941c64a7f51112747/translations/system-configuration.de.xliff#L187
Isn't it the same as Ceil then? 
Or should it be `Standard: Start werden nach unten, Ende und Dauer nach oben gerundet`?

**Comment by kevinpapst** [comment]
No, yes, yes 😁 
See https://www.kimai.org/documentation/timesheet.html#rounding-of-begin-end-and-duration
PRs are welcome!

**Comment by dabenzel** [comment]
There you go: #1309

**Comment by kevinpapst** [comment]
Thanks 🚀
