### ISSUE TITLE
Hide Begin / End in "my times" section when duration tracking is active

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#1307]
I think there is an inconsistency between tracking models.

If Timetracking mode [Duration] is set active in the settings, Only Duration can be set in the input field. In the "my times" section, the "begin" and "end" columns are still visible though, which takes away a lot of space for nonsense data and therefore reduces the quality of the user experience.

**Comment by kevinpapst** [comment]
"Duration only" shouldn't show the begin and end time, thats a bug.
Thanks for reporting.
