### ISSUE TITLE
Optimize Time Scheduling more straight forward

### ISSUE THREAD

**Issue by mr2017x** [kevinpapst/kimai2#1311]
Hello and good Evening,

i face the issue, that i have to fill in projects and doings in a new time schedule, but i guess it would be more straight forward, if i have to either fill in customer or (internal) projects/doings, but also have the possibility to fill in the three options, but not need (as i have many customers with work which is no project at all).

Maybe you can discuss and optimize that? Thanks in advance.

**Comment by kevinpapst** [comment]
A timesheet record knows the custom ONLY via the project. The select field in the edit dialog is only a "smart filter" to remove all other projects from the project dropdown box.

I'd say: create a default project for every customer. Maybe that can be simplified by having a checkbox "create default project" in the "create customer" dialog.
