### ISSUE TITLE
Reopen: API: GET Me/UserID doesn't show MetaFields

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#1313]
Reopens https://github.com/kevinpapst/MetaFieldsBundle/issues/24

I think a request like
`{{baseUrl}}/api/users/:id`
or
`{{baseUrl}}/api/users/me`

...should show the User-MetaFields, but doesn't.
It works with all other MetaFields Types (sheets, cust, proj, activity)

**Comment by pbksol** [comment]
I want to bump that request a bit.

Here is a real world example why the MetaFiels are being missed. We use Geofency-Webhooks (an iOS app) to start and stop time recordings when arriving or leaving a site. The transmitted identifier is the device ID which is then mapped to the user and the recording/timesheet.

It would be very helpful to put all allowed devices for each user in a Meta Field for the users and pull the data from there and use it for external processing.

Current solution is to gather the device IDs from another database/system. Having this all in one place would improve the usability a lot.

**Comment by kevinpapst** [comment]
Do you have some time to test the changes in #2905 @labor4 and @pbksol ?

**Comment by kevinpapst** [comment]
I want to bump that PR a bit.

If you would like to see the function in the API, could you please help testing?

**Comment by labor4** [comment]
Hi Kevin
Sorry for keeping you waiting, I'm stuck below a tree trunk near the tax office of Zamonia.

I try to set up an instance to test on Monday.
Which branch has this PR included? "api-user-prefs"?
Or do you run your own public test instance?

Regards
Manu

**Comment by kevinpapst** [comment]
Zamonia as in `Zamonia is the fictional continent where the books of Walter Moers take place`? 

Looking forward for your feedback! If we get it done next week, it will go into 1.16.

**Comment by labor4** [comment]
> Zamonia as in `Zamonia is the fictional continent where the books of Walter Moers take place`?

yes of course ;-)

**Comment by labor4** [comment]
Alright. A little difficult to be really certain, it's been 2 years since, and I made a fresh install.
Maybe @pbksol can answer his/her more complex use case right away, without the install.

**The User Meta Field is "usermeta_test"**

In my other in-use Kimai "1.14.1" there is no ``preferences`` branch an no meta field (though defined)

**So this seems a PASS to me**

User = testuser (ID= 2)

Query: ``/api/users/me``
```
{
  "language": "en",
  "timezone": "Europe/Berlin",
  "preferences": [
    {
      "name": "calendar.initial_view",
      "value": "month"
    },
    {
      "name": "first_weekday",
      "value": "monday"
    },
    {
      "name": "login.initial_view",
      "value": "timesheet"
    },
    {
      "name": "reporting.initial_view",
      "value": "week_by_user"
    },
    {
      "name": "theme.collapsed_sidebar",
      "value": ""
    },
    {
      "name": "theme.layout",
      "value": "fixed"
    },
    {
      "name": "theme.update_browser_title",
      "value": "1"
    },
    {
      "name": "timesheet.daily_stats",
      "value": ""
    },
    {
      "name": "timesheet.export_decimal",
      "value": ""
    },
    {
      "name": "usermeta_test",
      "value": "usermeta_test_default1234"
    }
  ],
  "teams": [],
  "id": 2,
  "alias": "testuser",
  "title": null,
  "avatar": null,
  "memberships": [],
  "username": "testuser",
  "accountNumber": null,
  "enabled": true,
  "roles": [],
  "color": null
}
```

Query ``/api/users/2``
```

{
  "language": "en",
  "timezone": "Europe/Berlin",
  "preferences": [
    {
      "name": "calendar.initial_view",
      "value": "month"
    },
    {
      "name": "first_weekday",
      "value": "monday"
    },
    {
      "name": "login.initial_view",
      "value": "timesheet"
    },
    {
      "name": "reporting.initial_view",
      "value": "week_by_user"
    },
    {
      "name": "theme.collapsed_sidebar",
      "value": ""
    },
    {
      "name": "theme.layout",
      "value": "fixed"
    },
    {
      "name": "theme.update_browser_title",
      "value": "1"
    },
    {
      "name": "timesheet.daily_stats",
      "value": ""
    },
    {
      "name": "timesheet.export_decimal",
      "value": ""
    },
    {
      "name": "usermeta_test",
      "value": "usermeta_test_default1234"
    }
  ],
  "teams": [],
  "id": 2,
  "alias": "testuser",
  "title": null,
  "avatar": null,
  "memberships": [],
  "username": "testuser",
  "accountNumber": null,
  "enabled": true,
  "roles": [],
  "color": null
}

```


Hope this was of help.
M

**Comment by kevinpapst** [comment]
Thanks 👍 

Now that I see it, I think some of the internally defined user-preferences should be hidden.

**Comment by labor4** [comment]
BTW is there an "ERROR: field exists" in place (if important)?

**Comment by kevinpapst** [comment]
I don't get why we would need that in a GET call???

**Comment by labor4** [comment]
right, off topic
