### ISSUE TITLE
Updation fail from 1.5 to 1.6 or higher

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1316]
**Describe the bug**
 While am updating from 1.5 to 1.6 or higher it showing some errors. I had created local.yaml . After this error came., i deleted local.yaml . After deleting also the same error is showing. 

**To Reproduce**
1.git fetch --tags
2.git checkout 1.6.2

**Logfile**
```
No log file created in var/log/ .but I attached the screenshot below.
```

**Screenshots**

![Updation Error](https://user-images.githubusercontent.com/25294547/70435194-30952800-1aac-11ea-9c41-762efcfc28a5.jpg)

**Desktop/Smartphone**
         Windows10

**Additional context**
 - Kimai version : 1.5
 - PHP version : 7.3
 - MariaDB      : 5.5

**Comment by kevinpapst** [comment]
You made changes to the mentioned file and therefor the git update stops.
That is not a Kimai issue, but a pure git issue.
Copy & paste the changes from security.yaml to local.yaml, revert the security.yaml to its original state and redo the update.

**Comment by karthikalsv** [comment]
Thanks alot. It fixed now and working good . 

Its there possible to get attendance with location module or plugin inside kimai.

**Comment by kevinpapst** [comment]
Glad that it works now! The other issue sounds very off topic for this thread.

You can always contact me via email if you want to buy a custom plugin or talk about custom development. Attendance is on my list. There is also a plugin by another developer, I think its in a issue about RFID here at GitHub.

**Comment by karthikalsv** [comment]
Can you please share your email?
