### ISSUE TITLE
Attempted to load class "WebServerBundle"

### ISSUE THREAD

**Issue by canonex** [kevinpapst/kimai2#1318]
During command "composer install --no-dev --optimize-autoloader" I get this error:
```
...
  - Installing twig/extensions (v1.5.4): Downloading (100%)         
  - Installing pagerfanta/pagerfanta (v2.1.3): Downloading (100%)         
  - Installing white-october/pagerfanta-bundle (v1.3.1): Downloading (100%)         
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebServerBundle" from namespace "Symfony\Bundle\WebServerBundle".
!!  Did you forget a "use" statement for another namespace? in /var/www/kimai2/src/Kernel.php:95
!!  Stack trace:
!!  #0 /var/www/kimai2/vendor/symfony/http-kernel/Kernel.php(429): App\Kernel->registerBundles()
!!  #1 /var/www/kimai2/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /var/www/kimai2/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 /var/www/kimai2/bin/console(39): Symfon in /var/www/kimai2/src/Kernel.php on line 95
!!  
Script @auto-scripts was called via post-install-cmd
```

Debian 10.2 - Debian 4.19.67-2+deb10u2
Apache/2.4.38 (Debian)
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Composer version 1.9.1 2019-11-01 17:20:17
Last Kimai2, tagged 1.6.2

**To Reproduce**
I have performed the exact steps as in:
[recommended-setup](https://www.kimai.org/documentation/installation.html#recommended-setup)

No log file has been created.

Thank you,
Rickyx

**Comment by kevinpapst** [comment]
What is your APP_ENV in .env?

**Comment by canonex** [comment]
APP_ENV is set as **dev**

I have set .env as dev as I had a problem with redirect.
If I write:
https://domain.net/ i'm redirected to https://brxkim.dynu.net/it/homepage and I get a 404
if I write
https://domain.net/index.php (and I set APP_ENV as prod) everything works.
I could not figure out why and so I tried to enable debug.

Thank you for the super-fast answer,
Riccardo

**Comment by kevinpapst** [comment]
If you use dev, then Kimai loads other bundles. But you deny these bundles to be loaded:
=> composer install **--no-dev** --optimize-autoloader

Better switch back to prod. 
The redirect is correct, I assume your Webserver configuration is broken/not complete if you see this 404. There are several pages and links in the documentation with examples.

**Comment by canonex** [comment]
Clear, I didn't notice that.

Thank you,
I close the issue, I'll search for configuration problems.

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/webserver-configuration.html
https://www.kimai.org/documentation/fresh-ubuntu-18.html#configure-webserver
https://www.kimai.org/documentation/installation.html#webserver

**Comment by canonex** [comment]
Thank you Kevin, I solved all my issues.
