### ISSUE TITLE
Migration from Kimai to Kimai

### ISSUE THREAD

**Issue by dosch** [kevinpapst/kimai2#1319]
**Is your feature request related to a problem? Please describe.**
I am running an FTP version of Kimai. I would like to move to Yunohost as soon as [that package](https://github.com/YunoHost-Apps/kimai2_ynh/issues/18#issuecomment-560369288) is updated. 

**Describe the solution you'd like**
As soon as I am moving from one Kimai to another, I hope to easily export the data from one instance and import it to a new instance without having to fiddle with MySQL dumps

**Additional context**
If this option is already there but I overlooked then I offer my apologies for being blind and not trying hard enough.

**Comment by acmeraptor** [comment]
This is documentation for migrating from v1 to Kimai2.  I've tested it and it works very well, your versions may be a different than what I've used but it might be some of the documentation that was overlooked (I missed it twice just getting this link for you).  https://www.kimai.org/documentation/migration-v1.html  You will need a mysql id with read access, but it's a straight migration.  Not a dump/export then import.

**Comment by kevinpapst** [comment]
I thought @dosch would mean a self-hosted v2 into a YunoHost v2.
Without version numbers hard to guess.

**Comment by dosch** [comment]
Indeed. My selfhosted (ftp) version is  **1.1 stable (Ayumi)** 
I do not know yet when the port of Yunohost will be updated...

**Comment by kevinpapst** [comment]
I have no idea what would be easier to migrate an app than "fiddling with MySQL dumps".
Export on A (current server) and import on B (YunoHost).

You should upgrade before moving to YunoHost. 
And honestly I cannot recommend YunoHost, as the maintainer seems not be active at all.
Maybe I will remove it from the website...

**Comment by dosch** [comment]
I think the whole purpose of YNH is that you do not have to fiddle with MySQL ;-)

But you are right... the problem with YNH is that there is a limited amount of volunteers doing a lot of the hard work; the project is not really sustainable in its current form. Which is a real pity, cause it allow people like me, who adhere to the self-hosting philosophy, but don't have all the technical skills, to host their own stuff.

Anyway, if I understand you correctly, I will have to look into the documentation of upgrading Kimai in an FTP-only environment, before migrating, but then the point of migrating has disappeared...

**Comment by kevinpapst** [comment]
Reading again, you are currently running FTP version (which means SQLite).
You would first have to migrate your SQLite database to MySQL before you can think about another migration.

**Comment by dosch** [comment]
migrating databases is stuff that scares me... 
Especially when you start looking up [tutorials](https://stackoverflow.com/questions/18671/quick-easy-way-to-migrate-sqlite3-to-mysql) on how to do it...
I think I'll finish my assignments in this kimai instance. Archive it, and start anew in a new instance. 

And I hope that exporting and importing functionality becomes an option for a future version of Kimai

**Comment by kevinpapst** [comment]
I have seen this list in the past, actually it is much easier. 
The thing is: you don't need to convert structure, you only need to export the data in a standard SQL compliant way - this can then be easily imported into an empty Kimai MySQL database.
I can do the conversion for you (paid) if you can't find a working way.

**Comment by jcgruenhage** [comment]
I've seen a few projects over time that had experimental sqlite and productions <something else> support. Most of them included migration script, like [this one](https://github.com/matrix-org/synapse/blob/master/scripts/synapse_port_db) for synapse, which migrates the sqlite db to postgresql cleanly. Would you consider something like this for kimai?

**Comment by kevinpapst** [comment]
I do understand that most users do not fully understand the consequences of their choice (even though there are several warnings in the installation docs) and that they are likely not capable of converting SQLite to MySQL themselves - and I agree that a software should do the best to support them. 
That said: I would integrate it, if somebody would provide it via PR.
And I would consider creating it, if somebody is willing to support the development financially.
But otherwise please understand that my free time is limited and that I am not going to spent it on such a feature.

**Comment by jcgruenhage** [comment]
> I do understand that most users do not fully understand the consequences of their choice (even though there are several warnings in the installation docs)

I think the docs didn't show this warning back when I installed kimai2 (v0.9)

> and that they are likely not capable of converting SQLite to MySQL themselves - and I agree that a software should do the best to support them.

So for now, opening an issue for that, listing it as a feature request with a "help wanted" label would be good?

> But otherwise please understand that my free time is limited and that I am not going to spent it on such a feature.

I can fully understand that, I am in a similar position there. If I had enough free time to do everything I wanted, I'd contribute this myself, but it's not as high of a priority for me either.

**Comment by kevinpapst** [comment]
Is that only for you? In that case you can simply dump the sqlite data eg. with the database tools in your jetbrains IDE.
Re-install your current Kimai version 0.9 (?) with MySQL and the import the dump.
If I remember correct, that should work without problem.
From there you can upgrade to the current version.

**Comment by kevinpapst** [comment]
And yes, you can open a new feature request

**Comment by jcgruenhage** [comment]
> Is that only for you? In that case you can simply dump the sqlite data eg. with the database tools in your jetbrains IDE.

I have this problem, but there's also other people having this problem (as can be seen on this issue). The jetbrains IDEs don't work on my machine for some reason, so I can't use that, but I'd assume the sqlite cli tool can also dump the data so that should be possible too.

> Re-install your current Kimai version 0.9 (?) with MySQL and the import the dump.

I tried to upgrade to v1.8 on sqlite, and that is broken, nothing in the logs (of the container at least) except a 500.

> If I remember correct, that should work without problem.
> From there you can upgrade to the current version.

So migrate to mysql first, then upgrade?

**Comment by kevinpapst** [comment]
Yes, migrate first, then upgrade.
Check var/logs/prod.log, not docker logs.
And read [UPGRADING](https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md) carefully, coming from 0.9 you might need to apply some config changes. Better remove local.yaml before (if you have one).

**Comment by jcgruenhage** [comment]
I tried a few times, but couldn't get it to work the way I wanted, so I now just dropped the old install and started a fresh one.
