### ISSUE TITLE
[API]: GET ​/api​/timesheets with tags produce "Bad Request" error message

### ISSUE THREAD

**Issue by rahulkrishnans** [kevinpapst/kimai2#1322]
**Bug Description**

To get a collection time sheets with same tags, I have used the below API. It produce 404 error message.
`curl -X GET "https://demo.kimai.org/api/timesheets?user=5&customer=3&project=28&activity=323&tags=Illo." -H "accept: application/json" -H "X-AUTH-USER: susan_super" -H "X-AUTH-TOKEN: api_kitten"`

**To Reproduce**

Use the above API in command line or add the below details in `GET ​/api​/timesheets Returns a collection of timesheet records` at https://demo.kimai.org/api/doc
user=5
customer=3
project=28
activity=323
tags=Illo.

**Screenshots**

***Kimai API output with tag***
![kimai_api_output_with_tag](https://user-images.githubusercontent.com/58850570/70881778-adb42600-1ff3-11ea-9fe0-302b573ed2b6.png)

***Kimai API output without tag***
![kimai_api_output_without_tag](https://user-images.githubusercontent.com/58850570/70881788-b4429d80-1ff3-11ea-99e8-ee7c987fddfb.png)

**Comment by kevinpapst** [comment]
```{
    "code": 400,
    "message": "Parameter \"tags\" of value \"test.\" violated a constraint \"Parameter 'tags' value, does not match requirements '[a-zA-Z0-9 \\-,]+'\""
}```
Not entirely sure if the API is wrong or the frontend, that allows `.` is tag names. 
But I guess for BC reasons, the API needs to be changed.

I don't mind a PR for that:
https://github.com/kevinpapst/kimai2/blob/master/src/API/TimesheetController.php#L128

**Comment by kevinpapst** [comment]
fixed in master

**Comment by rahulkrishnans** [comment]
Thank you for the fix @kevinpapst.
