### ISSUE TITLE
Time Tracker Using UTC and not Locale Time

### ISSUE THREAD

**Issue by Cable-Billing** [kevinpapst/kimai2#1323]
The first time a user records a time in thier times it uses UTC instead of locale time. After the first one it uses locale time. I'm using Australia/Adeliade as the users time zones. I have changed the time format to 12 hour, however this issue was occuring before changing it.

**To Reproduce**
1. Create a user
2. Record time (using Time Clock timetracking mode)

**Screenshots**
![times](https://user-images.githubusercontent.com/15027282/70903329-98b8b080-204e-11ea-95df-52066297f148.jpg)
![server](https://user-images.githubusercontent.com/15027282/70903244-5f804080-204e-11ea-8730-bcabc48b9c10.PNG)
![permissions-and-extensions](https://user-images.githubusercontent.com/15027282/70903248-60b16d80-204e-11ea-9d87-0ba831d5aa59.PNG)
![php](https://user-images.githubusercontent.com/15027282/70903250-61e29a80-204e-11ea-89bd-0774f2a478c3.PNG)

**Comment by kevinpapst** [comment]
Did you change the timezone in the users profile before creating the first record? 
I just tested and **cannot** confirm the bug in master.

**Comment by Cable-Billing** [comment]
Yes all the users had the correct timezone. So PHP needs to be configured for the timezone? It doesn't get the time from the system that it is running on?

**Comment by kevinpapst** [comment]
PHP itself has a timezone setting, which is used when the user has no explicit timezone setting. 
I don't know what is going on, but it is **highly recommended**, that you always configure your PHP to have a date.timezone setting: https://www.php.net/manual/en/function.date-default-timezone-get.php

If you can give me any more information how to reproduce this problem, please let me know and I will reopen here
