### ISSUE TITLE
Main Page Problem 

### ISSUE THREAD

**Issue by Hav3q** [kevinpapst/kimai2#1328]
Hello,

i think what i have is a small problem but i am still stuck and don't know where the problem ist. -.-

Tried it on ubuntu 16 and 18 and got the same result.

Webpage shows me this 

load(__DIR__.'/../.env'); } $env = $_SERVER['APP_ENV'] ?? 'prod'; $debug = $_SERVER['APP_DEBUG'] ?? ('prod' !== $env); if ($debug) { umask(0000); Debug::enable(); } if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? false) { Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST); } if ($trustedHosts = $_SERVER['TRUSTED_HOSTS'] ?? false) { Request::setTrustedHosts(explode(',', $trustedHosts)); } $kernel = new Kernel($env, $debug); $request = Request::createFromGlobals(); $response = $kernel->handle($request); $response->send(); $kernel->terminate($request, $response); 

Would realy be nice if someone can tell me where my problem ist. 

thank you

**Comment by kevinpapst** [comment]
You need to configure your webserver to run PHP scripts.
Currently the file is only sent to your browser without executing the application.

https://www.kimai.org/documentation/fresh-ubuntu-18.html
https://www.kimai.org/documentation/webserver-configuration.html
https://symfony.com/doc/current/setup/web_server_configuration.html

If you can't figure out how to configure your server, I offer paid support.
I am closing this issue as this is not a Kimai problem.
