### ISSUE TITLE
Duration mode: enter a value as minutes, not seconds

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#1329]
**Is your feature request related to a problem? Please describe.**
I've spotted the file src\Utils\Duration.php, which is of great added value, since it converts duration strings into seconds. In other words, entering, lets say *30* in the duration field, wil be accepted and converted in 30 seconds.

Although this might be of practical use for some businesses, precision by seconds is in our time records not used. For our way of time registration it would be much more convenient to convert these loose numbers into minutes, not seconds. Currently, if we want to register, lets say, 45 minutes, we need to type *0:45*. typing just *45* wil only register 45 seconds.

**Describe the solution you'd like**
Convert duration strings into minutes by changing the Duration.php file accordingly.

Creating the option in the configurations tab is also fine, off course, if both the options *convert to seconds* and *convert to minutes* need to be possible, depending on the needs of the company in question.

**Describe alternatives you've considered**
For a test, I manipulated the Duration.php file by changing the fraction from seconds to minutes. I edited
*$hour = floor($seconds / 3600);*  
*$minute = floor(($seconds / 60) % 60);*

into
*$hour = floor($seconds / 60);*  
*$minute = floor(($seconds / 1) % 1);*

This, surprisingly did the trick, duration strings were converted to minutes, but, expectedly, was to simple as a fix, since all the times (also the ones already present) were multiplied by 60, making it look as we had been working sixty times harder :-).

Do you agree that it would be more useful to use conversion to minutes, instead of seconds for duration input?

If so, do you know in what way the Duration.php file needs to be edited in order to have te desired effect? Or do you see other possibilities to add this feature?

Many thanks

Willem

**Comment by kevinpapst** [comment]
A lot of changes/improvements has been applied to the handling of the duration field, please see #2264

Your exact idea is currently not possible. But you could write 0.75 or 45m instead. If you enter 45 this would be 45 hours.

You can test it at https://demo-branch.kimai.org (eg. with `susan_super` and `kitten`).

**Comment by 1willem** [comment]
Thanks for the tip and the improvements, Kevin.
