### ISSUE TITLE
Move loader icon to viewport

### ISSUE THREAD

**Issue by strouble** [kevinpapst/kimai2#1330]
Just a tiny improvement: move the spinning loader icon to the viewport of the user.
When i scroll down to the pagination, i just see a "blank" (transparent) page. Changing this

https://github.com/kevinpapst/kimai2/blob/54255cf923546ad483d6ee399a13f2547e15e0be/assets/sass/datatable.scss#L12

to `position: fixed;` would be nicer.

**Comment by kevinpapst** [comment]
Nice idea, I'll try that

**Comment by kevinpapst** [comment]
Looks much better, will be included in 1.7.
Thanks for the suggestion 👍
