### ISSUE TITLE
User and Team API

### ISSUE THREAD

**Issue by kbancerz** [kevinpapst/kimai2#1331]
Hi,

I would love to see Kimai being capable of not only exposing user and team data over API, but to also allow creation/modification of these entities through REST. I am aware of a very similar issue posted some time ago - #977. However the author wasn't able to point to any use-case, other than a preference of REST over e.g. LDAP of someone on his team.

As for myself I actually do have a couple of reasons for wanting to create users and teams with API:
1. The nature of the users of Kimai in my organization - they are not employees strictly speaking, so their information cannot not be kept in user directories we use (rather in CRM). Making a new directory just for them would be a possibility, but it's not so trivial if you take GDPR into consideration - we are trying to reduce the number of databases containing personal data, and creating an intermediate directory, used just for the integration purposes seems like an overkill. Still, we would love to automate it as much, as we can.
2. I haven't found any information on how to create/modify teams and maintain membership in them using LDAP. Also, afaik API allows only getting and deleting of teams - there are no methods for creating/modifying them. There are also no methods for adding and removing members. This one is crucial, because we need to control the access to different customers' data - specifically, a user having access to one project, should not be able to even see any other customers, projects etc.

I have thought about using OS-level commands for user creation, but this still leaves the issue of the teams, and not being able to maintain those in any way.

Would it be possible for the addition of the create/modify/delete methods for users and teams to be reconsidered as a new feature in one of the next releases?

Thanks!

**Comment by kevinpapst** [comment]
Thanks for the detailed request and explanation!

Sure, expanding the API is always on my list, its crucial for the business.

If you use it in your company, you could also speak to your management - maybe they want to sponsor this feature?! It would likely speed up the integration as well...
