### ISSUE TITLE
unable to create schema in symfony while authentication

### ISSUE THREAD

**Issue by Saahilvrma** [kevinpapst/kimai2#1334]
bin/console doctrine:schema:create 

 !                                                                              
 ! [CAUTION] This operation should not be executed in a production environment! 
 !                                                                              

 Creating database schema...

In ToolsException.php line 34:
                                                                               
  Schema-Tool failed with Error 'An exception occurred in driver: could not f  
  ind driver' while executing DDL: CREATE TABLE like_new (id INTEGER PRIMARY   
  KEY AUTOINCREMENT NOT NULL, new_name VARCHAR(255) NOT NULL, new_age INTEGER  
   NOT NULL, slug VARCHAR(255) NOT NULL)                                       
                                                                               

In AbstractSQLiteDriver.php line 70:
                                                          
  An exception occurred in driver: could not find driver  
                                                          

In PDOConnection.php line 31:
                         
  could not find driver  
                         

In PDOConnection.php line 27:
                         
  could not find driver  
                         

doctrine:schema:create [--dump-sql] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by kevinpapst** [comment]
Your PHP has no SQLite support. Switch to MySQL.
