### ISSUE TITLE
Import SQLite DB to MySQL

### ISSUE THREAD

**Issue by schreckag** [kevinpapst/kimai2#1339]
**Describe the bug**
I install kimai2 local via prebuild FTP package. I used Kimai for a couple of month. Now I install Kimai on my shared server with your preferred installation procedure via ssh. The Plan is to use MySql as DB. I install Version 1.3 (the same Version I use local) the setup was successful. I exported the sqlite DB with "DB Browser for SQLite" as xxx.sql. I try to import that xxx.sql via phpMyAdmin, but it stopped with an Error(screenshot). How can I import SQlite DB to MySQL?

**Screenshots**
<img width="1099" alt="Bildschirmfoto 2019-12-30 um 19 42 19" src="https://user-images.githubusercontent.com/59319409/71595589-8eadac00-2b3c-11ea-9455-9b0e505304b3.png">

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [MacBook]
 - OS: [OSX 10.15]
 - Browser [ chrome, safari]

**Additional context**
 - Kimai version 1.3
 - PHP version 7.2.

**Comment by kevinpapst** [comment]
SQLite and MySQL are not fully compatible.
I would install Kimai 1.3 on your server and ONLY export and import the data.

Before you start Export the empty MYSQL structure (1).

Now:
- Import the data from SQLite

If that fails:
- Remove the failing statement (like begin transaction & end transaction)
- Delete all tables
- Import the structure from (1)
- Retry to import

**Comment by schreckag** [comment]
That was my thought, but the Import fails.
I am currently considering importing the necessary tables via csv. My Hope was, you know "easy way" ;). Do you mean, that earlier versions of Kimai (e.g. 1.2) contain less Problems with the DB Structure ?

**Comment by kevinpapst** [comment]
> Do you mean, that earlier versions of Kimai (e.g. 1.2) contain less Problems with the DB Structure ?

No, it's not about the version, it's about the incompatibilities between these two databases. 
Try another tool for the data export, maybe that works better. 

I already imported data from SQLite to MySQL, but that always includes manual steps.

**Comment by schreckag** [comment]
I'll try, thx a lot and happy coding

**Comment by kevinpapst** [comment]
This is not a real Kimai problem, you can find a lot of ideas (and even online converters) around the Internet when you search for this "problem", eg.

https://www.google.com/search?q=migrate+from+sqlite+to+mysql

**Comment by schreckag** [comment]
> This is not a real Kimai problem

I agree

**Comment by schreckag** [comment]
I exported the created DB, copied the entries (from the SQLite) with an editor (brackets), deleted the DB on the server. Then I imported the created DB.

**Comment by kevinpapst** [comment]
Thanks for the feedback
