### ISSUE TITLE
Search results stay empty

### ISSUE THREAD

**Issue by itrtimrear** [kevinpapst/kimai2#1341]
New installation of kimai2. After creating some entries and search for them (enter whatever timerange) there are no results.

"No entries were found based on your selected filters." Even there are matched records...

Same problem I already described in #1333

**Comment by kevinpapst** [comment]
As it works on the demo, so it must be an environment specific problem.
I can't help without more input.

What database system are you using? 
Please export the complete database structure and let me see it. 
What storage engine is used? 
What collation is used?
Whats in the logs?

**Comment by kevinpapst** [comment]
Which exact version did you install?

**Comment by kevinpapst** [comment]
If you installed master, then there could be a problem with missing timezone information in MySQL.
This will be changed back for 1.7, as it is not yet required.

Please have a look here:
https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md#17

You need to execute the scripts mentioned on this page:
https://mariadb.com/kb/en/library/mysql_tzinfo_to_sql/

ping @itrtimrear & @derchirurg

**Comment by kevinpapst** [comment]
You could retry with latest master or wait for 1.7, which will be available soon
