### ISSUE TITLE
No login possible after clean install

### ISSUE THREAD

**Issue by kreutho** [kevinpapst/kimai2#1342]
I installed Kimai 1.6.2 in a Website within ISPConfig. I followed the instructions from the website using git and composer and everything went fine. I'm able to open the login page but I can't log in - im redirected to the login page. Registering a new user doesn't work as well but I can see, that the communication with the database is working because I can't register a user with the same name of an existing user. After submitting the form I receive the following error:
"Der CSRF-Token ist ungültig. Versuchen Sie bitte das Formular erneut zu senden."

Any help is aprreciated.

Best regards,
Thorsten

**Comment by kevinpapst** [comment]
delete all cookies and reload the page.
you can have a look in var/logs/prod.log as well, maybe an error shows up.

**Comment by kreutho** [comment]
Tried it with different browsers - same result.
And there is no file in prod.log, the logs-dir is empty...

**Comment by kevinpapst** [comment]
Did you make sure that the permission are correct?
See https://www.kimai.org/documentation/installation.html#recommended-setup

If the session directory is not writable, this error will also happen.

**Comment by kreutho** [comment]
I had to adapt the documentation to my environment, e.g. give permissions to my specific user in the ISPConfig/fastcgi-setting instead of www-data. 
But I can see files in the sessions-directory and with every try to login a new one is created

**Comment by kevinpapst** [comment]
If a new session file is created on every login, something is definitely wrong.
PHP can't find/read the session and creates a new one. This new session doesn't know the security token (CSRF) and the login fails.
Deactivate session and caching plugins that may come with ispconfig.

**Comment by kreutho** [comment]
There aren't such plugins. But concerning the paths - maybe there could be the problem: ISPConfig creates the webspace automatically and there is a folder "web" which is the document root. I installed Kimai into this directory and used an apache directive to change the document root to web/public. Could this be the problem?

**Comment by kevinpapst** [comment]
Check If the file public/.htaccess is compatible with your Apache version.
Check if ispconfig has any php session related setting. Make sure it doesn't write session to redis over or alike.
Check if you have anything in your php or webserver logs.

Besides that, I have no clue. 
Environment specific problems have to be solved on your end, sorry, but this is not a Kimai bug.

**Comment by lowraxe** [comment]
I'm having a similar issue. I installed using Softaculous on my host. The login page comes up and I can log in using the administrator credentials entered in the Softaculous install. However, any data that I enter in after that first login does not "stick" in the web interface, though I can see that it does appear in the database by looking at phpMyAdmin directly.

After I logout the first time, I then can no longer log in. I get the same result of no error message, just a redirect right back to the login page. If I try to register a new user at that point, I get the CSRF-token message.

The program looks like just what I need, but I'm getting hung up on this login issue. Any help is greatly appreciated! Thanks!

**Comment by kevinpapst** [comment]
I have no clue what Softaculous is doing during the install. Can you try to install it manually?

**Comment by lowraxe** [comment]
Looking into that now, but the fact that I can log in successfully indicates to me that the install is OK. There just seems to be some problem with the program communicating with the database properly. The only part from the recommended setup that I couldn't do was chown -R :www-data . Might that be the issue?

Thanks for your quick response!

**Comment by lowraxe** [comment]
OK, I went through the official installation process. I started into the initial setup of company, project, and activity. Everything is making it into the database, but none of it shows up in the main interface.

Under the Doctor tool, everything is OK, except that in logfile, I get the message "Could not find logfile: var/log/prod.log.

And after I log out, I end up with same result of being unable to log in, as well as the CSRF message when trying to register a new account.

Not sure what I might be missing here. I've tried installing directly on a Synology NAS also and got pretty similar results.

**Comment by lowraxe** [comment]
Just another update - I went back and logged in successfully to the installation after leaving it dormant for a while and the data I had entered previously was in there. I then tried to add some more information, and had the same result - it went into the database, but wouldn't show up in the web interface. It's like there's a very delayed reaction between the interface and the database. Any thoughts?

**Comment by kevinpapst** [comment]
No, Kimai does nothing like that. Does this happen in every screen? Like customers, projects, system configuration ,user preferences ... or only for timesheets?

**Comment by lowraxe** [comment]
It happens on all the screens. I just went to log in again after it being dormant for a few hours. After logging out it went back to returning me to the login screen every time I try to log in.

I'm not sure what to do. It's very strange, as everything goes right into the database, but the interface just doesn't seem to want to update consistently.

I should note that when I did the most recent install, I did complete the chown command correctly.

**Comment by kevinpapst** [comment]
Sounds very strange. Talk to your hoster, maybe they use database replication for load balancing and something is off there. You could have look in your logs in var/logs/prod.log if something is in there.
I have no idea, but I can tell you this is definitely not normal behavior and is related to your environment and setup, with which I can't really help. This is not a Kimai bug.

**Comment by lowraxe** [comment]
That was another odd thing. There was no prod.log file after the initial install. I created the file in the folder, but forgot to change the permissions until just now, so it only now started actually writing data to the file. I'll keep checking back on it and let you know what I find, but I note that I just did the failed login a couple of times and nothing wrote to the file. The last error that showed up in the file was an uncaught PHP exception, but I think it was related to entering the wrong password on a previous login attempt.

**Comment by kevinpapst** [comment]
Are you sure all permission are correct? If Kimai can't write in all the documented directories recursively, you can't login as well.

**Comment by lowraxe** [comment]
I followed the instructions on the installation page:

chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
chmod -R g+rw public/avatars/

except that I used my database username instead of www-data. Is there something else I'm missing?

**Comment by kevinpapst** [comment]
You need to use the username of the webserver

**Comment by acmeraptor** [comment]
Just FYI, I have installed it successfully and still have no prod.log file.

Even on my own self hosted system, I had to use sudo for all the chmod commands for it to work correctly and thoroughly.

If you switch your .env setting from

###> symfony/framework-bundle ###
APP_ENV=prod

to

###> symfony/framework-bundle ###
APP_ENV=dev

It will provide a LOT of debugging info that can help, if you can read it

~acme

**Comment by lowraxe** [comment]
The group name of the webserver/php process should be the same as my cpanel username, right?

**Comment by kevinpapst** [comment]
I don't know. That depends on your system and has nothing to do with Kimai

**Comment by lowraxe** [comment]
OK, I'll ask my host about this a bit more, but as I said, I've done this three different ways - on my host following the official directions, on my host using Softaculous, and on my Synology NAS. That's three different environments where I'm getting the same results, so I don't see that it's environment specific. The original poster hasn't been active on this thread since last week, but he was experiencing the same thing on yet another environment. I'd be curious to know if he ended up getting it resolved some other way.

**Comment by kevinpapst** [comment]
Yep, I've read that and there are hundreds of people without that problem and I myself manage quite a few customer systems. So I am confident, that this is not a general problem. 
Whatever happens on your systems is nothing that I can debug from here.

**Comment by lowraxe** [comment]
I understand that. I just thought it was possible you or someone else on the forum had seen something similar in the past or had some idea of where I might be messing something up. I'll get with my host on it and play around with it some more, and I might hit you up for paid support if I don't get it resolved on my own soon.

Thanks for your effort on the software and your help here!

**Comment by kevinpapst** [comment]
Regarding the login problem, up until now it was always one of: 
- A hard coded "PHP plugin" that moved session to a redis cache (strange hosting environment)
- Invalid filesystem permissions (do you see files in var/sessions/ ?)
- Is there always a new file for page reloads?
- If there is nothing in Kimai log, try to change the env as @acmeraptor proposed: you need to do a composer reinstall WITHOUT '--no-dev'
- Check your PHP / Server logs

**Comment by lowraxe** [comment]
I asked the webhost through a chat. The response on the PHP plugin was that if I haven't actively installed any such thing, it wouldn't be there (and I haven't)
There's only a .gitkeep file in var/sessions, but there's also a prod/ folder which contains files. When I log in or out the contents of that folder change (files appear and disappear)
Since I went through the permissions process correctly, the log file has been working. I haven't taken the time to try to understand what's going on in it, but it doesn't appear that anything changes when I have a failed login.

**Comment by kevinpapst** [comment]
There should be files in var/session/prod/.
Out of curiosity please execute a `chmod -R 777 var/`, just to find out if it is a permission issue.

**Comment by lowraxe** [comment]
I've been doing the permissions through FileZilla since they didn't seem to be sticking in SSH, but I just went to change them again to 777 and they keep going back to 775. But that just means there's no public write access. That shouldn't be a problem, should it? Owner and Group can still write to it.

BTW, there are files in var/session/prod. They're just not consistently appearing based on actions taken on the web interface.

**Comment by acmeraptor** [comment]
It does sound like permission issues I have had.  You said the chmod command didn't work, are you able to do it with sudo authority?  I had to use sudo on my own file system on my own home server for the permissions to propegate correctly.

**Comment by kreutho** [comment]
Ok, now I had some spare time again and did the installation process from scratch.

The main problem ist still there - but at least I have entries in the prod.log and I am able to login using a private/incognito window. Any ideas about that are appreciated - I think I have to test some php settings....

**Comment by kevinpapst** [comment]
If it works in private mode, you better check your browser plugins use another browser.

**Comment by kreutho** [comment]
Firefox 72.0.2 general tab not working
Firefox 72.0.2 private tab is working fine
Chrome 79.0.3945.130 general tab not working
Chrome 79.0.3945.130 incognito tab is working fine
Internet Explorer 11.592.18352.0 is working fine
Opera 66.0.3515.36 is working fine
Microsoft Edge 79.0.309.71 is working fine

Despite Firefox no browser has any plugins installed...

**Comment by kreutho** [comment]
Ok, everything is running now. I had to manually clear all caches, history etc. but at last it's running now. From my sind this issue could be closed...

Thanks and best regards!
