### ISSUE TITLE
All pages blank on clean install through Softaculous

### ISSUE THREAD

**Issue by aeboi80** [kevinpapst/kimai2#1344]
Installed through Softaculous in cPanel and upon visiting https://ticktock.example.com/public/ and http://ticktock.example.com/public/en/login both pages load as blank white pages.

**Comment by kevinpapst** [comment]
Aha, logs?

**Comment by aeboi80** [comment]
Apache log is simply showing

`XXX.XXX.XXX.XXX - - [02/Jan/2020:11:23:56 -0500] "GET /.well-known/pki-validation/F8186CE0E9D25B2DE2FDD4A92DC453C2.txt HTTP/1.1" 200 64 "-" "COMODO DCV"
XXX.XXX.XXX.XXX - - [02/Jan/2020:11:23:57 -0500] "GET /.well-known/pki-validation/FBCCFD8DF9FEA3F54C4024120DF8CA23.txt HTTP/1.1" 200 82 "-" "COMODO DCV"
XXX.XXX.XXX.XXX - - [02/Jan/2020:11:23:57 -0500] "GET /.well-known/pki-validation/FBCCFD8DF9FEA3F54C4024120DF8CA23.txt HTTP/1.1" 200 82 "-" "COMODO DCV"
XXX.XXX.XXX.XXX - - [02/Jan/2020:11:29:44 -0500] "GET /public/en/login HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
XXX.XXX.XXX.XXX - - [02/Jan/2020:11:29:44 -0500] "GET /favicon.ico HTTP/1.1" 404 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
XXX.XXX.XXX.XXX - - [02/Jan/2020:11:29:49 -0500] "GET /public/en/login HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
`

/var/log within kimai is empty

**Comment by kevinpapst** [comment]
This is the access log, don't you have an additional error log?
I never used cPanel, maybe the permissions are incorrect, check the installation/update docs.

**Comment by kevinpapst** [comment]
No feedback, closing
