### ISSUE TITLE
"Custom Fields" not found in any one of the demo sites.

### ISSUE THREAD

**Issue by rahulkrishnans** [kevinpapst/kimai2#1345]
**Bug description**
I would like to check the features of "Custom Fields". But to create and test it, the facility is missing in both stable and development demo sites. Kindly check.

**Screenshot**
Logged in as admin in stable demo site, but the facility not found.

![kimai_demo_admin](https://user-images.githubusercontent.com/58850570/71711656-f65b4400-2e27-11ea-8747-0878241dd09f.png)

**Comment by infeeeee** [comment]
The custom fields plugin is available in the "Plugins" demo. Just login as susan_super or admin.

**Comment by kevinpapst** [comment]
https://www.kimai.org/demo/

<img width="1197" alt="Bildschirmfoto 2020-01-03 um 11 39 56" src="https://user-images.githubusercontent.com/533162/71721314-e68e3080-2e24-11ea-9f54-358a0e769455.png">

**Comment by rahulkrishnans** [comment]
Yeah! I missed that. Thanks a lot.
