### ISSUE TITLE
A little more help regarding adding Exports and adjusting the Dashboard

### ISSUE THREAD

**Issue by softdch** [kevinpapst/kimai2#1347]
Hi there, 
I've been using Kimai with Version 0.9.1 (what i guess is called Kimai v1) for almost ten years now and actually I would still be completely happy with that version except that my web hosting probably won't support PHP version 5.6 anymore within a year und this Kimai version doesn't seem to run under PHP 7.

In that old version it was for instance much easier to type in start and end time (e.g. I could just type 8 and 12.15, now in Kimai 2 I always have to type hh:mm or select date and time via drop-down). I also copied one of the export forms and adjusted it for my own purpose under the old version. 

When I now read the documentation regarding «Adding export renderer» or «Dashboard» and Widgets I don't understand what I need to do.  

**Adding Export Renderer**
I copied the file PDFRenderer.php in /public_html/kimai2/src/Export/Base and pdf.html.twig in /public_html/kimai2/templates/export/renderer, but nothing happens yet. The documentation says: 

> All you need to do is to register it as a service in the Symfony DI container.

But I have no idea how to do so. Is there somewhere a description that is a little bit more detailed? I haven't had to deal with Symfony so far and am more the Windows guy.

**Dashboard and Widgets** 
The documentation says:

> Widgets can be defined in the configuration node kimai.widgets.

What does this mean? Is this a file I need to edit or add? SSH?

I would appreciate any help and more detailed descriptions regarding above topics.

Regards
Stefan

**Comment by kevinpapst** [comment]
If you are happy with Kimai 1, you could upgrade to its latest release which has support for PHP 7.

**Comment by softdch** [comment]
@kevinpapst thank you for you reply and suggestion :)

I wasn't aware that there was a version comaptible with PHP 7. I actually tried updating to version 1.1.0 a couple years ago but wasn't happy with the result (some ui layout issues).

Since I already have done all the work of installing Kimai 2 (1.6.2), transferred all the data via SQL (phpMyAdmin) and tracked most of December only in this new installation, it makes more since to stick to this anyway. So, I'd still hope to get some hints on adding exports and widgets.

**Comment by softdch** [comment]
Hello @kevinpapst, I modified some of the Invoice templates but am still not really happy with them. Now I adjusted the existing PDF Export (instead of adding a new one since I still don't understand how to do so) and actually this is pretty close to what I need. There's one thing still missing though. In the summary (Zusammenfassung) I would like see totals per Project **and** Activity.
![grafik](https://user-images.githubusercontent.com/59471465/73663740-69addb00-469e-11ea-8175-26a630eb7523.png)
Within the same project I could actually have entries with different rates (e.g. development and travel time). Any hint how I could achieve this?

**Comment by softdch** [comment]
Was finally yet able doing it myself by copying and adjusting the summary block from default.html.twig into the pdf.html.twig. 

![grafik](https://user-images.githubusercontent.com/59471465/73728562-d9ba7080-4733-11ea-914e-d0a6ebbf909a.png)

Thank you

**Comment by kevinpapst** [comment]
Thats great!
Even though, you should really use invoice templates for that what you are doing.

**Comment by softdch** [comment]
but the invoice twigs don't seem to consider page breaks and printing out of the browser needs quite some adjustments. The Word doc could have worked, but I rather want a PDF right away. This is only an attachment that I send to the customer together with the invoice ;)

**Comment by kevinpapst** [comment]
Invoices in 1.9 now support PDFs as well, see documentation.
And with #1582 (also in 1.9) you can store custom exporter templates in `var/export/`.
Don't forget to copy your patched template there before the update!
