### ISSUE TITLE
"Create new time-record" does not sync start time with last time record

### ISSUE THREAD

**Issue by Tobias4872** [kevinpapst/kimai2#1348]
**Describe the bug**
Let's assume I have been working on a task and have recorded my time with the "Play" button on the top right of the application. Let's further assume it is now 2.00pm and I want to switch to a new task. I am using the "Create new time-record" option of the "Play" button dropdown and the editor for the new time record opens, setting the start time to 2.00pm. Let's also assume the setup of the new time-record takes me a while because I am adding a detailed description (let's say 5 minutes). What happens now is that when I hit "Save", the end time of the previous time record is set to 2.05pm (time of saving), but the start time of the new record is still set to 2.00pm. This means, that I am recording the 5 minutes between 2.00pm and 2.05pm twice for both time-records.

**To Reproduce**
1. Start a new time record via the "Play" button. Wait a bit.
2. Click on the "Play" button and select the "Create new time-record" from the dropdown.
3. Wait a bit on the "Create" screen and then hit save.
4. You will notice that the end time of the last time record is after the begin time of the new time record.

**Desired Behaviour**
It would be great if the end time of the previous time record and the begin time of the next record could be sync'ed with each other.

**Comment by kevinpapst** [comment]
Synching the times is not a good idea, but something like a "now" checkbox (which would deactivate the start field) could work. I like the idea!

**Comment by Tobias4872** [comment]
Thanks for looking into this.

A similar problem appears when you use the "Start again" functionality. Sometimes the new time record starts a minute before the old time record ends, e.g. new time record starts at 9:23, but the stopped time record ends at 9:24.

**Comment by kevinpapst** [comment]
If that matters to you, deactivate rounding for start and end times (set to 0). 
See documentation for timesheets.

**Comment by kevinpapst** [comment]
I don't think there is a viable option how that should be handled that works for everyone. 
Can you describe a solution that feels right for you?
