### ISSUE TITLE
Softaculous installation upgrade

### ISSUE THREAD

**Issue by phleva** [kevinpapst/kimai2#1350]
Hi, I have a working Kimai v2 (release is 1.5) installed through Softaculous.
Been using Kimai v1 as well and successfully ported all data from v1 to v2.

As v2 is under active deveIopment, I would like to upgrade my installation to the lastest stable release. I contacted Softaculous to ask if they have an upgrade script available and was told that there was none available and that I should do the upgrade through CLI and your instructions.
However, my installation was NOT acquired with git commands and instructions outlined here: https://www.kimai.org/documentation/updates.html would not work...

Am I missing something?
Could anyone provide insight on how to do that?

Thank you,

**Comment by kevinpapst** [comment]
Clone it via Git, instead of creating the .env file copy your current .env to the new directory, run the updater.
And create backups before 😁

**Comment by phleva** [comment]
Hi Kevin,

I managed to perform the update.

For the record:
- git clone
- update per instructions https://www.kimai.org/documentation/updates.html
- permissions had to be modified afterwards for group (-w) using "chmod -R g-w ."
Though I had the following error during the update script everything seems to be working as expected.
`Migration 20191113132640 was executed but did not result in any SQL statements.`
Please tell me if this can be an issue.

Note that following the update and accessing the Softaculous panel, I was asked to update the records so the correct version is now shown in my Softaculous installations. I should probably have installed kimai2 manually instead of using the so called one click installation... ;-)

Thank you for your help.

**Comment by kevinpapst** [comment]
Awesome, thanks for your feedback!
Not every migration changes stuff, some check data/structure and only fix it if necessary.
I'd say: if you have the knowledge, always go with the documented installation.
