### ISSUE TITLE
mpdf v7.1.9 requires php ... does not 7.4.1

### ISSUE THREAD

**Issue by DanSman** [kevinpapst/kimai2#1352]
Hi

I have a problem with the installation of Kimai2 on Arch with PHP 7.4.1. 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mpdf/mpdf v7.1.9 -> satisfiable by mpdf/mpdf[v7.1.9].
    - mpdf/mpdf v7.1.9 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.1) does not satisfy that requirement.
```

Are there any news for 7.4.1 support?

Thanks
Dan

**Comment by kevinpapst** [comment]
Never tried PHP 7.4. The message you posted is coming from pdf: https://github.com/mpdf/mpdf/commit/92200411ef05f0957c7a01e9f9f939bec6b68fdf

Seems they fixed it, but that means bumping it to version 8:
https://github.com/mpdf/mpdf/releases
I need to check if that is possible for the next release.

ping @hmr-it-jr please check the mpdf release notes, you mentioned that you are using the qrcode logic from the package?

**Comment by hmr-it-jr** [comment]
@kevinpapst thanks for mentioning! You can upgrade it. I generate them with Javascript on the clientside.
