### ISSUE TITLE
Is it possible to install Kimai on XAMPP?

### ISSUE THREAD

**Issue by PayShop** [kevinpapst/kimai2#1354]
Hello,

I'm having some problems installing Kimai Development Version on XAMPP. I want to try it and show it to some coworkers so I wanted to create my own account and all.
Should I do this on a VM? Or is it possible to do it on XAMPP?

Best regards!

**Comment by kevinpapst** [comment]
You could use the demo if you only want to show it to some people.

It is completely up to you how you do the setup. You can use VM, Docker, XAMPP, LAMP, Local webserver...

**Comment by PayShop** [comment]
Thank you for replying so fast again!
I wanted to install myself, but I guess I will have to go with the live demo. I tried with XAMPP and Docker, none worked. I thought it would be simple, but I was missing something basic for sure.

**Comment by kevinpapst** [comment]
Well it is not as simple as Wordpress. And "simple" always depends on your knowledge about the technology stack.
I am sure, if you co-worker like it, we find a way to install it properly!

**Comment by acmeraptor** [comment]
@PayShop I can offer you a guide, and it is only a guide!  I made a VM from scratch to use Kimai2 with Ubuntu 18.04.3 install disk/iso.  When it gets to tasksel, I only added openssh.  And here is the guide that I have written up so far: https://wiki.casperbb.com/view/Wyvt-rsksolutions.  If you have any issues with this, please take it up with me.  Kevin has no control over what I wrote, but hopefully it helps you and I can answer any questions that you may have.

**Comment by Arterter** [comment]
@acmeraptor hi men , i have tried to install the kimai via installation guide on their page but not successful, and i follow your step guide, and i got further but i am getting error in database.
i am on virtual machine with ubuntu
this is the error
ERROR] Failed to create database: An exception occurred in driver:           
         SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost'      
         (using password: YES)
if you could help step by step i would be appreciated thx man
