### ISSUE TITLE
Installation not writing to database

### ISSUE THREAD

**Issue by pablo-cyc** [kevinpapst/kimai2#1356]
Please excuse me writing about this here, I'm not sure if this is the right place. It's my first time here and I have no clue if I'm asking my issues to the right audience here either...

**Describe the bug**
I have installed kimai2. It basically works, I can login, create users, clients, jobs... But when I go find my sql database which I have connected during installation, there are not even tables in there. I have no idea where the data goes. Is there a way to find anywhere in my installation?

Can you help? 
What details would you need from me in order to be able to help...?

Thanks so much!

**Comment by kevinpapst** [comment]
You are likely using the SQLite database at var/data/kimai.sqlite
Check your .env file, which database is active.

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by pablo-cyc** [comment]
Sorry, thanks for your advice! I found the string, changed it and ran 
bin/console kimai:install -n

This is the reply from the system (I've changed the user to 'xx'):


[WARNING] Some commands could not be registered:                               
                                                                                

In ConnectionFactory.php line 79:
                                                                               
  An exception occured while establishing a connection to figure out your pla  
  tform version.                                                               
  You can circumvent this by setting a 'server_version' configuration value    
                                                                               
  For further information have a look at:                                      
  https://github.com/doctrine/DoctrineBundle/issues/673                        
                                                                               

In AbstractMySQLDriver.php line 93:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  
  ser 'xx'@'localhost' (using password: YES)                             
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'xx'@'localhost' (using  
   password: YES)                                                              
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'xx'@'localhost' (using  
   password: YES)                                                              
                                                                               


In ConnectionFactory.php line 79:
                                                                               
  An exception occured while establishing a connection to figure out your pla  
  tform version.                                                               
  You can circumvent this by setting a 'server_version' configuration value    
                                                                               
  For further information have a look at:                                      
  https://github.com/doctrine/DoctrineBundle/issues/673                        
                                                                               

In AbstractMySQLDriver.php line 93:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  
  ser 'xx'@'localhost' (using password: YES)                             
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'xx'@'localhost' (using  
   password: YES)                                                              
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'xx'@'localhost' (using  
   password: YES)

**Comment by kevinpapst** [comment]
Pretty clear error message:

**Comment by pablo-cyc** [comment]
'xx' ist wrong, I know (as I mentioned above, I've chnaged this here for you in order not to see my real username I've been using), but this error message came with the correct username.

**Comment by kevinpapst** [comment]
I don't care about the xx. If it tells you that it can't connect to the database, then you have to fix your connection string. Probably its the host `localhost` instead of `127.0.0.1`.

**Comment by pablo-cyc** [comment]
Nope, it's not. Same story.

**Comment by pablo-cyc** [comment]
Installation now successful, after a problem with the mysql user ( "%" instead of "localhost" won't work). Thanks for helping!
