### ISSUE TITLE
Selection of multiple workers/customers/projects/activities and display the time of it

### ISSUE THREAD

**Issue by DanSman** [kevinpapst/kimai2#1357]
Hi

I am still a Kimai v1 user. I checked the new version of Kimai again today. 

I am a painter and I use a lot of activities (281). Sometimes I need to know the specific time of a worker / project / client and the activity.

Example:
&nbsp;

# Project one - Ceilings and Walls
## Customer
Kevin Papst

## Activities:
- ceiling: first coat
- ceiling: second coat
- ceiling: sanding
- ceiling: priming
- ceiling: ...

Same for walls.

## Workers
DanSman
Ryan

&nbsp;

# Project two - Exterior walls
## Customer
Harry Wijnvoord

## Activities:
- masking up: window frames
- masking up: switches
- masking up: ...

## Activities:
- weatherboards: first coat
- weatherboards: second coat
- ...

## Workers
Claudia
Kimai

&nbsp;

Is it possible like with Kimai v1, to get only the times of 1 customer / 2 employees / 1 project / 12 activities?

Thanks
Dan

**Comment by kevinpapst** [comment]
Hi Dan, unfortunately you cannot select multiple activities yet for filtering.

**Comment by DanSman** [comment]
Ah, okay. Do you want me to keep the issue open?

**Comment by kevinpapst** [comment]
I am pretty sure there are some issues regarding multi select. Please have a quick look and vote for them on their initial post via the 👍 reaction. 
If you don't find one, keep it - otherwise close it as duplicate and set a link.

**Comment by DanSman** [comment]
I took a quick look, but the only similar thing was that #1292. I'll leave it open for now, if it's okay for you.

**Comment by kevinpapst** [comment]
Searching for "multi" brought up #1055 as well

**Comment by DanSman** [comment]
Yeah, I have seen that too, but I thought it was too different from my request.

**Comment by kevinpapst** [comment]
You can test #1157 - it adds multi-select for customer/project/activity in most screens.

The only exception are invoices, as an invoice targets one customer exclusively.
