### ISSUE TITLE
Installation problem: App/Kernel not found

### ISSUE THREAD

**Issue by winnewoerp** [kevinpapst/kimai2#1358]
Hi Kevin,

first of all: Thanks for Kimai! I use Kimai1 since many years now. Regarding my planned update to Kimai2: I'm new to SSH and all this command line stuff. So sorry for a newbie question and an issue that is probably not a basic Kimai2 problem, but might have to to with Composer and Symfony. I managed to get until this point following your step by step guide and my webhoster's guides for SSH, Git, and Composer:

`bin/console kimai:install -n`

However, I get this error message when trying to install:

```
Fatal error: Uncaught Error: Class 'App\Kernel' not found in /www/htdocs/w00dc564/kimai2/bin/console:38
Stack trace:
#0 {main}
  thrown in /www/htdocs/w00dc564/kimai2/bin/console on line 38
```

Any hints leading to resolving the problem are more than welcome!

Thanks and kind regards
winnewoerp

**Comment by kevinpapst** [comment]
Hi @winnewoerp !
You need to execute every step explained here: 
https://www.kimai.org/documentation/installation.html

The error sounds as if you did not run composer:
composer install --no-dev --optimize-autoloader

**Comment by winnewoerp** [comment]
Thank you. But this does not seem to be the problem. I already installed the Composer during my first installation attempt. When I run the respective command line, I get the following response:

```
*****@*********:/www/htdocs/*********$ composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
```
First I thought that the issue could be related to this topic:
[Symfony3: Fatal error: Class 'AppKernel' not found in .\bin\console](https://stackoverflow.com/questions/36286998/symfony3-fatal-error-class-appkernel-not-found-in-bin-console)
But I did not find a solution. Do you have any other idea?

winnewoerp

**Comment by kevinpapst** [comment]
You could try to move line 12 to line 3:
https://github.com/kevinpapst/kimai2/blob/master/bin/console#L12
But I doubt that it will change anything...

**Comment by winnewoerp** [comment]
OK, I though I had the solution. I have to be inside the "kimai2" directory for this step

`composer install --no-dev --optimize-autoloader`

right?

I uninstalled composer, symfony etc. and re-installed it in kimai2 directory. After installing /symfony/framework-bundle I get the following error:

`PHP Fatal error:  Class 'Symfony\Component\Console\Application' not found in /www/htdocs/w00dc564/kimai2/vendor/symfony/framework-bundle/Console/Application.php on line 30

Fatal error: Class 'Symfony\Component\Console\Application' not found in /www/htdocs/w00dc564/kimai2/vendor/symfony/framework-bundle/Console/Application.php on line 30`

I must say that I work with PHP quite often, but unfortunately I don't use classes much...

**Comment by kevinpapst** [comment]
Wrong PHP version? Or a broken composer cache. Try `composer clear-cache` and then retry the installation. Sorry, but I can't really help with these environment specific issues.

**Comment by winnewoerp** [comment]
Thanks, I will try that!
