### ISSUE TITLE
Global setting for numbers

### ISSUE THREAD

**Issue by simonschaufi** [kevinpapst/kimai2#136]
## Description

We need a global administration for numbers. We don't need everything but the numbers we definitely need are:

- invoice number

![grafik](https://user-images.githubusercontent.com/941794/36065295-df9b1dfe-0e98-11e8-836f-f1186a46f726.png)

![grafik](https://user-images.githubusercontent.com/941794/36065297-efddc98c-0e98-11e8-8771-0dc2abfe8b12.png)

**Comment by kevinpapst** [comment]
The oldest feature request in this repo is finally in work.
All features from the screenshot are possible!
