### ISSUE TITLE
Open PDF export in broawser instead of downloading it

### ISSUE THREAD

**Issue by Kantime** [kevinpapst/kimai2#1360]
Hi,

I'd like to see the generated PDF inside a window of my browser instead of having to download it.

Is there a way to obtain this behavior by modifing a file or it is more complicated than that ?

Thank's for the help.

**Comment by kevinpapst** [comment]
You could try to change this line:
https://github.com/kevinpapst/kimai2/blob/master/src/Export/Base/PDFRenderer.php#L70
from 
```
        $disposition = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, 'kimai-export.pdf');
```
to 
```
        $disposition = $response->headers->makeDisposition(ResponseHeaderBag::DISPOSITION_INLINE, 'kimai-export.pdf');
```
Maybe you need to rebuild the cache (check update docs for example).

**Comment by Kantime** [comment]
It worked perfectly !

Thank you 3000 😃
