### ISSUE TITLE
Stundensatz im Projekt für Abrechnung mit customer

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1361]
**Is your feature request related to a problem? Please describe.**
Der Betreiber von Kimai sitzt in der Mitte von Auftraggeber (Customer) und Mitarbeiter (User).
Für den Mitarbeiter sind Stundenlöhne in allen Bereichen gut einstellbar.
Der Abrechnungsstundensatz gegenüber dem Customer ist aber, so wie das sehe, nirgendwo erfassbar.
Damit ist eine automatsierte Abrechnung nicht möglich.

**Describe the solution you'd like**
Ein zusätzliches Datenfeld für den Abrechnungssatz gegenüber dem Customer, welches im Projekt eingebunden sein müsste.

**Comment by kreutho** [comment]
I'd like to have a structure with costs and turnover. The turnover should be adjustable for projects and activities (e.g. development can be more expensive than content management). That would be perfect. In the current design I can just use the timesheet - I can't use it for neither invoices nor profit calculation. Any chance that this will be available at some time?

**Comment by HeinzWuert** [comment]
I added missing data fields with the addon Metafields.
The calculations are done via Invoices> Excel export

**Comment by kreutho** [comment]
I don't know - in Kimai v1 it was possible, to make a reference between an acitivity and an user (via group). I used this so every user could see only the activities he was allowed to use and I could set the rate for the activity. In v2 the activity is just related to the project, so if I'd set up two activites for two users, they both would see both activities. So there is a chance they take the wrong one - and I'd have to double-check every entry before creating an invoice. There is a description of the activity, that could be used to reduce the danger of a wrong entry being taken, but the user can't see the description...

**Comment by HeinzWuert** [comment]
What does that have to do with the original posting?

**Comment by kreutho** [comment]
You asked for a relation between projects and customer rates - that is exactly what I want. The last topic described my workaround in Kimai v1, which is not possible anymore...
