### ISSUE TITLE
Project end - default time should be 23:59

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1363]
**Is your feature request related to a problem? Please describe.**
Projektende beinhaltet die falsche Uhrzeit

**Describe the solution you'd like**
Wenn man das Projektende (Datum) eingibt geht man vom Ende des Tages aus.
Aktuell wird aber beim Projektende immer im Zeitpicker 0:00 als Uhzeit eingetragen, womit das Projekt schon einen Tag früher endet.
Per default sollte der Zeitpicker auf 23:59 stehen.

**Comment by kevinpapst** [comment]
Wieso nicht das Projekt einfach einen Tag später enden lassen?
23.12 23:59:59 oder 24.12 00 ist ein Unterschied von einer Sekunde.
Und rein logisch betrachtet ist ja auch erst in der 00 Sekunde das Projekt vorbei.

**Comment by HeinzWuert** [comment]
Logisch gesehen ja, im Umgang mit Zeit und Datum denkt der Mensch aber anders.
Wenn etwas endet spricht man immer von dem Tag(Datum) an dem es vorbei ist. Dieser Tag endet dann um 23:59. Intuitiv ticken wir alle so und genau deswegen ist das jetzige Verhalten von Kimai eine potentielle Fehlerquelle,

**Comment by kevinpapst** [comment]
Ich schließe das Ticket weil der Punkt nicht eindeutig zu klären ist.
