### ISSUE TITLE
Option to diplay the total amount when printing a report

### ISSUE THREAD

**Issue by Kantime** [kevinpapst/kimai2#1365]
Hi,

In Export, when you clic on the Print button, the HTML report offers you to enable or disable some options to dispay or not.

In the summuary you can not choose to make invisible the calculated total amount. It is only possible for the detailed table.

Is it possible to modify a file in order to add the option for the summary table because i don't always need to print the amounts. Only the hours ?

Many thank's for any help.

**Comment by kevinpapst** [comment]
Hey @Kantime - thanks for the idea. I will include that in the next release.

**Comment by kevinpapst** [comment]
@Kantime you could test the changes from here: https://github.com/kevinpapst/kimai2/pull/1370/files and let me know if they work for you

**Comment by Kantime** [comment]
Thank you very much ! It works perfectly.

Same options for generated PDFs would be a must 😃
