### ISSUE TITLE
Export Renderer

### ISSUE THREAD

**Issue by cjk2** [kevinpapst/kimai2#1366]
Although I found the description about the possible export renderers. But I'm a bit on the edge. Is there a more detailed description or an example how to implement it?
I simply do not need certain columns in the Excel export and others (e.g. the address of the customer) I need in the export.

**Comment by softdch** [comment]
Hello cjk2, I also try figuring out how to adjust export (see #1347). I started with copying a couple files and would like to modify these copies, but I'm not sure whether I picked the right files and how to register the export with Symfony. Do you try altering the original files? Which file(s) are you working on?

**Comment by cjk2** [comment]
I tried that with several files. Lastly with the files in src/Export/Base and src/Export/Renderer and Co. But somehow the export doesn't work. I can adjust invoices very easily. But export to tables/Excel doesn't work. 
For example, if I knew what to do with "Each renderer is represented by a "button" below the datatable on the export screen." or where exactly this should be configured????!!!
Especially the sentence "All you need to do is to register it as a service in the Symfony DI container. I'm not a specialist and would really appreciate a tip!

**Comment by kevinpapst** [comment]
The thing is: an export is typically not meant to produce good looking document (even though the PDF does), but it should simply dump the raw data to be used by another system.

I am myself thinking about a way to simplify that for the user/admin. But until then, you have to build a custom plugin to add a new exporter. 

If you could tell me what you want to achieve exactly, I might be able to give you a better advice.

Including the customer address doesn't make a lot of sense from my point of view. 
The exporter dumps lines of timesheet records, (possibly) belonging to different customers, so the address would be repeated in every single line.

**Comment by cjk2** [comment]
That sounds very good, that the export should be basically simplified ;-)

I don't need a "nice" export, but I need an export to process the data in another system. Therefore also. the customer address in the record. 

Ideally, the export would look like that for each customer a row (also CSV) with columns (totals) for the respective activity (preparation, travel time, consultation, follow-up etc.) in a certain period of time (determined when filtering the data to be exported) would be available in the file. 

An export using the Invoice function cannot do this. Therefore I came to the topic export. Only one PlugIn exceeds my abilities by far ;-)

**Comment by kevinpapst** [comment]
1.9 supports export templates, but they do not allow to generate reports on the fly for each activity.

What you want to achieve is a rather special use-case, which needs a plugin.
There are people offering paid services around Kimai, see the developers in the Marketplace.

Closing here, as writing exporter for every possible situation is impossible.
