### ISSUE TITLE
2 instances of kimai on same server

### ISSUE THREAD

**Issue by popo24-24** [kevinpapst/kimai2#1367]
hello,

i should try to configure 2 instances of kimai on the same server.
the firt 1, i can connect to login interface.
The second, i receive an error : bad gateway.
My problem is about the nginx configurations.

here, the kimai conf (defaut)

`
server` {

   listen 80;
    server_name kimai2.dev;
    listen [::]:80;

    root /var/www/kimai2/public;
    index index.php;

    access_log off;
    log_not_found off;

    location ~ /\.ht {
        deny all;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/run/php/php7.3-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi.conf;
        fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/..:/tmp/";
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}

the seconf website:
`server {
    listen 8080;
    listen [::]:8080 ;
    server_name cci.dev;
    root /var/www/kimai3/public;
    index index.php;

    access_log off;
    log_not_found off;

    location ~ /\.ht {
        deny all;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi.conf;
        fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/..:/tmp/";
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
`

i don't understand how to configure 2 server blocks for nginx.
Need your help !

**Comment by infeeeee** [comment]
(This is not a kimai problem but an nginx problem, so you shouldn't post it here)

On your second server you use a port and a server_name. It should be enough to use port 80 on both of them, and server_name will handle everything. You will access one on kimai.dev, the other one on cci.dev.

Add this to the server directive to create separate logs for the two servers with different paths:
```
error_log /var/log/nginx/kimai_error.log;
access_log /var/log/nginx/kimai_access.log;
```
This way you can check what's going on.

**Comment by kevinpapst** [comment]
Good hint, thanks @infeeeee - closing
