### ISSUE TITLE
Export time in decimal format

### ISSUE THREAD

**Issue by camaer** [kevinpapst/kimai2#1368]
**Is your feature request related to a problem? Please describe.**
In Kimai v1 when exporting the hours we had the option to have it in decimal time. I cannot find this option in v2.

**Describe the solution you'd like**
The same checkbox that would allow us to export the hours in decimal format.

**Describe alternatives you've considered**
Manually calculating it

**Additional context**
Here's a picture of the option from v1 when exporting 

![kimai time decimal](https://i.imgur.com/BlJk2PU.jpg)

**Comment by kevinpapst** [comment]
Which esport are you talking about here?
There are many different types of export:
- invoices (support decimal with the next version)
- export from the left menu
- timesheet exports

**Comment by camaer** [comment]
Sorry, it's in the timesheet section I was referring to.
