### ISSUE TITLE
Can't find .env file

### ISSUE THREAD

**Issue by 2BCAD** [kevinpapst/kimai2#1369]
**Describe the bug**
Maybe it is just because I am not an Linux expert but I'm running into a problem with the installation. I followed the documentation and am at the point where it says that you need to modify the .env file. Unfortunately I am not able to find that file.
Any idea of what I am missing?
I use an Ubuntu 18.04 on a linux station.

**To Reproduce**
3. See error

**Logfile**
```
Add the last lines from your logfile at var/log/prod.log, around the time when the problem happened.
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s]

**Additional context**
 - Kimai version
 - PHP version

**Comment by kevinpapst** [comment]
It will be created once you run the composer install command from the docs.
You can see it when you type in `ls -la`

**Comment by kevinpapst** [comment]
Does it work?

**Comment by 2BCAD** [comment]
> Does it work?

Hi. Yes it worked! The installation is set up.

Thanks!
