### ISSUE TITLE
Kein <CRLF> im Datenfeld Customer Adress bei Rechnungen

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1373]
**Describe the bug**
Adresseingabe unter Customer mit 2 oder mehr Zeilen untereinander
Nutzt man diese Variable ${customer.address} zum Export in Excel steht der Inhalt der Variable in einer Zeile ohne Zeilenumbruch und ist so nicht mehr verwendbar.

**Additional context**
 - Kimai version 1.62

**Comment by kevinpapst** [comment]
Export != Invoice

Did you configure the cell to keep line breaks?

**Comment by HeinzWuert** [comment]
Despite the line break, two lines in Kimai result in only one line in Excel, despite the default line break.
Solution: You have to connect as many rows in Excel as <CRLF> were used in CustomAdress. Then it works.
Thanks for the tip!

**Comment by kevinpapst** [comment]
Sounds like a workaround, I need to check if there is something required on PHP side:

For example something [like this](https://stackoverflow.com/questions/43834343/phpexcel-new-line-in-cell):
```
$worksheet->getStyles()->getAlignment()->setWrapText(true);
```

**Comment by HeinzWuert** [comment]
My solution works, but a clean function out of Kimai is always the best!

**Comment by kevinpapst** [comment]
The solution in #1507 now sets the row height to the amount of lines. 
This will likely "break" existing templates, at least they will look strange after the update.
