### ISSUE TITLE
Report function for project progress

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1374]
In larger teams, it would be helpful if important informations could be recorded.
These reports should contain the creator and date.
This could be a large text field that is assigned to the creator, but visible to all team members.
The entire report should be exportable / printable.

This function could be part of the meta fields.

**Comment by kevinpapst** [comment]
Can you have a look at the latest changes for 1.7 at https://demo-branch.kimai.org/

Especially the customer and project pages. When you click in the lists on an entry, you come to the new detail page.

This new page will display the budget report, lets you configure team access (one click to add a default team for a new customer/project) and also adds a "comment" section. These comments allow arbitrary text length and support markdown formatting and auto link formatting. These comments can be pinned to the top and also deleted afterwards (and they contain a date and the author).

**Comment by HeinzWuert** [comment]
had a quick view, looks great!
This means, the menu Projects must be visible for all users to see the comment section and every entry can be seen by all team members, right?

I still lack a simple calculation of the remaining quota based on the number of weeks remaining until the end of project. Than it's perfect!

**Comment by kevinpapst** [comment]
There are new permissions available for comments and detail fields.
If those are given to regular users, they can see them.

**Comment by HeinzWuert** [comment]
If the restriction works only for the team and all other users are off than it's perfect!

**Comment by kevinpapst** [comment]
Yes, there are 3 different access levels for these informations:
- admin like: can see the infos for all projects
- teamlead: can see the infos for the projects/customers where the user is teamlead 
- team member: can see the infos for the projects/customers where the user is in an assigned team

If that makes any sense, not easy to explain in a short sentence.

**Comment by HeinzWuert** [comment]
Everything is said! Thanks a lot, seems to be perfect ;-)

**Comment by kevinpapst** [comment]
These comments support Markdown formats (like here on Github)  and markdown removes simple line breaks.
But thanks for the info, I changed line break handling, as this is not intuitive for normal users.
