### ISSUE TITLE
Skin settings with no effect

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#1375]
Should the skins in the settings be working? I would like to switch to a dark theme (like skin-black), but whatever I select, nothing changes...

**Comment by kevinpapst** [comment]
Works perfectly fine since the moment the feature was added.
Test it in the demo.
The changes ONLY affect the header and menu, nothing else.

**Comment by VOOM108** [comment]
Now I remember, it used to work, but does not any more. I was looking for a real dark theme, so it doesn't matter anyway. ;) (I have it open on the third monitor while working and I prefer to have the monitors I am not actively working on as dark as possible...)

**Comment by kevinpapst** [comment]
Weird that it doesn't work for you. Anything in the logs?

**Comment by VOOM108** [comment]
I have a weird configuration, so I think we can close this issue. I might investigate some later time. 

Are there any plans though to add real dark themes? I have an addon in Firefox that turns virtually any page dark - Kimai 2 looks perfect that way. But I want to use it in Ferdi (a fork of Franz) and it does not support addons / extensions. Ferdi has a universal dark mode, but that does not work for Kimai 2, makes it unusable. Maybe I'll find the time to build some css upon that dark mode to make it work for Kimai 2, until then I'll use it in the browser...

**Comment by kevinpapst** [comment]
Would be nice, indeed.
But the theme used by Kimai is an open source bundle (with custom modifications for Kimai).
If they release a dark version, I am happy to incorporate that, but until now I haven't read anything about it. 
I'll close here, if you want to find out what's wrong with your preferences, just open a new issue.
