### ISSUE TITLE
Advanced customizations (by code) like in FOSUserBundle

### ISSUE THREAD

**Issue by lduer** [kevinpapst/kimai2#1376]
**Is your feature request related to a problem? Please describe.**
In my point of view, Kimai already has a high number uf customization options for many different use cases. 

Kimai grew a lot, since my last issue about plugins (#437) and now, I'm working on some plugins, which I'll release soon. For plugins (improved plugin possiblities) and my use case, I want to go deeper into the customizations  (custom form & template adaptions, ... ). I want to suggest advanced features which will allow to customize forms and templates via configuration (local.yaml/kimai.yaml). The Classes then can be embedded into the Plugins and codebase of kimai doesn't need to be touched.

This idea is from FOSUserBundle, which shares the [possibilities of form customization here](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_forms.rst). See the [configuration here](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/Configuration.php#L141)

Additionally, in the FOSUserBundle the reusable controllers have [dispachers for special events](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/RegistrationController.php#L62), which could be added to the controllers to handle events from external plugins.

**Additional context**
My actual usecase for this suggestion is my issue #571 where I want a custom timesheet form (For me and my users, the datetimepicker is not suitable)

I want to discuss this topic here and I'm working on a PR with some code examples mentioned above.

**Comment by lduer** [comment]
After some code examples and testing, I found out that it's even easier than I thought. I haven't kept in mind, that the plugins are loaded after the code in `./src`. 

If I use the same route settings in the controller, i can create a new controller file, extend e.g. `App\Controller\TimesheetController` where the work for different forms, templates and settings is already done and I only need to redefine e.g. the `getCreateFormClassName()` 

Nevetheless, PR and Plugins are coming ;)

**Comment by kevinpapst** [comment]
The last point is nothing I plan to actively support. Especially as I began marking classes as final (when I touch them) and variables and functions as private... so it is not future proof as well.

I am extending the plugin infrastructure piece by piece when I need something for my plugins or customers, so there is for sure a lot of things that can be improved. Lets see what you have in mind

**Comment by kevinpapst** [comment]
> Nevetheless, PR and Plugins are coming ;)

did you make any progress here @lduer ?

**Comment by lduer** [comment]
Yes! :) because of time shortage, the bundles are still in dev mode. 

Here is the one with "overwriting the Controller-functions": https://github.com/lduer/CustomTimesheetFormBundle

Another plugin for improved "clock-in" on mobile is hosted on gitlab(private) because I haven't had time to move it to github. I want to publish it under MIT license too.

**Note**: Plugin is used and tested in Kimai 1.6 only - updates are in progress.

**Comment by kevinpapst** [comment]
I totally appreciate any kind of contribution and I'd love to see code examples and ideas.

But this seems like an open discussion that ended without a solution, so I am closing here.
