### ISSUE TITLE
when using EXPORT the checkbox of metafields is always on

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1377]
Kimai saves the choice of datafields for displaying and exporting.
But this does not happen with metafields. These are always marked as visible. 
For every export you have to uncheck the unwanted metafields.
Better choice would be to uncheck the metafields as default.

Version 1.62

**Comment by rarvin** [comment]
I think then this woiuld affect the users who need then to be checked always. Better option would be to have a favourite or default user preference.

**Comment by HeinzWuert** [comment]
I wrote; 
Better choice would be to uncheck the metafields **as default**.

**Comment by kevinpapst** [comment]
As you see: one group wants them to be on, the other group to be off.
There is no perfect preset and I will not add settings for that.
Maybe a cookie could be used to save the last setting client side.

**Comment by kevinpapst** [comment]
I added a cookie storage for the selected fields, so every time you open the print export  you will have the same fields active like last time - see https://github.com/kevinpapst/kimai2/pull/2445
