### ISSUE TITLE
separating bills between admin and user

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1380]
**Is your feature request related to a problem? Please describe.**
In Kimai, all Excel sheets are in the same INVOICES directory.
This means that not only admins have access to all files located there, but also every user.
This means that users can also see "prohibited" invoice forms for the client.

**Describe the solution you'd like**
It would be better under Invoices another directory, which only Admin / Sys-Admin has access to, where their invoice templates can be found.

**Comment by kevinpapst** [comment]
I have no plans on extending this functionality by now and there was no vote yet, closing.
There is always the possibility to add such a feature via plugin
