### ISSUE TITLE
changing behavior of + symbol when creating a project

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1381]
**Is your feature request related to a problem? Please describe.**
In our use, the customer turns a major project into successive projects with a different contingent and project duration.
It would improve the workflow if you could simply copy existing projects.
So you could also create recurring projects as a template.

**Describe the solution you'd like**
With the + symbol a new, empty project is created.
Select an existing project and with + symbol a copy will be createt.
All data are accepted, except for the start and end date of the new project.
The team of the selected project should also be taken over.

**Comment by infeeeee** [comment]
Maybe a better UX would be to add a 'Duplicate' option in the Actions menu. This duplicate button would open the new project dialog but already filled with the data from the duplicated project.

**Comment by kevinpapst** [comment]
Depends on the use-case:
- do you want to carry over only the project settings: then pop-up
- do you want to re-assign all applied teams and activities: then only a button
  - or extending from that: a button that opens a new modal where you can choose which data should be copied?

**Comment by HeinzWuert** [comment]
In my case all project settings including teams. The only thing that will change is
- sure project start and end
- possibly the time quota

Copy using the action button is a good solution!.
Perhaps Popup is the ideal solution, since all the variants you mentioned could be available here.
