### ISSUE TITLE
Invoice filter: Mandatory field Customer change to mandatory field Date

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1383]
**Is your feature request related to a problem? Please describe.**
We have several customers and many users have several projects with them.
Unfortunately, the user cannot create an overall invoice for all of them.
The result are several invoices and no total over all.

**Describe the solution you'd like**
Change of the mandatory field from customer to date in invoice filter.

**Comment by kevinpapst** [comment]
The complete concept of invoices is based on a single customer => won't fix.
