### ISSUE TITLE
Add RequestStack to ThemeEvent

### ISSUE THREAD

**Issue by lduer** [kevinpapst/kimai2#1385]
**Is your feature request related to a problem? Please describe.**
I'm working on a plugin where some javascripts are added via `ThemeEventSubscriber`. I don't need this actions on all kimai pages, so I thought about adding the `RequestStack` to the Constructor in the [`ThemeEvent`](https://github.com/kevinpapst/kimai2/blob/master/src/Event/ThemeEvent.php).

@kevinpapst I want to know your plans with this subscriber? I ask because of [L49](https://github.com/kevinpapst/kimai2/blob/master/src/Event/ThemeEvent.php#L49) with "`ThemeEvent::getUser()` will be removed in 2.0.

**Describe the solution you'd like**
I could provide a PR with the Request as constructor-argument (for the service `EventExtension` and the event). Can I add it like this:

``` 
    public function __construct(?User $user = null, $payload = null, Request $request = null)
```

**Comment by kevinpapst** [comment]
I don't think this is necessary. 

Let the Symfony container inject the RequestStack in your listener, eg: 
https://github.com/kevinpapst/kimai2/blob/master/src/Utils/LocaleSettings.php#L30

What do you think?

**Comment by lduer** [comment]
OK. true. I'm sorry for disturbing 🤦‍♂ - previousy already added two services to my listener and haven't thought about that. 

Thanks 👍 😄

**Comment by kevinpapst** [comment]
Ah no problem, I like developer discussions - much better than the 100 time being asked about wrong file permissions after an update ^^
