### ISSUE TITLE
Renaming of Office-files while exporting

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1392]
**Is your feature request related to a problem? Please describe.**
When exporting to Excel or Word, Kimai always creates an identical file name, which is given a count number for redundancy.

**Describe the solution you'd like**
Use e.g. when creating the file name User_Customer_Project as a universal name.

**Comment by lduer** [comment]
... and maybe add the date of the export too (something like 2020-01-19_user_customer_project)?

**Comment by kevinpapst** [comment]
I changed the invoice file naming, which seemed most important to me.
Which export are you guys talking about?

**Comment by HeinzWuert** [comment]
Invoices became more important for us than Export. If u changed there the behavior great.
Maybe the use of the same rules for Export is enough!?

**Comment by kevinpapst** [comment]
Well the timesheet user export is simple, but the export from the team timesheet screen and the export screen don't necessarily have a customer in their query. Thats why its easier in the invoice section. But without I could use something like "date_export" or "date_user_export".

**Comment by HeinzWuert** [comment]
I would prefer the last suggestion

**Comment by HeinzWuert** [comment]
**update:**
When exporting a lot of files via Excel you are loosing the overwiew about the contents.
Helpful would be variables for
- user
- project
- date
- invoice-no
as components of the filename.

**Comment by kevinpapst** [comment]
Closing. The filename was changed (didn't hear any feedback for a long time) and PDF templates can define the filename now, so developers are able to change them dynamically.
