### ISSUE TITLE
404 Not found 

### ISSUE THREAD

**Issue by sofiendamiP** [kevinpapst/kimai2#1395]
I can't seem to get kimai2 up and running:

I followed the installation documentation, But I used for my document root /var/www/kimai-dev
when I now go to my website and then go to kimai2/public I get a 404 Not Found error
Kimai2/public redirects me to kimai2/public/en/homepage

Apache/2.4.38 (Debian) Server
PHP Version 7.3.11-1

**Comment by kevinpapst** [comment]
You are not allowed to have public/ in your URL. 
Your document root must point to public/.

Read the webserver docs: 
https://www.kimai.org/documentation/webserver-configuration.html

This is a pure configuration issue, not a Kimai problem.

**Comment by sofiendamiP** [comment]
I have now this code in my default.conf but it is still not working
`<VirtualHost *:80>
    ServerName kimai-dev.vision11.net
    ServerAlias www.kimai-dev.vision11.net

    DocumentRoot /var/www/kimai-dev/kimai2/public
    <Directory /var/www/kimai-dev/kimai2/public>
        AllowOverride All

        # If you see an error like the following in your logs:
        # AH01630: client denied by server configuration: /var/www/kimai2/public/
        # then you might have to exchange the "Order/Allow" rules with "Require" (see below)
        # More infos at https://httpd.apache.org/docs/2.4/de/upgrading.html

        # Apache 2.2
        Order Allow,Deny
        Allow from All
        
        # Apache 2.4
        # Require all granted

        FallbackResource /index.php
    </Directory>

    <Directory /var/www/kimai-dev/kimai2>
        Options FollowSymlinks
    </Directory>

    # optionally disable the fallback resource for the asset directories
    # which will allow Apache to return a 404 error when files are
    # not found instead of passing the request to Symfony
    <Directory /var/www/kimai-dev/kimai2/public/bundles>
        FallbackResource disabled
    </Directory>
    
    ErrorLog /var/log/kimai_error.log
    CustomLog /var/log/kimai_access.log combined

    # optionally set the value of the environment variables used in the application
    #SetEnv APP_ENV prod
    #SetEnv APP_SECRET <app-secret-id>
    #SetEnv DATABASE_URL "mysql://db_user:db_pass@host:3306/db_name"
</VirtualHost>
`

**Comment by kevinpapst** [comment]
Is it `/var/www/kimai-dev/kimai2/public` or `/var/www/kimai-dev/public` ?

What does `apachectl -v` say? 
Nowadays you often have to use the rule for Apache 2.4 and not 2.2

**Comment by sofiendamiP** [comment]
I have Apache 2.4

**Comment by kevinpapst** [comment]
Good, then change the rules:
```
   # Apache 2.2
   #  Order Allow,Deny
    # Allow from All
    
    # Apache 2.4
    Require all granted
```

**Comment by sofiendamiP** [comment]
It sill didn't work
