### ISSUE TITLE
Kimai permissions are not consistent when creating a new group with identical rights

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1400]
**Describe the bug**
Permissions are not consistent when creating a new group with rights of the standard groups of Kimai

**To Reproduce**
A new group was created
The group was assigned identical rights to those of the admin
Effect: The user with the new group rights (like Admin) cannot select user names under, for example, export. The selection field remains empty.

**Comment by kevinpapst** [comment]
Admins and Super-Admins are special groups and treated different internally. They are not bound to team permissions and can see all content, no matter what their team assignments look like.

Updated the docs to explain that behavior: https://www.kimai.org/documentation/users.html

**Comment by kevinpapst** [comment]
Kimai 1.10 brings a new "view_all_data" permission, which disables all team restrictions (so the user role acts as like Admins and Super Admins did in the previous versions).

I guess that should solve the issue.

Please re-open if that doesn't work for you.
