### ISSUE TITLE
Export and Billing by day and Project

### ISSUE THREAD

**Issue by Kantime** [kevinpapst/kimai2#1401]
Hi,

When it commes to print a report you can only choose by day OR by project...

But, it is important to be able to make combinations like :
By day AND by project

It would be great to integrate that possibility in the futur.

**Comment by kevinpapst** [comment]
No, you are wrong ... or the UI is not that intuitive as it should be.
But you can filter your reports/exports and invoices by multiple factors (time range, customer, project, activity, user ...).
Which one are you exactly talking about?

**Comment by Kantime** [comment]
I would like to print reports that present the informations like this : 
**DAY 1**
PROJECT A – _TOTAL HOURS_
PROJECT B – _TOTAL HOURS_
**_DAY 1 – TOTAL HOURS_**

**DAY 2**
PROJECT A – TOTAL HOURS
PROJECT B – TOTAL HOURS
**_DAY 2 – TOTAL HOURS_**

**Comment by kevinpapst** [comment]
Aha, then I misunderstood your request. 

If it comes to invoices, then you have to build your own template. Almost everyone wants to show other values. You could for example build an Excelsheet that does the grouping.

Something else is the missing reporting functionality. I will log this request as possibility for the future for a dedicated report.

**Comment by Kantime** [comment]
Yes, by exporting for Excel, everything is possible indeed.

I just want to be able to create a report directly to avoid excel manipulations because it is time consuming.

Thank's

**Comment by kevinpapst** [comment]
Custom invoice and export templates exist. 
I am closing, because each and every user has another idea of the "best export".
