### ISSUE TITLE
Unable to start kimai from docker repo

### ISSUE THREAD

**Issue by martinscholz83** [kevinpapst/kimai2#1404]
**Describe the bug**
I'm trying to use kimai like described [here](https://hub.docker.com/r/kimai/kimai2). When trying to start with `docker-compose up -d` i get the following error:
```
Building nginx
ERROR: Cannot locate specified Dockerfile: Dockerfile
```
I'm using photon os.

**To Reproduce**
3. See error

**Logfile**
```
Add the last lines from your logfile at var/log/prod.log, around the time when the problem happened.
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s]

**Additional context**
 - Kimai version
 - PHP version

**Comment by kevinpapst** [comment]
Wrong repo, please ask the docker guys at https://www.github.com/tobybatch/kimai2
