### ISSUE TITLE
Admin user does not have admin rights

### ISSUE THREAD

**Issue by LAWI-Suttmoeller** [kevinpapst/kimai2#1406]
Dear Kevin,

our administrator does not have the rights to Change any documented time logs from herself or other users.

When clicking the pen button to change an entry, the change window pops up and changes can be entered but not saved.

Although she is the only admin user, her profile does not have the crown icon she should have.
She can create and manage users and their rights, but no Managing of the entries she or others make.

We are using Kimai Version v0.9.3.1384 on Internet Explorer and Google Chrome with Windows 10 pro.

Do you have any idea how she can get the overall rights to do changes?

Looking forward to hearing from you soon.

Best wishes and kind regards,
Irina

**Comment by kevinpapst** [comment]
You are using Kimai 1 which is out of maintenance. 
You can try your luck and ask the question again here: 
https://github.com/kimai/kimai
Be aware that you are not even using the most current version of Kimai 1, but a release that is 
more than 4 years old:
<img width="308" alt="Bildschirmfoto 2020-01-22 um 12 57 16" src="https://user-images.githubusercontent.com/533162/72892415-ba284e80-3d16-11ea-90e4-de57471ec95e.png">

Consider to upgrade to Kimai 2, you can test it here: https://www.kimai.org/demo/

**Comment by LAWI-Suttmoeller** [comment]
Thank you for your quick response.

Have a nice day!

Von: Kevin Papst <notifications@github.com>
Gesendet: Mittwoch, 22. Januar 2020 12:58
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: Suttmoeller, Irina <Suttmoeller@de.lawipower.com>; Author <author@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] Admin user does not have admin rights (#1406)


You are using Kimai 1 which is out of maintenance.
You can try your luck and ask the question again here:
https://github.com/kimai/kimai
Be aware that you are not even using the most current version of Kimai 1, but a release that is
more than 4 years old:
[Das Bild wurde vom Absender entfernt. Bildschirmfoto 2020-01-22 um 12 57 16]<https://user-images.githubusercontent.com/533162/72892415-ba284e80-3d16-11ea-90e4-de57471ec95e.png>

Consider to upgrade to Kimai 2, you can test it here: https://www.kimai.org/demo/
