### ISSUE TITLE
Upgrading to 1.7

### ISSUE THREAD

**Issue by coneng** [kevinpapst/kimai2#1409]
trying to upgrade from 1.3 to 1.7
I did the git fetch, git checkout and composer install
when I am doing kimai:update it seems it doesn't exist, as in the attached.
![image](https://user-images.githubusercontent.com/48026784/73013405-45244a00-3de6-11ea-9320-1d0d03064c19.png)

**Comment by kevinpapst** [comment]
Does this files exist: 
https://github.com/kevinpapst/kimai2/blob/master/src/Command/UpdateCommand.php
I guess your git update didn't't work.
What does `bin/console kimai:version` say?

**Comment by coneng** [comment]
![image](https://user-images.githubusercontent.com/48026784/73015541-3d66a480-3dea-11ea-8fa6-a80a93d5d1b6.png)

**Comment by kevinpapst** [comment]
You are still on 1.3, so the git update/fetch didn't work.
I guess you have a "dirty" git status due to changed files (see `git status`).
 Please fix that, then run the documented upgrade path.

**Comment by coneng** [comment]
For everyone's benefit.
use:
```
git rm --cached -r .
git reset --hard
```

**Comment by kevinpapst** [comment]
Thanks for sharing
