### ISSUE TITLE
Possible bug? v1.7

### ISSUE THREAD

**Issue by RPHr5TyZ** [kevinpapst/kimai2#1411]
Hi Kevin,

This is my first time installation of Kimai2. After step 'install -n' I got the Malformed parameter "url" Error. So I tried the 'php -r "echo urlencode' on my password as you suggested in the installation manual. Then I get this PHP Warning:  'PHP Startup: Unable to load dynamic library 'pdo_mysql''. When I look in my PHP all kinds of 'pdo_mysql' seems to confirm that this extension has been loaded...

Any suggestions?

Regards,

Peter

**Comment by kevinpapst** [comment]
What does `php -m|grep pdo` tell you?

**Comment by RPHr5TyZ** [comment]
Thank you for your help! The 'pdo_mysql'-extension error is solved. It was in unintentionally loaded in the 'php.ini' as where it seems already to be loaded in the 'conf.d' in php 7.3...

Bu t now I get this error after step 'install -n':

 [WARNING] Some commands could not be registered:

In srcApp_KernelProdContainer.php line 2255:

  The parameter "7E" must be defined.

**Comment by kevinpapst** [comment]
I have seen that before, your database password is too complex and now contains multiple %.
This is interpreted by Symfony as parameter and I don't know how to fix it. The easiest way is to change your DB password and use only alpha-numerical characters (if you use special character, stick with the ones that don't need to be urlencoded, like - and _).

**Comment by RPHr5TyZ** [comment]
[OK] Congratulations! Successfully installed Kimai 2 version 1.7 (stable)

Many thanks!

**Comment by RPHr5TyZ** [comment]
500 - error

 Kimai
Time Tracking
Something is wrong

A critical error occurred, please try again. You may have found a software problem, please contact your administrator if the problem persists.

Any suggestions?

**Comment by kevinpapst** [comment]
Yes, read for yourself: `var/cache/prod/translations`=> `mkdir(): Permission denied`.

Fix: read https://www.kimai.org/documentation/updates.html (at the bottom)

**Comment by RPHr5TyZ** [comment]
I already did the chown www-data and chmod's before and repeated them just now on debian buster but no avail... Any other suggestions?

**Comment by kevinpapst** [comment]
Is that a joke? The error message is clear.

**Comment by RPHr5TyZ** [comment]
Sorry Kevin, of course you are right... www-data:www-data did a better job. I'm logged in.

**Comment by kevinpapst** [comment]
😁  
But that shouldn't be necessary. You might not be able to flush the cache now without sudo now, but ... it works, I guess that is most important.

**Comment by RPHr5TyZ** [comment]
That's right! Many more thanks!
