### ISSUE TITLE
Scheduled Export

### ISSUE THREAD

**Issue by camaer** [kevinpapst/kimai2#1412]
A nice feature to add would be some sort of scheduling of an export and send the result by email.
We have a team using kimai and every week their boss need to log in kimai and export the hours of his team manually. Would be nice if he could get an automated email with a PDF containing all the hours of his team separated by users every week.

Thanks for your work

**Comment by kevinpapst** [comment]
Hey @camaer ! I think that this is a good idea, but obviously a requirement for a company setup with multiple employees. Maybe you want to ask your boss how much time he currently spents with this (boring) task and if he thinks it is worth to sponsor the development of such a feature.

**Comment by camaer** [comment]
Hey @kevinpapst ! Thanks for your response. After talking with my boss he wants to keep it like that since he need to manually check the hours and add stuff like vacation to the final sheet before sending it to HR so automating it is not really need. That being said maybe we could sponsor another feature like the decimal export in #1368. What do you think would be a fair compensation for your work ?

**Comment by kevinpapst** [comment]
Contact me via email please.
