### ISSUE TITLE
Mail adress used by Kimai

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1413]
Please make the email address required for password resets with SMTP settings available in the Kimai settings.

**Comment by kevinpapst** [comment]
You mean only the "from"  address, right?

**Comment by HeinzWuert** [comment]
the complete config for the mail adress Kimai is using for resetting password.

**Comment by kevinpapst** [comment]
I checked the code and it would take a couple of hour to move the address to the configuration. 
Not worth the effort, as it will rarely change. If there is documentation missing on how to change it, I will gladly add it.
