### ISSUE TITLE
Problem: One user but different hourly rates

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1417]
**Is your feature request related to a problem? Please describe.**
It can happen that a user works in different projects at different hourly rates.
To do this, I now have to enter the user with 2 different names to be able to represent at least 2 different hourly rates. Then there is the second problem that a user email address can only be entered once in the system.

**Describe the solution you'd like**
Allow at least two different hourly rates in the user profile. Allow an appropriate choice when assigning to a project.

**Comment by kevinpapst** [comment]
Won't fix. But there is a feature request somewhere asking for project&user specific hourly rates. Yu can vote for that one with the 👍 on the initial posting.
