### ISSUE TITLE
Duplicating timesheet entries

### ISSUE THREAD

**Issue by chrisbruijn** [kevinpapst/kimai2#1422]
I started using Kimai very recently and I really like it. Fits almost perfectly in my workflow of administrative tasks. Thanks!

One thing that would make it even better is to add possibilities to duplicate entries. I see two ways:
1. In the calender view you can now drag an item to a different date. It would be great if you could also copy-drag items in a similar way.
2. In the timesheet view it would be great if the action buttons on the right side also contains a duplicate button. If you click it all the characteristics of the existing item (dates, times, client, project, activity etc) are pre filled and off course changeable.

I now see issue #1246 is quite similar but I specified a bit more.

**Comment by kevinpapst** [comment]
You can "start again" an entry in the timesheet view (from the action menu), which is doing exactly what you want.

Duplicating a timesheet entry doesn't make a lot of sense to me (which doesn't mean nobody needs it). Can you explain why would you want to have the same entry twice with the same dates instead of restarting it (which copies all settings and moves it to the top of the table)?

**Comment by chrisbruijn** [comment]
Thanks for your answer. I will try to explain:
The Start again button is usefull for tracking your activity right now. Often that's not how I work. I'm a freelancer and I'm busy with a lot of things during the day, and I rather enter all my working hours at the end of the working day or even at the end of the week. I understand I can use the Start again button as well, but then I need to hit the start button, then close it and then edit the item. 

Why an exact copy of an entry would be handy for me? The prefilled details would work as a starting point. I only need to change date and time. It would especially work well with (weekly, daily, monthly) recurring activities. Then you only need to change the dates.

Does that make sense?

**Comment by kevinpapst** [comment]
Now available in master
