### ISSUE TITLE
dashboard runtime error: Division by zero

### ISSUE THREAD

**Issue by hmuench** [kevinpapst/kimai2#1428]
After a fresh setup of Kimai2 (according https://github.com/tobybatch/kimai2/blob/master/README.md ) I added one entry into 'my times' with a zero duration. When switching to the dashboard i get a runtime error:

in templates/widget/section-chart.html.twig (line 28)
`...
<div class="col-md-12">
    {{ render_widget(widgets.0) }}                   
</div>...`

in src/Repository/TimesheetRepository.php (line 344)
`...
$durationPercent = $duration / $result->getDuration();                
...`

Laptop
 - Device: Lenovo
 - OS: W10
 - Browser chrome
 - Version 79.0.3945.130

**Comment by kevinpapst** [comment]
Thanks I will have look asap. Did you install master or 1.7?

**Comment by hmuench** [comment]
imai/kimai2:fpm-alpine-master I think.

Here my docker-compose.yaml:

version: '3'
services:

  mydb:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiusr
      - MYSQL_PASSWORD=*****
      - MYSQL_ROOT_PASSWORD=*****
    volumes:
        - ./mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: always

  nginx:
    image: nginx:latest
    ports:
        - 8081:80
    volumes:
      - ./codebase:/opt/shared_kimai
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf

  kimai_fpm:
    image: kimai/kimai2:fpm-alpine-master
    environment:
        - APP_ENV=dev
        - TRUSTED_HOSTS=nginx,localhost,10.10.10.10
        - DATABASE_URL=mysql://kimaiu:kimaip@mydb/kimai
        - ADMINMAIL=info@gordiancode.com
        - ADMINPASS=*****
    volumes:
      - ./codebase:/opt/shared_kimai
    entrypoint: /nginx-startup.sh

**Comment by kevinpapst** [comment]
You find the Kimai version in the about screen (click on your avatar in the upper right => about).

Can you show me the exception from the Kimai log?
There is a doctor in the left menu, you find the latest 100 lines in there.

I don't understand why that should break, as there is an explicit check for 0 around that line to prevent division by zero.

**Comment by hmuench** [comment]
It was the version 1.2. I pulled a new image (v1.6) and cannot reproduce this error. It seems it’s fixed already, sorry for the inconvenience.

However, maybe you can help me with another issue: I’ve purchased the TaskManagementBundle-1.0. I’ve followed the installation instruction as follows:

bash-5.0$ cp -R TaskManagementBundle-1.0 /opt/kimai/var/plugins/TaskManagementBundle  --> ok
bash-5.0$ bin/console cache:clear --env=prod --> not ok:

--- snip log---
#6 /opt/kimai/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('KimaiPlugin\\Tas...')
#7 /opt/kimai/vendor/symfony/dependency-injection/ContainerBuilder.php(35 in /opt/kimai/vendor/symfony/config/Resource/ClassExistenceResource.php on line 150

Fatal error: Declaration of KimaiPlugin\TaskManagementBundle\DataFixtures\TasksFixtures::load(Doctrine\Persistence\ObjectManager $manager) must be compatible with Doctrine\Common\DataFixtures\FixtureInterface::load(Doctrine\Common\Persistence\ObjectManager $manager) in /opt/kimai/var/plugins/TaskManagementBundle/DataFixtures/TasksFixtures.php on line 36
14:34:21 CRITICAL  [php] Fatal Compile Error: Declaration of KimaiPlugin\TaskManagementBundle\DataFixtures\TasksFixtures::load(Doctrine\Persistence\ObjectManager $manager) must be compatible with Doctrine\Common\DataFixtures\FixtureInterface::load(Doctrine\Common\Persistence\ObjectManager $manager) ["exception" => Symfony\Component\Debug\Exception\FatalErrorException^ { …}]

In TasksFixtures.php line 36:

  Compile Error: Declaration of KimaiPlugin\TaskManagementBundle\DataFixtures\TasksFixtu
  res::load(Doctrine\Persistence\ObjectManager $manager) must be compatible with Doctrin
  e\Common\DataFixtures\FixtureInterface::load(Doctrine\Common\Persistence\ObjectManager
   $manager)
--- snip log  ---

Anyway, continued:

bash-5.0$ /opt/kimai/bin/console cache:warmup --env=prod
// Warming up the cache for the prod environment with debug
// false
[OK] Cache for the "prod" environment (debug=false) was successfully warmed.


bash-5.0$ /opt/kimai/bin/console kimai:bundle:tasks:install
  There are no commands defined in the "kimai:bundle:tasks" namespace.


In the README it is written:

This plugin is compatible with the following Kimai releases:

| Bundle version    | Kimai 2 version  |
|---                |---               |
| 1.0               | 1.7              |

Might this be the reason? If so, is there a container image from tobybatch with version 1.7?  Thank you!

Take care,
Hagen

**Comment by kevinpapst** [comment]
I sent you an email and close here, as the problem was fixed in the past
