### ISSUE TITLE
Calendar not displaying records

### ISSUE THREAD

**Issue by timlegge** [kevinpapst/kimai2#1429]
**Describe the bug**
When we connect to the calendar it does not display entries

**To Reproduce**
1. Go to Calendar
2. Not items show up
3. See error in console (dev tools)

(index):444 Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.success ((index):444)
    at u (1.16767f92.js:1)
    at Object.fireWith [as resolveWith] (1.16767f92.js:1)
    at k (1.16767f92.js:1)
    at XMLHttpRequest.<anonymous> (1.16767f92.js:1)

**Comment by kevinpapst** [comment]
can't reproduce it 😞 
this is likely connected with the call to fetch the timesheets. 
please check your network tab and let me know what you see

**Comment by timlegge** [comment]
For me it is related to: https://kimai-test.alc.ca/build/app.712803ae.js

customer: record.project.customer.name,

```
        document.addEventListener('kimai.initialized', function(event) {
            var API = event.detail.kimai.getPlugin('api');
            $('#timesheet_calendar').fullCalendar({
                defaultView: 'month',
                                eventSources: [
                    {
                        events: function(start, end, timezone, callback) {
                            var from = moment(start.format()).format(moment.HTML5_FMT.DATETIME_LOCAL_SECONDS);
                            var to = moment(end.format()).format(moment.HTML5_FMT.DATETIME_LOCAL_SECONDS);
                            API.get('/api/timesheets?size=1000&full=true&begin='+from+'&end='+to, {}, function(result) {
                                var apiEvents = [];
                                for (var record of result) {
                                    var color = record.activity.color;
                                    if (color === null) {
                                        color = record.project.color;
                                        if (color === null) {
                                            color = record.project.customer.color;
                                        }
                                    }
                                    apiEvents.push({
                                        id: record.id,
                                        title: record.activity.name,
                                        description: record.description,
                                        start: record.begin,
                                        end: record.end,
                                        activity: record.activity.name,
                                        project: record.project.name,
                                        **customer: record.project.customer.name,**
                                        tags: record.tags,
                                        color: color,
                                    });
                                }
```

**Comment by timlegge** [comment]
I also see:

**Comment by timlegge** [comment]
`0.1a6ffb43.js:1 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.`

**Comment by kevinpapst** [comment]
Thats the calendar, which at some point needs an update... but not now.
I want to see the response of the api call. Can you post the anonymized JSON here?

**Comment by timlegge** [comment]
or email sure

**Comment by timlegge** [comment]
{"JSON":[{"id":47,"duration":4500,"rate":0,"description":null,"begin":"2020-01-31T13:47:00-0400","end":"2020-01-31T15:02:00-0400","activity":2,"project":1,"user":2,"tags":[],"metaFields":[]},{"id":32,"duration":10800,"rate":0,"description":"Kimai Upgrade","begin":"2020-01-29T21:25:00-0400","end":"2020-01-30T00:25:00-0400","activity":3,"project":1,"user":2,"tags":[],"metaFields":[]},{"id":2,"duration":3600,"rate":0,"description":"Kimai Upgrade email and DNS","begin":"2019-12-18T22:45:00-0400","end":"2019-12-18T23:45:00-0400","activity":3,"project":1,"user":2,"tags":[],"metaFields":[]},{"id":1,"duration":5700,"rate":0,"description":"Prepare Kimai for testing","begin":"2019-12-18T17:45:00-0400","end":"2019-12-18T19:20:00-0400","activity":3,"project":1,"user":2,"tags":[],"metaFields":[]},{"id":30,"duration":18000,"rate":0,"description":null,"begin":"2017-12-26T10:46:00-0400","end":"2017-12-26T15:46:00-0400","activity":3,"project":1,"user":2,"tags":[],"metaFields":[]}],"Response payload":{"EDITOR_CONFIG":{"text":"[{\"id\":47,\"duration\":4500,\"rate\":0.0,\"description\":null,\"begin\":\"2020-01-31T13:47:00-0400\",\"end\":\"2020-01-31T15:02:00-0400\",\"activity\":2,\"project\":1,\"user\":2,\"tags\":[],\"metaFields\":[]},{\"id\":32,\"duration\":10800,\"rate\":0.0,\"description\":\"Kimai Upgrade\",\"begin\":\"2020-01-29T21:25:00-0400\",\"end\":\"2020-01-30T00:25:00-0400\",\"activity\":3,\"project\":1,\"user\":2,\"tags\":[],\"metaFields\":[]},{\"id\":2,\"duration\":3600,\"rate\":0.0,\"description\":\"Kimai Upgrade email and DNS\",\"begin\":\"2019-12-18T22:45:00-0400\",\"end\":\"2019-12-18T23:45:00-0400\",\"activity\":3,\"project\":1,\"user\":2,\"tags\":[],\"metaFields\":[]},{\"id\":1,\"duration\":5700,\"rate\":0.0,\"description\":\"Prepare Kimai for testing\",\"begin\":\"2019-12-18T17:45:00-0400\",\"end\":\"2019-12-18T19:20:00-0400\",\"activity\":3,\"project\":1,\"user\":2,\"tags\":[],\"metaFields\":[]},{\"id\":30,\"duration\":18000,\"rate\":0.0,\"description\":null,\"begin\":\"2017-12-26T10:46:00-0400\",\"end\":\"2017-12-26T15:46:00-0400\",\"activity\":3,\"project\":1,\"user\":2,\"tags\":[],\"metaFields\":[]}]","mode":"application/json"}}}

**Comment by kevinpapst** [comment]
Is your request URL looking like this one: 
https://demo.kimai.org/api/timesheets?size=1000&full=true&begin=2019-12-29T00:00:00&end=2020-02-09T00:00:00

From the posted code above I assume that...

Especially the `&full=true` is important. Your result is missing the project and activity objects, but instead received only the IDs (`"project":1,"`), as if the full=true would be missing.

Nothing has changed there since month, so I wonder why that would break. Probably a serializer caching problem ...

Or you have the same problem that was recently fixed in the docker repo, where GET parameters were not passed on to the PHP process.

Can you use any search (eg in My times) or the pagination?

**Comment by timlegge** [comment]
Yes, search on time sheet works and so does pagination

I think I should reset my database as its had a bunch of git forwards etc...

Probably better to rule that out

**Comment by lowrob** [comment]
Could be that - the error that I see is 

Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.success ((index):338)
    at u (1.c24a9c6f.js:1)
    at Object.fireWith [as resolveWith] (1.c24a9c6f.js:1)
    at k (1.c24a9c6f.js:1)
    at XMLHttpRequest.<anonymous> (1.c24a9c6f.js:1)
(anonymous) @ (index):338
u @ 1.c24a9c6f.js:1
fireWith @ 1.c24a9c6f.js:1
k @ 1.c24a9c6f.js:1
(anonymous) @ 1.c24a9c6f.js:1
load (async)
send @ 1.c24a9c6f.js:1
ajax @ 1.c24a9c6f.js:1
value @ app.04b966cf.js:1
events @ (index):320
(anonymous) @ calendar.5cc27719.js:1
construct @ calendar.5cc27719.js:1
t.fetch @ calendar.5cc27719.js:1
e.requestSource @ calendar.5cc27719.js:1
e.requestSources @ calendar.5cc27719.js:1
e.setPeriod @ calendar.5cc27719.js:1
e.requestEvents @ calendar.5cc27719.js:1
e.requestEvents @ calendar.5cc27719.js:1
t.fetchInitialEvents @ calendar.5cc27719.js:1
(anonymous) @ calendar.5cc27719.js:1
(anonymous) @ calendar.5cc27719.js:1
(anonymous) @ calendar.5cc27719.js:1
(anonymous) @ calendar.5cc27719.js:1
t @ calendar.5cc27719.js:1
dispatch @ 1.c24a9c6f.js:1
v.handle @ 1.c24a9c6f.js:1
trigger @ 1.c24a9c6f.js:1
triggerHandler @ 1.c24a9c6f.js:1
t.trigger @ calendar.5cc27719.js:1
t.setProps @ calendar.5cc27719.js:1
t.set @ calendar.5cc27719.js:1
t.setDate @ calendar.5cc27719.js:1
e.renderView @ calendar.5cc27719.js:1
e.initialRender @ calendar.5cc27719.js:1
e.render @ calendar.5cc27719.js:1
(anonymous) @ calendar.5cc27719.js:1
each @ 1.c24a9c6f.js:1
each @ 1.c24a9c6f.js:1
r.fn.fullCalendar @ calendar.5cc27719.js:1
(anonymous) @ (index):313
value @ app.04b966cf.js:1
t @ app.04b966cf.js:1
e @ app.04b966cf.js:1
(anonymous) @ (index):242
load (async)
(anonymous) @ (index):241
Show 13 more frames

**Comment by timlegge** [comment]
Actuall no to search on all timesheets

**Comment by kevinpapst** [comment]
> Yes, search on time sheet works and so does pagination

> Actuall no to search on all timesheets

???

**Comment by timlegge** [comment]
> Or you have the same problem that was recently fixed in the docker repo, where GET parameters were not passed on to the PHP process.

Probably.  Let me look

**Comment by kevinpapst** [comment]
Check this line: 
https://github.com/tobybatch/kimai2/pull/71/files#diff-5bcf1b5695cb99fcfed866e55e25b3c7R21
The `$is_args$args` in `try_files $uri $uri/ /index.php$is_args$args;` can break all GET params...

**Comment by timlegge** [comment]
fixed.  That was it thanks.

I need to review that file some more
