### ISSUE TITLE
invoice: sum calculation on entry per week

### ISSUE THREAD

**Issue by maarten-k** [kevinpapst/kimai2#1434]
**Is your feature request related to a problem? Please describe.**
I need to report the hours I worked every week, and I send an invoice once per month. Right now I have to "juggle" the hours by hand to make the numbers match up.

**Describe the solution you'd like**
- an option in the invoice template->Sum calculation to create on entry per week.

**Describe alternatives you've considered**
Merging the fields of the "one entry per day" sum calculation by hand in the final invoice.

**Comment by kevinpapst** [comment]
Step 1:

Copy & Paste https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/UserInvoiceCalculator.php

Step 2:
Use in [line 26](https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/UserInvoiceCalculator.php#L26) something like `return $invoiceItem->getBegin()->format('W')`;

Step 3:
Send in a PR and share it with all of us.
