### ISSUE TITLE
AD - LDAP : Unable to use email adress as username to login

### ISSUE THREAD

**Issue by Gyrfalc0n** [kevinpapst/kimai2#1436]
Good morning, sir,

After my problem to make the connection via AD work for Kimai2, I come to another problem.

(**I solved my previous problem by upgrading to PHP v7.3**).

So here's my problem: the following local.yaml file allows me to connect to my Kimai2 server via my AD users with their sAMAccountName.

**However I would like them to be able to connect by entering their email address which corresponds to the email attribute or userPrincipalName.**

How do I modify my file so that this is possible?
I have used a lot of possibilities without success.

*Can those who managed to make a connection via AD direct me to this?*

**Thank you in advance.**

**local.yaml**

```security:
    providers:
        chain_provider:
            chain:
                providers: [kimai_ldap]
    firewalls:
        secured_area:
            kimai_ldap: ~
kimai:
    user:
        registration: false
        password_reset: false
    ldap:
        connection:
            host: serveur-dc2
            username: cn=admin,cn=Users,dc=company,dc=local
            password: 
            accountDomainName: company.local
            accountDomainNameShort: COMPANY
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
        user:
            baseDn: ou=Comptes-mail,dc=company,dc=local
            filter: (&(objectClass=Person))
            usernameAttribute: samaccountname
            attributes:
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: cn, user_method: setAlias }
                - { ldap_attr: uid,  user_method: setUsername }```

**Comment by kevinpapst** [comment]
Have you tried `bindRequiresDn: false` with one of your combinations?
Its very helpful, to see what you tried and why it failed.
I guess you need to change `accountFilterFormat: (&(objectClass=Person(sAMAccountName=%s))` to match the email and not the `sAMAccountName`

**Comment by Gyrfalc0n** [comment]
Yes, I have to change the 'accountFilterFormat' to match with the email but I didn't manage to get it working, it could only extract the sAMAccountName in every case

**Comment by Gyrfalc0n** [comment]
After some tests, I made a compromise, users can connect with their email coming from the AD but at their first connection they have to inform their sAMAccountName that is to say their email without the @domain.

And it all works.

Thank you for the fast and efficient support !

**Comment by Gyrfalc0n** [comment]
After some tests, I made a compromise, users can connect with their email coming from the AD but at their first connection they have to inform their sAMAccountName that is to say their email without the @domain.

And it all works.

Thank you for the fast and efficient support !
