### ISSUE TITLE
User & activity/project/customer specific rates

### ISSUE THREAD

**Issue by HonzaKopecky** [kevinpapst/kimai2#1439]
Hello there,

if I am not mistaken, specific rates for a user given an activity/project/customer are still not implemented, is that right? I noticed that in some issues you mentioned there is a request for this feature but I just couldn't find it.

I would say this is a key feature for any business where employees work in different areas. As this is now the only reason we cannot migrate to the new Kimai, I will try my best and introduce this feature. Is there any way we could have a bit more real time chat to discuss how should I approach the implementation?

Thanks for your great work!

**Comment by kevinpapst** [comment]
Email? See https://www.kevinpapst.de/kontakt/

**Comment by HonzaKopecky** [comment]
Okay, I guess we can just briefly discuss it in here. So my overall idea consists of the following steps:

- Kimai Plugin
- Register new model entity for rates (user, project, activity, customer)
- Create new RateCalculator that will use the same logic as the current one but will also include evaluation of the new user-specific rates.
- At this point the rates can be directly inserted into the DB manually (as we used to do in old Kimai)
- Extend user interface with a screen that enables user to create/modify/delete these custom rates.

Does this seem reasonable to you?

The only thing I am currently not sure about is how to extend the model. Do I just define the Model myself and include it's creation in the install script?

**Comment by kevinpapst** [comment]
Please sent me an email quickly
