### ISSUE TITLE
Integrate FOSUserBundle (for registration, password-reset, etc.)

### ISSUE THREAD

**Issue by tacman** [kevinpapst/kimai2#144]
## Description

This is a great example of Symfony4 app with the AdminLTE theme.  But there's no way to register or reset a forgotten password.

## Possible Fix

Integrate FOSUserBundle.

**Comment by kevinpapst** [comment]
Hey @tacman, thanks for your feedback.

Right now "no register" is on purpose, as only admins should be able to create new user. 
Resetting a password is indeed something different. I'll look into FOSUserBundle.

**Comment by kevinpapst** [comment]
After having some deeper looks into FOSUserBundle I decided against going with it, but instead going to code it myself , see #163 and #164.

There are several reasons why I am not going to use it, probably the most important one is missing core compatibility with Symfony 4.1. Also there are quite some good write-ups why this bundle is not the best solution for every use-case.

I am closing this ticket in favor of the new created and linked above.

**Comment by kevinpapst** [comment]
Reopen again. After quite a lot of testing I figured that it will be easier to integrate this bundle instead of building it with another solution.

**Comment by kevinpapst** [comment]
Thanks for the inspiration @tacman 
FOSUserbundle is now integrated in the latest master
