### ISSUE TITLE
Timezone between teamlead and user

### ISSUE THREAD

**Issue by portosricos** [kevinpapst/kimai2#1441]
**Is your feature request related to a problem? Please describe.**
I understand Kimai has a timezone logic. I notice a problem with the timezone of Morocco. So I notice that our server didn't have the new timezone logic for that country (they don't change time except during Ramadan). I'm fixing the issue but notice an logic issue with the platform for multi timezone business.

Setup
- I set up the platform for a punch in/ punch out system.
- Users have their timezone set (some in America/New York and some in Morocco/Casablanca).
- In mysql (kimai2_timesheet), the start_time and end_time is in UTC and the timezone is set with the timezone of the user that enters the data:

  - If its a Morocco user, it will have Morocco timezone
  - If its a America user, it will be America timezone.

But if a teamlead in America adds a activity to a Morocco user, it will put the timezone of the teamlead and not of the user (same for the time).

It's a good logic the timezone in the database (allow consistent for the data)  but a user can never change his timezone because we will lose all concept of the time done.

**Describe the solution you'd like**
Since a lot of people use your platform, it would be a new option in the system settings. 

That option would be:
Enter time by user timezone.

When enable, new activities are entered with the employee timezone and not the user timezone that adds data.

**Describe alternatives you've considered**
I'm programming a logic that use the timezone of the activity and the timezone of the user it relate too.

**Additional context**
![image](https://user-images.githubusercontent.com/4107501/73783612-01283200-4762-11ea-8b5f-453e2faf498b.png)

This is all from same user. It should be all Africa/Casablanca  but some data was entered by the user and other by the teamlead.

**Comment by kevinpapst** [comment]
I guess you are right. Even though I don't like that... 😁 but that's definitely a bug. 
I don't think that a new config is required. The timezone MUST be the one from the user that owns the record and not from the user that entered the record.

Thanks for the detailed explanation!

**Comment by kevinpapst** [comment]
Did you have time to check my bugfix in #1509?

If not, now is the perfect time, because I changed the logic a bit.
