### ISSUE TITLE
Africa/Casablanca timezone issue

### ISSUE THREAD

**Issue by purebackend** [kevinpapst/kimai2#1442]
**Description**
When editing the timesheet entry it display an inaccurate time (GMT) if the entry is for Africa/Casablanca instead of GMT+1. The list view shows the proper GMT+1 as expected.

**Note**
Africa/Casablanca was changed in 2018 to no longer have DST, however, my tzdata, PHP and mysql all seem to have the updated timezone changes. So I believe this screen does something different then the rest :)

**To Reproduce**
1. As a regular user, change your timezone preferences to Africa/Casablanca
2. Create a time entry for any project and then stop it.
3. As a manager, view the timesheets under Administration. 
4. In the list view the time should be accurate, if you click on the entry, the modal popup has a different time. This is not expected.

**Logfile**
No lines added

**Screenshots**
I've added a screenshot of a list view that has a 06:38AM Africa/Casablanca time and when I click on it, it shows 05:38AM 
![image](https://user-images.githubusercontent.com/2199794/73816292-48d8a900-47b6-11ea-836d-05f3bd199d50.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: PC
 - OS: Windows10
 - Browser Chrome
 - Version 81.0.4040.5

**Additional context**
 - Kimai version (
 - PHP version (PHP 7.4.2)
- Linux is CentOS 7
- I've validated I have the latest tzdata installed
- Running the following command shows the proper date:
TZ=Africa/Casablanca date
Wed Feb  5 06:38:00 +01 2020
- I've ran the mysql_tzinfo_to_sql but it doesnt seem to help the issue.
- I've tested with CONVERT_TZ on mysql and it works as expected.
- I've tested with new DateTime and converting to Africa/Casablanca and it works as expected.

Let me know if you have any other questions

**Comment by kevinpapst** [comment]
Is this your own timesheet record or the one for someone else?

**Comment by portosricos** [comment]
The person looking the data has is account to America/ New York.
The user timesheet is at Morocco/Casablanca.

**Comment by portosricos** [comment]
@kevinpapst : sorry to bother but is it possible to have a direction of the situation. I could check to see why it reacts like that :)
thank you

**Comment by kevinpapst** [comment]
The direction is: I will check it when I find the time to do so. 
If it is urgent for you, then you could start debugging here: https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L113

**Comment by portosricos** [comment]
@kevinpapst thank you, I will try to help

**Comment by kevinpapst** [comment]
I am closing this as duplicate. It is a very good and detailed report, thanks for that. But let's keep on talking in #1441. 

A possible bugfix was posted a very long time ago, but I am not going to merge that without feedback.
