### ISSUE TITLE
Freeze headings in list display

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1443]
**Is your feature request related to a problem? Please describe.**
When scrolling through long lists, unfortunately, the headings also scroll out of the visible area.

**Describe the solution you'd like**
Fix headings in list display on top

**Comment by kevinpapst** [comment]
I tried to add it with latest HTML support for sticky headers, but wasn't able to find a working solution.

I can assist with the twig part, if someone wants to contribute the necessary CSS
