### ISSUE TITLE
Admin log page to see last user login

### ISSUE THREAD

**Issue by Gyrfalc0n** [kevinpapst/kimai2#1444]
Good morning, sir,

**Describe the solution you want**

It would be interesting to be able as an admin to see user logins so that you can know if a user hasn't logged in for a while.

This would be a log page where you could see the times when users logged in. And on their profiles we would see their last connection.

The goal is to avoid having to search in the time sheets to see if a user hasn't logged in recently.

Thank you in advance!
Great work

**Comment by kevinpapst** [comment]
Next version will contain the `last_login` as column in the user listing.
Try it int the demo. 
This column is hidden by default, you need to activate it first with the "eye" icon.

**Comment by kevinpapst** [comment]
Thanks for the feedback...

**Comment by Gyrfalc0n** [comment]
Hi, sorry I didn't see your message...
The feature is very good, exactly what I was thinking. She does the job very well. 

Thank you for constantly improving Kimai.
