### ISSUE TITLE
zend-ldap is deprecated

### ISSUE THREAD

**Issue by dasJ** [kevinpapst/kimai2#1445]
**Describe the bug**

See https://docs.zendframework.com/zend-ldap/
laminas-ldap should be used now.

**Comment by kevinpapst** [comment]
Yes I know.  But Zend LDAP is working great without any changes for a very long time now, so this is definitely not a bug^^ 
If anyone (you?) wants to fix it: please go ahead and open a PR.

**Comment by dasJ** [comment]
:shipit:

**Comment by kevinpapst** [comment]
Quick response 😁
