### ISSUE TITLE
Configure auth settings via system settings instead of local.yaml

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1449]
I noticed with pleasure that all standard configurations can be done inside the app. As far as I noticed, only the authentication settings need to be realised within the local.yaml
![screenshot](https://user-images.githubusercontent.com/51003649/74091353-b9cdd880-4ab6-11ea-98d4-5a32e0701030.png)
Its not a big deal but implementation of this (last standard) setting inside the app would be very much appriciated.

**Comment by kevinpapst** [comment]
Thats impossible by now, as this option needs to be available during the cache compile time.
I could hide the link, but then the functionality is still available.
That goes for all auth functions currently.
I will leave this feature request open, but don't think that I can change the behavior in the near future.

**Comment by kevinpapst** [comment]
Added a long time ago, closing.
