### ISSUE TITLE
Feature: Negative duration

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [kevinpapst/kimai2#1453]
I often find myself leaving a customer and on my way back to the office I want to record the time I've spent there. I have kimai in duration mode (Fields: from and duration) and calculating back from the current time and then entering the correct duration can get complicated.

**Describe the solution you'd like**
I would like to be able to enter a negative duration e.g. -2h and then on saving the from time is recalculated to accommodate the entered duration.

**Comment by kevinpapst** [comment]
Probably another tracking mode is better, which will subtract the entered duration from "now" instead of entering a negative duration.

**Comment by tofuSCHNITZEL** [comment]
I tend to disagree. because different people working with kimai would then have to be able to choose their tracking method separately because not all will need this kind of logic. Also myself only needs this some of the times but not always and I would argue that a negative duration keeps it flexible while staying in the "duration" mode while being pretty intuitive...
e.g. stetting a start time -> positive duration begins at this time; negative durations "goes back from the set time"

**Comment by goubergs** [comment]
I'd be interested in entering negative durations to e.g. correct timesheets of last month, which have been cleared (frozen) already.  E.g. to make a correction in total allocated hours over a period of time.  It could also be useful when a 'credit note' (negative invoice) would need to be sent based on earlier over-allocated hours...
