### ISSUE TITLE
Team independent / global permissions for regular Users

### ISSUE THREAD

**Issue by de-sec** [kevinpapst/kimai2#1456]
In our Implementation (V 1.7) we intend all regular Users (non-Admins aswell) to see all Customers to prevent duplicate Customer entries. 

Creating a new Role and assigning Customer (Admin) view_customer Permission to this Role does not seem to work. This permission behaviour is working as intended, if i interpret the documentation correctly. 

It would be great to be able to assign specific Admin sub-privileges to regular users - so i request this as feature.

**Comment by kevinpapst** [comment]
When using teams, a customer is immediately hidden from all non-admin users when a team is assigned to it. You have to create a second team "all users" and add each user to this team, which you need to assign to the customer as well.

**Comment by kevinpapst** [comment]
Does that help? From my perspective this is already possible, so I am closing here if no feedback is provided.

**Comment by de-sec** [comment]
It's a good approach but does not meet our requirements to 100%. 

if we configure as like as you recommended all employees are able to select regarding customers during the creation of time records. 

we intended to get an option which allows an overview about the "global" customer database but does not allow to track times for those customers. 

i guess it's much work regarding the permission structure so we are going to implement a cross-check workflow during that an admin is required to check if a "new" customer for a team is already set up by others.

**Comment by kevinpapst** [comment]
Hm, that would break the logic in Kimai. You can always create a simple HTML page with some javascript that uses the API to show a list of all customers. 

Or: simply set permissions on projects and not customers.
Then all customers have global visibility, but cannot be selected for tracking in case no project is available.

I am closing this feature request, as I will not add logic that allows this behavior.
