### ISSUE TITLE
Addons in the Kimai menu

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1459]
**Is your feature request related to a problem? Please describe.**
There are a lot of addons for Kimai now.
The bad thing is that they all appear in the left menu, which is becoming increasingly confusing.

**Describe the solution you'd like**
A separate menu "Addons" in which these are entered as default would be nice. A distinction should be made between addons for admins / sysadmin and user.

**Comment by kevinpapst** [comment]
It is up to the developer where the plugin will add its menu.
I don't think that a "plugins" menu will help => is the user really interested to know whether a function is coming from a plugin or Kimai core?
