### ISSUE TITLE
cannot create invoice or preview invoice or export

### ISSUE THREAD

**Issue by heeen** [kevinpapst/kimai2#1460]
**Describe the bug**
preview button for invoice and export does not show preview
print button for invoice opens same page again in a new window

**To Reproduce**

Using docker-compose to start a new instance, after setting up a customer, project, activity and template and adding some times, the preview buttons for export and invoice don't work. The print button for invoices does not work.

no erorrs or warnings
**Logfile**
There are no errors generated

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
Firefox, Chromium on Linux

**Additional context**
 - Kimai version: from docker-compose 1d06ffcc56a342222a592f35f83c7909783dc036

I ran docker prune --volumes to make sure I have everything from scratch

**Comment by kevinpapst** [comment]
As I already said in the other issue: that is a docker problem which was recently fixed. I cannot help with that.
You can verify it by executing any search. 
All GET parameters are ignored, while everything that is using a POST is working, correct?

**Comment by heeen** [comment]
docker issue as in I have to upgrade docker? I can also see that the calendar is blank and that issue had a fix for the nginx configuration. I just checked and I have that checked out.
What do I have to do?

**Comment by kevinpapst** [comment]
Why don't you ask in the docker repository? I am not a docker user and cannot give support for it.

**Comment by AlxBe** [comment]
see: https://github.com/tobybatch/kimai2/issues/61
