### ISSUE TITLE
Allow to set meta-fields in bulk update

### ISSUE THREAD

**Issue by mopheus** [kevinpapst/kimai2#1461]
Every Additonal field are not available to make changes in bulk by time entries.
I would like to store the order/ticket number in bulk.

Thanks

**Comment by SpoorthiPalakshaiah** [comment]
How can I get a meta field? Is it by adding MetaFieldSubscriber.php and MetaFieldDisplaySubscriber.php in /opt/kimai/src/EventSubscriber with code as in official documentation or is there any other way..

**Comment by kevinpapst** [comment]
this is now possible, I think with 1.11 or current master
