### ISSUE TITLE
Redirect to /en/homepage results in 404

### ISSUE THREAD

**Issue by ohardin** [kevinpapst/kimai2#1466]
Fresh install.  Nginx 1.16.1  php 7.3.

navigating to the webserver/ results in a redirection to /en/homepage which errors out.

**Comment by kevinpapst** [comment]
Aha. Not that I see a question here, but read the webserver config documentation...

**Comment by ohardin** [comment]
I did, the server config documentation doesn't cover hosting in nginx [https://www.kimai.org/documentation/webserver-configuration.html]  unless there is another one somewhere.   

Thanks anyway!

**Comment by kevinpapst** [comment]
Yes there are more infos available, I added some cross links so its easier to find
https://www.kimai.org/documentation/webserver-configuration.html
