### ISSUE TITLE
Add Custom Entities

### ISSUE THREAD

**Issue by mufermann** [kevinpapst/kimai2#1467]
**Is your feature request related to a problem? Please describe.**
We are working a lot with subprojects in our projects.
Tried to use the Plugin CustomFields, but cant find the possibili to connect the Custom timesheet field "Subproject" and the project CustomField "Subproject"

**Describe the solution you'd like**
I'd would by nice to create own entities and not only fields.

**Describe alternatives you've considered**
Possibility to connect CustomFileds

**Comment by kevinpapst** [comment]
Nope, sorry, Kimai is not Wordpress 😁 Own entities are completely out of scope. 
This will not be implemented neither in Kimai nor in the plugin.
