### ISSUE TITLE
Question: deleting of teams

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1471]
A project has expired.
The bookings in My Times are completed (exported)
A team of the same name was created with the project and is no longer required.
Can I delete this team
- without the unauthorized being able to see the completed project
- can the former team members still have access to their bookings?

If no problems arise here this FR:
When deleting or finishing a project, offer to delete the team of the same name.

**Comment by kevinpapst** [comment]
Users will always have access to all of their own bookings.
If this is the only team, then users will be able to see the expired project if they try to book times for the time range when it was active. If you want to prevent that either create an empty team "expired projects" OR set the project to invisible.

**Comment by HeinzWuert** [comment]
Is this a weak spot of Kimai?
After completion of a project, users are only interested in their own bookings.
For the admin, however, only the project itself.
Wouldn't it make sense to have a project completion that removes the teams and is then only visible to the admin?
Currently I have to delete the team and somehow make the project invisible to users.
A logical field for project completion would have the advantage of simplified statistical evaluations of completed projects.

**Comment by kevinpapst** [comment]
There is the "invisible" flag and the "project end" field. Having a third state would be redundant. 

We can talk about simplifying the process, eg. 
- having a "delete team" option directly from in the project detail page "Team permissions" section
- having an explicit "close project" button, which shows a confirmation dialog and which then (if confirmed) makes the project invisible, sets the project end date  (if not already set) to today
- I am not a fan of auto deletion of teams, that is too much magic and it could lead to unwanted effects

I am closing here for now, if you think any other action or one of my ideas is worth it, please open a new issue
