### ISSUE TITLE
edit_export_other_timesheet

### ISSUE THREAD

**Issue by hmuench** [kevinpapst/kimai2#1473]
Possibly not a bug: 
According to the documentation, with the edit_export_other_timesheet permission one can 'Set the export state of for other users timesheet records'. So, I assume that if I remove the permission for a specific role that the user with that role may not set the export state of other users records.

I have removed the edit_export_other_timesheet permission for the teamleader role and logged in as the assigned teamleader. I was still able to set the 'Mark as exported' flag in the export form and after export the status was 'cleared'.

Or is there another way to prevent a teamleader to mark other records as exported?

Thank you.

**Comment by kevinpapst** [comment]
Thanks for posting this issue. I believe it is an inconsistency from earlier days. 
In the past teamleads didn't have access to "invoice" and "export" and therefor had no ability to use these ways to set the export flag => the permissions was only made for the "edit timesheet" dialog.

Not sure what is the best way to proceed:
- remove the field completely from the "edit timesheet form" and let it be handled by export/invoice exclusively
- and then remove the features from invoice/export for the users without that permission
?

**Comment by kevinpapst** [comment]
The next release will remove the checkboxes "mark as exported" from invoice and export screen if the permission `edit_export_other_timesheet` is not assigned to the current users roles
