### ISSUE TITLE
Bad project overview for projects of the same name

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1475]
**Is your feature request related to a problem? Please describe.**
If there are several projects (also expired) with the same name, they cannot be differentiated in the list display, since the start / end date of the project is not displayed (eye symbol)

**Describe the solution you'd like**
Add appropriate options to the filter

**Comment by kevinpapst** [comment]
Available in master since a couple of days: 

<img width="653" alt="Bildschirmfoto 2020-03-15 um 16 22 37" src="https://user-images.githubusercontent.com/533162/76704421-30bf4800-66d9-11ea-91b8-50df8fc062a8.png">
