### ISSUE TITLE
Option to disable title updates

### ISSUE THREAD

**Issue by itkfm** [kevinpapst/kimai2#1477]
**Is your feature request related to a problem? Please describe.**
When Kimai is open in a tab in Firefox, it will light up again and again (every minute!) to notify the user. The change that happens appears to be the updated time in title only (which actally arouses only little or no interest).

**Describe the solution you'd like**
An option to disable this title updates by user. So those who have pinned the Kimar tab don't get those distracting notifications. (In 0.9 there was no title changing, so having the tab pinned was fine there.)

**Describe alternatives you've considered**
- Closing Kimai tab (less than ideal)
- Moving Kimai to bookmarks toolbar (which I'm not using; so first and only entry, waste of space)

**Additional context**
![Screenshot from 2020-02-18 11-30-14](https://user-images.githubusercontent.com/53079668/74728875-cf27cd00-5243-11ea-954b-8d6dfa7da71b.png)

**Comment by kevinpapst** [comment]
> which actally arouses only little or no interest

How do you get that impression? Dozends of users want that feature...

What is that screenshot? Can you explain a little. I don't get what this is.

**Comment by itkfm** [comment]
> How do you get that impression?

That's my personal thought about this. Sorry for not making this clear.

> What is that screenshot?

It shows the pinned tab in Firefox. The blue dot will always light up again every minute to notify me (about the title change).

![Screenshot from 2020-02-18 12-04-25](https://user-images.githubusercontent.com/53079668/74730672-d8feff80-5246-11ea-8b88-02b325206140.png)

**Comment by itkfm** [comment]
Also please don't get me wrong. I didn't say that there's no use for title updating feature. It's the notification indicator that it causes that _**I**_ don't have a use for.

**Comment by kevinpapst** [comment]
I agree, it is annoying in FF. 
I use FF exclusively for development but not for my production work, so I never noticed that. For now you can use a custom css in FF (search for: pinned tab ff indicator).

Unfortunately this needs a new user-preference and I am against new settings whenever possible, so this might go into a plugin...
