### ISSUE TITLE
Updating hourly rate on timesheet entry won't work

### ISSUE THREAD

**Issue by gitalexa** [kevinpapst/kimai2#1482]
I charge different rates so I always put in the value on starting new time entry. if I want to change the value it is not working. In other fields I can put new values, but if I insert new value in hourly rate - the old value appears after storing

**Comment by kevinpapst** [comment]
Did you read https://www.kimai.org/documentation/timesheet.html#rate-calculation

**Comment by gitalexa** [comment]
Yes.

Timesheet fixed rate = empty
Activity fixed rate = empty
Project fixed rate = empty
Customer fixed rate = empty
Timesheet hourly rate = 0 and I want change it to 50

**Comment by kevinpapst** [comment]
Can you verify that behaviour in the stable demo?

**Comment by gitalexa** [comment]
can I answer in german?

**Comment by kevinpapst** [comment]
Klar

**Comment by gitalexa** [comment]
Moin Kevin,

Kann sein, dass ich die Doku falsch verstehe. 

So wie ich es lese, sollte ein Eintrag des Stundenlohns im Zeiterfassungsformular alle evtl. In der Tätigkeit, Projekt oder Kunde vorgenommenen Einstellungen überschreiben. Soll das so sein?

Falls ja, bei mir ist es nicht so. Eingegebene Werte in der Zeiterfassung werden von anderen übersteuert. Die Reihenfolge habe ich noch nicht herausgefunden.

Grüße

Alex


PS:

Versionsupdate habe ich vorm Öffnen des Tickets gemacht

**Comment by kevinpapst** [comment]
Fixed rates gehen vor. 
0 ist nicht das gleich wie "Feld leer".
Du musst Aktivität/Projekt/Kunde kontrollieren und nachsehen ob da irgendwo was drinsteht.
Wenn Du den Eintrag neu abspeicherst, müssen Daten geändert werden, ansonsten wird nicht gespeichert.

**Comment by gitalexa** [comment]
> Am 28.02.2020 um 10:55 schrieb Kevin Papst <notifications@github.com>:
> 
> Fixed rates gehen vor.
> 

Ist in allen Fällen leer (nicht 0)


> 0 ist nicht das gleich wie "Feld leer".
> 

Das habe ich auch so verstanden

> Du musst Aktivität/Projekt/Kunde kontrollieren und nachsehen ob da irgendwo was drinsteht.
> 

Fixed ist immer leer, bei Tätigkeit habe ich mittlerweile paarmal Stundenlöhne eingetragen, um den „Bug oder Feature“ zu umgehen.

> Wenn Du den Eintrag neu abspeicherst, müssen Daten geändert werden, ansonsten wird nicht gespeichert.
> 
> 


Wir reden vom Zeiterfassungsformular? Ja, so sollte es sein - ist es aber nicht. Wenn ich dort den betrag ändere, wird er nicht angenommen. Formular schließt sich, aber nach öffenen steht wieder der alte wert drin.

**Comment by kevinpapst** [comment]
steht ein Fehler unter "Doktor > Log"?

**Comment by gitalexa** [comment]
Empty or missing logfile

**Comment by gitalexa** [comment]
Habs mal aufgenommen

**Comment by kevinpapst** [comment]
Passiert das immer bei Dir oder nur bei einem Eintrag?

> Habs mal aufgenommen

???

**Comment by gitalexa** [comment]
passiert immer. Der einmal eingetragene Stundenlohnwert ist quasi eine Konstante

**Comment by kevinpapst** [comment]
Also ich kann das beim besten Willen nicht nachvollziehen, auch nicht auf der Demo Seite. Weiß nicht wie ich da helfen soll.

Ich kann nur sagen (auch wenn Dir das jetzt nicht hilft) das es bei der Berechnung noch keinen Bug gab und jeder der sich dbzgl. meldete am Ende eine Fehlkonfiguration hatte.
Das Du keine Logs hast, finde ich aber etwas merkwürdig. Fehlende Schreibberechtigungen meckert der Doktor aber keine an, oder?

**Comment by gitalexa** [comment]
der Doktor zeigt grüne Häkchen bei den Permissions.
So wie der Fehler sich darstellt, scheint ja die eingegebene neue Zahl beim Stundenlohn gar nicht in der Datenbank anzukommen. Die Berechnung ist nicht das Problem, eher der Weg vom Eingeben zum Server.

Ich hab nicht viele Sachen drin und weiß dass es so ist. Ich muss halt immer den Zeiteintrag komplett löschen und neu anlegen, wenn ich was ändern will. Kommt nicht oft vor und so kann ich damit leben.
