### ISSUE TITLE
parameter "xxx" must be defined in srcApp_KernelProdContainer.php line 2255

### ISSUE THREAD

**Issue by jlgarnier** [kevinpapst/kimai2#1487]
**Describe the bug**
Tried to install Kimai v2 on a Debian private server (host = OVH), successfully passed Composer and kimai installation steps, passed database configuration steps with editing the .env file (had to URLize the password), but now stuck at the command "bin/console kimai:install -n" which returns: In srcApp_KernelProdContainer.php line 2255: The parameter "2472De" must be defined. In my case, the password begins by "%2472De[...]" characters, so it seems the password is not recognized or its format is not URL-compliant.

**To Reproduce**
1. Launch "bin/console kimai:install -n"
2. Bug pops up!

**Logfile**
```
No log file, installation aborted.
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue: **not applicable**
 - Device: [e.g. iPhone6s]

**Additional context**
 - Kimai version: latest 1.7
 - PHP version: 7.4.3

Thanks in advance for any help!

**Comment by kevinpapst** [comment]
Maybe you can call it a bug, but it can't be solved from Kimai side, as that is a limitation from the framework... simply said: your password has to many special characters.
Please change the password to use only simple ascii characters like numbers and letters or characters that do not need to be url encoded.

**Comment by jlgarnier** [comment]
Hi Kevin,

Sorry for the wrong word, I didn't want to offense anyone and it's just an
"issue" for me! By the way, you're probably right and I'll try to create a
new database user/password to check this out. I'll let you know of the
result and will close the case.

Thanks again for your help!

Cordialement / Best regards,

Jean-Luc GARNIER
Profil : http://jeanlucgarnier.tel

Le ven. 21 févr. 2020 à 18:54, Kevin Papst <notifications@github.com> a
écrit :

**Comment by kevinpapst** [comment]
No offense taken ^^
Its happening, because your password has multiple `%` and everything in between these percentage-signs is seen as a variable. 
Solution: use a longer password with simple letter and numbers.

**Comment by kevinpapst** [comment]
@jlgarnier please let me know when you solved the problem and we can close this issue.

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by jlgarnier** [comment]
Hi Kevin,

Sorry for the lack of feedback, I'm still struggling with the installation. I've tried to create a new database user "kimai/SimplePwd" but now, for unknow reason, I just can't give this user any permission on the selected database! This is clearly not related to Kimai, but to Virtualmin, so I'm waiting for support on this issue prior to finish Kimai installation...

Thanks again for the support and follow-up!
