### ISSUE TITLE
Error 500 after clear cache

### ISSUE THREAD

**Issue by SaroTaz** [kevinpapst/kimai2#1488]
I'm new to use Kimai. Fresh installation on ubuntu server LTS 18.04 following this [guide](https://www.kimai.org/documentation/fresh-ubuntu-18.html) (mysql + nginx setup).
All works fine. But after clearing cache (bin/console cache:clear) i' ve following message:

> Something is wrong
A critical error occurred, please try again. You may have found a software problem, please contact your administrator if the problem persists.

**Comment by kevinpapst** [comment]
Fix file permissions, see  eg. https://www.kimai.org/documentation/updates.html

**Comment by SaroTaz** [comment]
Solved! thanks!
