### ISSUE TITLE
Something missing? Theme is broken

### ISSUE THREAD

**Issue by ZoXx** [kevinpapst/kimai2#1492]
Hello, everybody,
I have "installed" the package once via SSH and once via FTP. However, both versions look like this to me: 
https://www1.xup.to/exec/ximg.php?fid=15083613

Sometimes when i click through the settings i get this one:
https://www1.xup.to/exec/ximg.php?fid=16512106

Is something missing here via .php or where is the error?

**Comment by kevinpapst** [comment]
Looks as if for some reason the CSS can't be loaded, which is normally a webserver configuration problem. Whats in your javascript console? Is there something in var/log/prod.log?

**Comment by ZoXx** [comment]
Hey,
Kimai is running in a subfolder of the domain.
Console settings: Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/build/A.app.8240996d.css.pagespeed.cf.eqjR21wt-X.css' with computed SHA-256 integrity 'deVFqpsMrqSO2e7AMP1soIaUErc2z0HN3DDnFiogp/U='. The resource has been blocked.

**Comment by kevinpapst** [comment]
Subdirectories should work but I can't give support for that.
As this filename is not available in Kimai, try to disable your Pagespeed browser plugin and retry, maybe it is messing with the Kimai assets.

**Comment by ZoXx** [comment]
What do you mean with:
> try to disable your Pagespeed browser plugin

**Comment by ZoXx** [comment]
Okay.
Chrome it has this error. Same on Opera.
Internet Explorer it is working.

Whats wrong here?

**Comment by kevinpapst** [comment]
This is not a valid Kimai assets filename:
<img width="489" alt="Bildschirmfoto 2020-02-23 um 13 39 32" src="https://user-images.githubusercontent.com/533162/75112210-ed296f00-5641-11ea-82ab-eced6b9043a0.png">
Something is changing the URLs and I guess it is a browser plugin.

**Comment by ZoXx** [comment]
Okay, sorry my bad.
It was my domain there before!

**Comment by kevinpapst** [comment]
I don't care about the domain name, but the filename. This is how it should look:
<img width="930" alt="Bildschirmfoto 2020-02-23 um 13 42 02" src="https://user-images.githubusercontent.com/533162/75112261-47c2cb00-5642-11ea-9612-46c73a13c8ea.png">
```
<link rel="stylesheet" href="/build/app.2bde4971.css" integrity="sha384-3bVuRNKO8FkMuSAu5Eefo+HJ9WNpiJsrIefh0qSdQsbk+8+MA1zre/NZ/AGrY1M9">
```
Compare these URLs in IE and Chrome.

**Comment by ZoXx** [comment]
Internet Explorer:
 <link rel="stylesheet" href="/build/A.app.8240996d.css.pagespeed.cf.eqjR21wt-X.css" integrity="sha384-ZaS4ro6HGbDfLyaJc8cVXJzTd8plX3mRzhHhiiUEErSzPlRKdZfViDk23BNvAaz+">

Chrome:
 <link rel="stylesheet" href="/build/A.app.8240996d.css.pagespeed.cf.eqjR21wt-X.css" integrity="sha384-ZaS4ro6HGbDfLyaJc8cVXJzTd8plX3mRzhHhiiUEErSzPlRKdZfViDk23BNvAaz+">

**Comment by kevinpapst** [comment]
Then you are running this: https://developers.google.com/speed/pagespeed/module
???

**Comment by ZoXx** [comment]
You're right! I deactivated it and it's running now. But now the other subdomains and the main domain without pagespeed are running. Is there a way to disable pagespeed only on the subdomain or to get Kimai running with pagespeed?

**Comment by kevinpapst** [comment]
Never used it, sorry can't help with that.

**Comment by ZoXx** [comment]
Okay but thank you very much!
