### ISSUE TITLE
login after setup

### ISSUE THREAD

**Issue by thaelke** [kevinpapst/kimai2#1493]
Hi, i installed yunoHost /kimai2 on a virtual mashine.

YunoHost and Kimai can be accessed via the URL

But i cant login with the admin user, i created. 
Is there a default second admin, or where might I find the users table in order to set a new admin?

**Comment by kevinpapst** [comment]
At this point of time, I cannot recommend to use YunoHst, as the version is outdated...
You can create a new user in the login screen. 
If you have access to the command line, you can use `bin/console fos:user:demote` to give this new user the role `ROLE_SUPER_ADMIN`

**Comment by thaelke** [comment]
What setup would you recommend? I can run it on any system, thats available / possible in a Hyper-V mashine.

**Comment by kevinpapst** [comment]
Simple SSH installation on any recent Linux with PHP >= 7.3 support. 
I'd go with an Ubuntu LTS, but that's just my personal flavor.
