### ISSUE TITLE
Invoice generation cares for user permissions

### ISSUE THREAD

**Issue by marcelcremer** [kevinpapst/kimai2#1494]
**Describe the bug**

This is most likely not a bug, but maybe a conceptional gap?

- We have configured permissions so that employees cannot see time entries from other employees, so that we have some privacy about each employees personal work performance. 
- We also allowed our Team leaders to create invoices for customers, which entries don't include the name of the executing employee.

However: 
When the team leader tries to print an invoice, only his own activities are invoiced to the customer, because it seems like the invoice generation cares for time entry visibility permissions.

As I said, I'm not really sure, if this is a "bug" or maybe it's even intended, but if so, I cannot think of a reasonable case, where it would make sense to send the customer an invoice about only a part of the work for the project (one invoice per executing worker)🤔 

**To Reproduce**

1. Create a team leader, who has no access to other people's activities
2. Log some time with him / her and a colleague on the same project
3. Generate an invoice for this project with the team leader - the colleagues activities are missing

**Additional context**
Linux kimai 5.3.0-26-generic 28-Ubuntu x86_64

**Comment by kevinpapst** [comment]
This is intended and used by several customers. Think of companies who only work with contractors. These contractors use it to invoice the company.

From my pov your configuration is not really logical. Either your teamlead can see other users entries or he can't. If he can't, he won't be able to invoice them.

But maybe we need a new permission for accessing the team timesheets page. 
Then you could use `view_other_timesheet` to allow access to other users data and at the same time forbid to access them.

**Comment by marcelcremer** [comment]
```
This is intended and used by several customers. Think of companies who only work with contractors. These contractors use it to invoice the company.
```
So you give the contractors access to a kimai instance, where they can write the invoices for you? Mhm okay, if there are use cases, it's no bug, but a feature request 👍  Sorry for that.

```
From my pov your configuration is not really logical. Either your teamlead can see other users entries or he can't. If he can't, he won't be able to invoice them.
```

Well, he needs to create a timesheet for the customer project, which of course needs to contain all entries. But he doesn't need to see, that John Doe has already made 5000€ in chargeable hours, while he only made 4000€. 

It's a huge difference for work councils etc. if timetracking happens to create bills for a customer or project vs. it can be used to compare the work performance for different employees.

```
But maybe we need a new permission for accessing the team timesheets page.
Then you could use view_other_timesheet to allow access to other users data and at the same time forbid to access them.
```

So yeah, the team leader needs to be able to send the "anonymous" invoice to the customer, so he needs to see the time entries for this, but he must not be able to see time entries to track work performance.

I'd need a schroedinger's cat permission 😄

Does this explanation make any sense?

**Comment by kevinpapst** [comment]
You could also hide the rate column in the timesheets for teamleads, there is a special permission for that (something like `view_rate_other_users`).

Besides that: I do understand the issue. But I am not sure that this should be solved in Kimai (complicated) or you should restructure your workflow.

Some workflows simply cannot be adapted with the default implementation. If you have special requirements you could create your own plugin to create invoices, re-using existing code. Thats rather simple and I have done it for some customers before.

**Comment by marcelcremer** [comment]
Got it - thank you very much for your answer and patience. I'm going to check back, how much we're able to alter the workflow - otherwise I'll give the plugin development a try. If I have something generalized, I'll let you know - might be interesting for other people too.

Till that, I'm going to close the ticket for the time being.

Thanks again, cheers

**Comment by kevinpapst** [comment]
What I do in these cases: create a customer specific plugin (see DemoBundle in the docs).
Clone the invoice controller and adapt the code to your requirements.
You can also hire me to do it for you.
