### ISSUE TITLE
Columns "Order number" and "Order date" not visible in Projects overview 

### ISSUE THREAD

**Issue by dhoeld** [kevinpapst/kimai2#1498]
**Describe the bug**
Since Kimai 1.7 there is no option for enabling column visibility of columns **order number** and **order date** in the **Projects** overview anymore. 

**To Reproduce**
1. Go to Projects
2. Click on the icon for changing column visibility

**Logfile**
```
```

**Screenshots**
![Screenshot from 2020-02-25 20-14-03](https://user-images.githubusercontent.com/6930035/75279388-cfa80100-580b-11ea-8d53-12118760a93e.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Desktop
 - OS: Win 10 Pro/Ubuntu Linux
 - Browser Firefox, Chrome

**Additional context**
 - Kimai version 1.7

**Comment by kevinpapst** [comment]
Yes. The complete column visibility logic needs a rewrite which is already planned.

**Comment by kevinpapst** [comment]
the latest changes in master include many more fields for the project view.
You have to activate them, by default they are hidden:
<img width="599" alt="Bildschirmfoto 2020-03-15 um 14 11 56" src="https://user-images.githubusercontent.com/533162/76702048-efbe3800-66c6-11ea-9d17-df9cf5783b2d.png">
