### ISSUE TITLE
Need help with new translations

### ISSUE THREAD

**Issue by SaroTaz** [kevinpapst/kimai2#1500]
Kimai is fresh-installed on linux 18.04 (nginx + mysql)
I try to create from scratch a new custom ita translation (i've tried to editing messages.it.xlf coping the content from messages.en.xlf and translating the terms but error 500 before the login screen).
I've followed this [guide](https://www.kimai.org/documentation/translations.html):
1. copy all file *.en.xlf in *.ita.xlf
2. update the headers
3. translate the terms (i'll do it later)
4. update services.yaml, app.js and calendar.js
5. clear cache

When i go to preferences or settings usual error 500 with usual 

> Something is wrong
A critical error occurred, please try again. You may have found a software problem, please contact your administrator if the problem persists.

**Comment by kevinpapst** [comment]
`ita` is not a valid locale. Do you mean Italian? This is `it` and already existing (probably not complete though).

Please edit the existing `.it.xlf` files and add the ones that are missing.

You have either an error in the services.yaml or one of the XML files is invalid.

You can check translation files with `bin/console lint:xliff translations`.
And with `bin/console lint:yaml config --parse-tags` you check if the changes in service.yaml are the problem.

**Comment by SaroTaz** [comment]
Ita is a **my custom locale**. I create a "new" version of italian locale naming it "ita" to maintain "it" standard traduction.

I would create a complete (and customized) locale for ita.


With _bin/console lint:xliff translations_ the response is 

> [OK] All 281 XLIFF files contain valid syntax

With _bin/console lint:yaml config --parse-tags_ the response is 

> [OK] All 59 YAML files contain valid syntax

**Comment by kevinpapst** [comment]
In that case the error is something else. Open "Doctor" or check var/log/prod.log after seeing the error.

**Comment by SaroTaz** [comment]
Here my log after error

> [2020-02-26 19:18:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Intl\Exception\MissingResourceException: "Couldn't read the indices [Names][ita] for the locale "ita" in "/var/www/kimai2/vendor/symfony/intl/Resources/data/locales". The indices also couldn't be found for the fallback locale(s) "en", "root"." at /var/www/kimai2/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php line 175 {"exception":"[object] (Symfony\\Component\\Intl\\Exception\\MissingResourceException(code: 0): Couldn't read the indices [Names][ita] for the locale \"ita\" in \"/var/www/kimai2/vendor/symfony/intl/Resources/data/locales\". The indices also couldn't be found for the fallback locale(s) \"en\", \"root\". at /var/www/kimai2/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php:175, Symfony\\Component\\Intl\\Exception\\ResourceBundleNotFoundException(code: 0): The resource bundle \"/var/www/kimai2/vendor/symfony/intl/Resources/data/locales/root.json\" does not exist. at /var/www/kimai2/vendor/symfony/intl/Data/Bundle/Reader/JsonBundleReader.php:39)"} []

**Comment by kevinpapst** [comment]
Thats what I said:

**Comment by kevinpapst** [comment]
You could fake it with one of the it sub-locales: 

Italienisch (it)
Italienisch (Schweiz) (it-CH)
Italienisch (Italien) (it-IT)
Italienisch (San Marino) (it-SM)
Italienisch (Vatikanstadt) (it-VA)

**Comment by SaroTaz** [comment]
Some terms in *.it.xlf files are missing so my idea is 
1. copy all the *.en.xlf files 
2. rename or move all *.it.xlf from translations folder
3. rename file previulsy copied in *.it.xlf
4. edit these files opportunely

Could it works?

**Comment by kevinpapst** [comment]
If you just want to add the missing translation, then why not simply editing the existing files + creating the missing files by copying from en?

**Comment by SaroTaz** [comment]
Ok. I try to explain by an example:
This part (extracted from messages.en.xlf) is entirely missing on messages.it.xlf

> <trans-unit id="admin_entity.delete_confirm">
                <source>admin_entity.delete_confirm</source>
                <target>
                    This data will be deleted as well!
                    Alternatively, you can select an entry to which all data will be transferred:
                </target>
            </trans-unit>

Translate only terms from original en files is faster than search missing partes, copy-paste and edit.

**Comment by kevinpapst** [comment]
Really? Don't you have any text editor that can compare files? You can see directly the differences and especially what is missing. That should be much faster than your approach ... here for example: 
<img width="1269" alt="Bildschirmfoto 2020-02-26 um 21 03 44" src="https://user-images.githubusercontent.com/533162/75382806-7d361580-58db-11ea-9112-5ad7e3fa160e.png">
Otherwise you could also delete all Italian files and recreate them from scratch (I would prefer the diff method).

**Comment by SaroTaz** [comment]
It's very complicated environment at this time. The server is up in a virtual machine and my access is restricted to terminal. So i edit (only for test) with nano :-) But i'll try to gain full access and set a ftp. 
Thanks for your patience and for help.

**Comment by kevinpapst** [comment]
You should do it very differently. I assume you are not familiar with git, so the best way is to download the ZIP: https://github.com/kevinpapst/kimai2/archive/master.zip
Then edit the files locally and upload the changed files here as ZIP. 
I will help you with the rest of the process.

**Comment by SaroTaz** [comment]
I solve by myself removing all *it.xlf files and copy-past all *.en.xlf and translating all terms in nano (yes big work but less time then you imagine). If it's a way to extract these files from virtual machine i can share with you the whole it locale but it is customized for use in my company (some terms are slightly different from original meaning and adapted for my specific use)

**Comment by kevinpapst** [comment]
You can define shared directories between host and vm. Copy the files into the shared directory, then you can access them.
I want generic terms, but maybe we can solve that after you were able to save them.
If you keep it like you did currently, you will run into trouble with the next update.

**Comment by SaroTaz** [comment]
Ok. I'll re-work on locale files adapting it to general purpose. When done, i'll send directly to you. Thanks for support.
