### ISSUE TITLE
Wrong duration for time entries in the future with undefined end

### ISSUE THREAD

**Issue by flofeld** [kevinpapst/kimai2#1501]
**Describe the bug**
For time entries beginning in the future the duration is negative und formatted incorrectly.

**To Reproduce**
1. Make a time entry with start set to a future time and end undefined.
2. Check the timesheet overview

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/388640/75356863-cb81ef00-58b0-11ea-89a7-1eb0a6a39940.png)

**Additional context**
Kimai 1.7

**Comment by kevinpapst** [comment]
So many people wanted to see the duration of running records... now they have it^^
