### ISSUE TITLE
Logo and invoice_salutation

### ISSUE THREAD

**Issue by DanSman** [kevinpapst/kimai2#1502]
I sent Kevin an email and asked him: How to implement a logo and how to change the salutation?  
He mentioned that I should use Github so that everyone knows how it works etc. So I'm doing this ;)  

[Logo](https://www.kimai.org/documentation/invoices.html#twig-templates)

Thanks for that!
  
invoice_salutation:  
> Do not use this "label" translation, but your own text. 
You don't seem to use Kimai 1.7 yet, do you?
This translation doesn't exist anymore (at least with 1.8, don't know exactly when I deleted it).
  
I'm on 1.7 as well.   
So, I disabled `label.invoice_salutation` and added my own text:
```
                Thank you!
<!--            {{ 'label.invoice_salutation'|trans|nl2br }}-->
```
I thought that was possible in the GUI? Or is it?

Thanks again
Dan

**Comment by kevinpapst** [comment]
Try to use `{{ model.template.paymentDetails|nl2br }}` which is the free editable "Payment terms" field in the GUI

**Comment by kevinpapst** [comment]
ping @DanSman any feedback?
