### ISSUE TITLE
Removal of Help and About section

### ISSUE THREAD

**Issue by sathyajackson** [kevinpapst/kimai2#1503]
Hi,

I really love your tool and its awesome to use. I would like to know how can i remove the about section in user profile and the help section from all the pages.

I did followed your Icon documentation and i was able to remove only the ICON but not that whole part.

Do let me know as to how to remove those from the page.

**Comment by infeeeee** [comment]
[Custom CSS plugin](https://www.kimai.org/store/keleo-css-custom-bundle.html) can do this!

To hide the help button add this in the plugin's settings: 
```
.btn.btn-help {
    display: none;
}
```
For the removal of the about box on profile pages add this: 
```
.col-md-4 .box.box-secondary:nth-child(2) {
    display: none;
}
```
This latter one is not a nice solution, but nor the profile page nor the about box has a unique class. My quick test found that this rule doesn't affect any other boxes on the demo website currently, but in future updates this can hide other boxes accidentally. 

Maybe we can add a class to the about box and to the profile pages. to make this second rule more future-proof.

**Comment by kevinpapst** [comment]
Or with your own bundle. Both things can be filtered.
