### ISSUE TITLE
Adding meta field in timesheet issue

### ISSUE THREAD

**Issue by SpoorthiPalakshaiah** [kevinpapst/kimai2#1504]
How could I get a meta field in timesheet? I followed the official docs https://www.kimai.org/documentation/meta-fields.html 
In /opt/kimai/src/EventSubscriber, I added MetaFieldSubscriber.php and MetaFieldDisplaySubscriber.php with code as in documentation but I'm unable to get metafields..

**Comment by kevinpapst** [comment]
See https://github.com/Keleo/DemoBundle

**Comment by SpoorthiPalakshaiah** [comment]
After using this https://github.com/Keleo/DemoBundle I'm getting 500-Error
![image](https://user-images.githubusercontent.com/43110794/75504838-90da9c80-59ff-11ea-91fe-95add48b1d52.png)

**Comment by kevinpapst** [comment]
Check var/log/prod.log 
Maybe the latest DemoBundle is using features from the upcoming 1.8, I don't know exactly

**Comment by SpoorthiPalakshaiah** [comment]
Is there any other way to add metafield without using plugins..

**Comment by kevinpapst** [comment]
No. And it's working exactly as written in the docs. I know many people who use them successfully.
But you can also support Kimai by buying the MetaFields bundle from the marketplace.

**Comment by SpoorthiPalakshaiah** [comment]
Should MetaFieldSubscriber.php and MetaFieldDisplaySubscriber.php in EventSubscriber in /opt/kimai/src?
And we should add only these 2 files right?

**Comment by kevinpapst** [comment]
I don't understand the question. Have a look at the DemoBundle, its all in there:
https://github.com/Keleo/DemoBundle

**Comment by kevinpapst** [comment]
No feedback, closing
