### ISSUE TITLE
Question - Can one migrate directly from 1.6 to 1.8

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1511]
This is a question and not a bug.
I am currently running 1.6 can I directly migrate to 1.8 or do i have to migrate one by one depending on each release and finally upgrade to 1.8. Kindly help since I do not want to mess up my live system.

**Comment by kevinpapst** [comment]
You can directly jump to 1.8, no problem. I added it to the update docs. 
But It would recommend that you setup a second Kimai instance only for these kind of tests.
