### ISSUE TITLE
Excel export with table format

### ISSUE THREAD

**Issue by yayitazale** [kevinpapst/kimai2#1512]
**The exported excel archive is not formatted as a table**

**Solution**
Format the excell as a table, with titles and so, This is the guide to do it manually: https://support.office.com/en-us/article/Format-an-Excel-table-6789619F-C889-495C-99C2-2F971C0E2370

Thanks

**Comment by kevinpapst** [comment]
Which export exactly? 
And I have no Excel for testing, so I need dev help with that one.

**Comment by yayitazale** [comment]
Export > Excel

![imagen](https://user-images.githubusercontent.com/6462849/75674284-102cd200-5c85-11ea-93ce-fd867d739df2.png)

This is hat we get:
[kimai-export-original.xlsx](https://github.com/kevinpapst/kimai2/files/4275207/kimai-export-original.xlsx)
And this is the same but with table format:
[kimai-export-titles.xlsx](https://github.com/kevinpapst/kimai2/files/4275208/kimai-export-titles.xlsx)

**Comment by kevinpapst** [comment]
Maybe this is related: https://stackoverflow.com/questions/50934401/phpspreadsheet-multiple-tables-with-format-as-table-in-excel-worksheet

**Comment by HeinzWuert** [comment]
Maybe this would solve the problem with loosing the autostart of the macro when creating the excel sheet.

**Comment by yayitazale** [comment]
> 
> 
> Maybe this is related: https://stackoverflow.com/questions/50934401/phpspreadsheet-multiple-tables-with-format-as-table-in-excel-worksheet

You only need 1 table format as table.

**Comment by kevinpapst** [comment]
@HeinzWuert this is the export, which creates the excel dynamically, instead of parsing an existing template file.

@yayitazale yes, but I have no idea how to apply that. if anyone knows how to set that style on the table, I am happy to integrate it into kimai.

**Comment by yayitazale** [comment]
I found this, maybe it can be usefull:

https://github.com/PHPOffice/PhpSpreadsheet

**Comment by kevinpapst** [comment]
Yes and no. 
Yes: this is the library I am using to generate the excel files.
No: I couldn't find any documentation how these table styles can be applied.

**Comment by kevinpapst** [comment]
now available in master
