### ISSUE TITLE
Regarding user specific hourly rates in Kimai2 1.8

### ISSUE THREAD

**Issue by arno1979** [kevinpapst/kimai2#1514]
Hi Kevin,

I just upgraded to v1.8 and struggled to comprehend the new hourly rates concept.
If I understand correctly the hourly rate is set on a user level. But what if I have a user with different hourly rates depending on the customer?
Also: I have a custom PDF export template. Up until v1.7 I used the twig variable `{{ query.customer.hourlyRate }}` to display the hourly rate above the expense list. How can I access the users hourly rate now?
I tried to find another variable containing the hourly rate but debugging is difficult because I can't set the `APP_ENV=dev` in `.env` anymore without producing a symfony error. Sorry for not being more specific but I rolled back my Kimai2 setup to v1.7 for the time being.

Thanks Arno

**Comment by kevinpapst** [comment]
> If I understand correctly the hourly rate is set on a user level. But what if I have a user with different hourly rates depending on the customer?

Its like before, but you can now define additionally user specific rates per activity/project/customer. Not interesting for freelancers, but I'd say more than 50% of the users are companies who need that differentiation.

> Up until v1.7 I used the twig variable {{ query.customer.hourlyRate }} to display the hourly rate above the expense list

There is no replacement for that right now. The applied hourly rate shouldn't be of any interest, but I do understand that everyone has different needs... if you have a custom export, you have custom PHP code as well, don't you? In that case you could load it. Or you use a custom field for that information. Or use an unused field (eg. customer number) to store and access it.

> because I can't set the APP_ENV=dev in .env anymore without producing a symfony error

Thats very likely because you are missing composer dependencies. If you switch to `dev`, you need to run `composer install` as well.

**Comment by arno1979** [comment]
Thanks for the quick reply.

> Its like before, but you can now define additionally user specific rates per activity/project/customer. Not interesting for freelancers, but I'd say more than 50% of the users are companies who need that differentiation.

I'm sorry but I don't get that. The hourly rate fields from the activity/project/customer settings are gone (at least in my setup) and the only place where I can enter the hourly rate is in my user's profile.

> if you have a custom export, you have custom PHP code as well, don't you? In that case you could load it.

Ok, I'll have to see about that if I can find the time, thanks!

> Thats very likely because you are missing composer dependencies. If you switch to dev, you need to run composer install as well.

I didn't know that, was not a problem before, but that could be coincidence. I'll try your suggestion.

**Comment by kevinpapst** [comment]
> The hourly rate fields from the activity/project/customer settings are gone

No, just somewhere else. See **Fees** at the bottom.
<img width="918" alt="Bildschirmfoto 2020-03-02 um 16 55 35" src="https://user-images.githubusercontent.com/533162/75693013-acb39c00-5ca6-11ea-8f6d-c70019b5b734.png">

**Comment by arno1979** [comment]
Ah!

> No, just somewhere else. See Fees at the bottom.

I always edit customers using the context menu which appears if I click on the down arrow at the right. But in the popup window the fees section is not included. Thanks for pointing that out!

**Comment by kevinpapst** [comment]
If you always use the same hourly rate for one invoice, just take the hourly rate from the first timesheet entry.

**Comment by BeckeBauer** [comment]
@arno1979 : have you been able to realise the showing of the hourly fee? 

I am looking for a (global) variable to show the "project.hourlyRate" (which differs from project to project). Presumably like you, I use two tables, the first to give an overview of the costs (total time x hourlyRate = invoice amount) and the second to show the individual timesheet entries (without rates). 

I was not able to include the hourly rate from the first timesheet entry (as suggested by Kevin) in the first overview. 

Any suggestions are appreciated...

**Comment by arno1979** [comment]
@BeckeBauer It has been sometime since I worked on this but the way I got this working was to write a custom plugin, placing it in the "var/plugins" directory. That way I was able to create a custom PDF export button and use my custom PDF template. In this template I could access a template variable `{{ projectRate }}` which I added in the CustomPDFBase class.
I put the code on GitHub:
https://github.com/arno1979/kimai2-custom-export.
If you want have a look at it. It contains some translations in German, but I suspect this won't be a problem for you. :)

**Comment by kevinpapst** [comment]
Nice one @arno1979 👍 If you would tag your repository with `kimai`, `kimai2`, `kimai-bundle`, `kimai-plugin` it would be easier to find by other users (you can do that in the about section of the repository start page).

**Comment by arno1979** [comment]
@kevinpapst Thanks for the thumbs up! It's appreciated. I added the tags, but I just wanted to mention - also to @BeckeBauer  - that the error handling in the plugin is not very good. For instance: If you want the export to not throw an unspecified error you HAVE TO select a customer and a project before hitting the "Custom PDF Export" button.
Also the hourly rate will only appear on the timesheet if a corresponding value is set for the respective project.

**Comment by BeckeBauer** [comment]
Thanks for the feedback... 
Indeed, German translations do not cause headaches, the code does (since I am not a programmer)... unfortunately, I use doxc (since I need to further adjust the invoices) so that I cannot use your plugin ... 
maybe some day, the "project.hourlyRate" will be introduced as global variable so that it can be used without a specific timesheet entry (but I understand that people might have different hourly rates within the same project)

**Comment by arno1979** [comment]
DOCX should be possible as well. But you need programming skills, that's for sure.
When I built my plugin I used the code for existing export options as a template and figured out (also with Kevin's help) how to integrate the plugin into the Kimai environment. But it definitely took some fiddling around.
But I just saw that there is no DOCX export present by default so that would mean an additional obstacle because one would have to create an DOCX export plugin from scratch.
