### ISSUE TITLE
Switch Positions of "Save" and "Close" Button 

### ISSUE THREAD

**Issue by tchristiansen** [kevinpapst/kimai2#1515]
**Is your feature request related to a problem? Please describe.**
As the „Save“ Button is on the right side in most UI’s (with LTR Languages), my (and i guess others) behaviour is trained to click the "bottom right" button so submit changes.
Because of the I often have to edit my entries twice.

**Describe the solution you'd like**
Switch positions of "Save" and "Close" button:

- "Close" bottom left
- "Save" bottom right

![Bildschirmfoto 2020-03-03 um 11 40 05](https://user-images.githubusercontent.com/4445885/75769054-c35d0000-5d45-11ea-8d1e-1833f7a55331.png)

**Comment by kevinpapst** [comment]
Your arrow implicates swapping the order, which I am not a fan of. Or do you mean => move it to the right side but keep the order?
Regarding the order: https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/

Several reasons for the current order: 
- keyboard users needs one keystroke less
- mouse users need less distance
- the highlighted button already tells you where to click

**Comment by tchristiansen** [comment]
Yes, I mean swapping them, basically by moving the "pull-left" class from "Save" to "Close".

The summery of the linked article states: "Following platform conventions is more important than optimizing an individual dialog box". I'm mainly working on MacOS, which puts OK in last position.

Maybe adding a "Preferred OS" option in the user settings would be a trade-off, to allow all users to choose to which order they are used to.

I injected some additional css to my server, to solve it for me. But maybe other mac users might have the same issue.

**Comment by kevinpapst** [comment]
You could share the CSS rule and we make it a pre-defined rule in  https://github.com/Keleo/CustomCSSBundle

**Comment by tchristiansen** [comment]
It's just: `#remote_form_modal  #form_modal_save { float: none !important }
#remote_form_modal .btn-cancel { float: left }`

BTW: This doesn't change the focus order for keyboard users. The order is still "Save" -> "Cancel".

**Comment by kevinpapst** [comment]
Tab order isn't changed, thanks to the floating trick, as HTML structure is still the same. And we could still set the tab order via HTML, so this argument is rather weak on my side anyways ;-)

Thanks for sharing, lets see if somebody else votes for this issue.

**Comment by BeckeBauer** [comment]
See possible solution in #1297

**Comment by strouble** [comment]
i am also used to have the save button on the right side and the back/close button on the left. My solution was to add a `pull-right` to the save and a `pull-left` to the close/back buttons in the templates. The tab order is still the same. I could also think of a "theme configuration option" for this.

**Comment by kevinpapst** [comment]
Quoting @yayitazale from #1621 

> I usually click on close instead of clicking on save because the cancel/confirm buttons of the date selector confuses my mind. Green line what my mind does to confirm and yellow line what I'm asking for, to swap save and close buttons on record creation
> 
> ![imagen](https://user-images.githubusercontent.com/6462849/78681560-33364b80-78ed-11ea-836b-c69b07179707.png)
> 
> Thanks

**Comment by kevinpapst** [comment]
Rule included in CustomCSSBundle:
https://github.com/Keleo/CustomCSSBundle/releases/tag/1.2

Thanks @lduer for the contribution and @tchristiansen for raising awareness of that topic 👍
