### ISSUE TITLE
Can't stop time tracking

### ISSUE THREAD

**Issue by WeirdCircumstances** [kevinpapst/kimai2#1520]
First I would like to say thank you for this project!

This is after a fresh install:
Right after creating the first time tracker, I tried to stop it. I got a 405 "Method not allowed."  

This is in the log:
```[2020-03-04 14:00:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /api/timesheets/2/stop": Method Not Allowed (Allow: PATCH)" at /var/www/html/kimai2/vendor/symfony/http-kernel/EventListener/RouterListener.php line 140 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/timesheets/2/stop\": Method Not Allowed (Allow: PATCH) at /var/www/html/kimai2/vendor/symfony/http-kernel/EventListener/RouterListener.php:140, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/kimai2/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:42)"} []```

![image](https://user-images.githubusercontent.com/6939992/75882281-24a5d180-5e21-11ea-9b30-ca30e4ab63a8.png)

Even when trying to delete it, this error appears:
```{"message":"Authentication required, missing headers: X-AUTH-USER, X-AUTH-TOKEN"}```
(Nothing in the logs afterwards.)

![image](https://user-images.githubusercontent.com/6939992/75882304-325b5700-5e21-11ea-94c5-165658b5fc96.png)

**Additional context**
 - Kimai 1.8
 - PHP 7.3.14-1
 - Apache/2.4.38 (Debian)

I'm shure the error is on my side (config), so I need some help in solving this.

Thanks in advance!

**Comment by kevinpapst** [comment]
Looks like you have either javascript disabled or a browser plugin is changing the requests.
First error:
You cannot open these URLs in a new browser tab, that won't work.
Second error: A header is missing, either client side or your server configuration is removing unknown headers?

**Comment by WeirdCircumstances** [comment]
Wow, that's it!

Problem was in my apache config: 
`Header set Content-Security-Policy "default-src 'self';"`

Thank you and problem solved! ;)
