### ISSUE TITLE
API methods for Fees

### ISSUE THREAD

**Issue by kbancerz** [kevinpapst/kimai2#1523]
**Is your feature request related to a problem? Please describe.**
With 1.8 version hourly rate field was removed from Project model. Instead, Fees functionality has been introduced - which is a welcome feature in my opinion. However, there is no option create/modify/delete entries with API.

**Describe the solution you'd like**
Add methods for Fee-related operations to Project and Activity API.

**Comment by kevinpapst** [comment]
> Add methods for Fee-related operations to Project and Activity API.

And customer.

**Comment by kbancerz** [comment]
> And customer.

Right.
