### ISSUE TITLE
Accounting person cannot see Time Sheets

### ISSUE THREAD

**Issue by AlexanderOsswald** [kevinpapst/kimai2#1525]
Situation:
Configured and running system with customers, projects, activities, some teams of customers with their team leaders. Everything is running fine.

Problem:
The time accounting is managed not by the team leader. The time accounting (evaluate and export the time sheets) managing is done by an separate accounting person. But this accounting person has no view privileges to see the "other" time sheets of all the other users in all other teams.

Workaround:
Put the accounting person into the role "ROLE_ADMIN". But the accounting person should not have privileges to change some customers, projects or activities!

other Workaround:
Set the accounting person as the team leader. But this is also not correct, the team leader is an another person!

Can anybody help me to solve this problem?
Is it possible to set a second team leader to a team?

**Comment by kevinpapst** [comment]
Create a team and put accounting as teamleaader.
Add all other users to that team.

**Comment by AlexanderOsswald** [comment]
quite simple, but works - BUT: now this person can see the time sheets of this month only, but there are time sheets from the last month also (no invoice, not exported).
How can i setup the time sheet view to see all time sheets (as like the admin)?

**Comment by kevinpapst** [comment]
The date range is always set from the search form, nothing else.
Are you talking about the "team timesheets" or some kind of export?

**Comment by AlexanderOsswald** [comment]
first of all i talk about the "Timesheets" page. (The second action will be export to Excel.)
If i login as administrator i get a list of 50 entries, sorting descending by date and can switch to the next page with the rest of timesheets.
If i login as the "accounting person" and click on "Timesheets" i get a list of 17 entries, at the next page(2) a list of 18 entries, but all from this month.
![2020-03-05_17h31_18](https://user-images.githubusercontent.com/61834425/76003498-68273b00-5f08-11ea-93c5-a59fcbd7abd7.png)


(second thing, maybe a bug)
Than the software get strange results: If i click on the search field and select "10 entries per page" i get a list of 4 entries and 9 pages....

**Comment by kevinpapst** [comment]
Which Kimai version is that?

**Comment by AlexanderOsswald** [comment]
1.7

**Comment by kevinpapst** [comment]
Did you assign all customers to team of the accounting person?

**Comment by AlexanderOsswald** [comment]
yepp

**Comment by kevinpapst** [comment]
In the screenshot I only see one customer. Should there be more?

**Comment by AlexanderOsswald** [comment]
thats correct, there is only one customer in the database at this time

**Comment by AlexanderOsswald** [comment]
do you like a live access and/or phonecall?
(Or take the Bus Line 213 to Ottobrunn....)

**Comment by kevinpapst** [comment]
Or you come over to Waldperlach ^^
But anyways, sent me a email. I am interested in that really "special looking" bug.

**Comment by kevinpapst** [comment]
Found the underlying problem and likely a bugfix as well, please test #1542
