### ISSUE TITLE
Problems with the update from version 0.9 to 1.8

### ISSUE THREAD

**Issue by pixelladen** [kevinpapst/kimai2#1529]
I try to update my Kimai (version 0.9) to the current version 1.8 with the console. (Hosting at all-inkl.com with Apache, PHP 7.2, MySQL 5.7.28) I follow the instructions in the KIMAI documentation. With two of the commands I get the following error messages:

Command: 
**git checkout 1.8**
Message: 
_error: Your local changes to the following files would be overwritten by checkout:
         templates / export / renderer / pdf.html.twig
         templates / invoice / renderer / timesheet.html.twig
Please commit your changes or stash them before you switch branches.
Aborting_

and

Command: 
**bin/console kimai:update**
Message: 
_Command "kimai:update" is not defined.
       Did you mean one of these?
       kimai: codestyle
       kimai: convert-timezone
       kimai: create-release
       kimai: create-user
       kimai: import-v1
       kimai: reset-dev
       kimai: test integration
       kimai: test unit
       kimai: version
       translation: update_

What can I do?

**Comment by kevinpapst** [comment]
The git checkout didn't work because you changed the files:
templates / export / renderer / pdf.html.twig
templates / invoice / renderer / timesheet.html.twig

Create a backup of these files and then run `git reset --hard`. 
Then re-execute the update commands.
If everything works, then you can read in the invoice documentation how to create custom templates and where to store them.

**Comment by pixelladen** [comment]
OK. Thank you very much.

**git checkout 1.8** now issues: _HEAD is now at b8273c4 prepare release 1.8 (# 1505)_

But **bin / console kimai: update** brings the following error message in the console and also in the browser:

```
PHP Fatal error: Uncaught Error: Class 'Symfony \ WebpackEncoreBundle \ WebpackEncoreBundle' not found in /www/htdocs/w00582ad/timer.pixelladen.de/kimai2/src/Kernel.php:97
Stack trace:
# 0 /www/htdocs/XXXX/XXXX/kimai2/vendor/symfony/http-kernel/Kernel.php(424): App \ Kernel-> registerBundles ()
# 1 /www/htdocs/XXXX/XXXX/kimai2/vendor/symfony/http-kernel/Kernel.php(130): Symfony \ Component \ HttpKernel \ Kernel-> initializeBundles ()
# 2 /www/htdocs/XXXX/XXXX/kimai2/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony \ Component \ HttpKernel \ Kernel-> boot ()
# 3 /www/htdocs/XXXX/XXXX/kimai2/vendor/symfony/console/Application.php(145): Symfony \ Bundle \ FrameworkBundle \ Console \ Application-> doRun (Object (Symfony \ Component \ Console \ Input \ ArgvInput ), Object (Symfony \ Component \ Console \ Output \ ConsoleOutput))
# 4 / www / htdocs / XXXX / XXXX / kimai2 / bin / console (40): Symfony \ Component \ Console \ Application-> run (Object (Symfony \ Component \ Console \ Input \ ArgvInput))
# 5 {in /www/htdocs/XXXX/XXXX/kimai2/src/Kernel.php on line 97
```

What do I have to do now?

**Comment by kevinpapst** [comment]
Follow the upgrading guide: https://www.kimai.org/documentation/updates.html

One more tip: As you are coming from a very old version, please delete the cache manually from INSIDE the Kimai directory "rm -r var/cache/prod/"

**Comment by pixelladen** [comment]
OK. Thank you very much . Now it worked :-)

**Comment by kevinpapst** [comment]
Wow, good news. 
Then you are the first person to make such a big update in one step. 
Thanks for your feedback!

**Comment by pixelladen** [comment]
uff, thats fine ;-)

**Comment by 3ruce** [comment]
I've also upgraded successfully from 0.9 to 1.8... thank you for the pointers...

**Comment by kevinpapst** [comment]
Good to hear that it works generally 👍 
If you can share any steps that might have crashed and how you solved it, you will help the next and probably less experienced person.
