### ISSUE TITLE
Invoice generation not taking quantity into consideration

### ISSUE THREAD

**Issue by redspart** [kevinpapst/kimai2#1531]
**Describe the bug**
Preface: I did modify the twig template. Some of the timesheets were generated with the `period insert plugin`. 

When an invoice is generated the total isn't summed up properly. It seems that `model.calculator.timeWorked` doesn't take quantity into consideration. Also I noticed,  If another timesheet had 4 hours, the total would be 12.

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Browser Firefox

**Additional context**
 - This is running in a vscode dev container. I pulled your code about a week ago and mount each folder (src/plugins/invoices...) into their correct spot. 
 - Kimai 1.8 dev
 - Symphony 4.4.4
 - Docker 19.03.6

------

**Screenshots**

**From the actual invoice:** 
<img width="643" alt="Screen Shot 2020-03-06 at 4 46 13 PM" src="https://user-images.githubusercontent.com/11378450/76125082-0deeae80-5fca-11ea-9be0-fcd04fc56cbb.png">

------

**From the preview window:**
<img width="261" alt="Screen Shot 2020-03-06 at 4 33 38 PM" src="https://user-images.githubusercontent.com/11378450/76124535-e1866280-5fc8-11ea-87e5-7af3774058fa.png">

**Comment by kevinpapst** [comment]
Can you try that in the demo and see if it happens there as well?
If so, I need more infos about the invoice settings and the exact timesheets

**Comment by redspart** [comment]
It isn't happening in the demo stable oddly enough. I pulled your code and rsync'ed the dirs on what's in my prod and restarted the docker-compose. It didn't fix it.

 My solution for now: modify the `timesheet.html.twig` to add a manual calculation like what's in `default.html.twig`.

**Comment by kevinpapst** [comment]
I assume you cleared the cache after syncing?

**Comment by redspart** [comment]
Yes I have cleared the cache multiple times

**Comment by kevinpapst** [comment]
Don't know what to do with that one. Usually if it works in the demo, I close the issue ...
Lets wait for the next version / docker image and see if that fixes your issue.
If not re-open the issue / open a new one.
