### ISSUE TITLE
editing translation not visible

### ISSUE THREAD

**Issue by ateliernz** [kevinpapst/kimai2#1546]
Question: I edited /translations/messages.nl.xlf

I cleared cache. I ran bin/console lint:xliff translations to validate - a lot of errors, but not for my file.

However, I don't see any changes. I think I do something wrong.

**Comment by kevinpapst** [comment]
> a lot of errors, but not for my file.

What errors?

**Comment by ateliernz** [comment]
for all .xliff-files: 
ERROR  in translations/invoice-numbergenerator.da.xliff
 * There is a mismatch between the language included in the file name ("invoice-numbergenerator.da.xliff") and the "da" value used in the "target-language" attribute of the file.

**Comment by kevinpapst** [comment]
Can you upgrade to the latest Kimai version? That error does not exist here.

**Comment by ateliernz** [comment]
last time i tried upgrading from 1.6.2 to  1.7 went wrong. It's not really easy to do from command line if you're not used to like me. I got some errors and I couldn't fix it/understand it, so I put the folders and files back from backup and it works now. 

Installing also wasn't easy on a Synology NAS. Trick was to install php7.2 on Synology, install composer.phar in the kimai2 folder via command line and run sudo php72 composer.phar instead of composer commands.

**Comment by kevinpapst** [comment]
Do you know that article: https://www.kimai.org/documentation/synology.html#updating-kimai

But back to topic: translation files should be reloaded when the cache was cleared.
Without seeing the file, I cannot help.

**Comment by ateliernz** [comment]
Never found it, but that looks promising!

I guess: first update, then, if still existing, shoot this issue again?

**Comment by kevinpapst** [comment]
Its your system ... at some point an upgrade should be done.
I could have a look at the translation file anyways, but need to know what you changed.

**Comment by ateliernz** [comment]
Well, I copied the nl file for backup and edited the original like [this](http://apps.ateliernoordzuid.nl/messages.nl.xlf)

**Comment by kevinpapst** [comment]
hahaha ... but actually NL should be nl_NL and not nl_BE or whatever the code for flemish is.
Inviting @1willem into the discussion.
And I cannot download the file, always run into a timeout. Please attach it in your post

**Comment by ateliernz** [comment]
[this](https://we.tl/t-QpBbOP57Dk)

**Comment by kevinpapst** [comment]
Works fine on my end. Just copied the file to my installation and I see e.g. "Mijn uren" as label for the timesheet menu

**Comment by ateliernz** [comment]
Thanks for testing. This issue can be closed. First I need to update my installation
