### ISSUE TITLE
Team zugewiesenen

### ISSUE THREAD

**Issue by john307** [kevinpapst/kimai2#1550]
Guten Tag!

Ich habe eine kurze Frage.

Ist es möglich, einem einem Team zugewiesenen Benutzer zu erlauben, die Arbeitszeittabellen aller Mitglieder desselben Teams anzuzeigen? Wenn ja, welches Recht darf dem Benutzer zugewiesen werden? Andernfalls, wenn dies nicht möglich ist, wird diese Funktion in Zukunft implementiert?
 
Ich freue mich auf ihre Rückmeldung und Danke für die freundliche Unterschützung.
 
Mit freundlichen Grüße,

**Comment by kevinpapst** [comment]
Das wurde bereits hinreichend hier diskutiert, z.B. nur einen Beitrag tiefer:
https://github.com/kevinpapst/kimai2/issues/1549

**Comment by kevinpapst** [comment]
See https://github.com/kevinpapst/kimai2/issues/1292 and vote for it with 👍 on the initial post
