### ISSUE TITLE
Hide already exported times on 'My times' / default filter

### ISSUE THREAD

**Issue by ToeiRei** [kevinpapst/kimai2#1553]
I usually need an overview of all of the positions which haven't been billed yet. Basically, everything that's been exported is only for legal/archival needs. Is it possible to set a filter per default/user for 'My times'?

**Comment by kevinpapst** [comment]
Not yet. I always check open positions via the export screen.
In the future I want to have bookmarks for filters/searches. One of them could be made the "favorite" filter, which would be used as default.

**Comment by ToeiRei** [comment]
Sounds good to me, as long as every user can have his default view.

**Comment by kevinpapst** [comment]
Sure, bookmarks would work per-user.
