### ISSUE TITLE
invoice counter for customer

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1554]
We use an invoice number system starting with the year, followed by the number of the invoice of the year, followed by the number of the invoice of the customer in this year. 

Let's say we already issued 20 invoices in 2020 and we want to issue the second invoice to Customer A. The invoice number would look like 2020-021-02

Thus, I would appriciate if a year counter for the customer like ``{cyc}`` could be added.

**Comment by kevinpapst** [comment]
Will be added for 1.10, see #1836
