### ISSUE TITLE
delete invoices from archive

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1555]
Issued invoices can be shown and payment status can be updated but otherwise, modification is not possible.

Sometimes, an invoice needs to be modified or even deleted (after justified complaints by the customer). 

In this case, I need to access the database and clear the entry in the table kimai2_invoices. An option to do so within Kimai2 would be very much appriciated.

**Comment by kevinpapst** [comment]
Please don't do it via database. If you do, remember to delete the generated invoice file in var/data/invoices/

**Comment by BeckeBauer** [comment]
Thank's for the hint - was wondering why I got an error after deletion in the database and re-creation. 

This folder gives also a (temporary) solution if I need to modify an invoice. 

Is there a way to define a different path for the invoice copies?

**Comment by kevinpapst** [comment]
In theory you can move the complete data directory somewhere else:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L301
But not the invoices directory on its own.
