### ISSUE TITLE
show non-visible customers under team tab

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1556]
I want to assign non-visible customers (old customers) to the team "Archive". 

Is there a way to make them appear (currently, only visible customers are shown and can be assigned to teams)?

A box "select all" would also very much appreciated (I know, I had this request previously and I can use the javascript command in the browser console to select all at once - but it would just be more comfy ;-)

**Comment by kevinpapst** [comment]
No, I reject that. Hidden customers are hidden. This setting is there to prevent to large lists.
If you need to assign them to a team, then reactivate them for a couple of seconds.
I am not sure though what will happen when you edit the team the next time.

For the other one, add a new feature request please.

**Comment by BeckeBauer** [comment]
I didn't mean to show them all at once but similar to the customer tab either or 

The customer list in the team tab is big anyway if you won't use the invisible feature. But if you do and have a list of let's say 50 invisible customers, it is quite an effort to make them visible again, asign them to a different team and make them invisible again since there is no bulk option. 

But I guess I will not be able to convince you

**Comment by kevinpapst** [comment]
In this case I have a strong opinion, yes. 
I don't want hidden items to show up anywhere, for me "hidden" is like a "soft delete". 

I just tried it and I think the best way to achieve the same is (more tedious, I know):
Search for all hidden customers, edit one by one and assign it from the customer details screen to your "Archive" team. Still less work than making them visible again.
