### ISSUE TITLE
API Entry (Timesheet) readonly by User

### ISSUE THREAD

**Issue by BernadoEco** [kevinpapst/kimai2#1558]
How can I, as an administrator, create (per API) an entry (Timesheet) that cannot be deleted by the user?
I use:
{
    "begin": start, 
    "end": end,
    "project": project,
    "activity": activity,
    "description": description,
    "user": id (from User)
  }

**Comment by kevinpapst** [comment]
A user can either delete its own entries or not, it has nothing to do with the way you create the entry.
That is defined by its user role / a permission https://www.kimai.org/documentation/permissions.html

**Comment by kevinpapst** [comment]
No feedback, closing
