### ISSUE TITLE
Issue when updating from 1.6 to 1.8

### ISSUE THREAD

**Issue by Regnalf** [kevinpapst/kimai2#1559]
Tried to update from 1.6 to 1.8 and got this error at the end of the composer install command:

```
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) in /data/web/e24498/html/kimai2-gg6/vendor/symfony/translation/TranslatorInterface.php on line 24
!!  
Script @auto-scripts was called via post-install-cmd
```

**Comment by kevinpapst** [comment]
Do `rm -rf var/cache/*`and run it again

**Comment by Regnalf** [comment]
Done ... but now a new error occur :-/
If this is server dependent i think i have to call my hoster.

```
Writing lock file
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  Fatal Error: composer.lock was created for PHP version 7.2.9 or higher but the current PHP version is 7.1.32.
!!  
Script @auto-scripts was called via post-update-cmd
```

**Comment by kevinpapst** [comment]
Hm. Kimai is not compatible with PHP 7.1 and wasn't before. So you must have installed it differently. Maybe prefix the command with `php73` if you are running on a shared host.

**Comment by kevinpapst** [comment]
Ok, new information which I didn't saw. If you are running web version with 7.3 but getting this error on the command line, then you have to find out how to use 7.3 on the command line as well.

You can use `which php` to find out the path for the SSH version of PHP and then try to find the executable for 7.3 that way => or you call your hoster if you are not that familiar with the bash. The installation docs has a short chapter about shared hosts and the PHP version problem as well.

**Comment by Regnalf** [comment]
Ok, it seems that the standard php is set on 5.6.40
I'm on a shared host, so i can't go to the path where "which php" points to. I tried to run composer with another php version, but i didn't get it run yet

**Comment by kevinpapst** [comment]
Read this chapter, even if you use another hoster (which one?):
https://www.kimai.org/documentation/installation.html#shared-hosting

Every hoster has multiple command line php versions, for sure.

**Comment by kevinpapst** [comment]
no feedback, closing
