### ISSUE TITLE
 How can I integrate the database on the old system to the new version?

### ISSUE THREAD

**Issue by furkantolu** [kevinpapst/kimai2#1561]
Hi, I am upgrading the 1.7 version to 1.8 due to the excel export problem. I will work in a separate domain.

1-) How can I create an additional menu for the menus in Tab. I will only put one embed on the page content.
2-) How can I integrate the database on the old system to the new version?

--

For the 1st case I mentioned;
In the meantime, I changed the doctor part to planner. It worked fine with admin, but users could not see it. I want to open the Planner section to all users.

I'm not good at PHP and backend software, I almost don't know, my boss wants me to do it. 
![Ek Açıklama 2020-03-16 170847](https://user-images.githubusercontent.com/32983969/76766368-ef966900-67a8-11ea-9910-73f57c3058c4.png)
![Ek Açıklama 2020-03-16 170904](https://user-images.githubusercontent.com/32983969/76766371-f02eff80-67a8-11ea-865e-646d1034d0e6.png)
![Ek Açıklama 2020-03-16 170931](https://user-images.githubusercontent.com/32983969/76766375-f0c79600-67a8-11ea-9f10-106767e3bb3f.png)

Thanks for your help in advance.

**Comment by kevinpapst** [comment]
Most of your answers should be clarified here: https://www.kimai.org/documentation/developers.html

Don't "abuse" an existing menu for your own extension. That will lead to several problem, like the permission checks (search for something like `isGranted`).

There is a demo bundle, which you can use as starting point for your own stuff:
https://github.com/Keleo/DemoBundle

**Comment by kevinpapst** [comment]
no feedback, closing
