### ISSUE TITLE
Support: can't get LDAP to work

### ISSUE THREAD

**Issue by 10erlosh** [kevinpapst/kimai2#1563]
Thank you for this great piece of software!
I'm trying to get LDAP connection working, so i did

1. `apt install php-ldap`
2. `composer require zendframework/zend-ldap`
3. add a minimal openLDAP config to local.yaml
4. `bin/console kimai:reload`
5. fix permissions

but i keep getting 

```
[2020-03-16 21:24:31] request.CRITICAL: Uncaught PHP Exception Exception: "Zend\Ldap\Ldap is missing, install it with "composer require zendframework/zend-ldap" or deactivate LDAP, see https://www.kimai.org/documentation/ldap.html" at /var/www/kimai2/src/Ldap/LdapDriver.php line 61 {"exception":"[object] (Exception(code: 0): Zend\\Ldap\\Ldap is missing, install it with \"composer require zendframework/zend-ldap\" or deactivate LDAP, see https://www.kimai.org/documentation/ldap.html at /var/www/kimai2/src/Ldap/LdapDriver.php:61)"} []
```

when trying to login with the initial local admin user.
When i try to login with an LDAP account i get no log-message but 

> Authentication request could not be processed due to a system problem.

on the login-page.

Thanks in advance!

System info:

```
root@kimai:/var/www/kimai2$ bin/console about
 -------------------- ----------------------------------------------------- 
  Symfony                                                                   
 -------------------- ----------------------------------------------------- 
  Version              4.4.4                                                
  Long-Term Support    Yes                                                  
  End of maintenance   11/2022                                              
  End of life          11/2023                                              
 -------------------- ----------------------------------------------------- 
  Kernel                                                                    
 -------------------- ----------------------------------------------------- 
  Type                 App\Kernel                                           
  Environment          prod                                                 
  Debug                false                                                
  Charset              UTF-8                                                
  Cache directory      ./var/cache/prod (6.1 MiB)                           
  Log directory        ./var/log (449 KiB)                                  
 -------------------- ----------------------------------------------------- 
  PHP                                                                       
 -------------------- ----------------------------------------------------- 
  Version              7.3.14-1~deb10u1                                     
  Architecture         64 bits                                              
  Intl locale          en_US_POSIX                                          
  Timezone             Europe/Berlin (2020-03-16T21:45:14+01:00)            
  OPcache              true                                                 
  APCu                 false                                                
  Xdebug               false                                                
 -------------------- ----------------------------------------------------- 
  Environment (.env)                                                        
 -------------------- ----------------------------------------------------- 
<retracted>                                     
 -------------------- ----------------------------------------------------- 
```

```
root@kimai:/var/www/kimai2$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by kevinpapst** [comment]
Try to `rm -rf var/cache/prod` and then run 4 & 5 again

**Comment by 10erlosh** [comment]
no success

**Comment by kevinpapst** [comment]
Was zendframework/ldap really installed?
What does git status report? Was composer.locl changed?
Does vendor/zend/ldap/ or vendor/zendframework/ldap exist?

**Comment by buoncri** [comment]
Try ... "composer require zendframework/zend-ldap"

--
P.S. @kevinpapst,  Just an idea ... can it be awful to have ldap composer dep in the default installation ?

**Comment by kevinpapst** [comment]
Yes, zend framework requires ext-ldap which means composer won't install any package if it is missing => which is the case on many ... many ... many ... I really mean A LOT OF servers. 
Generally a good idea and I appreciate any input! 
But in that special case impossible, as 90% of the users wouldn't be able to install Kimai.

**Comment by 10erlosh** [comment]
It turned out to be a server problem:
I did not notice that the `composer require` command was failing all the time :man_facepalming: 

<pre><font color="#EF2929"><b>root@kimai</b></font>:<font color="#729FCF"><b>/var/www/kimai2</b></font>$ composer require zendframework/zend-ldap --profile
<span style="background-color:#C4A000"><font color="#2E3436">Do not run Composer as root/super user! See https://getcomposer.org/root for details</font></span>
[181.3MiB/0.92s] Using version <font color="#4E9A06">^2.10</font> for <font color="#4E9A06">zendframework/zend-ldap</font>
[181.3MiB/0.92s] <font color="#4E9A06">./composer.json has been updated</font>
[186.2MiB/1.05s] <font color="#4E9A06">Loading composer repositories with package information</font>
[186.6MiB/1.06s] <font color="#4E9A06">Updating dependencies (including require-dev)</font>
Killed
<font color="#EF2929"><b>root@kimai</b></font>:<font color="#729FCF"><b>/var/www/kimai2</b></font>$ </pre>

After assigning 1024MB of RAM (it was 512MB before) to that LXC everything is fine and working like a charm now :wink:

**Comment by kevinpapst** [comment]
Thanks for the feedback!

**Comment by 10erlosh** [comment]
Thanks for the hints!
