### ISSUE TITLE
Remove Rate section from PDF exported report

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#1564]
Hi,

is there a way to remove the "rate" section from the exported PDF

![image](https://user-images.githubusercontent.com/40264293/76867825-baece500-686e-11ea-921e-303694f5c912.png)

**Comment by kevinpapst** [comment]
Sure. But you might get into troubles with the next update if you are not familiar with git.

You could edit this line:
https://github.com/kevinpapst/kimai2/blob/master/templates/export/renderer/pdf.html.twig#L7
and change it to `{% set showRateColumn = false %}`

**Comment by kevinpapst** [comment]
You have to reload your cache afterwards.

**Comment by Jurgens92** [comment]
Thank you,

I did the changes, and reload cache/redo permissions and it didnt work, so i went through the code and change the following:

https://github.com/kevinpapst/kimai2/blob/master/templates/export/renderer/pdf.html.twig#L2

to: {% set showRateColumn = true %}

and then it worked, thank you for pointing me into the right direction :)

**Comment by kevinpapst** [comment]
Ah, I missed that line. You should change both, otherwise the rate column might show up again when you add a user to the export filter.
