### ISSUE TITLE
Question: Making exported entries available

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1567]
Is it possible for administration to re-export more than one single entry in timesheets?
Because of changes from the customer more than 40 entries have to be re-exported.
Actualy this results in a click-party for the administration.

**Comment by kevinpapst** [comment]
If you are able to exactly filter these records, than you can use the "toggle" button in the upper right of the export screen (the button will first show up, after clicking preview).

**Comment by HeinzWuert** [comment]
Thanks, it works!
