### ISSUE TITLE
Unable to get minimal plugin to load

### ISSUE THREAD

**Issue by thexa4** [kevinpapst/kimai2#1570]
I'm trying to implement a plugin so as a first step I tried to follow the steps outlined here: https://www.kimai.org/documentation/plugins.html

This resulted in the following code: https://github.com/DelftSolutions/kimai-vacation-hours

Unfortunately I can't seem to get it to show up in the plugin list after running `bin/console kimai:reload`. The reload command does successfully throw an error if I add a `routes.yaml` file to the Resources/config folder so it is being opened.

I've tried comparing my code with the DemoBundle that is able to load but given the amount of code in there I'm not sure what code is essential to have. Is there a minimal plugin example anywhere?

There are no errors in var/log/prod.log nor in the apache log. Is there a way to view error that occur during loading?

**Additional context**
I'm developing using Kimai 1.8 on php v7.3.11-1~deb10u1 on Debian 10.

**Comment by kevinpapst** [comment]
Hi @thexa4 !
Thanks for posting and sharing.
Try to rename https://github.com/DelftSolutions/kimai-vacation-hours/blob/master/DependencyInjection/VacationHours.php to `VacationHoursExtension.php` and give it another try

**Comment by kevinpapst** [comment]
And change 
```
git clone https://github.com/delftsolutions/kimai-vacation-hours.git VacationHours
```
to 
```
git clone https://github.com/delftsolutions/kimai-vacation-hours.git VacationHoursBundle
```
Kimai has some [bundle loading magic](https://github.com/kevinpapst/kimai2/blob/master/src/Kernel.php#L121) that relies on the directory name, which needs to end with `Bundle` => so it must be called `VacationHoursBundle `

**Comment by thexa4** [comment]
Thanks for the quick reply! I changed both but it's not showing up.

**Comment by kevinpapst** [comment]
Have you ever worked with Symfony before? 
The extension is loaded during container compile time, not during runtime.
So if you add a `die()` without any output in there, the container will not be rebuilded and you are using the previous cache.

**Comment by thexa4** [comment]
Oh, wow, sorry. Didn't realize I left that in. Thanks!

**Comment by thexa4** [comment]
It works, thanks for making Kimai!

**Comment by thexa4** [comment]
In case anyone coming after me needs a minimal example: https://github.com/DelftSolutions/kimai-vacation-hours/commits/minimal-example
