### ISSUE TITLE
Calendar date picker not using i18n setting

### ISSUE THREAD

**Issue by noyez** [kevinpapst/kimai2#1572]
**Describe the bug**
When user preference is set to English, so first day of week is Sunday, the date-picker still uses Monday as first day of week, although the main calendar view displays the correct order of days. See screenshot.

**To Reproduce**
1. Set users's preference to Enlish so calendar starts on Sunday
2. Add entry in timesheet.
3. Click on *From* field to bring up calendar
4. Observer calendar has first day of week as Monday.

**Screenshots**

![Screen Shot 2020-03-19 at 11 31 12](https://user-images.githubusercontent.com/1292949/77085138-4af96e80-69d6-11ea-9a79-1c93ae81fd5d.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Firefox 74.0

**Additional context**
 - Kimai version: 1.8
 - PHP version: php-7.2

**Comment by kevinpapst** [comment]
English is just the translation, not the locale. Not all English speaking countries use Sunday as first day of the week. I'd say it's quite the opposite as many users have to use English, as Kimai is not translated to their own language.

Probably the first day of the week should be configurable, or in a more global scale => the users country / locale ...

But you are right that is should be consistent.
I am not sure why that is different, maybe the datepicker doesn't respect the first day of week setting from moment.js.

**Comment by kevinpapst** [comment]
I believe this was fixed in 1.9.
But with the next release I added a user specific setting for the "first day of week", see #1952 - so I am linking this issue with PR.
