### ISSUE TITLE
AD authentification 

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1578]
It's probably no bug but the other categories did not fit as well. 

I freshly installed Kimai from the latest master with "composer require laminas/laminas-ldap" (not sure if it applies since the documentation says "from Kimai 1.9 on")

When I use the login credentials of a user existing in the directory server, I get the error message "_Authentication request could not be processed due to a system problem._" 

Unfortunately, var/log does not show a logfile.

I can, however, create a local user and login. 

Any idea how I could get more information about the error (probably my configuration in the local.yaml)?

**Comment by kevinpapst** [comment]
For master laminas is correct.
Did you try APP_ENV=dev to get more logs?

**Comment by BeckeBauer** [comment]
now, I got a lot of information... no idea what might be of help...

**Comment by kevinpapst** [comment]
where?

**Comment by BeckeBauer** [comment]
I feel bad to copy the whole logfile for you to check since I assume that my local.yaml configuration is the problem; any chance that you could provide paid support in this matter (from other issues, I understand however that AD is not your favorite issue)?

**Comment by kevinpapst** [comment]
email please :)

**Comment by BeckeBauer** [comment]
seems that the active directory app on Synology supports Samba/Kerberos autentification and not ActiveDirectory/LDAP (not much documentation available) so that it won't work with Kimai (yet)...
