### ISSUE TITLE
Multitenant kimai instance

### ISSUE THREAD

**Issue by marcus905** [kevinpapst/kimai2#1581]
**Is your feature request related to a problem? Please describe.**

My company works in a shared office space where every company has its own timeclock system. To reduce costs we are developing a shared timeclock hardware system that interacted through REST APIs with the timeclocking system of each company.
However, since we use kimai internally, we were wondering if it was possible to implement a company/division section so that all timeclocking could be managed in a single platform, further reducing the expenses of all companies that rent offices here, if they so prefer.

**Describe the solution you'd like**

Ideally, there should be a Companies/Division section, in which the same functionality of the kimai system should be there (companywide admin, teams, etc.). 

All companies could be managed by the superadmin, which can also add, edit and remove companies. An admin instead could be assigned to one or more companies, and he could do as it is done right now, and userwise, nothing should change.
All setting that make sense at the company level (like timeclock mode) could be moved to the company level, with sane defaults to use as template for new companies, while maybe the branding section could be duplicated having a general prelogin branding logo (in my scenario the shared office space logo) while, once the user logged on, the logo of his company should show, if he is assigned to only one company, while if he is not assigned to any company or he is assigned to 2 or more companies, the same prelogin logo should show with a menu to select the company, maybe.

I have some experience (not much) in PHP programming, so if I have some pointers on what to do where I could try giving it a go.

**Comment by adrianrudnik** [comment]
Just to do a sanity check here:
What exactly is the feature set of this new super admin / super company role?
Just add and remove companies / tenants?
If you want to offer Kimai as SaaS, why not simply use docker to deploy a new instance for a new tenant and keep their data separated (instead of co-joined forever)? That would also provide a clean exit strategy to export data if they decide to leave your system and want to migrate to their own.

**Comment by marcus905** [comment]
Hi,
well, yes.

Docker instances seem the solution to my problem.

The superadmin role would exactly as you stated, and in the Docker scenario that task would be done by the release dev or sysadmin.

I think I will use docker then, thank you very much and sorry for the trouble!
