### ISSUE TITLE
Install on IIS

### ISSUE THREAD

**Issue by Brdisek** [kevinpapst/kimai2#1583]
Hi, 
I would like to ask, if it is possible to install Kimai on Win Server with IIS. On server PHP 7.4 and MySQL is running. I instaled composer too. Do I need something more? Thanks for help.

**Comment by infeeeee** [comment]
> This is not officially supported, basically because I have no way to test it…

From the docs: https://www.kimai.org/documentation/webserver-configuration.html#iis-on-windows-or-azure

Also read this issue: https://github.com/kevinpapst/kimai2/issues/979#issuecomment-514895906 

It seems that it's possible.

**Comment by Brdisek** [comment]
Thanks for help, but It still doesn't work. I prepared PHP, to my folder unzip everything from kimai-release-1.8.zip. Run myfolder/public and still have error 500 or error 404.0 - C:\inetpub\wwwroot\kimai\public\cs\homepage not found. I tried to edit web.config but I have C:\inetpub\wwwroot\kimai\public\web\app.php\ not found. 
Could you please help me to find right way. Thanks

**Comment by infeeeee** [comment]
Are you following blindly the simfony documentation? In kimai there is no `web`, nor `cs` folder in the `public` directory. Try Elijha's example in the linked issue. 

Maybe we can ping @Elijha to help.

We can't really help any more on this unfortunately. If you figure it out please share how you made it work.

**Comment by Brdisek** [comment]
I tried @Elijha script for web.config but what I see is phpinfo page. Throw Git I installed everything how it is written on kimai.org page. Succesfully added First user, but I can't see it in browser.

**Comment by adrianrudnik** [comment]
Maybe a stupid idea, but... if you can run php and composer on the shell, can you not just run the symfony app via `bin/console server:run 127.0.0.1:8080` (and later server:start to spawn it in the background) and use the IIS as simple reverse proxy to `127.0.0.1:8080`?

**Comment by Brdisek** [comment]
bin/console server:run 127.0.0.1:8080

In FilesystemLoader.php line 106:

  The "C:\inetpub\wwwroot\kimai/assets/css" directory does not exist ("C:\ine
  tpub\wwwroot\kimai/assets/css").

**Comment by adrianrudnik** [comment]
@Brdisek that sounds strange. Does that path exist on your filesystem? Maybe try to switch the path separators around (`/` instead of `\`)?

**Comment by Brdisek** [comment]
this path doesn't exist. 
I found some video about install and I realized that a lot of folders are missing on my server.

**Comment by Brdisek** [comment]
I don't know why I don't have instalation folder for first run...

**Comment by adrianrudnik** [comment]
@Brdisek are the permissions correct in `var/`, is it writeable? Why is the path incorrect while using mingw, why use mingw?

**Comment by Brdisek** [comment]
@adrianrudnik permission is correct it is writeable. Mingw used because it was in installation instructions - use git. I install GitDash and I used it. First time worked with that.

**Comment by kevinpapst** [comment]
You are mixing Kimai 1 (video) and Kimai 2 (which doesn't have an install folder).
If assets/ is missing, you are trying to use the FTP version. Do yourself a favor and switch to installation via git.

@adrianrudnik the webserver-bundle `bin/console server:run` was removed with 1.7 or 1.8

**Comment by Brdisek** [comment]
@kevinpapst  I saw. Sorry. I reinstalled complete Kima 2 and now I am able to enter the web site from IIS directly. Problem is, when I use browser from another computer. Than the address is incorrect. There is cs/homepage after correct URL and I don't know how to solve it

**Comment by kevinpapst** [comment]
Great ,one step further 👍 Indeed: `cs/homepage` is a valid redirect in Kimai.
You need to activate URL rewriting in IIS - but I have no clue how. I never used IIS and this is not really a Kimai issue either.

**Comment by Brdisek** [comment]
@kevinpapst I know. I'll search. I hope I'll find something

**Comment by Brdisek** [comment]
Thanks everyone for help! I solved. Reinstall complete Kimai once more, control the permission. Then I write this web.config and now it works corretly.
web.config:
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <defaultDocument>
            <files>
                <remove value="Default.htm" />
                <remove value="Default.asp" />
                <remove value="index.htm" />
                <remove value="index.html" />
                <remove value="iisstart.htm" />
                <remove value="default.aspx" />
                <remove value="default.php" />
            </files>
        </defaultDocument>
        <rewrite>
            <rules>
                <rule name="Redirect index.php" stopProcessing="true">
                    <match url="index\.php/(.*)" />
                    <action type="Redirect" url="{R:1}" appendQueryString="false" />
                </rule>
                <rule name="Rewrite index.php">
                    <match url="(.*)" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php/{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

**Comment by kevinpapst** [comment]
Thanks for sharing @Brdisek !
