### ISSUE TITLE
(Automatic) split times according to business times

### ISSUE THREAD

**Issue by F1reF0x** [kevinpapst/kimai2#1585]
**Is your feature request related to a problem? Please describe.**
No bug/problem

**Describe the solution you'd like**
I am looking for a way to split times accordingly when business hours start/end. On top of that (but not "important" would it be great to set rates for customers/projects depending on business hours.
For example: my office is open from 7 to 17 o'clock. When work while business hour is done the rate should be for example 100€. When work is outside business hours, then for example 150€. At first it would be great to find a way (generate invoice?) to have an export/print of times, splitted to outside/inside business hours.

Example: Work was done from 16 to 18 o'clock (2 hours) it would nice to have 16 to 17 and 17 to 18 o'clock and optional with different rates.

**Describe alternatives you've considered**
Stopping a task  an starting it manual.

**Additional context**
none

**Comment by kevinpapst** [comment]
You can do quite complex things with invoice templates, eg. when using excel sheets you could achieve these feature with formulas. 

With a custom plugin you could achieve the same logic, eg. by adding a Timesheet Calculator.

**Comment by kevinpapst** [comment]
Too complex to be handled in one issue, especially when different topics are mixed.
I do not have plans to support that kind of logic in the near future.
Considering that this is 2 years old and has no votes, I am closing for now.
I somebody wants to pay a feature like that, please reach out via email.
