### ISSUE TITLE
Menu TEAM visible for teamleader but no content

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1587]
Question:
How can I give the team leader the right to see all teams with all their members?
With the current permissions I can make the TEAMS menu visible to the team leader, but no content is displayed.

**Comment by kevinpapst** [comment]
You can't. Teamleads can only see their own teams on purpose.
These informations should not be leaked to non-privileged users.

**Comment by HeinzWuert** [comment]
I need a admin role with only read privileges except own data.
Thats also not possible to realize with the permissions for Agmin, afaiIk.

**Comment by kevinpapst** [comment]
Thats the same topic like viewing all timesheet records.
At one point I will add that feature and change the logic, which currently only checks for the "admin" roles. I am just not completely sure yet how to do it.

**Comment by HeinzWuert** [comment]
Maybe a new role Admin2 as a simple copy, but than it would be possible to change the editing rights.
