### ISSUE TITLE
Issues with creating and showing invoices

### ISSUE THREAD

**Issue by Sarmingsteiner** [kevinpapst/kimai2#1589]
When trying to save an invoice in Kimai2 1.8, this error message occurs:

_"An exception occurred while executing 'INSERT INTO kimai2_invoices (invoice_number, created_at, timezone, total, tax, currency, due_days, vat, status, invoice_filename, customer_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)': SQLSTATE[HY000]: General error: 1 no such table: kimai2_invoices"_

**Nevertheless, the invoice is saved in the var/data/invoices directory.**

When clicking on the list button (right corner) to show the already created invoices, an error page appears, showing a bug-symbol, the error message _"Something is wrong
A critical error occurred, please try again. You may have found a software problem, please contact your administrator if the problem persists."_ , and a button heading to the dashboard.

Any ideas?

**Comment by kevinpapst** [comment]
Yes: you are using master version with 1.8 database. Thats why FTP is crap. 

Upload the 1.8 files and use ONLY the assets directory from this ZIP: https://github.com/kevinpapst/kimai2/archive/1.8.zip
