### ISSUE TITLE
local.yaml

### ISSUE THREAD

**Issue by Brdisek** [kevinpapst/kimai2#1595]
I hope this is my last question for a long time. Sorry for that. 
I tried to build local.yaml like this:
kimai:
    user:
        country: CZ
        currency: CZK

because when users are building new companies they have country DE and currency EUR. 
Is something wrong in this file?
I have this when reloading:
![reload](https://user-images.githubusercontent.com/62537861/77792985-9f04f280-7069-11ea-914e-3dd55fdb3a0e.JPG)

**Comment by kevinpapst** [comment]
The error doesn't make a lot of sense to me. 
Did you notice the permission denied above the red box?

Anyway, you can revert these changes and and set it via UI:
<img width="988" alt="Bildschirmfoto 2020-03-27 um 20 32 13" src="https://user-images.githubusercontent.com/533162/77793286-176bb380-706a-11ea-9597-034c225692ed.png">

**Comment by Brdisek** [comment]
Ok, I'll say to admin

Can you please help me to which place is that permission? 
Thanks

**Comment by kevinpapst** [comment]
If there is no file mentioned, how shall I know... I am not a magician 😁 
Always check var/log/prod.log to see if there are more errors shown.

**Comment by Brdisek** [comment]
I understand, sorry :)
In prod.log is nothing to this error.
