### ISSUE TITLE
Get user preferences - hourly rate via API

### ISSUE THREAD

**Issue by amanzone** [kevinpapst/kimai2#1602]
I would need to get each user's hourly rate using the API (this should be one of the user preferences): how should I do it?

I'm not sure if it's already feasible (and I just cannot find it) or if this is missing.

Thanks in advance for your help.

Ciao,
Alberto

**Comment by paconte** [comment]
Hello,

I am not an expert of Kimai2 however I am currently testing the API. 

The hourly rate is available via the Timesheet. You can access it with the REST API call to /api/timesheets/{id}. For more info check the API documentation at https://demo.kimai.org/api/doc. Remember to login first at the demo to be able to see the documentation.

**Comment by kevinpapst** [comment]
Please note that the rate system will soon change and rate specific methods will be added:
https://github.com/kevinpapst/kimai2/pull/1591

The users own hourly rate is afaik not available via API. 
You might be able to set it, but I believe you can't read it.

**Comment by amanzone** [comment]
Yes, I also believe it's not accessible via API. Of course you can get it via timesheets, but that might be different and also you may not yet have a timesheet.

Anyway, with the coming changes, do you this the user own rate will still be present?
Currently, as it's not accessible via API, we get it directly from the db (I'm not too comfortamble with this, I know). But if you believe this user rate might be moved to a different table, that's something I need to plan for.

**Comment by kevinpapst** [comment]
The users own rate will stay where it is. It is still used as fallback, if you don't use eg. project specific rates.

You can also add an API call as plugin, which will return that value (the DemoBundle has examples for new API calls).

**Comment by kevinpapst** [comment]
@amanzone are you willing to provide a PR with a new API route to fetch the users hourly rate? Should be only a couple of lines and I can help...

**Comment by kevinpapst** [comment]
Hourly rate is available under the `preferences` node:
<img width="740" alt="Bildschirmfoto 2022-03-18 um 16 41 43" src="https://user-images.githubusercontent.com/533162/159035005-13b60509-7376-4ad8-be6b-ca7789b824fe.png">

Example answer:
<img width="324" alt="Bildschirmfoto 2022-03-18 um 16 42 16" src="https://user-images.githubusercontent.com/533162/159035146-7f6a3b46-a640-43fd-ae66-680364c107e0.png">
