### ISSUE TITLE
Login Screen - Loop

### ISSUE THREAD

**Issue by Hanner72** [kevinpapst/kimai2#1603]
**Original Deutsch**
Hallo,

Ich hab die Version 1.8 installiert. Bisher lief alles reibungslos. Heute wollten sich ein paar User einloggen, jedoch funktionierte dies nicht.
Es gab einen Loop im Login Screen.
Usernamen eintragen, Passwort eintragen und danach auf einloggen klicken. Danach leeren sich die beiden Felder und man kann wieder die Daten eingeben.

Bitte um Hilfe.
Dies ist operativ im Einsatz und wird dringend gebraucht.
Danke.

**Google Translate English**
Hello,

I installed version 1.8. So far everything went smoothly. A few users wanted to log in today, but this didn't work.
There was a loop in the login screen.
Enter username, enter password and then click on login. Then the two fields empty and you can enter the data again.

Please help.
This is operational and is urgently needed.
Thank you.

**Versions**
 - Kimai version 1.8
 - PHP version 5.4, 7.0 and 7.4

**Comment by kevinpapst** [comment]
Software geht nicht einfach kaputt ohne zutun von anderer Seite... was wurde wo geändert? 
Dateiberechtigungen korrekt?
Was steht im Log unter var/log/prod.log?

**Comment by Hanner72** [comment]
Es ist keine prod.log vorhanden.

**Comment by Hanner72** [comment]
Ich vermute dass der Speicherplatz am Server voll war.
Speicherplatz am Server wurde erhöht, jetzt funktioniert wieder alles.

Zu meiner Verteidigung.
Es läuft NUR Kimai auf diesem Server und ich dachte dass die Datenbank den Speicherplatz nicht so anfüllen kann. Jedoch machten dies automatisch die Backups.

Jetzt läuft wieder alles.
Danke.

**Comment by kevinpapst** [comment]
Dieses Login Problem deutet immer darauf hin, das Kimai keine Sessions erzeugen kann. 
Meistens ist das Problem:
> Dateiberechtigungen korrekt?

Aber Speicherplatz voll ist auch so ein Klassiker, den man selten direkt richtig zuordnen kann.
