### ISSUE TITLE
Subresource integrity is breaking the application if it is hosted behind a reverse proxy (a.k.a. how to disable .js integrity?)

### ISSUE THREAD

**Issue by Philippe-Arnaud** [kevinpapst/kimai2#1604]
**Describe the bug**
The js won't load properly if the application server is located behind a reverse-proxy running on a firewall.

Possible solution would require to disable the integrity check for .js

_How can I disable the Subresource integrity in the server configuration?_

**To Reproduce**
1. Install Kimai following the documentation
2. Try to serve the server behind a reverse proxy that inspects SSL and changes the payload
3. .js won't load and the whole application is broken

**Logfile**
Irrelevant as the problem is not related to the application itself.

**Screenshots**

![image](https://user-images.githubusercontent.com/767823/78033882-4bdfb800-7367-11ea-9587-ca7b2710d54f.png)

![image](https://user-images.githubusercontent.com/767823/78033571-dd9af580-7366-11ea-8a75-4104b50bec56.png)

**Desktop/Smartphone**
Same issue regardless of browser unless using IE (which don't support subressource integrity)

**Additional context**
Kimai 1.8

**Comment by kevinpapst** [comment]
You cannot turn them off.
Maybe you can remove the `integrity` block: https://github.com/kevinpapst/kimai2/blob/master/public/build/entrypoints.json#L43
Or you rebuild the frontend assets with deactivated hashes:
https://github.com/kevinpapst/kimai2/blob/master/webpack.config.js#L20

Or you tell your proxy to not fuck up the files ... the integrity check only fails if the files are being changed.

**Comment by Philippe-Arnaud** [comment]
> Or you tell your proxy to not fuck up the files ... the integrity check only fails if the files are being changed.
I wish I could... Fricking Sophos!

I'll remove the integrity hash to check if is fixes the issue.
