### ISSUE TITLE
Time based permissions

### ISSUE THREAD

**Issue by SpoorthiPalakshaiah** [kevinpapst/kimai2#1605]
Can Kimai provide time based permissions for users.
Like we can edit timesheets only for one day from the day timesheet was created.
or something like add timesheets only for the dates in the same week and not previous weeks.

**Comment by kevinpapst** [comment]
This would be a check like the "allow future times" check that is already available. 
Makes totally sense, yes.
No its not existing yet, but a good idea or the future

**Comment by adrianrudnik** [comment]
If this is every considered for implementation, please ensure this works hand in hand with already exported and invoiced items and offers hard rejections for both scenarios, not just a warning. Maybe even an "allow edits until exports/invoicings" may be an option.

**Comment by kevinpapst** [comment]
"allow edits until exports" already exist, it is the role permission `edit_exported_timesheet`.
