### ISSUE TITLE
User-friendly interface to create time-sheets for others

### ISSUE THREAD

**Issue by Philippe-Arnaud** [kevinpapst/kimai2#1606]
**Is your feature request related to a problem? Please describe.**
Creating a time-sheet for myself is quite easy when using the calendar. The drag and drop feature is quick and easy.

Nevertheless, the collaborators of my team cannot create time-sheet by themselves for various reasons. Therefore I have to create their entries by myself and it is tedious :-/

**Describe the solution you'd like**
I'd like to be able to mass-create time-sheets for my collaborators on a daily basis, or using recurring patterns by drag-and-dropping in the calendar and then multi-select the collaborators of my team in a list that belong to the activity I'm assigning them.

**Describe alternatives you've considered**
Using the current form to create time-sheets would be a nice solution if the selection were a multiple choices instead of a drop-down. :+1:

**Comment by kevinpapst** [comment]
Possible since many versions in the admin section via "create for multiple users".
Otherwise there is a plugin to create entries for periods.

If all of this is not sufficient, you can either vote for the "calendar user switching" feature or sponsor this feature.
