### ISSUE TITLE
Export Automation / Shell-Trigger / Cronjobs

### ISSUE THREAD

**Issue by phipz** [kevinpapst/kimai2#1608]
**Is your feature request related to a problem? Please describe.**
In the end of each month, i'd like to export a monthly overview for each employee. So not an invoice, which is always for a customer, but a report about the worked hours of each employee. Those reports (no matter if HTML or PDF), i'd like to save in harddrive or send per mail.

**Describe the solution you'd like**
It would be awesome to trigger the export function from the shell/command-line, so I could set up a cronjob. Or is it already possible to locally fire a php script from the shell, that does that?

**Describe alternatives you've considered**
Alternatively an export could be triggerd via API request or an integrated scheduler.

**Additional context**
Great work!

**Comment by kevinpapst** [comment]
Check #3605

**Comment by kevinpapst** [comment]
Will ship with 1.28.0
