### ISSUE TITLE
kimai:reload breaks file system permissions

### ISSUE THREAD

**Issue by phipz** [kevinpapst/kimai2#1609]
**Describe the bug**

After kimai:reload some file system permissions are wrong. So i need to run manually the following commands, that the system works again.

chmod -R g+rw var/
chmod -R g+rw public/avatars/

**Comment by kevinpapst** [comment]
Thanks for the feedback! 
But thats the nature of re-compiling cache files as different user.
If you run these commands as nginx/httpd/www-data user (or however it is called in your system) everything will be fine.
Thats explained in the documentation. 

If you are using Kimai as single user, you could try to run `rm -rf var/cache/*` and the simply reload the page. With a bit of luck, that will work without any permission trouble ... but it has other downsides, like missing config validation.
