### ISSUE TITLE
Inconsistent behavior when creating and copying a project

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1610]
**Is your feature request related to a problem? Please describe.**
When creating a project, a team of the same name is automatically created.
If I copy an existing project (this could be a project template, for example) and change the project name, no team of the new name will be created.

**Describe the solution you'd like**
The same behavior of the automatic team creation during initial creation and copy provided the project name is then changed.

**Comment by kevinpapst** [comment]
There is no team created automatically. If so: that would be the bug.
There is the `+` button which you refer to I guess.

**Comment by HeinzWuert** [comment]
Right, but this + sign is missing

**Comment by kevinpapst** [comment]
That is only shown if no team is attached to the project.

**Comment by HeinzWuert** [comment]
Would be nice to get it once more when changing project name.

**Comment by kevinpapst** [comment]
I changed the check for the "create button" - now it will always be visible if no team exists with the exact same name like the project/customer

**Comment by HeinzWuert** [comment]
:-) just seen it, good job!
