### ISSUE TITLE
Timesheet view does not list all records

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1614]
Please find the screen shot attached. Currently I have queries and the listing count is set at 50 but even though there are lot of records it just shows few records on screen. If i change the setting manually it shows more records but still does not show the required number of records as determined by the count parameter like 50 100 etc.
![Screenshot_20200405_154447](https://user-images.githubusercontent.com/50443902/78472221-c25c2b80-7754-11ea-80b4-97d8789f72cb.png)

This seems like a bug. I am logged in as a Team lead user. The problem does not occur if i log in as an admin and it displays the correct number of records.

**Comment by kevinpapst** [comment]
I think that was a bug, which is fixed in 1.8.
Please always test in the demo first!

**Comment by rarvin** [comment]
@kevinpapst I am running 1.8 on my system. I have checked the demo page and couldnt find the issue. Not sure why my system is having this issue.

**Comment by kevinpapst** [comment]
Behause it was a bug in 1.8 I guess. 
You can try the "demo-stable" which runs the latest release to check if the behavior changed since then.

**Comment by kevinpapst** [comment]
I believe this was a 1.8 bug. Closing as no feedback came. If that still is available with 1.9 please open a new issues
