### ISSUE TITLE
Duplicate entry in language files leads to wrong translation

### ISSUE THREAD

**Issue by Philippe-Arnaud** [kevinpapst/kimai2#1616]
**Describe the bug**
The user menu gets partly translated because of a duplicate entry in the original language file.

**To Reproduce**
Steps to reproduce the behavior **using a translated instance (i.e.: fr)**
1. Go to any page
2. Click on user avatar
3. See error: MY Profile isn't translated correctly.

** Source of error **

The "My Profile" directive exists at two different places in the `messages.en.xlf` file:

line 63:
```
             <trans-unit id="my.profile">
                <source>my.profile</source>
                <target>My profile</target>
            </trans-unit>
```
`...`
line 99:
```
            <trans-unit id="label.user_profile">
                <source>label.user_profile</source>
                <target>My profile</target>
            </trans-unit>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/767823/78579581-70d59e80-7831-11ea-8c11-7a3863e6bf01.png)

**Additional context**
Kimai 2
1.8 stable (Ayumi) 

**Dirty Patch**
This issue can be roughly patched by duplicating the entry that is missing in the transaltion file and by translating it again:

```
             <trans-unit id="my.profile">
                <source>my.profile</source>
                <target>Mon profil/target>
            </trans-unit>
```
**Fixed screenshot**
![image](https://user-images.githubusercontent.com/767823/78580102-37e9f980-7832-11ea-8f1f-d381355cd74c.png)

**Comment by kevinpapst** [comment]
So, if you complaint is that fr does not translate everything, please create a PR with the updated translation. I do not speak French or anything else besides German and a broken variant of English 😁 and cannot fix it. All translations are user-contributions.

I had a quick search and maybe the key `label.user_profile` is not used anymore. But I cannot guarantee that.

**Comment by Philippe-Arnaud** [comment]
> I had a quick search and maybe the key `label.user_profile` is not used anymore. But I cannot guarantee that.

That's the real question that you highlight here!

Which language should be considered the root reference for the set of keys that must be translated by the other languages in order to be exhaustive?

**Comment by kevinpapst** [comment]
Definitely English. German can be used as well, as I maintain these two packages in parallel, but it won't help most people as they don't understand it^^

I couldn't find any reference for `label.user_profile` but as it is still in `en` it should be considered mandatory until proven otherwise.

**Comment by kevinpapst** [comment]
Missing translations are nothing for the issue tracker.
You can create a PR with the missing translations.
Or you wait for someone else to translate it at some point.
