### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tqax** [kevinpapst/kimai2#1617]
Hi.
Is there anywhere I can download ready to use installation files? I use Windows and Ampps and I do noy have any knowledge in using git or compose.
Thanks for any help.

**Comment by kevinpapst** [comment]
Afaik not.
Kimai is not an app for windows. It is "server software" running with PHP and a webserver.
Follow the installation docs, use docker or ask a friend.
Its the perfect time to learn something new 😁
