### ISSUE TITLE
Installation instructions shared host: add netcup

### ISSUE THREAD

**Issue by spadge4711** [kevinpapst/kimai2#1620]
Maybe this will help others, these steps worked for me (webhosting @netcup):

- use git in the root folder:
git clone -b 1.8 --depth 1 https://github.com/kevinpapst/kimai2.git

- change to new "kimai2" folder:
cd kimai2/

- install composer:
curl -sS https://getcomposer.org/installer | /usr/bin/php

  php composer.phar install --no-dev --optimize-autoloader

- configure your .env file (nano .env)

- install kimai:
php bin/console kimai:install -n

- Reload config:
php bin/console kimai:reload

- optional add an user via console: php bin/console kimai:create-user username admin@example.com ROLE_SUPER_ADMIN

- configure netcup (using the customercontrolpanel) to use "/kimai2" as root folder for the domain or subdomain of your choice and add ssl (letsencrypt) for this domain/subdomain

- place a .htaccess file in the "kimai2" folder to redirect to "kimai2/public":

```
DirectoryIndex index.php

Redirect /index.php https://<your_kimai2_domain>/public/
```

**Comment by kevinpapst** [comment]
Thanks for sharing @spadge4711 !
But it is dangerous to point your domain to kimai2. Always point it to kimai2/public/.
What do you see when you open: https://<your_kimai2_domain>/.env ?

**Comment by kevinpapst** [comment]
Added it to the installation docs, thanks 👍
