### ISSUE TITLE
TAG in permissions: Deny create for users

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1623]
**Is your feature request related to a problem? Please describe.**

If possible, please insert another checkbox "create tags" in the permissions under TAGs.
If unchecked users can then set TAGs, but they cannot create their own.

**Comment by kevinpapst** [comment]
There is a system setting (maybe in 1.9 first, please check the demo): 
<img width="500" alt="Bildschirmfoto 2020-04-07 um 18 19 40" src="https://user-images.githubusercontent.com/533162/78694015-5a484980-78fc-11ea-9cae-1c2e889e0d83.png">

**Comment by HeinzWuert** [comment]
That's it, thanks!
