### ISSUE TITLE
Non-local route

### ISSUE THREAD

**Issue by tobybatch** [kevinpapst/kimai2#1629]
Sorry kevin, I didn't know to submit this question.  I'm working on a plugin to provide a trello power up and I need to serve a single page without locale or security.

How can I do that via a plugin.  I've tried adding my own firewall.yanl in the plugin folder but it doesn't seem to get loaded.

How can I turn off security and locale redirect for a single path, e.g. /trello

**Comment by kevinpapst** [comment]
Unfortunately this is not yet possible (due to limitations ins Symfony):
https://github.com/symfony/symfony/issues/25021

But we could add a base route for plugins like this:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/security.yaml#L57

Something like:
```
    access_control:
        - { path: '^/bundle/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

Try if your plugin would work if that rule would exist. If so: please open a PR and we add it for 1.9.

**Comment by kevinpapst** [comment]
And regarding the locale: thats defined in your routes.yaml
Simply don't define it as requirement. So this is how it should not look like: 
https://github.com/Keleo/DemoBundle/blob/master/Resources/config/routes.yaml#L4

**Comment by tobybatch** [comment]
Thanks Kevin.  I'll do that

**Comment by tobybatch** [comment]
@kevinpapst This seems to work in my bundle plugin

```yaml
security:
    firewalls:
        trello:
            pattern: ^/trello
            security: false
```

I'll work on my plugin and check that's true but if so no need for the PR

**Comment by kevinpapst** [comment]
Ah, never tried to add a new firewall. Good idea!
Will add it to the demo bundle.

**Comment by kevinpapst** [comment]
How and where did you define that?
I get the same exception `You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.` that previously occurred with the new `access_control ` setting
