### ISSUE TITLE
Paging doesn't work

### ISSUE THREAD

**Issue by martinscholz83** [kevinpapst/kimai2#1633]
**Describe the bug**
On Administration/Timesheets paging isn't working. I have entries distributed over 3 pages. When clicking on page 2 or 3 it loads shortly but the page stays at page one. But when doing manually `team/timesheet/page/2` in URL it works. So something wrong with the pager.

**To Reproduce**
3. See error

**Logfile**
There isn't any log file in `var/log/`

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s]
 - OS: macOS
 - Browser: chrome, safari, edge

**Additional context**
 - Kimai 1.8-prod on Docker
 - PHP version

**Comment by kevinpapst** [comment]
Works in demo. Please add more informations, eg. errors in javascript console?

**Comment by martinscholz83** [comment]
Checked already javascript console. No error at all

**Comment by kevinpapst** [comment]
Then try it in the "Latest stable" demo which is running the 1.8 release and check if it happens there as well.
https://www.kimai.org/demo/
https://demo-stable.kimai.org/

**Comment by martinscholz83** [comment]
There it works. I also tested another issue i have in my environment. The search filter doesn't work. For example when select the last month or a special user nothing happens. Something wrong with javascript then?

**Comment by kevinpapst** [comment]
Does any search work? Or does the "preview" on invoice screen show any result?
Sounds like an error that came up several times in the past.
in the past it was always a wrong nginx configuration where GET parameters were ignored.

**Comment by martinscholz83** [comment]
No search at all is working

**Comment by martinscholz83** [comment]
This is the GET command
```
[14/Apr/2020:10:05:11 +0000] "GET /en/team/timesheet/?state=1&exported=1&pageSize=50&page=2&order=DESC&orderBy=begin HTTP/1.1" 200 272939 "http://172.16.86.132:8001/en/team/timesheet/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 Edg/81.0.416.53"
```

**Comment by kevinpapst** [comment]
I already told you the problem:
> a wrong nginx configuration where GET parameters were ignored

**Comment by martinscholz83** [comment]
This is the [nginx.conf](https://github.com/tobybatch/kimai2/blob/master/compose/nginx_site.conf)

**Comment by kevinpapst** [comment]
You want me to validate/fix your nginx config? Really?
What did you try? eg. the config from the documentation?

**Comment by martinscholz83** [comment]
I just wanted to show you that the config is really simple and doesn't look it contains any miss-config. I'm using the docker image from [here](https://github.com/tobybatch/kimai2).

**Comment by martinscholz83** [comment]
Ok, it works now. I forgot to call `docker-compose build` after [that](https://github.com/tobybatch/kimai2/pull/71) fix comes in. Sorry again!

**Comment by kevinpapst** [comment]
Thanks for the feedback, glad that it works now!
