### ISSUE TITLE
Populate project and customer by activity selection

### ISSUE THREAD

**Issue by jojoemade** [kevinpapst/kimai2#1634]
**Is your feature request related to a problem? Please describe.**
When adding a timesheet entry, it's unnecessary to fill out the project and customer when those are always connectedto the activity. If you enter an activity, project and customer should be populated automatically.

**Describe the solution you'd like**
When going to the activity selection, a list of recent activities should be displayed. If none of those is the desired activity, the user can search by name. After a selection, customer and project are populated automatically.

**Describe alternatives you've considered**
Populating manually (although only project seems to be *really* neccessary as customer can be left empty even though it is marked as obligatory).

**Comment by kevinpapst** [comment]
You can use the "recent" activities dropdown to quickly start an entry.

The activity dropdown is only pre-populated with global activities if no project is chosen.
This cannot be easily changed, as that query would be huge and the list of activities can get extremely long. How would you render the complete activity list when you have similar named projects and activities (which is the case for many companies)?
Please provide a full concept for this request, as I don't see how that could be achieved in a manner that fits into larger setups.

Customer has no `*` here, so its not mandatory, it's there to pre-filter the project list.
<img width="268" alt="Bildschirmfoto 2020-04-14 um 12 34 48" src="https://user-images.githubusercontent.com/533162/79215739-56607e00-7e4c-11ea-97f3-05ac0839dfd4.png">

**Comment by jojoemade** [comment]
Didn't know about the recent activities, that's a good feature (I think it would help if buttons which have just an image had tooltips so you know what you're clicking.)

Okay, per my suggestion:
If you click on activity and no project is selected, use the same list of "recent" activities (how long can that list be? I'd suggest a maximum of 7 to 10) as suggestion. If none of the suggestions work for the user, he can enter a string and based on the input the suggestion list is updated from all activities matching the string with also a maximum of ten. This functionality would resemble how the URL bar works in modern browsers:
![image](https://user-images.githubusercontent.com/19491475/79217390-19e25180-7e4f-11ea-8624-bb1380382f1b.png)

**Comment by kevinpapst** [comment]
I am not happy with that, as we are only duplicating features that are already available ... but not that easy to understand (you are not the first person to miss that dropdown at all.) - so maybe its better to improve the UX for it? 

Adjusting the part you are asking for is a massive pain, as the code is already quite complicated (even though it might not look like it, as it is "only" a dropdown).

Adding other options to pre-select project and activity could be added as, eg. "bookmarks" were requested multiple times. 
Maybe dropdown buttons could be added to pre-select recent activities/bookmarks. 
But where? I am not good in UX... maybe in the "edit/create timesheet" floaters title bar?

**Comment by kevinpapst** [comment]
No feedback, closing
