### ISSUE TITLE
Field description from table kimai2_timesheet

### ISSUE THREAD

**Issue by khoebling** [kevinpapst/kimai2#1637]
I want to add the field description from table kimai2_timesheet to my invoice template

What is the name of the variable?

entry.description isnt working

using 1.8 stable (Ayumi)

thank you

**Comment by kevinpapst** [comment]
What do you think how often I heard  in my open-source live?
What do you think: is "isn't working" a good problem description?

Here is the answer, use `${entry.description}`: 
https://www.kimai.org/documentation/invoices.html#template-variables

**Comment by khoebling** [comment]
from default.html.twig
```
<snip>
<tr>
                    <td nowrap class="text-nowrap">{{ entry.begin|date_short }}</td>
                    <td contenteditable="true">
                        {% if entry.description is not empty %}
                            {{ entry.description|nl2br }}
                        {% else %}
                            {% if entry.activity is not null %}{{ entry.activity.name }} / {% endif %}{{ entry.project.name }}
                        {% endif %}
                    <br>
                    <br>
                    {{ entry.description }}
                    </td>
                    <td nowrap class="text-nowrap text-right">{{ rate|money(model.calculator.currency) }}</td>
                    <td nowrap class="text-nowrap text-right">{{ duration }}</td>
                    <td nowrap class="text-nowrap text-right">{{ entry.rate|money(model.calculator.currency) }}</td>
                </tr>
</snip>
```
i am using the variable for testing like this and the value of entry.discription is not the one which is in the table kima2_timesheet. it shows the activity

**Comment by kevinpapst** [comment]
If you use the invoice calculator "grouped by activity" then this is the expected behavior.
If you use "one entry per timesheet" then you get the timesheet description.

**Comment by kevinpapst** [comment]
For reference, this is the invoice calculator line that triggers the behavior:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/ActivityInvoiceCalculator.php#L36
You could easily add a new calculator, that concatenates all timesheet descriptions instead.

**Comment by khoebling** [comment]
thx - that did it

**Comment by khoebling** [comment]
thx - that did it
