### ISSUE TITLE
"To" is not correctly calculated from timesheets view

### ISSUE THREAD

**Issue by jojoemade** [kevinpapst/kimai2#1638]
**Describe the bug**
When adding a new entry from the timesheets view and just filling out the duration, "To" is not calculated but left empty. The entry is then generated as an active timesheet with the duration being ignored.
Creation from "My times" view works fine: Filling out a duration leads to "To" being calculated.

**To Reproduce**
1. Go to 'Timesheets'
2. Click on 'Add'
3. Fill out 'From', 'Duration' and all mandatory fields.
4. Click on 'Save'

**Screenshots**
![image](https://user-images.githubusercontent.com/19491475/79318392-38a41f00-7f07-11ea-8b40-2e50d2ed62ac.png)
![image](https://user-images.githubusercontent.com/19491475/79318485-57a2b100-7f07-11ea-8c7d-270e487400fe.png)

**Comment by kevinpapst** [comment]
This duration field is not used in the backend, but only in javascript.
Can you try to debug why this is not triggered:
https://github.com/kevinpapst/kimai2/blob/master/templates/timesheet/layout-edit.html.twig#L83
Did you maybe immediately click save with the focus still on the duration field?

**Comment by jojoemade** [comment]
Simple:
![image](https://user-images.githubusercontent.com/19491475/79321166-3c39a500-7f0b-11ea-9e53-05c4ca6b4543.png)
![image](https://user-images.githubusercontent.com/19491475/79321202-465ba380-7f0b-11ea-8a02-d3cd0d0f0523.png)

**Comment by kevinpapst** [comment]
I don't understand what you want to say with "simple" and the screenshot

**Comment by jojoemade** [comment]
The fields from the "Timesheets" view have "_admin" in them and there's no function for that. 😄

**Comment by kevinpapst** [comment]
Oh, ups.... yeah, some time ago I refactored these views, so all the logic is reused in the admin view to minimize the codebase. Seems I missed something there.
Should be easy to fix, I'll push a fix later on and invite you for testing

**Comment by jojoemade** [comment]
👍

**Comment by kevinpapst** [comment]
See #1639

**Comment by kevinpapst** [comment]
Thanks for letting me know, I rarely ever use that view myself.
