### ISSUE TITLE
Allow user to log time without project 

### ISSUE THREAD

**Issue by fulljackz** [kevinpapst/kimai2#1643]
**Is your feature request related to a problem? Please describe.**
By default, Project and Activites are mandatory when an user try to log some times. We have many activities and various project that are "dynamics" and that we do not want to be "hardcoded" by an admin.

**Describe the solution you'd like**
It would be great to allow users to log time without specific project by default, and let them to choose one with a dropdown menu for example ?
The same thing for activities would be great, but with a default value which could be the main activity in the team or company.

**Describe alternatives you've considered**
For the moment I have created a default project and activity. But it is not a very good solution because I need to have two actions without value.

**Additional context**
For a quick test, it could be a solution to let the admin if project and activities are mandatory. And so, if this option is disabled the UI would juste be :
- From / To / Duration
- Description
- Tags

**Comment by kevinpapst** [comment]
I don't think that this will implemented any time soon, if ever.
The complete backend relies on timesheets to return project objects.
