### ISSUE TITLE
Set the user.api_token via REST

### ISSUE THREAD

**Issue by paconte** [kevinpapst/kimai2#1647]
Hi, I can not see the possibility of setting the user.api_token. 

My issue is that I cannot create time-sheets for users using only the REST api. I have to login into the web application and set the api_token. My use case would be not to login in the web application so everything is automatized. I have a fingerprint reader that I am connecting to Kimai2.

**Comment by kevinpapst** [comment]
You can't set it via the API. But you could use a webscraping framework to login and set the api token via forms/http requests. Load the login page, fill out and submit. Load the cookie, set it for the next two requests: load the api token url for the users profile, fill out the form and submit it. You need to fill out the forms, to get the CSRF token.

Or you build a custom plugin to add such a API method. 
I might be wrong, but I think its a security risk and therefor will not add it to the core.

**Comment by paconte** [comment]
Thank you for the quick answer! I was wondering why it cant be full automatic. For a first version I prefer a script that writes it in the database directly, it will save time comparing with the scrappy solution. Afterwards I will write the custom plugin which is my favorite solution.

And yes it will more secure without the api-token, however it is possible to set the user password already!

**Comment by kevinpapst** [comment]
Ah, it’s available in the postAction. Ok, we can add the token there as well
