### ISSUE TITLE
API Timesheet GET request begin end parameters are ignored.

### ISSUE THREAD

**Issue by rpelletierrefocus** [kevinpapst/kimai2#1648]
**Describe the bug**
When I run an API Get request using the below parameters, no matter what I put in for begin end gives me all the results for that customer. Not just in between the two dates.
Running the following in jQuery, also tested with the same exact results in POstman

```

var settings = {
				  "url": "https://kimai.domain.com/api/timesheets?user=2&customer=1&begin=2020-04-01T14:00:00&end=2020-04-17T16:49:16",
				  "method": "GET",
				  "timeout": 0,
				  "headers": {
					"X-AUTH-TOKEN": "API_KEY",
					"Content-Type": "application/json",
					"X-AUTH-USER": "API_USER"
				  },
				};

				$.ajax(settings).done(function (response) {
				  console.log(response);
				});
                return false;
```

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: PC
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.163

**Comment by kevinpapst** [comment]
I cannot confirm that.
Try it at the demo: https://www.kimai.org/de/demo.html

**Comment by rpelletierrefocus** [comment]
I can confirm that the demo works perfectly for me. However, my install just does not. I am using the production docker install from @tobybatch . I have updated to the latest but this still does not work. I will open an issue in his project.

**Comment by kevinpapst** [comment]
Are your sure that the other filters (eg. user, customer) work as expected? There was a problem in the past with GET parameters that were not passed to the PHP FPM process.

**Comment by rpelletierrefocus** [comment]
Good call, forest for the trees on my part.  I only have a couple of customers and one user, therefore, I simply had not noticed that none of the filters are actually working. After reading some of the docs, I am suspecting it has something to do with my reverse proxy. I did not have TRUSTED_PROXIES set. However, even after setting that, the parameters still do not work.

I setup a completely new environment using docker and that environment is working properly with the exact same settings. I think I am just going to build on the new install since I am really not losing much. If I find any new information I will update this so folks coming after me will have it, but I will close this for now.

Thank You

**Comment by kevinpapst** [comment]
You didn't mention if you are using nginx. But I have seen that multiple times in the past.
Read this: https://www.kimai.org/documentation/webserver-configuration.html#nginx

The important line is `try_files $uri /index.php$is_args$args;` - if you don't include the `$args`, no GET parameter will be passed to PHP.

**Comment by rpelletierrefocus** [comment]
You solved it!! Although my nginx conf on my local file system had this entry, the nginx conf in the container did not. This is because I failed to rebuild the container after I updated. Thank you Kevin for pointing me in the right direction and being patient with me. You asked all the right questions and I am grateful.
