### ISSUE TITLE
Man sieht nur die 3 neuesten Einträge in der Zeiterfassung

### ISSUE THREAD

**Issue by mufermann** [kevinpapst/kimai2#1651]
Hallo,

wir haben jedem User ein Team mit den Kollegen/innen zugeordnet, deren Zeiten sie sehen dürfen.
Das funktioniert soweit auch, nur werden lediglich die drei letzten Einträge angezeigt. (Beim Export werden alle exportiert)

In der Staging-Umgebung sind die Permissions bei den Timesheets gleich, man kann jedoch alle Einträge der Kollegen sehen.

Haben Sie eine Idee, wo eventuell eine Berechtigung fehlt?

Danke und viele Grüße

**Comment by kevinpapst** [comment]
Das war ein Fehler in der Version 1.8.
Die Version 1.9 kommt diese Woche, bitte nach dem Update nochmal testen.
