### ISSUE TITLE
Failed to assign teams in future projects

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1653]
**Describe the bug**
If you create a project with a start in the future, it is not possible to assign additional users or teams to this project via TEAMS. The future project does not appear in the selection list.

Furthermore, when creating a project under teams, unfortunately no existing teams can be added, only individual users to the automatically generated team name.

**To Reproduce**
1. Create a project with start in the futrure
2. Change to TEAMS
3. Choose any team
3. try to assign the team to the future project

**Comment by HeinzWuert** [comment]
did you change this meanwhile?

**Comment by kevinpapst** [comment]
I don't know if anything changed in between.
But you can assign
-  teams to projects in project detail view
- change the users of a team in the project detail view
- add the future project in team view

So this seems to be fixed
