### ISSUE TITLE
TimeBudget via API

### ISSUE THREAD

**Issue by thelatch** [kevinpapst/kimai2#1657]
I am trying to use an API request (patch) to update TimeBudget for customer projects, as customers can buy and use time quotas. However, I am not allowed to do this. Tried the 
`{"timeBudget": "1000"} ` at the website.com/api/projects/1
command, but I get an 

`""errors"": [ "This form should not contain extra fields."] `
back. 

Am I misplacing my request?

**Comment by kevinpapst** [comment]
Thanks for pointing it out. Never occurred to me that the fields are missing.
Fixed in #1658
