### ISSUE TITLE
When exporting with decimals, sums that are in the thousands don't show correctly.

### ISSUE THREAD

**Issue by steinbitglis** [kevinpapst/kimai2#1659]
**Describe the bug**
When exporting with decimals, sums that are in the thousands don't show correctly.

**To Reproduce**
1. Go to 'Preferences / Use decimal duration in export'
2. Go to  'Export'
3. Create a PDF that should contain thousands of hours.
4. Observe that the hour sum is not displayed correctly.

**Screenshots**
![Screenshot from 2020-04-24 11-23-52](https://user-images.githubusercontent.com/1376725/80196813-25d3cd80-861e-11ea-867e-c6c16dd502f6.png)

**Additional context**
 - Kimai version: Kimai 2 (1.8 stable (Ayumi))
 - PHP version: 7.2.9

**Comment by kevinpapst** [comment]
I have no clue what you mean by "thousands of hours" and "Observe that the hour sum is not displayed correctly"

**Comment by kevinpapst** [comment]
Do you want to elaborate or shall I close the issue?

**Comment by steinbitglis** [comment]
The first line says 

> 1

But the correct number of hours is 1419,42

**Comment by kevinpapst** [comment]
Fixed rate entries use 1 as amount

**Comment by steinbitglis** [comment]
It's not fixed rate.

**Comment by kevinpapst** [comment]
Export the same with HTML please

**Comment by steinbitglis** [comment]
[data.txt](https://github.com/kevinpapst/kimai2/files/4541704/data.txt)

**Comment by kevinpapst** [comment]
Please retest with the latest version. 
I need to be able to reproduce the error. 
If you can create this data in the demo and trigger the wrong export, please let me know how and we can reopen the issue.

**Comment by steinbitglis** [comment]
I can confirm. I have just updated to 1.12 and we're still seeing this issue.

In the demo you can trigger this by

1. logging in a super admin
2. activating decimal duration in export
2. exporting 'John Doe' for the entire 2019+2020 (should be 1500-ish hours)
3. the grand total hours in the PDF will be displayed as '1'.

**Comment by kevinpapst** [comment]
Yep, now I see it as well. That 

> exporting 'John Doe' for the entire 2019+2020 (should be 1500-ish hours)

was the important hint!

**Comment by kevinpapst** [comment]
Found the problem, will be fixed with the next release
