### ISSUE TITLE
Updating to 1.8 can't acces

### ISSUE THREAD

**Issue by yayitazale** [kevinpapst/kimai2#1660]
**Describe the bug**
I launched the command 
`sudo docker-compose pull && sudo docker-compose up -d --build` to upgrade to 1.8 from 1.7
Migration of DB is clean but when kimai starts on log I see this:

```
Using Mysql DB
Wait for db connection ...
Connection established
Kimai2 ready
[Fri Apr 24 15:41:43.924257 2020] [core:warn] [pid 22] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Apr 24 15:41:43.927132 2020] [mpm_prefork:notice] [pid 22] AH00163: Apache/2.4.38 (Debian) PHP/7.3.10 configured -- resuming normal operations
[Fri Apr 24 15:41:43.927165 2020] [core:notice] [pid 22] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

**Screenshots**
This is what I get.
![imagen](https://user-images.githubusercontent.com/6462849/80225326-35b5d680-864b-11ea-8177-e68e2ea61eb8.png)

**Comment by kevinpapst** [comment]
Sorry, I donÄt support docker. Ask in the docker repo.
