### ISSUE TITLE
When entering time record, the "duration" field it pre-filled with 00:00 and has to be deleted before being filled

### ISSUE THREAD

**Issue by Kurgan-** [kevinpapst/kimai2#1667]
When you create a new time record (by pressing on the "+" button on the "my times" screen) the duration field is not empty: it contains the string "00:00". Also, it has focus. If you just type your duration (for example, "1h") the field shows "1h00:00". You have to select all and type over, or press "canc" or "backspace" until it's empty and then enter your duration. 

I expected it to be empty from the beginning, so that when I enter my duration, I don't have to edit the previous content of the field (that is, delete the "00:00" string before typing).

Also, after deleting its value, I see a greyed-out "00:00" that disappears as soon as I type something, so I suppose that the proper behaviour should be that the duration field starts with this greyed "00:00" string shown, and clears itself as soon as I start typing.

I see this issue on Firefox for Linux, but I suppose that it's not browser specific.
Kimai version is 1.8

**Comment by adrianrudnik** [comment]
The `/{_locale}/timesheet/create` route creates a default value of `value="00:00"` instead of just the placeholder value. Not sure if that is intentional.

**Comment by Kurgan-** [comment]
That's the problem. I would have just left the field empty (or with the placeholder value) so that it's easier to enter data.

**Comment by kevinpapst** [comment]
I will have a look into it when I have time

**Comment by Kurgan-** [comment]
Thanks

**Comment by kevinpapst** [comment]
A lot of changes/improvements has been applied to the handling of the duration field, please see #2264

You can test it at https://demo-branch.kimai.org (eg. with `susan_super` and `kitten`).
