### ISSUE TITLE
invoice language of variables in dependence of invoice language settings (not user language)

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1670]
With 1.9, there is a new option "language" when creating/modifying an invoice template. Is it possible that - if set - the invoice variables uses this setting instead of the user language. 

For example, we issue invoices in German and English. When I want to issue an English invoice, I need to switch to English in the main settings so that for instance the ${query.begin_month} is shown with the English term instead of the German term (e.g. May instead of Mai).

**Comment by kevinpapst** [comment]
Damned, so obvious ... but I missed that. Thanks for sharing this finding!
