### ISSUE TITLE
Export / Print: add a "count" column in Summary section

### ISSUE THREAD

**Issue by Kurgan-** [kevinpapst/kimai2#1671]
The "print" function in export is very nice because it's easily customizable (in real time) by simply flagging the needed checkboxes on top of it.

I would like to have another checkbox that allows for a "count" column in the Summary section. 

The count colum should show the number of entries that concur to the total of that row.

For example, if I have 5 entries for customer A project B Activity C, and the total sums up to 10 hours, I'd like to have the Summary section show (or hide) a column that contains the number 5.

``Customer   | Project    | Activity    | Count |  Duration | Rate``
`` Cust. A |Project B | Activity C |     5    | 10:00 h    | €250.00``

Damn, I can't produce a decent table here. Hope it's clear.

**Comment by adrianrudnik** [comment]
Technically quite simple, logically quite tricky. A count column would be an aggregate towards every row and not a summary of a single column. Instead of transporting it as a column, would a final line like "This export / The summary is based on X entries" be enough?

**Comment by Kurgan-** [comment]
I understand that it's not easy because of the logic involved in generating the data needed, but I'd really like to have a row count and not a total (global) count of entries. This is because I actually need to know the count for each row, which is a count of the occurrances of each customer/project/activity.

**Comment by Kurgan-** [comment]
Or, if it's hard to render but not to count, a table at the end should be fine, but it still must contain a count for every row, and not a single total count.

**Comment by kevinpapst** [comment]
I understand that everyone has some special wishes for Kimai, but I have to concentrate my time on functions that are most useful for everyone.

Having such a count column was never asked by someone else, so I am closing this one. 
If anyone ever wants to pay for the development, feel free to comment and I will re-open.
