### ISSUE TITLE
manipulate invoice counter

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1673]
Is there a way to manipulate the invoice counter in a way that it does not start from 1?

Practical application: New user installs Kimai in June; until then, the user has already issued 30 invoices and therefore wants to have the counter start at 31 (or the feature is introduced during the year and in order to use it in the current calendar year, the counter would need to be modified so that it starts with a higher number than 1)

**Comment by plutocrat** [comment]
I'm migrating to Kimai (from the dying Hamster app). My invoice number system is already in the hundreds. I'd like this ability, even if its only in the form {c+234} which would add 234 onto the base number. An invoice_base_number_adjustment=234 in some config file would be even better.

**Comment by plutocrat** [comment]
I also tried manipulating the invoice number in the database but that didn't work, so it seems to get the invoice number you're using count() in the database. Maybe grabbing the last invoice number and adding one might work instead?

**Comment by kevinpapst** [comment]
This method calculates the invoice number:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php#L57

**Comment by kevinpapst** [comment]
Will be available in 1.10, see #1836
