### ISSUE TITLE
activity without project

### ISSUE THREAD

**Issue by JosBergm** [kevinpapst/kimai2#1675]
I'm new to Kimai and have a problem with the workflow.
I've defined a global activitiy "hotline support" (not related to a customer or project) and when I want to add a new timesheet record with the activity "hotline support" the project field is always mandatory (customer is selected).
<img width="1019" alt="Bildschirmfoto 2020-04-30 um 12 00 21" src="https://user-images.githubusercontent.com/64585125/80698717-2a472d00-8adb-11ea-8928-ee24378f93c8.png">
Isn't it possible to add an activity without a project (not every activity can be assigned to a project)?
(Kimai2 1.9 installed on Debian 10 with PHP 7.3 FPM/FastCGI)
Thank you!

**Comment by kevinpapst** [comment]
Project is mandatory by now. 
That might be changed at some point in the future, but until then you have to create a "default" project for each customer.
