### ISSUE TITLE
dont think first user setup with ROLE_SUPER_ADMIN

### ISSUE THREAD

**Issue by funkytwig** [kevinpapst/kimai2#1677]
Hi, seems the support forum has been closed and all references to support point to GitHub so the only thing I can think of is raising this as a Bug.  Not sure what else to do.

I installed Kimai2 and in docs, it said the first user would be set to  ROLE_SUPER_ADMIN but when I try to use this user there seems to be no way of creating a project so it seems it has not been set to ROLE_SUPER_ADMIN.  I am using v1.6 stable.

**Comment by kevinpapst** [comment]
I don't support older versions. But I am pretty sure that it works. This feature is very simple and hasn't been changed since day one:
https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/RegistrationSubscriber.php#L46

> there seems to be no way of creating a project

Can you explain in detail?

**Comment by funkytwig** [comment]
OK, I'm not deliberately using an older version and its a new install so using latest prod seems sensible.  I'm using docker-compose from https://github.com/tobybatch/kimai2/blob/master/docker-compose.yml (Kimai2 v1.5).  Thought this was the official one.  Looking at https://hub.docker.com/r/kimai/kimai2 it uses a later version (Kimai2 v1.8) Is this where it is best to get compose file from.

**Comment by kevinpapst** [comment]
I don't support Docker myself, you find all links in the documentation.
AFAIK tobybatch is the most active repo and its the only one I watch myself.
But that isn't the real topic, was it? 😁 Can you answer my question, please.

**Comment by funkytwig** [comment]
Sorry, was trying to get to a version you supported, can't find any details of what versions there are.  

When I try to start tracking (press the play button) I get a pop up (Create) that gives me 2 dropdowns, project and activity.  Both of these are empty and if I type into them I get 'no results found'.  Therefore I thought somehow I needed to create a project.  The reason I thought I was not an Admin is I don't have Administration in the left panel.

**Comment by kevinpapst** [comment]
Yes, you need to create customer / project / activity before you can start time-tracking:
https://www.kimai.org/documentation/inital-setup.html

You do that at:
Menu => Customer
Menu => Project
Menu => Activity

**Comment by funkytwig** [comment]
OK, What do you mean by Menu, my screen looks like this - https://cloud.prsc.org.uk/owncloud/index.php/s/WGMMGwBfC2waipI.  I've clicked on everything and can't find Customer, Projects or Activity anywhere.  A;so I have no Administrator link in the left panel.  Going back to the start of this thread is I think the problem is I am not a Administrator.

**Comment by kevinpapst** [comment]
Yes, looks like it.
How did you create the user? Command line or web registration form?
If first, then you forgot to add the ROLE_SUPER_ADMIN flag.
You can still use `bin/console for:user:promote` to add that role via command line (inside the Kimai directory in your docker).

**Comment by funkytwig** [comment]
OK, will reinstall and try again, thanks.

**Comment by kevinpapst** [comment]
No need for reinstallation, use the command to add the role

**Comment by funkytwig** [comment]
That's OK, want to go to 1.8 anyway and not actually done anything.  I'm using docker-compose so it's easy.  However, for future reference, where are the docs for the commands. Spent a while looking around the documentation and could not find it.  Sorry to be a pain;-).

**Comment by kevinpapst** [comment]
`bin/console` will show you all commands with short information and more details if you use the `--help` flag, eg. `bin/console for:user:promote --help` 

If you want to contribute to the documentation, I could use some help there 😁

**Comment by funkytwig** [comment]
That's a distinct possibility.  Are they on github?

**Comment by kevinpapst** [comment]
Yep: https://github.com/kimai/www.kimai.org/tree/master/_documentation

**Comment by kevinpapst** [comment]
Retried registration, works for me: first user becomes SUPER_ADMIN

closing
