### ISSUE TITLE
Limited Filter invoice data in version 1.9 compared to version 1.8

### ISSUE THREAD

**Issue by brievenbusalex** [kevinpapst/kimai2#1679]
Hi, In version 1.9 the Filter invoice data function seems to have limited options compared to version 1.8 (see attached image).
 
Filtering invoice data on project / activity / user / tags is really handy or even needed. Can or will this be added again ?

Thanks in advance for your reponse.

![kimia_filter_invoice_data](https://user-images.githubusercontent.com/10253686/80794766-0b0fd480-8b9b-11ea-9e5e-f7d8fd82b3fc.png)

**Comment by kevinpapst** [comment]
What else is different in these images, besides the form?

**Comment by brievenbusalex** [comment]
According to me, in version 1.9 it's not possible to filter timesheets on activity level or for example all timesheets on a project for a specific user or specific tag(s).

For example we want a different invoice for user A and user B who are working on the same project/activity.

This was possible in version 1.8 and was very handy and used in our project.

**Comment by kevinpapst** [comment]
You want my feedback and then totally ignore my question.

> What else is different in these images, besides the form?

Look at the icons

**Comment by brievenbusalex** [comment]
I looked through the icons, I see the new list of archived invoices, and icon for managing the invoice number format. 

I don't see more filtering options for activity or user or tags ? Or am I blind :-) ?

**Comment by kevinpapst** [comment]
You are 😁 

<img width="916" alt="Bildschirmfoto 2020-05-01 um 12 03 34" src="https://user-images.githubusercontent.com/533162/80798083-cc324c80-8ba3-11ea-84de-77247b4df8c6.png">

Now look again, do you see the checkbox?

**Comment by brievenbusalex** [comment]
Wow...amazing, I am blind! Thanks, a great little hidden feature 👍

**Comment by kevinpapst** [comment]
Maybe the concept needs to be changed, something like a simple link that shows the full search form... I need to think about it. Lets see how many users have the same question.
