### ISSUE TITLE
Custom hourly rates per activity

### ISSUE THREAD

**Issue by adriansuter** [kevinpapst/kimai2#1680]
In our company, activities like "meetings" would not be factured with the same hourly rate as activities like "development". Is that possible to achieve in Kimai2?

If not I would suggest to introduce some sort of scale factor per activity. By default the scale factor is 1, which means no scaling at all. But if you set the scale factor for the activity to 0.8 for example, then the hourly rate (as shown by default in the timesheet upon creation) would be calculated by scaling the hourly rate of the user by 0.8.

This could even be more sophisticated to allow scale factors to projects and to clients.

### Example
Client A has a scale factor of 0.5 (this is a premium client which has good conditions).
Project 1 of client A has a scale factor of 1.0.
Activity "Meeting" has a scale factor of 0.8.

Say the hourly rate of a user is $100. Then the calculated hourly rate in the timesheet would be
`$100 * 0.8 * 1.0 * 0.5 = $40`.

### Note
The idea above is similar to the [Rate multiplier for specific weekdays](https://www.kimai.org/documentation/timesheet.html#rate-multiplier-for-specific-weekdays).

**Comment by kevinpapst** [comment]
> In our company, activities like "meetings" would not be factured with the same hourly rate as activities like "development". Is that possible to achieve in Kimai2?

Yes, you can set activity specific rates: 
https://www.kimai.org/documentation/timesheet.html#rate-calculation

If you have concrete questions AFTER testing, you can open a new issue
