### ISSUE TITLE
Reload after CSV plugin installation fails due to missing RegistryInterface

### ISSUE THREAD

**Issue by herrschmidt** [kevinpapst/kimai2#1681]
Hi,
I just installed the CSV import plugin that is mentioned in the docs with:
`git clone https://github.com/neontribe/KimaiCvsImportBundle.git var/plugins/NeontribeCvsImportBundle`

When I reload the configs the following error pops up:

```
[ERROR] Cannot autowire service "KimaiPlugin\NeontribeCvsImportBundle\Command\NeontribeCvsImportCommand":
         argument "$registry" of method "__construct()" references interface
         "Symfony\Bridge\Doctrine\RegistryInterface" but no such service exists. Try changing the
         type-hint to "Doctrine\Persistence\ManagerRegistry" instead.

```

Is this a bug? What can I do about the error? Is this an error in the CSV plugin or do I have to change a variable in my kimai 2 installation? I am not sure what changing the type-hint means.

**Comment by kevinpapst** [comment]
This repo is for Kimai 2. You need to ask in the original plugin repo.

**Comment by herrschmidt** [comment]
Sorry, wasn't sure if this was something on the plugin side or on the kimai side.

**Comment by kevinpapst** [comment]
BTW: Kimai cam import several things out of the box: https://www.kimai.org/documentation/imports.html
