### ISSUE TITLE
Export button in timesheet and my times defaults to current month

### ISSUE THREAD

**Issue by herrschmidt** [kevinpapst/kimai2#1682]
**Describe the bug**
Does not matter wether I select entries in the timesheet or not, the csv, pdf, print and excel export only exports entries of the current month. Shouldn't it export all visible filtered entries? Or all selected entries, if some are selected?

**To Reproduce**
1. Go to 'timesheet' or 'my times'
2. Click on 'download/export' button on the top right and select 'print' for example
3. See that only entries of the current month get exported.

**Logfile**
There is no error shown in the logfile

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Desktop PC
 - OS: Windows 10
 - Browser chrome
 - Version 81.0.4044.129 (Offizieller Build) (64-Bit)

**Additional context**
 - Kimai version
 - PHP version: 7.3

**Comment by kevinpapst** [comment]
It exports the filtered timesheets. 
If you did not select a time range in the search, then the current month is exported.
The checkbox is only relevant for the batch update (form below the table).

**Comment by kevinpapst** [comment]
Sorry that I simply close your issues, but that was discussed often in the past. Use the search to find these discussions.
Maybe not an obvious behavior, but otherwise Kimai would by default export all existing timesheets, which is definitely not what you want.

**Comment by herrschmidt** [comment]
No worries, sorry that I didn't find the relevant posts. Now that I know how to do it, it works great. Thank you! It is a little unintuitive though :). Is this in the documentation? If not, it would be nice to add it. Often small things take a long time to figure out..
