### ISSUE TITLE
Confusing project selection in Invoices

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1685]
**Describe the bug**
All projects are shown under Invoices (Invoices FZ), regardless of whether they are considered as invoiced (marked as exported) months ago or not. 
This is all the more confusing when it comes to extended projects of the same name. It's not clear which one ist the right one. Choosing the wrong (old) project results in not working Kimai variables like project name or project customer in Excel.

**Comment by kevinpapst** [comment]
Email please
