### ISSUE TITLE
Rates in Projects and Activities gone?

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#1686]
**Describe the bug**
Is it just me or **should there be entries for rates in Project/Activities, but are not?**
Did I miss a concept change? Default priorities (which overrules which) are still in the docs.

**To Reproduce**
1. login at v1.9 https://demo-plugins.kimai.org/ with Administrator
2. Edit Project
3. Don't see rates
4. via API neither

![Bildschirmfoto 2020-05-04 um 22 25 27](https://user-images.githubusercontent.com/18475375/81010428-9668be80-8e56-11ea-9dce-4c727380bfff.png)

**Comment by kevinpapst** [comment]
Yes, you missed the changes in 1.9. 
Go to the details page (instead of the edit form), there is a new "Fees" box that holds all rate configurations (which can now be user specific and have an optional internal rate as well).
That applies for customer/projects and activities. 
Keep on posting if you still have questions.
The update will take care of migrating the current settings.

**Comment by labor4** [comment]
Halleluja!

**Comment by kevinpapst** [comment]
Is that a "good", "bad" or "OOOO - I never saw the details page" 😁  ?

**Comment by labor4** [comment]
haha, it's beautiful that nothing's broken!
I was already asking myself how far back...

No it's clear now.
But I made a query by API:
`{{baseUrl}}/api/projects?customer=17`
... and I'm pretty sure there was something rate'ish in the answer...

**Comment by labor4** [comment]
I bet you'll come up with an elaborate trick via permissions ;-)

**Comment by kevinpapst** [comment]
Hm, I just saw that I forgot to mention this BC break in the UPGRADING.md....
This change was impossible to handle in the API, therefor the fields were removed.

There are new /rates methods for each entity type, see https://demo.kimai.org/api/doc
<img width="1423" alt="Bildschirmfoto 2020-05-04 um 23 06 37" src="https://user-images.githubusercontent.com/533162/81013711-ea29d680-8e5b-11ea-93a4-6ab1bc679a54.png">

**Comment by labor4** [comment]
thanks for clearing up.
no problem, I'll go have a look.
good evening!
