### ISSUE TITLE
Installation instructions for NetCup do not work

### ISSUE THREAD

**Issue by lukibahr** [kevinpapst/kimai2#1688]
**Describe the bug**

Following the installation instructions from https://www.kimai.org/documentation/installation.html#netcup leads to an unexpected Error500 in the browser. No logs are written into the var/ directory. 

**To Reproduce**

Follow the installation instructions on: https://www.kimai.org/documentation/installation.html#netcup. 

**Logfile**
```
none
```

**Additional context**
 - latest
 - 7.2

I've set up a shared hosting on NetCup and tried the installation with git and via FTP. The sqlite database seems to be initialized, however there are no log files written or any other activity is going on after visiting the website, despite an Error 500. 

Are there any further instructions on how to set up the app on a NetCup hosting? Installation instructions via git (composer and other stuff) worked and threw no errors.

All I get is the following error 500 in the browser window. The webserver logs do not give further information about the error or any error message.

![2020-05-07 08_42_00-Window](https://user-images.githubusercontent.com/17235051/81262891-eefab000-903e-11ea-85d8-4b782b6dc648.png)

**Comment by lukibahr** [comment]
![image](https://user-images.githubusercontent.com/17235051/81318925-40cb2680-908f-11ea-8c22-e9e57c97b9e7.png)

Debug mode lead to the same problem. Database connections are okay, but every call on the index page results in an Error500.

**Comment by kevinpapst** [comment]
Check if there is a log in var/log/prod.log.
I bet that its the file permissions. Please check the docs. Some directories need write permissions.

**Comment by lukibahr** [comment]
I've checked the file permissions:

![image](https://user-images.githubusercontent.com/17235051/81319532-19c12480-9090-11ea-97cc-0816ba8ce71a.png)

and created a testfile in var/log. Set 0777 permissions.

**Comment by lukibahr** [comment]
I've checked the permissions, and even set to 0777. Creating a testfile in var/log/ worked either. 

![image](https://user-images.githubusercontent.com/17235051/81319679-4aa15980-9090-11ea-8d27-94c3cd98d040.png)

**Comment by kevinpapst** [comment]
The webserver needs to write into the directory, not your bash user. But 777 sounds open enough...
Did you read https://github.com/kevinpapst/kimai2/issues/1620 ?

Why are you using SQLite and why is there no environment mentioned in the first screenshot? 
Did you configure your .env file?

**Comment by lukibahr** [comment]
I'll check the issue you_ve mentioned. I don't think i'ts failing due to the permissions.

Yes, I've configured the env file properly. The screenshot was a second run, running under dev environment, to ensure it's not a database issue

**Comment by lukibahr** [comment]
okay, the issue you've mentioned seems working, however, the .env file is downloadable now. (as also mentioned in the issue #1620 ). Do you know a way to solve this?

**Comment by kevinpapst** [comment]
Point your domain to kimai/public/ NOT to kimai/

**Comment by kevinpapst** [comment]
No feedback?

**Comment by lukibahr** [comment]
sorry closed the issue without feedback. the #1620 solved it.
