### ISSUE TITLE
'Merge' SAML users based on mail attribute

### ISSUE THREAD

**Issue by Jelle-S** [kevinpapst/kimai2#1690]
**Is your feature request related to a problem? Please describe.**
When using SAML authentication with an existing internal kimai user: 
If the user's email address match, but the username doesn't you get an SQL error:
```
[2020-05-08 10:47:15] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed creating or hydrating user "myuser" [...] 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'myuser@example.com' for key 'UNIQ_B9AC5BCEA0D96FBF'
```

**Describe the solution you'd like**
Add an extra check to load the user by mail to see if it already exists.

**Describe alternatives you've considered**
Possibly set the email as username in the SAML ticket? But I guess that wouldn't help if the internal username is not the email address?

**Additional context**
N/A

**Comment by kevinpapst** [comment]
The users could still not be merged if I check if one exists by email.
Yes, sure - it would prevent the SQL exception but would raise a custom exception.
Not sure what a good way to proceed is. 
SAML is used by several companies, changing the way the username is calculated is definitely not a solution.

**Comment by kevinpapst** [comment]
Is this still a thing @Jelle-S ? I'm not able to reproduce the problem.
Please share some more information, otherwise I have to close this issue. 
No one posted info for one year, so my current guess would be a misconfiguration instead of a bug,

**Comment by Jelle-S** [comment]
I haven't tested any further, we ended up creating all users through the API, so that we were sure the usernames matched, so I can't confirm nor deny if it is still an issue.

**Comment by kevinpapst** [comment]
Thanks, I am going to close it then. Can be reopened any time if the problem still exists.
I tried but couldn't reproduce it.
