### ISSUE TITLE
Multi-tenant ?

### ISSUE THREAD

**Issue by caprehab** [kevinpapst/kimai2#1691]
I was wondering if multitenant is possible? And if teamlead can create customers and projects?
If not, is it then easy to create this or to change it with the permissions settings?

Will there be a quotation feature in the future?

**Comment by kevinpapst** [comment]
> I was wondering if multitenant is possible? 

Not native. Use Docker for that.

> And if teamlead can create customers and projects?
> If not, is it then easy to create this or to change it with the permissions settings?

Yes, thats possible.
> Will there be a quotation feature in the future?

What is that?

**Comment by caprehab** [comment]
> > I was wondering if multitenant is possible?
> 
> Not native. Use Docker for that.
> 
> > And if teamlead can create customers and projects?
> > If not, is it then easy to create this or to change it with the permissions settings?
> 
> Yes, thats possible.
Oké, so it's possible for a team lead to create customers and projects. 
> 
> > Will there be a quotation feature in the future?
> 
> What is that?
A offer/ price offer

**Comment by kevinpapst** [comment]
Thanks for your questions!

Regarding:

> quotation feature

I have no plans for that
