### ISSUE TITLE
Invoice generator - Entry counter

### ISSUE THREAD

**Issue by Fanvaron** [kevinpapst/kimai2#1692]
Hello,
I created a template for generating invoices in word. My old (manual) template has a counter (position) as the first entry in every row, which does not seem to be supported right now.

I would really just need a simple counter for each duplication of my row, kinda like it automatically does when putting a wrong variable or an empty ${} at the moment, but just as a simple int.
Optionally with leading zeros.

Sincerely
Fanvaron

**Comment by kevinpapst** [comment]
https://www.techrepublic.com/blog/microsoft-office/how-to-number-rows-in-a-word-table/
???

**Comment by Fanvaron** [comment]
omg, yeah I'm not used to using word, so I didn't even consider that I could use an inbuild function like that instead of the template. thx
