### ISSUE TITLE
Unable to scroll to the right in users screen

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1696]
I have added a number of user preferences and as a result of this the number of columns that I would like to view in the users screen has increased. Even so the view is constant and no scroll bar appears allowing for scrolling and viewing the newly added columns and their values. Please help by allowing  scrolling to the right.

**Comment by kevinpapst** [comment]
I don't get it. Please add a screenshot.
You could try the Custom CSS Bundle with the "responsive table" rule.

**Comment by rarvin** [comment]
![Screenshot_20200511_184531](https://user-images.githubusercontent.com/50443902/81565911-ba2c8700-93b7-11ea-93e1-6238c9e79413.png)
@kevinpapst

**Comment by kevinpapst** [comment]
Ah, the looks crappy. Get a bigger screen 😁 no just kidding!
Do you need all of them to be visible in the list?

This should be fixed when you use:
> ... the Custom CSS Bundle with the "responsive table" rule.

**Comment by rarvin** [comment]
@kevinpapst I dont need all of them to be visible all the time, but currently there is no other option other than this where I can try and extract the data from the view. If its from export then users have to create some records and the user preferences do appear but it depends on what activities the users chooses, there is no fail proof method to know user has updated the records and can be extracted. For now i am enabling the visible option and then I would copy the whole user view manually and then i would update an excel sheet. Is there any way an export option can be provided in the user view itself.

Also can user preferences be made visible in the users view for some fields and some in the export views etc. Right now they are enabled globally when view is enabled

I enabled the responsive option in CSS it did not work

**Comment by kevinpapst** [comment]
I just tried the CSS rule, works for me in the timesheet views.
The rule does not by default enable responsiveness on all tables but only for the timesheet views.
If you want it for all views, you can use:
```
.box .dataTables_wrapper {
    overflow-x: auto;
    min-height: .01%;
}
box .dataTables_wrapper > .row {
    margin-left: 0;
    margin-right: 0;
}
box .dataTables_wrapper > .row > .col-sm-12 {
    padding-left: 0;
    padding-right: 0;
}
```

**Comment by kevinpapst** [comment]
> Is there any way an export option can be provided in the user view itself.

Sure, at some point yes. Open a new feature request please.

**Comment by rarvin** [comment]
@kevinpapst Thanks Kevin the CSS workaround works well.

**Comment by kevinpapst** [comment]
I added that general rule for scrolling on all tables to the plugin and the user export has a new issue, so I am closing here.
