### ISSUE TITLE
Separate userprerference custom fields from standard system level user preferences

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1697]
I have added a number of user preferences and all of the appear as needed. But it would be great if there is some kind of separation between the system level user preference fields and the custom user preference fields. Also allowing for category level split by custom user preference depending on categories which could help the user understand what user preference fields are associated with what category would be a good feature.

The use case is that at times for getting certain inputs from the users we would need to enable certain user preferences fields and during this period it becomes difficult for the user to understand which are the new ones that the user would need to enter. Have a category level split by the user preferences would be good as it help the user find them easily from the lot and also help with view-ability.

**Comment by kevinpapst** [comment]
Yes, some kind of title for a group of preferences is needed. Some like setting a custom order.
There is already request for it in the MetaFields bundle, you could vote for that as well.

**Comment by kevinpapst** [comment]
This is available since 1.10 I guess. 

And they can be configured via the MetaFields bundle as well.

Closing here, as all points are implemented.
