### ISSUE TITLE
Custom logo on exported PDF's

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#1698]
Hi,

ons the export feature, is there a way to inset a custom logo into the PDF's that are exported?

thank you

**Comment by kevinpapst** [comment]
No.

But you can build your own export template:
https://www.kimai.org/documentation/export.html#adding-export-templates

Copy & paste [this file](https://github.com/kevinpapst/kimai2/blob/master/templates/export/pdf-layout.html.twig) and adapt it to your needs
