### ISSUE TITLE
API for getting time sheet records updated after certain timestamp

### ISSUE THREAD

**Issue by lekhnath** [kevinpapst/kimai2#1699]
**Is your feature request related to a problem? Please describe.**
API to get all records that are updated after some timestamp.

**Describe the solution you'd like**
I am implementing a feature in my web application that synchronize our timesheets with KIMAI timesheets. For that I need to get all records created and updated after some timestamp. I could get all the records `CREATED` after certain timestamp using following API but could not get updated records.

`/api/timesheets/?begin=2020-05-12T04:00:00`

Is there any way to get all `UPDATED` timesheet records after some datetime?

**Comment by kevinpapst** [comment]
Hi @lekhnath!
Kimai doesn't store the info when or by whom a record was updated.
There is the Audit Log plugin, which does it, but this one has no API method yet. As nobody ever asked before, I'll keep this as feature request for now and we see, if it can get more votes.

**Comment by kevinpapst** [comment]
Will be available with 1.10 - new `modified_at` field (only available internally, but can be used to filter timesheet collection) was added in #1818
