### ISSUE TITLE
Time selector should match time rounding

### ISSUE THREAD

**Issue by heeen** [kevinpapst/kimai2#1701]
**Is your feature request related to a problem? Please describe.**
Time selector is always minute granularity, even when you configure times should be rounded to e.g. 15 minutes

**Describe the solution you'd like**
Time selector should offer :00, :15, :30, :45 according to rounding configuration

**Describe alternatives you've considered**
make start and end time text fields or a group of buttons

**Additional context**
the minute scroll box is too long and is annoying to get to 45 minutes

**Comment by alqu** [comment]
Sounds like a good plan. Also, There is a setting for this in the datepicker-component: "timePickerIncrement". See http://www.daterangepicker.com/#options

**Comment by kevinpapst** [comment]
Oh, didn't know that. Good finding @alqu !

But I don't think that start and end rounding should be used to configure that.
For example my own case: I am rounding duration only and use "start" and "stop" button whenever possible.
But in case I have to enter a time manually, I'd like to use 5 or 10 minute steps.

So probably its better to add a new config for that.

**Comment by alqu** [comment]
Yes, It would totally be OK to either set the time increments via Select box "every 15 minutes, every 10 Minutes, ..." or via Number field like "display increments for every x minutes".

**Comment by kevinpapst** [comment]
A lot of changes/improvements has been applied to the handling of the duration field, please see #2264

You can test it at https://demo-branch.kimai.org (eg. with `susan_super` and `kitten`).

All 3 fields (start, end, duration) have now a dropdown that uses the rounding rules.

**Comment by alqu** [comment]
Looks good to me!

**Comment by kevinpapst** [comment]
Master includes also config settings, which allow to explicit define the increment steps (by default running rules are used, but that can be changed)
