### ISSUE TITLE
calendar data should be configured

### ISSUE THREAD

**Issue by heeen** [kevinpapst/kimai2#1703]
**Is your feature request related to a problem? Please describe.**
neither me nor my customer care when I worked, but I care about the hours I have worked on which day. Calendar should be able to be configured what values to display

**Describe the solution you'd like**
similar to timesheet view, select columns should include:
duration of tasks
rate
maybe also:
sum of rates (income per day)
sum of all tasks (hours worked per day)
depending on view, maybe also hours per week, income per week, month etc

**Describe alternatives you've considered**

**Additional context**

**Comment by kevinpapst** [comment]
Can you please re-write this feature request and explain which view is missing what info.

**Comment by kevinpapst** [comment]
I am closing this issue now due to missing feedback.

If you want to share more input / test results from the [demo installation](https://www.kimai.org/demo/), please feel free to comment and re-open.
