### ISSUE TITLE
Dashboard time interval could be configured

### ISSUE THREAD

**Issue by heeen** [kevinpapst/kimai2#1704]
**Is your feature request related to a problem? Please describe.**
User should be able to set dashboard interval to months, two weeks etc

**Describe the solution you'd like**
Depending on your billing cycle you might be interested on your progress for the current month, last month etc.
two week payday cycles are common in the US, monthly in europe.

**Describe alternatives you've considered**
It relates to my issue about the calendar data being more flexible, so maybe it could be combined into a single view that shows the calendar with a dashboard about the shown date range below.

**Additional context**

**Comment by kevinpapst** [comment]
Being able to configure single dashboard widgets will likely come in the future.
The next major #2902 allows to configure which widgets will be shown to each single user.

But this feature request is far too broad to work on it. Closing.
