### ISSUE TITLE
Allow export option for Users view

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1706]
The size of the view for "users" being fixed prevents the user from scrolling and seeing all of the additionally added fields. 
To help see them Kevin has provided a workaround
The workaround works properly. Please see #1696 

But what would be great is an option to export the entries in the users view directly using the export function or something similar.

**Comment by buoncri** [comment]
I use to give "create_export" permission to users, so they can do own reports using exports.

**Comment by kevinpapst** [comment]
@rarvin can now be tested at https://demo-branch.kimai.org/ - more infos at via #1831

**Comment by rarvin** [comment]
Tested and works well. Thank you for your help.
-- 
Regards,
Aravind
