### ISSUE TITLE
Missing rates in projects, customers and activities

### ISSUE THREAD

**Issue by BKapelari** [kevinpapst/kimai2#1707]
**Describe the bug**
I don't know if it is since an update or a setting but I can't find the rates anymore. Only on the profile settings is still the input to set them.
**Screenshots**
I've added screenshots to help explain my problem.

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s]

**Additional context**
 - 1.8
 - PHP 7.3.17

![Bildschirmfoto 2020-05-14 um 12 07 57](https://user-images.githubusercontent.com/4718590/81922163-02c48a00-95dc-11ea-85cb-36d10e862d8c.png)
![Bildschirmfoto 2020-05-14 um 12 08 06](https://user-images.githubusercontent.com/4718590/81922167-03f5b700-95dc-11ea-81c9-57a51efab00f.png)
![Bildschirmfoto 2020-05-14 um 12 08 14](https://user-images.githubusercontent.com/4718590/81922172-0526e400-95dc-11ea-8112-176794f44bc6.png)

**Comment by kevinpapst** [comment]
Instead of putting so much effort into writing the issue, you should have tried to find existing topics instead: e.g #1686 😁

**Comment by BKapelari** [comment]
Sorry, didnt find one... my fault!

**Comment by kevinpapst** [comment]
So you found the new "Fees" section own the detail page?

**Comment by BKapelari** [comment]
YESSSS! But: If I have a fee defined on the activity and the customer, why does it calculate with de activity-fee now? Formerly it did calc with the customer specific fee. Or am I wrong?

**Comment by kevinpapst** [comment]
It bubbles up: timesheet -> activity -> project -> customer -> user 
The first one found is used and it was always working this way.
The logic didn't change, activity fee always wins over customer fee.

**Comment by kevinpapst** [comment]
Explained here: https://www.kimai.org/documentation/timesheet.html#rate-calculation

**Comment by BKapelari** [comment]
Okay, then our installation had a bug for over 6 months :-)
So if one of our customers has a custom fee for an activity, we have to duplicate the activity for the specific customer?

**Comment by kevinpapst** [comment]
I am 100% certain that it worked like that since day one. If you can prove that it worked different before (download an older version, lets say back to 1.3) you get a plugin for free!
