### ISSUE TITLE
Kimai APP for iphone API Failure on high project volumes

### ISSUE THREAD

**Issue by lumovan** [kevinpapst/kimai2#1709]
Hi,

we use the iphone APP for sync with kimai, we have import all our customers and projects to the app, but now i cant`t sync with the app anytime. Failure: Unkown API Failure . Please check your internet connection.... . Can someone help. THX

**Comment by kevinpapst** [comment]
If there is nothing in Doctor > Logs (in Kimai itself) then @hmr-it-jr might be able to help.

**Comment by hmr-it-jr** [comment]
@lumovan 

please check these points:

- self-signed ssl won't work
- internet connection to server is working
- post requests for api are working
- your api answers requests with valid json

If you've check the above points and you think everything on your side is correct please test it with demo login details and tell me if they work for you:

url: https://demo.kimai.org
user: susan_super
api-password: api_kitten

**Comment by kevinpapst** [comment]
No feedback, closing
