### ISSUE TITLE
column visibility settings stored in the database instead in a browser cookie

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1710]
The column visibility can be changed for the timesheet view through the eye symbol. Unfortunately, the settings are stored in a browser cookie. 

Since browser cookies are deleted with the closing of the browser (at least if you follow current security recommendations) it is very annoying to daily fix the timesheet view. 

Would it be possible to store the settings in the database instead?

**Comment by kevinpapst** [comment]
Duplicates #1230
