### ISSUE TITLE
Kimai2 sqlite-database issue  "Integrity constraint violation: 19 FOREIGN KEY constraint failed"

### ISSUE THREAD

**Issue by jsielemann** [kevinpapst/kimai2#1712]
**Describe the bug**
Hello Kevin!
The last action I did was to delete a Customer and it's projects.
After that I got a HTTP500 Error and "Etwas läuft falsch Ein kritischer Fehler ist aufgetreten. Möglicherweise haben Sie einen Software Fehler gefunden, kontaktieren Sie bitte ihren Administrator wenn der Fehler bestehen bleibt."

**To Reproduce**
Unsure...maybe try do delete some customers ;)

**Logfile**
[2020-05-17 13:52:38] request.INFO: Matched route "timesheet". {"route":"timesheet","route_parameters":{"_route":"timesheet","page":1,"_controller":"App\\Controller\\TimesheetController::indexAction","_locale":"de"},"request_uri":"https://timelog.jsiit.info/de/timesheet/","method":"GET"} []
[2020-05-17 13:52:38] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-05-17 13:52:38] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\ChainUserProvider","username":"jsi"} []
[2020-05-17 13:52:38] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2020-05-17 13:52:38] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-05-17 13:52:38] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-05-17 13:52:38] php.CRITICAL: Uncaught Error: Call to a member function getId() on null {"exception":"[object] (Error(code: 0): Call to a member function getId() on null at /s/www/kimai2/src/Repository/Loader/TimesheetIdLoader.php:58)"} []
[2020-05-17 13:52:38] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getId() on null" at /s/www/kimai2/src/Repository/Loader/TimesheetIdLoader.php line 58 {"exception":"[object] (Error(code: 0): Call to a member function getId() on null at /s/www/kimai2/src/Repository/Loader/TimesheetIdLoader.php:58)"} []
[2020-05-17 13:52:38] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []

**Additional context**
 - Kimai version: Kimai 2 - 1.9
 - PHP version: PHP 7.3.17

**Maybe it's worth to mention, that I made a copy of the sqlite-db and played around a little bit with the following results:**
apache@dc /s/www/kimai2 $ bin/console doctrine:schema:validate
 [ERROR] The database schema is not in sync with the current mapping file.

I tried "bin/console doctrine:schema:update --force" which results in
11:59:49 ERROR     [console] Error thrown while running command "doctrine:schema:update --force". Message: "An exception occurred while executing 'INSERT INTO kimai2_timesheet (id, user, activity_id, project_id, start_time, timezone, duration, description, exported, end_time, rate, fixed_rate, hourly_rate, internal_rate) SELECT id, user, activity_id, project_id, start_time, timezone, duration, description, exported, end_time, rate, fixed_rate, hourly_rate, internal_rate FROM __temp__kimai2_timesheet':\n\nSQLSTATE[23000]: Integrity constraint violation: 19 FOREIGN KEY constraint failed" ["exception" => Doctrine\DBAL\Exception\DriverException^ { …},"command" => "doctrine:schema:update --force","message" => """  An exception occurred while executing 'INSERT INTO kimai2_timesheet (id, user, activity_id, project_id, start_time, timezone, duration, description, exported, end_time, rate, fixed_rate, hourly_rate, internal_rate) SELECT id, user, activity_id, project_id, start_time, timezone, duration, description, exported, end_time, rate, fixed_rate, hourly_rate, internal_rate FROM __temp__kimai2_timesheet':\n  \n  SQLSTATE[23000]: Integrity constraint violation: 19 FOREIGN KEY constraint failed  """]

The backup of the kimai.sqlite has been restored after the failed tests.

Regards,
Jan

**Comment by kevinpapst** [comment]
Using SQLIte in production is not supported. It is explained in the installation docs why and you ran into the problem described.

https://www.kimai.org/documentation/installation.html#sqlite-not-supported-for-production-usage

> It does not support FOREIGN KEY constraints out of the box, which can lead to critical bugs when deleting users/activities/projects/customers

SQlite is crap when it comes to foreign keys. 
If you don't know what this means: if you delete a customer, all its projects, activities ... and all timesheets logged onto this customer should be deleted as well - by the database through the use for foreign keys.
Not Sqlite deleted only the customer and not the timesheets. When you open your timesheet view, a n entry is found that has no customer, which is an "illegal state" and Kimai breaks.

**Comment by jsielemann** [comment]
Hey Kevin,
thank you for the answer...yes...I think the border from "testing" to "oh it's good, use it as productive system" was floating. 
I'm planning to switch over to MariaDB anyway. So I will try to fix the FK issues...and after that I hope that I can import the data into MariaDB somehow. I  not, I will start from scratch.

But one question...normally DBMSes have functions like "ON DELETE CASCADE" to delete all FKs....so SQlite doesn't support it?

Regards,
Jan

**Comment by jsielemann** [comment]
Okay, I fixed it. Is there any tutorial, how to migrate to MariaDB?

**Comment by kevinpapst** [comment]
Export from sqlite, import into mysql.
Google knows more.

**Comment by sixtyfive** [comment]
> Google knows more

That's a slap in the face when you just spent a hundred and fifty bucks on one of your plugins and the plugin's description said nothing about needing MySQL in the requirements section. Also got blind-sided by the 150€ plugin needing another 50€ plugin, but fair enough, that one _was_ mentioned, so my bad for not reading the small print thoroughly enough. I do want to note down here, though, that my feelings have really begun to slip from "nice piece of software, and by buying the plugins you're even supporting a one-man company" to "shit, this might be a cheap scheme for ripping people off in the shallow disguise of a developer claiming to not have the time to provide free support". Sorry for the harsh words, but I've been at it for half a day now to try and figure out _using Google, among other things_ how to migrate the data out of SQLite properly.

**Comment by kevinpapst** [comment]
Kimai requires MySQL and does NOT support SQLite for any production database. That simple fact was and is ignored over and over again by many users. And thats because I removed support for it completely for the next version.

I am going to delete your comment, because it is not only full of frustration but also full of false accusations and harmful.

I understand frustration, but the way you present your arguments is against all community standards.

1. You did NOT contact me personally before, which should obviously be the first way to clarify questions.
2. This issue tracker is about Kimai core and not about plugins.
3. I am not selling any plugin that requires another plugin. Probably you should read first who is the author of stuff you publicly accuse of stuff. 

Now, please write to info@keleo.de to clarify things.
