### ISSUE TITLE
API-Endpoint requires budget and timeBudget to create a new customer

### ISSUE THREAD

**Issue by MPW1412** [kevinpapst/kimai2#1713]
When creating a new customer via the API, e. g. with kimai-python, Kimai rejects requests without time and timeBudget set.

I tried to adapt the API, but @kevinpapst told me, this was rather a bug in the Kimai api endpoint: https://github.com/kbancerz/kimai-python/pull/1

**To Reproduce**
1. Create a new customer with kimai-python
3. Following error occurs:

```
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Powered-By': 'PHP/7.4.5', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=nf3f4afk3o7o7kvg1f12qq4one; path=/; HttpOnly', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0, must-revalidate, private', 'Server': 'nginx', 'pragma': 'no-cache', 'Date': 'Sat, 16 May 2020 23:08:32 GMT', 'Expires': 'Sat, 16 May 2020 23:08:32 GMT'})
HTTP response body: {"code":400,"message":"Validation Failed","errors":{"children":{"name":{},"number":{},"comment":{},"company":{},"vatId":{},"contact":{},"address":{},"country":{},"currency":{},"phone":{},"fax":{},"mobile":{},"email":{},"homepage":{},"timezone":{},"color":{},"budget":{"errors":["This value should not be null."]},"timeBudget":{"errors":["This value should not be null."]},"visible":{}}}}
**Logfile**
```

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Kimai Version 1.9

**Comment by kevinpapst** [comment]
@MPW1412 can you give the branch from the PR a try?

**Comment by MPW1412** [comment]
I can confirm the API works without modifications now. Thanks for fixing this so quickly, @kevinpapst!

**Comment by kevinpapst** [comment]
Thanks for testing!
