### ISSUE TITLE
Markdown not supported in Calendar View

### ISSUE THREAD

**Issue by Kantime** [kevinpapst/kimai2#1719]
**Describe the bug**
Markdown is not supported in Calendar view.

**To Reproduce**
Comment a line with a bold texte like this : **texte**
Its is displayed as bold in list view but not in calendar view.

**Desktop**
 - Device: iMac
 - OS: Mac OS 10.14.6
 - Browser : Firefox
 - Version 76.0.1

**Additional context**
 - Kimai version 1.6.2 stable
 - PHP version 7.3

**Comment by kevinpapst** [comment]
Thanks for letting me know!

**Comment by kevinpapst** [comment]
If someone wants to contribute a PR to fix the issue, I am open to discuss integration.
But I will not implement this, closing.
