### ISSUE TITLE
Selection menu not reachable if browser window too small

### ISSUE THREAD

**Issue by kernie** [kevinpapst/kimai2#1721]
**Describe the bug**
When I want to edit e.g. a project and the project has a postition at the very end of the page the edit menu is partially invisible and cannot be accessed (see image).

**To Reproduce**
See image.

**Screenshots**
<img width="586" alt="Bildschirmfoto 2020-05-19 um 15 39 11" src="https://user-images.githubusercontent.com/23321751/82333739-689f8000-99e7-11ea-9032-2b9950aed819.png">

**Additional context**
 - Kimai version: 1.9
 - PHP version: 7.3

**Comment by kevinpapst** [comment]
Workaround: click on the table row to open the details page and then choose the action from the dropdown menu in the upper right corner.

Duplicates #1219 - so I am closing this one here
