### ISSUE TITLE
Translation to Hebrew

### ISSUE THREAD

**Issue by eransurg** [kevinpapst/kimai2#1723]
I have translated kimai to Hebrew (if you're interested I can send you the translation files).
Everything works fine except for the name of days in calendars which looks like Chinese...
I've added the following lines to assets\app.js:
    require('select2/dist/js/i18n/he');
    require('moment/locale/he');
And this line to assets\calendar.js:
    require('fullcalendar/dist/locale/he');
However I don't see any change.

Also, how can I translate the login page?
I've created the translation file under: 
kimai2\vendor\kevinpapst\adminlte-bundle\Resources\translations\AdminLTEBundle.he.xliff
But the page is still in English.

**Comment by kevinpapst** [comment]
Awesome, thank you! 👍 

Can you send me the files? Then I will take care of the calendar and other javascript widgets. 
Adding the lines is necessary but they need to be recompiled as well. If you don't have a developer setup, that's too much - let me do it.

The file location for the login page looks correct, just attach it as well and I will prepare a demo installation, so you can test all together

**Comment by eransurg** [comment]
[hebrew.zip](https://github.com/kevinpapst/kimai2/files/4656353/hebrew.zip)

**Comment by eransurg** [comment]
[expenses_he.zip](https://github.com/kevinpapst/kimai2/files/4656468/expenses_he.zip)

I forgot to upload the files for the expenses plugin...So here they are.
By the way, the login page is working now in Hebrew (cleared cache).

**Comment by kevinpapst** [comment]
I will install a demo soon, but it's currently taken by another branch. I'll post an update soon.
