### ISSUE TITLE
Kimai2 unable to delete timesheet

### ISSUE THREAD

**Issue by adivesa** [kevinpapst/kimai2#1726]
Hello,

I assume this is a server error not a kimai error, however some assistance would be appreciated.
Whenever I try to delete a timesheet, I get the error attached.

![err_ui](https://user-images.githubusercontent.com/16808929/82640974-3b83e500-9c14-11ea-9b27-b509bc52f9b1.JPG)
![err_server](https://user-images.githubusercontent.com/16808929/82640972-3aeb4e80-9c14-11ea-97c2-71e5b63062a9.JPG)

 - Kimai2
 - PHP version 7.3

**Comment by kevinpapst** [comment]
Check Doctor > Logs

**Comment by adivesa** [comment]
Thank you for the reply, the logfile is empty

**Comment by kevinpapst** [comment]
Hm, now I see the 405 error above, which sounds more like a webserver config problem.
Can you please create another one from the network console with the delete request selected (from firefox).
Should look something like that:
<img width="1643" alt="Bildschirmfoto 2020-05-23 um 12 24 32" src="https://user-images.githubusercontent.com/533162/82728454-7a876880-9cf0-11ea-98e0-5b9d5bfd7fbd.png">

**Comment by adivesa** [comment]
Sure, here it is

![image](https://user-images.githubusercontent.com/16808929/82728513-4a909300-9cf9-11ea-98c1-e1c3185ece44.png)

**Comment by kevinpapst** [comment]
Ok, looks as expected. 

Thanks to the screenshot I could see your domain and test with Postman.
No matter which URL I use, I always get the same 405 error page when I use any other HTTP methods besides GET/POST/HEAD.

The error looks as if it is outside from the Kimai vhost/server config.

Can you compare your nginx configuration with the one from the docs?
Eg. https://www.kimai.org/documentation/webserver-configuration.html or https://www.kimai.org/documentation/fresh-ubuntu-18.html#configure-webserver

**Comment by kevinpapst** [comment]
Search for `limit_except` or `add_header` - there seems to be a couple of ways to limit access to certain http request methods in nginx.

**Comment by adivesa** [comment]
Many thanks for the support, it was, of course, an nginx misconfiguration. Added DELETE to allowed methods and it works like a charm :)
