### ISSUE TITLE
blank screen in the login page

### ISSUE THREAD

**Issue by vijithd** [kevinpapst/kimai2#1728]
blank screen in the login page

Error log
PHP Parse error:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in public_html/public/index.php on line 3

Kimai version 2-1.9

Server
PHP Version | 7.3.17
MySQL Version | 5.6.41-84.1
Operating System | linux

**Comment by kevinpapst** [comment]
PHP version < 7.1

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by vijithd** [comment]
thank you for the response kevin.
