### ISSUE TITLE
Salary for freelance employees paid in hours

### ISSUE THREAD

**Issue by Turmz** [kevinpapst/kimai2#1729]
Kimai is great! 
But it's suboptimal for hourly-freelance employees. It would be great if there was a feature for you as an Admin to assign hourly rates for employees, where they could view that month's salary in the dashboard.
It's imperative, that the admin has the ability to set when the month starts and when it ends (e.g. 20th of May to 19th of June).

**Comment by kevinpapst** [comment]
There are per user internal and external rates, they should be sufficient.

As of now, there is no concept to display the internal rate anywhere except the detail pages of customer/project/activity.

The external rate is shown in the timesheet. The column can be shown or hidden, that [depends on the permission](https://www.kimai.org/documentation/permissions.html) `view_rate_own_timesheet`.

Making the month start and end date configurable is another feature request (I guess there is something quite similar already existing, please search through the existing issues with the term "month").

I need to think about how the internal and external rate should be displayed and where.
If you have ideas, please let me know.

**Comment by kevinpapst** [comment]
Its imperative that you provide feedback to the open source projects you want to do work for you.
