### ISSUE TITLE
prod.log missing

### ISSUE THREAD

**Issue by MRIIOT** [kevinpapst/kimai2#1730]
Installed 1.9 on docker, made sure var/log is owned by www-data and has permission. But prod.log is not written.  I see no errors in console.  Is there any verbosity or other settings preventing prod.log ?

Dockerfile: https://github.com/tobybatch/kimai2/issues/109

**Comment by kevinpapst** [comment]
With 1.9 a lot of deprecations were fixed and the log level was adjusted, so you should rarely see any log.
What you can do to force a log: open the timesheet in two tabs with a running record.
The stop that entry in one tab, switch to the other tab and try to stop it again. That will raise an error and the log file should be written.

**Comment by MRIIOT** [comment]
Perfect!
