### ISSUE TITLE
Install problems with Composer 2

### ISSUE THREAD

**Issue by anderlk** [kevinpapst/kimai2#1731]
Hi, I've got Problems with installation on my server with composer.

Can someone help me to get this work:

Creating a "kevinpapst/kimai2" project at "./kimai2"
Installing kevinpapst/kimai2 (1.9)
  - Downloading kevinpapst/kimai2 (1.9)
  - Installing kevinpapst/kimai2 (1.9): Extracting archive
Created project in /var/www/vhosts/xxx/kimai2
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - kimai/kimai2-composer is locked to version 0.1 and an update of this package was not requested.
    - kimai/kimai2-composer 0.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 3
    - symfony/flex is locked to version v1.6.2 and an update of this package was not requested.
    - symfony/flex v1.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 4
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ocramius/proxy-manager 2.2.3 requires ocramius/package-versions ^1.1.3 -> satisfiable by ocramius/package-versions[1.4.2].
    - ocramius/proxy-manager is locked to version 2.2.3 and an update of this package was not requested.

Use the option --with-all-dependencies to allow updates and removals for packages currently locked to specific versions.
ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-reqs, but this will also ignore your PHP version and may result in bigger problems down the line.

Thanks Andreas

**Comment by kevinpapst** [comment]
> You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with

The solution is simple: use Composer 1.

**Comment by anderlk** [comment]
Hi Kevin thanks for helping. Never done an installation with composer before. There was a global Install of Composer 2 on Server. For the first time it was not easy for me to install another version locally. But after reading the Composer documentation carefully, I did it.

Now it is time to move my 10 year old V1 installation to the new version.

Regards Andreas

**Comment by kevinpapst** [comment]
Oh, sorry, if I would have known, my answer would have been longer 😁 
But seems you did it by yourself, awesome!
I'll close here, but if you need help with the migration, just open a new issue.
