### ISSUE TITLE
Configurable first day of the week

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#1732]
**Is your feature request related to a problem? Please describe.**

Problem is the first day of the week being bound to the users locale.

While that fits in an environment where the user can choose its native language it doesn't work for the userbase with English as UI language, because English might only be a fallback if their native language is not available. Maybe there are other languages which are used in multiple timezones (eg. French).

Until 1.9 the datepicker was hardcoded to Monday as being the first day of the week.
With the translation to hebrew in #1724 that behavior was changed and adapted to the timesheet calendar, which already used the `dow` from momentjs.

**Describe the solution you'd like**

The `first day of the week` should be configurable. But the question is: where? Is that a user specific setting or a global setting? Being bound to the locale definition of Kimai or available through the system settings screen (I prefer latter one).

**Describe alternatives you've considered**

Stick to the definition of moment and create empty locales without translations for every language. Then the user needs to choose its own language but will see English as fallback.

**Comment by eransurg** [comment]
I also believe it should be in the global settings as it gives users more flexibility.
If a user prefer to work in English, he should still be able to see the calendar correctly.
Thanks for the hard work!

**Comment by HeinzWuert** [comment]
and last but not least the first month of year configurable would be the top! ;-)

**Comment by Recoil1980** [comment]
My 2 cents:

As stated in another issue about configurable starting days, our pay weeks run from Friday to the following Thursday.  All the users who would be checking their weekly times would be looking for them like they are listed now on an exported Excel document.  Calculating pay may be easier on HR as well.  I would vote for a numeric global setting for everyone -> Settings -> Calendar -> Starting Day of Week: [0 (Sunday)] - [6 (Saturday)]

I'm new to Kimai so I may be overlooking features which may make things easier to use.

**Comment by kevinpapst** [comment]
With the next release there will be a user specific setting for the "first day of week", see #1952.
This is for the frontend (calendar, date pickers) only.

@HeinzWuert and @Recoil1980 - "tax year" and a "payroll period" are different topics

**Comment by Recoil1980** [comment]
@kevinpapst will the ability to change the payroll period starting days be an option at some point in the core system, or is this more suited for a plugin?

I'll email about a custom plugin request.
