### ISSUE TITLE
Start of Billing Month

### ISSUE THREAD

**Issue by boginw** [kevinpapst/kimai2#1733]
**Is your feature request related to a problem? Please describe.**

Many businesses have a billing month, where the start of the month is usually around the 20th to 25th of the actual month. If the billing month begins on the 20th then it ends on the 19th of the next actual month. This is usually done so that the business can pay its employees before the next month begins. Currently, Kimai does not support changing the start of the billing, which leaves the dashboard reporting the wrong numbers for the whole month column.

**Describe the solution you'd like**
In the calendar box on the admin settings page, I would like to see an option labeled "Start of BIlling Month", with a default of 1, and a maximum of 28. The dashboard should then reflect the correct numbers for the current billing month and not the actual month.

**Describe alternatives you've considered**
Alternatively, one could add an extra column on the dashboard with a date-selector, giving the user the ability to specify the range.

**Additional context**
I think that is all.

**Comment by kevinpapst** [comment]
Hi @boginw ,  why do you say maximum is: 28? Because of February?

**Comment by boginw** [comment]
Hi @kevinpapst,

Sorry, I forgot to clarify, but yes, that is because of February.

**Comment by kevinpapst** [comment]
Nobody voted and nobody ever mentioned it in discussions. 
So I assume the community does not really need that feature. But a company interested in that feature can contact me and sponsor it.
