### ISSUE TITLE
Export sheet always has internal rate

### ISSUE THREAD

**Issue by sdillenburg** [kevinpapst/kimai2#1737]
Dear all,

When unchecking the column visibility for, e.g.  Unit price, Internal rate and Total price during export, they are stil part of the generated (standard) pdf document.

I am using Kimai 1.9 stable (Ayumi), PHP 7.3
Browser is Firefox 76.0.1 on Windows 10

I would have expected a timesheet withou any costs with the applied column selection.

Please let me know if more information is required.

**Comment by kevinpapst** [comment]
Interesting idea to configure the export columns with the visibility chooser.
Actually it is only used for the preview right now.
The export documents (PDF) have pre-configured columns, but you can add your own export templates (see docu).

**Comment by sdillenburg** [comment]
Thanks for your reply. In kimai1 it was possible to select columns to be exported to pdf in the web interface. Thus, I was assuming this was possible in kimai2 as well.

I will then adjust my template files.
