### ISSUE TITLE
When selecting activity many times I have to select it twice

### ISSUE THREAD

**Issue by mgilhar** [kevinpapst/kimai2#1740]
When selecting activity many times I have to select it twice:
1. Go My times
2. Click on the + to add time
3. Fill in From To times
4. Select project - project name appears in the dialog
5. Select activity - dialog stay empty although I selected activity
If I repeat step number 5 the second time it works

**Comment by kevinpapst** [comment]
Does the activity list look different when you select it at first, compared to the list when you have to select it the second time?
Is Kimai feeling slow for you?

**Comment by kevinpapst** [comment]
Which Kimai version are you using?
Can you test it at the demo, I never experienced the problem, but I guess it could happen if your server responds too slow.

**Comment by mgilhar** [comment]
This is the version I have
Kimai 21.8 stable (Ayumi)

Michal Gilhar 
Product Manager| Dalet Digital Media Systems 
Office:+972-73-2222-856 | Fax:+ 972-73-2222-801| mgilhar@dalet.com
Mobile: +972-52-510-6622 | skype id: Michal.gilhar www.dalet.com
The information contained in this message and any attachment to it is 
privileged, confidential and protected from disclosure. If the reader of 
this message is not the intended recipient, or an employee or agent 
responsible for delivering this message to the intended recipient, you are 
hereby notified that any dissemination, distribution or copying of this 
communication is strictly prohibited. If you have received this 
communication in error, please notify the sender immediately by replying 
to the message, and please delete it from your system. Thank you.

**Comment by mgilhar** [comment]
Hi,
I don't have slowness
Best,
Michal

Michal Gilhar 
Product Manager| Dalet Digital Media Systems 
Office:+972-73-2222-856 | Fax:+ 972-73-2222-801| mgilhar@dalet.com
Mobile: +972-52-510-6622 | skype id: Michal.gilhar www.dalet.com
The information contained in this message and any attachment to it is 
privileged, confidential and protected from disclosure. If the reader of 
this message is not the intended recipient, or an employee or agent 
responsible for delivering this message to the intended recipient, you are 
hereby notified that any dissemination, distribution or copying of this 
communication is strictly prohibited. If you have received this 
communication in error, please notify the sender immediately by replying 
to the message, and please delete it from your system. Thank you.

**Comment by kevinpapst** [comment]
Can't help without feedback / ignoring questions.
