### ISSUE TITLE
Configurable invoice filename / was bug: preview invoices with same filename

### ISSUE THREAD

**Issue by sdillenburg** [kevinpapst/kimai2#1741]
Hi all,

I want to generate weekly timesheets automatically. Therefore I would like to use `kimai:invoice:create`

When I do
`php7.3-cli bin/console kimai:invoice:create --user=XXX --by-project --template="timesheet" --start=$start --end=$end  --exported=all --preview=/XXX/_automatic_timesheets/`

files get overwritten when I have two projects for the same client. Is there a way to include the project in the filename or to prevent overwriting files when using the `--preview` option?

Thanks.

edit:
I am using a .docx template in case this matters.

**Comment by kevinpapst** [comment]
Hm, interesting use-case which I didn't see. 
Preview invoices always uses the same invoice number?
As a workaround you could add this code:
```
            $filename = uniqid() . $filename;
```
at this line: https://github.com/kevinpapst/kimai2/blob/master/src/Command/InvoiceCreateCommand.php#L355

**Comment by sdillenburg** [comment]
Thanks. This did the trick. However, I needed to add the line to the `saveInvoicePreview()` instead of ` createInvoicesForCustomer()`.

For the long term, it would be nice to add variables such as project name or calender week to the output filename.

**Comment by kevinpapst** [comment]
Hm, yes. The filename should be configurable like the invoice number, as everyone has a different idea how it should look like.

**Comment by sdillenburg** [comment]
In my document number I would like to use the number of the calender week. Therefore I have added 
`            'query.begin_week' => $model->getQuery()->getBegin()->format('W'),
            'query.end_week' => $model->getQuery()->getEnd()->format('W'),                          
`
to `src\Invoice\Hydrator\InvoiceModelDefaultHydrator.php`. I would like to propose to add this to Kimai.

**Comment by kevinpapst** [comment]
I don't know what the "document number is: do you mean the invoice number?

This logic should be moved somewhere else, because the filename will include the invoice number as well. You could add a case here:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php#L95
this would allow to use it as part of the configurable invoice format

**Comment by sdillenburg** [comment]
Sorry for not clarifying this. I am "misusing" `kimai:invoice:create` to automatically generate weekly timesheets for my client to review (with the `--preview` option). At the end of each month, a monthly invoice is generated.

With document number, I mean the number of my weekly timesheet. As I do not want to interfere with invoice numbers here, I generate the timesheet document number in the .docx template using various global variables.

**Comment by kevinpapst** [comment]
Okay, in this case: simply use one of the existing date variables and format it inside word.
No need to add extra variables via PHP.

**Comment by kevinpapst** [comment]
Previous:

bin/console kimai:invoice:create --user=susan_super --by-project --template="24" --start=$start --end=$end --exported=all --preview=/tmp/

```
+----------------------- Created 7 invoice(s) ------------------------+
| Filename                                                            |
+---------------------------------------------------------------------+
| /tmp/2021-057-0-CANADA-Demo.pdf                                     |
| /tmp/2021-057-2222222-010101010101.pdf                              |
| /tmp/2021-057-00_-_Customer_LLC-My_project.pdf                      |
| /tmp/2021-057-A_customer_name-Proactive_explicit_info-mediaries.pdf |
| /tmp/2021-057-2222222-22222.pdf                                     |
+---------------------------------------------------------------------+
```

New option: `--preview-unique`

bin/console kimai:invoice:create --user=susan_super --by-project --template="24" --start=$start --end=$end --exported=all --preview=/tmp/ --preview-unique
```
+---------------------------------- Created 7 invoice(s) ----------------------------------+
| Filename                                                                                 |
+------------------------------------------------------------------------------------------+
| /tmp/invoice_61923a2ff35dd2021-057-0-CANADA-Demo.pdf                                     |
| /tmp/invoice_61923a302bd3d2021-057-2222222-010101010101.pdf                              |
| /tmp/invoice_61923a30403472021-057-00_-_Customer_LLC-My_project.pdf                      |
| /tmp/invoice_61923a30541242021-057-A_customer_name-Proactive_explicit_info-mediaries.pdf |
| /tmp/invoice_61923a3067d9a2021-057-2222222-22222.pdf                                     |
+------------------------------------------------------------------------------------------+
