### ISSUE TITLE
Change view in calender

### ISSUE THREAD

**Issue by schwantuschke** [kevinpapst/kimai2#1742]
It would be nice if the user can change the headline for entries in calender view. At the moment only I can see the activity. But i would like to see the project in the calender overview.
It's possible to create a setting to change this?

**Comment by schwantuschke** [comment]
And something else. I think a filter (projects, clients...) for calender view will be nice.

**Comment by kevinpapst** [comment]
You can vote for the existing issue #573

**Comment by kevinpapst** [comment]
Closing as duplicate of #1703
