### ISSUE TITLE
Changes to the standard HTML invoice template doesn`t work

### ISSUE THREAD

**Issue by Andi-AKL** [kevinpapst/kimai2#1743]
Hello,

I want to change the HTML standard invoice template.
The columns "Rate" and "Entry Rate" should be deleted.

For this I have deleted the lines 
<td nowrap class = "text-nowrap text-right"> {{rate | money (currency)}} </td> and 
<td nowrap class = "text-nowrap text-right"> {{ entry.rate | money (currency)}} </td>
in the file **default.html.twig** located in  /kimai2/templates/invoice/renderer.

However, the changes in the template are not taken into account when creating the invoice. The HTML invoice is displayed unchanged!?

I am very grateful for help!

Best
Andreas

**Comment by kevinpapst** [comment]
See documentation:

https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document

Important points are:

> Do NOT change the default templates, but copy the file and save it (with a new filename) at var/invoices/

and

> After you changed an invoice template, you have to clear the cache to see the results:

**Comment by Andi-AKL** [comment]
Hi Kevin,

Thank you for your quick reply.

I copied default.html.twig and saved it under a different name (invoice_andi.html.twig). Then I uploaded this file to /var/invoices and included it in the invoice templates. I have deliberately not changed the content of the copy.

However, when using the new template, come the error message:
"Changes could not be saved: check doctor / logs"

The rights for the /var directory an subdirectories are set as follows:
drwxrwx --- 2

Do you have an idea why?

Best
Andi (Munich)

**Comment by kevinpapst** [comment]
Nothing in 

> check doctor / logs

**Comment by Andi-AKL** [comment]
There are two files in /kimai2/templates/doctor/

actions.html.twig
index.html.twig

??

**Comment by kevinpapst** [comment]
<img width="1047" alt="Bildschirmfoto 2020-05-25 um 18 37 30" src="https://user-images.githubusercontent.com/533162/82830724-cc79eb00-9eb6-11ea-8cd2-51d7b209f4b7.png">

**Comment by Andi-AKL** [comment]
Entry in Doctor:

[2020-05-25 18:59:05] app.CRITICAL: Unable to find template "@invoice/invoice_akl.html.twig" (looked into: /kunden/1234/timetrack/kimai2/templates/invoice/renderer). [] []

Why is Kimai looking for my individual template in /templates/invoice/renderer when I ´ve uploaded to /var/invoices?

**Comment by kevinpapst** [comment]
I know that is works in dozens of customer environments, so you must have changed your local.yaml?

**Comment by kevinpapst** [comment]
I hope you uploaded it to `kimai/var/invoices/` and not to `/var/invoices`

You can try to upload to via the invoice UI at /en/invoice/document_upload

**Comment by Andi-AKL** [comment]
I´ve upload it to /kimai2/var/invoices

Furthermore I tried to upload the "invoice_akl.html.twig" via invoice UI and got the message:
This file type is not allowed

**Comment by kevinpapst** [comment]
Oh right, sorry, my bad. I haven't allowed upload of twig templates yet....

**Comment by Andi-AKL** [comment]
> I know that is works in dozens of customer environments, so you must have changed your local.yaml?

local.yaml - what is this? I´ve never touched (see, found, edit...) this file. And I can´t find this file name in kimai2/.

**Comment by kevinpapst** [comment]
It doesn't exist by default. Did you clear the cache?

**Comment by kevinpapst** [comment]
No feedback, closing
