### ISSUE TITLE
DOCX activity report with daily summarized hours and activity descriptions

### ISSUE THREAD

**Issue by Andi-AKL** [kevinpapst/kimai2#1744]
Dear Kimai Community,

I would like to create a Word report (docx) that summarizes activity entries by days. The function of this report is similar to that of the standard HTML invoice
(Sample: [Kimai_report_daily_summary.pdf](https://github.com/kevinpapst/kimai2/files/4677580/Kimai_report_daily_summary.pdf))

What are the instructions or field variables for totaling the duration of the activity (per day)?

How can it be achieved that each date is only displayed once and not in every line of a activity description?

Many thanks for your help.

Best
Andreas

**Comment by kevinpapst** [comment]
You can change the "sum calculation" inside the invoice template settings to "Date: one entry per day". That will sum up all records per day.

**Comment by Andi-AKL** [comment]
Fine, that works.
This is a great function!
