### ISSUE TITLE
Importing Data does not work

### ISSUE THREAD

**Issue by Andi-AKL** [kevinpapst/kimai2#1745]
I would like to import time entries into Kimai.

According to the documentation, I try to access the command kimai: import: timesheet --help via SSH access in the directory /kimai2/bin/

Although the "console" file is in the /bin directory, I get the following message:
zsh: command not found: kimai: import: timesheet

actual permissions in /bin:
-rwxr-x--- 1 u456199 nobody 1184 May 22 19:21 console

What am I doing wrong?

Many thanks for help
Andreas

**Comment by kevinpapst** [comment]
`kimai: import: timesheet` is not the same as `kimai:import:timesheet`:

```bash
bin/console kimai:import:timesheet
```

**Comment by Andi-AKL** [comment]
o.k. - my fault ;-) 

But now i get this in my SSH-Terminal after typing 
bin/console kimai:import:timesheet --help

(18:41:52) [/kunden/1234/timetrack/kimai2] bin/console kimai:import:timesheet --help
X-Powered-By: PHP/4.4.9
Content-type: text/html

<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>/kunden/1234/timetrack/kimai2/bin/console</b> on line <b>7</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/kunden/1234/timetrack/kimai2/bin/console</b> on line <b>13</b><br />

**Comment by kevinpapst** [comment]
Wrong PHP version, check with `php -v`

**Comment by Andi-AKL** [comment]
PHP 4.4.9 (cgi) (built: Jan 13 2016 11:52:37)
Copyright (c) 1997-2008 The PHP Group
Zend Engine v1.3.0, Copyright (c) 1998-2004 Zend Technologies
    with Zend Optimizer v3.3.3, Copyright (c) 1998-2007, by Zend Technologies

**Comment by kevinpapst** [comment]
Wow, fantastic... read this, there are some tips how to solve that:
https://www.kimai.org/documentation/installation.html#shared-hosting

**Comment by Andi-AKL** [comment]
Yes, DF is a great hoster! :-))

Thanks for your hint! With the prefix "php7.3.5-cli" the commands are working.

**Comment by Andi-AKL** [comment]
Hi Kevin,

one more issue with importing data.

After command 
php7.3.5-cli bin/console kimai:import:timesheet --delimiter=";" Macintosh HD/Benutzer/Andi/TMP/import.csv

I get the error-message
Too many arguments, expected arguments "command" "file".

Is the space between "Macintosh HD" the problem (but this is the name of my volume)?

Thanks for help once more! 
I

**Comment by kevinpapst** [comment]
Pleas keep in mind that this is not some arbitrary IT forum. 
Did you try to use quotes around the filename?
Did you try to address your home directory with `~/TMP/import.csv`?

**Comment by Andi-AKL** [comment]
> Pleas keep in mind that this is not some arbitrary IT forum.

Yes I know, but I cannot assess what a software problem is and what can be attributed to me as a DAU ;-)

I´ve fixed the issue with the file (upload in root directory of the webserver and ~/import.csv).

But there is now an import error:
[ERROR] Failed importing timesheet row 1 with: DateTime::__construct(): Failed to parse time string (01.05.20 10:00) at position 9 (1): Double time specification   

Is there any documentation about the format or structure of a .csv import file?

This is my  File:
[import.csv.zip](https://github.com/kevinpapst/kimai2/files/4678679/import.csv.zip)

**Comment by kevinpapst** [comment]
Its rather hidden: it says `which are formatted like CSV exports`

I will add an example. Simply create an CSV export from Kimai and use it as template.

**Comment by kevinpapst** [comment]
Okay, I added an example as the formats of export and import do not fully match:

http://www.kimai.org/documentation/imports.html#example

**Comment by Andi-AKL** [comment]
Great Job Kevin!
Thanks for the added documentation and the example. Now it works! Jeahhh!
This saves me a lot of work from entering the time entries by hand! 

Thanks and good night
Andi
