### ISSUE TITLE
Show calendar of user in calendar of admin

### ISSUE THREAD

**Issue by hoangduy1505** [kevinpapst/kimai2#1746]
Hi, Can you show calendar of all user in calendar of admin, I see it in timesheet but it difficult to view.

**Comment by cloggg** [comment]
actually, it would make sense that the teamleader can be assigned rights to view/modify timesheets (based on permissions of the role). It is much easier to use 'drag'n'drop' calendar interface to fix/manipulate timesheets of employee using calendar (just as the employee would normally do)
