### ISSUE TITLE
Critical error after deleting an imported customer 

### ISSUE THREAD

**Issue by Andi-AKL** [kevinpapst/kimai2#1747]
**Describe the bug**
An "imported customer" was automatically created when a time entry was imported. The project belonging to the time entry was automatically assigned to this customer during the import.

After deleting the "imported customer", a critical error 500 occurred immediately (see screen shot):
<img width="725" alt="Kimai error 500" src="https://user-images.githubusercontent.com/65902365/82866237-c7558400-9f28-11ea-98bd-0c30c9270a93.png">

A login in Kimai is no longer possible with the same error message.

What needs to be done to start Kimai again?

**Logfile**
```
Add the last lines from your logfile at var/log/prod.log, around the time when the problem happened.
```
[prod.log.txt](https://github.com/kevinpapst/kimai2/files/4680231/prod.log.txt)

**Desktop/Smartphone**
 - Browser:  chrome & safari

**Additional context**
 - Kimai version: 1.9
 - PHP version: 7.3 stable

**Comment by kevinpapst** [comment]
there is a timesheet that has no project, which should be impossible

**Comment by Andi-AKL** [comment]
O.k. thanks for this information. 

I imported the data record again, hoping to restore the information missing in the database.
However, the error message above comes when trying to start Kimai.

And now?

**Comment by Andi-AKL** [comment]
Even bin/console cache:clear does not solve the problem.

**Comment by kevinpapst** [comment]
There are invalid records inside the table `kimai2_timesheets` which should be impossible.
Are you using SQLite?

**Comment by Andi-AKL** [comment]
yes - the out of the box database

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/installation.html#sqlite-not-supported-for-production-usage

> It does not support FOREIGN KEY constraints out of the box, which can lead to critical bugs when deleting users/activities/projects/customers

> and don’t file any bug report - you have been warned!

**Comment by Andi-AKL** [comment]
o.k. - thx for the hint.

I was still in test mode. Nevertheless, I hope that the communicated bug is useful for your knowledge.

Now I will start with a fresh installation on a MySQL-Database for productive use. ;-)

**Comment by kevinpapst** [comment]
Yeah, sorry. 
That problem is well documented and I consider this a bug in SQLite.
I will not add application code to work around that problem.
