### ISSUE TITLE
Add new language (Vietnamese)

### ISSUE THREAD

**Issue by hoangduy1505** [kevinpapst/kimai2#1748]
Hi,

I am translating Vietnamese language for kimai 2.
I follow your instructions step by step--> dont have issues, https://www.kimai.org/documentation/translations.html
But when I refresh my site to choose my language, it not show my new language
The language variant is vi is right?
![image](https://user-images.githubusercontent.com/15534810/82885646-a06e7080-9f6f-11ea-863d-bc70f7d93101.png)

**Comment by kevinpapst** [comment]
Cool 👍 

Did you edit the file [config/services.yaml ](https://github.com/kevinpapst/kimai2/blob/master/config/services.yaml#L5) and add `vi` to the list? Did you clear the cache afterwards?

**Comment by hoangduy1505** [comment]
Hi,

It work when I clear cache, thank you
Please help me add Vietnamese language to next release version

Thanks,

*----------------------------------------*

*Mr. Duy Ly*

System Development Engineer


Vào Th 3, 26 thg 5, 2020 vào lúc 19:17 Kevin Papst <
notifications@github.com> đã viết:

**Comment by kevinpapst** [comment]
Sure I will help you with that. Please share the translated files once you are ready with the translation and I will take care of the configuration, javascript and the other missing pieces.

**Comment by hoangduy1505** [comment]
Hi,

I attacked file in email before but you can not see it.
Can you download form my google drive link:
https://drive.google.com/drive/folders/1o0RdWG42evERZQOiPN07-5jrryNCLABT?usp=sharing

*----------------------------------------*

*Mr. Duy Ly*

System Development Engineer


Vào Th 5, 28 thg 5, 2020 vào lúc 17:17 Kevin Papst <
notifications@github.com> đã viết:

**Comment by hoangduy1505** [comment]
Hi,

I added file email.vn.xlf on my drive.

Thanks,

*----------------------------------------*

*Mr. Duy Ly*

System Development Engineer


Vào Th 3, 2 thg 6, 2020 vào lúc 21:15 Kevin Papst <
notifications@github.com> đã viết:

**Comment by kevinpapst** [comment]
Awesome, thanks!

I updated the demo. Can you please test it and let me know if you want to change anything:

https://demo-branch.kimai.org/vi/timesheet/ with user `susan_super` and password `kitten`

**Comment by hoangduy1505** [comment]
Dear Kevin,

I don't change any in this time, if I update it I will send a new file for
you.
In the administration, I think if we have a calendar it will be good for
view. The timesheet difficult to view.

Thanks,

*----------------------------------------*

*Mr. Duy Ly*

System Development Engineer


Vào Th 4, 3 thg 6, 2020 vào lúc 18:43 Kevin Papst <
notifications@github.com> đã viết:

**Comment by hoangduy1505** [comment]
Hi Kevin,

Can you use online translation for translation? Such as crowdin ==> When
you update new string we will see and translate it

*----------------------------------------*

*Mr. Duy Ly*

System Development Engineer


Vào Th 5, 4 thg 6, 2020 vào lúc 11:56 Ly Hoang Duy <hoangduy1505@gmail.com>
đã viết:

**Comment by kevinpapst** [comment]
If you find an online translation tool that allows free translations, please let me know!

Crowdin is not possible because they have a rule which I do not meet:
> You do not have any commercial products related to the open-source project you are requesting a license for.

I will merge Vietnamese then, thanks for the contribution!
