### ISSUE TITLE
Permissions to activities

### ISSUE THREAD

**Issue by eransurg** [kevinpapst/kimai2#1750]
Is it possible to add team permissions to activities (just like customers and projects)?
For example, we have several activities for a project:
 - Project manager
 - Developer
 - QA
and so on...
I want that each employee will see the activity that relevant to him.
The first version of Kimai used to have it and it seems to be deprecated now....
I just wonder if anyone else need this feature... In my opinion it make sense to manage the permissions this way.
Thanks.

**Comment by kevinpapst** [comment]
Added with 1.10

**Comment by eransurg** [comment]
Thanks!
