### ISSUE TITLE
UX: Filter/Search values handover? save to session or user profile?

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#1752]
**outline**
i think it is maybe useful/intended, to allow a user so switch between Invoice/Export/Expenses/Timesheets,
without entering the same filter settings every time.
Doing so the GUI could be used even more rapidly.
But currently the filters are reset on page change.

**use case**
My workflow is to **get a combined result** and **tuning overall numbers,** in order to **finalize an invoice**.
Usually that's the preparation for the final discussion with the client.
This means: I have to interpret totals, completeness, details etc, and make corrections.

To **get a combined result** I use the **Invoice preview** and switch back to **MyTimes** or **Expenses**.
currently I workaround that by having 2-3 windows open.

this could even be stored in the DB user profile, and survive a logout.

cheers
manu

Ps: I'm on v1.9

**Comment by labor4** [comment]
...hm
and should a prefilled filter, if it exists, be used as a default for a new "+" entry?

don't know if it is fully congruent system wide, but it seems at quick sight.

**Comment by Aybee** [comment]
I would also have expected the filters to keep their settings. If you don't want to include this, I'll try it with the addon Violentmonkey https://addons.mozilla.org/de/firefox/addon/violentmonkey/ within my Firefox.

**Comment by kevinpapst** [comment]
> If you don't want to include this

Its not that I don't want to add it, but its: time, priority and missing concept that keeps me from adding this feature.

**Comment by kevinpapst** [comment]
I am closing here as `duplicate`, please add your ideas (and a 👍 reaction to the initial post) in #564

**Comment by kevinpapst** [comment]
Reopening due to the explanation by @labor4 in #564 - I was too quick with reading.

**Comment by labor4** [comment]
Easy, just honk if you need more discussion!
Best wishes

**Comment by kevinpapst** [comment]
In 1.14 you will be able to set the default search parameter for every screen (exclusively, they are not shared between different pages). I know this is not what you asked for, but I thought I share the news, as it fits here.

What I will not implement: magically transferring search filters from one page to another.
Connecting search with + dialog sounds very magic as well, especially as you can click "restart" from one of the search results.

**Comment by labor4** [comment]
thank you,
be well!
