### ISSUE TITLE
Kimai accepts ultra weak API keys

### ISSUE THREAD

**Issue by benchonaut** [kevinpapst/kimai2#1753]
**Describe the bug**
Kimai2 1.9 accepts ultra-weak API tokens , all Password-strength efforts are bypassed when users can insert e.g. "ab123"

**To Reproduce**
1. Go to 'en/profile/usname/api-token'
2. Click on 'submit' after enetring too-easy token
3. See error

**Logfile**
```
Add the last lines from your logfile at var/log/prod.log, around the time when the problem happened.
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: any
 - OS: any
 - Browser any
 - Version 1.9 (current ZIP )

**Additional context**
Set minimum thingy or insert generator for 24+ `[:alnum:]_-.:` chars ;)

**Comment by kevinpapst** [comment]
Thanks for the report!
Next version will validate the api-token the same way like the password (minimum 8 character)
