### ISSUE TITLE
Sort feature for columns not in the default view

### ISSUE THREAD

**Issue by Fanvaron** [kevinpapst/kimai2#1754]
**Is your feature request related to a problem? Please describe.**
Opening Customer and Project List in default view shows every column with a SortBy button. 
When using the eye button to add other fields to the View those do not have a SortBy button.

**Describe the solution you'd like**
I would like to be able to sort by any column.

**Describe alternatives you've considered**
Maybe each column to be sorted by needs to be configured separately (I'm not sure how exactly it works) if so even having everything with a default text-based sort would help.

**Screenshot**
![Example](https://user-images.githubusercontent.com/5766194/83352311-cb2f3f00-a34a-11ea-8b5f-21d4a46e7824.png)

**Comment by alqu** [comment]
Of course filtering by user is easily done, but the option to have a sort on the user column would be very helpful. Especially for admins or teamleads.

**Comment by kevinpapst** [comment]
I added several columns for sorting in customer, project and activity in #1902
But ordering by user is hard because its not clear by which field: username, alias, title?
Everyone expects something else. The displayed name cannot be used, because it could be at least the username or alias.

So I leave that one out for now.

**Comment by alqu** [comment]
Hm, what about adding a calculated field "user" which then uses the fields that are available, username if alias is null or so?

**Comment by kevinpapst** [comment]
The result would be unexpected for 50% of the users, no matter which logic I use.
The username can be completely different from the displayed alias. 
Eg 
User 1: username: bbb and display name: zzzz).
User 2: username: fff and no display name).
User 3: username: www and display name: aaaa).
User 4: username: xxx and no display name).
User 5: username: yyy and display name: bbb).
User 5: username: zzz and display name: 111).
...
What order do you expect?

The only "reliable" way that I see is by sticking to the username (it is used for ordering in the team config view / user dropdowns). This is already not clear and I discussed the topic multiple times with clients.

I am not really happy with that as well, but as soon as I allow to order by a field and the result is weird (to say at least), there will be bug reports for a good reason.
