### ISSUE TITLE
Timesheet and my times Export 

### ISSUE THREAD

**Issue by furkantolu** [kevinpapst/kimai2#1755]
Hi everyone,

We using Kimai2 1.8
Everything works very well, but excel is empty when we export in my times and timesheet section.
When I export to Expenses, there is no problem. Excel is full of data.

What would be the reason ?

**Comment by furkantolu** [comment]
When I export my times in your demo version, excel is full.
But I added a new project to my local via Github. I had the same problem in that project.

Is a setting or something necessary?
![Ek Açıklama 2020-06-01 140228](https://user-images.githubusercontent.com/32983969/83403032-8e2d8000-a410-11ea-9660-80ce25830c17.png)

**Comment by areanod** [comment]
Do you get any data in the preview before exporting the data? If yes, do you get any data exported if you choose any other format?

**Comment by kevinpapst** [comment]
Exporting via "My times" uses the current month if you did not filter for a specific date range.

**Comment by furkantolu** [comment]
Exported option is turned off for users outside of superadmin. I reached the correct result by updating the settings.

**Comment by furkantolu** [comment]
Thanks a lot.
