### ISSUE TITLE
Cancel-Button should have a confirmation

### ISSUE THREAD

**Issue by dasarne** [kevinpapst/kimai2#1757]
Often when I edit an entry and write a lot of text I accidentally press Cancel and lose everything I've written up to that point without asking. Also the escape key causes here a painful data loss.

I would like to be asked for a confirmation prompt when a dialog is aborted, in which it is pointed out that data will be lost. Alternatively you could always save the changes immediately and remove both the save and the cancel.

**Comment by kevinpapst** [comment]
See also #1794 - different problem, same behaviour: entered data is lost

**Comment by kevinpapst** [comment]
The close button will work as before, but there was a change regarding forms in modals with changed content.
I am closing this, as I think that the most common cases have been solved
