### ISSUE TITLE
red lines in timesheet

### ISSUE THREAD

**Issue by swille77** [kevinpapst/kimai2#1761]
hello,

after update to 1.9 we have in timesheet thsi red lines and how we can disabled this new feature?
i have read it is for overlaping, but we use kimai in duration mode and then we are not interessting inj start and end time and we have much red lines now.

greetings

**Comment by kevinpapst** [comment]
You could use the CustomCssBundle and hide them.

**Comment by swille77** [comment]
Thank you for your help, it works.
