### ISSUE TITLE
Invoice: Decimal fraction is different depends on the value

### ISSUE THREAD

**Issue by fredyb** [kevinpapst/kimai2#1765]
When I generate an invoice (docx), the decimal fractioin are different, depending on the fraction value (e.g. 10 / 5.**5** / 35.**95** / ..)

Proposed solution (and tested):
add in: src/Twig/Extensions.php
 
    private function initLocale()
    {
        $locale = $this->localeSettings->getLocale();

        if ($this->locale === $locale) {
            return;
        }

        $this->locale = $locale;
        $this->numberFormatter = new \NumberFormatter($locale, NumberFormatter::DECIMAL);
        $this->moneyFormatter = new \NumberFormatter($locale, NumberFormatter::CURRENCY);

        _**// add formatter FRACTION_DIGITS #.## 
        $this->numberFormatter->setAttribute(NumberFormatter::FRACTION_DIGITS, 2);
        $this->moneyFormatter->setAttribute(NumberFormatter::FRACTION_DIGITS, 2);**_
    }

For me this change works fin.

Thanks for the great software!!

**Comment by kevinpapst** [comment]
You mean the length is not forced, but can differ between zero, one and two digits?
Can you submit a PR?

**Comment by fredyb** [comment]
yes exactly

**Comment by fredyb** [comment]
What is a PR?

**Comment by kevinpapst** [comment]
A PR is a "pull request" via GitHub. Basically you do the change in a branch of your fork and then sent this change as PR to this repo. Then I can check and accept it.

If all of that is new to you and/or you are not a developer: don't bother.
