### ISSUE TITLE
Invoice template dates do not change with template language

### ISSUE THREAD

**Issue by sdillenburg** [kevinpapst/kimai2#1771]
${query.end_month} changes with the language the user has set.
The output should depend on the language specified in the invoice template. 

The same applies for the format of ${invoice.date} etc.

edit:
This behaviour is also described in the documentation: https://www.kimai.org/documentation/invoices.html#docx-templates

I would like to suggest to make this depending on the invoice (template) language and not the user language.

**Comment by kevinpapst** [comment]
duplicates #1670
