### ISSUE TITLE
Not possible to delete a project depending on list position at the bottom of page

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1772]
**Describe the bug**
When listing projects it's not possible to delete it, when its one of the last 4 on the page.
The delete option can't be displayed.

![image](https://user-images.githubusercontent.com/45666972/84063571-872ee080-a9c1-11ea-801d-31cd1342d561.png)

**Comment by kevinpapst** [comment]
Duplicates #1219 which is planned for the next release
