### ISSUE TITLE
Duplicate activities can be created

### ISSUE THREAD

**Issue by georgeowell** [kevinpapst/kimai2#1777]
**Describe the bug**
Duplicate activities can be created under the same project. This can create incredible confusion :smile: 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a activity under a project
2. Create a second activity under the same project with the same name
3. There is no warning and both activities are visible in the interface

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s] Laptop
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 77.0.1

**Additional context**
 - Kimai version 1.9 stable (Ayumi) 
 - PHP version 7.3

**Comment by kevinpapst** [comment]
Even though that might not fit your use-case: there is nothing wrong with having multiple activities with the same name (eg. for different hourly rates). I wouldn't use duplicate activities, but from my perspective there is nothing wrong with the current behavior.
If you want to provide a PR with an optional configuration setting to validate the name, I am fine to accept it.

**Comment by georgeowell** [comment]
No problem. That does make total sense to me. I'm probably not going to work on PR for that as it's not a big deal. Closing.
