### ISSUE TITLE
Snap installer

### ISSUE THREAD

**Issue by remissao** [kevinpapst/kimai2#1778]
I'm really liking the simplicity of the Snapstore. Would be great to have Kimai package available.

**Comment by tobybatch** [comment]
@kevinpapst No promises but i might be able to do this.  I'm away on Hols until early September.

Assign this to me and I'll give it a go.

**Comment by kevinpapst** [comment]
That would be fantastic @tobybatch 😄

**Comment by tobybatch** [comment]
@kevinpapst I've had a look at building a snap but I don't think it's the right solution.  

Snaps are bundled into a single container like VM and to bundle kimai I'd need to include php, apache or nginx + php-fpm and mysql making it a complex set up.  That combined with the need for managing the (trusted) host names http ports and ssl certs etc make it a quite complex project.

The next cloud snap does do all this and could be used as a design pattern but it's a _big_ project.

@remissao Have you looked at the docker solution?

    docker run -ti --rm --name kimai2 -p 8001:8001 kimai/kimai2:apache-debian-1.10.2-prod

**Comment by kevinpapst** [comment]
@tobybatch I felt the same after having a look at all the logic in the next cloud installer: too much work for a hobby/side project for now. Snaps are better suited for desktop apps, not for server applications.

**Comment by tobybatch** [comment]
Agreed, @kevinpapst close this then?

**Comment by kevinpapst** [comment]
Leave it open. I doubt that someone will soon find the time or will to work on it, but it's documented now and its just one of 200+ issues - so just a drop in the ocean (don't know if that translates well, in german we say "just a drop on a hot stone").

**Comment by kevinpapst** [comment]
No vote yet, no plans to work on that one. Closing
