### ISSUE TITLE
Change VAT %age (Question)

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#1779]
In DE there will be a reduced VAT percentage of 16% instead of 19% from July to December. I went through all the settings and the documentation but can't seem to find where to change that globally.

**Comment by kevinpapst** [comment]
You define the tax rate in each invoice template separately at `/de/invoice/template`

**Comment by VOOM108** [comment]
Danke, habe es nicht gefunden, weil ich nicht oben rechts auf den Button geklickt habe und nicht mehr wusste, dass an der Stelle noch die Einstellungen zu finden sind ;)
