### ISSUE TITLE
customizable list fields on timesheets

### ISSUE THREAD

**Issue by Jenniches** [kevinpapst/kimai2#1782]
Hey,
i´m looking for a simple solution to get the order numbers of projects into the exported timesheet.
This would be a good sorting aid to our administrative department.

**Comment by kevinpapst** [comment]
Everyone wants a different set of columns, so I cannot provide templates for every situation.

But you can create custom export templates:
https://www.kimai.org/documentation/export.html#adding-export-templates

If you need help, you can contact me for paid support:
https://www.kimai.org/store/kevinpapst-custom-plugins.html
