### ISSUE TITLE
Internal rate and rate columns are switched in PDF

### ISSUE THREAD

**Issue by mrabans** [kevinpapst/kimai2#1785]
When exporting a PDF incl. internal rates the column details of _internal rate_ and _rate_ are switched. 
Total amount is calculated correctly.

**To Reproduce**
1. Define a rate and an internal rate for a project
2. Register some time entries
3. Export a PDF incl. internal rates

**Screenshots**
![image](https://user-images.githubusercontent.com/10339528/84915896-ac0c0d80-b0bd-11ea-91da-a5ea20ee0fd6.png)

**Additional context**
 - Kimai version 1.9 prod
 - PHP version 7.4.4

**Comment by kevinpapst** [comment]
Thanks for the report. Was already fixed in #1768
