### ISSUE TITLE
Add user property to Post timesheets API

### ISSUE THREAD

**Issue by Skoetting** [kevinpapst/kimai2#1787]
At the moment, you can create timesheets with the API, but only for the user who is executing the request.
As an Admin, you can create timesheets in the web-interface also for other users.

I would like to have the ability to add timesheets for other users with the API.

**Comment by kevinpapst** [comment]
You can create timesheets for other users, but only if the user account has the permission `create_other_timesheet`.

**Comment by kevinpapst** [comment]
The API docs are maybe not showing the fields properly, thats a caching issue. Check the response in that case

**Comment by Skoetting** [comment]
Hi Kevin,
Thanks for the reply but i have the same user in the Webinterface so i thinks its not a permission problem.
If i call the APi with the data 
`'{"begin": "2020-06-19T16:06:27", "project": 1,  "activity": 1}'`
it works, but if i add the user attribute:
`'{"begin": "2020-06-19T16:06:27", "project": 1,  "activity": 1, "user": 2}'`
I got the following response:
`{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."],"children":{"begin":{},"end":{},"project":{},"activity":{},"description":{},"tags":{},"fixedRate":{},"hourlyRate":{},"exported":{}}}}`

**Comment by kevinpapst** [comment]
Then debug 😁  

https://github.com/kevinpapst/kimai2/blob/master/src/API/TimesheetController.php#L346

Many customers use the API to share data between different software systems, so I am pretty sure that it works.

**Comment by Skoetting** [comment]
@kevinpapst 
> Then debug

I will try :D Im not a PHP-Expert.
Could you please test if it works for you on your env?
