### ISSUE TITLE
Integrate custom visualization in Kimai2

### ISSUE THREAD

**Issue by skotperez** [kevinpapst/kimai2#1792]
### Some context
i write this issue because we're using Kimai2 to track time in an organization called Wikitoki, in Basque Country, Spain. Maybe you remember us: one [Wikitoki](https://wikitoki.org) member has contributed to kimai2 with the Basque (euskera) translation.

First of all, thank you for this piece of software. It is really nice. It suits almost all our needs. We're evaluating how to implement some additional functionalities. We don't know which options will be the best for us, knowing that we don't know Symfony enough.

### Integrate custom visualization in Kimai2

To integrate in kimai2 some visualizations produced with D3 and Vega of the data compiled in our kimai instance.

We have explored two ways to integrate the visualizations with Kimai2:

1. A new interface produced with JS that communicate with kimai2 using its Rest API. It produces the visualizations and allows basic modifications in kimai2 data (add or edit a timesheet). We've used this "Calling the API with JavaScript" code from kimai2 documentation (https://www.kimai.org/documentation/rest-api.html#authentication). This solution works but we prefer not to develop a new interface for kimai2.
We'd also prefer to have just one interface: with these solutions we'll have two of them: kimai2 dashboard to register and config users and the new JS interface to edit and visualize data.
2. A modification of a Kimai2 widget. We have injected some JS code in kimai2 dashboard using a widget. We're blocked here because we don't know how to call the api inside Kimai2 or to query the database to get the data we need to produce the graphs.

Could you give us some cluesa bout how to do it? Which part of Symfony docs to read... Which kimai2 functions to use… Thanks in advance for your help.

Or maybe another way to achieve this comes to your mind. Don't hesitate to share with us!

**Comment by kevinpapst** [comment]
Depends on what you want to achieve. 

You can either call the database directly like this:
https://github.com/kevinpapst/kimai2/blob/master/src/Widget/Type/DailyWorkingTimeChart.php
https://github.com/kevinpapst/kimai2/blob/master/src/Widget/Type/UserTeamProjects.php

Or you call the API via JS (example not tested, but you should get the idea):

```
        document.addEventListener('kimai.initialized', function(event) {
            var API = event.detail.kimai.getPlugin('api');
             API.get('{{ path('get_timesheets') }}?size=1000', {}, function(result) {
             for (var record of result) {
                   var color = record.activity.color;
              };
         });
```

**Comment by skotperez** [comment]
Thanks for your answer,

to call the API, either via JS or PHP, it is necessary to authenticate the user, isn't it? And i think it is a good idea to protect our  data, so this is ok for us. How would you pass the credentials via JS in a non-interactive authentication?

**Comment by kevinpapst** [comment]
Please read the documentation, it is explained there.
I would recommend to write a Kimai plugin that adds a new page (instead of a dashboard widget.
No need for authentication then, Kimai already does it for you.
