### ISSUE TITLE
Create an user log to track changes in user features

### ISSUE THREAD

**Issue by skotperez** [kevinpapst/kimai2#1793]
### Some context

i write this issue because we're using Kimai2 to track time in an organization called Wikitoki, in Basque Country, Spain. Maybe you remember us: one [Wikitoki](https://wikitoki.org) member has contributed to kimai2 with the Basque (euskera) translation.

First of all, thank you for this piece of software. It is really nice. It suits almost all our needs. We're evaluating how to implement some additional functionalities. We don't know which options will be the best for us, knowing that we don't know Symfony enough.

### Create an user log to track changes in user features

A kind of users' log to track and store when a user has been active or not, to which groups the user belongs and to which ones he has belonged. We need this data to calculate average dedication to the organization per month, year...

We’ve explored in two different ways:

1. Use another database to store this data and insert a form in kimai2 dashboard to interact with it.
2. Extend the user class in kimai2.

Would you be able to provide some clues about how to do it? Which part of symfony docs to read... Which kimai2 functions to use...

There might be another way to achieve this. Don't hesitate to share with us!

**Comment by kevinpapst** [comment]
Hi @skotperez,
I am not sure what you want to achieve, but you can have a look at the AuditTrail bundle.
It tracks several changes, but not everything that is happening in Kimai.

**Comment by skotperez** [comment]
I'll have a look to this bundle. Thanks for the clue!

**Comment by kevinpapst** [comment]
I close here as this feature will not be added to the core of Kimai.
If you have specific questions about implementations I can try to help, but asking so generic questions is nothing that can easily be answered.
I would have a look at: symfony events (kimai sends events on several actions like timesheet updates ...) and doctrine lifecycle  callbacks, as you can literally "read" any database change.
