### ISSUE TITLE
Give modals static backdrop

### ISSUE THREAD

**Issue by couteau** [kevinpapst/kimai2#1794]
**Is your feature request related to a problem? Please describe.**
There have been so many times when I've accidentally clicked outside the modal after spending a ton of time typing a description of a time entry, which closes the modal and causes all of that work to be lost. 

**Describe the solution you'd like**
Add data-backdrop="static" to twig templates for modals (templates/default/_form_modal.html.twig and possibly also templates/embeds/modal.html.twig)

**Describe alternatives you've considered**
Possible alternatives would be a confirmation dialog if you close a modal (by clicking close or clicking outside the modal) after making changes. That would require a nested/double modal, which might be more complicated depending how it's implemented.

**Additional context**
I track a lot of information in long time entries. I have no idea if others use Kimai this way, but for me, losing a lot of work because of a careless mouse click is very frustrating.

**Comment by kevinpapst** [comment]
I tend to prefer the second solution, which is more complicated to develop but less intrusive.

Adding a Javascript that tracks all form fields inside a modal: and then, if one was changed and the modal should be closed, then a confirmation dialog should show up.

The JS changes can be done inside here: https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiAjaxModalForm.js

**Comment by kevinpapst** [comment]
I have added logic to detect a dirty form and prevent closing by accidentaly clicking the modals "outside", please see #2264

You can test it at https://demo-branch.kimai.org (eg. with `susan_super` and `kitten`).
