### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted 

### ISSUE THREAD

**Issue by Vivango** [kevinpapst/kimai2#1799]
**Describe the bug**
When installing kimai in developer mode with php bin/console kimai:reset-dev in a windows 10 environment, then I get the following error when loading App\DataFixtures\TimesheetFixtures

"Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in \kimai\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php on line 2748

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in \kimai\vendor\symfony\error-handler\Error\OutOfMemoryError.php on line 1"

I did put php memory limit on -1

I did make full control for the files in the directory

In /var/log/dev.log it shows all the sql queries and deprecation warnings but not the error which I reported here.

I did understand that composer might give issues with \ /, but not sure if that is what was caused here.

**To Reproduce**
php bin/console kimai:reset-dev  on windows with php7.3.12

**Logfile**
```
"Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in \kimai\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php on line 2748

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in \kimai\vendor\symfony\error-handler\Error\OutOfMemoryError.php on line 1"
```

**Desktop/Smartphone**
 - windows 10 64bit

**Additional context**
 - Kimai version
1.9
 - PHP version
7.3.12

**Comment by kevinpapst** [comment]
are you sure you set the memory_limit also for php cli or maybe only for the one used in your webserver?

**Comment by kevinpapst** [comment]
You can find the used ini file and the setting with `php -i`

**Comment by Vivango** [comment]
Looks like somehow my memory_limit wasn't saved in php.ini. Thank you for fast reply!
