### ISSUE TITLE
Dashboard showing 'wrong' data at turn of month

### ISSUE THREAD

**Issue by areanod** [kevinpapst/kimai2#1801]
**Describe the bug**
In the dashboard section "My working hours" the data field for "working hours this month" shows the amount of hours of the previous month when a week consists of both the end of a month and the beginning of the next one.
I realized this today (July, 3rd) when I had more time in this month than in this week which shouldn't be possible in the first week of the month.

**Screenshots**
![screenshot03072020](https://user-images.githubusercontent.com/4991855/86493457-eccc7d80-bd71-11ea-93f5-7b0240b9accf.png)

**Additional context**
 - Kimai version 2 (1.9 stable)
 - PHP version (7.3)

While writing this post I realized that this behavior might be by design. Dunno if I'm the only one who was confused by this but maybe the description of this field could by changed to something more dynamic, e.g from "working hours this month" to "working hours in $month".
Another possibility to clarify which months data is being displayed in that field could be something like an indicator, for example (pardon my paintbrush ;)):
![example](https://user-images.githubusercontent.com/4991855/86493758-09b58080-bd73-11ea-83a9-8b83953e7c04.png)

**Comment by kevinpapst** [comment]
No, you are not the only one 😁 Actually I am working at it right now. 
Yes, it is by design, so not a bug (as in wrong behavior) but more of a design flaw.
I am currently trying to incorporate the day/week/month into the translation, but that is rather hard to read when you scan over the text. 

Highlighting some areas is an interesting idea, but way too complex.

Probably its better to to use the end day to calculate the month/year, but then: what if the friday is the first day of the month? 
That would be wrong somehow as well...

**Comment by areanod** [comment]
Thx for your quick reply, I really appreciate this!

> Probably its better to to use the end day to calculate the month/year, but then: what if the friday is the first day of the month?
> That would be wrong somehow as well...

I get what you mean but I think that showing the current info makes the most sense on a dashboard. You could make this an option for a user's profile, like "show data of previous month if less than 1/2/3/4/5/6 days of week are from the next month"

I have no clue how much work that is but if you want to give the user the possibility to access statistical data like hours worked in XX month I think it would good to give the user an additonal section, called "Statistics".

**Comment by kevinpapst** [comment]
A reporting section is long outstanding, I know. It will come, no need to open a request for that (multiple are existing for that already).

So I changed the labels like this:
<img width="1011" alt="Bildschirmfoto 2020-07-03 um 23 26 02" src="https://user-images.githubusercontent.com/533162/86498081-93217e80-bd84-11ea-8e6e-12ee8c621585.png">

What do you think?

**Comment by areanod** [comment]
> A reporting section is long outstanding, I know. It will come, no need to open a request for that (multiple are existing for that already).

I'm looking forward to it!

> What do you think?
i think you are working far more documented hours than me per year ;)
As for the caption: I like it, thank you so much!

**Comment by kevinpapst** [comment]
LOL, thats just my development demo. I wish that would be paid hours...
