### ISSUE TITLE
error after installing task management plugin

### ISSUE THREAD

**Issue by psychomiller** [kevinpapst/kimai2#1804]
Today I have installed kimai2 and have to say, that i love it!
But I have faced a problem:
After buying the task management plugin if have installed it, following the given instructions.
In the chapter plugins, task management is showing up.
But I am not able to reach the dashboard anymore.
The error-message is:

> "Etwas läuft falsch. Ein kritischer Fehler ist aufgetreten. Möglicherweise haben Sie einen Software Fehler gefunden, kontaktieren Sie bitte ihren Administrator wenn der Fehler bestehen bleibt."

the output of prod.log is:

> [2020-07-04 18:06:05] request.INFO: Matched route "dashboard". {"route":"dashboard","route_parameter$
> [2020-07-04 18:06:05] security.DEBUG: Read existing security token from the session. {"key":"_securi$
> [2020-07-04 18:06:05] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\$
> [2020-07-04 18:06:05] security.DEBUG: Checking for guard authentication credentials. {"firewall_key"$
> [2020-07-04 18:06:05] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secu$
> [2020-07-04 18:06:05] security.DEBUG: Guard authenticator does not support the request. {"firewall_k$
> [2020-07-04 18:06:05] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exceptio$
> [2020-07-04 18:06:05] security.DEBUG: Stored the security token in the session. {"key":"_security_se$

I have checked with various browsers after deleting the cache.
Does anyone have a suggestion, how to go further?
Thanks in advance!

**Comment by kevinpapst** [comment]
This issue tracker is only about the free version of Kimai.

Please send me an email with your gumroad recipe, then I will add you to the task management repository and we can discuss the issue there. See the blue box here: https://www.kimai.org/store/task-management-bundle.html

And please include the full log, I need to see the complete line that starts with `[2020-07-04 18:06:05] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exceptio`
