### ISSUE TITLE
Project > timesheet is not filtered

### ISSUE THREAD

**Issue by blaue-mango** [kevinpapst/kimai2#1806]
**Describe the bug**
projects > timesheet > doesn't filter the times to the project: I want to see the timesheet of one project. For that I click on "projects" and then in the list I click on the right Arrow to open the submenu of that project. There I click on "timesheet" that should open a list of times, filtered by the customer and the project. But the list is not filtered. Instead the search field has a red border and by clicking on that there is a message (in german): "Dieses Formular sollte keine zusätzlichen Felder enthalten.".

**To Reproduce**
1. Go to 'Projekte'
2. Click on right arrow of a project
3. Click on "Stundenzettel"
4. Instead of seeing the times of that project I see all times (unfiltered)

**Additional context**
 - Kimai version 1.9 stable (Ayumi)
 - PHP version 7.3

**Comment by kevinpapst** [comment]
thanks, will be fixed with the next version
