### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by imadmoussa1** [kevinpapst/kimai2#1811]
Hello,
I had been testing kimai with different languages,
I add new translations in translations/*.en.xlf but not reloaded in webpage.
Do I need to send PR for the changes ? or these changes can take effects locally while translating the text and how?

Thank you

**Comment by kevinpapst** [comment]
If you are running in `APP_ENV=dev` (see your `.env` file) then changed translations will be reloaded automatically.
If you are running in `APP_ENV=prod` or you add completely new `.xlf` files, you have to run `bin/console kimai:reload -n` to clear and reload the cache. Then your changed translations should be visible after page reload.

**Comment by kevinpapst** [comment]
And yes, please create a PR to share your changes with the community 😄

**Comment by imadmoussa1** [comment]
@kevinpapst Thank You.
The changes appeared on the webpages.
Sure when my Arabic translation is valuable and accurate I will send you PR request.

**Comment by kevinpapst** [comment]
Awesome 🚀 then I will close this issue and you come back with your changes later on.
