### ISSUE TITLE
Consistent formatting of invoice variables

### ISSUE THREAD

**Issue by JayAige** [kevinpapst/kimai2#1812]
Hello together,

I was asked by a customer to switch from € to the ISO 4217 code EUR in my invoices. Therefore I changed the variables from ${entry.rate) to ${entry.rate_nc} ${invoice.currency} in my invoice template. Unfortunately the ${entry.rate} and ${entry.rate_nc} are formatted differently. If the rate is without decimals, they will be omitted in the _nc case. For example the rate is 100,00 €. The result in the invoice is:
${entry.rate}: 100,00 €
${entry.rate_nc} ${invoice.currency}: 100 EUR

I would suggest to use a consistent formatting of the variables. In this case I'd expect 100,00 for ${entry.rate_nc}.
Other affected variables I tested: ${entry.total_nc} and ${invoice.tax_nc}

Thank you very much. (I'm running Kimai 1.9)

**Comment by kevinpapst** [comment]
Thanks for the detailed report @JayAige 👍 
Actually all money values that did not have a currency were formatted different in Kimai.  

This issue will be fixed with #1814
