### ISSUE TITLE
Improve UI of timesheet entries

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#1813]
**Is your feature request related to a problem? Please describe.**
I like to have a clear overview and easy intuitive inputs. For the employees, the most important part of a time tracking system is it's easiness to use (e.g. in comparison to a paper time tracking sheet), so this feature request tries to level up the user experience.

I believe Kimai would gain a lot of added value if the entry of times could be added in an easier way while having a weekly overview.

**Describe the solution you'd like**
I imagine a view like this:

![image](https://user-images.githubusercontent.com/55000172/87023338-e0b04800-c1d7-11ea-89a3-19ff335ded36.png)

It can nicely be combined with #1676  to also track vacation days in a clear way.

I imagine to show by standard 7 rows or, if >= 7 projects are actively used n+1 rows
 
Clicking on an empty rows would lead to the existing standard pop up to track times, while i think that clicking on a weekday column cell in an existing project column should be a very minimalistic input of the duration (depending on which mode) and description of the task

**Example**
![image](https://user-images.githubusercontent.com/55000172/87024947-0dfdf580-c1da-11ea-9930-c77be3bce7f3.png)
![image](https://user-images.githubusercontent.com/55000172/87024994-16563080-c1da-11ea-9861-de4d70bc9617.png)

**Additional Comments**
I also see how this brings up the topic of over hours.
I guess the best way to combine this, vacation days and overhours would be to add contract details to the user (regular weekly working time, paid vacation days)

**Comment by kevinpapst** [comment]
Thanks for the great input! 👍 

This looks like a lot of work (on Kimai side), but when the time comes I will get back here. I really like the idea!

**Comment by kevinpapst** [comment]
Closing here as this is a duplicate. I moved your comment to https://github.com/kevinpapst/kimai2/issues/312 because of the great details it provides.
If you could upvote the feature with 👍 on the initial post in #312 it gets higher visibility
