### ISSUE TITLE
How to subscribe to Events? 

### ISSUE THREAD

**Issue by thelatch** [kevinpapst/kimai2#1816]
**Is your feature request related to a problem? Please describe.**
I know that this is not really an issue as such. However, I would like to send the events from Kimai to Zapier as a webhook, but I can't find a way to do that in the instructions. Is this already possible? If not, this is my Feature Request :) 

**Describe the solution you'd like**
It would be great to store webhooks for different events, so that you can start further processes with Zapier

**Describe alternatives you've considered**
//

**Additional context**

**Comment by kevinpapst** [comment]
The [DemoBundle](https://github.com/Keleo/DemoBundle) has examples for [EventSubscribers](https://github.com/Keleo/DemoBundle/tree/master/EventSubscriber).

Pick the [Event that you want to liste to](https://github.com/kevinpapst/kimai2/tree/master/src/Event), for example when a [timesheet was created](https://github.com/kevinpapst/kimai2/blob/master/src/Event/TimesheetCreatePostEvent.php) and listen to it.

For more information read the [Symfony docs about event dispatching](https://symfony.com/doc/current/event_dispatcher.html).

**Comment by thelatch** [comment]
You're awesome! Thanks Kevin for the project and the fast support!
