### ISSUE TITLE
Only question: Export of all projects even if they are empty

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1819]
How it's possible to export a list of all projects, even if there are no time entries made (means empty projects)?

Same question for users!
Users because a list for DSGVO reasons (Documentation) is needed.

**Comment by kevinpapst** [comment]
Exporting a list of users in on my agenda

**Comment by HeinzWuert** [comment]
what about projects? (list of all)

**Comment by kevinpapst** [comment]
will be available with 1.10 - the list of all currently filtered projects can be exported from the project view to an excel file

will post an update, once it is available on the demo

**Comment by kevinpapst** [comment]
@HeinzWuert can now be tested at https://demo-branch.kimai.org/ - more infos at via #1831

**Comment by HeinzWuert** [comment]
works, thumbs up!
What about custom fields? They are not supported?

**Comment by kevinpapst** [comment]
Did you try it?

**Comment by HeinzWuert** [comment]
Works! Was in Excel out of screen.

Both thumbs up!

 

Von: Kevin Papst <notifications@github.com> 
Gesendet: Montag, 20. Juli 2020 17:43
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: HeinzWuert <firstdata@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] Only question: Export of all projects even if they are empty (#1819)

 

Did you try it?
