### ISSUE TITLE
Selectable Language for Invoices

### ISSUE THREAD

**Issue by dotKuro** [kevinpapst/kimai2#1820]
**Is your feature request related to a problem? Please describe.**
We work with companies of different languages. The invoice feature of kimai does actually support different languages, which is great, but it uses the language of the user that is creating the invoice. So to get a different language you have to change the settings of the user interface for the user.

**Describe the solution you'd like**
An easy solution would be to add a pick list in the invoice template specifying the language.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by kevinpapst** [comment]
Already fixed in #1814 ... no, it was not an easy solution actually 😁

**Comment by kevinpapst** [comment]
You could try the demo (which is already running the code) and let me know if it works now as expected
