### ISSUE TITLE
permission "view_other_timesheet" doesn't affect user-role

### ISSUE THREAD

**Issue by iko94** [kevinpapst/kimai2#1821]
Issue: activating "view_other_timesheet" for the role "user" has no effect on users ability to see other timesheets from other users of the same department

for reproduction:
1. Log in as system administrator
2. Click on Users and then on permission icon 
3. Activate under the column "User" the permission "view_other_timesheet"
4. Log out 
5. Log in as user and click on timesheets. 
6. After clicking on timesheets, there is only the own timesheet avaiable although user has permission to see other timesheets from other users.

**Comment by kevinpapst** [comment]
This permission ONLY gives access to the timesheet administration.
If you use teams then team permissions will apply.
As this was discussed many times already, I am not going to repeat all arguments, please search through the issues (eg #1292).
