### ISSUE TITLE
reporting feature: summary row in first line; last column always visible; fixed width of first column

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1824]
First of all: the new reporting is great. 

Just some minor issues for a better overview at first glance: 
- show summary row as first line (if there are many entries it takes a while to scroll down to the summary row)
- always show the last column (in order to show it otherwise; you need two steps; first to scroll down in order to show the scrollbar for vertical scrolling (see issue above) and second then scroll vertically till the very end)
- the wide of the first column should not be dictated by the longest entry (otherwise, on small screens the report has only one column and in order to see the other columns, you need to exercise the two steps above); maybe there could be a line break at a defined width in case of a long entry 

my report looks as follows:
![screenshot](https://user-images.githubusercontent.com/51003649/87561795-71e25b80-c6bd-11ea-99c9-2033e0949316.png)

.

**Comment by kevinpapst** [comment]
Hahaha, yep that looks ridiculous.  I can't believe that you have so long activities/project names.
But great that you test it before the release, so we get a chance to smooth out some points - thanks 👍 

I am testing on a 27'' screen with a touchpad & vertical scrolling gestures, so it feels quite natural to use it like that.
Calculating the values upfront is more complicated, thats why the summary columns are below the table / at the end of the row. I need to test that.

The mobile/responsive view is even more challenging in that combination.
But limiting the first column is a good idea, so I have to test as well how that can be done. 
Any input & help is appreciated, as these frontend tasks are definitely not in my "best skills list" ...

**Comment by kevinpapst** [comment]
Summaries are now moved to the second column.

If you can experiment with the Custom CSSS plugin and rules for the report tables, that would be great.
Every report box has a unique class, so you can target them with something like:
```
div.user-month-reporting-box table tr td:first-child { width: 10%; }
```

**Comment by BeckeBauer** [comment]
- summary at second column is great
- tried your css suggestion (with the plugin) but it causes no change of the size of the first column (monthly view of user) 
- tried div.user-week-reporting-box table tr td:first-child { width: 10%; } but also no change of the size of the first column (weekly view of a user)
still, the size of the longest entry of the first column is used; any help from css experts is appreciated...

**Comment by kevinpapst** [comment]
Try
```
div.user-month-reporting-box table tr td:first-child { width: 200px; white-space:normal; }
```
The class `div.user-month-reporting-box` is different for each report

**Comment by BeckeBauer** [comment]
That did the trick also for div.user-week-reporting-box (I am happy with width: 50px though)
Thanks a lot...
