### ISSUE TITLE
reporting feature: selection of customer

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1825]
Would it be possible to select "customers" instead of "projects" or in addition to "projects" at it is currently shown in the reporting feature?

**Comment by HeinzWuert** [comment]
For me the better solution would be the filter function to select customer and/or project, based on the user indexing.

**Comment by kevinpapst** [comment]
One improvement after another 😁

**Comment by kevinpapst** [comment]
Is the new "project overview report" what this ticket is about?

**Comment by HeinzWuert** [comment]
not exactly, but should match 90% of user wishes.
I'd like to  say: To be closed.
There are more important FR than this one.
