### ISSUE TITLE
New Project > Shoudn't preselect the first customer

### ISSUE THREAD

**Issue by blaue-mango** [kevinpapst/kimai2#1828]
When creating a new project there is the (alphabetically) first customer prefilled within the select.
It would be better if the select was empty and has to be set by the user manually.
Otherwise it can happen that a project is created an the wrong customer is assigned.

**Comment by kevinpapst** [comment]
Thanks for posting the issue, totally true.

A customer should only be pre-selected if the create action was triggered from a customer action (list dropdown/detail page)
