### ISSUE TITLE
Problem with access - error 404

### ISSUE THREAD

**Issue by psycowby** [kevinpapst/kimai2#1832]
Hello there, i have a problem. I am still in "testing" mode with my colleagues so i am trying to have it on more user-friendly way than url:port address is (subdomain or vhost). Today i made some tests with name-based url instead of port-based and i completely lost connection to Kimai2. I dont understand why, but now when i am trying to connect over local ip i am getting 404 error, even on my public-static ip. I know, is not about Kimai2 probably, but is there possibility to check some basic parameters if is that correct? I am running on Synology. Of course i dont have any backup. Is possible to reinstall Kimai without touching the database? I am sorry for stupid questions. Thanks for your answers. Regards, Martin

**Comment by kevinpapst** [comment]
Hi Martin,

> Is possible to reinstall Kimai without touching the database?

Yes. You can reinstall Kimai completely. Database won't be touched if Kimai finds an existing one.
Still, dumping the database before never hurts.

Besides from that, read the Synology docs: https://www.kimai.org/documentation/synology.html

**Comment by psycowby** [comment]
Woah, such a fast response. Thanks Kevin, tomorrow i will try the reinstallation. One question - during my tests ive changed version of PHP to 7.0 by mistake. Do you think that this could be a problem? Regards, Martin.

**Comment by kevinpapst** [comment]
Kimai requires minimum 7.2.x - it will definitely not work with 7.0

**Comment by psycowby** [comment]
Hi guys, i found the problem but i dont know how to fix. In the installation manual for Synology is written:

> Now switch to the console and find the directory where the config needs to be stored.

Either use ls -la /etc/nginx/conf.d/ and check which subdirectories exist or better: have a look at the file /etc/nginx/app.d/server.webstation-vhost.conf where all virtual hosts are listed.

Watch out for the line that starts with include:

server {

    listen      7777 ssl default_server;
    listen      [::]:7777 ssl default_server;

    server_name _;

    ...

    root    "/volume1/web/kimai2/public";

    ...

    include /usr/local/etc/nginx/conf.d/1d16b269-904e-41c9-bd23-cbdf761e305e/user.conf*;

}
Ok, we found the directory /usr/local/etc/nginx/conf.d/1d16b269-904e-41c9-bd23-cbdf761e305e/, go ahead and edit a new config file to store the webserver configuration for Kimai:

vim /usr/local/etc/nginx/conf.d/1d16b269-904e-41c9-bd23-cbdf761e305e/user.conf-kimai2
Add the following lines to it:

    index index.php;

    access_log off;
    log_not_found off;

    location ~ /\.ht {
        deny all;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi.conf;
        fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/..:/tmp/";
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

> 

What i did was installation of SSL certificate for my own domain and i put on Synology also this certificate for vHost on port 7777. Now when i am looking at files you described in the quote above, i cant find the folder with conf file. Target file is not in /etc/nginx/app.d folder but /usr/syno/etc/security-profile/tls-profile/config folder. I dont know what to do :/. Please help. Regards, Martin

**Comment by psycowby** [comment]
I did all the setup like is described in manual and now i am getting error 502. Bah. :/

**Comment by psycowby** [comment]
Bah, after reading installation steps carefully i found that problem and its fixed. Kimai2 now running properly. Problem happen when i switched PHP version by mistake to 7.0, Synology made new vHost number and was not associated with user.conf file. Sorry for disturbing. Lock pls and wish you nice day. Martin.

**Comment by kevinpapst** [comment]
Thanks for your feedback and sharing your solution!
