### ISSUE TITLE
Work Break

### ISSUE THREAD

**Issue by Vivango** [kevinpapst/kimai2#1833]
**Is your feature request related to a problem? Please describe.**
The users are used to tell if they took a work break which is always 30 minutes. It is not clear how this could be integrated in kimai. Of course a user could fill in 9-12 12.30-16 having a work break between 12 and 12.30.

**Describe the solution you'd like**
A checkbox where a user could add if it took a work break during the inserted work period, which by default counts as 30 minutes

**Describe alternatives you've considered**
Maybe there is already a way to solve this in kimai, I would love to know how.

**Additional context**

**Comment by kevinpapst** [comment]
Searching for "pause" or "break" brings up many issues.
Why do you think we need just another one instead of feeding one of the other issues with your input?

**Comment by Vivango** [comment]
People are being paid by the hour, knowing if there was a working break is good to know. What do you advice to solve this?

**Comment by Vivango** [comment]
What is a duplicate here?

**Comment by kevinpapst** [comment]
You should answer my questions first before asking new ones. 
Did you check the existing issues? 
If there is one regarding "break times" then you should bring in your ideas there, instead of posting just another one.

**Comment by kevinpapst** [comment]
What exactly should happen if the checkbox is clicked?
I don't get it. Do you want that the calculated duration for that record is reduced by 30 minutes?
Do you want that the record is automatically split into two records?

**Comment by Vivango** [comment]
This is the case.

A cleaner has automatically a 30 minutes break if it has worked >= X minutes.
When >=X minutes has been filled the work-break checkbox should be checked so administration knows the cleaner had a break and 30 minutes is indeed reduced from the total time. The cleaner has the option to uncheck the box when the cleaner did not take the cleaning break although the cleaner worked >= X minutes.

**Comment by kevinpapst** [comment]
Closing, add any ideas to #963
