### ISSUE TITLE
Reporting function

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1838]
The reporting function in the current beta is very helpful. 
It would be even better if users or projects could be represented in this way.
Alternatively, the user presentation can be used to filter the presentation with focus on a single customer or a single project.

**Comment by kevinpapst** [comment]
> It would be even better if users or projects could be represented in this way.

Can you clarify that one please, not sure if I understand it properly.

**Comment by kevinpapst** [comment]
Please open a new issue with a detailed description: how it should work/look like, what should be displayed
