### ISSUE TITLE
Order number: prevent duplicates; Syntax of

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1844]
1. Order numbers are unique. Preventing duplicates would be useful.
2. Every user has his own syntax. Is it possible to define the input f.e. in the form AAaa99# for letters, numbers a.s.o.?

**Comment by kevinpapst** [comment]
1. But you could create two projects from one order. Actually I do know customers who do it exactly like this. So at least a checkbox is needed to trigger the "uniqueness check" behavior.
2. You mean for an optional check how the order number should be formatted?

**Comment by HeinzWuert** [comment]
1) two projects from one order no. will never happen, but with a checkbox this behaviour is ok!
2) yes, like u did with invoice name. Common are MM month, DD day, YY or YYYY year, 9 for numbers A letter etc. U know what I mean ;-)

**Comment by HeinzWuert** [comment]
push :-)

**Comment by kevinpapst** [comment]
Very specific feature request for one company - I don't see that in the core. Closing.
