### ISSUE TITLE
Option for enforcement of explicit team assignment

### ISSUE THREAD

**Issue by kbancerz** [kevinpapst/kimai2#1845]
**Is your feature request related to a problem? Please describe.**
At the moment Kimai uses the following logic in regards to customer/project accessibility (or at least this is how I personally understand it) - if there is at least one team, that has this customer/project assigned, then it will be visible only to members of such team/teams. Otherwise - meaning no team has this customer/project assigned - it is available to everyone. 

That means, that if by accident or omission a team was not created for a customer/project it will be visible to everyone (for example when entering a new timesheet entry). This is a potential information disclosure.

**Describe the solution you'd like**
It's up for a debate, but I think that maybe a system-wide flag (disabled by default, to retain current logic) would be a solution. With this flag activated customers/projects would be available only through explicit team assignment. Missing team assignment would result in no way to access the data, other than having admin authorization in the system.

**Describe alternatives you've considered**
n/a

**Additional context**
A user with only one team assigned:
![image](https://user-images.githubusercontent.com/9020152/88534288-0cb92f00-d008-11ea-987f-90745da233b8.png)

Sees two customers, because one of them doesn't have a team, that it is assigned to:
![image](https://user-images.githubusercontent.com/9020152/88534209-d976a000-d007-11ea-8a9f-9f7e6f6d4275.png)

It would be good to have an optional fail-safe for such a situation, that would prevent accidental information disclosure.

**Comment by kevinpapst** [comment]
A flag is no option due to the way the permissions are handled.
Actually you have to do just one click after creating the customer on "create default team", but I understand this might not be the best option for all cases. 

But I could imagine adding a new configuration: "Default team for new Customer" which gets assigned to every new customer (and this config could exist for every object type: customer, project, activity)

**Comment by kbancerz** [comment]
I agree - an option to have a default team created automatically for new customers sounds like a much better solution.

**Comment by HeinzWuert** [comment]
If so, please like it is now: project name = default team name

**Comment by kevinpapst** [comment]
Sorry, I wasn't clear what I meant and you got it wrong.. but thats another idea.
My proposal is three new configuration:
- Default team for new customers (a select box with all existing teams)
- Default team for new projects (a select box with all existing teams)
- Default team for new activities (a select box with all existing teams)

Then you can choose to configure an already existing team which will get assigned to any new entity.

Your idea about automatically creating a new team is interesting as well, but could lead to a lot of teams which are not used. 
Without giving it a lot of thought I am against it, as many users have projects with the same name (for example: 90% of all my clients have a project called "Kimai") and then creating these new teams would fail, as they are called like the project. And team names are unique. 

What do you think?

**Comment by HeinzWuert** [comment]
**For me** it makes no sense to add teams to customers oder activities. The main factor is always the project (and I have round about 150 teams!)
Now, when creating a project, a simple click on teams+ is enough to create a new team with the project name.
What I don:t want are new created projects without a team. But regarding the wishes of all users worldwide it's nearly impossible to get a match for everyone.

**Comment by kevinpapst** [comment]
The configs would be optional, so you can choose if a new object gets a default team assigned. 

Then we could add several configs (here as example for project):
- Create new default team for new project (optional checkbox, if ticked a new team is automatically created upon creating a project and assigned to it)
- Assign teams to new project (select box, if a team is chosen it will be assigned to every new project)

And I will not remove the "create default team" button 😁

**Comment by kevinpapst** [comment]
The next major version #2902 will have a team-multi-selection dropdown in the "create" dialog:
<img width="686" alt="Bildschirmfoto 2022-08-02 um 16 21 10" src="https://user-images.githubusercontent.com/533162/182397729-369a2e85-3f40-4728-bcad-093d040aa52e.png">
