### ISSUE TITLE
Reset Password API for User

### ISSUE THREAD

**Issue by groovyrb** [kevinpapst/kimai2#1847]
@kevinpapst  Hello I am searching for reset password api for user, I have search all the code and google but not able to create rest password api for user, It is working fine from web Application but I need to create a Rest API for user to reset password from mobile.
So please can you help me out, I dont have any plateform so I am writting here.

**Comment by BrookeDot** [comment]
Maybe I'm missing something, but I think you can [re]set the API password from the "API" area of the user profile.
<img width="1110" alt="Screen Shot 2020-07-27 at 11 13 16 AM" src="https://user-images.githubusercontent.com/150348/88576395-39fee080-cffa-11ea-9838-7c63f9087fe4.png">

**Comment by groovyrb** [comment]
Yes But I have made a Mobile app and I want user to do a request from there when they click on forgot password and an email will be sent to user email.

**Comment by kevinpapst** [comment]
I don't think this is a good method to add to the API. 

You could:
- Open a web view for the reset password url 
- Or if you really wanna automate it, load the reset password page and submit the form programmatically
  - If there is no good framework for processing the form, scrape the HTML for the csrf token and add that to the post

**Comment by groovyrb** [comment]
Thanks But I need something userfriendly to do so, I have found a solution by sending data to http://domain.com/public/en/resetting/send-email with post method key username:emailid it works for me.
thanks for the quick respose.

**Comment by kevinpapst** [comment]
> Thanks But ...

Thats exactly what I said 😁
