### ISSUE TITLE
Logbook for Timesheet

### ISSUE THREAD

**Issue by gises** [kevinpapst/kimai2#1851]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to integrate a logbook. 
I would see the following requirement:
In the customer base, the one-way trip from the office to the customer location is stored.
For the project (may have a different location) the one-way route from the office to the project location is stored.
During time recording, the kilometers are displayed and the user can select whether it is a single trip or a return trip using a selection field. In case of a return trip the kilometres are doubled. If the project has no kilometres, the kilometres stored for the customer are used. Sometimes kilometers can be charged, this should also be possible.
Depending on the authorisation, the kilometres can be edited during time recording.

I have bought the plugin Customer fields for this purpose, but I can not implement the desired requirement. 

**Describe alternatives you've considered**

**Additional context**

**Comment by kevinpapst** [comment]
Hi @gises 
that is a very complex requirement and nothing that fits into the core of Kimai. 
Someone would have to develop it in a plugin.

I have multiple customers using the Custom Fields plugin to track kilometers and then use a custom invoice template to further work with them. But not in the way you described it, which has multiple dynamic dependencies. 

But that is a discussion for the Custom Fields repository. Please drop me an email (see marketplace page for more infos) so I can give you access to that repository.

I am closing this issue as I do not consider to add it to the Kimai core.

**Comment by gises** [comment]
Hi Kevin 

 

Please grant access to the Custom fields plugin.

 

Thanks 

Best Regards

Michael

 

Von: Kevin Papst <notifications@github.com>
Antworten an: kevinpapst/kimai2 <reply@reply.github.com>
Datum: Samstag, 1. August 2020 um 23:17
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: gises <giesingerm@gmail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] Logbook for Timesheet (#1851)

 

Hi @gises
that is a very complex requirement and nothing that fits into the core of Kimai.
Someone would have to develop it in a plugin.

I have multiple customers using the Custom Fields plugin to track kilometers and then use a custom invoice template to further work with them. But not in the way you described it, which has multiple dynamic dependencies.

But that is a discussion for the Custom Fields repository. Please drop me an email (see marketplace page for more infos) so I can give you access to that repository.

I am closing this issue as I do not consider to add it to the Kimai core.
