### ISSUE TITLE
Missing /api endpoint

### ISSUE THREAD

**Issue by l00ptr** [kevinpapst/kimai2#1857]
**Describe the bug**
Missing API endpoint - /api and /api/doc don't exist - the doc doesn't give enought information about how to enable / use the  API 

**To Reproduce**
1. Install kimai on Debian 10
2. go to https://example.com/api/doc
3. 404 error

for your information here are the log of my install - on a freshly installed Debian 10
```
apt install php-gd php-mbstring php-intl php-xsl
cd /var/www/
git clone  https://github.com/kevinpapst/kimai2.git 
cd kimai2
git checkout 1.9
chown -R www-data:www-data kimai2
sudo -su www-data bin/console kimai:install -n
```

**Logfile**
No info into the log

**Screenshots**
Useless in our case

**Desktop/Smartphone**
Both

**Additional context**
 - the latest one
 - PHP 7.3

**Comment by kevinpapst** [comment]
Does Kimai work in general? Sounds as if your webserver config is wrong.

See https://demo.kimai.org/api/doc

**Comment by kevinpapst** [comment]
BTW: 
- you are using SQLite if you don configure .env
- you can use master
- https://www.kimai.org/documentation/webserver-configuration.html

**Comment by l00ptr** [comment]
we don't use sqlite but mariadb sorry for not giving directly this information.

**Comment by l00ptr** [comment]
> Does Kimai work in general? Sounds as if your webserver config is wrong.
> 
> See https://demo.kimai.org/api/doc

Yes kimai works

**Comment by l00ptr** [comment]
for your information this is the configuration our apache server : 
```

<VirtualHost *:80>
        ServerName xxxx
        ServerAdmin webmaster@xxxxx

        DocumentRoot /var/www/kimai2/public

        ErrorLog ${APACHE_LOG_DIR}/xxxx.info-error.log
        CustomLog ${APACHE_LOG_DIR}/xxxx.info-access.log combined

        <Directory /var/www/kimai2/public>
                Options +FollowSymLinks
                AllowOverride All
                Require ip xxxx
                Require ip 127.0.0.1
                Require ip ::1
        </Directory>
  <DirectoryMatch "/\.git">
    Require all denied
  </DirectoryMatch>

</VirtualHost>
```

**Comment by l00ptr** [comment]
And the only thing i changed to the .env file is the param about email and database (using mariadb)

**Comment by kevinpapst** [comment]
Yeah, I don't use Apache, but it looks different from https://www.kimai.org/documentation/webserver-configuration.html

Also, check the .htaccess file in public/ directory.

**Comment by l00ptr** [comment]
sorry for the the wrong bug repport it was due to the apache config. We can close this issue :+1:
