### ISSUE TITLE
Calendar view displays wrong start and end hour

### ISSUE THREAD

**Issue by jpaczes** [kevinpapst/kimai2#1858]
Created activity is wrongly displayed in calendar view, calendar shows start and end date 2 hours earlier than actual activity times.

**To Reproduce**
I managed to reproduce this problem on demo version (1.10 stable ) available on https://demo.kimai.org when i switched to super admin and changed setting to match one that we use in our company.

![image](https://user-images.githubusercontent.com/26572441/89041419-a274f700-d345-11ea-88ba-5058a7d0b281.png)
![image](https://user-images.githubusercontent.com/26572441/89041483-bc163e80-d345-11ea-9cd1-f29b900bf678.png)
![image](https://user-images.githubusercontent.com/26572441/89041531-d2bc9580-d345-11ea-98f6-f7861f70ab03.png)
![image](https://user-images.githubusercontent.com/26572441/89041574-e5cf6580-d345-11ea-9ea1-a10af0da5910.png)

After that i created new activity in calendar view

![image](https://user-images.githubusercontent.com/26572441/89041759-31820f00-d346-11ea-8985-8f9c5cd85f64.png)

and it's displayed like this

![image](https://user-images.githubusercontent.com/26572441/89042216-df8db900-d346-11ea-8fbd-f32a2d9b2319.png)

Other places like 'My times', 'Timesheets' or Record details display correct start and end time for this activity.

**Comment by kevinpapst** [comment]
Verified! Thanks for the report.
That has nothing to do with all these settings, there is something off with the timezone in the calendar.

**Comment by kevinpapst** [comment]
@jpaczes are you using master in your environment?

I have the feeling that this bug is ONLY related to the current dev version and has nothing to do with the calendar, as it was working in the past.

**Comment by kevinpapst** [comment]
Fixed by #1888
