### ISSUE TITLE
Reporting module displays only one activity for project but time sum is displayed for all acivities

### ISSUE THREAD

**Issue by jpaczes** [kevinpapst/kimai2#1859]
When several acivities from one project are created for one day Reporting module displays only one of them, summary is displayed for correct time for that day.

I recreated bug on  1.10 stable (Ayumi)  available on https://demo.kimai.org/

I created several activities for one day (2020-07-09) in one project

![image](https://user-images.githubusercontent.com/26572441/89053031-e4f2ff80-d356-11ea-971e-2ad9bc5904c9.png)

Than I checked reporting module and saw that only one activity is displayed for day but sum matches summary for whole day.

![image](https://user-images.githubusercontent.com/26572441/89053167-1bc91580-d357-11ea-9554-77480a957d12.png)

**Comment by kevinpapst** [comment]
Thank god someone tries the features before the release 😁

**Comment by kevinpapst** [comment]
@jpaczes fixed it, can you please test #1892 in the demo (see PR for more info)
