### ISSUE TITLE
Reporting View - Enhancement - Add more filter options

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1862]
The reporting function is indeed an excellent feature which all of the users of Kimai have been waiting for a very long time. Currently the view only provides option to view users in a monthly fixed view. Would it be possible to allow for weekly or custom time ranges also. 

Also currently even the admin cannot view the project level view of the users if this is also provided under the admin view to change the user and view their timesplit by project it would be really helpful.

**Comment by HeinzWuert** [comment]
for admins the simple filter with customer and/or project selection would be great as I mentioned a few days before!

**Comment by j-be** [comment]
I created a small patch allowing to select a week range in the `week_by_user` view. @kevinpapst Not exactly what this issue is about, but would that be worth a pull-request?

![Untitled](https://user-images.githubusercontent.com/8503582/99816444-fa7d7680-2b4b-11eb-96d6-836d78f3d7da.jpg)

**Comment by kevinpapst** [comment]
@j-be having a report that can handle more filters including variable time ranges is definitely on my list. But I haven't yet thought it through how to build the form.
My initial idea was to make the "Calendar week" button a dropdown, probably for selecting the amount of weeks that should be displayed (1 week, 2 weeks, 3 weeks, 4 weeks, 5 weeks...). Clicking the arrows would still behave the same and move the first report day +- 1 week.

**Comment by kevinpapst** [comment]
I think with all the new reports available, this is not longer a valid request. 
Please re-open with an explanation if you think differently.
