### ISSUE TITLE
Hide global activities in selected projects

### ISSUE THREAD

**Issue by FloDieudo** [kevinpapst/kimai2#1864]
**Allow projects to be restricted only to the desired activities for better  profitability management**

Hi @kevinpapst 

when creating time sheets on a given project, users have access to global activities, despite adding specific activities to the project, which leaves too much freedom in the choice of activities and can lead to confusion

**the solution I'd like: ALLOW / AVOID Global activities when users create timesheets for a project**

is it possible to add a function when editing / creating a project (such as a checkbox), in order to allow / avoid access to global activities for users when they create timesheets?

If the checkbox is ticked (by default) then we display all the activities (the project activities + the other global activities) otherwise, we only display the project activities.

**The advantage of the solution I'd like:**

We have a lot of global activities and they are not all used in each project, so this would restrict the project to the activities they belong to, for a better profitability tracking, so it  leaves the choice to the project creator to allow access or not to the global activities for other users

**The little-Extra:**

Therefore, would it be possible to inject or copy a global activity into a project, in order to make it a project activity?
this could drastically simplify the implementation of recurrent activities within different projects.

This could be a global activities ListBox in which we can choose several specific Global activities for this project. If the listBox stay empty, then, all global activities should be displayed for users when they create their timesheet.

please find attached an example of what this might look like

**Additional context**
mock-up of project creation in Kamai2 with possibility to Avoid / Allow all or only selected Global activities.
![PropositionFeatureKamai](https://user-images.githubusercontent.com/69149494/89196864-195ef980-d5ab-11ea-8b49-ad8572a89a56.jpg)

Thank you for your amazing Work

FloDieudo

**Comment by kevinpapst** [comment]
Thanks for the detailed explanation!

But as said before in another issue: global activities are "global" and not "global sometimes" or "global only in some projects".

I do accept the checkbox to prevent global activities from showing up in selected projects as feature request though.

**Comment by FloDieudo** [comment]
Ok, that’s great.

Thanks

Florent Dieudonné | Chef de Projet – Coordinateur 3D Temps Réel
7, rue Jean Mermoz Bât D - Rdc  78000 Versailles
Tél:  +33 (0)6 71 51 95 89
Mail : f-dieudonne@pagecran.fr<mailto:f-dieudonne@pagecran.fr>
[cid:image001.jpg@01D67F84.ADE49E20]
[cid:image002.jpg@01D67F84.ADE49E20]
[cid:image003.jpg@01D67F84.ADE49E20]<https://www.facebook.com/Pagecran>[cid:image004.jpg@01D67F84.ADE49E20]<https://twitter.com/pagecran>[cid:image005.jpg@01D67F84.ADE49E20]<https://www.linkedin.com/company/pagecran/>[cid:image006.jpg@01D67F84.ADE49E20]<https://vimeo.com/pagecran>


De : Kevin Papst <notifications@github.com>
Envoyé : samedi 29 août 2020 16:50
À : kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc : Florent Dieudonné <f-dieudonne@pagecran.fr>; Author <author@noreply.github.com>
Objet : Re: [kevinpapst/kimai2] Hide global activities in selected projects (#1864)


Thanks for the detailed explanation!

But as said before in another issue: global activities are "global" and not "global sometimes" or "global only in some projects".

I do accept the checkbox to prevent global activities from showing up in selected projects as feature request though.

**Comment by FloDieudo** [comment]
> But as said before in another issue: global activities are "global" and not "global sometimes" or "global only in some projects".
> I do accept the checkbox to prevent global activities from showing up in selected projects as feature request though.

Okay, I understand about the global activities. 

In this case, **would it be possible to set up a specific project activity system**, which would allow to build (if necessary) a list of project activities.
So in the Kimai interface we could have **a separate "project activity" section** to manage this list. 

**In the editing window of a project**, we could **have access to this list of "project activities"** via a listbox to select the ones we are interested in.

With such a system, it would be possible to **quickly activate/deactivate any of the project activities** that we want to see integrated or not, and **to be able to indicate budgets (time and financial) that would be, therefore, specific to each activity of each project** (something that is currently not possible in the current state when relying on global activities, because the budget is the same for each instance of the global activity).

All this associated with the possibility to authorize or not, the Global activities on this project.

**In this way, the creation of project activities would be faster**, because currently, on 2 different projects with the same project activity title, **we have to create the project activity twice (once in each project)**.
If we have 20 Projects with the same project activity title, **that's a lot of wasted time**.

I remain open to any exchange to evolve ideas on this point.

Regards,

**Comment by kevinpapst** [comment]
If you have many projects with the same structure, you could also setup a default project structure and clone that when setting up a new project.

I am not sure that I understand it correctly, so you want a 1:n connection => 1 activity for many projects?

**Comment by FloDieudo** [comment]
> so you want a 1:n connection => 1 activity for many projects?

yes, I think this is it... 

(I'm French so I may not express myself very clearly in English, and may not understand everything perfectly).

I will try to be as clear as possible.

I'm trying to put in place a way to make it easier to trace estimated and sold times compared to the time consumed for each activity (same thing for the financial aspect).

**Today we only work with global Activities** (because the management of project activities is time-consuming), which makes it very difficult to monitor consumption in detail... not to mention that with too many global activities, users can make mistakes when choosing global activities in the time sheets ... this is why I initially wanted to be able to activate or deactivate access to global activities depending on the projects... (cf first post)

**Global activities are interesting for activities** such as team meetings, attendance, or other activities that are not strictly speaking "jobs" and **"transversal" to all professions**.

We have, by "job", different " tasks ", **which are not necessarily all applied in a project.**

for example: 
the "3D Graphics" profession can do the following tasks (but not necessarily all of them) with specific costs for each one (depending on the client):
- Modelling
- Database recovery
- Definition of colours, textures, materials 
- Specific lighting
- Simulation of object dynamics and particle flows
- Object and camera animations
- etc ...

And so on for the different professions in our company (3 other professions).

The idea is **to be able to have "quick" access in the project editor to the different "tasks by profession"** and to be able **to integrate them (or not) into the project as independent "project activities".** 

In this way, on each of the "project activities", **the notions of budget** (time/financial) **could be included only within the project in question, and not transversally to all projects.**

If this is made possible, **then we would reduce our number of "global activities"** from 30 to 5, we would **control the specific "project activities" that we want to add to each project,** and we would also **avoid mistakes in the choice of activities made by users** when creating time sheets **(since the choice would be limited to the concerned "tasks by profession")**.

Sorry for this novel, but I hope it is more understandable for you

**Thank you very much for your time**

Regards,

**Comment by kevinpapst** [comment]
Will be shipped with the next update.
If you want to help testing, you can have a look at the demo.

**Comment by kevinpapst** [comment]
Fixed with #3437
