### ISSUE TITLE
downloaded kimai 2 and i have so many issues 

### ISSUE THREAD

**Issue by hamad2112020** [kevinpapst/kimai2#1868]
hello dears 

first i want to thank the developers for such a well designed software 

i downloaded kimai 2 as winrar  then i put it here 

:[kimai address ](
![aa](https://user-images.githubusercontent.com/69042606/89308240-b341a780-d67a-11ea-98c2-ac28718db1f4.PNG)

and i have windows 10 home 
so i opened kimai and tried to run index.php  to my localhost this returned 

![bb](https://user-images.githubusercontent.com/69042606/89308619-24815a80-d67b-11ea-80d6-f4b4c87a03fc.PNG)

then i followed the installation steps and first one is to connect to ssh

![cc](https://user-images.githubusercontent.com/69042606/89308622-2519f100-d67b-11ea-95ef-e8080cd6ea40.PNG)

 ....this came back to me 

[ssh](u
![kk](https://user-images.githubusercontent.com/69042606/89306850-129eb800-d679-11ea-8a5a-84f8c8420ffc.PNG)
rl)

even though i have both openssh client and server at my option manager

![jj](https://user-images.githubusercontent.com/69042606/89308631-277c4b00-d67b-11ea-8cb2-834687c1b9fa.PNG) 

then i copied first cmd in my command as admin and it returned that i already downloaded the file 

but the dependencies install command did not work [dependencies fail](

![ee](https://user-images.githubusercontent.com/69042606/89308626-264b1e00-d67b-11ea-82e7-58b46270623b.PNG)

even database link did not work for me 

![ff](https://user-images.githubusercontent.com/69042606/89308628-26e3b480-d67b-11ea-8c30-96ac3c482f68.PNG)

kimai installer ??
here 

![hh](https://user-images.githubusercontent.com/69042606/89308629-277c4b00-d67b-11ea-85c7-394fdc0c3808.PNG)

i know there is something or many things i did wrong 

and i am hopeful that you all tell me what it is 

thanks in advance

**Comment by HeinzWuert** [comment]
das ganze schon mal auf Linux probiert?  ;-)

**Comment by hamad2112020** [comment]
> das ganze schon mal auf Linux probiert?  ;-)

No windows 10 home

**Comment by HeinzWuert** [comment]
Ich meinte Kimai auf einem Linux System zu installieren ist schon sinnig ;-)

**Comment by hamad2112020** [comment]
OK danke
aber ich dachte, es funktioniert auch unter Windows

**Comment by kevinpapst** [comment]
Na dann antworte ich auch mal auf deutsch: es sieht so aus als würdest Du das erste mal mit so einer Art von Software arbeiten. Ich kann hier keine Schulung in Bash/CmdLine etc. geben, daher nur kurz.
SSH ist nur benötigt, wenn Du es auf einem Server installierst, nicht wenn es lokal läuft. 
Composer muss natürlich funktionieren. Die Zeile mit DATABASE_URL gehör in die .env Datei.
Alles weitere ist dann wohl Try&Error. Good luck 😄

**Comment by kevinpapst** [comment]
Achso, natürlich läuft es auf Windows, aber dann passt halt die Anleitung nicht. Und da ich weder ein Windows System noch einen MAMP Server habe, kann ich da auch nicht weiterhelfen.

**Comment by hamad2112020** [comment]
Ok 
Is there a chance you reply to me in english ?

**Comment by hamad2112020** [comment]
I will install linux then

**Comment by HeinzWuert** [comment]
Tut es aber die Befehle die du verwendest sind Linux.

 

Von: hamad2112020 <notifications@github.com> 
Gesendet: Dienstag, 4. August 2020 19:14
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: HeinzWuert <firstdata@web.de>; Comment <comment@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] downloaded kimai 2 and i have so many issues (#1868)

 

OK danke
aber ich dachte, es funktioniert auch unter Windows

**Comment by kevinpapst** [comment]
If you answer in German, I get the impression you speak german

**Comment by hamad2112020** [comment]
Understood kevin 
Now i will install linux 
But i still want to know steps for windows 10 
Its good to know 

And i have question regarding funding too

**Comment by hamad2112020** [comment]
I will install linux

I did not know these are linux phrases

I still want to know windows way too

في الثلاثاء، ٤ أغسطس ٢٠٢٠ ٨:٣٤ م HeinzWuert <notifications@github.com> كتب:
