### ISSUE TITLE
missing icons, try 2

### ISSUE THREAD

**Issue by copenhaus** [kevinpapst/kimai2#1871]
Hi, new to Kimai. I just followed an online tutorial and set this up on my Ubuntu 18.04 VM.

I started my Chrome browser and log into the Dashboard, but all the icons are missing.

https://imgur.com/a/prer7BW

What can I check/verify to have the icons shown?

I've rebooted the server once and the icons showed up...but once I logged out and log back in, the icons are missing...

Thanks in advance for the assistance!

**Comment by kevinpapst** [comment]
Check your browser console. Deactivate browser plugins.

**Comment by copenhaus** [comment]
hi Kevin.

Thanks for quick reply.

I've tried Chrome in Incognito mode...still no go...

**Comment by kevinpapst** [comment]
something is blocking stuff - Check your browser console

**Comment by copenhaus** [comment]
I just tried Microsoft Edge...first time log in, all icons shown...log out, log back in...icons missing...

**Comment by copenhaus** [comment]
OK, i looked into the browser console and it showed a bunch of errors:

1. Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

2. Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-TotaJgQpi3uAcFIYGbWcMXZfL/6yP3V4SMJJLI/gF94='), or a nonce ('nonce-...') is required to enable inline execution.

3. Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by kevinpapst** [comment]
Well then, update your CSP settings, they are way too strict

**Comment by copenhaus** [comment]
ahhh!!  ughhhh....

thanks... 👍

**Comment by kevinpapst** [comment]
Glad you understand CSP, fixing that problem would have been a nightmare if not 😁
