### ISSUE TITLE
export (CSV) with inconsistent unit

### ISSUE THREAD

**Issue by copenhaus** [kevinpapst/kimai2#1873]
Hi.

In the portal, the "Duration" is shown in hours, but when exporting to CSV, the Duration is shown in seconds.

All the other output formats (Print, PDF, Excel) are fine.

Here's a screenshot for reference:  https://imgur.com/a/qZDCSjx

**Comment by kevinpapst** [comment]
Excel is in seconds as well, it is just "properly formatted".

Print and PDF are meant for print or some other direct human usage, but CSV is meant for re-use with some kind of software.
It is up to you to format it then.

**Comment by kevinpapst** [comment]
No feedback, closing
