### ISSUE TITLE
HOW TO: Time / Cost Budget into Excel Export

### ISSUE THREAD

**Issue by FloDieudo** [kevinpapst/kimai2#1874]
Hi there, 

Is there any way to add "**Time budget**" and "**Cost Budget**" into the Excel export for:
> - Projects
> - Projects Activities

In the other Hand, is there any way to make the "Project Budgets" depending on its own 'Project activities"?
I mean:
> - if 2 "project activities"  have Two hours each for time budget, then the Project's Time budget automatically inherits those 4 hours 
> - Same thing for "cost budget"

This could be very usefull for project detailed profitability tracking.

Many thanks for your answer

**Comment by HeinzWuert** [comment]
I'm using it.
All variables can be found here: https://www.kimai.org/documentation/invoices.html#spreadsheets-ods-xlsx-and-csv

**Comment by kevinpapst** [comment]
Please clarify

> into the Excel export

There is more than one export.

> In the other Hand, is there any way to make the "Project Budgets" depending on its own 'Project activities"?

No, you have to define them independent

**Comment by kevinpapst** [comment]
No feedback, closing
