### ISSUE TITLE
Export on user level

### ISSUE THREAD

**Issue by dominodd** [kevinpapst/kimai2#1875]
Our company was one step away from using this software. It is great, no other words. 
The fact that a user can't export his own timesheet is a blocking point. 
Why should a user be able to export ONLY his own hours? 
- Some branches of consultancy need to print their hours and let them sign (digital via PDF or old school, with a real signature).
This is possible in kimai2 BUT for privacy reasons, a user should only be able to print his/her own timesheets and nothing else.
- if you work with external consultants, they should not be able to view all your clients and projects, only theirs.

**Describe the solution you'd like**
Let a user print his/her timesheets but ONLY his/her timesheets.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kevinpapst** [comment]
> The fact that a user can't export his own timesheet is a blocking point.

You are using it wrong, every user can export his own timesheets into several formats.
<img width="1186" alt="Bildschirmfoto 2020-08-06 um 13 22 36" src="https://user-images.githubusercontent.com/533162/89526422-0422de80-d7e8-11ea-880b-3eaacc519920.png">

By default only the current month is visible. If the user wants to export last month, he must use the last month date range filter in the search first.

**Comment by dominodd** [comment]
Yes! Thank you, I was looking at the left bar, my bad. Fantastic!

**Comment by kevinpapst** [comment]
If you start using it, please tell the boss that its great to get a free software ... [but the developer still has to eat](https://www.kimai.org/store/) 😁
