### ISSUE TITLE
Track Ip address or Device ID

### ISSUE THREAD

**Issue by momo-aux** [kevinpapst/kimai2#1876]
Hi, is there any possibility to track from which device or ID the timesheed entry was made?
We want to have a tablet in the Workshop where people can sign in for work but also allow external access for people on the go.
So wen would like to see if they tracked from inside or outside the shop.
Could be done by seeing if the entry was made by internal ID or by getting some kind of identifier from the device.

Any ideas on that?

**Comment by kevinpapst** [comment]
There is no functionality out of the box available for such a task. 

Plugins could probably achieve that using browser fingerprinting techniques with javascript.

**Comment by kevinpapst** [comment]
No feedback, closing
