### ISSUE TITLE
Configure displayed attributes in dropdowns

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1882]
**Is your feature request related to a problem? Please describe.**
We handle a project in successive sub-projects.
The projects always have the same name, they only differ in the start and end times.
For this reason, the user can see (max) 2 projects with the same name when selecting for input of bookings. At this moment, however, it is not possible for him to see which one he should call up for his booking, since the only distinguishing criterion (date) is missing.

**Describe the solution you'd like**
Show the project start and end date in the select field.

**Comment by kevinpapst** [comment]
Added recently
