### ISSUE TITLE
Adding/viewing Acitivities while in Project view 

### ISSUE THREAD

**Issue by zeroboioioy** [kevinpapst/kimai2#1885]
It would be nice to have the possibility to add or view activities while editing or creating projects.
With that, maybe it's also a good idea to add acitivities while tracking times, because sometimes the right acitivity is just not there and would make time tracking easier if you can just add it as you track it.

**Comment by kevinpapst** [comment]
Thats already possible via the "action dropdown" both in the projects list (right side of the table) and detail view (upper right).

In the upcoming 1.10 release there will be a second `+` button in the activity table for the people that can't find the button 😁 
<img width="148" alt="Bildschirmfoto 2020-08-12 um 13 48 11" src="https://user-images.githubusercontent.com/533162/90011768-78ef9000-dca2-11ea-86d7-bd7c76d4e988.png">


Maybe in the future I will add an option to add them from the time tracking screen, but thats not yet on my roadmap. 
I think there is already a feature request in one of the earlier issue pages, please search and vote for it (with a 👍 reaction in the initial posting).
