### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by grandeljay** [kevinpapst/kimai2#1886]
I've recently started learning web dev and I'm trying to setup kimai 2 locally the recommended way, via git (and on windows).

Following the installation instructions
1. I've cloned the repo
```
git clone -b 1.9 --depth 1 https://github.com/kevinpapst/kimai2.git
cd kimai2/
```

2. installed composer
```
composer install --no-dev --optimize-autoloader
```

3. set database
I don't have a password set, so I just left that bit out (hope it works out)
```
DATABASE_URL=mysql://root:@127.0.0.1:3306/database
```

3. run the installer
This is where my issue lies.
```
bin/console kimai:install -n
```

How do I execute this in the standard console?
```
D:\WampServer\www\kimai2\bin>.\console kimai:install -n
'.\console' is not recognized as an internal or external command,
operable program or batch file.
```

I've been trying to avoid WSL because so far I've been getting along with CMD and PowerShell, is this possible?

Any help is very appreciated. Thanks.

**Comment by kevinpapst** [comment]
can you go into kimai directory (not bin) and call `bin/console` ?

**Comment by kevinpapst** [comment]
Maybe you need to call `php bin/console`

**Comment by grandeljay** [comment]
`php` is the missing keyword, thank you so much!

```
D:\WampServer\www\kimai2\bin>php console kimai:install -n
```

has triggered install for me.
