### ISSUE TITLE
How to use SASS

### ISSUE THREAD

**Issue by grandeljay** [kevinpapst/kimai2#1887]
Sorry if this is not the right place for these things, I couldn't find a dev guide or similar. Kindly point me in the right direction if I'm wrong here.

I'm trying to get started with SASS, and I noticed the CSS files in `\kimai2\public\build` all seem to have a postfix appended. Is this where the compiled SASS files are supposed to end up?

```
sass --watch \kimai2\assets\sass:\kimai2\public\build
```
I've used this for now but my files do not have a postfix appended to them, is this wrong? Am I missing something?

Example:
`app.css` instead of `app.554717a4.css`

**Comment by kevinpapst** [comment]
There is a short section about recompiling the assets in the developer documentation with links to further tools.

This line is the reason why your files doesn't have versioning: https://github.com/kevinpapst/kimai2/blob/master/webpack.config.js#L22

There is a difference between the development and production build.

But You should start reading about webpack and webpack encore. 
Here is definitely not the right place to ask beginner questions about these topics (unless they are strictly connected to Kimai).

**Comment by kevinpapst** [comment]
BTW: why do you want to customize Kimai SSS files? If you only want to add some basic CSS rules, there is a plugin that allows to add custom rules.

**Comment by grandeljay** [comment]
Thanks again.

I would like to contribute to the kimai design.

**Comment by kevinpapst** [comment]
In that case: be welcome to ask further question 😄 

And please have a look at that block: https://github.com/kevinpapst/kimai2/blob/master/package.json#L16
These are likely the commands that you want to use instead of the sass watcher.

So if you execute `yarn run prod` it will internally run `node_modules/.bin/encore production`, which will trigger a production build and add the version hashes.

**Comment by grandeljay** [comment]
> be welcome to ask further question
Sweet, I'll come right up with my next question then!

If I run `yarn run prod` everything seems to be generated in the `\kimai2\public\build` folder which seems like good news but the changes I made in SASS do not seem to be in the new CSS files.

Is there anything else I could be missing?

**Comment by kevinpapst** [comment]
Not very likely if you changed existing files. But as

> the changes

could be literally anything, I can't say in more detail.

Which Kimai version are you using in which APP_ENV?
If you run in `APP_ENV=prod` which is the default setting in your `.env` file, then the assets are cached until cache reload with `php bin/console kimai:reload`.

**Comment by grandeljay** [comment]
I am using developer version
```
APP_ENV=dev
```

For instance, I was trying to change the padding in `/assets/box.scss` which is set to `10px` before changing it.
```
/* used on detail pages for: customer, project and activity */
.box-body.no-padding div.comment {
  padding: 20px;
}
```

![image](https://user-images.githubusercontent.com/45571053/90106041-21efc680-dd47-11ea-84e3-017d8298be69.png)


On the page it is rendered as follows:
```
.box-body {
  [...]
  padding: 10px;
}
```

Where/How do I edit the CSS for the boxes?

**Comment by kevinpapst** [comment]
Compile in dev, browser console should show you the origin thanks to sourcemaps

**Comment by grandeljay** [comment]
Do I compile with `yarn run prod`?

The origin does not seem to show for me:
![image](https://user-images.githubusercontent.com/45571053/90132304-d69cde80-dd6d-11ea-8a1e-754f1f1a6227.png)

I've tried [testing a "simple" source map](https://tromey.github.io/source-map-examples/css/index.html) and it seems to work for me:
![image](https://user-images.githubusercontent.com/45571053/90132379-03e98c80-dd6e-11ea-80bd-84426b5f8b58.png)
