### ISSUE TITLE
API v0.5 show user body parameter

### ISSUE THREAD

**Issue by Dwayne28** [kevinpapst/kimai2#1889]
Hi,

I installed kimai via docker 
from: https://github.com/tobybatch/kimai2
version: kimai/kimai2:fpm-alpine-1.9-prod

In the demo: https://demo.kimai.org/api/doc
I saw that the endpoint /api/timesheets includes the parameter "user"
The demo shows at the top the API version 0.6

My API version is 0.5 and doesn't show the body parameter "user"

So is it possible to activate this parameter somehow via a config or do I need to update to a newer version of kimai?

Thanks in advance

**Comment by kevinpapst** [comment]
Its available in your version as well (if you have the proper permissions).
Its just a documentation bug that is isn't displayed in the previous (0.5) version.

> or do I need to update to a newer version of kimai

If its a requirement for you to see it in the API docs, then yes. I only give forward support, no patches for old versions.
