### ISSUE TITLE
Filter activities shows all activities instead of just for project

### ISSUE THREAD

**Issue by tomatic** [kevinpapst/kimai2#1890]
**Describe the bug**
On the project list, when I click the dropdown arrow next to a project and select filter activities, it returns a list of all activities, not just those for the respective project. The same general error happens when filtering projects from the customer list (shows all projects from all customers). This bug seems to have appeared with Kimai 1.9, filtering activities worked as expected on earlier versions.

**To Reproduce**
1. Go to list of projects
2. Click on dropdown arrow next to a project and click Filter activities
3. The list of activities is loaded, the URL is /en/admin/activity/?customer=5&project=19. But the list shows all activities across all projects instead of just the activities of the selected project. Additionally, the search box on the activities page has a red border and when clicking in the search box, the error "This form should not contain extra fields." is displayed.

**Logfile**
The logfile prod.log does not contain any entries from the day I performed the test.

**Additional context**
 - Kimai 2 version 1.9 stable
 - PHP version 7.3.14

**Comment by kevinpapst** [comment]
Thanks for the report @tomatic 👍 This bug has already been fixed for the next release. 
You can test the "development version" demo.

**Comment by tomatic** [comment]
Awesome, thanks for the update.
