### ISSUE TITLE
fresh installation via portainer

### ISSUE THREAD

**Issue by koroleves** [kevinpapst/kimai2#1891]
Sorry for my English!
good morning!
I am using portainer to install but it does not support compose version 3

after modifying the compose file
version: '2'
services:
  kimai:
    image: kimai/kimai2:fpm-alpine-1.8-prod
    environment:
      - DATABASE_URL=mysql://kimai:J5Ps8c7z@192.168.1.10/kimai
      - APP_ENV=prod
      - APP_SECRET=secret
      - TRUSTED_HOSTS=localhost,192.168.1.10,omv,
      - TRUSTED_PROXIES=localhost,192.168.1.10,omv,
      - ADMINMAIL=mail@ya.ru
      - ADMINPASS=secret
      - MAILER_FROM=kimai@example.com
      - MAILER_URL=secret
    volumes:
      - /appdata/user2/.config/appdata/kimai/public:/opt/kimai/public
      - /appdata/user2/.config/appdata/kimai/var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    ports:
       - 8350:80
    restart: unless-stopped

I see the following logs:
1.8
Using Mysql DB
Wait for db connection ...
Connection established
first run - install kimai
Kimai installation running ...
==============================
Database `kimai` for connection named default already exists. Skipped.
                    Application Migrations                    
No migrations to execute.
 Rebuilding your cache, please be patient ...
 [ERROR] Failed to clear cache: Unable to write in the                          
         "/opt/kimai/var/cache/prod" directory                                  
 [OK] Congratulations! Successfully installed Kimai 2 version 1.8 (stable)      
 [ERROR] username (superadmin)                                                  
             The username is already used.                                   
 [ERROR] email (mail@ya.ru)                                                
             The email is already used.                                         
Kimai2 ready
Reloading configurations ...
============================
[ERROR] File or directory "config" is not readable.                            
[15-Aug-2020 08:38:38] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[15-Aug-2020 08:38:38] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[15-Aug-2020 08:38:38] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[15-Aug-2020 08:38:38] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[15-Aug-2020 08:38:38] NOTICE: fpm is running, pid 1
[15-Aug-2020 08:38:38] NOTICE: ready to handle connections

BUT WEBSITE STARTUP PAGE IS NOT AVAILABLE (PORT-8350) !!!
What have I configured incorrectly? Which port should you listen to? Is it possible to run at all with version 2 of compose?

**Comment by kevinpapst** [comment]
I don't know what portainer is and I don't support it. 
But you seem to be using a docker image, so please go to the docker repository and ask there: http://github.com/tobybatch/kimai2
