### ISSUE TITLE
How to make custom Role same as admin role(Just replicate)

### ISSUE THREAD

**Issue by groovyrb** [kevinpapst/kimai2#1896]
**Is your feature request related to a problem? Please describe.**
I am making a custom role and I want to give some permission which default Admin role have.
**for example** : Admin can see all team which is I made in Kimai web application but when I create a HR role And provided the team permission from permission section but HR can see the team only when HR is a team lead of that team, so that why i just need a duplicate Role same as Admin so I can give limited permission from Permission section.
or what sould I do here to make a custom Role which is capable like Admin role
**Thought: If new user come then Hr Role can able to assign them to Previous teams.**
kimai:
    permissions:
        sets:
            CUSTOM_ROLE_USER: ['@ROLE_USER', '@TAGS']
        maps:
            ROLE_USER: ['CUSTOM_ROLE_USER']

**Comment by kevinpapst** [comment]
You can't with 1.9 as Admin roles don't use team permissions (see [special treatment in repositories](https://github.com/kevinpapst/kimai2/blob/1.9/src/Repository/TeamRepository.php#L177)).

In 1.10 there is a `view_all_data` permission allows you to configure this behavior.

**Comment by groovyrb** [comment]
Thanks for the reply I cant switch back to 1.10 I have to make changes in 1.9 itself I will do as you suggested the treatment in repository.

**Comment by kevinpapst** [comment]
See this PR: 
https://github.com/kevinpapst/kimai2/pull/1803/files 
and this change: 
https://github.com/kevinpapst/kimai2/pull/1815/files#diff-a957d491412776c2c66c5cc386a95d0f
(the linked entity and the following event subscriber)
