### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sahara101** [kevinpapst/kimai2#1899]
Expected behaviour
Working kimai

Actual behaviour
500 internal Server Error CentOS8

Steps to reproduce
Installed using the Ubuntu 18.04 wiki with a few changes.

installed php-mysqld
installed mariadb
chown using the user nginx
had to modify /etc/nginx/nginx.conf to include /etc/nginx/sites-enabled/kimai2
had to modify /etc/nginx/default.d/php.conf to add the fastcgi_pass
created host entry for www.kimai.local
skiped SSL config
If I try www.kimai.local I am directly greeted with 500 internal server error....

Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.9

Relevant log entries from log file (debug tab or temporary/logfile.txt)
Cannot find any logs at all, not even in kimai var folder.
Thank you!

**Comment by kevinpapst** [comment]
A 500 should ALWAYS log something. 
Either in Kimai log or in Apache/Nginx or php/fpm log.
Check file permissions. If there is no log in var/log/ then this is a strong indication of wrong permissions

**Comment by sahara101** [comment]
Unfortunately no...
Kimai log folder empty
nginx error log empty
php-fpm error log only states fpm is running, ready to handle connections. systemd monitor interval set to 10000ms

Permissions;

drwxr-xr-x.  6 root nginx    138 19. Aug 19:59 assets
drwxr-xr-x.  2 root nginx     21 19. Aug 19:59 bin
-rw-r--r--.  1 root nginx   6349 19. Aug 19:59 CHANGELOG.md
-rw-r--r--.  1 root nginx   6303 19. Aug 19:59 composer.json
-rw-r--r--.  1 root nginx 486389 19. Aug 19:59 composer.lock
drwxr-xr-x.  6 root nginx    182 19. Aug 19:59 config
-rw-r--r--.  1 root nginx   1235 19. Aug 19:59 CONTRIBUTING.md
-rw-r--r--.  1 root nginx   1982 19. Aug 19:59 Dockerfile
-rw-r--r--.  1 root nginx   1100 19. Aug 19:59 LICENSE
-rw-r--r--.  1 root nginx   1259 19. Aug 19:59 package.json
-rw-r--r--.  1 root nginx   1605 19. Aug 19:59 phpstan.neon
-rw-r--r--.  1 root nginx   2627 19. Aug 19:59 phpunit.xml.dist
drwxr-xr-x.  6 root nginx    264 19. Aug 20:02 public
-rw-r--r--.  1 root nginx   4316 19. Aug 19:59 README.md
-rw-r--r--.  1 root nginx   1077 19. Aug 19:59 SECURITY.md
drwxr-xr-x. 32 root nginx   4096 19. Aug 19:59 src
-rw-r--r--.  1 root nginx  20134 19. Aug 19:59 symfony.lock
drwxr-xr-x. 27 root nginx   4096 19. Aug 19:59 templates
drwxr-xr-x. 32 root nginx   4096 19. Aug 19:59 tests
drwxr-xr-x.  2 root nginx  12288 19. Aug 19:59 translations
-rw-r--r--.  1 root nginx  17608 19. Aug 19:59 UPGRADING.md
drwxrwxr-x.  8 root nginx     89 19. Aug 19:59 var
drwxr-xr-x. 50 root nginx   4096 19. Aug 20:02 vendor
-rw-r--r--.  1 root nginx   1727 19. Aug 19:59 webpack.config.js
-rw-r--r--.  1 root nginx 330578 19. Aug 19:59 yarn.lock



public


-rw-r--r--. 1 root nginx 24282 19. Aug 19:59 apple-touch-icon.png
drwxrwxr-x. 2 root nginx    24 19. Aug 19:59 avatars
-rw-r--r--. 1 root nginx   438 19. Aug 19:59 browserconfig.xml
drwxr-xr-x. 4 root nginx  4096 19. Aug 19:59 build
drwxr-xr-x. 4 root nginx    42 19. Aug 20:02 bundles
drwxr-xr-x. 2 root nginx   102 19. Aug 19:59 favicon
-rw-r--r--. 1 root nginx  5674 19. Aug 19:59 favicon-32x32.png
-rw-r--r--. 1 root nginx  1150 19. Aug 19:59 favicon.ico
-rw-r--r--. 1 root nginx  1254 19. Aug 19:59 index.php
-rw-r--r--. 1 root nginx   416 19. Aug 19:59 manifest.json
-rw-r--r--. 1 root nginx   118 19. Aug 19:59 robots.txt
-rw-r--r--. 1 root nginx 43900 19. Aug 19:59 touch-icon-192x192.png



var


drwxrwxr-x. 4 root nginx 46 19. Aug 20:04 cache
drwxrwxr-x. 2 root nginx 67 19. Aug 20:05 data
drwxrwxr-x. 2 root nginx 22 19. Aug 19:59 log
drwxrwxr-x. 2 root nginx 22 19. Aug 19:59 packages
drwxrwxr-x. 2 root nginx 22 19. Aug 19:59 plugins
drwxrwxr-x. 2 root nginx 22 19. Aug 19:59 sessions

**Comment by kevinpapst** [comment]
Do you see hits in access log? If not, the error is maybe earlier (eg. nginx config, wrong php-fpm config)

**Comment by sahara101** [comment]
No, access.log is also empty. I really have no clue where to look for config errors...

**Comment by kevinpapst** [comment]
And how is that connected to Kimai? 😁 

As always: start with the smallest possible config and work your way up step-by-step.

Make sure that the virtual host is working as expected: 
Can you access static resources like one of the images in the Kimai public directory?

**Comment by sahara101** [comment]
Yes, I can. 
I also created a test.php file which nginx shows, so nginx does not seem to be te issue.
I deleted the files in the cache folder, now I am only getting a blank page.

**Comment by kevinpapst** [comment]
Apply `chmod -R 777 ...` to all folded from the docs  ... just to make sure.

If you can call a test.php then add some debug messages to public/index.php and see where it stops.

**Comment by sahara101** [comment]
Did, change also owner to root a stest, same issue
BUT. I activated apache2 now I see a forward to /de/login. Page is no longer white, I have the 500 error again.

Now I also have a prod.log

https://pastebin.com/ZC8rzyYz

**Comment by kevinpapst** [comment]
Did you even run the installer / composer and such?

> Table 'luna.kimai2_...' doesn't exist

**Comment by sahara101** [comment]
Yes, I see it does not see the DB, but I created it.

I ran this:
composer install --no-dev --optimize-autoloader
vim .env
Configure the above created database credentials:

DATABASE_URL=mysql://kimai2:my-super-secret-password@127.0.0.1:3306/kimai2
And execute the Kimai installation:

bin/console kimai:install -n

**Comment by kevinpapst** [comment]
It is looking in the database `luna` and you configured `kimai2` as database

But that makes no sense, unless you changed it after running the installer.

**Comment by sahara101** [comment]
Hell if I know...after I had the damn log, it was quite clear...
created new db. reinstalled.
All OK now.

In the end something was not right with the nginx config. Apache is working. DB issue canot explain, I tried so many things, probably got them screwed, 

Thank you for your time!

**Comment by kevinpapst** [comment]
Sure, the donation button is not far^^
