### ISSUE TITLE
Download version 1.10 link not working

### ISSUE THREAD

**Issue by yardstudio** [kevinpapst/kimai2#1908]
**Describe the bug**
Can´t download ftp package from kimai.org site

**To Reproduce**
1. Go to https://www.kimai.org/download/
2. Click on https://github.com/kevinpapst/kimai2/releases/download/1.10/kimai-release-1.10.zip
3. See error

  ![2020-08-23_23-05-49](https://user-images.githubusercontent.com/25852179/90988762-915e8500-e595-11ea-84c6-2c2d0e945ac7.png)

**Comment by kevinpapst** [comment]
Thanks @yardstudio 

Forgot to upload the FTP version. Did it and you can download it now.
