### ISSUE TITLE
invoice language

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1910]
**Reproduce the bug**
Access Kimai demo (as admin): Invoices - select Company invoice (DOCX) - set language to "Deutsch" - Save

Invoices - Select Time Range July - October - select first customer (Block - Blanda - Beatty) - print preview (or save)

All language-relevant data in the invoice remain in the English format (e.g. "Service date: July 2020" instead of "Juli 2020")
(I have the same issues with the variables in my invoices)

Is there anything else needed to be switched in order to change the invoice language independently from the gui-language?

**Comment by kevinpapst** [comment]
Hm, you seem to be right. 
I fixed that for all other invoice renderer (HTML, the new PDF format ...) but apparently not for DOCX 👎

**Comment by kevinpapst** [comment]
Wait: you have the same problem with other formats (eg. Excel) as well?

**Comment by BeckeBauer** [comment]
Don't have any other template invoice - all my invoices are docx-based... 
just tried the pdf-template in your demo - latest stable: set language for invoice (pdf) to German and the translations like "Datum" are German (so it works as expected)

Did you have something else in mind with your question (since the docx-based invoice in your demo did not work as well)?

**Comment by kevinpapst** [comment]
No, I was just not sure what you meant with

> I have the same issues with the variables in my invoices)

Obviously I cannot do anything about hardcoded translations in the DOCX files (like in the demo company.docx).
But the variables should be properly formatted, I will look into it soon.

**Comment by BeckeBauer** [comment]
I was referring to variables like ${query.begin_month} which remain English (like July) but will be correctly translated in the DOCX-invoice (like Juli) if the gui is switched to German (whereas the language setting of the invoice has no effect)

**Comment by kevinpapst** [comment]
Please retest, Demo was reinstalled.

**Comment by BeckeBauer** [comment]
It's working 👍

**Comment by kevinpapst** [comment]
Finally 😀 thanks for testing - will create a bugfix release later.

**Comment by slowguitar** [comment]
we have the same problem. If we run:

`sudo -u www-data bin/console kimai:invoice:create --user xxx -vvv --timezone=Europe/Berlin --customer=44 --template="Standardabrechnung" --start=2020-09-01 --end=2020-09-30`

The output in the Date field is 2020-09-XX . If i run php script from shell the output is correct in german format. If we create the the output from webgui all ok. But this is by ca 280 invoices not possible.

Regards 
thomas

**Comment by kevinpapst** [comment]
@slowguitar Thomas, this issue is closed and fixed with 1.10.2.
Please open a new bug report if you encounter problems with the latest release.
