### ISSUE TITLE
bin / console commands do not work

### ISSUE THREAD

**Issue by fSantosLima** [kevinpapst/kimai2#1911]
Hello! I am trying to install kimai following the documentation. However, when executing the bin / console kimai: install -n, I end up having this error: 

Failed to execute the program 'console': There are no applications associated with the file specified for this operationNo
line: 1 character: 1
+ bin / kimai console: install -n
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~.
In line: 1 character: 1
+ bin / kimai console: install -n
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId: NativeCommandFailed.

Would you have any ideas to help me? I'm using Windows 10 and the PHP version IS 7.4.9.

Thanks in advance for your attention!

**Comment by kevinpapst** [comment]
Try: `php bin / kimai console: install -n`

**Comment by fSantosLima** [comment]
> Try: `php bin/console kimai:install -n`

Worked perfectly! Thanks a lot for the help!!
