### ISSUE TITLE
Display a "time/budget"-bar on the projects overview

### ISSUE THREAD

**Issue by blaue-mango** [kevinpapst/kimai2#1912]
Currently you have to open each single project to see the "time/budget" bar.
It would be great to have one view where you can see which projects are in plan and wich are running out of budget.

**Comment by kevinpapst** [comment]
And which projects do you expect to show up in that view?
All existing ones? All visible ones? All that had a record in the last X days?

**Comment by HeinzWuert** [comment]
the idea is quite good!
Should work for own projects and when role is admin for all active projects.
Active could be defind in this way:
Today is between start- and endtime of projects .AND. time kontingent is > Null

**Comment by kevinpapst** [comment]
Okay, after giving it another thought:
1. change the dashboard widget which shows the team specific projects and only show 5 projects there + a link to 2.
2. a new reporting screen for projects

**Comment by HeinzWuert** [comment]
Sounds good!
No 2 is also great for admins to get an overlook about all active projects.
plus
A selectbox to allow/prevent display of projects with missing time kontingent

**Comment by HeinzWuert** [comment]
when working on this for V1.13 maybe it*s possible to include #2196 and as a nice addon  alphabetical sort of the projects in dashboard view.

**Comment by kevinpapst** [comment]
With #1738 a new "project overview" report was included. Can be tested in the demo.
