### ISSUE TITLE
kimai2 in a subdirectory - 500 Internal Server Error

### ISSUE THREAD

**Issue by francwalter** [kevinpapst/kimai2#1915]
I am a long term user of the old kimai. Now I found that kimai2 is there and I could migrate from old kimai to kimai2, so I tried to install it. 
I have Apache 2.4 and PHP 7.2.31-1+ubuntu18.04.1+deb.sury.org+1 on my Ubuntu 18.04 LTS server

I have Kimai in a subdirectory under my domain, e.g. example.org/kimai, so I went along the [Installation guide](https://www.kimai.org/documentation/installation.html) and set it up to example.org/kimai2. No worries here. But when I point to example.org/kimai2/public/ I get the error:

```

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

```

So I start to scrutinize it, didn't found in the apache this error, neither in php. Then I found the description that kimai2 should be installed not as subdomain. I have no spare domain for it, so I tried the solution in [With subdirectory usage](https://www.kimai.org/documentation/webserver-configuration.html#with-subdirectory-usage) but that didn't help me much, it is for nginx and not apache (I don't know nginx at all).

I read #1006 and #676 and #492 but I don't see the light here.

Does the internal error is not connected at all with the subdirectory issue?

Is there a how to for subdirectory with apache?
Thanks.

frank

**Comment by kevinpapst** [comment]
I don't know and I don't officially support it. Its a security risk if not done properly, eg. because of example.org/kimai2/.env

Its very good possible that the error is related to something else though.
Check var/logs/prod.log - 99% of all problems are related to wrong file permissions.

> I have no spare domain for it

Subdomains are for free since I can remember, which is at least 20 years.

**Comment by francwalter** [comment]
Ah, ok, as subdomain is possible. I didnt think of that.
It is long ago, that I used them, maybe 10 years at least ;)
Will try it then, thanks.

**Comment by kevinpapst** [comment]
Yep, good that we talked 😈 Thats why I 

> don't officially support it

It is too complicated for the vast majority to **safely** configure it with too many possible traps.

So subdomain is the way to go, which then needs to point to the `public/` directory.
I'll close here and you come back with new questions when you have the time for another try 😄
