### ISSUE TITLE
Invoice DOCX creation fails with newer LibreOffice than 6.2.8.2

### ISSUE THREAD

**Issue by cdahinten** [kevinpapst/kimai2#1916]
Upload an DOCX template quits with wrong file type detection. As this is obviously not a bug but maybe a issue of online-documentation to recommend LibreOffice 6.2 for template creation.

All LibreOffice-Versions fail after 6.2.8.2 (tested 6.3, 6.4, and new 7.0.0.3: fail.). It seems that [Content_Types].xml different from older Versions (inside the docx/zip Container) for regular 2007-365 DOCX export and DOCX-Transitional.

Maybe there is a way to pass the upload of LibreOffice-DOCX-files with relaxed and less rigid parsing. 

![Bildschirmfoto 2020-08-24 um 18 02 48](https://user-images.githubusercontent.com/52794941/91068434-932b5580-e634-11ea-9e2c-49e7041b7c3c.png)
  
![Bildschirmfoto 2020-08-24 um 17 47 46](https://user-images.githubusercontent.com/52794941/91067092-c79e1200-e632-11ea-8cab-0b161c1d3626.png)

**Comment by kevinpapst** [comment]
Its rather strict right now, you know... better safe than sorry.
Heere is the code that limits the mimetypes:
https://github.com/kevinpapst/kimai2/blob/master/src/Form/InvoiceDocumentUploadForm.php#L49
If you know which one is used in newer versions, please let know and I will add it.

**Comment by cdahinten** [comment]
You are right – Security first.
It seems to be "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml", right?

XML of 7.0.0.3 Sample DOCX:
[[Content_Types].xml.zip](https://github.com/kevinpapst/kimai2/files/5119156/Content_Types.xml.zip)

<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="jpeg" ContentType="image/jpeg"/><Override PartName="/_rels/.rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/><Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/_rels/document.xml.rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/_rels/header1.xml.rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/_rels/footer1.xml.rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/media/image1.png" ContentType="image/png"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"/>
</Types>

**Comment by kevinpapst** [comment]
Is that a question or did you test it in your installation? I don't have the software here right now.

You can simply add it :
```
                        'mimeTypes' => [
                            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                            'application/vnd.oasis.opendocument.spreadsheet',
                            'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml',
                        ],
```
and give it a try in your system. Just don't forget to revert it before the next Kimai update.

**Comment by cdahinten** [comment]
I added the mime as recommended.
cache:clear+warmup produces Error 500. After deleting cache/prod login possible again.
Upload docx LibreOffice produces same error: This file type is not allowed
Is there more neccessary that I have to do to test properly?

**Comment by kevinpapst** [comment]
Not sure. Have to check how the mime type is detected within the used framework.
Please attach such a document here and I will give it a try as well

**Comment by kevinpapst** [comment]
Okay, Installed LibreOffice 7.0 and created a simple test document.

I could upload both "2007-365 DOCX" and "DOCX-Transitional" types without any problem.

The framework tries to detect the mime type by using two methods IMO:

1. By calling `file -b --mime -- the-file.docx`
```
file -b --mime -- ~/Downloads/Untitled\ 1.docx 
application/vnd.openxmlformats-officedocument.wordprocessingml.document; charset=binary
```
And the other one is my using the `finfo` functions of PHP which rely afaik on magic.mime

Maybe something with that is not properly configured in your system?

**Comment by cdahinten** [comment]
Unbenannt-1 empty test file saved in LO7 as 2007-365 DOCX uploads properly. 
ubuntu@kimai:/$ file -b --mime -- Unbenannt-1.docx
application/vnd.openxmlformats-officedocument.wordprocessingml.document; charset=binary

Where as company-lo7 (based on your sample-file) saved as 2007-365 DOCX does not upload. Mime seems not correct, but why. I have no clue.

[Unbenannt-1.docx](https://github.com/kevinpapst/kimai2/files/5124476/Unbenannt-1.docx)
[company-lo7.docx](https://github.com/kevinpapst/kimai2/files/5124477/company-lo7.docx)

ubuntu@kimai:/$ file -b --mime -- company-lo7.docx
application/octet-stream; charset=binary

**Comment by kevinpapst** [comment]
Yep, can't seem to get it working either. Converting it back and forth doesn't help either 😞 

Seems this is a well know problem: https://github.com/symfony/symfony/issues/22702 or https://www.google.com/search?q=mfile+mime+reports+octet-stream+for+docx

For your own installation, you can always simply upload the file to `var/invoices/` as workaround or allow the `application/octet-stream` mimetype. Not sure how to move forward, as registering this mime type in official Kimai is nothing that I would actually consider a legit solution.

**Comment by kevinpapst** [comment]
This seems to be a known bug: https://bugs.documentfoundation.org/show_bug.cgi?id=101317

Interestingly, I could open the file with Apple pages, export it as word and all was fine.
Same with Google Drive/Docs: imported the file and downloaded it as word document - correct mime type as well.
Seems this is a LibreOffice bug.

Best solution right now: mention it in the documentation!?!

**Comment by cdahinten** [comment]
As application/octet-stream is considered vulnerable I'd use the upload var/invoices/.
Mention it in documentation would be a great help – especially the workaround with Drive-Docs … and probably it works with Microsoft Office Online Free-Version (test it tomorrow).

Thank you for your help!

**Comment by kevinpapst** [comment]
Oh yeah, please let me know if that works and I will add it to the new documentation section:
https://www.kimai.org/documentation/invoices.html#uploading-invoice-documents

**Comment by cdahinten** [comment]
Creating a fresh/empty sample file docx in Microsoft 365 Online Office (free version) uploads successful to kimai due to correct MIME:
application/vnd.openxmlformats-officedocument.wordprocessingml.document; charset=binary
Modifiying and resaving the sample comany.docx works also fine in Microsoft 365 Online Office (free version).

Uploading the previous in LibrefOffice 7 (or later than 6.2.8.2) modified company.docx to Microsoft 365 Online Office (free version) and resaved stays: application/octet-stream; charset=binary and does not upload for that mime-type-reason.

So, for now LibreOffice (later than 6.2.8.2) fails to deliver the proper mime-type. That is sad for now, because LibreOffice would offer an Open-Source commited workflow and Microsoft (and Google as well) seems to use the ODF Online Librarys.

**Comment by kevinpapst** [comment]
Added Microsoft to the list of free alternatives to export the docx with proper mime type.

I am closing here, as I am not able to do anything about that problem.

**Comment by kevinpapst** [comment]
> So, for now LibreOffice (later than 6.2.8.2) fails to deliver the proper mime-type. That is sad for now, because LibreOffice would offer an Open-Source commited workflow and Microsoft (and Google as well) seems to use the ODF Online Librarys.

@cdahinten I totally agree... we should probably try OpenOffice and see if it works better. And additionally we could promote upvoting the LibreOffice bug
