### ISSUE TITLE
Manual plugins installation via ftp

### ISSUE THREAD

**Issue by yardstudio** [kevinpapst/kimai2#1918]
Hello,

how is correct way install plugin via ftp?

I downloaded  https://codeload.github.com/mxgross/EasyBackupBundle/zip/master, unzipped it and uploaded to my server by ftp: ..../kimai/var/plugins/EasyBackupBundle-master. 

Then manually deleted cache in ...../kimai/var/cache/prod

but nothing was happen 

What´s wrong in my way ?

**Comment by kevinpapst** [comment]
`kimai/var/plugins/EasyBackupBundle-master` must be `kimai/var/plugins/EasyBackupBundle`

The plugin homepage is here: https://github.com/mxgross/EasyBackupBundle

**Comment by yardstudio** [comment]
Thanks for quick reply. Now working, but red number - compatible with 1,6, what does this mean? Plugin is no compat with my version?  I have Kimai 2 1.10 stable (Ayumi)
![2020-08-24_19-45-44](https://user-images.githubusercontent.com/25852179/91078153-8281dc00-e642-11ea-8987-c81f25418d57.png)

**Comment by kevinpapst** [comment]
It means it is not confirmed by the developer it is fully compatible. If it works you can ignore it.

But I am not the developer of the plugin, so please ask him: https://github.com/mxgross/EasyBackupBundle
