### ISSUE TITLE
change select box for colors

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1919]
**Is your feature request related to a problem? Please describe.**
Color selection ,for example project names, in general: If you don't have the RGB code in mind, after a while you will get a colorful mixture of similar colors. 

**Describe the solution you'd like**
It would be much easier to limit yourself to 16 basic colors as a simple choose and click selection

**Comment by kevinpapst** [comment]
For further reference (both have a "palette only" mode):
- http://bgrins.github.io/spectrum/
- https://github.com/easylogic/codemirror-colorpicker

**Comment by HeinzWuert** [comment]
This one I would prefer, fast an easy to use!
https://github.com/easylogic/codemirror-colorpicker
- Support only Palette Style
