### ISSUE TITLE
CREATE CUSTOM INVOICE

### ISSUE THREAD

**Issue by EdoardoMDP** [kevinpapst/kimai2#1920]
Hi all,

I'm trying to create a custom invoice template.
I have created my-invoice.docx into var/invoices but when i use this template all variables are resolved except ${entry.activity} and ${entry.project}, why?
<img width="352" alt="custom-invoice" src="https://user-images.githubusercontent.com/31856288/91320064-6787a700-e7bd-11ea-8512-77819b281fe0.PNG">

Thank you

**Comment by kevinpapst** [comment]
${entry.project} and ${entry.activity} are pointing to one timesheet record and can only be used in the listing table.

Example: You filter only a custom to create the invoice and have entries across multiple projects => what should be displayed?

If you always create your invoices with project/activity filter you can use the ${project.XXX} and ${activity.XXX} variables, which point to the selected entries from the search form.

**Comment by EdoardoMDP** [comment]
ok thank you!
