### ISSUE TITLE
Server Error 500 when logging in

### ISSUE THREAD

**Issue by laurensk** [kevinpapst/kimai2#1921]
**Describe the bug**
When I try to login to my Kimai2 Server, I get a 500 Server Error. But it's not that easy. When I look at the Logfile, it says "MySQL Server has gone away" but that's not actually true. If I restart the MySQL server, I can Login to Kimai2 for the next 5-10 minutes. After then, active sessions continue to work just fine (I can create, edit, delete time trainings, etc) - just the login process does not work anymore.
Does someone know how I could resolve this issue? Thanks in advance!

**Logfile**
```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.value AS value_3 FROM kimai2_configuration t0':  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away")
```

**Additional context**
 - Kimai version: newest
 - PHP version: newest 7.3

**Comment by kevinpapst** [comment]
I am 100% sure that this is not a Kimai problem., but maybe a connection problem of MySQL. 
Next time when that happens and **before** you restart, try to login into MySQL via bash and the Kimai user to see if the problem exists there as well. Could also be a problem between MySQL, PHP and MySQL.
And then don't restart the database but try to restart only PHP-FPM (or Apache if thats what you are using) and see what happens. Maybe something is keeping the DB connections alive ... or the limit is too low ...

**Comment by laurensk** [comment]
I just tried to only restart PHP-FPM and it does work. When I restart the service, I can log in again (for the next 5-10 minutes) and use Kimai just fine when I don't end the session.

Thanks for the edit, I actually just ran the installer and did nothing else. Do you have an idea where to look?

**Comment by kevinpapst** [comment]
Next time it happens check mysql status to see how many connections are open and who keeps them.

Do you use a custom FPM config or the one from your package manager?

**Comment by laurensk** [comment]
Followed the following guide https://www.kimai.org/documentation/fresh-ubuntu-18.html and installed Kimai on a fresh linux.

**Comment by laurensk** [comment]
Manually restarting PHP-FPM must do something different from restarting the whole server - since I restarted just PHP-FPM yesterday, there hasn't been a problem...
It seems like the problem has been resolved. Thank you @kevinpapst

**Comment by kevinpapst** [comment]
Self-healing problems are the best 😁
