### ISSUE TITLE
On the dashboard the revenue widget isn't working.

### ISSUE THREAD

**Issue by karcsiasd** [kevinpapst/kimai2#1923]
On the dashboard the revenue widget isn't working.

<img width="759" alt="29c7f74c5d29c7fb7ed94c6c25257985" src="https://user-images.githubusercontent.com/55631387/91330362-99066f80-e7c9-11ea-971c-e9144908f4ca.png">

We didn't change the local.yaml file. We've only expanded the hungarian translation and use javascript code to hide some functions.
Do you have any idea what's the cause of the problem?

**Comment by kevinpapst** [comment]
The template for a new issue is there for a reason, my magic is unable to detect your Kimai version or see your logs.

**Comment by kevinpapst** [comment]
There wa a bug in 1.10 regarding a wrong calculation. But it showed too much instead of no data.
You could try to update to 1.10.1.

**Comment by kevinpapst** [comment]
Found out that this is "just another" bug with (older?) ICU versions when displaying money values without currency.
