### ISSUE TITLE
CREATE CUSTOM INVOICE WITH CUSTOM FIELD

### ISSUE THREAD

**Issue by EdoardoMDP** [kevinpapst/kimai2#1928]
Hi all,

I'm trying to create a custom invoice template using custom-field plugin.
I have created Location into en/admin/custom-meta-fields 
![image](https://user-images.githubusercontent.com/31856288/91424228-cdc20780-e859-11ea-8964-bbd13d3715cb.png)
how can i use this variable into template docx?
Can I use something like ${custom.Location}?

Thanks

**Comment by kevinpapst** [comment]
NO NEED TO SCREAM!

Its all in the docs: https://www.kimai.org/documentation/invoices.html#customer-variables

**Comment by kevinpapst** [comment]
`${entry.meta.location}` - but again: only in the description table, as explained in the last issue

**Comment by EdoardoMDP** [comment]
ok thank you very much
