### ISSUE TITLE
Add a description filed in the New Reporting vuew

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1933]
The new reporting functionality in 1.10 is very good. Could you please provide a description or comments field adjacent to each row shown in the reporting field.

If a description filed specific to each row is difficult then one common description field would also be good. Anything entered by the user could be displayed. This would really help in justifying for any gaps in time etc.

**Comment by kevinpapst** [comment]
Please create an example (eg. Excel) to show what you want. I don't understand yet how that should look like and which report you are talking about.

**Comment by kevinpapst** [comment]
No feedback, closing
