### ISSUE TITLE
Reporting - Weekly view for all users, with exporting/printing

### ISSUE THREAD

**Issue by Recoil1980** [kevinpapst/kimai2#1934]
**Is your feature request related to a problem? Please describe.**
This would display a basic weekly breakdown of user hours, for a faster view to calculate payroll.
Ability to print the view of the sheet, with column to display hourly rate * number of hours, would be great.

**Describe the solution you'd like**
A view similar to `Monthly view for all users`, except for that work week.
Column next to user total hours column, for hourly rate * number of hours.
Ability to export/print the weekly view.

**Describe alternatives you've considered**
None at this time

**Additional context**
For our circumstances, this would be a great option along with the starting day of the week being changeable to Friday.

**Comment by kevinpapst** [comment]
Print was added in the last version
