### ISSUE TITLE
User - restrict permission on changing Name, Title, and Profile Image

### ISSUE THREAD

**Issue by Recoil1980** [kevinpapst/kimai2#1935]
**Is your feature request related to a problem? Please describe.**
Not all workers would leave this alone, and will likely put inappropriate names, titles, and profile pictures on fields.

**Describe the solution you'd like**
Permission option to prevent the user being able to change Name, Title, and Profile Picture, while retaining ability for users to change their password. 

**Describe alternatives you've considered**
Setting permission `edit_own_profile` for user stops them from changing password if necessary...I have also considered kicking the users in the head as a counter-measure.

**Additional context**

**Comment by kevinpapst** [comment]
I will not put dedicated permissions on each single field. 
If you users assign dick picks to their profiles, that is likely a social/human problem that cannot be solved via software 😁 
But I will think about extending the usage of the `edit_own_profile` permission.

**Comment by Recoil1980** [comment]
LOL!  They're construction workers and don't have the most professional attitudes...

Setting `edit_own_profile` to false, while still retaining ability to change password, would cover any of those issues.

**Comment by kevinpapst** [comment]
I am not sure if I changed anything in 1.14 that is related to this wish, but it works.
The permissions `view_own_profile` and `password_own_profile` must be granted.
