### ISSUE TITLE
Project Quotes

### ISSUE THREAD

**Issue by Recoil1980** [kevinpapst/kimai2#1937]
**Is your feature request related to a problem? Please describe.**
Project Quotes are a large part of our business, and a plugin or integrated quoting option to track them would keep us from using separate system strictly for job quotes.

**Describe the solution you'd like**
To be able to fill out line items for materials, labor, etc, which can be printed out on a form and delivered to customer on quoting projects.

**Describe alternatives you've considered**
None at this time.

**Additional context**
[GeneralContracting-v4 - Customer Quote.pdf](https://github.com/kevinpapst/kimai2/files/5144921/GeneralContracting-v4.-.Customer.Quote.pdf)

I'm still working my way around, but the Invoices may be able to be utilized for this purpose.

**Comment by kevinpapst** [comment]
I agree that it would be a nice feature, but it definitely needs to go into a plugin. 
Closing for now, too many open requests are pilling up and I don't see a chance that this one will be implemented soon.
