### ISSUE TITLE
Login extremly slow

### ISSUE THREAD

**Issue by anderlk** [kevinpapst/kimai2#1938]
The Login process is extremly slow. After entering username und password it takes between 15 and 30 sec to login to kimai software.

On the same Server there are some other Web Applications (eg. TYPO3) thats works very fast.

**Comment by kevinpapst** [comment]
If it doesn't happen in the Demo it is very likely s a server/env/config issue.
Check your log file.

**Comment by anderlk** [comment]
Thanks, do you mean Server logfile, or is there in kimai a seperatly logfile?

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/faq.html#i-have-a-problem

**Comment by kevinpapst** [comment]
No feedback, closing
