### ISSUE TITLE
Users with teamlead role can view all revenue

### ISSUE THREAD

**Issue by pascal541** [kevinpapst/kimai2#1944]
**Describe the bug**
If an user has the teamlead role, that users can view the revenue of all users instead of only the revenue from the users that are assigned to the team.

**To Reproduce**
1. Give an users the teamlead role
2. Go to the dashboard for that user
3. Dashboard shows all revenue (below own revenue)

**Screenshots**
![image](https://user-images.githubusercontent.com/7486865/91730499-38e74300-eba6-11ea-9907-29dfffe12d15.png)

**Additional context**
 - Kimai version: 1.10.2
 - PHP version: 7.4.9

**Comment by kevinpapst** [comment]
This is related to this config line:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L213
You can change it and set `ROLE_ADMIN` instead of `view_rate_other_timesheet` for now.
Dashboard widgets will become configurable somewhen in the future...
