### ISSUE TITLE
user permission for system configuration sections (here: invoice counter)

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#1945]
Would it be possible to introduce a specific user permission to the invoice counter settings in the "Invoice section" of the user permission table? 

If I want to give a accounting person the right to manipulate the invoice counter, the only way to do so is to grant permission to change the whole system configurations.  

Although I understand that this permission can be seen as part of the system configuration, it is quite likely that the accounting team need the right to set / change the invoice counter instead of a system admin (but the accounting team should not be able to have access to all the other system settings on the other hand)

**Comment by kevinpapst** [comment]
What is the real use-case behind that? An invoice number format should normally not change...

**Comment by BeckeBauer** [comment]
Sometimes, we need an invoice number but cannot create the invoice right away (an external colleague creates the invoice without access to kimai) 

Sometimes, we need to take back an invoice after consultation with the customer (at a stadium were the invoice is still a draft but created with kimai) 

In these cases, our accounting person needs to `play` with the invoice number (first case: go on with invoice numbers and leave the invoice number open for the external colleague; second case: re-use the invoice number although there are later invoices)

But it is really a minor issue if realisation is complicated (since I can give admin right to the accounting person) - let me know and I will close it

**Comment by kevinpapst** [comment]
Hm, I see.
Legit use-case... let's keep this feature request open, can't promise anything though. 
I could imagine that this is needed for other configurations in the future as well.

**Comment by kevinpapst** [comment]
Closing for now, too many open requests are pilling up and I don't see a chance that this one will be implemented soon.
