### ISSUE TITLE
Project/Activity color  in Calendar view

### ISSUE THREAD

**Issue by zeroboioioy** [kevinpapst/kimai2#1946]
After correcting the color display in the Dashboard view, please also correct to see the corresponding colors also in the calendar view instead of all grey.

**Comment by kevinpapst** [comment]
???
<img width="1092" alt="Bildschirmfoto 2020-09-02 um 12 25 46" src="https://user-images.githubusercontent.com/533162/91970084-70293180-ed17-11ea-90da-cf0d4f46a79a.png">

**Comment by kevinpapst** [comment]
I have no clue what you exactly mean. You can re-open the issue if you want to provide more info.

**Comment by zeroboioioy** [comment]
Dashboard looks like this:
![grafik](https://user-images.githubusercontent.com/69542272/92327544-b86b8b00-f05a-11ea-846a-57a4ff4a2364.png)


Calendar looks like this:
![grafik](https://user-images.githubusercontent.com/69542272/92327506-70e4ff00-f05a-11ea-8d20-b1300ffccacb.png)


Obviously there is some difference in color in both views.

**Comment by kevinpapst** [comment]
What exactly has the colors attached in your setup? Customer, Project or Activity?

**Comment by zeroboioioy** [comment]
Most times it's "customer".

**Comment by kevinpapst** [comment]
Okay, its definitely true that the dashboard widget uses a different default color (light blue vs grey) than calendar & dots.
Thanks for spotting, totally overlooked that.

But I cannot reproduce the "missing colors in calendar" yet. If you share a working example I would check it as well.

**Comment by zeroboioioy** [comment]
ok, what do you need as example?

**Comment by kevinpapst** [comment]
Just the exact explanation about the used fields for customer/project/activity and timesheet to see the problem locally.

**Comment by zeroboioioy** [comment]
i created a Customer, color blue:
![grafik](https://user-images.githubusercontent.com/69542272/92402057-39945200-f12f-11ea-8ea3-543bea58f3d7.png)



I also created a Project, no color selected (grey), it inherits the color from the customer (as you see in the screenshot above):
![grafik](https://user-images.githubusercontent.com/69542272/92402228-7c562a00-f12f-11ea-861a-879c9543cfd4.png)



Then I created an Activity, also no color selected (grey), it also inherits the colour from the customer:
![grafik](https://user-images.githubusercontent.com/69542272/92402513-fa1a3580-f12f-11ea-86d8-cac779c3e95c.png)
![grafik](https://user-images.githubusercontent.com/69542272/92402553-08685180-f130-11ea-9fa2-a5dd630bd27f.png)



Then i created a time entry for the activity.
Looks like this in Dashboard, in blue as the customer:
![grafik](https://user-images.githubusercontent.com/69542272/92402718-4f564700-f130-11ea-8c1d-9d1de3530bb6.png)



...and like this in Calendar, color is grey, not inherited from the customer:
![grafik](https://user-images.githubusercontent.com/69542272/92402794-8167a900-f130-11ea-8819-e6909d72f7e5.png)


I prefer that it gets the color from the customer, because it's way to much administration (for me) to set the colors all the way. Maybe there should ne an option to set the colors for anyone who needs it, if not default will be customer color?

Do you need any more information?

**Comment by kevinpapst** [comment]
The correct color should be blue here, as the color should be inherited by the children - unless they overwrite it.
Perfect information, I will try it that way.

**Comment by kevinpapst** [comment]
@zeroboioioy I did a lot of changes in the calendar and think this problem is also gone ([see this PR for more infos](https://github.com/kevinpapst/kimai2/pull/1962)) ...
You can test it at https://demo-branch.kimai.org/en/calendar/ with eg. `susan_super` / `kitten` and [other accounts](https://www.kimai.org/demo/) and let me know if it works better for you now.
