### ISSUE TITLE
Issue with missing timesheets in list / bad left joins

### ISSUE THREAD

**Issue by purebackend** [kevinpapst/kimai2#1948]
**Version**
This was tested on v1.10 and v1.10.2

**Describe the bug**
It requires a specific setup, but when a user goes to https://kimai/en/team/timesheet/ it only shows 1 entry per page instead of 50. It shows multiple pages, if I click on page 2, it will show 1 entry but on page 2.

**To Reproduce**
The specific setup required is:
  The user needs to NOT have the permission of timesheet permission of "view_all_data" 
  The user needs to be in multiple teams that have access to the same project.

1. Log into kimai with the user with the above setup
2. Click on Timesheets
3. Then count the # of records on screen, and see they're not the correct amount.

**Details**
We debugged the code and realized that if they don't have view_all_data, the query then does several left joins. I ran the query directly on the database and got 50 records, but they were all the same one duplicated.
This was because the timesheet record joins teams and projects and it was a many to many.

**Fix**
We temporarily fixed it by adding a ->distinct() call in src/Repository/TimesheetRepository.php on line 691 (in the setQueryBuilderForQuery) function.
Obviously, feel free to fix it however you feel is most appropriate :)

**Screenshots**
This is a screenshot of the duplicate query results. You'll notice its all the same ID
(https://user-images.githubusercontent.com/2199794/92035902-69adb080-ed3d-11ea-93db-558e7c9d7eb3.png)

The query in question is:
SELECT 
  k0_.id AS id_0, 
  k0_.start_time AS start_time_1, 
  k0_.end_time AS end_time_2, 
  k0_.timezone AS timezone_3, 
  k0_.duration AS duration_4, 
  k0_.description AS description_5, 
  k0_.rate AS rate_6, 
  k0_.internal_rate AS internal_rate_7, 
  k0_.fixed_rate AS fixed_rate_8, 
  k0_.hourly_rate AS hourly_rate_9, 
  k0_.exported AS exported_10, 
  k0_.billable AS billable_11, 
  k0_.category AS category_12, 
  k0_.modified_at AS modified_at_13, 
  k0_.`user` AS user_14, 
  k0_.activity_id AS activity_id_15, 
  k0_.project_id AS project_id_16 
FROM 
  kimai2_timesheet k0_ 
  LEFT JOIN kimai2_projects k1_ ON k0_.project_id = k1_.id 
  LEFT JOIN kimai2_customers k2_ ON k1_.customer_id = k2_.id 
  LEFT JOIN kimai2_projects_teams k4_ ON k1_.id = k4_.project_id 
  LEFT JOIN kimai2_teams k3_ ON k3_.id = k4_.team_id 
  LEFT JOIN kimai2_customers_teams k6_ ON k2_.id = k6_.customer_id 
  LEFT JOIN kimai2_teams k5_ ON k5_.id = k6_.team_id 
WHERE 
  k0_.user IN (
    44, 51, 237, 210, 403, 405, 407, 408, 409, 
    410, 411, 412, 413, 414, 417, 418, 419, 
    420, 440, 441, 451, 471, 472, 473, 474, 
    475, 476, 477, 478, 479, 480, 481, 482, 
    490, 491, 492, 518, 519, 520, 521, 522, 
    523, 524, 525, 526, 527
  ) 
  AND (
    k3_.id IS NULL 
    OR EXISTS (
      SELECT 
        1 
      FROM 
        kimai2_projects_teams k7_ 
        INNER JOIN kimai2_teams k8_ ON k7_.team_id = k8_.id 
      WHERE 
        k7_.project_id = k1_.id 
        AND k8_.id IN (79,80,17,60,79,80)
    )
  ) 
  AND (
    k5_.id IS NULL 
    OR EXISTS (
      SELECT 
        1 
      FROM 
        kimai2_customers_teams k9_ 
        INNER JOIN kimai2_teams k8_ ON k9_.team_id = k8_.id 
      WHERE 
        k9_.customer_id = k2_.id 
        AND k8_.id IN (79,80,17,60,79,80)
    )
  ) 
ORDER BY 
  k0_.start_time DESC 
LIMIT 
  50
;

**Comment by kevinpapst** [comment]
I thought it was finally fixed, weird - this is my personal nightmare bug. I tried like 5 different fixes, each with its own trade-off.

Afaik `distinct()` is the stinky brother of group by and only hides the actual issue with the query itself. Your mentioned problem actually existed in all repositories that include these joins to check team permissions (customer, projects, activities, timesheet).

I switched back and forth between several solutions, eg here:
https://github.com/kevinpapst/kimai2/commit/af4101c9fe188ea6156b7027f387a30fcec06794#diff-80798d377dbcd130c5b56358c17f6c7f

This (hopefully) solved the problem in the other repositories.

Can you please try to remove the `->distinct()` and add:
```
$qb->addGroupBy('t')->addGroupBy($orderBy);
```
[in this line](https://github.com/kevinpapst/kimai2/blob/master/src/Repository/TimesheetRepository.php#L840) at the end of the method.

And you have to add a `->resetDQLPart('groupBy')` in `getPaginatorForQuery()` [here](https://github.com/kevinpapst/kimai2/blob/master/src/Repository/TimesheetRepository.php#L645).

**Comment by kevinpapst** [comment]
@purebackend can you provide some feedback on my suggestion above?

**Comment by purebackend** [comment]
Hi Kevin! 

Sorry for the late reply

I applied your recommendations and it now works as expected, however, it caused a large increase in the page load time.
Previously, it was 3 to 4 seconds for the page load, and now its around 15 seconds.
I've attached the 2 queries that took longer then a second during the page load.
Let me know if you need anything else.

![image](https://user-images.githubusercontent.com/2199794/93117550-04d34e00-f68d-11ea-9966-b97fe9bb7c33.png)
![image](https://user-images.githubusercontent.com/2199794/93117584-10267980-f68d-11ea-9558-0c4b5eade71b.png)
![image](https://user-images.githubusercontent.com/2199794/93117642-26343a00-f68d-11ea-8239-7d1c109af689.png)
![image](https://user-images.githubusercontent.com/2199794/93117669-30eecf00-f68d-11ea-98cb-31ae7ceb8956.png)

**Comment by kevinpapst** [comment]
That is alarming feedback, thanks for testing!
So the distinct was faster than the group by?

**Comment by purebackend** [comment]
Oops I forgot to mention that.
The distinct was around 5-6seconds for the page load. So it is not as fast as without but not as slow as the group by.
I've included the 2 queries that are slow on the distinct as well..
![image](https://user-images.githubusercontent.com/2199794/93118666-9d1e0280-f68e-11ea-9667-1ddef403e0a3.png)
![image](https://user-images.githubusercontent.com/2199794/93118708-adce7880-f68e-11ea-97dd-6aa0aabcdc9e.png)
![image](https://user-images.githubusercontent.com/2199794/93118804-d0609180-f68e-11ea-81bb-891449ec6445.png)
![image](https://user-images.githubusercontent.com/2199794/93118820-d8203600-f68e-11ea-89c8-a0015a98835d.png)

**Comment by kevinpapst** [comment]
What kind of hardware are you using? The result ist way too slow in my opinion. 
Or is your timesheet table so large?
Obviously the select to filter permissions is terrible.
Which page are you opening there? Is that the "My times" page or the "team timesheets" for all users?

**Comment by purebackend** [comment]
The hardware is fine. It's a Dell PowerEdge R310, so 16G RAM and Intel(R) Xeon(R) CPU L3406  @ 2.27GHz and SSD drive
There are other sites on the server, but the load average is low (0.3)

The timesheet table has 133871 rows. Is that considered large?

The page is "Timesheets" under "Administration" ie /en/team/timesheet/
The "My Times" loads quick either way. ~2seconds.

**Comment by kevinpapst** [comment]
Haven't done a load test in a longer time, because it's painful to setup. 
But in the past I tested with > 2000000 entries and it wasn't as slow as you mention it.

**Comment by purebackend** [comment]
Maybe it's related to some other relationship.. we have 74 teams, 8 roles, 538 users, 1076 in users_teams, 26 projects, 84 projects_teams

**Comment by portosricos** [comment]
The logic is the following:

1 team is created for a new project. Like this we block everyone for that new project.
Each team leader has a team for the project he has.

**Comment by kevinpapst** [comment]
Oh, well that could be the reason. I don't think I ever tested a setup like that and I don't know any customer with so many users and teams.

Do you see any chance of creating an anonymized database dump? 
It would require a copy of the database which must be prepared with some statements to remove all sensitive data (I would help with all the necessary statements) before dumping.

**Comment by portosricos** [comment]
I need to talk with @purebackend but we could do a database manipulation and overwrite the name logic/ password.

We are using plugins too:
![image](https://user-images.githubusercontent.com/4107501/93123738-96938900-f696-11ea-9848-358e6865bcc7.png)
(the hidden pluggin is just a simple page with links. It doesn't contains nothing.

I could explain the logic for our environment too.

**Comment by kevinpapst** [comment]
Please have a look at the linked PR #2017
