### ISSUE TITLE
Setting framework.session.cookie_lifetime does not seem to have any effect, session always times out after approx 1 hour

### ISSUE THREAD

**Issue by RayCulp** [kevinpapst/kimai2#1950]
**Describe the bug**
A recent update seems to have introduced a short session timeout (approximately one hour, maybe less) that did not previously exist and does not appear to be configurable via framework.session.cookie_lifetime. Regardless of the value set in framework.session.cookie_lifetime, the cookie PHPSESSID always seems to have a lifetime of 2:45. Regardless of this cookie lifetime, the session times out after approximately an hour.

**To Reproduce**

1. Log in
2. Start a new entry, enter some text in the description
3. Wait an hour
4. Try to save the entry
5. The entry cannot be saved because the session has timed out
6. You are redirected to the login page

**Logfile**
Kimai apparently stopped logging about 5 months ago. The last log entry is from 2020-04-18 01:33:58.

**Screenshots**
**ATTENTION! The following screen recording was made using demo.kimai.org**

**Desktop/Smartphone**
- OS: Windows 10 
- Browser: Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Additional context**
 - Kimai version: 1.10.2 stable (Ayumi)
 - PHP version: 7.4

**Comment by kevinpapst** [comment]
There was an update, yes: sessions are now stored in the database.
Check your PHP session configuration via `php -i |grep session` and paste the output here please.
Kimai does not handle the session lifetime (yet). It just uses what is configured in the environment.

**Comment by RayCulp** [comment]
session
session.auto_start => Off => Off
session.cache_expire => 180 => 180
session.cache_limiter => nocache => nocache
session.cookie_domain => no value => no value
session.cookie_httponly => 0 => 0
session.cookie_lifetime => 0 => 0
session.cookie_path => / => /
session.cookie_secure => 0 => 0
session.gc_divisor => 100 => 100
session.gc_maxlifetime => 1440 => 1440
session.gc_probability => 1 => 1
session.lazy_write => On => On
session.name => PHPSESSID => PHPSESSID
session.referer_check => no value => no value
session.save_handler => files => files
session.save_path => /var/lib/php/sessions => /var/lib/php/sessions
session.serialize_handler => php => php
session.sid_bits_per_character => 4 => 4
session.sid_length => 32 => 32
session.upload_progress.cleanup => On => On
session.upload_progress.enabled => On => On
session.upload_progress.freq => 1% => 1%
session.upload_progress.min_freq => 1 => 1
session.upload_progress.name => PHP_SESSION_UPLOAD_PROGRESS => PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix => upload_progress_ => upload_progress_
session.use_cookies => 1 => 1
session.use_only_cookies => 1 => 1
session.use_strict_mode => 0 => 0
session.use_trans_sid => 0 => 0
session.trans_sid_hosts => no value => no value
session.trans_sid_tags => a=href,area=href,frame=src,form= => a=href,area=href,frame=src,form=

**Comment by kevinpapst** [comment]
These are default setting `session.gc_maxlifetime => 1440` meaning 24 minutes. 
You might want to raise this value in your php.ini.

Please be aware: the 24 minutes is be the time that is allowed between two distinct action (each page reloads) before a session expires. If a new page is loaded after 25 minutes, the session might be expired and deleted.

BTW: please don't post links to that video page anymore. The first thing I saw was a "wanna fuck me?" fake notification message. 👿

**Comment by RayCulp** [comment]
Very sorry that happened with the lewd advertising with the video link! I have every ad blocker under sun plus a hosts file with tens of thousands of entries, so I literally did not even know it was there!

I am not sure I can make the required modifications to the php.ini file because I'm on a shared hosting solution, but I will get back to you soon! Thanks again!

**Comment by RayCulp** [comment]
Ok, so my hosting provider already answered my ticket. I cannot change the value, but they can do it for me. However, I have to tell them what the new value should be. I'm not a PHP programmer. From your point of view, do you think there might be any issues -- perhaps affecting other programs running on the same server -- if I ask them to set the value to six hours (21,600 seconds)? Any guidance is greatly appreciated!

**Comment by RayCulp** [comment]
I did some research, and according to this [Stackoverflow article](https://stackoverflow.com/questions/14703363/why-is-the-standard-session-lifetime-24-minutes-1440-seconds), the original value for sessions was 24 hours (1440 minutes). In view of this, I think it's unlikely that a value of six hours will cause problems. While this may be a viable solution, I still don't quite understand why this behavior only cropped up after a recent update. Do I understand correctly that the change to storing the sessions in the database caused it?

**Comment by kevinpapst** [comment]
I cannot recommend any specific value, this is up to you.
All I can say is: the "problem" was just made visible with the change. I don't fully understand why it did not time out earlier in older versions, but it seems to be "correct" behavior - even though unexpected due to the previously experienced longer sessions. 

I do understand why the session did not end earlier before the update. Maybe I will add a setting in the future to set the session lifetime for Kimai explicit.

**Comment by RayCulp** [comment]
Thanks Kevin!

**Comment by kevinpapst** [comment]
Re-open, because I need to change the documentation

**Comment by RayCulp** [comment]
Ah, ok sorry, I'm still very new to Github! :-)

**Comment by RayCulp** [comment]
After I asked the hosting provider to set the value to 6 hours (21600 seconds), none of us can log in anymore. We get "Invalid CSRF token" error. I asked the provider to reset it back to 1440 seconds and will keep you posted on what effect this has.

**Comment by kevinpapst** [comment]
Try to delete all cookies first, if possible before the hosting provider turns it back.

**Comment by RayCulp** [comment]
I did this and also tried with Microsoft Edge and Waterfox classic, which I have never used to access kimai, but still the same error.

**Comment by RayCulp** [comment]
Ok, so our provider set framework.session.cookie_lifetime back to the old value, but it didn't help. I did a clean install of Kimai in a new folder, exported the old database (minus the records in the sessions table), imported the SQL file into the new DB, and now everything is working fine again. Kind of unsatisfying not knowing exactly what caused the problem, but since everything is working now, I'm happy.

**Comment by kevinpapst** [comment]
There is most certainly no reason to re-install Kimai. That is really weird, I cannot imagine what should have caused the issue.
Did your hoster tell you, which PHP setting was changed exactly?

**Comment by RayCulp** [comment]
Yes, the parameter was framework.session.cookie_lifetime, and it was initially changed on my request a few days ago from 1440 seconds to 21600 seconds. 

Shortly after that, Kimai began to give the "Invalid CSRF token" error mentioned above. 

My **assumption** was that the error had something to do with the change to this parameter. However, when my hoster changed it back to 1440 seconds on my request, the error did not go away. 

For this reason, all we can really say is that there was a correlation between the change and the error appearing. It is not at all established that there was a causal relationship.

In any case, it's working again. :-)

**Comment by kevinpapst** [comment]
Did your hoster change the Kimai setting or did they change the PHP setting? That's a massive difference.
We talked about `session.gc_maxlifetime` and then you mention `framework.session.cookie_lifetime`.

Changing the value `framework.session.cookie_lifetime` will not even have any effect, without reloading the Kimai configuration. Did they do that?

You said you are happy now, so we could say: all settled. But I'd like to ask you: what happens next time when you ask your hoster for a change? A dedicated and Kimai compatible server costs ~10€ per month and we are talking about a software to manage employee times, invoices, your income ...

**Comment by RayCulp** [comment]
You're right, I made a mistake. Our hosting provider did not modify `framework.session.cookie_lifetime`, they modified `session.gc_maxlifetime`.

I actually have a virtual private server to play around with, but I'd be a fool to think I can administrate it and keep it secure, at least with my current almost non-existent knowledge of Linux, and I most certainly do not have time to learn how to do it right and take on that role as well. This is why we use a shared hosting service. The hoster makes sure the underlying systems like Linux, the web server, PHP, MySQL and so on are running correctly and securely, I install whatever I need on top of that. If I need help, they do their absolute best to help. I've been with them for 13 years, and this has earned me the privilege of being able to call up the head of customer service directly if something is not getting solved. It has been a very good arrangement so far and I am very happy with it.

**Comment by kevinpapst** [comment]
Sounds very positive! 
Back to topic: The default PHP setting for the session timeout is simply too low, but from my perspective this is nothing that the application should take care of. 
I will investigate that topic asap, as it is at least an annoying problem.

**Comment by kevinpapst** [comment]
@RayCulp I added new documentation for the session lifetime at https://www.kimai.org/documentation/users.html#session-lifetime
