### ISSUE TITLE
FTP installation problems

### ISSUE THREAD

**Issue by wildview** [kevinpapst/kimai2#1954]
Hi, I've been using Kimai1 for the last 4yrs and have loved it. I want to upgrade to Kimai2, but my hosting server doesn't support ssh/git support. Therefore, I went the FTP approach and copied all the files into a folder call Kimai2 on my hosted server. Based on the FTP installation document it says to point your domain (document root) to the public/ directory, how do I that? The FTP installation is not very detailed, so if someone can guide me through this I would appreciate it since I'd love to update to the newer version, but I'm not a server IT expert. I have Kimai1 SQL database backed up, do I need to migrate this over to use /w Kimai2? If so, are there instructions for this? Tnx.

**Comment by kevinpapst** [comment]
I cannot provide support for FTP. 
There is documentation for the migration process, but I never tried it with a FTP (SQLite) installation.

FTP is crap. Hosting providers that don't support SSH as well 👎 
Sorry, but I have to close the issue as this is out of scope of free help.
