### ISSUE TITLE
Forgot Password link redirecting

### ISSUE THREAD

**Issue by groovyrb** [kevinpapst/kimai2#1956]
**Describe the bug**
When I do forgot password I recieve email but when I click on link to reset password it redirect me to page where it again ask me email id to reset the password. it happen most of the time, previously also it happen so I remove kimai and  install it again but right now it live in production so I cant do that. please check 
I have created your **info** id so you can test it [link](#)
And I have another qa enviorment setup where it is working fine. but on Live and Dev env it's not working. One more thing how to modifiy the 2 hour forgot password link to minimim or how to remove this validation?

**Comment by groovyrb** [comment]
I found The issue It occur due to modification in resetting controller setPasswordRequestedAt() as empty, Can you let me now how to decrease the forgot password time from 2 hour to less or max 30min?

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/blob/master/config/packages/fos_user.yaml#L11
