### ISSUE TITLE
Rounding changes end time on timesheet entry edit

### ISSUE THREAD

**Issue by apiening** [kevinpapst/kimai2#1959]
**Describe the bug**
When **Rounding of the duration in minutes** is used with a positive value, the **End** time is set to **Begin** + **Duration** when the entry is edited.

**To Reproduce**
1. Go to **Settings** /  **Time rounding** and set **Rounding of the duration in minutes (0 = deactivated)** to 15 (minutes).
2. Click on **My times** and create a task. 
3. Stop the task after a minute or so. The **duration** is correctly set to **15 minutes** automatically, based on rounding!
4. Edit the task, update the description and save.
5. The End time has been updated to **Begin** + **Duration**.

This is wrong, since the end time should not change when only the description is updated.
This also leads to overlapping tasks, even though the real end time does not overlap with a following task. Rounding should only be used to round the duration.

**Additional context**
 - Kimai version 1.10.1
 - PHP version 7.4.9

**Comment by kevinpapst** [comment]
This does not happen for me. 
Please attach a screenshot of your system settings (the complete **Time rounding** box) after verifying that this happens on the demo as well.

**Comment by kevinpapst** [comment]
Any feedback @apiening , so I can investigate further?

**Comment by apiening** [comment]
Hi @kevinpapst,
I'm sorry for the delay.

I just checked the described issue with the demo instance at https://demo.kimai.org and it still happens.

Here is a screenshot of the rounding settings:
![Bildschirmfoto 2020-11-13 um 13 31 16](https://user-images.githubusercontent.com/2064875/99074212-a4428d80-25b7-11eb-83fc-0a70e6f76f81.png)

I have created three tasks in the **My times** section: One with a difference of just one minute between **Begin** and **End** time. The Duration was rounded to 00:00 accordingly to the settings, which is correct. (By the way this is not really what I want, because I always want my customer to be charged for the first unit of 15 minutes, even if the duration is below 7.5 minutes. I'm applying mathematical rounding just for the second and every following 15 minutes period. But that's not the point of this issue.)
Another task was started right away and it was stopped with a difference of 8 minutes between Begin and End time. This time it was rounded to 00:15 which is again, correct!
The third task was started directly after the second one has been stopped. It was stopped after 8 minutes and was correctly rounded to 00:15.
Until now, everything is fine and matches the expectation.

Then I have edited the second task, updated the description and clicked **save**. This time the **End** time has been adjusted based on the 00:15 minutes duration that was a result of the rounding of the real duration of 8 minutes. Not only is the real End time of the task lost (it has been recalculated and overwritten automatically), the task now overlaps with the third task which has been started right after the second task. That's why it is marked with a red dotted line.

Here is a screenshot of the result:
![Bildschirmfoto 2020-11-13 um 13 51 58](https://user-images.githubusercontent.com/2064875/99075515-e8369200-25b9-11eb-9255-dda314bdda4a.png)

To clear things up: The rounding does work correctly, but the **End** time should not be recalculated if just the **Description** field has been updated.

I hope this example helps to reproduce the issue.

**Comment by kevinpapst** [comment]
Thanks for the details. Agreed. 

I understand what happens: the javascript in the frontend triggers a recalculation of the values whenever one of the (start/end/duration) fields looses focus. After opening the modal, the focus is already inside one of the fields. When you now click to the description field, the end value is adjusted. So it is not a rounding issue, but an issue with the frontend.

Can you confirm that?

**Comment by apiening** [comment]
Yes, that's exactly what I observed.
