### ISSUE TITLE
Timer Exceed more than 24 Hour?

### ISSUE THREAD

**Issue by groovyrb** [kevinpapst/kimai2#1960]
**Describe the bug**
Need Suggestion: If an user start a timer or fill a timesheet then how to stop user not to fill timesheet more than 24 hour a day?
From Api also it takes more than 24 hour entry for a day? Or is there any setting to do that?

**Comment by kevinpapst** [comment]
You can create tasks that are longer than 24 hours, yes. 
There is no validation existing currently to prevent that.
And there is no automation that prevents log running entries or stops them automatically.

I am planning to setup a simple cron logic for tasks like that, but well ... so many pending feature requests ...

**Comment by kevinpapst** [comment]
See #141

**Comment by kevinpapst** [comment]
If you have a custom plugin, there are multi possible solutions:
- You can add a Symfony Form Extension (`class X extends Symfony\Component\Form\AbstractTypeExtension`) that extends the Timesheet Edit form and registers a Form event subscriber to execute that kind of validation.
- You can implement a [Timesheet constraint](https://github.com/kevinpapst/kimai2/blob/master/src/Validator/Constraints/TimesheetConstraint.php), which will be automatically called upon saving.

Anyway: this is a nice idea for a new system configuration, sounds as if more users could benefit from such a feature.

**Comment by kevinpapst** [comment]
There is a new system setting, that should solve your problem:
<img width="709" alt="Bildschirmfoto 2021-11-10 um 12 55 04" src="https://user-images.githubusercontent.com/533162/141108616-a63faede-481d-4e7c-8bff-74dece96edbe.png">

It does not automatically stop these entries, it just prevents to save them
