### ISSUE TITLE
Kimai data for Lexware Accounting

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1961]
**Is your feature request related to a problem? Please describe.**
The export of data from Kimai to Lexware in no prpblem, because Lexware needs only ASCII (CSV) Data.
Issue: Two important infos are missing for a complete export:
- the invoice date of last month for every user
- the invoice number of last month for every user

**Describe the solution you'd like**
two exportable data fields, automatically filled in every project when creating invoices.
The Invoice number should be editable.

**Comment by kevinpapst** [comment]
Can you elaborate on that? I don't understand that issue good enough for discussion

**Comment by HeinzWuert** [comment]
Would like to close this and open a few days later a new one with more detailed informations.
