### ISSUE TITLE
Rounding problem (forcing error) when prohibiting time overlaps

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1963]
**Describe the bug**
Practice shows that users book times according to the following example
Appointment 1: 10: 30-11: 00
Appointment 2: 11: 00-12: 00
This procedure already generates an error message caused at 11:00.
Even if the user records 10:59, the time is rounded to 11:00, causing an error too.

**To solve the issue**
Simple solution: Allow an (optional?) time overlap of 1 minute.

**Comment by kevinpapst** [comment]
"Simple" only from a logical perspective, not from the view of the developer 😁

**Comment by HeinzWuert** [comment]
Simple in the way, that bookings are allowed, when end time and start time of the follower are identical. Is there a difference > 1 minute overlapping becomes active.
For me it's only a boolean operation ;-)
For u I don't know 😁

**Comment by kevinpapst** [comment]
Yep, unfortunately the check for an existing timesheet is a rather complex operation due to all possible combinations of time-ranges and is currently done on the database layer.
A quick fix might be to add/remove one second when checking the database.

**Comment by HeinzWuert** [comment]
However, you will find a working solution!

**Comment by kevinpapst** [comment]
@HeinzWuert Does that still happen? I remember working on it and there is a referenced commit. So I assume it is fixed?

**Comment by HeinzWuert** [comment]
Fixed! As far as I remember you changed the seconds of the booked time to prevent overlapping.

**Comment by kevinpapst** [comment]
👍 Yes, I am adding one second for the comparison. One fixed, yeah!
