### ISSUE TITLE
Eye function: mark/unmark of fields followed by page changing has no effect

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1964]
**Describe the bug**
Eye function: mark/unmark of fields works first, but scrolling to the next page and a rechange has no effect.

**To Reproduce**
See picture.
Simple changing mark/unmark of fields, than change to the next page
Another effect: Changes were submitted for the actual page. Scrolling to the next page forgets the setting.

![Screenshot 2020-09-10 201025](https://user-images.githubusercontent.com/45666972/92778770-c3e3ec80-f3a1-11ea-854e-edc29ef5912e.png)
The picture is showing the state with the unmarked fields. No changes were made!

**Comment by kevinpapst** [comment]
Cannot reproduce that. Settings are stored in cookies, so if your browser does not accept cookies or some plugin interferes with them it might not work. Or if you have too many cookies, this maybe fail too. 
Not sure about the browser settings and how much data is allowed.

**Comment by HeinzWuert** [comment]
We will test it. Meanwhile close this posting. Will write a new one when the issue seems to have another cause.

**Comment by kevinpapst** [comment]
Ok
