### ISSUE TITLE
Remove CLA from Weblate component

### ISSUE THREAD

**Issue by comradekingu** [kevinpapst/kimai2#1965]
Copyright and licensing is already covered in point 6.4 of https://hosted.weblate.org/legal/terms/
and that is already stated in https://hosted.weblate.org/projects/kimai/#information

**Comment by kevinpapst** [comment]
I registered with Weblate a couple of hours ago for testing and appreciate any feedback.
But please speak with me like a child, as I have no clue what you want to tell me ;-)

**Comment by kevinpapst** [comment]
So you mean this:
<img width="748" alt="Bildschirmfoto 2020-09-12 um 00 14 47" src="https://user-images.githubusercontent.com/533162/92977324-02a2a100-f48d-11ea-8fdd-6389b64f6562.png">

**Comment by comradekingu** [comment]
@kevinpapst Yes :) Scrap the "Mitwirkungsvereinbarung".

**Comment by kevinpapst** [comment]
Please retry

**Comment by comradekingu** [comment]
@kevinpapst The info you put in that field is not needed. This is because it is already accepted by the user.
This happens when the user registers for Hosted Weblate.

Since the user has already registered for Weblate when the user sees the info, the info is not needed.

If the user sees there is info in this field the user will often be discouraged. This is because there it is usually a field where project owners claim all rights to the work.

**Comment by kevinpapst** [comment]
Thanks! 
But I kinda did the opposite with the MIT license, didn't I? 
Or is that because you see the banner on top of the repository and don't yet know what is inside?

**Comment by comradekingu** [comment]
@kevinpapst 
You can use an announcement to tell translators there is a MIT license if you want.
https://hosted.weblate.org/projects/kimai/#announcement
The license information is always available in https://hosted.weblate.org/projects/kimai/#information anyway.
Closing as my issue is fixed. Thanks :)
