### ISSUE TITLE
Export - change default setting

### ISSUE THREAD

**Issue by Brdisek** [kevinpapst/kimai2#1971]
Hi, 
is it possible to change default setting in Export - Filter data for export? I would like to have in Exported line All  in stead of Open. In line Records the same All in stead of Stopped. 
How can I change it in my Super-Admin account? 
Thanks for help.

**Comment by kevinpapst** [comment]
You can't. At some point in time I might add a feature to store search form settings.
Then this topic would be covered automatically.
But I have no plans on adding custom settings for the export form only.
Closing, as this is no feature that I plan to add explicit.
