### ISSUE TITLE
Invoice creation: Different ordering in web-interface compared to command line

### ISSUE THREAD

**Issue by apiening** [kevinpapst/kimai2#1972]
**Describe the bug**
When an invoice is created with the web UI, the entries are ordered ascending by date.
However, when I create an invoice based on the same template from the command line, the entries are sorted descending by date.

Is there any way to override / force the ordering so that it is always by date, ascending?

**To Reproduce**
1. Create an invoice template based on **PDF document**.
2. Create an invoice based on the newly created template. Make sure that there are sufficient entries in the selected time range. The entries in this invoice should be ordered by date, ascending.
3. Create a new invoice based on the same template, but from the command line:
```bash
bin/console kimai:invoice:create --user=<user> --timezone=Europe/Berlin --customer <n> --template="<templatename>" --start=<from-date> --end=<to-date>
```
The order of the entries is now reversed (ordered by date, descending).

**Additional context**
 - Kimai version 1.10.1
 - PHP version 7.4.9

**Comment by kevinpapst** [comment]
Hm, true. Will fix it for the next version.

In the meanwhile you can add that new line here: https://github.com/kevinpapst/kimai2/blob/master/src/Command/InvoiceCreateCommand.php#L241

```php
        $defaultQuery->setOrder(InvoiceQuery::ORDER_ASC);
```

This will fix the order in the command.

**Comment by apiening** [comment]
Wow that was quick, thank you very much!
Please can you link to this issue when the next version is released, so that I get notified?

**Comment by kevinpapst** [comment]
This issue will be closed when it is fixed in the code (which does not mean it is released, unless you have master installed). 
Please watch the repository for release notifications.

**Comment by apiening** [comment]
Ok, watching the repo now.
Thanks.
