### ISSUE TITLE
Add option to make specific fields readonly

### ISSUE THREAD

**Issue by mike1573** [kevinpapst/kimai2#1974]
**Is your feature request related to a problem? Please describe.**
Some fields (regular & meta) in Timesheets, Activities, Projects and Users are set by Admins and should only be changeable by an Admin. We need users to view the records but currently they can change them which is a problem.

**Describe the solution you'd like**
In permissions or via another screen or yaml file we should have an option to make specific fields not edit/greyed-out to selected users/groups.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kevinpapst** [comment]
some fields are already protected. any examples to share (both: which fields and why)?
because "some fields" is a bit vague...

**Comment by mike1573** [comment]
Hi Kevin,
    Let's use Any instead of Some ...fields should have the option to be veiwable but protected from change.
Example: If an Admin/Lead creates a timesheet on behalf of an employee for a specific Activity, then (i) the User, (ii) the Activity, (iii) the Project, (iv) the Customer fields should not be changeable by the employee because if they do change these, the Timesheet would be inaccurate and not aligned with the project. The could also be the case for specific Meta fields which were filled with project data for the employee to see but should not be changed.

I know we can set permission on who can see/not see the field (but not may who can see but not change). If I missed it, can you point me to which fields are already protected like this and where/how to manage these to achieve the above?

Thanks
Michael

**Comment by kevinpapst** [comment]
Definitely a edge case use-case, which can be sponsored by a company. Otherwise: wont fix
