### ISSUE TITLE
Export - CSV

### ISSUE THREAD

**Issue by dima1002** [kevinpapst/kimai2#1976]
Is it possible to create such an CSV export? Attached an example.
![export](https://user-images.githubusercontent.com/15138232/93051333-98dcef80-f664-11ea-9938-de5c344e7496.JPG)

**Comment by kevinpapst** [comment]
Basically yes, but currently not without development work.

Currently export templates aren't available for CSV. 
So you could either try to use an invoice template (not the best way) or someone has to create a CSV export renderer:
https://www.kimai.org/documentation/export.html#adding-export-templates

**Comment by dima1002** [comment]
How much effort would it take to develop it?

**Comment by kevinpapst** [comment]
A couple of hours. Then you would be able to add CSV templates and define the columns yourself.

**Comment by kevinpapst** [comment]
no feedback, closing
