### ISSUE TITLE
Implement Event Subscriber

### ISSUE THREAD

**Issue by scolson** [kevinpapst/kimai2#1977]
**Is your feature request related to a problem? Please describe.**
When someone interacts with the system to add a new time entry, adding a new customer, or generating an invoice, I would love to be able to tie in to the process and alter the data, kick off some 3rd party process, perform lookups and validation, or other inline flow changes. For example, in concert with MetaFieldsBundle, allow the system to record an issue ID from an issue tracker, and have realtime alterations of allowed values and validation.

**Describe the solution you'd like**
Ideally, I would love to see an implementation of the Symfony Events and Event Listener system. As a few other aspects of Kimai already use event listeners, this does not feel like a major refactoring. I would love to see separate events for create, read, update, and delete of the different objects, so that relevant data can be injected or passed along. In the above example, a custom event subscriber could alter allowed values in a dropdown for a given user based on the then-current issues assigned to that user for the client or project in question.

**Comment by kevinpapst** [comment]
I guess you have seen the existing events: https://github.com/kevinpapst/kimai2/tree/master/src/Event
Its simply impossible to foresee all possible use-cases, so I normally add new events when when I need them myself.

So if you have ideas or use-cases where you need new events (you seem to know what you are talking about) then please go ahead and sent in a PR. Will be much faster than asking me to add them one by one 😁

**Comment by kevinpapst** [comment]
No feedback, closing
