### ISSUE TITLE
Kimai Custom User Plugin 

### ISSUE THREAD

**Issue by groovyrb** [kevinpapst/kimai2#1979]
**Is your feature request related to a problem? Please describe.**
I need to buy Custom Field plugin but I have some questions before I buy it,
1: I need to create some custom fields for User section like (location,number,employee id and so on)
2: The custome field created in user section should come in API(location,number,employee id etc..).
3: Is that Possible? if yes then it is great good to go with this plugin but.
4: If that is not possbile so how to make it possible to do so, because we mostly use mobile app only and use kimai API for that.

**Describe the solution you'd like**
I know there is Model.User.yml in serializer where we allowed fields in user api so is that possible if I add custome field there and in User API.

**Comment by kevinpapst** [comment]
In your case I cannot recommend using the plugin, due to your customizations in Kimai.
Updates would be (at least) complicated.
And user-preferences are generally not available in the API yet.

**Comment by groovyrb** [comment]
Hi Kevin,
Thanks for the reply.




Thanks and Regards,


*RAHUL RAJORIA*

*Sr. Software Developer | Left Right Mind Pvt Ltd.*

*Left Right Mind,  Business Bay, Plot No. 84, Wellesley Road** Pune-411014*

Ph.: +91 9993881314 <rahuraj225@gmail.com> | Alt: +91 9168671825

Email : rahuraj225@gmail.com | Website :www.groovyrb*.wordpress.com*
<http://www.groovyrb.wordpress.com>
