### ISSUE TITLE
CUSTOM FIELD ERROR 500

### ISSUE THREAD

**Issue by EdoardoMDP** [kevinpapst/kimai2#1981]
Hi all,
I have installed plugin on /var/plugins and reloaded cache.
When i click on custom field button i got this error:

HTTP 500 Internal Server Error
`An exception occurred while executing 'SELECT t0.id AS id_1, t0.entity_type AS entity_type_2, t0.name AS name_3, t0.label AS label_4, t0.help AS help_5, t0.value AS value_6, t0.type AS type_7, t0.visible AS visible_8, t0.required AS required_9, t0.permission AS permission_10, t0.section AS section_11, t0.weight AS weight_12, t0.customer_id AS customer_id_13, t0.project_id AS project_id_14, t0.activity_id AS activity_id_15 FROM kimai2_meta_field_rules t0 ORDER BY t0.weight ASC':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.section' in 'field list'`

Could you help pleas?
Thanks

**Comment by kevinpapst** [comment]
Execute `bin/console kimai:bundle:metafields:install` and retry

**Comment by EdoardoMDP** [comment]
Thank you cery much! i have also this error:
```
An exception occurred while executing 'SELECT COUNT(DISTINCT k0_.id) AS sclr_0 FROM kimai2_ext_log_entries k0_':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai.kimai2_ext_log_entries' doesn't exist
```
what can I do?
Thanks

**Comment by kevinpapst** [comment]
Can you please sent me an email with your gumroad receipts (or the email used for purchase) to info@keleo.de and I will invite you to the repositories for the plugins

**Comment by kevinpapst** [comment]
You need to create the database for the bundle:
```
bin/console kimai:bundle:audittrail:install
```

Actually it's all in the documentation 😁 
https://www.kimai.org/store/audit-trail-bundle.html#installation (last heading: database)
