### ISSUE TITLE
only john_user works for "latest stable" demo

### ISSUE THREAD

**Issue by tangeloservices** [kevinpapst/kimai2#1983]
I'm unable to login using any other user except john_user. tony_teamlead, anna_admin, susan_super, and admin do not work, presenting the message "invalid credentials" when clicking sign in button.

**Comment by kevinpapst** [comment]
I cannot guarantee that these logins work all the times. If someone deletes these users or changes their password it doesn't work until the next automated installation.

But in this case it works for me with all users... you are talking about http://demo-stable.kimai.org/ right?

**Comment by tangeloservices** [comment]
yes, i was - but that was yesterday, sorry; i didn't hit the post button before i walked away from my home workstation. the logins are working for me now, apologies for the noise. looks like a fantastic project, thank you!

**Comment by kevinpapst** [comment]
😄 happy testing!
