### ISSUE TITLE
Trying to add comments to Activities

### ISSUE THREAD

**Issue by wilmerterrero** [kevinpapst/kimai2#1985]
**Describe the bug**
I'm trying to add comments to Activities section but I got some issues with that. The form is not displayed. I have everything the same.

**To Reproduce**
All the files are the same like others comments.

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Browser [chrome]
 - Version last]

**Comment by kevinpapst** [comment]
Activities don't have support for comments yet. So I added the "feature request" label.

**Comment by wilmerterrero** [comment]
How could I do it on my own?
I imitated the whole process you did to add comments to the other things. But the form is still not showing.
I created the Controller, the Entity, etc.

**Comment by kevinpapst** [comment]
Ah okay. But without seeing your changes that is impossible to know. Can you sent a PR?

Did you adjust the detail template like so:
https://github.com/kevinpapst/kimai2/blob/master/templates/customer/details.html.twig#L142

**Comment by wilmerterrero** [comment]
Yes. I did it. I'll do a PR

**Comment by kevinpapst** [comment]
Awesome 👍
