### ISSUE TITLE
german date field output in kimai:invoice:create 

### ISSUE THREAD

**Issue by slowguitar** [kevinpapst/kimai2#1987]
Version:

kc kimai:version
`Kimai 2 - 1.10.2 stable (Ayumi) by Kevin Papst and contributors.
`
php version: 7.2.33

the date output field is formated in excel 2020-09-XX if we create kimai:invoice:create . From Webgui output is correct in german format.

Run command:
`kc kimai:invoice:create --user userbla -vvv --timezone=Europe/Berlin --customer=44 --template="Standardabrechnung" --start=2020-09-01 --end=2020-09-30
`
If i create a php shell script and print date eg., then output correct in german.

**Comment by kevinpapst** [comment]
Sorry, I don't get it. There are so many information missing... show me the generated file, show me the invoice template configuration, show me the language preference of userbla

**Comment by philippgiere** [comment]
Hi Kevin,
attached you will find the Template and the generated file. 
The Server is completely set to german Locale:

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=de_DE.UTF-8

Also the PHP cli php.ini timezone is set to Europe/Berlin


[2020-09-13-animate.xlsx](https://github.com/kevinpapst/kimai2/files/5268353/2020-09-13-animate.xlsx)
[Standard.xlsx](https://github.com/kevinpapst/kimai2/files/5268335/Standard.xlsx)

Thanks in Advance!

**Comment by kevinpapst** [comment]
Everything looks ok by now. English is fallback if your invoice template  has no explicit language configured and Kimai is not running via WebUI (fallback there is afaik the current request locale).

Still waiting for 2 answers (screenshots please) to my above questions.

**Comment by philippgiere** [comment]
Sorry Kevin, the problem very often sits in front of the pc - it was my fault. I copied the template and forgot to set the language for the template properly .... 
Thanks and best Regards
Philipp

**Comment by kevinpapst** [comment]
So it works now as expected?

**Comment by slowguitar** [comment]
Yes - stupid man for the PC :-) it works now
Best regards!
Thomas

**Comment by kevinpapst** [comment]
Not all config settings in Kimai are self-explaining. Even worse when a behavior changes by an update.
I expected a bit of crunching with that change.
