### ISSUE TITLE
TimeBudget API show used/available budget

### ISSUE THREAD

**Issue by thelatch** [kevinpapst/kimai2#1990]
**Is your feature request related to a problem? Please describe.**

It is possible to see the used and available time budget via the web interface, but this is not possible via the API. Here you can only see the total time, but not the used or still available time budget. 

**Describe the solution you'd like**
The possibility to query used and available time budgets via API

**Comment by tobiasgraeber** [comment]
+ API should allow to update time budget per projekt/activity/customer 

And i noticed one more thing:
Could it be, that currently, only "project"-based time budgets are reflected (shown) in data-exports (with remaining budgets) and that budgets on activities / customer.level are not (yet?) output in reports currently?

**Comment by kevinpapst** [comment]
This is clearly a feature used by (larger) companies, so I am happy to work on it, as soon as someone will financially back the development.

**Comment by kevinpapst** [comment]
talk to your companies who are using kimai about sponsoring features. closing until then
