### ISSUE TITLE
Token problem

### ISSUE THREAD

**Issue by accaraffaelecolarusso** [kevinpapst/kimai2#1991]
Hello Kevin,
I agree on the choice to use tokens with a short duration to protect data security but, in my specific case, the duration of the token is too short and this involves a loss of time optimization because, both me and and my colleagues, we are forced several times a day to clean the cache and log in, especially for those who take a little longer to enter and confirm a registration.
Following what has been said, I ask you to kindly tell me, if possible, how to change the settings relating to the token in order to increase the duration of the token by at least 1 or 2 hours.

Thanks for the attention
Raffaele Colarusso

**Comment by kevinpapst** [comment]
The CSRF token has no explicit lifetime but it is bound to the session of the user. 

If the session expires too soon, then this is likely the cause of the default PHP setting. being only 24 minutes.
You need to change your session lifetime either on the server or configure Kimai to manage it.

I updated the documentation with more information how to do that:
https://www.kimai.org/documentation/users.html#session-lifetime

**Comment by accaraffaelecolarusso** [comment]
Thanks

**Comment by kevinpapst** [comment]
Please let me know if that helped, so we can close the issue

**Comment by accaraffaelecolarusso** [comment]
Yes, now it's ok
