### ISSUE TITLE
Feature request: button for decimal format

### ISSUE THREAD

**Issue by SaroTaz** [kevinpapst/kimai2#1992]
It is a possibility to add a button for viewing (converting in real-time) the duration in decimal format?
It would be very usefull for payroll preparation (in italy all times are in decimal format).

**Comment by kevinpapst** [comment]
A user-specific configuration would be nice for that.

**Comment by RayCulp** [comment]
I'd love to see this too. We use a separate system to generate invoices for clients, and we always have to convert Kimai's hh:mm format to decimal manually to enter the right values in that system.

**Comment by kevinpapst** [comment]
Both export and invoice module offer options to show durations in decimal.

**Comment by RayCulp** [comment]
I'm looking for the option in export, but I don't see it. Could you point me to the right menu item?
![image](https://user-images.githubusercontent.com/7621330/97810193-6c138480-1c72-11eb-9075-b4df525b2959.png)

**Comment by kevinpapst** [comment]
User Preferences:
<img width="490" alt="Bildschirmfoto 2020-11-01 um 18 54 08" src="https://user-images.githubusercontent.com/533162/97810372-a03b7500-1c73-11eb-80c9-99d58425a3bb.png">

**Comment by RayCulp** [comment]
Brilliant! Thanks!
