### ISSUE TITLE
White Login Screen New Install on Fedora 32

### ISSUE THREAD

**Issue by gjcarter2** [kevinpapst/kimai2#1996]
I have a Fedora 32 Server which I recently pulled to install Kimai2 on and the installation as far as I can tell went fine. Installation was tricky as I wanted to run in a different context as Apache.  However, I was able to run the inatller with out issue.

However in the initial login page I get a white screen and the following error:

[25-Sep-2020 20:06:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method ComposerAutoloaderInit2e421a8ef89dccd2c2a4aec0452c3452::getLoader() in /home/kmtime/www/kimai2/vendor/autoload.php:12
Stack trace:
#0 /home/kmtime/www/kimai2/public/index.php(8): require()
#1 {main}
  thrown in /home/kmtime/www/kimai2/vendor/autoload.php on line 12
^
Since the installation completed successfully, I am wondering if this is a bug or something I missed?

**Comment by kevinpapst** [comment]
Probably an agressive opcache. Restart php-fpm / apache.

Otherwise I am missing all information from the bug report / support template.

**Comment by gjcarter2** [comment]
ok, 

> Probably an agressive opcache. Restart php-fpm / apache.
> 
> Otherwise I am missing all information from the bug report / support template.

Oh sorry, can you point me to this link for the support template and I will fill it out.

Here is the Fedora 32 Recipe I used to sucessfully do the install/database portion: (Work In Progress)

Kimai2 Installation Instructions Fedora 32

Installation Directory of the Web Sources:

cd /home/kmtime/www
git clone -b 1.10.2 --depth 1 https://github.com/kevinpapst/kimai2.git
cd kimai2/composer install --no-dev --optimize-autoloader
composer install --no-dev --optimize-autoloader

Set credentials for webserver user as runtime user:
/etc/httpd/httpd.conf
User kmtime
Group kmtime

Added kmtime to the apache group:

usermod -G apache kmtime

php Runtime Environment Settings

/etc/php-fpm.d/www.conf
Added kmtime to run as user and group:
user=kmtime
group=kmtime
Added kmtime to the ACL users:
listen.acl_users = kmtime,apache,nginx
usermod -G apache kmtime<-Not required I don't think as the entire runtime stack is switched over to kmtime user, and kmtime group at this point.

MySQL Setup

mysql –host localhost –user=kmtime --password=
You may need to urlencode the password for it to be included in MySQL connection URL:
php -r "echo urlencode('');"
It might be better to redefine the password:
ALTER USER 'kmtime'@'localhost' IDENTIFIED BY ''; 

Create Database

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
+--------------------+
1 row in set (0.001 sec)

MariaDB [(none)]> create database kmtime;
Query OK, 1 row affected (0.001 sec)

GRANTS for the new Database
MariaDB [(none)]> GRANT ALL PRIVILEGES ON kmtime.* TO kmtime@localhost;
Query OK, 0 rows affected (0.002 sec)

Drop User

MariaDB [(none)]> SELECT host, user FROM mysql.user;
+-----------+-------------+
| Host      | User        |
+-----------+-------------+
| localhost | kimai2      |
| localhost | kmtime      |
| localhost | mariadb.sys |
| localhost | mysql       |
| localhost | root        |
+-----------+-------------+
5 rows in set (0.001 sec)

MariaDB [(none)]> DROP USER kimai2@localhost;
Query OK, 0 rows affected (0.003 sec)

Drop Database

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| kimai2             |
| kmtime             |
+--------------------+
3 rows in set (0.002 sec)

MariaDB [(none)]> drop database kimai2
    -> ;
Query OK, 0 rows affected (0.004 sec)

Set the current Database

MariaDB [(none)]> use kmtime;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [kmtime]> show tables;
+---------------------------+
| Tables_in_kmtime          |
+---------------------------+
| kimai_activities          |
| kimai_configuration       |
| kimai_customers           |
| kimai_expenses            |
| kimai_fixedRates          |
| kimai_globalRoles         |
| kimai_groups              |
| kimai_groups_activities   |
| kimai_groups_customers    |
| kimai_groups_projects     |
| kimai_groups_users        |
| kimai_membershipRoles     |
| kimai_preferences         |
| kimai_projects            |
| kimai_projects_activities |
| kimai_rates               |
| kimai_statuses            |
| kimai_timeSheet           |
| kimai_users               |
+---------------------------+
19 rows in set (0.001 sec)

Apache Config:
# require a client certificate which has to be directly
# signed by our CA certificate in ca.crt

<VirtualHost XXX.XXX.XXX.XXX:80>
    ServerName kimai.xxx.com
    DocumentRoot /home/kmtime/www/kimai2/public
    <Directory /home/kmtime/www/kimai2/public>
      AllowOverride All
      Order allow,deny
      Allow from All
      FallbackResource /index.php
    </Directory>
    <Directory /home/kmtime/www/kimai2>
      Options FollowSymlinks
    </Directory>
    <Directory /home/kmtime/www/kimai2/public/bundles>
      FallbackResource disabled
    </Directory>
    ErrorLog /var/log/httpd/kimai.xxx.com.error.log
    CustomLog /var/log/httpd/kimai.xxx.com.transfer.log common
#    <IfModule mpm_itk_module>
#
#    </IfModule>
</VirtualHost>

Listen 443
<VirtualHost XXX.XXX.XXX.XXX:443>
    ServerName kimai.xxx.com
    DocumentRoot /home/kmtime/www/kimai2/public
    <Directory /home/kmtime/www/kimai2>
      Options FollowSymlinks
      AllowOverride All
      Order deny,allow
      Allow from All
      FallbackResource /index.php
    </Directory>
    SSLEngine on
    #SSLVerifyClient require
    #SSLVerifyDepth 1
    SSLCACertificateFile ""
    SSLCertificateFile ""
    SSLCertificateKeyFile ""
    ErrorLog /var/log/httpd/kimai.xxx.com.ssl-error.log
    CustomLog /var/log/httpd/kimai.xxx.com.ssl-transfer.log common
#    <IfModule mpm_itk_module>
# 
#    </IfModule>
</VirtualHost>

You might have to change the doctrine.yaml file and remove the commenting has from:

server_version: 5.7
in file: /home/kmtime/www/kimai2/config/packages/doctrine.yaml

bin/console kimai:install -n

Creating a New User:

[kmtime@apache kimai2]$ bin/console kimai:create-user xxxxxx xxxxx@xxxx.xxx ROLE_SUPER_ADMIN
Please enter the password: 

                                                                                         
[OK] Success! Created user: xxxxxx       

Change and Update Cache Clearing

For some updates you may need to do:

bin/console clear:cache --env=prod
bin/console cache:clear

**Comment by kevinpapst** [comment]
> Oh sorry, can you point me to this link for the support template and I will fill it out.

You deleted it, when you opened your issue. The text box was pre-filled with required information.

Check your logfile. I guess it is a permission issue.

**Comment by gjcarter2** [comment]
Ok, I got a copy of the bug report and included it here:

**Describe the bug**
A clear and concise description of what the bug is.

White screen after completion of the installation and configuration of the git and apache config.

**To Reproduce**
1. Go to '...'  
https://kimai.allkiosk.com/en/homepage
or
http://kimai.allkiosk.com/en/homepage
2. Click on '....'
Page is blank.
3. See error
Error generated is from Apache log file:
[Mon Sep 28 10:51:40.013888 2020] [proxy_fcgi:error] [pid 245463:tid 245653] [client 10.100.101.157:33602] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ComposerAutoloaderInit2e421a8ef89dccd2c2a4aec0452c3452::getLoader() in /home/kmtime/www/kimai2/vendor/autoload.php:12\nStack trace:\n#0 /home/kmtime/www/kimai2/public/index.php(8): require()\n#1 {main}\n  thrown in /home/kmtime/www/kimai2/vendor/autoload.php on line 12'
```
Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
```

**Additional context**
 - Kimai version: 10.2  
 - PHP version: 7.4.10
 - Device: [Linux Fedora 32/Server]
 - Browser [Firefox 81 ]

**Comment by kevinpapst** [comment]
Something is wrong with your composer installation, but I don't know what it is.
This is an installation/environment issue and I can assure you that this is not a Kimai bug.

**Comment by gjcarter2** [comment]
ok, perhaps we can find out what that might be.

I erased everything and started over.  :-)

I did notice this during my second install attempt at the bottom for
zendframework....is that a problem?

[kmtime@apache kimai2]$ composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 160 installs, 0 updates, 0 removals
 - Installing composer/package-versions-deprecated (1.8.0): Loading from
cache
 - Installing kimai/kimai2-composer (0.1): Loading from cache
 - Installing symfony/flex (v1.8.4): Loading from cache
 - Installing psr/container (1.0.0): Loading from cache
 - Installing symfony/service-contracts (v2.1.2): Loading from cache
 - Installing symfony/polyfill-php80 (v1.17.1): Loading from cache
 - Installing symfony/polyfill-php73 (v1.17.1): Loading from cache
 - Installing symfony/console (v4.4.10): Loading from cache
 - Installing doctrine/lexer (1.2.0): Loading from cache
 - Installing doctrine/annotations (1.10.1): Loading from cache
 - Installing doctrine/reflection (1.2.1): Loading from cache
 - Installing doctrine/event-manager (1.1.0): Loading from cache
 - Installing doctrine/collections (1.6.4): Loading from cache
 - Installing doctrine/cache (1.10.0): Loading from cache
 - Installing doctrine/persistence (1.3.7): Loading from cache
 - Installing doctrine/instantiator (1.3.0): Loading from cache
 - Installing doctrine/dbal (v2.10.1): Loading from cache
 - Installing doctrine/inflector (1.3.1): Loading from cache
 - Installing doctrine/common (2.12.0): Loading from cache
 - Installing doctrine/orm (v2.7.2): Loading from cache
 - Installing beberlei/doctrineextensions (v1.2.6): Loading from cache
 - Installing symfony/routing (v4.4.10): Loading from cache
 - Installing symfony/polyfill-ctype (v1.17.1): Loading from cache
 - Installing symfony/polyfill-intl-idn (v1.17.1): Loading from cache
 - Installing symfony/mime (v4.4.10): Loading from cache
 - Installing symfony/http-foundation (v4.4.10): Loading from cache
 - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from
cache
 - Installing symfony/event-dispatcher (v4.4.10): Loading from cache
 - Installing symfony/var-dumper (v4.4.10): Loading from cache
 - Installing psr/log (1.1.3): Loading from cache
 - Installing symfony/debug (v4.4.10): Loading from cache
 - Installing symfony/error-handler (v4.4.10): Loading from cache
 - Installing symfony/http-kernel (v4.4.10): Loading from cache
 - Installing symfony/finder (v4.4.10): Loading from cache
 - Installing symfony/filesystem (v4.4.10): Loading from cache
 - Installing symfony/dependency-injection (v4.4.10): Loading from cache
 - Installing symfony/config (v4.4.10): Loading from cache
 - Installing symfony/var-exporter (v4.4.10): Loading from cache
 - Installing psr/cache (1.0.1): Loading from cache
 - Installing symfony/cache-contracts (v2.1.2): Loading from cache
 - Installing symfony/cache (v4.4.10): Loading from cache
 - Installing symfony/framework-bundle (v4.4.10): Loading from cache
 - Installing symfony/stopwatch (v4.4.10): Loading from cache
 - Installing zendframework/zend-eventmanager (3.2.1): Loading from cache
 - Installing zendframework/zend-code (3.4.1): Loading from cache
 - Installing ocramius/proxy-manager (2.2.3): Loading from cache
 - Installing doctrine/migrations (2.2.1): Loading from cache
 - Installing symfony/doctrine-bridge (v4.4.10): Loading from cache
 - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
 - Installing doctrine/doctrine-bundle (2.0.7): Loading from cache
 - Installing doctrine/doctrine-migrations-bundle (2.1.2): Loading from
cache
 - Installing egulias/email-validator (2.1.17): Loading from cache
 - Installing erusev/parsedown (1.7.4): Loading from cache
 - Installing willdurand/negotiation (v2.3.1): Loading from cache
 - Installing willdurand/jsonp-callback-validator (v1.1.0): Loading from
cache
 - Installing symfony/security-core (v4.4.10): Loading from cache
 - Installing friendsofsymfony/rest-bundle (2.7.3): Loading from cache
 - Installing behat/transliterator (v1.3.0): Loading from cache
 - Installing gedmo/doctrine-extensions (v2.4.39): Loading from cache
 - Installing ralouphie/getallheaders (3.0.3): Loading from cache
 - Installing psr/http-message (1.0.1): Loading from cache
 - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
 - Installing hoa/exception (1.17.01.16): Loading from cache
 - Installing hoa/consistency (1.17.05.02): Loading from cache
 - Installing hoa/event (1.17.01.13): Loading from cache
 - Installing hoa/visitor (2.17.01.16): Loading from cache
 - Installing hoa/ustring (4.17.01.16): Loading from cache
 - Installing hoa/protocol (1.17.01.14): Loading from cache
 - Installing hoa/zformat (1.17.01.10): Loading from cache
 - Installing hoa/iterator (2.17.01.10): Loading from cache
 - Installing hoa/compiler (3.17.08.08): Loading from cache
 - Installing hoa/math (1.17.05.16): Loading from cache
 - Installing hoa/regex (1.17.01.13): Loading from cache
 - Installing hoa/stream (1.17.02.21): Loading from cache
 - Installing hoa/file (1.17.07.11): Loading from cache
 - Installing symfony/inflector (v4.4.10): Loading from cache
 - Installing symfony/property-access (v4.4.10): Loading from cache
 - Installing symfony/security-http (v4.4.10): Loading from cache
 - Installing symfony/security-guard (v4.4.10): Loading from cache
 - Installing symfony/security-csrf (v4.4.10): Loading from cache
 - Installing symfony/security-bundle (v4.4.10): Loading from cache
 - Installing robrichards/xmlseclibs (3.0.4): Loading from cache
 - Installing onelogin/php-saml (3.4.1): Loading from cache
 - Installing hslavich/oneloginsaml-bundle (v1.5.0): Loading from cache
 - Installing psr/simple-cache (1.0.1): Loading from cache
 - Installing illuminate/contracts (v7.5.1): Loading from cache
 - Installing jms/metadata (2.1.0): Loading from cache
 - Installing jms/serializer (3.6.0): Loading from cache
 - Installing jms/serializer-bundle (3.6.0): Loading from cache
 - Installing twig/twig (v3.0.3): Loading from cache
 - Installing symfony/options-resolver (v4.4.10): Loading from cache
 - Installing kevinpapst/adminlte-bundle (3.2.3): Loading from cache
 - Installing symfony/translation-contracts (v2.1.2): Loading from cache
 - Installing symfony/validator (v4.4.10): Loading from cache
 - Installing symfony/twig-bridge (v4.4.10): Loading from cache
 - Installing symfony/twig-bundle (v4.4.10): Loading from cache
 - Installing symfony/translation (v4.4.10): Loading from cache
 - Installing symfony/intl (v4.4.10): Loading from cache
 - Installing symfony/polyfill-intl-icu (v1.17.1): Loading from cache
 - Installing symfony/form (v4.4.10): Loading from cache
 - Installing paragonie/random_compat (v9.99.99): Loading from cache
 - Installing kimai/user-bundle (1.2.2): Loading from cache
 - Installing intervention/image (2.5.1): Loading from cache
 - Installing voku/portable-ascii (1.4.10): Loading from cache
 - Installing nesbot/carbon (2.32.2): Loading from cache
 - Installing illuminate/support (v7.5.1): Loading from cache
 - Installing illuminate/cache (v7.5.1): Loading from cache
 - Installing laravolt/avatar (3.2.0): Loading from cache
 - Installing league/csv (9.6.0): Loading from cache
 - Installing league/html-to-markdown (4.9.1): Loading from cache
 - Installing setasign/fpdi (v2.3.2): Loading from cache
 - Installing myclabs/deep-copy (1.9.5): Loading from cache
 - Installing mpdf/mpdf (v8.0.5): Loading from cache
 - Installing zircote/swagger-php (2.0.15): Loading from cache
 - Installing symfony/property-info (v4.4.10): Loading from cache
 - Installing webmozart/assert (1.7.0): Loading from cache
 - Installing phpdocumentor/reflection-common (2.0.0): Loading from cache
 - Installing phpdocumentor/type-resolver (1.1.0): Loading from cache
 - Installing phpdocumentor/reflection-docblock (5.1.0): Loading from cache
 - Installing exsyst/swagger (v0.4.1): Loading from cache
 - Installing nelmio/api-doc-bundle (v3.6.1): Loading from cache
 - Installing nelmio/cors-bundle (1.5.6): Loading from cache
 - Installing pagerfanta/pagerfanta (v2.1.3): Loading from cache
 - Installing pclzip/pclzip (2.8.2): Loading from cache
 - Installing markbaker/matrix (1.2.0): Loading from cache
 - Installing markbaker/complex (1.4.8): Loading from cache
 - Installing phpoffice/phpspreadsheet (1.11.0): Loading from cache
 - Installing zendframework/zend-escaper (2.6.1): Loading from cache
 - Installing phpoffice/common (0.2.9): Loading from cache
 - Installing phpoffice/phpword (0.17.0): Loading from cache
 - Installing sensio/framework-extra-bundle (v5.5.4): Loading from cache
 - Installing symfony/mailer (v4.4.10): Loading from cache
 - Installing symfony/amazon-mailer (v4.4.10): Loading from cache
 - Installing symfony/css-selector (v4.4.10): Loading from cache
 - Installing symfony/dotenv (v4.4.10): Loading from cache
 - Installing symfony/expression-language (v4.4.10): Loading from cache
 - Installing symfony/google-mailer (v4.4.10): Loading from cache
 - Installing symfony/http-client-contracts (v2.1.2): Loading from cache
 - Installing symfony/http-client (v4.4.10): Loading from cache
 - Installing symfony/mailchimp-mailer (v4.4.10): Loading from cache
 - Installing symfony/mailgun-mailer (v4.4.10): Loading from cache
 - Installing monolog/monolog (1.25.3): Loading from cache
 - Installing symfony/monolog-bridge (v4.4.10): Loading from cache
 - Installing symfony/monolog-bundle (v3.5.0): Loading from cache
 - Installing symfony/polyfill-intl-grapheme (v1.17.1): Loading from cache
 - Installing symfony/polyfill-intl-normalizer (v1.17.1): Loading from
cache
 - Installing symfony/postmark-mailer (v4.4.10): Loading from cache
 - Installing symfony/sendgrid-mailer (v4.4.10): Loading from cache
 - Installing symfony/serializer (v4.4.10): Loading from cache
 - Installing symfony/asset (v4.4.10): Loading from cache
 - Installing symfony/webpack-encore-bundle (v1.7.3): Loading from cache
 - Installing symfony/yaml (v4.4.10): Loading from cache
 - Installing tijsverkoyen/css-to-inline-styles (2.2.2): Loading from cache
 - Installing twig/cssinliner-extra (v3.0.3): Loading from cache
 - Installing twig/extra-bundle (v3.0.3): Loading from cache
 - Installing lorenzo/pinky (1.0.5): Loading from cache
 - Installing twig/inky-extra (v3.0.3): Loading from cache
 - Installing twig/intl-extra (v3.0.3): Loading from cache
 - Installing symfony/string (v5.1.2): Loading from cache
 - Installing twig/string-extra (v3.0.3): Loading from cache
Package zendframework/zend-eventmanager is abandoned, you should avoid
using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-code is abandoned, you should avoid using it.
Use laminas/laminas-code instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it.
Use laminas/laminas-escaper instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
69 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [OK]
Executing script assets:install [OK]

**Comment by kevinpapst** [comment]
Did you restart the services as I said earlier?
What is the error now?

**Comment by gjcarter2** [comment]
Mmmm...it would seem composer is operating fine:

[kmtime@apache kimai2]$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.10.13
PHP version: 7.2.9 - Package overridden via config.platform (actual: 7.4.10)
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020

Are you sure this will work with this version of php?  (i.e. 7.4?)

**Comment by gjcarter2** [comment]
Yes, I restarted:

systemctl restart httpd
systemctl restart pgp-fpm

I get the same error:

[Mon Sep 28 15:26:45.439740 2020] [proxy_fcgi:error] [pid 274294:tid 274489] [client 10.100.101.157:36792] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ComposerAutoloaderInitfb8e976b3597cc292b2e2c4b200e4dbd::getLoader() in /home/kmtime/www/kimai2/vendor/autoload.php:12\nStack trace:\n#0 /home/kmtime/www/kimai2/public/index.php(8): require()\n#1 {main}\n  thrown in /home/kmtime/www/kimai2/vendor/autoload.php on line 12'

**Comment by gjcarter2** [comment]
[kmtime@apache kimai2]$ php -r "echo ini_get('memory_limit').PHP_EOL;"
512M

Just double checking but is 512M enough memory for this app?

**Comment by gjcarter2** [comment]
Since you think it might be a composer issue, I might try installing composer from scratch instead of using the fedora packages to setup the application.

What do you think about that idea?

**Comment by gjcarter2** [comment]
Well I went ahead and removed the composer from the Fedora32 repos, and used the Ubuntu instructions to install the composer manually.

Ironically I get the same message after installation.

So, I am not sure how to proceed from here.

If fedora 32 is to recent a distro, maybe I can pick something a little more dated/not up to date like Ubuntu to install the app on.

What distro and version are you using for your daily development driver? Maybe that might be easier for ya?

**Comment by kevinpapst** [comment]
I installed Kimai on a variety of systems: Ubuntu 18.04, 20.04, CentOS, Synology, Mac and I know that is is running on Windows and a lot of other Linux distros as well. This is very likely a problem in your PHP setup or maybe some kind of paranoid security setting (but I never used Fedora, so I cannot share any tip here where to start looking).

What is the content of `/home/kmtime/www/kimai2/vendor/autoload.php`?
There should be line inside with `require_once __DIR__ . '/composer/autoload_real.php';`

And that file (/home/kmtime/www/kimai2/vendor/composer/autoload_real.php) should start with `class ComposerAutoloaderInitfb8e976b3597cc292b2e2c4b200e4dbd` which is related to the error message: 
```
Uncaught Error: Call to undefined method ComposerAutoloaderInitfb8e976b3597cc292b2e2c4b200e4dbd::getLoader() 
```

**Comment by gjcarter2** [comment]
So I am pleased to report that I have Kimai running on Fedora32.

So we can close this ticket.

The problem stemmed from the fact that the original installation of the Fedora 32 server included approximately 200 or more seperate php packages that were in fact not needed, as I suspected.

To fix that I did a:

dnf remove php*

Which reset the php environment on the server to baseline.

I then did a:

dnf install php composer php-mysqlnd

This resulted in a package profile:

cmd: dnf list installed |grep php

php.x86_64                               7.4.10-1.fc32                      @updates          
php-PsrLog.noarch                        1.1.3-1.fc32                       @fedora           
php-cli.x86_64                           7.4.10-1.fc32                      @updates          
php-common.x86_64                        7.4.10-1.fc32                      @updates          
php-composer-ca-bundle.noarch            1.2.7-1.fc32                       @updates          
php-composer-semver.noarch               1.7.0-1.fc32                       @updates          
php-composer-spdx-licenses.noarch        1.5.4-1.fc32                       @updates          
php-composer-xdebug-handler.noarch       1.4.3-1.fc32                       @updates          
php-fedora-autoloader.noarch             1.0.1-2.fc32                       @fedora           
php-fpm.x86_64                           7.4.10-1.fc32                      @updates          
php-gd.x86_64                            7.4.10-1.fc32                      @updates          
php-intl.x86_64                          7.4.10-1.fc32                      @updates          
php-json.x86_64                          7.4.10-1.fc32                      @updates          
php-jsonlint.noarch                      1.7.2-2.fc32                       @fedora           
php-justinrainbow-json-schema5.noarch    5.2.10-1.fc32                      @updates          
php-mbstring.x86_64                      7.4.10-1.fc32                      @updates          
php-mysqlnd.x86_64                       7.4.10-1.fc32                      @updates          
php-opcache.x86_64                       7.4.10-1.fc32                      @updates          
php-pdo.x86_64                           7.4.10-1.fc32                      @updates          
php-pecl-zip.x86_64                      1.18.2-1.fc32                      @fedora           
php-process.x86_64                       7.4.10-1.fc32                      @updates          
php-seld-phar-utils.noarch               1.1.0-1.fc32                       @fedora           
php-sodium.x86_64                        7.4.10-1.fc32                      @updates          
php-symfony-browser-kit.noarch           2.8.52-3.fc32                      @fedora           
php-symfony-class-loader.noarch          2.8.52-3.fc32                      @fedora           
php-symfony-common.noarch                2.8.52-3.fc32                      @fedora           
php-symfony-config.noarch                2.8.52-3.fc32                      @fedora           
php-symfony-console.noarch               2.8.52-3.fc32                      @fedora           
php-symfony-css-selector.noarch          2.8.52-3.fc32                      @fedora           
php-symfony-debug.noarch                 2.8.52-3.fc32                      @fedora           
php-symfony-dependency-injection.noarch  2.8.52-3.fc32                      @fedora           
php-symfony-dom-crawler.noarch           2.8.52-3.fc32                      @fedora           
php-symfony-event-dispatcher.noarch      2.8.52-3.fc32                      @fedora           
php-symfony-expression-language.noarch   2.8.52-3.fc32                      @fedora           
php-symfony-filesystem.noarch            2.8.52-3.fc32                      @fedora           
php-symfony-finder.noarch                2.8.52-3.fc32                      @fedora           
php-symfony-http-foundation.noarch       2.8.52-3.fc32                      @fedora           
php-symfony-http-kernel.noarch           2.8.52-3.fc32                      @fedora           
php-symfony-polyfill.noarch              1.18.1-1.fc32                      @updates          
php-symfony-process.noarch               2.8.52-3.fc32                      @fedora           
php-symfony-var-dumper.noarch            2.8.52-3.fc32                      @fedora           
php-symfony-yaml.noarch                  2.8.52-3.fc32                      @fedora           
php-xml.x86_64                           7.4.10-1.fc32                      @updates          

Which these seem to be the baseline packages, and nothing else required to run Kimai.

You can close the ticket on this issue.

**Comment by kevinpapst** [comment]
That is interesting and a little bit weird. 

I wouldn't expect a distro to include all the `php-symfony*` packages, but I guess they also include some web application in their repos (like next cloud, phpmyadmin...) which rely on them. And those packages or the other ones which were purged might interfere with the php include path and therefor with composer and finally Kimai.

Okay, thanks for posting the solution @gjcarter2 this will definitely help the next fedora user 👍
