### ISSUE TITLE
Some zendframework/*-extensions are abandoned

### ISSUE THREAD

**Issue by 2chg** [kevinpapst/kimai2#1998]
**Describe the bug**
When installing the project dependencies via `composer`, there are warnings about abandoned packages 
`zendframework/zend-eventmanager`, `zendframework/zend-code` and `zendframework/zend-escaper`
with the advice to replace them with the `laminas/*`-counterparts:

```
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
```

**To Reproduce**
1. Clone the project repository
2. Install dependencies via `composer install --no-dev --optimize-autoloader`

**Additional context**
 - Kimai version: 1.10.2
 - PHP version: 7.4.3
 - Device: VM with Ubuntu 20.04.1 LTS
 - Browser n/a

**Comment by kevinpapst** [comment]
I appreciate any feedback, but I have to close this one as `wontfix`.

The dependencies [are not from Kimai&(https://github.com/kevinpapst/kimai2/blob/master/composer.json#L76), but from other packages which cannot be upgraded due to the fact that I want to support PHP 7.2.

**Comment by 2chg** [comment]
I do understand.

Probably this should be mentioned in the installation guide or faq to prevent others from wondering.

**Comment by kevinpapst** [comment]
This topic came up a couple of times and I can assure you: 
normal users don't wonder - they couldn't care less ... it's only devs who are so friendly to drop a line to let me know ;-)
