### ISSUE TITLE
cannot edit timesheetentry when "Allow overlapping time entries" is disabled

### ISSUE THREAD

**Issue by physi** [kevinpapst/kimai2#1999]
**Describe the bug**
When disable "Allow overlapping time entries" in the settings, one cannot make any changes to already existing entries in the "my times" pages. It causes an error : **"You already have an entry for this time"**

**To Reproduce**
1. Go to 'Settings/TimeSheet'
2. Uncheck  'Allow overlapping time entries'
3. login as a "normal" User
4. make a timesheet entry
5. edit the same entry you entered before
6. try to change the start or end time, or even just change the description
7. click **save**
8. The errormessage **You already have an entry for this time.** appers in red below the startdate.

**Additional context**
 - Kimai version: 1.10.2, 1.10
 - PHP version: 7.4.10
 - Device: centos8 with docker compose file
 - Browser Chrome, Edge

**Comment by kevinpapst** [comment]
I worked a lot on this validation and even if there might be still false negatives, I am pretty sure that it does not happen to every record. While testing I had a lot of "problems" as well, but all of them where valid cases in the end. 
I would propose you create a new account and test with that one (you can do it in the demo).

And please include your rounding configuration.

**Comment by physi** [comment]
I tried it in the DEV version, and you are right, no problems there.
Thanks so much! 
I will wait for the merge into the next stable branch 👍

**Comment by kevinpapst** [comment]
closing, as it is fixed in master
