### ISSUE TITLE
Invoice grouped time entries per day

### ISSUE THREAD

**Issue by simonschaufi** [kevinpapst/kimai2#2000]
**Is your feature request related to a problem? Please describe.**

My customer requests my time records to be grouped by day (only one entry per day even if I have multiple per day)

**Describe the solution you'd like**

I want to write an invoice to my customer with one line per day only instead of one line per time entry. The description should be merged together and separated by a new line.

If not done via db query, it can be done in php as well.

**Describe alternatives you've considered**

Do a lot of manual work to combine records from each day

See also https://github.com/kimai/kimai/pull/1312 for the same request from someone else. Now I'm in the same situation :D

I'm willing to sponsor this implementation :heavy_dollar_sign:

**Comment by kevinpapst** [comment]
Doesn't that work?
<img width="449" alt="Bildschirmfoto 2020-09-30 um 00 19 38" src="https://user-images.githubusercontent.com/533162/94622510-a32cf980-02b2-11eb-8148-4e43c8f32c39.png">

**Comment by simonschaufi** [comment]
Awesome, it works as expected! Thank you
