### ISSUE TITLE
Different rates for on-site and off-site (remote) and possibility to choose in time sheet

### ISSUE THREAD

**Issue by simonschaufi** [kevinpapst/kimai2#2001]
**Is your feature request related to a problem? Please describe.**

Maybe this is possible already bu I'm not aware of. I want to have different rates for on-site and off-site (remote) and possibility to choose in time sheet

**Describe the solution you'd like**

- Add an additional field in the time sheet for on-site and off-site
- Set different rates for both
- Show field in export
- Show field in invoice

**Describe alternatives you've considered**

none

I'm willing to sponsor this implementation :heavy_dollar_sign:

**Comment by kevinpapst** [comment]
What about different activities with different rates?

**Comment by simonschaufi** [comment]
Not the best solution but works as a workaround.
