### ISSUE TITLE
Missing validation for duplicate email address and username

### ISSUE THREAD

**Issue by jnfarrelly** [kevinpapst/kimai2#2003]
I set the admin (superuser) email and password, then when I went to set a user (the first user), used the same email address for a different name, and the app failed with an "oops contact the developer".

Here is the actual string in the "Dr" view:

[2020-09-29 19:17:40] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException:........

.........Integrity constraint violation: 1062 Duplicate entry 'jfarrelly@vercet.com' for key 'UNIQ_B9AC5BCEA0D96FBF' at /var/www/html/kimai2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []

**Comment by kevinpapst** [comment]
Thanks for the report @jnfarrelly 👍 

Its fixed (for the next release).
