### ISSUE TITLE
make the "permanent login" checkbox configurable

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#2008]
**Is your feature request related to a problem? Please describe.**
Since some changes in Kimai 2 V1.10 users get logged out more often due to changes in session handling. See #1950

**Describe the solution you'd like**
Make this checkbox configurable so it can be enabled by default - or even hidden and enabled by default.

![grafik](https://user-images.githubusercontent.com/36242595/94771208-02743200-03b7-11eb-88ff-dc9ec38c020a.png)

**Comment by kevinpapst** [comment]
Please check your PHP configuration and let me know if that was the problem: https://www.kimai.org/documentation/users.html#session-lifetime

PHP has 24 minutes session lifetime by default, which is ridiculous short. 
The new session implementation in Kimai now makes sure that your session doesn't last longer than it should.

**Comment by hmr-it-jr** [comment]
You're right, it's 24 minutes. But unfortunately my kimai 2 instance is running on a shared hosting server which doesn't allow to make changes on the session lifetime.

![grafik](https://user-images.githubusercontent.com/36242595/94785962-ab7b5680-03d0-11eb-80b6-6704b90d0d8b.png)

**Comment by kevinpapst** [comment]
And did you try the proposed config change from the docs?

**Comment by hmr-it-jr** [comment]
Yes. I haven't put it in the local.yaml but in framework.yaml.

If I put it in local.yaml the following error shows up:

![2020-10-01 10_46_24-hosting106863 a2f1e netcup net - KiTTY](https://user-images.githubusercontent.com/36242595/94788462-de731980-03d3-11eb-9b9f-ebca9d061fe9.png)

If I change the framework.yaml to this: 
![grafik](https://user-images.githubusercontent.com/36242595/94788508-f21e8000-03d3-11eb-8bb3-7cc47aba7da3.png)

it works. Users will be logged out after 60 seconds. But as soon as  I write a time >1440 1440 will always be used. I think they prevent an override or something like this.

**Comment by kevinpapst** [comment]
It works in local.yaml, just make sure to use the right order and indentation:
<img width="743" alt="Bildschirmfoto 2020-10-01 um 10 54 33" src="https://user-images.githubusercontent.com/533162/94788867-7ec93e00-03d4-11eb-8025-e9a26912a5a6.png">

I have never heard that its forbidden to overwrite the session configs, that would be really strange.
Give it a try in local.yaml and set the cookie_lifetime to `~`. Then delete all cookies a re-login.

**Comment by hmr-it-jr** [comment]
ok, will test it and give feedback in a few hours.

**Comment by hmr-it-jr** [comment]
no logout so far - putting it in the local.yaml seems to do the trick.
