### ISSUE TITLE
DELETE ENTRY TIMESHEETS - Entry could not be deleted

### ISSUE THREAD

**Issue by EdoardoMDP** [kevinpapst/kimai2#2010]
Hi,

I got this error message when i try to delete items on timesheets:
![image](https://user-images.githubusercontent.com/31856288/94785539-18422100-03d0-11eb-8214-3e56ea6d6fde.png)

Entry could not be deleted:
parsererror

There is nothing in the log file.
Moreover, if I delete the item from the dropdown menu on the right, I get the error.
image
![image](https://user-images.githubusercontent.com/31856288/94785604-2c861e00-03d0-11eb-8e51-bc1abf2c1265.png)

but if I select the item and delete it from the menu that appears at the bottom of the page, it works

Could you help me?
Thanks

Kimai version: 1.10.2 stable

**Comment by kevinpapst** [comment]
> but if I select the item and delete it from the menu that appears at the bottom of the page, it works

You mean you can't delete the item by itself, but if you choose the multi-delete it works?

There needs to be something either in your browser console or in the API response for the failing delete call.
Please open the network tab in your browser and show me the response of the DELETE (here it is the first line):
<img width="2076" alt="Bildschirmfoto 2020-10-01 um 10 39 14" src="https://user-images.githubusercontent.com/533162/94787255-5c362580-03d2-11eb-8a3f-a3424d9dc493.png">

Please check if there is any content as well (here the tab on the right side is called  "Antwort").

**Comment by EdoardoMDP** [comment]
No, even if I select only 1 file.

![image](https://user-images.githubusercontent.com/31856288/94790871-31020500-03d7-11eb-9bcb-582f5e5df193.png)

**Comment by EdoardoMDP** [comment]
I solved this issue. 
Thanks you

**Comment by kevinpapst** [comment]
If you can share the solution for the next person with the same issue, that would be great!
