### ISSUE TITLE
Reporting - Internal Server Error

### ISSUE THREAD

**Issue by sathyajackson** [kevinpapst/kimai2#2014]
**Description**
Hi,

I love your production and its awesome and I have been using your tool in my production environment. It was working fine till the 9th of Sep and now all of a sudden when I try to pull the reporting using the export module I get 500 Error.
Need your help in fixing the same.

This error gets generated while pulling a bulk report, the preview mode is working file, only when trying to export the report to csv or excel the below issue occures.

**Error in Prod.log**
[2020-10-02 14:51:41] request.CRITICAL: Uncaught PHP Exception PhpOffice\PhpSpreadsheet\Calculation\Exception: "Worksheet!I3597 -> Formula Error: An unexpected error occured" at /var/www/kimai2/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php line 274 {"exception":"[object] (PhpOffice\\PhpSpreadsheet\\Calculation\\Exception(code: 0): Worksheet!I3597 -> Formula Error: An unexpected error occured at /var/www/kimai2/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:274)"} []

**Additional context**
 - Kimai version: 2
 - PHP version: 7

**Comment by kevinpapst** [comment]
I have seen that error in other logs as well, but I don't exactly know what causes it.

A couple of question to find the possible reason:
- you are using the default exports and not a custom-export-template, right?
- which language are you using?
- can you try to filter a single timesheet record and try to export it - to check if it happens always or only when certain records are included.

My gut feeling is: there are some timesheet records or other fields in customer/project/activity which contain unexpected characters, which are interpreted as a (Excel/Spreadsheet) formula and that fails.
Probably they start with a `=` or contain content like `13*a1`.

**Comment by sathyajackson** [comment]
Hi,

Yes, if I download the report one by one ( individual) I can get the report, but this issue occurs only when I try to download a bulk ( One whole team report).

It all started only in September. I am not sure if any patch update has caused this issue. Need your help in fixing the same

**Comment by sathyajackson** [comment]
Language is English
using the default reporting

**Comment by kevinpapst** [comment]
I don't think this is something that is directly caused by Kimai (AKA bug) as otherwise much more bug reports would be here
I still think that some character sequence is not properly encoded when passed to the spreadsheet engine.

Please try to narrow down the timesheet (or project) that causes the issue. 
You can start by filtering weeks and if some work and some don't, then start by exporting single days until you find out which records cause the effect. Then export to HTML and place it here so I can have a look as well.

**Comment by sathyajackson** [comment]
ok, here is what I have done, I have close to 40 projects and close to 80 users onboarded on the tool. Monthly we will run a huge report across all the projects to get the engineer timesheet.

I am trying to generate a report across all the 20 projects for  a duration of 2 months to get the utilization ----> Error
I tried to reduce it to one month still the same ----> Error
if I try to generate a report for an individual user, yes it's working fine ( 2 months ), but If I exceed the number of months to more than 2 then ----> Error.

**The print and preview are working fine**, when I try  to download it as a CSV, Excell I get this error message ( 500 internal server error)
If I try to use the PDF I get a different error which is listed below.

***********Error*******************************
[2020-10-05 14:14:33] request.CRITICAL: Uncaught PHP Exception Mpdf\MpdfException: "The HTML code size is larger than pcre.backtrack_limit 1000000. You should use WriteHTML() with smaller string lengths." at /var/www/kimai2/vendor/mpdf/mpdf/src/Mpdf.php line 26766 {"exception":"[object] (Mpdf\\MpdfException(code: 0): The HTML code size is larger than pcre.backtrack_limit 1000000. You should use WriteHTML() with smaller string lengths. at /var/www/kimai2/vendor/mpdf/mpdf/src/Mpdf.php:26766)"} []
[2020-10-05 14:14:33] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []

**Comment by sathyajackson** [comment]
Hi Kevin,

Got the issue fixed and yes one of the users has entered ==== in the description which caused an issue. I have edited the file and now the reports are getting generated just fine.

How can I ensure that users is not making such mistakes? Any setting I can enable which will not allow users to input special characters.

My second question is, the special character was in the description box ( String), how is it affecting the reports?

**Comment by kevinpapst** [comment]
Thanks for your feedback! 

Right now you can't really do anything against it. But I will find a solution to prevent such problems in the future and keep you updated.

Regarding the PDF: there is a memory limit. You can try to adjust the PHP config to raise that limit. 
Generating a report for 2 month and 80 users is probably too much. Let's say it is 25 days per month (2*25 = 50 days) and only one record per user => that is 80*50 => 4000 rows. That is too much for a PDF (which is meant for smaller amounts of data). I'll try to find a workaround, but I am not sure if that can really be fixed.
