### ISSUE TITLE
Improve usability on modal buttons

### ISSUE THREAD

**Issue by simonschaufi** [kevinpapst/kimai2#2015]
My intuition is always confused when opening a modal window and wanting to click on the cancel button. I expect the positive buttons to be always on the right and the cancel button to be on the left.

**Comment by kevinpapst** [comment]
There is a rule for changing the button order in the CustomCSSBundle.

After a lot of reading I couldn't find a UX rule that says 100% where which button should be.
All I could find is the clear recommendation to be consistent, no matter where the buttons are.

**Comment by simonschaufi** [comment]
You are totally right, it's a total mess but I would say that if the positive button is on the left, the cancel button should be very different in the contrast that the eye is quick in deciding which one is cancel and which one is the OK.

See: https://uxdesign.cc/buttons-placement-and-order-bb1c4abadfcb

**Comment by kevinpapst** [comment]
If you want to give it a try, use the pre-made CustomCSSBundle rules.
I am open to improve the buttons and if you find a good solution, please share it.
Its just ... I am really not a good frontend developer 😁

**Comment by simonschaufi** [comment]
@kevinpapst Could you please guide me in the right direction about `CustomCSSBundle`? I didn't find anything about that in the code.

**Comment by kevinpapst** [comment]
Guide - in what way exactly?

**Comment by kevinpapst** [comment]
Like in: install [this bundle](https://github.com/Keleo/CustomCSSBundle) and then choose the right rule to swap button positions?

**Comment by simonschaufi** [comment]
yes but I'm still wondering where this bundle is loaded as I only see the admin bundle in my installation

**Comment by kevinpapst** [comment]
What is the Admin Bundle? 
The css bundle just adds some custom styles (via an event) to the HTML output. 
If you want to change the styles for the core, you have to adjust the assets/sass files and recompile them (npm task available).

**Comment by simonschaufi** [comment]
AdminLTE ;)

So the button order is simply done by css, not a template?

**Comment by kevinpapst** [comment]
Ah, symfony bundle not Kimai bundle (plugin).

Both I guess, but when I understand the CSS rules correctly (I don't use them, so I might be wrong) it seems to be possible to achieve it with CSS only.

Have a look at these templates as well, I think all forms use one of the includes for rendering:
https://github.com/kevinpapst/kimai2/tree/master/templates/default

**Comment by kevinpapst** [comment]
CustomCSSBundle: https://www.kimai.org/store/keleo-css-custom-bundle.html

Here is the required CSS to change the button order:
https://github.com/Keleo/CustomCSSBundle/blob/master/Resources/ruleset/general/switch-submit-cancel-reset-button.css

So in general, you can simply install the bundle, add the "css button rule" and thats it.
So I am closing here for now. 
If you come up with a good solution for everyone, please open a PR or a new discussion with some screenshots, so we can talk about it.
