### ISSUE TITLE
Add more help texts for text fields

### ISSUE THREAD

**Issue by simonschaufi** [kevinpapst/kimai2#2016]
**Description**
I already reported some time ago (see https://github.com/kevinpapst/kimai2/issues/138) an issue about missing description / help texts for form fields as often it is really not clear what input format is expected

Example:
- Profile edit: Avatar: Url? Path to file on server? Why can't I upload a picture?
- System settings: brand settings at the bottom: same as for profile avatar

**Comment by HeinzWuert** [comment]
Same for activities! When creating you have a description field for the activity, but this nowhere appears.

**Comment by kevinpapst** [comment]
Even though there can never be enough information this is a "never-ending issue". 
I added descriptive buttons and a lot of help labels for the next major release #2902 and close this issue for now. 
If there are missing description, which the docs do not explain as well, I am happy to add more in the future.
