### ISSUE TITLE
time of timesheet

### ISSUE THREAD

**Issue by accaraffaelecolarusso** [kevinpapst/kimai2#2018]
I’m writing to you because I have a problem with the time of timesheet.

The date of the machine on which the application is installed is in line with the settings
set in the Kimai application.
When I insert a recording, the date and time are  correct:
The problem occurs on the database side because at the moment I go to enter a 
recording, the date of this last recording is correct while the time is not correct 
because it is two hours earlier

**Comment by kevinpapst** [comment]
You say everything is okay
> When I insert a recording, the date and time are correct:

And now it is not okay:
> The problem occurs on the database side because at the moment I go to enter a
recording, the date of this last recording is correct while the time is not correct
because it is two hours earlier

Can you please describe in detail what is wrong.

And did you set the correct timezone in your user profile?

**Comment by accaraffaelecolarusso** [comment]
[Hi Kevin.docx](https://github.com/kevinpapst/kimai2/files/5327466/Hi.Kevin.docx)

**Comment by kevinpapst** [comment]
The application settings don't matter, it is the user preference "timezone" which is important.
Regarding the database: times are always stored in UTC. 
There is a column timezone which says "Europe/Rome" in your case.

**Comment by accaraffaelecolarusso** [comment]
[Problem with datetime.docx](https://github.com/kevinpapst/kimai2/files/5339367/Problem.with.datetime.docx)

**Comment by buoncri** [comment]
> [Problem with datetime.docx](https://github.com/kevinpapst/kimai2/files/5339367/Problem.with.datetime.docx)

I think if you report your issue in a [markdown ](https://guides.github.com/features/mastering-markdown/)format, other guys can better help you or get help from this tread.

**Comment by kevinpapst** [comment]
1. Why do you even care how Kimai saves the data?
2. Read about storing datetimes and handling timezone conversions: 
- https://derickrethans.nl/storing-date-time-in-database.html
- https://medium.com/@Danuka_Praneeth/guide-to-time-zones-conversion-between-zones-and-storing-in-mysql-da4fc4350cd9

Shortly speaking: there is no problem!
> times are always stored in UTC.
> There is a column timezone which says "Europe/Rome"

You need both information to calculate the correct time. There is no other way of properly storing a datetime without loosing information.

**Comment by buoncri** [comment]
If i am right, you have to look at the kimai2_timesheet table for finding what @kevinpapst said

![immagine](https://user-images.githubusercontent.com/3062441/95323394-60fd4c80-089e-11eb-8e86-eabcf25df666.png)

**Comment by accaraffaelecolarusso** [comment]
I understood. Thanks for helping me and good luck to all
