### ISSUE TITLE
Inaccuracies in Kimai Reporting Documentation

### ISSUE THREAD

**Issue by theapu** [kevinpapst/kimai2#2019]
**Description**
In the Kimai Reporting Documentation Extending the reports section at 
https://www.kimai.org/documentation/reporting.html#extending-the-reports I have noticed following two inaccuracies 

1. ```public function onMainMenuConfigure(ReportingEvent $event)```
should be
```public function onReportingMenu(ReportingEvent $event)```
in ReportingEventSubscriber.php

2.```use App\Reporting\Report;``` is also required in ReportingEventSubscriber.php

Kindly update Documentation.

**Additional context**
 - Kimai version: 1.10

**Comment by kevinpapst** [comment]
True, thanks for the report 😁 

Needs updating here: https://github.com/kimai/www.kimai.org/blob/master/_documentation/reporting.md
