### ISSUE TITLE
Remove Rate Column from PDF exports

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#2021]
Hi, 

in version 1.8 there was a way to remove the rate column from the code, but cant find it in the new v1.10.1

is there a new wat we can remove this?

![image](https://user-images.githubusercontent.com/40264293/95169305-f4f1ea00-07b2-11eb-8766-e73205dee7e2.png)

thanks

**Comment by kevinpapst** [comment]
Please read the documentation how to create your own export template.

Then use something like this:
```
{% extends 'export/pdf-layout.html.twig' %}
{% set showInternalRate = false %}
{% set showRateColumn = falsetrue %}
```

Here you can find more options: 
https://github.com/kevinpapst/kimai2/blob/master/templates/export/pdf-layout.html.twig#L1

**Comment by Jurgens92** [comment]
thanks, ive changed the code,

do i need to do anything else? 
on the export the rates are still there,

tnx
