### ISSUE TITLE
Deleting a user who is a teamleader will make the Database inkonsistent

### ISSUE THREAD

**Issue by tambi-soft** [kevinpapst/kimai2#2022]
Deleting a user who is still a teamleader will make the Database inkonsistent, causing crashes while clicking on "Teams" at the sidebar.

**Comment by kevinpapst** [comment]
Interesting, not on my end. teams where he is teamlead are deleted, otherwise he is removed from teams where the user is "only a member". I guess you are using SQLite?

**Comment by tambi-soft** [comment]
Yes, SQLite.
I will test this issue with a newly created kimai2-installation and report.

**Comment by kevinpapst** [comment]
The problem will still be there in a new installation when using SQLite:
https://www.kimai.org/documentation/installation.html#sqlite-not-supported-for-production-usage
Kimai relies on DB functionality to delete connected items and SQLite is just a pile of crap handling foreign keys.

**Comment by tambi-soft** [comment]
Thanks! Is there a recommended way to migrate from SQLite to MySQL?

**Comment by kevinpapst** [comment]
Here is a excerpt and highlight of the docs: 

---
<img width="771" alt="Bildschirmfoto 2020-10-06 um 17 54 10" src="https://user-images.githubusercontent.com/533162/95226198-f1835080-07fc-11eb-940a-d463642e1c2d.png">

---

Sorry, but all I can say is: don't use SQLite.

You need to find the team in the SQLite database in `kimai2_teams` table and fix the row with the invalid user id in the `teamlead_id` column, then the teams page will work again.

**Comment by kevinpapst** [comment]
> Thanks! Is there a recommended way to migrate from SQLite to MySQL?

- Export to plain insert statements
- Use the install command (see docs) to create the new database in Mysql
- Import 

This might or might not be as easy as it sounds - depends on the export. Try to get plain insert statements.
Not sure which tool is the best though, haven't done it in a longer time.

**Comment by tambi-soft** [comment]
Thanks a lot! I have fixed the SQLite-DB for now and going to migrate in the following days. I am confused i did not see the SQLite-Warning during installation. Maybe it wasn't there last year when I did the installation?
However: Thank you very much for kimai2, it is nevertheless a great tool!

**Comment by kevinpapst** [comment]
Actually it is in the docs for a long time, but maybe it still needs more highlighting, so nobody stumbles upon it in such a way.

Sorry for the troubles! I hope the migration goes smooth!

I am closing this issue, but I will see answers if you have questions regarding the migration later on.
