### ISSUE TITLE
Add equivalent variable to row.nr to templating system

### ISSUE THREAD

**Issue by kernie** [kevinpapst/kimai2#2024]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In Kimai v1 there was a variable "row.nr" that would simply put an increasing number to the timesheet entry of the query. If I'm not mistaken this functionality is not (yet) available in Kimai v2.

**Describe alternatives you've considered**
I'm using a docx template, so I cannot not use cell functions like in spreadsheet applications.

**Comment by kevinpapst** [comment]
Closing, duplicate of #2023
