### ISSUE TITLE
changing activities with Fee has no effect on hourly rate in bookings

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2026]
**Describe the bug**
Changing bookings, where a fee is added/changed in the activity have no effect on the already saved timesheet.

**To Reproduce**
open activities and add in activity yyy a fee with another hourly rate than default
make a simple booking and use activity xxx with default hourly rate and save it
edit the booking
change the setting from xxx to yyy
Now the hourly rate should have changed in the timesheet to the new fee

**Comment by buoncri** [comment]
Look at this if can be the solution ... a free plugin to recalculate a single timesheet in editing.
https://www.kimai.org/store/keleo-recalculate-rates-bundle.html

**Comment by kevinpapst** [comment]
@HeinzWuert a once applied hourly rate will never be overwritten by Kimai. It could have been set/changed on purpose by the user. If you want to use another hourly rate, you can empty the field upon changing the activity.
If your user doesn't see the hourly rate field or you never want to use a custom rate on single records, then the plugin mentioned by @buoncri might be the right choice.

**Comment by HeinzWuert** [comment]
Sorry, can't agree!
The user makes his bookings and uses the activity xxx with default hourly rate.
Than he realize, that he has taken a wrong activity.
No problem, he changes the activity to yyy, but this activity has a fee with another hourly rate. This correction will be not taken by Kimai. For me it's a bug!

Your hint, the user might have tried to manipulate the entry is not logic. He can't do that, because he has no rights to change that in activities/fees and not in his default, personal data.

**Comment by kevinpapst** [comment]
How shall I distinguish between a manually changed rate and a rate that changed by switching an activity? 
It could still be the case, that an admin changed the rate for the users entry. Or the activities rate changed and the user only updated the description of a record. There are many examples where it might or might not be the best to recalculate the rate.

Changing the behavior based on the users permissions would be hard to communicate (and technically challenging).

I can give you a lot of other examples where you would argue that the rate should not be changed automatically. I don't see how that should be determined accurately and I did think about that a couple of times.  

The behavior can be changed by plugins and I don't mind talking about logic for a custom plugin.
But I will not change the current logic in Kimai core.
