### ISSUE TITLE
Error on duplicate invoice_id in database while creating invoice

### ISSUE THREAD

**Issue by kernie** [kevinpapst/kimai2#2027]
**Describe the bug**
I defined the the invoice_id over settings menu to {ccm,3}, which is a counter per customer per month. I created the first invoice for customer1 and trying to create a new invoice for customer2.
Upon creating the second invoice I get the error message:

```
An exception occurred while executing 'INSERT INTO kimai2_invoices (invoice_number, created_at, timezone, total, tax, currency, due_days, vat, status, invoice_filename, customer_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["001", "2020-10-08 11:04:30", "Europe\/Berlin", 476, 76, "EUR", 30, 19, "new", "document.docx", 6, 1]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '001' for key 'UNIQ_76C38E372DA68207' 
```

**To Reproduce**
As described

**Logfile**
No relevant entry.

**Additional context**
 - Kimai version: 1.10.2
 - PHP version: 7.4
 - Device: OpenSuSE 15.2
 - Browser Firefox 81.0

**Comment by kevinpapst** [comment]
That is on purpose. You cannot create multiple invoices with the same invoice number.
ccm always to be prefixed with something else, that makes it unique.

**Comment by kernie** [comment]
From the wording in the documentation I concluded that I have an counter per customer and month, means it starts every month at 1 and increases per invoice and customer. 

What I want to achieve is something like ${project.order_number}-${query.end_month_number}-${invoice.number} as invoice number with ${invoice.number} being 001, 002... on a per customer basis. So that is unique, but I cannot put it into the numbering format this way?

Maybe I didn't get the full concept here?

**Comment by kernie** [comment]
and for the record:
under var/data/invoices/ I see a document generated, that is not shown in the web frontend of Kimai...

**Comment by kevinpapst** [comment]
Most people use simple increasing numbers combined with a year and maybe a month.
Obviously Kimai cannot support every-possible invoice format in the world, but for special cases you can create a custom invoice number formatter.

Or if you think [more replacers](https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php#L123) should be supported, you can have a look at this class:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/NumberGenerator/ConfigurableNumberGenerator.php
And sent in a PR with your adaptions. By using `$this->model` you can access the query, the project ...

**Comment by Terrox** [comment]
There's a problem here with the default format and deleting which causes integrity violation.
Format is {Y}/{cy,3}
If you export three and remove the second invoice, the next invoice it tries to use is 2020/003 - which already exists. I would like to use customerID instead to avoid this, but so far just went with {Y}/{D}/{cy,3} to avoid the issue mostly.

**Comment by kevinpapst** [comment]
@Terrox this is documented in #1914 - so this is a duplicate

@kernie all `{ccX}` replacer are customer specific. I added the word "per" to the explanation as in `per customer invoice counter`. I hope that explains it better, see https://www.kimai.org/documentation/invoices.html

No bug, closing
