### ISSUE TITLE
error on restarting a duplicated timesheet entry

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#2029]
**Describe the bug**
If you duplicate a still running timesheet entry and then restart the previously finished entry this error occurs.

**To Reproduce**
1. Start a timesheet entry and don't finish it
2. Create a copy of it (the copied timesheet entry will be stopped)
3. Restart the copied entry
4. Error occurs

![20201008_131256](https://user-images.githubusercontent.com/36242595/95454724-1c8cb200-096d-11eb-96bd-61f33708419d.gif)

**Additional context**
 - Kimai version: latest master
 - PHP version: 7.3
 - Browser latest Firefox
 - Database: 
![grafik](https://user-images.githubusercontent.com/36242595/95454785-35956300-096d-11eb-98f2-1a99788d836d.png)

**Comment by kevinpapst** [comment]
really latest master, because I recently fixed a bug created to restart: https://github.com/kevinpapst/kimai2/pull/1993

**Comment by hmr-it-jr** [comment]
guess this was my fault - thought i changes branche, but actually haven't 😬  Works fine on latest master 😃
