### ISSUE TITLE
Install Kimai as WebApp

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#203]
Enable Kimai to be installed as WebApp on devices that support it (at least Android does).

See https://github.com/kevinpapst/kimai2/issues/198#issuecomment-403914249

Other resources:
- https://developer.chrome.com/multidevice/android/installtohomescreen
- https://developers.google.com/web/fundamentals/app-install-banners/
- https://w3c.github.io/manifest/

**Comment by hmr-it-jr** [comment]
So I've tried to fix this with adding the below meta tag in "templates/security/login.html.twig"
`<meta name="mobile-web-app-capable" content="yes">`
and it works perfectly. It's just not offering to install it as a WebApp. For everyone who adds it manually to homescreen it works fine. Maybe this is acceptable as a quick fix until add-to-homescren is fully implemented.

<a href="https://ibb.co/bD6T2T"><img src="https://preview.ibb.co/nHgHwo/SVID_20180711_092014_1.gif" alt="SVID_20180711_092014_1" border="0"></a>

I did some research and found this project: https://github.com/cubiq/add-to-homescreen - it's able to add it to the users homescreen on iOS 6+ and Android with a notification for the user to add it.

What do you think about it?

**Comment by kevinpapst** [comment]
I have to read a bit about the consequences. I guess real "web-apps" would have at least some kind of fallback if there is no Internet connection. What happens if you start it without any accessible network?

**Comment by hmr-it-jr** [comment]
This meta tag is basically just hiding the url bar. I've used this in other projects, too and haven't discovered any consequences. Of course it's possible to add a shortcut to the desktop without seting the meta tag, too.

Screenshot comparison of having no internet connection (flightmode enabled) and launching the app from desktop.
<a href="https://ibb.co/g3QQ1o"><img src="https://preview.ibb.co/ejX51o/Screenshot_20180711_132904.jpg" alt="Screenshot_20180711_132904" border="0"></a>

**Comment by kevinpapst** [comment]
Thanks for the feedback!!!!
I will research in the next weeks to find out more about the topic, as its new to me and I'd like to know more about it before adding it. 
But I would accept a PR in the meantime if its urgent for you...

**Comment by parthakarmick** [comment]
Hello,

I have tried to install kimai_1.3.1. But after hitting Install button it gives blank black screen and noting happening. Need guidance here.

Thank you

**Comment by kevinpapst** [comment]
please don't hijack random topics which don't have to do anything with your problem. and you are in the wrong repo: https://github.com/kimai/kimai

**Comment by kevinpapst** [comment]
@hmr-it-jr I created a PR with app icons and web app metadata (the meta tag + manifest.json for standalone mode). Could you test it and see what happens on Android (I don't have one for testing)?!
See https://github.com/kevinpapst/kimai2/pull/211

**Comment by hmr-it-jr** [comment]
@kevinpapst I've tested the PR today. The icon works fine, and the login page, too. After login the responsivness is broken.
I've tested it on three different devices. Android 7.1, Android 8.1, iOS 11.4

<h2>Android 8.1:</h2>
<a href="https://ibb.co/gmwf6o"><img src="https://preview.ibb.co/g1Nbe8/Screenshot_20180714_093531.jpg" alt="Screenshot_20180714_093531" border="0"></a>
<a href="https://ibb.co/c0mDRo"><img src="https://preview.ibb.co/hcYtRo/Screenshot_20180714_093540.jpg" alt="Screenshot_20180714_093540" border="0"></a>
<a href="https://ibb.co/i78tRo"><img src="https://preview.ibb.co/cxmf6o/Screenshot_20180714_093601.jpg" alt="Screenshot_20180714_093601" border="0"></a>
<hr>
<h2>Android 7.1:</h2>
<a href="https://ibb.co/gzKQ6o"><img src="https://preview.ibb.co/k6EEz8/Screenshot_20180714_094404.png" alt="Screenshot_20180714_094404" border="0"></a>
<hr>
<h2>iOS 11.4:</h2>
<a href="https://ibb.co/jtgrCT"><img src="https://image.ibb.co/m4rDRo/Whats_App_Image_2018_07_14_at_09_51_16.jpg" alt="Whats_App_Image_2018_07_14_at_09_51_16" border="0"></a>
<a href="https://ibb.co/npbPXT"><img src="https://image.ibb.co/dgm2K8/Whats_App_Image_2018_07_14_at_09_51_17.jpg" alt="Whats_App_Image_2018_07_14_at_09_51_17" border="0"></a>
<a href="https://ibb.co/hq0jXT"><img src="https://image.ibb.co/jHb2K8/Whats_App_Image_2018_07_14_at_09_51_18.jpg" alt="Whats_App_Image_2018_07_14_at_09_51_18" border="0"></a>

**Comment by kevinpapst** [comment]
Wow, nice - thanks for the detailed feedback! 👍 
The checkbox in the login page is fixed in another branch.

TODO:
- the iOS icon needs a white background, I believe transparent is not possible
- change the name to "Kimai 2" only
- check responsiveness

I'll let you know when I fixed that stuff.

**Comment by kevinpapst** [comment]
Updated the branch with updated icons and changed app short_name.
Couldn't figure out while the responsiveness is not working, still checking it out.

**Comment by hmr-it-jr** [comment]
I've tested the updated branch and the hotfix and can confirm both work perfectly!

<h3>Updated App icon</h3>
<a href="https://ibb.co/faoYST"><img src="https://image.ibb.co/ccLPZ8/Whats_App_Image_2018_07_15_at_15_42_33.jpg" alt="Whats_App_Image_2018_07_15_at_15_42_33" border="0"></a>
<h3>iOS responsiveness works</h3>
<a href="https://ibb.co/jS8uZ8"><img src="https://image.ibb.co/fCV8u8/Whats_App_Image_2018_07_15_at_15_50_43.jpg" alt="Whats_App_Image_2018_07_15_at_15_50_43" border="0"></a>
<hr>
<h3>Android responsiveness works</h3>
<a href="https://ibb.co/gqKe1o"><img src="https://preview.ibb.co/m7f8u8/Whats_App_Image_2018_07_15_at_15_49_37.jpg" alt="Whats_App_Image_2018_07_15_at_15_49_37" border="0"></a>

**Comment by kevinpapst** [comment]
I still don't like the iOS icon, but as my frontend skills are very limited I would say we go with it.
Could you do a quick check on Android as well? I modified the icons and metatags as well.

**Comment by hmr-it-jr** [comment]
I think the old one looked better...
<a href="https://imgbb.com/"><img src="https://image.ibb.co/dHzq7T/Unbenannt.png" alt="Unbenannt" border="0"></a>

**Comment by kevinpapst** [comment]
LOL, so true. Thats an SVG bug... I will update the branch later.

**Comment by hmr-it-jr** [comment]
Looks good now!
<hr>
<a href="https://ibb.co/dK56id"><img src="https://preview.ibb.co/eTXmid/Whats_App_Image_2018_07_15_at_21_09_10.jpg" alt="Whats_App_Image_2018_07_15_at_21_09_10" border="0"></a>

**Comment by kevinpapst** [comment]
Thank @hmr-it-jr for all your support!!!!

Very much appreciated 👍
