### ISSUE TITLE
Support for TOTP (Time-based One-time Password)

### ISSUE THREAD

**Issue by x-jokay** [kevinpapst/kimai2#2030]
Would be great if you consider to add [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm) (Time-based One-time Password) one day 😉 

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support for [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm).

**Describe alternatives you've considered**
None.

**Comment by x-jokay** [comment]
Similar to https://github.com/kevinpapst/kimai2/issues/197.

**Comment by kevinpapst** [comment]
Work was started https://github.com/kevinpapst/kimai2/pull/435 and then ... well stopped.

Please vote with 👍 on the first post in #197 as I am closing this here as duplicate.

**Comment by kevinpapst** [comment]
Two factor implementation will finally ship with the next major release https://github.com/kevinpapst/kimai2/pull/2902
