### ISSUE TITLE
API: Patch values to a timesheet column invisible in "Edit record"

### ISSUE THREAD

**Issue by rahulkrishnans** [kevinpapst/kimai2#2034]
**Description**
I have a situation to patch rate from user via API through a program. But it is visible and can be edited through "Edit Record" by the user. To restrict edit in "Edit Record" I have closed the permission, but this cause failure in API rate patching. How can I fix this?

**Additional context**
 - Kimai version: 1.10.2

**Comment by kevinpapst** [comment]
Either the user has the permission to change a rate or he doesn't.

But in your case, you can create a new user account with admin permissions and use that one to call the API.
