### ISSUE TITLE
Restart last activity fails if last entry was deleted

### ISSUE THREAD

**Issue by skylord123** [kevinpapst/kimai2#2036]
**Describe the bug**
If you delete the last time card entry and then go to restart activity on the same project (from same window that the item was deleted from without refreshing) it will fail because the restart URL contains the last time entry ID (i.e. `/api/timesheets/56/restart`).

This should be an easy fix. Instead of passing the ID of the last entry it should instead pass the activity ID and the server should look up the last entry for that activity (and then fail if none exist).

**To Reproduce**
1. Create a time card entry for an activity
2. Delete the entry and do not refresh the page
3. Try to start the same activity from the top right of the page and it will fail because the last entry no longer exists.

**Logfile**
Log file should be irrelevant for this but if needed I can fetch it.

**Additional context**
 - Kimai version: 1.10.2
 - PHP version: 7.4
 - Device: Docker on Unraid linux system
 - Browser Brave version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)

**Comment by kevinpapst** [comment]
Thanks! There is a JS event that triggers a reload of the last activities. It just needs to be dispatched after successful delete.
