### ISSUE TITLE
Provide project budget information to "simple" users

### ISSUE THREAD

**Issue by michaelberndt** [kevinpapst/kimai2#2038]
Hi,

is it possible, that a "simple" user has access to the budget information of a project? Or are those budget information only visible for teamleads or adminitrators?

**Comment by kevinpapst** [comment]
Thats completely configurable via permission, please read the documentation about users & roles & permissions, test (with two different browser instances - one with a admin login and one with a regular user login) and then come back with more detail questions.

**Comment by michaelberndt** [comment]
Hi,
"Thats completely configurable", these information is sufficient :)
