### ISSUE TITLE
parallel activities

### ISSUE THREAD

**Issue by michaelberndt** [kevinpapst/kimai2#2039]
Can kimai handle parallel activities. One for working time measurement and than single project activties?
For example:
9:00: start to work (start activity A)
9:10 - 12:00: work on project A (activity B)
13:00 - 17:00 work on project B(activity C)
17:00: end of work (stop activity A)

**Comment by kevinpapst** [comment]
Yes, Kimai has a couple of settings to configure/allow parallel records (see System configs / hard & soft limit).

**Comment by michaelberndt** [comment]
Perfect, thanks 👍
