### ISSUE TITLE
Approval Process

### ISSUE THREAD

**Issue by AddoSolutions** [kevinpapst/kimai2#2040]
Moving feature request from the v1 branch here:
https://github.com/kimai/kimai/issues/470

**Is your feature request related to a problem? Please describe.**
At a basic level, it would be great to be able to quickly "approve" or "reject" time entries in a timesheet, and then be able to do basic report on it.

**Comment by kevinpapst** [comment]
I have customers who are using Custom "boolean" fields for that.
You can search for custom fields (see documentation, eg. `my_field:1`) and use that in export.

**Comment by AddoSolutions** [comment]
Is there a qay to quickly assign a large number of records that boolean
data? Like can I check 20 records and set all to "yes"?

**Comment by kevinpapst** [comment]
Not yet, but soon (batch update will be extended for custom fields).

**Comment by kevinpapst** [comment]
I am closing here, as a real approval process is currently not in scope and would require a new feature request with much more input necessary.

But the process using a custom field nd setting the fields via "batch update" would work now.
