### ISSUE TITLE
Importing Data

### ISSUE THREAD

**Issue by devoeger** [kevinpapst/kimai2#2041]
**Describe the bug**
The "Customer" importer command runs the "Project" importer.

**To Reproduce**
1. Run a bin/console kimai:import:customer customer.csv command launches "Kimai importer: Projects" and fails because it is expecting different fields.

```

**Additional context**
 - Kimai version: 1.10 
 - PHP version: ?.?
 - Device: Windows Server 2016
![Screenshot 2020-10-15 170235](https://user-images.githubusercontent.com/72947507/96185676-43685c80-0f08-11eb-9649-6670a25dca56.jpg)

**Comment by kevinpapst** [comment]
The documentation shows the next version of Kimai.
If you are using <= 1.10.2 read this: https://github.com/kimai/www.kimai.org/blob/379a5e343fac018e01daf42bb8885a03ab6003d3/_documentation/imports.md

**Comment by devoeger** [comment]
I updated to 1.10.2 and still have the same issue.  See attachment.  

![image](https://user-images.githubusercontent.com/72947507/96260437-01cdc500-0f8d-11eb-92e3-8d61c725996c.png)

**Comment by kevinpapst** [comment]
Yes, you updated to 1.10.2 (which ist still ` <= 1.10.2 ` 😁 ) - not to the "next version" (master branch).

**Comment by devoeger** [comment]
Ahh, I see now.  Thanks!
