### ISSUE TITLE
More mobile friendly hour/minute set value.

### ISSUE THREAD

**Issue by rmab-se** [kevinpapst/kimai2#2044]
Its clumsy to write 00:00. Its more then usual where employees write only ”8” for 8 hours.
The system puts out 00:01.

Idd like a more friendly / failsafe hour input.

**Screenshot**
<img width="1366" alt="Request" src="https://user-images.githubusercontent.com/73024798/96337406-476eb880-1087-11eb-8457-70a9c65c60d2.png">

**Comment by kevinpapst** [comment]
A lot of changes has been applied to the handling of the duration field, please see #2264

You can test it at https://demo-branch.kimai.org (eg. with `susan_super` and `kitten`).
