### ISSUE TITLE
Reports for inactive users

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#2048]
**Is your feature request related to a problem? Please describe.**

When opening the profile of an inactive suer, you can click the graphs/month data and will be redirected to the monthly report, which shows an error.

**Describe the solution you'd like**

Do not allow to drill down into report, add `user.enabled` [condition here](https://github.com/kevinpapst/kimai2/blob/master/templates/user/stats.html.twig#L52)

**Comment by crm-developer** [comment]
I take
