### ISSUE TITLE
Previous and Future entries

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#2052]
Prod Version: 1.10.1

Hi,

is there a way to limit users to NOT be able to enter entries for the future or past.
eg, a user can only do entries for the current day, and no other day

thanks

**Comment by kevinpapst** [comment]
Should be possible with the lockdown period:
https://www.kimai.org/documentation/timesheet.html#lockdown-period

something like `today 00:00:00` for start and `today 23:59:59` for end - but I haven't tested that.

**Comment by Jurgens92** [comment]
thanks,

I used today for start and today for end, that works fine.
now i tried today for start and yesterday for end, then it doesnt work.

so i re-thought the idea I have, and would like to only have users enter entries for yesterday and today, and no other.

might I be doing something wrong with the yesterday and today idea?

thanks

**Comment by kevinpapst** [comment]
Just an assumption: end (yesterday) cannot be before start (today) => any time would be outside the range. Try to switch it.

**Comment by Jurgens92** [comment]
works perfect. but i had to add a grace period for this to work as expected:

![image](https://user-images.githubusercontent.com/40264293/96863906-e3256d80-1467-11eb-83f6-ee33bf6c7e67.png)

**Comment by kevinpapst** [comment]
If you do not append times like `yesterday 00:00:00` and today `23:59:59` the current time will be used.
Thats why it is not working as expected.

**Comment by kevinpapst** [comment]
added this case as example to https://www.kimai.org/documentation/timesheet.html#lockdown-period
