### ISSUE TITLE
Calendar: Add actions to entries (like in list view)

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2053]
**Is your feature request related to a problem? Please describe.**
Calendar is becoming the most used feature for bookings.
Unfortunately the workflow does not match any more. You have to leave calendar for deleting entries and there is no way to create a new booking with drag&drop and add expences for this new entry.

**Describe the solution you'd like**
add an option to do both for the currently marked object in calendar

**Comment by HeinzWuert** [comment]
The worflow for adding or deleting an entry in the calendar is poor. Same for adding expenses.
Realization idea:
Clicking on an entry in the calendar opens the editing window.
Here you could add 2 more buttons to SAVE and CLOSE:
- SAVE and add expense
- Delete entry
This saves the detour via My Times.

**Comment by HeinzWuert** [comment]
Got another idea from a user:
If the Expenses module is available, display a modified window in which the expenses are contained instead of the normal time recording window.
This eliminates the break between time and expense recording.

**Comment by HeinzWuert** [comment]
looks like this
![New input](https://user-images.githubusercontent.com/45666972/99145635-c2b88f80-2670-11eb-9f22-aefb6913537b.jpg)

**Comment by kevinpapst** [comment]
Delete and drag & drop was added. Closing.
