### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by kulturbande** [kevinpapst/kimai2#2057]
**Describe the bug**
If I run docker build from the [documenation](https://www.kimai.org/documentation/docker.html) it results in an error at the end. The container is usable, but results in some weird errors, if I want to use other invoice templates for example.

**To Reproduce**
1. run `docker build -t kimai/kimai2:dev .`
2. an error occurs in the fouth step

**Logfile**
```
Step 4/8 : RUN git clone https://github.com/kevinpapst/kimai2.git /opt/kimai &&     sed "s/prod/dev/g" /opt/kimai/.env.dist > /opt/kimai/.env &&     composer install --working-dir=/opt/kimai --dev --optimize-autoloader &&     /opt/kimai/bin/console doctrine:database:create &&     /opt/kimai/bin/console doctrine:schema:create &&     /opt/kimai/bin/console doctrine:migrations:version --add --all &&     /opt/kimai/bin/console cache:warmup &&     chown -R www-data:www-data /opt/kimai/var &&     chown www-data:www-data /opt/kimai/vendor/mpdf/mpdf/tmp
 ---> Running in 778e7648cc31
Cloning into '/opt/kimai'...
You are using the deprecated option "dev". Dev packages are installed by default now.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-xsl * is missing from your system. Install or enable PHP's xsl extension.
  Problem 2
    - Installation request for lorenzo/pinky 1.0.5 -> satisfiable by lorenzo/pinky[1.0.5].
    - lorenzo/pinky 1.0.5 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
  Problem 3
    - lorenzo/pinky 1.0.5 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
    - twig/inky-extra v3.0.3 requires lorenzo/pinky ^1.0.5 -> satisfiable by lorenzo/pinky[1.0.5].
    - Installation request for twig/inky-extra v3.0.3 -> satisfiable by twig/inky-extra[v3.0.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
The command '/bin/sh -c git clone https://github.com/kevinpapst/kimai2.git /opt/kimai &&     sed "s/prod/dev/g" /opt/kimai/.env.dist > /opt/kimai/.env &&     composer install --working-dir=/opt/kimai --dev --optimize-autoloader &&     /opt/kimai/bin/console doctrine:database:create &&     /opt/kimai/bin/console doctrine:schema:create &&     /opt/kimai/bin/console doctrine:migrations:version --add --all &&     /opt/kimai/bin/console cache:warmup &&     chown -R www-data:www-data /opt/kimai/var &&     chown www-data:www-data /opt/kimai/vendor/mpdf/mpdf/tmp' returned a non-zero code: 2
```

**Additional context**
 - Kimai version: current master
 - PHP version: 7.2.9 
 - Device: [Mac OS 10.13.6, Docker version 19.03.13, build 4484c46d9d]

**Comment by kevinpapst** [comment]
Seems the PHP extension for XML is missing...

If you are familiar with Docker, you could try to fix the docker script by adding a new line after 
https://github.com/kevinpapst/kimai2/blob/master/Dockerfile#L31
```
        xml \
```

Otherwise you might want to test https://github.com/tobybatch/kimai2

**Comment by kulturbande** [comment]
Thx for your fast response. I added `xsl` (and `libxslt-dev`) and it solved it, but I have the typical PHP/composer error: 
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Cloner/Data.php on line 331
!!  
```
But I have no idea atm. where I should increase the memory limit.

**Comment by kevinpapst** [comment]
Hm, sorry for the troubles. I never use docker, so this image wasn't tested in a while...

Try to replace line https://github.com/kevinpapst/kimai2/blob/master/Dockerfile#L43 with
`COMPOSER_MEMORY_LIMIT=-1 composer install --working-dir=/opt/kimai --dev --optimize-autoloader && \`

**Comment by kulturbande** [comment]
Did not worked out. I will use MAMP or something else to keep it running. I will think about the problem. Last time I hade this problem, I create a docker compose file with multiple Docker Container and for example a container only for composer purposes.

**Comment by kevinpapst** [comment]
Why don't you try this one: https://github.com/tobybatch/kimai2

**Comment by kulturbande** [comment]
I tried it, but at the moment I upload my new invoice to my server and try it their. I will take a look later. First of all I need to create an invoice that is less then ten pages long. Some sort of compact invoice. And I do hate TWIG, because it make it incredibly hard to write array operation without be extrem ugly.

**Comment by adrianrudnik** [comment]
@kulturbande Yeah, twig is not the best way to prepare data for the actual template, but you can extend it easily by [building your own function/methods/macros](https://symfony.com/doc/4.4/templating/twig_extension.html) and mount it into the symfony base. That way you can move the logic into a PHP script and just use simple abstractions in twig templates.

I'll take a look at the current Dockerfile and try to move it up to a current PHP version that contains the XML/XLS extensions.

**Comment by adrianrudnik** [comment]
@kulturbande to get XSL working use a combination of

```
apt -y install libxslt-dev libxml2-dev libssl-dev
```

and

```
docker-php-ext-install xsl xml xmlrpc xmlwriter simplexml
```

thats all that is needed.

In case you do not run your own Dockerfile, [here is mine](https://gist.github.com/adrianrudnik/a55760be74616896ceb1c100ff73da11) in case you want to use it. It's based on PHP 7.4, includes XSL/XML, opcache and should be configured through env.

**Comment by kevinpapst** [comment]
Want to sent a PR instead of a gist?

**Comment by adrianrudnik** [comment]
@kevinpapst I can, through it takes a bit more as the Dockerfile is not contained in itself (requires a second gist for the apache vhost.conf). Not sure if it's worth it, the current Dockerfile in this repo is for development purposes only right or should it be for production use in the first instance?

**Comment by kevinpapst** [comment]
It is only meant for development/quick testing.
I am not a docker user, so I cannot give any support - so production wouldn't be the best idea 😁

**Comment by adrianrudnik** [comment]
@kevinpapst i'll prepare a simplification and update to the Dockerfile for dev stuff that includes xsl and PR it!

**Comment by tobybatch** [comment]
@adrianrudnik Our docker images for kimai are here: https://github.com/tobybatch/kimai2 & https://hub.docker.com/repository/docker/kimai/kimai2

Raise a PR for us and we'll almost certainly role it into the image.

**Comment by adrianrudnik** [comment]
@tobybatch Thanks, already saw it, I always get confused when the official docker hub image is in some other repository. Not sure my stuff is of use for anyone in commited form, this is more a conflict of using a the Dockerfile from this repository that spools up a PHP server via `server:run` and not using the one you're offering that's based on alpine and already includes xsl. My apache/ubuntu stuff just gonna confuse more people so I'll just bump the Dockerfile in this repo, yours looks fine and should work anyway :+1:

**Comment by kevinpapst** [comment]
Docker has been removed from this repository, closing. 
Please go to https://github.com/tobybatch/kimai2
