### ISSUE TITLE
Filtering record by group or user company

### ISSUE THREAD

**Issue by ctpntn** [kevinpapst/kimai2#2062]
**Is your feature request related to a problem? Please describe.**
I use Kimai for the reporting of orders by internal users inside and external user (from other companies). It would be very convenient to be able to filter by group membership or to have a company field related to the users so you can filter according to the company.

**Describe the solution you'd like**
Filtering according to user membership or user's company

**Comment by kevinpapst** [comment]
wont be added unless someone sponsors this feature
