### ISSUE TITLE
Can create second timesheet entry

### ISSUE THREAD

**Issue by kulturbande** [kevinpapst/kimai2#2064]
**Describe the bug**
Can't create a new time event if the previos time slot is still running

**To Reproduce**
1. Start a timesheet entry (importend with a tag)
2. Try to start a second one (again with tag)
3. An error in the modal appears

**Logfile**
```
A new entity was found through the relationship 'App\Entity\Tag#timesheets' that was not configured to cascade persist operations for entity: App\Entity\Timesheet@000000003d47eda9000000007775692b. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\Timesheet#__toString()' to get a clue. 
```

**Additional context**
 - Kimai version: 1.11
 - PHP version: 7.2.9
 - Device: [Mac OS 10.15]
 - Browser [Firefox 81]

**Comment by kevinpapst** [comment]
Argh ... thanks for posting!
Reusing a tag is impossible currently, if another entry is running. That is really weird, but I guess something has to break in every release 😁 good candidate for a patch release.
