### ISSUE TITLE
Allowing team members to view other team members time entries

### ISSUE THREAD

**Issue by nuraeil** [kevinpapst/kimai2#2065]
**Is your feature request related to a problem? Please describe.**
I currently face the issue of being unable to setup a permission role to allow others to view the time entries in their own team. Reading the documentation around the permissions systems, searching open and closed issues as well as consulting Google, have not yet brought me to a solution. As far I as I am able to discern, it is only possible to view the timesheets or even activity with view_all_data permission.

I setup the permissions for other timesheets for user to be able to view and edit them. I pretty much allowed a test group everything aside from core admin permissions. But am unable to view time entries made by others.

The only other way to view all entries is by being the team lead of a Team rather than having the team lead role.

My setup is 4 departments/teams, 4 internal customers that reflect the departments/teams and multiple projects per team/customer. The team is assigned to the corresponding customer. 

**Describe the solution you'd like**
I would like to be able to setup permissions inside a team to allow any team member to view the time entries from other team members in a project where their own team is assigned.

For example: I have team A. In team A there are 10 people. Those 10 people each have different projects but all are related to each other. Team A is assigned to all of these projects. So everyone in Team A needs to be able to view the projects of Team A as well as all time entries from each member of Team A.

In my scenario this is needed for internal planning as well as there being multiple team leads across projects who need to view the entries from these projects.

**Describe alternatives you've considered**
I tried out multiple options with the permissions system as well as people being the team lead, which automatically gives them the ability to view the time entries. This would be good as a role permissions.

**Screenshot**
View with no own entries while there are multiple by others in different projects in the same team
![image](https://user-images.githubusercontent.com/32387849/97295712-f792ad00-184f-11eb-8452-5f4cf82f2768.png)
Last row is the custom user group with full permissions aside from view_all_data
![image](https://user-images.githubusercontent.com/32387849/97295749-05483280-1850-11eb-9d10-3afbcf6ec03d.png)

I hope I explained my issue and request adequately. If it is necessary, I would be more than willing to give more information.

**Comment by kevinpapst** [comment]
There is no permission existing that translates to "show my team members times".
Teamlead positions can see times of their team member, thats it. Team members cannot see times of their team peers.

There are reasons for this, eg. the GDPR in the EU. 
Working times are private informations and should not be shown to arbitrary team member.

In the future support for multiple teamleads is planned, until then the simplest solution is: create 10 teams with the same users - but assigned another user the teamlead position in each team.

**Comment by nuraeil** [comment]
> There is no permission existing that translates to "show my team members times".
> Teamlead positions can see times of their team member, thats it. Team members cannot see times of their team peers.
> 
> There are reasons for this, eg. the GDPR in the EU.
> Working times are private informations and should not be shown to arbitrary team member.
> 
> In the future support for multiple teamleads is planned, until then the simplest solution is: create 10 teams with the same users - but assigned another user the teamlead position in each team.

Thank you for the very quick response!

I thought so that the feature has legal implications. In our case those would not have been an issue as the tool is internal and everyone involved would be asked if this would be okay for them. Most of them asked themselves if this would be possible.

But it is good knowing that there is such a feature in the works, which we really need. Thank you for that information! And your other suggestion was also an idea of mine but the amount of work for that workaround would have been too much as we have around 50 people and 2-3 teamleads.

Again, thank you for your answer and I am looking forward to the multiple teamleads functionality!

**Comment by 3ruce** [comment]
>In the future support for multiple teamleads is planned...

This will be cool...
