### ISSUE TITLE
Upgrade from 1.10.2 to 1.11 failed

### ISSUE THREAD

**Issue by wforumw** [kevinpapst/kimai2#2070]
**Description**
I upgraded our Kimai from 1.10.2 to 1.11. I followed the instructions here
https://www.kimai.org/documentation/updates.html

We got the confirmation the upgrade was successful
` [OK] Congratulations! Successfully updated Kimai 2 to version 1.11 (stable)`

But when we open the login page we get

![kimai](https://user-images.githubusercontent.com/12762849/97418084-ad213700-1908-11eb-887f-8092181af004.png)

**Additional context**
 - Kimai version:  1.11
 - PHP version: 7.3

**Comment by kevinpapst** [comment]
Aha. https://www.kimai.org/documentation/faq.html#i-have-a-problem

**Comment by wforumw** [comment]
Sorry, my mistake
There was a problem with the permissions.
Thanks now it works!!

**Comment by kevinpapst** [comment]
Thanks for the feedback and glad you could help yourself with the logfile 👍
