### ISSUE TITLE
Permissions - Lockdown

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#2074]
Hi,

the permissions for lockdown is not showing in the "edit Permissions" section as per: 
https://www.kimai.org/documentation/timesheet.html#lockdown-period and https://www.kimai.org/documentation/permissions.html

on the edit permissions screen (V1.10.1) the lockdown_override_timesheet permission is missing from the checkbox section

or am i missing something

**Comment by kevinpapst** [comment]
https://demo.kimai.org/en/admin/permissions (user: susan_super / pw: kitten)
<img width="904" alt="Bildschirmfoto 2020-10-29 um 09 19 36" src="https://user-images.githubusercontent.com/533162/97542953-e076cb00-19c7-11eb-9f42-4188d5feb22a.png">

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by Jurgens92** [comment]
no prob, seems like I need to update 1st to 1.11

thanks for the help
