### ISSUE TITLE
Xlsx Template

### ISSUE THREAD

**Issue by Gagasas** [kevinpapst/kimai2#2075]
**Description**
I'm creating a template in xlsx format. In my template i need to add twice ${entry.date}, but if i insert it in the template, the first entry.date shows all values and the second entry.date only the last value from the entries. Same problem with entry.begin, entry.description and also entry.row. 

**Screenshot**
![Bildschirmfoto vom 2020-10-29 09-52-06](https://user-images.githubusercontent.com/73638118/97546346-9d6b2680-19cc-11eb-9418-4e4579ea5817.png)
![Bildschirmfoto vom 2020-10-29 09-52-41](https://user-images.githubusercontent.com/73638118/97546348-9e03bd00-19cc-11eb-8ef8-61d1f4e10d5d.png)

**Additional context**
 - Kimai version: 1.11 
 - PHP version: 7.4.3

**Comment by kevinpapst** [comment]
> In my template i need to add twice ${entry.date}

You should explain your use-case more detailed. 

But I guess the trick is not to use the variables twice (which is not supported), but use references in your spreadsheet to the previously generated rows.

**Comment by kevinpapst** [comment]
No feedback, closing
