### ISSUE TITLE
Multiple project periods in a single project

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2076]
**Is your feature request related to a problem? Please describe.**
Currently, a project that consists of sequential sub-projects must always be created as a sub-project with a fixed start and end date. The time / cost quotas then also belong to this sub-project.
If a follow-up project starts, this can be done by using the copy function, but in this case the connection between the sub-projects is lost. 
It also creates more projects than necessary, because in reality we are still adminstrating one single project.

**Describe the solution you'd like**
Allow any number of start / end periods with the associated time / cost contingents to be created within a single project.

**Comment by NagelKlaus** [comment]
I always read along silently, but now I have to take part.
I love this idea. With us, a project is a service contract for 1-3 years. Within the contract, maintenance work will be carried out on demand for 1-2 weeks. For this we have to create a new project every time. With the above idea one could cover different periods of time within a project, which reduces the administrative effort and increases the clarity in the project. An absolutely perfect solution!

**Comment by HeinzWuert** [comment]
this also solves #1882

**Comment by kevinpapst** [comment]
I have no plans to add this feature. 
I guess the simplest solution is to edit the project start/end dates after the last one ended.

Closing.
