### ISSUE TITLE
Import Customers from timesheet on the fly: Docs wrong or unclear or function broken

### ISSUE THREAD

**Issue by jannefleischer** [kevinpapst/kimai2#2077]
I just imported a kimai-timesheet from a former install following the documentation on https://www.kimai.org/documentation/imports.html#importing-timesheets

There it sais, that missing customers will be created on the fly. This doesn't really happens. Instead only one new customer "Imported customer" holding all the projects will be created. 

Now I have to decide if I want to move the database or reconfigure all my projects... little bummer... Meh. :/

Though: Thanks for this software-piece! :)

**Comment by kevinpapst** [comment]
What is 
> from a former install

I used this script for a couple of clients, so I am pretty sure that it works. 
The magic lies in the CSV that you throw at the script.

Please paste a couple of lines from your CSV.

**Comment by jannefleischer** [comment]
Oh sorry, I used the docker-environment and in there, there seem to be a kimai 1.8 instead of the current. Now updated. Everything seem to be fine now. Closing. :)

**Comment by kevinpapst** [comment]
That sounds better :)
