### ISSUE TITLE
Daterange picker does not work correctly with Sunday being first day of week

### ISSUE THREAD

**Issue by josephtingiris** [kevinpapst/kimai2#2078]
**Describe the bug**
If the timetracking mode is set to duration then the daterange picker does not render correctly when creating a new time entry.

**To Reproduce**
1. Go to Settings, enable `[Duration] replaces the end time ...`
2. Go to My Times, Click on + (add new entry)
3. Notice initial date is in the future, Click on date
3. See error; incorrect year (1920) and NaN for all calendar days

**Logfile**
```
does not produce any log messages
```

**Additional context**
 - Kimai version: 1.11
 - PHP version: 7.2.24
 - Device: Multiple
 - Browser All browsers

![image](https://user-images.githubusercontent.com/1857176/97729146-c234cc00-1aa8-11eb-863c-bd007c1f004e.png)

**Comment by kevinpapst** [comment]
Does that happen since an update?
Did you test it in the demo as well?

**Comment by josephtingiris** [comment]
No sure re: update.  I did recently upgrade from 1.10 to 1.11.  Though it was not on previously; I just turned it on and noticed it.  

It does not happen on any of the demos.

**Comment by josephtingiris** [comment]
I was able to reproduce it on the plugins demo.  I added a (single) custom field to Timesheets, like I have setup in my env.

**Comment by josephtingiris** [comment]
Sorry, I found the issue in the config.  Thanks for pointing me at the demos.  I was able to use them to quickly find & fix the problem.  This is not a bug, per say.

The issue was `Default start-time (not used in all timetracking modes)` was set to `Sunday` (which is an invalid date value).  Changing it back to `now` resolved the issue.  Validation on that field would be helpful.

**Comment by kevinpapst** [comment]
Hm, works for me on the plugins demo right now, in DE and EN.

That is the weird thing, as I have seen it as well in ONE installation before. I just thought it was some kind of browser plugin problem... because I wasn't able to reproduce it anywhere else.

It only happens for some months, so when you skip through the months it happened for March 2020/November 2020/August 2021. are for you?
Unfortunately your change in the config does not work for me, it is `now` and still happens.

**Comment by josephtingiris** [comment]
Change the config to `Sunday` rather than `now`.

**Comment by kevinpapst** [comment]
No: I mean I see the error in one of my systems as well. But the start day is `now` (and the time tracking mode `Default`). So I don't think the it has todo anything with those configs.
Also: the date picker is quite isolated from Kimai, it just receives the datetime object, language, date format + user timezone as input.

> It only happens for some months, so when you skip through the months it happened for March 2020/November 2020/August 2021.

Can you confirm that?

**Comment by josephtingiris** [comment]
Yes, confirmed, same behavior.  For me, changing it from `Sunda` to `now` fixed the initial month.  However the very next month reverts back to 1920 with NaN.  Then again every 9 months.

**Comment by josephtingiris** [comment]
This fixes it for me, and works in all of the use cases I've tested for both Sunday & Monday ...

```diff
diff --git a/src/Twig/Extensions.php b/src/Twig/Extensions.php
index 85fdc634..06f8ccf8 100644
--- a/src/Twig/Extensions.php
+++ b/src/Twig/Extensions.php
@@ -50,14 +50,14 @@ class Extensions extends AbstractExtension
     {
         $key = array_search(
             strtolower($weekDay),
-            ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
+            ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
         );
 
         if (false === $key) {
             return 1;
         }
 
-        return ++$key;
+        return $key;
     }
 
     /**
```
... but it's technically not true ISO weekday numbering per ISO 8601 and the functions & variables reference ISO in some way, i.e. _getIsoDayByName_, _iso_day_by_name_, or _first_dow_iso_   I don't seen anything other than fullcalendar using these.  Am I missing something?  I'd submit a PR, however I hesitated now that naming's misleading.  What to do about that?

**Comment by kevinpapst** [comment]
Good finding! But due to the naming issue I would rather add a new variable here: https://github.com/kevinpapst/kimai2/blob/master/templates/base.html.twig#L235 (`first_dow` - I guess you can re-use `first_dow_iso % 7`).

You (or me, if you don't have the stack installed) have to recompile the frontend assets after changing the code to use the new variable. eg. [here](https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiDatePicker.js#L30). Go ahead and start the PR and I will jump in 😄

**Comment by kevinpapst** [comment]
You could test #2084 to see if it fixes the issue on your end

**Comment by josephtingiris** [comment]
Yes, #2084 fixes it for me.  Thanks!
