### ISSUE TITLE
Timesheet view of all users add column showing team 

### ISSUE THREAD

**Issue by mdwcsc** [kevinpapst/kimai2#2079]
**Description**
In the timesheet view when logged in as an administrator it would be nice to have the ability to show the team the user is reporting time against so when exported we can roll up that value. Or have the ability to search time entries to show all belonging to a team.

**Screenshot**
Add a mockup / screenshot of your idea here

**Additional context**
 - Kimai version: 1.9
 - PHP version: 7.2.34

**Comment by kevinpapst** [comment]
That is impossible, as a user can be in multiple teams and multiple teams can have access to the same projects.
In theory that could be three different teams for customer, project and activity. 
I don't see a chance to get that information without some kind of customization.

**Comment by kevinpapst** [comment]
No feedback, closing
