### ISSUE TITLE
Can't store customer on activity

### ISSUE THREAD

**Issue by kulturbande** [kevinpapst/kimai2#2082]
**Describe the bug**
If I editing an activity and add a customer to it, the customer isn't stored!

**To Reproduce**
1. Go to '/admin/activity/'
2. Add a new activity without customer or project
3. open it again, add the customer and save it again
4. if you open it, the previous customer isn't selected

**Additional context**
 - Kimai version: 1.11.1
 - PHP version: 7.2.29
 - Device: [MacOS 10.15.7]
 - Browser [Firefox 82.0.2]

**Comment by kevinpapst** [comment]
Yes. The customer is only a filter for the project.
Same as in timesheet for example.

**Comment by kulturbande** [comment]
Ok, that is supprising. Thanks for the explaination.

**Comment by kevinpapst** [comment]
I added a sentence to the documentation to make that clear: https://www.kimai.org/documentation/activity.html
