### ISSUE TITLE
API: Patch to api/timesheets ignores "description"

### ISSUE THREAD

**Issue by JulesRenz** [kevinpapst/kimai2#2087]
First of all, THANKS A LOT for making Kimai. We have adopted it recently and it is a great tool, that we'd also like to contribute to.

**Describe the bug**
We use the API to track our times. Kimai accepts the field "description" when the timesheet is created but not when the timesheet is stopped. 
My understanding is, that I close/stop the timesheet for an activity when i switch tasks and this is the time when I think about what I have accomplished in the last minutes/hours and thats when I'd like to enter the description for a timesheet.

**To Reproduce**
1. Create a new TimeSheet via POST /api/timesheets. 
  - Note the record ID, that is returned. 
  - Note, that the returned description is null
2. Stop the TimeSheet via PATCH /api/timesheets/{{id}}/stop and provide a "description" in the JSON body
  - Note, that thre returned description is still null
  - Note, that in the UI, there is no description being displayed for the now stopped TimeSheet

3. Repeat but provide a "description" in the initial POST call.
  - now the description is returned as result of the POST call
![grafik](https://user-images.githubusercontent.com/8132086/97964687-79875680-1db9-11eb-8d67-3aae0815a29c.png)
  - but is unchanged when the TImeSheet is stopped and a new description is provided
![grafik](https://user-images.githubusercontent.com/8132086/97964745-8c9a2680-1db9-11eb-97d0-bc1cb744ff08.png)

**Additional context**
 - Kimai version: 1.11

**Comment by kevinpapst** [comment]
Hi!

I don't get why you flag this as bug the API clearly says that the stop endpoint is not accepting/supporting a request body:
<img width="1364" alt="Bildschirmfoto 2020-11-03 um 09 51 43" src="https://user-images.githubusercontent.com/533162/97965132-2feb3b80-1dba-11eb-82fd-ce3d7632fb14.png">

Simply issue a patch to the timesheet record explicit before (or after) you stopped it.

> that we'd also like to contribute to

Great 👍 can I assume that you want to contribute a patch for your **feature request**?

**Comment by JulesRenz** [comment]
Hi @kevinpapst, thanks for the quick reply. Of course you are right, I misunderstood the documentation.

I'll close this issue.

Regarding the patch ;) I'm not much of a php coder to be fair, but I'll give it a look.
Have a nice day!

**Comment by kevinpapst** [comment]
I am not saying that it is not a good idea to add that feature, as your use case sounds pretty legit. 

I was just arguing against the bug label 😁

**Comment by JulesRenz** [comment]
Ah, I see, maybe i was a bit quick to close the issue then. I'll give it a try with the code (and can open a pull request then) but if that does not work out, I can always go back to patching the timesheet before stopping it as you suggested.
