### ISSUE TITLE
Configure displayed attributes in Calendar view

### ISSUE THREAD

**Issue by marcseguin** [kevinpapst/kimai2#2090]
**Is your feature request related to a problem? Please describe.**
In the calendar view the displayed information is only about the activity. In some use cases this is not sufficient. 
![image](https://user-images.githubusercontent.com/5563153/97970560-fdddd780-1dc1-11eb-842e-139b9deb7e8a.png)

**Describe the solution you'd like**
The administrator is able to configure the displayed information in a configuration file. The configuration should support typical string manipulation (concat, substring, typecast from other datatypes, ...) across all attributes of a task.

**Describe alternatives you've considered**
n.a.

**Screenshot**
Here an illustration attempt ...
![image](https://user-images.githubusercontent.com/5563153/97972364-b0af3500-1dc4-11eb-8a88-b83c43b2861f.png)

**Comment by kevinpapst** [comment]
Was released in 1.19.x
