### ISSUE TITLE
project budget per month poosible ?

### ISSUE THREAD

**Issue by kurznet** [kevinpapst/kimai2#2095]
Hi,
how can i assign a budget for a project per month..
i only saw a budget value over all but not per month
For example project A i have a budget for 20h every month if budget is full than info..

is this possible if yes how ?

**Comment by kevinpapst** [comment]
That is not possible by now. I will keep it open, as feature request.

**Comment by HeinzWuert** [comment]
Maybe my FR #2076 will fit here too!
The project stays always the same, only start/end of project and time/money budget can be added multiple times.

**Comment by tobiasgraeber** [comment]
Hi @kevinpapst any suggestion for a good starting point to realize this feature? 

How does kimai2 handle cronjobs (i think we would need some, or at least some logic to handle the recurring calculation of bugets, or?)...and this would also help -> https://github.com/kevinpapst/kimai2/issues/1990 (if availeable, maybe we could make use of the api for this, for example by just updating the buget of a project/activity/customer once a month via a little calculation script (sum up) and update statement via cron/api ...?

**Comment by kevinpapst** [comment]
In theory... you don't need a cronjob, you could "simply" group time records by month.
The budget would need to have a new field, like a "period type".

**Comment by tobiasgraeber** [comment]
Yes. Can you share some more details how to start? Maybe i can have a look
into this. Somewhere the calculations would of course need to be done. Not
sure where and how at the moment. Also not sure on how to "track" the
budget changes and also "credit" or negative budgets could be a thing.

For example, let's say you have a customer with a time budget of 10h/month.
Now the following situation happens : 5 hours of work are done in one
month, month is over, so 5 hours budget left. If these 5 hours should not
"get lost" an additional requirement could be to add them (with the next
month) to the budget of 10h. So 15h would be the budget in the next month.
In this month, 20h work are done so - 5h would be the budget at the end of
the month - leading to again +5h budget in the next iteration and so on...

How/where would you handle this?

Are the API endpoints for budgets are already on the roadmap?

Kevin Papst <notifications@github.com> schrieb am So., 24. Jan. 2021, 02:50:

**Comment by kevinpapst** [comment]
This is too big in my opinion for the first move.
Support a budget period first, add a simple report with these results (calculated on the fly, you can `select duration group by month/date`) and add a pagination to the details page to step through the single periods/months.
This should be more than enough for a first PR.

**Comment by HeinzWuert** [comment]
This goes along with #2076.
But there are two options you have to consider:
1. overtake not used contingents
2. cut off not used and start with default monthly contingent

**Comment by HeinzWuert** [comment]
becomes more and more important!

**Comment by Stan-Sch** [comment]
I would also need such a function.
We receive orders from the public sector.
The term goes over several months.
The hourly quota is to be billed monthly.
The first month is calculated proportionally depending on the start date.

In the current version of Kimai, I would have to create a series of projects for a contract, even though it is only one project.
With around 15-20 such contracts, unfortunately, there is such a workload that introducing Kimai is not worthwhile, even if all the other features on our test installation were convincing.
If this problem is solved, we will be happy to introduce Kimai to us.

**Comment by kevinpapst** [comment]
@Stan-Sch if you want to use a free software, you should consider to support development of a feature that you require

**Comment by kevinpapst** [comment]
budget per month is supported since a couple of month
