### ISSUE TITLE
Invoice - one entry per project but several entries are shown

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#2099]
Several entries for one project are shown in the invoice (doc template) although it was configured "one entry per project"

log in to Demo and create customer "Test" and project "Testprojekt"
create two timesheets for this customer and project, one with fixed rate of 500 Euro, the other one without rates

configure invoice.doc template to "one entry per project" 

create invoice for customer "Test" using the invoice template - the invoice shows two entries "Testprojekt", one with unit price 0 Euro and one with unit price 500 Euro

I hoped to have just one entry showing 500 Euro as total price for the project "Testprojekt" (as the template "one entry per project" suggests) - my overall goal is still to find a workaround to have a fixed price for a project to be shown in the invoice no matter how many hours I have spent on the project and combine it with the costs plugin, so that the invoice has two lines showing the fixed project fees and the project costs disregarding of the amount of the timesheet entries.

**Comment by kevinpapst** [comment]
Three solutions that come to my mind: 

1. Manual work per invoice with available features:
- Set all related records to exported and only leaves the one fixed rate entry open
- Export this one entry

2. One time work by building a new template:
- Use a twig template (maybe possible with Excel as well) for rendering the invoice
- Filter all entries that are timesheets and group them into one line, using the project budget as price

3. One time work for building that thing:
- Build a custom sum calculator that does exactly what you want

**Comment by BeckeBauer** [comment]
So, the "Invoice - one entry per project" is not a working option yet? 

Anyway, the work around's 1 and 2 are not favourable since we work with word-documents. Do you offer paid support for the third option?

**Comment by kevinpapst** [comment]
I admit "one entry per project" is a misleading naming and these invoice features need more documentation in general...

So these "grouping" invoice calculators will do the following:
- they group entries by the announced attribute (here by [the project id](https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/ProjectInvoiceCalculator.php#L27))
- by the rate type
- by the rate amount

See https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/AbstractSumInvoiceCalculator.php#L39-L43 for the last two.

So in the unlikely case of very will rate mixing you could still have many lines in the invoice, even though it says "one entry per project".

Why? Imagine:
- 1 timesheet with 4,5 hours for 55€
- 2 timesheets with 1 hour each for 80€
- 1 timesheet with 0,5 hours and a fixed rate of 100€
- 1 timesheet with 3 hours and a fixed rate of 200€

What should the one entry show? The total amount obviously, but which amount and which price for a single item?
Everyone expects a different outcome here, as always 😁 

But we can quite easily add a new calculator which will group by project and object type (expense vs timesheet).
I'd propose adding a "Fixed price" invoice calculator, which will use the projects budget as invoice total. 
Amount is 1 and single item price is the budget again.
Other option would be to use the logged amount of hours as "amount" and the single price would be the budget / hours.

I offer paid support for almost everything related to Kimai.

**Comment by BeckeBauer** [comment]
Your proposal would work fine with me (projects budget as invoice total), combined with a monthly project budget in the future would be perfect.
I would not need a single item amount for this line but if, the total amount of hours would make more sense for me than just the number '1'. 
How does it work with paid support?

**Comment by kevinpapst** [comment]
Email please => info@keleo.de
