### ISSUE TITLE
question concerning usage of "bin/console kimai:invoice:create"

### ISSUE THREAD

**Issue by marcseguin** [kevinpapst/kimai2#2100]
Hi,

I need to generate invoices from the console with the command `bin/console kimai:invoice:create ...` for all projects and customers *except* one customer. How can I exclude a single customer number or project number from being considered?
My current command looks like `bin/console kimai:invoice:create --verbose  --user=<the user> --start=2020-01-01 --end=2020-10-31 --timezone=Europe/Berlin --by-project --template-meta=_inv_template` and I hope that the additional parameter `--search` could make the trick but I don't find any documentaiton about this parameter.

**Additional context**
 - Kimai version: 1.11.1
 - PHP version: 7.2.24

Thx

**Comment by kevinpapst** [comment]
Hi!

> I need to generate invoices

Who forces you to do so? 😁 

> the additional parameter --search could make the trick but I don't find any documentaiton about this parameter.

The `--search` flag is the same as the free search term field in the invoice creation screen.
I don't think that you can use it to filter customer.

Or in other words: invoice creation is currently a whitelisting and not a blacklisting approach.
Adding flags to filter customer (when using `--by-customer`) or projects (when using `--by-project`) is feasible. As that is a very advanced topic I do offer paid support for it.

**Comment by kevinpapst** [comment]
no feedback, closing
