### ISSUE TITLE
Calendar view after logging time shows resume activity

### ISSUE THREAD

**Issue by marck-gee** [kevinpapst/kimai2#2105]
**Describe the bug**
When logging time, either via fixed time, or via continuous logging mode, when I switch to the calendar only the most recent time logging is shown, asking me if I want to resume, even if the activity is already stopped.

**To Reproduce**
1. Log time using the play button as any user
2. Enter any data (either fixed duration, or open-ended)
3. return to the calendar view

The following is displayed:

![Kima_1 11 1_Calendar_Issue_20201109](https://user-images.githubusercontent.com/74202597/98572149-963df580-22b5-11eb-8260-b5c9bce4aefb.png)

without any calendar

If the offending logged time is deleted, then the calendar view works correctly

**Logfile**
```
None, running under docker (logdir /opt/kimai/var/log is empty, and docker logs kimai2 only show HTTP requests)
```

**Additional context**
 - Kimai version: 1.11.1 (docker)
 - PHP version: ?.?
 - Device: Windows, Mac
 - Browser: Tested Chrome, Firefox, IE

**Comment by kevinpapst** [comment]
I need logs and more information.
Try to reproduce it on the demo and then post a message here, so I can see it myself.

**Comment by kevinpapst** [comment]
https://www.kimai.org/demo/

**Comment by marck-gee** [comment]
I am not able to reproduce it under on the demo environment, but I see this in my testing environment that is a clean, fresh install of 1.10.2, upgraded to 1.11.1 with no data.

Do you have any suggestions on how I can help reproduce this, or send you more detailed logs?

**Comment by kevinpapst** [comment]
Please spin up a completely fresh docker image and try it again. We need to find out if that is a general problem (I doubt that) or an update problem or some strange configuration issue.

**Comment by marck-gee** [comment]
With a fresh docker image, and no configuration changes, using the same configuration files (cp -r the directory) as my production and testing environment, I do not see a problem. The activities shows up correctly in the calendar view after logging time.

Can I send any additional files, or look in the DB for the configuration?

[cid:image001.jpg@01D6B76A.55A1C5D0]

--
Marck Gorszwick • Senior Staff Engineer
Phone +4989215372448 • www.brusa.biz<http://www.brusa.biz>
BRUSA Elektronik (München) GmbH • Hollerithstr. 7A • DE-81829 München

Amtsgericht München, HRB 246963, USt-IdNr. DE-323058060
Geschäftsführer: Thomas Nindl, Thomas Würz

[cid:SocialLink_Linkedin_32x32_225bd7cc-87d5-450b-9566-33b87b69ff92.png]<https://www.linkedin.com/company/brusa-elektronik-ag/> [cid:SocialLink_Facebook_32x32_e3f78c22-982d-4607-9a48-39c89c943f87.png] <https://www.facebook.com/BRUSAElektronikAG/> <https://www.facebook.com/user_name_here>

Any e-mail sent from BRUSA Elektronik (München) GmbH may contain information which is confidential and/or privileged. Unless you are the intended recipient, you may not disclose, copy or use it; please notify the sender immediately and delete it and any copies from your systems. We protect our system from viruses etc. In case however a message is virus contaminated we accept no responsibility for damage that may be caused by it.

**Comment by kevinpapst** [comment]
If you have a docker mount for the public/ directory, try to replace its contents with the one from the fresh image.

If Kimai works as expected in a fresh install it is likely an updating issue.
And if you are using the tobybatch docker images, its better to ask in the repository directory.

**Comment by marck-gee** [comment]
Replacing the public volume also fixed the problem.

Running a diff on the directories (diff -qr) shows this:


Only in /var/lib/docker/volumes/kimai2-dev-temp_public-dev-temp/_data/build: 1.32489d92.js
Only in ./build: 1.512c747c.js
Only in /var/lib/docker/volumes/kimai2-dev-temp_public-dev-temp/_data/build: app.0325b7e0.css
Only in ./build: app.554717a4.css
Only in ./build: app.cafc411b.js
Only in /var/lib/docker/volumes/kimai2-dev-temp_public-dev-temp/_data/build: app.dc6c3f34.js
Only in ./build: calendar.0e49d4da.js
Only in /var/lib/docker/volumes/kimai2-dev-temp_public-dev-temp/_data/build: calendar.541a15eb.js
Files ./build/entrypoints.json and /var/lib/docker/volumes/kimai2-dev-temp_public-dev-temp/_data/build/entrypoints.json differ
Files ./build/manifest.json and /var/lib/docker/volumes/kimai2-dev-temp_public-dev-temp/_data/build/manifest.json differ

The files in . are from the errant public directory, while those in /var/lib are from the working public directory

Does any of this help? If not, I’ll just swap the working public volume into production.

Thanks again for your help!


--
Marck Gorszwick • Senior Staff Engineer
Phone +4989215372448 • www.brusa.biz<http://www.brusa.biz>
BRUSA Elektronik (München) GmbH • Hollerithstr. 7A • DE-81829 München

Amtsgericht München, HRB 246963, USt-IdNr. DE-323058060
Geschäftsführer: Thomas Nindl, Thomas Würz

[cid:SocialLink_Linkedin_32x32_225bd7cc-87d5-450b-9566-33b87b69ff92.png]<https://www.linkedin.com/company/brusa-elektronik-ag/> [cid:SocialLink_Facebook_32x32_e3f78c22-982d-4607-9a48-39c89c943f87.png] <https://www.facebook.com/BRUSAElektronikAG/> <https://www.facebook.com/user_name_here>

Any e-mail sent from BRUSA Elektronik (München) GmbH may contain information which is confidential and/or privileged. Unless you are the intended recipient, you may not disclose, copy or use it; please notify the sender immediately and delete it and any copies from your systems. We protect our system from viruses etc. In case however a message is virus contaminated we accept no responsibility for damage that may be caused by it.

**Comment by kevinpapst** [comment]
That is a known problem... https://github.com/tobybatch/kimai2/issues/158

I am not sure if that mount is really necessary, but better head over to the docker issue and share your findings there!

Closing here.
