### ISSUE TITLE
Installation issue on CentOS7 via SSH

### ISSUE THREAD

**Issue by MikeSierraRO** [kevinpapst/kimai2#2108]
**Description**
I successfully installed Kimai on a CentOS 7, but now when I want to run the Kimai behind a nginx-reverse-proxy, I receive error: 2020/11/11 13:47:30 [error] 5283#0: *2 open() "/home/billing/public_html/kimai2/public/en/login" failed (2: No such file or directory$/kimai2/public/en/login"

**Screenshot**
![kamai](https://user-images.githubusercontent.com/56639628/98808558-fef7b000-2424-11eb-8b51-2d67109a53c8.png)
This is my NGINX Config file.

**Additional context**
 - Kimai version: latest version
 - PHP version: PHP 7.3.24 (cli) (built: Oct 27 2020 11:01:59)

**Comment by MikeSierraRO** [comment]
Forgot to initially ad, I also specified (as in tutorial) the trusted proxies, but without any help.

**Comment by kevinpapst** [comment]
This is all I can say to Reverse Proxy:
https://www.kimai.org/documentation/webserver-configuration.html#reverse-proxy

I assume your config is wrong.

**Comment by MikeSierraRO** [comment]
Changed the second "location" from location ~ \.php$ to simply location / how tutorial recommends.

Now it displays a blank page, but no errors in /var/log/nginx.

Any ideeas? :D

**Comment by kevinpapst** [comment]
Permissions? https://www.kimai.org/documentation/faq.html#i-have-a-problem

**Comment by MikeSierraRO** [comment]
Nope, I even tried with chmod -R 777 on the whole directory, it won't work.

**Comment by MikeSierraRO** [comment]
Nevermind, I aborted the installation on Centos and completed it on cPanel but I found another error.

Thanks.
