### ISSUE TITLE
Plugin for customizable areas

### ISSUE THREAD

**Issue by MikeSierraRO** [kevinpapst/kimai2#2110]
**Is your feature request related to a problem? Please describe.**
Nope, it's just an ideea.

**Describe the solution you'd like**
I would really like to see a plugin that allow you to create custom sections like the "Activities" one for example. Let's say that the company needs a section where to enter all the Receipts that have been issued, or a section where all Employees to be registered with fully customizable Titles, buttons and options.

For example, I want to create Section/Area named "Employees", the plugin should ask me what name would I like to enter for the new Section/Area and let me create it. After I created the Section/Area, to have the option to add custom Values like: "Date that Employee was hired", "Is the Employee still working", "Where does the Employee Work (Branch/HQ)" with radio buttons.

Also, would be really interesting if there would be added the option for adding "IP Addresses", masking the "Password" option, add a "Last edited by user" option and so on.

**Describe alternatives you've considered**
I didn't considered an alternative.

**Screenshot**
Well.. that's why I suggest this, I can't provide screenshots :).

**Comment by kevinpapst** [comment]
I do appreciate feedback, feature request and such - but I don't see this one come to reality:

A. This is not Wordpress... 
B. And then? You have the data and what? If you need a database, use a database. Kimai is not a CMS or application builder framework. It is mainly a time-tracker with add-ons.
C. If you need a custom solution for special business use-cases, I offer paid services.

But have a look at the custom fields plugin: https://www.kimai.org/store/custom-fields-bundle.html - maybe it already offers some of the features you need (new user fields).
