### ISSUE TITLE
red line when overlapping times are detected disapears while zooming

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2113]
It's not really a bug.
When zooming the browser window the red line disapears sometimes.
Maybe it*s only a one dot line used by kimai and this could be prevented with a 2 oder 3 dot line.

**Comment by kevinpapst** [comment]
Currently it is 2px.

Can be changed by using the CustomCSSBundle and applying a CSS rule:
```css
tr.overlapping { 3px dotted red; }
```

By default everything looks okay.
What I do see is: when zooming out (making everything smaller) the line disappears at some point.
That is wanted behavior (by the browser). There is no way to detect the users zoom level and apply different styles.
Making the line larger by default looks silly.

Interesting, I never tried to zoom out. But unfortunately nothing we can do about it => closing
