### ISSUE TITLE
FR: Duration Only Mode Improvement

### ISSUE THREAD

**Issue by alderson59** [kevinpapst/kimai2#2114]
**Is your feature request related to a problem? Please describe.**
Duration only mode is amazing but it gives users no flexibility on the date on which the task was done.

In consulting, it doesn't matter when you do a certain task, but how many hours - since these are billable. It's important for managers to keep track of how many hours are charged each week for budgeting.

Users are also probably too busy to keep adding hours every single day, and most likely will do at the end of the work week, or even fortnight, in some companies.

Thus, let's say at the end of a work week, users key in how many hours they spent on each task for the week. It would be impractical to set start and end times due to the amount of input and self-tracking required. Duration is perfect, but without the ability to change the date, users cannot batch add the tracking, and must do tracking for each day.

**Describe the solution you'd like**
Several options for your consideration:
1. Add the ability to change the date only for duration only mode.
2. Add a new mode "duration and date" which is exactly as duration, but with ability to change date.

Use the date selector which is already in the time mode, but remove the time aspect of it. Only date. And Duration.

**Describe alternatives you've considered**
I'm stuck between the two currently available modes: duration only (without date) or change start date (and time), and both of these options hamper the user experience. Users get confused when they see the time and attempt to make everything match so it doesn't overlap.

I have not yet been able to deploy Kimai in production due to this. We're still stuck with spreadsheets for now! 😅

**Screenshot**
![image](https://user-images.githubusercontent.com/69715968/98859823-ba5c2b00-249d-11eb-88db-46745c60a9db.png)

**Comment by kevinpapst** [comment]
Changing the existing mode won't happen. It is used and required by several companies like it is.

> Add a new mode "duration and date" which is exactly as duration, but with ability to change date.

More like the "duration, replace end time mode" which already does what you want, but keeps track of the start time. That should be fairly easy.

You should probably try to use the default mode AND then use the calendar drag & drop feature, which might be the fastest way to batch add entries.
Or you use the "copy timesheet" function and simply change the date.
Both are much faster than filling the entire form for each record.

> I have not yet been able to deploy Kimai in production due to this.

What a luxury problem. 

> We're still stuck with spreadsheets for now

Sorry to hear that 😁

**Comment by alderson59** [comment]
> What a luxury problem.
😅 ^ Golden comment.


> You should probably try to use the default mode AND then use the calendar drag & drop feature, which might be the fastest way to batch add entries.
I suppose this is a good solution, but still has the time problem. Also leaves more wiggle room for errors on the users' input part. 

If there's anything I know about UI/UX, is that if you give an opportunity for someone to make a mistake, THEY WILL! 😫


I could use your suggestions in the mean time, but any chance of getting that little addition? A new mode perhaps? It should *theoretically* be drawing on the existing coding, with a few modifications, so not much changes to be made. Though what do I know, I'm not a dev lol.

This may sound like a really niche problem but I've personally been in several very large firms that operate with this same timesheet format, though they had massive budgets to develop their own proprietary in-house apps for that, hah!

I suppose that's why they never had to open github issues to request features for the community :P

**Comment by kevinpapst** [comment]
I accept payed contracts to add new tracking modes. But I don't see a lot of requests for new modes, so I will close this one for now
