### ISSUE TITLE
Supprt a default project and activity 

### ISSUE THREAD

**Issue by bernd-wechner** [kevinpapst/kimai2#2117]
I suggest user preferences as follows:

- Default to same as previous activity
- Default to these:
    - Default project
    - Default activity

The first tier being radio buttons, and the first option means the Project and Activity fields are prepopulated with my previous selections. So I can stop and start more easily on the same job.

**Comment by kevinpapst** [comment]
Everyone who voted in this issue should revote in #403 and #699

Closing as duplicate here
