### ISSUE TITLE
Consolidation of items in the search function between time recording and expenses

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2118]
Optical correction:
If you click on Search in the two modules, the order of the search terms is different.
It would be nicer if outputs were adapted to the search field of time entries.

**Comment by kevinpapst** [comment]
What about adding some more explanation?

**Comment by HeinzWuert** [comment]
This is the  search form from activities and should be the "master" for search items regarding the order.
![image](https://user-images.githubusercontent.com/45666972/98926510-b3520e80-24d7-11eb-9761-d1c8acf2caec.png)

correct the form in expenses, which looks so:
![image](https://user-images.githubusercontent.com/45666972/98926646-df6d8f80-24d7-11eb-91c6-a7377dfb7c2e.png)

**Comment by kevinpapst** [comment]
thanks. after posting I saw it as well. 
so many details that you easily miss when working on a product. thanks for posting!
I moved the fields around for the next update
