### ISSUE TITLE
I can still delete a time entry from a locked period

### ISSUE THREAD

**Issue by petervanhee** [kevinpapst/kimai2#2121]
**Describe the bug**

Time entries from a locked period can still be deleted by the person who made the time entry.

**To Reproduce**
Setup for locking a period is like this:
![image](https://user-images.githubusercontent.com/69186790/98936836-d7b4e780-24e5-11eb-9ae6-ff49c0f554cd.png)

Today, November 12, we should not be able to make any changes on time entries of October. This works fine in case you want to modify or make of copy of a time entry ==> you get a message and you are not able to do the change.
![image](https://user-images.githubusercontent.com/69186790/98937524-cc15f080-24e6-11eb-9c38-1b0aa0ebce8d.png)

But when deleting a time entry of October, you are not blocked by the system and the time entry disappears after pushing the delete button on the confirmation popup.
![image](https://user-images.githubusercontent.com/69186790/98937659-041d3380-24e7-11eb-8f65-55b501cfbb32.png)
![image](https://user-images.githubusercontent.com/69186790/98937729-21520200-24e7-11eb-950c-ba016c831e69.png)

**Logfile**
```
Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
```

**Additional context**
 - Kimai version: 1.11.1
 - PHP version: 7.3
 - Device: Windows notebook
 - Browser Chrome  86.0.4240.183

**Comment by petervanhee** [comment]
@kevinpapst Can you give an update on this please?

**Comment by kevinpapst** [comment]
Can be tested in the development demo => "Edit" and "Create copy" buttons will be hidden, "Delete” button is hidden and action is prevented

**Comment by petervanhee** [comment]
I tested it in the development demo and seems ok
