### ISSUE TITLE
Calendar view not showing the calendar

### ISSUE THREAD

**Issue by x-jokay** [kevinpapst/kimai2#2123]
**Describe the bug**

It was working on `1.10` but after the update to `1.11` and later `1.11.1` the calendar on the calendar view is missing. 

![calendar](https://user-images.githubusercontent.com/18613935/98954226-dabbd200-24fd-11eb-8351-a33f68431f12.png)

Can this be the result of some missing assets?

**To Reproduce**

1. Go to 'Calendar'
2. Shows no calendar

**Logfile**

```sh
Empty logfile
```

**Additional context**

 - Kimai version: 1.11.1
 - PHP version: 7.4.12
 - Device: Debian 10
 - Browser: Firefox 82.0.3

**Comment by kevinpapst** [comment]
Yes, very likely. 
The old assets are loaded and the new draggable include (which is only activated on the calendar page) can't be found.

It works in fresh and upgraded "native" installations, so it must be your public volume. 
Perfect moment after reviewing the new upgrade docs by @tobybatch to give it a try and share if it worked!

**Comment by x-jokay** [comment]
Ok, will further investigate and we may close the issue 👍🏼

**Comment by x-jokay** [comment]
Was a problem with not up-to-date assets, issue can be closed.
