### ISSUE TITLE
Calendar: provide possibility to delete a time entry in the calendar view

### ISSUE THREAD

**Issue by petervanhee** [kevinpapst/kimai2#2124]
**Is your feature request related to a problem? Please describe.**
I am not able to delete a time entry in the calendar view. You can add, modify or even move a time entry to another day but you can not delete a time entry in the calendar view.

**Describe the solution you'd like**
Possibility to delete a time entry in the calendar view

**Describe alternatives you've considered**
In My Timesheets you can delete the time entry

**Comment by HeinzWuert** [comment]
matching #2053

**Comment by kevinpapst** [comment]
Kimai 1.14 will ship a drag & drop area to delete an entry:
<img width="436" alt="Bildschirmfoto 2021-04-19 um 21 40 43" src="https://user-images.githubusercontent.com/533162/115293682-e7e98680-a157-11eb-8f7c-7729360481be.png">
Pulling a record on that button will delete the timesheet.

Clicking the button will show an alert to instruct the user what to do:
<img width="479" alt="Bildschirmfoto 2021-04-19 um 21 41 31" src="https://user-images.githubusercontent.com/533162/115293768-02236480-a158-11eb-85c7-5153d331bd34.png">
