### ISSUE TITLE
Failed to create database: An exception occurred in driver: could not          find driver

### ISSUE THREAD

**Issue by SoufianBakhti** [kevinpapst/kimai2#2126]
**Description**
hi everyone,

After composer install --no-dev --optimize-autoloader
i get this message issue:
![image](https://user-images.githubusercontent.com/74318103/99200123-c39e0e00-27a3-11eb-9384-895d031d9e66.png)

bin/console kimai:install :

 Create the database "/var/www/kimai2/var/data/kimai.sqlite" (yes) or skip (no)? (yes/no) [yes]: yes

 [ERROR] Failed to create database: An exception occurred in driver: could not find driver

**Screenshot**
Add a mockup / screenshot of your idea here

**Additional context**
 - Kimai version: v2 - https://github.com/kevinpapst/kimai2.git
 - PHP version: PHP 7.2.24-

**Comment by kevinpapst** [comment]
Besides the fact that I will definitely not support Kimai 1.1, which was released more than 1 year ago, you need the sqlite extension when you want to use it: https://www.kimai.org/documentation/installation.html#sqlite-not-supported-for-production-usage
I do not support sqlite on production => closing.

**Comment by SoufianBakhti** [comment]
thank you for your respond,
i think this is kimai2 not kimai1.1

**Comment by Julien-asv** [comment]
Hi, I followed the install guide of kimai 2 (here : https://www.kimai.org/documentation/installation.html#recommended-setup ), and i have the same issu as you SoufianBakhti.
Ubuntu 20.04
PHP 7.4.3

do you find a solution ?
Thank you

**Comment by kevinpapst** [comment]
@SoufianBakhti version 1.1 from Kimai 2 is not the same then the latest version (screenshot from installation):
<img width="791" alt="Bildschirmfoto 2020-11-19 um 12 21 43" src="https://user-images.githubusercontent.com/533162/99659849-ca59a900-2a61-11eb-9cb9-19ae8633edcc.png">

@Julien-asv 
Change into kimai directory and type `cat src/Constants.php|grep VERSION` (or open the file with some an editor).
You should see `public const VERSION = '1.11.1';`.

**Comment by Julien-asv** [comment]
Hi, yes when i type _src/Constants.php|grep VERSION_ i have _public const VERSION = '1.11.1';_

**Comment by kevinpapst** [comment]
And you see this exact message with `Kimai installer - v1.1`?

![](https://user-images.githubusercontent.com/74318103/99200123-c39e0e00-27a3-11eb-9384-895d031d9e66.png)

**Comment by Julien-asv** [comment]
The error message yes. Not the title. Mine is : Kimai installation running ... not Kimai installer - v1.1

**Comment by kevinpapst** [comment]
Then you don't have sqlite support in PHP. 
You need to install it (the php extension).

But be aware: you will not be able to upgrade Kimai. SQLite is only meant for development:
https://www.kimai.org/documentation/installation.html#sqlite-not-supported-for-production-usage

**Comment by Julien-asv** [comment]
Thank you it's working now. Just somes littles issues but maybe it's because it's a dev build. But what is the proper way to isntall Kumai ? I just follow from main site "The recommended way to install Kimai!".

**Comment by kevinpapst** [comment]
The "proper way" includes changing the database connection to mysql:

> Configure the database connection in the `.env` file:
>
> ```
> DATABASE_URL=mysql://user:password@127.0.0.1:3306/database
> ```
