### ISSUE TITLE
Create an event on timesheet create or update

### ISSUE THREAD

**Issue by senormedia** [kevinpapst/kimai2#2128]
Im trying to add a curl event when a timesheet is created or updated

I created a plugin, do i need bring over Timesheet/ folder classes to the plugin to create the event

pretty much trying to send the timesheet info to another server on update or create

anyway to proceed on this let me know

**Comment by kevinpapst** [comment]
Listen to the Timesheet*Pre/Post Events and then trigger your curl call.

See https://github.com/kevinpapst/kimai2/tree/master/src/Event

**Comment by senormedia** [comment]
gotcha so i register by copying overt the same class on event or event subscribe folder

**Comment by kevinpapst** [comment]
Maybe these links help:
https://symfony.com/doc/current/event_dispatcher.html
https://github.com/Keleo/DemoBundle

**Comment by senormedia** [comment]
ok let me give it a try, i was able to get some more knowledge using the demo info

just confused ill give that listen to see how it works

**Comment by senormedia** [comment]
i was able to hook in with using the calculator template from the recalculator rates plugin,

i tried the same for timesheet secure but did not work, i also did a an event subscriber 

namespace KimaiPlugin\PluginBlundle\Timesheet\Calculator;

use App\Entity\Timesheet;
use App\Timesheet\Calculator\RateCalculator;
use App\Timesheet\CalculatorInterface;

class RecalculateRateCalculator implements CalculatorInterface
{
    /**
     * @var RateCalculator
     */
    protected $calculator;

    public function __construct(RateCalculator $calculator)
    {
        $this->calculator = $calculator;
    }

    /**
     * @param Timesheet $record
     */
    public function calculate(Timesheet $record)
    {
        $curl = curl_init();
        $customer_create = array();
        $customer_create["calculate"] = json_encode($record);
        $customer_create["id"] = json_encode($record->getId());
        $jsonArray = json_encode($customer_create);

        curl_setopt_array($curl, array(
            CURLOPT_URL => "https://webhook.site/",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $jsonArray,
            CURLOPT_HTTPHEADER => array(
                "Content-Type: application/json",
                "X-AUTH-USER: senormedia",
                "X-AUTH-TOKEN: potatoes",
            ),
        ));
        $response = curl_exec($curl);
    }
}


Event Subscriber for time sheet

use App\Event\ThemeEvent;
use App\Event\TimesheetMetaDisplayEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class PluginEventSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            TimesheetMetaDisplayEvent::EXPORT => ['renderTimesheetMetaDisplayEvent', 100],





Timesheet Service
namespace KimaiPlugin\PluginBundle\Timesheet;

use App\Configuration\TimesheetConfiguration;
use App\Entity\Timesheet;
use App\Entity\User;
use App\Event\TimesheetCreatePostEvent;
use App\Event\TimesheetCreatePreEvent;
use App\Event\TimesheetDeleteMultiplePreEvent;
use App\Event\TimesheetDeletePreEvent;
use App\Event\TimesheetMetaDefinitionEvent;
use App\Event\TimesheetRestartPostEvent;
use App\Event\TimesheetRestartPreEvent;
use App\Event\TimesheetStopPostEvent;
use App\Event\TimesheetStopPreEvent;
use App\Event\TimesheetUpdateMultiplePostEvent;
use App\Event\TimesheetUpdateMultiplePreEvent;
use App\Event\TimesheetUpdatePostEvent;
use App\Event\TimesheetUpdatePreEvent;
use App\Repository\TimesheetRepository;
use App\Security\AccessDeniedException;
use App\Validator\ValidationException;
use App\Validator\ValidationFailedException;
use InvalidArgumentException;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

//final class TimesheetService
class PluginTimesheetService implements TimesheetService
{
    protected $timesheetService;

    public function __construct(Timesheet $timesheetService)
    {
        $this->$timesheetService = $timesheetService;
    }
    public function createNewTimesheet(User $user, ?Request $request = null): Timesheet
    {
    }

    public function prepareNewTimesheet(Timesheet $timesheet, ?Request $request = null): Timesheet
    {

    }

    public function restartTimesheet(Timesheet $timesheet, Timesheet $copyFrom): Timesheet
    {
    }

    public function saveNewTimesheet(Timesheet $timesheet): Timesheet
    {


        //return $timesheet;
    }
    public function updateTimesheet(Timesheet $timesheet): Timesheet
    {
        // there is at least one edge case which leads to a problem:
        $curl = curl_init();
        $customer_create = array();
        $customer_create["timesheet"] = json_encode($timesheet);
        $customer_create["timesheet_end"] = json_encode($timesheet->getEnd());
        $jsonArray = json_encode($customer_create);

        curl_setopt_array($curl, array(
            CURLOPT_URL => "https://webhook.site/",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $jsonArray,
            CURLOPT_HTTPHEADER => array(
                "Content-Type: application/json",
                "X-AUTH-USER: senormedia",
                "X-AUTH-TOKEN: potatoes",
            ),
        ));
        $response = curl_exec($curl);
        return $timesheet;
    }
    public function updateMultipleTimesheets(array $timesheets): array
    {
    }
    public function stopTimesheet(Timesheet $timesheet): void
    {
    }

    public function deleteTimesheet(Timesheet $timesheet): void
    {
    }

    public function deleteMultipleTimesheets(array $timesheets): void
    {
    }

    /**
     * @param Timesheet $timesheet
     * @param string[] $groups
     * @throws ValidationFailedException
     */
    private function validateTimesheet(Timesheet $timesheet, array $groups = []): void
    {
    }

    /**
     * Stops all active records for the current user, besides the given $timesheet.
     *
     * @param Timesheet $timesheet
     * @return int
     * @throws ValidationException
     * @throws ValidationFailedException
     */
    private function stopActiveEntries(Timesheet $timesheet): int
    {
    }
}

**Comment by kevinpapst** [comment]
Please use StackOverflow to ask Symfony specific questions, I cannot teach you how to use it properly.
Kimai events are based on https://symfony.com/doc/current/event_dispatcher.html on the work properly in other plugins.

**Comment by senormedia** [comment]
Incase some one needs this

Create a file called TimesheetSubscriber.php insed your EventSubscriber Folder in your plugin

use App\Event\TimesheetCreatePostEvent;
use App\Event\TimesheetCreatePreEvent;
use App\Event\TimesheetDeleteMultiplePreEvent;
use App\Event\TimesheetDeletePreEvent;
use App\Event\TimesheetMetaDefinitionEvent;
use App\Event\TimesheetRestartPostEvent;
use App\Event\TimesheetRestartPreEvent;
use App\Event\TimesheetStopPostEvent;
use App\Event\TimesheetStopPreEvent;
use App\Event\TimesheetUpdateMultiplePostEvent;
use App\Event\TimesheetUpdateMultiplePreEvent;
use App\Event\TimesheetUpdatePostEvent;
use App\Event\TimesheetUpdatePreEvent;
use App\Event\TimesheetMetaDisplayEvent;
use App\Repository\TimesheetRepository;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class TimesheetSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
          TimesheetCreatePostEvent::class => 'onTimesheetCreate',
          TimesheetUpdatePostEvent::class => 'onTimesheetUpdate',
          TimesheetDeletePreEvent::class => 'onTimesheetDelete',
          TimesheetStopPostEvent::class => 'onTimesheetStop',
      ];
    }

  public function onTimesheetCreate() .... etc....

**Comment by kevinpapst** [comment]
Thanks for sharing!
