### ISSUE TITLE
allow time entry for reporting / initial view

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#2131]
**Is your feature request related to a problem? Please describe.**
Usability is key. The reporting page already enhances overview by a lot, why not allow time entries?

**Describe the solution you'd like**
The reporting feature so far gives the best overview for hours entered. Two things can quickly improve user experience
1) Being able to enter hours on click directly in the reporting view and/or allow to switch to weekly / monthly view in time sheet screen
![image](https://user-images.githubusercontent.com/55000172/99514001-8c8a5100-298b-11eb-8ffe-50f098416a28.png)

2) Allow to use this screen as initial view and / or add dashboard widget
![image](https://user-images.githubusercontent.com/55000172/99514175-bf344980-298b-11eb-80e5-23fe2190d11f.png)

**Comment by kevinpapst** [comment]
Thanks for your feedback!

There are actually already existing feature requests for such a kind of logging view.
But I'll keep it open, as your second request is new.

You want the (weekly) reporting view as option in that user-preference dialog, correct?

**Comment by stereo9** [comment]
Exactly, since it's probably the most important overview it makes sense to have that view upon login

**Comment by zeezhao** [comment]
Great idea!

**Comment by crm-developer** [comment]
I take

**Comment by zeezhao** [comment]
Hi - is the time entry aspect also covered  i.e. "Being able to enter hours on click directly in the reporting view and/or allow to switch to weekly / monthly view in time sheet screen" - see first image above. Thanks

**Comment by kevinpapst** [comment]
No: only the option to select the initial view.
The other one is a duplicate of an existing issue.
