### ISSUE TITLE
timesheet denying specific field from editing

### ISSUE THREAD

**Issue by szmeki** [kevinpapst/kimai2#2132]
Hi!

I am using tags on timesheets as an approve method by teamleaders. I hide the option to edit tags on a timesheet as a normal user. However it's only a frontend solution so it's a possible security issue.

_I would like deny the permission to editing tag field on a timesheet by ROLE_USER_. I've been studying the src library and symfony for days. I tried to deny access in the controllers (with denyAccessUnlessGratend() / isGranted() ) but I was only able to do it for the whole timesheet, which is already an existing permission.

_May i ask for your suggestion about where to make changes(or how) to make it possible?_

Thank you for your time!

Kimai version: 1.10.2

**Comment by kevinpapst** [comment]
You have to tell the form to hide it: 
https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L137

**Comment by szmeki** [comment]
Thank you! I was able to hide it in the form but only for all users. _How should i check the roles in the form?_ I'm not able to use the Security service there. Shouldn't have symfony inject it automatically because of autowire in the yaml file?

**Comment by kevinpapst** [comment]
You have to pass it from the controller via options like this:
https://github.com/kevinpapst/kimai2/blob/master/src/Form/TimesheetEditForm.php#L262

Don't get me wrong: 
If you have any Kimai specific question don't hesitate to ask, but I have very limited time and want to invest that into Kimai.
You are asking Symfony specific development questions which are not really related to Kimai => Stackoverflow is your friend.
