### ISSUE TITLE
Read only User

### ISSUE THREAD

**Issue by ctpntn** [kevinpapst/kimai2#2133]
Role that allows reading and reporting, but does not create records.
I have tried using roles page in order to create one role with these characteristics, but it seems impossible to disable the creation of records.

**Comment by kevinpapst** [comment]
if `create_own_timesheet` does not work for you, then please prepare the role setup in the demo and sent me a ping.

Afterwards I can have a look.

**Comment by ctpntn** [comment]
I created in the demo area the user ctpntn (qwerty123456) and the role ctpntn with 'no role'.
I'd expect he shouldn't be able to insert record, but he's able.

**Comment by kevinpapst** [comment]
Ok, I see your problem. It is documented here: https://www.kimai.org/documentation/users.html#roles
<img width="798" alt="Bildschirmfoto 2020-11-20 um 10 36 23" src="https://user-images.githubusercontent.com/533162/99784532-3e588780-2b1c-11eb-86af-c5da39c6966f.png">

Please retest now. I removed the `create_own_timesheet` permission from the "normal user" role.

**Comment by ctpntn** [comment]
I created a new user (ctpntn/qwerty123456) because the previous one has been removed.
Created new role ctpntn with 'no role'
Assigned this role to the user.
But nothing has changed.

**Comment by kevinpapst** [comment]
Demo was reinstalled in between...

You have to understand:
- every user is always member of the "User" role
- the "User" role has the permission `create_own_timesheet` by default
- you have to remove `create_own_timesheet` from the "User" role to achieve your goal

> Please retest now. I removed the `create_own_timesheet` permission from the "normal user" role.

I did it again. You can test again.

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by ctpntn** [comment]
I'm sorry but I didn't understand how to remove the `create_own_timesheet`
