### ISSUE TITLE
week start sunday brake timesheet calendar

### ISSUE THREAD

**Issue by jb10av** [kevinpapst/kimai2#2134]
**Describe the bug**
When an user select sunday for the first day of the week, than create or edit a timesheet the calendar show january 1920 and it's impossible to select a date.

**To Reproduce**
1. Go to user's preferences > select sunday for " First day of the week " entry
2. Go to my times > + ( create a new timesheet )
3. Click on "From" line to see the calendar

**Logfile**
No error in the log file

**Additional context**
 - Kimai version: 1.11.1 stable (Ayumi)
 - PHP version: 7.3.19-1~deb10u1
 - Device: Windows 10 and Debian 10
 - Browser firefox 78.3, chrome, Vivaldi 3.4

**Comment by kevinpapst** [comment]
Thanks for the report, problem is already fixed in master: https://github.com/kevinpapst/kimai2/pull/2084

**Comment by kevinpapst** [comment]
Previously reported here: https://github.com/kevinpapst/kimai2/issues/2078
