### ISSUE TITLE
Invoice Calculator

### ISSUE THREAD

**Issue by Gagasas** [kevinpapst/kimai2#2137]
**Description**
Is it possible to have a calculator that filters date and activity? I have more than one activity selected, and now I need the time and date for activity 1 and time and date for activity 2. It should be calculated like the DateInvoiceCalculator (that means one date for all records of activity 1) but also filter like the ActivityInvoiceCalculator (that means one date for activity 1 and one date for activity 2).
For better explanation following screenshots:

This is my first activity (named Testing Handout):
![Bildschirmfoto vom 2020-11-23 11-41-35](https://user-images.githubusercontent.com/73638118/99953229-49f8b800-2d81-11eb-92db-78d9ce26561a.png)

This is my second activtiy (named Anfahrt):
![Bildschirmfoto vom 2020-11-23 11-42-35](https://user-images.githubusercontent.com/73638118/99953387-790f2980-2d81-11eb-904f-f532141cedc7.png)

When I create the invoice with the DateInvoiceCalculator both activities are merged together (what i don't want):
![Bildschirmfoto vom 2020-11-23 11-43-03](https://user-images.githubusercontent.com/73638118/99953529-a6f46e00-2d81-11eb-9721-2119c3723a89.png)

I need it to be seperated like in the ActivityInvoiceCalculator:
![Bildschirmfoto vom 2020-11-23 11-43-51](https://user-images.githubusercontent.com/73638118/99953569-b96ea780-2d81-11eb-95cf-73a76f21a079.png)
But here is the problem that all records from one activity are merged together. It should be seperated like in the DateInvoiceCalculator.
I hope my problem was clear enough.

**Comment by kevinpapst** [comment]
Nope, it wasn't. What do you expect exactly?

**Comment by Gagasas** [comment]
So. I have two activities. One "Testing Handout" and one "Approach". If I want to create an invoice now, I want all recorded times to be displayed in one date (see DateInvoiceCalculator). However, the DateInvoiceCalculator includes all activities (see the third screenshot). I don't want that. I want each activity to be displayed separately (see last screenshot). Example: I worked several hours in one day. These are adopted in this way. However, before I started working, I had to drive to work. This is the second activity. Now the second activity, i. e. the route, wants to be displayed separately from the first activity. The ActivityInvoiceCalculator does exactly this, but everything from the first activity is summarized, including the date (see last screenshot). However, this is to be divided according to the respective date. So you have the first activity with date and time and the second activity with date and time.

**Comment by Gagasas** [comment]
Vielleicht ist es so einfacher. Jede Tätigkeit soll getrennt voneinander dargestellt werden. Hierbei sollen die Datums zusammengefasst werden. Also eine Kombination von dem DateInvoiceCalculator und dem ActivityInvoiceCalculator.

**Comment by kevinpapst** [comment]
Understood, you want a `DateActivityInvoiceCalculator`. Thanks for the explanation.

**Comment by Gagasas** [comment]
No problem, I'm glad that you understood what i meant!
Do you know if it's hard to implement and how long it would take?

**Comment by kevinpapst** [comment]
Simple, just create a new file and merge logic from 
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/DateInvoiceCalculator.php and https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/ActivityInvoiceCalculator.php

**Comment by Gagasas** [comment]
Awesome! So I wasn’t on the wrong track. I’m trying to rewrite the codes myself, but I’m desperate because I can’t find a solution. I’m looking forward to your solution. :)

**Comment by Gagasas** [comment]
Sorry to bother you again. But how long would it take you to implement the new calculator?

**Comment by kevinpapst** [comment]
2 hours - you can contact me at info@keleo.de if you want to hire me for this feature.
Otherwise this is a totally legit feature requests which stands in line with the other 200+.

**Comment by Gagasas** [comment]
I finally managed to write a calculator. Now I have another question. Is it possible to get the start and end time of different activities by selecting all activities? So start and end time of approach and start and end time of testing. For example: Activity 1: ${entry. begin_time.Approach} and activity 2: ${entry. begin_time.Testing}

**Comment by kevinpapst** [comment]
> I finally managed to write a calculator.

Great 👍 what about sharing it as PR?

I don't understand the other question. But you can extend the list of possible replacer values by adding a new implementation of a `InvoiceModelHydrator`, example see here: https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Hydrator/InvoiceModelActivityHydrator.php

Everything that is returned from the `hydrate` method will be available as `${variable}` in your invoice template.

**Comment by Gagasas** [comment]
Sure, i already made a PR! :+1:
