### ISSUE TITLE
Change area name

### ISSUE THREAD

**Issue by ctpntn** [kevinpapst/kimai2#2138]
Is there a way to change the words 'Customers' or 'Projects' with other words?

**Comment by buoncri** [comment]
For this i use a trick that is a new locale where i change every word in what i need.

**Comment by kevinpapst** [comment]
Thats an interesting solution @buoncri 
👍 for creativity 😁  

But I would prefer if everyone else uses the `Kimai default way`.
See https://www.kimai.org/documentation/branding.html at the bottom, headings `Translations`.

**Comment by buoncri** [comment]
@kevinpapst I was praticing translations ... so i made this  😁

**Comment by ctpntn** [comment]
Ok. I'm trying the `default way`.
I added the code 
```
kimai:
    theme:
        branding:
            translation: test
```
to `local.yaml`, created the file `test.en.xlf` and added this code:
```
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="en" target-language="en" datatype="plaintext" original="test.en.xlf">
        <body>
            <!--
              Global template keys
            -->
            <trans-unit id="stats.customerTotal">
                <source>stats.customerTotal</source>
                <target>CUSTOM TRANSLATION</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```
but nothing seems changed.
Where am I wrong?

Ps: I'm trying to change the word CUSTOMERS in the left menu.

**Comment by ctpntn** [comment]
Ok. It works! I had to flush cache.

**Comment by kevinpapst** [comment]
Closing then, as it works for you.

**Comment by BeckeBauer** [comment]
@ctpntn: Where did you put your translations? In the official documents, it is said _"in the translation directory of your company plugin at ``Resources/translations/``"_ but I could not find a directory resources in the first place...

**Comment by kevinpapst** [comment]
Quote from the docs:

>  in the translations/ directory

😁

**Comment by BeckeBauer** [comment]
Now, I'm completely confused. The docs state: "you create a file **either** in the ``translations/ directory`` (**should be avoided if possible**) **or** in the translation directory of your company plugin at ``Resources/translations/``."
I understood the docs as if there are two different locations whereas the location ``translations/ directory`` should be avoided. So, I was looking for the second location (maybe somewhere in the ``var`` directory so that updates will not conflict)?

**Comment by kevinpapst** [comment]
The * should be avoided if possible* part is there to warn you about possible update conflicts.
If you have a custom plugin, place the file it its translation directory. If you don't have a custom bundle, then you obviously need to use the first directory.

If you name the file *_my-awesome-acme-company* then it is 100% safe that there will never be a file in Kimai with that name.
But if you call the file *timetracking* then there is a chance that you run into update troubles in the future, if and only if Kimai will ever ship a file with the same name.

**Comment by BeckeBauer** [comment]
Understood, thanks for the explanations...
