### ISSUE TITLE
Project directory detected wrong. Symlinks

### ISSUE THREAD

**Issue by NikoGrano** [kevinpapst/kimai2#2145]
**Describe the bug**

**To Reproduce**
I am using currently following structure:
```
├── public_html [symlink to 734bf7e9 or xxxxxxxx]
├── releases
│   ├─    xxxxxxxx
│   └── 734bf7e9
│       ├── assets
│       ├── bin
│       ├── config
│       ├── public
│       ├── src
│       ├── templates 
│       ├── tests
│       ├── translations
│       ├── var
│       └── vendor
└── static
      └── .env
```

**Issue**
Site goes boom 500.

In Kernel, we are using default Symfony method `getProjectDir()`. 
With this setup default implementation of it will return something like: `string(00) "/path/to/kimai/ci/releases/734bf7e9/src"`.

Instead of this value we should get `string(47) "/path/to/kimai/ci/releases/734bf7e9"`.
I did not go deeply debugging whats wrong this the default implementation. However, my recommendation is to override this method. Example of this override could be following:

```diff
diff --git a/src/Kernel.php b/src/Kernel.php
index 8651b23e..5ac5455c 100644
--- a/src/Kernel.php
+++ b/src/Kernel.php
@@ -70,6 +70,11 @@ class Kernel extends BaseKernel
         return $this->getProjectDir() . '/var/log';
     }
 
+    public function getProjectDir()
+    {
+        return dirname(__DIR__);
+    }
+
     protected function build(ContainerBuilder $container)
     {
         $container->registerForAutoconfiguration(TimesheetCalculator::class)->addTag(self::TAG_TIMESHEET_CALCULATOR);
```

I am personally using custom Kernel as long this is fixed. My fix is above.

**Additional context**
 - Kimai version: 1.11.1 
 - PHP version: 7.4

**Comment by kevinpapst** [comment]
> Instead of this value we should get string(47) "/path/to/kimai/ci/releases/734bf7e9".

Is that what a blank Symfony app would return?

**Comment by kevinpapst** [comment]
Fo reference: https://symfony.com/doc/current/reference/configuration/kernel.html#project-directory

**Comment by kevinpapst** [comment]
I doubt that the problem is the symlink, as I use the deployment setup in many installations myself. Even thought public_html should point to `releases/734bf7e9/public/` and not `releases/734bf7e9/` but I guess its just a typo in your tree.

The default implementation checks for a composer.json. So my wild guess is: you delete the `composer.json` during deployment?

**Comment by NikoGrano** [comment]
> I doubt that the problem is the symlink, as I use the deployment setup in many installations myself. Even thought public_html should point to releases/734bf7e9/public/ and not releases/734bf7e9/ but I guess its just a typo in your tree.

Accually it isn't a typo. Web server is configured to use `public`. I was just lazy and didn't want fix all my totally-not copy-pasted scripts.

> The default implementation checks for a composer.json. So my wild guess is: you delete the composer.json during deployment?

Good point on that composer.json. Ill check that right after I've got some sleep.

**Comment by NikoGrano** [comment]
You were right about the `composer.json`. Some sneaky CI script cleans it up.
