### ISSUE TITLE
Lockdown Permissions

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#2147]
Hi,

version: 1.11.1 stable (Ayumi)

on the permissions config page - from user admin
the lockdown permission is not visible on the webpage

is there anything i can do regarding this?

thanks

**Comment by kevinpapst** [comment]
Show me a screenshot of this page => section "Timesheet"

**Comment by Jurgens92** [comment]
hi Kevin,

I got this sorted, i figured that i created a local.yaml file, with the v1.9 configuration
I deleted the local.yaml, and used the default kimai.yaml as config, 
and its sorted now

thank you
