### ISSUE TITLE
Error 500 on CentOS 8 after fresh install

### ISSUE THREAD

**Issue by carlosfc72** [kevinpapst/kimai2#2148]
**Description**
I have installed two times in different machines Kimai2 under CentOS 7 and 8 into VirtualBox Image and I always get the same error: "Error 500: page not found". If the "debug" option is activated, I see the redirection to /en/homepage that is not fount in this server.

I read all the post and fix issues like the permissions of "./var/" dir, vhost file is checked and  config files as indicated in the setup guide.

**Additional context**
 - Kimai version: latest release bu github
 - OS: CentOS release 8.2.2004
 - PHP version: 7.3.25 (all modules including intl installed)
  - Apache: 2.4.37

**Comment by kevinpapst** [comment]
You need to configure the virtual host in your webserver properly. Read https://www.kimai.org/documentation/webserver-configuration.html

**Comment by carlosfc72** [comment]
Thanks you Kevin, finally I solved the problem uncommenting the env lines in the VirtualHost conf. I don't know the reason but my web server didn't read them from the .env.
