### ISSUE TITLE
User Permission

### ISSUE THREAD

**Issue by Gagasas** [kevinpapst/kimai2#2152]
**Describe the bug**
When you want to give the Role User the permission to create_invoice and view_invoice, it is not taken over. All other permissions work. Trough the Dashboard it is possible, but not through the kimai.yaml.

**To Reproduce**
1. Edit `kimai.yaml`
2. Insert to the Role ROLE_USER following line: `ROLE_USER: ['@TIMESHEET','@PROFILE','@REPORTING','@SINGLE_USER','@INVOICE']`
3. Do a cache reload with `bin/console kimai:reload`
4. Sign in as Super Admin and go to users and permissions; you see Users cannot create or view invoices
5. Manually give permission works through Dashboard

**Logfile**

No log

**Additional context**
 - Kimai version: 1.11 stable
 - PHP version: 7.4.3

**Comment by kevinpapst** [comment]
Did you try with a fresh install?
If not, your database rules take precedence and overwrite the kimai.yaml.

**Comment by Gagasas** [comment]
Thanks! You were right. After a fresh install my permissions changed with the kimai.yaml file.
