### ISSUE TITLE
Error component Symfony and Twig

### ISSUE THREAD

**Issue by felixdice** [kevinpapst/kimai2#2153]
**Description**
I installed Kimai as per procedure (git, composer, MySQL, config php.ini see below details, config env file), but I'm having problems with the  Symfony and Twig libraries.

The first user registration and authentication is successful. after logging in to the application the "Something is wrong" error page is displayed.
For each test, I cleared the files in the browser cache and cache folder kimai.

I also tried running the commands:
- composer require twig / extensions --with-all-dependencies
- composer require symfony / intl --with-all-dependencies

I report CRITICAL errors from the log. Can you give me some directions? I need support. thanks @kevinpapst 

**request.CRITICAL:** Uncaught PHP Exception Symfony\Component\Intl\Exception\MethodNotImplementedException: "The Symfony\Component\Intl\Locale\Locale::setDefault() is not implemented. Please install the "intl" extension for full localization capabilities." at C:\MAMP\htdocs\kimai2\vendor\symfony\intl\Locale\Locale.php line 351 {"exception":"[object] (Symfony\\Component\\Intl\\Exception\\MethodNotImplementedException(code: 0): The Symfony\\Component\\Intl\\Locale\\Locale::setDefault() is not implemented. Please install the \"intl\" extension for full localization capabilities. at C:\\MAMP\\htdocs\\kimai2\\vendor\\symfony\\intl\\Locale\\Locale.php:351)"} []

**request.CRITICAL:** Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("PHP Fileinfo extension must be installed/enabled to use Intervention Image.")." at C:\MAMP\htdocs\kimai2\templates\base.html.twig line 149 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"PHP Fileinfo extension must be installed/enabled to use Intervention Image.\"). at C:\\MAMP\\htdocs\\kimai2\\templates\\base.html.twig:149, Intervention\\Image\\Exception\\MissingDependencyException(code: 0): PHP Fileinfo extension must be installed/enabled to use Intervention Image. at C:\\MAMP\\htdocs\\kimai2\\vendor\\intervention\\image\\src\\Intervention\\Image\\ImageManager.php:137)"} []

**Additional context**
 - Windows OS
- Apache 2
 - Kimai version: 1.11.1
 - PHP version:  7.3.7
- php Configure Command	cscript /nologo configure.js "--disable-all" "--enable-cli" "--enable-cgi" "--enable-apache2-2handler" "--enable-apache2-4handler" "--with-bz2=shared" "--enable-mbstring=shared" "--enable-exif=shared" "--enable-pdo=shared" "--with-pdo-sqlite=shared" "--with-sqlite3=shared" "--with-curl=shared" "--with-openssl=shared" "--with-gd=shared" "--enable-json=static" "--enable-session=shared" "--with-mysqli==mysqlnd,shared" "--with-mysqlnd" "--enable-opcache=shared" "--enable-apcu=shared" "--with-tidy=shared" "--enable-ftp=shared" "--with-gettext=shared" "--with-gmp=shared" "--with-imap=shared" "--enable-intl=shared" "--with-ldap=shared" "--with-pgsql=shared" "--with-pdo-firebird=shared" "--with-pdo-odbc=shared" "--with-pdo-pgsql=shared" "--enable-shmop=shared" "--enable-phar" "--enable-hash" "--with-simplexml" "--enable-soap" "--with-libxml" "--with-iconv" "--with-xml" "--enable-zlib" "--enable-zip" "--enable-ctype" "--enable-filter" "--enable-sockets" "--enable-calendar" "--enable-bcmath" "--enable-fileinfo" "--enable-xmlreader" "--enable-xmlwriter" "--with-dom" "--enable-tokenizer" "--enable-com-dotnet" "--enable-odbc" "--with-wddx" "--enable-mbregex" "--with-imagick=shared,C:\prog\ImageMagick-6.8.9;C:\prog\ImageMagick-6.8.9\VisualMagick\lib" "--with-xsl=shared" "--with-pdo-mysql=mysqlnd,shared" "--enable-memcache=shared" "--with-oauth=shared" "--with-xdebug=shared"

**Comment by kevinpapst** [comment]
Install php `intl` extension, eg. `apt-get install php-intl`

**Comment by felixdice** [comment]
Thanks for the prompt reply @kevinpapst , but it is already installed. I attach screen php.ini. Can you think of anything else?

![image](https://user-images.githubusercontent.com/75254974/100612839-e12ab600-3313-11eb-9a5e-78d35a206688.png)

**Comment by kevinpapst** [comment]
The error message is pretty clear. Intl is missing. Maybe your are editing the wrong php.ini (there are usually two of them: one for command line and one for fpm/apache)

**Comment by kevinpapst** [comment]
And I have never seen the message

> PHP Fileinfo extension must be installed/enabled to use Intervention Image

But sounds as something else is also missing.

**Comment by felixdice** [comment]
@kevinpapst Thanks I solved !!! You were right MAMP has two PHP.INI, one in the directory where PHP is installed and one in the config directory. In fact in the phpinfo page the php.ini points to C: \ MAMP \ conf \ php7.3.7 \ php.ini and not C: \ MAMP \ bin \ php \ php7.3.7 (where the changes have been made)
Thanks for the fast and timely support, I will contact you privately with some questions about the plugins I would like to purchase.
Fernando
