### ISSUE TITLE
reporting translation issue

### ISSUE THREAD

**Issue by jb10av** [kevinpapst/kimai2#2154]
**Describe the bug**
In French, the Calendar week number doesn't work as expected

in English : Calendar week 49
in French : Semaine civile %semaine%

**To Reproduce**
1. Go to user preference
2. Chose French in the Language drop down
3. Go to reporting
4. Chose Weekly view for one user
5. See the error

**Additional context**
 - Kimai version: 1.11.1 stable (Ayumi)
 - PHP version: 7.3
 - Device: all
 - Browser : all

**Comment by kevinpapst** [comment]
Thanks. I fixed it for the next version - you could too at http://hosted.weblate.org/languages/fr/kimai/
