### ISSUE TITLE
httpd crashed due a corrupt pid

### ISSUE THREAD

**Issue by nicoLedesma** [kevinpapst/kimai2#2156]
**Description**
I have executed:
docker run --restart unless-stopped -p 8025:8001 --name kimai2 kimai/kimai2:apache-debian-master-prod

After a reboot of my system, the container is always restarting. When I read the logs I get this:
>>Using non mysql DB
>>Kimai2 ready
>>(20014)Internal error (specific information not available): AH00058: Error retrieving pid file >>/var/run/apache2/apache2.pid
>>AH00059: Remove it before continuing if it is corrupted.
>>Action '-D FOREGROUND' failed.
>>The Apache error log may have more information.

My big problem is that I need the data from the database I was using. 
Since I can't access the container, I got the complete file system of the container but when I go to the folder:
```
/var/data
```
i don't have the sqlite database. 

I need to know very urgently how I can recover the data. 
Can you please help me?
Thank you very much.

**Additional context**
 - Kimai version: Kimai2
 - PHP version: 7.2.9 (according to the docker file)

**Comment by kevinpapst** [comment]
1. This is Kimai, not the docker repository.

> I need to know very urgently how I can recover the data.

2. Having a recovery plan is great to have upfront 😁 

3. SQLite is NOT meant/supported for production usage! This is clearly stated in the docs.

Please ask again in: https://github.com/tobybatch/kimai2
