### ISSUE TITLE
Issue on create time

### ISSUE THREAD

**Issue by ilicilho** [kevinpapst/kimai2#2157]
**Describe the bug**
My scenario:
NGINX TZ=America/Sao_Paulo
Linux TZ = America/Sao_Paulo
MySQL = System Time
Kimai = America/Sao_Paulo

**To Reproduce**
1. Go to 'My time and add new time, example: 02/12/2020 09:00 to 02/12/2020 13:00 and Save'
2. Go to Timesheets and the new entered time shows: 02/12/2020 08:00 to 02/12/2020 12:00'
3. This is the error

**Logfile**
```
no error in logs
```

**Additional context**
 - Kimai version: 1.10.2 
 - PHP version: 7.2.24
 - Device: [0ubuntu0.18.04.7]
 - Browser [whatever]

**Comment by kevinpapst** [comment]
This is a misconfiguration on your end.

What do you mean by `Kimai = America/Sao_Paulo`? There is no global Kimai timezone.

**Comment by ilicilho** [comment]
> This is a misconfiguration on your end.
> 
> What do you mean by `Kimai = America/Sao_Paulo`? There is no global Kimai timezone.

Hi Kevin
In Configuration > Create Customer  - Default Values> Timezone Is America/São_Paulo,

**Comment by kevinpapst** [comment]
And why do you think that `Create Customer - Default Values` relates to your timezone?

Set it in your user preferences: https://www.kimai.org/documentation/user-preferences.html#timezone

**Comment by ilicilho** [comment]
> And why do you think that `Create Customer - Default Values` relates to your timezone?
> 
> Set it in your user preferences: https://www.kimai.org/documentation/user-preferences.html#timezone

Thank Kevin.
I have one observation:
This "problem" started in Oct/19. In another years, in this date start Day Light Saving , TZ from BR is -2, but, in 2020, the Government cancel DLS. This can be a coincidence, but, ocours at the same time.

**Comment by kevinpapst** [comment]
Interesting. Then your default server timezone is used and the problem is not even related to Kimai / the user preference.

I assume that your `icu` library is outdated, which is used by the underlying frameworks (eg. to calculate the time offset).

If you manage your server yourself, check if you can get a new icu version (eg. apt-get upgrade).
If the server is managed, contact your hoster.

**Comment by ilicilho** [comment]
> Interesting. Then your default server timezone is used and the problem is not even related to Kimai / the user preference.
> 
> I assume that your `icu` library is outdated, which is used by the underlying frameworks (eg. to calculate the time offset).
> This library is the main storage for all these time & date related informations world wide.
> 
> If you manage your server yourself, check if you can get a new icu version (eg. apt-get upgrade).
> If the server is managed, contact your hoster.

Take a look this.

In SQL:
![image](https://user-images.githubusercontent.com/38463244/100994076-f92d5000-3534-11eb-982b-846d5127c31a.png)

In timesheet
![image](https://user-images.githubusercontent.com/38463244/100994164-12360100-3535-11eb-97ec-6e98a1adca37.png)

In form:
![image](https://user-images.githubusercontent.com/38463244/100994233-24b03a80-3535-11eb-8f48-73366ed41881.png)

**Comment by kevinpapst** [comment]
Did you set the correct timezone in your user preferences?
Does it match the timezone (that you did not show in the SQL output) of the entry?
If not that is completely fine. 
The form uses the timesheets timezone, while the listing uses your users timezone.
