### ISSUE TITLE
Add discount to invoices

### ISSUE THREAD

**Issue by swoop124** [kevinpapst/kimai2#2162]
In my invoices, i would like to add/grant discounts.

for example:
discount: 5%
discount: 15€
discount: 0,5 hours

It is now not possible to add a negative value into the cost fields. Or is there another way to realize this?

**Comment by kevinpapst** [comment]
For now, this is not possible

> Or is there another way to realize this?

You could probably write your own invoice templates or calculators for that.

**Comment by kevinpapst** [comment]
Adding negative costs is now possible using the Expenses plugin:
https://www.kimai.org/store/expenses-bundle.html
