### ISSUE TITLE
Extending Invoice Twigs

### ISSUE THREAD

**Issue by kulturbande** [kevinpapst/kimai2#2163]
**Description**
I have multiple invoice templates and a common calculation logic which is currently written in the templates itself (pretty ugly twig style). I would like to extend this. I guess I need to write a plugin for myself (or maybe more are interested). The only question is if the invoice model can be extended or some sort of service can be used to introduce an additional sum calculation model or if there is a way to extend the Twig handling (https://twig.symfony.com/doc/3.x/advanced.html).

**Screenshot**
<img width="436" alt="Bildschirmfoto 2020-12-06 um 13 14 22" src="https://user-images.githubusercontent.com/68833/101279801-ff396000-37c4-11eb-8fbb-fc131060447b.png">

**Additional context**
 - Kimai version: 1.11.1
 - PHP version: 7.4

**Comment by kevinpapst** [comment]
Yes, you should create an plugin / symfony bundle.
You can add any Twig extension (mainly filter and functions) from within the bundle.

You can add invoice calculator, see docs: https://www.kimai.org/documentation/developers.html#adding-invoice-calculator

**Comment by kulturbande** [comment]
Thx for your input. I will solve my current problem quick and dirty. I have same free time in the next days and take a look, how to solve these issue in a better way. Thx for your input! Kimai is great!
