### ISSUE TITLE
Documentation of available translations in twig templates

### ISSUE THREAD

**Issue by NKnuelle** [kevinpapst/kimai2#2164]
**Description**
I did not find any information about translations in the twig templates as found in the default templates (e.g. for invoices). All files in the /translations folder seem to be only for translation of the backend. 

**Problem**
Currently I am changing the default pdf template to add a project name and I am trying to use it like this:

```        
<strong>{{ 'project.name'|trans }}:</strong>
{{ model.query.project.name }}
<br>
```

The problem is, that `project.name` does not seem to be a valid input for the translation. Where are those translations stored or where are all possible variables mentioned?

**Additional context**
 - Kimai version: latest
 - PHP version: 7.4.x

**Comment by kevinpapst** [comment]
You can use any translation you want, either self provided ( eg. via bundle or custom translation file https://www.kimai.org/documentation/branding.html ) or from the existing ones.

You probably want to rely on the ones from `translations/messages.de.xlf`, eg `label.project`. Search from the translated string and then use the ID you found:
```
      <trans-unit id="label.project">
        <source>label.project</source>
        <target>Projekt</target>
      </trans-unit>
```
