### ISSUE TITLE
Question: Different VATs for activities

### ISSUE THREAD

**Issue by NKnuelle** [kevinpapst/kimai2#2165]
**Description**
I want to create an invoice and I need to specify different VAT values for different activities. For example:
Activity 1 is calculated with 16%  VAT
Activity 2 is calculated with 5% VAT

**Problem**
It seems that I can specify only one VAT value for my invoice. Is there a kind of workaround or some setting I can change to achieve my goal?

**Additional context**
 - Kimai version: 1.11.1
 - PHP version: 7.4.x

**Comment by kevinpapst** [comment]
Not possible by default.
Kimai is NOT a full-fledged invoicing solution but a time-tracker with basic invoice features.

Maybe you could achieve it with custom templates, customer-fields and your own calculator. But this is a big maybe...
If you have ideas on how to improve that in Kimai (code wise) please share your ideas!

**Comment by NKnuelle** [comment]
Hey there,
thank you for your quick response!
I fully understand that Kimai cannot be used for every use case. Anyway it is a very nice software and I like the design, too. But I think this is a kind of model design problem:
In my understanding the VAT should be linked to an activity/product - not the invoice itself. Normally, products/activities require a specific VAT so it would be an improvement to redesign this relationship. I know that this would need some major changes and I'm not sure if this change is even possible. But if you could give me some advice how to start I can try to create such a patch?

**Comment by kevinpapst** [comment]
> Normally, products/activities require a specific VAT so it would be an improvement to redesign this relationship.

I have a strong e-commerce background, so I understand where this is coming from.
But if you see it from a time-tracking perspective, where do you have different VATs for different activities? 

> I'm not sure if this change is even possible

I wouldn't go down this road. I heard the request for a second VAT setting for an invoice (which seems to be necessary in some countries) but I canÖt remember ever hearing a request like yours before. So I am pretty sure that almost all users who use the invoice system can live with the way it currently works. Which is definitely not the best solution for everyone - I get that - but it seems to be an acceptable compromise.

But still: you could write your own logic to achieve that. 
Extend activities with custom fields for the VAT rates and then build a custom template. You have to calculate the amounts yourself, which can be done with your own calculator: https://www.kimai.org/documentation/developers.html#invoices

**Comment by kevinpapst** [comment]
Or you use an invoicing software like Grandtotal. You could build another connector, if GT is not working for you:
https://www.kimai.org/store/grandtotal-plugin-for-kimai.html

In the end it doesn't have to be Kimai, if it doesn't fit your use case ...
