### ISSUE TITLE
Mobile App Not Working Android

### ISSUE THREAD

**Issue by senormedia** [kevinpapst/kimai2#2170]
Hello

bought the android app, its connecting to my server but it does not update it,

Also if i added a event listener that app will trigger it correct when it uploads it?

**Comment by kevinpapst** [comment]
> bought the android app, its connecting to my server but it does not update it,

Please contact the app developer, I am not connected with them. @hmr-it-jr 

> Also if I added a event listener that app will trigger it correct when it uploads it?

I don't know hat you mean.
