### ISSUE TITLE
API for statistics

### ISSUE THREAD

**Issue by ZeiP** [kevinpapst/kimai2#2176]
**Is your feature request related to a problem? Please describe.**
It'd be great to be able to access different statistics through the API to present them for example in a mobile client software. What I'm currently most interested in are user's (and total) hours this and last month and week and total billing this and last month and week, but obviously it'd be better configurable similarly to the widgets.

**Describe the solution you'd like**
Versatile API call(s) to fetch the needed statistics information by querying an endpoint with the relevant arguments.

**Comment by kevinpapst** [comment]
PRs welcome!

**Comment by kevinpapst** [comment]
Closing, see #2346 for more info
