### ISSUE TITLE
Redirect to http after login using https

### ISSUE THREAD

**Issue by leMaik** [kevinpapst/kimai2#2194]
**Describe the bug**
When logging in into Kimai the `/login_check` route redirects to `http://…/homepage` instead of keeping the https protocol. This leads to security warnings on recent Chrome versions.

**To Reproduce**
1. Go on a https Kimai instance, log out if you're logged in
1. Go to the login page
1. Log in with recent Chrome versions
1. See the warning (and note how the URL starts with http://)

If you don't get a warning, open the developer tools and switch to the network tab to observe the non-https redirect.

**Logfile**
```
localhost:8001 10.0.0.88 - - [15/Dec/2020:09:16:30 +0000] "POST /de/login_check HTTP/1.1" 302 1020 "https://kimai.mycompany.com/de/login" "Mozilla/5.0 (Linux; Android 10; ONEPLUS A6003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36"
```

**Additional context**
 - Kimai version: 1.9 and 1.12
 - PHP version: 7.4.12
 - Device: [Ubuntu Laptop 16 inch, Windows Desktop 27 inch, iPhone 6s]
 - Browser: Chromium 87 (insecure redirect, no warning), Chrome Android 87 (insecure redirect _and_ warning)

**Comment by kevinpapst** [comment]
Try the demo. Does it happen there as well?
100% sure this is a misconfiguration in your webserver/proxy.

**Comment by leMaik** [comment]
Thanks for the quick response. :raised_hands: It doesn't happen with the demo (should have checked that myself). So I guess I'm somehow not telling Kimai that it's behind a reverse proxy?

**Comment by kevinpapst** [comment]
> So I guess I'm somehow not telling Kimai that it's behind a reverse proxy?

How shall I know 😁 

Do you want me to google `kimai reverse proxy` for you or do you give it a try yourself?

**Comment by leMaik** [comment]
Yeah, I resolved it. :smile:

**Comment by kevinpapst** [comment]
👍 If just all support questions were so easy to solve 😄
