### ISSUE TITLE
Create time: Cannot TAB from hour to minute field

### ISSUE THREAD

**Issue by caugner** [kevinpapst/kimai2#2197]
**Describe the bug**
When I manually add a time, after selecting the hour, a <kbd>TAB</kbd> does not take me to the minute field.

**To Reproduce**
1. Go to 'My times'
2. Click on '+'
3. Click into 'From' field.
4. Click into minute select.
5. Choose minute via keyboard.
6. Press <kbd>TAB</kbd>

**Logfile**
(Irrelevant)

**Additional context**
 - Kimai version: 1.12
 - PHP version: 7.4.11
 - Device: Windows
 - Browser: Firefox Nightly 86.0a1 (2020-12-14)

**Comment by kevinpapst** [comment]
Does it work in https://www.daterangepicker.com ? If not, please open an issue in their issue tracker.

The time input will be changed in the future, but I am still not sure how. But this picker will be definitely replaced.

**Comment by caugner** [comment]
> Does it work in https://www.daterangepicker.com ?

Yes, same issue there, but I think I won't adopt Kimai in the end, because I find it too tedious for my use case (regular work time recording for a single customer/employer, independently of any project/activity; recording offline first, then adding all items for a day day in one go). But then again, I'm biased, because I used this UI before ([source](https://www.projektron.de/fileadmin/_processed_/6/9/csm_tagesbuchen_7e89d81cd7.png)):
![grafik](https://user-images.githubusercontent.com/495429/102239271-f9472b80-3ef6-11eb-83e6-46d80459d4b5.png)

**Comment by kevinpapst** [comment]
Fine for me!
