### ISSUE TITLE
Timesheet import: Add project/activity option to allow import of 3-column "Date,From,To" CSV file

### ISSUE THREAD

**Issue by caugner** [kevinpapst/kimai2#2198]
**Is your feature request related to a problem? Please describe.**
I only have one customer, project and activity, so my timesheet CSV file only has the three columns (date, from, to). However, in order to import I have to also provide the project and activity columns.

**Describe the solution you'd like**
Add project/activity options, similar to `--customer`.

**Describe alternatives you've considered**
An alternative would be to prompt for all required values that don't have a CSV column.

**Comment by kevinpapst** [comment]
Open the CSV, fill the columns with the required information, save and import.

I accept PRs for the feature if you want to give it a try!

But I don't see a reason to add such a feature, so I am closing.

**Comment by caugner** [comment]
> But I don't see a reason to add such a feature

Can you elaborate what the difference is to `--customer`? After all, you could open the CSV fill out the customer column likewise.

**Comment by kevinpapst** [comment]
I accept PRs for the feature if you want to give it a try!

But now, that I spent my rare time to open the discussion again... the difference is: I needed `--customer`.
