### ISSUE TITLE
Small color bug with projects

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2200]
You can assign a color to projects.
The following happens with the standard color gray:
Everything is ok in the display of all projects.
If you open a gray project, the color always changes to green.

**Comment by kevinpapst** [comment]
Screenshot please, I don't understand the problem and where exactly it happens / cannot verify it on the demo as well.

**Comment by HeinzWuert** [comment]
2 days ago sent desktop video of issue, personal mail

**Comment by kevinpapst** [comment]
Thats the problem with emails, they get lost. I can't remember how to reproduce it. Do you?

**Comment by HeinzWuert** [comment]
Only happens if:
1. the color of a project is grey
2. and the customer has another color, f.e. red

Open Projects, the  is default color of all projects in demo is grey
Open the project with red customer
the color of project öooses grey and takes the color of customer

By the way, there is another FR to change the choosebox for colors from 3xRGB and color palette to 16 or 32 standard colors.
If u want to have some identical colors u have to write down the RGB code, otherwise it becomes a rainbow.
