### ISSUE TITLE
No budget recalculation if the start / end date is changed

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2202]
**Describe the bug**
No budget recalculation if the start / end date is changed.

It also seems to be the case that there is also no recalculation if a user has booked hours on the wrong order and these have been rebooked (here by the administration). His working time remains in the time budget for the original project.

**To Reproduce**
In the project no start / end of the budget period set.
Inclusions from Jan-Mar
If I subsequently define the start and end period over a shorter period of Feb-Mar, the budget hours used remain on Jan-Mar. In such a case, there is no recalculation.

**Solution**
- If you define or change the start / end period, always recalculate the budget.
- If a change is made to the booked project by user or administration all hours must be postponed here.

**Comment by kevinpapst** [comment]
The budget is not tied to the projects start and end date in any way.
So you are right that nothing is recalculated.
Whatever is booked onto the project goes into the budget, no matter when it was booked.

Additionally: the budget is always calculated on the fly, so a record that is moved from `one` project to `another` should always be calculated in `another`.

**Comment by HeinzWuert** [comment]
so the recalculation seems to be more a FR than a bug ;-)

**Comment by HeinzWuert** [comment]
Please close this "bug". 
Changing the behavior may result in other problems when we tested this. 
If strictly working with start- and end times will there be no further issue.
