### ISSUE TITLE
Mini-Logo img tags

### ISSUE THREAD

**Issue by nh-matti** [kevinpapst/kimai2#2203]
At the Admin Settings for mini logo, write down the url isnt enough, i had to add the img tags like
`<img src="URL">`. Is this a feature or a bug?

**Comment by kevinpapst** [comment]
The "Mini Logo" should contain text, but the field allows to enter HTML tags as well (which wasn't intended, so it is a bug, but lets call it a feature).

See https://www.kimai.org/documentation/branding.html
