### ISSUE TITLE
Week 53 not showing

### ISSUE THREAD

**Issue by pascal541** [kevinpapst/kimai2#2204]
**Describe the bug**
Week 53 is not showing on the dashboard. After week 52 it is going directly to week 1 (skipping dates 28th December thru 4th Januari)

**To Reproduce**
1. Go to the dashboard
2. Click on the arrows on the top right
3. Skip to week 52 and go to the next week

**Additional context**
 - Kimai version: 1.12
 - PHP version: 7.4.13

**Comment by kevinpapst** [comment]
If you have a chance to test #2206, please let me know if that wrks for you

I tried 2018/2019/2020

**Comment by pascal541** [comment]
Tested for 2020. Works fine. Thank you!
