### ISSUE TITLE
Instant Time Record

### ISSUE THREAD

**Issue by nh-matti** [kevinpapst/kimai2#2215]
**Is your feature request related to a problem? Please describe.**
Starting a Time Record is very long when your in hurry, like receiving a phone call, you want to track

**Describe the solution you'd like**
Second Play Button for instant recording with prefilled project and Activity over api, like /api/timesheets/create

**Describe alternatives you've considered**
- Creating a shortcut like /timesheet/create?project=2&activity=2 -> open only modal, not a direct start
- use the api for restart /api/timesheets/95/restart -> requires already tracked time with existing id

**Screenshot**
![Screenshot 2020-12-21 120112](https://user-images.githubusercontent.com/75842166/102770342-46f2e680-4384-11eb-8ef9-4c603cef59d3.png)

**Comment by muety** [comment]
I'd like to see this feature as well. Also, it would be cool to be able to add new activities right way, instead of having to explicitly create them first inside the "Activities" page.

**Comment by nh-matti** [comment]
Can this feature be prioritized by payment? If this is an browser extensions or directly in the UI, that doesn't matter.

**Comment by kevinpapst** [comment]
Please send me an email to info@keleo.de

**Comment by hmr-it-jr** [comment]
The plugin is ready and can be purchased here: https://gum.co/ZsyGKF

There is no configuration necessary for this plugin. The plugin itself creates a placeholder customer, project and activity. Once you click the 
![menu](https://user-images.githubusercontent.com/36242595/124083760-8b0b2600-da4e-11eb-8984-13e8fbe8e3d9.png)

quick record button time tracking starts immediately 🚀

**Comment by nh-matti** [comment]
thank you for your quick developement
