### ISSUE TITLE
Offer Customer deletion via API

### ISSUE THREAD

**Issue by thomasDOTwtf** [kevinpapst/kimai2#2222]
**Is your feature request related to a problem? Please describe.**
The UI is currently offering the possibility to delete a customer.
This functionality was added with the request #68 
I'm using version 1.12 stable.

**Describe the solution you'd like**
Please add the DELETE verb to the /customers api route.

**Comment by kevinpapst** [comment]
Not sure if that is a good idea. Calling this method accidentally might trigger a cascade deletion of thousands of timesheets, projects, activities, invoices....

Share your use-case please.

**Comment by kevinpapst** [comment]
The demo bundle contains an example API method and I wrote a blog post how to do that on my personal site as well about that topic. If you need it, you have to create it yourself.

I will not an API for that, for the reason mention above.
