### ISSUE TITLE
Kimai2 installation on Plesk Obsidian 18.0.32

### ISSUE THREAD

**Issue by MikeSierraRO** [kevinpapst/kimai2#2227]
**Describe the bug**

Tried to install the Kimai2 on a Plesk dedicated server that is running Git and PHP Composer, I added the repo to the Git in Plesk, it automatically pulled the remote repository, branch and deployed to the subdomain. But I think I am missing something or the repository it's not compatible with Plesk auto Git install? I pointed the root of the subdomain directly to the /public folder, still the same.

Do I need to run any cmds on the ssh console? I tought that after Git pulls the repo data, it will auto-install it. 

Also, I updated all PHP Composer package dependencies, and I can see that I have the kevinpapst/adminlte-bundle version 3.2.4 and kimai/user-bundle.

**Logfile**
```
Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_configuration' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:91, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_configuration' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:86, Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.value AS value_3 FROM kimai2_configuration t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_configuration' doesn't exist\"). at /var/www/vhosts/XXX/kimai.XXX/templates/partials/logo_login.html.twig:1, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.value AS value_3 FROM kimai2_configuration t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_configuration' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:46, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_configuration' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:91, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_configuration' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:86, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_sessions' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:131, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_kimai.kimai2_sessions' doesn't exist at /var/www/vhosts/XXX/kimai.XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129)"} []
```

**Additional context**
 - Kimai version: 2 
 - PHP version: latest 7.4

**Comment by itrtimrear** [comment]
We are running Kimai 1.10 and 1.12 successfully on several plesk servers.

If you have installed from git within plesk, you need to run the following commands (take a look at installation guide) in an user (not Root / admin) ssh session:

- Optionally: Change SSH/PHP Version one time:
`export PATH=/opt/plesk/php/7.4/bin:$PATH;`

- Install dependencies:
`composer install --no-dev --optimize-autoloader`

- Change / deploy Database access
`nano .env`
-> `DATABASE_URL=mysql://user:password@127.0.0.1:3306/database`

- Install Kimai:
`bin/console kimai:install -n`

- Change access rights
```
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
chmod -R g+rw public/avatars/
```

- Create Admin:
`bin/console kimai:create-user USERNAME EMAIL@ADRE.SS ROLE_SUPER_ADMIN`

Dont forget to open url with public ending: https://yourkimai.url/public
**And secure the all files in root using .htaccess or something else so nobody can get your database credentials ;)**

Still Problems? Clear Cache:
`bin/console kimai:reload --env=prod`

Hope it is helpful for you...

**Comment by vic-t** [comment]
itrtimrear is right, Kimai2 works just fine on Plesk. 

I believe you can skip his first two steps, though. Configuring the PHP version can be done from the user interface of Plesk, the same goes for Composer. But you still need to create a database (Plesk helps you with that) and reference it in the .env file within the Kimai2 directory. Also, you can set the root of your subdomain to the public folder directly which is the preferred way IMO. 

I further recommend to run the bin/console commands as the web user, otherwise you may end up with permission issues.

**Comment by kevinpapst** [comment]
Just one comment regarding @itrtimrear explanation, which is very important!!!

Point your subdomain to public/ - it should in no circumstances appear in the URL afterwards.
If it does, please try if you can access the .en file via http://example.com/public/.env <= would be a huge security risk.

@MikeSierraRO I am closing here, as you don't respond, seems you solved it...
