### ISSUE TITLE
Term "Umsatzsteuer" change to "Mehrwertsteuer" for Swiss customers

### ISSUE THREAD

**Issue by muweb1** [kevinpapst/kimai2#2230]
I used kimai as a Swiss company. In Switzerland "sales tax" (Umsatzsteuer) is referred to as "Mehrwertsteuer" ("Mwst" for short).

Swiss customers do not understand the term "Umsatzsteuer"

Idea: Is it possible to change the name to "Mehrwertsteuer" on the invoice? This can possibly be made dependent on the selected language. If language = German (Switzerland), then name "Mehrwertsteuer".

![Umsatzsteuer](https://user-images.githubusercontent.com/76791832/103378483-bda98580-4ae2-11eb-8c11-b8ff5f3cea5f.jpg)

**Comment by kevinpapst** [comment]
Sure, you need to translate that string here: https://hosted.weblate.org/languages/de_CH/kimai/

I guess it is this line:
https://github.com/kevinpapst/kimai2/blob/master/templates/invoice/renderer/default.html.twig#L109
so the key `invoice.tax` needs to be adapted for `de_CH`

**Comment by kevinpapst** [comment]
Fixed with 
https://hosted.weblate.org/translate/kimai/-/de_CH/?offset=1&q=invoice.tax&sort_by=-priority%2Cposition&checksum=#translations
