### ISSUE TITLE
Blank page and no errors on clean installation

### ISSUE THREAD

**Issue by fyrfli** [kevinpapst/kimai2#2231]
**Describe the bug**
I've followed the installation instructions carefully (I even deleted the whole thing and re-did it to make sure) and all the steps seem to complete successfully. I've checked and re-checked pre-requisite php libraries and checked and re-checked error and access logs for the installation. I should also not that I am running the installation behind a proxy and I checked what those settings should be as well. All seems to be perfectly in order. Yet I get a blank screen when I go to the homepage.

**To Reproduce**
https://kimai.cejf.me

**Logfile**
There is nothing but .gitkeep in the kimai2/var/log directory. The nginx error log has nothing. The nginx access log contains these two lines only:

[30/Dec/2020:14:37:37 -0600] "GET / HTTP/1.0" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
[30/Dec/2020:14:37:37 -0600] "GET /favicon.ico HTTP/1.0" 200 1150 "https://kimai.cejf.me/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

**Additional context**
 - Kimai version: 1.12
 - PHP version: php7.4-fpm
 - Device: Debian 10.7 container on a Proxmox installation
 - Browser Chrome 87

**Comment by kevinpapst** [comment]
Check the file permissions and ownership recursively for the var/ directory.
Share your nginx conf...

**Comment by fyrfli** [comment]
Should have mentioned that I executed the permissions change commands too. No errors. (I installed under the www-data user anyhow, but I did the perms set just in case).

Nginx for the installation is:

```
server {
        listen 443;
        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
        server_name kimai.cejf.me;
        root /home/www/kimai2/public;
        index  index.php;
        access_log /var/log/nginx/kimai-access.log;
        error_log /var/log/nginx/kimai-error.log;
    location ~ /\.ht {
        deny all;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/..:/tmp/";
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
```

Proxy nginx is:

```
server {
        server_name kimai.cejf.me;
        access_log /var/log/nginx/kimai-access.log;
        error_log  /var/log/nginx/kimai-error.log;
        location / {
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "Upgrade";
               proxy_set_header Host $http_host;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
               proxy_set_header  X-Forwarded-Host $host:$server_port;
                proxy_set_header  X-Forwarded-Server $host;
               proxy_read_timeout 90;
               proxy_pass_header X-CSRFToken;
               proxy_pass $scheme://10.0.0.172;

        }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cejf.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cejf.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

**Comment by fyrfli** [comment]
FYI: this line broke the other sites I have so I commented it out:

```
fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/..:/tmp/";
```

Not sure if that makes a difference?

**Comment by kevinpapst** [comment]
Not required at all. It is just a security setting that is not necessary.
Please try it without proxy first, best is to use http. 
Hard to spot a problem if there are multiple layers involved, so eliminate as many possible failure points as possible.

**Comment by fyrfli** [comment]
It should be fine if I move the port from 80, yes? Otherwise I'd have to break everything that is behind the proxy while I do this test. I mean, if that's the only way, I can work around that but I'd prefer not to.

**Comment by kevinpapst** [comment]
Your setup should work, even though I have no chance to verify your proxy settings. 

If you want to find the point that breaks, then you need to debug your system somehow.
You can use curl from the proxy server as well if you feel better with that.

**Comment by fyrfli** [comment]
Ok. Give me few minutes to switch around configs and try this. I'll get back to you with some results momentarily.

Also, thank you so much for your time and patience.

**Comment by fyrfli** [comment]
Ok. 
http://kimai.cejf.me goes straight to that installation now. And I've removed all the other virtual servers from nginx. 

Same issue: a blank page.

Here is what the nginx config file looks like now:

```
server {
        #listen 443;
        #ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        #ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
        listen 80;
        server_name kimai.cejf.me;
        root /home/www/kimai2/public;
        index  index.php;
        access_log /var/log/nginx/kimai-access.log;
        error_log /var/log/nginx/kimai-error.log;

        location ~ /\.ht {
                deny all;
        }

        location / {
                try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                #fastcgi_param PHP_ADMIN_VALUE "open_basedir=$document_root/..:/tmp/";
                #internal;
        }

        location ~ \.php$ {
                return 404;
        }

}
```

**Comment by kevinpapst** [comment]
```
cd /home/www/kimai2/public
cp index.php index.php_old
echo "Hello World" > index.php
```

**Comment by fyrfli** [comment]
Done.

And interestingly, nothing is showing up. Scouring log files and permissions, etc.

**Comment by fyrfli** [comment]
Something clearly got missed upon installation because there doesn't seem to be anything wrong at all considering there are no messages in any log files anywhere. 

I am going to try installing it in it's own virutal machine. If I have the same issue I can probably re-open this or open a new issue.

Thanks for the help.

**Comment by kevinpapst** [comment]
😞  

Are you running other PHP projects on that machine?
This works http://kimai.cejf.me/apple-touch-icon.png so your nginx setup in general is okay

**Comment by fyrfli** [comment]
At the moment, nothing else is configured in the nginx config file. So even though there are other projects there, they aren't currently accessible.

**Comment by fyrfli** [comment]
They worked fine before so I am thinking that either something in the existing environment is in conflict or something went wrong in the installation. I am going to try a totally clean install with just Kimai alone and see how that works.

**Comment by kevinpapst** [comment]
Have you checked the php/fpm log as well? Some errors don't bubble up

**Comment by fyrfli** [comment]
I list the /var/log directory based on date so I see which log files get written last (ls -lAtr) and didn't notice that the fpm log had been written to. Let me look....

Nope... nothing since I last restarted the daemon:
```
[30-Dec-2020 14:01:53] NOTICE: systemd monitor interval set to 10000ms
[30-Dec-2020 15:08:57] NOTICE: Terminating ...
[30-Dec-2020 15:08:57] NOTICE: exiting, bye-bye!
[30-Dec-2020 15:08:57] NOTICE: fpm is running, pid 10895
[30-Dec-2020 15:08:57] NOTICE: ready to handle connections
[30-Dec-2020 15:08:57] NOTICE: systemd monitor interval set to 10000ms
```

**Comment by fyrfli** [comment]
Hang on a tic; let me check php error log level...

Nope; php would tell me if something was wrong (from php.ini):
```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

**Comment by kevinpapst** [comment]
maybe: try to turn show_errors on?

**Comment by fyrfli** [comment]
Done. Also changed error_reporting to be E_ALL and tried again. Still nothing.

This is so frustrating.

**Comment by kevinpapst** [comment]
On the other hand, if not even the hello world is shown... then there is something else going on with your fpm. 
Did you try to restart the service? Sounds lame, but sometimes the simple solutions are the best^^

**Comment by fyrfli** [comment]
Does not sound lame at all - Occam's Razor and all that. I did that myself. Been wracking my brain about what in the config could be doing this... which is why I want to try a fresh install on a clean Debian VM. That way (a) I don't continue to eff with my current projects and (b) we have a clean slate to troubleshoot on.

**Comment by kevinpapst** [comment]
👍 let me know how it goes! and bring your other projects back online :D

**Comment by fyrfli** [comment]
Will do. And thanks again.

**Comment by fyrfli** [comment]
Well ... the clean install helped the troubleshooting.

After a lot of digging and tweaking, this line is what got the php files to execute instead of look blankly at me or download:

```
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
```

That gave me a 500 error and something told me to switch from php7.3 to php7.4 (I had downgraded as part of the troubleshooting process) and voilà.

![image](https://user-images.githubusercontent.com/5287261/103398723-8bf4e680-4b03-11eb-96e5-75fc83958345.png)

Again, thank you SO much for all the help - you helped guide me in my digging and I so appreciate it.

**Comment by kevinpapst** [comment]
Oh shit, that was a known bug in the fasgi.params file of nginx. At least I thought that this is part of the past and does not exist any longer.
Glad you could fix it!
