### ISSUE TITLE
Dashboard My working hours chart shows incorrect date on 01/01/2021

### ISSUE THREAD

**Issue by theapu** [kevinpapst/kimai2#2232]
**Describe the bug**
On 01/01/2021 My working hours chart in Dashboard page starts with date Jan 3, 2022 and ends with Jan9, 2022  instead of Dec 28, 2020 to Jan 03, 2021

This problem occurs on the Kimai demo sites (Stable and Development) as well.

**To Reproduce**
1. Go to Dashboard page on Kimai
3. Check the My working hours chart.

**Additional context**
 - Kimai version: 1.12 stable 
 - PHP version: 7.2.24

**Comment by kevinpapst** [comment]
Fixed in https://github.com/kevinpapst/kimai2/pull/2206 - unfortunately a bit too late for most users, as it is not released yet. 
But you could upgrade to master?!

**Comment by pascal541** [comment]
With master, if you go to the dashboard, the timechart starts at 2022 (January).

**Comment by kevinpapst** [comment]
Damned. New bug introduced. Please follow #2235
