### ISSUE TITLE
Update from earlier version not quite complete/correct.

### ISSUE THREAD

**Issue by magicmicros** [kevinpapst/kimai2#2233]
I just updated to 1.12 from a 1.8 installation.

Everything seemed to work fine, until I clicked the "Customers" in Dashboard and I got a 500 error.

Looking at the log, I saw the following messages:

[2021-01-01 17:41:49] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to App\Utils\LocaleHelper::country() must be of the type string, null given, called in /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleFormatter.php on line 167" at /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleHelper.php line 93 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Utils\\LocaleHelper::country() must be of the type string, null given, called in /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleFormatter.php on line 167 at /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleHelper.php:93)"} []
[2021-01-01 17:41:49] php.CRITICAL: Uncaught Error: Argument 1 passed to App\Utils\LocaleHelper::country() must be of the type string, null given, called in /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleFormatter.php on line 167 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Utils\\LocaleHelper::country() must be of the type string, null given, called in /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleFormatter.php on line 167 at /var/www_vhosts/redegg.net/htdocs/kimai2/src/Utils/LocaleHelper.php:93)"} []

Apparently, it didn't like my customers that had not been assigned a country code.
But, the MySQL field "country" is set as varchar[2], nullable.

I ran some SQL to set all to "US", and the problem was solved.

So, while that was an easy fix, it took hours to find the issue (I didn't know about the log ;))
But, it makes me wonder what other issues there may be, and what fields that suddenly may not be of the right type.
I would have expected update scripts to have caught this and adjusted accordingly. 

Interestingly enough, everything else seemed to work fine, I could make invoices, look at the timesheets e.t.c.
The problem only occurred when accessing the "Customers" page.

 - Kimai version: 1.12
 - PHP version: 7.4.10
 - Device: Mac, Catalina
 - Browser Chrome 87

**Comment by kevinpapst** [comment]
Can you prove that Kimai created the field nullable?
The code indicates otherwise and out of the hundreds of installations I manage, none ever had that problem.

Here are the relevant scripts:
https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20180701120000.php#L41 (install script)
https://github.com/kevinpapst/kimai2/blob/master/src/Entity/Customer.php#L153 (entity definition)

**Comment by magicmicros** [comment]
I certainly didn't do the database fields manually  ;)

There are lots of other fields that are nullable. Which is okay, until a code change suddenly expexts otherwise.

This was working fine with version 1.8, but not in 1.12.

<img width="951" alt="Screen Shot 2021-01-01 at 18 31 27" src="https://user-images.githubusercontent.com/35914281/103437916-a9d75e00-4c5f-11eb-893a-12aec4853c62.png">

**Comment by magicmicros** [comment]
Are there some relatively easy way I can make sure my database is "up-to-date" and have the right structure?

**Comment by kevinpapst** [comment]
`bin/console doctrine:migrations:diff` and then check the new file.
This tool is not perfect and results may vary between database versions.
Before posting here and trying to discuss every single field with me, please compare the results with the entity files (I linked the customer definition above). My time is limited and NO ONE posted that problem before. So this is not a general issue you are seeing and my time is limited.

**Comment by magicmicros** [comment]
I'm not sure what that tool should show me.
I've been running Kimai since 2015 and doesn't do all updates.
Not sure when I changed up to Kimai2, but at least I can see I installed (or updated) to 1.8 in March 2020.
I think I had one of the 0.xx versions initially.

Maybe the issue is because of a large version jump. You mention you haven't seen this before, with the installations you manage. I'm sure they're all updated as soon as there is a new version.

Anyway, current problem is solved and I'll see if I can do a complete re-install instead and re-import my DB to make sure everything is up to date.

Thank you for your quick response, it is much appreciated.

**Comment by kevinpapst** [comment]
The tool creates a new file (in src/Migrations/) with a bunch of SQL commands, all which the tool think are necessary to get the database in sync with the definition.

Doing a full reinstall with a database import might be a good idea. But if everything works now ... probably its best to wait for the next. update/problem ;-)
