### ISSUE TITLE
Cache reload leaves some directories unwritable

### ISSUE THREAD

**Issue by magicmicros** [kevinpapst/kimai2#2234]
Running the cache reload command/script changes var/cache/prod to be owned by root, and therefore not writable from kimai.

1. Run cache reload command:    bin/console kimai:reload --env=prod
2. ls -l  var/cache gives:
    drwxr-xr-x 2 root root 4096 Jan  1 18:12 pro_
    drwxr-xr-x 7 root root 4096 Jan  1 18:12 prod
3. Trying to open ANY Kimai web-page result in a 500 error.

From the log:
Failed to create "path_to_kimai2/var/cache/prod/translations": mkdir(): Permission denied at path_to_kimai2/vendor/symfony/filesystem/Filesystem.php:105

Running the update scripts to fix file permissions solve this issue :
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
chmod -R g+rw public/avatars/

Actually, it's the third of those that makes sure var is writable again.

This is no big deal, but it's annoying, as I have to run all of this repeatedly, while trying to make a new invoice template.
Every time I have made a change to the template, I have to clear the cache, then band-aid the missing write permissions.

- Kimai version: 1.12
- PHP version: 7.4.10
- Device: Mac, Catalina
- Browser Chrome 87

**Comment by kevinpapst** [comment]
RTM: https://www.kimai.org/documentation/cache.html (scroll down to the bottom and copy&paste the script)

If you have an idea how that could be automated, please send a PR.

**Comment by magicmicros** [comment]
While it IS described on that page, in detail, I was reading on the Invoice documentation page, which describes how to reload the cache, but not the potential issues.
Perhaps instead of describing how to do it on the Invoices page, a link to the cache page would be better?

**Comment by kevinpapst** [comment]
👍 But having good ideas is just half or the work.

Here is the file, please sent a PR: https://github.com/kimai/www.kimai.org/blob/master/_documentation/invoices.md

**Comment by magicmicros** [comment]
;)
No problem, happy to help. I just have to figure out how to do that the right way.
