### ISSUE TITLE
Reporting does not work

### ISSUE THREAD

**Issue by sgsgmbh** [kevinpapst/kimai2#2242]
Hi,

Kimai ist a wonderful software. 

But i have a problem with the reporting. This don't work here.
If i select a user, then the page reload and show the first user on the list and show no entries.

See video on youtube: https://www.youtube.com/watch?v=MuDwz5SCRPQ for better understanding.

No Errors in Logs

Can you help me?

Thanks.

Hier nochmal auf Deutsch, da mein Englisch nicht so gut ist:

Wenn man auf Reporting klickt und einen User auswählt, dann lädt die Seite sich neu und der erste User in der Liste wird wieder angezeigt und nicht der ausgewählte User. Auch die Wochen kann man nicht vor oder zurück Blättern. In den Logs sind keine Fehlermeldungen zu sehen und auch in der Webconsole (F12) gibt es keine Fehler.
Oben habe ich ein Youtube Video verlinkt, wo ich das zur besseren Verdeutlichung einmal aufgezeichnet habe.

Vielen Dank und viele Grüße

Daniel

**Comment by kevinpapst** [comment]
Try the demo and let me know if it works for your there.
There was a bug with first ISO week of the year and there is a PR waiting that fixes reports: https://github.com/kevinpapst/kimai2/pull/2239
I guess you are seeing that bug.

**Comment by sgsgmbh** [comment]
I don't think this bug has anything to do with it. This error occurred since the beginning of the installation (in the middle of last year).

The demo works, but I checked that too last year.

**Comment by kevinpapst** [comment]
How do the link targets look like and what is in your javascript console and in the browser url after clicking?

**Comment by sgsgmbh** [comment]
The JavaScript console is empty.

And the browser url are https://example.com/en/reporting/week_by_user?user=3&date=2021-01-04 after clicking.

Should I create a test account for you. Would that help?

**Comment by sgsgmbh** [comment]
I found another problem. Apparently the search filters don't work for us.

What could be the reason?

**Comment by kevinpapst** [comment]
Something is wrong with your webserver setup. Seems GET parameter are not working

**Comment by sgsgmbh** [comment]
Ok, thats is. A wrong nginx configuration. Thanks!

**Comment by kevinpapst** [comment]
So everything works now?

**Comment by sgsgmbh** [comment]
Yes :-)
