### ISSUE TITLE
symfony cache:clear throws AutowirePass exception

### ISSUE THREAD

**Issue by JEDIBC** [kevinpapst/kimai2#2245]
**Describe the bug**
Hi,

There's an exception thrown on `bin/console cache:clear`

If I upgrade the vendors with `composer upgrade` the problem disapear but I obviously don't want to do that :-)

**To Reproduce**
1. `git clone` the repository (master branch)
2. `composer install`
3. See error

**Logfile**

[console.log](https://github.com/kevinpapst/kimai2/files/5777309/console.log)

**Additional context**
 - Kimai version: master
 - PHP version: 7.3
 - Device: Ubuntu 18.04

**Comment by kevinpapst** [comment]
Each commit is run through a CI with different PHP 7 versions, so this is likely an environment problem => if you have the chance: please debug to find out what is causing that issue.

**Comment by JEDIBC** [comment]
Well following https://stackoverflow.com/a/65104323 I uninstalled xdebug and now it works like a charm. Sorry for the inconvenience :wink:

**Comment by kevinpapst** [comment]
Thanks for sharing your result!
