### ISSUE TITLE
My Times, download symbol > PRINT

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2247]
Please add in the print page costs and in the buttom line according to working time the sum.
This is helpful for a quick overwiew, because costs are not displayed in the reporting modul.

Maybe an idea to add a switch in the reporting modul for cost or working hours.

**Comment by kevinpapst** [comment]
> Maybe an idea to add a switch in the reporting modul for cost or working hours

Which was added in the last release. Solved?

**Comment by kevinpapst** [comment]
Solved 😁
