### ISSUE TITLE
Calendar: add day-total per day on the calendar-view 

### ISSUE THREAD

**Issue by petervanhee** [kevinpapst/kimai2#2252]
**Is your feature request related to a problem? Please describe.**
The calendar is very usefull for adding time entries but we lack the day-total per day. To verify that a day is complete (we have a standard workday of 8 hours/day), we have to switch to the personal timesheet where we have the day-total.

**Describe the solution you'd like**
Additional user-preference that activates the day-total in the Calendar-view

**Describe alternatives you've considered**
The alternative now is to use the Timesheet-view but this demands for an extra action for the user.

**Comment by kevinpapst** [comment]
See https://github.com/kevinpapst/kimai2/pull/2519
