### ISSUE TITLE
Error in Controlling plugin when end time is null

### ISSUE THREAD

**Issue by darioseidl** [kevinpapst/kimai2#2299]
We installed the [Controlling plugin](https://www.kimai.org/store/hmr-it-controlling-bundle.html) and found a bug in it. I don't know if this is the right place to report it, I could also send an email to the authors of the plugin.

When opening the plugin "Check" page, there is an error in `var/plugins/ControllingBundle/Repository/OverlappingRepository.php`, apparently when a time entry isn't finished yet (end time null):

> [2021-01-26 23:05:06] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to KimaiPlugin\ControllingBundle\Controller\UtilController::convertTimeZone() must be of the type string, null given, called in /var/www/kimai2/var/plugins/ControllingBundle/Repository/OverlappingRepository.php on line 88" at /var/www/kimai2/var/plugins/ControllingBundle/Controller/UtilController.php line 276 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to KimaiPlugin\\ControllingBundle\\Controller\\UtilController::convertTimeZone() must be of the type string, null given, called in /var/www/kimai2/var/plugins/ControllingBundle/Repository/OverlappingRepository.php on line 88 at /var/www/kimai2/var/plugins/ControllingBundle/Controller/UtilController.php:276)"}

Line 88 is this line

    $entries[$key]['end_time'] = $utilController->convertTimeZone($entries[$key]['end_time'], $entries[$key]['timezone']);

When we add a not-null check ` $entries[$key]['end_time'] != null` to the surrounding if, it works again:

    if ($diff <= -60 && $entries[$key]['end_time'] != null) {

        $entries[$key]['start_time'] = $utilController->convertTimeZone($entries[$key]['start_time'], $entries[$key]['timezone']);
        $entries[$key]['end_time'] = $utilController->convertTimeZone($entries[$key]['end_time'], $entries[$key]['timezone']);

        $entries[$key - 1]['start_time'] = $utilController->convertTimeZone($entries[$key - 1]['start_time'], $entries[$key - 1]['timezone']);
        $entries[$key - 1]['end_time'] = $utilController->convertTimeZone($entries[$key - 1]['end_time'], $entries[$key - 1]['timezone']);

        array_push($return, [
            '0' => $entries[$key],
            '1' => $entries[$key - 1]
        ]);
    }

**Comment by kevinpapst** [comment]
@hmr-it-jr ping - your bundle. Closing here for obvious reasons: please contact the author via email.

**Comment by hmr-it-jr** [comment]
@darioseidl I've moved the issue: https://gitlab.com/hmr-it/kimai2plugins/ControllingBundle/-/issues/5

Please have a look at it.
