### ISSUE TITLE
reporting feature - allow current view to be exported to excel

### ISSUE THREAD

**Issue by alqu** [kevinpapst/kimai2#2306]
**Is your feature request related to a problem? Please describe.**
Currently, there is a nice overview that displays the times for some/all users in a month (or other period).
How do I get these numbers into an excel sheet?

**Describe the solution you'd like**
It would be VERY convenient if there would be a "Download as Excel" button, which renders the data into an excel sheet. Basically exactly the same structure as in the current reporting view.

**Describe alternatives you've considered**
The "Export" Feature could by augmented by a "report type" select box, which then allows to choose between list, aggregated by month, etc.

**Comment by kevinpapst** [comment]
I agree, but have you tried copy & paste?

**Comment by alqu** [comment]
Of course. You can copy the whole page and paste it into Excel. Result: you get all fields in separate cells. Fine. But then it is pretty awkward to work with that data since the duration is interpreted as a naked string, e.g. "08:30 h". And I am too dumb to convert it in a clever way to get it understood by Excel.

**Comment by HeinzWuert** [comment]
![image](https://user-images.githubusercontent.com/45666972/106785090-55077880-664d-11eb-8808-19b4336f1020.png)

**Comment by alqu** [comment]
Yes, works, but I think the users are not clever enough to perform this over all cells. What they want is a formatted Excel Cell with the format `[h]:mm" h";@`.

**Comment by HeinzWuert** [comment]
a simple macro converts all data

**Comment by kevinpapst** [comment]
In the last release you can export the user-list reports.
Not the single user export though.
