### ISSUE TITLE
using the same tag multiple times  in csv not resolved

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2318]
**Describe the bug**
* imported a csv ( see the bug in this project from few minutes ago)
* used the same tags (that did not exist in system) multiple times

**To Reproduce**
* try to import csv with the famous : `bin/console kimai:import:timesheet --timezone=CEST --delimiter="," /tmp/reimport.csv`
* see  
   ```
  [ERROR] Failed importing timesheet row 2 with: An exception occurred while executing 'INSERT INTO kimai2_tags
  (name, color) VALUES (?, ?)' with  params ["xyzlalala", null]:
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyzlalala' for key 'UNIQ_27CAF54C5E237E06'
  ```

Kimai 1.9, PHP7.4

**Comment by bash-stack** [comment]
seems like it works on existing tags, so maybe the resolve process (" is it there, if not ,create") and the associated "find all categories" in csv could either happen before import or in each row

**Comment by kevinpapst** [comment]
Yes, I can see that from the code. New tags should be cached internally. See https://github.com/kevinpapst/kimai2/blob/master/src/Command/ImportTimesheetCommand.php#L368

**Comment by crm-developer** [comment]
> Yes, I can see that from the code. Should be true at least for the batch inserts.
> 
> **TODO**
> 
> * New tags [must be cached internally](https://github.com/kevinpapst/kimai2/blob/master/src/Command/ImportTimesheetCommand.php#L368)
> * Re-use cached instances instead of creating new objects

I will take it
