### ISSUE TITLE
logs not rotated (maybe switch to mononolog→rotated)

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2319]
**Describe the bug**
6 months old logs in entry

## suggestion: 
* → easy fix without extra logrotate/cron hussle ( think about microservices):
 [Symfony](https://symfony.com/doc/current/logging.html#how-to-rotate-your-log-files)
 [Laravel ( has some good advice on monolog](https://laravel.com/docs/8.x/logging)

**To Reproduce**
1.  install & use
2. in console/filemanager , check `var/log/prod.log`
3. see ancient entries

**Additional context**
 - Kimai version:  1.9
 - PHP version:  7.4

**Comment by kevinpapst** [comment]
I agree, that it can should be documented (a different log directory or even the monolog rotator can be configured by adapting local.yaml). 
But I disagree that the application needs to take care of log rotation. Nevertheless: great input, thanks!

Changing the config would likely be a BC break for all the container users and other environments where a cleanup script is running, so I will change this issue from bug to documentation (works as expected for me).

**Comment by bash-stack** [comment]
could not find it here:  https://www.kimai.org/documentation/configurations.html#localyaml

**Comment by kevinpapst** [comment]
Thats why it's good that you opened the issue, so it can be documented in the future!

BTW: if you want, you can [add documentation as well](https://github.com/kimai/www.kimai.org/tree/master/_documentation) if you feel motivated.

**Comment by bash-stack** [comment]
( okay , but i need a hint on that , ldap is already enabled , so the basic key structure is there )

**Comment by kevinpapst** [comment]
Try posting this to your local.yaml right at the beginning before anything else:

```yaml
monolog:
    handlers:
        nested:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.foooooo.log'
            max_files: 10
```

**Comment by kevinpapst** [comment]
Btw: please read this. Might be better for docker users: 
https://symfony.com/blog/logging-in-symfony-and-the-cloud

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/logging.html

**Comment by kevinpapst** [comment]
thanks for the feedback btw 👿
