### ISSUE TITLE
New permission to disable Multi-Delete

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2320]
**Is your feature request related to a problem? Please describe.**

Users tend do "`multi-delete`" stuff accidentaly, epic battles with re-importing `xslx`→`csv`→`importer` steal the time you wanted to track, also time is wasted on researching the incident ( who called what when )

It would be cool to have this either featured with one more permission  ( easy to implement ), 
or a generously "`lock this danger router`" feature in Backend

## Quick fix: 

modify `.htaccess`

```
# use the classic teapot as there is no bialetti available
#ErrorDocument 418 "<html> <h1> Bro:dont <br> Sis: not like this<br></html>"

##^ fails on apache
# 
ErrorDocument 451 '<html><head><meta http-equiv="refresh" content="7; url=/" /></head> <body><center><h1>NOT SORRY:<br>NO MASS DELEtiON AT THIS POINT - USE API OR  CONTACT HELPDESK</h1><br><img src=/apple-touch-icon.png ></body></html>'

RedirectMatch 451 ^/de/team/timesheet/multi-delete$
RedirectMatch 451 ^/en/team/timesheet/multi-delete$
```

**Describe the solution you'd like**
have a button in backend "NO"

**Describe alternatives you've considered**
`.htaccess` as above

**Screenshot**
Add a mockup / screenshot of your idea here.
![example lock](https://user-images.githubusercontent.com/62184749/107121328-19112500-6892-11eb-8833-12bc86e93e49.png)

**Comment by kevinpapst** [comment]
For now: remove `delete_own_timesheet` from `ROLE_USER`

**Comment by kevinpapst** [comment]
> Also it is a legal issue that ( like with POS and other money related systems ) , SUCH REQUESTS SHALL BE LOGGED GENEROUSLY

Ever user, especially companies that use a free software, are welcome to sponsor features! Thats how OSS business works...

**Comment by kevinpapst** [comment]
Solution should be to add new `delete_multiple_own_timesheet` and `delete_multiple_other_timesheet` permissions

**Comment by bash-stack** [comment]
( happened on an adminitrastive user that deleted "foreign" times after export )

**Comment by kevinpapst** [comment]
Well, honestly: then this user shouldn't be an admin 👿 ... timesheet records shouldn't ever be deleted, unless they are wrong.

**Comment by HeinzWuert** [comment]
LOL, send such as FR to microsoft to prevent mass deletions in windows explorer....
For me this is an IO problem and can never be solved!  ( IO = idiot operator )
Sorry, not my FR but funny.

**Comment by bash-stack** [comment]
Okayokay guys ,

despite jokes about people you don't know (  für die Kartoffeln hier :  Witze auf kosten anderer Leute..)

the button only apears after selection and still we have no clue if the pop-up "do you really wanna?" did pop-up ( cannot test on users machine currently )

**Comment by kevinpapst** [comment]
@bash-stack you can sponsor the feature. meanwhile I close it, because I strongly disagree that this needs or even can be be solved with further permissions.
