### ISSUE TITLE
create/edit form disappears on clicking somewhere else

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2322]
**Describe the bug**
(many times) when creating a  new time , the form closes on every action ( clicking) somewhere else in the page

** Countermeasures**
- either `cache` the last entered values in localstorage until submit happens
- or lock the form in javascript/html to not close unless the buttons or ESC key is pressed

**Comment by kevinpapst** [comment]
Please check the demo before opening issues.
If it doesn't happen there, then your software might be outdated 😁 

This feature was added recently, I appreciate feedback on it!

**Comment by bash-stack** [comment]
oh sry..

**Comment by bash-stack** [comment]
> Please check the demo before opening issues.
> If it doesn't happen there, then your software might be outdated grin
> 
> This feature was added recently, I appreciate feedback on it!

is it safe to jump multiple versions when updating ?

**Comment by kevinpapst** [comment]
Yes, should be no problem. 
But please read https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md before.
AND: I don't know shit about docker, so this comment is ONLY true for native installations.
