### ISSUE TITLE
allow LDAP jpegPhoto via data:image/jpeg,base64, url

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2323]
**Is your feature request related to a problem? Please describe.**
currently most ldap servers do not spit a public avatar URL, 
but uers have `jpegPhoto` , 
trying to "errornoulsy" pull them into the avatar-adressfield ( config excerpt)
```
                          ## FAILS , WOULD NEED URL FROM LDAP OR BASE64 capabilites 
                           - { ldap_attr: jpegphoto, user_method: setAvatar }
```
not only misses the needed `data:image/jpeg,base64` string a browser would accept
also the string is somehow escaped to a billion escape sequences
 but:
 
```
 An exception occurred while executing 'INSERT INTO kimai2_users (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, alias, registration_date, title, avatar, api_token, auth) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["testnutzer", "testnutzer", "a@b.de,"a@b.de", 1, null, "", "2021-02-07 17:27:10", null, null, "a:0:{}", "Test Nutzer", "2021-02-07 17:27:09", null, "\xff\xd8\xff\ 
 .. TONS OF ESCAPES...
 ", null, "ldap"]:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xFF\xD8\xFF\xE0\x00\x10...' for column `kimai2`.`kimai2_users`.`avatar` at row 1
```

**Describe the solution you'd like**
* SOLUTION A: kimai stores a copy of `jpegphoto` in `public/` folder ( and maybe resync every X time period)
* SOLUTION B: kimai takes the `jpegPhoto` content transformed as ` data:image/jpeg,base64,$jpegPhoto`

**Comment by kevinpapst** [comment]
#1405

**Comment by bash-stack** [comment]
( maybe just add `setAvatarBase64() `as a function that sets the url to `data:image/jpeg,base64,$jpegPhoto` 
DANGER:  this could kill browsers when appearing in html forms ( like user edit page), inline-stuff in forms pushs e.g. firefox to 100% cpu load   )
