### ISSUE TITLE
Send the user back to timesheet after multi edit 

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2339]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i stay in timesheet on single edit but my search gets lost after multi-update

**Describe the solution you'd like**
send me back to my previous page after multi-edit  ( e.g. /en/team/timesheet/?searchTerm=&daterange=&projects[]=35&order=DESC&orderBy=begin )

**Describe alternatives you've considered**
hiring someone for single edits?

**Comment by kevinpapst** [comment]
duplicate for store latest search
