### ISSUE TITLE
Sorting in Team slection seems random

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2340]
**Is your feature request related to a problem? Please describe.**
There are machine accounts for tracking long-run operations ( cron , heavy calculation  etc.) 

implemented with [kima-cmd-track](https://gitlab.com/the-foundation/kimai-cmd-track) 

when selecting teams it seems totally random: 
* users names do not seem to be the sort key
* neither the user id

the machine accounts are named Z_MyMachine ( hint: in LDAP-AD Setup: $machineaccountname )
but they appear some where ( they were created before most users but appear everywhere)

![So random](https://user-images.githubusercontent.com/62184749/107424254-baf87200-6b1d-11eb-8e00-2053734dafec.png)

**Describe the solution you'd like**
have a sort key on that form or in backend

**Describe alternatives you've considered**
none

**Screenshot**
the above one with sort key :)

**Comment by kevinpapst** [comment]
They are sorted by username (not by email, not by alias)
