### ISSUE TITLE
Prevent bookings with same start / stop time

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2342]
**Is your feature request related to a problem? Please describe.**
Bookings with same start and stop time are making no sense, but are now possible

**Describe the solution you'd like**
Prevent these bookings.
If there is another sense behind this behavior make it optional via settings.

**Comment by kevinpapst** [comment]
See also https://github.com/kevinpapst/kimai2/discussions/2315

**Comment by HeinzWuert** [comment]
to be closed

**Comment by kevinpapst** [comment]
Nope, a discussion is not a feature request. I don't keep track of them.

**Comment by HeinzWuert** [comment]
it's the same to #2315

**Comment by kevinpapst** [comment]
Sorry for the confusion. I meant we keep this feature request, because a discussion will be gone soon.

**Comment by kevinpapst** [comment]
There should be a new system configuration, which is activated by default.
Code wise: a new Constraint and Validator class is needed. 
Build the class as `final class TimesheetZeroLength extends TimesheetConstraint` [see here](https://github.com/kevinpapst/kimai2/blob/master/src/Validator/Constraints/TimesheetLockdown.php#L12) and it will be automatically loaded and applied when saving a new record.

Problem might be: rounding rules could become a problem. They are applied later and we might not be able to detect if the given being and end datetime lead to an zero duration.

**Comment by HeinzWuert** [comment]
My workaround in #2315 helps for the moment.

**Comment by crm-developer** [comment]
I take
