### ISSUE TITLE
Word Invoice does not consider locale

### ISSUE THREAD

**Issue by vic-t** [kevinpapst/kimai2#2347]
Hi Kevin, 

Since this is my first entry here, just a quick introduction. I reviewed quite a few time tracking solutions over the last year, all of them commercial. Most of these solutions are really good, particularly from a usability perspective. But when it comes to certain technical details, they always lack something of importance to me and, as usual with commercial software, it's rather difficult to get them to improve even small things, not to mention bigger ones. 

Just very recently when I was yet again looking for a new, potentially better solution, I came across Kimai and it sounds very promising. Also, having access to a solution that is open source is just such a big bonus and I thank you for your generosity. I'm not a full time developer but I know my way around PHP and if I should decide to fully commit to the project, you can at the very least expect regular bug reports and feature requests, and at some stage maybe even pull requests.

So, I may have found an issue in the current stable version of Kimai2. Specifically, the Word Invoice creation does not seem to take the locale into account. I wish to use the **Swiss German** locale for numbers and this seems to work fine for the web frontend. But when creating an invoice, a different locale is used for numbers. Currently, a four digit numbers looks like this 1.000,00 instead of this 1'000.00. 

According to your documentation about Translations, you write "The number formats on the Kimai frontend as well as in the invoices are defined by the frontend locales. If you get wrong decimal separator or thousands separator keys, please import the correct frontend locale as described above." 

I can confirm that the Kimai frontend is shown in the correct Swiss German locale but the invoice is not. If the documentation is correct, then I assume this is a bug. Otherwise there may be an issue with the documentation.

**Comment by kevinpapst** [comment]
Works for me. Invoice templates have a separate language setting.Have you configured the invoice template (/de_CH/invoice/template) to use `German (Swiss)`?
<img width="919" alt="Bildschirmfoto 2021-02-14 um 08 05 18" src="https://user-images.githubusercontent.com/533162/107870741-62b5cd00-6e9b-11eb-8a5f-9fe07f270cec.png">

**Comment by vic-t** [comment]
That was it! Thanks, it really wasn't obvious for me from the documentation. 

Please note that, even though I chose "Deutsch (Schweiz)" as a language for the invoice, in the invoice templates overview it still just says "Deutsch". Is that intended?

I wonder if, in the longer term, it wouldn't make more sense to differentiate language and number formats in Kimai? Just as on Linux where you can set a language locale but independently set a different locale for time and numeric formats. In my specific case, I like to work with an English user interface but I would still like for dates and number formats to follow the Swiss German locale. 

Anyway, this is not of major importance at that stage, thanks for your quick help with my issue.
