### ISSUE TITLE
Allow setting a custom invoice date

### ISSUE THREAD

**Issue by vic-t** [kevinpapst/kimai2#2348]
**Is your feature request related to a problem? Please describe.**
Like many other companies, we issue quarterly invoices, specifically, at the end of each quarter. Of course, it is not realistic that all timesheet entries for the quarter are verified and approved in one day so, typically, the invoices are sent within 2 weeks but the invoice date still needs to reflect the end of the quarter. 

**Describe the solution you'd like**
We need to be able to specify not just the time period that needs to be invoiced but also the date the invoice should show. This is pretty standard for invoicing solutions. 

**Describe alternatives you've considered**
I think the only alternative are Word invoices where the date is changed manually. That's not very practical, though. 

**Screenshot**
Most likely not necessary.

**Comment by kevinpapst** [comment]
You said you are a PHP developer: you can write a plugin that listens to the [InvoicePreRenderEvent](https://github.com/kevinpapst/kimai2/blob/master/src/Event/InvoicePreRenderEvent.php) and set the date to the model.

**Comment by vic-t** [comment]
I said I'm not a full time developer! ;-) I certainly could do it but while a seasoned developer will get this done quickly I'm sure I would have to spend quite some time on it. I'd love to but just can't afford the time at this moment.

Can you give me just a very rough indication how much time it takes, in your opinion, to create such a plugin? 1 hour, 4 hours, a day, longer?

**Comment by kevinpapst** [comment]
Supported with the next major release: https://github.com/kevinpapst/kimai2/pull/2902

Closing here.
