### ISSUE TITLE
More layout options for Word invoices with regards to entries

### ISSUE THREAD

**Issue by vic-t** [kevinpapst/kimai2#2352]
**Is your feature request related to a problem? Please describe.**
For Word invoice templates, Kimai currently supports only one single timesheet table that will include all elements for all activities and all types of timesheet entries, including actual times, fixed rates, and even expenses. With a high number of entries, it will lack clarity.

**Describe the solution you'd like**
Ideally, we could create multiple tables that contain only the information we need. So, I thought about how to communicate this from within Word when, unlike Twig templates, no direct interaction is possible. I believe I found an elegant solution. 

Right before the entries table, there could be some sort of filter instruction that Kimai reads, for example in brackets. So, let's assume I mostly work with two global activities and I wish to present this information in two very different tables, I could just put this filter instruction before the table, looking something like this: 

```
[Project_ID: All, Activities: All, User: All]
${entry.activity} ${entry.description}

[Project_ID: All, Activity_ID: 1, User_ID: All]
${entry.description} ${entry.total}

[Project_ID: All, Activity_ID: 2, User_ID: All]
${entry.description} ${entry.rate} ${entry.total}
```

Needless to say, filtering could be further enhanced with other filter types. Instead of filtering by ID, it may make sense to filter by name which is probably the way to go for those users who don't use global activities. 

Either way, this would not break existing invoices (no instruction means just use everything) but it would massively improve usability for Word and potentially other types of invoices. 

**Describe alternatives you've considered**
I believe Twig templates may be another alternative or to just export all entries to third party systems.

**Comment by kevinpapst** [comment]
There is no two-way communication possible between template and Kimai.
Technically maybe feasible, but sounds rather complicated.
Nice idea, but this will not make it into Kimai.

**Comment by vic-t** [comment]
I'm not sure why you consider my suggested procedure a two-way communication. The whole point of it is that the file can just be read and some of the placeholders can be interpreted as instructions. At no point in time does the template actively communicate with Kimai. 

I believe you do the exact same thing already when you consider a table row containing the placeholder ${entry.description} as an instruction to repeat rows as long as there are entries. 

It's the same here, if you find a placeholder `[Activities_ID:1]` right before the table row, Kimai would simply provide all entries, filtered by the activities_id 1. 

It's definitely not something simple but I think it's a valid request. As such, I'd appreciate it if you could leave it open for others to find and vote on it. If you're going to work on it or not is still entirely your decision, so you can even leave the wontfix tag for all I care, maybe a plugin developer will pick this up. :-)
