### ISSUE TITLE
Export invoices

### ISSUE THREAD

**Issue by vic-t** [kevinpapst/kimai2#2354]
From what I've seen, currently, it's not possible to export information about created invoices, there isn't even an API call. 

If I should decide to use Kimai for invoicing, I will need to export information about these invoices in order to import the same in my accounting system from where I can then manage payments and payment reminders. 

Clearly, Kimai saves the necessary information in the database, there already is a table named kimai2_invoices. So, as a temporary alternative, I can just create a CSV export from the database directly. But it would be nice if an invoice export functionality could be built into the Kimai frontend. 

I saw that a bounty was created for an invoice exporter with some very specific functionality (see https://github.com/kevinpapst/kimai2/issues/1955) but it seems to me that exporting invoices or referencing them via API should be part of the official product. 

Anyway, I'd be happy to match the bounty offered by the OP in the other post to support the developers with this task. (I never worked with bounties so I'll need some info on the funding process).

**Comment by kevinpapst** [comment]
Please include your comments in #1955 - so all information are in one place. Closing here
