### ISSUE TITLE
Unreadable dirty modal notice

### ISSUE THREAD

**Issue by strouble** [kevinpapst/kimai2#2370]
On delete modals, the "dirty notice" isn't readable very well:
![not_readable](https://user-images.githubusercontent.com/4526793/108206722-1088dc00-7127-11eb-83d2-63b54d874b73.png)

A possible fix could be: `assets/js/plugins/KimaiAjaxModalForm.js`
```
-                    jQuery('#remote_form_modal .modal-body').prepend('<p class="text-danger small remote_modal_is_dirty_warning">' + msg + '</p>');
+                    const msg_class = (self.modal.hasClass('modal-danger') ? 'well well-sm ' : '') + 'text-danger small remote_modal_is_dirty_warning';
+                    jQuery('#remote_form_modal .modal-body').prepend('<p class="' + msg_class + '">' + msg + '</p>');
```
![readable](https://user-images.githubusercontent.com/4526793/108207516-264ad100-7128-11eb-9616-48217fce75d3.png)

Not quite sure, if i should create a pull request for this, or not ... :wink:

**Comment by kevinpapst** [comment]
I have seen that as well - obviously after the release^^ and thought it could be hidden for a bit longer 😁 

The check probably doesn't even make a lot of sense in danger/delete forms.  But your solution looks good!

And a PR is always a good idea, then we can forget it again 👍 I will recompile the assets later. The changed JS is enough.

Thank you @strouble !

**Comment by kevinpapst** [comment]
After giving it another thought, I think the listener should be deactivated on delete forms completely. 
Deletion is the most obtrusive form of data manipulation and should not be necessary, especially with data that is linked to other data via foreign keys.

So in my opinion it is better to allow closing a delete modal by clicking outside of it, even after selecting something in the dropdown.

So I see two improvements here:
- being able to deactivate the [has form changed handler](https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiAjaxModalForm.js#L161) , eg. by looking for a css class on the form element or modal itself
- fix the CSS issue

**Comment by crm-developer** [comment]
I will take it
