### ISSUE TITLE
New config: default team for new customer

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#2372]
**Is your feature request related to a problem? Please describe.**
In an environment with teams and protected access to certain customers, creating new customers can be a risk, if you forget to add a new team directly afterwards.

**Describe the solution you'd like**
There should be a new default system configuration for a team, which is automatically applied to new customers.

**TODO**
- Add a new config to the [customer section](https://github.com/kevinpapst/kimai2/blob/master/src/Controller/SystemConfigurationController.php#L372)
- Check config and [add team for new customers](https://github.com/kevinpapst/kimai2/blob/master/src/Customer/CustomerService.php#L55)
- Translation 'label.team' can be used

**Comment by crm-developer** [comment]
I take

**Comment by kevinpapst** [comment]
See #1845

**Comment by kevinpapst** [comment]
closing as duplicate of #1845
