### ISSUE TITLE
Kalender Darstellung

### ISSUE THREAD

**Issue by dg3fbl** [kevinpapst/kimai2#2378]
In der Kalenderdarstellung wird bei der Uhrzeit ":00" unterdrückt, siehe Screenshot.

https://xxxxx.kimai.cloud/de/calendar/

Kimai Cloud 1.13
Browser Chrome 88.0
![image](https://user-images.githubusercontent.com/58482370/109000465-0a08e000-76a4-11eb-8c87-3597b65a4ee6.png)

**Comment by HeinzWuert** [comment]
I like it this way, helps for fast orientation

**Comment by kevinpapst** [comment]
Ist gewollt so.
