### ISSUE TITLE
Unknown format length found

### ISSUE THREAD

**Issue by ilicilho** [kevinpapst/kimai2#2381]
After update my Kimai version to latest, when I try to generate a invoice, I see a baloom :
The changes cannot be saved, check Doctor.
 In doctor I can see this error:

app.CRITICAL: An exception has been thrown during the rendering of a template ("Unknown format length found"). [] []

I try to reload cache, I check the permissions, it´s all rigth

**Comment by kevinpapst** [comment]
Thats a problem with your invoice number format. Can you share it?

**Comment by ilicilho** [comment]
Hello Kevin.
This is the format, used since version2.10 {Y}/{cy,cc,3}

**Comment by kevinpapst** [comment]
Aha, okay. There was a bug in parsing the invoice number.
This is not a legal format and therefor now rejected. 
It must be `{Y}/{cy,3}{cc,3}` or `{Y}/{cy}{cc,3}`, depends what you want to achieve.
How did the generated invoice number look like before?

**Comment by ilicilho** [comment]
Great!! that is working!!
Thanks, Kevin!
