### ISSUE TITLE
Easy editing of translations without programming knowledge.

### ISSUE THREAD

**Issue by crm-developer** [kevinpapst/kimai2#2384]
**Is your feature request related to a problem? Please describe.**
Project localizations are too complex. In order for people with no programming knowledge to participate in the translation, you need to simplify the translation. This will increase the flow of people from other countries to the project. And translate the entire project almost instantly. This will make it very easy to edit all the missing translation in one file.

**Describe the solution you'd like**
Command line controller.
Go to yaml.
Rebuilds all locales with sorting.
Rearranging missing items.
TODO:
create command line controller
get a list of locales
make a backup of all translations
delete all translations
update all english translations
create new files with translations in other languages ​​according to the English template
update all translated words
remove tmp
clear cache
running from the console in one line for everything:
`php bin/console kimai:clean-locales`

**It's done. I can PR it.**
--------------------------------

**Describe alternatives you've considered**
There are no alternatives. We can later add translation editing functions directly from the admin panel.

![file](https://user-images.githubusercontent.com/54503325/109572976-30dd7100-7aff-11eb-8e23-228f9323083c.png)
![terminal](https://user-images.githubusercontent.com/54503325/109573170-90d41780-7aff-11eb-8093-a6551328364b.png)

**Comment by kevinpapst** [comment]
Weblate is enough for now. There are more important features waiting.
