### ISSUE TITLE
Cleaning Dashboard from projects out of date

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2390]
**Is your feature request related to a problem? Please describe.**
All projects that are assigned to the user are displayed in the dashboard, but expired jobs are actually no longer relevant.

Idea: Automatically hide all projects where the month of the end date is older than the current month.

Example:
Today is February 15th
One of the orders ends on February 7th = is still displayed for this month, still important for  the user.
Orders with an end date before February 1st should be hidden.

**Comment by kevinpapst** [comment]
Sounds good, but why not hiding it directly after it ended?

**Comment by HeinzWuert** [comment]
simply as an overview of the current month but hidding when ended is also ok.
