### ISSUE TITLE
Timesheet export ignores column visibility

### ISSUE THREAD

**Issue by lbm-services** [kevinpapst/kimai2#2395]
Even if I change column visibility and uncheck rates I get exports with rate column in summary and "Full list". 
The templates displays depending on the vars showRateColumn and showRateBudget. Where are these set?
A temporarily solution seems to set this options to false in the template itself:

```
{% set showRateColumn = false %}
{% set showRateBudget = false %}
```

**Comment by kevinpapst** [comment]
The column visibility has nothing to do with the exported columns.

At some point in the future, the export functionality might allow to customize the columns.
Until then, you have to define the columns via export templates.

**Comment by lbm-services** [comment]
Sure. I am refering to the export template.
