### ISSUE TITLE
I want to modify the duration count.

### ISSUE THREAD

**Issue by zhasan0** [kevinpapst/kimai2#2406]
There have only begin and end time. But I added extra two fields as a afternoon shift begin and end time. Duration will count based on begin and end time.  But now how can I modify the duration counting. I want to the duration count like below image.

![SCREEN-1](https://user-images.githubusercontent.com/42202246/110311178-9fee2480-802d-11eb-990b-b4277ffeba09.png)

**Comment by kevinpapst** [comment]
You mean this?
https://github.com/kevinpapst/kimai2/blob/master/src/Timesheet/Calculator/DurationCalculator.php
