### ISSUE TITLE
Duration modified doesn't working.

### ISSUE THREAD

**Issue by zhasan0** [kevinpapst/kimai2#2410]
Hello great people, I am a beginner developer. Who wants to learn more. Can you please help me to solve this problem.

I modified the DurationCalculator file like below image.  But it's do not working like new modification. It's work like existing duration count.

Thank you.

![modified duration calculator ](https://user-images.githubusercontent.com/42202246/110331572-7f33c800-8049-11eb-977b-b8a0a70f3f71.png)

There is only beginning and end time. But I added extra two fields as an afternoon shift begin and end time. Duration will count based on begin and end time.
But now how can I modify the duration counting?

**Comment by kevinpapst** [comment]
Post answer to your discussion: 
https://github.com/kevinpapst/kimai2/discussions/2407
