### ISSUE TITLE
Database locks not supported on Percona cluster

### ISSUE THREAD

**Issue by matthijs-va** [kevinpapst/kimai2#2421]
**Describe the bug**

When using a MySQL database the advisory lock mode is is used:
```
if ($pdoOrDsn->getAttribute(\PDO::ATTR_DRIVER_NAME) === 'mysql') {
    $lockMode = PdoSessionHandler::LOCK_ADVISORY;
}
```

But this breaks on a Percona cluster because locking isn't supported.

**Logfile**

```
General error: 1105 Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING
```

**Comment by kevinpapst** [comment]
I have no experience with Persona clusters. If you find a solution, please share it!
Is locking really completely forbidden?

**Comment by matthijs-va** [comment]
Yes, it has something to do with replication (I'm not an expert myself).
I would suggest you make this behaviour configurable?

**Comment by kevinpapst** [comment]
Nope, without locking there will be concurrency bugs. This is unavoidable.
I have no Persona experience. If the company wants to hire me for the job, sure. 
Otherwise someone else with hands at the system needs to debug the issue and come up with a solution.

**Comment by matthijs-va** [comment]
Our hosting partner provided another solution, so I'm closing this.

**Comment by kevinpapst** [comment]
Can you share the solution from your hosting partner for the next user with this problem?
