### ISSUE TITLE
Option to export timesheets with duration in minutes and not seconds

### ISSUE THREAD

**Issue by ad-si** [kevinpapst/kimai2#2434]
**Is your feature request related to a problem? Please describe.**
We need to further process the timesheets and then generate an invoice. Our invoice generation program expects the duration to be provided in minutes.

**Describe the solution you'd like**
A checkbox on the export page "Export duration as minutes"

**Describe alternatives you've considered**
A URL query parameter if you don't want to clutter the UI.
Otherwise the checkbox could also be hidden in an expandable section "advanced settings".

**Screenshot**
![image](https://user-images.githubusercontent.com/36796532/111084173-fb765180-8508-11eb-9560-3fb6c60d7c6a.png)

**Comment by kevinpapst** [comment]
I don't see, why Kimai should solve this task.
This can be done via plugin or some script in between Kimai and your invoice program or maybe with a custom export template. Or you ask the developer of the invoice program (which one is it?) to allow seconds.

**Comment by ad-si** [comment]
Yeah, I already wrote a script to do it.
Nevertheless, since most users will use time tracking on a minute basis, it seems weird to not be able to export it also in that format.
But yeah, not a must have feature, so feel free to close it if you don't want to support it.
