### ISSUE TITLE
Invoices -> new field to save the date when the invoice was payed and it is relevant for German "Umsatzsteuer-Voranmeldung"

### ISSUE THREAD

**Issue by cayacdev** [kevinpapst/kimai2#2449]
**Is your feature request related to a problem? Please describe.**
In Germany, we have to pre-register sales tax with the tax office on a monthly basis (Umsatzsteuer-Voranmeldung). This information refers to the incoming payments from the previous month. The number given is the total of paid invoices in the previous month without the sales tax.

**Describe the solution you'd like**
1. When I mark the invoice as paid, I want to specify the date the payment was received. So at the end of the month I can filter the invoices that were paid in a certain period. 
2. The invoice can be be marked as relevant for "Umsatzsteuer-Voranmeldung".
3. I can view the total (without taxes) of paid invoices relevant for "Umsatzsteuer-Voranmeldung" and within a certain period. 

**Describe alternatives you've considered**
I considered no alternatives yet.

**Screenshot**
No screenshots yet.

I'm a Java Dev, so I'm not a PHP Pro but I guess that I can work on a Pull Request (or a plugin) with a little help. 
I think that this problem is only relevant for German companies / freelancers. Therefore, a plugin will probably be the better option. Or it could be divided into multiple parts. Specifying a date when the invoice was paid could be interesting for all countries.

My first scribbled solution is:
- Adding two new attribute to Invoices (paidOn, relevantForGermanSalesTax)
- Adding an additional filter to the invoice filter (#2408) ("Time range of payment") or a radio button on the existing time range field (option 1: "creation", option 2: "payment")
- Adding an additional filter checkbox "relevant for german sales tax"
- Add a new column for the invoices "subTotal" and include it also in the xlsx export (Apparently, the InvoiceEntity does not have a persisted attribute for subTotal yet. But with AbstractCalculator#getSubtotal this is probably an easy thing to do.)

Is this possible with an plugin? In the documentation I found the option of "Custom Fields" but there is no word about the invoice entity.

**Comment by kevinpapst** [comment]
Hi @cayacdev , thanks for posting your idea!

> I'm a Java Dev, so I'm not a PHP Pro but I guess that I can work on a Pull Request (or a plugin) with a little help.

Strong 👍 for the PR 😁 

I want to see the date of payment as field as well!
Another feature I would like to add is an input field to manually set the invoice date.
That fits well into Kimai core.

Contrary is the field `relevantForGermanSalesTax`, which I don't want to see in the (core) database.
We could either add custom field support to invoices - good idea - or you could add the field via plugin.
I don't even know which one is more work.
The custom field logic (eg interfaces and ORM logic) is already there and  can be copy&pasted from other objects,

Then you could configure a checkbox as custom field and use the existing search logic `customFieldName:1` (free search term) for selecting invoices.

**Comment by cayacdev** [comment]
Hi @kevinpapst, thank you for the quick response.

I will created a Pull Request containing:
- a new field on invoices "date of payment"
- a new field on invoices "subtotal"
- custom field support for invoices


One question: Do I need the Custom Field Plugin to create "relevantForGermanSalesTax" as custom field or can I also implement a custom plugin to it? I have read this page https://www.kimai.org/documentation/meta-fields.html but I don't understand where to put this custom code. I guess in a custom plugin, right?

**Comment by kevinpapst** [comment]
You can create your own plugin - eg. start of with a clone of https://github.com/Keleo/DemoBundle

**Comment by cayacdev** [comment]
Hi @kevinpapst,

I was able to create the new fields and for the subtotal I already have the whole roundtrip (creation, viewing, xlsx export). 
For the field "payment_date" I still have no idea how to get the value into the entity.

I imagine an input field at the action "Invoice Paid" where the user can choose a date. In this file the invoice actions are created: `InvoiceSubscriber.php`. 

<img width="454" alt="Screenshot 2021-03-20 at 18 50 46" src="https://user-images.githubusercontent.com/6408145/111880898-387d9080-89ae-11eb-8fa7-56ccbd6113b0.png">

Unfortunately I can't find an action that already uses something similar to input fields (I searched for the usages of `\App\Event\PageActionsEvent::addAction`).

Can you give me a hint or a suggestion for a solution?

**Comment by kevinpapst** [comment]
Oho, that was quick, I didn't expect feedback so soon.

You need to change the logic in the controller action, which is called to change the invoice state.
First check which status was given in https://github.com/kevinpapst/kimai2/blob/master/src/Controller/InvoiceController.php#L190
and then display a form (only one field of type `DateTimePickerType::class` is necessary eg [like this](https://github.com/kevinpapst/kimai2/blob/master/src/Form/ProjectEditForm.php#L76)) before proceeding in case the new status should be "paid. 

And you need to change this action: 
https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/Actions/InvoiceSubscriber.php#L37
and add the `'class' => 'modal-ajax-form'`. That is enough to open a modal with the datetime picker picker.

**Comment by cayacdev** [comment]
Hi @kevinpapst ,

thank you for your tips :) 

I was able to open the modal with a form and submit it and I added it as new column to the listing page. 
Now I'm struggling with the updating of the listing page.
When I change the status from `New` to `Waiting for payment`, then the listing is updated (Status column is updated). But when I change the status to `Paid` and choose the paymentDate in the form, the listing is not updated after submitting the form. I have to reload the page to show the updated listing page.

Can you give me a hint why it is not updating as before?
Should I open a pull request (work in progress) already?

**Comment by cayacdev** [comment]
Found it ;)
```
    <script type="text/javascript">
        document.addEventListener('kimai.initialized', function() {
            KimaiReloadPageWidget.create('kimai.invoiceSetPaymentDate');
        });
    </script>
```

**Comment by kevinpapst** [comment]
Really nice, I can't believe that you are not a PHP developer.
Please sent in a PR right away, I saw a couple of tiny things that need to be smoothed out (mostly internal stuff that came in by copy&paste) which you can't know about.

**Comment by cayacdev** [comment]
I have made a very small Laravel (Lumen) project which has a few entities and a few controllers to provide an API. But it is more copy / paste. So I know a little bit the syntax of PHP, but not enough to call myself PHP Developer :D

I created the PR as draft: #2450

**Comment by cayacdev** [comment]
Hi @kevinpapst,

should we leave this issue open or better to close it because #2450 is backmerged yet. For the two open topics (custom field support for invoices, invoice search on payment date range) I can open new issues or directly create PR's. What do you prefer?

**Comment by kevinpapst** [comment]
Missed it, thanks 👍 

I will close it, as the topic was about the date and that its now available
Lets create new issues for the other topics.
