### ISSUE TITLE
Optionally hide Username/Password and Login button

### ISSUE THREAD

**Issue by urinal-cake** [kevinpapst/kimai2#2458]
**Is your feature request related to a problem? Please describe.**
When bringing on new employees and contractors, we find it fairly confusing to repeatedly have to remind them that they do _not_ need to use the Username and Password fields when logging in. This is not necessary for us, because we use SAML login, and I would imagine this would not be necessary for those using OAUTH or other LDAP providers.

**Describe the solution you'd like**
Ideally, within local.yml, it would be great if we could add a line that was similar to the documented [User Registration disabling feature](https://www.kimai.org/documentation/users.html#user-registration):
```
kimai:
    user:
        username_password_login: false
```
By default, this setting would be set to true. When set to false, it would check to make sure `saml: activate:` (or any other LDAP/OAUTH setting) is set to true, and then hide the username and password form input, the remember me checkbox and label, the login button and the forgot password option.

**Describe alternatives you've considered**
I have considered making CSS changes myself to do this. However, since our time tracker is accessible to the public, I would feel more secure if these inputs were not available at all, since our users should ONLY be using their SAML login to login with.

**Screenshot**
![image](https://user-images.githubusercontent.com/7855304/112402339-c0330a00-8ce2-11eb-8f77-93e6839ea020.png)

**Comment by kevinpapst** [comment]
Will be implemented by #2602

**Comment by kevinpapst** [comment]
Version 1.15 allows to de-/activate:
<img width="592" alt="Bildschirmfoto 2021-07-13 um 13 53 41" src="https://user-images.githubusercontent.com/533162/125447221-20bd174e-bd69-42d3-bd3e-304fd5e5e768.png">
