### ISSUE TITLE
Monthly view for all users

### ISSUE THREAD

**Issue by nhadsall** [kevinpapst/kimai2#2460]
**Describe the solution you'd like**
A simple fix would be offering the "Monthly view for one user" but for all users. Or better yet, let us toggle which ones to include.

**Describe alternatives you've considered**
We are stuck using clockify for now. We would really like to switch to Kimai, we need the reporting that clockify offers. Being able to generate reports based off the same search options available in the timesheet view would be a GAME CHANGER!

**Comment by kevinpapst** [comment]
You can always sponsor the development of features. 
Especially if you could get rid of a paid tool with this new report^^

**Comment by nhadsall** [comment]
@kevinpapst Thanks for the fast reply. We are currently using clockify free, but as web dev company ourselves, I always prefer control of my own data and code. I've been using Kimai v1 since 2016 and just now discovered v2 lol.

For now, simply being able to select all users for the report layout "Monthly view for one user" would really help us make the switch. Without that, we just can't get the data we need. This would be request one.

![Capture](https://user-images.githubusercontent.com/10870098/112472752-e210a900-8d43-11eb-8ab2-2845f93c497e.PNG)

The best option would be what I mentioned, to have different report formats that can give data based on the same search feature you already have in the timesheet. The ability to filter the data in any given report is huge. This would be a second part of the feature request.

The last element would be consolidating the various types of reporting that Kimai already has. Clockify has 3 formats. "Summary" report is in the screen shot below. That's similar to the dashboard graphs in Kimai already. However, it also lets us see the total hours for any given project/client. It just has flexibility to select client or project. The "Detailed" report is really just the same as the Kimai Timesheets view. Weekly is very much like the "Monthly view for one user" report.

I'd love to see how much work it would be to simply implement point 1. We could even help, but just don't know the code base well, so a point in the right direction would be great. Then, I'd be happy to chat about supporting points 2 and 3.

Let me know! Thanks!

**Comment by HeinzWuert** [comment]
Isn't it the same direction? https://github.com/kevinpapst/kimai2/pull/2020

**Comment by kevinpapst** [comment]
Part 1 added for next release 1.14. 
Part 2 and 3 can be re-opened as new feature request
