### ISSUE TITLE
/api/timesheets?page=[nonexistant] fails with error 500 instead of 404

### ISSUE THREAD

**Issue by pbksol** [kevinpapst/kimai2#2466]
From the API documentation:

page - string - The page to display, renders a 404 if not found (default: 1)

The API call renders a 500 error if a non existent page is requested:

`[2021-03-26 21:56:51] request.CRITICAL: Uncaught PHP Exception Pagerfanta\Exception\OutOfRangeCurrentPageException: "Page "6" does not exist. The currentPage must be inferior to "1"" at …/kimai2/vendor/pagerfanta/pagerfanta/lib/Core/Pagerfanta.php line 298 {"exception":"[object] (Pagerfanta\\Exception\\OutOfRangeCurrentPageException(code: 0): Page \"6\" does not exist. The currentPage must be inferior to \"1\" at …/kimai2/vendor/pagerfanta/pagerfanta/lib/Core/Pagerfanta.php:298)"} []`

Kimai 1.13 stable

**Comment by kevinpapst** [comment]
Thanks for letting me know!

**Comment by kevinpapst** [comment]
Will be fixed with https://github.com/kevinpapst/kimai2/pull/2468
