### ISSUE TITLE
Administration of projects throws error if locale is "de"

### ISSUE THREAD

**Issue by ravor-org** [kevinpapst/kimai2#247]
**Describe the bug**
I just added a project within kimai and as soon as you do so, you cannot edit them anymore as it throws a HTTP 500. If you switch to locale "en" everything works fine.

**To Reproduce**
1. Go to "Administration" -> Projects
2. Add a new one (if there's none)
3. Go to "Administration" -> Projects

**Expected behavior**
A localized administration page should be shown.

**Screenshots**
![error_500](https://user-images.githubusercontent.com/10080228/43386570-53a3c5e0-93e4-11e8-98c6-38f63b772a05.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Doesn't matter
 - Version: doesn't matter

**Server:**
 - OS: Debian Wheezy
 - PHP: 7.1.20 (intl extension is installed)
 - Webserver: nginx

**Additional context**
Intl Extension Info:
```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 4.8.1.1
ICU Data version => 4.8.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

Error Log:
`request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The Symfony\Component\Intl\NumberFormatter\NumberFormatter::__construct() method's argument $locale value 'de' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities.")." at <path>/templates/admin/project.html.twig line 39 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The Symfony\\Component\\Intl\\NumberFormatter\\NumberFormatter::__construct() method's argument $locale value 'de' behavior is not implemented. Only the locale \"en\" is supported.  Please install the \"intl\" extension for full localization capabilities.\"). at <path>/templates/admin/project.html.twig:39, Symfony\\Component\\Intl\\Exception\\MethodArgumentValueNotImplementedException(code: 0): The Symfony\\Component\\Intl\\NumberFormatter\\NumberFormatter::__construct() method's argument $locale value 'de' behavior is not implemented. Only the locale \"en\" is supported.  Please install the \"intl\" extension for full localization capabilities. at <path>/vendor/symfony/intl/NumberFormatter/NumberFormatter.php:263)"} []`

**Comment by ravor-org** [comment]
Problem solved. Somehow the INTL extension was available in php but wasn't loaded for the php-fpm. Restarted the service and everything works as expected.

**Comment by kevinpapst** [comment]
Thanks for the feedback!
Actually its checked during composer installation: https://github.com/kevinpapst/kimai2/blob/master/composer.json#L8
So having it only activated in cli was the only thinkable solution.
