### ISSUE TITLE
Preselect Customer and Project

### ISSUE THREAD

**Issue by lbm-services** [kevinpapst/kimai2#2470]
if there is only one customer and one project, new actvities were easier to create if they were preselected.
Even if there are more than one, it would come handy if the last project was preselected, since most of the time you add activities to your current project, I guess.

If I start an activity the latest created activity should be first in the list of the dropdown. It is kind of annoying that I have to search for my just created activity, if I want to start working on it.

**Comment by HeinzWuert** [comment]
same as #960

**Comment by kevinpapst** [comment]
Vote for #960. Closing as duplicate
