### ISSUE TITLE
The table Reporting page does not respect the user's First day of the week setting

### ISSUE THREAD

**Issue by urinal-cake** [kevinpapst/kimai2#2475]
**Describe the bug**
This issue is _similar_ to #2459, but is not the same, as it has the same results on a different page, with a different UI control. If the user views the Reporting page, then the table that appears that displays the week will always start with a Monday regardless of the user's setting for 'First day of the week' within their preferences.

**To Reproduce**
1. Go to Preferences for the currently logged in user
2. Select 'Sunday' for the 'First day of the week' preference
3. Go to the Reporting page
4. Notice that the first column in the table still shows Monday in the top left.

**Additional context**
 - Kimai version: 1.13 stable
 - PHP version: 7.4.15
 - Device: Ubuntu 18.04 Virtual Machine
 - Browser: Chrome 89

**Comment by kevinpapst** [comment]
Calendars are such an annoying topic ... why can't we (as world) decide for one format everywhere? 👿 😁 


Sorry, that first day of the week will likely be a topic that will pop up over and over again. No offense, its just that I don't think about it ever. But I'll look into it!

**Comment by urinal-cake** [comment]
@kevinpapst I'm not very great at Symfony, so I can't imagine how it works on the backend, but as someone who deals with lots of various tooling across many platforms and ecosystems. AGREED!

Understood that you don't look into it. I've been slowly introducing Kimai2 to many US and Canadian partners over the last two years, so the more support for days that start with Sunday, the better!
Thanks for the hard work!

**Comment by kevinpapst** [comment]
> Understood that you don't look into it.

No, I WILL look into it. 

Growing up with the "one truth" 😀 that the first day of the week is Monday, it feels "weird'ish" and it is very hard for me to remember that setting. 

But it is an important topic, so please keep on posting the places you find.
