### ISSUE TITLE
Reporting show time entries of other users the teamleader has no access to

### ISSUE THREAD

**Issue by colorcube** [kevinpapst/kimai2#2478]
Teamleader Kevin has access to projects AA and BB.
User Karen has access to projects BB and CC.

view_other_timesheet is on for Kevin

In Administration>Timesheets Kevin can see Karens times of the project BB (not CC).
In Administration>Reporting Kevin can see all of Karens times (projects BB and CC).

I think in Reporting Kevin should only see times he has access to. Like in Timesheets.

**Additional context**
 - Kimai version: 1.13
 - no plugins installed

**Comment by kevinpapst** [comment]
Not sure about that, I do not strongly disagree but I do not agree as well.
A teamlead should not be able to edit or see details of these records (prevent information leakage).
But a teamlead should be able to see if his team mates have worked the appropriate hours / what they have done outside of his own team.

**Comment by colorcube** [comment]
I don't have a need for evaluating "have worked the appropriate hours" so I can't say anything about that.

But both views show different data which is inconsistent.
And I can only en-/disable both with view_other_timesheet.

How about to "fix" Reporting and add another report on work hours? (using an additional right)

**Comment by kevinpapst** [comment]
Master includes a new permission `view_other_reporting` (enabled by default).
That should hopefully fix your issue.

I will not change which data is shown, a report about working times should show all working times.
