### ISSUE TITLE
CSV importer adds only first missing customer, assigning all other projects to that new customer

### ISSUE THREAD

**Issue by colorcube** [kevinpapst/kimai2#2479]
Importing a CSV file (with the right format) like this:

`bin/console kimai:import:timesheet myfile.csv`

works, but only one of the customers in the CSV file already existed in Kimai. The file had a bunch of new customer in it.

The time entries for the existing customer XX were all added as expected.

The first unknown customer ZZ was added but not the others.
All time entries from other unknown customers were added to customer ZZ (newly created during import)

```
 [OK] Created 1 customers                                                                                               
 [OK] Created 18 projects                                                                                               
 [OK] Created 112 activities                                                                                            
 [OK] Imported 2049 rows    
```

I'm unsure if this is a bug or I did something wrong. I can have a more detailed look if this is not the expected behaviour.

I've got (hopefully unreleated):

`WARNING   [php] Notice: A non well formed numeric value encountered ["exception" => ErrorException { …}]`

I assume that was because the _Exported_ column was just empty instead of having 0/1 in it.

**Additional context**
 - Kimai version: 1.13
 - PHP version: 7.2

**Comment by kevinpapst** [comment]
Sounds wrong, needs to be debugged. 
It definitely worked in the past, as I imported data for multiple customer with it (hundreds of customers and thousands of projects).

**Comment by kevinpapst** [comment]
Last time I used the function it worked... Can you share your CSV file?

**Comment by kevinpapst** [comment]
Hello @colorcube ?

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by kitzler-walli** [comment]
I can confirm the bug but currently can't post the CSV - I'll have to generate an anonymized version of it.

**Comment by kitzler-walli** [comment]
I found the error - simply comment the line `if (null === $this->customerFallback) {` in line 563 and it will work as expected.

**Comment by kevinpapst** [comment]
Thanks for the feedback @kitzler-walli 

Do you mean if this block is removed it will work? 
https://github.com/kevinpapst/kimai2/blob/master/src/Command/ImportTimesheetCommand.php#L563-L597

**Comment by kitzler-walli** [comment]
No - not the whole block - just the if and it's corresponding closing bracket.

**Comment by kitzler-walli** [comment]
I could create a pull request if you'd like to.

**Comment by kevinpapst** [comment]
Yes, that would be great 👍
