### ISSUE TITLE
Location Field

### ISSUE THREAD

**Issue by lbm-services** [kevinpapst/kimai2#2480]
As a freelancer I have different hourly rates depending on the work location (on-site/remote).
It could be useful to set hourly rates in the activities, then I could add activities for different locations and track them as needed.
Since I need to report my on-site/remote hours on a monthly basis, the summary should be enabled to sum up remote/on-site hours and rates as well. 
Implementation of a location field was essential.

**Comment by kevinpapst** [comment]
You can add different rates for different activities.
You can define a custom field for location (or use tags).
You can use invoice calculator "group by activity" to sum up on remote activity vs onsite activity.

What is the feature request about?

**Comment by kevinpapst** [comment]
Thanks for the feedback!
