### ISSUE TITLE
When creating timesheet entry and entry is before project start date generate error rather than not listing the project

### ISSUE THREAD

**Issue by kernie** [kevinpapst/kimai2#2485]
**Is your feature request related to a problem? Please describe.**
When I create a timesheet entry the date and time is autofilled with the current date and time. If the entry date is before project start date the project wouldn't be listed in the dropdown menu. One may justify this, because one cannot work for a project that didn't start. However, searching for my project, I'm getting confused why my project is missing.

**Describe the solution you'd like**
If the entry is before project start I wish to see a message, that this is not possible rather than getting a missing project.

** Kimai
Version 1.13

**Comment by kevinpapst** [comment]
That is ONLY you (as admin and user at the same time) who might get confused. 
Consider you are a teamlead managing projects for dozens of users.

You:
- don't want hidden projects to show up 
- or your users complaining that they cannot book times on a certain project (which did not yet start)

I understand your point, but I reject the feature request.  I think the current behavior is the correct one.

**Comment by kernie** [comment]
I understand that point of view and can life with that. 

One point to consider, however, could be the option in the admin panel that I can create entries in the future. If activated, I will not find my project ...

**Comment by kevinpapst** [comment]
Sorry, normally I don't close issues right away, but in that case I have a strong opinion how Kimai should behave.

The problem with a new setting is: 
- Kimai gets bloated with behavior options which are very hard to remember (even for me) and which interferes with each other
- If you have a setting to ignore project start, why not simply removing the project start?

**Comment by kernie** [comment]
In case others have the same experience I added a section in the project documentation (https://github.com/kimai/www.kimai.org/pull/97) to explain the restriction, which results from setting the start or end date.
