### ISSUE TITLE
Some words in docx invoices aren't getting translated

### ISSUE THREAD

**Issue by buti1021** [kevinpapst/kimai2#2486]
**Describe the bug**
Some words in docx invoices aren't getting translated

**To Reproduce**
1. Go to 'Invoices'
2. Go to 'Invoice Templates'
3. Create a template with Invoice document 'docx' and a language other than 'englisch' e.g. 'german'
4. Expected behaviour: no english words, everything in selected language
5. Actual behaviour: some words remain english

Other invoice document types (file formats) work properly (e.g. pdf)

**Additional context**
 - Kimai version: Kimai Cloud Version 1.13

**Comment by kevinpapst** [comment]
Docx templates do not support translations. 
You need to prepare a different template file for every language.

**Comment by buti1021** [comment]
Hey @kevinpapst ,

thanks for your reply!
Is it possible to prepare templates with a reasonable effort for different languages or change the existing one?

Best @buti1021

**Comment by kevinpapst** [comment]
I don't understand the question. There is documentation about invoice templates:
https://www.kimai.org/documentation/invoices.html

You can copy & paste the existing word template and change the contents to match another language.

**Comment by buti1021** [comment]
Well I guess you perfectly understood my question. This was exactly what I was looking for! 
Guess I just didn't jump deep enough into the documentation 🤦‍♂️. Sorry!
However when I try to access /en/invoice/document_upload I get an permission error. As I have System-Admin and administrator rights I guess that is a Kimai Cloud Plan issue (currently using Basic). 
Am I correct? Which plan would be needed to use this feature? The feature comparison doesn't seem to include it (or I just didn't get it) and I wasn't able to find this information elsewhere.

Thanks again, Kimai is great!

**Comment by kevinpapst** [comment]
For security reasons, upload of invoice templates is not yet allowed in the cloud.

You can sent the document to the support email address. 
Lets discuss further via support@kimai.cloud.
