### ISSUE TITLE
Change check buttons in reports > project overview

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2489]
**Is your feature request related to a problem? Please describe.**
There are 2 checkbuttons in project overview for entries without budget and entries without bookings.
It's never possible to see only one of them, because u get an mixture of the default view and the checked button choice.
When using a lot of projects you have to scroll through all of them to find  the checked items.

**Describe the solution you'd like**
a 3rd checkbutton for  the standard view would allow to see each of them as a single list.

**Comment by kevinpapst** [comment]
Added for the next major release, closing
