### ISSUE TITLE
The dates in the header row of the table on the Reporting page are not in the correct format for English (US)

### ISSUE THREAD

**Issue by urinal-cake** [kevinpapst/kimai2#2492]
**Describe the bug**
Inside of the first (header) row of the table on the Reporting page are abbreviated days of the week (Mon, Tue, Wed, etc.) and the dates in a DDMM format. For En-US localizations, the Month should always come before the Day, so for Calendar week 14 of 2021, the dates should read 04.05, 04.06, 04.07, etc. This may be a different system for En-GB or En-AU localizations, I'm not entirely certain.

**To Reproduce**
1. Go to 'My Preferences' and ensure that your Language is set to English
2. Go to the 'Reporting' page
3. Notice that dates inside of the header row are improperly marked as DDMM, instead of MMDD.

**Additional context**
- Kimai version: 1.13 stable
- PHP version: 7.4.15
- Device: Ubuntu 18.04 Virtual Machine
- Browser: Chrome 89

**Comment by kevinpapst** [comment]
Agreed, missed that one. I will check the other report pages as well.

**Comment by urinal-cake** [comment]
I... didn't know there were other report pages until now. This is fantastic.

**Comment by kevinpapst** [comment]
Hm ... and that feedback from an IT guy. 
I guess this is rather bad feedback for my UI skills 😁 If you have any idea how it could be made clearer that there are more reports, please let me know!

**Comment by kevinpapst** [comment]
No offense taken, I see it as important feedback! Thats valuable input.
I know the monthly view is missing, will be added.

**Comment by kevinpapst** [comment]
@urinal-cake currently all English date formats use a dash `-` and not a point `.`. See this config:

```yaml
        en:
            date_time_type: 'yyyy-MM-dd HH:mm'
            date_type: 'yyyy-MM-dd'
            date: 'Y-m-d'
            date_time: 'm-d H:i'
            duration: '%%h:%%m h'
```

Why should it be a point here? Are the other formats wrong? Is there a difference between en_GB and en_U? Or is that a speciality of this short format?

**Comment by urinal-cake** [comment]
Hey @kevinpapst 
Not sure if this was closed for this reason, but the issue here isn't use of dashes vs dots (we use either in the States.) It's that the Reporting page shows 19.04, 20.04, 21.04, etc. instead of 04.19, 04.20, 04.21, etc.

**Comment by kevinpapst** [comment]
Screenshot made right now:
<img width="896" alt="Bildschirmfoto 2021-04-22 um 10 47 22" src="https://user-images.githubusercontent.com/533162/115685083-336a8300-a358-11eb-9984-628958ecd478.png">

**Comment by urinal-cake** [comment]
This is fantastic. I just logged into the Demo and verified this for myself.
Now I'm trying to understand _why_ I'm so excited about an update for a piece of software? I must not have a lot going on in my life right now. :)
