### ISSUE TITLE
Customer budget (time and $) lost after update

### ISSUE THREAD

**Issue by yroberttissot** [kevinpapst/kimai2#2506]
**Describe the bug**
After update from 1.12 to 1.13 of Kimai2, I noticed (2 days later) that the budget was again 0CHF and 0Hours. It was set to a value before the update.
The sum of hours done is not lost. Only the budgeted hours.

**To Reproduce**
1. Make update (done from SSH terminal) like descriped in documentation + add Expenses plugin
2. Click on 'Customer', open an existing customer with budget
3. See error: budget to 0.

**Logfile**

unfortunatelly not available

**Additional context**
 - Kimai version: 1.12 to 1.13
 - PHP version: 7.3

for me, it is not an issue, I expect no support for this, since I can quickfix it. It is for making the problem aware that I share it.

**Comment by kevinpapst** [comment]
I have no clue how that should have happened.
There was not even a database update between 1.10 and 1.14.
As budgets are used by many many Kimai users and I didn't hear about that problem before, I doubt that this is a general issue.
Anything I can do about it?

**Comment by yroberttissot** [comment]
mmh oh, I forgot to add that I also installed the Expenses plugin! (after the update). Maybe it's linked with that.

As said, no need for help here, nothing important lost.

**Comment by kevinpapst** [comment]
Thanks for the heads up! 

If someone else will find this, please post a comment and I will have a look.
But by now I have to admit: it is not reproducible, so I am closing this case.
