### ISSUE TITLE
Monthly Budget

### ISSUE THREAD

**Issue by FWITC** [kevinpapst/kimai2#2515]
I have a few Customers that have a yearly contract but have a monthy amount of hours.
Actually i create foreach month a new Project, it will be cool if can create one project an the budges could be tracked for one month by mont.

**Comment by HeinzWuert** [comment]
Have the same situation!
See #2095 and #2076

**Comment by kevinpapst** [comment]
Please vote for one or both of the linked issues, closing this here as duplicate,
