### ISSUE TITLE
Team Lead Timesheet Approval permission

### ISSUE THREAD

**Issue by captain-planet** [kevinpapst/kimai2#2524]
**Is your feature request related to a problem? Please describe.**
When  a user submits a timesheet, I would like a notification be sent to the 'team lead' of the 'project', whereby the team leader then has to 'approve' the timesheet before the 'administrator' can process the timesheet (and ultimately pay the user).

**Describe the solution you'd like**
I'd like a permission added called timesheet_approver and a drop-down entry/option in the 'timesheet' view (for users with the timesheet_approver permission) to 'Approve' or 'Reject' a timesheet.  If rejected the user will be notified and asked to amend, possibly with a note/reason.

**Describe alternatives you've considered**
N/A

**Screenshot**
N/A

**Comment by kevinpapst** [comment]
This feature request here is way too much for a single issue.

But there is an approval plugin existing, see:
https://www.kimai.org/store/katjaglass-approval-bundle.html

Closing
