### ISSUE TITLE
Tags in invoices

### ISSUE THREAD

**Issue by webaff** [kevinpapst/kimai2#2525]
**Is your feature request related to a problem? Please describe.**
I would like to print out tags on invoices (PDF/Twig).

**Describe the solution you'd like**
I would like to have a template variable, something like {{entry.tags}}, to render all tags assigned to a timesheet entry.
To be able to format the output of the tags (html, separator) would be even nicer.
I dont't necessarily need to see tags in kimai gui (invoice preview or change column visibility). It would be completely enough to have a variable for .pdf.twig templates.

**Comment by kevinpapst** [comment]
What kind of template are you using (PDF, HTML/Twig, Word)?

Try to add here:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Hydrator/InvoiceItemDefaultHydrator.php#L93
this code:
```php
        if ($item instanceof Timesheet) {
            $values = array_merge($values, [
                'entry.tags' => implode(', ', $item->getTagsAsArray())
            ]);
        }
```

**Comment by webaff** [comment]
Thanky for your super fast reply!
I'm using PDF templates (mPDF/Twig).
After adding your code, I tried {{ entry.tags }} inside of my template.pdf.twig but the variable stays empty.
What else is needed besides clearing the cache?

**Comment by kevinpapst** [comment]
Sorry, I double checked and was wrong. There is more to do to activate tags support in invoices.

Let's treat this as feature request for a future release (unless you are a developer and want to work on it, then I can lead you into the right direction).

**Comment by webaff** [comment]
Unfortunately, I am not a dev. Looking forward to see this feature soon, thanks.

**Comment by kevinpapst** [comment]
will be available in the next release

**Comment by webaff** [comment]
what a response time! thank you, @kevinpapst, have a nice weekend.
