### ISSUE TITLE
Multiline issue docx

### ISSUE THREAD

**Issue by cianiandreadev** [kevinpapst/kimai2#2530]
**Describe the bug**
I created a new docx template (using Apple Pages exported as docx) with the following 2 variables.
The rendered output contains double new lines.

**To Reproduce**
Create a new template with company details such as:
```
${template.address}

${template.contact}
```

In insert the values in the invoice as following:

```
My Company
5th Avenue
NYC
```

The invoice generated will be such:

```
My Company

5th Avenue

NYC
```
With "double" new lines for each row.

**Logfile**
No log file.

**Additional context**
 - Kimai version: Environment: prod – Version: 1.11.1 stable
 - PHP version: 7.4.2
 - Device: Linux 4898c8e33ed6 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64
 - Browser ---- Error on file. Not in browser.

**Comment by kevinpapst** [comment]
Problem is very likely in your template. The value is passed without any changes into the processor:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Hydrator/InvoiceModelDefaultHydrator.php#L50
Check the formats of the template line (eg. line height)

**Comment by kevinpapst** [comment]
No feedback, no problem. Closing
