### ISSUE TITLE
Search results in Projects do not display time-budgets

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2531]
**Describe the bug**
Search results in Projects do not display time-budgets

screenshot should display 50:00h for  _test project
![image](https://user-images.githubusercontent.com/45666972/115994199-45595980-a5d6-11eb-9080-4bfa64fbc773.png)

**Comment by kevinpapst** [comment]
Nope, there is no time budget column shown. So you will not see 50:00h

**Comment by HeinzWuert** [comment]
demo-branch
![image](https://user-images.githubusercontent.com/45666972/115995814-07abff00-a5dd-11eb-88db-fb924d25ed2e.png)

**Comment by kevinpapst** [comment]
Please use another environment. The one you use is not an official demo environment and can be weeks old, as there is no auto-install running.

**Comment by HeinzWuert** [comment]
now official branch
![image](https://user-images.githubusercontent.com/45666972/115995984-d54ed180-a5dd-11eb-922b-66c81fde8071.png)

**Comment by kevinpapst** [comment]
If I add a money budget the time budget is shown.
That info was crucial, because it worked for me all the time.

**Comment by HeinzWuert** [comment]
Nope, not in the demo and not in real in our working area.
created new _test2 and once more no time-budget is shown. 
the old _test is now displayed with the time-budget.
No consistent behavior?

**Comment by kevinpapst** [comment]
i do not see a test2, but if you add anything greater than 0.00 to money budget, the time budget is displayed in the list.
I already fixed the bug, so I am sure^^

**Comment by HeinzWuert** [comment]
![image](https://user-images.githubusercontent.com/45666972/115997467-7ab87400-a5e3-11eb-9280-8064da6cb100.png)

**Comment by HeinzWuert** [comment]
Added a money budget and time-budget is displayed.
Bug: No display of time-budget when money-budget is empty!
