### ISSUE TITLE
Update to v1.14.0 failed - unable to open database file

### ISSUE THREAD

**Issue by ralf1070** [kevinpapst/kimai2#2533]
When upgrading von Version 1.13.0 to 1.14.0 "./bin/console kimai:update" reports

  [ERROR] Failed to validate database: An exception occurred in driver:          
  SQLSTATE[HY000] [14] unable to open database file

The installation is based on a sqlite database.

**To Reproduce**
  rsync -aHAXv --delete kimai2-1.13.0/ kimai2-1.14.0
  cd kimai2-1.14.0/
  git fetch --tags
  git checkout 1.14
  sudo -u wwwrun bash
  composer install --no-dev --optimize-autoloader
  bin/console kimai:update -vvv

**Result:**
  wwwrun@kimai> bin/console kimai:update -vvv
  Kimai updates running ...
  [ERROR] Failed to validate database: An exception occurred in driver:          
         SQLSTATE[HY000] [14] unable to open database file                      
  07:15:19 DEBUG     [console] Command "kimai:update -vvv" exited with code "8"
  [
    "command" => "kimai:update -vvv",
    "code" => 8
  ]
  wwwrun@kimai> ls -la var/data/
  insgesamt 8124
  drwxrwxr-x 3 wwwrun wwwrun    4096 26. Apr 09:12 ./
  drwxrwxr-x 8 wwwrun wwwrun    4096 26. Nov 2019  ../
  -rw-rw-r-- 1 root   wwwrun       0 29. Aug 2019  .gitkeep
  drwxr-xr-x 2 wwwrun www       4096  8. Feb 11:14 invoices/
  -rw-rw-r-- 1 wwwrun wwwrun 8306688 26. Apr 09:10 kimai.sqlite

**Additional context**
 - Kimai version: Transition - 1.13.0 -> 1.14.0
 - PHP version: 7.4.6
 - Device: OpenSuSE Leap 15.2

**Comment by kevinpapst** [comment]
I am sorry to disappoint you: https://www.kimai.org/blog/2021/sqlite-and-ftp-support-removed/

**Comment by ralf1070** [comment]
Ah - sorry. I didn't got the sqlite-will-be-removed notification (or at least I missed it ...).

Migration done. Update works.

Thanks a lot for your time. Best regards.

**Comment by kevinpapst** [comment]
Wow, that was fast 👍 
Thanks for not complaining about the silent removal of SQLite, but it really caused too much unpaid work for me.

**Comment by ralf1070** [comment]
Wat mutt, dat mutt ;)
