### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#2534]
Hi,

after updating Kimai to 1.13 the calendar view is broken. How can I fix this?

<img width="667" alt="Bildschirmfoto 2021-04-26 um 15 38 17" src="https://user-images.githubusercontent.com/42935152/116092016-ba479480-a6a5-11eb-8ba8-6381b801d8a0.png">

**Comment by kevinpapst** [comment]
Something went wrong with your update (docker?).
Check your browsers JS and network console.

**Comment by blochwitz** [comment]
Hi Kevin,

thanks for your reply. I made a clean installation and compilation of version 1.13 and the calendar view is already broken. Also i checked the JS and network console but didn't found any error for the calendar view...

**Comment by kevinpapst** [comment]
I can assure you that something else must be wrong. 
Kimai 1.13 runs on hundreds of platforms without that problem, same goes for 1.14 

Are we talking about 1.13 or 1.14 (latest release)?

**Comment by kevinpapst** [comment]
No feedback, no problem I assume
