### ISSUE TITLE
timesheet form doesn't immediatly focus search box in combobox

### ISSUE THREAD

**Issue by noyez** [kevinpapst/kimai2#2535]
**Describe the bug**
When adding a new timesheet entry (either from calendar or timesheet list) view, the search box is not selected by default when clicking the drop-down menu. The result is, to fill out the form the user must click in the search box (or select an item from the list). It is not possible to fill out the form without clicking several times to select the searchbox in each dropdown. This is the current behavior i see at https://demo-plugins.kimai.org/ at the time of this issue creation. 

However the code running at https://demo-branch.kimai.org/en/calendar/ (at the time of this issue creation) does have the desired behavior. (I have no idea how i found that instance). Note the screenshot below, when the combo-box is opened (by click or spacebar), the search box is immediately focused and the user can just start typing to find the desired entry.
<img width="885" alt="image" src="https://user-images.githubusercontent.com/1292949/116093204-7be5b180-a674-11eb-9a6e-717bc2391443.png">

**To Reproduce**
1. Go to Calendar or Timesheet
2. Click on '+' or Add Entry
3. Click on Client, combobox will appear and search box is not selected. 

**Additional context**
 - Kimai version: 1.14
 - PHP version: 7.4
 - Device: Desktop MacOs
 - Browser: Firefox and Safari

**Comment by kevinpapst** [comment]
Interesting finding, thanks for posting!
I cannot find the reason, seems some updated Javascript library causes this problem. 
I will investigate and include it for a 1.14.1 release.

**Comment by kevinpapst** [comment]
Okay, jQuery 3.6 raises a bug in Select2, see https://github.com/select2/select2/issues/5993
Working around that problem in #2532
