### ISSUE TITLE
My Times: more choices in eye function

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2554]
**Is your feature request related to a problem? Please describe.**
Users would like to see start- and endtime in My Times. Now only duration is available.

**Comment by kevinpapst** [comment]
Hiding start and end is a feature which is ONLY true if you changed the time tracking mode at System preferences.

**Comment by HeinzWuert** [comment]
But would be nice to see in the listing!

**Comment by kevinpapst** [comment]
If you use a time tracking mode that only tracks duration, you will not see start and end.

**Comment by HeinzWuert** [comment]
Understood, but why deny display of start / endtime?
It's only an optional information.

**Comment by kevinpapst** [comment]
For you. And for other companies it is an information that needs to be hidden.
There is no perfect software
