### ISSUE TITLE
select an invoice template as a default on a per customer basis

### ISSUE THREAD

**Issue by jamescraig-engineer** [kevinpapst/kimai2#2560]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request.

**Describe the solution you'd like**
I'd like to have the ability to define a default invoice template on a per customer basis. I have different terms (payment, delivery etc) with different customers, so most end up having their own invoice template. It would be great to be able to set this on each customer, so that mistakes aren't made when invoices are generated.

**Describe alternatives you've considered**
None.

**Screenshot**
Add a "Default Invoice Template" drop-down box at > en/admin/customer/ -> Edit

**Comment by HeinzWuert** [comment]
in this context:
We already have a special solution which type of invoice should apply to certain users.
This individual solution could be replaced at the same time with this FR by assigning a specific invoice type to a user group.

**Comment by fredyb** [comment]
That is a very great idea. For us it would be ideal if this supported at project level.

**Comment by kevinpapst** [comment]
Added customer default invoice template to the next major version, see #2902
You can also define a custom text per customer, which is available as variable in the invoice template:
<img width="689" alt="Bildschirmfoto 2022-08-02 um 00 46 58" src="https://user-images.githubusercontent.com/533162/182258141-afbb1f59-3cfb-4c6c-9c30-4f66d3bc8e4f.png">

In the invoice screen, you can still change the template and invoice date:
<img width="375" alt="Bildschirmfoto 2022-08-02 um 00 48 06" src="https://user-images.githubusercontent.com/533162/182258258-516c3f01-3e33-4196-9485-05641fbe3d2b.png">
