### ISSUE TITLE
Open timesheet after copying

### ISSUE THREAD

**Issue by kosli** [kevinpapst/kimai2#2563]
Similiar to #2310 but independent of the allowance of overlapping records.

I assume the use case for using the copy function of a timesheet entry is to edit it right after copying? 
Currently if you click on "create copy" it creates a copy -> Is there any use case to duplicate it and NOT edit it afterwards? 
It gets cumbersome if you have a long list of timesheet entries and you want to re-use one of them. I know i could use the start again function, but if just want to create a copy and enter a specific start/stop time, it would be much more convenient with the copy function.

**Comment by kevinpapst** [comment]
was already on my list for 1.15 and is an exact duplicate of #2310 

Next time you can simply vote for the other issue with a 👍 one the initial posting, like I did now hear in yours.

**Comment by kosli** [comment]
Thanks @kevinpapst  and @HeinzWuert 
It is not exactly the same and I thought it may be easier to implement than in #2310 -> if overlapping records are allowed, the copy can be created as-is (= already saved in the DB) and just move forward to the edit step  (vs. creating a "temporary" copy for editing).

But fine for me both ways ;-) Closing this issue. Thanks all.

**Comment by kevinpapst** [comment]
Ah, I didn't notice this difference. I added the function now like this: clicking the "create copy" action opens the normal create dialog with all values pre-filled. If this form is not saved the item will not be copied. 

And it can now be used when "deny overlapping records" is active, which is the preferred solution.
