### ISSUE TITLE
API add patch to /api/config/timesheet 

### ISSUE THREAD

**Issue by GoProAndy** [kevinpapst/kimai2#2571]
Hi Kevin,

i run a API script where i duplicate timesheets and i need to set for the runtime 
isAllowOverlapping = true

and afterwards again back to false.

can you please add an apli call for that?

thanks
Andreas

**Comment by kevinpapst** [comment]
No, sorry, but API routes for system configuration will not be added. 
There are always workarounds possible when you create your own plugin.
