### ISSUE TITLE
Add option to search by exclude tag

### ISSUE THREAD

**Issue by RokkuCode** [kevinpapst/kimai2#2574]
**Is your feature request related to a problem? Please describe.**
It is not possible to filter by exclusion of a tag. So i request to add the option to exclude tags in filter.

**Describe the solution you'd like**
Show all entries without tag "test". Select the search bar, select a tag and an option to exclude the tag.

**Screenshot**
I have no idea how to design this well.

**Comment by kevinpapst** [comment]
> I have no idea how to design this well.

Me neither 😀

**Comment by kevinpapst** [comment]
If anyone is interested n the future please add a comment. Closing for now.
