### ISSUE TITLE
Reassigning activity to other customer/project does not adapt timesheet entries

### ISSUE THREAD

**Issue by kosli** [kevinpapst/kimai2#2576]
I had to reassign certain activities to a new customer & project. 
I have expected that the associated timesheet entries will be "pointing" to the same customer & project as the activity does. Unfortunately this is not the case. After looking at the database, I see that a timesheet entry is associated with an activity AND a project. This explains the behavior that I saw after reassigning the activity. Is this the expected behavior? 
What is the proper way to reassign an activity (including all timesheets) to a new project?

**Comment by kevinpapst** [comment]
Just tested it and you are right: there is a problem.
But I am not sure about the consequences.
Re-assigning timesheets might work for you, but if you already have exported or invoiced some of them, this would change the history. Instead I think it shouldn't be possible to change the project for an activity / the customer of a project if they have assigned timesheets.

**Comment by kosli** [comment]
Thanks @kevinpapst for confirming it.
FYI, I have updated the timesheets straight in the DB so that they point to the right project_id. Seems to be fine.
Yes, either not allowing to "move" projects & activities with timesheets, or otherwise have the timesheets reassigned automatically too. 
Another option may be to have the activity_id only set for timesheets where there is no project associated to the activity, but this would have a bigger impact and require many more changes due to the design change.

**Comment by kosli** [comment]
@kevinpapst just an idea: a function in the system/doctor area that validates the timesheet entries would be nice. e.g. if the acitvity_id matches the right project_id.
