### ISSUE TITLE
export xls error: could not open temporary file

### ISSUE THREAD

**Issue by ateliernz** [kevinpapst/kimai2#2578]
**Describe**
exporting xlsx and csv does fail.

**Reproduce**

1. Go to export section
2. Filter on any customer and/or project and/or activity
3. tick button CSV or Excel
4. new screen with error: " Something is wrong - A critical error occurred, please try again. You may have found a software problem, please contact your administrator if the problem persists."
5. Log: [2021-05-20 17:15:01] request.CRITICAL: Uncaught PHP Exception Exception: "Could not open temporary file" at /volume1/web/kimai2/src/Export/Base/XlsxRenderer.php line 40 {"exception":"[object] (Exception(code: 0): Could not open temporary file at /volume1/web/kimai2/src/Export/Base/XlsxRenderer.php:40)"} []

**Expected**

1. Go to export section
2. Filter on any customer and/or project and/or activity
3. tick button CSV or Excel
4. download of csv or excel file with timesheet records

**Tried**

- update to version 1.14.1
- reload cache
- executed permission commands in kimai directory

Server is Synology NAS, discovered error in Kimai2 version 1.13

**Comment by kevinpapst** [comment]
That is a problem of your local environment. 
Check the temporary directory that is used by PHP. 
Kimai needs write access for it.

**Comment by ateliernz** [comment]
Grazzi, i was looking at the permissions on the kimai directory, but forgot that i had changed the temporary directory of php..
