### ISSUE TITLE
Wrong version number for 1.14.3

### ISSUE THREAD

**Issue by GaneshKandu** [kevinpapst/kimai2#2582]
Hi,

I am Trying to install Kimai 1.14.3 ( downloaded from [Release 1.14.3 · kevinpapst/kimai2](https://github.com/kevinpapst/kimai2/releases/tag/1.14.3) )
but when i visit **About Kimai** it shows Kimai 1.14.1  Installed.

![image](https://user-images.githubusercontent.com/12833130/119217219-55415c00-baf6-11eb-8a1e-2e6f4779bda4.png)

**Comment by kevinpapst** [comment]
Yeah, I forgot to bump the version number  😁 
See https://github.com/kevinpapst/kimai2/blob/master/src/Constants.php#L20
Will bump it for the next release

**Comment by chriscroome** [comment]
Thanks for all the work on this project @kevinpapst, it is greatly appreciated!

Incidently it would be good if the format of the version output command line didn't change again (I'm splitting it on spaces and have to [check to work out which bit has the version number](https://git.coop/webarch/kimai/-/blob/9d2d4da75d617f388e77471a837e48bfdadcf403/tasks/version.yml)), for example these are some recent outputs from `bin/console --no-ansi -n kimai:version`:

```
Kimai 2 - 1.12 stable (Ayumi) by Kevin Papst and contributors.
Kimai - 1.14 stable (Ayumi) by Kevin Papst and contributors.
Kimai 1.14.1 by Kevin Papst and contributors.
```

**Comment by kevinpapst** [comment]
@chriscroome `bin/console --no-ansi -n kimai:version --short`

**Comment by chriscroome** [comment]
Thanks and sorry for not realising there was a `--short` option :roll_eyes:
