### ISSUE TITLE
Stuck at 1.14.1, cannot update to 1.14.2 or 1.14.3

### ISSUE THREAD

**Issue by RayCulp** [kevinpapst/kimai2#2590]
Can't update past 1.14.1 with Git. All commands execute without apparent errors, but it stays at 1.14.1. Tried `git reset --hard` , but it doesn't help. Any idea what the problem might be?

**Comment by kevinpapst** [comment]
Yeah, I forgot to bump the version number in the release. If git says 1.14.3 all is fine
