### ISSUE TITLE
Not applicable tax case 

### ISSUE THREAD

**Issue by dkstiler** [kevinpapst/kimai2#2592]
**Statement of the feature request**
In Europe there is a non applicable vat for invoices that are inside the agreement for 
VAT on digital services (MOSS scheme) there is no need to apply taxes or in some cases the vat applies to be paid by the buyer of the services in his country
 
**Proposed solution**
Would be amazing if there was a checkbox of sort for that scenario, when its ticked it will grey out the tax field and not calculate the tax  or even show on the tax field non applicable. My accountant asked me to do this and my customers accountant as well
There is no need to tinker with the existing way of calculation since we need to leave the 0% tax as an option due to the fact that exists a use case in Europe for that as well.
Also there maybe a way to incorporate the issue #1849 in a similar manner

**Alternatives**
For now im using the HTML feature of the invoices and using and external script to edit the field of tax, while  at the same time setup of the tax as zero so it wont calculate it. Or even use the word generated invoice and fix what i need.

**Screenshots**
A screen shot of the idea proposed would be like:
![image](https://user-images.githubusercontent.com/5874499/120252357-f8c80480-c28c-11eb-9a7c-36ad90eab58f.png)

And it should generate something similar to this on the invoice: 
![image](https://user-images.githubusercontent.com/5874499/120252629-be129c00-c28d-11eb-8c85-ad73cde39d45.png)

**Comment by kevinpapst** [comment]
Sounds to me as if you are mixing MOSS with Reverse charge.

I am using Kimai for Reverse charge invoices since years without any problem. 
Just set tax to 0% and add a sentence:

<img width="470" alt="Bildschirmfoto 2021-06-01 um 12 29 29" src="https://user-images.githubusercontent.com/533162/120309100-1e78fc00-c2d5-11eb-9f39-d2d347cbb618.png">

If you think that must be changed, you can create a new invoice template.

**Comment by dkstiler** [comment]
Yes you are right at start that was the setup i created but the customer accountant asked specifically for the text stated above. The business plans are applied to both cases reverse charge and moss. I would like to help and even contribute to what is needed to fix and even with the secondary tax since in my country i need to regulate the amount for my tax rates beside regular vat. Where do i need to look at the code, to actually make some things and make a PR so we can elaborate on it :)

**Comment by kevinpapst** [comment]
Understand. Depends on the importance of that customer. There is always a choice to say "No", even to customers 😁
I have checked so many lawyer texts and invoice templates for my business needs and none ever had that text in there.

A hard-coded second tax is nothing I would add. Kimai is not and invoicing/ERP system at the end.
Simple invoicing cases work, more complex scenarios need to be managed differently.
There are so many different strange tax rules out there in the world, that I don't know how that should be added properly.

The invoicing system can be extended in multiple ways, if you don't want to apply the second taxt inside the template.
But please start by reading the documentation about invoices. 
I assume you can do everything in your own invoice template.

**Comment by dkstiler** [comment]
Well that's true! Ok well then you can close this feature request if you wish i will use an external invoicing/erp system to be more flexible to needs of some customers. as for help well let me know if there is something to look at and help in my free time :)

**Comment by kevinpapst** [comment]
> if you wish i will use an external invoicing/erp system

I never said that. I just said that Kimai can't handle every possible use-case. Its still a time-tracker with invoice add-on 😁 

> I assume you can do everything in your own invoice template.

I do not understand why you ignore my repeated answer. 
Copy & paste this file: https://github.com/kevinpapst/kimai2/blob/master/templates/invoice/renderer/default-pdf.pdf.twig
and adjust that line:
https://github.com/kevinpapst/kimai2/blob/4859ac8ecbe25d14800b5464dee7a1a9f5e5b129/templates/invoice/renderer/default-pdf.pdf.twig#L138

**Comment by kevinpapst** [comment]
And hee the personal link to the docs: https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document
