### ISSUE TITLE
Default option of the "Billable" attribute for each defined activity

### ISSUE THREAD

**Issue by de-sec** [kevinpapst/kimai2#2594]
Hey everyone, 

we would like to request a feature improvement regarding the setup of activities in Kimai2 to improve the time recording in general and analysis during the billing process by adding an option for the default of the "billable" attribute of each defined activitiy. 

**Describe the solution you'd like**
First: a Checkbox to set the default value of the Billable attribute for each activity within the activities administration (see appended screenshot). 
Second: If an activity is set as non billable within the activities administration each new time record should be set as non billable aswell. 

**Describe alternatives you've considered**
no alternatives found, except a manual uncheck of the box for each recorded activity

**Screenshot**
![image](https://user-images.githubusercontent.com/60732155/120439838-458e0700-c383-11eb-8e8b-3a1c6a624bdd.png)

**Comment by kevinpapst** [comment]
That is 90% what I had in mind. 👍 Select box should be on by default.

**Comment by de-sec** [comment]
> That is 90% what I had in mind. 👍 Select box should be on by default.

aggree - the screenshot should only express the additional box within the activity creation form :-)

**Comment by devoeger** [comment]
Can we add the ability to disable this checkbox completely (all work is billable) or prevent users from changing the value set for the activity or project?

**Comment by cloggg** [comment]
Is the feature mentioned by devoeger already implemented? (possibility to disable 'billable' checkbox foor 'add timesheet' action and use the default value set in the Activity?

**Comment by SixStrings89** [comment]
@kevinpapst Hi Kevin
We need this feature in our environment and would like to develop it and create a PR for this.
In your business-case, we will determine the billable-option for a time-entry with the following workflow (in this given sequence):

- Is the activity marked as billable? -> Record will marked as billable (end)
- Are records by default billable? -> Record will marked as billable (end)
- If none of this cases matches? -> Record will not marked as billable (end)

Does this correspond to your ideas?

**Comment by kevinpapst** [comment]
@SixStrings89 sounds good for a start.
Some quick thoughts:
- by default entries need to be billable

The state for activity should probably not be a pure boolean.
It needs to store the infos `default behavior`, `billable`, `not billable`.

"activity marked as billable" and "records by default not billable" => billable
"activity marked as not billable" and "records by default billable" => not billable
"activity marked as default behavior" and "records by default not billable" => not billable
"activity marked as default behavior" and "records by default billable" => billable

Later on I would like to extend that for project and customer as well, but starting with the activity is perfect!

What about the billable field in the timesheet? 
Should that be hidden for new records? 
Or should it also be a 3-state field and by default it is set to "default behavior" which means => calculate the state.
Should it be hidden for normal users / protected by a permission?

**Comment by SixStrings89** [comment]
@kevinpapst Thank you for your feedback.
Adding your behavior makes a lot sense for me, so we would change the type to a numeric example for instance.
We well implement it as you have described.

We had also some thoughts about the next steps and may add it also to the project. For this reason we have to discuss the behavior and the state sequence first.

For your other questions, we have also some ideas:
What about the billable field in the timesheet?

> Should that be hidden for new records?
> Or should it also be a 3-state field and by default it is set to "default behavior" which means => calculate the state.
> Should it be hidden for normal users / protected by a permission?

Our idea was to add a permission flag for overriding the billable-field in the timesheet. If it's set, you see the field and if not, you wont see it. In my opinion, we can show the calculated state on the UI as a boolean (at this time, it should make no difference if the flag is enabled by default or by activity).

I will check it with my team tomorrow, maybe there are some additional ideas :)

**Comment by kevinpapst** [comment]
Yap sounds very good 👍 

Regarding the permission: please use `edit_export_other_timesheet` as template. You should be able to find all places where this needs to be checked when searching for `include_exported` or even `'include_exported' => $this->isGranted('edit_export', $timesheet)`.

Regarding the state: please check whether a nullable boolean field or a tinyint makes more sense.

Regarding the  sequence: I think we can or should use the [same flow that is used to calculate the hourly rate](https://www.kimai.org/documentation/rates.html#rate-calculation).
