### ISSUE TITLE
Calendar is cut off at the bottom of the browser

### ISSUE THREAD

**Issue by bykof** [kevinpapst/kimai2#2609]
**Describe the bug**
The calendar is cut off and only displayed 3/4, so that it's impossible to press the "Select" button to select the datetime.

See screenshot:
<img width="513" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/5264141/121511635-20d00a00-c9e9-11eb-8bea-3596da41e0e4.png">

**To Reproduce**
1. Go to Project
2. Click on create a Project
3. Select "Project start"

**Additional context**
 - Kimai version: 1.14.1
 - PHP version: 7.4.15
 - Device: [Macbook Pro 15"]
 - Browser [Firefox 89]

**Comment by kevinpapst** [comment]
Yep, true on small screens. Thanks for the report

**Comment by kevinpapst** [comment]
That caused a more serious bug on mobile phones, so I am likely going to revert it.
