### ISSUE TITLE
All files exported as kimai_report.pdf, and not taking into account documentation

### ISSUE THREAD

**Issue by llabat-fr** [kevinpapst/kimai2#2615]
Hello,

I'm trying to properly name the exported PDF Files, using a custom template (running 1.14.1, even if I synched with 1.14.3 through git - upgrade procedure)

I started from the template  pdf-layout.html.twig

Added the following lines on top (as per the documentation : https://www.kimai.org/documentation/export.html)

{%- set customer = query.customers|length == 1 ? query.customers.0 : null -%}
{%- set project = query.projects|length == 1 ? query.projects.0 : null -%}
{%- set filename = 'TimeReport_' ~ (customer is not null ? customer.name|replace({' ': '-'}) ~ '_' : '') ~ (project is not null ? project.name|replace({' ': '-'}) ~ '_' : '') ~ query.begin|date_format('Y-m') -%}
set option = pdfContext.setOption('filename', filename) -%}

Report is always called kimai_report.pdf, and does not account for the code above. 

I believe we need to pass that "option" somwhere, but nothing in the export.html page related to that.

**Comment by kevinpapst** [comment]
This is working at several customs, so I doubt there is a problem, but who knows ... 
Please try it  in the demo and let me know what happens.

**Comment by llabat-fr** [comment]
You're right, sorry about that.
