### ISSUE TITLE
Bug Context menu on entry is not properly shown on screen

### ISSUE THREAD

**Issue by Filechaser** [kevinpapst/kimai2#2616]
The Timesheets are not completly shown and there is no scrollbar or anything to access them, if the window is to small (Displaysize 13" Mac) 
Image follows

The same goes for the contextmenu. Always no matter the screensize.
If you want to delete the last entry of a timesheet and it is at the bottom of a page, the contextmenu gets cut off.
Buttons like delete are no longer visible.
<img width="1227" alt="Bildschirmfoto 2021-06-16 um 11 26 40" src="https://user-images.githubusercontent.com/13608679/122194775-076e0880-ce96-11eb-8920-f4b2f4ecdacb.png">

In the "Eintrag bearbeiten"-window, there is no "Delete"-Button. Entries cannot be deleted that way either.
I hope this issue can be fixed.

I worked around it by lowering the zoom in Microsoft edge on small devices. 
Unfortunately I cannot always use that, as I have bad eyesight.

Second bug i work around by searching for the specific entry, so it appears at the top of the page.

**Comment by kevinpapst** [comment]
Check demo, the dropdown was fixed long ago.
The smaller the screen, the less infos can be displayed: remove columns.
Install the CustomCSSBundle and activate the "responsive tables" rule to be able to swipe left to right.

**Comment by Filechaser** [comment]
To answer you as fast as possible I booted the plugin demo edition on your website and added the CSS Responsive Tables. The Table is now shown but the contextmenu is cut off by the data-row.
<img width="1222" alt="Bildschirmfoto 2021-06-16 um 12 02 29" src="https://user-images.githubusercontent.com/13608679/122209797-3770d800-cea5-11eb-8ac5-df6adc34e8e8.png">

**Comment by Filechaser** [comment]
oh i am sorry
The newest version of kimai has responsive already enabled
So by enabling custom css I basically destroyed an already working version.

Case closed
In the future I promise to update before opening a bug report.

I am sorry

**Comment by kevinpapst** [comment]
The dropdown definitely works here, but responsiveness for tables is not activated by default. 

On Mac it works great, because you can simply swipe to the side, but I am not sure how that works with Linux / Windows and if it has other flaws. Thats why "responsive tables" are not active by default.
