### ISSUE TITLE
Timesheet uncheck billable by default

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#2625]
### Discussed in https://github.com/kevinpapst/kimai2/discussions/2624

<div type='discussions-op-text'>

<sup>Originally posted by **cfshawnmaholick** June 25, 2021</sup>

![Screenshot 2021-06-25 at 15 44 16](https://user-images.githubusercontent.com/36766765/123434172-7bae5780-d5cc-11eb-85e4-16146890d363.png)
Hello, is there a way to configure the billable checkbox to not be checked by default?

Beside my main question:
Is there a way by config to remove optional fields from the form?

Thanks,
Shawn</div>

**Comment by Silver-Golden** [comment]
o/

Something else to think of is restarting an existing time entry to maintain its billable status.  
So if ye start a task, mark it as non billable, end it, then later resume it it should remain non billable.
