### ISSUE TITLE
Official support for running the app in a subdirectory

### ISSUE THREAD

**Issue by Verfuchst** [kevinpapst/kimai2#2629]
**Is your feature request related to a problem? Please describe.**
The current way to make the app running in a subdirectory is just a [workaround](https://www.kimai.org/documentation/webserver-configuration.html#with-subdirectory-usage) and can end badly see https://github.com/kevinpapst/kimai2/issues/1915.

**Describe the solution you'd like**
It would be awesome if a official support would be added to run the app in a subdirectory without problems.

**Comment by kevinpapst** [comment]
1. Did you try it? What didn't work? https://www.kimai.org/documentation/webserver-configuration.html#with-subdirectory-usage

2. "Official support" won't be added (unless paid). I cannot care about everyones hosting issues.
