### ISSUE TITLE
DragAndDrop 10 RecentActivities configurable

### ISSUE THREAD

**Issue by typo3rel** [kevinpapst/kimai2#2646]
Hi,
can you please make the number of 10 recent activities configurable in CalendarController:getDragAndDropResources:
```
$data = $repository->getRecentActivities(
                $this->getUser(),
                $this->getDateTimeFactory()->createDateTime('-1 year'),
                10
            );
```

**Comment by kevinpapst** [comment]
If you (or someone else who reads this)  want to help: https://github.com/kevinpapst/kimai2/pull/2291
