### ISSUE TITLE
Reports are limited to current month only

### ISSUE THREAD

**Issue by petecooper** [kevinpapst/kimai2#2647]
**Describe the bug**
Reports are limited to current month only. Selected timesheets older than current week are not included in reports.

**To Reproduce**
1. Create activity in current month.
2. Create activity in previous month.
3. Select both activities via checkbox.

![Screenshot 2021-07-05 at 15 21 11](https://user-images.githubusercontent.com/226578/124486628-b327bb80-dda5-11eb-93e6-58e696981a7c.png)

4. Create report (I used Print for this issue), note only one activity is included in the report.

![Screenshot 2021-07-05 at 15 21 21](https://user-images.githubusercontent.com/226578/124486636-b622ac00-dda5-11eb-90be-3b88599ce2dd.png)

**Logfile**

Not applicable – I used the demo site ("Missing logfile" in Doctor).

**Additional context**
 - Kimai version: 1.14.1
 - PHP version: 7.3.28-2+ubuntu18.04.1+deb.sury.org+1
 - Device: macOS 11.14.6
 - Browser: Safari 14.1.1

**Comment by kevinpapst** [comment]
The export on your "my timesheets" page will export the current month only, unless you filtered something else.
You need to use the "search2 dialog to filter explicit data and then hit export.

**Comment by petecooper** [comment]
Ah! Yes! Thank you @kevinpapst – now it makes sense.

**Comment by kevinpapst** [comment]
I know its not good communicated in the UI, its on my roadmap to fix that ... since a very long time. 
Posts like yours always remind me of that 😁
