### ISSUE TITLE
Version reporting mismatch on upgrade: `1.14.1` or `1.14.3`?

### ISSUE THREAD

**Issue by petecooper** [kevinpapst/kimai2#2648]
**Describe the bug**
I have run the upgrade script as per the documentation, and provided `1.14.3` as the target version for the upgrade. The upgrade completes with a notification that I am updated to `1.14.1`…but I was expecting `1.14.3`.

![Screenshot 2021-07-05 at 18 18 08](https://user-images.githubusercontent.com/226578/124503661-eaa26200-ddbd-11eb-8eff-1c4ccb83eda4.png)

**To Reproduce**

This is my 'belt and braces' upgrade script, which completes without errors:

```
kimai_version="1.14.3" \
&& cd ./kimai2/ \
&& git fetch --tags \
&& git checkout $kimai_version \
&& sudo chown -R www-data:www-data . \
&& sudo chmod -R g+r . \
&& sudo chmod -R g+rw var/ \
&& sudo chmod -R g+rw public/avatars/ \
&& php ~/composer.phar install --no-dev --optimize-autoloader \
&& php bin/console kimai:update \
&& sudo chown -R www-data:www-data . \
&& sudo chmod -R g+r . \
&& sudo chmod -R g+rw var/ \
&& sudo chmod -R g+rw public/avatars/
```

Thank you in advance for any advice.

**Logfile**
```
Empty logfile
```

**Additional context**
 - Kimai version: 1.14
 - PHP version: 7.4.21
 - Composer version: 2.0.9

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/issues/2590
https://github.com/kevinpapst/kimai2/issues/2582

**Comment by petecooper** [comment]
Thank you @kevinpapst - I did search but did not find those issues.

**Comment by kevinpapst** [comment]
My bad... the more people post, the less likely I will forget to bump the version number the next time hahaha

**Comment by petecooper** [comment]
I promise I will not become your personal assistant for releases…

Thank you again for your time and assistance!
