### ISSUE TITLE
Tag colour defaults to grey on editing

### ISSUE THREAD

**Issue by petecooper** [kevinpapst/kimai2#2649]
**Describe the bug**
If a tag has the default colour (e.g. green), editing it via Tags -> Edit will change the colour to grey. If the tag does a non-default colour, it appears to retain its colour in the Tags -> Edit workflow.

I have attached a safe-for-work screencast, no audio. I have also searched open issues and I cannot find this.

**To Reproduce**
1. Create one or more tags with default colour.
2. Visit Tags, then Edit a tag.
3. Note colour has changed to grey.

https://user-images.githubusercontent.com/226578/124562249-b5862600-de36-11eb-92c3-16898d17a1cb.mp4

**Logfile**

"Missing logfile" since I used demo site.

**Additional context**
 - Kimai version: 1.14.3
 - PHP version: 7.3
 - Device: macOS 10.14.6
 - Browser Safari 14.1

**Comment by kevinpapst** [comment]
Hm, I have already changed that a bit in https://demo-branch.kimai.org/en/admin/tags/ (Login with susan_super and kitten).

But I guess the real bug is that the fallback color for tags is green, should be the default grey instead.
Never thought about it before, because I don't use them.

**Comment by petecooper** [comment]
Thank you @kevinpapst 👍
