### ISSUE TITLE
Contradicting week number in Dashborad and Calendar

### ISSUE THREAD

**Issue by k-apc** [kevinpapst/kimai2#2652]
**Describe the bug**
The week number at https://example.com/en/dashboard/ differs from the one at https://exmple.com/en/calendar/

On July 6th, dashboard says it's week 27th whereas calendar says it's 28th.
![Captura de pantalla de 2021-07-06 14-04-53](https://user-images.githubusercontent.com/69361419/124654138-cdc06a00-de63-11eb-8762-8fc42cbfe203.png)
![Captura de pantalla de 2021-07-06 14-04-30](https://user-images.githubusercontent.com/69361419/124654142-ce590080-de63-11eb-89ef-f5efb5a524df.png)

**Additional context**
 - Kimai version:  1.12 stable (Ayumi) 
 - PHP version: 7.3
 - Device: Debian Buster (10)
 - Browser Firefox 88.0.1

**Comment by kevinpapst** [comment]
1.12 is old... does the same happen on the demo for you?

**Comment by k-apc** [comment]
I was not aware of the demo. it's fixed there. Thanks! Closing!
