### ISSUE TITLE
Adding entries in the past is cumbersome

### ISSUE THREAD

**Issue by alqu** [kevinpapst/kimai2#2653]
**Describe the bug**
When adding a new entry manually that is in the past, then the end time has always to be adjusted, since it defaults to "today, 0:00"
Instead it should display something like "dateTime of 'from'-field + default duration, e.g. 1 hour", which is also less error prone since it prevents adding overlapping time records.

**To Reproduce**
1. Go to Administration / Timesheets
2. Click on "+", "create"
3. Fill in some date in the past in the "from" field
4. click on "To" DateTimePicker
3. See error 
![Kimai - New Entry - EndDate](https://user-images.githubusercontent.com/12250845/124720159-28130680-df08-11eb-966c-71ec59b1ddbd.png)

**Logfile**
- no Logfile, since it is pure frontend.

**Additional context**
 - Kimai version: 1.14.1
 - PHP version: 7.2.24
 - Device: CentOS Linux release 8.4.2105
 - Browser Chrome 91, Safari 14, Firefox 89.0

**Comment by kevinpapst** [comment]
Why don't you configure the duration dropdown.
Then, when entering a time: enter a start and then select a duration? This will auto calculate the end.

**Comment by alqu** [comment]
> Why don't you configure the duration dropdown.
> Then, when entering a time: enter a start and then select a duration? This will auto calculate the end.

Interesting solution. I will discuss this internally.

**Comment by kevinpapst** [comment]
And I will look at the your problem as well, because that is definitely a bad user experience as well.

**Comment by kevinpapst** [comment]
The next major version has a rewritten interface for start and end:
<img width="749" alt="Bildschirmfoto 2022-07-17 um 14 29 41" src="https://user-images.githubusercontent.com/533162/179398364-241b0416-ff3d-4366-a90a-7a8ad70b32c3.png">

So only one date field and two time fields (+ the duration input).
I am closing here, as this is solved for the next version. 

If you want to help testing these (and other) changes, find more information in https://github.com/kevinpapst/kimai2/pull/2902
