### ISSUE TITLE
Windows 10 detecting Kimai 1.14.3 zip package as a Trojan script

### ISSUE THREAD

**Issue by prbt2016** [kevinpapst/kimai2#2654]
Hello @kevinpapst,

I was trying to download the latest version of Kimai i.e 1.14.3 on Windows from this Github link : 

https://github.com/kevinpapst/kimai2/archive/1.14.3.zip

However Windows Virus and threat protection on Windows 10 detects it as a Trojan script.

Could you please look into this ?.

**Comment by kevinpapst** [comment]
No. I don't have Windows. If you think this is true, I need more infos.

**Comment by prbt2016** [comment]
Yes following are the screenshots of the same:

![test_kimai](https://user-images.githubusercontent.com/17871448/125048828-f17eec80-e0bd-11eb-8b8c-bf5b0627e27d.jpg)


![kimai2](https://user-images.githubusercontent.com/17871448/125048888-ffcd0880-e0bd-11eb-950a-fec033c4569a.jpg)

**Comment by kevinpapst** [comment]
Thanks. But there is nothing to fix. This is simply a false-positive warning.
Kimai is a PHP application and has no file that can be executed on Windows natively.

Follow the installation instructions: you don't need to download the ZIP file anyways.
