### ISSUE TITLE
Add expense with two ore more categories

### ISSUE THREAD

**Issue by leuedaniel** [kevinpapst/kimai2#2666]
**Is your feature request related to a problem? Please describe.**
We use the expenses to record attendance fees. For example, if I have a meeting tonight, I make an entry for 1 attendance fee. In addition, I make another entry for travel expenses. I have saved two types for this. Once the attendance fee, which I enter with the number 1, and once the travel expenses, which I enter with the number of kilometers. This means that I have to enter two entries for each session.

**Describe the solution you'd like**
It would be a big simplification if I only had to enter one entry per session where the attendance fee can be selected and the travel expenses can also be recorded.

**Describe alternatives you've considered**
I tried to do this with the add-on module custom-fields, but I cannot use it to enter additional amounts in the expenses that count as total.

**Screenshot**
It would be great if I could add several categories with one + icon.
![image](https://user-images.githubusercontent.com/44936305/125748831-9c1569b6-d33c-4eac-8af4-04783ca41d87.png)

**Comment by kevinpapst** [comment]
Thanks for your idea!
Please re-post this issue in the Expenses repository. This here is Kimai core application (the wrong place). 

> Every customer gets free access to a private GitHub repository (like a forum) for support and access to the latest updates. Sent your GitHub username and your purchase receipt to info@keleo.de and you will receive an invite soon!
