### ISSUE TITLE
Version number not bumped in release 1.14.3

### ISSUE THREAD

**Issue by kosli** [kevinpapst/kimai2#2688]
I was puzzled as the about dialog didn't show me the updated version (when I updated from 1.14.1 to 1.14.3). I assume you missed to update the version number here: https://github.com/kevinpapst/kimai2/blob/df6bd30d0391aaf70ea84f4d5e7f088e2a48b858/src/Constants.php#L20

**Comment by kevinpapst** [comment]
Thanks @kosli 

But I am not going to create a new release because of that, see #2648 and #2648

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/discussions/2687

**Comment by kosli** [comment]
OMG, sorry, shame on me! :-(
