### ISSUE TITLE
Cumbersome position of "End" button for active timesheet entry since Kimai 1.14

### ISSUE THREAD

**Issue by Sarmingsteiner** [kevinpapst/kimai2#2693]
**Is your feature request related to a problem? Please describe.**
The position of the "End" button for an active timesheet entry has moved since Kimai 1.14 from first place to second place. This makes it way more complicated, as an active timesheet entry most probably will be ended and you have to focus to hit the right button. We have around 10-20 timesheet entries a day. 

**Describe the solution you'd like**
Position of "End" button should be in first place as till Kimai 1.13

**Describe alternatives you've considered**
Rolling back to Kimai 1.13

**Screenshot**
![Kimai 1 13](https://user-images.githubusercontent.com/62648132/127492236-2d98976e-cc50-4087-b644-50a5397f1334.png)
![Kimai 1 14 ](https://user-images.githubusercontent.com/62648132/127492245-a8f3412a-38d5-4127-8ad4-c960f894d761.png)

**Comment by kevinpapst** [comment]
Please have a look at: https://github.com/kevinpapst/kimai2/pull/2692
Could that solve your problem as well?
