### ISSUE TITLE
Timesheet API does not allow creating objects

### ISSUE THREAD

**Issue by dasJ** [kevinpapst/kimai2#2699]
**Describe the bug**

The validator of the timesheet API (POST) always fails with there errors:
```json
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "This form should not contain extra fields."
    ],
    "children": {
      "begin": {},
      "end": {},
      "project": {
        "errors": [
          "This value is not valid."
        ]
      },
      "activity": {
        "errors": [
          "This value is not valid."
        ]
      },
      "description": {},
      "billable": {},
      "tags": {}
    }
  }
}
```

This happens when all fields are specified and no extra fields are specified

**To Reproduce**
1. Set a API password
2. Go to swagger UI
3. Log in
4. Use the dummy data to POST to /api/timesheets

**Logfile**

Nothing really

**Additional context**

This is happening on whatever setup https://demo.kimai.org is running

**Comment by kevinpapst** [comment]
Don't rely on the Swagger UI only, it can be misleading and produce false-negatives.
Thats what I see: 
<img width="1403" alt="Bildschirmfoto 2021-08-06 um 22 23 52" src="https://user-images.githubusercontent.com/533162/128567412-8dc79557-d410-4c52-a692-f4b531a87535.png">

The difference is obvious if you compare the fields in your request with the fields in the answer: the `user` field.

As regular user, you are not allowed to set this field. Only an admin (or teamlead depending on your roles permission config) can create timesheets for other users.

**Comment by dasJ** [comment]
Thanks, that almost did it.

My second mistake was that I forgot to set `Content-Type: application/json`. Setting the header fixed it.
