### ISSUE TITLE
Kimai API billable switch missing

### ISSUE THREAD

**Issue by Filechaser** [kevinpapst/kimai2#2705]
I could not find a method to only get billable:true entries with the api.
Is billable missing on purpose?

**Comment by kevinpapst** [comment]
No. I just did not add it. "Add a feature and improve it in the future" is my preferred way of working 😁 

Do you want to help out with a PR?

We need a new flag in: 
- [the API endpoint](https://github.com/kevinpapst/kimai2/blob/master/src/API/TimesheetController.php#L114)
- [the query class ](https://github.com/kevinpapst/kimai2/blob/master/src/Repository/Query/TimesheetQuery.php#L20)
- [the timesheet repository](https://github.com/kevinpapst/kimai2/blob/master/src/Repository/TimesheetRepository.php#L853)
