### ISSUE TITLE
Timesheet Entry Popup While Clocking Out (instead of clocking in)

### ISSUE THREAD

**Issue by cicibai** [kevinpapst/kimai2#2714]
**Is your feature request related to a problem? Please describe.**
 An option for users to be able to clock in (without inputting anything) and input their timesheet information when they clock out instead.

**Describe the solution you'd like**
Clocking in: click play button
Clocking out: click play button -> input info -> save

I am a fairly new programmer, and I'm not too sure on how to go about implementing this. I would be more than willing to try making this a feature though - any pointers would be appreciated :)

**Comment by kevinpapst** [comment]
The database structure doesn't allow that. You would have to book these records on fake entries. 
What you describe will not be added to the core of Kimai, but could easily be added via plugin.
