### ISSUE TITLE
Time entry popup: make a round clock or minutes in 5 min steps

### ISSUE THREAD

**Issue by kosli** [kevinpapst/kimai2#2715]
When using the mobile phone to create a time entry and selecting the From/To time via the pop up it is quite cumbersome to scroll through all the 60 minutes. 

I would suggest to make it in 5-minute-steps only (or configurable)... 

or the best would be somehting like the "Android TimePicker with Clock Mode" (clock on the right: https://www.tutlane.com/tutorial/android/android-timepicker-with-examples)

**Comment by kevinpapst** [comment]
I suggest you use the available configuration 😁 
<img width="470" alt="Bildschirmfoto 2021-08-10 um 22 09 57" src="https://user-images.githubusercontent.com/533162/128928235-4b939ba6-5761-4806-990e-81fe251c2ccf.png">
You can post your idea here: https://github.com/kevinpapst/kimai2/issues/571
And if you would like to work on a better time-picker, I would be gladly help with the PR.

**Comment by kosli** [comment]
@kevinpapst  OMG I missed that configuration option. Shame on me! Sorry :-( 
I would love to submit a PR but I am completely out of time to work on that :-( 
Thanks for your fast reply.
