### ISSUE TITLE
Dashboard: Anzahl Kunden - Anzahl Projekte kann für Teamleiter nicht ausgeblendet werden

### ISSUE THREAD

**Issue by Sarmingsteiner** [kevinpapst/kimai2#2718]
Dashboard: Anzahl Kunden - Anzahl Projekte kann für Teamleiter nicht ausgeblendet werden, auch nicht wenn alle Widgets (order 10 bis order 50) mit der Berechtigung "ROLE_SUPER_ADMIN" in der local.yaml konfiguriert werden:

![Dashboard Kunden + Projekte](https://user-images.githubusercontent.com/62648132/129619348-42dcd82d-6fc9-44ec-8cc1-409023f7d434.png)

**Comment by kevinpapst** [comment]
Siehe: https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/DashboardSubscriber.php#L86

Die Sichtbarkeit hängt momentan an der Sichtbarkeit der Projekt / Kunden Module (sie sind auch im Menü sichtbar).
Also an den Berechtigungen `view_customer` und `view_project`.
