### ISSUE TITLE
Return pagination related info in the api response

### ISSUE THREAD

**Issue by ArnavLimaye** [kevinpapst/kimai2#2720]
**Is your feature request related to a problem? Please describe.**
When I call /api/timesheets endpoint for fetching timesheet entries, by default Kimai 2 API returns 50 entries present on page 1(Default page size). But I have no means of knowing whether there are any more records and if there are, how many records/pages are there.

**Describe the solution you'd like**
I would love to get a meta object along with timesheet entries so that I would know exactly how many pages/records are available.

**Describe alternatives you've considered**
Calling /api/timesheets GET endpoint with incrementing page param and collating responses until pagerfanta gives 404 exception because of the page out of range. But this is very very hacky, hence it would be good to know exact numbers of total pages.

**Screenshot**
Timesheets response object can look something like this :

`
{
   "data":[
      {
         "activity":0,
         "project":0,
         "user":0,
         "tags":[
            "string"
         ],
         "id":0,
         "begin":"2021-08-19T09:59:27.920Z",
         "end":"2021-08-19T09:59:27.920Z",
         "duration":0,
         "description":"string",
         "rate":0,
         "internalRate":0,
         "metaFields":[
            {
               "name":"string",
               "value":"string"
            }
         ]
      }
   ],
   "meta":{
      "currentPage":1,
      "totalPages":10,
      "itemsPerPage":50,
      "totalItems":490
   }
}
`

**Comment by kevinpapst** [comment]
See here: https://github.com/kevinpapst/kimai2/pull/1536

Many systems already rely on the current API and changing the structure the way you propose would be a massive BC ever. 

But if you want to work on a PR that provides a versioned API, we can work together on implementing a new structure.
I would propose to use an open standard for the part that you call "meta".
