### ISSUE TITLE
Prevent expired / future projects from being displayed in the dashboard for normal users

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2721]
**Is your feature request related to a problem? Please describe.**
If orders are not set invisible by the administration, the user can still see them.
The same applies to projects that have already been created but will start in the future.
This leads to a display of currently irrelevant data.

**Describe the solution you'd like**
Idea: Provide two optional check boxes in the settings:
1. Prevent future projects from being displayed (current date is before the project start date)
2. Prevent the display of expired projects (if the project has ended and the time set in the settings until when entries should be possible has been exceeded)
Example:
Project ends on 20.08.
Settings: Project can be edited until September 10th.
From 11.09. project is no longer displayed in the dashboard.

**Comment by kevinpapst** [comment]
Sounds like a bug if the dates are ignored. 
I will not add a new setting, but simply remove the projects when `now` is not inside the date range.

**Comment by HeinzWuert** [comment]
Ok, but the example above should be respected!
