### ISSUE TITLE
Whitespace on line endings in created docx invoices

### ISSUE THREAD

**Issue by Input-BDF** [kevinpapst/kimai2#2748]
Using .docx invoice templates adds whitespaces on lineendings when using multiline values for customer address, contact, payment_details, ... Whitespace is added from second until penultimate line.

I am using templatevariables like
```
${customer.address}
${template.contact}
${template.payment_details}
```
 as follows:
```
Line1
Line2
Line3
```
Within document.xml from unpacked .docx the result is:
```
<w:t>Line</w:t><w:br/>
<w:t xml:space="preserve">Line2 </w:t><w:br/>
<w:t>Line3</w:t></w:r>

```
This is only noticeable when using right aligned text and happens on all textarea input fields using multiple lines. Other template formats like pdf or html are not affected 

 - Kimai version: 1.14.3 (already happend on 1.12)
 - PHP version: 7.3

**Comment by kevinpapst** [comment]
And your problem is the extra space in `Line 2 `?

**Comment by Input-BDF** [comment]
Exactly. First and last line is okay and without whitespace. Every line between gets an extra whitespace.

**Comment by kevinpapst** [comment]
See https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Renderer/DocxRenderer.php#L38

Are you sure the value is not in your text box?

**Comment by Input-BDF** [comment]
Double checked.
Maybe I should notice that I'm using Libre Office. But i rechecked with Word 365. Word is showing formating correctly but Whitespaces are also present.

I renamed .docx to zip and examined document.xml
Source there is showing an CR (marked as [CR] in the code below) where imho it should not be:

```
<w:t>ADLine1[CR]
</w:t><w:br /><w:t xml:space="preserve">ADLine2[CR]
</w:t><w:br /><w:t xml:space="preserve">ADLine3[CR]
</w:t><w:br /><w:t xml:space="preserve">ADLine4</w:t>
```
I'm not shure, but document.xml should only have <?xml... and <w:document... as Lines. Removing the CRs from document.xml repacking, renaming etc. And everything is as wanted.

It seems to by caused by using PHP_EOL since it is imho plattform specific on line endings: LF vs CRLF.

**Comment by Input-BDF** [comment]
LOL. Found this: https://eidson.info/post/php_eol_is_broken

My php knowledge is out of date but i did a quick and dirty-fix via ssh.
```
$replace = preg_replace('/\n|\r\n?/', '</w:t><w:br /><w:t xml:space="preserve">', $replace);
```
Seems to work.

I can do a clean checkout when I find time the days and create a pull request. Or do you want to handle this by yourself?

**Comment by Input-BDF** [comment]
Seems so. Or I am the only one using right aligned texts^^. Due I'm living hybrid I will keep an eye on windoof vs. linux clitches X)
