### ISSUE TITLE
Update "Preview"/ "Save" buttons after invoice template (re)selection

### ISSUE THREAD

**Issue by Input-BDF** [kevinpapst/kimai2#2749]
Within invoice creation form changing selected template does not update usage of selected templates for preview/ save. For better user experience these buttons should be updated automatically after selecting another template. Currently you have to perform a new search.

**Comment by kevinpapst** [comment]
Agree & yes, the complete flow is only half-ready.

I have more ideas how to improve the invoicing process and this is one of them.

Allowing to select the invoice template per customer is another.

**Comment by Input-BDF** [comment]
Wooo. Default template per customer or project sounds like a nice idea. Maybe saves some work, cause you don't have to handle the template update on frontend side. Atleast the need for updating the invoice search after selecting another template would be hugely reduced.
