### ISSUE TITLE
Kimai2 Migrations conflict with MySQL `ANSI_QUOTES` mode

### ISSUE THREAD

**Issue by mikenoethiger** [kevinpapst/kimai2#2751]
**Describe the bug**
When the MySQL server used by Kimai2 has the `ANSI_QUOTES` mode on (see [Server SQL Modes](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html)), initial migrations which populate the tables fail because the generated SQL statements use double quotes instead of single quotes for string literals.

What is the consequence of having the `ANSI_QUOTES` mode? From [the docs](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes):
> Treat " as an identifier quote character (like the \` quote character) and not as a string quote character. You can still use \` to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings because they are interpreted as identifiers.

Example SQL produced by Kimai which fails with `ANSI_QUOTES` mode:
```
UPDATE kimai2_users SET roles = 'a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}' WHERE roles LIKE "%ROLE_SUPER_ADMIN%"
```

The following error is produced (full log below):
```
kimai_1  | SQLSTATE[42S22]: Column not found: 1054 Unknown column '%ROLE_SUPER_ADMIN%' in 'where clause'
```

How it would succeed:
```
UPDATE kimai2_users SET roles = 'a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}' WHERE roles LIKE '%ROLE_SUPER_ADMIN%'
```

**Solution proposal**

Generate SQL statements in the migrations which use single quotes for string literals instead of double quotes, this way Kimai is more agnostic to MySQL server configuration. Although a workaround exists (see below), it is limited as the MySQL server may have a requirement for `ANSI_QUOTES` and as a consequence is incompatible with Kimai2 (or I'm unaware of another workaround).

**Workaround**

As an operator of the Kimai application one can set the [SQL Mode](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html) to `STRICT_TRANS_TABLES` instead of `ANSI_QUOTES` in the MySQL database. You should note that this affects all databases on the server, since the setting has to be set globally (otherwise it'd only persist for the duration of the session). If one of your databases relies on `ANSI_QUOTES`, for example because you have table names which contain white spaces, this workaround is not feasible for you.

Display the current modes:
```
SELECT @@GLOBAL.sql_mode;
```

Example Output:
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0,03 sec)
```

In the example output you can see `ANSI_QUOTES` is present, but we need to have `STRICT_TRANS_TABLES`.

On your MySQL database, set sql mode to `STRICT_TRANS_TABLES`, **add all other modes shown in the output of the previous select statement to sustain the other modes**:
```
SET GLOBAL sql_mode='STRICT_TRANS_TABLES';
```

**To Reproduce**

The problem can be reproduced by starting a Kimai and MySQL Docker container.

Create a `docker-compose.yml` file with the following content:
```
version: '3.5'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=kimaipw
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3306:3306"
    command: mysqld --sql-mode='ANSI_QUOTES'
  kimai:
    image: kimai/kimai2:apache-1.14.3-dev
    environment:
      - DATABASE_URL=mysql://kimai:kimaipw@mysql/kimai
    ports:
      - "8001:8001"
```

The `command: mysqld --sql-mode='ANSI_QUOTES'` part ensures that `ANSI_QUOTES` mode is used when starting the mysql deamon.

Start the containers:
```
docker-compose up
```

Now look at the console output, if you search for `Column not found: 1054 Unknown column '%ROLE_SUPER_ADMIN%'` in the log outputs you should find the first SQL error, as shown in the initial bug description and in the log below.

**Logfile**

```
...
kimai_1  | [2021-09-07 14:45:57] doctrine.DEBUG: UPDATE kimai2_users set username_canonical = username [] []
kimai_1  |      -> UPDATE kimai2_users set username_canonical = username
kimai_1  | [2021-09-07 14:45:57] doctrine.DEBUG: UPDATE kimai2_users set email_canonical = email [] []
kimai_1  |      -> UPDATE kimai2_users set email_canonical = email
kimai_1  |      -> UPDATE kimai2_users SET roles = 'a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}' WHERE roles LIKE "%ROLE_SUPER_ADMIN%"
kimai_1  | [2021-09-07 14:45:57] doctrine.DEBUG: UPDATE kimai2_users SET roles = 'a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}' WHERE roles LIKE "%ROLE_SUPER_ADMIN%" [] []
kimai_1  | [2021-09-07 14:45:57] doctrine.DEBUG: "ROLLBACK" [] []
kimai_1  | Migration 20180715160326 failed during Execution. Error An exception occurred while executing 'UPDATE kimai2_users SET roles = 'a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}' WHERE roles LIKE "%ROLE_SUPER_ADMIN%"':
kimai_1  | 
kimai_1  | SQLSTATE[42S22]: Column not found: 1054 Unknown column '%ROLE_SUPER_ADMIN%' in 'where clause'
kimai_1  |  [ERROR] Failed to set migration status: An exception occurred while executing  
kimai_1  |          'UPDATE kimai2_users SET roles = 'a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}'  
kimai_1  |          WHERE roles LIKE "%ROLE_SUPER_ADMIN%"':                                
kimai_1  |                                                                                 
kimai_1  |          SQLSTATE[42S22]: Column not found: 1054 Unknown column                 
kimai_1  |          '%ROLE_SUPER_ADMIN%' in 'where clause'                                 
kimai_1  | 
kimai_1  | [2021-09-07 14:45:57] console.DEBUG: Command "-n kimai:install" exited with code "32" {"command":"-n kimai:install","code":32} []
kimai_1  | [2021-09-07 14:45:57] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\MakerBundle\Event\ConsoleErrorSubscriber::onConsoleTerminate". {"event":"console.terminate","listener":"Symfony\\Bundle\\MakerBundle\\Event\\ConsoleErrorSubscriber::onConsoleTerminate"} []
...
```

**Additional context**
 - Kimai version: [apache-1.14.3-dev](https://hub.docker.com/layers/kimai/kimai2/apache-1.14.3-dev/images/sha256-21ca5c313345b55d24952d849f9473116e2c9b3a631e4e88ed3c0d00161124bf?context=explore)
 - MySQL version: 8
 - MySQL with `ANSI_QUOTES` mode and not `STRICT_TRANS_TABLES` (which is the default)
- Further references:
- https://stackoverflow.com/questions/214309/do-different-databases-use-different-name-quote
- https://stackoverflow.com/questions/13884854/mysql-double-quoted-table-names
- https://stackoverflow.com/questions/11321491/when-to-use-single-quotes-double-quotes-and-backticks-in-mysql
- https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-full

**Comment by kevinpapst** [comment]
Hi!

As you are thee first ever to complain about that, I guess this mode isn't active in many systems. But Kimai should work nevertheless, so thanks for detailed reporting!

I am in holiday right now, so don't expect any change soon.
But if you are interested in helping to fix the bug, you can grep for the conflicting SQL in the directory https://github.com/kevinpapst/kimai2/tree/master/src/Migrations and sent a PR with the update/fix.

**Comment by mikenoethiger** [comment]
Hi kevinpapst

Yes I was indeed thinking about whether the bug label is inappropriate for this issue but didn't find another suiting label. I see your point, unfortunately I'm affected by the issue and not able to modify the mode on the MySQL server. But yeah seems to be an outlier case.

Is the issue solved by fixing the migration files? Or does it arise again once a new migration is generated?

**Comment by kevinpapst** [comment]
This is only an issue for the first migration files,  where some commands were written manually. 
Most migrations are using a programmatic approach, but some contain pure SQL commands. And some of those seem to be wrong.

**Comment by kevinpapst** [comment]
In other words: no, the problem does not automatically pop up again for the next migration. But I am not able to promise 100% that I will not have to write a migration command ever again re-introducing the same but another bug.
It is software written by humans and it can break. But there is no automation that will cause this bug...
