### ISSUE TITLE
No update to 1.14.3 it stops by 1.14.1

### ISSUE THREAD

**Issue by Aybee** [kevinpapst/kimai2#2759]
I tried to update version 13 to 1.14.3
```console
git fetch --tags
git checkout 1.14.3
php7.3 composer.phar install --no-dev --optimize-autoloader
php7.3 bin/console kimai:update
```

No new "var/log/prod.log" entry.

**Comment by kevinpapst** [comment]
Yes, the version string wasn't updated. You are still on the latest version, thanks for posting 👍

**Comment by Aybee** [comment]
Thanks for your reply.
