### ISSUE TITLE
Bug in activities API

### ISSUE THREAD

**Issue by Jelle-S** [kevinpapst/kimai2#2765]
In testing the API on the latest master revision, we are encountering some more errors:

```
Error on PATCH "[...]/api/activities/723". Response: 400 Bad Request
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "This form should not contain extra fields."
    ]
  }
}
```

This error does not contain the "children" element, which is weird to me. It seems like it doesn't accept any field at all. Comparing the API docs from 1.14 to the latest master, nothing seems to have changed. But when we click on one of the 'activity' endpoints in the docs, we get an error:
![kimai_api_docs_error](https://user-images.githubusercontent.com/1828542/133567711-7288caa9-1be6-4213-bf8a-b28d4e223d22.png)

**Comment by kevinpapst** [comment]
@Jelle-S any chance you could test the changes in #2766 ?

**Comment by Jelle-S** [comment]
Thanks for the update! I'll try to test this tomorrow

**Comment by kevinpapst** [comment]
Okay, then you can test master tomorrow 😁
