### ISSUE TITLE
Default project or activity

### ISSUE THREAD

**Issue by takte1** [kevinpapst/kimai2#2767]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start time and I have to manually select Customer then Project and then Activity. It is too much clicking. 
The problem is also when you start new task, you first select Customer but then there are listed all projects in system, also ones which do not belong to selected Customer so I am able to select wrong one. When you click Save, system throws error on Project "This value is not valid." and then there are shown only projects belonging to selected Customer, which is OK. Is it possible to modify that so it is like that in the first place? In short - when you select certain Customer, there should be only Projects which belong to selected Customer.

**Describe the solution you'd like**
1. I would like the option to select default Project or Activity.
2. When you select certain Customer, there should be only list of Projects which belong to selected Customer.

**Comment by kevinpapst** [comment]
1. There are many options to restart timesheet entries, which prefill these fields. Check the "restart activity" dropdown next to the play button and the dropdown "copy" and "restart". This feature wish already exists, please vote for #699 and/or #403 with a 👍 
2. The bug you mention is not existing, you have a broken Kimai installation. Most likely docker with outdated assets.
