### ISSUE TITLE
In cloud version give labels while howering over symbols.

### ISSUE THREAD

**Issue by stgpepper** [kevinpapst/kimai2#2780]
**Is your feature request related to a problem? Please describe.**
I am new to Kimai and I am using Kimai cloud. I find it somewhat difficult to find things. In almost every window there are symbols that make some action. It is pretty hard to gues what symbols do on their own. Bellow is a screenshot of some of the symbols.

**Describe the solution you'd like**
I would suggest giving the symbols label when mouse is howering over them after some time. This would make guessing of the action easier and learning to use the program faster.

**Screenshot**
![kuva](https://user-images.githubusercontent.com/74211382/133939359-73e2e281-2455-49bc-8499-3488dab86bff.png)

**Comment by kevinpapst** [comment]
Appreciate the input! 
Developers tent to get blind for such things. Good to know, I see what I can do. 
It's a little problematic to add dozens of new translations, which need to be translated into over 20 languages.

**Comment by kevinpapst** [comment]
You can see the requested changes at work following the link in the [milestone description](https://github.com/kevinpapst/kimai2/milestone/38). 

I am closing this issue, even if the new version is not yet there and it might take some months before it will be released.
