### ISSUE TITLE
No map files, hard to debug JavaScript error

### ISSUE THREAD

**Issue by pbek** [kevinpapst/kimai2#2785]
**Describe the bug**

I'm using the `kimai/kimai2:apache` Docker container to run Kimai 2 with Traefik as ingress controller.

In Firefox 92 or Chrome 93 I get a JavaScript error on e.g. `https://my.domain.com/en/timesheet/`.

![image](https://user-images.githubusercontent.com/1798101/134137465-5407cdcc-bd21-49aa-b0a8-105d712bbb39.png)

Since there doesn't seem to be any js map files around I cannot check where exactly the error is thrown.
And because of the JS error it seems no JS is executed on the page, so I can't `Start again` a time entry. Because if you click on it a `GET` request will be made, instead of a `PATCH` request according to the routes.

```
  restart_timesheet                    PATCH      ANY      ANY    /api/timesheets/{id}/restart                                        
```

Does above JS error ring any bell to you or is there a way to get map files generated to get more information?

**To Reproduce**
1. Go to `https://my.domain.com/en/timesheet/`
2. Click on `Start again` on a time entry
3. See error `Method Not Allowed` on a new page `https://my.domain.com/api/timesheets/185/restart` because of the `GET` request.

**Logfile**

```
[Tue Sep 21 10:31:42.321607 2021] [php:notice] [pid 94] [client 172.19.0.32:57558] [2021-09-21 08:31:42] request.ERROR: Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException: "No route found for "GET /api/timesheets/185/restart": Method Not Allowed (Allow: PATCH)" at /opt/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php line 140 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\MethodNotAllowedHttpException(code: 0): No route found for \\"GET /api/timesheets/185/restart\\": Method Not Allowed (Allow: PATCH) at /opt/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php:140, Symfony\\\\Component\\\\Routing\\\\Exception\\\\MethodNotAllowedException(code: 0):  at /opt/kimai/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:42)"} [], referer: https://my.domain.com/en/team/timesheet/
```

**Additional context**
 - Kimai version: 1.15.1 stable
 - PHP version: 8
 - Device: KDE Neon
 - Browser Firefox 92, Chrome 93

**Comment by kevinpapst** [comment]
Read this: https://tobybatch.github.io/kimai2/updating.html

Further questions ONLY in the Docker repo: https://github.com/tobybatch/kimai2

**Comment by pbek** [comment]
I'm using the apache image, so there is no need for the upgrade procedure. (I copied the files over from the image anyway, but that didn't help.)

Thank you for leading me on to https://github.com/tobybatch/kimai2, I'll try my luck there.

But about the js map files, any chance we might get those?

**Comment by kevinpapst** [comment]
No, this is a known browser

**Comment by kevinpapst** [comment]
Missed the Apache part, sorry. Can you check the demo if the error exists there as well?

You can switch to development mode and recompile the assets: https://www.kimai.org/documentation/developers.html#frontend-dependencies

**Comment by kevinpapst** [comment]
Why is there no play button in your screenshot?

**Comment by pbek** [comment]
https://demo-stable.kimai.org/en/timesheet/ seems to work fine. No JS error, restarting a time entry works. Thank you for pointing that and the dev mode out.

It really seems to be an issue with the assets, although `/opt/kimai/bin/console assets:install` ran through...

```
 Installing assets as hard copies.

 --- -------------------- ---------------- 
      Bundle               Method / Error  
 --- -------------------- ---------------- 
  ✔   AdminLTEBundle       copy            
  ✔   NelmioApiDocBundle   copy            
 --- -------------------- ---------------- 

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.  

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
```

**Comment by kevinpapst** [comment]
This command does only copy new assets from bundles into the public directory.
You instead are seeing outdated Kimai core assets.
Compare the asset filenames from your install with the ones from the demo. The cache buster ID in the filename must be identically. 
Eg:
<img width="594" alt="Bildschirmfoto 2021-09-21 um 11 29 14" src="https://user-images.githubusercontent.com/533162/134147070-f6ef68e6-f1ad-4ff6-b7f9-e3e8c7db1a55.png">
<img width="788" alt="Bildschirmfoto 2021-09-21 um 11 29 50" src="https://user-images.githubusercontent.com/533162/134147174-e7c479f5-a04b-44ba-b47e-cb0fa69f0e36.png">
Then verify that the contents match.

**Comment by pbek** [comment]
The `https://my.domain.com/build/app.cafc411b.js` is loaded correctly, along with all other JS and CSS files. (Only the `favicon.ico` gets a `Content Security Policy` error.) Only one set of `app.*.js`, `runtime.*.js` is present in `/opt/kimai/public/build`.

Demo is at <https://demo-stable.kimai.org/build/app.e22732af.js>. Are you sure cache buster ID will not be locally generated by Symfony?

**Comment by pbek** [comment]
Interesting, the `kimai/kimai2:apache` docker image also has `app.e22732af.js`.

**Comment by kevinpapst** [comment]
Are you sure you really want to question the developer about details? 😁 

See https://github.com/kevinpapst/kimai2/tree/master/public/build about the correct assets for the latest build.

Again: you are using outdated assets. You are loading the wrong ones. Their URL is retrieved from https://github.com/kevinpapst/kimai2/blob/master/public/build/manifest.json, so it **seems** to work in your app. 

This is a docker issue. I am finally closing here, because I cannot help with docker. 
Please try to clarify in https://github.com/tobybatch/kimai2/issues/289 what is going on.

**Comment by pbek** [comment]
I finally managed it! The content of `/opt/kimai/public/build` really was deprecated! Although I shouldn't need to migrate the files myself with `kimai/kimai2:apache` and I though I did it anyway the kimai-public volume has a prefix on my configuration, so I had to use another `docker run` command. The misnamed volume was silently created, so I didn't see what was amiss.

Only you insisting that the asset names need to match the demo page made me aware of the issue.

**Thank you very much for your precious time!**
I was struggling with this issue since I migrated from Kimai v1 to v2 two years ago!

**Comment by kevinpapst** [comment]
For two years? Wow, you can take some pain 😁 

Glad you have solved the mystery. Now if you could somehow share that solution in the docker repository, that would be awesome. Who knows how many other users suffer from the same problem? @tobybatch any explanation for that?

**Comment by pbek** [comment]
> For two years? Wow, you can take some pain grin

I still could use the `Start again` menu link for some reason, only all other things like `Stop` didn't work. But I could enter a stop time manually.

Only when watchtower now updated the kimai docker image to v1.15.1 also the `Start again` menu link stopped working.
And I always tried to fix a header problem, because I thought that the `PATCH` requests just didn't went through...

> Glad you have solved the mystery and thanks for sharing the solution +1

No, thank YOU for helping me!

> Now if you could somehow share that solution in the docker repository, that would be awesome.

I commented in https://github.com/tobybatch/kimai2/issues/289#issuecomment-923905013.

**Comment by pbek** [comment]
@kevinpapst, the `public` folder doesn't need to writeable by the user, correct? Only the `var` folder holds the data, that needs to be persisted, isn't it?

**Comment by kevinpapst** [comment]
With <= 1.14.3 there was a public/avatars/ directory, which was written to.
But I removed that code for 1.15, so yes => only var( needs to be writable by the server.

**Comment by pbek** [comment]
Ah, awesome! So we can get away with not having a docker volume for the public folder at all with `kimai/kimai2:apache`. That means there will be no issues in the future. Thanks a lot! 😁
