### ISSUE TITLE
Floating Duration

### ISSUE THREAD

**Issue by adrianrudnik** [kevinpapst/kimai2#2786]
**Is your feature request related to a problem? Please describe.**
I need to respond to a technical phone line. Clients get billed by time passed. Answering a call has high priority and time to collect info is only allowed afterwards. So the actual time tracking record is created after the call ended and support was handled. the time entry itself can only be done by working with the start date, not relative to the end date, which would be much more intuitive.

**Describe the solution you'd like**
Keep the duration field as a floating value.

- 1h: works
- 01:00 works
- "-1h" fails
- "-00:30" fails
- Entering the end-date and entering a postive value in the duration field fails.

**Describe alternatives you've considered**
Trying to look up the starting time after every call. It's complex, skype for example hides the beginning datetime stamp. Yealink is a hell to dig through the call log to research the actual starting time. In contrast, viewing the call duration is everywhere.

I can try to implement it myself but I'm honestly lost to where the blur listener is for the duration field.

**Comment by kevinpapst** [comment]
I'd be happy about an improved field handling. Usually, whenever I change something in there, some use-case breaks 😁 

But please have a look at that inline javascript block: 
https://github.com/kevinpapst/kimai2/blob/master/templates/timesheet/layout-edit.html.twig#L116

If you can improve it, please 👍

**Comment by kevinpapst** [comment]
You might want to test the next major release (beta coming soon) at #2902.

If you want to work on your suggestion, check this file:
https://github.com/kevinpapst/kimai2/blob/v2/assets/js/forms/KimaiTimesheetForm.js#L166

**Comment by adrianrudnik** [comment]
Thanks for the hint! It's been a year already? Oh my, good luck with the new major release!
