### ISSUE TITLE
 kimai:update – Error: "The column 'color' on table 'kimai2_teams' already exists."

### ISSUE THREAD

**Issue by BKapelari** [kevinpapst/kimai2#2797]
I have a problem with the upgrade from version 1.14.3 to Version 1.15.2

```bin/console kimai:update

Kimai updates running ...
=========================

[notice] Migrating up to DoctrineMigrations\Version20210802174320
[error] Migration DoctrineMigrations\Version20210704111542 failed during Execution. Error: "The column 'color' on table 'kimai2_teams' already exists."

 [ERROR] The column 'color' on table 'kimai2_teams' already exists.
```

if i drop the "color" column i get the following error

```[notice] Migrating up to DoctrineMigrations\Version20210802174320
[error] Migration DoctrineMigrations\Version20210704111542 failed during Execution. Error: "An exception occurred while executing 'ALTER TABLE kimai2_users ADD color VARCHAR(7) DEFAULT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"

 [ERROR] An exception occurred while executing 'ALTER TABLE kimai2_users ADD color VARCHAR(7) DEFAULT NULL':

         SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used
         table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change
         some columns to TEXT or BLOBs

```

**Additional context**
 - Kimai version: 1.15.2
 - PHP version: 8.0
 -

**Comment by kevinpapst** [comment]
Then you installed some branch in between. 
Otherwise this status is impossible, especially as PHP 8 was not working with 1.14.3.
You need to update the table `migration_versions` and manually set the migration status.

**Comment by BKapelari** [comment]
okay, what if i increase the innodb_log_file_size. this could also be the issue right?

**Comment by kevinpapst** [comment]
Ups, I just read the first part of the error message, sorry. I never saw that `Row size too large` error message before. 
I manage quite a lot of Kimai installations and never came across this one. 

Do you have a customized MySQL ini? I would have to google for a solution myself, I guess its faster if you do it yourself 😁

**Comment by BKapelari** [comment]
> Ups, I just read the first part of the error message, sorry. I never saw that `Row size too large` error message before. I manage quite a lot of Kimai installations and never came across this one.
> 
> Do you have a customized MySQL ini? I would have to google for a solution myself, I guess its faster if you do it yourself 😁

Thanks, in the meantime i changed the value in the MySQL ini. Now the error appears with the next table:

```

Kimai updates running ...
=========================

[notice] Migrating up to DoctrineMigrations\Version20210802174320
[error] Migration DoctrineMigrations\Version20210704111542 failed during Execution. Error: "The column 'color' on table 'kimai2_teams' already exists."

 [ERROR] The column 'color' on table 'kimai2_teams' already exists.

```

**Comment by kevinpapst** [comment]
Thats because both columns are created in the same migration: https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20210704111542.php

Delete the color column from kimai2_teams and kimai2_users

**Comment by BKapelari** [comment]
okay problem solved!
added the following to the my.cnf 

```
default_storage_engine=MyISAM
innodb_strict_mode = 0
```

Thanks!!!

**Comment by kevinpapst** [comment]
This `default_storage_engine=MyISAM` is likely a bad idea. 
I guess `innodb_strict_mode` changed a handful of internal settings, which fixed the issue.

I will see what I can do to fix the underlying problem.

**Comment by BKapelari** [comment]
okay, should i delete the firs line in the conf or should i leave it as it is for now?

**Comment by kevinpapst** [comment]
delete it, apps nowadays will likely not use `MyISAM` (Kimai uses inno_db as storage engine)
