### ISSUE TITLE
Index uniq_b9ac5bce92fc23a8 does not exist on table kimai2_users

### ISSUE THREAD

**Issue by Aldrighetti** [kevinpapst/kimai2#2798]
**Describe the bug**
Update from 1.14.1 to 1.15.2
Following https://www.kimai.org/documentation/updates.html
[notice] Migrating up to DoctrineMigrations\Version20210802174320
[error] Migration DoctrineMigrations\Version20210605154245 failed during Execution. Error: "Index 'uniq_b9ac5bce92fc23a8' does not exist on table 'kimai2_users'."                                                                                                           
 [ERROR] Index 'uniq_b9ac5bce92fc23a8' does not exist on table 'kimai2_users'.

**To Reproduce**

**Logfile**
```
Database  Table kimai2_users
| kimai2_users | CREATE TABLE `kimai2_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username_canonical` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_canonical` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  `salt` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_login` datetime DEFAULT NULL COMMENT '(DC2Type:datetime)',
  `confirmation_token` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password_requested_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime)',
  `roles` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:array)',
  `alias` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_date` datetime DEFAULT NULL COMMENT '(DC2Type:datetime)',
  `title` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auth` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_53B03B4492FC23A8` (`username_canonical`),
  UNIQUE KEY `UNIQ_53B03B44A0D96FBF` (`email_canonical`),
  UNIQUE KEY `UNIQ_53B03B44F85E0677` (`username`),
  UNIQUE KEY `UNIQ_53B03B44E7927C74` (`email`),
  UNIQUE KEY `UNIQ_53B03B44C05FB297` (`confirmation_token`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
```

**Additional context**
 - Kimai version: 1.15.2 
 - PHP version: 7.4.16
 - Device:Ubuntu 20.04
 - Apache/2.4.41 
 - mariadb  Ver 15.1 Distrib 10.3.31-MariaDB

**Comment by kevinpapst** [comment]
Fascinating. Your database is not correct, no clue how you got there.
You can adjust the file on your server and remove these two lines and run the update again:
https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20210605154245.php#L30-L31

**Comment by Aldrighetti** [comment]
That was fast. Thanks i try it!
Thank you

**Comment by kevinpapst** [comment]
while you are on it, please verify that you have set the correct server version: 
https://github.com/kevinpapst/kimai2/blob/master/.env.dist#L4
this caused some weird bugs in the past as well.

**Comment by Aldrighetti** [comment]
Hi Kevin;  my mariadb Server is on 10.3.31. 
Is it the source of the messed up db?

**Comment by kevinpapst** [comment]
Who knows what happened in the past. Lets concentrate on fixing the update problem.

Your `.env` should include something like this now (apply before executing the update again):
```
DATABASE_URL=mysql://user:password@127.0.0.1:3306/database?serverVersion=mariadb-10.3.31
```

**Comment by Aldrighetti** [comment]
Not exactly, but similar
DATABASE_URL=mysql://kimai:password@127.0.0.1:3306/kimai

**Comment by Aldrighetti** [comment]
Should i change it and append "....?serverVersion=mariadb-10.3.31" ?

**Comment by Aldrighetti** [comment]
Thanks for the hints. I appreciate it very much!!
**_[OK] Congratulations! Successfully updated Kimai to version 1.15.2_**  
so i have no clue either bout i got the wrong UNIQUE KEYS

**Comment by kevinpapst** [comment]
Glad it works now! Thanks for your feedback
