### ISSUE TITLE
default team for new users

### ISSUE THREAD

**Issue by MarkusWz** [kevinpapst/kimai2#2802]
**Is your feature request related to a problem? Please describe.**
When a time tracking responsible (TTR) puts a new user in kimai, this user is not assigned to any team as a starting point.
The TTR has now no posibility to see the user just put in kimai as not assigned to the TTR team unless I give the permissions "view_all_data".
But giving these permission to the TTR means that in the export of all users in a certain location is not possible until I select all users manually in the export button.

**Describe the solution you'd like**
Assign a default team like "all users" to each new user. By adding the TTRs to this "all users" team as team lead (multiple are possible now) they would see all users.

**Describe alternatives you've considered**
Have a role permission dedicated to see all users.

**Comment by MarkusWz** [comment]
Another alternative could be also to select the team directly when creating a new user. But for this more changes might be needed.

**Comment by kevinpapst** [comment]
I decided to go with the adjusted "create user" form => screenshot see #2849

**Comment by MarkusWz** [comment]
I like this alternative solution!
