### ISSUE TITLE
"local changes" to symfony.lock prevent git checkout from working

### ISSUE THREAD

**Issue by kosli** [kevinpapst/kimai2#2818]
I just run into the same issue as #2545 

I assume the symfony.lock is only used locally and should never be committed to git? 

Can you add it to the .gitignore file?

**Comment by kevinpapst** [comment]
No, this file keeps being in git. This is a bug in Symfony Flex, see https://github.com/symfony/flex/issues/669 and https://github.com/symfony/flex/pull/794

Lets hope it will be released soon, so the next updates will less problematic.
