### ISSUE TITLE
[all-inkl] "Service Unavailable" on specific pages after update from 1.15.2 to 1.15.3

### ISSUE THREAD

**Issue by skipperTux** [kevinpapst/kimai2#2868]
**Describe the bug**

After update from version 1.15.2 to 1.15.3 (or higher) getting the following error on the pages _My times_, _Calendar_ and _Timesheets_, other pages like _Dashboard_, _Export_ etc. work without any error.

> **Service Unavailable**
> 
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> 

Restoring database backup and going back to version 1.15.2 everything is working again without errors.
Remark: No time records in the database for October 2021 (because of vacation).

**To Reproduce**
1. Hosting on [all-inkl](https://all-inkl.com/)
2. Update to version 1.15.3 or higher
3. Click on _My times_, _Calendar_ or _Timesheets_

**Logfile**
Unfortunately `var/log/prod.log` is empty, [activating php-logging](https://blog.teamgeist-medien.de/2016/05/all-inkl-php-error-log-aktivieren.html) that log is also empty.

**Additional context**
 - Kimai version: 1.15.3 or higher (update from 1.15.2)
 - PHP version: 7.4.23
 - Composer: 2.1.9
 - Device: Fedora 34 Notebook
 - Browser: Firefox 93, Chrome 94

**Comment by kevinpapst** [comment]
Thanks for posting!

You are not the first person posting this. I was not able to reproduce this problem on multiple systems, but it seems to exist if multiple people post it.

I know this is hard, but I have no idea what it might be, so I need more input.

**Comment by kevinpapst** [comment]
This one (also all-ink): https://github.com/kevinpapst/kimai2/discussions/2859
