### ISSUE TITLE
500: Internal Server Error on user login and password change

### ISSUE THREAD

**Issue by highplainsdesignstudio** [kevinpapst/kimai2#288]
**Describe the bug**
Upon a fresh install per documented guidelines, I tried logging in to the app using the correct username and password. I am then directed to kimai.local/index.php/en/login_check and given a 500: Internal Server Error. The full text of the page reads:

> Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it  again.

>

However, I navigate back to kimai.local and and am directed to http://kimai.local/index.php/en/timesheet/ and am fully logged in. This happens every time I try to login after I've logged out. (I've tried about 10 times or so in about the past hour to reproduce it). 

I also got the same 500 error page when I changed the user's password. The user is a system-admin user. However, I went back to the home page and was given the login form.
 

**To Reproduce**
1. Fresh install on server using the instructions in the readme.md.
2. Be sure to create a user and password using the command bin/console kimai:create-user username admin@example.com ROLE_SUPER_ADMIN (per the readme.md).
3. navigate to kimai install home page.
4. Be greeted with login page and login form.
5. login with correct credentials.
6. get 500: Internal Server Error.
7. Navigate back to install home page.
8. Be logged in and viewing timesheets.
9. logout
10. greeted with login page and login form.
11. login with correct credentials.
12. get 500 error.
13. navigate to install home page.
14. be logged in and viewing timesheets.
15. change password.
16. get 500 error.
17. navigate back to install home page.
18. greeted with login page and login form.

**Expected behavior**
Login should go straight to the timesheets when correct credentials are received. There should be no 500 internal error. When the user changes their password, they should probably be given the login form to login with new credentials. There should be no 500 error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Firefox 
 - Version 61.0.1

**Additional context**
It may be because of my Apache virtual host configuration. I am hosting the app on a directory within my user account for development purposes.

UPDATE: I am getting the 500 error when trying to create a customer entry as well. However, the database is not being updated when I create a new customer. For some reason, the application doesn't appear to be properly connecting to the database.

**Comment by kevinpapst** [comment]
Hi!
Sounds a bit as if reading works, but not writing. But you can create timesheets, activities and such?
On https://demo-v2.kimai.org/ (which is installed from master every couple of hours) it works, so I don't think its Kimai in general.
Please check application logs for Kimai in .../kimia/var/logs/ and at the webserver error log.

**Comment by kevinpapst** [comment]
Any feedback @highplainsdesignstudio ?

**Comment by kevinpapst** [comment]
No feedback, closing
