### ISSUE TITLE
Invoice - partial payment

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#2894]
So far, invoices can be marked as open or paid. Sometimes however, invoices are only partially paid (e.g.bank fees are deducted). Could there be an option included by which the user can enter an amount (of the partial payment) and kimai shows the remaining open amount?

**Comment by kevinpapst** [comment]
Sounds as if "Custom fields for invoices" would be helpful. 
Until then you could write it in the invoice description, not very elegant but at least a reminder...

**Comment by kevinpapst** [comment]
Custom fields are supported for invoices. Be creative with them 😄
