### ISSUE TITLE
reporting table

### ISSUE THREAD

**Issue by Sascha1233** [kevinpapst/kimai2#2908]
![Screenshot (2)](https://user-images.githubusercontent.com/93703453/140307907-f3830e74-13a7-4cec-8e25-19911612ce08.png)
Hello, i look in the reports table the time only. I wish to the time with one icon/symbol.

 For example U = Holiday and Time,  M =Meeting. Thanks Greeting

**Comment by kevinpapst** [comment]
What? Use Google Translate please, I have no clue what you are trying to say.

**Comment by Sascha1233** [comment]
Hallo Kevin,

ich teste gerade Kimai und möchte es gern als Ersatz für eine Abwesenheitstabelle verwenden.
Mitarbeiter sollen nur ihre Abwesenheiten eintragen. Die Projekte sind dann Urlaub, Meeting, Arztbesuch usw. 
Unter Berichte kann ich alle Mitarbeiter auswählen. Dort werden die Abwesenheiten wie Urlaub, Außendienst, Meeting, Arztbesuch etc. allerdings nur als Stundenzeiten angezeigt. 
Kann dort der Anfangsbuchstabe U = Urlaub, M = Meeting in der Zelle zusätzlich für die Tätigkeiten der Projekte angezeigt werden? Siehe oben Bild. Evtl. auch anklickbar.  

Gruß Sascha1233

**Comment by kevinpapst** [comment]
Zu spezielle Anforderung, solange Kimai nicht nativ Dinge wie Urlaub/Krankheit kennt. 
Kann gerne als bezahlte Anforderung umgesetzt werden.
Ich schließe das hier erst mal, weil man ansonsten einfach pro Benutzer die Monatsansicht auswählen kann.
