### ISSUE TITLE
Time records marked as exported even when invoice is not saved due to duplicate invoice numbers

### ISSUE THREAD

**Issue by jonaswinkler** [kevinpapst/kimai2#2917]
**Describe the bug**
Premise: When manually entering invoice numbers without using the invoice number generator placeholders, it could happen that you enter a number which already exists.

When creating an invoice and selecting "Mark as exported" in the "Filter invoice data" settings, everything works as expected, even the preview. If you then choose to save the invoice, the error message

"Changes could not be saved: Invoice "xyz" already exists"

but the time records are marked as exported. Now you have to figure out which time records were on that invoice and manually mark them as open / not exported.

=> I'd expect the time records to not be marked as exported when errors occur.

**To Reproduce**
1. Go to 'Invoices'
2. Manually set invoice number
3. Save an invoice with that number (this should succeed)
4. Enable "Mark as exported"
5. Save another invoice
6. See error message "invoice already exists"
7. Note that time records are marked as exported

**Logfile**
This is on Kimai cloud, no logs available.

**Additional context**
 - Kimai version: 1.15.6
 - PHP version: ?.?
 - Device: Kimai Cloud
 - Browser Chrome

**Comment by kevinpapst** [comment]
Thanks for the report! 
Yes, that should be an atomic operation and I'll look into it.
