### ISSUE TITLE
Week-Chooser label shows month, not week

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#2933]
**Describe the bug**
The week picker shows the month, not the week
![image](https://user-images.githubusercontent.com/55000172/141764417-cb4736f8-b3f3-43b4-b09b-ba5f3d06fe3e.png)

tooltip is correct, arrows work correctly, just the labelling is not correct.

**Additional context**
 - Kimai version: release-1.16

**Comment by kevinpapst** [comment]
That is on purpose and not a bug.
Skip back a couple of weeks and tell me in which month you are / do you know which month is week 27 ?

**Comment by kevinpapst** [comment]
BTW: all week pickers were changed to work that way (eg. in reports)

**Comment by stereo9** [comment]
oh okay, i see.
in the construction industry, all deadlines etc revolve around weeks, so coming from there it felt like a bug.
especially now i feel the handling is counterintuitive, because the arrows suggest, that the month will be changed when clicking on the arrows

maybe both should be visible?
![image](https://user-images.githubusercontent.com/55000172/141766024-21633e8f-7039-4801-b83d-3a737a605638.png)

**Comment by kevinpapst** [comment]
Apple calendar:
<img width="710" alt="Bildschirmfoto 2021-11-15 um 11 32 03" src="https://user-images.githubusercontent.com/533162/141766454-1f35ec3f-c966-430b-8659-cf64d4ecbf4f.png">

Google calendar:
<img width="801" alt="Bildschirmfoto 2021-11-15 um 11 32 44" src="https://user-images.githubusercontent.com/533162/141766578-8c0beda8-3a8b-40de-8f1f-34d477ca679c.png">

Maybe adding the KW XX in small letters would be an option

**Comment by stereo9** [comment]
sounds like a good compromise.

i just realized, the way the dates display also changed. I think the two ways apple approached it are quite nice
Either no dots (Mo 15) or dots but no commas (Mo. 15.)

although i personally still prefer
Monday
15.11.
:P

**Comment by kevinpapst** [comment]
Long format does not fit in smaller screens / boxed layout. There is so much to consider when building these interfaces.
Same with the comma, German is just one language ... but I'll check.

**Comment by kevinpapst** [comment]
Looks crappy, no matter how I style it. That is the best I can come up with
<img width="278" alt="Bildschirmfoto 2021-11-15 um 12 20 12" src="https://user-images.githubusercontent.com/533162/141773298-9b79c9c2-3b3b-473a-bf1d-7dd6b4aa8679.png">

**Comment by stereo9** [comment]
does the month need to be a button?
![image](https://user-images.githubusercontent.com/55000172/141773923-0a92dbbc-c463-43b6-bd4d-48e928d0a048.png)

**Comment by kevinpapst** [comment]
Tried that in branch https://github.com/kevinpapst/kimai2/tree/form-picker

Year
<img width="366" alt="Bildschirmfoto 2021-11-16 um 02 00 52" src="https://user-images.githubusercontent.com/533162/141876731-245f658f-c341-44fb-9a49-0126a568e8a5.png">
Week
<img width="545" alt="Bildschirmfoto 2021-11-16 um 02 00 59" src="https://user-images.githubusercontent.com/533162/141876734-bce590af-669e-4942-aa28-d50badc60464.png">
Month
<img width="511" alt="Bildschirmfoto 2021-11-16 um 02 01 04" src="https://user-images.githubusercontent.com/533162/141876735-57b79c91-465d-4206-a5a6-8f07677e475d.png">

Still not entirely happy, but maybe better to understand?

**Comment by kevinpapst** [comment]
For now I will use this here and include it in 1.16.2:
<img width="299" alt="Bildschirmfoto 2021-11-17 um 08 27 03" src="https://user-images.githubusercontent.com/533162/142155248-d8ac05f7-6dc7-40ae-a4e2-c5057e782613.png">

<img width="295" alt="Bildschirmfoto 2021-11-17 um 08 26 54" src="https://user-images.githubusercontent.com/533162/142155243-a31f282f-8a94-4834-96fb-eb1b26537672.png">

I will test the other solution for the next major release
