### ISSUE TITLE
update from 1.16 to 1.16.1

### ISSUE THREAD

**Issue by Aybee** [kevinpapst/kimai2#2945]
Again it's not possible to update. Did the same tricks as last time.

**Comment by kevinpapst** [comment]
What was last time? Sorry, but I cannot remember every possible problem.

**Comment by Aybee** [comment]
Ups, yes, sorry. I meant this one https://github.com/kevinpapst/kimai2/issues/2837#issue-1022086224

Additionaly I tried with a cache clear and a hard reset.
```sh
rm -r var/cache/*
git fetch --tags
git reset --hard
git checkout 1.16.2
php7.3 composer.phar install --no-dev --optimize-autoloader
php7.3 bin/console kimai:update
```
But now with 1.16.2 everything is ok. Thank you.

**Comment by kevinpapst** [comment]
Glad to hear that it is solved now!
