### ISSUE TITLE
[API] PATCH team members removes existing ones

### ISSUE THREAD

**Issue by Jelle-S** [kevinpapst/kimai2#2975]
**Describe the bug**
When team members that are already part of a team get passed in the body of the PATCH method to update a team, they are removed from that team.

**To Reproduce**
Create a team with one member, update it through the API with the same member in the body. The member is then deleted.
```
curl --location --request PATCH 'http://kimai.local/api/teams/774' \
--header 'X-AUTH-USER: [insert API user]' \
--header 'X-AUTH-TOKEN: [insert API token]' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Test jelle",
    "members": [
        {
            "user": 3,
            "teamlead": true 
        }
    ]
}'
```

This is also reproducible on your demo environment:
```
curl --location --request PATCH 'https://demo-stable.kimai.org/api/teams/1' \
--header 'X-AUTH-USER: susan_super' \
--header 'X-AUTH-TOKEN: api_kitten' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "District09",
    "members": [
        {
            "user": 3,
            "teamlead": true
        }
    ]
}'
```
**Logfile**
Not relevant, no error messages

**Additional context**
 - Kimai version: 1.15.6 (but also reproducible on 1.16.5)
 - PHP version: 7.4
 - Device: Ubuntu Laptop, Linux server
 - Browser: Not relevant

**Comment by Jelle-S** [comment]
I did some more digging, basically https://github.com/kevinpapst/kimai2/blob/master/src/Entity/User.php#L595-L603 removes *all* memberships of a user for a team, including the newly added ones through the PATCH method (the PATCH method creates a new membership (empty ID)), because it calls itself recursively as long as it finds memberships for that user & team. Changing that code to:
```
    public function removeMembership(TeamMember $member): void
    {
        $this->memberships->removeElement($member);
    }
```
Doesn't fix it tho, that gives me duplicate key mysql errors.

**Comment by kevinpapst** [comment]
Hey, I have no time to debug this right now, sorry. 

But what about reverting the method and then only removing the entries, `if $member->getId() !== null`?

**Comment by Jelle-S** [comment]
I fixed it by emptying the team membership list first. Since no ids are passed through the API in the patch method, they (the TeamMember entities) all are recreated anyway, so I don't see any use in caching the list and then comparing it. The end result is the same: alle existing TeamMember entities are deleted, and new ones are created.

**Comment by Jelle-S** [comment]
Mind you, this might still need a better fix, since if this API callback is used in a synchronisation jobs (as it is in our case) it might ramp up the AUTO_INCREMENT value of the kimai2_users_teams table pretty rapidly (but this issue exists with or without this fix anyway).
