### ISSUE TITLE
Sequenced Records with Quick Entry (Weekly)

### ISSUE THREAD

**Issue by majidalzariey** [kevinpapst/kimai2#2978]
**Describe the bug**

Hi Team, 

Is it possible for the times to be after each other
Default Start-date-time: 08:00

Hours                                               Respected Date
First time: 5 Hours                            Mon 22 08:00 -> 13:00
Second time: 2 Hours                       Mon 22 13:00 -> 15:00

What I am getting now is
Hours                                               Respected Time
First time: 5 Hours                            Mon 22 08:00 -> 13:00
Second time: 2 Hours                       Mon 2208:00 -> 10:00

![image](https://user-images.githubusercontent.com/81531772/143734556-26210437-aea7-4087-b1cb-1cc9598d2337.png)

Thank you for your support.

**Additional context**
 - Kimai version: 1.16.5 
 - PHP version: 7.4
 - Device: Linux (Shared Hosting)
 - Browser Edge

**Comment by kevinpapst** [comment]
Hi @majidalzariey, thanks for raising your opinion!

Unfortunately I have to say that this feature was intentionally not added. 
Whatever this calculation magic would do, the result would be as "wrong" as the currently created timesheets are "wrong" in their start and end time. If you are using this form, then you are likely already only tracking durations and not the real times.

Even though I will not add it personally (unless paid for) I would accept it as PR. So if someone reads this and wants to work on it: this should be a configurable behavior. I would imagine a new system configuration that allows to switch between "use configuration `Default start-time`" and "create sequenced".

I updated the documentation page to reflect this discussion. Thanks for bringing it up 👍
