### ISSUE TITLE
Feature Request: Rate per project

### ISSUE THREAD

**Issue by jfbethlehem** [kevinpapst/kimai2#2994]
I would like to be able to set a rate per project. Some of my projects have different rates than others for the same client. For example, I have a client that acts as an in-between, sending me to different sub-clients at different rates. Each sub-client I create as a different project.

**Comment by kevinpapst** [comment]
So? What do you think does not work? Set a different rate for the project...

**Comment by dixi83** [comment]
I think I have related question. I am a freelancer and I use different rates for different projects. example:
- Project A > $60 /h
- Project B > $75 /h
- Charity Project C > $0 /h

I do'nt see how I can set this up (I'm just clicking around a few days now). There might be possibilities in using different accounts for 1 person. But that will take away the ease of use of this wonderful project.

**Comment by kevinpapst** [comment]
According to this page it is already possible: https://www.kimai.org/documentation/rates.html
I am going to extend the documentation, so that everyone understands how to set them

**Comment by dixi83** [comment]
Thanks!

I think what was not clear to me... is how to add a rate to a activity. Maybe this can be a field if you create a activity/project/customer?? Anyways it works great if you know how!

If someone hits this thread while searching for a related thing, here is a little HOWTO:
- make an activity/project/customer:
![image](https://user-images.githubusercontent.com/10693808/147873127-9d5aa659-e577-4f3e-844b-a5bb7970e699.png)
- click your newly created item: 
![image](https://user-images.githubusercontent.com/10693808/147873289-bafa5706-3c87-441c-ab92-3ad2947e300a.png)
- add a hourly rate: 
![image](https://user-images.githubusercontent.com/10693808/147873310-ddb6e0f3-a138-47a6-b440-5c080da97b76.png)
- fill in the required properties: 
![image](https://user-images.githubusercontent.com/10693808/147873353-c0cc0c37-b010-4c91-b335-64e58b966dcd.png)

I my opinion you can close this!

**Comment by kevinpapst** [comment]
I am currently writing a documentation because you are not the first person to ask that.  So the least I can do to "fix" that bad UX is to write some documentation.

I'll leave the link here later on and close the issue then. Thanks for posting the images!

**Comment by kevinpapst** [comment]
Thanks for the reminder about the missing docs 😁 I added documentation for:

- https://www.kimai.org/documentation/customer.html
- https://www.kimai.org/documentation/project.html
- https://www.kimai.org/documentation/activity.html

and also cross-linked them from https://www.kimai.org/documentation/rates.html#edit-rates
