### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by StefanGebhardt** [kevinpapst/kimai2#2999]
Hi, I installed Kimai on an webspace (all-inkl.de). Everything is fine described, but not how to start the application.

Only with googling and finding this issue I found my problem - not to start from the root but from the public directory: https://github.com/kevinpapst/kimai2/issues/541

_Whats the entry point for the browser after installation?
The root of the git repository clone is not working
The public directory is working_

Should be the last point in the documentation
https://www.kimai.org/documentation/installation.html#all-inkl

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/installation.html#webserver

**Comment by StefanGebhardt** [comment]
Sorry - blindness on my side
