### ISSUE TITLE
Menu TEAMS: search all linked projects

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#3006]
**Is your feature request related to a problem? Please describe.**
With hundreds of projects and associated teams, forgotten teams quickly emerge that are no longer assigned to any project.

**Describe the solution you'd like**
A search function in the Teams menu: Show all linked projects.
Is the result negative directly open the option: Delete unused team? Yes No

**Comment by kevinpapst** [comment]
> A search function in the Teams menu: Show all linked projects.

Do you mean "all teams with assignments" ?

**Comment by HeinzWuert** [comment]
Good idea to have 2 options:
- Check all teams to see whether a project is assigned> Result is a list of hits
- Check the selected team to see whether a project is assigned
Visible / invisible should be selectable. If that is not possible then only limit it to visible projects.
