### ISSUE TITLE
Feature Request: Sort entries in "quick_entry"

### ISSUE THREAD

**Issue by TomKost4001** [kevinpapst/kimai2#3028]
It would help if the entries in "quick_entry" could be sorted by personal choice.

**Comment by kevinpapst** [comment]
Sorted by project now.

**Comment by TomKost4001** [comment]
cool, super! Vielen Dank.

Cheers,
Tom

From: Kevin Papst ***@***.***>
Sent: Wednesday, October 19, 2022 1:12 AM
To: kevinpapst/kimai2 ***@***.***>
Cc: Kost, Tom ***@***.***>; Author ***@***.***>
Subject: [EXTERN] Re: [kevinpapst/kimai2] Feature Request: Sort entries in "quick_entry" (Issue #3028)


Sorted by project now.
