### ISSUE TITLE
Refresh of dropdown filtered data too slow, causes issues

### ISSUE THREAD

**Issue by askeddie** [kevinpapst/kimai2#3029]
Upon selecting a customer from the "Customer" dropdown screen, you need to pause 2 or more seconds before selecting a value in the "Project" field. 

Otherwise, your selection is erased and you have to select a value again.  

Let's say you are entering time for project B, for customer one.

There are project "A" and "B" under customer "One" and projects C and D under customer "Two". 

When you choose customer One and immediately go to select a project, you will see:

One
   Project A
   Project B
Two
   Project C
   Project D

The entire table of projects is shown. It usually takes 2 or more seconds to filter. So of you choose Project B, for example, it will get erased and then you must re-select it.

Perhaps as a suggestion, do not populate sub-fields until they have been filtered. This will cutback on the SQL queries and amount of data being transferred by requiring only 1 seek.

**To Reproduce**
1. Go to enter a new timesheet entry.
2. Click on Customer and select any from the dropdown.
3. Immediately go and select a project from the dropdown list and you will see the entire list, not just the projects corresponding to the customer you chose.
4. Select a project, it doesn't matter which, as it will be erased once you click out of the dropdown box.
5. Attempt to re-select a project. Note that this time the dropdown list of projects will be filtered, allowing you to choose only a project that corresponds to the customer chosen.
6. Continue entering data.

**Logfile**
```
Nothing unusual in the log file.

**Additional context**
 - Kimai version: 1.16.9
 - PHP version: 7.3.33
 - Device: Linux 4.19.150-76.ELK.el6.x86_64
 - Browser: Same occurs on Safari, Chrome, and MS Edge Chromium

**Comment by buzter** [comment]
Under circumstances that I have not yet checked, this behavior also occurs here - mind you, not always.

Until now I didn't try to select a project in this moments so I can't confirm the further reported behaviour.

**Comment by askeddie** [comment]
Hello again Kevin,

It seems the issue with the filtering of the dropdown for the project field is still a problem and I've tried now hosting it on three different cloud environments.

My most recent attempt, an Amazon AWS E2 instance with Amazon Linux2 / CentOS 7 with PHP 7.4 and Percona 5.7 as the database server. Previously tried MariaDB for MySQL.

My next attempt will be to try a previous version of Kimai2, as maybe my issue is only occuring with the latest release.

Anything else you can think of?

Kind regards,
Eddie

![Screenshot_20211219-112330](https://user-images.githubusercontent.com/8823933/146683090-37354e55-a07e-4c10-b811-cd34a11005a8.png)


On Fri, Dec 17, 2021 at 11:46 AM, Eddie Hernandez
<askeddie@aol.com> wrote:
Hello Kevin.

Thank you for your prompt response. This was a clean, new install of Kimai on a shared/hosted Linux server provided by HostGator.  We had been testing Kimai for several months in the same shared/hosted environment and did not come across any issues. 

Here is a screenshot that shows the issue.  I chose "305-Weston" as the customer, yet when I click on Project it shows a complete list, starting with 305-Aventura... not just those filtered for that one customer.  I must then either: choose anything and wait and repeat, click out of the box and back again to allow it to refresh, or wait 2 seconds before choosing the project.

Database currently: 25 customers, 81 projects, 2 activities.
DB Server: Server: Localhost via UNIX socket
Server type: Percona Server
Server connection: SSL is not being used Documentation
Server version: 5.6.41-84.1 - Percona Server (GPL), Release 84.1, Revision b308619
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)
cpsrvd 11.94.0.19
Database client version: libmysql - 5.6.43
PHP extensions: mysqli / curl / mbstring
PHP version: 7.3.32



Best Regards,
Eddie Hernandez
Email: askeddie@aol.com
Mobile: (305) 799-6270
Website | Linked-in | Google+ | Facebook | Twitter


-----Original Message-----

**Comment by kevinpapst** [comment]
Can you reproduce it on the demo?

**Comment by askeddie** [comment]
Hello Kevin. I have marked this ticket for closing. I could not get Kimai2 to function properly on a shared hosted account by HostGator. I do not know what PHP extensions may be different.

I went ahead and hosted Kimai2 on an Amazon AWS Lightsail instance and after some effort configuring the Ubuntu Lamp, I got it working. It works on Amazon, but it did not work on Hostgator, Google Cloud, or Oracle Cloud instances that I tried as well.

**Comment by askeddie** [comment]
Got it working on an Amazon Lightsail Ubuntu LAMP with Plesk. I tried other configurations and I was unsuccessful.

**Comment by askeddie** [comment]
> Can you reproduce it on the demo?

It did not reproduce the issue on the demo. Although there were too many localization changes to try, such as language, region, and settings that I would have to make to the demo to get it configured for appropriate use in USA.

**Comment by kevinpapst** [comment]
Sorry to hear that. Well, Kimai needs definitely CPU and database resources. I am running Kimai on so many different systems and they work. But shared hosting is not sufficient.

**Comment by dkgof** [comment]
I have seen this behaviour aswell, present in the last few versions at least.

I am running kimai2 inside of docker using the image from here:

https://github.com/tobybatch/kimai2

Maybee that has something to do with it?

**Comment by kevinpapst** [comment]
The only option would be to lock the next field until it is loaded with a spinner image. 
Maybe better than loosing the input... I am reopening it.

**Comment by serotonie** [comment]
Hi there,
I just had the same issue last week.
After a lot of troubleshooting, it turns out that I had a sort of DNS Loop in my network setup and that my reverse proxy was getting the ip adresse of my kimai instance server a bit late.
Taking the FQDN out and replacing it by the ip in my nginx configuration resolved it for me.

Just for info :)

Cheers!

**Comment by kevinpapst** [comment]
Next major version (see #2902) will disable the select during reload
