### ISSUE TITLE
Kiosk Plugin modification

### ISSUE THREAD

**Issue by osnet** [kevinpapst/kimai2#3049]
d'ehre Kevin, guads neichs, 

got a lil question,  will there be a possibility to alter the kiosk-plugin to enable the following. 

As of now the admin can only assign ONE activity to ALL  generated barcodes. 
But i'd like to be able to assign differrent activities. 
i.e. :   a bunch of  barcodes for team A at location A with project / activity A  and same with  B.C, n 
goal: teamleader A able to see all of A  and not B , vice versa 

would be really nice. 

thanks

kimaiv2: Version: 1.16.8 prod (prod) with KioskBundle-1.8

**Comment by kevinpapst** [comment]
Let's discuss KioskBundle in KioskBundle repo. 

If you don't have a invitation yet, please sent me your Gumroad invoice or something else identifiable

See here: https://www.kimai.org/documentation/buy-a-plugin.html

The idea in general is good and I heard it before.

**Comment by osnet** [comment]
ist unterwegs ...
