### ISSUE TITLE
Negative entries in Invoice

### ISSUE THREAD

**Issue by Cata-ExF** [kevinpapst/kimai2#3060]
You cannot use negative values and I will not support bastardizing the field for a purpose that [it was never meant for](https://github.com/kevinpapst/kimai2/blob/master/src/Entity/Timesheet.php#L239).

But what is possible indeed: the invoice system supports arbitrary sources for line items (the Expense plugin uses this API) and we could work on a very small plugin that handles customer balances. I would have to test whether the invoice system can handle negative prices.
I am just not sure if a proper invoice (might depend on the jurisdiction where you live) can hold negative invoice items. But that's probably another topic...

_Originally posted by @kevinpapst in https://github.com/kevinpapst/kimai2/discussions/2745#discussioncomment-1921125_

A credit note is effectively a negative invoice - it's a way of showing a customer that they don't have to pay the full amount of an invoice. A credit note might either cancel an invoice out completely if it’s for the same amount as the invoice, or it might be for less than the invoice.

Negative invoices are used everywhere, it's a way to properly manage a refund to client in the accounting system.
As an example, if I issue an Invoice for an advance payment for 10 hours (which is also a common scenario), then I use the time tracker and record 15 hours in 5 separate time entries, the final invoice should be for the 5 hours, I can't send to client another invoice for 15 hours, without refunding the initial amount for 10 hours. 
It's not easy to go through all time entries and calculate which ones should not be billed, will never fit exactly the advance payment, one entry will need to be manually split into 2 entries.
Therefore, a negative entry in the final invoice is needed to deduct 10 hours or a fixed amount from the tracked time.

Negative entries in an Invoice are common, for example if one needs to offer a discount to a client they add a manual item in the invoice with a negative value, the invoice total amount to be paid will reflect the discount. paypal invoicing allows negative entries, primaERP time tracker also allows manual entries in the final invoice, so I guess it's not an exceptional case.

It will be great if sometimes in the future manual invoice entries (positive or negative) will be possible.
Thank you for your work, you are doing a great job!
Catalin

**Comment by kevinpapst** [comment]
Please post this as answer in #3008
