### ISSUE TITLE
Import from Kimai v1:  This timesheet is already exported

### ISSUE THREAD

**Issue by marcovannoord** [kevinpapst/kimai2#3061]
**Describe the bug**
When importing data from Kimai v1, i'm running into issues for timesheet entries that have been marked "Exported" and am unable to import those items into Kimai v2.

**To Reproduce**
1. Drop all database tables manually. I found that running `bin/console doctrine:schema:drop --force` does not remove the table `migration_versions` and then creating the database at step 2 would fail.
2. run `bin/console kimai:install -n`
3. Import my old Kimai v1 installation with `bin/console kimai:import:v1 --global --timezone="Europe/Amsterdam" --country="NL" --prefix="" --fix-email="DOMAIN.com" --currency="EUR" "mysql://USER:PASS@127.0.0.1:3306/DATABASE?charset=latin1" "NEW_PASSWORD"`

**Logfile**
There are a lot of lines of these: for approx. 3500 entries that have been marked "exported" in v1, i get this error.
```
 !
 ! [CAUTION] Failed to validate timesheet record: 10329 - skipping!
 !


 [ERROR] Object(App\Entity\Timesheet).exported:
             This timesheet is already exported. (code kimai-timesheet-exported-01)


 !
 ! [CAUTION] Failed to validate timesheet record: 10330 - skipping!
 !


 [ERROR] Object(App\Entity\Timesheet).exported:
             This timesheet is already exported. (code kimai-timesheet-exported-01)


 !
 ! [CAUTION] Failed to validate timesheet record: 10338 - skipping!
 !


 [ERROR] Object(App\Entity\Timesheet).exported:
             This timesheet is already exported. (code kimai-timesheet-exported-01)


 !
 ! [CAUTION] Failed to validate timesheet record: 10342 - skipping!
 !
```

**Additional context**
 - Kimai v2 version: 1.16.8
 - Kimai v1 version: 1.2.2.1394 (we are running a slightly older version due to some issues with our custom layout)
 - PHP version:  7.4
 - Device: Linux on shared hosting

**Comment by kevinpapst** [comment]
Please try latest release, there was some error with the exported validator.

**Comment by marcovannoord** [comment]
Thanks! I only had 1.16.8 since i got lazy and installed it using Softaculous. I just removed that one and installed the latest v1.16.10 through a git clone but the issue stays the same i'm afraid.

**Comment by kevinpapst** [comment]
Aha, edge case that wasn't test before.

Please try to add the following lines 
```php
        if ($timesheet->getId() === null) {
            return;
        }
```

Here into this line in the validator class:
https://github.com/kevinpapst/kimai2/blob/1.16.10/src/Validator/Constraints/TimesheetExportedValidator.php#L40

**Comment by marcovannoord** [comment]
Thanks, that got me pointed in the right way. 
I also had to uncomment some stuff  in https://github.com/kevinpapst/kimai2/blob/1.16.10/src/Validator/Constraints/TimesheetBasicValidator.php#L103 
```
        if ($newOrStarted && !$activity->isVisible()) {
            $context->buildViolation('Cannot start a disabled activity.')
                ->atPath('activity')
                ->setTranslationDomain('validators')
                ->setCode(TimesheetBasic::DISABLED_ACTIVITY_ERROR)
                ->addViolation();
        }

        if ($newOrStarted && !$project->isVisible()) {
            $context->buildViolation('Cannot start a disabled project.')
                ->atPath('project')
                ->setTranslationDomain('validators')
                ->setCode(TimesheetBasic::DISABLED_PROJECT_ERROR)
                ->addViolation();
        }

        if ($newOrStarted && !$project->getCustomer()->isVisible()) {
            $context->buildViolation('Cannot start a disabled customer.')
                ->atPath('customer')
                ->setTranslationDomain('validators')
                ->setCode(TimesheetBasic::DISABLED_CUSTOMER_ERROR)
                ->addViolation();
        }
``` 

All had to be uncommented, but now importing was success.

Regarding the `bin/console doctrine:schema:drop --force` not dropping `kimai2_sessions` and `migration_versions`, resulting in `bin/console kimai:install -n` assuming it has nothing to do ( and therefore not adding tables), is that a known issue, or am i misinterpreting the documentation?

**Comment by kevinpapst** [comment]
The import should go into a normal `kimai:install` database. If the drop command does not delete the migration table that must be new / something that doctrine changed in the last two years. Don't know. I am pretty sure it worked when I wrote the docs.
There are not many people nowadays using the v1 importer, most users either have already migrated or contact me directly. 
But if you want to sent a PR to fix the docs, you are welcome to do so!

**Comment by kevinpapst** [comment]
These validators are very old, strange that they triggered. You might have some invalid data in your v1 db. 
Which is often the case, data integrity was not the strength of v1 😁

**Comment by marcovannoord** [comment]
Haha, yeah i was postponing upgrading to Kimai v2 for way too long because i did not wanna teach my users the new interface. 
And you could be very right about the data-integrity of v1, i have seen some weird stuff in invoice output before.
