### ISSUE TITLE
Invoice amount with deducted advance payment

### ISSUE THREAD

**Issue by Medius7** [kevinpapst/kimai2#3066]
I used Kimai now for a few month to track my work.
I receive a prepayment for that (i'm not sure about the correct english term ... "Installment payment", "Advance payment", "down payment", prepayment, ...).

When I wanted to create the invoice, I found no way in Kimai to deduct the advance payment from the invoice total.
How to do this task? Am I missing something?

**Comment by kevinpapst** [comment]
Duplicates #3008

**Comment by Medius7** [comment]
> But if you would join the people in #3008 and leave your vote, the feature request gets higher priority.

Hi Kevin, 
i dont think, your linked request doesnt request the exact same thing (and its closed with "wontfix").

I'm trying to describe my issue with an example:
I have recorded some activities, e.g. with an amount 300 € for an client. She payed 100 € in advance. 
So I have to generate an invoice in which I calculate all activities for 300€ and then deduct the 100€ upfront payment (results in an invoice amount of 200€).

I don't want to pretend how this could work specifically in Kimai. Whether a negative fixed price (as you suggested, but closed) or a credit applied to the customer .... or another solution ... I'm not an expert on that.

Or ... is there already a solution that I don't know about?

**Comment by kevinpapst** [comment]
The expense plugin allows to record negative amounts, which will be transferred to the invoice.
You can try it in the plugins demo.
