### ISSUE TITLE
start_time wrongly entered in Database

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#3072]
**Describe the bug**
When I enter work hours through the quick entry, Kimai displays a different start time than what is set in the database.

![image](https://user-images.githubusercontent.com/55000172/149504823-429c894f-50f5-480a-b794-25c9ab85afd4.png)

![image](https://user-images.githubusercontent.com/55000172/149504888-f945754a-26cc-48d7-a468-58d4534d60dd.png)

This causes the time entry to overlap into the next day.

**Additional context**
 - Kimai version: 1.16.10 but behaviour was observed in earlier versions as well
 - PHP version: 8.0.13

**Comment by kevinpapst** [comment]
Is there a bug in Kimai? Otherwise you should not care about data storage (which is correct in UTC in the database).
You can use the last column `date_tz` to check the "real date".
