### ISSUE TITLE
Handle advance paiments

### ISSUE THREAD

**Issue by yroberttissot** [kevinpapst/kimai2#3087]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/70005531/150561353-f5880ea5-712d-41d6-97a8-a42e4139203a.png)

Now I need to manually remove the billable check for every time record for 1 specific project that has been paid in advance.
for Other projects, the time is invoiced at the end of each month.
Since we are multiple persons working on that project, there are always 1 person that forgets one or more times to remove the 'billable' checkbox. 
This gives me a lot of administrative work to control and remove all checkboxes before generating the invoice. 

(if i put by default that billable is not selected, the problem will be reversed: people will forget to check it for other projects...)

**Describe the solution you'd like**
It would be nice at activity level (maybe project level as well), to have an option that all records coming from that activity (or project) will not be billed. To force the issue. If you do that task/activity for this project, it will never be billed. 

**Describe alternatives you've considered**
Create a script that removes all billable checkbox in all time records of a specific project

**Comment by yroberttissot** [comment]
I saw that it is included in the newest version. Now I can set 'billable' at project level.

Thanks! and good day :)

**Comment by kevinpapst** [comment]
Yes, you can set it at customer, project and activity level. It is already included in the latest release.
