### ISSUE TITLE
Problem updating from 1.16.10 to 1.17: error at composer install

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kevinpapst/kimai2#3094]
**Describe the bug**
Problem updating from 1.16.10 to 1.17: error at composer install.
I was precisely following the update guide.

**To Reproduce**
1. git fetch --tags
2. git checkout 1.17
3. composer install --no-dev --optimize-autoloader -n
4. Messages appearing about composer-runtime-api requirement which are unmet

**Logfile**
root@kimai:/var/www/kimai2# git status
HEAD detached at 1.17
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cache.sh
        public/images/

nothing added to commit but untracked files present (use "git add" to track)
root@kimai:/var/www/kimai2# git fetch --tags
root@kimai:/var/www/kimai2# git checkout 1.17
HEAD is now at 9e320674 phpstan improvements (#3092)
root@kimai:/var/www/kimai2# composer install --no-dev --optimize-autoloader -n
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/migrations 3.4.0 -> satisfiable by doctrine/migrations[3.4.0].
    - doctrine/migrations 3.4.0 requires composer-runtime-api ^2 -> no matching package found.
  Problem 2
    - Installation request for doctrine/orm 2.11.0 -> satisfiable by doctrine/orm[2.11.0].
    - doctrine/orm 2.11.0 requires composer-runtime-api ^2 -> no matching package found.
  Problem 3
    - doctrine/migrations 3.4.0 requires composer-runtime-api ^2 -> no matching package found.
    - doctrine/doctrine-migrations-bundle 3.2.1 requires doctrine/migrations ^3.2 -> satisfiable by doctrine/migrations[3.4.0].
    - Installation request for doctrine/doctrine-migrations-bundle 3.2.1 -> satisfiable by doctrine/doctrine-migrations-bundle[3.2.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
there are no entries

**Additional context**
 - Kimai version: 1.16.10
 - PHP version: 7.4.3

**Comment by kevinpapst** [comment]
Are you still using Composer 1?
Execute `composer self-update --2` and run the `composer instal ...` again

**Comment by rbuehler-teletrend** [comment]
yes, it was still composer 1 as it was installed through the OS packet manager.
I updated composer to v2 and the update to Kimai 1.17 went smoothly.
Thank you!
