### ISSUE TITLE
use activity description when adding new timesheet entry

### ISSUE THREAD

**Issue by mysash** [kevinpapst/kimai2#3098]
i use many activity templates for different things, inside the activity templates is the description section.

it will be great if i can set here content / free text and this content will be used to fill the description field when adding a new timesheet entry after selecting the correct activity template.

maybe there is already a way but i dont know it? ;)

**Comment by mysash** [comment]
I work as an software packaging consultant and many tasks of my work are the same activity only with an other software package.

therefore I would like to use an template like:
„Software packaging“
Software Vendor: Adobe
Software Name: Acrobat Reader DC
Software Version: 2022.01.01
Comments: disabled the automatic update after the installation

Or an other example: teams meeting 
There I would like to write the participants, subject, content and other informations about the meeting 

This are only two ideas / activities I would like to document. 
maybe it could be an additional field like „content template“ or so

**Comment by kevinpapst** [comment]
What kind of packages are we talking? Flatpack? Snap? Windows? Mac? 
Just wondering if we could help each other :D 

I heard the same reason from someone else before, which I count as vote then.

**Comment by mysash** [comment]
just normal Windows packages likely for sccm or other software deployment systems ;)

**Comment by kevinpapst** [comment]
Can you share your code @wobouser ?

**Comment by wobouser** [comment]
@kevinpapst 
i am not a developer - so bear with me ;-)
the code is very edgy and still in raw form - I was primarily concerned with mapping my requirement
(no errorhandler and so on)

improvements are welcome :-)

```
window.addEventListener('click', function(event) {
    checkTimeSheet(event);
});

function checkTimeSheet(event)
{
    var timeSheetAdmin = document.getElementById("timesheet_admin_edit_form_activity");
    var timeSheetEdit = document.getElementById("timesheet_edit_form_activity");
    var timeSheetDescAdmin = document.getElementById('timesheet_admin_edit_form_description');
    var timeSheetDesc = document.getElementById('timesheet_edit_form_description');

    if(timeSheetAdmin != null) {
      getActivitiesValue(timeSheetAdmin,timeSheetDescAdmin);
    }
    if(timeSheetEdit != null) {
      getActivitiesValue(timeSheetEdit,timeSheetDesc);
    }
}

function getActivitiesValue(tsElementActivity,tsElementDescription)
{
  tsElementActivity.onchange = func
tion(){
     let fetchData = {
      method: 'GET',
      headers: new Headers({
        'X-AUTH-SESSION': true,
        'Content-Type': 'application/json'
      })
    };

    fetch('http://mykimaidomain.xy/api/activities/' + tsElementActivity.value,fetchData)
      .then(data => {
        return data.json();
      })
      .then(post => {
        tsElementDescription.value = post.metaFields[0].value;
      });
  };
}
```

**Comment by kevinpapst** [comment]
BTW: this exact feature is available in the Expense plugin. 
I am closing here as I have no plans to add this to core. It can be achieved through other ways.
