### ISSUE TITLE
Error when updating composer dependencies with 1.17.1

### ISSUE THREAD

**Issue by leuedaniel** [kevinpapst/kimai2#3101]
**Describe the bug**
When i will update the composer dependencies with /usr/bin/php7.4 /usr/bin/composer install --no-dev --optimize-autoloader -n there is a error:

`Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/migrations 3.4.0 -> satisfiable by doctrine/migrations[3.4.0].
    - doctrine/migrations 3.4.0 requires composer-runtime-api ^2 -> no matching package found.
  Problem 2
    - Installation request for doctrine/orm 2.11.0 -> satisfiable by doctrine/orm[2.11.0].
    - doctrine/orm 2.11.0 requires composer-runtime-api ^2 -> no matching package found.
  Problem 3
    - doctrine/migrations 3.4.0 requires composer-runtime-api ^2 -> no matching package found.
    - doctrine/doctrine-migrations-bundle 3.2.1 requires doctrine/migrations ^3.2 -> satisfiable by doctrine/migrations[3.4.0].
    - Installation request for doctrine/doctrine-migrations-bundle 3.2.1 -> satisfiable by doctrine/doctrine-migrations-bundle[3.2.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`

**To Reproduce**
1. git fetch --tags
2. git checkout 1.17.1
3. /usr/bin/php7.4 /usr/bin/composer install --no-dev --optimize-autoloader -n

**Additional context**
 - Kimai version: 1.17.1
 - PHP version: 7.4 (with 8.0 it doesnt works)

**Comment by kevinpapst** [comment]
Upgrade to Composer 2: https://github.com/kevinpapst/kimai2/issues/3094#issuecomment-1019982570

And Kimai definitely works with 8.0
