### ISSUE TITLE
Parameters for defining, if addding timesheet record in simplified form is allowed

### ISSUE THREAD

**Issue by cloggg** [kevinpapst/kimai2#3108]
Please implement parameter to:
- allow adding timesheet record via 'weekly working time'
- allow using realtime time measurement (arrow in top right corner)

Problem:
Both of above mentioned method allow for adding records even if a mandatory field (defined for timesheet using 'Custom Fields' plugin) is set as required. The timesheet record is added anyway (without required field)

**To Reproduce**
1/ Create meta field for timesheet  using 'Custom Filds' plugin and make it 'required;
2/ Adding new timesheet records via 'my times' form validates, if the field is not empty
3/ Adding the same record via 'weekly working time' form does not care about presence of the mandatory field. the record is added without it

**Additional context**
 - Kimai version: 1.16.8

**Comment by kevinpapst** [comment]
I don't understand you entire posting. 
If you don't want to allow Weekly working times => remove the permission and users won't be able to use it.

**Comment by cloggg** [comment]
You are absolutly right. For some reasons I have missed the parameters.
Sorry for false alert.
Issue is closed

**Comment by kevinpapst** [comment]
Oh, that fixed your issue? 

Thats good to hear, seems I understood your issue without knowing 😁
