### ISSUE TITLE
Deletion of Invoices or confirm alert on invoice creation

### ISSUE THREAD

**Issue by kulturbande** [kevinpapst/kimai2#3116]
**Is your feature request related to a problem? Please describe.**
In one of the recent versions the functionality of invoice deletion was removed in favour of a cancel mechanic. Yesterday I created by accident an invoice (I wanted only a preview). I had to go to the database and deleted the entry by hand, because otherwise there would be a jump in my incoice numbers. 

**Describe the solution you'd like**
Allow to delete the invoices again _or_ show some sort of confirmation alert on invoice creation, that this entry is not deletable. 

**Describe alternatives you've considered**
Do nothing or patch it with a plugin

I have no idea which solution is the best, but currently there is the possibility to make a mistake without the possibility to correct this.

**Comment by kevinpapst** [comment]
The other solution could be to RTFM 😁 
https://www.kimai.org/documentation/invoices.html#deleting-invoices

**Comment by kulturbande** [comment]
This is awesome and I didn't saw this before. I will close this issue, because it solved my case. Maybe there have to be in the future some sort of alerting, if the user is kicking off an action which is not undoable.

**Comment by kulturbande** [comment]
@kevinpapst And thx for the hint. I didn't saw that before.

**Comment by kevinpapst** [comment]
Deletion caused so many bug reports, that I had to turn it off. The current mechanism of calculating the next invoice number is not idempotent, as it uses the list of existing invoices. 
So if you ever delete an invoice, which is not the last one, you will have a problem...

**Comment by kulturbande** [comment]
With great power comes great responsibility. I will keep that in mind and will let the permission off. 

Thx, for your effort and work you put into Kimai2!
