### ISSUE TITLE
Fixed table header

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kevinpapst/kimai2#3117]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be helpful if the table header was fixed on top and only the table body would scroll. Especially in larger lists with a number of table columns you get easily lost and may have to scroll up again to see what type of entries you're looking at.

**Describe alternatives you've considered**
I'm not aware of any.

**Comment by kevinpapst** [comment]
Already available in the next major release, but version 2 will need a couple of months before landing...
You can already get a first impression here: https://demo-branch.kimai.org/ with `susan_super` and `kitten`

**Comment by kevinpapst** [comment]
You can see the requested changes at work following the link in the [milestone description](https://github.com/kevinpapst/kimai2/milestone/38). 

I am closing this issue, even if the new version is not yet there and it might take some months before it will be released.
