### ISSUE TITLE
Change invoice filename does not work

### ISSUE THREAD

**Issue by daboss84** [kevinpapst/kimai2#3125]
**Describe the bug**
According to the export docu, I tried to set a PDF invoice filename as follows:
`{%- set filename = model.invoiceNumber ~ '-' ~ model.customer.company|default(model.customer.name)|u.snake ~ '-Rechnung' -%}`
`{%- set option = pdfContext.setOption('filename', filename) -%}`

After deleting the cache, reloading the page and clicking "prieview" on the invoice page, the invoice name remains unchanged at <invoice-number>-<customer>.pdf

**To Reproduce**
See the description.

**Additional context**
 - Kimai version: 1.16.8 prod (Ayumi)
 - PHP version: 7.4.26
 - Device: Windows client, Ubuntu server
 - BrowserFirefox, Chromium

/Edit: Note that I am talking about invoices here, not the export (I was just using the export docu)

**Comment by kevinpapst** [comment]
I highlight it for you:

> Change invoice filename does not work

> According to the export docu

Even though both produce PDFs, it is an entirely different codebase.
Or in short version: Invoice is not Export 😁

**Comment by daboss84** [comment]
Yeah, I got it, that export and invoice are both handled differently. However, I expected the document generation part to be the same :)

Thanks for relabel it as a feature request. Do you have an estimate when you'll realese a version containing this feature?

**Comment by kevinpapst** [comment]
Found it: https://github.com/kevinpapst/kimai2/releases/tag/1.20.3
