### ISSUE TITLE
Price calculation in invoices seems wrong

### ISSUE THREAD

**Issue by daboss84** [kevinpapst/kimai2#3131]
**Describe the bug**
On the invoice, the price is calculated like:
Hourly rate 48,00 * 0,77h = 36,80

But 48,00 * 0,77 = 36,96

I found an earlier entry: https://github.com/kevinpapst/kimai2/pull/1424#issue-557505854 so I tried to reconstruct "your" (Kimai2's) calcuation:
The above entry is, in the timesheet, split up into two entries:
(48 * 0,68h) + (48 * 0,08h) = 32,64 + 3,84 = 36,48 (not 36,80 either)
Here is another issue: 0,68 + 0,08 != 0,77 
Which means in the invoice, it must be 48,00 * 0,76h = 36,48! (not 36,80 either)

Your result of the above mentioned Link: "ith the change the values within the invoice are inconsistent"
The current way of calculating the resulting project-based invoice is inconsistent. Please fix this. How should one explain to the customer, that 48 * 0,77 = 36,80 instead of 36,96 (and that 0,68 + 0,08 = 0,77 instead of 0,76 so this line item sould sum up to 36,48 instead of 36,80) ? I am sure he would feel quite mucked out.

This goes on for all 6 projects on the invoice. (53 * 44,35h != 2350,37, 48 * 17,72h != 850,65 and so on)

Don't get me wrong, I don't want to be rude (if it sounds this way). I'm just a little ...confused... about such big troubles about getting the correct numbers. I really did not expect this so I did not check this before hand (my bad).

Please, please fix this discrepancies. 
For now I am going manually through the entries and recalculate what kind of defeats the purpose of using a time reporting and invoicing tool...

**Additional context**

 - Kimai version: 1.16.8 prod (Ayumi)
 - PHP version: 7.4.26
 -  Device: Windows client, Ubuntu server
 -  BrowserFirefox, Chromium

**Comment by kevinpapst** [comment]
Before doing anything, you should provide exact numbers and not rounded decimal representations.
We could stop arguing right here, but for the sake of good customer service for a free product...

Export the plain data from the database and share it, so we can discuss further. I am 100% certain that neither 0,77 nor 0,68 are not the original duration values, but already a rounded visual decimal representation.

Kimai calculates with the original values. What you see in the invoice are rounded values. All your examples above are rounded values.

The most important rules when you want to invoice times:
- Configure a duration rounding with a multiple of 3 to be sure that you don't hit (too many) rounding issues.
- If you don't want to use duration rounding, you should print your invoices with no-decimal times. 

I am not saying that the math behind cannot be improved, but time has the base 60 and money the base 100. Converting between these two without rounding problems is hard without the proper input values.

**Comment by daboss84** [comment]
No, those are the numbers the customer sees when (s)he double-checks the invoice. No-Decimal times don't help that much in this case, either.

I am going with 3 minute rounding as a workaround for now.

In my opinion (again, no personal offence), it looks like Kimai tries to calculate with a way too high precission according to, e.g. an Excel export. Calculating in through with full precission, it calculates correct. But I find it a little hard to explain to said customers.

> but for the sake of good customer service for a free product...

Don't worry, for free good software, I usually donate - latest end-of-year. I'll do so here, even if there are some edges ;)
