### ISSUE TITLE
problem with the update - error 500

### ISSUE THREAD

**Issue by lllp1** [kevinpapst/kimai2#3141]
Hi,
I am updating to version 1.17.1 and am having trouble with error 500
I update it according to the instructions: https://www.kimai.org/documentation/updates.html - the update runs without error
Finally, I change the directory permissions. On the login page to the administration panel, I enter the login and password and I get an error 500.
I have the current version of Ubuntu 20.04.3, PHP 7.4.3

I am asking for help in resolving the problem and fixing the error 500 after the update

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/discussions/3140
