### ISSUE TITLE
Currency Symbol for Project and Activity doesn't reflect Customer Currency

### ISSUE THREAD

**Issue by ravensorb** [kevinpapst/kimai2#3148]
**Describe the bug**
Not sure if this is a bug or a feature request. Right now it seems that the Project and Activity screen currency fields show the Euro Symbol regardless of what currency is set for the customer. 

Note: When I go back in and edit the project or activity (after clearing browser cache) it does seem to show the correct currency.  Could this juts be a matter of the UI having a default symbol and it not being updated with a customer/project is selected?

**To Reproduce**
1. Create a New Customer
2. Set Customer name
3. Set TimeZone (I used New York)
4. Set currency on customer to 'US Dollar'
5. Save customer (not I left the country set to Germany)
6. Create New Project
7. Set Customer
8. Budget Currency Symbol remains set to Euro 
9. Create New Activity
10. Select Project created in step 8
11. Budget Currency Symbol remains set to Euro  

**Logfile**
N/A (no error in log related to this that I can find)

**Additional context**
 - Kimai version: 1.17.1 prod (Ayumi)
 - PHP version: (Running in docker container -- apache latest)
 - Device: Ubuntu/Mint/Windows
 - Browser Chrome 98

**Comment by kevinpapst** [comment]
The currency fields should be empty, until it is clear which currency should be displayed.
That is only after saving the new project. Meaning the "create" screen should not have show any currency, but the "edit" screen should.
Right now the fallback currency is shown, which is wrong as you correctly pointed out.
