### ISSUE TITLE
SVG avatars not shown in top bar

### ISSUE THREAD

**Issue by muety** [kevinpapst/kimai2#3163]
**Describe the bug**
When setting an SVG image as user avatar, it is properly displayed under `/en/profile/<user>`, but missing in the top bar.

![image](https://user-images.githubusercontent.com/8978843/154566920-a0c61e05-4e91-469e-b61b-55b86db5af86.png)

That is probably, because the `img` is given a `max-height` there, instead of a `height` and since a SVG itself doesn't have a size inherently, it is shown as a 0 x 0 px image.

**Additional context**
 - Kimai version: 1.17.1 
 - PHP version: 8.0
 - Browser: Firefox 97

**Comment by kevinpapst** [comment]
Quite an edgy issue. You can install the Custom CSS plugin, fix it and share your solution.

**Comment by muety** [comment]
I think the solution is literally replace `max-height: 26px` by `height: 26px`.
