### ISSUE TITLE
xlsx export: the summery value of duration and rates does not depend on the selected filter

### ISSUE THREAD

**Issue by fredyb** [kevinpapst/kimai2#3165]
The exported timesheets (in xlsx format) have data filtering active. If the data is filtered according to selected criteria, the total (sum) of the Duration and Rates columns is not adjusted. The SUM function must first be manually replaced with the subtotal function.

**Comment by kevinpapst** [comment]
Yeah, I was recently thinking about a way to replace the manually calculated sums with proper excel functions.
But this sounds easier than it is unfortunately. 
But this, I like it and it should be added, thanks for writing it down!
