### ISSUE TITLE
Typo in plugin description

### ISSUE THREAD

**Issue by limitedAtonement** [kevinpapst/kimai2#3169]
**Describe the bug**
At https://www.kimai.org/store/custom-content-bundle.html, markdown is spelled markdwon.

**To Reproduce**
1. Go to https://www.kimai.org/store/custom-content-bundle.html
2. Read

**Logfile**
```
not applicable
```

**Additional context**
 - Kimai version: none
 - PHP version: none
 - Device: AMD Ryzen 7 3700X, 32 GB ram, Arch Linux, nvidia
 - Browser: Chromium 98.0.4758.102

**Comment by kevinpapst** [comment]
Thank you for the info 👍 already fixed and live.
