### ISSUE TITLE
Decimal format in print export doesn't work when language is set to German (Austria)

### ISSUE THREAD

**Issue by klemensz** [kevinpapst/kimai2#3172]
**Describe the bug**

If I set "Deutsch (Österreich)" as the language in my user settings, then the setting "Dezimal Format für Export nutzen" doesn't have an effect.

It works if I set the language to "Deutsch" thought.

<img width="974" alt="Bildschirmfoto 2022-02-25 um 13 03 28" src="https://user-images.githubusercontent.com/1116517/155712213-e384ee92-0438-4433-8479-92fd6f2fc1b8.png">

**To Reproduce**
1. Go to user settings and change preferred language to  German (Austria)
2. Click on Export > Search > Print 
3. Select checkbox "Dezimal Format für Export nutzen" on the print page that opens
4. See error in browser console

**Logfile**

Browser console log:

```
data:584 Uncaught RangeError: Incorrect locale information provided
    at new NumberFormat (<anonymous>)
    at HTMLInputElement.<anonymous> (data:584:43)
```

**Additional context**
 - Kimai version: 1.16.6
 - PHP version: 7.4.27
 - Device: macOS 12.2.1
 - Browser: Chrome 98.0

**Comment by kevinpapst** [comment]
Thanks for letting me! Will be fixed with 1.18. 
You can apply the fix directly, see https://github.com/kevinpapst/kimai2/pull/3158/commits/3bc4477cc85a4186b63c7d3b9e10af2bfd9abb5b

**Comment by klemensz** [comment]
OK thanks. In the meantime I changed the language to German as a workaround, I suppose it won't make a difference. 😉

**Comment by kevinpapst** [comment]
I can't think of any differences expect Januar vs Jänner, which shouldn't matter that much in Februar 😁
