### ISSUE TITLE
Missing translation files

### ISSUE THREAD

**Issue by milotype** [kevinpapst/kimai2#3173]
**Describe the bug**
Missing translation files for **Croatian** (and possibly for other languages) in the folder **Translations** of the kimai2 repository:
- invoice-calculator.hr.xlf
- invoice-numbergenerator.hr.xlf
- invoice-renderer.hr.xlf

These files exist for many other languages though in the repository:
I cannot find them in the [Kimai - Time tracking](https://hosted.weblate.org/projects/kimai/) project at Hosted Weblate, although all components are translated into Croatian.

Should I translate them and send a PR via GitHub?
Or will you add them as components to Hosted Weblate?

**Comment by kevinpapst** [comment]
Hm, interesting. 
I think you should be able to translate them there as well.
Let me check if there is a misconfiguration in Weblate, I'll keep you posted...

**Comment by kevinpapst** [comment]
I have to admit that I never really used Weblate, I just configured it for Kimai... 
But I can remember that I did not create components for these files, becuase I wanted to change the usage of them.
As this did not happen in month I am adding the components now. Can you please check if you can work with them.
URLs follow...

**Comment by kevinpapst** [comment]
First one for invoice calculator: https://hosted.weblate.org/projects/kimai/invoice-calculator/

**Comment by kevinpapst** [comment]
Invoice templates: https://hosted.weblate.org/projects/kimai/invoice-templates/

**Comment by kevinpapst** [comment]
For `invoice-numbergenerator.*.xlf`: https://hosted.weblate.org/projects/kimai/invoice-numbers/

**Comment by kevinpapst** [comment]
Thank you @milotype for all your support 🎉 

Very much appreciated 👍

**Comment by milotype** [comment]
@kevinpapst All components are now translated into Croatian!

**Comment by kevinpapst** [comment]
Awesome, thanks a lot! Then it will be include in the next release, which I will publish this weekend.
