### ISSUE TITLE
Font changed after installing it locally

### ISSUE THREAD

**Issue by klemensz** [kevinpapst/kimai2#3187]
**Describe the bug**

It looks like the font that's being used by Kimai changed after installing a font locally into my macOS "Font Book" (Schriftsammlung).   

**To Reproduce**
1. I locally installed the Source Sans Pro font from Google Fonts
2. After that it seems that Kimai is using a different font than before
3. So probably this font family is set in CSS but it's not linked in HTML or imported in CSS, so it's only used when installed by the user

Not sure if this is done on purpose or if it's a bug. 

**Additional context**

- Kimai version: 1.16.6
- PHP version: 7.4.27
- Device: macOS 12.2.1
- Browser: Chrome 98.0

**Comment by kevinpapst** [comment]
Interesting finding. I guess I will leave it as is or remove the `Source Sans Pro`, so it looks the same everywhere.

Currently the rule is 
```css
font-family: Source Sans Pro, Helvetica Neue, Helvetica, Arial, sans-serif;
```
And I am happy with using `Helvetica` only, as this font is available in every device.

**Comment by klemensz** [comment]
Or import it in the stylesheet like this `@import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap');`.

**Comment by kevinpapst** [comment]
Thanks for the idea 👍 Neverthelss: Google fonts is definitely not an option (privacy!). 
Shipping the font would be possible, but I am against that. Nobody ever complained before, so it seems to be okay for almost everyone and with the next major release on the horizon, I don't want to make too many changes anymore.

**Comment by klemensz** [comment]
Yeah you can probably leave it as it is. I just caught my eye because Source Sans Pro looks a bit smaller than Helvetica with the same px size.

**Comment by kevinpapst** [comment]
Looks nice with the font installed. But I'll keep it as is...
