### ISSUE TITLE
Issue raised after Excel export

### ISSUE THREAD

**Issue by majidalzariey** [kevinpapst/kimai2#3189]
**Describe the bug**
Empty string after Excel import raises an issue.

**To Reproduce**
1. Prepare timesheet import csv with empty description strings 
2. Import the timesheets
3. Export the imported Timesheet as Excel
4. Issue Raised

I have fixed the issue from my side by adding the following snippet code to sanitizeDDE() function in StringHelper.php

```
if ('' === $text) {
            return null;
}
```

for your kind consideration. 

**Additional context**
 - Kimai version: latest
 - PHP version: 8.0
 - Device: Any
 - Browser Any

**Comment by kevinpapst** [comment]
Thanks @majidalzariey - will be fixed with the next minor release.

It is impossible to create an empty string with the UI, so this test case was missed.
