### ISSUE TITLE
Unwanted behavior during reassignment of working hours

### ISSUE THREAD

**Issue by phillsec** [kevinpapst/kimai2#3201]
# Am I doing something wrong?
Hi there, first of all, i really do enjoy using kimai thank you for this hard work!
I don't know PHP myself that good to make this feature that's why I'm requesting it.

## Problems
- If an employee's working hours get changed, this should only be valid from the effective date on only, it's important for further calculation. The occurring problem is that all times before this effective date are also changed to the new shift, which leads to false calculation results in the end

## Questions
- Have I possibly found a bug/feature?
- Is there way to prevent this already, possibly a checkbox or something similar?
- If not can someone add this as a feature?

best regards
phillsec

**Comment by kevinpapst** [comment]
I have no clue what you are talking about. 
But it sounds as if it might be related to the Controlling Bundle @j0hannesr0th

**Comment by j0hannesr0th** [comment]
I habe no clue what he is talking about, too. In Controlling Plugin when a month gets "closed" we save the daily working time of the user of this month in the table "kimai2_ext_controlling" to not change old values, etc.

**Comment by kevinpapst** [comment]
Hahahaha, okay, lets wait what this is about

**Comment by phillsec** [comment]
# Hey thanks

This feedback was fast, yes it 's about the Controlling Bundle.

## Further explanation

**Case:**  Someone is switched from full time to part time and it changed all entries even the days this person was in full time, which was leading to misscalculations in the end.

**Meanwhile**: I figured out there's a setting/option in which one can set the first working day. So with this setting, I hope to prevent the wrong calculations, it may be that I have overlooked this and therefore the "misterious problem" occured.
___

Unfortunately, the data is not updated daily, the hours are calculated weekly. Need to wait till next week for further feedback on whether the problem is solved or not.


I would like to thank you anyway for your time reading this.

I wish a great weekend!  :-)


best regards
phillsec

**Comment by kevinpapst** [comment]
Okay, I am closing here. Please use the plugin support channel for that, which is eg. linked here:
https://www.kimai.org/store/mr-software-controlling-bundle.html
