### ISSUE TITLE
Billable of time-records created from recent acitivities in calendar view

### ISSUE THREAD

**Issue by de-sec** [kevinpapst/kimai2#3218]
**Describe the bug**
While creating time-records in the calender view with the quick-draw feature of recent activities all new time records are marked as billable by default.

**To Reproduce**
1. Go to Calendar
2. Crate a Time Record from drawing recent activities

**Logfile**
```
no log files attached
```

**Additional context**
 - Kimai version: 1.19 stable
 - PHP version: 7.4.19
 - Device: Windows Notebook 14"
 - Browser: Edge (Chromium) 99

-> Default behavior for new records created by this procedure should be billable: auto including a re-calculation of the recent activity or the billable state of the recent activity used.

**Comment by de-sec** [comment]
Happens aswell - same result. The new record had the billable attribute set to yes.

**Comment by kevinpapst** [comment]
Thanks for your research! Will be fixed with the next release

**Comment by kevinpapst** [comment]
Can you please re-test tomorrow and let me know if it works now?

**Comment by de-sec** [comment]
Hi Kevin, 

currently we don't have a test-environment established - is there a more simple way to test, except manually replacing the changed files? 

Best regards

**Comment by kevinpapst** [comment]
Yes, thats why I said "tomorrow" because the demo environments are reinstalled every 12 hours.

Use the "development demo": https://www.kimai.org/demo/ 

😄

**Comment by de-sec** [comment]
forgot the automated provisioning of the dev-demo environment. *facepalm* 

Checked it with a freshly created non-billable projects of a billable customer - seems to work. Thank you very much!

**Comment by kevinpapst** [comment]
Thanks 👍 I will release a new version today or tomorrow then.
