### ISSUE TITLE
500 Error navigating to /en/team/timesheet/

### ISSUE THREAD

**Issue by nhadsall** [kevinpapst/kimai2#3230]
[2022-03-30 19:40:22] request.INFO: Matched route "stop_timesheet". {"route":"stop_timesheet","route_parameters":{"_route":"stop_timesheet","_controller":"App\\API\\TimesheetController::stopAction","_format":"json","id":"6"},"request_uri":"https://domain.com/api/timesheets/6/stop","method":"PATCH"} []

[2022-03-30 19:40:23] request.CRITICAL: Uncaught PHP Exception App\Validator\ValidationFailedException: "Validation Failed" at /home/user/domain.com/kimai2/src/Timesheet/TimesheetService.php line 274 {"exception":"[object] (App\\Validator\\ValidationFailedException(code: 400): Validation Failed at /home/user/domain.com/kimai2/src/Timesheet/TimesheetService.php:274)"} []

**Comment by nhadsall** [comment]
Hey, not sure if this is being closed because you need additional info or there's anything else I can do.

**Comment by kevinpapst** [comment]
If you open a new issue, there is a template that asks for data. You decided to ignore it. I decided to ignore it.

**Comment by nhadsall** [comment]
**Describe the bug**
We get multiple 500 errors without usually seeing anything in the error logs. We did see the one error above.

**To Reproduce**
Brand new install per the documentation.
User tried to track time, received 500 error.
Navigating to /en/team/timesheet/ 500 error.

**Logfile**
See first comment.

**Additional context**
 - Kimai version: 1.9
 - PHP version: 7.4.28
 - Device: CentOS 7
 - Browser Windows 10, Chrome 99.0.4844.51

**Comment by kevinpapst** [comment]
The posted error has nothing to do with your description.

It happens when you stop an entry that cannot be stopped due to validation issues like overtime, reached budget...

The 500 is something else. I assume wrong file permissions.

**Comment by nhadsall** [comment]
All file permissions have been confirmed (a few times) per the documentation. This was a totally new install with just a few users and a single project added. No settings like budget had been added. We had to delete the buggy entry from the database or it wouldn't let us to anything. Oddly, the url would display after clearing the cache, but once we refreshed we would get a 500 error. The apache log only showed that no info was being returned.

**Comment by kevinpapst** [comment]
See, this should all be part of the initial description. Or how shall I help otherwise? 
Again: ehe error you posted can only occur when you click on the stop button and the API route is triggered via Javascript (you can only reach it via POST). The log message has nothing to do with your description.
What is a buggy entry? 
How can I reproduce the issue?
