### ISSUE TITLE
New Date-Time-Picker library

### ISSUE THREAD

**Issue by h2Entwicklung** [kevinpapst/kimai2#3232]
Hello,
first of all thanks for the great tool. We use it so much and it is so easy to use

**Is your feature request related to a problem? Please describe.**
We build our own web apps and we used the same timepicker module as you used. We were so anoyed about the timepicker so we developed our own date-time picker npm module. It is almost like an android date-time picker.
Here I published the date-time picker at github. I would be so glad to see the major update with an updated one.
https://github.com/h2Entwicklung/dateTimePicker

**Describe the solution you'd like**
Just replace the timepicker with the new one :)

**Screenshot**
![image](https://user-images.githubusercontent.com/87967468/161063614-971364b6-044c-4a50-90c2-052c9a62b069.png)
![image](https://user-images.githubusercontent.com/87967468/161063679-1b8400f4-828a-466c-9bb3-1f01ac4c7c0a.png)
![image](https://user-images.githubusercontent.com/87967468/161063749-3817852b-18bf-4e8b-912c-4b04381ead65.png)

**Comment by kevinpapst** [comment]
Thanks for your feedback!
Yes, I want to improve the Time edit dialog and use a different set of inputs and another library.
But it must be one that targets bootstrap and not material UI.
I hope browsers start improving the HTML5 form types soon...

**Comment by kevinpapst** [comment]
Next major version has different inputs: https://github.com/kevinpapst/kimai2/pull/2902
Still no timepicker though. Material design doesn't fit, closing.
