### ISSUE TITLE
Parameter Fiscal Year

### ISSUE THREAD

**Issue by leuedaniel** [kevinpapst/kimai2#3248]
**Is your feature request related to a problem? Please describe.**
It is currently possible to record a fiscal year. However, only a single fixed date can be selected as a parameter. Unfortunately, the function behind it is not clear to me.

**Describe the solution you'd like**
It would be practical if a permanently valid fiscal year could be defined. In our case e.g. 01.10. - 30.09.
When exporting, the fiscal year could be superimposed as the evaluation period.

**Describe alternatives you've considered**
As an alternative, the date in the parameters can already be adjusted annually.

**Screenshot**
Now:
![image](https://user-images.githubusercontent.com/44936305/161769319-f31d4953-7333-49de-af9a-11de1a0dffc7.png)

**Comment by kevinpapst** [comment]
> It would be practical if a permanently valid fiscal year could be defined. In our case e.g. 01.10. - 30.09.

Isn't that the case? You define the start date and then Kimai should use this date as fiscal year. No matter which year it is. 
Check the yearly reports, the start date should change

**Comment by kevinpapst** [comment]
In your case set "01.10.2020" and everything should be fine
