### ISSUE TITLE
Use the displayed hours precision for computing the total

### ISSUE THREAD

**Issue by m0wer** [kevinpapst/kimai2#3282]
**Describe the bug**
Kimai uses more decimals than shown in the bill for computing the total cost so for example, 0:50 minutes are converted to `0.833333...` which is used for computing the total cost, but then displays only the first two decimal places in the bill. So if the customer multiplies the displayed hours in decimal format by the houry rate, they might get a different number than the displayed in the bill.

**To Reproduce**
1. Log one time entry of 50 minutes at 100 monetary units per hour.
2. Create and invoice with time in decimal format.
3. Check the difference between the total cost and the result of multiplying the displayed hours by the displayed hourly rate.

**Additional context**
 - Kimai version: `1.19.5`
 - PHP version: `php:8.0.14-fpm-alpine3.15`

**Comment by kevinpapst** [comment]
AFAIK that is normal invoicing behavior. 
I am not changing the current behavior, there is a lot of information out there about rounding behavior in invoices.
Time with the base of 60 and money with the base of 100 add an additional layer of complexity.

Best approach to prevent that is to use a combination of matching rates and rounding rules, which will prevent such cases.
E.g. duration rounding of 15 minutes will simply not lead to such problems.
