### ISSUE TITLE
Marking invoice as paid results in an error when behind a reverse proxy

### ISSUE THREAD

**Issue by ttay24** [kevinpapst/kimai2#3283]
**Describe the bug**
I am running Kimai in a docker container on my server. I have a reverse proxy set up (using Caddy currently) to run under https and forward my requests to the Kimai instance running http, Whenever I try to mark an invoice as paid, I hit an error and the request is rejected. If I login to the instance outside of the reverse proxy (running http), that request will work. All other requests work fine under the reverse proxy.

**To Reproduce**
1. Create a timesheet
2. Click on Invoices
3. Enter search time range/other fields to pick up the timesheets from step 1. Hit Search
4. In the table on the invoices page, click the drop down menu on the row for the newly created invoice. Select "Waiting for Payment"
5. Click the drop down menu again, and this time select "Invoice paid"
6. Select a date and click 
7. See error
![image](https://user-images.githubusercontent.com/4239808/166162275-86eb48c7-9341-442d-a72c-4b3a04505aba.png)

**Logfile**
I'm not actually seeing anything in the logs when I run that request. Maybe it's being rejected before that and not showing up in the logs? Here's the network trace from the browser: 
![image](https://user-images.githubusercontent.com/4239808/166162354-6028c764-7686-4b4d-9d93-59faa9339103.png)

I will also add, it looks like the request for paid is trying to go to `http`. All other requests are correctly using `https`

**Additional context**
 - Kimai version: 1.14.1 stable (Ayumi)
 - PHP version: ?.?
 - Docker: 
     - Tag: kimai/kimai2:apache 
     - Hash: 96e317749942170c9761457d0c1fac1e55838f0dbda273afd104410223b017fd
     - It looks like this image was last updated 11 months ago
 - Device: Windows 11 via Chrome. Kimai instance is a docker container running on an Unraid server
 - Browser Chrome Version 100.0.4896.127 (Official Build) (64-bit)

Thanks for any insight! Please let me know if there's any more information I can provide.

**Comment by kevinpapst** [comment]
Update to the latest version and let me know if the error is still present.
