### ISSUE TITLE
Kimai 1.14.1: ${project.comment} wont be exported to Invoice anymore

### ISSUE THREAD

**Issue by sgaechter** [kevinpapst/kimai2#3285]
**Describe the bug**
I placed the variable "${project.comment}" in my Invoice document (*.docx). Before 1.14.1 the Project comment was placed instead of the variable (Sorry, I can't reproduce in which version it worked properly anymore...).
In this version, the variable stays unfilled in the exported invoice document:

![Invoices](https://user-images.githubusercontent.com/29682065/166314065-78bf4a0c-bbaf-41e0-b6fd-4c007636afd0.png)

**To Reproduce**
1. place variable "${project.comment}" in the Invoice Template
2. write something as a comment on a project
3. generate Invoice
4. see Invoice

**Logfile**
```
Docker: kimai2:apache --> "Missing logfile"
```

**Additional context**
 - Kimai version: 1.14.1
 - PHP version: 7.4.15
 - Device: Docker Container kimai2:apache from tobybatch
 - Browser: Any Browser.

**Comment by kevinpapst** [comment]
These values are only filled, if you select the project in the search. Did you do that?
Anyways: 1.14.1 is pretty old. Upgrade to the latest version and re-open if the bug still exists.

**Comment by sgaechter** [comment]
Hello Kevin. This did the trick... I could have sworn it didn't used to be this way. :-) Is there a way to get around this issue so I can bulk-generate the invoices without preselecting the project? 

Sorry, 1.14.1 is the version provided from tobybatch wih Docker container "kimai2:apache" The "apace-latest throws an error at the moment: https://github.com/tobybatch/kimai2/issues/377
