### ISSUE TITLE
TimeSheet > Activity* : Only one client activities are listed!

### ISSUE THREAD

**Issue by fedibelkacem** [kevinpapst/kimai2#329]
**Describe the bug**
Only first client activities are listed in the dropdown activity menu when editing a timesheet.

**To Reproduce**
1. Go to '/en/timesheet/create' or '/en/timesheet/<timesheet number>/edit'
2. Click on 'the Activity* field'
3. Scroll down into 'the menu'
4. You will find only one client activities listed, more precisely the first client!

**Expected behavior**
We expect all activities listed and grouped by clients.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Server: CentOS
 - Browser: Chrome, FireFox,the lasts.
 - Version of Kimai2: cloned/installed today.

**Additional context**
Tis bug is really BLOCKING!

**Comment by kevinpapst** [comment]
That is definitely not true, always check the demo first if the problem exists there: 
https://demo-v2.kimai.org/
If customer, project or activity are hidden, they won't be offered in the dropdown.
Can you create some screenshots from the customer/project/activity admin panels and the edit timesheet screen?

**Comment by fedibelkacem** [comment]
You are right. 
I create activities only in a project of the first client.
I'm really sorry.

**Comment by kevinpapst** [comment]
Thanks for your feedback 👍
