### ISSUE TITLE
Uncouple duration from date-time parts

### ISSUE THREAD

**Issue by andreaspollak** [kevinpapst/kimai2#3291]
**Is your feature request related to a problem? Please describe.**
No. I've used another desktop application before, which has this feature. 

**Describe the solution you'd like**
Add an additional field **billable duration** to increase transparency and  improve statistics level of detail. Track the whole spent time without further non-billable entry. Use it in customer reports.

**Describe alternatives you've considered**
I'm a new Kimai User and open for suggestions.
I'v tried Fixed Amount and Duration Plugin (https://github.com/glorpen/kimai-duration-plugin) which solved another Case
<img width="383" alt="Bildschirmfoto 2022-05-05 um 09 32 26" src="https://user-images.githubusercontent.com/1319839/166883671-cb34c259-d5d0-46e1-8e95-0500ce975ee9.png">

**Screenshot**
![Bildschirmfoto_2022-05-04_um_08_43_04](https://user-images.githubusercontent.com/1319839/166884601-1278cd31-5a68-426c-ac8b-7f1e9136cd05.jpg)

**Comment by kevinpapst** [comment]
Always interesting to see how other software works. Nevertheless in Kimai an entry is either billable or not. 
This can be changed on per record level.
If you have 9 hours of work and only 15 minutes billable, your work log description is much longer and you probably only want to share the 15 minutes part with the customer. 

I think the Kimai way is the better solution. 

The only thing that I could imagine is a UI solution to uncouple the duration input from the time inputs:
Currently changing the duration will automatically adjust the end.
I could imagine a solution where you can enter an arbitrary duration that does not get reflected in the date time parts.

**Comment by andreaspollak** [comment]
> The only thing that I could imagine is a UI solution to uncouple the duration input from the time inputs:
Currently changing the duration will automatically adjust the end.
I could imagine a solution where you can enter an arbitrary duration that does not get reflected in the date time parts.

I think this is a good compromise! 

In clockodo I had an option switch to decouple duration from start/end. Unlike Kimai, the clockodo entry form has a field for date, start time and end time, which is faster to complete the form.

**Comment by kevinpapst** [comment]
> clockodo

appreciate the feedback! 
but please do not compare a free open source software by a single developer with a +20 person company...

**Comment by andreaspollak** [comment]
> appreciate the feedback! but please do not compare a free open source software by a single developer with a +20 person company...

I appreciate and respect your work and it was not meant as a project comparison. There is already a plugin https://github.com/lduer/CustomTimesheetFormBundle with similar fields, like I mentioned.

Thanks!

**Comment by kevinpapst** [comment]
I do see some cool use-cases for that feature and I like the idea, but I have no plans to change this core behavior currently.

An entry has a duration, which is automatically calculated from end-begin.

Closing for now. 

Thanks for your sharing your ideas and input @andreaspollak 👍
