### ISSUE TITLE
Changing user timezone is not reflected in new tasks

### ISSUE THREAD

**Issue by petecooper** [kevinpapst/kimai2#3292]
**Describe the bug**
Changing user timezone is not reflected in new tasks.

**To Reproduce**
1. Confirm user timezone is correct (e.g. `Europe / London` in my example)
2. Create new task with record button, note timestamp, cancel task.
3. Change user timezone to another region (e.g. `Pacific / Fiji` in my example).
4. Create new task with record button, note timestamp, cancel task.

Screencast attached (safe for work, no audio, MP4)

[kimai2 timezone.mp4.zip](https://github.com/kevinpapst/kimai2/files/8630635/kimai2.timezone.mp4.zip)

**Logfile**
```
Empty logfile
```

**Additional context**
 - Kimai version: 1.19.6
 - PHP version: 8.0.18
 - Device: macOS Mojave 10.14.6
 - Browser: macOS Safari 14

Note: I am investigating why there is a 1-hour offset with new task creation, the `date.timezone` and user timezone are both `Europe / London`, so please ignore that part of the screencast.

**Comment by kevinpapst** [comment]
From your description I don't know what is wrong. I don't even understand what your issue is.
Please host the video somewhere and embed it here / share a link.

**Comment by petecooper** [comment]
https://www.youtube.com/watch?v=Ipeg80La47U (as above, safe for work, no audio)

**Comment by petecooper** [comment]
Got it - thank you very much, now I understand.
