### ISSUE TITLE
Remove Weekly working hours entry

### ISSUE THREAD

**Issue by 3isenHeiM** [kevinpapst/kimai2#3297]
**Is your feature request related to a problem? Please describe.**
There is no possibility to have only 1 entry (line) in the weekly working hours page.

The default view lists 3 lines, and I haven't found a button to remove a line fro; the page.

Being a freelancer, there are weeks where I register only 1 activity for the whole week. And I always have to fiddle around in order to save the timesheet.

**Describe the solution you'd like**

1. Besides the "Add" button, a "Remove" button, for the checked lines could be setup.
2. A setting allowing to define the default lines present on that page. 

**Screenshot**

![image](https://user-images.githubusercontent.com/26417172/167361605-63690a16-72e5-4a04-8584-5ada869435e5.png)

**Comment by kevinpapst** [comment]
Why do you need less rows? Empty rows will be ignored and not saved.

**Comment by 3isenHeiM** [comment]
Actually no, I need to have all the rows filled in order to save the timesheet.

**Comment by kevinpapst** [comment]
Please upgrade to the latest version, there was a bug about empty rows.
