### ISSUE TITLE
Configuration option to disable fixed rate and hourly rate from "edit timesheet"

### ISSUE THREAD

**Issue by mr-jingles** [kevinpapst/kimai2#330]
**Is your feature request related to a problem? Please describe.**
As of now Kimai2 offers many valuable features for freelancers. However to use it as a time tracking / attendance tool for companies some of these features need to be disabled. 
In the current master I didn't find a configuration option to disable fixed rate / hourly rate from the "edit timesheet" forms ,

**Describe the solution you'd like**
A configuration option to disable fixed and hourly rate from "time edit" form would be nice. Its already possible to disable the  "user rate" and "rate" widgets from the dashboard. :+1:  

**Describe alternatives you've considered**
   * Possibility to disable the invoice module altogether. Since it is not required if kimai2 is used as a time tracking and attendance software for employees within a company.

**Additional context**
   * none yet

**Comment by kevinpapst** [comment]
I am currently working on the configurable permission system and could need some help with testing and feedback to see if the solution fits your needs.

You can configure to:
- de-/activate to view rates for own user
- de-/activate to edit rates for own user
- de-/activate to view rates for other user
- de-/activate to edit rates for other user
- deactivate invoices

The most important part is here:
https://github.com/kevinpapst/kimai2/pull/424/files#diff-a4c4c3e459663533af7607848e15e457R56
and here is the docu:
https://github.com/kevinpapst/kimai2/pull/424/files#diff-627f9e7618137a3b4d52c91d3d8b4970

**Comment by kevinpapst** [comment]
I would appreciate your feedback on this one. If you don't have the time, could you let me know?
I will merge it by the end of the week and cannot promise further work on this topic in the next months.

**Comment by mr-jingles** [comment]
Hi - its on my ToDo list! Just came back from vacation and didn't have the time yet. I will try my best to provide feedback this weekend!

**Comment by mr-jingles** [comment]
Hi Kevin! 
I have tested the new permissions implementation. It works great for functional access rights. And totally solves my use case for disabling the invoice module. I can also disable the hourly rates which keeps the time input form clean and simple! :metal:

The console commands also work for promoting user roles. However its not directly obvious which roles are available without looking at the configuration file. A short list of available roles could help here.. but that's a minor.

One more small thing. Kimai hides every link / tab for which the user has no access. However this does not happen with links in the right side menu like - "user profile". I get an 403 exception page after clicking on the link.

Additionally to functional rights a more granular access control over resources such as projects would be required - this is already proposed with #366.

Thanks again - and yes a bit of absence from the computer is always very valuable! :smiley:

**Comment by kevinpapst** [comment]
Good point, I forgot the links in the right sidebar. Thats why testing and user feedback is so important, you get sometimes "blind" after working too long on a product.

Regarding the roles, [you mean this docu](https://github.com/kevinpapst/kimai2/blob/master/var/docs/users.md) ? I know reading docu sucks ;-)

**Comment by mr-jingles** [comment]
..well, yes docu!! :laughing: - I should have a closer look on it!

One question though - currently it is possible to assign roles which do not exist within the configuration. Is there a use case for this or should better be prevented?

I will leave feedback on #366!

**Comment by kevinpapst** [comment]
Are you missing more documentation or can you find anything else in the permission branch?

**Comment by mr-jingles** [comment]
I am fine with the permission branch!
