### ISSUE TITLE
The dates in the header row of the table on the Calendar page are not in the correct format for English (British English localizations)

### ISSUE THREAD

**Issue by Stewstews** [kevinpapst/kimai2#3311]
**Describe the bug**
Inside of the first (header) row of the weekly layout on the Calendar page are abbreviated days of the week (Mon, Tue, Wed, etc.) and the dates in a MMDD format.  Similarly, the Calendar title is showing as "Month, Day, Year".  For example, "May 16 - 22, 2022" on week view and "May 16, 2022" on day view.

For British English rather than American English localizations (e.g. En-GB, En-AU), the Day should always come before the Month.

Refer to locked conversation on https://github.com/kevinpapst/kimai2/issues/2492, where it looks like American English conventions were applied.

**To Reproduce**
• Go to 'My Preferences' and ensure that your Language is set to English
• Go to the 'Calendar' page
• Notice that dates inside of the header row and titles are improperly marked as MMDD, instead of DDMM.

**Additional context**
• Kimai version: 1.19.5 stable
• PHP version: 7.4.29
• Browser: Chrome 101

**Comment by kevinpapst** [comment]
Hey @Stewstews, thanks for your feedback!

I will add explicit configurations for en_AU, en_GB and en_US. 
Wikipedia is rather misleading on this topic: do you use `dd-MM-yyyy` or `dd.MM.yyyy` or `dd/MM/yyyy`?

**Comment by Stewstews** [comment]
> Hey @Stewstews, thanks for your feedback!
> 
> I will add explicit configurations for en_AU, en_GB and en_US. Wikipedia is rather misleading on this topic: do you use `dd-MM-yyyy` or `dd.MM.yyyy` or `dd/MM/yyyy`, for list views and the date chooser / input types?

As far as date formats, I'm not sure there is a difference between en_AU and en_GB.  For en_AU refer this link: https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/numbers-and-measurements/dates-and-time

Numeric dates are 'dd/mm/yyyy' or shortened to 'dd/mm/yy'.

Text / full dates are written as dd MMM yyyy, as in '17 August 2022'

**Comment by Stewstews** [comment]
> Can you please define the correct formats for `en_GB`:

I don't think there is a difference between en_GB and en_AU when it comes to date formats.

Would it be worth have a 'date format' selector independent of Language selection?  That way users can select their preference on separators (. / or -) and ordering of day, month and year.

Extending on this, are there scenarios where the date format could impact where a customer recipient may have a different localization than the user?  As far as I can recall, the invoice always shows as "yyyy-mm-dd" format.

**Comment by kevinpapst** [comment]
Thanks. I fixed it in the meantime.

> Would it be worth have a 'date format' selector independent of Language selection? 

Yes, at a later point.

> As far as I can recall, the invoice always shows as "yyyy-mm-dd" format.

Definitely: no. Invoices have a separate language setting.
