### ISSUE TITLE
Add another permission to be able to switch user in calendar view (#3314)

### ISSUE THREAD

**Issue by serotonie** [kevinpapst/kimai2#3316]
**Is your feature request related to a problem? Please describe.**
As a workaround to let my users filters the timesheets records of a customer/project, I'm already giving the "view_other_timesheet" permission to all of them (everybody is also teamleader).
It wasn't a problem since 1.20, because the timesheets menu is a bit hidden and not every users will always see it. Now that we have a big users choice-list in the calendar view, it could soon become a problem for me...

**Describe the solution you'd like**
It would be good to have a new entry in the settings to allow or not this choice-list to appear in the calendar view
OR
Add a permission to only allow certain users to see the said choice-list

**Describe alternatives you've considered**
At the moment, I just disable the "view_other_timesheet" for all my users, but they are now unable to get an overview of everything that was already done by a customer when they need to contact a colleague to know why certain things was done in a certain manner.

**Comment by kevinpapst** [comment]
My intuitive reaction is: you request doesn't make sense. 

You want to allow that your user can see other users timesheets, but at the same time don't want to allow it. Sorry, I don't get it.

What exactly are you trying to achieve?

**Comment by serotonie** [comment]
Hi Kevin,

I totally understand your reaction and I surely not addressing my problem with the right angle.

My end goal is to let every of my users filter every timesheets record of a customer/project to be able to follow along what was already done by the customer or for the project, but I don't want everybody to have a easy solution to be able to stalk a colleague by checking every of his timesheets entry.

I trust my team and I know that the probability of such thing happening is not really high so I decided to give everybody the permission to "view_other_timesheet", as the possibility of stalking is a bit hidden with this workaround (the Timesheets menu is not part of any of our processes, so my users shouldn't go to much in it).
Now with the choice list in the calendar view the thing isn't hidden at all any more and I know that it will come to delicate discussions if I let this at the view of everybody.

Hope that my goal is more or less understandable, if not it's halb so schlimm :)

**Comment by serotonie** [comment]
Yes, we're a little team of 5 people, so it would make no sense to split our customers/projects in smaller groups.
Comment function is not realistic in a real world situation, where everyone is running behind the clock to achieve to work that has be done. And what isn't important for a person could be it for another and vice versa :)

My need is really to have a feature being able to list every records for a customer/projects without every users being able to list every records of another given user.
Yes a very motivated user could still find out what did his colleague did by searching every timesheets record of the said colleague by every customer, but it would be much more time consuming.
I'm closing this feature request and will look into the plugin way.

**Comment by kevinpapst** [comment]
> My need is really to have a feature being able to list every records for a customer/projects without every users being able to list every records of another given user.

You can write a tiny script that queries the API with teamlead access, which simply shows all descriptions of all records.
Super easy to code, maybe an hour (without experience) to fetch the customers and then the filtered timesheets.
Check out the examples at https://www.kimai.org/documentation/rest-api.html

**Comment by serotonie** [comment]
It could be a good start point to finally learn a bit of php/symfony indeed :)
I just have to finish my custom excel exporter/converter in python first.

Thanks !

**Comment by kevinpapst** [comment]
No need for PHP / Symfony. Query the API with whatever you like. 
You could even use some bash-magic ... but Python sounds good as well.

**Comment by serotonie** [comment]
Indeed, but I'd like to be able to show the results in the same UI as the rest.
Is it theoretically possible with a plugin to extend the customer controller / twig template to add another form on this page that show this results ?
Or do I have to create a new menu entry for it ?

**Comment by kevinpapst** [comment]
New menu entry is much better, but you could also add new "action buttons" in the upper right or dropdown menu in the table. So eg. a new "Performed tasks" menu entry for each customer that links to a new page.

The DemoBundle should have most of the code, so the learning curve is smoother .

**Comment by serotonie** [comment]
Hi Kevin,

For my (very) custom excel exporter, I need a new button on the calendar view that call /schenkexporter/<kw>:<jahr>.
I managed to add this feature by modifying the `./templates/calendar/user.html.twig` like this :

`header    : {
                    left  : 'prev,next today{% if canDelete %} deleteButton{% endif %}, schenkButton',
                    center: 'title',
                    right : 'month,agendaWeek,agendaDay'
                },
...
                    schenkButton: {
                        text: 'Export Schenk',
                        click: function() {
                            const kw = $(".fc-week-number").text().replace("KW", "");
                            const jahr = $(".fc-center").text().substr(-4);
                            const urlToOpen = "/de_CH/schenkexporter/" + kw + ":" + jahr;
                            window.open(urlToOpen);
                        }
                    }`

Is it a way to do it a little less dirty within a plugin (https://github.com/serotonie/SchenkExporterBundle) ?

**Comment by kevinpapst** [comment]
Copy & Paste this to your project:
https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/Actions/CalendarSubscriber.php
