### ISSUE TITLE
Festbetrag/Fixed amount does not work

### ISSUE THREAD

**Issue by muadeep** [kevinpapst/kimai2#3322]
**"Festbetrag"/Fixed amount does not work**

Fixed amount is not saved or ignored. 
When I enter something and save it, after saving the number is gone.

A few months ago, it worked.
Maybe it's because of the switch from sqlite to mariaDB?

**Logfile**
Nothing regarding this problem.

**Additional context**
 - Kimai version: 1.20.1 and older
 - PHP version: 7.4.29
 - Device: Windows Machine
 - Browser: all

**Comment by muadeep** [comment]
I show a new entry via the modal window by clicking on the + in the upper right corner of the "My times" overview.

![Screenshot 2022-05-24 at 12-48-46 Zeiterfassung](https://user-images.githubusercontent.com/2182559/170017945-9edd3cde-5221-4c59-9647-5ab31c1f0b51.png)

**Comment by kevinpapst** [comment]
Works for me and never heard of that from someone else. 
Please test it in the demo and check if it fails there.
If you can make it fail, please include details how so I can understand your exact setup.

**Comment by kevinpapst** [comment]
I am closing this issue now due to missing feedback.

If you want to share more input / test results from the [demo installation](https://www.kimai.org/demo/), please feel free to comment and re-open.
