### ISSUE TITLE
New permission "view_all_teams"

### ISSUE THREAD

**Issue by de-sec** [kevinpapst/kimai2#3323]
**Is your feature request related to a problem? Please describe.**
We recently created a new role for users managing our projects - permission management works fine with one exception: we are not able to allow this role to see all teams created without being assigned to them. Background: The created role should be able to configure permissions at project level for all former created teams without being member of the specific team. 

**Describe the solution you'd like**
I'd suggest a new permission "view_all_teams" which is able to see all teams and their members in addition to the current "view_team" permission, which applies to the assigned teams only. 

**Describe alternatives you've considered**
The permission view_all_data would fix it but is not suitable for this scenario (prinicple of at least privilege) .

**Comment by kevinpapst** [comment]
This does get a 👎 from my side.

These permissions are checked very low level and overwriting them somehow with a new permission might or might not be easily. There is already the solution to add the user to the team. I leave it open for a while to see if anyone else is interested.
But I believe this is a case for the 80/20 rule.

**Comment by lllp1** [comment]
I also report a need for such a feature
