### ISSUE TITLE
LDAP - Multiple domains

### ISSUE THREAD

**Issue by aramilialon** [kevinpapst/kimai2#3327]
**Is your feature request related to a problem? Please describe.**
We are trying to use Kimai for multiple companies, but we would not like to use internal credentials because every company has ad Active Directory in place

**Describe the solution you'd like**
We would like to have the possibility to configure multiple LDAP backend so that we could provide a single instance of Kimai for more companies

**Describe alternatives you've considered**
I have already tried to use both oAuth and LDAP togheter, but we are going to implement a third company and... Well, I'm out of options for centralized credentials :)
Jokes aside, I have also tried to use OpenLDAP to create an LDAP proxy, but since all the companies has Active Directory and different binding users, even if I managed to join all the AD trees in a unique tree I still cannot walk through all the edges

**Screenshot**
Quite simply in the local.yaml configuration file having the opportunity to define multiple LDAP servers:

> kimai:
>    ldap:
>        server1:
>            [...]
>        server2:
>            [...]
>        server3:
>            [...]

**Comment by kevinpapst** [comment]
Not sure which issue you are trying to solve. Why would multiple companies even share one Kimai?

Anyway: you see that this is a very rare edge case issue and will not be supported out of the box.

If you want to buy support time, I am happy to help, you have my email.
