### ISSUE TITLE
Project end date problem

### ISSUE THREAD

**Issue by rbuehler-teletrend** [kevinpapst/kimai2#3341]
**Describe the bug**
Let's assume you want a project that starts on 01.01.2022 and ends on 31.12.2022 (including both dates), so you just use the date picker to click the desired dates without specifying the time. Kimai will add 00:00 as time for all dates. However, if 00:00 is defined, Kimai will omit the time in the project overview or project detail view so actually it looks like the project would run from 01.01.2022 to (and including) 31.12.2022.
![grafik](https://user-images.githubusercontent.com/54700498/171632500-ec3d49bd-4331-4128-be75-c9d12bb479fd.png)
But in fact the project runs from 01.01.2022 00:00 till 31.12.2022 **00:00**. So, except for the first minute of the day, on 31.12.2022 it won't be possible to log time to this project.

I wonder if it is actually required to define a time for project start and stop. I'm not able to see a use case where it would be reasonable to define the time as well. In this case it could be changed the way that only dates but no times are defined and Kimai always counting full days. Another option would be a checkbox next to the input fields or a global Kimai setting to allow/disallow counting full days only.

A workaround is to define the stop date with the time 23:59 (which requires additional effort and manually entering the value as the date picker would only allow to chose minutes in steps of 15). Kimai will then present (in my opinion useless) additional time information:
![grafik](https://user-images.githubusercontent.com/54700498/171632991-59f79f0a-d2f9-4d9a-b310-ce760c14f0ed.png)

Or you define the end date 01.01.2023 to make it work until (and including) 31.12.2022 but the end date shown is of course wrong:
![grafik](https://user-images.githubusercontent.com/54700498/171633269-a16f44d7-0142-4ea8-92c4-a900d7c10b97.png)

**To Reproduce**
see description above

**Logfile**
no log

**Additional context**
 - Kimai version: 1.20.2
 - PHP version: 7.4.3

**Comment by kevinpapst** [comment]
> Or you define the end date 01.01.2023 to make it work until 31.12.2022 but the end date shown is of course wrong:

Which is of course correct. End date 01.01. is not the same as 31.12. 

I do understand your point... but: 
it is your opinion that end date 01.01 means end of the day and not beginning of the day.
Or maybe it is me and I am too long working with dates and my view shifted away from project reality.

Id there some kind of (more or less official) definition that says project end date is end of the day?

I guess this is more of a philosophical question than anything else. But I am happy to discuss this longer and see what others think.

**Comment by rbuehler-teletrend** [comment]
You're right, this is a question of definition and I don't know of any official definition (neither am I any expert in such matter).
But my logic tells me that the end date is normally inlcuding and that's how I see it in various other applications as well.
After all, if somebody tells me to finish something by date X that normally includes date X. So I don't suppose the other person expecting me to finish it the day before X.

**Comment by rbuehler-teletrend** [comment]
This is far from something "official" but the best I could find for the moment: https://support.preceden.com/article/18-inclusive-vs-exclusive
Their service can be used to create project timelines and roadmaps and as they write their end date definition is including.

**Comment by rbuehler-teletrend** [comment]
That looks like a good solution. :)
That way it would still be possible to set times if needed for some reason and you could probably still use the same date picker without modification.

**Comment by kevinpapst** [comment]
In 2.0 all three dates (start, end and order) will be plain dates without time.

Start and end date will be handled "inclusive".

**Comment by kevinpapst** [comment]
Can be tested in the demo, read more at https://github.com/kevinpapst/kimai2/pull/2902

Closing
