### ISSUE TITLE
Gmail blocking activation / password reset emails

### ISSUE THREAD

**Issue by skadarnold** [kevinpapst/kimai2#3354]
This bug seems to have happened sometime between updating from a 1.12 era to a newer 1.20.1.  When kimai sends the activation to a gmail account, the email is totally blocked. There is no trace of the email even within the spam or other filtered folders. Only once in testing have I seen the email arrive in inbox, just to totally disappear seconds after. It seems something about the email or the way it is sent is triggering gmail to block it entirely from the inbox. I have tested this on several different gmail accounts, and two different smtp mail servers. Both smtp servers are provided by Bluehost, and were working fine on the previous version of kimai. When I send activation and password reset emails to an email outside of gmail, everything seems to be working perfect. Outside of gmail, the message arrives every time. All hosting is being done with Bluehost. 

I am not sure if this is a fault in kimai, or just a combination of things from the way Bluehost works and is sending these emails and the way gmail decides to block things. But considering I was able to recreate this twice, I am curious if there is something in the email formatting that might have changed that in combination could trigger gmail to block. 

The log is not showing any errors, and it seems the smtp is working properly. I have looked through several settings in gmail and I am not able to find where these messages are going too.

**Comment by kevinpapst** [comment]
Works totally fine, just tested (sent via sendinblue.com):
<img width="1346" alt="Bildschirmfoto 2022-06-11 um 00 11 12" src="https://user-images.githubusercontent.com/533162/173157319-77b7383a-db6c-4965-b314-2c92e6137707.png">

I am sending hundreds of password forgotten emails daily and never heard that complaint.
The reason for emails that "get lost" is in 99% of all cases fault of the sending side.
