### ISSUE TITLE
Disable old/not used Customers

### ISSUE THREAD

**Issue by mr2017x** [kevinpapst/kimai2#3364]
Hi :)

as easy at it is named: Project is done, Customer is gone (for this time) - let it go out of the drop-down(s), maybe a simple checkbox - disabled - in customers company settings? :)

**Comment by BeckeBauer** [comment]
Have you tried to change visibility of the customer?
![image](https://user-images.githubusercontent.com/51003649/174679604-5174d1a9-0bd0-4997-a134-0851accdf9ed.png)
