### ISSUE TITLE
e-mail with information that working time has not been entered

### ISSUE THREAD

**Issue by lllp1** [kevinpapst/kimai2#3379]
1. Is there a function that will automatically send an email to the employee with the information that he or she has not completed the working hours, e.g. once a week?
2. Is there a function that will automatically send an email to PM with information that an employee from his team has not completed the working hours, e.g. once a week?

**Comment by kevinpapst** [comment]
This is mainly a duplicate of https://github.com/kevinpapst/kimai2/issues/1810

Please add your comments there.
