### ISSUE TITLE
New common field "nature of project" oder meta-fields usable by filter

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#3382]
**Is your feature request related to a problem? Please describe.**
We use a meta field to define the nature of a project.
For monthly and annual statistics or a corresponding export for evaluation in Excel, it would be necessary to be able to filter the meta field. In the statistic costs and used hours are displayed. Great would be to include as own value the expenses.

Due to the amount of data, it is currently not possible to export more than 2 months of compltete bookings to Excel.

**Describe the solution you'd like**
Add a common datafield to Kimai to describe the  nature of a project. This field must be usable by filter.
Maybe add this as a statistic function to Kimai.
or
Make metafields available in the filter function for exporting the data

**Comment by kevinpapst** [comment]
You can filter for meta-fields as described in the docs.
This works in timesheet listings, in export and invoice screen.
Please read https://www.kimai.org/documentation/timesheet.html#filter-and-search

**Comment by HeinzWuert** [comment]
Additionally, you can filter for by using a search phrase like location:homeoffice. This would find all entries with the custom field location matching the term homeoffice.

In which position the item must be placed? Under "search item" the value has no effect.

**Comment by kevinpapst** [comment]
The custom field must be attached to the timesheet and then you can put that phrase into the "free search term " field.
You cannot filter for meta-fields of projects/customers...

**Comment by HeinzWuert** [comment]
_You cannot filter for meta-fields of projects/customers...__
__
but this would be necessary.

**Comment by HeinzWuert** [comment]
Finally, maybe a common field: **nature of project** or **kind of project** is interesting not only for us, as long as meta fields are not usable.

**Comment by kevinpapst** [comment]
I am not planning to add new fields to the search, but I think there is a more generic solution.
What do you think about adding a feature, which allows to select `tags` for projects.
These tags would be forced for every timesheet recorded with this project.
As you can already filter for tags, I believe this would solve your issue as well!?

**Comment by HeinzWuert** [comment]
Great idea and for our use absolutely ok!
Thanks a lot!

**Comment by kevinpapst** [comment]
Meta-fiel plugin for next version #2902 will include a "Tags-autotype" field that can be used with customer, project and activity. Can be tested at https://demo-branch.kimai.org

<img width="721" alt="Bildschirmfoto 2022-08-11 um 00 14 41" src="https://user-images.githubusercontent.com/533162/184029931-15fe0351-30d4-4728-bafa-2aac000c08ac.png">
<img width="1328" alt="Bildschirmfoto 2022-08-11 um 00 20 49" src="https://user-images.githubusercontent.com/533162/184030562-76b6caa7-5d1a-43cb-a3da-d7353eaf3865.png">
<img width="737" alt="Bildschirmfoto 2022-08-11 um 00 21 04" src="https://user-images.githubusercontent.com/533162/184030595-c368225c-9f8b-44fd-a2bc-bd58d2e7af81.png">
