### ISSUE TITLE
Customer Onboarding - check boxes

### ISSUE THREAD

**Issue by mr2017x** [kevinpapst/kimai2#3397]
Hi Kevin,

thanks for your work (i have to say it once again).

As in the discussions before you know i am thinking about integrations between specific pieces of software but this one is actually about customers integration. It isn't urgent but maybe also worth to think about: Customers onboarding and integration, therefore i think about check boxes like "customer agreed to rates" with date and comment and "customer signed gdpo compliance" with check and date.

But behind that maybe it would be cool to give a function which gets sent out directly to customer on it's creation (which needs to be adjusted and sent manually, to prevent issues with not fully configured data or so.)

So it's a twice or thrice parted thing. 

Thanks again :)

**Comment by kevinpapst** [comment]
I am only commenting to the checkboxes part...

You can use the custom fields plugin to create both checkboxes and/or date-time fields and/or text-fields.

Kimai core cannot have fields for every single use-case and that is the perfect use-case for the custom-fields.
I would propose adding a date field. If it is empty it means "customer did not yet agree", if it has a value it means "customer agreed on that date".

So this can already be solved with existing features.

**Comment by kevinpapst** [comment]
Oh and thank you for your kind words! Appreciate it 👍
