### ISSUE TITLE
Input with dropdown to jump to a dedicated page

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#3412]
When you have several invoices (over the years) and you want to browse through them (without using the filter), it can be somehow cumbersome since you can go only to the first or last page or in single steps

![image](https://user-images.githubusercontent.com/51003649/178680031-b4741d1a-5398-451c-9897-d9cb206f4c72.png)

Therefore, a drop down menu would be handy that gives the opportunity to select any available page.

**Comment by kevinpapst** [comment]
The same pager is used everywhere in Kimai. I don't really see a reason for a dropdown, which could easily get too big and too slow if if would be used in all places (having hundreds or thousands of pages of timesheets isn't unusual).

But someone could add an input, which would allow to enter a dedicated page number (same can already be done by changing the URL, but that is less user-friendly).

**Comment by BeckeBauer** [comment]
Understood; cannot argue the point that such a change would also effect (a speedy) timesheet selection (and could get even confusing when having thousands of timesheet pages) - I can live with the URL "manipulation" which I did not realise so far (good workaround)

**Comment by kevinpapst** [comment]
Not a bad idea, but so many other things are waiting... Closing for now.
