### ISSUE TITLE
Changes could not be saved: [503] Service Unavailable | Kimai 1.21.0

### ISSUE THREAD

**Issue by GaneshKandu** [kevinpapst/kimai2#3417]
**Describe the bug**
Changes could not be saved: [503] Service Unavailable
![image](https://user-images.githubusercontent.com/12833130/179194153-230cafa2-9f69-4efd-9e73-a1ba5b036e4c.png)

**To Reproduce**
1. Go to admin dashboard
2. create project and save
3. See error

**Logfile**
```
Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.

No "var/log/prod.log" file generated
```

**Additional context**
 - Kimai version: 1.21.0
 - PHP version: 7.4.30
 - Device: Linux 
 - Browser [e.g. Firefox 81, Chrome 85, Safari 14] Firefox 102.1.2

Error dispatching request to : , referer: en/admin/project/
AH01067: Failed to read FastCGI header, referer: en/admin/project/

**Comment by kevinpapst** [comment]
Please re-open if you have more infos. Unless then, test the demo. Does it work there? No: you found a bug. Yes: it is an environment issue on your end.

**Comment by GaneshKandu** [comment]
It was server configuration issue in CPanel related to LSAPI.
Deleting .htaacess of public_html works.

**Comment by kevinpapst** [comment]
That is a weird problem 😁 

Thanks for sharing your solution 👍
