### ISSUE TITLE
503 error with PHP 7.4 under 1.21

### ISSUE THREAD

**Issue by motiosw** [kevinpapst/kimai2#3432]
**Describe the bug**
I've updated Kimai yesterday to the newest version. After adding some entries, the system looked fine. But by editing an entry in the calendar, the system got my an pop-up 503 error. After refreshing the page I couldn't reach Kimai at all (503 server error page).
I switched to PHP 8 an the error doesn't occur anymore.

**Logfile**
2022-07-21 20:49:39 | Error | X.X.X.X | 503 | PATCH /api/timesheets/16979 HTTP/1.0 |   |   | 1.31 K | SSL/TLS-Zugriff für Apache
2022-07-21 20:49:42 | Error | X.X.X.X | 503 | GET /de/calendar/ HTTP/1.0 |   |   | 1.31 K | SSL/TLS-Zugriff für Apache

**Additional context**
 - Kimai version: 1.21 
 - PHP version: 7.4
 - Device: Ubuntu 18.04 Server
 - Browser: Safari 15.4

**Comment by kevinpapst** [comment]
Glad you could solve the issue. I guess the cache was not cleared entirely after the update.
There is no general issue, but I appreciate your feedback!

If that happens again, try to `rm -r var/cache/prod/*`.
