### ISSUE TITLE
Trashbin hovering/sticky at side top

### ISSUE THREAD

**Issue by motiosw** [kevinpapst/kimai2#3433]
**Is your feature request related to a problem? Please describe.**
I like the new feature at the top, to delete entries by dragging them into the delete button at the top of the calendar. The problem with that is, that if I want to delete an entry at the bottom, the delete button isn't shown anymore.

**Describe the solution you'd like**
You could make the menu sticky, this way it would be always reachable.
In addition to that, it would help to have a delete button in the edit dialog (click on an entry).

**Comment by kevinpapst** [comment]
Next major release #2902 will bring a context menu (with right click) to every calendar entry.
Which fixes your request, just in a much better way 😄
