### ISSUE TITLE
Group timesheet by project

### ISSUE THREAD

**Issue by dirk-graetz** [kevinpapst/kimai2#3460]
**Is your feature request related to a problem? Please describe.**
I have a client (agency) for whom I manage several projects.

**Describe the solution you'd like**
For the invoice document "timesheet" an option for the "sum calculation" like "one entry per record / group by project"

**Describe alternatives you've considered**
The export "PDF -> default" gives the information about the projekt, but does not group the projects. So every entry must be assigned to a project.

**Screenshot**
![grouped](https://user-images.githubusercontent.com/9319211/182970441-d6941abf-b690-4fd8-a933-11b92c03f1d4.jpg)

**Comment by dirk-graetz** [comment]
Alternative: do not show the user but the project:
![projects](https://user-images.githubusercontent.com/9319211/182971213-a4f66824-18e2-4039-872a-19c6d9618e05.jpg)

**Comment by kevinpapst** [comment]
Thats what custom invoice templates are for:  https://www.kimai.org/documentation/invoices.html#invoice-document

You can create custom export templates as well, if you prefer that over invoices. 

And you can get paid support if you can't do it yourself. But I do not see anything here that can be done in Kimai.

**Comment by dirk-graetz** [comment]
I just need the same like in Kimai V1!!
![kimai_v1](https://user-images.githubusercontent.com/9319211/182973364-304e17cd-a5ce-4fa4-b3d2-f9cf0f614def.jpg)

**Comment by dirk-graetz** [comment]
Hi Kevin,
I just need the output like in Kimai v1!



Kind regards
Dirk

Von meinem iPhone gesendet
