### ISSUE TITLE
Kimai V2: MyTimes, Extended Settings

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#3461]
V2.0 looks good!

MyTimes page, the last row: There is the option "Extended Settings"
It would be great to have a second line line with "Expenses" if this module is activ.
Since expenses are linked to entries, it would be logical and easiest to assign the expenses directly when entering the working time in MyTimes.

The CREATE button in MyTimes as the main button on this page should be more distinctive. What about short cuts, in this case the  + button?

**Comment by kevinpapst** [comment]
Keyboard shortcuts were added in a recent release. But those currently need a trigger key, see:
https://www.kimai.org/documentation/keyboard-shortcuts.html

Expenses is a different topic. I know your wish, no need to repeat it here again. 
Already covered in the plugin repo.
