### ISSUE TITLE
Sometimes difficult to see Main Menu Scroll-bar on Left

### ISSUE THREAD

**Issue by zeezhao** [kevinpapst/kimai2#3473]
**Describe the bug**
Because the Menu on left is in black, sometimes it is difficult to see the scroll-bar. Hence can not always get to System Menu.

**To Reproduce**
3. See error

**Logfile**
```
Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
```

**Additional context**
 - Kimai version: 1.22.1
 - PHP version: 7.4.15
 - Device: Windows 10
 - Browser: Firefox 103.0.1
<img width="168" alt="kimai-menu" src="https://user-images.githubusercontent.com/51227714/184873109-0c7eeb3e-e693-47ef-9b6f-c972add76354.png">

I have also seen this in previous versions.

**Comment by zeezhao** [comment]
<img width="168" alt="kimai-menu" src="https://user-images.githubusercontent.com/51227714/184872801-9cc122c5-6c09-4d40-ae30-6f5ee418081d.png">
I have also noticed this in previous versions.

**Comment by kevinpapst** [comment]
Interesting problem, it never occurred to me that someone would use the scrollbar. What about using the mouse wheel instead?

Closing, as the next major release #2902 uses another design, which has one vertical and one horizontal layout. Not spending more time to work on that issue.

**Comment by zeezhao** [comment]
Same issue using tracking pad on laptop. Hence the reason I use scrollbar. 
Please what is the keyboard sequence to scroll, as I can't use down-arrow either. Thanks
