### ISSUE TITLE
Use "Content-Disposition: inline" for PDF previews

### ISSUE THREAD

**Issue by LiaraAlis** [kevinpapst/kimai2#3481]
For me it is very annoying when you have to download the PDF invoice every time before you want to see the preview.
I would be very happy if the preview (for PDF files) is opened with "Content-Disposition: inline" so that the browser can open the PDF itself without downloading it. This should only be the case for the preview, not for the save function.
This could be added for invoices as well for the timesheets.

If you want I can make a PR for this. Or is there any reason that the download for the preview is necessary?

**Comment by kevinpapst** [comment]
I am pretty sure there was some issue, but I honestly cannot remember why I have chosen the download. 

Let's give it a try 👍
