### ISSUE TITLE
Timesheet without project

### ISSUE THREAD

**Issue by EnMaster** [kevinpapst/kimai2#3483]
I have several clients (just a simple private person or small company) without the need to create a project, for example for "ASSISTENCE" or "CONSULENCE". Is possibile to create a timesheet without a project?

At the moment i use this procedure for ALL my clients
client: AAAAAA
project: ASSISTENCE
activitie: ASSISTENCE

**Comment by kevinpapst** [comment]
I know the structure is not ideal, but changing this would lead to so many problems inside the software, that I have to reject this idea.

I tried to make activity optional and that already took a lot of time, while still not all bugs where found & fixed. So I am afraid that this will not be possible in the near future.
