### ISSUE TITLE
Stylesheet in export pdf layout

### ISSUE THREAD

**Issue by LiaraAlis** [kevinpapst/kimai2#3485]
I suggest to move the stylesheet for the export pdf layout into a scss file.
Or is there a reason why the stylesheet in the export timesheet pdf is written inline and in the invoice pdfs the `encore_entry_css_source()` function is used?

(feature request is not really the right topic, but bug isn't too 😅)

**Comment by kevinpapst** [comment]
Sounds like a feature request to me 😄 

I am fine with the proposed change. Want to work on a PR?

**Comment by kevinpapst** [comment]
Let's target the next major, I want to avoid too much noise in the current release. 
There are so many invoice and export templates around, I don't want to risk breaking anything in this release.

**Comment by LiaraAlis** [comment]
Good idea. This goes perfectly with my suggestion in #3484. 😊

**Comment by kevinpapst** [comment]
Available in #2902
