### ISSUE TITLE
exceeding the time quota possible in calendar view

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#3487]
**Describe the bug**
Use time kontingent (tried it with monthly)
Calendar view: By dragging the handle of an entry, the number of hours can be extended beyond the quota.

**Comment by kevinpapst** [comment]
confirm: that happens for all monthly budgets, when records change the month

fixed (hopefully without breaking other rules) in #3489

**Comment by HeinzWuert** [comment]
No, this happens also without changing the day or month. Only with using mouse and drawing the duration results in exceeding the limit!

**Comment by kevinpapst** [comment]
True, that is another bug related to the API.

And I found one more: changing the project from a non-billable to the billable one was also possible when overbooking.

WOW... thank you so much for testing 👍
