### ISSUE TITLE
My timetracker is now an online pharmacy

### ISSUE THREAD

**Issue by Nandi72** [kevinpapst/kimai2#3492]
Hi,

my self-hosted timetrack install is now an online pharmacy - had this issue previously on some WP installs.

What can I do to restore the site?

Thanks,
Andy

**Comment by Nandi72** [comment]
... and obviously desinfect the install...

**Comment by kevinpapst** [comment]
Well if that happened before, than you should probably change the hoster or setup the server again.
And you should ask yourself if self.hosting is a good idea...

The solution is easy: www.kimai.cloud
