### ISSUE TITLE
Weekly working hours: New entries do not take grace period into account

### ISSUE THREAD

**Issue by Jelle-S** [kevinpapst/kimai2#3495]
**Describe the bug**
When using the weekly working hours (quick entry), it doesn't seem to take the grace period into account. When I try do add an entry today (01 Sept 2022) for 01 Aug 2022, the input element is disabled

**To Reproduce**
Use these settings for your lockdown and grace periods:
![image](https://user-images.githubusercontent.com/1828542/187851189-8fe554e2-664d-42e7-81fd-b3f99b87c0f1.png)

And on the first day of a month, try create a time entry for the first day of last month. The input will be disabled, while existing time entries are still editable. Adding them through "My Times" or through the calendar does work.

**Logfile**
N/A

**Additional context**
 - Kimai version: 1.22.1
 - PHP version: 8.1.9
 - Device: Ubuntu 20.04.4 LTS (Focal Fossa) 64-bit Laptop 16 inch
 - Browser: Firefox 104.0

**Comment by kevinpapst** [comment]
Hm, maybe the permission check is missing something?

This is used to de/activate the form fields:
https://github.com/kevinpapst/kimai2/blob/master/src/Voter/TimesheetVoter.php#L229

This is used for validation:
https://github.com/kevinpapst/kimai2/blob/master/src/Validator/Constraints/TimesheetLockdownValidator.php#L34

Do you have time to look into it?

**Comment by kevinpapst** [comment]
One question: is it possible that you have `00:00:00` configured as default start time (see below, here "now")?
If so, would changing that value to `00:00:01` fix the issue as well?

<img width="455" alt="Bildschirmfoto 2022-09-01 um 17 06 54" src="https://user-images.githubusercontent.com/533162/187948286-e982fc97-0107-4c7b-a8d8-a2be47930b31.png">

**Comment by Jelle-S** [comment]
No, the default start time is left on the default value:
![image](https://user-images.githubusercontent.com/1828542/188077294-f00ec502-6874-4516-9799-51fa167dbaa0.png)

**Comment by Jelle-S** [comment]
Created https://github.com/kevinpapst/kimai2/pull/3504 to fix the issue.

**Comment by kevinpapst** [comment]
> Problem seems to be that the (empty) timesheets that are created for the quick entry (so for the new rows) by default have their start time to the selected date, at midnight 

I don't quite understand. Empty entries should be set to this configured time and not to midnight:
https://github.com/kevinpapst/kimai2/blob/master/src/Controller/QuickEntryController.php#L135

**Comment by Jelle-S** [comment]
Weird, when I add
```
var_dump($tmp->getBegin(), $beginTime);
```
Below that line, the output I get is:
![image](https://user-images.githubusercontent.com/1828542/188126886-bac0442e-43ba-4fc0-9c18-56a1dac0d2c6.png)

**Comment by kevinpapst** [comment]
Let me investigate a bit on that. Not that I against your two character bugfix 😁 just want to see if there is some underlying issue hidden.

**Comment by Jelle-S** [comment]
If I have the time I'll try to investigate too, but I'm a bit swamped atm. Either way, that bugfix still is valid for when someone does set the start time to midnight I think.

**Comment by Jelle-S** [comment]
I've been doing some digging through the documentation, and my guess is the problem lies with the core PHP date and time format parser. As t[he documentation](https://www.php.net/manual/en/datetime.formats.relative.php) says 'now' is "simply ignored", which makes sense for `strtotime` and for constructing a new `DateTime` object, but makes no sense if the context we're using it. Not sure if we stumbled upon a core PHP issue, or if it's by design and the core devs know about it...

**Comment by kevinpapst** [comment]
Uff, that is weird to say at least:
<img width="427" alt="Bildschirmfoto 2022-09-02 um 15 25 02" src="https://user-images.githubusercontent.com/533162/188155618-504ecdf6-9e54-4a5e-9b55-93f68c6e8f85.png">

And it is entirely new to me and opens up a stairway to a dark cellar which I I don't want to enter right now^^

I'll keep you posted, but likely not today, as I have too much on my desk as well ... and I guess we have a month time to fix that (for you) 😁

**Comment by Jelle-S** [comment]
Yeah I've got a month.
Either way, as I said, the PR is still valid for when (for example) someone wants timesheets to start at 9AM by default, and wants the lockdown period from the first of the month at 9AM as well.

**Comment by kevinpapst** [comment]
Yep, I am with you. 
But when I merge it first, my subconsciousness will immediately bury the `now` issue.
So I keep the PR open until after that check.

**Comment by kevinpapst** [comment]
Here is the fix for the other part of this issue #3511
