### ISSUE TITLE
Refactoring invoice/export templates for v2

### ISSUE THREAD

**Issue by LiaraAlis** [kevinpapst/kimai2#3510]
As discussed in #3484, we should completely rework the export and invoice templates for v2.
Here we should discuss what's the best way is. The goal should be to make the templates as uniform as possible, especially with regard to naming Twig blocks.

My first idea is to add a base layout for pdfs that can be extended for every template.

**Comment by LiaraAlis** [comment]
At the moment I'm very busy with private stuff. But I have not forgotten this.

**Comment by kevinpapst** [comment]
Giving this another thought: we have to avoid BC breaks at any costs in this area.

So if this going to be worked on, we need fallback-blocks which call the ones with the new names.

**Comment by kevinpapst** [comment]
I am closing here for now. If you still want to contribute, I am happy to discuss possible changes!
