### ISSUE TITLE
Tax return statistics

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#3513]
Every ending year all freelancer ask for a printout of their own annual turnover and a list of the kilometers driven with the reimbursed share.
The following data should be included based on the configured financial year:
- the monthly turnover of the user
- the total of the year
- the monthly km and the amounts reimbursed
- the total km and reimbursement

Such a statistic fits perfectly into the layout of the upcoming V2.0

**Comment by kevinpapst** [comment]
Jurisdiction across the globe is not the clear on that topic.

Besides: Kimai does not know anything about driven kilometers.
To me that is a custom report, that needs to be tailored to your needs.

> Such a statistic fits perfectly into the layout of the upcoming V2.0

Nice try 😁
