### ISSUE TITLE
Modal Entry doesnt load in Chrome 105

### ISSUE THREAD

**Issue by petrk94** [kevinpapst/kimai2#3514]
**Describe the bug**
I tried to install Kimai the first time without problems, Super Admin was set up and login work via Web Interface, all pages are accessible, but when I want to add something, new client, new project, new task, always a modal appear for entering the data, but it doesnt get loaded at all. See Screenshot. I tested it in Firefox 104, no problems.

Hope someone can help me to get this run. Thanks

**To Reproduce**
1. Go to ['demo.kimai.org'](https://demo.kimai.org/en/timesheet/)
2. Click on Timer to add a new entry
3. See error, the modal is not appearing at all, only the modal header and modal footer, the modal content doesnt get load.

**Logfile**
```
Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
```

**Additional context**
 - Kimai version: Tested with 1.23 demo site and 1.22 version on my server
 - PHP version: my Server has PHP 7.4
 - Device: Windows Desktop
 - Browser Firefox 104 work, Chrome 105 doesnt work

![2022-09-04_14-24-53](https://user-images.githubusercontent.com/19719052/188313472-f580297a-14ba-4b69-b287-d38389c1ab74.png)

**Comment by kevinpapst** [comment]
Please use [discussions](https://github.com/kevinpapst/kimai2/discussions) for such questions.

Whatever it is, it is not a Kimai bug. 
Check your developer/browser console to see which error is reported / likely a browser extension that is causing the issue.

**Comment by petrk94** [comment]
@kevinpapst 
I identified the problem, its relying on a js which is provided by the FasterWeb plugin by instant.page, this cause the problem that the kimai modal is not loading. Take a look, they will check what the problem is, the developer console, unfortunately, didnt throw an error to work with. I have tested the extensions step by step to see where the problem is.

https://github.com/instantpage/instant.page/issues/114

**Comment by petrk94** [comment]
A workaround would be, to make a setting to disable the modal view and just open /create as own page.
I tried this by opening the create page as a new tab, while the fasterweb extension was enabled, the modal function didnt worked, but the create page still worked. 

![image](https://user-images.githubusercontent.com/19719052/188318569-1fe351ad-f8c5-4eca-9d40-aa1bb1694e87.png)

**Comment by kevinpapst** [comment]
Thanks for your feedback! 
Never heard of instant page, I hope you can deactivate it for the Kimai domain.
