### ISSUE TITLE
Unable to reload cache after update to v1.24.0

### ISSUE THREAD

**Issue by varunpan** [kevinpapst/kimai2#3516]
**Describe the bug**
I updated my docker container to the latest image, v1.24.0 and getting an error when reloading cache.
I attempted to manually rebuild the cache and getting the same error when running the cache:clear and cache:warmup

**To Reproduce**
1. Updated docker image to v1.24.0
2. reloaded cache: `docker exec -ti kimai /opt/kimai/bin/console kimai:reload --env=prod`
3. See error:
```
In DefinitionErrorExceptionPass.php line 54:
                                                                                                               
  Cannot autowire service "App\Utils\MPdfConverter": argument "$cacheDirectory" of method "__construct()" is   
  type-hinted "string", you should configure its value explicitly.
```

**Additional context**
 - Kimai version: 1.24.0
 - PHP version: 8.1.9
 - Device: Linux 5.18.0-0.deb11.3-amd64 Debian
 - Browser Firefox 104

**Comment by kevinpapst** [comment]
I do not provide docker images or support for it.
Please read the official docs at https://github.com/tobybatch/kimai2 before posting the next question there.
