### ISSUE TITLE
Add "Go to today" button in date/time picker

### ISSUE THREAD

**Issue by Sarmingsteiner** [kevinpapst/kimai2#3520]
Since we are often copying/adding/editing entries from/for the past, a button such as "Go to today" in the date/time picker would be very helpful.

**Comment by kevinpapst** [comment]
The next version #2902 brings a changed & improved UI, I am not trying to optimize anything in the old view by now.

BUT:
You can click the date icon, which will pre-fill the datetime field with "now". 
And then you can open the date picker, whoc month switched to today.
