### ISSUE TITLE
calendar  quick entry does not copy previous entry description like it used to

### ISSUE THREAD

**Issue by aldas** [kevinpapst/kimai2#3524]
Previously when you dragged activity from "Restart one of your last activities" on calendar view into your calendar it would copy the description of previously added activity.  This does not happen in `1.22.1` version and that dragged entry has empty description to start with.

It is/was useful feature because "activity" name itself is not very descriptive and if you want to add some specific info in addition to that logged entry you would need to retype this stuff again and again when you are working multiple days/entries on same activity.

**Comment by kevinpapst** [comment]
I answered that before, but can't find it anymore...

Short: that is on purpose. Copying the description was a bug before.
You are restarting a "project specific activity" and not a timesheet. If you want to copy values, restart from the action dropdown in the timesheet listing - this will restart a specific timesheet.

**Comment by aldas** [comment]
@kevinpapst, I do not understand where is that "restart from the action dropdown in the timesheet listing" located? I am almost 100% time only using calendar view and filling time for past week/couple of days, so it was very convenient/quick way to fill my calendar with things that I have done. We have been using description field for additional (which is importand as is project or activity itself) info like jira task numbers etc. Now every time I drag activity from left panel I need to open it up and fill description which I previously did not need to do.

**Comment by kevinpapst** [comment]
Here "Start again":
<img width="778" alt="Bildschirmfoto 2022-09-06 um 12 30 30" src="https://user-images.githubusercontent.com/533162/188613142-9b365d9d-6220-4c6f-b33b-43756a9504e5.png">

I am 100% certain, that the old logic was broken. If you are working on a longer project, the JIRA task number does not belong into the description field, but into the project description. But if you want, you can contact me to make this behavior configurable.

And maybe you want to have a look at the "Task management" plugin, which I believe behaves like you want and (from what you wrote) is much nearer to your workflow then using pure timesheets. 
And it supports drag & drop tp the calendar as well.

**Comment by aldas** [comment]
Ok, thanks. If it was a bug it was useful bug and will be missed :)   

I have looked into "Task management" at demo site and seems it would fit if you are managing your tasks solely with Kimai but if you have some other 3rd party software for project management it makes life now even harder as for you to "drag a task" at calendar view to your calendar you need to go to the tasks page and create those tasks first. But if you only operate with activities you do not need to navigate away from calendar page at all as if you click on your calendar you can create new activity and if you refresh your page it is now on left side menu and now you can "copy" it by dragging.
