### ISSUE TITLE
Reporting documentation not precise regarding project report permissions.

### ISSUE THREAD

**Issue by jsobiecki** [kevinpapst/kimai2#3525]
**Describe the bug**
According to the documentation (https://www.kimai.org/documentation/reporting.html#projects), to access projects reporting, two permissions are required:
- budget_project
- view_reporting

I have user, that belong to role with "view_reporting", but no "budget_project" permission. This person is able to access project's reporting (including financial data). I believe it's a not expected behaviour (at least according to the documentation).

After investigating permission documentation (https://www.kimai.org/documentation/permissions.html), I noticed that "time_team_project" also grants access to project reporting. This is bit confusing, and it's easy to overlook for starters.

**Comment by kevinpapst** [comment]
There is a reason why you get asked for several informations when creating a bug report:
<img width="527" alt="Bildschirmfoto 2022-09-06 um 12 02 51" src="https://user-images.githubusercontent.com/533162/188607322-666f0d00-d5ca-43ff-8baf-9a4610694a05.png">

**Comment by jsobiecki** [comment]
Ok, sorry for not leaving information there => this is definitely documentation improve issue (I labeled it in wrong way), so no need for context. I'll try to prepare documentation PR in spare time.

**Comment by kevinpapst** [comment]
You don't understand: I need to know the Kimai version for this topic.
It indeed might be a partial bug, but ONLY if you tried it with the latest release.

**Comment by jsobiecki** [comment]
Ah, sorry for misunderstanding. 

I'm using:
docker image: kimai/kimai2:apache-1.22.1-prod
Device: Ubuntu 22.04 PC
Browser: FF 104
KImai version: 1.22.1
PHP: 8.0.14

**Comment by kevinpapst** [comment]
Too sad, I fixed some permission checks in this report recently, but I believe it was before 1.22.1.

Then it is indeed likely a documentation issue, but I will look into it and give you an update.

**Comment by kevinpapst** [comment]
I tried to reproduce, but can't.
Testing with `time_team_project` and `time_project ` did not show anything unexpected.

Can you please tell me which reports and which data was accessible, even though it shouldn't?
