### ISSUE TITLE
Set timesheet entries to "open" / not exported when canceling an invoice

### ISSUE THREAD

**Issue by praul** [kevinpapst/kimai2#3526]
**Is your feature request related to a problem? Please describe.**
_I don't know if I get all the terms right, my kimai is german_

When I cancel an invoice, for example because it's faulty, I have to manually set all affected timesheet-entries to "open"/not exported in order to reissue a corrected invoice

**Describe the solution you'd like**
Automatically setting all affected entries to "open"/not exported . If I cancel an invoice - this should be the desired action, no? 
Alternatively another button: "Cancel Invoice and reopen entries"

This would be reaally helpful. Thanks a lot

**Comment by kevinpapst** [comment]
Then you should use tags wisely 😁

**Comment by praul** [comment]
This is interesting. Never used nor even noticed the tag function. Could be a way to declusterfuck my workflow. Thx
