### ISSUE TITLE
Automatically redirect to SAML

### ISSUE THREAD

**Issue by Mortein** [kevinpapst/kimai2#3533]
**Is your feature request related to a problem? Please describe.**
I use SAML only, with the login form disabled in System > Settings. It works perfectly, but the user must click the `Login with <SAML IdP>` link to start the login process.

**Describe the solution you'd like**
The login page automatically redirects to the `Login with <SAML IdP>` link if the login form is disabled and SAML is configured.

**Describe alternatives you've considered**
An option in the Authentication section of System > Settings to automatically redirect to the SAML Identity Provider when visiting the login page.

**Comment by kevinpapst** [comment]
I have clicked that SAML link so often, I totally forgot that I could add this feature for myself 😁 

Good idea 👍
