### ISSUE TITLE
Poor UX:  Create time dialog cancel /close buttons on opposing sides

### ISSUE THREAD

**Issue by kwhat** [kevinpapst/kimai2#3545]
**Describe the bug**
I don't care of you want to put the save / confirm buttons on the left or on the right, but you shouldn't have the date drop drop down cancel button on the left and the dialog close button on the right.

**To Reproduce**
1. Click the play button at the top to start tracking time
2. Notice the dialog has button order Save / Close
3. Click on the from date input field
4. See button order Cancel / Confirm

**Comment by kevinpapst** [comment]
Fixed in the next major release #2902
