### ISSUE TITLE
Create invoice for selected projects only

### ISSUE THREAD

**Issue by adis1987** [kevinpapst/kimai2#355]
When creating invoice, I want to select which project should be in the invoice (like in v1). Some customers want to separate the projects.

A solution would be a check-box to the left of the project name. Buttons:
Select/De-select all
Select only billeble this month

**Comment by kevinpapst** [comment]
You can already limit the invoice to a specific project.
What exactly do you miss?

**Comment by adis1987** [comment]
Lets say you have worked on 5 projects. The customer want me to separate some projects in the invoice. One invoice for three projects and the other invoice for the other two projects. In v1 I could do that.

**Comment by kevinpapst** [comment]
Alright, so you want to be able to select multiple projects at once. 
Okay, sounds fairly simple to do and is a legit use-case. Accepted.
Thanks for the explanation 👍

**Comment by kevinpapst** [comment]
Closing this one in favor of #486 which is described in more detail
