### ISSUE TITLE
Tax calculation with 3 decimal digits following the actual number i.e  xx.yyy instead of xx.yy

### ISSUE THREAD

**Issue by beauprgu** [kevinpapst/kimai2#3558]
Would it be possible to have 3 digits precision for the tax calculation in the invoice template. 
At the moment, the number is rounded up to 2 digits.

Exemple : 14.975% is rounded to 14.98% in the invoice template.

**Comment by kevinpapst** [comment]
I don't understand, can you post a screenshot / example please.

**Comment by beauprgu** [comment]
Hi Kevin,

Thanks for the reply. Find enclosed two images of the area where the tax rate is used. They are rounded to two digits after the decimal separator. I would need 3 digits to accommodate the tax rate in Canada.

Regards
![Image1](https://user-images.githubusercontent.com/114317/192550373-01c952fa-88d6-44a0-beb8-04b4bb15da5d.png)
![Image 2](https://user-images.githubusercontent.com/114317/192550447-92ec7938-3eb4-48bd-b9c2-3b4ed2bab03d.png)

**Comment by kevinpapst** [comment]
Thanks for your explanation!

Can you try yourself: edit the database directly in the table `kimai2_invoice_templates` in the column `vat` and enter the correct VAT there and tell me what happens? 

Or use this SQL: 
```sql 
update kimai2_invoice_templates set vat = '14.975' where vat = '14.98' LIMIT 1;
```

I know the edit form will change it back to two digits, just give it a try and see how the invoice templates behaves when you create a preview.

**Comment by beauprgu** [comment]
Thanks....It does work.!
I have used the SQL update approach.

The invoice template selection is showing 14.975
The invoice format page is showing 14.98

The invoice by itself ( preview mode ) is showing 14.975 and the calculation is ok.

Great application!

Please, see attached images.
![image1](https://user-images.githubusercontent.com/114317/192578965-ee3350dd-3ee8-41d6-a0aa-10f51e9d14f1.png)
![image2](https://user-images.githubusercontent.com/114317/192579008-d9795581-2055-4b2b-9175-179c62d17d12.png)
![image3](https://user-images.githubusercontent.com/114317/192579450-272f0a3e-7df4-415f-afd5-4d77166575c5.png)

**Comment by kevinpapst** [comment]
Thanks for testing, that is actually good feedback.

Then all that needs to be done is loosen the format on the edit form to allow more decimals.

**Comment by kevinpapst** [comment]
Fix will ship with next release
