### ISSUE TITLE
Decimal Input in Weekly Sheet adds one minute on top

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#3561]
**Describe the bug**
I updated kimai today from 1.23.1 to 1.25

since then, one minute is added to decimal time entries in the weekly sheet

**To Reproduce**
go to weekly sheet, enter time in decimal
![image](https://user-images.githubusercontent.com/55000172/192784480-1657f224-4d82-4390-b0f5-dc744e166cb2.png)
hit save
![image](https://user-images.githubusercontent.com/55000172/192784532-e89574dc-e7d6-40cb-93f1-9d725d311f07.png)
voila, one minute is added on top

i may add, that once the entry is there, editing works fine. this only applies to a new time entry

**Comment by kevinpapst** [comment]
Check your configured "default begin time". What do you have there?
<img width="533" alt="Bildschirmfoto 2022-09-28 um 15 22 29" src="https://user-images.githubusercontent.com/533162/192789654-b2efff28-82a5-4f2a-b681-0dc7bb4de1ef.png">

**Comment by stereo9** [comment]
@kevinpapst these are the settings

![image](https://user-images.githubusercontent.com/55000172/192789989-aed8c537-dc4f-48a0-923c-73e689e96fe6.png)

**Comment by kevinpapst** [comment]
That's it. You always round the minute up. 
The default time is "now" so unless you save exactly at 00 seconds, every record will be rounded up.
Round down, should solve the problem.

**Comment by kevinpapst** [comment]
You are welcome to join in improving the code!

Aside from that, if you only have a duration, then you need to set something as start to calculate from. 
And that is "now" so it includes seconds.

So eg. 15:40:23 + 30 min duration is 16:10:23 which is then either rounded up to 16:11:00 or down to 16:10:00.
The value you enter in the form sets the end and is not the duration. The duration is calculated from end - start.

**Comment by kevinpapst** [comment]
Re-open: clearly a bug. Thanks for talking it through with me @stereo9 👍

**Comment by kevinpapst** [comment]
If anyone knows how to reproduce this behavior reliable, please let me know. 
I saw it once and then it suddenly disappeared...

**Comment by PeterNerlich** [comment]
For me it seems consistent anytime I input something into a field that previously just showed the placeholder of `0:00`, as described by the opening post

**Comment by kevinpapst** [comment]
Fixed with #3580 - thanks everyone for helping me with the required input 👍
