### ISSUE TITLE
Sort by "hourly rate" ("Stundenlohn") is not possible

### ISSUE THREAD

**Issue by daboss84** [kevinpapst/kimai2#3566]
**Describe the bug**
The timesheet overview does not sort by "hourly rate".
![grafik](https://user-images.githubusercontent.com/18015530/193456805-932f57ca-5fb2-4bb2-905d-d13ea85c99d8.png)
![grafik](https://user-images.githubusercontent.com/18015530/193456830-2eda0abc-d000-43ce-9243-879c3fd58d41.png)

**To Reproduce**
1. Go to 'Zeiterfassung'
2. Click on 'Stundenlohn'
3. No sorting

**Additional context**
 - Kimai version: 1.25.0 

Is this a bug or a feature? :)

**Comment by kevinpapst** [comment]
Thanks for posting your finding!
I'd say it is a bug that the filter icon/function is shown. Sorting by the hourly rate seems kind of useless to me.

**Comment by daboss84** [comment]
Oh, why?
I stumbled upon this issue because I assigned some entries initially to the wrong (admin) user by mistake and reassigned it later to the correct one. So I had some (wrong) "0.00" entries. So I wanted to sort the timesheets by hourly rate to see if I fixed all wrong entries (by deleting the 0,00 hourly rate and save again).

**Comment by kevinpapst** [comment]
Hm, there is always someone with a valid use-case. 
But this "not working filter" is in Kimai since months and nobody noticed, so I assume the use-case is pretty small.
Anyway: appreciate your input! Lets see how it will be solved 😁 

Until then: export to Excel and search that way

**Comment by kevinpapst** [comment]
Sorting by hourly rate will come with the next release.
