### ISSUE TITLE
Make Kimai v2 keyboard friendly

### ISSUE THREAD

**Issue by eeproto** [kevinpapst/kimai2#3569]
Can you make the application keyboard friendly?

When using Kimai v2 on a daily basis, it would perfect if you could do so without switching between keyboard and mouse.

Example: You want to record a new time sheet entry. Hit a key (or combination) to open the "Create" dialog window. Then use the keyboard to go through the fields, select the dates (ideally with a smart date entry like GnuCash has it), select the customer and project, and complete the entry. 

Options:
- Classical key combinations like ctrl-something
- VIM style key bindings. Steeper learning curve but super fast thereafter.
- Pentadactyl style hints, type the first few letters of the item you want to access.

Sort-of workaround: Run kimai v2 in qutebrowser. Some fields are accessible through hints, some through tabs, some are missing id/name attributes.

**Comment by kevinpapst** [comment]
The latest release added some global keyboard shortcuts, see:
https://www.kimai.org/documentation/keyboard-shortcuts.html

Aside from that, I need clear explanations about what is missing. 
I am typing so much, I am happy to switch between keyboard and mouse and have no need for it myself - and therefor I have not much experience in that field. I did some adjustments in the past to make it more keyboard friendly, but it would be good if you could tell me exactly what is missing or should be improved.

**Comment by luco5826** [comment]
Hi @kevinpapst , one of the missing keystroke I often use on other software is the Ctrl+Enter to confirm a form. 
For example, when adding a new entry to the calendar, after writing the "Description" of the event, I'm used to confirm and save the form via Ctrl+Enter (of course that's just me, but I saw other time tracking software, e.g., Clockify doing the same and I find it very useful).

**Comment by kevinpapst** [comment]
Test

**Comment by kevinpapst** [comment]
Test 2

**Comment by kevinpapst** [comment]
Just wondering if we need different shortcuts on Mac, so I tried on if Control+Enter or Command+Enter or both work. 
Seems both shortcuts work 😁

**Comment by kevinpapst** [comment]
Submitting a dialog with CTRL+Enter will come with 2.0.
Configurable shortcuts are out of scope.
If something specific is missing, like #3572, please open a new feature request.
