### ISSUE TITLE
Error The table with name 'xxx_kimai2.kimai2_bookmarks' already exists.

### ISSUE THREAD

**Issue by gitalexa** [kevinpapst/kimai2#3578]
**Describe the bug**
Trying to update my kimai from 1.14.1 to latest version, but i get error: 

**To Reproduce**
following the documentation for updating:

Migration 20210316224358 failed during Execution. Error The table with name 'xxx_kimai2.kimai2_bookmarks' already exists.
 [ERROR] The table with name 'xxx_kimai2.kimai2_bookmarks' already exists.

**Additional context**
 - Kimai version: 1.14.1

**Comment by kevinpapst** [comment]
That is a follow up issue of some error that was ignored in the past OR because the installation instruction was not followed. Not a bug, read here: https://github.com/kevinpapst/kimai2/discussions/3414

**Comment by gitalexa** [comment]
ok. Thank you. In which file is the database-script located?

**Comment by kevinpapst** [comment]
Here are the migration scripts:
https://github.com/kevinpapst/kimai2/tree/master/src/Migrations

You should add all versions to the database_table `migration_versions` which were already executed but due to an error not recorded in there. That is the only safe way to prevent future problems.
