### ISSUE TITLE
Undefined constant "STDIN" when creating new user

### ISSUE THREAD

**Issue by jona-es** [kevinpapst/kimai2#3591]
### Describe the issue

As there is no default login, vVia SSH I tried to create a new user as described in https://www.kimai.org/documentation/installation.html#create-your-first-user
But I get:
```
bin/console kimai:user:create admin info@example.com ROLE_SUPER_ADMIN
Please enter the password: 18:03:22 CRITICAL  [console] Error thrown while running command "kimai:user:create admin 'info@example.com' ROLE_SUPER_ADMIN". Message: "Undefined constant "STDIN" ["exception" => Error { …},"command" => "kimai:user:create admin 'info@example.com' ROLE_SUPER_ADMIN","message" => "Undefined constant "STDIN""]

In QuestionHelper.php line 108:
                              
  Undefined constant "STDIN"  
                              

kimai:user:create [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <username> <email> [<role> [<password>]]

X-Powered-By: PHP/8.0.24
Content-type: text/html; charset=UTF-8
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.27.0

### Which PHP version are you using?

8.0

### How do you run Kimai?

Other (please mention below)

### Steps to reproduce the behavior

1. install on STRATO via SSH
2. insert ```bin/console kimai:user:create admin info@example.com ROLE_SUPER_ADMIN```

**Comment by kevinpapst** [comment]
Thats happening, becuase you use the wrong PHP to execute the bin/console command.
Shared hosts are, sorry, crappy.

But good that there is explicit docs for Strato: https://www.kimai.org/documentation/installation.html#strato

**Comment by jona-es** [comment]
thanks.
For all the others who didn't see the relation either, the complete command for STRATO is:
```
/opt/RZphp80/bin/php-cli bin/console kimai:user:create admin info@example.com ROLE_SUPER_ADMIN
```

Then you are prompted to insert a password, and no, this is not any default password but the **new** password you want to assign

**Comment by kevinpapst** [comment]
Hahaha, does it really say "enter the password"?

**Comment by jona-es** [comment]
src/Command/AbstractUserCommand.php
line 25:
```
  $passwordQuestion = new Question('Please enter the password: ');
```
