### ISSUE TITLE
Huge Session table when using the API via Browser-Plugin

### ISSUE THREAD

**Issue by schmunk42** [kevinpapst/kimai2#3600]
### Describe the issue

I have `kimai2_sessions` table of 1,2 GB.
We're using a custom Chrome browser-plugin to communicate with the API.

It looks like every request from the plugin is creating a new entry in the session table.

It's stated [here](https://www.kimai.org/documentation/rest-api.html) that plugins should use `X-AUTH-SESSION`, we'll try validating if this works.

Here's the corresponding line in the code:
https://github.com/kevinpapst/kimai2/blob/21dbfdb4f94ad25785cf753b405e131deb0fd29e/src/Security/TokenAuthenticator.php#L49-L51

Question: Is the "current session" show found in the database? Shouldn't API requests not create a session at all?

Additional question: How can I trigger an automatic or manual session-data cleanup?

CC: @handcode @eluhr

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.15

### Which PHP version are you using?

7.4

### How do you run Kimai?

Self-Hosted

### Additional context

Device: any
Browser: Chrome (plugin)

**Comment by kevinpapst** [comment]
Wow, how edgy.
Create a batch job and call `TRUNCATE kimai2_sessions` on saturday midnight...
And upgrade Kimai to a recent version 😁 

Check your PHP session settings and make it more likely to trigger a cleanup.

Probably your plugin is spamming the API? Is there a public repo to see what it does?

**Comment by schmunk42** [comment]
Some example code...

```javascript
const fetchFromKimai = path => {
    return fetch(`${ userSettings.urls.kimaiApi }${ path }`, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
            'X-AUTH-USER': userSettings.username,
            'X-AUTH-TOKEN': userSettings.apiToken
        }
    }).then(response => response.json())
}

const updateInKimai = (path, data) => {
    return fetch(`${ userSettings.urls.kimaiApi }${ path }`, {
        method: 'PATCH',
        headers: {
            'Content-Type': 'application/json',
            'X-AUTH-USER': userSettings.username,
            'X-AUTH-TOKEN': userSettings.apiToken
        },
        body: JSON.stringify(data)
    }).then(response => response.json())
}

const writeToKimai = (path, data) => {
    return fetch(`${ userSettings.urls.kimaiApi }${ path }`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-AUTH-USER': userSettings.username,
            'X-AUTH-TOKEN': userSettings.apiToken
        },
        body: JSON.stringify(data)
    }).then(response => response.json())
}
```

Basically we're sending every request with USER and TOKEN, this might be the spamming problem.
Should subsequent request only contain `X-AUTH-SESSION`?
Is there a way to disable sessions for `/api` - or is this fixed in a recent version. I was in the process of updating kimai when I stumbled upon the huge session table ;)

**Comment by kevinpapst** [comment]
This is a complex topic and even though my local tests passed, I need help pushing that live.

Can you give #3602 a try and report back?
