### ISSUE TITLE
Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#3608]
### Describe the issue

After upgrading to 1.28.1, I got the following error when I tried to create an invoice
```
php.CRITICAL: Uncaught Error: Invalid or uninitialized Zip object {"exception":"[object] (ValueError(code: 0): Invalid or uninitialized Zip object at /kimai2/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php:115)"} []
request.CRITICAL: Uncaught PHP Exception ValueError: "Invalid or uninitialized Zip object" at /kimai2/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php line 115 {"exception":"[object] (ValueError(code: 0): Invalid or uninitialized Zip object at /kimai2/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php:115)"} []
```
any idea how to fix it?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.28.1

### Which PHP version are you using?

8.0

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Additional context

Device: [Ubuntu Laptop 16 inch, Windows Desktop 27 inch, iPhone 6s]
Browser [e.g. Firefox 81, Chrome 85, Safari 14]

**Comment by kevinpapst** [comment]
Does it happen in the demo as well?

**Comment by BeckeBauer** [comment]
That's a trick question - I have not tried it in the demo but I assume it works flawless... Therefore, problem most probably caused by my own server, so I am closing here...

**Comment by kevinpapst** [comment]
I am just asking that, because testing it takes time and result might be related to your custom invoice template, which I cannot test at all. So can you confirm it is working on the demo?

**Comment by BeckeBauer** [comment]
As said before, I have not checked the demo but I found the issue: very strange "misbehaviour" of my synology server: After I changed the content of my invoice-template.docx to check out the new `${invoice.first} ${invoice.last}` variables, it was no longer listed in the invoice templates / invoice document as "Microsoft Word (docx)" but as a "Docx@SynoResource".

![image](https://user-images.githubusercontent.com/51003649/199022240-d3386c79-5418-483f-94f8-e1c8732cd34f.png)

Could fix it by merely moving the changed invoice-template.docx out of my template folder and back in... so, no Kimai issue at all ... sorry for creating bug report before fully examine the issue on my side...

**Comment by kevinpapst** [comment]
Thanks for the update!

Sounds weird, true. Glad it was rather easy to solve 👍
