### ISSUE TITLE
Please add posibility to add planned tasks without start date

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [kevinpapst/kimai2#3617]
### Describe the problem

For example in current version i can add in My times only jobs for which i exactly must know start date and time. 
But quite often appears tasks which have to be done in future but in current moment no time to do it but it have to be done later in moment time appears. Some kind of low priority task. 

### Describe the solution you'd like

Need to add possibility to add tasks without time binding which can be converted to My times in a moment when it is really started.

**Comment by kevinpapst** [comment]
If you are talking about the Task management plugin, here is not the right place to post that.
Please read https://www.kimai.org/documentation/buy-a-plugin.html and then send me your receipt, so I can invite you to the real repository for the plugin.
