### ISSUE TITLE
Random logouts while authenticate via saml

### ISSUE THREAD

**Issue by macmoritz** [kevinpapst/kimai2#3631]
### Describe the issue

I have a kiami deployment with saml authentication via authentik.  
User get randomly logged out, sometimes auth is required after a few minutes, sometimes after a few hours reauth is required.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.28.1

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

1. Activate SAML auth (https://goauthentik.io/integrations/services/kimai/)
2. Login via SAML auth
3. Wait some time (20m - 1.5h)
4. Need reauth

**Comment by kevinpapst** [comment]
The topic session was discussed often in the past and it is explained in these either closed issues or discussions. 
Plus there is explanation in the docs as well.
Basically: this is the stupid default session timeout of 14 minutes that is configured in PHP by default.
Not a Kima issue.
