### ISSUE TITLE
Button to fill in current time

### ISSUE THREAD

**Issue by naton0** [kevinpapst/kimai2#3654]
### Describe the problem

As a user of the kimai2 web interface, I sometimes want to fill my start or end time with the current time when adding or editing a time in the timesheet page. Currently, you have to use the date picker and select the time.

### Describe the solution you'd like

I want a small link styled button with the name “now” along the label that fills the date picker with the current date and time.

### Screenshots

![Screenshot 2022-11-28 at 01 41 44](https://user-images.githubusercontent.com/33197199/204169303-4a13efd4-782a-42ba-872e-59583833857e.png)

**Comment by kevinpapst** [comment]
Yeah or you just click that blue calendar icon in front.
