### ISSUE TITLE
non-admins: can't search for all users

### ISSUE THREAD

**Issue by ymarkus** [kevinpapst/kimai2#3667]
### Describe the problem

As explained in #3666, if I allow users the `view_user` permission I thought the API call to `/api/users` should return all users, regardless of what user calls it. That's how I understand this sentence:
![2022-12-02T11-59-43](https://user-images.githubusercontent.com/62380378/205277878-2c2bed62-5a8f-4c4d-b6dc-b5fb40efc42c.png)
I was assuming this code snippet is responsible for that:
https://github.com/kevinpapst/kimai2/blob/11dac19c8c9484b521f98160281a0c49c7a15e01/src/Repository/UserRepository.php#L209-L212

### Describe the solution you'd like

Not sure what the best solution is.

**Comment by kevinpapst** [comment]
The fix should address the API description, not the actual functionality 😁 
A regular user is not allowed to see other users. Kimai is designed with privacy in mind => GDPR for the win ...

You can add this user to a new team, make him the teamlead and assign all other users as members to this team. Then he will see them.

There would be no sense in limiting the frontend results, but then returning the full set in the API. Data consistency is important to prevent leaking personal data.

**Comment by ymarkus** [comment]
OK thanks, then the documentation needs more clarification. Shall I open a PR or will you do it yourself?
