### ISSUE TITLE
Reporting: Difference between yearly and montly reporting

### ISSUE THREAD

**Issue by idemus** [kevinpapst/kimai2#3676]
### Describe the issue

Hi,

there is a difference in reporting comparing yearly and monthly view.

Yearly view (wrong data for November: 96h instead 176h)

![image](https://user-images.githubusercontent.com/71780381/205510089-278ccbdc-8542-4fdf-b6c0-718e3024bb89.png)

Monthly view for November: 176h (correct)

![image](https://user-images.githubusercontent.com/71780381/205510076-d021a8b2-8dfc-4cbb-9142-809d17940aaa.png)

Best regards
Klaus

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.28.1

### Which PHP version are you using?

7.4

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Screenshots

see screenshots in the description

### Additional context

Device: [Ubuntu Laptop 16 inch, Windows Desktop 27 inch, iPhone 6s]
Browser [e.g. Firefox 81, Chrome 85, Safari 14]

**Comment by kevinpapst** [comment]
I have no clue how you managed to do that. I would need to see that myself.

**Comment by idemus** [comment]
Hi Kevin,
found it. It's no bug. As it seems it depends on "financial year" in settings.

Best regards
Klaus

**Comment by kevinpapst** [comment]
App gets too complicated, when the maintainer doesn't understand things himself 😁 

I missed that the first month is November in that view.
True, normally it starts on the first of January.
But if your financial year starts in the middle of November, then the counting starts at that exact date.

Thanks for clarifying the cause 👍
