### ISSUE TITLE
Weekly working hours is not honoring the billable flag on Customer/Project/Activity

### ISSUE THREAD

**Issue by aramilialon** [kevinpapst/kimai2#3677]
### Describe the issue

Howdy!
I have seen a problem using the Weekly Working Hours and I have confirmed it in the test instance of kimai.
For some customers (but the same applies with projects or activities) we have unflagged the "Billable" flag and if we insert a time record using the "My times" function that configuration is honored. However, if you insert a timerecord using the Weekly working hours, the billable flag for that insert in still on "Yes".
BR,
Giorgio

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.29.0

### Which PHP version are you using?

8.2

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

1. Configure a customer to not be billable
2. Add a timerecord in the Weekly Working Hours for that customer
3. Open the generated record and see the billable field

**Comment by aramilialon** [comment]
Configuration done on the customer:
![image](https://user-images.githubusercontent.com/938951/205862720-17ce9c48-b5f9-4734-b2c6-63ec7ec42a70.png)
Timerecord resulted from the insert in the Weekly Working Hours
![image](https://user-images.githubusercontent.com/938951/205862774-5490587e-1716-403a-bcd0-dcacd661e787.png)

**Comment by kevinpapst** [comment]
Confirmed, fix in progress
