### ISSUE TITLE
Existing Activity under Project not found when importing timesheet

### ISSUE THREAD

**Issue by dewulf** [kevinpapst/kimai2#3678]
### Describe the issue

I have setup in kimai a customer, project and an activity under the project. Then I try to import a timesheet entry with th csv importer. The customer is found, the project is found as well. But the activity is not found, instead a global activity is inserted. I assume the error is related to the line here https://github.com/kevinpapst/kimai2/blob/58a9facc6d4db7258d6ff08b6509eb5900e97a61/src/Command/ImportTimesheetCommand.php#L511
You are using $project as parameter for findBy. But $project is of the Project type. So I assume it should be $project.id (or something like this, I'm not a PHP programmer) that should be referenced. 

### I already tried

- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).
- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).

### Kimai version

 1.29.1

### Which PHP version are you using?

7.3

### How do you run Kimai?

kimai.cloud service

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Additional context

Device: [Ubuntu Laptop 16 inch, Windows Desktop 27 inch, iPhone 6s]
Browser [e.g. Firefox 81, Chrome 85, Safari 14]

**Comment by kevinpapst** [comment]
Ah, that looks like a bug. It is using the Project name to query find the activity (by [casting the Project object to a string](https://github.com/kevinpapst/kimai2/blob/master/src/Entity/Project.php#L564)), but it needs to use the project ID. Change the code to this an try again:

```php
 $tmpActivities = $this->activities->findBy(['project' => $project->getId(), 'name' => $activity]); 
```

**Comment by dewulf** [comment]
This is interesting. As I mentioned, I was working in the Cloud version and there it doesn't work. Now I installed the latest version with docker-compose from https://github.com/tobybatch/kimai2/blob/main/docker-compose.yml and importing there with the commandline tool works - the Import UI is somehow not available in this version (is this bu design?)

**Comment by kevinpapst** [comment]
Ah, I did not see `kimai.cloud`. The UI is not available in the self-hosted version.

And it works slightly different than the linked code examples. I will check that.

**Comment by kevinpapst** [comment]
Both importer have the same problem.

Thanks for the detailed report and especially for finding the correct place to fix it 👍
