### ISSUE TITLE
Activity list empty from the Create Timesheet window

### ISSUE THREAD

**Issue by amanzone** [kevinpapst/kimai2#3685]
### Describe the issue

Hello, I've just updated to 1.29.1, but now we seem to have issues when staring timers

If I try to start a new timesheet entry I select:

- the Customer:  that works ok
- then I select the Project: this is already weird because now I get a drop-down list with ALL projects, not only the ones belonging to the custome I have selected, anyway I scroll down till I get the customer projects I want and select it
- then I try to select the Activity: now the activity list is empty instead of showing all activities belonging to the project selected

Here are the screenshots I get

Do you have any idea why this happens?

Thanks in advance for your help

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.29.1

### Which PHP version are you using?

7.3

### How do you run Kimai?

kimai.cloud service

### Steps to reproduce the behavior

1. Go to web page "My times"
2. Click on + icon top right of the page to add a timesheet
3. Click the button to open the drop down list and Select a Customer
4.  Click the button to open the drop down list and Select a Project (You'll see ALL projects, not only those belonging to the selected customer)
5. The Activity list will be empty

### Screenshots

See Project list with all Customers and Projects

![Screenshot1](https://user-images.githubusercontent.com/25303066/207645366-633aacef-a7bd-40f2-9c4d-80044678fdd4.jpg)

See Activity list is empty (While this Project should have about 10 activities to select from)

![Screenshot 2022-12-14 164940](https://user-images.githubusercontent.com/25303066/207646029-3c4ff66f-1ecc-4c9a-b2b2-0456439b8617.jpg)

### Additional context

Server: [Ubuntu 20.04 VM]
Browser [Chrome 108 on Windows]

**Comment by kevinpapst** [comment]
PHP 7.3 is not supported and the log file is missing, which is most important.

Anyway, this is not a bug. Please use discussions: https://github.com/kevinpapst/kimai2/discussions

**Comment by amanzone** [comment]
Sorry, the page crashed on me while opening the bug... I'm on PHP 8.2, I'll updatethe bug entry now.
The logfile does not seem to carry any useful information but I will add that as well.

Either way I did not find anythin in the Discussions detailing why this is not a bug: I don't say at all that you're wrong, simply could you be more specific explaining to me why this is not a bug, and pointing me in the right direction?

Many thanks for your help and please excuse me Iif I miss something evident.

**Comment by kevinpapst** [comment]
Did you try the demo before posting to check if it is working? That's why.

Your issue is very likely a filesystem permission problem.

**Comment by kevinpapst** [comment]
> Attempted to call an undefined method named "getAttributes" of class "ReflectionClass"." 

Aha, running mixed PHP versions on console and web. 
Check `php -v` vs the Doctor screen PHP version.
Fix your webserver php version.

**Comment by amanzone** [comment]
I did mange to have it working, but I had to move to PHP 8.1 (8.1 module for apache2 is available on ubuntu 20.04 and working fine) in case this will help anyone.

Thanks again for your help.

**Comment by kevinpapst** [comment]
Thanks for sharing the solution 👍 

The error is (unfortunately) really common if you install composer packages with 8.1 on the bash and then run Kimai PHP 7.4 webserver module.
