### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by 53c70r** [kevinpapst/kimai2#3688]
### Describe the issue

The Documentation for AD / LDAP Login is wrong.
Please update https://www.kimai.org/documentation/ldap.html so the
username: user@ad.example.com
gets replace by the correct DN-Query example like
username: CN=kimai,OU=Server,OU=FooBar,DC=ad,DC=FooBar,DC=com

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

0.0.0.0

### Which PHP version are you using?

Other (please mention below)

### How do you run Kimai?

Other (please mention below)

### Steps to reproduce the behavior

Documentation.

### Additional context

Device: [Ubuntu Laptop 16 inch, Windows Desktop 27 inch, iPhone 6s]
Browser [e.g. Firefox 81, Chrome 85, Safari 14]

**Comment by kevinpapst** [comment]
All examples are from working installations.
Sharing is caring, so thanks for sharing your version 😄 
Next time, you can open a discussion, which stays open and might help others how are looking for a solution in the future.
