### ISSUE TITLE
Error when upgrading to 1.30.0

### ISSUE THREAD

**Issue by StefanGebhardt** [kevinpapst/kimai2#3691]
### Describe the issue

Hi, when I upgrade to 1.30.0 I get the following error message. Any idea where I can research?

```
/www/htdocs/xxx/kimai2$ git fetch --tags
remote: Enumerating objects: 479, done.
remote: Counting objects: 100% (203/203), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 59 (delta 48), reused 20 (delta 13), pack-reused 0
Unpacking objects: 100% (59/59), 17.74 KiB | 227.00 KiB/s, done.
From https://github.com/kevinpapst/kimai2
 * [new tag]           1.30.0     -> 1.30.0
ssh-xxx@xxx:/www/htdocs/xxx/kimai2$ git checkout 1.30.0


config/routes/annotations.yaml: needs merge
error: you need to resolve your current index first
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.30.0

### Which PHP version are you using?

8.0

### How do you run Kimai?

Self-Hosted

### Additional context

Hoster: all-inkl.com

**Comment by kevinpapst** [comment]
Please do not such end-user errors as bug, open a discussion instead.

> config/routes/annotations.yaml: needs merge

This means you changed a file locally: https://www.kimai.org/documentation/updates.html#troubleshooting

**Comment by StefanGebhardt** [comment]
Sorry, was not transparent for me, if its a bug or not
Thank you :-)
