### ISSUE TITLE
Installation instruction on Synology Docker 

### ISSUE THREAD

**Issue by andrenalin282** [kevinpapst/kimai2#376]
Hey, 
can someone provide a step by step installation or give settings instructions
for docker installation on synology?
https://hub.docker.com/r/kimai/kimai2/

i try to start it but it stops immediately ...

thanks a lot!
Kai

**Comment by tobybatch** [comment]
@andrenalin282 I think you may want the compose bundle.  The only docker currently on docker hub is a development docker meant to be run against the code base.  It relies on a checkout of the code on the host file system to function.

I don't currently have a stand alone production one available.  I am working on one.

There is a compose bundle that runs an php-fpm/nginx/mariadb version here: 
 https://github.com/tobybatch/kimai2/tree/master/.docker

I have a nascent documentation here: https://github.com/tobybatch/kimai2/tree/master/var/docs

**Comment by andrenalin282** [comment]
thanks for your answers.

i am now running v1 on apache 2.4, mariadb10, on synology. the installer worked great :-)

i do not have a compiler or git installed on the synology, i don´t want to open ssh and 
i don´t have enough knowledge to install it on this way :-(

i tried this package too, but ... i also don´t know how to add the config in the visuell ui of docker in synology... :-(
https://hub.docker.com/r/dysonsphere/kimai2/

i need to wait for the v2 installer Version, hope it will follow (not only for me)

**Comment by jmucks** [comment]
Perhaps I find next week sometime to test it on my synology setup and if possible I provide you some tips to get it run on your syno. 

Or you try to compose it on you pc and upload it to the syno. 

How to is described  
Here under ftp installation 

https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md

**Comment by andrenalin282** [comment]
This would be great.

i just tried to install composer on my second smaller syno, but without success.

isn´t it possible to make a backup from a running clean system and copy it on any webserver?
upload db and change parameter in options and config files!?

maybe you can compress a db export and the kimaiv2 folder... ?

**Comment by kevinpapst** [comment]
Yes that should be possible, but delete var/cache/* before compressing

**Comment by andrenalin282** [comment]
Oh great!!!
That would be helpful for many other people they don´t know how to compile...

Thanks a lot for this support!!!

**Comment by kevinpapst** [comment]
@andrenalin282 there is now a docker version in master which can be used, please check this: 
https://github.com/kevinpapst/kimai2/blob/master/var/docs/docker.md

**Comment by Haidy777** [comment]
I tried the prod Image today on my Plesk-Mashine, I could not get it to work, maybe somebody got an idea?

I ran `docker run --rm -d -p 8001:8001 -v /root/kimaidata/kimai.sqlite:/opt/kimai/var/data/kimai.sqlite --name kimai2 kimai/kimai2:prod` as root user.
I got the following message:
`
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/root/kimaidata/kimai.sqlite\\\" to rootfs \\\"/var/lib/docker/overlay2/2af53f966da6eaed79a633ec6c1a498e60f67ce83149f948ec15272f124087b3/merged\\\" at \\\"/var/lib/docker/overlay2/2af53f966da6eaed79a633ec6c1a498e60f67ce83149f948ec15272f124087b3/merged/opt/kimai/var/data/kimai.sqlite\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
`
At first I had no file inside the `kimaidata` directory, after that I tried with `touch kimai.sqlite`. Same message.

**Comment by kevinpapst** [comment]
Answering the first initial question: there is now an installation documentation for the officially shipped dockerfile at: https://github.com/kevinpapst/kimai2/blob/master/var/docs/docker.md

I am sorry to say so, but this issue has so many topics that it is literally unsolvable. I will close it. Please everyone: open new tickets for all of your other question/issues. Thanks 👍

**Comment by tobybatch** [comment]
@Haidy777 The error is from your docker daemon, not the image itself. From the look of things your source sqlite file does not exist.
