### ISSUE TITLE
Merge projects and/or activities

### ISSUE THREAD

**Issue by geniusupgrader** [kevinpapst/kimai2#406]
**Is your feature request related to a problem? Please describe.**
At the moment I have created many projects (this was before the migration to the separate project and activity design) and I would like to bring them down to only two projects (personal and work; maybe in the future I will divide them again more). So the task I would like to perform is some kind of merging the projects (and their times) into another. But at the moment this is not possible. I have to filter for project/activity (which I want to merge) and edit each time entry individually (and changing the project/activity to which I want to merge there). Now, we say, I have a project called "hobbies", where I want all (1000) time entries to be merged into the project "personal". For that at the moment I need to manually filter and edit each of the 1000 time entries individually.

**Describe the solution you'd like**
I would like to perform is some kind of merging the projects/activities (and their times) into another.

**Describe alternatives you've considered**
The functionionality of "multi edit" maybe have the same effect or is similiar.

**Comment by kevinpapst** [comment]
I thought about adding a "re-assign form" to the warning message, which shows up when you try to delete a activity/project/customer which has assigned timesheet entries.
Lets say you want to delete project "foo" then you get a select-box to choose any other project. 
You choose "bar" and then the attached timesheet/activities will be moved from "foo" to "bar".

This workflow could later on be used to build a UI that allows to move things around.

**Comment by geniusupgrader** [comment]
Thanks for tackling this.

To transfer one activity to another is really good. But unfortunately it does not help me to transfer whole projects, as explained above. Is it possible to implement the same thing as you done now but when deleting projects as well?

**Comment by kevinpapst** [comment]
Latest commit includes support for projects

**Comment by geniusupgrader** [comment]
I get:
Twig_Error_Runtime
HTTP 500 Internal Server Error
Impossible to access an attribute ("customer") on a null variable.
in templates/timesheet/index.html.twig (line 53)

**Comment by kevinpapst** [comment]
Can you have a look if there is something relevant in var/log/dev.log ? Unfortunately it works for me ... so I don't see what could have went wrong.

**Comment by geniusupgrader** [comment]
now it works on my side as well. Propably old table data..

**Comment by geniusupgrader** [comment]
I'll test it on my data (after backup) and tell you

**Comment by geniusupgrader** [comment]
Seems to be fine :1st_place_medal: 

Though it is a bit confusing to push the delete button, if you transfer the project to another

**Comment by kevinpapst** [comment]
True, but as I said often before: one step after another ;-)
