### ISSUE TITLE
Form fields should be always visible

### ISSUE THREAD

**Issue by geniusupgrader** [kevinpapst/kimai2#408]
**Is your feature request related to a problem? Please describe.**
For example: when filtering for times: You cannot filter for Activities alone, because this field is hidden and gets only accesible when entering customer and project beforehand. But all fields (in the filter form and elsewhere) should always be visible. After the latest separation of project and activities it is natural to filter/search only for activities alone. (When filtering for activities only, all projects should be selected)

**Describe the solution you'd like**
See above

**Additional context**
Coming from #405

**Comment by kevinpapst** [comment]
Thanks for posting all these great ideas!
I worked on this and think I found a solution that works. 
Can you test the attached branch and let me know what you think?
