### ISSUE TITLE
After installation no graphic/background/icons shown

### ISSUE THREAD

**Issue by ralfboernemeier** [kevinpapst/kimai2#417]
## Description
After following the installation decribed here on Github, which works without any error, I have tried to open kimai2 using the URL: https://ralfb-web.de/kimai2/public. The page was loaded but I have no "graphic" elemnts --> please check using the above URL.

Any ideas? Is this a known bug or a miss configuration? I'm using PHP 7.2.

## Expected Behavior
I expect the same look and feel as shown on the Demo page.

## Steps to Reproduce
1. Check the above URL
2.
3.
4.

## Your Environment
* Version: 0.6 dev
* Browser Name and version: Firefox 63.0.1
* Operating System and version (desktop or mobile): Wndows 10

**Comment by kevinpapst** [comment]
From the Readme:
> Kimai needs to be installed in the root directory of a domain or you need to recompile the frontend assets
So you have two choices:
- point your document root to "public/" (which I would highly recommend => use a subdomain like kimai.ralfb-web.de)
- Follow https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#frontend-dependencies

**Comment by ralfboernemeier** [comment]
Hi Kevin,

Thanks for the hint, I will try using a sub-domain.

Regards,

Ralf

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kevinpapst** [comment]
👍 Sure, please let me know if it worked

**Comment by ralfboernemeier** [comment]
Hi Kevin,

it works fine using sub-domain https://kimai.ralfb-web.de which points to /kimai2/public/

Regards and Thank You

Ralf

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kevinpapst** [comment]
Glad to hear that, thanks for your feedback!
