### ISSUE TITLE
Refresh of Duration time

### ISSUE THREAD

**Issue by ralfboernemeier** [kevinpapst/kimai2#420]
**Is your feature request related to a problem? Please describe.**
There is no problem/bug - just a nice feature from my point of view, like it was with kimai v1.

**Describe the solution you'd like**
Like in kimai v1 it would be great if the duration time will be updated automatically. Currently, using Firefox it will not be updated until I use the Browser refresh button. I also like the feature we have with kimai v1 that the duration time was shown in the Tab Label of Firefox. If this is not possible, a refresh button behind the stop,delete,edit button would be great.

Regards,

Ralf

**Comment by kevinpapst** [comment]
Thanks Ralf, reasonable request, will be added in the future.

**Comment by kevinpapst** [comment]
Please have a look at PR #660 and let me know what you think
