### ISSUE TITLE
Activities cant be used

### ISSUE THREAD

**Issue by meFailure** [kevinpapst/kimai2#434]
Hi,

i just wanna say that if we created an Activitie that is related to an Project, we cant use the activity in our time recording. It will not pop up. It just shows the activities that are not related to an project. 
You can see it in the gif:
![github](https://user-images.githubusercontent.com/45262886/48904491-d3a5e000-ee5e-11e8-9ae3-951454e23a8e.gif)

**Comment by kevinpapst** [comment]
I cannot reproduce the problem. 
Can you please try it at https://demo-v2.kimai.org/ - there is always the latest master installed.
Normally when you change a project or customer in the "edit/create timesheet form" a javascript call to the API is performed, fetching all entries (projects / activities) for that specific customer & project.
So either your browser does prevent the call or something inside the API is failing. 
Does your javascript console tell you anything? Can you see the API call in the network tab and post the result here

**Comment by meFailure** [comment]
Hey,
yeah did a test and in your demo version is everything fine. in my browser console im getting ab internal server error which is causing the problem. 
thanks

**Comment by kevinpapst** [comment]
Okay, can you please reproduce the error on your system and then immediately afterwards go to the server and copy the log file from var/logs/prod.log here.

**Comment by meFailure** [comment]
Hey, thanks for ur answer. I didnt had access to my computer the last couple of days and thats why im answering few days delayed. Im afraid but i dont have var/logs/prod.log ... =(

**Comment by kevinpapst** [comment]
There must a log file inside the Kimai folder at var/log/
Please check every file. And if there is nothing available, check the permissions of the var/ folder recursive, your webserver needs write permissions in there. 
Also check the global php/webserver log if there is an exception.

**Comment by kevinpapst** [comment]
The exception is pretty clear:
```
[2018-11-22 16:25:13] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The directory "/var/www/kimai2/var/cache/prod/jms_serializer" is not writable." at /var/www/kimai2/vendor/jms/metadata/src/Metadata/Cache/FileCache.php line 39 {"exception":"[object] (InvalidArgumentException(code: 0): The directory \"/var/www/kimai2/var/cache/prod/jms_serializer\" is not writable. at /var/www/kimai2/vendor/jms/metadata/src/Metadata/Cache/FileCache.php:39)"} []
```

I quote myself:
> check the permissions of the var/ folder recursive, your webserver needs write permissions in there.

Please follow the installation instructions carefully:
https://github.com/kevinpapst/kimai2#installation
https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md
https://symfony.com/doc/current/setup/file_permissions.html

**Comment by meFailure** [comment]
Hey, thanks! Its working now! =)
