### ISSUE TITLE
Keep kimai code straight and simple, do not add too much features

### ISSUE THREAD

**Issue by lduer** [kevinpapst/kimai2#437]
## Description
There were two suggestions/contributions I detected in the issues (#361) and pull requests (#435)

These are two suggestions, where additional features and new 3rd party packagesare added (are suggested to add).

Although I like those two additions, I want to start a discussion about "including all kinds of special requirements". I have some special requirements of my own (and would like to share the code when they are ready to use) but I'm sure, they should not be part of the kimai main-code.

I personally see kimai as a **simple timetracking tool**. In the future, it could be the *base* for more complex additions, but the setup and base configuration should be easy. The code should not be overloaded with too much features and configuration options.

**Comment by lduer** [comment]
> for now the plugin support from Kimai core is probably not as good as it can be - and on the other hand it is way more complicated to write a proper Symfony bundle than adding the feature directly to the core

Is there any documented plugin? Or any documentation for adding plugins? I only found https://github.com/kevinpapst/kimai2-invoice in your projects. I understand that symfony bundles are more complicated than adding code to the core, but a working example of a plugin/bundle could help to add more features quickly.

> When v2 grows, I hope that more people leave their opinion in feature requests

I don't know how to reach more people ATM. But in favor of getting more feedback and feature requests from potential endusers, I agree with @Ark74 in #356 to improve the communication to end users with other types of communication-channels than github but I don't know which could be the best   ;-)

> "Markdown enhancement"  [...] I like the idea and accept these changes. 

Thanks, I think that documentation is a very important part too (provide help contents in different languages could be a new issue). And users need to find the contents easily e.g. with the use of link-anchors.

**Comment by kevinpapst** [comment]
The linked bundle is really old and I haven't tried it for a couple of month but I added the issue #442 for creating a demo bundle and some documentation. 
In fact its fairly easy if you are used to Symfony and their bundle structure. 
The layout used in Kimai for example is a [Symfony bundle](
https://github.com/kevinpapst/AdminLTEBundle) that I created, but obviously hard-wired and different than the ones that would extend Kimai.

And regarding the communication, if you have any idea please post it. What I will definitely not do: host any discussion software like a forum. This is too much hassle. But any "free cloud solution" that has a chance to survive the next years can be used.

**Comment by kevinpapst** [comment]
Plugin support was added with one of the last commits (coming with 0.9).
I think this is a good starter for the future.
Thanks for all your input so far!!!!
I am closing this issue, as I'd like to keep the issue tracker for feature requests and bugs. I loose sight for the relevant stuff otherwise.
