### ISSUE TITLE
PHP Fatal Error - Symfony dotenv void

### ISSUE THREAD

**Issue by marquesmatheus** [kevinpapst/kimai2#447]
**Describe the bug**
After fresh install can't load the login page. Blank page.

**To Reproduce**
1 - Fresh install
2 - All composer dependencies installed ok

**Expected behavior**
Access to the login page.

**Desktop (please complete the following information):**
 - OS: Debian 9 
 - Browser: Firefox 60.3

**Additional context**
I've made the configurations for web server, using apache and pointing the /public folder.

Got this message error on log:

`PHP Fatal error:  Uncaught TypeError: Return value of Symfony\\Component\\Dotenv\\Dotenv::populate() must be an instance of Symfony\\Component\\Dotenv\\void, none returned in /var/www/kimai2/vendor/symfony/dotenv/Dotenv.php:95\nStack trace:\n#0 /var/www/kimai2/vendor/symfony/dotenv/Dotenv.php(57): Symfony\\Component\\Dotenv\\Dotenv->populate(Array)\n#1 /var/www/kimai2/public/index.php(15): Symfony\\Component\\Dotenv\\Dotenv->load('/var/www/kimai2...')\n#2 {main}\n  thrown in /var/www/kimai2/vendor/symfony/dotenv/Dotenv.php on line 95
`
Actually i'm using php 7.2 version.

Thx in advice.

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/blob/master/var/docs/faq.md#dotenvpopulate-must-be-an-instance-of-symfonycomponentdotenvvoid

**Comment by marquesmatheus** [comment]
Lol if i do php -v 

PHP 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215 (cli) (built: Nov 12 2018 10:23:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215, Copyright (c) 1999-2018, by Zend Technologies

**Comment by kevinpapst** [comment]
Yes, but that is PHP CLI. 
You need to check your PHP Webserver version and I bet that this is still 7.0.
Create a phpinfo file and check its output.

**Comment by marquesmatheus** [comment]
As you said :( ... going to upgrade to see the results. Thx man!

**Comment by marquesmatheus** [comment]
Forget it.
It worked! Thx Man!

**Comment by kevinpapst** [comment]
👍 thx for your feedback
