### ISSUE TITLE
don't allow start end dates, just punch in or out

### ISSUE THREAD

**Issue by Jasonparks** [kevinpapst/kimai2#448]
Is there a way to not allow the user to specify start date or stop date but to just either punch in or out like a traditional timeclock?

**Comment by kevinpapst** [comment]
Test if the [duration-only-mode](https://github.com/kevinpapst/kimai2/blob/master/var/docs/timesheet.md#duration-only-mode) is something you like.

If that is still not sufficient, I will take this as a feature request to add [another permission](
https://github.com/kevinpapst/kimai2/blob/master/var/docs/permissions.md), which allows editing of start and end datetime. If a user doesn't have that permission the fields won't be shown.

**Comment by Jasonparks** [comment]
The duration only is much better, but I think the permissions route would be best for my exact scenario. Then you can just use the system time for in and out and the user has less chance of entering time wrong, or editing if they are late etc.

**Comment by kevinpapst** [comment]
@Jasonparks this took way longer than expected, but I am finally working on this feature. Would you support with testing the feature? See #812
