### ISSUE TITLE
LDAP - Active Directory

### ISSUE THREAD

**Issue by marquesmatheus** [kevinpapst/kimai2#449]
Is there a integration to log in using AD users on kimai2? Like kimai1?
Or a doc explaining how to use.

Ty.

**Comment by kevinpapst** [comment]
No, not yet. If there would be, then #193 would be closed with additional information.
Please leave your voice in #193 so it gets a higher voting for the future.

**Comment by marquesmatheus** [comment]
Thx man!

**Comment by kevinpapst** [comment]
Feature now available in master.
