### ISSUE TITLE
Translation file

### ISSUE THREAD

**Issue by giannigio** [kevinpapst/kimai2#450]
I modified a transaltion file "messages.it.xliff"  but the changes are not seen on the site.

**Comment by kevinpapst** [comment]
Too lazy to write a question?

**Comment by kevinpapst** [comment]
`bin/console cache:clear --env=prod`

**Comment by giannigio** [comment]
Sorry but i not speak english and i have a problem to write a correct question.
Thank you

**Comment by kevinpapst** [comment]
If there is a problem in the official translation, let me know! Then we can fix it in Kimai directly.
Did cache:clear fix your problem?

**Comment by giannigio** [comment]
fix it! the offical translation is perfect, i modified only the text for my personal project.
Kimai is a perfect tool for my job ;)

**Comment by kevinpapst** [comment]
Ok, thanks!
