### ISSUE TITLE
de/help/invoices returns 404 error

### ISSUE THREAD

**Issue by Sch-Tim** [kevinpapst/kimai2#452]
## Description
Clicking on the little question mark left from the invoice document label doesn't show any help but a nice looking 404 error page.

## Expected Behavior
I'd like to see some advice how to import an invoice template.

## Actual Behavior
Ooops!

## Possible Fix
Fix the route.

## Steps to Reproduce
1. Open the form for a new invoice template (Rechnungsvorlage in german).
2. Click the question mark left from invoice document (Rechnungsdokument in german).
3. Admire the 404 page.

**Comment by kevinpapst** [comment]
Works for me and in the demo as well: https://demo-v2.kimai.org/de/help/invoices (login with `susan_super` and `kitten`.
Which Kimai version? What kind of user are you using?

**Comment by kevinpapst** [comment]
Any feedback on this one? Does it still not work for you?

**Comment by Sch-Tim** [comment]
It works now!
