### ISSUE TITLE
Invoice Number Generator possibly not compatible 

### ISSUE THREAD

**Issue by Sch-Tim** [kevinpapst/kimai2#454]
**Describe the bug**
Using a Number Generator which accesses some model attributes makes it impossible to use it in docx invoices. It throws a 500 error "Call to a member function getCustomer() on null". 
The worst thing is that this error fires, even when this particular generator is not used.

**To Reproduce**
1. Write a generator which returns something like `return $this->model->getCustomer() . '-' . date('m-Y', $this->model->getInvoiceDate()->getTimestamp());`
2. Try to create an invoice which uses a docx template.
3. See error

**Expected behavior**
It should display the invoice but it doesn't when using a docx template (it works using twig).

**Comment by Sch-Tim** [comment]
```php 
class DateNumberGeneratorExtended implements NumberGeneratorInterface
{
    /**
     * @var InvoiceModel
     */
    protected $model;

    /**
     * @return string
     */
    public function getId(): string
    {
        return 'Datum erweitert';
    }

    /**
     * @param InvoiceModel $model
     */
    public function setModel(InvoiceModel $model)
    {
        $this->model = $model;
    }

    /**
     * @return string
     */
    public function getInvoiceNumber(): string
    {
        return $this->model->getCustomer() . '-' . date('m-Y', $this->model->getInvoiceDate()->getTimestamp());
    }
}
```

**Comment by Sch-Tim** [comment]
I'm using 0.6.1 and upgraded from v1. Maybe something went wrong there.

**Comment by kevinpapst** [comment]
Hm, okay. Thats needs some debugging. Can you execute a SQL query:
`select * from kimai2_timesheet where project_id is null`
There shouldn't be a result.

**Comment by Sch-Tim** [comment]
You're right. There was no result. 
But I wonder why it works when I use the twig invoice template for the same set of work. Shouldn't it make problems for every kind of template if it was that kind of problem?

**Comment by Sch-Tim** [comment]
I send you whatever you want. What's your prefered approach? I happily help with the debugging.

**Comment by kevinpapst** [comment]
You can duplicate your Kimai v1 database (cleanup whatever you need - like customer names/rates) and then export it. ZIP it and send me a Dropbox/GoogleDrive link to kevin at kevinpapst.de.
I should be able to find the problem in the importer and also the invoice bug you are struggling with.

**Comment by Sch-Tim** [comment]
I just sent you the link.

**Comment by kevinpapst** [comment]
Okay, found the problem: if you change the default calculator, the exception is thrown. The only one that works is the `DefaultCalculator`.
Will post an update when I have a pull request in place, which fixes the problem

**Comment by Sch-Tim** [comment]
Hi, 
it works with "one entry per measurement" (the default one). It still fails with "one entry per activity".

**Comment by kevinpapst** [comment]
Did you clear your cache?

**Comment by Sch-Tim** [comment]
Sorry, it seems that this one was my fault. I cloned the git again and installed it completely fresh. It works fine now! 
Thanks for your help
