### ISSUE TITLE
Installation (Cannot declare.... in use)

### ISSUE THREAD

**Issue by gomiat** [kevinpapst/kimai2#455]
## Description
After Installation according to the instructions i get a 500-error. 

log:
[Sat Dec 01 12:23:35.041602 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP Fatal error:  Cannot declare interface Psr\\Cache\\CacheItemPoolInterface, because the name is already in use in /var/www/html/kimai2/vendor/psr/cache/src/CacheItemPoolInterface.php on line 14
[Sat Dec 01 12:23:35.041617 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP Stack trace:
[Sat Dec 01 12:23:35.041622 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   1. {main}() /var/www/html/kimai2/public/index.php:0
[Sat Dec 01 12:23:35.041625 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   2. App\\Kernel->handle() /var/www/html/kimai2/public/index.php:37
[Sat Dec 01 12:23:35.041628 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   3. App\\Kernel->boot() /var/www/html/kimai2/vendor/symfony/http-kernel/Kernel.php:183
[Sat Dec 01 12:23:35.041630 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   4. App\\Kernel->initializeContainer() /var/www/html/kimai2/vendor/symfony/http-kernel/Kernel.php:123
[Sat Dec 01 12:23:35.041633 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   5. ContainerXoCxfiM\\srcProdProjectContainer->set() /var/www/html/kimai2/vendor/symfony/http-kernel/Kernel.php:463
[Sat Dec 01 12:23:35.041636 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   6. ContainerXoCxfiM\\srcProdProjectContainer->ContainerXoCxfiM\\{closure}() /var/www/html/kimai2/vendor/symfony/dependency-injection/Container.php:150
[Sat Dec 01 12:23:35.041638 2018] [php7:notice] [pid 17747] [client xxx.xxx.xxx.xxx:24881] PHP   7. include_once() /var/www/html/kimai2/var/cache/prod/ContainerXoCxfiM/srcProdProjectContainer.php:195

## Your Environment
* Version: CentOS Linux release 7.5.1804
php 7.1.24
Symfony 4.1.6

**Comment by kevinpapst** [comment]
I have never seen this error and have no idea how to reproduce it. 
Try to `rm -rf var/cache/*` and then call the cache warmup command as explained in the installation documentation.

**Comment by gomiat** [comment]
warmup works
same error

**Comment by kevinpapst** [comment]
When exactly does that error show? During warmup? During first page load?
Can you post the output of `php --version` and from within the Kimai directory:
- `composer show`
- `ls -la var/`
- `ls -la var/cache/`

**Comment by gomiat** [comment]
composer show
`beberlei/DoctrineExtensions         v1.1.5  A set of extensions to Doctrine 2 that add support for additional query functions available in MySQL and Oracle.
doctrine/annotations                v1.6.0  Docblock Annotations Parser
doctrine/cache                      v1.8.0  Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.5.0  Collections Abstraction library
doctrine/common                     v2.9.0  Common Library for Doctrine projects
doctrine/dbal                       v2.8.0  Database Abstraction Layer
doctrine/doctrine-bundle            1.9.1   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.3   Symfony Bundle for Doctrine Cache
doctrine/doctrine-migrations-bundle v1.3.1  Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0  Doctrine Event Manager component
doctrine/inflector                  v1.3.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.1.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.8.1  Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.6.2  Object-Relational-Mapper for PHP
doctrine/persistence                v1.0.1  Doctrine Persistence abstractions.
doctrine/reflection                 v1.0.0  Doctrine Reflection component
egulias/email-validator             2.1.6   A library for validating emails against several RFCs
erusev/parsedown                    1.7.1   Parser for Markdown.
exsyst/swagger                      v0.4.1  A php library to manipulate Swagger specifications
friendsofsymfony/rest-bundle        2.4.0   This Bundle provides various tools to rapidly develop RESTful API's with Symfony
friendsofsymfony/user-bundle        v2.1.2  Symfony FOSUserBundle
jdorn/sql-formatter                 v1.2.17 a PHP SQL highlighting library
jms/metadata                        1.6.0   Class/method/property metadata management in PHP
jms/parser-lib                      1.0.0   A library for easily creating recursive-descent parsers.
jms/serializer                      1.13.0  Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle               2.4.2   Allows you to easily serialize, and deserialize data of any complexity
kevinpapst/adminlte-bundle          2.1.2   Admin theme bundle for Symfony 4 based on AdminLTE 2.4.8 with FOSUserBundle support
markbaker/complex                   1.4.6   PHP Class for working with complex numbers
monolog/monolog                     1.23.0  Sends your logs to files, sockets, inboxes, databases and various web services
nelmio/api-doc-bundle               v3.3.0  Generates documentation for your REST API from annotations
ocramius/package-versions           1.3.0   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.1.1   A library providing utilities to generate, instantiate and generally operate with Object Proxies
pagerfanta/pagerfanta               v2.0.1  Pagination for PHP 5.3
paragonie/random_compat             v2.0.17 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pclzip/pclzip                       2.8.2   A PHP library that offers compression and extraction functions for Zip formatted archives
phpcollection/phpcollection         0.5.0   General-Purpose Collection Library for PHP
phpdocumentor/reflection-common     1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         0.4.0
phpoffice/common                    0.2.9   PHPOffice Common
phpoffice/phpspreadsheet            1.4.1   PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoffice/phpword                   0.15.0  PHPWord - A pure PHP library for reading and writing word processing documents (OOXML, ODF, RTF, HTML, PDF)
phpoption/phpoption                 1.5.0   Option Type for PHP
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/log                             1.0.2   Common interface for logging libraries
psr/simple-cache                    1.0.1   Common interfaces for simple caching
sensio/framework-extra-bundle       v5.2.1  This bundle provides a way to configure your controllers with annotations
swiftmailer/swiftmailer             v6.1.3  Swiftmailer, free feature-rich PHP mailer
symfony/asset                       v4.1.6  Symfony Asset Component
symfony/cache                       v4.1.6  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                      v4.1.6  Symfony Config Component
symfony/console                     v4.1.6  Symfony Console Component
symfony/debug                       v4.1.6  Symfony Debug Component
symfony/dependency-injection        v4.1.6  Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.1.6  Symfony Doctrine Bridge
symfony/dotenv                      v4.1.6  Registers environment variables from a .env file
symfony/event-dispatcher            v4.1.6  Symfony EventDispatcher Component
symfony/expression-language         v4.1.6  Symfony ExpressionLanguage Component
symfony/filesystem                  v4.1.6  Symfony Filesystem Component
symfony/finder                      v4.1.6  Symfony Finder Component
symfony/flex                        v1.1.1  Composer plugin for Symfony
symfony/form                        v4.1.6  Symfony Form Component
symfony/framework-bundle            v4.1.6  Symfony FrameworkBundle
symfony/http-foundation             v4.1.6  Symfony HttpFoundation Component
symfony/http-kernel                 v4.1.6  Symfony HttpKernel Component
symfony/inflector                   v4.1.6  Symfony Inflector Component
symfony/intl                        v4.1.6  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bridge              v4.1.6  Symfony Monolog Bridge
symfony/monolog-bundle              v3.3.0  Symfony MonologBundle
symfony/options-resolver            v4.1.6  Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.5  A pack for the Doctrine ORM
symfony/polyfill-ctype              v1.9.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-icu           v1.9.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring           v1.9.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.9.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/profiler-pack               v1.0.3  A pack for the Symfony web profiler
symfony/property-access             v4.1.6  Symfony PropertyAccess Component
symfony/property-info               v4.1.6  Symfony Property Info Component
symfony/routing                     v4.1.6  Symfony Routing Component
symfony/security                    v4.1.6  Symfony Security Component
symfony/security-bundle             v4.1.6  Symfony SecurityBundle
symfony/serializer                  v4.1.6  Symfony Serializer Component
symfony/stopwatch                   v4.1.6  Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.3  Symfony SwiftmailerBundle
symfony/templating                  v4.1.6  Symfony Templating Component
symfony/translation                 v4.1.6  Symfony Translation Component
symfony/twig-bridge                 v4.1.6  Symfony Twig Bridge
symfony/twig-bundle                 v4.1.6  Symfony TwigBundle
symfony/validator                   v4.1.6  Symfony Validator Component
symfony/var-dumper                  v4.1.6  Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle         v4.1.6  Symfony WebProfilerBundle
symfony/webpack-encore-pack         v1.0.3  A pack for Symfony Encore
symfony/yaml                        v4.1.6  Symfony Yaml Component
twig/extensions                     v1.5.2  Common additional features for Twig that do not directly belong in core
twig/twig                           v2.5.0  Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                    1.3.0   Assertions to validate method input/output with nice error messages.
white-october/pagerfanta-bundle     v1.2.2  Bundle to use Pagerfanta with Symfony2
willdurand/jsonp-callback-validator v1.1.0  JSONP callback validator.
willdurand/negotiation              v2.3.1  Content Negotiation tools for PHP provided as a standalone library.
zendframework/zend-code             3.3.1   provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-escaper          2.6.0   Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application
zircote/swagger-php                 2.0.13  Swagger-PHP - Generate interactive documentation for your RESTful API using phpdoc annotations
`

ls -la var/
`
drwxrwxrwx  7 apache apache   70 Dec  1 11:41 .
drwxrwxrwx 14 apache apache 4096 Dec  1 12:04 ..
drwxrwxrwx  3 apache apache   34 Dec  1 15:51 cache
drwxrwxrwx  2 apache apache   47 Dec  1 11:41 data
drwxrwxrwx  2 apache apache 4096 Dec  1 11:41 docs
drwxrwxrwx  2 apache apache   22 Dec  1 11:41 log
drwxrwxrwx  2 apache apache   22 Dec  1 11:41 sessions

`

ls -la var/cache/

`
drwxrwxrwx 3 apache apache   34 Dec  1 15:51 .
drwxrwxrwx 7 apache apache   70 Dec  1 11:41 ..
-rwxrwxrwx 1 apache apache    0 Dec  1 11:41 .gitkeep
drwxr-xr-x 8 apache apache 4096 Dec  1 15:52 prod

`

**Comment by kevinpapst** [comment]
> When exactly does that error show? During warmup? During first page load?

And please try this tool, maybe it finds the problem:
https://symfony.com/doc/current/reference/requirements.html

**Comment by gomiat** [comment]
check.php tells me that intl.icu is outdated (V. 50.1.2) icu synfony bundled is 62.1.
icu 50.1.2 is needed by php 7.1.4 (remi) 
But this cannot be the problem - icu was always this version. For about one month i installed kimai2 the first time - with no problem. 
Whithin the first page load a 500error appears.

**Comment by kevinpapst** [comment]
So you installed Kimai in the past and it worked? 
And then what exactly did you do?
Is the other Kimai2 installation still running? 
Are you performing an update or a fresh new installation?

One thing I can say: this is definitely not a Kimai bug, but something within your server setup. 
Probably you are using some aggressive opcache, see  for example: 
https://php.net/manual/en/opcache.configuration.php#ini.opcache.dups-fix

**Comment by gomiat** [comment]
Problem solved!

php 71 remi has obviously problems with kimai... everything else is working but not kimai... 
basically problems or corrupt - anyway, i changed it to webtatic php 7.1. and now it works. 

Thank you for your help kevin! :)

**Comment by kevinpapst** [comment]
Huh? Thats majorly weird. But thanks for your feedback!
