### ISSUE TITLE
invoice template

### ISSUE THREAD

**Issue by giannigio** [kevinpapst/kimai2#457]
hello!
I have a problem with a file 
/templates/invoice/renderer/timesheet.html.twig
I tried to edit the file but the changes have no effect, can you help me?
thank you

**Comment by kevinpapst** [comment]
Don't edit the file directly, create a new file (read the documentation!). Otherwise your changes are gone after an update.
You need to flush your cache after changing the file `bin/console cache:clear`, then the changes are visible.
