### ISSUE TITLE
Possible to use a decimal in hourly rate field?

### ISSUE THREAD

**Issue by Jasonparks** [kevinpapst/kimai2#458]
**Is your feature request related to a problem? Please describe.**
Yes, when entering a employee rate I can only use whole numbers. Some employees may be paid 14.50 vs 14 or 15 dollars per hour.
**Describe the solution you'd like**
I need to be able to change the hourly rate to 15.25, 15.50 or 15.75 per hour. Not just whole numbers.
**Describe alternatives you've considered**

**Comment by kevinpapst** [comment]
Woods, wrong field definition: 
It works in the backend, but the frontend used a wrong input field.
Fixed in #460 - if you wanna test it, switch to the linked branch.

**Comment by Jasonparks** [comment]
Is the linked branch different than the master? I updated my install per the instructions and now I am getting segmentation faults in my apache log but kimai is not logging any issues and apache returns no data. Any idea what may cause this on a installation that was working perfectly? I even did a clean install and pointed it to the existing DB and get the same issue.

**Comment by kevinpapst** [comment]
Wow, thanks for the information. I have the same problem on my server ... locally everything works fine and also Travis in Scrutinizer. 
Some dependency seems to be "fucked-up" - if I use the [last commit before the composer update](https://github.com/kevinpapst/kimai2/commits/master) via `git checkout 43b488f21ff6e016ff7726ba314c4e` it works again. I'll revert the last commit.

**Comment by kevinpapst** [comment]
If you are currently available, could you try out the attached PR?!
I fixed some composer problems, now works again on my server.

**Comment by jkabat** [comment]
It is actually known problem after upgrading to 4.1.8, should be fixed for next minor (not yet released).
https://github.com/symfony/symfony/issues/29341

**Comment by kevinpapst** [comment]
Thanks for the info @jkabat !
I was too lazy to check all dependencies and simply reverted everything... I'll try 4.2 soon, but until then we stay with 4.17.

**Comment by kevinpapst** [comment]
Merged and fixed @Jasonparks you can try the latest master again

**Comment by jkabat** [comment]
You're welcome, I faced the problem myself on one of my projects.
