### ISSUE TITLE
Line breaks for address and payment information fields

### ISSUE THREAD

**Issue by Sch-Tim** [kevinpapst/kimai2#464]
**Is your feature request related to a problem? Please describe.**
I took a look at invoice.md and didn't find any information. At the moment line breaks in the mentioned text areas aren't considered in the document (docx in my case). I tried to add a html break but this broke my document I also tried markdown. Is there a way to insert line breaks in those fields?

**Describe the solution you'd like**
For even more formatting options something like markdown support would be great. But for the moment I'd be happy to be able to insert simple line breaks.

**Comment by kevinpapst** [comment]
There seems to be no "clean way" to fix this. But I added one that works in the linked PR.
But: I don't have Word, just tested with LibreOffice...

Can you test this and let me know if it works in MS Word as well?!

**Comment by Sch-Tim** [comment]
oops, i commented the PR. However it works great you can merge this.
