### ISSUE TITLE
maximale Anzahl Projektstunden als Vorgabe

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#467]
Ein Projekt wird häufig auch über zur Verfügung stehende Stunden limitiert.
Daher wäre es schön neben einem Projekt Budget auch die maximalen Projekt Gesamtstunden vorgeben zu können.

**Comment by kevinpapst** [comment]
Danke für die Ideen!
Ja, die gesamte Budget Verwaltung und Auswertung fehlt noch. Das wird aber noch kommen.

**Comment by HeinzWuert** [comment]
Hallo,Das wäre toll. Dann wäre das Programm in unserem Unternehmen einsetzbar. Knackpunkt ist aber noch die durchsichtigkeit über alle Projekte für jeden MA. Das darf bei uns nicht sein. Nur projektmitarbeiter dürfen die Projektnamen sehen (Projektnamen sind bei uns Familiennamen).Wir haben eine Timeline bis Dez 2019 zur Einführung.Wären sie in der Lage als Auftrag Teile des Programmes anzupassen? Mehrheitlich ginge es da nur um Überschriften und Begleittexte, kleinere Anpassungen zum dauerhaften ausblenden eiiniger nicht relevanten Funktionen.MfGH.Würtele


Von Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: Kevin Papst <notifications@github.com> Datum: 06.12.18  22:03  (GMT+01:00) An: kevinpapst/kimai2 <kimai2@noreply.github.com> Cc: HeinzWuert <firstdata@web.de>, Author <author@noreply.github.com> Betreff: Re: [kevinpapst/kimai2] maximale Anzahl Projektstunden als Vorgabe
  (#467) 
Danke für die Ideen!


Ja, die gesamte Budget Verwaltung und Auswertung fehlt noch. Das wird aber noch kommen.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kevinpapst/kimai2","title":"kevinpapst/kimai2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/kevinpapst/kimai2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kevinpapst in #467: Danke für die Ideen!\r\nJa, die gesamte Budget Verwaltung und Auswertung fehlt noch. Das wird aber noch kommen."}],"action":{"name":"View Issue","url":"https://github.com/kevinpapst/kimai2/issues/467#issuecomment-445028759"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/kevinpapst/kimai2/issues/467#issuecomment-445028759",

"url": "https://github.com/kevinpapst/kimai2/issues/467#issuecomment-445028759",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

},

{

"@type": "MessageCard",

"@context": "http://schema.org/extensions",

"hideOriginalBody": "false",

"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",

"title": "Re: [kevinpapst/kimai2] maximale Anzahl Projektstunden als Vorgabe (#467)",

"sections": [

{

"text": "",

"activityTitle": "**Kevin Papst**",

"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",

"activitySubtitle": "@kevinpapst",

"facts": [



]

}

],

"potentialAction": [

{

"name": "Add a comment",

"@type": "ActionCard",

"inputs": [

{

"isMultiLine": true,

"@type": "TextInput",

"id": "IssueComment",

"isRequired": false

}

],

"actions": [

{

"name": "Comment",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"kevinpapst/kimai2\",\n\"issueId\": 467,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"

}

]

},

{

"name": "Close issue",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"kevinpapst/kimai2\",\n\"issueId\": 467\n}"

},

{

"targets": [

{

"os": "default",

"uri": "https://github.com/kevinpapst/kimai2/issues/467#issuecomment-445028759"

}

],

"@type": "OpenUri",

"name": "View on GitHub"

},

{

"name": "Unsubscribe",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 421242785\n}"

}

],

"themeColor": "26292E"

}

]

**Comment by kevinpapst** [comment]
Bis Dez 2019 sind die beiden Themen garantiert fertig. Beides steht weit oben auf meiner Liste, insbesondere die Berechtigungen, welche Unternehmenskritisch sind.
Bzgl. der anderen Themen mich bitte via Email kontaktieren an kevin [at] kevinpapst.de

**Comment by kevinpapst** [comment]
Falls von Deiner Seite noch Interesse besteht, eine erste Testversion ist verfügbar: #843

**Comment by HeinzWuert** [comment]
Vielen Dank für die Info, ein wichtiger Punkt im Aufgabenkatalog!

Ich habe am 19.06. Termin Vorbesprechung Realisierung Kimai.

Ich denke, dass darauf folgend recht zeitnah die Installation auf einem Strato-Server erfolgen wird.

In dem Termin geht es auch um evtl. zukaufbare Dienstleistung deinerseits.

Ich würde mich dann nochmals melden.

MfG

H.Würtele

 

Von: Kevin Papst <notifications@github.com> 
Gesendet: Montag, 10. Juni 2019 17:04
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: HeinzWuert <firstdata@web.de>; Author <author@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] maximale Anzahl Projektstunden als Vorgabe (#467)

 

Falls von Deiner Seite noch Interesse besteht, eine erste Testversion ist verfügbar: #843 <https://github.com/kevinpapst/kimai2/pull/843>
