### ISSUE TITLE
Für Projekt Bearbeiter Ansicht aller anderen Projekte verhindern

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#468]
Projekte werden auch durch externe Mitarbeiter (MA) betreut.
Hier kann es nicht sein, dass diese MA einen Überblick über alle laufenden Projekte des Unternehmens bekommen.
Es müsste die Möglichkeit bestehen beim Anlegen eines Projektes auch die MA des Projektes zuzuordnen.
Dann sollten diese nur noch ihre Projekte sehen können.

**Comment by kevinpapst** [comment]
Danke! Das steht schon länger auf meiner Liste. 
Ich schliesse das Thema hier, weitere Details dazu finde sich dann in #366
