### ISSUE TITLE
404 while trying to resume the time tracking

### ISSUE THREAD

**Issue by gnimor** [kevinpapst/kimai2#470]
I am able to create a new time tracking record by clicking the play button. After that I am stoping the time tracking for this new entry. Now when I try to resume the time tracking I get a 404 page.

Moving the mouse pointer over the resume button shows the following link:

http://XXXXX/en/timesheet/start/1

I have tried this for several entries and it seems that all resume buttons point to this link which doesn't work. Moving the mouse pointer over the delete button for the corresponding row shows the following:

http://XXXXX/en/timesheet/8/delete

So it seems something with the routing is messed up?

Any idea what's wrong here?

By the way the installed version is 0.6.1.

**Comment by kevinpapst** [comment]
This bug has already been fixed with 0.6.1 - so I guess you upgraded from a previous version?
Did you already try flush your cache with `bin/console cache:clear`?

**Comment by kevinpapst** [comment]
Please compare the file `templates/timesheet/index.html.twig` in your installation with this:
https://github.com/kevinpapst/kimai2/blob/master/templates/timesheet/index.html.twig#L93

This part is most important `{'id' : entry.id}` - does it look the same?

**Comment by kevinpapst** [comment]
Closing, due to missing feedback
