### ISSUE TITLE
missing vendor folder

### ISSUE THREAD

**Issue by celestice441** [kevinpapst/kimai2#472]
hello, i've a problem, i will be try to install Kimai on my Debian Strech with PHP 7.2 , i following README , but when i start this command : sudo -u www-data composer install --no-dev --optimize-autoloader .....

pop up message error :  [RuntimeException]                                               
  /var/www/kimai2/vendor does not exist and could not be created.

And i check git repo , i clould not find vendor directory

what should I do to have a solution ?

Thx

**Comment by kevinpapst** [comment]
The vendor/ directory will be created by composer. 
I guess the www-data user doesn't have the permission to create the directory.

Did you execute:
```
chown -R :www-data .
chmod -R g+r .
```
? 
What is the output of `ls -la`?

**Comment by dhoppy** [comment]
I had the same issue, and I did execute those commands.  I got around it by chmod -R 777 the kimai2 folder, but I know that isn't secure.

**Comment by subdiff** [comment]
Vendor folder needs write permission for www-data group when doing the composer install. So just issue as root in your top-level folder `/var/www/kimai2/`:

```
mkdir vendor
chown -R :www-data vendor
chmod -R g+rw vendor
```
