### ISSUE TITLE
Arbeitstag starten / beenden - Alle Aufgaben dazwischen

### ISSUE THREAD

**Issue by Ninister** [kevinpapst/kimai2#473]
Hallo Kevin, ich nutze Kimai schon einige Jahre und schätze es sehr für die Übersichtlichkeit, Schnelligkeit und tabellarische Nüchternheit(nicht überfrachtet). Ich freue mich auf die zweite Version. Hier mal ein Wunsch aus unserem Büroalltag:

Der Tag beginnt um 9:00 Uhr und endet um 18:00 Uhr. Im Prinzip hat man an diesem Tag eine Hauptaufgabe oder Hauptprojekt. Wäre es möglich um 9:00 Uhr die Hauptaufgabe auszulösen, dann läuft der Timer bis zum Arbeitsende durch und registriert erstmal die Hauptaufgabe. Unterbrechungen für andere Tätigkeiten oder zB. Pausen aktiviert man zwar gesondert, aber sobald man diese stoppt, läuft die Hauptaufgabe weiter, bis ich Arbeitsende auslöse. Somit müsste man den eigentlichen "Tagesjob" nur einmal mit Beschreibung erfassen. Auch bei der Betrachtung des Postens wäre dann die Gesamtansicht sinnvoll - also zB zw. 9:00-18:00 Tätigkeit A - Stundenanzahl 6:00 h (3 Unterbrechungen 1:40 h) o. ä. Vllt. mache ich noch eine Grafik hierfür....

Praktischer Hintergrund: Ich zeichne ein Projekt den ganzen Tag. Es kommt ein Anruf, ich möchte nicht das gefühl haben, dass ich jetzt meine Aufgabe abbreche, sondern vielmehr ein Telefonat dazwischenschiebe. Während ich telefoniere, teile ich das Kimai mit, sobald ich auflege ebenfalls und die Zeiterfassung läuft weiter. Wenn ich am Abend die Hauptaufgabe beschreibe, schreibe ich die Details nur einmal, ohne sie in die vielen Einzelposten zu kopieren. Nebeneffekt könnte sein, dass ich Arbeitsbeginn und Arbeitsende gesondert auswerten könnte.

Ich hoffe ich konnte meinen Gedanken transportieren....
Vielen Dank!

**Comment by Ninister** [comment]
hier mal eine bescheidene Grafik zur Verdeutlichung.
<img width="566" alt="screenshot 2018-12-13 00 06 44" src="https://user-images.githubusercontent.com/45833430/49904668-2d506780-fe6b-11e8-9683-49e6da0cc00a.png">

**Comment by kevinpapst** [comment]
Sorry für das ausbleibende Feedback, stecke mitten in anderen Aufgaben fest und komme leider gerade nicht dazu an Kimai 2 zu arbeiten. Melde mich aber nochmal um genau zu verstehen, was Du hier im Sinne hast.

**Comment by gustawdaniel** [comment]
Really? Issues in not English? How to contribute project when English is not treated as official language of international communication? 

I was considering supporting this project, but when had seen this, I resigned.

**Comment by kevinpapst** [comment]
@gustawdaniel you know that there are people existing who do not speak english? Accidentally I come from Germany and I am capable to support these people as well. And you know what? I will do that, even though I'd prefer English as well. 
I could argue more, but pictures say more than words:
<img width="876" alt="bildschirmfoto 2018-12-22 um 13 37 15" src="https://user-images.githubusercontent.com/533162/50374439-ca8b6880-05ee-11e9-9ace-5eaae148d3cf.png">

**Comment by kevinpapst** [comment]
Eine Pausenfunktion wird eventuell noch irgendwann kommen. Dazu gibt es gesonderte Tickets.

Ein anderer Teil Deiner Anforderungen sollte eigentlich mit dem Kalender möglich sein. Falls dort etwas fehlt bitte ein neues Ticket aufmachen.
