### ISSUE TITLE
hide global activities option for projects

### ISSUE THREAD

**Issue by eglyn** [kevinpapst/kimai2#475]
Hi :)

I have a request about activities: 
We have some global activities, like development, requierements, tests, etc... and some specials activities linked only with a project.
Our problem is that a global activity is visible on every project, even the project witch have special activities.
We would like to hide this global activities to those special projects.
The best way would be to have a check box in the project list when creating an activity.
We check the project in which we want to see this activity.

thx :)

**Comment by kevinpapst** [comment]
A global activity is a global activity. 
The whole concept is about having activities that appear in every project.
The only thinkable solution would be a checkbox on project level "hide global activities".

**Comment by eglyn** [comment]
the checkbox "hide global activities" would be perfect !

**Comment by kevinpapst** [comment]
I know that the setup is not perfect and/or matching everyone needs.
But I decided to keep it as is and not work on that feature.
