### ISSUE TITLE
Kimai 2 Security vs Kimai 1

### ISSUE THREAD

**Issue by sleekwse123** [kevinpapst/kimai2#476]
Hello,

Is Kimai 1 still receiving security updates, or has it been abandoned completely for Kimai 2? Am I exposing myself to security risks, by using Kimai 1?

Thank you.

**Comment by kevinpapst** [comment]
I am working exclusively on v2, but @simonschaufi is still working on v1.

**Comment by simonschaufi** [comment]
Kimai 2 is no update, it is a complete rewrite so they don't have any single line of code in common. That's why you can still use v1 as long as you want.

**Comment by sleekwse123** [comment]
Thanks for the quick response, but for how long will Kimai 1 be continued to be updated.

**Comment by simonschaufi** [comment]
If you want to have a change and will pay for it, you will get this feature but I won't do any bigger changes for free any more. There are still many people who do exact that. Some changes are very customer specific and won't be released publicly but others will find their way into into the public releases.

**Comment by sleekwse123** [comment]
I think there may be a bit of a misunderstanding. We are not looking for any extra features. Our Kimai installation is not on an intranet. It is running on a public server that is exposed to the Internet. We would like to know whether version 1 of Kimai is still receiving security updates and patches, just like any other system that runs on public servers would (such as Jooma, Moodle, OwnCloud, Drupal). When a product reaches the end of its life cycle, it stops receiving security patches. At this point, it is absolutely necessary to switch to a newer version that is under active development. I hope this clarification is helpful. Thanks!

**Comment by simonschaufi** [comment]
Whenever we will get a security notice, we will fix it (we don't have a hard deadline).
