### ISSUE TITLE
login-screen optimizations

### ISSUE THREAD

**Issue by lduer** [kevinpapst/kimai2#483]
**Is your feature request related to a problem? Please describe.**
I want to improve some lines of the login screen (and all other UserBundle/AdminLTEBundle templates.

> Note: These changes affect all template files inside the `templates/bundles/FOSUserBundle` folder.

Example 1: The Login-Screen displays some unwanted (not overwritten) text: `<title>AdminLTE 2 | Log in</title>` (see https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/layout/security-layout.html.twig#L9)
Solution: Add a Title-block with something like this: `{% block title %}{{ 'browser.title'|trans }}{% endblock %}` in all files in `/templates/bundles/FOSUserBundle`

Example 2: The line `{% block logo_login %}<b>Kimai</b><br>TimeTracking{% endblock %}
` (https://github.com/kevinpapst/kimai2/blob/master/templates/bundles/FOSUserBundle/layout.html.twig#L3) is always the same and could be included from another template file to simplify the customization for another logo-header. 

Solution: I thought about adding another template to the `partials` folder like in https://github.com/kevinpapst/kimai2/blob/master/templates/bundles/FOSUserBundle/layout.html.twig#L8

**Describe the solution you'd like**
I could commit the code changes.

**Describe alternatives you've considered**
... 

**Additional context**
...

**Comment by lduer** [comment]
See: https://github.com/kevinpapst/kimai2/compare/master...lduer:login-screen-optimizations

**Comment by kevinpapst** [comment]
Hi Lukas, sorry for not being more active recently - I moved to a new city and have no proper Internet access right now. That should be fixed by next week "fingers-crossed" so I will be able to jump back into Kimai.

**Comment by kevinpapst** [comment]
Can you submit a PR? I will work on all of them next week, promised!

**Comment by lduer** [comment]
PR is here for you :)

**Comment by kevinpapst** [comment]
This one can be closed, right?
