### ISSUE TITLE
${entry.description} needed in Word-Docx

### ISSUE THREAD

**Issue by StephenWilde** [kevinpapst/kimai2#485]
Hi there,

in our work, we have the requirement to generate a timesheet and a seperate invoice.
The timesheet contains all actions done in a project with date, description and duration:
${entry.date} | ${entry.description} | ${entry.amount}

Additionally we have a seperate invoice, which only contains the projectname, the hourly/daily rate [€], the sum of accomplished hours and the total cost, plus tax.
What we do not need in the invoice is the description of a certain action.

${entry.description} seems to be a mandatory variable for creating a Word-Doc invoice.
If the variable is missing, we receive an:
Oops! Ein Fehler ist aufgetreten.
500: Internal Server Error

So the question is, why is this variable mandatory?
If possible to use a different variable, one idea would be to use ${invoice.date} instead.
${invoice.date} would be needed as a current date value in timesheets and in invoices.

Would this be possible?

Or would we be able to create invoices in a Word-Doc without using the variable ${entry.description} ?

Thx in advance
Regards
Stephen

* Version: Kimai v2 - 0.6.1 stable

**Comment by kevinpapst** [comment]
The variable was mandatory, as the rendering engine will duplicate the row containing this variable as often as there are records. 
But I added a fallback, if you want to test it use the attached branch from the PR #504. You can add the variable `${entry.row}` to mark the template row. The variable will be removed while rendering.
