### ISSUE TITLE
Mulitselect of projects for generating invoices

### ISSUE THREAD

**Issue by StephenWilde** [kevinpapst/kimai2#486]
Hi there,

I tested Kimai v2 - 0.6.1 stable for our needs and one helpfull feature, would be a mulitselect on projects, when creating an invoice.
In this version, a user can select on or all projects to create an invoice. But is not able to choose some certain projects he needs in the invoice.

Addtionially, if a mulitselect would be possible, it would be very good, if there would be according project variables for adding in the invoice, like e.g.

20h - Project A - 10€/h - Sum 200€
10h - Project B - 10€/h - Sum 100€
15h - Project C - 10€/h - Sum 150€
20h - Project D - 10€/h - Sum 200€

So there would be the need to iterate the actual existing project variables while choosing them in a multiselect combo and then generating an invoice.

This would be a feature like "Sammelrechnung".

It would be cool, if this would be a new feature in Kimai2.

Thx in advance
Stephen

**Comment by kevinpapst** [comment]
Multi-selection of projects in the invoice creation is possible once PR #1557 is merged.
