### ISSUE TITLE
No styling after install

### ISSUE THREAD

**Issue by jlpeifer** [kevinpapst/kimai2#490]
**Describe the bug**
After installing Kimai2 to the root of a subdomain I am able to see the textual elements of different pages, but the graphical elements are missing. 

I'm quite sure the "bug" here is the user (me). This question was previously posed and a fix was obtained, but I'm pretty sure I've followed-along well and have things set up like the other user. Still, I can't see the graphic elements.

DocumentRoot for this subdomain is set to public/
From my httpd.conf...
`DocumentRoot /home/help/domains/time.helpomatic.com/public_html/public
`

**To Reproduce**
1. Browse to https://time.helpomatic.com
2. Notice the lack of graphic elements

**Expected behavior**
A GUI interface

**Screenshots**
![kimai2](https://user-images.githubusercontent.com/5297832/50837291-442e9080-1329-11e9-9b67-7feb5de14ac5.png)
.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 64.0

**Additional context**
Nadda

**Comment by kevinpapst** [comment]
You are currently trying out different configs? I saw a 404 and a "Forbidden" in between.
If you have setup the DocumentRoot directly to public/ everything should be fine.
I need to have a look into the source code of your generated page, so please reactivate it and let me know.

**Comment by jlpeifer** [comment]
Sorry! I didn't expect such a fast response. Decided to re-install from scratch to see if it fixed anything (it didn't). Site's back up with the same problem.

**Comment by kevinpapst** [comment]
There is a reference to 
https://time.helpomatic.com/build/app.css?979d88ed847886068fcf3eb0bc3de545
in the pages source code. It returns a 404. 
But its in git: 
https://github.com/kevinpapst/kimai2/tree/master/public/build
Please check on your server in the public directory if there is the `build/` directory and what's inside.

**Comment by jlpeifer** [comment]
Here is the contents of /build:
`drwxrwxr-x 4 help help    7 Jan  8 15:30 .
drwxrwxr-x 5 help help   14 Jan  8 15:35 ..
-rw-rw-r-- 1 help help 331K Jan  8 15:30 app.css
-rw-rw-r-- 1 help help 1.1M Jan  8 15:30 app.js
drwxrwxr-x 2 help help   18 Jan  8 15:30 fonts
drwxrwxr-x 2 help help   10 Jan  8 15:30 images
-rw-rw-r-- 1 help help 2.2K Jan  8 15:30 manifest.json`

**Comment by kevinpapst** [comment]
I cannot help any further I guess. The file is there, but your webserver says its not - as it returns a 404 for: https://time.helpomatic.com/build/app.css
You need to find out why that happens, all resources under `public/` need to be accessible by the browser.

**Comment by kevinpapst** [comment]
Btw. this happens for all static resources:
https://time.helpomatic.com/favicon.ico
https://time.helpomatic.com/apple-touch-icon.png
https://time.helpomatic.com/build/manifest.json
https://time.helpomatic.com/build/app.js

**Comment by jlpeifer** [comment]
Ok, thanks. You've given me some good direction.

**Comment by jlpeifer** [comment]
Thank you Kevin for helping to resolve this problem. Entire issue centered around mis-configured nginx.conf.
