### ISSUE TITLE
admin activity: visibility "none" (no filter) causes sql-error

### ISSUE THREAD

**Issue by lduer** [kevinpapst/kimai2#491]
**Describe the bug**
In the admin-activities list, the select list of "visibility" causes an exception, when selecting the "empty" line (display both: visible and invisble activities).

> An exception has been thrown during the rendering of a template ("[Syntax Error] line 0, col 94: Error: Expected Literal, got 'ORDER'").

The QueryException:
>Doctrine\ORM\Query\ QueryException
>
>SELECT a, p, c FROM App\Entity\Activity a LEFT JOIN a.project p LEFT JOIN p.customer c WHERE ORDER BY a.id ASC

**To Reproduce**
1. Navigate to "Admin" -> "Activities"
2. Click on the Filter Icon to display the filter-form
3. Select the empty row in the "visible" dropdown
4. See error. 
 (direct navigation to the Error: `your-kimai.url/en/admin/activity/?customer=&pageSize=&project=&visibility=3`

**Additional context**
The Exception itself is caused by the template, when calling `{{ entries.count }}`, while `entries` is the `Pagerfanta\Pagerfanta` object. This causes the error when accessing `$entries->count()`.

**Comment by lduer** [comment]
After investigation, I found out that the error only occurs if there is no other than the visibility selected in the form.

The `findByQuery()` creates an empty `$where` and generates the SQL-error: https://github.com/kevinpapst/kimai2/blob/master/src/Repository/ActivityRepository.php#L148

**Comment by kevinpapst** [comment]
Thanks for the investigation! Should be fixed with the attached PR #506
