### ISSUE TITLE
Redirecting when using Kimai on a subdirectory

### ISSUE THREAD

**Issue by namelivia** [kevinpapst/kimai2#492]
## Description
I've have installed kimai on a subdirectory using nginx, I tested it on the server root and worked perfectly, I tested it with the configuration I have for other projects and I can get to run the app by calling the subdirectory url, the problem comes with redirects. I'm not sure if this can be solved from nginx or this is an application-level issue, can I configure the router to prepend the subfolder on every redirect?

## Expected Behavior
After getting into kimai by accessing the urk https://my-server.com/kimai a redirect should be performed to https://my-server.com/kimai/en/homepage.

## Actual Behavior
The redirect is performed to https://my-server.com/en/homepage resulting in a 404.

## Possible Fix
If the router can be configured to prepend /kimai/ on every redirect the problem would be fixed.

**Comment by kevinpapst** [comment]
Redirect should work out of the box properly.
I haven't tested it lately, but it worked in the past and is a default behavior of Symfony.
Maybe some server env variables are not setup correctly, did you check the Symfony docu?

If you use it in a subdirectory, you have to:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory

**Comment by kevinpapst** [comment]
Do you still need help?

**Comment by namelivia** [comment]
Sorry! I'll try it again this weekend, and come back with the results so we can close the issue.

**Comment by namelivia** [comment]
No luck, I've spent a lot of hours trying to fix this and I couldn't I'll close the issue because I think is more related to my particular web server setup and maybe symfony than to kimai itself.
I'll post my setup and discoveries in case someone is having the same problem.
First, I discovered that my issue is not really about running on a subdirectory but I think its more related to running the app behind an Nginx reverse proxy, the (convoluted) setup is as follows:

`http://server.com/kimai -> (nginx proxy pass) -> http://localhost:8080`

The Nginx's proxy_pass config was like this:
```
  location /kimai {
    proxy_pass  http://127.0.0.1:8080/;
  }
```
And the kimai web server config file would start like:
```
server {
	listen 8080;
	server_name localhost;
	root /srv/http/kimai/public;
```

Then when accessing to `http://server.com/kimai` would actually run the application, and it will perform a redirect, but it doesn't know is running behind a proxy_pass so it will redirect to `http://server.com/kimai/en/homepage`, that was the point I were when opening the issue.

After researching I discovered that adding `proxy_redirect / /kimai/;` after the nginx `proxy_pass` directive would make the redirect go to `http://server.com/kimai/en/homepage`. However at this point I was facing two issues, one that the assets were loading with a wrong path, and also that the GET request for `homepage` was returning a 404 error. I resolved the load of _some_ of the assets by setting the asset `base_url` on `config/packages/framework.yaml` from this point I couldn't advance more.

Anyway I will close the issue because now I think is not a kimai thing. Thanks for the time!

**Comment by namelivia** [comment]
I'm not sure if Symfony could automatically pick the path it comes from for making the redirect from the headers. I've tried setting the x-forwarded headers and printing the values on `index.php` to check that the values that are set in `$_SERVER` but it comes with just addresses and not paths.
```
    [HTTP_X_FORWARDED_PORT] => 25893
    [HTTP_X_FORWARDED_HOST] => server.com
    [HTTP_X_FORWARDED_FOR] => 71.20.11.8
```
