### ISSUE TITLE
Visual Grouping of entry from same day or same week with some stats of that group

### ISSUE THREAD

**Issue by jannefleischer** [kevinpapst/kimai2#495]
**Is your feature request related to a problem? Please describe.**
Not really. Just convenience.

**Describe the solution you'd like**
In Kimai v1 on the timesheet, there have been black lines between the days. This is what I currently missing on kimai v2. 
On kimai v1 I always missed a micro-overview of any day or a week on the timesheet: Worked hours that day/that week in sum.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by kevinpapst** [comment]
@jannefleischer Can you have a look at PR #552 and let me know what you think about it?!

**Comment by kevinpapst** [comment]
@infeeeee as you voted here, maybe you can have a look as well?
