### ISSUE TITLE
Adding Interledger Protocol to allow streaming of wages/payments

### ISSUE THREAD

**Issue by rslater12** [kevinpapst/kimai2#496]
## Description 
Using Interledger Protocol (ILP) moneyd and the XRP config could you add a feature that the main employer or owner operating the software could stream payments by the minute to the employee, when they clock in and then payment stops when they clock out.
Each user could be allocated an account using destination tags and the main employee holds the main crypto address, they have a gateway to the XRPL as they hold the funds for there emoloyes to with draw.
This would benefit the employee by allowing them to withdraw money when they wanted either daily weekly monthly and the employer by allowing them to say spread the cost of one big wage bill also freeing up doing the payment roll.

**Comment by kevinpapst** [comment]
closing, as there is no interest from the community
