### ISSUE TITLE
Field for location missing (e.g. onsite / remote)

### ISSUE THREAD

**Issue by blu-IT** [kevinpapst/kimai2#497]
Hello,

in Kimai v. 1 there was a field "location" where I could fill in for the customer if things were done onsite or remote. I am missing that field in Kimai v.2 when checking the demo. Is it just a setting or isn't it available any more. I would like to see this feature very much! 

Regards

**Comment by kevinpapst** [comment]
Thanks for the feature request. That field does not yet exist.

**Comment by hmr-it-jr** [comment]
It'd be extremely helpful if we could track the kilometers of onsite work, too. At the moment we write this in the description, but a designated place for it is more useful.

**Comment by rarvin** [comment]
We have users who work from home, office as well as users who are not our direct employees but from various outsource agencies who work from home as well as work from the outsource offices too. Having an option to identify the users would be great. Somehow having some way of linking them to the tasks that they create would be great. We just enter them in the title, but that does not get mapped anywhere so as of now we manually identify them during our analysis.

**Comment by kevinpapst** [comment]
Can be achieved with the custom-fields plugin:
https://www.kimai.org/store/custom-fields-bundle.html
Or with your own plugin:
https://www.kimai.org/documentation/meta-fields.html
