### ISSUE TITLE
Configuration of first page after login

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#501]
Hi Kevin,

is it possible to configure which page will be loaded after the login? Currently the timesheet is displayed as a list and we like to display either the timesheet as calendar or the dashboard.

Maybe the user can decide and configure it in the preferences...

**Comment by kevinpapst** [comment]
Not yet but good idea, thanks!

**Comment by kevinpapst** [comment]
Added PR that implements it, maybe you can have a look and test it?

**Comment by kevinpapst** [comment]
Now available in master

**Comment by blochwitz** [comment]
Hi Kevin,

i tested the configuration and the calendar view will be the first view after login. really fine but after adding a new entry the list view will displayed again instead of calendar view.

the same happened when click the menu „my times“. maybe a config of the my times view could be an idea?

**Comment by blochwitz** [comment]
Hi Kevin,

one more thing: in ou case we use calendar view as initial view after login but after adding a new entry the view jumps back to the list view.

**Comment by kevinpapst** [comment]
It is always helpful to explicitly tell me what you do. If I click the + button from the calendar it jumps back to the calendar after creation.
Please open a new issue, this topic was about something completely different.

**Comment by blochwitz** [comment]
Hi Kevin,

we add a new entry by clicking the +Button in the calendar view and after saving the new entry the view jumps to the list view and not back to the calendar view.

**Comment by kevinpapst** [comment]
Clicking + on
https://demo-v2.kimai.org/en/calendar/ 
goes to 
https://demo-v2.kimai.org/en/timesheet/create?origin=calendar 
origin=calendar tells the form where to redirect to after creation - after saving I am back at 
https://demo-v2.kimai.org/en/calendar/

**Comment by blochwitz** [comment]
I'm sorry: my colleague added a new entry by clicking into the calendar and after saving it jumps to the list view

**Comment by kevinpapst** [comment]
Again: no, it works also in the monthly view.
But I finally found what you are talking about. Its not working in the week and day view. 
That information upfront would have saved us both time, which we will never get back ^^
> Please open a new issue, this topic was about something completely different.
