### ISSUE TITLE
This value should be greater than or equal to zero

### ISSUE THREAD

**Issue by maaikez** [kevinpapst/kimai2#511]
## Description
When I fill in date/time correctly, I get error "This value should be greater than or equal to zero"

## Expected Behavior
When I select a date/time from the date/time picker, the date should be not a negative number internally.

## Actual Behavior
I started an activity with the start button (triangle) without end date. The time was not ok (1 hour too early), so I changed the start time. After 1 hour, I was done and clicked the stop button. I tried to change the second time (stop time) and save, but saving was not allowed because of the just mentioned error. This error was present on the first date/time field (from) and the date in it was correct.

As I remember correctly, the time in the overview was 0-1:0-2.

The local time was not working correctly, when starting the activity, utc time was automatically the start time, which I had to correct.

## Possible Fix
??

## Steps to Reproduce
1. Start an activity with the 'play' button without end date / time.
2. Change the start time to 1 hour later.
3. After some time, stop the activity.
4. Change the end time to a time later than the start time.
5. Hit the save button (error will appear).

## Your Environment
* Version: Kimai2 - 0.6.1 stable
* Browser Name and version: Chrome on Android
* Operating System and version (desktop or mobile): Android (mobile)

**Comment by maaikez** [comment]
![screenshot_20190119-131502](https://user-images.githubusercontent.com/4672351/51426928-84c3bf00-1bf1-11e9-9ca3-874c0e06eb62.png)

Screenshot

**Comment by maaikez** [comment]
![screenshot_20190119-131502 2](https://user-images.githubusercontent.com/4672351/51426980-00257080-1bf2-11e9-8dca-1b5d0bcee528.png)

**Comment by maaikez** [comment]
I just created a new time recording the same way without stopping it yet. This is what you can see in the overview:
![screenshot_20190119-135718 2](https://user-images.githubusercontent.com/4672351/51427006-627e7100-1bf2-11e9-95bc-4d641ca2deb6.png)

**Comment by kevinpapst** [comment]
This sounds as if there is a problem with your server timezone.
Can you check: your server timezone, your PHP timezone and your mysql timezone?
Kimai doesn't convert dates/times, so I expect a problem with the underlying system. 

You could also try this branch #372 and set your users timezone inside Kimai, maybe that helps?

**Comment by kevinpapst** [comment]
So this is really interesting, you found a problem which I never thought about...
I could reproduce the error when I start a record in the future and stop it far enough in the future.
Then it is not possible to save the form again, as the validator complains about a negative duration and negative rate. I'll check how to fix that. 

But still: if you didn't change the starting time manually, there is something odd going on: the start time should always be "now" when the page is rendered, so it should never be in the future. My only idea is that there is a timezone problem.
Probably @tobybatch is available to check/explain how the timezones in the docker images work?
Maybe there are different settings in PHP and MySQL? Maybe one takes the timezone from the host system and one is hardcoded?

**Comment by maaikez** [comment]
I can imagine you would start your time a few minutes in the future to round to 5 minutes or 15 minutes or so. So I think it is a good idea to fix it. However, it is not happening often probably (on the other hand, it was my very first time I started a recording via Kimai2).

About the timezones: I would expect the software to get the timezones from the users pc. But timezones is never easy (been there done that) :). I don't know if there is a possibility to change the timezone in a docker container or something like that.

**Comment by kevinpapst** [comment]
Timezones are a major pain... the linked branch allows to set the users timezone, but I am not sure if that is the best way to go, so its laying around and waiting for user tests and feedback.
Docker is "just another server" so you can ssh into the container and check `date` and the output of  `php -i|grep date.timezone`.

And about rounding: there are settings in Kimai for automatically rounding. Doing it manually is not a good idea and maybe disallowed in some environments (e.g. when duration-only mode is activated or editing of entries disallowed)

**Comment by kevinpapst** [comment]
I created a PR and it would be great if you could test it.

**Comment by maaikez** [comment]
I finally had time to test, but it didn't work. See the branch you asked me to test for the user timezone. I also changed the time in the docker container, but that didn't work either. 

I saw you changed the behaviour so it is not possible anymore to add times in the future. See [531](https://github.com/kevinpapst/kimai2/issues/531). So now I have to create times in UTC. And the next day, change them so they are in local time. That is also not really handy.

**Comment by kevinpapst** [comment]
Can you please remove these lines I mentioned in issue #532 and let me know if that fixes the problems for you?

**Comment by kevinpapst** [comment]
@maaikez there was still a bug in the convert script, which I found and fixed yesterday. Also a twig helper was used, which internally converted the date time object to the users timezone - I didn't knew that, but found out after some debugging. This one was replaced as well. 
As you said "timezones are a pain" ;-)
Could you support me / offer some more time for testing?
I hope/think its finally fixed, but you are currently the only person who reported problems and who was able to reproduce it.

**Comment by kevinpapst** [comment]
I do understand if you don't have the time to provide feedback.
Please open a new issue if you have troubles after updating to the latest version.
