### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#516]
**Is your feature request related to a problem? Please describe.**
There are some minor problems I don't like in the layout of the site. For example I think the text size for the name of the projects and customers are too small, or if you use long project names the width of the box for the restart last activities is too small, and part of the text is hidden.

**Describe the solution you'd like**
A box on the settings where I can write some custom CSS. Maybe this setting should be available only for administrators.

**Describe alternatives you've considered**

**Additional context**
This custom CSS box is very common in webapps like Kimai. For example I can apply custom css in TT-RSS or in nextcloud. Maybe the theme selector is redundant in this case. Or the regular users can only change the theme, and only the administrators can add custom css.

**Comment by infeeeee** [comment]
I think only the admin should change this, and that's apply to all users. 

Pros for only admin can change the CSS:
- Corporate branding is possible
- Blend in other services(e.g I use it as a tab in nextcloud, in an iframe)
- Regular users can't mess up the UI (But I think a regular user won't try to change it anyway)

If you think these changes should be changed in the default installation, maybe I can try to fix them. I don't really know these modern frameworks, but I see the developer documentation is well written.

**Comment by kevinpapst** [comment]
You can already help by writing detailed bug requests, but fixing them directly in the code via Pull requests would be even better!
And I fixed some of your points already in a branch that I am working on. I'll share that within the next days.

**Comment by kevinpapst** [comment]
Hey @infeeeee, if you have the time and will to help testing:
I added functionality for easy plugin loading in #592 and created a first demo plugin.

The demo plugin is implementing your feature request about the custom css:
https://github.com/keleo/CustomCSSBundle

Documentation is being written in the meantime, but I'd like to start testing early...
