### ISSUE TITLE
Error running reset-dev command

### ISSUE THREAD

**Issue by jazael-me** [kevinpapst/kimai2#517]
I'm having an error executing the "reset-dev" command, while following development installation steps.
  https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#development-installation

Error occurs when executing 
```
> bin/console kimai:reset-dev
Do you want to create the database y/N ?
Do you want to drop and re-create the schema y/N ?
                                                                                                  
 [ERROR] Failed to import fixtures: There are no commands defined in the "doctrine:fixtures"      
         namespace.  
```
(  EXIT Code: 4  )

Everything else works, and I was able to use the create user command and login and use the system. 

I see #42 and #64 both reference "kimai:dev:reset" but executing that says it's not defined at all.

**To Reproduce**
Steps to reproduce the behavior: follow install directions on
https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#development-installation

**Expected behavior**
Test users should be added to the database.

system:
 - Apache/2.4.29 (Ubuntu 18.04.1 LTS)
 - PHP 7.2

**Comment by kevinpapst** [comment]
I am pretty sure that you forgot to adjust your .env file to: `APP_ENV=dev`
This command is not registered in production mode.

**Comment by jazael-me** [comment]
Thanks.
