### ISSUE TITLE
Error after update in AppExtension

### ISSUE THREAD

**Issue by opHASnoNAME** [kevinpapst/kimai2#524]
**Describe the bug**
Fetched latest version, when running

`/bin/console cache:clear`

`!!  11:03:53 CRITICAL  [php] Argument 1 passed to App\DependencyInjection\AppExtension::createPermissionParameter() must be of the type array, null given, called in /var/www/virtual/zisops/html/time/src/DependencyInjection/AppExtension.php on line 42 ["exception" => Symfony\Component\Debug\Exception\FatalThrowableError { …}]`

**To Reproduce**

1. git pull 
2. /bin/console cache:clear

**Expected behavior**
No errors

**Desktop (please complete the following information):**
 - OS: Centos7

**Comment by kevinpapst** [comment]
Wanna share insights what fixed the problem?

**Comment by opHASnoNAME** [comment]
Fresh installation from Master

**Comment by kevinpapst** [comment]
Hm, not a satisfying solution. But I guess to late to find out what went wrong...
