### ISSUE TITLE
No projects in filter section

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#525]
Hi Kevin,

i found another bug: in the filter section there are no projects in the list.

![bildschirmfoto 2019-01-29 um 13 37 28](https://user-images.githubusercontent.com/42935152/51911127-4be5d000-23d1-11e9-9e58-8ea5ff41c7c1.png)

**Comment by kevinpapst** [comment]
Projects are only displayed after selecting a customer

**Comment by blochwitz** [comment]
I'm sorry, but selecting a customer doesn't help :(

![bildschirmfoto 2019-01-29 um 15 25 56](https://user-images.githubusercontent.com/42935152/51914957-4b056c00-23da-11e9-99db-13974f8d20d3.png)

**Comment by kevinpapst** [comment]
Can you please don two things:
- check your browser console if there is an error
- deactivate the `select_type: selectpicker` and change back to `select_type: ~` and try again

**Comment by blochwitz** [comment]
changing back to `select_type: ~` helps but with thousands of projects scrolling won't be nice..

**Comment by kevinpapst** [comment]
Good to know. Then some javascript event is not fired with this select type. I'll check.
You have thousands of active projects for one customer?

**Comment by blochwitz** [comment]
Not really yet but in some years ;)

**Comment by kevinpapst** [comment]
Can you test the attached PR #529 ?
