### ISSUE TITLE
Better user expierence on "My Times"

### ISSUE THREAD

**Issue by opHASnoNAME** [kevinpapst/kimai2#526]
**Is your feature request related to a problem? Please describe.**
Save Filter / or Button Today in "My Times" + Times entered today

**Describe the solution you'd like**
Save the defined Filter in "My Times". Our users only want to see the current day and the total amount of hours for today

**Comment by kevinpapst** [comment]
Interesting approach. I'll think about how that could be integrated. 
Do they have many small records or why do they just want to see the current day?

**Comment by opHASnoNAME** [comment]
Yes we have many small tasks around 30 minutes or sometimes 2 hours.

**Comment by kevinpapst** [comment]
The filter is not saved yet, but in the meantime a date range picker was added, which has quick filter buttons - one of them for "today".
And now there is a PR #552 which adds a statistic row between days (needs to be activated by each user).

Can you have a look if that is sufficient for you?

**Comment by opHASnoNAME** [comment]
Thats, this helps a lot !

**Comment by kevinpapst** [comment]
There is another feature request for storing filters between requests, you can vote in #564 if you want
