### ISSUE TITLE
Kimai2 will not allow me to enter times in the future

### ISSUE THREAD

**Issue by jaapcrezee** [kevinpapst/kimai2#531]
**Describe the bug**
Kimai2 will not allow me to save hours in the future.

**To Reproduce**
1. Go to my times
2. Create entry
3. Enter start time in the future

**Expected behavior**
Saved anyway.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium

**Additional context**
I would like to be able to record times in the future. For example I arrive at my customers office at 08:35 and know that I will have lunch around 12:30. In that case I would like to record my start time as 08:45 and end time as 12:30 but currently the system does not allow me to do so. I have to wait until it is actually 08:45 to be able to enter the time. Please allow the user an option to disable this check. Thank you.

**Comment by kevinpapst** [comment]
The PR #372 introduces a new boolean setting `kimai.timesheet.rules.allow_future_times` which is true by default. So future records can be disabled, but are allowed by default.

**Comment by jaapcrezee** [comment]
Will try to merge/test these changes in the coming days.
