### ISSUE TITLE
Änderung/Bearbeitung von Zeiten nicht möglich

### ISSUE THREAD

**Issue by GoldAri** [kevinpapst/kimai2#532]
Hallo Kevin, 

sobald ich schon eingetragene Zeiten ändern möchte erhalte ich eine Fehlermeldung. 
Hierzu gehe ich auf einen Eintrag --> bearbeiten, anschließend ändere ich den Kunden und das Projekt.
Wird anschließend mit Speichern bestätigt erhält man, die Meldung im Feld Projekt: "Dieser Wert ist nicht gültig."

![grafik](https://user-images.githubusercontent.com/46789994/51969545-f9f68600-2474-11e9-8ed2-0a763341792d.png)

Gruß

**Comment by GoldAri** [comment]
Hallo Kevin, 
ich habe gerade mal auf 0.7 geupdatet. Verhält sich genauso. Mit dem Problem.
Außerdem habe ich nun bei der 0.7 das Problem welches in Issue #503 behandelt wurde wieder. 

kimai.theme.select_type: selectpicker - habe ich in der admin_lte.yaml nicht eingetragen.

**Comment by kevinpapst** [comment]
Wenn dann in der local.yaml oder geändert in der kimai.yaml
Aber wen Du das nicht eingeschaltet hast, dann kann ich mir das nicht erklären.
Du kannst immer über https://v2.kimai.org/demo/ nachschauen, ob der Bug wirklich ind er aktuellen Version vorhanden ist. Dort wird 2x am Tag der master installiert.

Was ich ein wenig merkwürdig finde: die Fehler sollen wieder gekommen sein?
Bist Du sicher das Du alle Update Schritte ausgeführt hast? Insbesondere Cache löschen ist wichtig!

**Comment by kevinpapst** [comment]
Achse vergessen: den von Dir beschriebenen Fehler gab es in irgendeiner Zwischenversion mal, aber der dürfte nicht mehr existent sein. Er lässt sich auch nicht mehr nachstellen, weder bei mir noch in der Demo.

**Comment by GoldAri** [comment]
Nachdem ich nun mal alles frisch installiert habe, geht es wieder wie in der demo. 
Kann also hiermit auch zu. Woran es genau lag kann ich aber auch nicht nachvollziehen, den Cache etc. habe ich gelöscht gehabt. 

Gruß

**Comment by kevinpapst** [comment]
Eventuell hast Du eine unglückliche Zwischenversion erwischt. Das Editierformular ist leider immer noch nicht perfekt und dürfte erst mit der 0.8 komplett korrigiert sein.
Es wurde viel optimiert für große Datenmengen, dabei ist aber leider nicht alles ganz rund geworden. Sorry dafür!
Ich schließe den Issues hier dann, wenn es wieder geht.
