### ISSUE TITLE
On the last activities dropdown show tha last ten DIFFERENT activities

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#533]
**Is your feature request related to a problem? Please describe.**
On the last activities dropdown on the top right corner it shows the last 10 activities. It's very useful, however if I just start and stop the same timer a lot of time this dialog is quickly filled with the same entry, so it shows the same thing 10 times.

**Describe the solution you'd like**
I want to see the last 10 different activities. If I restart one of them it moves to the top, but doesn't duplicate.

**Describe alternatives you've considered**
Currently I use the restart buttons on the my times page, as on this page it shows more than 10, so I can scroll back. It would be nice if the last activities would be differentiated this way.

**Additional context**

**Comment by kevinpapst** [comment]
Wanna give the PR #550 a go while I try to understand your SCSS change?

**Comment by infeeeee** [comment]
I cannot test that now, only later today.
