### ISSUE TITLE
template entry.end_time shows empty field

### ISSUE THREAD

**Issue by maaikez** [kevinpapst/kimai2#535]
**Describe the bug**
When creating a template, entry.end_time is not working.

**To Reproduce**
I copied the timesheet template and edited it.
1. Copy kimai2/templates/invoice/renderer/timesheet.html.twig
2. Edit the template, add 
            {% for entry in model.calculator.entries %}
            <tr>
                <td>{{ entry.begin|date_short }}</td>
                <td>{{ entry.begin_time }}</td>
                <td>{{ entry.end_time }}</td>
                <td>{{ entry.activity.name }} / {{ entry.project.name }}</td>
                <td>{{ entry.duration|duration }}</td>
            </tr>
            {% endfor %}
3. Save the template under a new name in the var/invoices directory.
4. Create an invoice with this template.

**Expected behavior**
I expected to see the begin and end time, but in that columns, nothing was visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/4672351/52064407-e29ec200-2574-11e9-9bc6-1b5c19c2656c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version doesn't matter

PS maybe it is a good idea to write somewhere in the documentation that underscores in templates or long names or whatever it is are not allowed. It took me hours to find out why my newly created template was not working and it was because the filename was wrong (too long / underscore / I don't know).
And clear cache is also a good idea to add in the documentation about templates.

**Comment by kevinpapst** [comment]
You should not create templates in the production environment ;-) 
In the dev environment, the cache should be automatically flushed on every file change. But nevertheless: I can add that sentence.
But I didn't understand the underscore, whats wrong with that one? Do you mean in file names? I just created a new file with an underscore and it shows up (without clearing the cache manually btw):
<img width="247" alt="bildschirmfoto 2019-01-31 um 16 43 48" src="https://user-images.githubusercontent.com/533162/52065769-7d989b80-2577-11e9-842b-c17b6a10418a.png">
<img width="294" alt="bildschirmfoto 2019-01-31 um 16 44 05" src="https://user-images.githubusercontent.com/533162/52065770-7d989b80-2577-11e9-9caf-292e76eda331.png">

Maybe the documentation is not completely clear, the last table with all the shiny variables is for all formats except twig/html.

As written in the docs:

> Generally speaking, you should use only the variable model in your template which is an instance of App\Model\InvoiceModel.
>
> Please see the default templates at GitHub to find out which variables can be used or debug it with:
>
> {{ dump(model) }}

You need to create the end_time and begin_time for yourself in twig templates like that:
```twig
{{ entry.begin|date('H:i') }}
```
Can you make a suggestion on how to rephrase the documentation, so this is better to understand?

**Comment by maaikez** [comment]
Ok dat works. I thought I already tried that out and then I got a 500 error or so. But there was something else wrong I think.

I already found out it is not the underscore (I already changed the text ;)), but I think long names are the problem. When the name is too long, I get an error (Changes could not be saved: Could not save InvoiceTemplate).

You are right that I didn't read the documentation well enough. Maybe you can add a line that the template variables below can not be used. I found that {{ entry.begin|date('H:i') }} somewhere else in a template (and tried to use that), but a list or a bit more help about how the variables would be helpful. 

When using {{ dump(model) }} and try to use that template (click on 'Print') I get a 500: Internal Server Error
Where should I add that? I just added that line under the import and extend lines.

Oh and yes, files are adding up without clearing the cache, but when you change them and give them the same name, the change is not visible. So that's when the cache should be cleared.

**Comment by kevinpapst** [comment]
Can you have a look at the PR and let me know what else you want to have covered?!

**Comment by maaikez** [comment]
So I created a template which works. I copied it and changed the name (see file in the zip) and when trying to use it, I get this error:
Changes could not be saved: Could not save InvoiceTemplate

[template.zip](https://github.com/kevinpapst/kimai2/files/2825552/template.zip)

**Comment by maaikez** [comment]
I have to say that is in a prod environment (in another docker container with dev environment it seems to work, although I get another 'Unable to find template' error when trying to use the template, but that is another problem I think).

**Comment by maaikez** [comment]
dump() indeed really helps!

**Comment by kevinpapst** [comment]
Not reproducible for me. Please re-open/answer if you can provide a way to see the error.

**Comment by maaikez** [comment]
Did you test adding it in prod environment?

What I did: 
Add template file to var/invoices directory.
Create new template from invoices page. 
Save.
Then it will not save, but the error 'Changes could not be saved: Could not save InvoiceTemplate will show'.

When using the exact same file but with another name, there is no problem. 

If you can't reproduce it, I can't do more. Sorry. Strange error. 
Is there any debug flag I can set to true, so I can send you debug output?

We can not really test right now, because we updated the docker container, giving is 500 errors :(. So we first have to solve that.

**Comment by kevinpapst** [comment]
LOL, only troubles with open source ;-)
No I didn't test in production env.
I followed your steps, but no error. There should be no difference between production and development, besides that you don't have to clear the cache manually in latter on.
You could try to find relevant entries in `var/log/production.log`.

**Comment by maaikez** [comment]
In development env it is working ok. In production env I had this problems. I can still reproduce it with the newest version.

No log line is added in var/log/prod.log

**Comment by kevinpapst** [comment]
OK, I will retry with production

**Comment by kevinpapst** [comment]
No luck in prod as well ... maybe I am missing one important step.
Must be a validation error, which you can only debug in dev, where it works^^
So you are not able to save the template, only if you rename the file? Doesn't make a lot of sense. 
Not that I don't believe you, it's just working here.

**Comment by maaikez** [comment]
No the only thing I did was renaming a working template, giving it a longer name. I just tried again, changing the name of a working template to something long (like templatetimesheetthisisalongname.html.twig). I then copy it to the var/invoices directory and try to use the template in kimai (in **production** env). That's all. It's only the name change indeed.

Can it be a problem of the docker container probably? We use the most downloaded one on docker hub (the one you mention as well?). I don't think so actually.

Well, if you can't reproduce it, then you can't fix it ;). I don't know where to look / debug to see what's going wrong. I also get a 200 response from the server after pushing the 'Save' button.

I suggest to leave it for now and hope no one else will have this problem.
