### ISSUE TITLE
Import customers from CSV/XML

### ISSUE THREAD

**Issue by bomberlord** [kevinpapst/kimai2#537]
**Is your feature request related to a problem? Please describe.**
I needed to create a large number of Customers in my solution and i had to do it manually.

**Describe the solution you'd like**
Allow the administrator to import multiple customers from a CSV file or any other format that you prefer.

**Comment by hmr-it-jr** [comment]
Maybe it helps: you can import files to your db with tools like phpmyadmin

**Comment by bomberlord** [comment]
I've imported the customers with mysql queries. I thought it was just a nice to have.

**Comment by rarvin** [comment]
Instead of customer if an option to add tag data can be provided it would be good. Maybe the same could be used for other kinds of data tables like customer, project, activity. Currently there is now way of creating tag words centrally, they are created when a new tag value is entered in - this indeed is great functionality but an option to create them would be nice. When tag data is present it prevents users from incorrectly creating other types of tag words. Also an option to filter/search tags in the tags view could be useful.

**Comment by tobybatch** [comment]
I started working on a plugin to do this so I could learn how plugins worked.  Here is the version we used to migrate our old Jira data into our current Kimai instance.  

https://github.com/neontribe/KimaiCvsImportBundle

We don't use rates etc so it just does a subset of the function but if anyone want it as base code it's there supplied "as is".

**Comment by rarvin** [comment]
@tobybatch I have cloned the file to the plugins directory. Is there something additionally that needs to be done to get this appear in my kimai frontend.

**Comment by tobybatch** [comment]
@rarvin My bad you need to rename the folder to match the bundle name.  It should then just pop up in the menu link if you are an admin.

Something like:

    mv var/plugin/KimaiCvsImportBundle var/plugin/NeontribeCvsImportBundle

There are some docs in the web ui.

**Comment by rarvin** [comment]
It sttil didnt appear but after doing the following it appeared
sudo -u www-data bin/console cache:clear --env=prod
sudo -u www-data bin/console cache:warmup --env=prod

**Comment by rarvin** [comment]
@tobybatch Could you please send me a sample file the one that you had used as input (the csv). I'll work things out using that.

**Comment by tobybatch** [comment]
@rarvin Here is some sample data that imports.  I also just pushed an commit that adds log lines for failed imports, in addition to the flash bag message.

```
"244","Some customer","Diagnostic Tool Platform BETA heartbeat","Planning","2019-01-07 14:35:00","158400","Sprint planning week","John User","john@example.com"
"245","Some customer","Diagnostic Tool Platform BETA heartbeat","Planning","2019-01-14 14:43:00","158400","Sprint planning week","John User","john@example.com"
"246","Some customer","Diagnostic Tool Platform BETA heartbeat","Sprint development","2019-01-21 14:44:00","158400","Sprint development work","John User","john@example.com"
"248","Some customer","Diagnostic Tool Platform BETA heartbeat","Test & Deploy","2019-02-04 14:46:00","158400","Last bits of Sprint development & deployment","John User","john@example.com"
"249","Some customer","Diagnostic Tool Platform BETA heartbeat","Sprint development","2019-01-28 14:49:00","129600","Sprint development work","John User","john@example.com"
"23","Some customer","Heartbeat (6 weeks) 19 Nov - 14 Dec 2018","Monthly patching and maintenance","2018-11-19 08:30:00","10800","patched all servers and retrieved weekly backup.","Chris User","chris@example.com"
"24","Some customer","Heartbeat (6 weeks) 19 Nov - 14 Dec 2018","Monthly patching and maintenance","2018-11-26 09:30:00","7200","weekly backup retrieval","Chris User","chris@example.com"
"25","Some customer","Heartbeat (6 weeks) 19 Nov - 14 Dec 2018","Monthly patching and maintenance","2018-11-26 10:45:00","3600","monthly security audit checked all security reports for centos and ubuntu across all installed packages on momo infrastructure.","Chris User","chris@example.com"
"26","Some customer","Heartbeat (6 weeks) 19 Nov - 14 Dec 2018","Monthly patching and maintenance","2018-11-27 10:30:00","3600","openscap-documentation.txt consolidation of the various decisions and choices we have made for next infra so far.","Chris User","chris@example.com"
```

I had kind of discarded this code for the moment.  If you fix anything then please send me a diff, or better a PR on the repo.  If I get enough interest I may put some more time into it.

**Comment by kevinpapst** [comment]
I have added two basic importers for 1-6 as well, but each importer works a little bit different and its good if people can choose... thats why I have created a documentation page for imports that will contain the link to your plugin as well @tobybatch

**Comment by kevinpapst** [comment]
there are some option now to import data via css, closing here.
