### ISSUE TITLE
Improving installation setup, allow installation in subdirectorys of Web Root

### ISSUE THREAD

**Issue by Tilogorn** [kevinpapst/kimai2#541]
I stumbled upon three problems during installation, and I'm an experienced PHP dev. I followed the exact instructions in the [docs for recommended installation](https://github.com/kevinpapst/kimai2/blob/master/var/docs/installation.md#recommended-setup). I could solve all the problems but a normal user might not.

1. First time, I got the following error: 

```
$ sudo -u www-data php composer.phar install --no-dev --optimize-autoloader
[...]
Script cache:clear returned with error code 1
!!  
!!  In DriverManager.php line 259:
!!                                
!!    Malformed parameter "url".  
!!                                
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```
A normal user who is not capable of reading PHP Code and opening the concerning line might not notice that he/she has invalid characters in his/her database connection string in the `.env`-File (in my case some special chars in the password). I was about to open a issue about that before reading the source by myself. A better error description might suffice.

2. Proceeding to step `Create all schema tables`:
```
$ bin/console doctrine:schema:create
 !                                                                                                                      
 ! [CAUTION] This operation should not be executed in a production environment!                                         
 !                                                                                                                      
 Creating database schema...                                                                            
 [OK] Database schema created successfully! 
```
So I'm trying to setup a production environment. The warning is irritating me. Is this because of the early `0.x.x` version? Is that planned to disappear in coming versions?

3. Whats the entry point for the browser after installation? 
- The `root` of the git repository clone is not working
- The `public` directory is working

**Finally, a bug**
Installing in a subdirectory of the web server root leads to non-accessible CSS. It's hardcoded as absolute path `/`

Local-URL: `http://local.example.com/kimai2/public/de/login`
Error 404: `http://local.example.com/build/app.css?caadc4d6101e9889a4fa28e77f1d9362`

I don't know the code patterns from symphony but setting up a `base_url` in `.env` might help.

**Comment by kevinpapst** [comment]
Thanks for your feedback!

This is a server application, so "not really targeting normal users" like Wordpress or alike. If someone doesn't know how to install it, but likes the demo, support can be offered.
If you are an experienced dev and like Kimai, I am happy to accept contribution/PRs if you have ideas on how to improve the installation flow!

And now some answers to your feedback:
- the error message `Malformed parameter` comes from Doctrine, I am not sure if I can even change it, but I can add it to the FAQ or installation docs
- the message `This operation should not be executed in a production environment` again comes from doctrine. You are right, that might be is irritating, but I am again not sure if I can change it. But I'll have a look if that can be improved.
- the webserver-root and path is clearly documented in the main README and installation docu
> Kimai needs to be installed in the root directory of a domain or you need to [recompile the frontend assets](https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory)

And:
>If you want to use a fully-featured web server (like Nginx or Apache) to run Kimai, configure it to point at the public/ directory of the project

**TODO**
- [ ] installation docu - special character and urlencoded passswords
- [ ] check schema:create for wording improvements or flow change

**Comment by Tilogorn** [comment]
Hey Kevin,

thanks for your fast reply. As a full-time employee and non symfony user I thought a textual issue might be much faster than a PR for both of us :-)

I agree on both point 1 and 2 and excuse for point 3, I must have had tomatoes on my eyes (german expression for being blind).

**Comment by kevinpapst** [comment]
The internet made us lazy when it comes to reading docs, myself included.

I know that I am getting "betriebslind" so any input is and feedback is totally welcome!
