### ISSUE TITLE
Export / Timesheet - Auswahl welche Einträge aufgenommen werden sollen

### ISSUE THREAD

**Issue by GoldAri** [kevinpapst/kimai2#544]
Hi, 
was zumindest mEn noch nützlich wäre und in der Version 1 auch so vorhanden war, ist 
dass man aktuell wenn man über Administration --> Zeiterfassung sich die Einträge filtert, es keine Möglichkeit gibt, einige Einträge nicht in den "Export" bzw. Download einfließen zu lassen. 

Dies war in Kimai v1 über den Bereich Export mEn besser gelöst, hier konnte man Einträge auswählen, 
welche man im Export haben wollte, bzw. nicht haben wollte. 

Für mich wäre das schon wichtig, da ich den Export nutze um dem Kunden gegenüber eine Abrechnungsgrundlage zu haben, aber einige Einträge der Mitarbeiter von mir aus Kulanz nicht dem Kunden gegenüber erscheinen müssen. 

Ein zweiter Punkt wäre noch eine Mehrauswahl bei der Filterung, also Auswahl von zwei Mitarbeitern oder zwei Tätigkeitspunkten. Dies war in Kimai v1 besser gelöst mEn. 

Ich hoffe ich habe mich verständlich ausgedrückt.

**Comment by kevinpapst** [comment]
Du kannst die Einträge doch einfach als exportiert markieren, dann erscheinen sie auch nicht. Zumindest wenn Du den Status nach "offen" anstatt nach "alle" gefiltert hast.

Mehrfachauswahl steht auf der Roadmap.

**Comment by GoldAri** [comment]
Hallo Kevin, 
mein Fehler, nach einem neuen clone vom GIT, wird es bei mir nun auch wie in der Demo angezeigt. 
Cache hatte ich zwar gelöscht, aber irgendwo hat es noch gehakt. 

Kann also zu. 

Gruß

**Comment by kevinpapst** [comment]
Ich verlinke mal #486, damit Deine Stimme auch für die Mehrfachauswahl gezählt wird.
Wenn der Cache mal "bockig" ist, kannst Du auch`rm -rf var/cache/*` ausprobieren.
