### ISSUE TITLE
New time picker not working on languages without updated translation

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#546]
**Describe the bug**
The new time picker not working with languages which didn't translated the new time picker yet. It works with english or german languages.

**To Reproduce**
1. Change the language to something which is not english or german
2. Go to My times or Export.
3. It shows the entries from the current month correctly as the default timeframe, but if you click on anything in the time picker nothing changes. Other filters are working as expected.

**Expected behavior**
It should work with translations which are not updated yet, with fallback to english.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome, firefox

**Smartphone (please complete the following information):**
I didn't check it on phone, but it should exist there.

**Additional context**
This bug is reproducible on the demo installation as well. 

P.S. Sorry for not finding this bug when I tested this before merge.

**Comment by kevinpapst** [comment]
Thanks, I'll have a look. 
That "videomod.js" is definitely not coming from Kimai, do you probably have Video Player plugins activated in Firefox?

**Comment by infeeeee** [comment]
Yes it was from an addon, I deleted those parts from the bug report.

**Comment by kevinpapst** [comment]
Seems it fails only for some languages:
- fr
- ar
- hu

These worked for me:
- en
- de
- it
- es
- ru
- pt_BR

**Comment by kevinpapst** [comment]
Arabic was a bit harder to fix then french and hungarian. Its done, wanna test it?
