### ISSUE TITLE
local.yaml makes kimai unaccessible

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#556]
Hi Kevin,

using configurations in local.yaml makes kimai2 unaccessible (i'm using the latest master-branch).

my server-log gives me that:

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\\DependencyInjection\\AppExtension::createPermissionParameter() must be of the type array, null given, called in /.../kimai2/src/DependencyInjection/AppExtension.php on line 43 and defined in /.../kimai2/src/DependencyInjection/AppExtension.php:56\nStack trace:\n#0 /.../kimai2/src/DependencyInjection/AppExtension.php(43): App\\DependencyInjection\\AppExtension-]createPermissionParameter(NULL, Object(Symfony\\Component\\DependencyInjection\\Compiler\\MergeExtensionConfigurationContainerBuilder))\n#1 /.../kimai2/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): App\\DependencyInjection\\AppExtension-]load(Array, Object(Symfony\\Component\\DependencyInjection\\Compiler\\MergeExtensionConfigurationContainerBuilder))\n#2 /.../kimai2/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigu in /.../kimai2/src/DependencyInjection/AppExtension.php on line 56

**Comment by kevinpapst** [comment]
Remove all data from local.yaml and see if works then. You misconfigured a permission node. 
Not a Kimai bug.

**Comment by blochwitz** [comment]
I'm sorry but an empty local.yaml doesn't work too. In my case Kimai works only fine without a local.yaml...

**Comment by kevinpapst** [comment]
Then something else is wrong (check your var/log/prod.log). 
The above error says that you tried to configure permissions and something wasn't as expected (at least thats what I read from the error message).

An empty local.yaml works, I just tested it again on multiple environments.

**Comment by kevinpapst** [comment]
Copy&paste you config that you tried to create.

**Comment by kevinpapst** [comment]
Well yes, tabs have a special meaning in yaml files. Nasty bug ... thanks for the feedback!
