### ISSUE TITLE
Error 404 on 'My times' page 2+ if the time range is changed to something smaller

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#558]
**Describe the bug**
On 'My times' if I go to page 2, than change the time range to something smaller so page 2 is not needed I got error 404. If I delete '&page=2' from the end of the url, the page shows the expected output.

**To Reproduce**
1. Go to 'My times'
2. Select a time range where pagination enabled
3. Go to page 2
4. Change the time range to something much smaller
5. Get an error 404, and the url ends with '&page=2'

**Expected behavior**
It should go back to page 1 if there are no items on page 2. If I change any other filter on page 2 it goes back to page 1 as expected.

**Additional context**
Tested on the demo installation.

**Comment by kevinpapst** [comment]
I was curious how long it takes until somebody finds that bug ...
Now its documented and I have to fix it ;-)

**Comment by kevinpapst** [comment]
Added a PR to fix it
