### ISSUE TITLE
Export other users' timesheets using the API

### ISSUE THREAD

**Issue by mhaustein** [kevinpapst/kimai2#562]
I'm looking for a way to export timesheets of other / all users via the API.

Currently we are using Kimai 1 and import all timesheets into our invoicing system via an ODBC connection to the database on a regular basis. We are thinking about switching to Kimai 2 and start using the API, but I couldn't find a suitable method in the API. It looks like /api/timesheets can only access timesheets for the current user. Is there a way to get all timesheets or query by user id?

**Comment by kevinpapst** [comment]
Hi!
Thanks for the feature request. 
Not yet possible, but just a couple of lines to get it working.
I can add that to the next release.
I'll let you know when the PR is there, maybe you can help testing?!

**Comment by kevinpapst** [comment]
Well, that was easy... please check the attached PR.

**Comment by hmr-it-jr** [comment]
I'm curios about this change, too. Correct me if I'm wrong: it's not possible to filter the project and timespan yet?

We use direct DB access in v1 to get all the time sheet entries for a specific project of all users for a specific timespan - usually the last month.

**Comment by kevinpapst** [comment]
Timespan is indeed not possible yet, but you can filter for: customer, project, activity and user.
You can also define: order, orderBy, page and result-set size.
I'll see if I can easily add the timespan as well

**Comment by kevinpapst** [comment]
@hmr-it-jr I can add the time range, but please open a new issue for it. I will do some more refactoring when working on that.
