### ISSUE TITLE
Resuming a tracking does not stop prevoious tracking

### ISSUE THREAD

**Issue by DERanselmus** [kevinpapst/kimai2#565]
Hi,

resuming a tracking from the list does not stop the previous tracking automatically as it did in v1. If running two trackings simultaniously is intentional, may be the v1 behaviour could be forced via a configuration switch?

Cheers
Stephan

**Comment by kevinpapst** [comment]
Change `hard_limit` to 1 in your `local.yaml`:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L46
Seems its not yet documented in the docs.

**Comment by DERanselmus** [comment]
My fault. It's in the docs. Just didn't know what to look for.

Thanks
Stephan

**Comment by kevinpapst** [comment]
Ok, found it as well, probably should be moved to another docu place.
For the next one, its here: https://github.com/kevinpapst/kimai2/blob/master/var/docs/configurations.md#limit-active-entries
