### ISSUE TITLE
Inline editing of Description field

### ISSUE THREAD

**Issue by DERanselmus** [kevinpapst/kimai2#566]
Hi,

inline editing of the Description-field in "My times" would be great.

Cheers
Stephan

**Comment by kevinpapst** [comment]
Absolutely, I had that idea for a long time now.
Finally a feature request is there, thanks!

**Comment by HeinzWuert** [comment]
Good? Yes and No.
If you realize this please make the function unavailable in the settings.
Standardization of documentated activities is a big theme!

**Comment by kevinpapst** [comment]
Can you explain that in more detail? I am curious about that.
I don't mind if you open a new issue in German if that is easier for discussion.

**Comment by HeinzWuert** [comment]
Die Definition vorgegebener Tätigkeiten sehe ich als elementar an. Soll hier jemand ausserhalb der Administration Zugriff haben?
Ich begrüsse die fixe Definition ausdrücklich, da es schwer ist freie Tätigkeitsbeschreibungen unterschiedlicher Projektbearbeiter zum gleichen Thema zusammen zu führen.
Sollte man also in My times ein Editieren erlauben, müsste das Auswirkungen auf die Definition haben. Damit würde diese laufend verändert. Keine gute Idee.
Entweder fügt man eine frei beschreibbare Zeile je Tätigkeit an oder man erlaubt in den Programm Settings das Editieren der Definitionen für alle Mitarbeiter mit den wievor beschriebenen Problem.

**Comment by kevinpapst** [comment]
Es geht ausschließlich um das "Beschreibungsfeld jedes einzelnen Zeiteintrags". Also das Feld, dass die Mitarbeiter sowieso bearbeiten können. Aktivitäten würden hierdurch nicht editierter gemacht!

**Comment by kevinpapst** [comment]
If anyone wants to work on it, I am here to help with code hints.
But I have no plans to add that feature in the near future, so I am closing here.
