### ISSUE TITLE
Optimize UI for timesheet form

### ISSUE THREAD

**Issue by lduer** [kevinpapst/kimai2#571]
**Is your feature request related to a problem?**
Not a real problem, rather an improvement in the UI for creating or modifying a timesheet entry.

As I got feedback from users and also thought by myself, the datetimepicker ist not the best solution for updating the begin/end time in the form. In the mobile view, it's even worse to pick the right time, when selecting the dropdown for hours and then selecting the dropdown for minutes and the form is "jumping"/scroling up and down while trying to display the whole calendar-"popup".

**Describe the solution you'd like**
I want to suggest the use of a similar approach like google calendar, where the date is inserted with a calendar, and the time is inserted sparately with *one* selectlist (`HH:mm` format; not one for `HH` and one for `mm`). The steps should be configurable (5/10/15/30/.. minutes).

<img width="200" alt="bildschirmfoto 2019-02-14 um 10 00 39" src="https://user-images.githubusercontent.com/3307025/52775365-ceac9300-303f-11e9-8888-b3d2577a94a2.png"> <img width="201" alt="bildschirmfoto 2019-02-14 um 10 00 33" src="https://user-images.githubusercontent.com/3307025/52775375-d79d6480-303f-11e9-9ecf-f40b8bc9663f.png">

Because I think the guys at google know how to improve UX (and also my test users suggested something similar) I'd suggest to implement something like https://timepicker.co/ or  http://jonthornton.github.io/jquery-timepicker/. The timepicker from jonthornton allows to display the dropdown to a `<select>` list   `$('#selectExample').timepicker('option', { useSelect: true });` (e.g. for better use in mobile view.

**Describe alternatives you've considered**
Another alternative is to use a clockpicker like https://weareoutman.github.io/clockpicker/ for a more improved insertion of times on smartphones.

**Additional context**
For this adaptions, the form itself must to be splitted into fields like `beginDate, beginTime, endDate, endTime`  and new getter/setter needs to be inserted into the timesheet entity where each method only updates the time OR the date of the `DateTime`-object.

**Comment by kevinpapst** [comment]
Yes, definitely worth an improvement! 
I don't really like the current solution as well and as time-tracking is the most basic feature of all, its  time for a change.

The clock picker is probably a bit too much, even though it looks really cool.
I'll have a look at the time-pickers, but I guess that many people/companies want to track exactly by minute and not by quarters, so a dropdown list might become too long?

**Comment by lduer** [comment]
Maybe the clockpicker can be used only for mobile-input when the screen size is limited (keyboard input not the best solution). 

> JS mobile detection like  https://stackoverflow.com/a/22885503 > "ORIGINAL ANSWER" in combination with Modernizr: `` var is_mobile = isBreakpoint(['xs', 'sm']) && (Modernizr.touchevents || Modernizr.pointerevents);`` works pretty well for me.

On larger screens/PCs, time can also be inserted with the keyboard, where IMO the timepicker would be a better solution.

Regarding the "track exactly by minute": My experience when "writing" the hours (e.g. before leaving the office in the evening) the precision interval is either 5 min, 1/4 or 1/2 hours. When "clocking in/out" the time is minute-exactly, so you are right: it's possible start the timesheet without endtime and "stop" the entry with one button and the time is saved exatctly by minute. In this case the solution could be to configure the timepicker to allow times between intervals (scroll to 19:30 and modify to 19:28 with the keyboard)

**Comment by HeinzWuert** [comment]
Maybe worth an additional function in the fundamental settings to use 
- exactly minutes or
- grid (free definition)

It's not always standard to record the exactly time.
For us it;s enough to record only the duration of work.
A simple Input of that, regarding the setting of exactly minutes or grid would be great!

**Comment by kevinpapst** [comment]
@HeinzWuert [Duration-only mode](https://github.com/kevinpapst/kimai2/blob/master/var/docs/configurations.md#duration-only) ?
What you mean by grid?

**Comment by infeeeee** [comment]
What about `<input type="time">`? [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)
It has a really nice interface on android, supports keyboard on desktop, and not one more js dependency. Unfortunately it's not supported in safari yet.

**Comment by HeinzWuert** [comment]
> @HeinzWuert [Duration-only mode](https://github.com/kevinpapst/kimai2/blob/master/var/docs/configurations.md#duration-only) ?
> What do you mean by grid?

timesteps in 5, 10 or 15 minutes steps

**Comment by kevinpapst** [comment]
https://www.malot.fr/bootstrap-datetimepicker/demo.php

**Comment by HeinzWuert** [comment]
Here a link of two possible solutions:
http://ninodezign.com/20-awesome-material-design-date-time-picker/  
2 – AngularJS Circular Time Picker     or
4 – SM Date, Time and Range Picker
The ui should be conform to the time grid if defind in the settings

**Comment by lduer** [comment]
@HeinzWuert: My Plugin https://github.com/lduer/CustomTimesheetFormBundle implements the a [jquery-timepicker](https://github.com/jonthornton/jquery-timepicker) on desktop screens: 

> timesteps in 5, 10 or 15 minutes steps
(not yet customizable)

In the mobile view, the timepicker is disabled, and the native timepicker from the browser/OS is used. Feedback is welcome :)

**Comment by kevinpapst** [comment]
Optimizations like this would be great as PR in the core.

**Comment by lduer** [comment]
@kevinpapst I was not sure if it's the the best way to force all kimai users to use the updated timesheet form ;) 

additionally: you mentioned somewhere else that you don't want too much configuration options, which was my idea too, so I decided to create a plugin: 

+ enabled: my new timesheet form 
+ disabled: original timesheet form 

if you tell me, which features you want (maybe as issue-feedback in my project?) I'd be proud to contribute to the core.

**Comment by HeinzWuert** [comment]
I would like it in the core but still miss a direct connection with the global time settings (time grid).

**Comment by lduer** [comment]
@HeinzWuert I don't know if I get you right: Do you want a new configuration option for the time grid?
Or use an existing one (e.g. `timesheet.rounding.default.begin`)? Do you want to describe your requested features here? https://github.com/lduer/CustomTimesheetFormBundle/issues/new?template=feature_request.md

**Comment by alqu** [comment]
Also, coming from a different project, it was pretty important for the users to enter dates and times via keyboard, e.g. something like "8-13.15" creates a time entry with start=08:00 and end=13:15. So there was a kind of fault tolerant logic needed, which tried to guess intervals. It also assumes that you are usually not entering time intervals that are longer than 24 hours.
The same is applicable to date fields, whereas eg. a string like "4" is being interpreted as "the fourth of this month" or "-4" is being interpreted as "today - 4 days" - you get the idea.

This is especially helpful for a user that has to enter 10 or more time records into Kimai. This happens quite frequently at the end of the month for some users. I am not saying that I find it especially clever, but that is the reality. :-\

**Comment by freelancer1845** [comment]
I would also like to see a different *time select form*. Maybe this could be something that is configurable per user?

Time Input:   Dropdown | Grid | Text

I'm used to an input where I could just write **"1532"** and this would result in **15:32** and **"8"** would result in **08:00**.

I've put together a simple plunker which only shows this specific functionality for the input element:
https://plnkr.co/edit/vuGQeppYo97wmmVL?open=lib%2Fscript.js

Of course there will be some corner cases, but it doesn't seem to be too complicated. I could work on a PR that adds this as extra input field and from that integration into user preferences could be worked out

**Comment by kevinpapst** [comment]
Next version (see https://github.com/kevinpapst/kimai2/pull/2902) has a different input:
<img width="735" alt="Bildschirmfoto 2022-07-17 um 14 43 06" src="https://user-images.githubusercontent.com/533162/179398853-82141859-f6b1-4af8-8c49-95ea2e92a704.png">

You can jump in and help to further improve it (or comment here with test feedback).
What is missing right now is a nice time picker. Problem is that the time picker needs to support configurable locales and none of the tested ones had that built-in.

**Comment by Vivango** [comment]
My users have an issue to have in the popup the calendar date and time in same popup. Is there an option to put them in seperated fields?
