### ISSUE TITLE
Options to link different customers to a project and different projects to an activity

### ISSUE THREAD

**Issue by xtremelora** [kevinpapst/kimai2#572]
**Is your feature request related to a problem? Please describe.**
I need (and I think more people too) to be able to create **Projects that can be linked to one or more Customer** and also would be great to link one **Activity to one or more Projects without making them Global Activities** (I just want them to appear when specific Projects are selected).

I have some Customers (about 8) and my Projects are the same for all these Customers and also the Activities are the same for these Projects and Customers... Until now the only solution is to duplicate every entry and is frustrating as I have 169 Activities which means I would need to enter a total of 1352 Activities to give solution to this issue.

**Describe the solution you'd like**
It would be nice to have **Checkboxes** besides Projects to choose Customers to link to and of course the same option on Activities to link to different Projects.

**Describe alternatives you've considered**
Another option (less accessible but it will be a central point) would be to have a **special panel on Customer section** that let you select which Projects and Activities an specific Customer can use/access.

**Additional context**
Of course, if a Project is selected (from Customer's Panel) or attached (from Project Checkbox options) all the Activities belonging to that Project will be available for such Customer

**Comment by kevinpapst** [comment]
> my Projects are the same for all these Customers
I understand your frustration, but having the same name for a Project, doesn't mean it is the same Project. As often requested, having a bulk administration would probably the solution here. 

If you have the same 169 activities for all projects, why don't you want to make them global? 

Kimai is built very different from your request and this would basically mean rewriting the entire core. 
So this is nothing that I will add. I will close this a "won't fix", you might follow #814 which could be a solution for you and others with similar needs. I know, that is not exactly what you want, but at least a step that would make the initial setup easier.
