### ISSUE TITLE
Also put filtering option on the calendar view

### ISSUE THREAD

**Issue by jaapcrezee** [kevinpapst/kimai2#573]
**Is your feature request related to a problem? Please describe.**
Currently the calendar view shows all entries and does not have a filtering option.

**Describe the solution you'd like**
It would be very nice to also have the filter (*) option on the calendar view to only show certain entries in the view. In that case I can clearly see in the blink of an eye when I worked for a certain customer on the current calendar timespan/view.

(*) customer, project, activity.

**Comment by kevinpapst** [comment]
I really do not think, that the calendar is the right place to filter records. And considering that there were 3 votes  in 3,5 years, I believe this is safe to be closed for now.
