### ISSUE TITLE
Administration > Projects: Input for searching a project

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#574]
Hi Kevin,

my colleagues missing a input field for searching a project/customer in the filter section at the project/customer administration site.

In our case we have a lot of projects/customers and currently the filter section doesn't contain a field like this. 

(The background is that sometimes my colleagues attach a new project incorrect to a customer and after that they need to search for this project at the project administration site.)

**Comment by kevinpapst** [comment]
Yep, sounds reasonable. The list views are not ideal when dealing with too many entries.

**Comment by rarvin** [comment]
This is now present in 1.0, this is a great functionality thank you for it.

**Comment by kevinpapst** [comment]
No, this is not present and 1.0 is not even available.

**Comment by rarvin** [comment]
Apologies again, i was referring to the search in timesheets, i have deleted the last comment.

**Comment by kevinpapst** [comment]
Search fields for all admin screens is now available in master
