### ISSUE TITLE
Extend rounding options with "to closest" mode

### ISSUE THREAD

**Issue by nyquist2205** [kevinpapst/kimai2#576]
**Describe the solution you'd like**
I think a rounding option "to closest" would be cool. E.g. if I start at 6:59 and stop at 7:31, I'd like to get an entry with duration of 30 min (and start 7:00, end 7:30).

**Describe alternatives you've considered**
At the moment I use duration-rounding, but the example above leads to a duration of 45 min, what (especially for short entrys) is not so cool. Start/end rounding anyway would result in a duration of 60 min here...

**Comment by kevinpapst** [comment]
I am not sure if I understand what you exactly want...
Can you explain what exactly should be rounded and how, why you need that, some examples and if possible: how do you think could the rules look like?

**Comment by nyquist2205** [comment]
Okay... What I'd like to have is a way to round mathematically, to create "fair" duration logging and not always round upwards. So if the one value (start-time, end-time or duration) exceeds the half of the rounding-value it gets rounded upwards, else downwards.
Like in mathematics, where you allways will round 3.4 to 3 and 3.5 to 4.

E.g. let's call these options "begin-closest", "end-closest" and "duration-closest". So we could have following situations:

"begin-closest: 15", "end-closest: 15" in the configuration should result in: 
7:08 until 8:37 gets calculated to 7:15 until 8:30
7:07 until 8:37 gets calculated to 7:00 until 8:30
7:07 until 8:38 gets calculated to 7:00 until 8:45
7:08 until 8:38 gets calculated to 7:15 until 8:45

"begin-closest: 10", "end-closest: 10" in the configuration should result in: 
7:05 until 8:44 gets calculated to 7:10 until 8:40
7:04 until 8:44 gets calculated to 7:00 until 8:40
7:04 until 8:45 gets calculated to 7:00 until 8:50
7:05 until 8:45 gets calculated to 7:10 until 8:50

"duration-closest: 10" in the configuration should result in: 
7:08 until 7:43 gets calculated to 40 min
7:08 until 8:42 gets calculated to 30 min

Written as pseudocode (with % as modulo):
`if (begin % begin-closest < begin-closest/2) begin = begin - begin % begin-closest //round downwards

else begin = begin + begin-closest -  begin % begin-closest //round upwards`

I hope this makes it clearer what I'm trying to realize...
BTW: Thanks for your great work!! :-)

**Comment by kevinpapst** [comment]
Thanks for the detailed input!
This is the part where the rounding is applied ... not beautiful, but works ;-)
https://github.com/kevinpapst/kimai2/blob/master/src/Timesheet/Calculator/DurationCalculator.php#L81

Are you familiar with software development? Just asking  because. you know what pseudo-code is :D
Do you think you could come up with the PHP algorithm, then I will add all the other necessary changes so it can activated via config.

**Comment by nyquist2205** [comment]
It's not really my main job, but I'm okay with software development. I took the fast way and wrote 3 new functions with my rounding code. I already tested this in my installation (by replacing the original code) and it works fine!
That's what I've done (any better way than a *.txt upload??):
[kimaiRounding.txt](https://github.com/kevinpapst/kimai2/files/2871147/kimaiRounding.txt)

**Comment by kevinpapst** [comment]
Nice, thanks 👍 that was quick. I'll test and integrate it the next days.

If you want to show up as contributor, you need to send in a pull request, otherwise I can use the code from the text file - it's totally fine as well.

**Comment by nyquist2205** [comment]
Great, thanks!
No, I'm fine without showing up as contributor.

**Comment by kevinpapst** [comment]
Are you familiar with Git? If so, you could test if the changes in #611 are working as expected.

There is a new config setting for rounding called `mode`, which is optional:
```
        rounding:
            default:
                days: ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
                begin: 1
                end: 1
                duration: 0
                mode: closest
```

**Comment by nyquist2205** [comment]
Let's say I'm getting more and more familiar to git ;-)

I tested the new rounding mode and I think it's fine. I mentioned one thing, but it seems to be "correct":
If you start a new entry at, let's say 7:22 and expect it to be rounded to 7:15 it may round to 7:30. That seems to be because seconds are used for the calculations and (even if you can't see it in kimai) it was 7:22:50 or something which gets rounded upwards.

But as said, I think it's correct and cool like that, thanks!

**Comment by kevinpapst** [comment]
Thank you for your contribution! :-)
