### ISSUE TITLE
Support 12h time format

### ISSUE THREAD

**Issue by xtremelora** [kevinpapst/kimai2#578]
Is there any way to change the 24h format to 12h format?

**Comment by kevinpapst** [comment]
You can try to change the configs for your language:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L113
The ones ending with `_picker` are used in the javascript components.

But one place is still hard coded (this one is only used for display):
https://github.com/kevinpapst/kimai2/blob/master/src/Twig/DateExtensions.php#L86

I never tried to change it to 12 hour AM/PM format. If you are successful, we can make a PR to support it out-of-the-box.

**Comment by xtremelora** [comment]
Thank you for your answer.
I modify the kimai.yaml file and nothing happened.

When I modified the DateExtensions.php file the displayed format on My Time is the right one, just as I desire.

But, the time picker is still showing 24h format, I just replace HH:xx for hh:xx on every entry for my language but nothing is affected (I think it fall back to default format). The main issue with this is not me because I can easily manage 24h format but regular workers can not understand this format and that is why I am trying to change it.

**Comment by xtremelora** [comment]
May I ask where is the main function/class/code for Calendar/Time widget?
Is it a plugin included in kimai? An external function call? Or an integrated one?

**Comment by kevinpapst** [comment]
Reload config:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/configurations.md#reload-changed-configurations

Kimai uses this one:
http://daterangepicker.com
which uses moment.js for all the date formatting. It supports 12h format, but I never tested if it works in combination with Kimai.

The formats in kimai.yaml must match each other: the ones for the PHP side must result in the same exact format than the `_picker` ones for the javascript components => they are used for conversion.

**Comment by kevinpapst** [comment]
Datepicker is initialized automatically on each page call. The configs are taken mainly from data attributes on the form elements: https://github.com/kevinpapst/kimai2/blob/master/assets/js/kimai.js#L62

**Comment by xtremelora** [comment]
I found it...
I was checking the code last night and I saw that daterangepicker is 12h by default but in kimai it bring the line "timePicker24Hour: true".

On the official web site if you disable that line it will show 12h format and it will add a AM & PM drop-down menu after minutes.

I haven't test it yet but I think that is what I need.

**Comment by xtremelora** [comment]
Oooppsss.

Not working even if I disable 24h format in kimai.js

**Comment by kevinpapst** [comment]
Pretty sure there is more to do than just remove that one line. The datetime-format must match a 12 hour pattern as well.

**Comment by kevinpapst** [comment]
BTW ... you know that you have to recompile the frontend assets? 
Otherwise the change won't be used: https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#frontend-dependencies

**Comment by xtremelora** [comment]
I didn't know that. Thank you for your assistance. I will try that and I will review the code again.

**Comment by xtremelora** [comment]
@kevinpapst after recompiling assets front end it worked...
[https://photos.app.goo.gl/2fSze6eNMgQHHZNGA](url)

The only issue I have found now is that doesn't matter if I select AM or PM on the ending hour, if it is menor than starting hour it will show an error.

For example, if I mark 7am in the starting hour and I select 3pm on ending hour kimai still sees that as an error considering 3 menor than 7, so the issue I think is related with AM/PM format conversion.

Any clue??

**Comment by kevinpapst** [comment]
Did you change the date and time configs in kimai.yaml? Show me your complete date config please.

As mentioned in my first answer, both components frontend and backend must understand each other.
From your screenshots it looks as if the date picker does not add the AM / PM part to the input field, so this is  the first place you have to check.

I would try this for the frontend:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L115
=> `date_time_picker: 'YYYY-MM-DD hh:mm A'`

**Comment by xtremelora** [comment]
This is how my kimai.yaml looks: https://pastebin.com/gm3nZbRT

And this is the error I am getting now:

![screenshot_20190221-123858__01](https://user-images.githubusercontent.com/24559481/53454987-b26d0680-39ee-11e9-9053-7356dec26bf4.jpg)

**Comment by xtremelora** [comment]
@kevinpapst should I modify something else on the timepicker code?

**Comment by kevinpapst** [comment]
According to this docu:
https://symfony.com/doc/current/reference/forms/types/datetime.html#date-format
you need to use these formats:
http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax
Probably its enough to change from
`date_time_type: 'yyyy-MM-dd hh:mm A'`
to
`date_time_type: 'yyyy-MM-dd hh:mm a'`?

**Comment by kevinpapst** [comment]
@xtremelora please test the PR #615 which uses am/pm format for `en` now by default.

**Comment by xtremelora** [comment]
> Probably its enough to change from
> `date_time_type: 'yyyy-MM-dd hh:mm A'`
> to
> `date_time_type: 'yyyy-MM-dd hh:mm a'`?

On my 0.8 version this worked very well, now I don't have errors on the picker nither on the frontend, the only cosmetic issue is that on the frontend there isn't AM/PM representation but I understand the time frame.

**Comment by kevinpapst** [comment]
Yep. But you patched the JS file, which will be gone after the update. Thats why the new configs were introduced.
