### ISSUE TITLE
resize mobile navbar buttons

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#582]
**Is your feature request related to a problem? Please describe.**
The menu on mobile devices such as the Samsung Galaxy S9/S9+ is in two rows.

![grafik](https://user-images.githubusercontent.com/36242595/53021772-3d338b80-345a-11e9-956b-80dab782d60f.png)

**Describe the solution you'd like**
Make the size of the buttons/icons in the mobile navbar a bit smaller that they fit in one row.

Changing the font-size of the navbar to 9pt instead of 14pt did the trick:
![grafik](https://user-images.githubusercontent.com/36242595/53022313-3b1dfc80-345b-11e9-8bf9-4277eaac68c3.png)

**Comment by kevinpapst** [comment]
Thanks for the info! Will be adjusted

**Comment by kevinpapst** [comment]
Okay, I am almost there... but one question:
you say, you decreased the size from 14**pt** to 9**pt**.
When I check the elements, I can only see a font-size of 14**px** for the link. 
And decreasing it to 12px was enough to stop it from breaking.

**Comment by hmr-it-jr** [comment]
Hm, I used the arrow keys to count down the font size and it was good at 9. Maybe the view didn't update as fast as i counted down the value.

**Comment by kevinpapst** [comment]
I was more curious about pt vs px, but doesn't matter. 
I updated the size and padding, should. be good on mobile and desktop now.

**Comment by hmr-it-jr** [comment]
I've tested it and it looks good. What do you think about removing the headline above the nav bar?

![grafik](https://user-images.githubusercontent.com/36242595/53050192-0d57a880-3499-11e9-85e3-7197a036b114.png)

It refers to /homepage which forwards to /timesheet

**Comment by kevinpapst** [comment]
Actually it forwards to your setting "Initial view after login", so it could be the calendar as well.
I am not sure about removing it, but go ahead and open a new issue and we see what others think about it. I am planning to finally adopt a plugin system and this feature (hide mobile header) could be a simple one...

**Comment by kevinpapst** [comment]
Oh and thanks for testing! Too bad we just found out that bug after the release ;-)
