### ISSUE TITLE
Entry editor label wrong (from/to)

### ISSUE THREAD

**Issue by nyquist2205** [kevinpapst/kimai2#587]
Small one, but couldn't find an existing issue:

**Describe the bug**
In the entry editor (pencil symbol in timesheet view), the times are labeled "From" and "From" instead "From" and "Until". Also in the german version it's a double "Von".

**To Reproduce**
1. Go to Kimai demosite
2. Click on edit button of an entry (or start a new one)
3. See error

![unbenannt](https://user-images.githubusercontent.com/47365194/53055669-d4273480-34a8-11e9-82ec-125d54840e77.PNG)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - OS: Win10
 - Browser: Firefox

**Comment by kevinpapst** [comment]
LOL, so obvious but missed it nevertheless. Thanks for posting!

**Comment by xtremelora** [comment]
On my server installation it show it correctly. "From" & "To". En locale.
