### ISSUE TITLE
remove mobile navbar header

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#588]
**Is your feature request related to a problem? Please describe.**
At the moment Kimai - Time Tracking uses a lot of space on mobile views.

![grafik](https://user-images.githubusercontent.com/36242595/53071313-233d8b80-34e2-11e9-9fc4-e56384fc1aad.png)

**Describe the solution you'd like**
"Home" should be added to the left menu swiper. Some margin/padding adjustments are needed, but it gives you more space on devices with a small screen.

![grafik](https://user-images.githubusercontent.com/36242595/53071419-7ca5ba80-34e2-11e9-81fd-ebc575a3f8b6.png)

**Comment by kevinpapst** [comment]
Hey @hmr-it-jr, if you have the time and will to help testing?!

In #592 I added functionality for easy plugin loading.

I also created a first demo plugin, which adds the ability for custom css rules:
https://github.com/keleo/CustomCSSBundle

It comes with some pre-made rules, which can be added with a click of a button. 
One of these rules is the necessary css to "remove header on mobile". 

I'd appreciate if you could test that and let me know how it goes.

**Comment by hmr-it-jr** [comment]
Hey @kevinpapst, of course I'll test it!

It's a pretty good idea to make it available with predefined rules and it works like a charm:
![grafik](https://user-images.githubusercontent.com/36242595/53266824-2dc67380-36e2-11e9-8777-dc564c587f85.png)

What do you think about adding a comment by default to the css if you use predifined rules? Or maybe add a font-awsome check icon to the rules which have been applied?

![grafik](https://user-images.githubusercontent.com/36242595/53266928-7716c300-36e2-11e9-9e14-939bd13615fd.png)

**Comment by kevinpapst** [comment]
The comment sounds like a good improvement.
The icon instead could easily cause problems. When the user changes even one whitespace the detection could fail.

If you have further rules, which could be used by all users - they can very easily be added, they are basically only single css files:
https://github.com/Keleo/CustomCSSBundle/tree/master/Resources/ruleset

**Comment by kevinpapst** [comment]
Done, closing
