### ISSUE TITLE
deletion of customers leads to internal server error 500

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#589]
**Describe the bug**
By sorting out a few old customers in my database I've noticed that after the deletion of some I wasn't able to switch back to timesheet again.

**To Reproduce**
1. Go to https://demo-v2.kimai.org/en/admin/customer/
2. Delete all customers
3. Try to go to "My times" https://demo-v2.kimai.org/en/timesheet/

**Screenshots**
![20190220_073041](https://user-images.githubusercontent.com/36242595/53071989-1883f600-34e4-11e9-98d9-544c967b089b.gif)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: PC
 - OS: Win10
 - Browser: Firefox
 - Version: 65.0.1

**Additional context**
 - Kimai version: latest
 - PHP version: 7.2

**Comment by kevinpapst** [comment]
That screen-recorder is really cool. Which one is it?

Regarding the bug: that is a problem of SQLite, which doesn't cascade deletes via foreign keys and thats why I discourage to use it in production.
When deleting a customer (and not passing the records to an "anonymous customer", the database should:
- delete all linked projects
- delete all linked activities
- delete all links timesheet records
But SQLite isn't doing it like a proper database should, so you have orphaned entities in the database.

https://github.com/kevinpapst/kimai2/blob/master/var/docs/faq.md#sqlite-not-recommended-for-production-usage

**Comment by kevinpapst** [comment]
I knew about this problem for quite a while, but I wasn't aware that the behavior to activate foreign keys and cascade deletes can be configured per connection.
I added a PR that fixes the problems.

**Comment by hmr-it-jr** [comment]
Yes, the screen recorder is nice. It has a lot of functions and it's free: [https://www.chip.de/downloads/Kostenloser-Bildschirmrekorder_86422110.html](https://www.chip.de/downloads/Kostenloser-Bildschirmrekorder_86422110.html) If you want to download it, **do not** click the blue "download" button - **click "Manuelle Installation"**.

I haven't tested mysql because I just wanted to test and play with Kimai 2 since it's 0.8 and will be out of beta soon. Thanks for fixing it anyway!
