### ISSUE TITLE
remove duplicate confirm dialog of deletion

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#591]
**Is your feature request related to a problem? Please describe.**
If you want to delete a user, customer, project or activity which is in use you have to confirm two times that you really want to delete it. First time is confirm dialog with pure Javascript and second time is is in a box by AdminLTE.

**First confirm:**

![grafik](https://user-images.githubusercontent.com/36242595/53117645-a810bf80-354b-11e9-8cf5-3e3beb67b160.png)

**if you confirm with ok you'll see this:**

![grafik](https://user-images.githubusercontent.com/36242595/53117675-b8c13580-354b-11e9-99b1-78958ab524a8.png)

**Describe the solution you'd like**
Instead of asking the user twice when he clicks the trash bin open a modal [(https://adminlte.io/themes/AdminLTE/pages/UI/modals.html)](https://adminlte.io/themes/AdminLTE/pages/UI/modals.html) and show him what he is going to delete with the stats (e.g. in how many projects this activity is used).

![grafik](https://user-images.githubusercontent.com/36242595/53118262-fffbf600-354c-11e9-937f-fe1ef85332ad.png)

p.s. maybe with the modal it's possible to not leave the route?
p.s.s. the activity transfer select can be put in the modal, too.

**Describe alternatives you've considered**
Just remove the pure JS confirm dialog and use the current existing box confirm dialog.

**Comment by kevinpapst** [comment]
The JS confirm was born first, then came the dialog ... and the confirm was never deleted ;-)
Good idea with the modal.

We just have to make sure that nothing gets deleted accidentally:
if I remember correctly users or activities without any record will be deleted directly when the JS dialog was confirmed. The modal needs to be shown for these cases as well.

**Comment by hmr-it-jr** [comment]
Yes, correct - if there are no entries for the specific item it'll be removed immediately after the JS confirm dialog. So showing the modal with 0s in it for this special case is ok. If you don't think so you can check it and put a different message in the modal if the item doesn't have any entries.

**Comment by kevinpapst** [comment]
I started working on this and could use some feedback @hmr-it-jr

**Comment by hmr-it-jr** [comment]
@kevinpapst sorry for late response...

fyi:
I've tested it on master and it looks great!
![grafik](https://user-images.githubusercontent.com/36242595/54311791-a16aea80-45d5-11e9-95e8-37b1acb6a7e9.png)
![grafik](https://user-images.githubusercontent.com/36242595/54311815-acbe1600-45d5-11e9-9ade-901bdbfe84fd.png)

**Comment by kevinpapst** [comment]
No deal, I am happy when you find the time ... any time :-D

Thanks for the feedback!
