### ISSUE TITLE
create a timeline per activity in the timesheet

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#596]
**Is your feature request related to a problem? Please describe.**
This issue is not directly related to #224 but it logs manipulations or changes in the timesheet.
I thought about what the lifecycle of an activity is - it's:

- being created
- times added
- times changed
- exported / or in use with an invoice
**and then maybe:**
- marked as not exported
- times changed
- exported again
- ...

Maybe it's possible to add a trigger to the database which stores the changed thing and then the admin or any other role with the permission is possible to view the lifecycle.
The most important information are:

- who has changed it
- when was it changed
- what was changed

**This feature can be used for: projects (when was the project created, ...), activities (change of rates per acitivity, ...), customers, ...., too.**

Then it's perfectly comprehensible what has changed, when has it changed and who did the change.

**Describe the solution you'd like**
Already mentioned above.

In the gui framework AdminLTE there is something called timeline which is perfectly for this. [https://adminlte.io/themes/AdminLTE/pages/UI/timeline.html](https://adminlte.io/themes/AdminLTE/pages/UI/timeline.html) - as a suggestion we can add a "fas info-circle" which opens the lifecycle of the activity, user, project, .... in a modal:
![grafik](https://user-images.githubusercontent.com/36242595/53291141-be6a8580-37ae-11e9-9c9b-a69e52097d72.png)

**Timeline example:**
![grafik](https://user-images.githubusercontent.com/36242595/53291197-d989c500-37af-11e9-937b-7ceb011fe2de.png)

**Comment by kevinpapst** [comment]
Very good idea!

Dropping some infos for future reference:
- https://symfony.com/doc/current/doctrine/common_extensions.html
- https://github.com/Atlantic18/DoctrineExtensions
-https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html

Using the LoggableListener, this should be possible "quite easily".

**Comment by kevinpapst** [comment]
I worked on the audit trails, could you test #623 ?

**Comment by kevinpapst** [comment]
Now available as payed plugin https://www.kimai.org/store/audit-trail-bundle.html
