### ISSUE TITLE
Failed to import users: failed to validate user

### ISSUE THREAD

**Issue by Richigeht** [kevinpapst/kimai2#600]
**Describe the bug**
I try to migrate my data from Kimai V1 but I do get an error then I try to do so. 

**To Reproduce**
1.  bin/console kimai:import-v1 "mysql://kuser:.xxx@127.0.0.1:3306/kimai?charset=latin1" "kimai_" ".xxx" -vvv

**Logfile**
[ERROR] Failed to import users: Failed to validate user: xxx
         #0 /var/www/kimai2/src/Command/KimaiImporterCommand.php(263):
         App\Command\KimaiImporterCommand->importUsers(Object(Symfony\Component\Console\Style\SymfonyStyle), '.xxx',
         Array, Array)
         #1 /var/www/kimai2/vendor/symfony/console/Command/Command.php(255):
         App\Command\KimaiImporterCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #2 /var/www/kimai2/vendor/symfony/console/Application.php(911):
         Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #3 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(89):
         Symfony\Component\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #4 /var/www/kimai2/vendor/symfony/console/Application.php(262):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #5 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(75):
         Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #6 /var/www/kimai2/vendor/symfony/console/Application.php(145):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #7 /var/www/kimai2/bin/console(39):
         Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
         #8 {main}

**Screenshots**

**Additional context**
 - Kimai version 0.8.3
. - PHP version 7.3

If I could get more information on where to find logs etc. I would troubleshoot this myself.
I also do get: 
 [ERROR] Object(App\Entity\User).email:
             This value is not a valid email address. (code bd79c0ab-ddba-46cc-a703-a7a4b08de310)

However I checked now all mail addresses and they are actually correct.

**Comment by kevinpapst** [comment]
Did you check the emails in the Kimai 1 database?
Kimai 1 was terrible when it comes to data integrity. I already added multiple workarounds for defect data, but that one is very likely on your end. 
If you database is really okay, I would need a dump of at least the users table for debugging.
There is just `var/logs/prod.log` and I don't know if the import logs there.

You could add some debug comments around this code:
https://github.com/kevinpapst/kimai2/blob/master/src/Command/KimaiImporterCommand.php#L511

The error is coming from the Symfony framework and says:
`const INVALID_FORMAT_ERROR = 'bd79c0ab-ddba-46cc-a703-a7a4b08de310';`
but I don't know what that means. 
What is the email adress of that user? Simply replace all chars with x to prevent abuse if you paste it here.

**Comment by Richigeht** [comment]
Hi
I did but will re-check. Thanks for the hints I will try my best and in worst case I might just reset all mail addresses so that the user have to update them manually later to see if this helps. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by Richigeht** [comment]
Hi, 
apparently the address included a "," instead of a "." hence the error. Also it does not like duplicates but at least the users are imported now.
The rest of the data gets imported now - hopefully without issues.

**Comment by kevinpapst** [comment]
Was everything successful, or did you find anything else?

**Comment by Richigeht** [comment]
Hi
Thanks for the follow up - I did run into errors indeed. Not with users that’s fine but with actual data entries. 
However since the import took forever I did get side tracked and forget to follow up. 
I will post new logs next week or the weekend. But the user import works. I will close the ticket. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
You already closed it. But I have had several issues with the import in the past, as Kimai 1 didn't use foreign keys and produced a lot of broken relationships/invalid data. 
I'd be glad to fix these problems, just let me know what happened!

**Comment by Richigeht** [comment]
Thanks, seems like the issues were cause due to endtime set to 0 (I expect at least that was the issue, will reimport everything now). 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
Had a look at the code and you might be correct. If it fails again, please add these lines here:
https://github.com/kevinpapst/kimai2/blob/master/src/Command/KimaiImporterCommand.php#L962
```
            if (empty($oldRecord['end']) || $oldRecord['end'] === 0) {
                $io->error('Cannot import running timesheet record, skipping: ' . $oldRecord['timeEntryID']);
                continue;
            }
```

**Comment by Richigeht** [comment]
Hi
I manipulated the data it worked now. Some users were disabled after the migration but I just modified it in the database as well (since it's just a test import it does also not really matter).

**Comment by kevinpapst** [comment]
You manipulated the data any our Kimai 1 database?

Please share our insights with me, so I can improve the importer!

**Comment by Richigeht** [comment]
Yeah; I just made a simple update statement to make the END=START time for those entries with end value 0.
After that I had to just check some users which have been set to "enabled=0" in the users table. Not sure why that was since those have been active on kimai1 however just checking the data: it looks like they had a banTime set against them.
