### ISSUE TITLE
Unable to select «projects» while filtering in timesheets

### ISSUE THREAD

**Issue by trfnvo** [kevinpapst/kimai2#601]
Hello Kevin,
Tanks for Kimai! 
Bug: in admins timesheets (*/team/timesheet/) I can't select «Project» while filtering, but some projects exists

1. Go to https://demo-v2.kimai.org/en/team/timesheet/
2. Click on Filter button, press «Projects» dropdown
3. See no projects in this menu while it existst in list below: https://i.imgur.com/gaGsrGi.jpg

Kimai version: Kimai2 0.8.1
PHP version: 7.2.15

**Comment by kevinpapst** [comment]
Thanks for the report @trfnvo 👍 
Unfortunately I don't see a way to fix that for now. You have to select the customer before the project list is populated.

**Comment by hmr-it-jr** [comment]
@kevinpapst you could disable the projects select dropdown by default - and with onchange event on customer select dropdown you can enable the projects select dropdown.

**Comment by kevinpapst** [comment]
Another option would be to pre-populate the list with all projects, but that could be a problem for the people with hundreds of projects. And we would need to activate the JS select extension by default, which allows searching inside the project title. 
Deactivating for non-selected customer is easier and for now consistent with the other forms

**Comment by BKapelari** [comment]
> Thanks for the report @trfnvo 👍
> Unfortunately I don't see a way to fix that for now. You have to select the customer before the project list is populated.

I can't see any project even if I select a customer. Same in the other views (export, …)

**Comment by kevinpapst** [comment]
@BKapelari please open a new issue if fixing the directory permissions for var/cache/ doesn't help. The API needs write permissions in that folder and in var/cache/prod/.

**Comment by BKapelari** [comment]
> @BKapelari please open a new issue if fixing the directory permissions for var/cache/ doesn't help. The API needs write permissions in that folder and in var/cache/prod/.

# Problem solved!
I've changed the permissions to 777 no changes. So I have reset the permissions to 755.

## What solved the problem:
In my Plesk hosting settings I've selected another PHP-Version (v7.3.6) and that solved the problem. Maybe it was a caching problem on the server.
