### ISSUE TITLE
Revoke of start_own_timesheet permission doesn't prevent start active entry

### ISSUE THREAD

**Issue by dzmudist** [kevinpapst/kimai2#606]
Having ROLE_USER granted only permission for [view_own_timesheet, create_own_timesheet,    edit_own_timesheet] and not having granted permission [start_own_timesheet] doesn't prevent user to create timesheet entry with duration=00:00, which automatically starts active timesheet entry, which starts counting time, while not having 'start_own_timesheet' permission should prevent user to start active timesheet record. If there is no 'stop_own_timesheet' permission, then user doesn't have right to stop automatically started active timesheet entry.

1. Go to local.yaml and set 
   kimai.timesheet.duration_only: true
   kimai.permissions.roles.ROLE_USER: [view_own_timesheet,create_own_timesheet,edit_own_timesheet]
2. Login as a user which belongs to Role User and create new timesheet entry, leave duration value as default (e.g 00:00), hit Save.
Actual behavior: new timesheet records is added and timer started on it.
Expected behavior: user cannot create active record if there is no 'start_own_timesheet' access right for that.

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome

 - Kimai version: 0.7

**Comment by kevinpapst** [comment]
Thanks for the info, I will look into it the next days

**Comment by kevinpapst** [comment]
I am working on this right now. Fixed it for "normal mode" but duration_only mode is still failing. 
I'll need some more time to fix this for duration_only mode as well.
Will keep you updated. In the meantime you could test PR #613 and help testing if you have the time.

**Comment by kevinpapst** [comment]
That was more complicated than I thought, as some technical debts had to be fixed first.
Please read #613 for more information.

**Comment by kevinpapst** [comment]
@dzmudist Do you think you have the time to test this change and provide some feedback in the next days?

**Comment by dzmudist** [comment]
Optimistically I will be able to find time closer to weekends, I will try to test.

**Comment by kevinpapst** [comment]
Ok, couldn't way until then. It is now available in master and can be tested there.
