### ISSUE TITLE
Ability to configure if active entries (with active timer) allowed

### ISSUE THREAD

**Issue by dzmudist** [kevinpapst/kimai2#607]
**Is your feature request related to a problem? Please describe.**
Having an intention to disable active timehseet entries (continue counting time until stopped) attempt to set kimai.kimai.active_entries.hard_limit=0 was failed to reach the desired behavior. It looks like min value for hard_limit is 1.

**Describe the solution you'd like**
Expected solution is either allow hard_limit value to be set to 0 or another boolean flag incroporated (e.ge active_entries_enabled:true|false)

**Describe alternatives you've considered**
start_own_timesheet permission should prevent user to start active entry, but there is a bug #606, which creates possibility to create timesheet record with duration=00:00, which automatically causes this record to become active and start timer.

**Comment by kevinpapst** [comment]
May I ask why you want to have a time-tracker that does not allow to track times?
What is the use-case behind this?

**Comment by dzmudist** [comment]
Sure, here is user stories for 100+- peoples who I know do track their time:
As a user I would like to populate timesheet in the end of work day.

For most of who I work with it is inconvenient to start and stop timer, because you switch context to many times per day in most cases switch is not planned and emergent (e.g - hey could you please help me with that feature? - sure, here is explanation). Below is example of one day report:
1 to 1 (Employee 1) (0.5h)
1 to 1 (Employee 2) (1h)
Training (subject xxx) (1h)
Product development sync meeting (1h)
New Project P1 discussion  (1h)
HR (discuss offers, review hiring plans) (1.5h)
Time tracking (model various schemas of Customer/Project/Activity definition) (1.5h)
Bug in product XYZ (investigate why functionality doesn't work since release N) (0.5h)
Customer request in scope of project P2  (write email with proposal) (0.5h)
Other activities (read emails, answer to adhoc questions) (2h)

In 95% of cases all tracked Activities belongs to the same Customer, but to different Projects.
In many cases you are not in front of your computer. Having mobile phone to start/stop tracking is not convenient, because you have just few minutes to switch location (e.g from one meeting room to another or somebody ask a favor and it is easier to answer immediately). You don't want spend time on writing description of what you just did or what you will do. It is easier to write everything in the end of day when you are calm.

Having that in mind another feature that would be nice to have is batch report creation, which would allow from a single screen populate multiple activities for different projects/customers, such that date is selected once per batch, total hours can be seen as a sum of all entered activities in order to check actual vs expected total hours per day and save button persists all the records at one hit.

**Comment by dzmudist** [comment]
Forgot to say, ability to disable active records on the product level is requested in order to escape problem when user by mistake creates a record and forget to specify duration, leaving it =0, which unexpectedly to that user starts timer, which with high probability will not be acknowledged and may screw up monthly report, because it will contain records with duration bigger than it really should be.  So, I'd say it better to have record with duration=0, rather than have record with duration 24h or bigger (not sure if tool automatically stops timer after certain period of tracking). 

Meanwhile, for others who do use active timers, it may be good to have configuration which will determine where active records are allowed, granularity is not clear: may be per user/role or/and may be per activity. But it definitely should be explicit intention of a user to start time, rather then implicitly when you don't expect that to happen or when you unintentionally forgot to enter duration.

**Comment by kevinpapst** [comment]
Thanks for the explanation! I misunderstood you initially, but now I get what you want to achieve.

I guess you are using the duration_only mode, as only there it is possible to enter 0 as duration. 
In the normal timesheet form you have a start and end date and setting it to the same value creates a stopped record with zero duration.
I'll check why duration_only mode behaves different and starts a timer with zero duration.

@lduer do you have an opinion about hard_limit = 0?

**Comment by lduer** [comment]
Did I get you right: You simply want to use `hard_limit = 0` to disable the use of active timesheets? (all timesheets need to have an endtime when submitting)

I think it's very good to use this configuartion-variable  :)

**Comment by kevinpapst** [comment]
@dzmudist first of all: thanks for your detailed input, explanations and ideas.
But to be able to manage this project, I have to ask you to create separate issues for separate feature request (e.g. batch record creation).
Being able to configure where active records are allowed sounds like an edge case which I am not going to support.

But back to this issue: I gave this another thought and think this feature request is not required, as the bug in #606 is fixed. The permission `start_own_timesheet` and `start_other_timesheet` already covers this use-case.

Would you agree or do you have anything else in mind with the hard_limit 0 that cannot be covered with the permissions?

**Comment by dzmudist** [comment]
I agree, no need to have extra setting for enable/disable active records, since having ability to grant/revoke start_own_timesheet to necessary roles will give required granularity of control, because If ability to create custom Groups and assign permissions on them will be added to permission system (like in Kimai1 probably), then it will cover ability to manage who are allowed to start_own_timesheet on per user basis and it will be exactly the use case that I had in mind while said "configuration which will determine where active records are allowed".
Thanks!

**Comment by kevinpapst** [comment]
A finer detailed permission system based on customer and/or projects is on my roadmap, even though that might need some time. 
Okay, then I will close this issue. Thanks again for your input!
