### ISSUE TITLE
Installation and permission problems

### ISSUE THREAD

**Issue by coneng** [kevinpapst/kimai2#608]
**Describe the bug**
the following part doesn't work properly... keeps failing with SSL Operation fail or /cache folder is not writable..etc., download fail
sudo -u www-data composer install --no-dev --optimize-autoloader

tried root or other user and same thing

**To Reproduce**
try to install fresh
create a user, install Apache, MySQL and php 

**Logfile**
```
- Installing doctrine/inflector (v1.3.0): Cloning 5527a48b73 from cache
  - Installing doctrine/common (v2.10.0): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download doctrine/common from dist: The "https://api.github.com/repos/doctrine/common/zipball/30e33f60f64deec87df728c02b107f82cdafad9d" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: VM
 - OS: ubuntu 18.04
 - Browser firefox 
 - Version 65.0.1

**Additional context**
 - Kimai version 2

**Comment by hmr-it-jr** [comment]
I don't think this a problem of Kimai 2 itself since it works for me and others. I think this is a problem of your server.

Have you checked your system time? Correct system time is coercing for SSL.
Have you tried to install this on your server?
```bash
apt-get install ca-certificates apt-transport-https openssl
```
And then test it again?

**Comment by coneng** [comment]
it is a waste of time... everything fails... can't user www-data, cant use root, can't use proxy, 

this error now:
In Filesystem.php line 232:

  Could not delete /var/www/html/kimai2/vendor/friendsofsymfony/rest-bundle:

**Comment by coneng** [comment]
this error
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---flex.symfony.com/, or directory is not writable. Proceeding without cache

**Comment by xtremelora** [comment]
@coneng that is a problem on your permissions file and folders structure, it has nothing to do with kimai.

I was running into the same issues before and is just related to your server's permissions.

**Comment by xtremelora** [comment]
Run:
chown -R www-data:www-data /your/directory

You may need to re-run this command if you run superuser commands after as they will get roots permissions flags.

**Comment by kevinpapst** [comment]
No bug, no feedback, closing.
