### ISSUE TITLE
Some activites don't show up in last activities

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#609]
**Describe the bug**
On my production server some projects don't show up on last activities dropdown. 
The database is originally imported from kimai 1. After I first discovered this bug I changed all of the imported activities to global activities. This was before the only 10 last activities update. This bug remained, and I still have some activities that missing from that dialog.
I reinstalled the whole server last week, and reimported the database, but some of them still don't show up there.
I can't find any pattern why they are not showing. They are not containing any special character. Some show up from the same customer, same activities show up for different customer etc, they are totally random.

My question is where should I look for reasons? If you want to check it, I can give access to my server, or send a mysqldump.

**To Reproduce**
I cannot reproduce this bug, exists only on my installation

**Additional context**
 - Kimai 0.8
 - PHP 7.2
 - mysql: 10.1.37-MariaDB-0+deb9u1
 - db charset: utf8mb4

**Comment by kevinpapst** [comment]
This is the query which finds the activities:
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/ActivityRepository.php#L43
You could add a `var_dump($qb->getQuery()->getSQL(), $qb->getQuery()->getParameters());exit;` in line 70 and execute the generated SQL (you have to replace the placeholders with the parameter values before). 

Maybe a sanitized dump would help, so I can debug it. 

The rules are:
- fetch the 10 last activities 
- for the current user
- that where used in the last year => "now - 1 year "
- ordered by the usage in your timesheet records
- where activity, project and customer are not hidden

**Comment by kevinpapst** [comment]
@infeeeee any feedback on this one? wanna share your db dump?

**Comment by infeeeee** [comment]
The output of var_dump is here: https://pastebin.com/qH5FEE2V 
I replaced my personal information. 

My knowledge of sql is very limited so I don't know what I have to replace with what.

I will send the dump to your email: kevin at kevinpapst dot de.

**Comment by kevinpapst** [comment]
This will give you all IDs from the timesheet table, that were selected:
```
SELECT MAX(k0_.id) AS sclr_0 FROM kimai2_timesheet k0_ INNER JOIN kimai2_activities k1_ ON k0_.activity_id = k1_.id INNER JOIN kimai2_projects k2_ ON k0_.project_id = k2_.id INNER JOIN kimai2_customers k3_ ON k2_.customer_id = k3_.id WHERE k0_.end_time IS NOT NULL AND k1_.visible = 1 AND k2_.visible = 1 AND k3_.visible = 1 AND k0_.user = 1 AND k0_.start_time > "2019-01-14 22:29:34" GROUP BY k1_.id, k2_.id LIMIT 10
```
But never mind, I will debug this later on with your dump.

**Comment by infeeeee** [comment]
The query shows the correct values, however they are not the ones that show up on the dialog. Their order on the dialog is correct, five of them missed out, and other 5 added to the end of the list which are not in the output of the query.

Only the first five shows up on the dialog. The sql output is not ordered.
```
+--------+
| sclr_0 |
+--------+
|   2010 |
|   2268 |
|   2138 |
|   2266 |
|   2236 |
|   2149 |
|   2262 |
|   2258 |
|   2130 |
|   2157 |
+--------+
```

**Comment by kevinpapst** [comment]
Huh? Thats really weird. The result is only ordered by the end time of the timesheet records:
https://github.com/kevinpapst/kimai2/blob/master/src/Repository/ActivityRepository.php#L89
Still working on something else, but I'll let you know after I was able to test it with your dump.

**Comment by kevinpapst** [comment]
Your DB dump was very helpful, thanks!
Seems when fixing one issue, I introduced another some weeks ago.

There is a new PR, can you please test if this change is working on your side as well: 
https://github.com/kevinpapst/kimai2/pull/631/files
