### ISSUE TITLE
Customer: Quota / Kontingent

### ISSUE THREAD

**Issue by John231** [kevinpapst/kimai2#612]
At first, great work! I love it!

**Is your feature request related to a problem? Please describe.**
Is there a customer quota function?
The first three hours for 40 €/hour and all over the first three hours, 50€ / hour  

**Describe the solution you'd like**
The agent starting kimai, working three hours for 40€ / hour, and then automatically for 50€ / hour. 

**Describe alternatives you've considered**
no alternatives ;)

**Additional context**

**Comment by HeinzWuert** [comment]
Solution: Use 50€ as standard but ask for the option to change that individualy ;)

**Comment by kevinpapst** [comment]
Nope, not available in the core and no plans to add it. Could be done as plugin.
