### ISSUE TITLE
Ability to save combination of Customer/Project/Activity into Favorites and make one default

### ISSUE THREAD

**Issue by dzmudist** [kevinpapst/kimai2#617]
Feature request created based on topic discussed in #403

**Is your feature request related to a problem? Please describe.**
As a user I would like to save Customer+Project+Activity combinations as "favorite" such that when creating new record in timesheet I can select it from the list of saved favorite combinations as result selected "favorite combination" will fill Customer Project and Activity fields
As a user I would like to make saved favorite combination as default such that when create new record this particular favorite combination populates Customer/Project/Activity fields.
As a user I would like to set custom label for saved favorite combination in order to make it easier to find required combination in the list of other saved favorite combinations because custom names would be shorter and better recognizable.

**Additional context**
In the past I used to work with home-grown time tracking system, where was ability to predefine default Customer/Project, such that when you create new report then Customer and Project fields got populated. It was convenient for those developers and qa who continue work on the same project for long time, because they mostly switch only between Activities like: development, code review, testing, investigation, etc, but for example they may interrupt for several hours or days to do work for other projects and customers, thus fields Customer and Project are still should be available for them to set other Customer and Project than specified in default value.
Meanwhile for those persons who deals with multiple projects in the same day (e.g architects and management) it was not enough to have just one default combination and these persons has to dig through tons of customers/projects and activities in the drop downs in order to find the one they need. But even so, within a period of time, like week or month, in 80% of cases they switch between small subset of Customers and Projects. In average I would say that 80% of time you switch between about 5-7 mutually exclusive combinations of Customer/Project/Activity.

Having that in mind the feature that may be useful and covers "default value for Customer/Project/Activity" will be something like "Saved Favorite Combinations" where one of saved favorite combination can become "Default Favorite Combination".

**Comment by kevinpapst** [comment]
The next major version #2902 will have an option to bookmark entries in the recent activities dropdown.

**Comment by kevinpapst** [comment]
The bookmark feature looks like that:
<img width="475" alt="Bildschirmfoto 2022-08-02 um 18 39 27" src="https://user-images.githubusercontent.com/533162/182427872-7a39ad6b-0fa4-4ea1-8e43-bffe185ade87.png">

In the "restart your recent activity" menu you get a bookmark link, which will pin this specific entry to the list (the yellow bookmarks). By clicking the yellow star, the bookmark will be removed. 

I am closing here for now and would ask everyone (also the ones who voted) to help testing and then leaving your feedback for the new version (link to the demo in #2902). I am keen to further improve that workflow, once all had a chance to use this feature for a while in production. Please open new feature requests then. Closing here.
