### ISSUE TITLE
Time selection dropdown not working in Firefox

### ISSUE THREAD

**Issue by nyquist2205** [kevinpapst/kimai2#618]
**Describe the bug**
If you try to create or edit a timesheet entry in Firefox, you can't choose the time, because the dropdown menus aren't working properly. It seems like the menu is opened and and closed again instantly.  

**To Reproduce**
1. Go to https://demo-v2.kimai.org/en/timesheet/ (with Firefox on Windows)
2. Edit existing entry and try to change a time
3. See error

**Screenshots**
![kimai_dropdown](https://user-images.githubusercontent.com/47365194/53818846-0afd5000-3f69-11e9-93f1-3ee16511f818.gif)
Note that some of the mousclicks (red circles) aren't displayed correctly in the GIF...

**Desktop/Smartphone**
 - OS: Win 10
 - Browser Firefox 65.0.1 and 65.0.2

**Additional context**
Also tested on clean Firefox installation in VM. Works properly on Edge, Chrome and Firefox for Android. Also the error doesn't appear in release 0.8.1, only in the demo or if you install the current master branch.

**Comment by kevinpapst** [comment]
The additional context is very important. Thanks for that info!
Found a solution on Stackoverflow (which is weird... maybe a firefox bug):
Please post this into your JS console:
`$.fn.modal.Constructor.prototype.enforceFocus = function (){};`
and let me know if it works after re-opneing the modal.

For me on MacOS with FF 65.0.1 it fixed the problem.

**Comment by nyquist2205** [comment]
Yes, the JS code fixed it for me too, on Win10 with FF65.0.1 and FF65.0.2.

It's interesting that this only appears in the development version of kimai and not in the release. But apart from that it indeed seems like a "inconvenience" of Firefox...

**Comment by kevinpapst** [comment]
Thats because the modal wasn't existing before. 
It seems to be a focus bug in firefox, which is caused by the bootstraps modal.
I have to check how that can be incorporated without breaking to much other functionality ... 2019 and we still have to "fix" browser bugs^^

**Comment by kevinpapst** [comment]
Reference for the fix:
https://stackoverflow.com/questions/21059598/implementing-jquery-datepicker-in-bootstrap-modal
https://stackoverflow.com/questions/22050641/month-select-in-datepicker-inside-a-bootstrap-modal-wont-work-in-firefox

**Comment by kevinpapst** [comment]
Any chance you could help testing the attached PR @nyquist2205 ?

**Comment by nyquist2205** [comment]
Sure, I'll try later. Hope I'll get this github-stuff done ;-)
