### ISSUE TITLE
Adding entry view / date picker translation

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#619]
Hi Kevin,

we are using Kimai 0.8.1 stable and in comparison to the demo the view of edit/adding a entry and the translation of date picker buttons are different.

At the demo the view of edit/adding a entry is in a lightbox and the date picker buttons are in german:
![bildschirmfoto 2019-03-06 um 08 40 56](https://user-images.githubusercontent.com/42935152/53867134-77bd2c80-3ff3-11e9-8749-ec84b053680e.png)

In our Kimai the view isn't in a lightbox and the buttons are not translated:
![bildschirmfoto 2019-03-06 um 08 41 23](https://user-images.githubusercontent.com/42935152/53867128-73910f00-3ff3-11e9-8e5c-8b148a964d3d.png)

**Comment by kevinpapst** [comment]
Yes, well noticed - thanks for your constant tests and feedback :-)
That is a new feature for 0.9.
Is there a question? Did you find a bug?

Btw: nice screenshots, which tool are you using?

**Comment by blochwitz** [comment]
Ah, okay. So the missing translation in the date picker box will solved in the next branch?

I make screenshots at the mac by using Alt+Shift+4 & Space...
