### ISSUE TITLE
Autofocus on first entry of forms

### ISSUE THREAD

**Issue by orzechow** [kevinpapst/kimai2#620]
**Is your feature request related to a problem? Please describe.**
When creating many projects / activities / ... it is cumbersome that it is necessary to click into the name field first (especially if you have created one entry before and the confirmation popup makes the name field slide up after some time).

**Describe the solution you'd like**
Simply autofocus the first entry item of all input forms (user, customer, project, activity, timesheet, ...).
This way one could enter many entries with keyboard only.

**Additional context**
Using Firefox 65.0.1 on an Ubuntu-based Linux system.

**Comment by kevinpapst** [comment]
Great idea! Its these small things that make life so much easier ;-)
PR #640 adds support for it.
