### ISSUE TITLE
Calendar: Return to last view after creating a new time entry

### ISSUE THREAD

**Issue by orzechow** [kevinpapst/kimai2#622]
**Is your feature request related to a problem? Please describe.**
When creating a new time entry in calendar view (I like the week view most to select start / end time), the page after submitting this entry is always the list view of "My Times".
This is cumbersome if I want to enter many entries via calendar view (I'd like to log my worktime at the end of a workday).

**Describe the solution you'd like**
Load the last view again, after submitting the entry.

**Describe alternatives you've considered**
Two alternatives
- Add a setting to choose the default "My Times" view.
- Open a modal dialog instead of full page form for the time entry, like it is done in the list view. This would probably allow to directly stay on the page.

**Additional context**
Using Firefox 65.0.1 on an Ubuntu-based Linux system.

**Comment by kevinpapst** [comment]
Calendar improvements merged to master, your feature request is solved by using modals.
