### ISSUE TITLE
„red lines“ in list view

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#625]
Hi Kevin,

in the list view my colleagues missing these red (dotted/strong) lines that exist in kimai1.

they told me that these lines (showing a gap > dotted or a overlap > strong) are helpful to identify entries which overlap.

![bildschirmfoto 2019-03-07 um 09 13 55](https://user-images.githubusercontent.com/42935152/53942150-5115f900-40ba-11e9-96b1-705e40c1946e.png)

![bildschirmfoto 2019-03-07 um 09 14 17](https://user-images.githubusercontent.com/42935152/53942156-53785300-40ba-11e9-8722-fce87938ea3d.png)

**Comment by nqb** [comment]
+1 for this feature. I hope we could have it back in 1.0.

On 0.9 version, you can easily create two tasks which overlap causing a wrong duration.

Example:
![Screenshot from 2019-06-28 17-27-46](https://user-images.githubusercontent.com/10830260/60353432-4c0ee980-99ca-11e9-9873-f8181c892f9f.png)

**Comment by nqb** [comment]
In my opinion, it would be nice if you can have a warning when you're creating a task which overlaps another one.

**Comment by kevinpapst** [comment]
It might be a wrong tracking, but this is not a "wrong duration".
A warning should be a new feature request. And I do accept a PR for both!
