### ISSUE TITLE
Restarting a entry- missing description

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#626]
Hi Kevin,

we use the restart function to create a new entry based on an existing entry but the new entry doesn't contain the description of the restarted entry.

Is this a bug or should it be a feature?

**Comment by kevinpapst** [comment]
That is on purpose. But sound like a valid use-case.
I am planning on changing the actions buttons on the tables to be a dropdown with dynamic options and this could be a new one.

**Comment by rarvin** [comment]
I could see that you have implemented the actions button on kimai that is deployed on the development demo server, when do you think this feature of copying the description filed would be implemented.

**Comment by kevinpapst** [comment]
Please test #782 and leave your feedback.
