### ISSUE TITLE
Allow edit Date From for saved time records

### ISSUE THREAD

**Issue by shurenok2** [kevinpapst/kimai2#627]
After a time record is created there is no possibility to change the value of "Date From" on "Edit record" form. There is no such field there although it is present on "Create" form.

![image](https://user-images.githubusercontent.com/16302703/53962516-509e5200-40fc-11e9-8c3f-6e815ec082de.png)

If a wrong date was specified for a time record, the only way to change it is to delete the time record and add a new one with the correct date i.e. re-enter all the rest of the time record fields (including descriptions which may be big enough)

**Comment by kevinpapst** [comment]
Will be fixed with #812
