### ISSUE TITLE
Customer public page

### ISSUE THREAD

**Issue by thenotec** [kevinpapst/kimai2#629]
I think it is a good feature to add a public link for customers, so these have the possibility to view the progress of works if the admin shares the link with these.

For security reason the link could be formatted with a random code.
Ex. https://domain.com/random_code/name_customer

The public page could have the navbar for filter the results.

I hope you can consider my request.
Carlo

**Comment by hmr-it-jr** [comment]
@thenotec same as #579 ?

**Comment by kevinpapst** [comment]
I like that idea much more than the customer login in #579 .

Can you share some more thoughts and ideas?
- which data should be presented? 
  - one link per customer and project? 
  - what about activities? 
  - should it be possible to exclude certain data that shouldn't be visible to the customer?
- how should the data be presented?
  - simple charts? 
  - budgets? 
  - detailed lists?
- configurable time-range?

I'd say:
- one project per link
- customer should be able to set a password in addition to the unique link for additional security
- option to set an expiration date for the link
- add a new layout without sidebar/navbar
- customizable title/logo for company branding
- do not show users that worked => show only summaries

**Comment by hmr-it-jr** [comment]
**Good:**
> option to set an expiration date for the link
> add a new layout without sidebar/navbar
> customizable title/logo for company branding

**Discussion needed:**
> do not show users that worked => show only summaries
- can you make that configurable? In Kimai 1 it was possible for the customer to see who was worked what. We add the issue/ticket number #xyz to our Kimai description. So if the customer has a question it's easier that he can contact directly the person. On the other side the customer can see who closed the ticket/issue. Anyway, a checkbox "show users" would be great.

> customer should be able to set a password in addition to the unique link for additional security
- keep in mind, that the user which creates the link should be able to set a password, too.

**Not Good:**
> one link per customer and project?
> one project per link

- Imho it's better to make one link per customer but with all projects. I'll give you a real live example wich might change your mind.

We develop a ERP system for a customer. As you might know a ERP system has a lot of components for different departments.

If we'd track the time only on one project "ERP" the customer would have a hard time to see how much time we've spend on what.

So we've splitted the big ERP-project in Sub-projects.
- ERP warehouse management
- ERP financial administration
- ERP marketing
- ERP controlling
- ERP quality assurance
- ERP legal department
- ERP shop floor
- ERP web shop module
- ERP research and development
- ERP ....

So if we send the customer now 10+ links that his financial administration can check which department caused which costs it's not very handy.

An other real live example:
- homepage development
- server administration
- user remote support
- user on-site service
- network maintenance
- miscellaneous

So you see if you have customers with more than 2 projects it's better to show all projects and just add filters for projects and activities like it was in Kimai 1.

**Comment by thenotec** [comment]
Hi Kevin,
I was thinking of something more simple.

What I thought is a public link for each project.
The public link shows the summary of the project activities to permit to guest to view the activities and their budget.

For example... see Invoice Plane demo at https://demo.invoiceplane.com/index.php/sessions/login
Under a Quote with status Send you can see a Guest URL.
Similar to this.
I think this function could be very useful.

**Comment by srdco** [comment]
LOVE the idea ...
What about a combo ... project per link (that way if different projects have different combos of clients, you don't have confidentiality issues -- like Clients A&B on Project 1, Clients B&C on Project 2, and only Client A on Project 3)
THEN ... what if you had a configurable link that you could tie different project links to?
That way, you could granularize / modularize the functionality -- just keep it simple and less 'config options' on project link,
but could create a 'User' Page that shows different projects

In addition to hmr-it-jr use scenario, we have a number of projects that mix clients. It would be VERY inconvenient for the clients to have to keep track of multiple 'project links'. We could always create a page on our site to keep track of them for them ... but that's outside of Kimai. It would be great if it could all be managed from inside Kimai.

Not sure how hard to implement a variation of this.

Thanks!

**Comment by dexterity42** [comment]
Hi all, is there an active development on this topic? Currently i'm using a very simple solution for my customers. I would like to provide a plugin which offers a simple version of what was discussed to share this with you, if there is no solution yet.

First version could consist of:
- Management page for "public projects"
- Simple timesheet view with month and year selection
- One link per project, including random code
- Password protection

Any other suggestions for a first version?

@kevinpapst I couldn't find anything about public pages in Kimai 2. The default layout can not be used (navbar and sidebar are not removable) and public routes need to be added to security.yaml, which cannot be provided by the plugin and therefore require manual adjustment steps. Do you have plans to provide public pages (layout and routes) for plugins?

**Comment by kevinpapst** [comment]
Hi @dexterity42 - that would be awesome, I'd love to see that (and I will support you in that regards as good as I can)!

Regarding the layout, please check if you could use this layout from the AdminLTE bundle:
https://adminlte.io/themes/AdminLTE/pages/layout/top-nav.html
There is nothing pre-made available in Kimai or the used theme bundle, but at least the styles should be included. 
We can add that either to Kimai or to [the theme bundle](https://github.com/kevinpapst/AdminLTEBundle) directly.

Regarding the route/security:
- You could use the `/auth` route which is public and we could argue that the security token is kind of a authentication anyway
- You could sent a PR here with a generic prefix, probably something like `/p/` (which would both match *p*ublic and *p*lugin) 

Additional feature wishes:
- Long term wish to keep in mind: option to switch between an project overview with budget vs used time/money (like the projects detail view)
- Option to hide rates (at least in the timesheet view)
- Option to hide/anonymize username (you know GSDPR...)

**Comment by dexterity42** [comment]
Thanks for your feedback and hints. I just released an alpha version of the plugin: https://github.com/dexterity42/SharedProjectTimesheetsBundle/releases/tag/v1.0.0-alpha
Note that this is a really simple solution and that i don't have that much free time to develop it.

Features of the view:
- Password protection
- Option to show/hide user
- Option to show/hide rate
- Support for multiple links per project

Some technical stuff:
- The plugin uses the `/auth` route for now. An additional route for plugins or public pages would be great, but is not needed for now.
- To speed up the plugin development i used the top-nav layout by simply copying it to the bundle.

I would appreciate your feedback.

**Comment by kevinpapst** [comment]
@dexterity42 Do you want to add the plugin to the website? Then more people will notice that it is available!

Read how: https://www.kimai.org/documentation/plugins.html#list-your-plugin-in-the-marketplace

**Comment by kevinpapst** [comment]
Closing, as the plugin by @dexterity42 is doing the job perfectly fine. 

Please go to https://github.com/dexterity42/SharedProjectTimesheetsBundle for further discussions
