### ISSUE TITLE
Installing kimai via Git-Remote-Repository

### ISSUE THREAD

**Issue by fatnmad** [kevinpapst/kimai2#632]
Hi, 
I use Kimai since the beginning of time and love it. It saved my ass sooo many times 
... but I am so excited to use the latest version as it looks incredibly awesome to use.

As my Webspace-Provider now lets me use the [Git Repositorys](https://www.plesk.com/extensions/git/) via Plesk, I tried to install kimai2, but failed.

_But_ as it seems, it doesn't work as easy as that: My screen is left blank when I head to kimai2/public/

System: Linux, PHP 7.3.2, MySQL

**Comment by kevinpapst** [comment]
I do not know what Plesk does. Did you follow the installation docs?

**Comment by fatnmad** [comment]
Plesk installs the kimai2-git and "installs" it to the server.

as a sidenote: I also used the "FTP installation"-Guide without success

**Comment by kevinpapst** [comment]
Plesk will very likely "only" clone the git repository. But It does not execute the installation steps.

> Did you follow the installation docs?

**Comment by fatnmad** [comment]
> Did you follow the installation docs?

You mean the Installation-Docs for FTP installation? Yes. 
Still blank page :/

**Comment by kevinpapst** [comment]
You said you installed it via Plesk & Git.
If you want my free help, you should start posting clear information: help without logs and understandable step-by-step instruction what you did is impossible.

**Comment by fatnmad** [comment]
I am sorry, but your answer confused me... 

My first try was: using the git extension which clones kimai2 onto my webspace and that's it.
So my second step was: Using XAMPP and composer to locally install kimai2 (as in the installation doc for kimai).
Afterwards I re-uploaded all files and tried to log in / register through kimai2/public/ - but there is nothing happening. And there is also no log-file created or any message.

I am sorry, but that's all I have... Hope it's enough for your free help ;)

**Comment by kevinpapst** [comment]
No server logs? No PHP logs? Nothing in var/logs/prod.log?
Did Kimai work locally?

**Comment by kevinpapst** [comment]
Did you read the sentence?
> Kimai needs its own sub-domain or you need to recompile the frontend assets for usage in a sub-directory

**Comment by fatnmad** [comment]
No server logs?
> it's a shared webhosting ...
No PHP logs?
> it's a shared webhosting ...
Nothing in var/logs/prod.log?
> no.
Did Kimai work locally?
> no.

**Comment by fatnmad** [comment]
> No server logs?
it's a shared webhosting ... (
>No PHP logs?
it's a shared webhosting ...
>Nothing in var/logs/prod.log?
no.
> Did Kimai work locally?
no.

> Did you read the sentence?
> > Kimai needs its own sub-domain or you need to recompile the frontend assets for usage in a sub-directory
Even if this is a rhethorical question: I guess not. (But how to have a subdomain on a local machine? ^^)

I am sorry to bother you at all. Maybe I'll just wait until a webinstaller is avaible...

**Comment by kevinpapst** [comment]
I haven't had a shared webhosting since 10 years, but even back then you had access to your logs...

If you try the FTP installation, you have to make sure that Kimai works locally before uploading.

**Comment by fatnmad** [comment]
I re-did everything from the Installation Docs (FTP Installation) and saved every bit of log I can offer you.
I installed on xampp, re-uploaded it and tried to enter the /public/ (on a sub-domain).
still a blank page: [See](http://kimai.spurgo.de/public/)

composer:
`# xampp install log
composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 119 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.3.0): Loading from cache
  - Installing symfony/flex (v1.1.8): Loading from cache
  - Installing beberlei/doctrineextensions (v1.2.0): Loading from cache
  - Installing symfony/routing (v4.1.11): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing symfony/http-foundation (v4.1.11): Loading from cache
  - Installing symfony/event-dispatcher (v4.1.11): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.1.11): Loading from cache
  - Installing symfony/http-kernel (v4.1.11): Loading from cache
  - Installing symfony/finder (v4.1.11): Loading from cache
  - Installing symfony/filesystem (v4.1.11): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.1.11): Loading from cache
  - Installing symfony/config (v4.1.11): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.1.11): Loading from cache
  - Installing symfony/framework-bundle (v4.1.11): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/persistence (v1.1.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing doctrine/common (v2.10.0): Loading from cache
  - Installing symfony/doctrine-bridge (v4.1.11): Loading from cache
  - Installing symfony/console (v4.1.11): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.5): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing doctrine/doctrine-bundle (1.10.2): Loading from cache
  - Installing dama/doctrine-test-bundle (v5.0.2): Loading from cache
  - Installing doctrine/data-fixtures (v1.3.1): Loading from cache
  - Installing doctrine/doctrine-fixtures-bundle (3.1.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing symfony/stopwatch (v4.1.11): Loading from cache
  - Installing zendframework/zend-eventmanager (3.2.1): Loading from cache
  - Installing zendframework/zend-code (3.3.1): Loading from cache
  - Installing ocramius/proxy-manager (2.1.1): Loading from cache
  - Installing doctrine/migrations (v2.0.0): Loading from cache
  - Installing egulias/email-validator (2.1.7): Loading from cache
  - Installing erusev/parsedown (1.7.1): Loading from cache
  - Installing willdurand/negotiation (v2.3.1): Loading from cache
  - Installing willdurand/jsonp-callback-validator (v1.1.0): Loading from cache
  - Installing symfony/templating (v4.1.11): Loading from cache
  - Installing symfony/inflector (v4.1.11): Loading from cache
  - Installing symfony/property-access (v4.1.11): Loading from cache
  - Installing symfony/security (v4.1.11): Loading from cache
  - Installing friendsofsymfony/rest-bundle (2.5.0): Loading from cache
  - Installing twig/twig (v2.6.2): Loading from cache
  - Installing symfony/translation (v4.1.11): Loading from cache
  - Installing symfony/validator (v4.1.11): Loading from cache
  - Installing symfony/twig-bridge (v4.1.11): Loading from cache
  - Installing symfony/twig-bundle (v4.1.11): Loading from cache
  - Installing symfony/security-bundle (v4.1.11): Loading from cache
  - Installing symfony/options-resolver (v4.1.11): Loading from cache
  - Installing symfony/intl (v4.1.11): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.10.0): Loading from cache
  - Installing symfony/form (v4.1.11): Loading from cache
  - Installing paragonie/random_compat (v2.0.18): Loading from cache
  - Installing friendsofsymfony/user-bundle (v2.1.2): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing jms/metadata (1.7.0): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Loading from cache
  - Installing jms/parser-lib (1.0.0): Loading from cache
  - Installing phpcollection/phpcollection (0.5.0): Loading from cache
  - Installing jms/serializer (1.13.0): Loading from cache
  - Installing jms/serializer-bundle (2.4.3): Loading from cache
  - Installing kevinpapst/adminlte-bundle (2.2): Loading from cache
  - Installing setasign/fpdi (1.6.2): Loading from cache
  - Installing myclabs/deep-copy (1.8.1): Loading from cache
  - Installing mpdf/mpdf (v7.1.9): Loading from cache
  - Installing zircote/swagger-php (2.0.13): Loading from cache
  - Installing symfony/property-info (v4.1.11): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing exsyst/swagger (v0.4.1): Loading from cache
  - Installing nelmio/api-doc-bundle (v3.3.1): Loading from cache
  - Installing pclzip/pclzip (2.8.2): Loading from cache
  - Installing markbaker/matrix (1.1.4): Loading from cache
  - Installing markbaker/complex (1.4.7): Loading from cache
  - Installing phpoffice/phpspreadsheet (1.6.0): Loading from cache
  - Installing zendframework/zend-escaper (2.6.0): Loading from cache
  - Installing phpoffice/common (0.2.9): Loading from cache
  - Installing phpoffice/phpword (0.15.0): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.2.4): Loading from cache
  - Installing symfony/asset (v4.1.11): Loading from cache
  - Installing symfony/polyfill-php72 (v1.10.0): Loading from cache
  - Installing symfony/var-dumper (v4.1.11): Loading from cache
  - Installing symfony/web-profiler-bundle (v4.1.11): Loading from cache
  - Installing symfony/profiler-pack (v1.0.4): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing symfony/monolog-bridge (v4.1.11): Loading from cache
  - Installing symfony/monolog-bundle (v3.3.1): Loading from cache
  - Installing symfony/debug-bundle (v4.1.11): Loading from cache
  - Installing symfony/yaml (v4.1.11): Loading from cache
  - Installing easycorp/easy-log-handler (v1.0.7): Loading from cache
  - Installing symfony/debug-pack (v1.0.7): Loading from cache
  - Installing symfony/dotenv (v4.1.11): Loading from cache
  - Installing symfony/expression-language (v4.1.11): Loading from cache
  - Installing nikic/php-parser (v4.2.0): Loading from cache
  - Installing symfony/maker-bundle (v1.11.3): Loading from cache
  - Installing doctrine/orm (v2.6.3): Loading from cache
  - Installing doctrine/doctrine-migrations-bundle (v2.0.0): Loading from cache
  - Installing symfony/orm-pack (v1.0.6): Loading from cache
  - Installing symfony/serializer (v4.1.11): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.1.3): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.2.5): Loading from cache
  - Installing symfony/process (v4.1.11): Loading from cache
  - Installing symfony/web-server-bundle (v4.1.11): Loading from cache
  - Installing twig/extensions (v1.5.4): Loading from cache
  - Installing pagerfanta/pagerfanta (v2.0.1): Loading from cache
  - Installing white-october/pagerfanta-bundle (v1.2.3): Loading from cache
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [OK]
Executing script assets:install [OK]


E:\Temp\xampp\htdocs\kimai2>php bin/console doctrine:schema:create

 !
 ! [CAUTION] This operation should not be executed in a production environment!
 !

 Creating database schema...


 [OK] Database schema created successfully!



E:\Temp\xampp\htdocs\kimai2>bin/console doctrine:migrations:version --add --all
Der Befehl "bin" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

E:\Temp\xampp\htdocs\kimai2>php bin/console doctrine:migrations:version --add --all
WARNING! You are about to add, delete or synchronize migration versions from the version table that could result in data lost. Are you sure you wish to continue? (y/n)y
20180701120000 added to the version table.
20180715160326 added to the version table.
20180730044139 added to the version table.
20180805183527 added to the version table.
20180903202256 added to the version table.
20180905190737 added to the version table.
20180924111853 added to the version table.
20181031220003 added to the version table.
20190124004014 added to the version table.
20190201150324 added to the version table.
20190219200020 added to the version table.

E:\Temp\xampp\htdocs\kimai2>bin/console kimai:create-user username admin@example.com ROLE_SUPER_ADMIN
Der Befehl "bin" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

E:\Temp\xampp\htdocs\kimai2>php bin/console kimai:create-user username admin@example.com ROLE_SUPER_ADMIN
Please enter the password:


 [OK] Success! Created user: username
`

and here's the var/prod.log:

`[2019-03-11 07:24:07] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "EventManager" from namespace "Doctrine\Common". Did you forget a "use" statement for "Zend\EventManager\EventManager"?" at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php line 23 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"EventManager\" from namespace \"Doctrine\\Common\".\nDid you forget a \"use\" statement for \"Zend\\EventManager\\EventManager\"? at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:23)"} []
[2019-03-11 07:24:07] php.WARNING: Warning: include_once(/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\twig-bundle\Controller\ExceptionController.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): Warning: include_once(/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\\vendor\\symfony\\twig-bundle\\Controller\\ExceptionController.php): failed to open stream: No such file or directory at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/var/cache/prod/ContainerAYMBEQl/getTwig_Controller_ExceptionService.php:9)"} []
[2019-03-11 07:24:07] php.WARNING: Warning: include_once(): Failed opening '/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\twig-bundle\Controller\ExceptionController.php' for inclusion (include_path='.:/opt/plesk/php/7.3/share/pear') {"exception":"[object] (ErrorException(code: 0): Warning: include_once(): Failed opening '/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\\vendor\\symfony\\twig-bundle\\Controller\\ExceptionController.php' for inclusion (include_path='.:/opt/plesk/php/7.3/share/pear') at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/var/cache/prod/ContainerAYMBEQl/getTwig_Controller_ExceptionService.php:9)"} []
[2019-03-11 07:24:07] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Loader: The "/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\framework-bundle/Resources/views" directory does not exist ("/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\framework-bundle/Resources/views"). at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/vendor/twig/twig/lib/Twig/Loader/Filesystem.php line 101) {"exception":"[object] (Twig_Error_Loader(code: 0): The \"/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\\vendor\\symfony\\framework-bundle/Resources/views\" directory does not exist (\"/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\\vendor\\symfony\\framework-bundle/Resources/views\"). at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101)"} []
[2019-03-11 07:24:07] php.CRITICAL: Uncaught Exception: The "/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\framework-bundle/Resources/views" directory does not exist ("/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\framework-bundle/Resources/views"). {"exception":"[object] (Twig_Error_Loader(code: 0): The \"/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\\vendor\\symfony\\framework-bundle/Resources/views\" directory does not exist (\"/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\\vendor\\symfony\\framework-bundle/Resources/views\"). at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101, Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"EventManager\" from namespace \"Doctrine\\Common\".\nDid you forget a \"use\" statement for \"Zend\\EventManager\\EventManager\"? at /var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:23)"} []`

**Comment by kevinpapst** [comment]
The last one is a bit too much ;-) but thats something we can start working with.

But I guess I have have bad news: it seems a if the autoloader from windows is not working on linux, see how the backslash and slash changes in the middle of the directory:
`/var/www/vhosts/web43.c18.webspace-verkauf.de/kimai.spurgo.de\vendor\symfony\framework-bundle/Resources/views`
Can you please check the files in vendor/composer/autoload_* ? 
For me it looks like this (autoload_classmap.php):
```
return array(
    'Collator' => $vendorDir . '/symfony/intl/Resources/stubs/Collator.php',
    'FPDF_TPL' => $vendorDir . '/setasign/fpdi/fpdf_tpl.php',
    'FPDI' => $vendorDir . '/setasign/fpdi/fpdi.php',
    'FilterASCII85' => $vendorDir . '/setasign/fpdi/filters/FilterASCII85.php',
    'FilterASCIIHexDecode' => $vendorDir . '/setasign/fpdi/filters/FilterASCIIHexDecode.php',
    'FilterLZW' => $vendorDir . '/setasign/fpdi/filters/FilterLZW.php',
    'IntlDateFormatter' => $vendorDir . '/symfony/intl/Resources/stubs/IntlDateFormatter.php',
    'Locale' => $vendorDir . '/symfony/intl/Resources/stubs/Locale.php',
    'NumberFormatter' => $vendorDir . '/symfony/intl/Resources/stubs/NumberFormatter.php',
```
while I expect that you see something like:
```
    'Collator' => $vendorDir . '\\symfony\\intl\\Resources\\stubs\\Collator.php',
```

Seems Windows is still not compatible with Linux in 2019. 
Use a Virtualbox/Vagrant/Homestead to perform the composer install (btw. the docu says `composer install --no-dev --optimize-autoloader`).
You could also try to replace the slash types. 

I will update the documentation

**Comment by hmr-it-jr** [comment]
@fatnmad I use Kimai 2 with Plesk Onyx and git installer on shared hosting too. Which hoster are you using? Maybe my picture in #469 helps you?

**Comment by fatnmad** [comment]
@kevinpapst 
ty

But my autoload_classmap.php looks same like yours (correct Backslash):

```
// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Collator' => $vendorDir . '/symfony/intl/Resources/stubs/Collator.php',
    'FPDF_TPL' => $vendorDir . '/setasign/fpdi/fpdf_tpl.php',
    'FPDI' => $vendorDir . '/setasign/fpdi/fpdi.php',
    'FilterASCII85' => $vendorDir . '/setasign/fpdi/filters/FilterASCII85.php',
    'FilterASCIIHexDecode' => $vendorDir . '/setasign/fpdi/filters/FilterASCIIHexDecode.php',
    'FilterLZW' => $vendorDir . '/setasign/fpdi/filters/FilterLZW.php',
    'IntlDateFormatter' => $vendorDir . '/symfony/intl/Resources/stubs/IntlDateFormatter.php',
    'Locale' => $vendorDir . '/symfony/intl/Resources/stubs/Locale.php',
    'NumberFormatter' => $vendorDir . '/symfony/intl/Resources/stubs/NumberFormatter.php',
    'PclZip' => $vendorDir . '/pclzip/pclzip/pclzip.lib.php',
    'SqlFormatter' => $vendorDir . '/jdorn/sql-formatter/lib/SqlFormatter.php',
    'fpdi_pdf_parser' => $vendorDir . '/setasign/fpdi/fpdi_pdf_parser.php',
    'pdf_context' => $vendorDir . '/setasign/fpdi/pdf_context.php',
);
```

Afterwards I manually searched all files in kimai2 for the wrong backslash with notepad++ (esp. "\vendor\") and found __2542__ hits in __560__ files...
Strange thing is: They're all in /var/cache/prod/ContainerAYMBEQL/ and in the form you mentioned:

```
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\src\\Form\\Type\\DateRangeType.php';
´´´


@hmr-it-jr  I saw your image, but my provider didn't allow me to change any values for PHP :/
but my openbasedir is:

```
open_basedir  {WEBSPACEROOT}{/}{:}{TMP}{/}
´´´

**Comment by kevinpapst** [comment]
Please try to delete all files in var/cache/*

**Comment by fatnmad** [comment]
so... I once again tried to redo the FTP-Installation, replacing all \\ to // and re-uploading it to the server. And afterwards deleting contents in /var/cache/

at least, it looks like this:
![kimai](https://user-images.githubusercontent.com/48413888/54124835-b98b1000-4403-11e9-8504-5a9ac23382f6.jpg)

Doesn't look quite right and it doesn't function (I end up at __Error 501__ )

**Comment by kevinpapst** [comment]
Point your Document root to /public/. public is not allowed within the URL.

**Comment by kevinpapst** [comment]
I linked the documentation about assets already above.
But maybe I found a fix for that problem, which was existing since a while now.
You could try the changes from this PR: #636

**Comment by kevinpapst** [comment]
Fixed in master, you can try the latest version - should fix your issues with missing styles

**Comment by kevinpapst** [comment]
No feedback, URL is not reachable => closing

**Comment by fatnmad** [comment]
nothing worked...
still waiting for webinstaller.

**Comment by kevinpapst** [comment]
Please see this issue #642 which adds a FTP package. 
There is a package for the upcoming version 0.9 linked which can be used for FTP installation.
