### ISSUE TITLE
Filter sleeping projects

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#644]
Dear Kevin and co

I've met Kimai2 only yesterday. It seems like the tool that does just that what our team is looking for. So I'm very exited. I explored the demo and that felt great. I did mis one little thingy, though, that would keep us more in control of our active projects: finding sleeping projects. If this possibility already exists, I apologize in advance. I was not able to find it in the demo.

In the "Administration" tab under "Projects" it would be nice to be able to filter on "inactive since" using a calendar (or several options like "3 or more months"; "6 or more months"; 1 or more year"). I drew a paint preview that should make clear what I'm trying to say (attached).

I explain myself. Currently, we can mark projects that are closed as "not visible", so it doesn't regard these projects. Instead, the requested filter option would make it possible to easily find those projects that are not closed (marked visible) but on which we've lost track, being occupied by other, more urgent projects. If we could filter out those projects whose most recent time tracking record dates XX months or years back, we can easily evaluate if and what still has to be performed in those projects or if they are ready to be closed (marked invisible). Do you think it would be a hard nut to crack to insert this filter option, whether or not in the form of a plug-in?

If this suggestion does not seem like an improvement to you, it would in no way temper my enthusiasm about this great project of yours.

Thanks in advance to consider my request.

Willem

![Filter sleeping projects request](https://user-images.githubusercontent.com/48569441/54392064-edd22b00-46a6-11e9-8d0e-2ad7930ea426.jpg)

**Comment by kevinpapst** [comment]
Hi Willem, thanks for the feature request.
From my perspective that's something which fits better into a reporting extension and not in the normal toolbar filter.
But lets see if more users vote for the feature.

**Comment by 1willem** [comment]
Hi Kevin, many thanks for your fast response. The Kiss principle in mind, I fully understand your point of view to keep this feature out of the Kimai core. For interested users to be able to add this feature by means of a plug-in, sounds great to me. I'm looking forward to other users response on my request.

**Comment by buzter** [comment]
Both - the suggested filter option by 1willem and the suggested solution by Kevin - sound very interesting to me.

**Comment by kevinpapst** [comment]
Finally a report was added to filter "inactive projects". Available in master, will be released with 1.15

**Comment by 1willem** [comment]
That is great news, Kevin! Looking forward to it.

Keep it up!

Willem

Op zo 16 mei 2021 om 20:20 schreef Kevin Papst ***@***.***>:
