### ISSUE TITLE
API is not able to handle CORS

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#646]
**Describe the bug**
When calling the API from a different url, the CORS preflight fails.

**To Reproduce**
1. create simple get request in js on a domain to the api
2. set-up everything correct
3. watch it fail with error

`
{
    "code": 405,
    "message": "Method Not Allowed"
}
`

**Additional context**
 - CORS is necessary to work if you want that the API is callable from other frontends on different urls. It's a security mechanism. CORS always does a pre-flight with OPTIONS.
 - More info: https://stackoverflow.com/questions/29954037/why-is-an-options-request-sent-and-can-i-disable-it#answers-header

If you have any questions or details let me know it.

As soon as this is fixed I'll contine with developing for #198

**Comment by kevinpapst** [comment]
Can you try to install `composer require nelmio/cors-bundle` and see if that fixes the problem.
It maybe needs configuration: https://codereviewvideos.com/course/beginners-guide-back-end-json-api-front-end-2018/video/symfony-4-cors-json-api

**Comment by hmr-it-jr** [comment]
@kevinpapst I've tried it but didn't succeed.

What I did:

- composer require nelmio/cors-bundle
- setting allow_origin config/packages/nelmio_cors.yaml to ['*']

It didn't work so I've tried this:
- ['%env(CORS_ALLOW_ORIGIN)%']

and in .env setting
- CORS_ALLOW_ORIGIN=^http?://.*?$

I cleared cache, etc. too.

**Comment by hmr-it-jr** [comment]
@kevinpapst can you help me out here?

**Comment by kevinpapst** [comment]
Sure, when I have the time. Is it urgent?

**Comment by hmr-it-jr** [comment]
I don't know how much it is to fix it. But I have time this weekend to work on the app so if you could fix it this weekend it would be nice :-)

**Comment by kevinpapst** [comment]
I created a demo page to test some simple API calls, it can be copy & pasted from:
https://www.kimai.org/documentation/rest-api.html

And I added the PR #655 to fix the CORS problem

**Comment by hmr-it-jr** [comment]
@kevinpapst do you even sleep?

I've tested it and now it works like a charm 👍

**Comment by kevinpapst** [comment]
Hahaha, well from time to time I have to.

**Comment by hmr-it-jr** [comment]
Hm, I've tested the GET request and it worked fine, so I assumed POST will work as well, but it doesn't.

Have you tested the POST request?
![grafik](https://user-images.githubusercontent.com/36242595/54876776-c94c2080-4e15-11e9-99dd-1f89fe971ebf.png)

------------

And I think there is some other error/bug:
Taken from /api/doc
![grafik](https://user-images.githubusercontent.com/36242595/54876745-2e534680-4e15-11e9-99f3-72110227fb9b.png)

If you try to send this with this time format it won't work:
![grafik](https://user-images.githubusercontent.com/36242595/54876756-5d69b800-4e15-11e9-9b05-548174d5cd89.png)
If you look at "begin" with the YYYY-mm-dd H:i:s format it's accepted by the api.

When I send both dates in the correct format the api returns this:
![grafik](https://user-images.githubusercontent.com/36242595/54876764-8f7b1a00-4e15-11e9-8012-f845079e9187.png)

Is this correct? I think it makes more sense to work with the same date format everywhere.

**Comment by kevinpapst** [comment]
No, I haven't tested POST.
Try to add 'Content-Type' to the allowed headers here: https://github.com/kevinpapst/kimai2/blob/master/config/packages/nelmio_cors.yaml#L23
Regarding the date formats, yes that needs to be adressed.
But I donÄt have time today, sorry.
Can you open a new issue, so it won't be lost?!

**Comment by hmr-it-jr** [comment]
Thanks, it works now with this line:
`
allow_headers: ['X-AUTH-USER', 'X-AUTH-TOKEN', 'Content-Type']
`

--------

> Can you open a new issue, so it won't be lost?!

yes, will do

**Comment by hmr-it-jr** [comment]
> 
> 
> Thanks, it works now with this line:
> `allow_headers: ['X-AUTH-USER', 'X-AUTH-TOKEN', 'Content-Type']`


This doesn't need to be implemented. I've removed the Content-Type-Header when posting something to the api.

**Comment by hmr-it-jr** [comment]
I've set my defaults.headers.post["Content-Type"] = "application/json";

It's necessary so 'Content-Type' in allow_headers is necessary, too.

**Comment by kevinpapst** [comment]
Gracias! As I didn't use these bundles before its a game of try-and-error until it works out properly.
I wonder if the demo script (from the documentation) still works with this change...

**Comment by hmr-it-jr** [comment]
I've tested it right now just to be sure - and it works.
It's because with a GET request the api tells the requester "you get json from me". When doing a POST request the requester hast to tell the api "here I send you json". The server is allowed to send every header to the client - however CORS prevents that the client can send any header to the server. If the headers don't match it doesn't work.

So since there are only get requests in the api.html this change is not affecting it.

**Comment by kevinpapst** [comment]
I would have waited until someone complains^^ but this is even better.
Awesome, thanks for testing and the details.
