### ISSUE TITLE
Error export PDF

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#648]
**Describe the bug**
Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it again.

**To Reproduce**
Log in to Demo with Susan_Super (or any other)
Go to 'Export'
Click on 'PDF' in the lower right corner.

**Expected behavior**
Export the data in PDF.

Screenshots
![image](https://user-images.githubusercontent.com/48569441/54816176-e658e600-4c93-11e9-8e47-c85f6d8c4780.png)
![image](https://user-images.githubusercontent.com/48569441/54816210-ff619700-4c93-11e9-8120-1a17725d559b.png)

**Device**
Desktop
Windows 7 Professional
Chrome version 72.0.3626.121 (Officiële build) (64-bits)

**Comment by kevinpapst** [comment]
Thanks for the report! 
The cache directory was not set, so it was using the servers global temp directory. 
Fixed in the attached PR #650
