### ISSUE TITLE
Export - Mark all as cleared button doesn't update

### ISSUE THREAD

**Issue by nyquist2205** [kevinpapst/kimai2#649]
**Describe the bug**
If you mark multiple entries as "cleared" (or "open") with the button in the upper right of the export view and then edit the filters to view another set of entries, the button does not update.
If e.g. you filter all entries of one customer last month, mark them all as "cleared" and then change the filters to this month (with all entries "open"), the button still has a "Mark as open" functionality.

**To Reproduce**
1. Go to kimai-demo
2. In export view set filters to e.g. one month and one customer
3. use "set all cleared" button
4. Change filters (e.g. to another month, containing open entries)
5. Now, if you want to "clear" them all, you have to press the button twice: First time it "opens" them all, second time it clears them.

**Additional context**
Maybe it's not really a bug, but more kind of unwanted behaviour (to me). Even if you change the filters from "only open" to "only cleared", the button still has a "clear" function.

I think it would be nice to check if the majority of the entries is open or cleared and set the button to the other function, every time the filter changes.
Alternatives would be: Two buttons (one for clear, one for open) or one button with "toggle" functionality

**Comment by kevinpapst** [comment]
Maybe I have to make it two buttons, as I fiddled already a lot with that button. Actually spending wy too much time on it ;-) And this is the best solution I could come up with...

**Comment by nyquist2205** [comment]
Yes, I think two buttons is fine.
It's worth the time, i really like and use the function :-)

**Comment by kevinpapst** [comment]
@nyquist2205 could you have a look at #1046 - I was thinking of removing the button completely.
Pleas give it a try and see if it satisfies your use-cases.

**Comment by nyquist2205** [comment]
Tried it on the demo and yes, it satifies my use cases.

But like that we're loosing the functionality to "open" a batch of entries with one click. Not sure if this is really needed, but a solution would be two buttons ("Mark as Opened" and "Mark as cleared") next to the "Preview" button. Of course in addition to the new checkbox, which by the way is great to export and mark with one click ;-)

**Comment by kevinpapst** [comment]
Yeah, I wonder if this functionality is needed at all (with that new functionality in place).
But as there is no "batch update" module yet I will keep it for now.

**Comment by kevinpapst** [comment]
Oh and thanks for your feedback!
