### ISSUE TITLE
Datepicker "From" not working

### ISSUE THREAD

**Issue by nyquist2205** [kevinpapst/kimai2#651]
**Describe the bug**
If you edit an entry (or create one), the datepicker for "From" doesn't show up. For "To" it works correctly - if you click into the field, the datepicker shows up.

**To Reproduce**
1. Go to kimai-demo
2. Edit entry
3. Try to change "From" date or time

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - OS: Win10
 - Browser: Tried in Firefox, Chrome and Edge

**Comment by kevinpapst** [comment]
Damned. Tried to fix a Firefox issue and created 3 others...
Thanks for the report!
