### ISSUE TITLE
Inter-month entries don't get exported in single month

### ISSUE THREAD

**Issue by nyquist2205** [kevinpapst/kimai2#652]
**Describe the bug**
Entries that start in one month and end in another (e.g. 28.2. until 1.3.) don't get exported if you export the first month **or** the second month. Only if you export first **and** second month.
In the example if you export february, it doesn't show up (I would expect it here!) and it also doesn't show up in march (wouldn't expect it here). Only if you export at least 28.2. - 1.3., it shows up.

**To Reproduce**
1. Go to kimai-demo
2. Create entry from 28.2. until 1.3. (time doesn't matter) or use existing one
3. In export view set filter to "this month"
4. See that entry doesn't show up (also in exported file)

**Additional context**
Filtering in "My Times" view works correctly, so it seems to be an issue with filtering only in "Export" view. Same behaviour in my kimai 0.8.1 installation.

**Comment by kevinpapst** [comment]
fixed in master, thanks for the report!
