### ISSUE TITLE
PHP Fatal error:  Allowed memory size ....exhausted

### ISSUE THREAD

**Issue by emabot80** [kevinpapst/kimai2#659]
Hi Kevin,

in the meantime best congratulations for Kimai project.
I've installed it on a Centos 7 OS.
The PHP version is 7.3.

When I bind ,through the browser, http://kimai.loc/index.php
I receive an HTTP error 500 and the following errors about memory.

[Mon Mar 25 15:55:30.771266 2019] [php7:error] [pid 25632] [client 192.168.117.1:1513] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 36864 bytes) in /var/www/kimai2/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Mon Mar 25 15:55:30.771947 2019] [php7:error] [pid 25632] [client 192.168.117.1:1513] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/www/kimai2/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1​

I tried to modify the memory limit in php.ini but the error persist.

Could you suggest me how to fix this issue?

Thanks in advance

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/installation.html

> Make sure the file permissions are correct:
```
chown -R :www-data .
chmod -R g+rw var/
```
Your webserver/PHP needs write permissions for var/

The logger tries to write a log, fails and that error should be logged as well => thats a recursive problem until the "memory explodes".

**Comment by emabot80** [comment]
HI Kevin,

thanks for reply.
I've used apache group instead of www-data.
Is this can be a problem?
I applied on /var the instructions described in installation guide.

**Comment by kevinpapst** [comment]
I don't know your server and every distribution is different. 
If you need apache instead of www-data and that fixes the problem, perfect!

**Comment by emabot80** [comment]
Solved, the problem was on SELinux security policy.

Thanks

**Comment by kevinpapst** [comment]
Could you share it for the next person who has the same problem?

**Comment by emabot80** [comment]
I've modified the file /etc/selinux/config.
In detail I've changed SELINUX=enforcing to SELINUX= disabled.
Then reboot the server and the appliance works!

**Comment by kevinpapst** [comment]
Thanks for sharing! 
Thats weird and probably not the best solution, but I am not that familiar with CentOS and don't know how to do it better.
