### ISSUE TITLE
Show on the title if there is an active recording

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#660]
**Is your feature request related to a problem? Please describe.**
In kimai1 on the titlebar of the website the current counter was visible. I want a similar feature, so if there are a lot of tabs open I can see if I started the timer or not.

**Describe the solution you'd like**
In kimai1 a user could have only 1 active record, so it was straightforward which counter to show. In kimai 2 I recommend a static sign instead: the [play button emoji ](https://emojipedia.org/black-right-pointing-triangle/)looks cool in the titlebar: ▶ 
![image](https://user-images.githubusercontent.com/1271737/54993322-d60d7780-4fc1-11e9-8c53-a9e907109495.png)
This should only appear if at least one recording is active, and disappear if no active.

**Describe alternatives you've considered**
I think showing a counter would be harder to implement, and personally I didn't like it, I just liked that it's visible that the recording is going. There would be a problem if there are multiple recordings active, which one to show?
Changing the favicon to an other color would an other option, I don't know if it's possible. But I like the emoji better.

**Comment by hmr-it-jr** [comment]
possible duplication of #420

**Comment by kevinpapst** [comment]
Please have a look at PR #660 and let me know what you think
