### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by emabot80** [kevinpapst/kimai2#662]
Hi All,

when I login with my Super Admin Account I don't see any admin panel to config user,projects and activities.

![Cattura](https://user-images.githubusercontent.com/42611712/55069377-2d741c00-5084-11e9-8a57-86290043bd2a.JPG)

How Can I config and administrate? only via local.yaml file?

Thanks everyone

Ema

**Comment by kevinpapst** [comment]
You are definitely not using an super admin account or you have an invalid cache due to your problems with selinux. 
Try to delete all in var/cache => `rm -rf var/cache/*`

**Comment by emabot80** [comment]
As shown I suppose I'm Super Admin

![image](https://user-images.githubusercontent.com/42611712/55072055-6adba800-508a-11e9-8169-d0c64da073e5.png)

I've deleted the cache, restarted the web service but nothing improve on visualize Admin functions

**Comment by kevinpapst** [comment]
No, you are not. You entered ROLE_SUPER_ADMIN as your email address.
I double checked and the validation is only partially triggered from the command-line, thats why you have an invalid email address.

For creation:
Use: `bin/console kimai:create-user ema ema@example.com ROLE_SUPER_ADMIN` as stated in the documentation:  https://www.kimai.org/documentation/installation.html#recommended-setup

And for the immediate fix:
`bin/console fos:user:promote ema ROLE_SUPER_ADMIN`

You might have to te-login afterwards to reload the roles.

**Comment by emabot80** [comment]
Thank you very much.
I fix the issue.
