### ISSUE TITLE
Activities Drop Down Menu Empty

### ISSUE THREAD

**Issue by emabot80** [kevinpapst/kimai2#664]
Hello All,

I've populated all the sections (Users,Customers,Projects and Activities).
Next I'd like to create timesheets under Administration/Timesheets section.
I click on + button.
I fill all the fields requested, except the Activity one, that's empty on drop down menu.
Is it possible to correct in such way or is a bug?

![image](https://user-images.githubusercontent.com/42611712/55140981-a08b9a00-5139-11e9-8fe9-fbe54a00969f.png)

thanks very much

Ema

**Comment by kevinpapst** [comment]
If it happens in the demo site, then it is a bug.
If it happens only in your environment, its something else.
Check your browser console if there is a failing network request after changing the project.
Are there relevant logs in var/log/ ?

**Comment by emabot80** [comment]
Hi,
on downright side you can find the console browser message when I perform:
1)Click on Administration/Timesheets
2)+ button
3)set date
4)set customer
5)set project
6) try to set activity but I view empty drop down window and nothing on console is tracked.,

![image](https://user-images.githubusercontent.com/42611712/55164620-41934880-516c-11e9-96de-4c8f9de8b09a.png)


192.168.117.1 - - [28/Mar/2019:15:18:25 +0100] "GET /en/team/timesheet/ HTTP/1.1" 200 18181 "http://kimai2.loc/en/team/timesheet/create" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
192.168.117.1 - - [28/Mar/2019:15:18:26 +0100] "GET /build/apple-touch-icon.png HTTP/1.1" 404 3756 "http://kimai2.loc/en/team/timesheet/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
192.168.117.1 - - [28/Mar/2019:15:18:27 +0100] "GET /en/team/timesheet/create HTTP/1.1" 200 19530 "http://kimai2.loc/en/team/timesheet/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
192.168.117.1 - - [28/Mar/2019:15:18:28 +0100] "GET /build/apple-touch-icon.png HTTP/1.1" 404 3756 "http://kimai2.loc/en/team/timesheet/create" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
192.168.117.1 - - [28/Mar/2019:15:18:34 +0100] "GET /api/projects?customer=7&orderBy=name&visible=1 HTTP/1.1" 500 46 "http://kimai2.loc/en/team/timesheet/create" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
192.168.117.1 - - [28/Mar/2019:15:18:36 +0100] "GET /api/activities?project=1&orderBy=name&visible=1 HTTP/1.1" 500 46 "http://kimai2.loc/en/team/timesheet/create" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

**Comment by kevinpapst** [comment]
Hm, 500 error means something is wrong. But without logs I cannot say what.
Check var/log/prod.log and/or your webserver/php logs.

**Comment by emabot80** [comment]
[prod.log](https://github.com/kevinpapst/kimai2/files/3018725/prod.log)

that's the prod.log produced When I reply the above steps 

Hope it's useful

**Comment by kevinpapst** [comment]
You have still permission problems.
The complete directory var/ and all subdirectories need write permissions:
```[2019-03-28 15:22:15] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The directory "/var/www/kimai2/var/cache/prod/jms_serializer" is not writable." ```

**Comment by emabot80** [comment]
Ok thanks.

I fix the permission problem.
Now works fine.

Many many thanks

Best regards
