### ISSUE TITLE
Demo not loading

### ISSUE THREAD

**Issue by eldelacajita** [kevinpapst/kimai2#665]
**Describe the bug**
When trying to access the demo from Firefox, I only get a white screen.

**To Reproduce**
1. Go to https://www.kimai.org/demo/ and click on any demo.
2. Get a new, blank tab.

**Logfile**
-

**Screenshots**
-

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Thinkpad X240
 - OS: Antergos Linux
 - Browser: Firefox
 - Version: 66.0.2 

**Additional context**
-

**Comment by kevinpapst** [comment]
Thanks for the info!
A cron job killed all sites, is fixed now and I hope it stays this way.

**Comment by eldelacajita** [comment]
Thanks! I'm trying it now, it's looking great so far.
