### ISSUE TITLE
Additional fee for on-site work; could be implemented by adding fixed and hourly rates

### ISSUE THREAD

**Issue by Kurgan-** [kevinpapst/kimai2#666]
I bill my time per hour (and this is easy with Kimai) but I also bill a fixed fee for on-site work, that covers the cost for traveling to the customer's site. This cost is, in my use case, related to the activity (some activities are on-site, others are at my office, so some have a travel cost and others don't). I usually (with Kimai 1.0) export data and then manually (out of Kimai) add the travel cost by counting the occurrences of activities that are on-site. 

For example, if I have gone to the customer's site 5 times (for a total of 40 hours) Kimai v1 shows me the cost for 40 hours, and I manually add the cost for 5 trips to the customer's site. 
This comes quite easy because in the export I can count the occurrences of the on-site activities I have recorded. 

In Kimai V2, i hoped that the "fixed" rate could be added to the hourly rate, so that an activity that has a fixed rate of 10 and a hourly rate of 50 could be billed as 10 + (50 * hours spent). As far as I have understood, this is not the case. Fixed rate overrides hourly rate, it does not get added.

It should be nice to be able to ADD fixed and hourly rates (as defined for an activity) so that some activity have only a fixed rate, some only an hourly rate, and some both.

In my opinion it should be not too hard: just alter the logic used to calculate rates. Now the logic is "if there is a fixed rate, use it and ignore the hourly rate". The new logic should be "If only one rate is defined, use it. If both are defined, add up the rates, fixed and hourly". Which can be reduced to a simple "add both rates anyway; an undefined rate means zero".

I know I can somehow emulate this behaviour using rounding, but I'd like to have a clear indication of times (not rounded) and the additional "on-site" fee (if it's applicable to the activity).

Thanks

**Comment by kevinpapst** [comment]
Changing the logic is unfortunately not as easy as that, as it would cause a huge BC break.

We would either need an additional field or, what I would prefer:
I am thinking of an "location field" for each timesheet record, which then could be used for calculating additional costs.

**Comment by Kurgan-** [comment]
Uhm, ok, so my idea is not feasible. 

I'm still not sure about what could be the best solution: something that is easy to use from my point of view, and also hopefully useful for other people.

I could be fine with a simple logic: in the activity record there is a field that, if set, adds a cost (the cost is indicated in the field itself) to the activity.

Every time I log that activity, the cost gets added (once per logged entry). This is quick and easy to use (just log the right activity, and I get the fixed cost plus the hourly cost), and has a little limitation: if I go to a customer site in the morning, then take a break for lunch, then work in the afternoon, I end up with TWO entries for one day of work, and I cannot make the customer pay the travel fee two times. 

To avoid this, I currently (in Kimai v1)  log only one entry, from morning to evening, then manually subtract the time spent out for lunch from the total time logged, so that I don't log two entries.This is sub-optimal bu I can live with this limitation.

Otherwise, there could be something that must be flagged every time you log an entry, so it would be easy not to flag two travel fees for the morning and the afternoon at the same customer site, but this way I'd have to manually flag the travel fee every time I start a task, and this means more interaction every time, and less automation.

**Comment by kevinpapst** [comment]
And the next person wants an added value which is not static but based on the logged duration ;-)
It can become very complicated very fast, thats why a proper plan needs to be laid out first before I will work on such a feature.

**Comment by Kurgan-** [comment]
You already have that feature for overtime / weekends, if I remember correctly. :-)

Sure, it must be planned properly. And, if I may, I think that proper planning should take into consideration my first idea, that is adding fixed and hourly fees. I have read the manual about fees, and the way that they "win" one on another, I quote:

    Timesheet fixed rate
    Activity fixed rate
    Project fixed rate
    Customer fixed rate
    Timesheet hourly rate
    Activity hourly rate
    Project hourly rate
    Customer hourly rate
    Users hourly rate

I really don't get the logic in working like this, and not like this:

Take the first that's not empty of these:
   Timesheet fixed rate
    Activity fixed rate
    Project fixed rate
    Customer fixed rate

then ADD the first that's not empty of these:
    Timesheet hourly rate
    Activity hourly rate
    Project hourly rate
    Customer hourly rate
    Users hourly rate

Also, if for some reason you want to override the logic, set the desired rate to ZERO (and not empty string) in the timesheet, and you have just avoided adding the wrong rate from lower tier entries (for example, from project or customer).

The more I think of it, the more it seems simple and flexible to me.

**Comment by kevinpapst** [comment]
If I get you right that is an unacceptable BC break, because:

Consider someone:
- having an activity with an hourly rate of 80
- logged 1000 records on that activity with a duration of 1 hour each
- 50 of them have a fixed rate of 150
- piles up a total of 83500

If we change it to your proposed logic, that would now mean a total of 87500.

Yes, all these values are calculated in the DB, but if one of the records would get updated, then the rate value would be re-calculated and suddenly changed without user interaction. That record was probably already billed to the customer => you changed your billing history, which is definitely not allowed.

Its simple: it is too late to add such a breaking change.

But we could think about adding calculation modes. Then you could actively decide whether the current logic logic applies (default) or your proposed one is used. 
There are already modes for rounding, then why not using them for rate calculation as well...

**Comment by Kurgan-** [comment]
You are right. In this case, the previous records would be miscalculated, unless the user manually modifies the 50 fixed ones settinga a zero in place of the null in the hourly value of every record, thus neutralizing the default rate of 80 for that 50 records.

I believe that my proposed logic is nice and flexible, but it surely is not backwards-compatible unless you "correct" the old records by setting a zero in the hourly rate instead of a null, when there is a value set in the fixed rate. That way, the default hourly rate would not be added to the fixed rate, thus mimicking the previous behaviour.

**Comment by kevinpapst** [comment]
Rate calculation changed a lot in the meantime.
As I will not work on that exact use-case, all I can provide are some ideas:
- You can add plugins to change the rate calculation
- You can have a look at the Expenses plugin: https://www.kimai.org/store/expenses-bundle.html
