### ISSUE TITLE
How-to : Invoice Exclusion

### ISSUE THREAD

**Issue by emabot80** [kevinpapst/kimai2#668]
Hi all,

I'd like to exclude the Invoices section and all cost related fields.
How is the best way?

Thanks folks

**Comment by kevinpapst** [comment]
Use your own permission definitions: 
https://www.kimai.org/documentation/permissions.html

Not available through a UI by now.

**Comment by kevinpapst** [comment]
Any feedback? If not, I am closing this

**Comment by emabot80** [comment]
Hi Kevin,
I had not time these last days to change permissions.
I'm going next week.
If you want to close no problem.

thanks 

ema
