### ISSUE TITLE
Group of user

### ISSUE THREAD

**Issue by emabot80** [kevinpapst/kimai2#669]
**Is your feature request related to a problem? Please describe.**
Not a technical problem, but shaping kimai to my objectives I'd like to have the chance to create group of user, useful for statistical purposed (Export section)

**Describe the solution you'd like**
Group of users creation option

many many thanks

**Comment by emabot80** [comment]
Hi All,

any replies to this feature request?

thanks

**Comment by kevinpapst** [comment]
This was discussed multiple times in the issues, e.g. in #366. 
To sum it up: yes, at one point in time there will be support for user teams.
Closing, duplicates #366
