### ISSUE TITLE
Question about ROLES and IP Access

### ISSUE THREAD

**Issue by xpresas** [kevinpapst/kimai2#674]
Super_Admins ROLE should be able to connect from any IP adress just like right now.
But simple user could connect only from a certain IP.
I was looking into security.yaml and some symfony documentation. I am junior level programmer so I can make some things myself. Altho I havent tried it yet. So my question: is it possible to do on a current stable kimai version?

**Comment by kevinpapst** [comment]
Kimai itself doesn't have such a feature.
I don't know if Symfony supports something like that out-of-the-box. Maybe there is a bundle that can be installed via composer and then configured.
Or you write your own Kimai plugin (also just a Symfony bundle) which listens on the login event.

Should be fairly easy (at least when you previously worked with Symfony): 
https://symfony.com/doc/master/bundles/FOSUserBundle/controller_events.html
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/FOSUserEvents.php#L235

Your first step should be to create a EventSubscriber and place it in the EventSubscriber directory.
Copy & paste [this class](https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/RegistrationSubscriber.php).
After you get it working, create a plugin from it, so we can make it available to everyone.

**Comment by xpresas** [comment]
I was thinking more simple approach like "https://symfony.com/doc/current/security/access_control.html" here.

**Comment by kevinpapst** [comment]
Hm, you see: I don't knew about that. Did you try it?

**Comment by xpresas** [comment]
Not yet, wanted to see other opinions and maybe hear from you. I do not want to break the whole system. Cuz I installed it over FTP which is a pain in the ...

**Comment by kevinpapst** [comment]
Yes, FTP is definitely a pain^^

**Comment by xpresas** [comment]
Quick update: I tried it but any changes made to the security.yml does not affect webpage at all.

**Comment by kevinpapst** [comment]
Did you run `bin/console cache:clear`?
In `production` all configs are cached until they are refreshed.
Chance to `APPLICATION_END=dev` in your `.env` file, then each file change is automatically detected and the cache refreshed upon page load.

**Comment by xpresas** [comment]
Im still playing with it I managede to restrict IP acess altho it still f***s up some permissions. After I will make it work I'am gonna post it here. (I didint even delete the cache just changed the security.yaml and it worked)

**Comment by xpresas** [comment]
Alright so I managed it to make it work. This code example will make your website accessable only from IP adress privided in the brackets `ip [NN.NN.NN.NN]` if you want to make it accessable from several IP adressess instead of `ip [NN.NN.NN.NN]` it needs to be ``ips [NN.NN.NN.NN, MM.MM.MM.MM]``
the file to be edited is in your 

> config/packages/security.yaml

```
    access_control:
        - { path: '^/(%app_locales%)$', role: IS_AUTHENTICATED_ANONYMOUSLY, ip: [NN.NN.NN.NN] }
        - { path: '^/(%app_locales%)/login', role: IS_AUTHENTICATED_ANONYMOUSLY, ip: [NN.NN.NN.NN] }
        - { path: '^/(%app_locales%)/register', role: IS_AUTHENTICATED_ANONYMOUSLY, ip: [NN.NN.NN.NN] }
        - { path: '^/(%app_locales%)/resetting', role: IS_AUTHENTICATED_ANONYMOUSLY, ip: [NN.NN.NN.NN] }
        - { path: '^/(%app_locales%)/', roles: ROLE_USER, ip: [NN.NN.NN.NN] }
        - { path: '^/api', roles: IS_AUTHENTICATED_REMEMBERED, ip: [1NN.NN.NN.NN] }
        - { path: '^/(%app_locales%)/login$', roles: ROLE_NO_ACCESS }
```

The last part was added by me. It uses the default Role_no_access role which means that user doesnt have any roles and is restricted to go to the webpage.
```
        - { path: '^/(%app_locales%)/login$', roles: ROLE_NO_ACCESS }
```

I am still gonna work on making Super_admin role to be able to connect from any IP so in the future Im gonna post my code here.

**Comment by kevinpapst** [comment]
Thanks for sharing! I'd love to make this a documentation page for the website if you figured it out completely.

**Comment by xpresas** [comment]
No problem. Right now I made it just to restrict access from other people. My next step is to let everyone connect to the Login page and only then to filter people by their IP's and Roles. When I will succeed I'am going to post it here. Thanks for taking your time to answer me.

**Comment by xpresas** [comment]
I made it work in a way. Now I need to thing a way to redirect a user who is not authenticated to see /timesheet and /dashboard to something like Google. Gonna post how to tommorow.

**Comment by kevinpapst** [comment]
👍

**Comment by rarvin** [comment]
Dear @xpresas were you able to make #674 work. If so I am looking for IP blocking and also only users with a defined set of IP's from accessing my kimai instance.
