### ISSUE TITLE
When not installed at web root, Kimai fails to load properly

### ISSUE THREAD

**Issue by stoberblog** [kevinpapst/kimai2#676]
**Describe the bug**
When Kimai2 is installed as a subdirectory (alias in apache in this case), it fails to load as the application calls files that it thinks should be under the domain root. In my case I installed kimai on a VM, where it's installed at 192.168.1.224/kimai2/ When I run open kimai2, the graphics is all missing and the inspector in chrome say it is trying to load 192.168.1.224/build/app.js (where this should be 192.168.1.224/kimai2/build/app.js).

I've attached a screen shot of my chrome window with the inspector open.

I'm sure there is a simple fix but it's not noted in the installation guide, and the link for developers given in this bug report (https://github.com/kevinpapst/kimai2/issues/492) no longer works (https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md#rebuilding-assets-for-use-in-a-subdirectory)
![Kimai2 Bug](https://user-images.githubusercontent.com/25950862/55535043-b254da80-5701-11e9-98c3-7e12faa86a20.PNG)

For those wondering why I'm installing as a sub directory and not creating a domain; a sub directory means I don't need to set my virtual machine up with a static IP address, as I use the same VM on different machines which can occasionally be on different networks.

**Comment by kevinpapst** [comment]
Use the latest master, this was fixed and the documentation therefor removed.

Or try to set this config: https://symfony.com/doc/current/reference/configuration/framework.html#base-path
