### ISSUE TITLE
Option to allow Markdown in Project/Activity-comments

### ISSUE THREAD

**Issue by ralf1070** [kevinpapst/kimai2#677]
To be able to better describe projects and activities it would be nice to have an option to activate Markdown in comments of both of this record types. Currently all formating within these comments is ignored, even newlines to at least have paragraphes are skipped.

I read the statement about possible security risks in the documentation. Even if I can't see the risk: it would be nice if this feature could be enabled as an option for installations where security issues are no problem.

**Comment by kevinpapst** [comment]
The used Markdown parser does not apply sanitization, so you could potentially insert javascript code, which could again potentially lead to security issues ... always assuming that you can't trust the user.

But yes, feature request accepted.

**Comment by kevinpapst** [comment]
Wanna test it? This will be added with #807
