### ISSUE TITLE
Is Lifetime option in security.yaml connected to users time?

### ISSUE THREAD

**Issue by xpresas** [kevinpapst/kimai2#678]
So In security.yaml theres an a default value called "lifetime" which is set to one week. 
The question is this duration is directly connected with users time session? 

What I mean is if user is still working(timesheet/create) but the life time expires does the clock is still active for the user?

**Comment by kevinpapst** [comment]
The lifetime setting is AFAIK only for the users session / the cookie lifetime:
https://symfony.com/doc/current/security/remember_me.html

The record stays active until it is stopped, there is no logic to stop a record which is running automatically.

**Comment by xpresas** [comment]
> The lifetime setting is AFAIK only for the users session / the cookie lifetime:
> https://symfony.com/doc/current/security/remember_me.html
> 
> The record stays active until it is stopped, there is no logic to stop a record which is running automatically.

Thank you, I was just making sure. :D
