### ISSUE TITLE
Grouping Users when Exporting

### ISSUE THREAD

**Issue by mserrano3** [kevinpapst/kimai2#680]
Is there any way to export time spent on tasks grouped together? For example when I export a timesheet, it gives me each individual user's time every time they clocked it in. I am wondering if we can skip the task of having to add the total time spent and just automatically get a total time. 

Allowing to group users and tasks and get one total time spent in a given task would be ideal. 

We've been exporting to an excel and adding everything that way. it's time consuming given the fact that each task will sometimes have hundreds of time inputs put against it. 

Thank you, I tried finding this issue discussion elsewhere but was unsuccessful.

**Comment by kevinpapst** [comment]
I don't understand your problem. Please describe your use-case.

**Comment by kevinpapst** [comment]
@mserrano3 Can you please give me an real-world example, because I am still unsure what you mean exactly.
So for example an export and the version you created from it via Excel

**Comment by kevinpapst** [comment]
No feedback, no vote, closing
