### ISSUE TITLE
mysql limit of max amount of activities ?

### ISSUE THREAD

**Issue by bjdros** [kevinpapst/kimai2#681]
Using kimai2 in windows10 with the XAMPP application, i have it all working but when i try to create a new timesheet with customer id 326, i can not choose anymore the activity in the pulldown menu. 
All goes well till customer id 325.
I dont understand why it goes wrong when choosing customer id 326.
Is there a limit of max amount of activities ?

I inserted into the customers, activities, projects tables, records with a sql file like this 

LOAD DATA LOW_PRIORITY LOCAL INFILE 'D:\\xampp\\htdocs\\kimai2\\activities.csv' INTO TABLE `kimai2_activities` FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES ( 
id,
project_id,
NAME,
comment,
visible,
fixed_rate,
hourly_rate
);

Here the amount of records i inserted into each table 

![image](https://user-images.githubusercontent.com/49257542/55676153-e6b4cc00-58a4-11e9-8c78-32328dbbe2c8.png)

Below a the timesheet screen with the last id (customer 325) where i can choose the activity without a problem 

![image](https://user-images.githubusercontent.com/49257542/55676137-8de53380-58a4-11e9-80a9-a1381a86332f.png)

And here where it goes wrong at customer id 326 where i can not choose anymore an activity in the pulldown menu

![image](https://user-images.githubusercontent.com/49257542/55676133-6db57480-58a4-11e9-9646-8318ae8e6f8d.png)

 - OS: Windows10
 - Browser: chrome
 - Versión 73.0.3683.86 (Build oficial) (64 bits)

 - Kimai 2 - 0.8.1
 -  Apache 2.4.38, MariaDB 10.1.38, PHP 7.2.16, , XAMPP Control Panel 3.2.2

Thanks, Brienen

**Comment by kevinpapst** [comment]
Are these global activities?
Do you have anything in var/logs/prod.log?
Anything in your browser console when changing the customer? Probably the API runs for any reason out of memory and does not return the list of activities.

**Comment by bjdros** [comment]
hi kevin,

thanks for the fast response, 
i checked the prod.log but is empty.
i did a clear and warmup of the prod

![image](https://user-images.githubusercontent.com/49257542/55677068-b75b8a80-58b7-11e9-9197-9fa4de7e1535.png)

and the activities are not global.
here the customer that has all its activities (id 325)
![image](https://user-images.githubusercontent.com/49257542/55677115-52ecfb00-58b8-11e9-97f6-5ffd902aee64.png)

and here the customer (id 326) that does have anymore none activities

![image](https://user-images.githubusercontent.com/49257542/55677128-93e50f80-58b8-11e9-847d-ec6968a2aff7.png)

i dont know how to see my browser console...
ok so it might be a mysql memory issue.

**Comment by bjdros** [comment]
i tried a lot, tweaking the my,ini variables but no success 

key_buffer
max_allowed_packet
sort_buffer_size
net_buffer_length
read_buffer_size

if you got more ideas let me know.

thanks, brienen

**Comment by kevinpapst** [comment]
You know how to tweak Mysql settings but not how to open your browser console / network tab?
http://www.lmgtfy.com/?q=how+to+open+my+browser+console

How do you know that there are existing and visible activities for this customer?

**Comment by bjdros** [comment]
No, I dont know how to tweak mysql, i just changed the variables but nothing changed.
Ok i found the browser console, thanks for the link.

I know there are existing and visible activities for this customer since i inserted for each customer 15 activities with visible = 1 with the load data sql file.

**Comment by kevinpapst** [comment]
Then please change to the network tab within your browser tools (the console is one of the tabs) and check what happens after you change the project or customer.

There should be a request to the api happening with an URL like `/api/activities?project=xx&orderBy=name&visible=1`. Does that request have the status 200 or 500?
<img width="434" alt="Bildschirmfoto 2019-04-07 um 13 42 06" src="https://user-images.githubusercontent.com/533162/55683005-f979e000-593a-11e9-9ad6-3d5c65394164.png">

If its 200, please click it and check the "preview". What inside?
<img width="834" alt="Bildschirmfoto 2019-04-07 um 13 41 37" src="https://user-images.githubusercontent.com/533162/55682995-e49d4c80-593a-11e9-8fed-cd52a54e82b1.png">

**Comment by bjdros** [comment]
i did as you described and with the customer id 325 which shows the preview window with info

![image](https://user-images.githubusercontent.com/49257542/55685319-1a3a3980-592b-11e9-813a-abc1cbfea3aa.png)

but with the customer id 326, the preview window is empty 

![image](https://user-images.githubusercontent.com/49257542/55685349-5d94a800-592b-11e9-87c6-25dc1727113c.png)

in the headers window, the request has status 200 

![image](https://user-images.githubusercontent.com/49257542/55685392-fa574580-592b-11e9-88f3-c91167e72388.png)

**Comment by kevinpapst** [comment]
Hm, now it would be interesting to execute a manual SQL query `SELECT * from kimai2_activities WHERE project_ID=1301 and visible=1`. I guess there are results, because your screenshot above shows them in the activities overview (at least unless you don't have duplicated project names).

**Comment by bjdros** [comment]
yes i had only 19486 activities but it had to be 4 times that, because of the 4 projects you can choose for each client. 
tx for the help. you can close this issue.

**Comment by kevinpapst** [comment]
Wow, thats a lot. Using global activities is no option?
Let me know how it works and if you find any performance problem.

**Comment by bjdros** [comment]
yes would be great to have only 15 global activities , but i did not find yet how to do that. 
in administration/activity i see visible and only global on top of the page to choose/set.
but i dont see how to create a global activity?

**Comment by kevinpapst** [comment]
Simple: set the project field in the activity to null

**Comment by bjdros** [comment]
wau , you made my day, instead of having 77.760 activities, now i only have 15 global activities !

last question, is there a way when adding a new timesheet , that the last 2 fields (fixed rate and hour rate) wont show ? and so also wont appear in the xlsx file when i do a export to excel ?

**Comment by kevinpapst** [comment]
You can control the visibility (for the form) with permissions (check docu for that on the website).
But they are always visible in the export. You could change the export template though, but you have to reset it before the next update. For now they are not configurable like the invoice templates.

**Comment by bjdros** [comment]
hi kevin,
i changed the code in  templates/export twig files and the AbstractSpreadsheetRenderer.php file in src/Export  so now no more rates on my export screen and not anymore in the excel file.
But for some reason as being SUPER_ADMIN , the menu option System Configuration on the left side does not appear.
What am i doing wrong with the permissions ?

![image](https://user-images.githubusercontent.com/49257542/55917998-e0d22a00-5bc7-11e9-8dda-0c3575bfc83e.png)


below the part of the local.yaml file

        maps:
            # mapping "sets" or permissions to user roles ("role name" = [array of "set names"])
            ROLE_SUPER_ADMIN: [ACTIVITIES,PROJECTS,CUSTOMERS,INVOICE,INVOICE_TEMPLATE,TIMESHEET,TIMESHEET_OTHER,PROFILE,PROFILE_OTHER,USER,RATE,RATE_OTHER,EXPORT]
        roles:
            ROLE_SUPER_ADMIN: [hourly-rate_own_profile,hourly-rate_other_profile,delete_own_profile,roles_own_profile,system_information,system_configuration]

after changing something i always execute these two commands in Git Bash :
$ php.exe console cache:clear --env=prod
$ php.exe console cache:clear --env=prod

**Comment by kevinpapst** [comment]
Looks good to me. 
If you still run 0.8.1 the screen does not exist.
Are you running the latest master?

**Comment by bjdros** [comment]
no, it does not appear after remove local.yaml and clear cache.

i am using now kimai-release-0.9_dev since that one comes with all the vendor APT.
