### ISSUE TITLE
Monthly export with minimal set of data

### ISSUE THREAD

**Issue by palla89** [kevinpapst/kimai2#682]
**Is your feature request related to a problem? Please describe.**
When exporting a timesheet for a user at the end of the month, I'd need a different set of informations than the exported ones. Right now, Kimai exports an excel with very specific informations, I'd need just a monthly report with just the number of hours worked totally in that month. Example in attachment

**Describe the solution you'd like**
It would be really cool to have an export option to show how much hours users worked, as required for fiscal entities.

**Describe alternatives you've considered**
I read in documentation that there is a custom renderer template that I could override, but I've not found lot of infos about it

**Additional context**
This is the concept I'd like to have: (just for reference of course)
![IMG_3470](https://user-images.githubusercontent.com/12301205/55717939-c7c84e00-59fa-11e9-9256-158aadda4a4e.jpg)

By the way this project is awesome and it's working flawlessly, so I want to thank you very much!!

**Comment by kevinpapst** [comment]
You might want to go with an invoice template, as those are customizable. There is documentation available at the website.
Exporters are currently not supporting dynamic templates.

**Comment by kevinpapst** [comment]
Kimai 1.10 ships with some reports now. 
They don't exactly match your mockup, but almost.
You can have a look and check if that is sufficient. If not, I am open to add more reports.
