### ISSUE TITLE
POST/PUT API endpoints for projects and activities

### ISSUE THREAD

**Issue by schmunk42** [kevinpapst/kimai2#683]
We are evaluating kimai atm. and we're planning to sync projects and todos with it.

Can we do that via the API?

I've just seen GET endpoints for projects and activities.

https://demo.kimai.org/api/doc

**Comment by kevinpapst** [comment]
Yep, API is work-in-progress and extended when someone asks for it.
Or when someone supplies a PR ;-)
What would you need to switch to Kimai?

**Comment by schmunk42** [comment]
Basically it would be nice to have writable endpoints for all URLs.

Moreover, is there a way to write importers and/or a sync for other web-services. We are using Basecamp (https://basecamp.com/) at the moment in conjunction with Roadmap (https://ppmroadmap.com/) and planning to replace Roadmap with Kimai.

**Comment by kevinpapst** [comment]
Ok, that's what I guessed. 
It would be nice to have everything in place ;-) but Kimai is currently attracting a lot of users and I simply can't handle all the workload fast enough ... so things have to wait. But the API endpoints are needed, I know. 

Don't know if an importer can be abstracted in a useful way. The 3rd party APIs might be too different for that. Having that as plugin (a Symfony bundle basically) would be the best solution. If we are talking about a one-time import, a Symfony command should be enough which take your API credentials as parameters.
If we are talking about a regular import job, a UI might be nice - or a Symfony command with a cronjob.
I just today received another request for an importer(in that case Asana) today. I guess we should talk about that in another topic.

Do you need the API endpoints for the importer or for another integration? An importer could safely use the repositories and wouldn't need the API.

**Comment by schmunk42** [comment]
> An importer could safely use the repositories and wouldn't need the API.

What exactly are the *repositories*? The database-models?

**Comment by kevinpapst** [comment]
Yep via Doctrine ORM, e.g. [CustomerRepository](https://github.com/kevinpapst/kimai2/blob/master/src/Repository/CustomerRepository.php)
You would create a Symfony command, fetch the CustomerRepository and persist new Customer objects, pseudo-code:
```
$entityManager = $this->getDoctrine->getRepository(Customer::class);
$entityManager->persist((new Customer())->setName('foo'));
```

**Comment by kevinpapst** [comment]
Endpoints are now available in master. Feedback is welcome!

**Comment by schmunk42** [comment]
Works basically, pretty nice!

Would be very helpful to have a more detailed overview about the allowed values for eg. `country`, `currency`, `timezone`.
Also when creating a project I need to specify a budget, which is not part of the API docs (https://demo.kimai.org/api/doc). Would also be good to know which values are optional, eg. `hourlyRate` and `fixedRate`.

**Comment by kevinpapst** [comment]
Required and optional can be distinguished by looking at the models (down at the bottom or switch from "Example value " to Model in the method itself).

I have to lookup the RFCs to be able to tell you the exact value definition, but its basically what you use everywhere: Country = two letter code (DE; GB; FR; RU), Currency = three letter code (EUR; USD; FRA, RUB), Timezone = official ICU list.

Do you need them now or was your intention to raise my awareness, that it should be documented?

**Comment by schmunk42** [comment]
I figured out the values on my own :wink: So just take it as some feedback.

The model info in the method and at the bottom is definitely very helpful, I've missed that :see_no_evil: thank you!

What would be your recommendation to track external references or IDs, can/should I add a custom field?

**Comment by kevinpapst** [comment]
Hm, custom fields should be handled by the core. Its a more or less common request.
My question is: how do you want to use it?

I think its good to have `addCustomField(name, value)` and `getCustomField(name)` at the core entities. Internally an `customFields` array could be used and serialized to the DB as JSON. That allows to have multiple custom fields without the overhead of new tables and joins. 
Could be added as trait (like [this one](https://github.com/kevinpapst/kimai2/blob/master/src/Entity/RatesTrait.php)). 

But it depends on your use-case if that would be enough. 

Lets discuss in a new issue, as this one is finished and closed.
