### ISSUE TITLE
Third-party apps integration

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#684]
I want to collect ideas about third-party integrations.

There are many SaaS software around project-management, which could be coupled with Kimai:
- for synching customer/projects/tasks
- for automatic time-tracking
- for import/export

If you submit an idea, please include your use-case and what should be possible. If you can supply that, also leave some links here to their API.

**Comment by kevinpapst** [comment]
Request via email...
Asana: https://asana.com/developers/documentation/examples-tutorials/overview

**Comment by kevinpapst** [comment]
Dollibarr, see #471

**Comment by hmr-it-jr** [comment]
Not a project management software but a SaaS: Lexoffice - https://www.lexoffice.de/funktionen/api/

**Comment by simone-gasparini** [comment]
Atlassian Jira to track issue/project time

**Comment by infeeeee** [comment]
[Redmine](https://www.redmine.org/) open source project management platform has a rest api where you can add time entries to issues: https://www.redmine.org/projects/redmine/wiki/Rest_TimeEntries. Also projects and users can be created or read by the api.

**Comment by infeeeee** [comment]
[Gitea](https://gitea.io/en-us/) self hosted git server has built in time tracking per issues, but time entries can be created with the api as well: https://app.swaggerhub.com/apis/gitea/gitea-api/1.4.2#/issue/issueAddTime

**Comment by yayitazale** [comment]
A periodicaly importer from and folder route with CSV archive type and a GUI configuration would be awsome to import from almost any Ticketing software.

**Comment by kevinpapst** [comment]
@yayitazale can you open a new issue for that and append an example CSV?

**Comment by HeinzSchrot** [comment]
Hi,
those integrations would be great:
- Punch in via MS Teams Bot
- Timeular:  https://developers.timeular.com/public-api/
Thanks!

**Comment by nightvisi0n** [comment]
Integration with [GitLab](https://about.gitlab.com/) would be great:  
- https://docs.gitlab.com/ce/workflow/time_tracking.html  
- https://docs.gitlab.com/ee/api/issues.html#add-spent-time-for-an-issue

**Comment by Dzordzu** [comment]
Integration with [taiga.io](https://taiga.io/) would be a great option. 
> Taiga is a project management platform for agile developers & designers and project managers
* [API](https://taigaio.github.io/taiga-doc/dist/api.html)

It would be great if there will be an import/sync option with the current tasks

**Comment by kevinpapst** [comment]
LOL, never heard the wording "necrobump".

Even though this is not on the very near roadmap, this collection of possible integrations is good to have for the future.

**Comment by dabenzel** [comment]
Would also love to see a Lexoffice integration :)

**Comment by dabenzel** [comment]
Lexoffice now has a [public API ](https://developers.lexoffice.io/docs/#lexoffice-api-documentation/?CID=1766)
