### ISSUE TITLE
Lock exported objects

### ISSUE THREAD

**Issue by chrisandchris** [kevinpapst/kimai2#686]
**Is your feature request related to a problem? Please describe.**
As a "manager", i want to lock certain time objects from editing, as they were exported (or invoiced to a client) and edit should be prohibited.

**Describe the solution you'd like**
We wold like to have an option to disable editing of time entries that are exported. Because from the moment we created an invoice (or we export the time entries to another system), any change in entries results in differences between the invoice or the information in the 3rd party system.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
None provided.

**Comment by kevinpapst** [comment]
Thanks for your request! I thought about that already, but not sure if I like the "option". Maybe make this a default behaviour, as it makes pertly sense to lock them down. 

The invoice screen would need improvement (something like a "preview" and "save" button, latter one will automatically set all included records to exported). This should also be considered for the export view.

What is your opinion on:
- Deleting exported records
- Editing exported items in the admin view

**Comment by chrisandchris** [comment]
I think an option is not wrong - it may be a business rule (emphasize may, it's not a must).

Personally, i don't like "delete" and rather would make it "delete" button which executes an "archive" action (hides the record everywhere, but still there on database level), as this prevents some issues (accidental delete, deletion under bad pretext, ...).

**Comment by kevinpapst** [comment]
I think simple is the best and I am against too many config options.
I'ts simple logic (and probably even required by the law in some countries) that an exported/invoiced record is not allowed to be edited afterwards.
Maybe I will make it a permissions, I'll have to think about it...

**Comment by hmr-it-jr** [comment]
I think this is somehow related to #224 - if you implement this, you can definitely close my issue #224 

I don't like the possibitly to delete something. As @chrisandchris mentioned already the archive solution sounds best.

**Comment by kevinpapst** [comment]
I added this feature in PR #798 
Can you @chrisandchris and @hmr-it-jr please have a look and help testing?
Its installed at the demo site, link can be found in the PR.

**Comment by chrisandchris** [comment]
I just looked through the code and it seems quite good. Testing will take a couple of days.

**Comment by kevinpapst** [comment]
Now available in master
