### ISSUE TITLE
Export to PDF: Format like the "list" format in Kimai V1

### ISSUE THREAD

**Issue by Kurgan-** [kevinpapst/kimai2#689]
I'd like to have a PDF export in Kimai2 that resembles the "LIST" format of the export in Kimai 1. 

Summary header is perfect in Kimai2, but the list below shows entries ordered by times, all of the customers and projects are mixed. 
In Kimai v1, two pdf export formats exist: one is named "List" and it does what I need. It groups entries by customers, then project, and then it shows entries ordered by date and time.

Something like:
```
CUSTOMER1
 PROJECT1
    entry
    entry 
    entry
 PROJECT2
    entry
    entry

CUSTOMER2
  PROJECT1
    entry
    entry
```
and so on.
 
Thanks

**Comment by Kurgan-** [comment]
Sorry, i used some wrong terminlogy. I have corrected "tasks" in "projects", which is consistent with Kimai terminology.

**Comment by kevinpapst** [comment]
Next version supports adding export templates.
What do you think about building and sharing it with the community?

**Comment by kevinpapst** [comment]
Writing export that satisfy every user is impossible. 
If someone wants to provide and maintain a report in the long run, I gladly accept PRs.

Closing until then.
