### ISSUE TITLE
totals do not match

### ISSUE THREAD

**Issue by 1willem** [kevinpapst/kimai2#691]
**Describe the bug**
The totals shown on the dashboard tab do not match the totals in brackets on top of the separate tabs (projects, users, costumers, activities). The latter show a lower number. Has this anything to with the active/visible notion?

**To Reproduce**
log in with susan_super
check the different tabs and compare the total on the dashboard with the total in brackets next to the title of the separate tabs.

**Desktop/Smartphone**
 - Device: [Desktop PC]
 - OS: [WIN7]
 - Browser [chrome]
 - Version [Versie 73.0.3683.86 (Officiële build) (64-bits)]

**Additional context**
 - Kimai version: I checked the developer demo and the stable demo. Same issue.

**Comment by kevinpapst** [comment]
You are right, there is a bug. Not the one you mentioned, because the number on the dashboard shows the "real" total and the number on the admin screen shows the number of all entries within the filtered result. And the default filter does not include hidden items, therefor the number is different.

BUT: with the introduction of the javascript reload, this number now doesn't change when the filter changes. 

Thanks for pointing out! I guess I will simply delete the number from the admin screen.

**Comment by 1willem** [comment]
The delete you propose is indeed a simple solution. However, it could be interesting information to see in an eye blink the exact total amount of visible/active users/customers/projects/activities. Maybe changing the description in the title of the separate tabs is a more elegant solution, for instance in: "(### active users in total)", "(### visible projects in total)", etc. There is then no need to reload this number according to the filters applied.

Or just delete it anyway. The latter brings me to a suggestion (we kind of leave the label of bug here):
Would it be an idea to add in the Custom CSS plugin the possibility to customize the totals shown below in the dashboard tab? I, for instance, do not have a wide variety of activities. Therefore, to show this total isn't much of interest to me. The dashboard showing me the total amount of "visible" projects and next to it the total amount of "invisible" projects is more interesting to me. This way I can easily manage how many projects I have openend and closed. This, off course, is a need that is very depending on the demands of each occupation. That is why I'm thinking of an extension of the Custom CSS plugin. Maybe this could be implemented in the: "Add pre-defined rule" in the "General" tab under the name "Dashboard-totals". The manipulation could, for instance, exist in choosing what amount is shown in each of the four tiles (users/customers/projects/activities) and, next, choosing whether, for each tile, the "real" total amount is shown, the amount of actives/visibles is shown, or the amount of inactives/hiddens is shown. Furthermore, the description could be changed (now default as "Amount users", etc.) and the "more infos" link could (automatically) redirect to the chosen tab in question (users/customers/etc.) with the chosen filters in question applied (active/visible or inactive/invisible).

This plug-in would make showing the total in brackets in the separate tabs no longer of use.

What is your idea on this in terms of usefulness/feasibility/workload?

**Comment by kevinpapst** [comment]
The custom css extension is not usable for that.

And the configurability of the dashboard needs probably a rewrite, I am not happy as it works today.
But it is already configurable (see documentation), unfortunately the active/inactive flag is not included in the statistics which are used to populate the data. Its simple to add, but I wonder how many people are really interested in these number. 
I would much more like to add that to an upcoming reporting extension, but if you want to submit a PR I can guide you in the right direction and we can add it to the dashboard.
