### ISSUE TITLE
Remove active flag in user preferences form for non admin user

### ISSUE THREAD

**Issue by simone-gasparini** [kevinpapst/kimai2#694]
Remove active flag in user preferences form for non admin user, this prevent users to auto lock out itself.
PR will follow.

<img width="207" alt="Schermata 2019-04-10 alle 17 34 16" src="https://user-images.githubusercontent.com/1280258/55892631-ebd08e80-5bb6-11e9-8b9a-cacc50b6850c.png">

**Comment by kevinpapst** [comment]
True, that option should only be available for users with proper permission.
Can you please open a separate PR for this.
