### ISSUE TITLE
Add custom fields in timesheet record

### ISSUE THREAD

**Issue by simone-gasparini** [kevinpapst/kimai2#697]
I think it may be useful for an administrator to add custom fields to keep track of other values

Example:
we need a custom field to track the number of the lunch tickets used by a person

@kevinpapst have you any idea on how to do it?

**Comment by kevinpapst** [comment]
Write a plugin for that? Or build something that allows custom fields.
I like the idea, but don't see that this will fit on the near roadmap.

**Comment by kevinpapst** [comment]
I know this was the earlier ticket, but the other one is more detailed, so I will close this one and keep #760.
Please subscribe there. I will help with that feature, if someone starts a branch.

**Comment by kevinpapst** [comment]
Working on it right now, wanna help testing and provide feedback? See #871
