### ISSUE TITLE
API date and datetime format

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#700]
**Describe the bug**
Were there some breaking api changes I've missed?

I wanted to make some final tests on the Kimai 2 app I've developed and noticed that posting my activties doesn't work anymore.  Will post the error below. Besides this /api/doc returns an error, too.

**To Reproduce**
1. Go to demo.kimai.org
2. Login as susan_super | kitten
3. navigate to /api/doc

![grafik](https://user-images.githubusercontent.com/36242595/55988097-4515ec00-5ca3-11e9-8d81-3ea569b956fe.png)

----------

**Error response when posting activities**
```
{
   "config":{
      "transformRequest":{

      },
      "transformResponse":{

      },
      "timeout":29000,
      "xsrfCookieName":"XSRF-TOKEN",
      "xsrfHeaderName":"X-XSRF-TOKEN",
      "maxContentLength":-1,
      "headers":{
         "Accept":"application/json, text/plain, */*",
         "X-AUTH-USER":"susan_super",
         "X-AUTH-TOKEN":"api_kitten",
         "Content-Type":"application/json;charset=utf-8"
      },
      "method":"post",
      "baseURL":"https://demo.kimai.org/api/",
      "url":"https://demo.kimai.org/api/timesheets",
      "data":"{\"begin\":\"2019-04-11 21:39:28\",\"end\":\"2019-04-11 21:39:30\",\"customer\":1,\"project\":2,\"activity\":3,\"description\":\"test\",\"fixedRate\":\"0\",\"hourlyRate\":\"0\"}"
   },
   "request":{

   },
   "response":{
      "data":{
         "code":400,
         "message":"Validation Failed",
         "errors":{
            "errors":[
               "This form should not contain extra fields."
            ],
            "children":{
               "begin":{

               },
               "duration":{

               },
               "customer":{

               },
               "project":{

               },
               "activity":{
                  "errors":[
                     "This value is not valid."
                  ]
               },
               "description":{

               },
               "fixedRate":{

               },
               "hourlyRate":{

               },
               "exported":{

               }
            }
         }
      },
      "status":400,
      "statusText":"Bad Request",
      "headers":{
         "cache-control":"max-age=0, must-revalidate, private",
         "content-type":"application/json"
      },
      "config":{
         "transformRequest":{

         },
         "transformResponse":{

         },
         "timeout":29000,
         "xsrfCookieName":"XSRF-TOKEN",
         "xsrfHeaderName":"X-XSRF-TOKEN",
         "maxContentLength":-1,
         "headers":{
            "Accept":"application/json, text/plain, */*",
            "X-AUTH-USER":"susan_super",
            "X-AUTH-TOKEN":"api_kitten",
            "Content-Type":"application/json;charset=utf-8"
         },
         "method":"post",
         "baseURL":"https://demo.kimai.org/api/",
         "url":"https://demo.kimai.org/api/timesheets",
         "data":"{\"begin\":\"2019-04-11 21:39:28\",\"end\":\"2019-04-11 21:39:30\",\"customer\":1,\"project\":2,\"activity\":3,\"description\":\"test\",\"fixedRate\":\"0\",\"hourlyRate\":\"0\"}"
      },
      "request":{

      }
   }
}
```

**Comment by kevinpapst** [comment]
Hm, yeah ... the internal server error is a problem I cannot reproduce that locally... thats what I like the most. I'll check what's going on there.

The combination customer 1 / project 2 / activity 3 seems to be legit, don't know what the reason is for that error.

And I found another problem unfortunately in the API. Its related to the time-format, which seems to be user and locale specific for the API as well, what is wrong IMO.

Grrr, the API is really not stable for now. I have to work on that for 0.9. I'll keep you updated...

**Comment by hmr-it-jr** [comment]
> And I found another problem unfortunately in the API. Its related to the time-format, which seems to be user and locale specific for the API as well, what is wrong IMO.

I think using the mysql datetime format makes sense the most - and it's format I already use 😄 
I read the time from the phone - so I don't know if  there are some cases where the timezone of the phone is different than the timezone from the server. If this is a feature people want then they'll report it to me.

**Comment by kevinpapst** [comment]
Without doing anything related, the docs work again.
I just merged some other changes the last days, really weird - maybe a server issue.

**Comment by hmr-it-jr** [comment]
I can confirm that it works now again. I've tested the docs, and with the Kimai 2 app, the GET and POST requests which I've tested in #701 too.

I think we can close this issue.
