### ISSUE TITLE
Review export lifecycle for plugin injection

### ISSUE THREAD

**Issue by simone-gasparini** [kevinpapst/kimai2#702]
Add ExportSubscriber to dispatch event for plugin based export module.
PR will follow.
Help needed 😄

**Comment by kevinpapst** [comment]
Are you sure you need a EventSubscriber?
The service already finds automatically all tagged exporter:
https://github.com/kevinpapst/kimai2/blob/master/config/services.yaml#L71
I'd always prefer a build-time logic (custom CompilerPass if necessary) over an EventSubscriber ... if possible.

**Comment by simone-gasparini** [comment]
Now the export types are hardcoded in ExportQuery.php, I've added the ability to load the export ids dynamically.

**Comment by simone-gasparini** [comment]
With this commits I've created a fully functional export plugin.

**Comment by kevinpapst** [comment]
Nice job! Which format do you export?

**Comment by simone-gasparini** [comment]
It's another html export but in a custom format for an our customer

**Comment by kevinpapst** [comment]
I wonder if we should rework the export to allow templates (like invoice) instead of doing it this way. Might be a more common request.

**Comment by simone-gasparini** [comment]
I don’t think that the export can be done by template only. In my case I have done all the timesheet elaboration in php and it’s not possible to do that in template/javascript. Plugin integration is essential, templating can be a secondary solution, because if you have to elaborate timesheet data or add something like translation, with template only way it can’t be done.

**Comment by kevinpapst** [comment]
Long term plan for the export: there should be some options (probably shown in a modal after clicking one of the buttons) that will change how/which data is passed to the renderer... but this can probably never satisfy everyone.

But good argument why a template won't work in this case.
