### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#705]
Hi Kevin,

we're using the latest Version of Kimai (0.8.1.) and can't login anymore.

The log contains:

> [2019-04-16 14:31:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /de/login_check": Method Not Allowed (Allow: POST)" at /is/htdocs/wp1162879_MZPWXTP1OB/www/kimai2/vendor/symfony/http-kernel/EventListener/RouterListener.php line 143 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /de/login_check\": Method Not Allowed (Allow: POST) at /is/htdocs/wp1162879_MZPWXTP1OB/www/kimai2/vendor/symfony/http-kernel/EventListener/RouterListener.php:143, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /is/htdocs/wp1162879_MZPWXTP1OB/www/kimai2/var/cache/prod/srcProdProjectContainerUrlMatcher.php:25)"} []

Deleting the cache doest help...

**Comment by kevinpapst** [comment]
You followed exactly these steps:
https://www.kimai.org/documentation/updates.html
?

**Comment by kevinpapst** [comment]
Also - it says "only POST allowed". This is true. Did you modify templates?

**Comment by blochwitz** [comment]
Why? We don't made any update. We use this version since its release and today this error appeared...

**Comment by blochwitz** [comment]
After compiling/installing we made some changes of the login page and other parts in the backend view but until today this works without any error.

**Comment by kevinpapst** [comment]
LOL, so its clearly the fault of Kimai that is suddenly stops working when you change stuff?!?
Fix your login form and add `method="POST"`.

**Comment by blochwitz** [comment]
This is the error that is displayed at the login-page since 1 hour:
![Bildschirmfoto 2019-04-16 um 15 24 17](https://user-images.githubusercontent.com/42935152/56213123-bb2ba180-605b-11e9-8a9f-f93370421953.png)

**Comment by blochwitz** [comment]
What? Why is Kimai working anymore today when we made our changes weeks ago?

**Comment by blochwitz** [comment]
We only changed the css (background color and logo file) and nothing in the „login form“

**Comment by blochwitz** [comment]
Now the login works again... but i didn't made changes

**Comment by kevinpapst** [comment]
That's Kimai self-destruction mode, randomly stops working - just to have some fun in the issue tracker ;-)

Thanks for the update!

**Comment by blochwitz** [comment]
Yeah, you have the fun and i 15 angry colleagues...

**Comment by kevinpapst** [comment]
You think I have fun when I waste my time on stuff thats not related to Kimai ... for free?!?

**Comment by blochwitz** [comment]
Yes, sure. We think so cause you do that for free ;)

**Comment by kevinpapst** [comment]
Good idea, I guess I am gonna create a "first of April" plugin that randomly breaks stuff in Kimai!

**Comment by blochwitz** [comment]
Yeah, but only the login page after changing something in the css so that the user have to add <method="POST"> in the “login form“...
