### ISSUE TITLE
Is this project support postgres ?

### ISSUE THREAD

**Issue by naiba** [kevinpapst/kimai2#706]

**Comment by kevinpapst** [comment]
Not yet, as nobody ever asked. But its fairly simple to add this.

**Comment by naiba** [comment]
Thanks @kevinpapst, nice tool, but I am a little dizzy with so many forms, and I can't set a salary for everyone, maybe I will try https://timetracker.anuko.com first.

**Comment by kevinpapst** [comment]
Not every tool fits every purpose. Good luck!
