### ISSUE TITLE
Export date parsing does not care about timezone

### ISSUE THREAD

**Issue by simone-gasparini** [kevinpapst/kimai2#707]
**Describe the bug**
Export date parsing does not care about timezone

**To Reproduce**
php.ini with date.timezone = 'Europe/Rome'.
User setup with timezone to Europe/Rome and Italian language.

**Logfile**
ExportQuery var dump
...
protected 'dateRange' => 
    object(App\Form\Model\DateRange)[1611]
      protected 'begin' => 
        object(DateTime)[1579]
          public 'date' => string '2019-03-31 22:00:00.000000' (length=26)
          public 'timezone_type' => int 3
          public 'timezone' => string 'UTC' (length=3)
      protected 'end' => 
        object(DateTime)[1542]
          public 'date' => string '2019-04-30 21:59:59.000000' (length=26)
          public 'timezone_type' => int 3
          public 'timezone' => string 'UTC' (length=3)
...

**Screenshots**
<img width="545" alt="Schermata 2019-04-16 alle 15 28 10" src="https://user-images.githubusercontent.com/1280258/56213440-51f85e00-605c-11e9-9618-bd89e828dc78.png">
<img width="341" alt="Schermata 2019-04-16 alle 15 28 25" src="https://user-images.githubusercontent.com/1280258/56213445-53c22180-605c-11e9-85b0-2955a4cc71ec.png">

**Comment by kevinpapst** [comment]
There might be other places where a toolbar filter is existing. Thanks for the report!

**Comment by kevinpapst** [comment]
Could you test #716 and see if that fixes your problem?

**Comment by kevinpapst** [comment]
Okay, I verified it by setting the timezone to Australia/Sydney and creating an entry at the beginning of this and next month "01.04.2019 00:01 - 01.04.2019 00:02" and "01.05.2019 00:01 - 01.05.2019 00:02".
When filtering for this month (being on master) I didn't saw the "beginning of this month" entry, but saw the "beginning of next month" entry. Which is definitely wrong... now with the changes it vice versa. I see the correct entries.
As assumed that problem existed on all toolbar queries, so thanks for finding this critical problem!

**Comment by simone-gasparini** [comment]
I will verify it in few hours
