### ISSUE TITLE
500 (Internal Server Error) create customer

### ISSUE THREAD

**Issue by MalteKoa** [kevinpapst/kimai2#711]
**Describe the bug**
The creation of an new customer leads into error code 500. The install of kimai was flawless and looked clean. Everything with no need of an customer works fine.

**To Reproduce**
1. Go to Administration>Customer>New Customer
2. After 300s (max_ex for testing) -> 500 (Internal Server Error)

**Logfile**
[prod.log](https://github.com/kevinpapst/kimai2/files/3089950/prod.log)

**Desktop/Smartphone**
 - Device: PC
 - OS: Win10
 - Browser: Chrome/Edge/Firefox

**Additional context**
Debian9
Apache2
MariaDB
PHP7.3

**Comment by kevinpapst** [comment]
Yes, that is a known issue on PHP 7.3 with an older Symfony intl package - you could try the PR #710 which updates all packages

**Comment by MalteKoa** [comment]
Works like a charm for me! Thanks for the quick response! Time to test everything.
