### ISSUE TITLE
Additional field for breaks

### ISSUE THREAD

**Issue by MalteKoa** [kevinpapst/kimai2#713]
**Describe the solution you'd like**
An additional field with the data type date/time in the creation form. There you can add for example "00:30" and this value will be subtracted from the duration.

**Describe alternatives you've considered**
Think the solution above, will be the easiest.

**Additional context**
We need to track our breaks everyday - so somehting like this feature will be a make our life mutch more comfortable.
And additional it is possible to use this kind of field for a workaround. You can subtract the "have to work hours" every day/week/months for a balanced time track or shift hours between persons for a clean invoice.

**Comment by kevinpapst** [comment]
Break times and holidays, illness... are planned - just in a different way.
I am closing this one, as I will not add such a field and break times are already existing as feature request.
