### ISSUE TITLE
Kimai-v1 Import Failure

### ISSUE THREAD

**Issue by sdo992** [kevinpapst/kimai2#719]
Followed the upgrade to Kimai v2 [Documentation](https://www.kimai.org/documentation/migration-v1.html).

My setup:

- Old Kimai v1 1.3.1
- Old Kimai v1 Revision 1394
- One user, who is also the admin
- nginx & mariadb
- OS: Void Linux

I had to re-install void linux; so, I backed up my kimai DB and then re-imported the data from mysqldump and am able to see all my information in the mysql databases & tables. I am able to login and use kimai v1, if I install the old version; however, I would like to upgrade to v2.

I have nginx up and running and can login into Kimai v2 if I use bin/console kimai:create-user; however, the import does not import user information from the kimai v1 database. I do not have any information from the v1 database into the new v2 database. I receive a failure:

`[ERROR] Failed to load timeSheet: An exception occured while executing 'SELECT * FROM `kimai_timeSheet`': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai.kimai_timeSheet' doesn't exist
`

**To Reproduce**
1. mysqldump -u _<username>_ -p > kimai_backup20190421.sql
2. mysql -u root -p kimai < kimai_backup20190421.sql
2. [Install Kimai v2](https://www.kimai.org/documentation/installation.html)
3. [Upgrade to Kimai v2](https://www.kimai.org/documentation/migration-v1.html)

bin/console kimai:import-v1 "mysql://_user_:_password_@127.0.0.1:3306/kimai?charset=utf8" "kimai_" "_password_" "US" "USD"

Produces the error.

**Additional context**
 - Kimai v2_0.8.1
 - PHP version 7.3.4

**Comment by kevinpapst** [comment]
How are the tables in your Kimai v1 database called?

**Comment by sdo992** [comment]
MariaDB [kimai] > SHOW TABLES;

- kimai_activities
- kimai_configuration
- kimai_customers
- kimai_expenses
- kimai_fixedrates
- kimai_globalroles
- kimai_groups
- kimai_groups_activities
- kimai_groups_customers
- kimai_groups_projects
- kimai_groups_users
- kimai_membershiproles
- kimai_preferences
- kimai_projects
- kimai_projects_activities
- kimai_rates
- kimai_statuses
- kimai_users

**Comment by sdo992** [comment]
Okay, I was able to get it to work by manually renaming all tables that had compound words:

`MariaDB [kimai]: RENAME TABLE kimai_timesheet TO kimai_timeSheet;`

I did that for fixedrates, globalroles, and membershiproles.

**Comment by kevinpapst** [comment]
Thats weird. Maybe a collation setting in your database. Kimai 1 created them like this:
https://github.com/kimai/kimai/blob/master/installer/install.php#L201
Did the import work properly or did you find further problems?

**Comment by sdo992** [comment]
So far, it seems to have imported correctly. 

I made this backup database from my Windows 10 partition which was using xampp. I wonder if that had anything to do with it?

**Comment by kevinpapst** [comment]
Maybe, I haven't used windows in a very long time ...
If I would have to guess, I'd say its related to the database collation or maybe the tool used for the dump. 
But good to read that it works now and thanks for the feedback!
