### ISSUE TITLE
Multiple Work Orders under Project for a Customer

### ISSUE THREAD

**Issue by sdo992** [kevinpapst/kimai2#720]
I've just got Kimaiv2 up and running and so far, it's not bad; however, I'm running into a problem tracking business activities.

For example:

I am a sub-contractor who gets work from a contractor. The contractor has several different customers.

My customer is: **Business 1**
I get a client from Business 1 named "**John Smith**" (I name my Project "Smith, John").
My first work order is 300999 and, for Tasks, I can:

- email
- phone call
- community/business meeting
- etc.

For work order 300999, I can track my hours and then bill once I reached my 5,10,20 or more hours that I was given to work with this client.

One month later, I get the same client again, this time the work order number is 301888, and I have the same tasks and maybe more or less hours.

I would like to be able to have multiple work orders for projects (Smith, John) whom I receive from my customer (Business 1). Right now, all information would be entered into a single work order (called 'Order Number' in Kimai) under a Project.

I could recreate my entire database, and rename my projects as my customers, but, they are not my actual customers, they are assigned to me by my real customer, Business 1. Which means that I would have to continue to manually create an invoice, like I do with Kimai v1.

**Comment by kevinpapst** [comment]
Do you need to track the order number or is it just there for the invoice?

**Comment by kevinpapst** [comment]
But then: why don't you create a new project for the next order? You hide the first "John Smith" after creating the invoice and open a new "John Smith" project when getting the next contract (maybe giving it a more descriptive name to be able to differentiate between them)?
You can assign the new order number to that new project and don't lose the ability to later on see what you worked on this specific project.

**Comment by sdo992** [comment]
@kevinpapst 

That's what I just spent the better part of 5 hours doing. I need to track and bill the order. The work flow is:

The State of Alaska sends my customer dozens of jobs. My customer (Business 1), then sends me and several other people certain jobs with work order numbers attached. The work orders represent 5,10,15, or 20 hours of work with a client. After each work order is complete, I bill my customer who then bills the State. Many times, I have to work with the client again, under a new work order, but my customers is still Business 1.

Another customer of mine is much easier: They hire me to do a job and I finish and bill it. Let's call them Business 2. Then, I have several other businesses I hope to be doing work for, and each will have their own work order and some might have me act as a sub-contractor. So, would like to be able to see all my bills under one customer, Business 1 or Business 2 or Business 3, with each Project and work order number. Right now, there's no way for me to get all 30 clients I have for Business 1 and all associated work orders for my clients through them all at one time.

With all that being said, I'm liking v2 much more than v1. In v1, I was naming Projects like this:

300888 John Smith
311999 John Smith

But they are the same person with 2 separate projects.

In v2, I just converted every project into a customer, and have no way of telling which one is attached to which Business (my actual customer). So, I'm using an inelegant solution of just adding BUSINESS 1 to every customer that I get through that business. It's ugly, but it works; then, I will just need to create an invoice manually.

**Comment by kevinpapst** [comment]
I think you could create the invoice via the exporter, as you don't have to select a dedicated customer there. I plan to support export templates, so this could be a way in the future.

Or you think about using projects for John Smith instead of the Customer level.
From my understanding John Smith is a project for your customer Business 1 and not your customer.

If you have a good technical idea/proposal on how to "fix" that please let me know. 
You think about a general solution, as Kimai needs to be a multi-purpose time-tracker and the current structure is the one that fits most companies and freelancers out there.

There is a PR waiting, which will introduce "tags" - maybe that could be a solution to your problem?

**Comment by kevinpapst** [comment]
In master a new feature arrived: tagging of timesheets. 
Do you think that could solve your problem? 
See it as a completely free level of grouping your timesheets, which can also be used to filter invoice and export data.

**Comment by kevinpapst** [comment]
I gave it another thought and think that tags can fix your problem.
See a tag as "work order" and don't use the "order number" field. 
In the invoice, simply replace the order number by your work number (either manually or create a new invoice template, which uses the tag(s) from the query as work order.

I will close this ticket, but you can answer if you need help or think I am completely off-track here.
