### ISSUE TITLE
403 error after installation

### ISSUE THREAD

**Issue by 3ruce** [kevinpapst/kimai2#725]
**Describe the bug**
After installation, the browser returns a 403 and the apache log reads as follows

```
[Thu Apr 25 14:40:49.240945 2019] [autoindex:error] [pid 25384] [client 10.114.60.123:41688] AH01276: Cannot Cannot serve directory /home/admin/web/public_html/: No matching DirectoryIndex (index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
```

**To Reproduce**
I suspect this is an Apache config option based on googling the error. This is the extract from the apache config file for the VirtualHost

```
    <Directory /home/admin/web/public_html>
        AllowOverride All
        Options +Includes -Indexes +ExecCGI
        php_admin_value open_basedir /home/admin/web/public_html:/home/admin/tmp
        php_admin_value upload_tmp_dir /home/admin/tmp
        php_admin_value session.save_path /home/admin/tmp
    </Directory>

```

**Logfile**
```
[Thu Apr 25 14:40:49.240945 2019] [autoindex:error] [pid 25384] [client 10.114.60.123:41688] AH01276: Cannot Cannot serve directory /home/admin/web/public_html/: No matching DirectoryIndex (index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
```

**Additional context**
 - Kimai version - latest from git clone
 - PHP version - 7.1

**Comment by kevinpapst** [comment]
This is not a Kimai problem, but here you go:
https://www.kimai.org/documentation/installation.html
https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by 3ruce** [comment]
:+1: any pointers though?

**Comment by kevinpapst** [comment]
Did you read the links? 
Yes, pretty sure your document root is wrong. But please: ask someone else how to configure your Webserver. Definitely not the right place here.

**Comment by 3ruce** [comment]
I love it... I'm running 18 other PHP apps, all are configured via VestaCP and work fine... I've tweaked the odd `open_basedir` value but otherwise it's smooth sailing :thinking:

**Comment by kevinpapst** [comment]
the index.php is in public/

**Comment by 3ruce** [comment]
Ok, so the login/home url is `mywebsite.com/public/index.php`?

Having logged in to that url, this is the next error... which, according to [this issue](https://github.com/symfony/symfony/issues/25469) is a php version problem... 

`php -v` returns `PHP 7.1.28-1+0~20190412071216.17+stretch~1.gbpbe9b36` do you think that might be the problem?

```
[Thu Apr 25 17:04:23.610195 2019] [:error] [pid 7437] [client 10.114.60.123:55558] PHP Fatal error:  Uncaught TypeError: Return value of Symfony\\Component\\Dotenv\\Dotenv::populate() must be an instance of Symfony\\Component\\Dotenv\\void, none returned in /home/admin/web/public_html/vendor/symfony/dotenv/Dotenv.php:96\nStack trace:\n#0 /home/admin/web/public_html/vendor/symfony/dotenv/Dotenv.php(57): Symfony\\Component\\Dotenv\\Dotenv->populate(Array)\n#1 /home/admin/web/public_html/public/index.php(15): Symfony\\Component\\Dotenv\\Dotenv->load('/home/admin/web...')\n#2 {main}\n  thrown in /home/admin/web/public_html/vendor/symfony/dotenv/Dotenv.php on line 96
```

**Comment by 3ruce** [comment]
>Having logged in to that url
I mean having **loaded** that url...

**Comment by kevinpapst** [comment]
You should point your DocumentRoot to public, which is everything written in the documentation.
> If you want to use a fully-featured web server (like Nginx or Apache) to run Kimai, configure it to point its DocumentRoot at the public/ directory. For more details, see https://symfony.com/doc/current/setup/web_server_configuration.html

https://www.kimai.org/documentation/faq.html#dotenvpopulate-must-be-an-instance-of-symfonycomponentdotenvvoid
