### ISSUE TITLE
Possible to translate login page

### ISSUE THREAD

**Issue by tellustheguru** [kevinpapst/kimai2#736]
Make it possible to translate the login page.

For example:

English -> Swedish
-------------------
Login -> Logga in
Username -> Användarnamn
Password -> Lösenord
Remember me -> Kom ihåg mig
I forgot my password -> Glömt lösenordet

<img width="595" alt="bild" src="https://user-images.githubusercontent.com/47452862/56895581-d352e600-6a89-11e9-93d7-79d6995148d5.png">

English -> Swedish
-------------------
Reset your password  -> Nollställ ditt lösenord
Back to login  -> Tillbaka till inloggningssidan

<img width="545" alt="bild" src="https://user-images.githubusercontent.com/47452862/56895705-2462da00-6a8a-11e9-9ad4-fa0faa324be8.png">

**Comment by kevinpapst** [comment]
It is translatable. But this is another bundle:
https://github.com/kevinpapst/AdminLTEBundle

You are right: that could be documented. Until then, here are the files:
https://github.com/kevinpapst/AdminLTEBundle/tree/master/Resources/translations

**Comment by kevinpapst** [comment]
Now available in master
