### ISSUE TITLE
Finally got this installed!

### ISSUE THREAD

**Issue by 3ruce** [kevinpapst/kimai2#743]
**Describe the bug**
* VestaCP has a different user from `www-data`, typically it's `admin`
* You need to let `bin/console doctrine:database:create` make the database, as opposed to using PHPMyAdmin or whatever...
* That root folder structure is very unique!
* The log errors typically talk about out of memory errors as opposed to permissions
* There was a very weird error 500 that I couldn't track the source of down but it wasn't the standard vesta error page and neither was it from HA Proxy... Symphony maybe?!?
* Turning on the debug mode via `APP_ENV=debug` helped a lot!

Anyway, now it's installed!

**Comment by kevinpapst** [comment]
Thanks for your feedback 👍 I will link this issue on the "Installation" page for the VestaCP users.
I will close it nevertheless after adjusting the docu, as there seems to be no question for now.

**Comment by 3ruce** [comment]
No problem, I think it would be worth adding that this is an a-typical install with the requirements to install composer and create the DB in a non-standard way...

**Comment by kevinpapst** [comment]
In order to make it easier for the next folks, could you pin-point exactly what was missing in the installation docu: https://www.kimai.org/documentation/installation.html ?

**Comment by 3ruce** [comment]
Over and above what I wrote, I think all 3 of these PHP apps use symfony, at least a search for `symfony` returns results in all 3 repositories... Likewise, I don't think much of this will come as a surprise to you and I appreciate that Kimai2 is quite new...

## LimeSurvey
* https://github.com/LimeSurvey/LimeSurvey
* https://manual.limesurvey.org/Installation_-_LimeSurvey_CE#General

## Mautic
* https://github.com/mautic/mautic
* https://www.mautic.org/getting-started/

## EspoCRM
* https://github.com/espocrm/espocrm
* https://www.espocrm.com/documentation/administration/installation/

All of these apps basically work along the lines of

1. Extract the files in your (normal!) web root folder
2. Run some chmod stuff, typically `chmod -R 777 /coolfolder1` and  `chmod -R 777 /veryimportantfolder2`  etc.
3. Create your MySQL db and copy the user, pass and db name
4. Fire up a browser at `https://mycoolnewapp.onmydomain.com` or sometimes `https://mycoolnewapp.onmydomain.com/install` etc.
5. Even if there's no web installer and I need to edit a config file, I typically set some simple settings and bingo...

Yes, your instructions work but at a minimum, it would be good to say something along the lines of
* There us no web installer
* You'll need to use composer to compile(?) stuff
* You must let `bin/console doctrine:database:create` create your db etc. etc. 
* At this stage of Kimai2, everything is quite different from most **typical** php apps, we're still not at 1.0, we're working on a web installer etc. etc.

**Comment by kevinpapst** [comment]
Hey, yes nothing new to me ;-) Problem ist that it takes literally 2 minutes to install Kimai if you are used to such kind of software. 
I gave my best to document it, but I guess it needs someone who actually had troubles installing Kimai and found ways to fix them.

So if anyone wants to contribute to the documentation, here is the source file:
https://github.com/kimai/www.kimai.org/blob/master/_documentation/installation.md
Send me a PR and I will gladly merge it!

Besides that, I added two sentences about VestaCP and a backlink to this topic.

**Comment by 3ruce** [comment]
Thanks Kevin... one thought did cross my mind... you might want to make it clear (or clearer?) at the top that Kimai2 doesn't have a web based installer so people need to install using composer and use composer to make their DB... right now, the FTP option is also quite tricky for the non ssh/shared hosting folks... but then I guess we both already knew this?

Also, is it worth splitting the installation instructions across a couple of pages?

Finally, are you planning on offering Kimai2 as a SaaS product with a per seat license as many projects do, or are you sticking to the open source only route?

**Comment by kevinpapst** [comment]
Well well .... you are right. 
I should add a warning on top, so this question (web-installer) stops popping up ;-)
FTP is a pain - that's why I don't support it officially.

Yes, a SaaS product is in planning, with multiple plans (free as well). Needs a couple of weeks, I plan to go live with 1.0. But Kimai is and will stay open-source. No doubt about that last point whatsoever!

**Comment by 3ruce** [comment]
>I should add a warning on top, so this question (web-installer) stops popping up ;-)
>FTP is a pain - that's why I don't support it officially.
Yeah... I'm guessing the web installer is going to be on the roadmap in some shape or form?

>Yes, a SaaS product is in planning, with multiple plans (free as well).
Yeah, I can see this working well, Mautic, LimeSurvey, Zulip to name a few all work with this model and I think it's great!
