### ISSUE TITLE
Error 500 when exporting to csv, ods, pdf and excel

### ISSUE THREAD

**Issue by 3ruce** [kevinpapst/kimai2#744]
**Describe the bug**
When trying to export from this page `kimai.com/en/export/` and picking csv, ods, pdf and excel as per this screenshot https://i.imgur.com/GJDHJGM.png, there is an error 500...

Do I need to install anything extra for this to work? The print option works fine...

**To Reproduce**
1. Go to this page `kimai.com/en/export/` to export data
2. Select your criteria
3. Picking any of these 4 formats csv, ods, pdf and excel as per this screenshot https://i.imgur.com/GJDHJGM.png, 
4. There is an error 500...

**Logfile**
```
[2019-04-30 16:21:50] request.CRITICAL: Uncaught PHP Exception PhpOffice\PhpSpreadsheet\Writer\Exception: "Could not open  for writing." at /home/admin/web/public_html/kimai2/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php line 218 {"exception":"[object] (PhpOffice\\PhpSpreadsheet\\Writer\\Exception(code: 0): Could not open  for writing. at /home/admin/web/kimai.fourgroups.com/public_html/kimai2/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:218)"} []
```
Here's the full `prod.log` 
[prod.log](https://github.com/kevinpapst/kimai2/files/3131672/prod.log)

**Additional context**
 - Kimai version - latest from git
 - PHP version - 7.3 on Debian 9

**Comment by kevinpapst** [comment]
You PHP is strangely configured:
```[2019-04-30 16:19:21] php.WARNING: Warning: tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/admin/web/public_html:/home/admin/tmp) {"exception":"[object] (ErrorException(code: 0): Warning: tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/admin/web/public_html:/home/admin/tmp) at /home/admin/web/public_html/kimai2/src/Export/Renderer/OdsRenderer.php:41)"} []```

The function [tempnam](https://www.php.net/manual/en/function.tempnam.php) is trying to write a temporary file at the location of [sys_get_temp_dir](https://www.php.net/manual/en/function.sys-get-temp-dir.php).

Thats the code part in Kimai: https://github.com/kevinpapst/kimai2/blob/master/src/Export/Renderer/XlsxRenderer.php#L41

You have to configure your PHP / VirtualHost so this function returns the allowed tmp path `/home/admin/tmp` which is mentioned in the error message.

**Comment by kevinpapst** [comment]
This comment is helpful: https://www.php.net/manual/en/function.sys-get-temp-dir.php#117168
Or you reconfigure the open_basedir to allow the global `/tmp` directory which is likely the better idea, as this directory is guaranteed to be cleaned up by the OS on restarts.

**Comment by 3ruce** [comment]
Ok, perfect, adding :/tmp to `open_basedir` fixed that... yeah, it's another VestaCP thing!
