### ISSUE TITLE
Does Kimai2 send emails at the moment?

### ISSUE THREAD

**Issue by 3ruce** [kevinpapst/kimai2#745]
I noticed the following in the `.env` file but it doesn't look like Kimai2 sends out any email at the moment, unless I've missed something?

```
###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###

```

**Comment by 3ruce** [comment]
I just spotted this comment https://github.com/kevinpapst/kimai2/issues/226#issuecomment-406878128

I'm guessing forgot password is the only thing right now?

**Comment by kevinpapst** [comment]
Yep, only registration and forgot password for now:
https://www.kimai.org/documentation/emails.html
