### ISSUE TITLE
Action menu instead of icons

### ISSUE THREAD

**Issue by bjoerne2** [kevinpapst/kimai2#747]
I wasn't always able to understand the icon buttons in the action column of the tables. Eye = Show, Pencil = Edit and Trash = Delete is always easy, but everything else is difficult in my opinion.

I was in the same situation in another project and decided to use a drop down menu instead of the buttons. In kimai that would look like this:

![Bildschirmfoto 2019-05-01 um 23 11 49](https://user-images.githubusercontent.com/1454836/57043096-e53db000-6c66-11e9-8fe0-f45a44fcf3a0.png)

That gives you the opportunity to add more actions without being afraid of space and a fitting icon. Just use text in the menu.

If this idea matches the UI strategy of kimai I'd like to provide a PR.

**Comment by kevinpapst** [comment]
What a pitty, you are about a day to late: https://github.com/kevinpapst/kimai2/pull/746

But if you are willing to contribute some of your time to improve Kimai, please check the PR #746 and let me know what you think and would improve.

**Comment by kevinpapst** [comment]
Fixed by #746 and now available in master
