### ISSUE TITLE
Login not working on Prod (but in Dev)

### ISSUE THREAD

**Issue by bhelm** [kevinpapst/kimai2#749]
**Describe the bug**
The Login is not working when in prod mode, but works fine in dev mode. Cant see any errors on page or in the webserver/php logs.

I think this can be related: the Password reset page is also refusing to work when in prod mode but works in dev. In prod, it says "The CSRF token is invalid. Please try to resubmit the form." after submitting a new password. No matter how often i reload the Page. This also happens in both ff and Vivaldi.

If this is related to my Nginx setup, i cant see why it is working in dev mode.

Thank you.

**Screenshots**
Screenshot of failed login here: https://pasti.ng/a0rmvkrAycd

**Desktop/Smartphone**
Tested on Vivaldi 2.4.1488.35 (Crome based) and Firefox 66.0.3

**Additional context**
- PHP-FPM 7.2
- Nginx
- Kimai 0.9 from Git

**Comment by kevinpapst** [comment]
Please check the permissions for var/cache/prod/ (different from var/cache/dev/).
If that doesn't help, delete your cookies.
If that doesn't help, flush your cache manually by issuing `rm -rf var/cache/*`.

And please check `var/log/prod.log` (kimai directory)?

**Comment by kevinpapst** [comment]
Still an issue? Otherwise I will close this issue

**Comment by kevinpapst** [comment]
Thats why I sometimes hate doing open source work. 
Using free software for a business and then wasting the maintainers time by not even responding.
