### ISSUE TITLE
Custom data for external references

### ISSUE THREAD

**Issue by schmunk42** [kevinpapst/kimai2#760]
**Is your feature request related to a problem? Please describe.**
My use-case is to track IDs of external systems to identify eg. projects, customers, etc...

**Describe the solution you'd like**
I'd like to have a possiblity to add custom data to a record, eg. as JSON.

**Describe alternatives you've considered**
Saving it in the comments :speak_no_evil: 

**Additional context**
Continued from https://github.com/kevinpapst/kimai2/issues/683#issuecomment-489221700

**Comment by kevinpapst** [comment]
Interested in contributing a PR?

**Comment by schmunk42** [comment]
Can't really promise it, since I have no experience with the underlying software.

But some technical questions, about how to proceed:
- generate migration (db-changes) to add a `custom_data` field
- create a `CustomDataTrait`
- update forms, API

Would this be the way to go?

**Comment by kevinpapst** [comment]
Yes + unit / system tests. 
I can help with all of that. If you want to provide a draft, we can work together on the branch. 
If you start with a draft for the Trait and the entities I can jump in and we work together on the branch. The API is a bit tricky if you don't know the libs. 
The migration is fairly easy, you can use the code from last one where I added the color field to the customer/projects/activities entities.

**Comment by kevinpapst** [comment]
ping @schmunk42 ready for testing #871

**Comment by schmunk42** [comment]
Thank you for the ping. I am quite busy atm, but will report, when I find time to test this.
Was looking good on first sight.
