### ISSUE TITLE
Docker refactor

### ISSUE THREAD

**Issue by tobybatch** [kevinpapst/kimai2#763]
@kevinpapst I've had some spare time at work this week and have refactored the external docker repo to build against tags.  Also we now correctly export thr DATABASE_URL so the console works in the dev env.

Consequently the latest dev image will be stored here: https://github.com/tobybatch/kimai2/blob/master/Dockerfile

I hope that's OK.

**Comment by kevinpapst** [comment]
Thanks for the update.
Could you please explain the consequences for the Dockerfile in this repo - is it outdated?

Oh and I see this line: https://github.com/tobybatch/kimai2/blob/master/Dockerfile#L16
If you find stuff like that, it would be nice if you report them - that's looks like a bug.

**Comment by tobybatch** [comment]
The ownership of that file is a consequence of the user de-escaltion in the docker.  The phpunit is run by the www-data user.  I don't think it's actually a bug for you to worry about as you will run your tests as the same user that installed the stack.

And yes, the Dockerfile in the core repo is, or will, be out of step with changes in the docker reepo.  I don't expect these docker files to change very often.  Perhaps I can just ping you when they do?

**Comment by tobybatch** [comment]
BTW Any help on where to build the bridge for this https://github.com/kevinpapst/kimai2/issues/193 would be appreciated.

The reason I've been a bit slack on the docker files is that my company needs LDAP auth in it's time keeping solution so I can't support the container in work hours if we aren't using it.  If I can help develop that bridge then I'll be able to justify time on issues.

**Comment by kevinpapst** [comment]
I will have a look nevertheless, as nothing should ever write outside var/cache/.

And I will try to setup and LDAP and then we can discuss further in the other topic.

Yes please ping me on changes. But I still wonder what should happen to the Dockerfile in this repo? You want to manage the dev image also exclusively in your repo?
Shall I simply copy & paste your changes over here? And is there a benefit from using the Kimai base image of the Debian image used here?

**Comment by tobybatch** [comment]
The bug only manifests when tests are run.

The creation of the base image was in response to one of the bugs in my repo where it was pointed out that I was basing the prod image on the dev image.  Basically I was relying on the dev image to set up the LAMP requirements.  This way I do the common set up in kimai_base.  That will only change when/if  I roll up a php version or os version.

I think that if you just pick up the dev docker image and drop that into the base repo for now.  We can see if there is a better way of doing this at a later date.

**Comment by tobybatch** [comment]
@kevinpapst I was messing around with an idea for a plugin and I created this little LDAP docker set up.  I thought you might like it if you where testing a LDAP integration with the kimai user sub system.

https://github.com/tobybatch/kimai-test-ldap

You can just ```docker-compose up``` and you'll have a working ldap user auth work against.

**Comment by kevinpapst** [comment]
@tobybatch my local OpenLDAP installation is a mess, but now running after several wasted hours ;-) so I could start working on LDAP support finally - see #815
I could use some help testing, as I have only that demo data from your repository. Which is great btw, I wouldn't be posting this without that!

**Comment by tobybatch** [comment]
I can totally help with this. It's school half term in the UK and I'm away right now. I'll be back Thursday. 

I can pull your branch and test it against our company LDAP and i can generate you more dummy data in a new docker. What else would help?

**Comment by kevinpapst** [comment]
The last time I worked with LDAP is probably 10 years ago and my knowledge about it was never great... so some input about the general workflow would be great. 
Or to be more clear: how do other apps handle LDAP support? I posted the open questions which came to my mind into #815 .
Maybe you could have a look and answer them?

**Comment by bsumners** [comment]
Was the docker image refactored? Or did I miss it?

**Comment by kevinpapst** [comment]
thanks @bsumners good catch!
See the PR #840
