### ISSUE TITLE
Disable manual To date and duration entry option in timer

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#764]
**Is your feature request related to a problem? Please describe.**
Ability to disable the end date or manual entry of time. 

**Describe the solution you'd like**
We allow only one active timer to be active at the same time and do not want the users to fill in random time entries into the future or to manually enter time by starting the timer. Is there any way of disabling manual entry of end date duration in timesheet entry.

A way of identifying manual timesheet entries are being made can also be a good functionality 

**Describe alternatives you've considered**
None available as of now. 

**Additional context**

**Comment by kevinpapst** [comment]
Not sure if I understand that correctly, so let me ask:
How should your users track their time? Only with start + stop button?

**Comment by rarvin** [comment]
Yes they should track time with the start and stop button alone. Entering the start datetime and end datetime should be disabled. No manual change of tracking time should be allowed other than maybe by the administrator, if its possible can really help, since we dont want our users to manipulate records manually.

**Comment by rarvin** [comment]
Thank you for adding this as a feature request.

**Comment by rarvin** [comment]
![image](https://user-images.githubusercontent.com/50443902/57649991-5413f500-75e7-11e9-99b6-918b02ae7c03.png)

Default timetracking mode to be system controlled with no control in the hands of the users.

**Comment by kevinpapst** [comment]
@rarvin Can you help testing? See #812

**Comment by rarvin** [comment]
I have tested this and and updated the comments (all looks good) against
the merge request.
