### ISSUE TITLE
Grouping users in teams

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#765]
**Is your feature request related to a problem? Please describe.**
We would like to group users and create reports in the dashboard by the group the user is assigned to. Currently under the admin user it shows the summed up summary of all users within the enter kimai platform, what would be nice is an option to show a summary by also the various groups (like department, team, agency or internal or all) that are present on the platform. This filtering and summation summary can really help.

**Describe the solution you'd like**
Summarised view by various groups in the dashboard as well as in the filtering pages that are already present. Currently in the dashboard a summarised view of all users on the platform are reported. Having an option to summarise and show by department, team or agency or internal can help. 
Similarly the filter option allows to filter by user, customer, project, activity. Having an option to filter by various teams that are present can really help. If nothing is chosen it would be all users on the platform. In addition there must be an option to assign a user to multiple teams. For example we have users who are company resources who work from office and some who work from home, in this case they are to be part of the company team and also have to be part of the work from home team or office worker team. Summarised view of the time for such team users can really help. I think currently you have the pervlige mapping similar to this for a user where is a user can be a team lead a user as well as admin etc all together and individually. The idea is similar where this is for teams or groups.

**Describe alternatives you've considered**
None as of now.

**Additional context**
None

**Comment by kevinpapst** [comment]
I started to work on the teams and permissions. Can you help testing?
See #996 and please leave your feedback in there, so we have everything in one place.

**Comment by rarvin** [comment]
If one is assigned as a team lead for a team then he should be able to see
only the records for the users associated with that specific team, like in
timesheets, invoices, exports etc. This would be a nice add on.


-- 
Regards,
Aravind

**Comment by kevinpapst** [comment]
Teams are now available in master. Please write new issues for further features. 
Your story was good written, but a bit too much for one go ;-)
