### ISSUE TITLE
Include option of tags field to link various timesheet entries together and use them for filtering data

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#768]
**Is your feature request related to a problem? Please describe.**
We have defined customer project and respective activities, but our work involves working on multiple linked work related to a particular article. Currently there is no way of tracking all activities related to the article under any fields and hence we use the description field for it. Would it be possible for you to add a new filed called as tags or something similar which can be used for linking all of the project activities that we are tracking using kimai, so that we would know that these are work items related to that task.

**Describe the solution you'd like**
A user creates a timesheet entry for a customer, project and activity and starts it. Now the users tries to assign this task against a tag, if its one of the existing tags already added or used before the user can choose one of them, if not the user manually keys in the new tag. 

This tag to be available in the filtering view so that tasks by tag can be filtered and viewed, summarised view of the total time taken for the task (tagged entries can also really help. 

**Describe alternatives you've considered**
Currently we are using the description filed to enter the value, this is done manually and is prone to user error or the user misses to enter this. Filtering by this value is not possible. Reports of any sort is not possible and all of this done by exporting the data in a excel and then filtering by description which is difficult to use.

**Additional context**

**Comment by kevinpapst** [comment]
Please try to find existing topics first before you post one request after another. 
I really like contributions and appreciate and input, but don't my life harder than necessary.
Closing as this duplicates #604
