### ISSUE TITLE
open kimai in subfolder

### ISSUE THREAD

**Issue by MajidDehnamaki** [kevinpapst/kimai2#773]
hi friends.
I install kimai on windows server with apache in a subfolder.
I config apache like this:

`
<VirtualHost *:80>
	DocumentRoot www/kimai/public
	<Directory www/kimai/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>
	ProxyPreserveHost On
	ProxyRequests Off
	ServerName kimai.karans
	ProxyPass / http://domain:8090/
	ProxyPassReverse / http://domain:8090/
	RewriteEngine On
	RewriteRule ^/$ /kimai [R]
</VirtualHost>`
when i open my domain,i just see directory of file.
what can i do?

**Comment by kevinpapst** [comment]
Please ask somewhere else (e.g. server fault, stackoverflow) how to configure your webserver.

All I can say: Kimai is a Symfony 4 application and thus the entry point is public/index.php.
Maybe this helps: 
https://symfony.com/doc/current/setup/web_server_configuration.html
