### ISSUE TITLE
adding a new timesheet entry is broken in current master

### ISSUE THREAD

**Issue by magiruuvelvet** [kevinpapst/kimai2#778]
**Describe the bug**

Adding new timesheet entries is completely broken in current master. I updated to commit `5c227888f20ca81352ba1e44d724b0932ebed3cb` and the activity select box isn't updated at all now. The project drop-down always shows everything.

Editing an existing timesheet entries fills the activity drop-down with the correct activities.

The browser console remains silent, so I guess there is never code executed at all. I tried in a clean browser with no extensions installed to be sure ad-blockers are not breaking the application.

**Additional context**

 - Kimai version: `5c227888f20ca81352ba1e44d724b0932ebed3cb`
 - PHP version: `7.3.5`

EDIT: I guess this works in Debian and is just broken on Arch? Like the other issue I opened where all activities were shown from all customers and projects.

**Comment by kevinpapst** [comment]
Can you let me know which browser are you using? I updated the complete Javascript to EcmaScript 6 and I am not sure about the browser compatibility. But if that would be a browser issue, I would expect some console logs. 

Which database are you using on Arch?

I'd really like to find out more about these issues. I mean Arch is a rolling release, always shipping newest software versions, right? So its possible that this is a server issue and not Kimai, but I wonder if there is anything inside the codebase that could be improved, to get a better compatibility.

Are you using a native Arch? I could try to find a Docker image with Arch to see if that has the same issues. Bu then: these images are probably made for PHP usage and don't have these bugs ... 
Any idea how we can work together to find out what's going on there?

**Comment by magiruuvelvet** [comment]
I tried Waterfox (which is based on Firefox) as well as a Chromium based browser with the latest version of the engine; ECMA 6 is well supported. There are actually no logs in the browser console, nothing happens. Could this be an issue with the event listeners not being registered correctly?

About the server stuff: I use vanilla Arch Linux and everything is the latest version.

 - MariaDB 10.3.14 for the database
 - PHP 7.3.5
 - PHP-FPM via Caddy web server to serve the pages

Arch Linux ships official docker images `archlinux/base` where you could probably install php to test if you can reproduce the issue. I have plenty of PHP extensions installed, since this is my local workstation and not a production server optimized to run a single PHP application. Could this be causing troubles? I don't use PHP myself that much, but I don't have issues with other PHP software running on my system with this overload of extensions installed. They all seem to be working fine without issues.

I still couldn't figure out the root cause, but my guess is that the problem is happening on the PHP side with some checks failing or causing the wrong results. I even tried an older PHP version (7.2), but I got the same problem with that too. Maybe an extension is causing trouble in the code?

**Comment by kevinpapst** [comment]
We checked the Kimai logs at var/log/prod/ already the last time without success, did we?

The select boxes are populated initially during page load (customer and projects in create timesheet) and after changing them via API, so maybe you have a server error? That would show up in the network tab instead of the console.

Is there anything happening in the network tab when you change e.g. the customer? If there is no request going out, then there could be a problem with the JS

**Comment by kevinpapst** [comment]
Hm, I think you are right, there is something broken... I'll have a look. 
Maybe it was too late yesterday night^^

**Comment by kevinpapst** [comment]
Fixed with #780

**Comment by magiruuvelvet** [comment]
the select boxes are working again, except that everything is showing up, but that's another issue

**Comment by kevinpapst** [comment]
Grmpf, yeah stupid problem. 
If there would be a docker image which I could just boot and see the bug I would debug it.
Is there an open bug for that problem or did we close it? Probably someone else shows up with the same problem who could help debugging.

And thanks for your feedback!
