### ISSUE TITLE
Add daily, weekly statistics data to the users statistics page

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#785]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/50443902/57650365-427f1d00-75e8-11e9-9629-9cd5d635d8e9.png)

Adding weekly and daily statistics to the same user statistics page. 

**Describe the solution you'd like**

We would like to audit our users as well as allow the users to see if they have met the daily work hours as well as weekly and monthy quota set for the users. Having a view of the daily monthly and weekly statistics can really help. Maybe a configurable filter option. If this is too complicated can you atleast add the weekly and daily statics into the user image box.

**Describe alternatives you've considered**
None available, these stats can only be seen by the user from their dashboard, but adding them in the admin statitics page can help the admin user his prevlige and view these stats via the statistics page.

**Additional context**

**Comment by rarvin** [comment]
Also a way of accessing the user daily stats (by day - showing all records and the sum for each day) from admin user page can also help.

**Comment by kevinpapst** [comment]
Please have a look at https://github.com/kevinpapst/kimai2/pull/1805

**Comment by kevinpapst** [comment]
Available in the new report screens.
Please open new issues for new report types
