### ISSUE TITLE
Colors for tags

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#786]
**Is your feature request related to a problem? Please describe.**
Currently tagging is possible but all tags are shown with the same colour. Having an option to configure the colour for specific tags can really help.

**Describe the solution you'd like**
By default for any newly created tag the colour could be a default colour, but if the user wishes to reuse some tag and having them all appear with a said colour could help then if via the tag administration screen colours could be set for specific tags then it could really help.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by jojoemade** [comment]
@kevinpapst I've tried to do this but got stuck on failing unit tests. Would you be willing to review any way? :)

**Comment by kevinpapst** [comment]
Sure, open up a PR
