### ISSUE TITLE
Older Kimai2 version compatible with PHP 7.0?

### ISSUE THREAD

**Issue by ivomarino** [kevinpapst/kimai2#790]
hi there, first of all thanks for this great tool. I was just wondering which is the latest available version which is compatible with PHP 7.0, some hoster don't yet provide 7.1 or 7.2, thanks in advance for any feedback.

**Comment by 3ruce** [comment]
I think you need at least 7.2, if not 7.3

**Comment by ivomarino** [comment]
thanks @3ruce, but for sure there must be an older kimai2 version which works with `7.0` I think

**Comment by kevinpapst** [comment]
Nope, Kimai 2 was never compatible with 7.0.
It is based on the framework Symfony 4, which always required 7.1.3. 
And with the 0.9 release I increased the minimum requirement to 7.2 for future compatibility.

If any hoster out there still does only support 7.0 I would recommend to immediately leave them. They are a risk to their customers and themselves:
https://www.php.net/supported-versions.php

**Comment by ivomarino** [comment]
ok, thanks for the infos @kevinpapst, all fine then;)
