### ISSUE TITLE
Template for Nginx and Apache

### ISSUE THREAD

**Issue by duven87** [kevinpapst/kimai2#792]
Hallo Kevin,
I'm trying since 2 days to install kimai2 and always I have the same result on my nginx server .
404, 502 and now File not found . I couldnt do more. 
Can you or someone please provide a Template of Nginx and maybe Apache for the rest of users?

Thanks 
Grüße

I put mine:

```
server {
    listen 80;
  
    root /var/www/html/kimai2/public;
    server_name kimai2web.de;
    return 301 https://kimai2web.de$request_uri;
}

server {
      listen 443 ssl; 
**  #  listen [::]:443 ssl ipv6only=on; 
      server_name kimai2web.de;
      ssl_certificate /etc/letsencrypt/live/kimai2web.de/fullchain.pem; 
      ssl_certificate_key /etc/letsencrypt/live/kimai2web.de/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf; 
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
   
 location / {
        try_files $uri /index.php$is_args$args;
}

 location ~ ^/index\.php(/|$) { 
   fastcgi_pass unix:/run/php/php7.3-fpm.sock;
   fastcgi_split_path_info ^(.+\.php)(/.*)$;
   include fastcgi_params;
  
  auth_basic "Private";
  auth_basic_user_file /etc/nginx/.htpasswd;

  fastcgi_param APP_ENV prod;
 *# fastcgi_param APP_SECRET <app-secret-id>;
   fastcgi_param DATABASE_URL "mysql://my_db_user:my_db_pass@localhost:3306/kimai2";
   fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
   fastcgi_param DOCUMENT_ROOT $realpath_root;

    internal;
    }

location ~ \.php$ {
    return 404; 
}

access_log /var/log/nginx/kimai-access.log;
error_log /var/log/nginx/kimai-error.log;

} 

```

**Comment by infeeeee** [comment]
Here is my nginx config, it works flawlessly: 

```
server {
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate     /etc/ssl/certs/cert.crt;
    ssl_certificate_key /etc/ssl/private/key.key;
    server_name kimai.example.net;
    set $root_path "/path/to/kimai2/public";
    root $root_path;
    access_log /var/log/nginx/kimai-access.log;
    error_log  /var/log/nginx/kimai-error.log;
    large_client_header_buffers 4 8k;
    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        index index.php;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
```

Disclaimer: I'm not a sysadmin, so I'm not 100% sure that it's 100% secure, but it works.

**Comment by duven87** [comment]
> Here is my nginx config, it works flawlessly:
> 
> ```
> server {
>     listen 80;
>     listen [::]:80;
>     listen 443 ssl http2;
>     listen [::]:443 ssl http2;
>     ssl_certificate     /etc/ssl/certs/cert.crt;
>     ssl_certificate_key /etc/ssl/private/key.key;
>     server_name kimai.example.net;
>     set $root_path "/path/to/kimai2/public";
>     root $root_path;
>     access_log /var/log/nginx/kimai-access.log;
>     error_log  /var/log/nginx/kimai-error.log;
>     large_client_header_buffers 4 8k;
>     location / {
>         try_files $uri /index.php$is_args$args;
>     }
> 
>     location ~ ^/index\.php(/|$) {
>         index index.php;
>         fastcgi_pass unix:/run/php/php7.2-fpm.sock;
>         fastcgi_split_path_info ^(.+\.php)(/.*)$;
>         include fastcgi_params;
> 
>         fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
>         fastcgi_param DOCUMENT_ROOT $realpath_root;
> 
>         internal;
>     }
> 
>     location ~ \.php$ {
>         return 404;
>     }
> }
> ```
> 
> Disclaimer: I'm not a sysadmin, so I'm not 100% sure that it's 100% secure, but it works.

Oh thanks!  I tried to change some lines like you and now I have again a redirect to:
https://kimai2web.de/es/homepage
I was in this point before and I couldnt do much more.
 But good to find a reference anyway that works
Thanks :)

**Comment by infeeeee** [comment]
Can you edit your original post and format it correctly so we could read your config? Just like I did? It's really hard to read it, I don't know what are you missing and what is lost with formatting. Here is how you can put it in a code block: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

And first try to make it work without a ssl, it's easier to set up that way, and later add the lines required for ssl.

**Comment by duven87** [comment]
Done, sorry. Usually I dont write in github. 
Ok, I will try.

**Comment by infeeeee** [comment]
Do you own kimai2web.de? you have to write there the url you want access the site, what you own. If you just want to access directly through the IP omit that line. And I would replace your ` location ~ ^/index\.php(/|$) { ` directive with mine, just replace 7.2 with 7.3. Make sure that `/run/php/php7.3-fpm.sock` is exists, it's location can be different based on the distro. If you have multiple versions of php installed make sure that 7.3 is the default you can check it by running `php -v` it will output the default version.

**Comment by infeeeee** [comment]
And you can write ` auth_basic "Private"` lines outside and before the locations. But at first setup without auth, and later add the auth when it works without it.

**Comment by duven87** [comment]
> Do you own kimai2web.de? you have to write there the url you want access the site, what you own. If you just want to access directly through the IP omit that line. And I would replace your `location ~ ^/index\.php(/|$) {` directive with mine, just replace 7.2 with 7.3. Make sure that `/run/php/php7.3-fpm.sock` is exists, its location can be different based on the distro. If you have multiple versions of php installed make sure that 7.3 is the default you can check it by running `php -v` it will output the default version.

kimai2web its just a example for here. I own another website and it's wrote correctly.
I change all like you and stil I have a redirection to "kimai2web.de/es/homepage" and nothing appear.
I think its some config problem with Symfony

**Comment by kevinpapst** [comment]
I will close this issue as you opened #793

**Comment by duven87** [comment]
> Here is my nginx config, it works flawlessly:
> 
> ```
> server {
>     listen 80;
>     listen [::]:80;
>     listen 443 ssl http2;
>     listen [::]:443 ssl http2;
>     ssl_certificate     /etc/ssl/certs/cert.crt;
>     ssl_certificate_key /etc/ssl/private/key.key;
>     server_name kimai.example.net;
>     set $root_path "/path/to/kimai2/public";
>     root $root_path;
>     access_log /var/log/nginx/kimai-access.log;
>     error_log  /var/log/nginx/kimai-error.log;
>     large_client_header_buffers 4 8k;
>     location / {
>         try_files $uri /index.php$is_args$args;
>     }
> 
>     location ~ ^/index\.php(/|$) {
>         index index.php;
>         fastcgi_pass unix:/run/php/php7.2-fpm.sock;
>         fastcgi_split_path_info ^(.+\.php)(/.*)$;
>         include fastcgi_params;
> 
>         fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
>         fastcgi_param DOCUMENT_ROOT $realpath_root;
> 
>         internal;
>     }
> 
>     location ~ \.php$ {
>         return 404;
>     }
> }
> ```
> 
> Disclaimer: I'm not a sysadmin, so I'm not 100% sure that it's 100% secure, but it works.

Hi infeeeee, 
What do you mean with $realpath_root?
It's not defined in any place of the config file.

**Comment by infeeeee** [comment]
It's an embedded nginx variable: https://nginx.org/en/docs/http/ngx_http_core_module.html#variables

2019. június 12. 15:19:23 CEST, duven87 <notifications@github.com> írta:
>> Here is my nginx config, it works flawlessly:
>> 
>> ```
>> server {
>>     listen 80;
>>     listen [::]:80;
>>     listen 443 ssl http2;
>>     listen [::]:443 ssl http2;
>>     ssl_certificate     /etc/ssl/certs/cert.crt;
>>     ssl_certificate_key /etc/ssl/private/key.key;
>>     server_name kimai.example.net;
>>     set $root_path "/path/to/kimai2/public";
>>     root $root_path;
>>     access_log /var/log/nginx/kimai-access.log;
>>     error_log  /var/log/nginx/kimai-error.log;
>>     large_client_header_buffers 4 8k;
>>     location / {
>>         try_files $uri /index.php$is_args$args;
>>     }
>> 
>>     location ~ ^/index\.php(/|$) {
>>         index index.php;
>>         fastcgi_pass unix:/run/php/php7.2-fpm.sock;
>>         fastcgi_split_path_info ^(.+\.php)(/.*)$;
>>         include fastcgi_params;
>> 
>>         fastcgi_param SCRIPT_FILENAME
>$realpath_root$fastcgi_script_name;
>>         fastcgi_param DOCUMENT_ROOT $realpath_root;
>> 
>>         internal;
>>     }
>> 
>>     location ~ \.php$ {
>>         return 404;
>>     }
>> }
>> ```
>> 
>> Disclaimer: I'm not a sysadmin, so I'm not 100% sure that it's 100%
>secure, but it works.
>
>Hi infeeeee, 
>What do you mean with $realpath_root?
>It's not defined in any place of the config file.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/kevinpapst/kimai2/issues/792#issuecomment-501269397

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kevinpapst** [comment]
This is not an arbitrary discussion forum. These issue are meant for discussions about Kimai.
And this is NOT a kimai problem. Thanks @infeeeee !
