### ISSUE TITLE
kimai dashboard does not display correctly

### ISSUE THREAD

**Issue by duven87** [kevinpapst/kimai2#793]
![image](https://user-images.githubusercontent.com/24485101/57927498-77bc9100-78ae-11e9-917a-2d3a908ddc75.png)

What didnt I wrong?

**Comment by duven87** [comment]
If I comment in my nginx config file
fastcgi_param APP_ENV env;
then appears that:

![image](https://user-images.githubusercontent.com/24485101/57932024-27e3c700-78ba-11e9-9504-fa974e3a83fc.png)

**Comment by kevinpapst** [comment]
Looks like a broken CSS. Anything in your browser console? Any error in the network tab?
APP_ENV should be `prod` and not `env`.
Show me all of your environment configs.

**Comment by kevinpapst** [comment]
Still an issue for you?

**Comment by kevinpapst** [comment]
And no feedback here as well, closing.

**Comment by duven87** [comment]
Sorry kevin, I haven't tried again.
I had another projects with major priority and I wanted leave it until I see a more stable update.
Anyway I will try all again these days.
Thanks

Regards
