### ISSUE TITLE
Adding a command as Plugin

### ISSUE THREAD

**Issue by tobybatch** [kevinpapst/kimai2#797]
**Adding a command as Plugin**
Currently only routes.yaml is read to configure a plugin so a service cannot be added.

**To Reproduce**
1. Create a new plugin bundle.
2. Create a new command
3. Create a services.yaml
3. Clear cache and run console command
4. Command does not appear

**Logfile**
N/A

**Screenshots**
N/A

**Desktop/Smartphone**
N/A

**Additional context**
 - 0.9
 - PHP 7.2.17-0ubuntu0.18.04.1 (cli) (built: Apr 18 2019 14:12:38) ( NTS )

This section is listed in the read me.  I don't think we even try and load the services.yaml.

> Routes are automatically loaded with the search pattern:
> var/plugins/YourBundle/Resources/config/routes.{php,xml,yaml,yml}

**Comment by kevinpapst** [comment]
The services.yaml must be loaded by your plugin, as with every other Symfony bundle.

Check this example:   The [extension file](https://github.com/Keleo/CustomCSSBundle/blob/master/DependencyInjection/CustomCSSExtension.php) requires [a services.yaml](https://github.com/Keleo/CustomCSSBundle/blob/master/Resources/config/services.yaml).

Okay, the example doesn't register a command ;-) but the logic still applies: some plugin related services are loaded and configured.

**Comment by tobybatch** [comment]
thanks @kevinpapst
