### ISSUE TITLE
Adding credit for a customer

### ISSUE THREAD

**Issue by Sch-Tim** [kevinpapst/kimai2#799]
Let's say the customer owes me 50€ and gives me 100€.   
Is it possible to add this positive balance and reckon this up with the next invoice?

**Comment by kevinpapst** [comment]
No and I don't see finance management as a key feature of Kimai. 
Even though I do understand the link with the invoice system, it's nothing which I currently plan to add.
I would maybe accept a PR for such a feature but tbh I think a feature like that should be part of an enhanced invoice management plugin.
