### ISSUE TITLE
Show customer/project/activity colors on last activities dropdown

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#803]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The new customer/project/activity colors are very useful, they make the 'My times' page much more understandable. However I miss them on the 'Last 10 activities' dropdown, the look of the dropdown is not consistent with the look of My times. The colors should show up similarly on the my times, inline and before the name of the project/activity. Here is a mockup: 
![image](https://user-images.githubusercontent.com/1271737/58262495-adfc8380-7d7a-11e9-8866-89ee3a18107a.png)
Just like it's the part of the name of the project.

**Describe alternatives you've considered**
The dots before the name is consistent with the current display, so I didn't consider alternative, this way it will nicely blend to the existing style

**Additional context**

**Comment by kevinpapst** [comment]
Probably it would look even better when the icon in frontend was removed and the contents structured in a table-like way => so it more readable (but I am not sure about both points).

**Comment by kevinpapst** [comment]
Tried and stopped: the dropdowns are reloaded via javascript and the color information / calculation would have to be transferred to the frontend as well. Just for the next time when I will look into it.

**Comment by kevinpapst** [comment]
Next major version #2902 does finally add the colors and also includes a "favorite activities" feature in the dropdown:
<img width="440" alt="Bildschirmfoto 2022-08-06 um 02 43 42" src="https://user-images.githubusercontent.com/533162/183226760-ad4c0774-f918-414d-974c-3ff23389fd25.png">
