### ISSUE TITLE
Import from backup from Kimai2 to Kimai2

### ISSUE THREAD

**Issue by sdo992** [kevinpapst/kimai2#809]
I gave my daughter my main system since hers went down and backed up the SQL data. I tried to install on my new main system and kept getting a 500 error. Searching the log, I think that I have an issue with my previously created user and the .env file(?).

**Describe the solution you'd like**
The ability to seamlessly restore from backup. Is it possible to create a script or even a step-by-step guide to go from Kimai2 backup to a new Kimai2 on a different system?

**Describe alternatives you've considered**
I think I'm screwed; I've not considered any other alternative since all my data are already in the old mysql db.

**Additional context**
I followed the Installation instructions except for user and database creation. I was able to login but when i tried to go anywhere outside of the initial login screen (the 'Calendar' view), it gave me the 500 error.

**Comment by kevinpapst** [comment]
I re-create my system 10 times a day, simply point the DATABASE_URL to another DB and you are good to go (or vice versa, point it to an old DB). There is nothing special that you need to know. 

I can only guess... which I am now doing:

1. You switched the version without noticing, then your old DB structure doesn't match the new one which is expected. That could be fixed by running the DB migration from the normal upgrade process.
What did you use before and what did you install?

2. Are you sure you have setup the file permissions properly?

> Searching the log, I think that I have an issue with my previously created user and the .env file(?).

Did it occur to you, that sharing the log message might be a good idea?

**Comment by kevinpapst** [comment]
Wanna share an update?

**Comment by sdo992** [comment]
Sorry, been busy with the holiday weekend here.

Most likely the kimai2 DB was 0.8 (the one just before 0.9) and now I just downloaded the 0.9 and have it up and running as a new system with none of my old information.

As far as file permissions, it's been odd. I followed the installation process off the website and get a blank page. So, I tried several different things:

`chown -R www-data:www-data /var/www/kimai2/*`
`chmod -R 775 /var/www/kimai2/*`

Those don't work.

`chmod -R 777 /var/www/kimai2/*`

The final one is what gets me a workings system. It's completely wide open.

When I try to import my data and use a completely different user, I get a 500 error.

**Comment by sdo992** [comment]
I'm using Solus Linux and nginx.

nginx.conf:

```
user www-data;
worker_processes 2;

events {
	worker_connections	1024;
}

http {
	include		mime.types;
	default_type	application/octet-stream;

	sendfile	on;
	keepalive_timeout 65;
	gzip		on;
	include		/etc/nginx/sites-enabled/*.conf;
}
```
/etc/nginx/sites-availabe/kimai.conf:

```
server {
	listen 80 default_server;
	server_name localhost;
	root /var/www/kimai2/public;
	index index.php;

	location / {
		try_files $uri /index.php$is_args$args;
		#try_files $uri $uri/ /index.php?q=$uri&$args;
	}

	location ~ \.php$ {
		#try_files $uri = 404;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		#include	fastcgi_params;
		include /etc/nginx/fastcgi.conf;
	}

	error_log /var/log/nginx/project_error.log;
	access_log /var/log/nginx/project_access.log;
}
```

Nothing to report in either:

`/var/log/nginx/error.log`

or

`/var/log/nginx/access.log`

May try another linux or even windows; since I have a f***ing Max-Q hybrid graphics laptop, Solus seems to work the best with it. So, I've been hesitant to switch.

**Comment by kevinpapst** [comment]
Hahaha, you shouldn't switch an OS for a software. 

Its simple and as I guessed in the beginning:
> Unknown column 'k0_.email' in 'field list' at

Everything is "fine" besides that you didn't migrate your database. You still have a backup, right?

Then execute the normal upgrade process, explained here:
https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md

Make sure to check the version specific steps. As you did a fresh install, you maybe only need to call the migration.

**Comment by sdo992** [comment]
I ran the migrate and it found nothing to migrate, after the DB restore, of course.

I was able to log in, but got a blank page everywhere; I ran:

chmod -R 777 var/

And was able to see the Calendar, Dashboard, User, Plugin, and Settings, but nothing else. They all return the same error as above:

```
Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it again. 
```
I completely removed the database and /var/www/kimai2 folder and started over and still have the problem.

local.yaml does not exist in `config/packages/` so I have nothing to change.

**Comment by sdo992** [comment]
Oh my dear gods, what a long process. It took weeks to get this up and running.

This FINALLY fixed it:

`bin/console doctrine:schema:update --force --complete`

I changed the permissions back on /var/www/kimai2/var to 775 and it still works. I need to make sure I can enter new data, change old data, and everything else, but at least I can finally get back in!

**Comment by kevinpapst** [comment]
Oh thats not good. If the command did not find missing migrations, you have another problem.
Was 0.8 the first version you installed?
Did you execute the [documented command](https://www.kimai.org/documentation/installation.html) `bin/console doctrine:migrations:version --add --all`? Don't do it know, if you haven't before.
Do you have the database table `migration_versions`?

**Comment by sdo992** [comment]
Yeah, it was the 0.8. I started in v1 and then successfully upgraded to v2, 0.8. Between 26 Apr 2019, my last entry in 0.8, and now, I guess 0.9 was released

And, I did execute `bin/console doctrine:migrations:version --add --all` several times as I tried to get it up and running.

I do not have the database table `migration_versions` in kimai database.

**Comment by sdo992** [comment]
So, if I want to import my backup, how do I do that?

If the migrations have a possibility to cause data corruption, I have to run it before the database restore.

When I restore the database, it gets rid of the `migration_versions` in kimai.

**Comment by kevinpapst** [comment]
I hope that helps: https://www.kimai.org/documentation/backups.html

**Comment by sdo992** [comment]
Awesome, thank you! I read through it and those are the steps that finally got it working, but we stumbled through it. Now that it's online, it should be easier.

**Comment by kevinpapst** [comment]
Thanks for your feedback, yes I hope the next one doesn't have to "suffer" what you went through :-D
