### ISSUE TITLE
Filter for Projects without selecting a customer

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#817]
**Is your feature request related to a problem? Please describe.**
Not a problem like a bug. More an issue regarding the usability.

**Describe the solution you'd like**
In the page "My Times" i would like to filter entries for a Project without selecting a customer first.
It should behave like the Project selection if i create a new time entry.

**Describe alternatives you've considered**
An alternative solution could be, that the filed for filtering projects is disabled or invisible as long as no customer is selected. At the moment it is confusing, why there are no projects listed. (But i prefer the first solution)

**Comment by StefanWinterberger** [comment]
I just saw, that the alternative solution i mentioned, is implemented in the development branch. Thank you.

**Comment by kevinpapst** [comment]
An upgraded version is now available in master. 
Would be great if you could test it and leave some feedback!
Use the "development version" demo: https://www.kimai.org/demo/

**Comment by StefanWinterberger** [comment]
Hey Kevin
This issue is solved great in the current development demo server. Thank you.
