### ISSUE TITLE
Show total hours for selected filters in MyTimes

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#819]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the view MyTimes, I would like to see the total duration for the current selcted filters (time range), without to press the export button first. I would like to see the total on top of the list, so i don,t have to scroll down.

**Comment by frederickjh** [comment]
@StefanWinterberger Thanks for the workaround of using the export button until this gets implemented!

**Comment by nqb** [comment]
+1 for this feature, would be nice if we can have same information in Timesheets menu

**Comment by herrschmidt** [comment]
+ 1 in Timesheets menu, My Times and Dashboard. A simple "Total Hours" title above the timesheet would be great, almost mandatory for the user experience. I am also trying to figure out how to gain an overview over all tasks of a project. In the project overiew it would be great to see all project tasks and their total hours.

**Comment by kevinpapst** [comment]
You can see the requested changes at work following the link in the [milestone description](https://github.com/kevinpapst/kimai2/milestone/38). 

I am closing this issue, even if the new version is not yet there and it might take some months before it will be released.
