### ISSUE TITLE
Clear selected customer when editing an time entry

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#820]
**Is your feature request related to a problem? Please describe.**
Not sure if this behaviour is intended...

**Describe the solution you'd like**
When I edit an existing time entry, there is no way to clear the customer field. To compare: In the fileds Project and Activity i can select to top most entry to clear the fields, but in the list of the customer there is no blank field. 
While creating a new entry, this is possible. But if i clear the field i cannot see any project in the list (on demo-stable server) or the Project field is disabled after (on the demo server)

I would like to have a possibility to clear the customer field, so i can see the whole project list again. In both (creating and editing) screens.

**Comment by kevinpapst** [comment]
I do admit that these selects still need improvement, as they behave different throughout the UI.
But why would you want to see the complete project list again? 
Initially when creating a new entry: okay, to save you one click. 
But why would you want to reset the list to see all projects again when editing an existing entry? The need to change a project is rare (you misconfigured it initially) but then: don't you know which customer you worked for?

**Comment by StefanWinterberger** [comment]
I see your point.
In our company we are very project oriented, since our customers are often funding organisations etc. So it really can be that we are not sure for which organisation the current project is for. (I agree that this is a special case.) 

Nevertheless, if i missclicked the customer and i then i see the project i am looking for is not in the list, (and then i am not sure from which customer the project is), I would like to select the project from the whole project list.

And finally, as a user i don't like it if i cannot clear a form field :)
And i think it should behave identical while creating or editing an entry.

**Comment by kevinpapst** [comment]
An upgraded version is now available in master. 
Would be great if you could test it and leave some feedback!
Use the "development version" demo: https://www.kimai.org/demo/

**Comment by StefanWinterberger** [comment]
Hi Kevin.
Feedback to this issue in the current development demo server.

I tried following steps:

- Under "My tiimes" I opened the topmost entry to edit.
- I cleared the customer (Funk-Treutel) with selecting the blank field in the list. Then the following fields gets cleared as expected.
- Know i selcted a project from another customer (BarrowsGroup) without selecting the customer itself.
- I select an Activity and want to Save the entry.
- Then the Project field turns red and reports "This value is not valid", so i can't save. (See screenshot)

![grafik](https://user-images.githubusercontent.com/43982536/60900014-c6adf380-a26b-11e9-988b-494c5a6ac2bb.png)

(Note: I noticed that there are some activites on top with more indent than the rest. If i choose an activity from the one with no indent it works as expected)

![grafik](https://user-images.githubusercontent.com/43982536/60900441-77b48e00-a26c-11e9-8a68-4ba59ba267d1.png)

Can you reproduce this behaviour with this description?

**Comment by kevinpapst** [comment]
Yes, I can ... unfortunately 😢 
Ok, I'll debug that problem. Thanks for testing!

**Comment by StefanWinterberger** [comment]
No problem. I will test it again, if you can fix it. Thank you.

**Comment by kevinpapst** [comment]
This time, please test on: 
https://demo-branch.kimai.org/

I don't want to merge something broken again into master ;-)

**Comment by StefanWinterberger** [comment]
Hi Kevin
I tested now on the demo-branch server and it still shows the pretty same behaviour.
I clear the customer field, choose a project directly (without selecting a customer first), then i have a list of activities (some wiht an indent and some not) and no matter which of them i choose i get the red warning on the project field. "This value is not valid."

I tried with many different projects and activites.
(If i choose a customer first it works as expected.)

**Comment by kevinpapst** [comment]
Yep, I missed one case. Can you please test once again at https://demo-branch.kimai.org/

And btw: the once that are not indented are "global activities".

**Comment by StefanWinterberger** [comment]
Hey Kevin
Now it works great. I can't find any bugs to this use case anymore.
Thx for explenation about the indented activities. 

I'm happy to have this feature in a future release :)

**Comment by kevinpapst** [comment]
Thanks for testing! 
Merged to master
