### ISSUE TITLE
Advanced filter options

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#821]
**Is your feature request related to a problem? Please describe.**
Not a problem. Its an improvment for administartors.

**Describe the solution you'd like**
Following filteroptions are missed by our Administrators.

- In the Page Administartion -> Timesheets, if i set a filter on projects i would like to see wich user had worked how many hours for the selected project and time range (and activity if its selected)

- In the Page Administartion -> Timesheets, if i set a filter on a user, i would like to see for which project the user worked how many hours. Either with our without a breakdown to activities.

- In every filter it would be nice to select multiple entries. For example to see how many hours two or three users have worked in total without adding them myself.

I know that these are advanced filters and you can argument that i am free to export the tables and do the filtering in Excel. But i still think its worth a discussion. :)

**Comment by kevinpapst** [comment]
That will be part of a reporting extension and won't be part of the team timesheets.

**Comment by StefanWinterberger** [comment]
Is there a plugin already in development?

**Comment by kevinpapst** [comment]
Only in my head ;-) but there will be something in the future.

**Comment by cgx** [comment]
One additional note: in **v1**, we were able to filter the timesheets by **multiple** users, **multiple** customers, **multiple** projects, **multiple** activities. In **v2**, we can filter by multiple users, but only by a **single** customer, a **single** project, and a **single** activity. It was a very convenient feature in v1 that we miss in v2.

**Comment by kevinpapst** [comment]
@cgx Then vote for it with 👍 in the initial post

**Comment by saschafoerster** [comment]
Just adding for documentation purpose: a monthly overview on project level would help to see, how much time for which project has been spend in the last month: https://github.com/kevinpapst/kimai2/issues/190

**Comment by kevinpapst** [comment]
So PR #1557 finally adds multi-select in the filter section for customers/projects and activities.

If anyone can help testing and provide some feedback (demo installation is available) that would be highly appreciated.

**Comment by StefanWinterberger** [comment]
Hi Kevin

Thank you for your effort and for the new features.
On a first sight, it looks very promising. I will have a closer look at it next week, since I’m in holyday at the moment.

Stefan Winterberger
Wissenschaftlicher Assistent

Hochschule Luzern
Technik & Architektur
iHomeLab
Technikumstrasse 21, CH-6048 Horw

T direkt +41 41 349 35 66 | T +41 41 349 35 99
stefan.winterberger@hslu.ch<mailto:stefan.winterberger@hslu.ch>
www.ihomelab.ch<http://www.ihomelab.ch/> | www.hslu.ch<http://www.hslu.ch/>


Von: Kevin Papst <notifications@github.com>
Gesendet: Sonntag, 15. März 2020 15:18
An: kevinpapst/kimai2 <kimai2@noreply.github.com>
Cc: Stefan Winterberger [iHomeLab] <stefan.winterberger@ihomelab.ch>; Author <author@noreply.github.com>
Betreff: Re: [kevinpapst/kimai2] Advanced filter options (#821)


So PR #1557<https://github.com/kevinpapst/kimai2/pull/1557> finally adds multi-select in the filter section for customers/projects and activities.

If anyone can help testing and provide some feedback (demo installation is available) that would be highly appreciated.
