### ISSUE TITLE
Support for different formats in user export

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#822]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
As a user without admin rights I would like to export my timeentris (for the currently set filters) to excel so i can use them for different reports etc.

**Additional context**
The existing export function is great. But its only available for administrators. As a user without admin rights, i would like to have the same only for my data.

**Comment by kevinpapst** [comment]
What is missing from the user export (via the users timesheet => action button in the upper right)?

**Comment by StefanWinterberger** [comment]
This only exports to HTML. Or did I miss something?
It would be nice if it could be downloaded as excel.

**Comment by kevinpapst** [comment]
You know that you can copy&paste the HTML table? This worked at least with every office product I tried (Excel, Numbers, Open & Libre Office)

**Comment by StefanWinterberger** [comment]
This works, but if I copy/paste it, i have all the entries for Customer, Project and Activity in one cell. Thats not that nice for further editing. It would be nice if they are in seperate columns.
And still a direct download would be comfortable :)

**Comment by kevinpapst** [comment]
Can you explain the user case for that? Besides that it would be comfortable. 
Why would a user need that and what he do with that export?
Don't get me wrong, if that would be easily achievable I would have done it already, but for you its a matter of 2 minutes to post the issue, for the developer this will a task of one day or so.

**Comment by StefanWinterberger** [comment]
Our users have to do a lot of other reports based on their time entries. And an excel (or csv) with seperate columns would be very practical to make furhter filters or sorting for these reports and would save a lot of time.
If you think its not needed or not interesting, feel free to close the issue :)

**Comment by kevinpapst** [comment]
> Our users have to do a lot of other reports based on their time entries. And an excel (or csv) with seperate columns would be very practical to make furhter filters or sorting for these reports and would save a lot of time.

As Product Owner you need to question the intention of each feature: is it worth the costs?
Its very easy to leave a feature request, but if you want it to be developed, you need to convince the stakeholders (in this always me) that it is worth the effort. Especially unpaied...
So adding a good reason to your issue will increase the probability of its development.

**Comment by StefanWinterberger** [comment]
Yes, sure. I am totally with you.
And you are doing a great job.
Thats why i am wrote, if i cannot convince you as stakeholder and you think its not worth it, feel free to close it.

**Comment by rarvin** [comment]
This is on the timesheet html manual table export  -- 
Would it be possible for you to add a comma or a delimiter like semi colon in the html table that you generate in the timesheet view so that when one copy paste the data to an excel sheet the tag text would appear with a comma or some delimiter after each complete tag word. Since currently for tags text spaces are allowed and when one copies and pastes the data to an excel sheet its difficult to differentiate between one complete tag with space and the other and so on.

Example - 

Description | Tags
test arvin | arvin arvin2
Here arvin and arvin2 are two different tags hence they would not have any issues when we delimit the text 

Description | Tags
test 2 tag words with space in them | arvin with spacearvin_without_space

Here both tag words have merged together and also the tag data with space would delimit into multiple columns when they are to be considered as one. I hope you understand the problem one would face.

If you need a new issue to be raised I could do that too.

**Comment by kevinpapst** [comment]
@rarvin
The current HTML export is for a use-case which is often used in companies: a user prints his monthly sheet and walks up to his manager to sign it, so both sides can be sure that no manipulation is done afterwards and that no hours get lost, therefor this report simply does not need tags.

I think having a direct Excel export with all columns (that the user is allowed to see) is much better.

**Comment by rarvin** [comment]
Thanks Kevin, I just need a way to get the list of active tasks which have tagged data against them, which can't be pulled out from the other views. Hence was asking. Is there some way to get this by some technique, even if it is manual its fine with us. We prioritise certain active task based on who is working on it and use the tags to find if they were a priority. The tags are also used to hold the name of the work-order they are working on etc which have spaces in them. We can for the time being add a comma to the end of the tag and wait till you are able to provide an excel download.

**Comment by kevinpapst** [comment]
If you need them in Excel, I don't think there is a way right now out of the box. 

With some adjustments/dev knowledge, you can:
- pull it from the API (there is an example file in the documentation how to use it)
- add a new column [here](https://github.com/kevinpapst/kimai2/blob/master/templates/timesheet-team/export.html.twig#L61) something like `<td>{{ timesheet.tagsAsArray|join(',') }}</td>` and clear your cache afterwards, then you have it in the admin timesheets html export

But this Feature request is about something else...

**Comment by kevinpapst** [comment]
The next release ships different formats for user exports. They can be extended, like the regular exports. Out-of-the box there are 4 different types:

<img width="896" alt="Bildschirmfoto 2019-11-23 um 21 55 06" src="https://user-images.githubusercontent.com/533162/69485163-fa18a580-0e3b-11ea-9279-d238880b2f2a.png">

You can test that in the demo.

It does not export the filtered columns, but instead all the fields that the regular exports spits out as well.

Closing here, as it is implemented for 1.6.
