### ISSUE TITLE
Tooltips for new users

### ISSUE THREAD

**Issue by StefanWinterberger** [kevinpapst/kimai2#823]
**Is your feature request related to a problem? Please describe.**
Not a problem. Just an improvement regarding the usability.

**Describe the solution you'd like**
For new users it would be helpful if they can activate (in user prefernces) mouse over tooltips for all the buttons etc.

**Comment by kevinpapst** [comment]
Are you willing to contribute the translations for all these buttons?

**Comment by StefanWinterberger** [comment]
I see that this is a lot of work.
I just wanted to mention it since I heard this a lot from our users.
