### ISSUE TITLE
Add tag data to exports

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#825]
**Is your feature request related to a problem? Please describe.**
Under the export option one can export excel or pdf or csv reports, it allows for various fields to be exported but not the tag fields. The tag field is now a vital filed containing very important data and having them exported would greatly help us in filtering data in excel sheets etc for our analysis.

**Describe the solution you'd like**
The tag filed should be exportable, even is they are exported under a single column in comma delimited fashion then we could delimit them by exporting the data to a excel sheet. It is best to keep the tag data column to the last column of the sheet so that when we delimit the data in the excel sheet the columns would merge onto the subsequent columns and we would not have problems of column data getting overwritten. Giving us this export option would greatly help and only then can we effectively use the tag option to our needs.

**Describe alternatives you've considered**
None available unless the data is exportable we would not be able use them for our analysis

**Additional context**

**Comment by kevinpapst** [comment]
Fixed by #860
