### ISSUE TITLE
Create documentation for layman users to deploy the master code on their servers 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#827]
**Is your feature request related to a problem? Please describe.**
Currently numerous needed functionality are released early before the final release are packaged and released. It would be great if some documentation is made which guides uses to deploy code that has been released to the master so that certain required critical functionality can be deployed as and when the uses needs them before the final release happens.

**Describe the solution you'd like**
Documentation describing how code in master can be deployed and used.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by kevinpapst** [comment]
@rarvin can you please delete the stuff from the issue template that you don't fill out. It makes it really hard to read if I see "A clear and concise description of what you want to happen." all the time.

Regarding your question: No I will not document that more than it is.
If you don't know how to replace a version ID with a branch name in a git clone and/or not willing to google how that works: better stick with the latest stable.
I don't want to answer either so simple questions or problems that arise from using comands you don't understand and can't handle yourself.

Also: there are a lot of platforms out there where you can get help with such questions (like Stackoverflow).
