### ISSUE TITLE
Fix a threshold for a particular activity

### ISSUE THREAD

**Issue by rishinairt** [kevinpapst/kimai2#828]
.
Is it possible to add a threshold or allowed time for a particular activity? For example, I created a new activity called "Login" and if any task in this category runs beyond the threshold or allowed time of 2 hrs (as I fixed), it should be flagged immediately? For example, an alert email should be sent to the administrator or managers (as per the role). Also a pop-up should appear to the users screen that he/she has exceeded the allowed time for that particular activity.

**Comment by kevinpapst** [comment]
Not yet, budgets (this is a time budget instead of money) will be implemented in the future.
I am sure there are existing issues around here, please search for "budget". Might be better to include your opinion in there (if it fits the actual ticket) or upvote it with a thumbs-up.

**Comment by kevinpapst** [comment]
Fixed by #2422
