### ISSUE TITLE
Add hardware support (like scanners or timeflip)

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#829]
Having hardware support would greatly improve the range of use-cases for companies, especially in clock-in and clock-out environments.

Some detail questions can be found in:
- #285 / [Timeflip](https://timeflip.io/)
- #357 / Scanners in clock-in clock-out environments

**Comment by rarvin** [comment]
Our use case is, in addition to tracking the time users spend on each activity we would like to know when the arrive at office and when they leave work. In general they are to spend a said number of hours at work. Mostly what happens is that the users clock in more time than they spend at work by starting timers before they arrive at work and leave timers running after they leave work. Having the time when the clock in and when the clock out could help us in auditing and understanding if users are accounting for the right amount of time at work. Having a clock in clock out module along side the the time tracking module can be beneficial.

**Comment by kevinpapst** [comment]
https://www.kimai.org/store/kiosk-barcode-bundle.html
