### ISSUE TITLE
apache indexes file after installation has complete

### ISSUE THREAD

**Issue by lepidas** [kevinpapst/kimai2#831]
**Describe the bug**
After installing kimai2, visiting the coresponding web page with browser, apache lists the files instead of the kimai2.
Everything has gone fine with the installation.

**To Reproduce**
3. See error

**Logfile**
```
Add the last lines from your logfile at var/log/prod.log, around the time when the problem happened.
```

**Screenshots**

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s]

**Additional context**
 - Kimai version
 - PHP version

**Comment by kevinpapst** [comment]
Read this: https://symfony.com/doc/current/setup/web_server_configuration.html
or ask at Stackoverflow / ServerFault...

This is not a Kimai problem => closing.
