### ISSUE TITLE
503 Error Service Unavailable

### ISSUE THREAD

**Issue by cameronneuhoff** [kevinpapst/kimai2#834]
I am new to server programming. However, I think I've installed everything correctly, but when I try to access Kimai2 through Google Chrome browser, I am getting a 503 _Error Service Unavailable: The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later._

The Kimai icon appears in the Browser tag, which I take as a good sign.

I was able to view the PHPinfo() document with localhost, so I am confident I am able to configure the Apache files accordingly

Running:

Apache 2.4.29 (Ubuntu 18.04) Server at 127.0.0.1 Port 80 (localhost)
PHP 7.2
Windows 10 Operating System
Lenovo P50 Workstation 
32 GB RAM
2.8 GHz Intel XEON processor

Thank you for your help. Again, I'm very new at this...

**Comment by kevinpapst** [comment]
I can't help with webserver configuration, a helpful link to a Symfony page is available in the installation docs.
But 503 means server error, so I assume it an uncomplete Kimai installation .
Check the logfiles at var/log/prod.log and post the last ~50 lines here.

**Comment by cameronneuhoff** [comment]
I don't have a /var/log/ directory for some reason, but I've located the apache2/project_error.log and got this:

It looks like a proxy_fcgi issue? :

[Thu May 30 14:41:26.522575 2019] [proxy:error] [pid 16847:tid 140282789037824] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Thu May 30 14:41:26.522840 2019] [proxy_fcgi:error] [pid 16847:tid 140282789037824] [client ::1:62012] AH01079: failed to make connection to backend: 127.0.0.1
[Thu May 30 14:44:06.795330 2019] [proxy:error] [pid 16848:tid 140282780583680] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Thu May 30 14:44:06.795673 2019] [proxy_fcgi:error] [pid 16848:tid 140282780583680] [client ::1:62016] AH01079: failed to make connection to backend: 127.0.0.1
[Thu May 30 14:45:59.390457 2019] [proxy:error] [pid 16938:tid ] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Thu May 30 14:45:59.390638 2019] [proxy_fcgi:error] [pid 16938:tid 140282789037824] [client ::1:62029] AH01079: failed to make connection to backend: 127.0.0.1
[Thu May 30 14:49:47.018519 2019] [proxy:error] [pid 17146:tid 140685143377664] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Thu May 30 14:49:47.018671 2019] [proxy_fcgi:error] [pid 17146:tid 140685143377664] [client ::1:62042] AH01079: failed to make connection to backend: 127.0.0.1
[Thu May 30 14:51:18.496906 2019] [proxy:error] [pid 17253:tid 140222918100736] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /path/to/fpm.sock (*) failed
[Thu May 30 14:51:18.496989 2019] [proxy_fcgi:error] [pid 17253:tid 140222918100736] [client ::1:62045] AH01079: failed to make connection to backend: httpd-UDS
[Thu May 30 14:51:23.942703 2019] [proxy:error] [pid 17253:tid 140222696195840] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /path/to/fpm.sock (*) failed
[Thu May 30 14:51:23.942777 2019] [proxy_fcgi:error] [pid 17253:tid 140222696195840] [client ::1:62046] AH01079: failed to make connection to backend: httpd-UDS
[Fri May 31 07:55:35.758368 2019] [proxy:error] [pid 19706:tid 140402236262144] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 07:55:35.758605 2019] [proxy_fcgi:error] [pid 19706:tid 140402236262144] [client 127.0.0.1:62544] AH01079: failed to make connection to backend: 127.0.0.1
[Fri May 31 08:00:36.404950 2019] [proxy:error] [pid 19705:tid 140402236262144] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 08:00:36.405136 2019] [proxy_fcgi:error] [pid 19705:tid 140402236262144] [client 127.0.0.1:62591] AH01079: failed to make connection to backend: 127.0.0.1
[Fri May 31 08:03:43.520142 2019] [proxy:error] [pid 19706:tid 140402002626304] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 08:03:43.520299 2019] [proxy_fcgi:error] [pid 19706:tid 140402002626304] [client ::1:62634] AH01079: failed to make connection to backend: 127.0.0.1
[Fri May 31 08:11:00.435462 2019] [proxy:error] [pid 19705:tid 140402002626304] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 08:11:00.435612 2019] [proxy_fcgi:error] [pid 19705:tid 140402002626304] [client ::1:62780] AH01079: failed to make connection to backend: 127.0.0.1
[Fri May 31 09:33:58.463912 2019] [proxy:error] [pid 19706:tid 140401977263872] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 09:33:58.464067 2019] [proxy_fcgi:error] [pid 19706:tid 140401977263872] [client 127.0.0.1:63556] AH01079: failed to make connection to backend: 127.0.0.1
[Fri May 31 10:04:47.770844 2019] [proxy:error] [pid 19706:tid 140401968809728] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 10:04:47.771012 2019] [proxy_fcgi:error] [pid 19706:tid 140401968809728] [client 127.0.0.1:63684] AH01079: failed to make connection to backend: 127.0.0.1
[Fri May 31 10:10:16.497215 2019] [proxy:error] [pid 19705:tid 140401960355584] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Fri May 31 10:10:16.497324 2019] [proxy_fcgi:error] [pid 19705:tid 140401960355584] [client ::1:63702] AH01079: failed to make connection to backend: 127.0.0.1

**Comment by cameronneuhoff** [comment]
I'm going to do a bit more looking around... I don't want to take your time for a stupid small issue... I was just concerned that I wouldn't be able to run it at all on my machine. Thank you

**Comment by kevinpapst** [comment]
You should be able if your PHP at least 7.2 otherwise you would need a VM.
Your error is something for ServerFault or Stackoverflow.

**Comment by kevinpapst** [comment]
BTW `/var/log/` is not `var/log/` (inside your Kimai directory)

**Comment by cameronneuhoff** [comment]
Thanks Kevin! I figured it out! Until next time, keep up the good work.

**Comment by kevinpapst** [comment]
Thanks for your feedback!
