### ISSUE TITLE
Problem adding a new user - No such file or directory

### ISSUE THREAD

**Issue by ClintfromCanada** [kevinpapst/kimai2#836]
I have tried following the instructions many times and on a couple of different VMs and I keep getting the same result.  I'm pulling my hair out over this.  Any idea what's going on?  All the files are owned by the webserver.  I can't figure out which folder is the culprit.

Thanks,

Clint

<img width="801" alt="Screen Shot 2019-05-31 at 4 01 29 PM" src="https://user-images.githubusercontent.com/3891892/58739250-276d2500-83be-11e9-9dc6-f00022b4cbdb.png">

**Comment by kevinpapst** [comment]
Looks as if you have the default `.env` file which uses SQLite database.
Is that on purpose? If so, did you create it?
Did you create it like [written in the docs](https://www.kimai.org/documentation/installation.html#recommended-setup)?
If you didnÄt change anything, it is locate din your Kimai directory inside `var/data/`

**Comment by ClintfromCanada** [comment]
It is pointed in .env to my mysql server with I believe the correct credentials, etc.  Should incorrect credentials throw a no such file or directory error?

**Comment by kevinpapst** [comment]
IMO this error is thrown when using SQLite. Can you show me your .env file?

**Comment by ClintfromCanada** [comment]
Sadly I'm in a VM and can't readily get the file out, but just took a screenshot.  Changed the password to "password"... but all else is the same.  I know the creds work on my mysql server.

![Screen Shot 2019-05-31 at 4 24 07 PM](https://user-images.githubusercontent.com/3891892/58739720-acf1d480-83c0-11e9-96ec-1e61b16645c8.png)

**Comment by kevinpapst** [comment]
> did you create it as [written in the docs](https://www.kimai.org/documentation/installation.html#recommended-setup)?

Additionally run `bin/console doctrine:migrations:status` and show me the result

**Comment by ClintfromCanada** [comment]
Here it is.
![Screen Shot 2019-05-31 at 4 37 29 PM](https://user-images.githubusercontent.com/3891892/58739983-6b622900-83c2-11e9-96db-32dd4008d6e7.png)

**Comment by kevinpapst** [comment]
You ignored my question twice. Why?

**Comment by ClintfromCanada** [comment]
Which question?  The docs?  Yes - step by step.

**Comment by ClintfromCanada** [comment]
Sorry - my bad - you probably get a lot of questions.  I wouldn't bother you with mine unless I had no other solution.  I've done it step by step as you detailed.  One other question - do you recommend any canned VM builds that are out there that will accept kimai2 without much customization?  I'm pulling my hair out over just trying to get it running.  I am now building another from-scratch VM using Ubuntu Server and installing php, mysql, apache, composer, etc. etc. and trying it a third time...

**Comment by kevinpapst** [comment]
Because you don't have a database. Thats what this error tells you.
I may have been wrong about SQLite, but the error is still database `SQLSTATE`.
You can create a user in the login / registration screen. The first user that will be created gets super-admin permissions automatically.
Yu can check the file var/log/prod.log to see if there are more error messages.
You can try to execute `bin/console doctrine:database:create` and see what that shows.

**Comment by kevinpapst** [comment]
Did you solve it is this still an issue? I updated the installation docs to be clearer, maybe that helps.

**Comment by ClintfromCanada** [comment]
Thanks. I'm taking a break on the weekend.  Back at it on Tuesday. Thanks
for checking in.

Clint

**Comment by ClintfromCanada** [comment]
Got it figured Kevin.  Thanks for your assistance.  Once I did another clean install in a new VM it went smoothly.  There was obviously a configuration problem with the other VM that I couldn't identify.  Trashed now!  Cheers!

**Comment by kevinpapst** [comment]
👍
