### ISSUE TITLE
import project "budget" field

### ISSUE THREAD

**Issue by ClintfromCanada** [kevinpapst/kimai2#841]
Hello, I am importing data from Version 1.31 and in reviewing the import code I see that the "budget" field is unsupported.  Does anyone have any guidance for me where I could start in including this field in the import or what mods I would need to make?  I have tons of projects in my old database where I would like to carry over the budget value into the new db.  Even if it is moving it into an integer or something.

Thanks!

Clint

**Comment by kevinpapst** [comment]
Hm, indeed you are right. I missed that field...
You could try to [add a line after this one](https://github.com/kevinpapst/kimai2/blob/master/src/Command/KimaiImporterCommand.php#L679):
```
->setBudget($oldProject['budget'] ?: 0)
```

**Comment by ClintfromCanada** [comment]
That worked Kevin.  Now the next problem I have is that we had the Budget value as being the number of hours estimated that are required to get a job done.  Because I have a fixed rate for each project, if I use Hours budgeted it should be able to automatically calculate the total in $ spent.  The trouble is, I think the "budget" field is used in the program as $.  My next step is to look for other calculations to see where or how difficult it would be to change that from a $ value to an hours budgeted value, but that sounds harder than it's probably worth.  I may need to tackle it from the import side where I do the calculation on import so the budget field is in $.

Clint

**Comment by kevinpapst** [comment]
The field is displayed in the customers currency, so in your case likely dollars. 
I plan to add an explicit hourly budget field this week for project and additionally budgets columns for activities and customers as well, so maybe you want to wait for that? Or you go ahead and migrate the data later between the columns.
I guess you saw that reporting is a feature which is yet missing...

**Comment by kevinpapst** [comment]
I am currently working on the budgets.
How exactly did you adjust the importer, with my code example or did you have to cast the value anyhow?

**Comment by ClintfromCanada** [comment]
No I just looked at what you wrote and went that way.  Made a CustomerProjectCalculator.php with a ProjectInvoiceCalculator class same as the activity one.  I was working on the replacement for mergetimesheets function but don't have anything of significance yet...

**Comment by ClintfromCanada** [comment]
Sorry - was referring to wrong thing.  Regarding the importer, I simply cast the value as you had suggested and it worked correctly.
