### ISSUE TITLE
Project Grouped - One entry per Project

### ISSUE THREAD

**Issue by ClintfromCanada** [kevinpapst/kimai2#842]
The invoice would benefit from a Sum Calculation option called Project Grouped - One entry per Project whereby you can create an Invoice for each customer grouped by the projects that have time attributed to them for the given month set in the invoice.  Would love to try and tackle this but not sure where this is referenced from.  I thought I would duplicate the ActivityInvoiceCalculator.php and make a ProjectInvoiceCalculator.php but I can't determine where to modify the Sum Calculation field options in the template creation form.

**Comment by kevinpapst** [comment]
Sounds good. In your case the `AbstractMergedCalculator::mergeTimesheets()` won't work, as it assumes that you selected a project (tbh. I think this method needs a re-write, but thats a different topic).

So you would create a new `CustomerProjectCalculator` which does NOT extend the `AbstractMergedCalculator` but calculate the duration and sum yourself. 
There is not much to do, as you will only return one Timesheet entry per project.
That one record does not need to display comments or hourly&fixed rates. But I am not sure what to do with the activity. 
The only thing I am not sure about without testing: the renderer probably assume that an activity per timesheet exists, so you imght have to add a dummy activity.

**Comment by ClintfromCanada** [comment]
Thank you!  You are very helpful.  I will give that a shot and report back...

**Comment by ClintfromCanada** [comment]
So I now have something to test, but how do I add that as an option to the form when I make a template?

**Comment by kevinpapst** [comment]
Depends. Running in `dev` or `production`? In dev it should be picked up automatically, in production you need to flush your cache: `bin/console cache:clear`.

**Comment by kevinpapst** [comment]
Btw. the developer docs mention the invoice parts: 
https://www.kimai.org/documentation/developers.html#adding-invoice-calculator

**Comment by kevinpapst** [comment]
Still on it?

**Comment by ClintfromCanada** [comment]
Hey Kevin! I'm stilll working on it but haven't done much due to other
issues. How's the dev going?  I was thinking I may try the dev version with
the new changes?

Clint

**Comment by ClintfromCanada** [comment]
Kevin I have a question for you.  It is related to kimai 1.31 though. Any
thoughts or ideas you have would be appreciated. I am trying to limp along
my 1.31 installation until I can get everything migrated to 2, but I keep
getting these errors in the log as attached. It is an undefined index error
as shown in the attached. Having said that I do have an index on fixedRate,
so I'm not sure what else to check. Basically the website becomes
unresponsive until I reset apache. Any ideas?

See the bottom 3 error lines in the top section.

Many thanks!

Clint

**Comment by kevinpapst** [comment]
Added new invoice calculator in #892 if someone wants to help testing.
