### ISSUE TITLE
Add a "now" button to manual timesheet entry

### ISSUE THREAD

**Issue by stoberblog** [kevinpapst/kimai2#844]
**Is your feature request related to a problem? Please describe.**
When adding an entry manually, I'm frequently adding an entry for something that just happened. In Kimai v1, this was made easier with the "now" button next to the end time field. This meant that the entry could be told to have finished straight away and then the start time would be manually set.

**Describe the solution you'd like**
As in Kimai v1, a simply now button next to the time field (in the pop up once click on end time) would be the simplest and most elegant solution.

I've attached images of Kimai v1 and one way I could see Kimai v2 implementing this.

![Kimaiv1](https://user-images.githubusercontent.com/25950862/59080902-8dadf680-892e-11e9-9c42-1a5648ff114b.PNG)
![kimaiv2-example](https://user-images.githubusercontent.com/25950862/59080903-8e468d00-892e-11e9-8b8c-219760daa596.PNG)

**Comment by kevinpapst** [comment]
Thanks for the feature request!
Yes, I do often create entries ending "now" as well and could also need such a quick button. 
The complete screen could be improved in many ways and I will collect everything in one milestone.

**Comment by kevinpapst** [comment]
@stoberblog Can you have a look at #1180 for the updated timesheet edit dialog (added "now" to the calendar icon and added a duration field)?

**Comment by stoberblog** [comment]
@kevinpapst Where is the new "now" button? I can't see it in the https://demo-branch.kimai.org/en/timesheet/ page?
![Kimai-Branch](https://user-images.githubusercontent.com/25950862/67528140-71a3c980-f704-11e9-91cd-32400dbbb402.PNG)

**Comment by kevinpapst** [comment]
You should not expect the button where you painted it...

>  added "now" to the calendar icon

You'll find it eventually ;-)
