### ISSUE TITLE
Timesheet events

### ISSUE THREAD

**Issue by tobybatch** [kevinpapst/kimai2#849]
**Is your feature request related to a problem? Please describe.**
I want to trigger plugin actions on timesheet creation

**Describe the solution you'd like**
An event dispatched on timesheet creation

**Describe alternatives you've considered**
Listening to resposne events and guessing which timesheet was created

**Additional context**
I've got a chrome plug in 80% written that pops kimai out in a pop up that if triggered from a github issue uses the project and issue to identify the customer and project to log time against but I need to add some logic around the timesheet creation.

I have added the event dispatching in a branch in my fork but it results in a redirect loop. https://github.com/tobybatch/kimai2-app/pull/1/files

How do I stop the redirect loop? or is there a way of detecting timesheet creation I have missed?

**Comment by tobybatch** [comment]
@kevinpapst If events from timesheets is acceptable to you and I can solve the infinite redirect loop caused by https://github.com/tobybatch/kimai2-app/pull/1/files#diff-91d4021462425291d95a43517f957906R180 then I'll add the events for edit and delete, add some tests and put up a PR for you.

**Comment by kevinpapst** [comment]
Do you need it in the backend or in the frontend? Both are already existing. But it depends on what you want to achieve.

Frontend are simple JS events, eg. used here: 
https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiRecentActivities.js#L43

Backend events can be used in two flavours:

- Prefered way via Calculator: https://www.kimai.org/documentation/developers.html#adding-timesheet-calculator and examples here: https://github.com/kevinpapst/kimai2/tree/master/src/Timesheet/Calculator
- Also possible but not recommended (via Doctrine events), eg the class that triggers the Calculators:
https://github.com/kevinpapst/kimai2/blob/master/src/Doctrine/TimesheetSubscriber.php

Please try to avoid triggering an event yourself, as timesheet can be created/updated from various  entry points (API, user timesheet, admin timesheet...).

**Comment by tobybatch** [comment]
Thanks, that will do perfectly.

**Comment by kevinpapst** [comment]
Will we see this plugin or this is internal only?

**Comment by tobybatch** [comment]
It's for the world!  

Still very much a work in progress but if you are interested: https://nuget.pkg.github.com/neontribe/kimai-chrome-plugin

You'll need to add the unpacked chrome ext to point at https://nuget.pkg.github.com/neontribe/kimai-chrome-plugin/tree/master/chrome-extension

I thought about a JS based rest client but way too much work.

**Comment by kevinpapst** [comment]
Cool! I will have a look ...

**Comment by kevinpapst** [comment]
> [](https://nuget.pkg.github.com/neontribe/kimai-chrome-plugin)
> 
> You'll need to add the unpacked chrome ext to point at https://nuget.pkg.github.com/neontribe/kimai-chrome-plugin/tree/master/chrome-extension

Can you elaborate on this? Or add a step-by-step to the README?  I don't get what to do.

**Comment by tobybatch** [comment]
Sure, You need to load an unpacked extension into chrome.  See here: https://developer.chrome.com/extensions/getstarted

I really am hacking around this ATM but the chrome bit is pretty stable, it just loads a kimai into a pop up.  (I should really change the icon to the green arrow, it's still from the demo I copied).
