### ISSUE TITLE
Error on bin/console doctrine:schema:create

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#851]
Hi, I installed Kimai2 via git clone and composer, created a user account and database each named "Kimai2" via PHPMyAdmin and I configured the file .env as follows 
APP_ENV=prod
DATABASE_URL=mysql://kimai2:password@127.0.0.1:3307/kimai2

When I run the commend "bin/console doctrine:schema:create" the following error is shown: 
"Beendigungscode 255
PHP Parse error: syntax error, unexpected '?' in /bin/console on line 26"

I am unable to create the required tables - could you maybe provide the required sql-tables to be uploaded via PHPMyAdmin (or is there another way to fix it)?

**Comment by kevinpapst** [comment]
Could you run composer install? Which PHP version are you using?
The error indicates that there is something else wrong.

**Comment by BeckeBauer** [comment]
I am using php7.2

It was the first time that I used composer. Installed it on my Synology NAS and created a link in the installation folder of Kimai to the file composer.phar. The, I had to run 'php72 composer install...' (without php beforehand, I got an error message). It seemed to have installed all dependencies (folder vendor was created)
And hint what might have went wrong?

**Comment by kevinpapst** [comment]
I am pretty sure it has to do with your environment. I guess you are running an old version of PHP by default, otherwise you would not have to prepend php72.
What is the output of `php -v` and `which php` (without the 72!).

**Comment by BeckeBauer** [comment]
That was the right hint: had to prepend php72 to the commands; thus, instead of "bin/console doctrine:schema:create" I had to use "php72 bin/console doctrine:schema:create" and it worked
Thanks a lot
