### ISSUE TITLE
Ability to hide the revenue stats to users

### ISSUE THREAD

**Issue by yayitazale** [kevinpapst/kimai2#853]
**Is your feature request related to a problem? Please describe.**
I don't want to my users to see his revenue on dashboard.

**Describe the solution you'd like**
A button on admin config page to hide/show the revenues to users

**Comment by kevinpapst** [comment]
That was [fixed in master already](https://github.com/kevinpapst/kimai2/pull/843/files#diff-a4c4c3e459663533af7607848e15e457).
You can apply the changes manually to your config.

**Comment by kevinpapst** [comment]
https://www.kimai.org/documentation/dashboard.html
