### ISSUE TITLE
Create a Kimai app for Cloudron

### ISSUE THREAD

**Issue by jeau** [kevinpapst/kimai2#854]
Cloudron is a private cloud platform, a solution for running apps on your own server.
https://cloudron.io

It would be nice to add Kimai2 to the Cloudron applications and extend the 1-click installations solutions.

https://forum.cloudron.io/topic/1420/kimai-time-tracking

unfortunately, I don't have now the Docker expertise to do it :(

**Comment by kevinpapst** [comment]
And I don't know Cloudron. 
LDAP support is available in master (if that is necessary for Cloudron) and Docker images are available for Kimai.
We need an experienced Cloudron user who can take over.

**Comment by kevinpapst** [comment]
Fixed by @nebulade and documented in https://github.com/kimai/www.kimai.org/pull/36
