### ISSUE TITLE
Department under client

### ISSUE THREAD

**Issue by yayitazale** [kevinpapst/kimai2#855]
**Is your feature request related to a problem? Please describe.**
We need to define a department who is asking for an activity under certain clients, so we need to add the option at entry creation page.

**Describe the solution you'd like**
Now we have _Client->Project->Activity_ schema, we need a _Client->Department->Project->Activity_ schema.

**Describe alternatives you've considered**
Another way to achieve this is to add a custom box under description on time entry creation page to define the name of the person or the departament who is asking for that activity.

**Comment by kevinpapst** [comment]
The schema won't be changed. 
But you can vote for #760 (custom fields for timesheets) with a 👍 in the initial post and also watch the issue so you get a notification when I start working on it.
Or you use tags for that, one tag "Requested by" and one with the name of the department...

**Comment by kevinpapst** [comment]
Custom fields are coming soon, see #871
