### ISSUE TITLE
Allowed memory in reset-dev

### ISSUE THREAD

**Issue by pvsaintpe** [kevinpapst/kimai2#857]
Hi, I have a problem with loading demo-data

**Describe the bug**

bin/console Kimai:reset-dev
N
Y

```
   > loading App\DataFixtures\TimesheetFixtures

 // Clearing the cache for the dev environment with debug true                                                          

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /Users/pvsaintpe/test/symfony4-app/vendor/twig/twig/src/Node/Expression/ConstantExpression.php on line 21
PHP Stack trace:
```

**Additional info**
1. MacBook Pro  + MariaDB (brew) + php 7.3.6

**Solution (Huck)**
```
php -d memory_limit=2G bin/console kimai:reset-dev
```

It's worked.

But is not a right way, maybe....

**Comment by kevinpapst** [comment]
Hi @pvsaintpe !
128MB seems to be a lot of memory on the on hand, but on the other hand this is a developer command: creating a lot of in-memory data, especially the TimesheetFixtures and I can't change the way Doctrine is handling the fixtures. 

The memory consumption will stop at one point and not rise, but I never cared to researched where that point is. But I can tell you, that I recently created a database with 1.5 million timesheet records and the memory never went above a certain threshold - so there is no "real memory leak".

**Comment by kevinpapst** [comment]
Thanks for sharing your experience! I don't think there is much to do here, so I close the issue.
Hopefully it will someone else with the same problem in the future.
