### ISSUE TITLE
Database migration from 0.9 to master

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#858]
Hi, I am using Kimai 0.9 (latest stable) and installed in addition the Development version . Is it possible to migrate the existing database from 0.9 to the dev version for testing?
(I created an empty database and copied the tables from 0.9 database to it and then tried "bin/console doctrine:migrations:migrate" without success)

**Comment by kevinpapst** [comment]
A tag in nothing else then a freezed point in time in git.
So there is no difference between an "official release" and the current master.
Just perform your update as documented.
I am not going to explain anything else, as this would cause people without technical background to try it and I am neither interested in these help requests nor do I want more noise in the issue tracker - as this would steal my free time and wouldn't improve Kimai in any way.
