### ISSUE TITLE
Authentication request could not be processed due to a system problem

### ISSUE THREAD

**Issue by diogojesus95** [kevinpapst/kimai2#861]
**Describe the bug**
After creating a first user I get the following "Authentication request could not be processed due to a system problem." when trying to login. Also If I create my user trough the web interface I get 500 error

**To Reproduce**

Follow the install instructions on a debian 9 machine (apache and php7.2)

**Logfile**
Error log file is empty

**Additional context**
 - Kimai2
 - PHP 7.2

**Comment by kevinpapst** [comment]
Can't help without logs. There must be either Kimai logs or webserver/php logs.
Without any more infos: it is a misconfigured database connection or wrong file permissions.

**Comment by tobybatch** [comment]
@diogojesus95 if you have no logs then I'd check file permissions on the var folder. They should be writable by your web users.

**Comment by diogojesus95** [comment]
After a clean install I was able to install. I don't know what the error was but it's all good now
