### ISSUE TITLE
Capacity planning

### ISSUE THREAD

**Issue by Stadly** [kevinpapst/kimai2#866]
Capacity planning would have been a great addition to Kimai. Have you considered this? I imagine a way to plan how much time each user or team will use on each project the coming days/weeks/months.

There should be an overview on how the planned time compares to the time budget on each project.

There should be an overview on how the planned time compares to the capacity of each user or team.

**Comment by kevinpapst** [comment]
I don't think this fits very well into a time-tracking app, which I see more on the HR side than on the project management side, but I understand that people would like to have everything in one app.

But please share your vision!

**Comment by Stadly** [comment]
Thanks for your feedback @kevinpapst!

I don’t consider Kimai as just a time-tracking app, as it also includes project management features (as you can e.g. specify a budget for your projects and you can prepare invoices to your customers etc.). In fact, we use Kimai mostly for project controlling.

What we are currently doing outside of Kimai (that would be nice to integrate) is a way to differentiate the currently existing field `time budget` that you can also specify per project. We currently distribute the days we plan to work on a project over the involved team members and time (monthly) in a spreadsheet.

That way, we can see two things:
1. Who has to much work on his plate for upcoming months (i.e. more project days assigned than he will be able to handle).
2. Who can be assigned to a new project, given the not yet used resources of the person.

It would be nice to integrate this so we don’t have to copy-paste back and forth the project names etc. (major hassle of our setup).

**Comment by kevinpapst** [comment]
Hi @Stadly - the task management plugin has planning features that allow some forecasts.

Tasks allow to add estimations and there are reports available in the latest versions, which help to plan ahead.
I am closing here, as I have no plans to add planning features to Kimai core.
