### ISSUE TITLE
LDAP Documentation Enhancement for Active Directory

### ISSUE THREAD

**Issue by firegore** [kevinpapst/kimai2#867]
Greetings,

i tried to connect our AD to Kimai.

The Documentation was already very helpful with that, however it's missing one Mandatory Option (atleast for us on Server 2012 R2)
you need to set 

user:
    usernameAttribute: samaccountname

Otherwise you always get "password wrong".

Also it would be helpful if there was a note that the LDAP Fieldnames in "usernameAttribute" and "ldap_attr" NEED to be lowercase otherwise it won't work (as the LDAP Attributes include CamelCase in AD and i had never issues with this).

Regards

**Comment by kevinpapst** [comment]
Oh great, an AD user! I updated the docs to reflect your findings.
Was it only the `usernameAttribute: samaccountname` you had to add (besides configuring your customer structure)?

Regarding lowercase, see the big yellow box below the example:
https://www.kimai.org/documentation/ldap.html#user-attributes
No matter where and how I will place this, people will miss it - at the end its boring documentation ;-)
But I added a second box at the end beneath the AD example.

**Comment by firegore** [comment]
It was the only attribute that wasn't in the Docs, attached is the full Config i used.

Oops, i guess i missed the obvious ;)
That was the only part of the whole site that i didn't read, thanks for the Heads-up tho!

`kimai:
    ldap:
        connection:
            host: 
            username: [DN]
            password: 
            accountDomainName: main.htl-perg.at
            accountDomainNameShort: MAIN
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))

        user:
            baseDn: [XXX]
            usernameAttribute: samaccountname
            filter: (&(objectClass=Person))
            attributes:
                - { ldap_attr: "mail", user_method: setEmail }
                - { ldap_attr: "displayname", user_method: setAlias }
        role:
            baseDn: [XXX]
            filter: (&(objectClass=group))
            groups:
                - { ldap_value: Leads, role: ROLE_TEAMLEAD }
                - { ldap_value: Sysadmins, role: ROLE_SUPER_ADMIN }
                - { ldap_value: Users, role: ROLE_USER }`

**Comment by kevinpapst** [comment]
I linked the word "example" to your gist:
https://www.kimai.org/documentation/ldap.html#connect-to-active-directory
so would be cool if you keep this alive.

Thanks again for your input!
