### ISSUE TITLE
Selective filtering options among the list 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#870]
The current filtering allows one to choose all or choose one of the options among the list. This feature request is to allow selective filtering like if there are 10 items in the list I would like to select 1 to 4 and exclude the rest from the selection. This could help with analysis or displaying results of what one wants to selectively looks at. Having this across all of the columns used for filtering would widely increase the analysis capabilities of kimai.

**Comment by kevinpapst** [comment]
Can you remember what you meant with this @rarvin ?
Is this about selection in search/filters? If so #1557 would fix this as well, right?

**Comment by rarvin** [comment]
@kevinpapst Give me a days time I shall check and come back

**Comment by rarvin** [comment]
@kevinpapst I think the other feature request was for project, customers and activities and this was for the filtering in the timesheet and export views. Since with #1557 you have done this for everything so that satisfies all requirements. But while testing on the new version I could see that in the invoice page you have restricted the choice to just customer and project. Kindly provide us the other filtering options too which allowed for activity user etc. Please help, we greatly use those things.

**Comment by kevinpapst** [comment]
Many users only need to select customer/project/timerange => so this is the new simplified view.
But you can configure it back to show all search options. Click the gear icon in the upper right, thats where you configure invoice numbering as well.

**Comment by rarvin** [comment]
Thanks kevin, i did see that but failed to observe the simple search option. Thanks again for this.
