### ISSUE TITLE
Option to exclude timesheet tasks/entries from calculation without deleting them completely from the system

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#872]
Right now all timesheet task are included by default in the various calculations, if they are to be removed from calcuation the option available is that they may be deleted. Would like like an option to exclude a timesheet task/entry from being used for calculation. 

Example would be  
In the mytimes, the sum for one day would be all timesheet tasks or entries created in that day. I should be able to exclude certain entries and be able to see the sum without those entries used in calculation.
The same idea may applied to look places too. More like a billable or use for calculation flag. A hide record from calculation button. :)

**Comment by kevinpapst** [comment]
Please vote via 👍 on #415 for the billable flag. 
Closing, duplicates #415
