### ISSUE TITLE
Admin Timesheets Toolbar: order users by username

### ISSUE THREAD

**Issue by cgx** [kevinpapst/kimai2#876]
**Is your feature request related to a problem? Please describe.**
The select input form field to filter users is order by id.

**Describe the solution you'd like**
It would be much more convenient to order the users list by username.

**Additional context**
Affects administrators only.

**Comment by kevinpapst** [comment]
If you would have asked me, I would have placed a bet that the users are already sorted by username...

Really strange they weren't, but that was easy to fix...

Thanks for posting 👍 I added that "feature" in PR #880 .

**Comment by BuzzDausBerlin** [comment]
So is this fixed in 1.1? Because when applying a filter in the timesheet-menu, the users in the dropdown-menu are still sorted by ID, not by name?

**Comment by kevinpapst** [comment]
Nope, I mis-read the ticket. 
I fixed the order on the users admin page, not in the toolbar.
Will be fixed with the Team permissions, I already changed it in the branch.
