### ISSUE TITLE
Feature Request - Invoice sum per day

### ISSUE THREAD

**Issue by Mikesch-mp** [kevinpapst/kimai2#879]
If possible can we get a "sum per day" option for invoices/timesheets?

Sometimes i have multiple entries per day for the same customer/project/activity and need a report for the customer that sums all activities per day. So that i have 1 line per day with the hours i worked.

Thanks,
Carsten

**Comment by kevinpapst** [comment]
> Invoice sum per day

vs 

> same customer/project/activity and need a report for the customer that sums all activities per day

What exactly do you want? All records for one day (and customer), merged into one line OR all records for the same day (and customer, project and activity)?

Thats a big difference...

Lets say;
- Customer A
- Customer B
- Project A1
- Project A2
- Project B1
- Activity A1A
- Activity A2A
- Activity AxB (global)

5 records:
- 01.01.2019 A / A1 / A1A
- 01.01.2019 A / A1 / AxB
- 01.01.2019 A / A2 / A2A
- 01.01.2019 A / A1 / A1A
- 01.01.2019 A / A2 / AxB
- 01.01.2019 B / B1 / AxB

Results:
- 01.01.2019 A / A1 / A1A
- 01.01.2019 A / A1 / AxB
- 01.01.2019 A / A2 / A2A
- 01.01.2019 A / A2 / AxB
- 01.01.2019 B / B1 / AxB

or

- 01.01.2019 A / ?? / ???
- 01.01.2019 B / ?? / ???

**Comment by Mikesch-mp** [comment]
For now only a report that sums all activity  per day in one line for a customer.
Maybe for future development add abillity to sum per customer + project or customer + project + activity.

**Comment by kevinpapst** [comment]
merged to master, will be available with the release later today
