### ISSUE TITLE
Exporting - Minutes output or a Summery of hours when filtering

### ISSUE THREAD

**Issue by stoberblog** [kevinpapst/kimai2#882]
**Is your feature request related to a problem? Please describe.**
When using the export function, the way time is currently presented (##:## h) is very hard to use in excel (or similar). 

**Describe the solution you'd like**
I'm proposing, another column is added (or can be set up) to just export minutes, and with a decimal point and not character suffix. This would mean the column could be selected and summed very easily.

**Describe alternatives you've considered**
An alternative, would be to have a summary of the hours/minutes performed once a filter has been added in the export (eg Project A, between date B and date C).

**Comment by kevinpapst** [comment]
I don't have Excel, just the Apple Calc called "Numbers" ... but there it took me 30 seconds to add a new column "C" with the Formula "B2-A2" and auto-completed that for the complete table + one more sum for this newly created column.
Et voila, the duration was there for all exported entries in less than a minute.
It shouldn't be much harder with Excel I guess.

**Comment by VOOM108** [comment]
I have a similar issue. In Kimai1 there was a variable exporting the times in decimal like so: 
4,5 h (= 4:30 h)

One customer requires me to log the entries like that. The templates are not Excel but .docx so I can't calculate it from other variable data (or can I e.g. in Libreoffice Writer?)

**Comment by kevinpapst** [comment]
If someone wants to try it: you need to add a new line here:
https://github.com/kevinpapst/kimai2/blob/master/src/Export/Renderer/AbstractSpreadsheetRenderer.php#L174
the defined variable will be available in all export renderer (spreadsheets, not pdf).

**Comment by BeckeBauer** [comment]
A working solution would be:
Line 174: ```$sheet->setCellValueByColumnAndRow($entryHeaderColumn++, $entryHeaderRow, number_format($timesheet->getDuration() / 60));```
Output will than be minutes 
In Excel: 
```=A1/(24*60)``` (A1 must be substituted with the cell where the minutes are shown) then format the cell as ```hh:mm``` (or whatever time format you like)

**Comment by kevinpapst** [comment]
`begin` and `end` date are DateTime objects: https://www.php.net/manual/de/class.datetime.php
So you can format them as you want: `$timesheet->getBegin()->format('Y-m-d')`

**Comment by BeckeBauer** [comment]
Perfect, thank you!

**Comment by kevinpapst** [comment]
Please post all your additions later on, so I can add them to the core version.

**Comment by BeckeBauer** [comment]
I modified the AbstractSpreadsheetRenderer.php according to our internal needs. For the date field I added a new line 116
```$sheet->setCellValueByColumnAndRow($recordsHeaderColumn++, $recordsHeaderRow, $this->translator->trans('label.date'));``` 
and a new line 155 
```$sheet->setCellValueByColumnAndRow($entryHeaderColumn++, $entryHeaderRow, $timesheet->getBegin()->format('d.m.Y'));```
Now, exports start with a row "Date"

**Comment by BeckeBauer** [comment]
By the way, I just noticed two missing ++ in row 175. If you use this line before the last row, the code should be ```$sheet->setCellValueByColumnAndRow($entryHeaderColumn++, $entryHeaderRow, $this->getFormattedMoney($timesheet->getRate(), $customerCurrency));``` (two "+" after $entryHeaderColumn)

**Comment by kevinpapst** [comment]
They are not missing, but absent on purpose.
But yes, the line should not be appended without noticing that, thats why I linked line 174 😆

**Comment by kevinpapst** [comment]
Please have a look at #1046 - I added two columns to the export and changed the data format.

**Comment by Stadly** [comment]
I just got a similar request from my co-workers. They would like to have the following columns in the exported Excel files:
1. Date shown without time.
2. Duration shown as number of hours (with decimals).

**Comment by Stadly** [comment]
> They are not missing, but absent on purpose.
> But yes, the line should not be appended without noticing that, thats why I linked line 174 😆

It wouldn't harm to include `++` on the last line as well, and it would make it less error-prone :) If you really want `$entryHeaderColumn` to equal the number of columns for some reason, I suggest starting with `$entryHeaderColumn = 0` and using `++$entryHeaderColumn` everywhere instead. The same goes for `$recordsHeaderColumn`.

**Comment by kevinpapst** [comment]
@Stadly please check #1046 both for the changed code and the updated Excel document on export
