### ISSUE TITLE
Add just the amount of hours worked per day

### ISSUE THREAD

**Issue by diogojesus95** [kevinpapst/kimai2#883]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Depending on the company environment not all companies require a timesheet that accurate.

For example instead of adding that I started at 8am on June 26th until 10am on June 26th, I could simply add June 26th 2h.

And that would save me a lot of time by the end of the month when adding all the hours.

If there was a way to implement a check box under the date and time to just add the day and the amount of hours worked under a project would be perfect for our current needs and would save us a lot of time when adding this to our timesheet.

Thank you,
Diogo Jesus

**Comment by tobybatch** [comment]
@diogojesus95 You can turn on duration only.  This allows you to just select a start date and a time.

https://www.kimai.org/documentation/timesheet.html#duration-only-mode

**Comment by kevinpapst** [comment]
There are feature requests regarding a quick mode using a calendar like view to input all the days at a glance, Thats maybe what you want in the end, check the open issues and vote for it.

Until then: 
- change the tracking mode as mentioned by @tobybatch 
- use the calendar view, either monthly to open a new task for the selected day or even quicker: select a time range in the weekly view, which will pre-fill the date and times

I am closing this as duplicate, as there are similar requests existing and your request is actually already possible.
