### ISSUE TITLE
Signout in addition to log out

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#886]
Currently the logout option in Kimai logs out the user from the current session but this does not in any way affect the current running tasks and Kimai tracks the time in the background. This is a great functionality present in the tool and really needed for all of us. What would be great would be an additional signout button. When a user clicks the signout button the user would not be logged out but all tracking that is currently active would all be stopped in one go. This would be really useful as users who would like to stop all activities when they leave work for a day or take a break could just signout and then log off from Kimai. 

An added pop up asking them confirm that all tasks would be stopped would also be be nice when they click on signout to prevent accidental closure of all tasks. 

Any name could be used instead of signout like stop all or sign off or anything. 
A similar feature is now being built into clockify and having such a functionality Kimai would be of great use for most users.

**Comment by kevinpapst** [comment]
Hm, the easiest solution I can think of: when the user clicks logout
- check if a task is still active 
  - if so, show a confirm dialog that allows to choose "logout" or "stop all running tasks and logout"

**Comment by kevinpapst** [comment]
Not one vote, closing
