### ISSUE TITLE
Configurable default date-range for initial filter in export, invoice and team-timesheets

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#887]
Currently when clicked on the export view it defaults to load the data present in Kimai for a month. Due to the presence of large number of records it takes quiet a lot of time for the page to load. I have seen this more with chrome than Firefox. In most cases we want to just see a days worth of data for exporting but can’t choose any options till the whole page loads which take like around 3 minutes. Could you please change the way export page works so that no data is displayed by default or it just shows only one days worth of data so that the page loads quickly. 

Also the filter options works or starts fetching data when one option is selected, in our case we would like to have multiple filtering by a specific user and for a specific day. The view starts fetching when one option is itself selected and one has to wait for the results to be shows before we could select the next filter criteria. Could you please change this since when there is considerable data in the system it could be very slow.

Change default export to just one day as default or not display anything till chosen.
As well as change the selection to accept all filter options before starting to fetch records. Even if the first option is done it would be good for us.

**Comment by kevinpapst** [comment]
I made some adjustments, so that large amounts of data should render much faster:
https://github.com/kevinpapst/kimai2/pull/874

You should also compare this page to yours: 
https://demo-branch.kimai.org/en/export/
to see if this might be a hardware or configuration issue.

**Comment by rarvin** [comment]
Thanks kevin, I shall check once the new version is released.

**Comment by kevinpapst** [comment]
ping @rarvin 1.0 was released today

**Comment by rarvin** [comment]
@kevinpapst There is considerable difference. I could see that the page now loads in around 25 to 30 seconds now, but we are at the start of the month and it would only be fetching data for the last 5 days. So the best way to check would be at the end of the month. This is now okay for us. But the team would provide some better insights on monday when they are back to work. Would update again. During my test by choosing the data range for the complete month of June it still rendered the data in around 30 seconds time. And while exporting i could see the record count to be around 32000

**Comment by kevinpapst** [comment]
There is still room for improvements, but only if you have many customer/project and activities. 
Those did not receive the speed improvements, which I applied for timesheets.
But I am happy to see that there are first positive results!

Rendering so many entries in the browser is extremely slow (on the client side), so having a configuration for the date-range might help as well => thats why I changed the title.

Still wondering if it might be a server or PHP configuration issue, as the load time on my server is so much faster.

**Comment by rarvin** [comment]
Dear @kevinpapst ,
Today we are on the 30th of July, 2019 and have one complete month of data in the system. And the export screen took around 7 minutes to render and show all of the drop down options. When i tried exporting using the xls option it threw the following error
Oops! An error occured.
500: Internal Server Error
An unexpected error occured, please try again. You may have found a bug, so please contact your administrator if the problem doesn't go away after you tried it again.

But when i try downloading using the csv option it downloaded and the file size was 5.8MB. Containing around 35800 records in total.

I think changing the option to show a days data by default would be nicer, since waiting for 7 minutes is quiet a long wait.

**Comment by rarvin** [comment]
Just to let you know even the ODS option failed for the same download for a month. When the range was reduced to a day, or a week, the export as xls and ods options successfully downloaded the files. Downloaded file size was around 200KB

**Comment by kevinpapst** [comment]
Okay, well yes: 7 minutes is too long. You are generating quite a lot of records!

I will add two things: a default range and also a limiter, which will stop after 500 rows latest. 
The download is another topic, I guess you run into memory issues. 
Can you check your Kimai logs and PHP logs as well please, after the download stopped.

I am not sure if I can fix everything. 
At some point the performance is limited by the hardware and server setup/configuration as well.

**Comment by kevinpapst** [comment]
@rarvin please check #1046 
I changed invoice and export pages. By default the preview will not be shown and the filters can be changed without reloading.
