### ISSUE TITLE
Keyboard shortcuts for starting stopping tasks

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#888]
Having keyboard shortcuts to start stop restart tasks could be a great functionality.

**Comment by kevinpapst** [comment]
Please expand your ideas.
Clear to me is:
- stopping if only ONE entry is running
- starting a new entry by opening a record
But all the others? What should happen?

**Comment by rarvin** [comment]
In general it would be like 
Shortcut to stop all active tasks, same way if the same shortcut is used it starts the same tasks that were stopped. If the operator uses the gui and stops a task individually then only the last stopped task would be started and vice versa. So it’s basically a last action recreator. Using this operator could stop all active tasks, comeback and restart all last stopped tasks. There is a possibility doing this is going to be too complicated and maybe not worth the effort. We mostly use this in a single task at a time environment so managing that with keyboard shortcuts might be easier.

**Comment by rarvin** [comment]
If multiple selection options are provided like a checkbox selection, then it’s makes it easier to select them in one go and use keyboard shortcuts to start or stop them

**Comment by kevinpapst** [comment]
Fore reference https://www.hongkiat.com/blog/keyboard-shortcuts-website/

**Comment by kevinpapst** [comment]
There was no vote yet and I have no plans to add such a feature, closing
