### ISSUE TITLE
Use partition tables in MySQL for easier achiving of data

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#889]
As data volume increases there would be a need for a simple mechanism of archiving or removing data. Having data kept in a partition table could help with easy removal of data by dropping the partitions that can be archived or removed. This can help keep the Kimai system lean and also help users not keep records beyond any compliance mandates that they have to meet.

**Comment by kevinpapst** [comment]
How many entries do you plan to have? 
Unless we are talking about multiple millions of records, I don't see any reason for this.
Lets talk about other performance improvements first.

If you need to delete old data, delete it with date filters.

I am closing this, as it is completely out of scope for me. But thanks for the idea nevertheless!
