### ISSUE TITLE
expense tracking

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#893]
**Is your feature request related to a problem? Please describe.**
It would be great to also track non-time related entries related to a customer / project like expenses and to have them separately shown on the invoice. 

**Describe the solution you'd like**
There could be a predefined activity, for example 'expenses' (or another term maybe defined by the user in the kimai.yaml), where - when used - just the date is recorded without a start time and stop time or duration. 

In the invoice, such entry(ies) is listed at the end but at least in a second line after a line of added up hours.

**Comment by kevinpapst** [comment]
Duplicates #351 - so closing.
Can you please vote with a 👍 in the first posting in #351.
