### ISSUE TITLE
Add times duration and Rate of running task to summary

### ISSUE THREAD

**Issue by tquast** [kevinpapst/kimai2#894]
It would be great if the duration and rate of the current running task was added to the summary in the "My times" and "Dashboard" view. Or if it were at least configurable ('add running task to summary = yes / no')
![grafik](https://user-images.githubusercontent.com/23353547/60415291-01b08700-9bdb-11e9-9abe-c69881d39faa.png)

**Comment by tquast** [comment]
I fixed it myself for the "My times" view. If you're interested in the code...let me know.

**Comment by kevinpapst** [comment]
Yes please sent a PR. Thats the idea of open source software  👍
