### ISSUE TITLE
Update Spanish translation

### ISSUE THREAD

**Issue by kevinpapst** [kevinpapst/kimai2#898]
The following translations are currently missing from Spanish:
```bash
$ bin/console debug:translation --only-missing es
 ----------- ---------- ---------------------------- ---------------------------- ------------------------------------- 
  State       Domain     Id                           Message Preview (es)         Fallback Message Preview (en)        
 ----------- ---------- ---------------------------- ---------------------------- ------------------------------------- 
   missing    messages   recent.activities            recent.activities            Restart one of your last activities  
   missing    messages   label.timeBudget             label.timeBudget             Time budget                          
   missing    messages   invoice.total_working_time   invoice.total_working_time   Total duration                       
   missing    messages   label.unit_price             label.unit_price             Unit price                           
 ----------- ---------- ---------------------------- ---------------------------- ------------------------------------- 
```
There might be more, the debug command cannot find all missing translations.

**Comment by kevinpapst** [comment]
@yayitazale do you have time and think you can help to update them?

**Comment by yayitazale** [comment]
Done.

**Comment by yayitazale** [comment]
You have been promoted:

https://ethical.net/resources/?resource-category=team-collaboration-software

Cheers

**Comment by kevinpapst** [comment]
Hm, I got a comment via email but can't see it here, thats strange...
Well, nevertheless, thanks for posting at ethical.net 👍

**Comment by yayitazale** [comment]
There is a not translated string that I can't find on translate archives.

![2019-07-10 115602](https://user-images.githubusercontent.com/6462849/60960147-bc423700-a309-11e9-897a-49dfe107f512.jpg)

**Comment by kevinpapst** [comment]
True, its not translatable right now. 
I don't use the Javascript select and use Kimai mostly in english to find problems, so I missed it.
