### ISSUE TITLE
No Timeclock mode?

### ISSUE THREAD

**Issue by fizgig10** [kevinpapst/kimai2#903]
Documentation appears to suggest a "time-clock" mode is available but I don't see it listed. 

 - Kimai version:  2 v0.9
 - PHP version 7.2 I think

**Comment by kevinpapst** [comment]
Can't remember when it was added. Maybe there is a "added with 1.0" missing.

You can find it in the system configuration screen:
<img width="553" alt="Bildschirmfoto 2019-07-01 um 22 22 18" src="https://user-images.githubusercontent.com/533162/60464379-b59f2a00-9c4e-11e9-91b7-73d9e27e4686.png">

I will release 1.0 within the next two days. If you don't want to wait, use the latest master.

**Comment by fizgig10** [comment]
Thanks!  1.0 appears to have the option.  Going to go play with it now and see what it can do! :)

**Comment by kevinpapst** [comment]
Thanks for the info, I updated the docs and added the missing version constraint.
