### ISSUE TITLE
Update the web UI when current recording stopped from API

### ISSUE THREAD

**Issue by infeeeee** [kevinpapst/kimai2#904]
**Is your feature request related to a problem? Please describe.**
I don't know if it's a bug, or is it necessary at all.

I started using the API, and I noticed if I stop one or all recordings from the API the counter in the title doesn't stop. It's because the webUI is not reloaded.

**Describe the solution you'd like**
The webUI reflects changes from the server, for example updating every minutes, or using some realtime framework like [socket.io](https://github.com/socketio/socket.io) where the server can ping the frontend but I don't know if something similar exists for php.

**Describe alternatives you've considered**
I'm not sure if it's needed at all. It's not a big annoyance, and the use case for checking the webui and using the API at the same time is really rare.

But considering your plans with hardware support (#829) an other use case would be that an employer can see in realtime which workers are already started working. Now on Admin->Timesheets it's only updates when I reload the page.

**Additional context**
I started working on a command line client for kimai, you can check it out here: [kimai2-cmd](https://github.com/infeeeee/kimai2-cmd). I used the demo server for testing, and found this "bug" there

**Comment by kevinpapst** [comment]
Hm, websockets could be used.  But the trouble is with the setup. Afaik you can't use a simple Apache/Nginx vhost for that, but I am not really sure. I do understand the background, but never used it.

Or we use the poor mans solution: polling with JS each minute. With some clever caching this shouldn't be too expensive. Neither clever nor interesting, but might work.

If web sockets would be used, I assume that this small "bug" (I would call it a feature request, as it could be used for other cool features) will lead to a bigger refactoring. 

But it could be very useful, as many other cool features could be based on this...

**Comment by kevinpapst** [comment]
Closing. Good idea, but not worth the time, considering how many open feature requests are pending.
If anyone finds this topic and wants to work on it, I can help and will review a PR.
