### ISSUE TITLE
Feature Suggestion: Document How To record login/logoff events

### ISSUE THREAD

**Issue by DeftNerd** [kevinpapst/kimai2#911]
I'm a system administrator and it's useful to keep track of how much time I spend connecting to a system to do various maintenance tasks. 

While some time trackers come with a desktop client that keeps track of what you do and logs it for you, until one is available for Kimai2, one alternative is to configure the servers you connect with to log the start of the connection and the end of the connection. 

Here are some possible solutions. They might be helpful to anyone that searches the issues, or you might want to document them somewhere more visible. 

If you install the libpam-script package on your server, you can create a system-wide scripts that execute at various times like login, logout, password change, and a bit more. There is some documentation [in this github repo](https://github.com/jeroennijhof/pam_script)

The scripts can be easily configured to curl the Kimai2 API to track your login and logoff.  

That's a system-wide solution, and if anybody else ever logs into the system, your time sheet will reflect their work.... So it might not be useful all the time. 

For scripts that execute for a specific user, assuming that they're using the bash shell, they can put a login API call in their .bash_profile. For logoff API hits, you can create an executable .bash_logout script in your home directory and it'll be run every time you type exit or logout.

**Comment by kevinpapst** [comment]
Thanks for stopping by @DeftNerd !

Your idea is an interesting approach. Personally I don't like these automatic timetrackign apps, that record each program, usage website ... but there are so many different use-cases, its great to see which ideas come from the community. 

Unfortunately I am not really sure what your request is:
Did you wanted to share this info with us?
Or do you want to share a documentation for the website how to set this up?
Or do you need help in setting this up?

**Comment by kevinpapst** [comment]
@DeftNerd I re-read your text and understand now that you wanted to share your solution. Thanks!
I would write a HowTo for the documentation section and having some config examples would make it even better. Can you share some?

**Comment by kevinpapst** [comment]
Don't know how to proceed, no feedback, closing
