### ISSUE TITLE
stacked working hours graph

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#916]
**Is your feature request related to a problem? Please describe.**
If you track times in parallel the graph of "Your working hours" shows more than 30 h/day.

**Describe the solution you'd like**
Per day there shouldn't be single bar, but a bar per project per day.
For me it's more logical like this. What do you think?

**Additional context**
![Unbenannt](https://user-images.githubusercontent.com/36242595/60670517-2a51ae80-9e71-11e9-8d5d-fa06b57be64d.png)

**Comment by kevinpapst** [comment]
Strange edge case 😕 but true.

Having a stacked bar would definitely be nicer, I already see the next request please split it by activity ^^

**Comment by infeeeee** [comment]
How about stacking them on top of each other, based on the color of the project? Instead of separate bars for separate projects. This way it's sum is still visible. Something like this: 

![image](https://user-images.githubusercontent.com/1271737/60679069-b28e7e80-9e86-11e9-97d9-4bcd9d88a4ce.png)

Of course split by activity would be nice as well, I really would love to see more graphs and charts in kimai. But  'your working hours' is a very nice start!

**Comment by kevinpapst** [comment]
>  I really would love to see more graphs and charts in kimai

Me too, and they will come. Please open requests if you have good ideas. I know the Dashboard has great potentials and is currently painfully under-used.

Back to the stacked chart:
What do you think is better: grouped by project or by activity? 
Talking about weekly or monthly charts I'd say projects is better, but daily?

**Comment by rarvin** [comment]
Having a toggle list  somewhere which can be turned on to see by activity by customer, project, activity or tags or any custom field value might be nice. 

Similarly the same view showing the timerange of day week month would make it more usable.

**Comment by kevinpapst** [comment]
Here is an example fo a stack chart on the dashboard. It is grouped by activity. It will use the colors that are used in the (activity/project/customers) dots as well, besides that the default color is not grey but blue for the charts.
<img width="1082" alt="Bildschirmfoto 2020-08-15 um 17 39 02" src="https://user-images.githubusercontent.com/533162/90315770-55d11480-df1e-11ea-909c-40121c138dc7.png">
And as you see, the tooltips changed. They always target the single stack group but you still need to see the daily total.

I'll setup a demo soon. But what do you think from that first glance?
