### ISSUE TITLE
default value for end of visible time range is not valid

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#917]
**Describe the bug**
Try to change something in the Calendar settings. It won't work.

**To Reproduce**
1. Go to https://demo.kimai.org/de/admin/system-config/update/calendar
2. Change some time but not "End of visible time range"
![grafik](https://user-images.githubusercontent.com/36242595/60670903-135f8c00-9e72-11e9-90fa-23ef5b6b1aeb.png)

3. See error

I think the default time for "End of visible time range" should be "23:59".
If you hit save you have to scroll manually down, it would be cool if Kimai could scroll down automatically.

**Comment by kevinpapst** [comment]
👍 fix attached
