### ISSUE TITLE
Activity drop-down not listing data in Kimai v1.0 for older browsers but works well in new

### ISSUE THREAD

**Issue by resstm** [kevinpapst/kimai2#929]
We had migrated to Kimai v1.0 from v0.9 today and in some of the systems using older browsers, after selecting the customer & project details, the activity dropdown field is coming as empty. This was not happening in the previous Kimai version(0.9) on the same old browsers. Having said this, for the newer version of browsers, all works fine. We're having to use old Mac systems running the maximum supported Firefox versions as they are loaded with old Adobe software which will not work on the new OS and is very expensive due to Adobe's subscription rates. As over 13 operators are unable to make use of Kimai due to this, after the upgrade today, we request you to kindly help us find a solution. 
      
While testing out different features in version 1.0, we added a new global activity. Strangely enough, that alone is getting populated in the activity list.

All the other existing functionalities along with the new ones like 'Tag' option are accessible to the operators. They're also able to edit the existing entries but are unable to add new ones due to this problem. Similarly, they are unable to restart the existing task also and it throws up an xml exception. Screenshot of both the errors are attached.

![kimai-1](https://user-images.githubusercontent.com/51189640/60811500-0235b880-a1ad-11e9-885b-f37175e4d2fe.jpg)
![kimai-2](https://user-images.githubusercontent.com/51189640/60811506-0661d600-a1ad-11e9-9223-d52df079ef09.jpg)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: MAC OSX 10.5
 - Browser [Mozilla Firefox 29.0]

**Comment by kevinpapst** [comment]
Please confirm that this happens also on demo.kimai.org, credentials here:
https://www.kimai.org/demo/
For the meantime, deactivate the Javascript inputs and see if that fixes your issue (Administration:  Settings).

**Comment by resstm** [comment]
Yes. We tried both. The issue is also there in the demo. Also, deactivating javascripts does not solve the problem. Only global activities are getting listed in the demo site as well as in ours.

**Comment by kevinpapst** [comment]
For me its working as expected, so I need your help...

Please be more specific, as I don't understand the problem.
You tried with old browsers? Or new ones? Both?
Are all dropdownas (created, edit, filter) affected?
You know that the activity dropdown is pre-populated with global activities only, project specific are fetched when a project is choosen.
What happens when editing existing timesheets with a none global activity?
Is something in your javascript console?

**Comment by resstm** [comment]
The person has left for the day
> For me its working as expected, so I need your help...
> 
> Please be more specific, as I don't understand the problem.
> You tried with old browsers? Or new ones? Both?
Tried both browsers. old as well as new, on new, it works fine on the old ones we have the problems as I have listed above when i try to select an activity (nothing is listed except global activity), or when i try restarting an activity or even deleting an activity.
> Are all dropdownas (created, edit, filter) affected?
yes all are affected
In the filter option if i choose customer the next project option does not allow me to select anything, blocked.
For edit I am able to open the edit view and all fields are populated, but when i change the project or customer filed the activity field values dont change and still the old values from when i opened the edit screen is listed. Looks like it is not fetching the records. 
> You know that the activity dropdown is pre-populated with global activities only, project specific are fetched when a project is choosen.
so even if i choose the customer and project they are not getting fetched then
> What happens when editing existing timesheets with a none global activity?
It does not fetch the records allowing me to change anything. If I choose one of the other values from what every is prepopulated under the activities list, I am able to save the edit record and it gets changed to it.  But if i change the project and choose something from activity (the ones from the last fetched values) it shows an error on screen as project mismatch, project specific activity and timesheet project are different. Now the interesting thing is if i click on activities the list related to activites for the project chosen now are populated, and I am able to change the activity and save it. Not able to do this for create or filter.
> Is something in your javascript console?
no errors as such shown but as described above. But for edit alone could find errors if i choose the incorrect activity by change the project and then hitting save. Which later populates the right activity list.

**Comment by kevinpapst** [comment]
Thats an important info:
>  In the filter option if i choose customer the next project option does not allow me to select anything, blocked.

So none of the API-enabled dropdowns is working in old browsers. Interesting and annonying. 
I switched 90% of the Javascript codebase to the latest javascript standard ES6 for 1.0, so thats why might cause the problems.

Are other things working, like the new notifications when saving or creating an entry?

We are talking about this browser: https://ftp.mozilla.org/pub/firefox/releases/29.0/mac/de/
That was released 12-Oct-2015 and is more than 3,5 years old. 
Seriously, thats like middle-age in terms of web technology.

Can't your colleagues switch to another browser?
If you have some talented javascript guys on your end, I will happily accept PRs or ideas how to fix it.

**Comment by resstm** [comment]
The notifications are also not working.

Yes that is true Kevin but we cant switch. That is the latest supported browser for the OS. We use the machines for graphics processing and if we switch to the latest machines, we cant use the graphics software as they are not supported or built for the new OS and moving to the latest version of Adobe subscription adds too much cost which we cant afford. 

There is a someone whom I know who is in Czech republic if you could let me know what I should ask I can get him to give you inputs.  

Can we have an additional Kimai 0.9 installed on the same database and using the same schema used by 1.0 and users who are using the old browsers could still use kimai but with limited functionality. But all data would be held centrally in the new 1.0 database allowing us to enjoy the new features through the new interface for reporting etc. This is just a guess i dont know if this is anyway possible.

**Comment by resstm** [comment]
Screen shots from the issue. 
![Picture 7](https://user-images.githubusercontent.com/51189640/60820603-65304b00-a1bf-11e9-8bbb-9717c1e7b6e2.png)
![Picture 8](https://user-images.githubusercontent.com/51189640/60820604-65304b00-a1bf-11e9-8514-3e54aae9fead.png)
![Picture 9](https://user-images.githubusercontent.com/51189640/60820606-65c8e180-a1bf-11e9-9b6b-56f5c7b95f81.png)
![Picture 10](https://user-images.githubusercontent.com/51189640/60820607-65c8e180-a1bf-11e9-88ec-ee141b900808.png)
![Picture 11](https://user-images.githubusercontent.com/51189640/60820608-65c8e180-a1bf-11e9-8484-aed67631b6c0.png)
![Picture 12](https://user-images.githubusercontent.com/51189640/60820610-66617800-a1bf-11e9-82fd-8a7d06eeaa89.png)
![Picture 13](https://user-images.githubusercontent.com/51189640/60820611-66617800-a1bf-11e9-837f-48ef47f2f706.png)

**Comment by hmr-it-jr** [comment]
@resstm about which OS are we talking?

I have an native app for MacOS,  Windows and Linux which is ready to be deployed.

The basic function of the native app is: tracking times - even if the client is offline. There are no features like reporting, etc. - and there are no plans to add them at the moment. Just basic time tracking with some comfort features like searching and so on.

So employees can track times on their old macs/pcs - reports have to be generated on more mordern macs/pcs. The app itself doesn't have any dependencies. If you are interested in it let me know it.

**Comment by resstm** [comment]
Yes @hmr-it-jr indeed having a native app would be of great help. Our OS version is Mac OS X 10.5 which is really old by any standards now. Moreover having this native app would be useful for all of our users too since at times our connections to the internet breaks and during these said intervals we might be able to use the locally installed app to collect data and sync them with the main database when the connection is back up. One more point I hope I am not asking too much would the locally installed app also have the option to do tagging which is a feature that has now been delivered in 1.0.

**Comment by hmr-it-jr** [comment]
@resstm can you send me an email to johannes.roth [at] hmr-it.de ?

**Comment by resstm** [comment]
@hmr-it-jr Hi, I've dropped a mail just a few minutes back.

**Comment by resstm** [comment]
@kevinpapst I have spoken to a developer over here and he was saying if it was an ES6 issue then he was suggesting that we dont we try using tranpiler to move from ES6 to ES5 so that the javascript works with older browsers. Also he was asking in kimai if we are using one javascript alone or more than that.

**Comment by kevinpapst** [comment]
I know that, nothing new so far ;-)

Thats why Babel is active: 
https://github.com/kevinpapst/kimai2/blob/master/webpack.config.js#L31

But maybe I missed some important configurations, who knows... 
https://symfony.com/doc/current/frontend/encore/babel.html

**Comment by hth2** [comment]
I tested https://demo-stable.kimai.org with Firefox 29, english version, running on macOS Sierra. In console I see some errors like this:
```
TypeError: t.currentTarget.matches is not a function app.0ac6f178.js:1
TypeError: n.matches is not a function app.0ac6f178.js:1
```

I tried to copy & paste the following polyfill to the console:
```
if (!Element.prototype.matches) {
  Element.prototype.matches = 
      Element.prototype.matchesSelector || 
      Element.prototype.mozMatchesSelector ||
      Element.prototype.msMatchesSelector || 
      Element.prototype.oMatchesSelector || 
      Element.prototype.webkitMatchesSelector ||
      function(s) {
        var matches = (this.document || this.ownerDocument).querySelectorAll(s),
            i = matches.length;
        while (--i >= 0 && matches.item(i) !== this) {}
        return i > -1;            
      };
}
```

After that, it seems to work for the simple tests I did.

**Comment by kevinpapst** [comment]
Interesting, then the Babel mechanism to detect required polyfills is maybe not working (completely) for Kimai or its just to old ... but very good hint!
Lets see if the team of @resstm can confirm that it fixes the issues for them as well.

Are you experienced with frontend tooling & builds? 
I am not, so I am wondering if there is a better way to copy&paste this into an own polyfill file.
Maybe [CoreJS](https://github.com/zloirock/core-js)?

Have you tried the second version as well?
https://developer.mozilla.org/en-US/docs/Web/API/Element/matches
```
if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.msMatchesSelector ||
                              Element.prototype.webkitMatchesSelector;
}
```

**Comment by hth2** [comment]
> Are you experienced with frontend tooling & builds?
> I am not, so I am wondering if there is a better way to copy&paste this into an own polyfill file.
> Maybe [CoreJS](https://github.com/zloirock/core-js)?

sorry I am not (yet).

> 
> Have you tried the second version as well?
> https://developer.mozilla.org/en-US/docs/Web/API/Element/matches
> 
> ```
> if (!Element.prototype.matches) {
>   Element.prototype.matches = Element.prototype.msMatchesSelector ||
>                               Element.prototype.webkitMatchesSelector;
> }
> ```

I have just tried now; this shorter version didn't work.

**Comment by rarvin** [comment]
Did the 

> Interesting, then the Babel mechanism to detect required polyfills is maybe not working (completely) for Kimai or its just to old ... but very good hint!
> Lets see if the team of @resstm can confirm that it fixes the issues for them as well.
> 
Did the test after running the code in console. I was still not able to create a new task.
Please see screen shot attached.
![Picture_2](https://user-images.githubusercontent.com/50443902/60907038-31742480-a296-11e9-8e7c-14cd62689703.png)

> Are you experienced with frontend tooling & builds?
> I am not, so I am wondering if there is a better way to copy&paste this into an own polyfill file.
> Maybe [CoreJS](https://github.com/zloirock/core-js)?
> 
> Have you tried the second version as well?
> https://developer.mozilla.org/en-US/docs/Web/API/Element/matches
> 
> ```
> if (!Element.prototype.matches) {
>   Element.prototype.matches = Element.prototype.msMatchesSelector ||
>                               Element.prototype.webkitMatchesSelector;
> }
> ```

**Comment by kevinpapst** [comment]
@rarvin please copy&paste this here as well: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill

**Comment by rarvin** [comment]
I shall update back tomorrow.

**Comment by kevinpapst** [comment]
please test the branch in #941

**Comment by kevinpapst** [comment]
ping @resstm any feedback?

**Comment by kevinpapst** [comment]
I am goign to close here. If someone has valueable feedback, please comment in the PR #941 

For now, I am NOT going to invest any more time into this issue / supporting "shitty old browsers" 😈. Even large companies who get paid big times for their software drop their support.

But again: I don't min help with that, I will test and merge if someone can help with the required code to make it compatible.
