### ISSUE TITLE
Required predefined projects and activities

### ISSUE THREAD

**Issue by Collandi** [kevinpapst/kimai2#935]
Hello Kevin,
it would be very good if the fields "Project" and "Activity" were not needed for the time recording. This makes the entries very cumbersome because these records can only be created by a teamleader/administrator. If project or activity are not present, the user must first consult an authorized person.
It should also be possible to enter a free text. Or the possibility that the user can create a project and / or the activity with the main term in the fields. Maybe with settings for the admin.

Is it possible to switch the fields to not required?

**Comment by kevinpapst** [comment]
No its not possible.
The philosophy is a bit different. But I understand that some companies don't want/need that.
So I take that as a PR to add a new feature & permission for creating projects and activities inline.

**Comment by Collandi** [comment]
>The philosophy is a bit different.
I know, but for a whole project management to accounting Kimai has to grow for most companies. ;-)

Thank you very much!

**Comment by kevinpapst** [comment]
> So I take that as a PR to add a new feature & permission for creating projects and activities inline.

If you close an issue, you have no chance that it will be added in the future...

**Comment by kevinpapst** [comment]
I have plans for the future to make activity optional. But Kimai relies on it in several places and plugins. 
This cannot be changed at random times, so I will keep it in mind for the a new major version.
