### ISSUE TITLE
Reporting: users monthly timesheet

### ISSUE THREAD

**Issue by xpresas** [kevinpapst/kimai2#936]
The main idea is that when you export for eg: a whole month of 20 users timedata. There is a lot of "coffee breaks, WC brakes" and etc. So there is basicaly from 2 to 4 timestamps at the same day from one person. Which is a pain to sum it up in the end when you need to see how much time each person was working on that exact day. This could be an checkbox or smth in the admin menu or a config option..

Also the buttons for exporting "Csv, opt, txt, whatever" could be moved or duplicated to be on top of the whole table. Because now its just inconvienient to scroll down the whole table just to click on the excel button.. :) 
Examples:

Currently:
```
1. 2019/01/01 - Tom X - 2h;
2. 2019/01/01 - Tom X - 6h;
3. 2019/01/01 - Luke Y - 7h
4. 2019/01/01 - Luke Y - 3h;
```
After turning on the functionality:
```
1. 2019/01/01 - Tom X - 8h;
2. 2019/01/01 - Luke Y - 10h;
```
This is just an abstract idea of it, because I saw a couple of issues like this but they failed to correctly explain it. Plus it is an pain for me too because I had to write a whole mini application to add up these times.. (unfortunately I only know C# so I could not have done this myself in php..) 

Thank you for your amazing work and making it open source. I wish you good luck.

**Comment by xpresas** [comment]
@kevinpapst Hi, maybe now this idea is faster to make it possible after you implemented a colum with seconds in it?

**Comment by kevinpapst** [comment]
Honestly I don't think this is something the export should do. And there is no vote other for it.

Have you thought about writing your own invoice template? 
Create an Excel template:
https://www.kimai.org/documentation/invoices.html#spreadsheets-ods-xlsx-and-csv
and use the user-grouped calculator.

**Comment by xpresas** [comment]
Well I think othervise, if you need a document to see how much monthly hours your personell spent, it feels awkward to look at these records split up. How hard would that be to make it to a template?

**Comment by xpresas** [comment]
@kevinpapst Or maybe it would be easier to be able to resume your day old entry? So that in the end in the export it would be just one entry for one day for each person?

**Comment by kevinpapst** [comment]
One year later 😁 https://github.com/kevinpapst/kimai2/pull/1805
