### ISSUE TITLE
Offline mode for Kimai

### ISSUE THREAD

**Issue by resstm** [kevinpapst/kimai2#937]
There are instances where having an offline mode for Kimai would be good since if an internet connection breaks users would still be able to continue to work and log in their time and possibly when the internet connection is restored the data held in the offline mode could be pushed back to the database. This would be more like offline gmail mode. 

When in offline mode just the basic features like starting new activities or stopping/editing an already running task or restarting an existing task be allowed. Other functionality could be used when the client system is online. 

An indicator to display if the user is running in online or offline mode and a facility to switch from online to offline mode.

**Comment by kevinpapst** [comment]
That is completely out of scope for Kimai. Should be facilitated by third party apps, not by the core.
