### ISSUE TITLE
Functionality to allow only authenticated kimai clients

### ISSUE THREAD

**Issue by resstm** [kevinpapst/kimai2#938]
Right now any user with the user credentials could access the kimai system from anywhere in the world and use it, which is simply great. But there are at times for companies where we would like to restrict only few users to connect and track time but from machines which are authenticated or company provided client machines. 

Can kimai block user access or link user access to a specific IP address of the client machine or more so to the MAC address of some identifier from the client machine so that the said user can only use kimai from that machine alone.

Doing this from the web based tool would be the best but even if that is not possible since we now have locally installable kimai clients can they be linked to a local system and a user by some mechanism and the same is authenticated client details allowed aceess are configurable from the Kimai frontend. So basically it would be like each local client would have a unique key generated after installation based on the machine details (like mac id or system unique code or something unique for the local mcahine) and this would be updated in the kimai database through the frontend by the admin user once and at login the client application needs to generate the key pass this at login and if it matches the key that is registered allow login. If someone copies the kimai application files to a different machine and tries to log in from there the key generated would not match what is registered in the database.

Its to allow only authenticated clients from connecting and updating records linked to a specific user.

**Comment by kevinpapst** [comment]
If you have control in your network, then you have a server which hosts Kimai.
That server is already capable to restrict the access.
Either configure it in your webserver (nginx/apache) or directly in iptables.

If you want software side protection, you have to configure your security.yaml to restrict the basic firewall to certain IPs:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/security.yaml#L55

I cannot support with that, its basic Symfony functionality:
https://symfony.com/doc/current/security/access_control.html#matching-access-control-by-ip

Please search the issues, that was already discussed in the past.

**Comment by rarvin** [comment]
I was not alone talking of IP based blocking. The problem with IP based blocking is as follows. Only users who get a static IP assigned by the ISP can be blocked or authenticated by an IP, mostly users are assigned a dynamic IP which one would not know till the same is assigned and the same keeps changing. So IP blocking fails or cant be implemented. The idea was to control access by some means like native app authentication with the server using a fingerprint etc and IP blocking was one of the suggestion but in general does not suite our needs. MAC ID based blocking is good since they dont change but I am not sure if MAC ID can be identified by the browser.

**Comment by kevinpapst** [comment]
Blacklisting: 
- https://github.com/kevinpapst/kimai2/issues/951#issuecomment-510945667
- the best and most annoying solution are captchas (there are other ways like WAFs, but thats completely out of scope here)

Whitelisting: 
- Possible in a closed network
- via VPN
- 100% static IPs
