### ISSUE TITLE
Invoice generation to allow selection of tag data without choosing customer project activity or project activity

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#939]
![Screenshot_20190709_201129](https://user-images.githubusercontent.com/50443902/60897678-1d282b80-a286-11e9-9389-d4c7032e75d7.png)

Under invoices one could generate an invoice by using the user grouped option which provides the required output by grouping data per user and the filtering helps granularise the data range also. But the existing tree based approach does not allow filtering directly by a tag excluding the customer, project and activity or the project and activity alone.

An option to allow invoice grouped by the user and allow filtering alone by tag would be good. This has great levels of application if implemented for analysis.

**Comment by kevinpapst** [comment]
Invoices always require a selected customer.
You want to use it for reporting, thats not what it is made for.
