### ISSUE TITLE
Can't reach API

### ISSUE THREAD

**Issue by stavtsob** [kevinpapst/kimai2#943]
Hello there,
When I try to send a GET request to the API from postman, kimai returns me the Log In page instead of the request result. 

I have added the following fields in header: X-AUTH-USER,X-AUTH-TOKEN,Content-Type and the request that I am making is:
.../kimai2/public/index.php/api/activities

As additional information I have to tell you that when I try this request as a logged in user from browser, I get the expected results. But if I am not logged in, I get the log in page. 
What am I doing wrong?

Thank you in advance.

**Comment by kevinpapst** [comment]
Point your webserver to /kimai2/public/
There shouldn't be anything related to the `public` folder or the `index.php` visible in the URL.
