### ISSUE TITLE
IP addresses to log if login fails

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#951]
Is there a way to record IP addresses in the prod.log file in case that login fails due to invalid credentials? 

I would like to use [fail2ban ](https://github.com/fail2ban/fail2ban)  to block such IPs after a given number of invalid trials in order to protect agaist unauthorised access.

**Comment by kevinpapst** [comment]
https://www.nomisoft.co.uk/articles/symfony-fail2ban-ip-blocking

**Comment by BeckeBauer** [comment]
Thank you for the link. I tried my best to implement the code but tremendously failed. It starts that I have no clue in which directory to place the services.yml 
Also, I modified the existing AuthenticationListener.php unter fos/user-bundle/EventListener but am unsure if this is the right file. 
Any hint would be appreciated...

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/kimai2/blob/master/config/services.yaml

**Comment by BeckeBauer** [comment]
Thank you, it worked! 
(your link does not refer to the the service.yaml - despite its name - but the location kimai2/config was the right hint). 
If required, I can describe the steps to log the IP addresses!?

**Comment by kevinpapst** [comment]
Does it work for you? Then yes, please share it! I'd love to make a documentation page for it.

**Comment by BeckeBauer** [comment]
1. Create a PHP file with the following content:

<?php

namespace FOS\UserBundle\EventListener;

use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\RequestStack;

class FailedLoginListener
{

    /**
     * @var LoggerInterface
     */
    private $logger;

    /**
     * @var RequestStack
     */
    private $request;

    /**
     * @param LoggerInterface $logger
     * @param RequestStack $request
     */
    public function __construct(LoggerInterface $logger, RequestStack $request)
    {
        $this->logger = $logger;
        $this->request = $request;
    }

    /**
     * onAuthenticationFailure
     */
    public function onAuthenticationFailure()
    {
        $ipAddress = $this->request->getCurrentRequest()->getClientIp();
        $this->logger->error('Authentication failed for IP: ' . $ipAddress);
    }

}

2. Save it to kimai2\vendor\friendsofsymfony\user-bundle\EventListener as FailedLoginListener.php 
(or give it a different name if you do not like it and rename the class and service.yaml accordingly)

3. Add the following code to service.yaml in kimai2\config

    # ================================================================================
    # Logging IP Addresses on Failed Authorisation
    # ================================================================================   
    app.security.authentication_event_listener:
        class: FOS\UserBundle\EventListener\FailedLoginListener
        arguments: ["@logger","@request_stack"]
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }   

3.  Run	
	composer install --no-dev --optimize-autoloader 
	bin/console cache:clear --env=prod
	bin/console cache:warmup --env=prod

4.  To test: use wrong login credentials and check your prod.log

**Comment by BeckeBauer** [comment]
oops, format got destroyed...

**Comment by kevinpapst** [comment]
You need to add 3 `  before and after the code (and no space in the beginning of the line):
https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by BeckeBauer** [comment]
1. Create a PHP file with the following content:

```/**
<?php

namespace FOS\UserBundle\EventListener;

use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\RequestStack;

class FailedLoginListener
{

    /**
     * @var LoggerInterface
     */
    private $logger;

    /**
     * @var RequestStack
     */
    private $request;

    /**
     * @param LoggerInterface $logger
     * @param RequestStack $request
     */
    public function __construct(LoggerInterface $logger, RequestStack $request)
    {
        $this->logger = $logger;
        $this->request = $request;
    }

    /**
     * onAuthenticationFailure
     */
    public function onAuthenticationFailure()
    {
        $ipAddress = $this->request->getCurrentRequest()->getClientIp();
        $this->logger->error('Authentication failed for IP: ' . $ipAddress);
    }

}
```
2. Save it to kimai2\vendor\friendsofsymfony\user-bundle\EventListener as FailedLoginListener.php (or give it a different name if you do not like it and rename the class accordingly)

3. Add the following code to service.yaml in kimai2\config

```
    # ================================================================================
    # Logging IP Addresses on Failed Authorisation
    # ================================================================================   
    app.security.authentication_event_listener:
        class: FOS\UserBundle\EventListener\FailedLoginListener
        arguments: ["@logger","@request_stack"]
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
```   

3.  Run	
	composer install --no-dev --optimize-autoloader 
	bin/console cache:clear --env=prod
	bin/console cache:warmup --env=prod

4.  To test: use wrong login credentials and check your prod.log

**Comment by kevinpapst** [comment]
Ok, you have a working solution for now, great & thanks for sharing!

Then let me see what I can make of that. This implementation is far from being ideal ;-)

**Comment by BeckeBauer** [comment]
one remark: the following expression to be used in the filter for fail2ban is working:
```[Definition]
failregex = Authentication failed for IP: <HOST>
```

**Comment by kevinpapst** [comment]
Hey @BeckeBauer , do you want to test the new Fail2Ban bundle?
See https://www.kimai.org/store/fail2ban-bundle.html
Feedback can be left here: https://github.com/Keleo/Fail2BanBundle
The log format and file changed... but it makes your change update safe.

**Comment by BeckeBauer** [comment]
I will do tonight

**Comment by BeckeBauer** [comment]
nice work, works flawless, thank you!
Just 2 minor suggestions: 
- in your [documentation ](https://www.kimai.org/store/fail2ban-bundle.html) you suggest to name the ```filter = symfony``` in the jail.local. Since you also suggest to name the Kimai specific filter ```#/etc/fail2ban/filter.d/kimai2.conf``` (and not symfony.conf), the filter name has to be ```filter = kimai2``` in the jail.local
- it would be nice to have some hint about the plugin being installed even though there are no options to configure it within Kimai
![screenshot](https://user-images.githubusercontent.com/51003649/61981516-33f6ae00-affa-11e9-9709-9db5fed698be.gif)

**Comment by kevinpapst** [comment]
Follow up: https://github.com/Keleo/Fail2BanBundle/issues/1
