### ISSUE TITLE
[solved] Found no way to install successfully 

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#953]
I tried all variants except Docker. I tried Git / Composer and the FTP-Version. It does not work with SQLite nor MySQL. I have a Cloudserver with Ubuntu 14.04, using PHP 7.2, tried via SSH and Plesk GUI. 

I have a subdomain pointing to /public as docroot

The issues: 
Using Git and Composer it installs, but creating the database schema in the existing database always "permission denied". I tried several settings for the DB and put the right data into the .env

Using the FTP-Version (0.9 from Google Drive) I get the login screen, but no database schema is created (nor can I create one, see above issue). I also tried SQLite. Another issue with the FTP-Version is that when trying to register I get a 404 from Nginx. 

I also tried to install Kimai2 via Git and Composer, setting the new database (w/out schema) and migrating the Kimai1 Data. I get an error in the bash like "got garbage in your command line?" I checked the command over and over from the examples to my own data. 

The server is Apache and has Nginx as proxy. All apps including Kimai1 1.01 work fine that way. 

Kimai2 looks really great and I have been using Kimai1 for years. Now I am really! frustrated after trying a full day and most of the night to install Kimai2 while getting nowhere whatever I try. I am really not inexperienced with this kind of thing, but Kimai2 I cannot get to run.

**Comment by VOOM108** [comment]
In other words: in very desperate need of a nicely working web-installer, preferrably with an optional migration wizard gui included.

**Comment by VOOM108** [comment]
Grrr.... Ok, so it all came down to two things PHP: I had to change the php-fpm to be delivered by apache instead of nginx, and I did add the php-version when installing via composer, but did not realize I had to do the same thing with the bin/console commands. 

So 
/opt/plesk/php/7.2/bin/php bin/console doctrine:schema:create 
did the trick, same with the following commands of course. 

Migration worked, too. Now I have to see how I can migrate my important .odt invoice templates to kimai2

**Comment by kevinpapst** [comment]
Ah Plesk and multiple PHP version at the same time. Yeah, thats an annoying setup.
Let me guess: the default PHP version was 5.x?

The invoice templates are not compatible. But I hope the documentation is sufficient to be able to migeate it over: https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document  - let me know if anything is missing.

**Comment by kevinpapst** [comment]
Oh, and you migrated successfully the DB entries from 1 to 2?

**Comment by VOOM108** [comment]
Yes, the migration from 1 to 2 looks sucessful and complete. 

I have edited the first invoice template and changed the variables and saved it to Open Document XML Text .docx from Libreoffice. Now when setting up an invoice in Kimai2, selecting the .docx (in var/invoices) I get a 500 error...

**Comment by VOOM108** [comment]
Is there a way to keep a set filter in the timesheet like in Kimai1? Like wanting only to see the current month and keeping that setting when coming back to the timesheet?

**Comment by kevinpapst** [comment]
Something like `ln -s /usr/bin/php72 /usr/bin/php` changes the default php... but better don't, otherwise pleask might be broken...

500 means all and nothing, check the logfile at var/log/prod.log. I'd say wrong permissions on the var directories. Does that happen for the HTML invoice as well?

Search the issues, there is an open one for permanent filters.

**Comment by VOOM108** [comment]
Oh, damn. I put "immediately" into "due time" where it should habe been a number of days. Because I could and that is what I wanted to see in the invoice.

**Comment by kevinpapst** [comment]
I can't follow ;-) but seems you make progress.

I'll close this ticket as the original issue was solved. If you find any other problem, just open a new one.
