### ISSUE TITLE
Template variable with decimal time entry (with "dirty" self-made solutions)

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#955]
**Is your feature request related to a problem? Please describe.**
In Kimai1 I could format the times in decimal like so: 4,5 h (= 4:30 h) One customer requires me to log the entries like that. 

**Describe the solution you'd like**
Have variable formatting like [row.hour;frm='0,00'] or [var.ttltime;frm='0,00']

**Describe alternatives you've considered**
Have a variable exporting times in decimal format

**Comment by kevinpapst** [comment]
I see the need, but don't have the time right now.
If you want to try it yourself, just add a new line in this array:
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Renderer/RendererTrait.php#L206
That variable is then availble in all invoice templates.

**Comment by VOOM108** [comment]
Can somebody help putting the line together? I don't know how to calculate this in the first place, and then even less how to construct the PHP to put into the array... I have tried some stuff from googling without knowing what I am doing and the best thing I could get was a nice number x,xx h that simply calculated wrongly when putting it against the correct total.

**Comment by VOOM108** [comment]
Or else - somewhere in kimai1 this is being calculated. Where do I find the functions etc. for the frm-calculations in kimai1?

**Comment by VOOM108** [comment]
One step further: 

'entry.duration_decimal0' => number_format((strtotime($this->getFormattedTime($end)) - strtotime($this->getFormattedTime($begin)))/3600, '2', ',', '') . ' h',

**Comment by VOOM108** [comment]
Don't know why I had such a hard time with this. It was actually very easy... 

'invoice.total_time_decimal0' =>  number_format(($model->getCalculator()->getTimeWorked()) / 3600, 2, ',', ''). ' h',

Now I have all my templates in place as needed for now :)

**Comment by kevinpapst** [comment]
now available in master, documentation was added.
you should change your invoice templates after the next release.
