### ISSUE TITLE
Searching Tags, Multiselect delete of tags and ability to Edit/rename Tags

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#956]
Current system allows adding and deleting tags. An option of editing the existing tags would be good. Once the tag names are changed from the current name to the new one it would be good if existing mapping on the system on existing timesheets are moved to the new tag name.

It might be difficult but would be a nice functionality to have. 

Currently the number of tags on the system has grown and it has become very difficult to search them as they appear in different pages. It would be good if the existing search functionality is extended to the tag screen also 

User mistake creates lots of junk tags into the system, having an option of multi select and delete at once would be good.

**Comment by kevinpapst** [comment]
Searching was added with #1064
Editing (renaming) will be added with #1083

I will skip the "multi-delete" for now, as I need to create the basic functionality for updating multiple items first.
