### ISSUE TITLE
Audit Trail or Audit log for user - extension of audit trail plugin

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#958]
The plugin for identifying the changes made for customer, project, activity and timesheet is very nice. It would be good if this is also extended to the user. Audit trail of audit log viewable from within Kimai for the admin. Details needed would be on when each operator is logging in and logging off. Especially the first login and last logout in a 24 hour interval a summarised view. This can help in understand the usage patterns of users and data anlaytics, understanding peak usage etc. A report viewable per user per day, week, month and a summarised view for all users with their first login and last logout and the duration of time in between.

**Comment by kevinpapst** [comment]
I have sent you an email. As this is a paid plugin, I don't want to discuss it here.
