### ISSUE TITLE
${invoice.total_time} sums up time and fixed rate entities

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#959]
**Describe the bug**
Fixed rate entries from ${entry.amount} as documented always get calculated as "1" into ${invoice.total_time}. Meaning that with mixed timesheets - a customer pays a fixed rate per month plus extra time for special work done - the total time is a wrong time. With 1 fixed rate item and 3 hours work I get a total time of 3:01 h which makes no sense to me. 

There should be different variables for totals with amounts of fixed rate items and actual time records. 

For me it would suffice if the total excluded the fixed rate items and there was an extra variable for fixed rate single row entries.

**Comment by kevinpapst** [comment]
Mixing fixed rates and normal rates is very problematic (depending on the calculator you use).
Please the the invoice configuration you used.

**Comment by VOOM108** [comment]
Beschreibung | Datum | Dauer/Anzahl | pro Einheit | Betrag
-- | -- | -- | -- | --
${entry.activity}    ${entry.description} | ${entry.date} | ${entry.amount} | ${entry.rate} | ${entry.total}
  | Summe | ${invoice.total_time} |   |

**Comment by VOOM108** [comment]
Maybe I should create another template separating it to two tables... It worked for me in Kimai1 because I just kept the actual time logged for the fixed rate entry at 0...

**Comment by kevinpapst** [comment]
With configuration I meant the InvoiceTemplate (in Kimai):
<img width="472" alt="Bildschirmfoto 2019-07-12 um 20 16 19" src="https://user-images.githubusercontent.com/533162/61149672-fcf4a880-a4e1-11e9-86e1-a08c77386239.png">

**Comment by kevinpapst** [comment]
You can calculate your own stuff only when using a HTML (Twig) template.
This works perfectly fine when using a PDF printer (this is what I always use).

**Comment by VOOM108** [comment]
This is part of one of the templates I translated from those I have been using in Kimai1. The other settings are like in your screenshot

**Comment by VOOM108** [comment]
> You can calculate your own stuff only when using a HTML (Twig) template. This works perfectly fine when using a PDF printer (this is what I always use).

Hmm, yeah... Would mean building the templates once more in a different way; it's kind of exhausting... ;)

**Comment by VOOM108** [comment]
For now I use this very quick and dirty workaround. There will never be time-entries of 60 seconds other than the fixed rate "minutes"... 

AbstractCalculator.php line 97 ff
/**
     * Returns the total amount of worked time in seconds.
     *
     * @return int
     */
    public function getTimeWorked(): int
    {
        $time = 0;
        foreach ($this->model->getEntries() as $entry) {
			if ($entry->getDuration() != 60) {
				$time += $entry->getDuration();
			}
        }
        return $time;
    }

**Comment by kevinpapst** [comment]
Can you retest with the latest release 1.1?
I slightly changed the calculation logic, bt it might still not work correctly for mixed invoices...

**Comment by VOOM108** [comment]
You are right, with mixed invoices it does not help; I will apply my workaround again for now...

**Comment by kevinpapst** [comment]
Hm, looking at the discussion again and thinking about the use-case:
a fixed rate items needs an amount (as they are required for legal reasons) and it might have a duration. 
Question: do you want to show the duration for a fixed item? I would expect: no.
Then a possible solution is to have three variables. 
- the existing `${invoice.total_time}` should not include the fixed rates items
- a new `${invoice.total_time_fixed_rates}` for the duration of all fixed rates items
- a new `${invoice.total_time_with_fixed_rates}` for the combined times
where the two new ones will likely not be used very often...

**Comment by VOOM108** [comment]
That would be completely sufficient for my use-cases. Also it makes sense to me, that there could be a duration time for fixed rate items, even though I personally would not want to mix that in an invoice. 

In general: I thought of a sum of fixed rate items, but I am not sure if there is a use case for that.

**Comment by kevinpapst** [comment]
Well, the same like for times can be added for the rates as well. Even though I don't see a use-case for it. But who knows what the community comes up with ;-)

**Comment by kevinpapst** [comment]
@VOOM108 Can you please test #1058 (there is a link to a demo installation) if that works better?
