### ISSUE TITLE
Better visualization of active time-recordings and start-stop

### ISSUE THREAD

**Issue by VOOM108** [kevinpapst/kimai2#961]
I liked the way Kimai1 visualized active time-recordings and the big start button would change to a stop button. I tend to forget to stop time-recordings and it would help to have a clear visual change in the timesheet-gui when there are active recordings. 

Also maybe the process of stopping could be improved. Of course since concurrent jobs are possible now, it makes sense, that the start-button shows the badge and offers a menu with the items that can be stopped. Still it maybe could change to a red stop-button and still open the menu. 

It then would help to have a red stop-button in the row of an active recording in addition to the function moved into the actions-menu. I prefer to have very obvious functions directly available and move less often used functions into the menu.

**Comment by VOOM108** [comment]
I know this is a terrible hack, but works for me for now. Since any changes I made to twig-templates did not show, I created a stylish-style and had a look wich items I could target that way. This is what I came up with: 
```
.navbar-static-top .label-warning {
	background:crimson!important;
    font-size:2.7em!important;
    border-radius:50%!important;
    padding-right:28%!important;
    padding-left:28%!important;
    padding-bottom:25%!important;
    padding-top:14%!important;
    margin-top:-5px!important;
    margin-right:-5px!important;
}
.modal-ajax-form.open-edit i {
	font-size:1.2em!important; 
    font-weight:bold!important; 
    background:crimson!important; 
    color:white!important; 
    border-radius:50%!important;
    padding:6px!important;
}
```
I know the important-inflation is bad style, but I was too lazy to check which ones I needed. 

This is what it looks like: 

![stylish](https://user-images.githubusercontent.com/16562946/61173808-b3b36000-a598-11e9-9a27-79ddae568369.png)

**Comment by infeeeee** [comment]
You can achieve this with the [custom css plugin](https://www.kimai.org/store/keleo-css-custom-bundle.html).  You can test this in the [plugins demo](https://www.kimai.org/demo/). With this plugin you can override the default styles in kimai, your css works in the demo, only modify the first selector to this: `.navbar-static-top .dropdown-toggle .label`. It's much better to use this plugin than modifying your files directly. On updates your local files will be overwritten, so you will loose your changes, but with the plugin you won't.

**Comment by VOOM108** [comment]
That's pretty cool... :) I will install and try that. Though: this does not offer any other alterations to the templates, like adding CSS-classes to otherwise unreachable elements.

**Comment by infeeeee** [comment]
I think all elements are reachable at least with [pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes). Which element is unreachable?

To clear the cache:
```
bin/console cache:clear --env=prod
bin/console cache:warmup --env=prod
```
Source: the update guide:  https://www.kimai.org/documentation/updates.html

**Comment by VOOM108** [comment]
I wanted to change the background of the table row that has an active recording. In order to do that I now put a class into the row with a condition: 

 <tr{% if is_granted('edit', entry) %} class="modal-ajax-form open-edit  **{% if not entry.end %}recording{% endif %}**" data-href="{{ path('timesheet_edit', {'id': entry.id}) }}"{% endif %} >

Now I can use the CSS Plugin to do sth. like this easily: 
![recording-row](https://user-images.githubusercontent.com/16562946/61295875-4b9f8c80-a7d9-11e9-83b9-cd8463b2489a.png)

**Comment by infeeeee** [comment]
Yes, you are right. I think it's a valid reason to add this class, maybe open a PR, it would be better for others to use this as well, and your files won't be overwritten on update.

**Comment by VOOM108** [comment]
Can't quite seem to figure out how to open a pull request - never did that so far... ;)

**Comment by kevinpapst** [comment]
- Fork the repo
- clone your fork
- create a branch
- change the file
- commit your change and push your banch
- go to https://github.com/kevinpapst/kimai2/pulls
- a yellow box will appear asking if you want to open a PR

Try that first: https://learngitbranching.js.org

**Comment by kevinpapst** [comment]
And to simplify targeting the running timer in the row:
```
tr > td > i[data-since] {
color:red;
}
```
But having that new css class is a good and useful idea!
