### ISSUE TITLE
Help Needed: How to add a new permission from a kimai2-plugin

### ISSUE THREAD

**Issue by fungus75** [kevinpapst/kimai2#965]
I'm currently going to write a kimai2-plugin ( https://github.com/fungus75/ReadOnlyAccessBundle - Very early state, most of the code taken from the CustomCSS plugin).

I do want to create a new permision that can be assign to a user.
In my optinion I do want to do that:
1. Create a new user
2. assign only the new role to that user

Now the new user can login to Kimai and can access a some special data.
But this can only be done, if the user has this special role/permission.

In the CustomCSS-Plugin there is a new role "edit_custom_css" mentioned but in my optinion this role does not exist: I can not assign it to a user from the settings-view and I do not find any codefragment within the CustomCSS-Plugin that creates that role.

**Comment by kevinpapst** [comment]
You don't need new roles (please forget them, Kimai does NOT support custom roles by now), but ONLY a new permission, where a permission is basically only a string like `edit_custom_css`.

Thats how you use it:
https://github.com/Keleo/CustomCSSBundle/blob/master/EventSubscriber/MenuSubscriber.php#L56

Or check it in a twig template with:
```
{%if is_granted('edit_custom_css') %}
permission given
{% else %}
permission denied
{% endif %}
```

The user of the plugin has to assign that permission like documented:
https://www.kimai.org/documentation/permissions.html

**Comment by kevinpapst** [comment]
Solved?

**Comment by fungus75** [comment]
Sorry, Kevin. Just had time today. Yes. now it is clear, thanks for your explanations.
