### ISSUE TITLE
Cannot remove a permission from a user

### ISSUE THREAD

**Issue by stavtsob** [kevinpapst/kimai2#966]
Hello there,

I need to prevent my users from editing their own timesheets. 
I tried two things to do that in the kimai.yaml to edit permissions and neither of them worked.

Attempt#1 :  (didn't worked)
ROLE_USER: ['!edit_own_timesheet'] 

Attempt#2  :  (didn't worked)
New permission set
TIMESHEET_NO_EDIT: ['view_own_timesheet','start_own_timesheet','stop_own_timesheet','create_own_timesheet','edit_own_timesheet','export_own_timesheet','delete_own_timesheet']
ROLE_USER: ['@TIMESHEET_NO_EDIT','@PROFILE']

**Comment by kevinpapst** [comment]
Did you clear the cache afterwards?

**Comment by stavtsob** [comment]
Nope you are right.
I tried the command: _bin/console cache:clear_ and now everything is fine.
Thank you!
