### ISSUE TITLE
plugin advice please

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#967]
Hi!
I'd like to look into whether I can port my old Indesign XML exporter from v1 to the new platform. 
I saw the structure but some basic export specific hints would be great as a starting point. 
Where would you start?
Thanks
Best
Manu

**Comment by kevinpapst** [comment]
Here you go:
https://www.kimai.org/documentation/export.html#adding-export-renderer

If you need more infos, please open a new issue with a concrete question ;-)

**Comment by labor4** [comment]
I get it.
Digging time.

**Comment by kevinpapst** [comment]
Copy & pase the CustomCssBundle if you don't have Symfony experience and adapt it. 
That makes it much easier, as you have already the basic setup of a plugin.
