### ISSUE TITLE
Allow user changing the date for "duration with fixed start time" tracking mode

### ISSUE THREAD

**Issue by JayAige** [kevinpapst/kimai2#968]
When using the 'duration_only' mode it is allways necessary to enter a time for the start of the entry. As my customers are not really interesseted in the exact time when the work was done, I really appreciate the new 'duration_fixed_start' mode. This really saves me some needless clicks and scrolls. So I configured 'default_begin: 08:00' in my local.yaml to avoid overlapping with the next day, for example when entering a 8 hour workday at 22:00.

So now comes the feature request. Unfortunately it is not possible to change the date anymore. Therefore it's only possible to track times for the same day. When I travel for example from tuesday to thursday, I usually track my times on friday for the last 3 days. With the current configuration it's not possible to track those times comfortable in 'duration_fixed_start' mode. Is it possible to add a new permission for users to select a different date while in this tracking mode? I think tracking times with the calendar view would definitely benefit from this additional configuration feature. At the moment when clicking on different dates in the calendar view, the times is always tracked for today.

**Comment by kevinpapst** [comment]
This mode is there for employeer who "only kinda trust their employees" but don't want them to enter times as they like it. If the user forgets to track a day, he can step up to his manager, who can still change the day in the admin view.

Sounds as if you are a freelancer and use it for yourself, in that case I would recommend to use the admin view to track past entries.

What you request is a new tracking mode, as I don't want to mix tracking modes with permissions..
They can quite easily be added if you are familiar with PHP.

**Comment by JayAige** [comment]
Thank you for your swift response! Unfortunately I'm not familiar with PHP or coding/developing at all. I see myself more like a technically interessted user.

I switched the tracking mode to 'duration_only' now. The 'default_begin' is still set to 08:00. When I click the "+" button in the timesheet the starting time is automatically set to 08:00 now and it stays there while changing the date via the small calendar. After reading the documentation (timesheet.html) it wasn't clear for me that the option 'default_begin' affects also the 'duration_only' tracking mode. Maybe the doc-page could be modified so this point gets clearer for less sophisticated users. This totally solves the needless clicking and scrolling problem for me.

By adding a new time entry via the calendar app, the 'default_begin' is ignored in the pop up menu. Therefore I want to modify my feature request a little bit because I understand that mixing tracking modes with permission could be challenging. Would it be possible to apply the 'default_begin' configuration to the calendar? So when I click on a specific day in the calender and the menu pops up, the time is automatically set to the 'default_begin' time.

**Comment by juup** [comment]
I was looking for such "duration tracking". Because of your post here, I found the option for the system administrator to set it. Great.
For the calendar view now it would be helpful to see the duration instead of the "start time".

**Comment by kevinpapst** [comment]
Thats for your input. Noted as calendar improvements!

**Comment by kevinpapst** [comment]
Closing as no user voted for this feature for 2,5 years.
