### ISSUE TITLE
Concept: Duration should be into the past?

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#969]
Hi
Maybe I follow another philosophy, but should the duration mode not END at a given time and let us set the timespan into the past?
My way of thinking is that I use this mode at the end of work, picking the appropriate amount based on my efficiency. After that, I am done with the timespan and do something else.

So question is:
Duration: Choose OUT time plus TIMESPAN.
Instead of IN time plus TIMESPAN.

cheers
manu

**Comment by labor4** [comment]
or both options. this thing is hella modular.

**Comment by kevinpapst** [comment]
What is it doing now? Is it currently using the moment in time as start and the duration added on top?
If so, sounds wrong to me... 

Adding another option is definitely not my favorite. I'd say you always track after you are finished. Its rare that you really know upfront how long you work on a task ... and then you can still log if afterwards.

**Comment by labor4** [comment]
yes my thoughts exactly.

<img width="901" alt="Bildschirmfoto 2019-07-17 um 19 05 43" src="https://user-images.githubusercontent.com/18475375/61395544-f7bea180-a8c5-11e9-94be-9786b87d9994.png">

**Comment by labor4** [comment]
Just tested it, the scheme is IN+DURATION, not OUT-DURATION

Another thing: Entering a integer into Duration will be interpreted as seconds. Should this rather be minutes? Or even 0115 meaning 01:15?

**Comment by kevinpapst** [comment]
No one else seems to be interested, even though I agree that it sounds useful.
Closing for now.
