### ISSUE TITLE
How can i create a custom widget using a custom bundle?

### ISSUE THREAD

**Issue by merceaemil** [kevinpapst/kimai2#970]
Hey,

I have a question, is it possible to create a custom Widget using a custom plugin? I have tried to do that but i have a problem with how to create the view for it. It's always asking me to add the widget view into templates/widget/widget-something.twig.html

**Comment by kevinpapst** [comment]
Yes, it should be possible:
https://www.kimai.org/documentation/developers.html#extending-the-dashboard-with-widgets

Don't extend the SimpleWidget: 
https://github.com/kevinpapst/kimai2/blob/master/src/Widget/Renderer/SimpleWidgetRenderer.php#L27

**Comment by merceaemil** [comment]
It worked thank you. But the documentation i think it needs to be updated with something like this:

```
        use App\Widget\Type\CompoundRow;
        use KimaiPlugin\YourCustomBundle\Widget\Type\YourCustomWidget;

        .....

        $section = new CompoundRow();
        $section->setTitle('Section title');
        $section->setOrder(1);

        $section->addWidget((new YourCustomWidget())
                    ->setId('yourcustomwidgetid')
                    ->setTitle('Your custom widget title')
                    ->setData([])
                    ->setOptions([]));

       $event->addSection($section);
```

**Comment by kevinpapst** [comment]
Thanks! Docs were deprecated, fixed now.
