### ISSUE TITLE
DOCS: Another example for smtp connect

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#971]
Example into DOCS:

In 
https://www.kimai.org/documentation/emails.html
...i had a hard time getting @ chars in Logins zu work.

This was my working example and may help others:
`
MAILER_URL=smtp://login%40mydomain:weird!%24%3Apassword@mailserver:587?encryption=tls&auth_mode=login
`

(the forbidden chars urlencode trick also counts for logins)

**Comment by kevinpapst** [comment]
thanks @labor4 👍 I added it to the docs
