### ISSUE TITLE
Add dashboard to initial view + Setup default initial view after login

### ISSUE THREAD

**Issue by merceaemil** [kevinpapst/kimai2#973]
Is it possible to add dashboard in the list of Initial view after login?
Also is it possible to configure the default initial view after login for all users?

**Comment by kevinpapst** [comment]
Well, it was already in the list, but there was a bug in the permission check... see attached PR #974 .
Thanks for pointing it out!

Yes, but ONLY via code. You need to write your own EventSubscriber for:
https://github.com/kevinpapst/kimai2/blob/master/src/EventSubscriber/UserPreferenceSubscriber.php#L158
