### ISSUE TITLE
API [POST] User

### ISSUE THREAD

**Issue by stavtsob** [kevinpapst/kimai2#977]
Hello once again,

I wanted to ask if a POST API request for users will be added soon. 
Currently User is the only entity that cannot be created via API. It would be really helpful if it could be added.

Thank you in advance.

**Comment by kevinpapst** [comment]
Can you explain the use-case?

**Comment by stavtsob** [comment]
In case I want to merge Kimai in a bigger system, and I want users from another platform to be transferred to Kimai through API. So if I want to create a new user in my system, I won't have to register  the user account to each platform separately.

**Comment by kevinpapst** [comment]
Isn't that what directory servers (LDAP, AD) were made for?

**Comment by stavtsob** [comment]
That is right. But in my case I am trying to connect different platforms with different kind of data for users for example (different columns and different columns count, different kind of implementations for the similar entities etc). That is why I created a script that syncs the data from the different platforms using APIs.
I am almost sure that there is a better solution for this, but my boss told me to do it using APIs, so here I am.

**Comment by kevinpapst** [comment]
> my boss told me to do it using APIs
Hahaha! Don't know if that translates well, but it sounds like: if all you know is a hammer, every problems looks like a nail ;-)
Did he say "HTTP API"? 
Otherwise you could SSH into the server and use the `bin/console fos:user:create` "API" for now.
