### ISSUE TITLE
Dashboard incorrect timezone (histogram only)

### ISSUE THREAD

**Issue by trentks** [kevinpapst/kimai2#987]
**Describe the bug**
I live in UTC+12 (New Zealand), my workday is usually from 08:30 local to 17:00 local, or 20:30 UTC to 05:00 UTC. At around 12:00 local (00:00 UTC) the histogram will start populating the next days bar—or I should really say the current days bar (local time), prior to 12:00 local it populates the previous days bar. All other times are accurate however and take account of local timezone (both on the dashboard, and across all other aspects—calendar, etc, as far as I can tell).

**To Reproduce**
1. Have a timezone sufficiently different to UTC.
2. Browse to Dashboard
3. Dashboard splits a day across two days.

**Screenshots**
![An example taken at 2019-07-26 16:21:09 local.](https://i.imgur.com/WSWnZzY.png) You will note that the histogram is incorrect, the working hours today shows 05:59h, but the histogram shows only 3:56h, this is because the remaining 2:03h were assigned to the previous (2019-07-25 date).

Do note also, that 2019-07-21 was a Sunday, and not only did I not work that day—but I hadn't even yet installed Kimai, I installed Kimai on 2019-07-22.

![Here is a listing of my todays time recording](https://i.imgur.com/WrUKsfb.png) (minus customers/project/rate/etc fields). This image was taken at 2019-07-26 16:27:43 local. I recognise that your current working task doesn't populate through to the dashboard until it is finished.

**Additional context**
 - Kimai version 1.1 (bug existed on 1.0 too)
 - PHP version 7.2.19-0ubuntu0.18.04.1

**Comment by kevinpapst** [comment]
Interesting finding, you are right I completely ignored the users timezone when populating the widgets data. Thanks for the info!

I attached a possible fix: https://github.com/kevinpapst/kimai2/pull/988
Can you please test if that corrects the times in your installation?

**Comment by trentks** [comment]
Thanks @kevinpapst,

I will test first thing Monday. I'm afraid I cant get to it over the weekend.

**Comment by trentks** [comment]
Whoops, dropped phone and tapped the button! Will test and get back to you.

**Comment by trentks** [comment]
Solved by #988.
