### ISSUE TITLE
How to add a logo to the login screen?

### ISSUE THREAD

**Issue by JayAige** [kevinpapst/kimai2#990]
I was trying to add a logo to the login screen but didn't find anything in the docu. The description of #856 sounds very promising. What exact configuration variables do I have to use? Where has the image to be stored? Thank you in advance.

**Comment by kevinpapst** [comment]
Here you go: https://www.kimai.org/documentation/branding.html

**Comment by coneng** [comment]
So I followed the branding section, created local.yaml under config/packages directory and added the text from branding page rebooted the server and nothing.
anything missing ?

**Comment by kevinpapst** [comment]
You rebooted the server? LOL
I guess the simpler approach is: https://www.kimai.org/documentation/configurations.html#reload-changed-configurations

**Comment by coneng** [comment]
This is what i got after reload:

![image](https://user-images.githubusercontent.com/48026784/65328235-db6c0900-db83-11e9-97c6-bf1d15bbd691.png)

**Comment by kevinpapst** [comment]
I bet 5€ on wrong formatted yaml:
https://www.kimai.org/documentation/faq.html#i-have-a-problem

**Comment by coneng** [comment]
you lost lol
Every time we reload a new vendor directory is created. permissions for kimia2 directory need to be applied again!
working now.. thank you

**Comment by kevinpapst** [comment]
Strange^^ How do you "reload"? 
How can a new vendor directory be created? There is only one directory with the name "vendor".
I guess you make a mistake in your flow. 
Clearing the cache is only "bin/console cache:clear && bin/console cache:warmup".

**Comment by coneng** [comment]
first link you sent was using:
`bin/console cache:clear --env=prod`
`bin/console cache:warmup --env=prod`
I think that created a new vendor directory because the permissions on that directory were reset

**Comment by kevinpapst** [comment]
Its safer to use `--env=prod` as it will not work properly if you use Webserver environment variables. If you have a `.env` file it doesn't matter if you use `--env=prod` or not.

But where did the old vendor directory went to? Did you delete it?
The cache command will not touch the vendor directory, it should only change files in `var/cache/`.

**Comment by coneng** [comment]
hmm I guess something is wrong .. but the only thing I know now is if reload is needed I need to re-set permissions again for the kimia2 directory for the application to work.
can't run as www-data only as root that's why

**Comment by kevinpapst** [comment]
Hm, okay. Normally only the var/ directory needs extended permissions for www-data.
But at least you know how to fix it and you can write a small script to do the task.
