### ISSUE TITLE
Kimai update 1.0.1 > 1.1

### ISSUE THREAD

**Issue by ralf-e** [kevinpapst/kimai2#991]
I tried upgrading from 1.0.1 to 1.1.

**To Reproduce**
 bin/console doctrine:migrations:migrate

**Error:**

 Application Migrations

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20190706224219 from 20190703155522

  ++ migrating 20190706224211 (Fix meta-table definitions)

     -> ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL
Migration 20190706224211 failed during Execution. Error An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':

SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'
19:57:34 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':\n\nSQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:migrations:migrate","message" => """  An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':\n  \n  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'  """]

In AbstractMySQLDriver.php line 106:

  An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'

In PDOConnection.php line 90:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'

In PDOConnection.php line 88:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

**Comment by kevinpapst** [comment]
First of all: what is "version 20190703155522"? This is not an offical migration, at least I [can't find it](https://github.com/kevinpapst/kimai2/tree/master/src/Migrations).

You are running four statements, all of them having the exact same logic and only the [last one fails](https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20190706224211.php#L43)?

The update works fine on SQLite and MySQL. I don't know what to do here. 
You can try to lock the tables by editing the Migration file.

Start of up() function:
```php
$this->addSQL('LOCK TABLE kimai2_activities_meta');
$this->addSQL('LOCK TABLE kimai2_activities');
```
End of up() function:
```php
$this->addSQL('UNLOCK TABLES');
```

**Comment by ralf-e** [comment]
I already had problems with the database during the last update.

As far as I can remember, the import from Kimai1 was not completely flawless. But somehow I got that to work then. I think I will just do a new clean installation without importing the old data.

Is actually planned to implement an import function of foreign data in a future version (.csv or others)

**Comment by kevinpapst** [comment]
Yes, importing is planned for somewhen in the future, but nothing I can give you a date for.

Please run `bin/console doctrine:schema:update --dump-sql` and paste the results.
We need to get your DB in sync with the required structure.

**Comment by ralf-e** [comment]
/kimai2$ bin/console doctrine:schema:update --dump-sql

 The following SQL statements will be executed:

     CREATE INDEX IDX_4F60C6B18D93D649502DF587 ON kimai2_timesheet (user, start_time);
     CREATE INDEX IDX_4F60C6B1502DF587 ON kimai2_timesheet (start_time);
     CREATE INDEX IDX_4F60C6B1502DF58741561401 ON kimai2_timesheet (start_time, end_time);
     CREATE INDEX IDX_4F60C6B1502DF587415614018D93D649 ON kimai2_timesheet (start_time, end_time, user);
     ALTER TABLE kimai2_projects_meta CHANGE project_id project_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL;
     ALTER TABLE kimai2_timesheet_meta CHANGE timesheet_id timesheet_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL;
     CREATE INDEX IDX_407F12069395C3F37AB0E8595E237E06 ON kimai2_projects (customer_id, visible, name);
     CREATE INDEX IDX_407F12069395C3F37AB0E859BF396750 ON kimai2_projects (customer_id, visible, id);
     CREATE INDEX IDX_8811FE1C7AB0E859166D1F9C ON kimai2_activities (visible, project_id);
     CREATE INDEX IDX_8811FE1C7AB0E859166D1F9C5E237E06 ON kimai2_activities (visible, project_id, name);
     CREATE INDEX IDX_8811FE1C7AB0E8595E237E06 ON kimai2_activities (visible, name);
     ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL;
     ALTER TABLE kimai2_activities_meta RENAME INDEX a7c0a43d81c0696 TO IDX_A7C0A43D81C06096;
     CREATE INDEX IDX_5A9760447AB0E859 ON kimai2_customers (visible);
     ALTER TABLE kimai2_customers_meta CHANGE customer_id customer_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL;

**Comment by kevinpapst** [comment]
This one looks suspicious:
```
 ALTER TABLE kimai2_activities_meta RENAME INDEX a7c0a43d81c0696 TO IDX_A7C0A43D81C06096;
```
Can you execute `DROP INDEX a7c0a43d81c0696` manually and run the migration again?

**Comment by ralf-e** [comment]
I thought, error actually occurs at the line before
( ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL;)

still trying:

DROP INDEX a7c0a43d81c0696 ON kimai2_activities_meta;
OK

kimai2$ bin/console doctrine:migrations:migrate

                    Application Migrations


WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20190706224219 from 20190703155522

  ++ migrating 20190706224211 (Fix meta-table definitions)

     -> ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL
Migration 20190706224211 failed during Execution. Error An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':

SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'
18:55:22 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':\n\nSQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:migrations:migrate","message" => """  An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':\n  \n  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'  """]

In AbstractMySQLDriver.php line 106:

  An exception occurred while executing 'ALTER TABLE kimai2_activities_meta CHANGE activity_id activity_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL':

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'


In PDOConnection.php line 90:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'


In PDOConnection.php line 88:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'activity_id': used in a foreign key constraint 'FK_A7C0A43D81C06096'


doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

**Comment by kevinpapst** [comment]
Well, to be honest: I have no idea whats wrong / which MySQL configuration triggers that error.

Can you tell me which version of MySQL is running on your server, maybe that gives more hints on the error.

Can you try the LOCK/UNLOCK table code from above? Do you need help with it?

**Comment by ralf-e** [comment]
>Can you tell me which version of MySQL is running on your server, 

no own server, Webhosting ALL-INKL.COM Premium
Kimai2 Installation with SSH
Datenbank-Server
    Server-Typ: MySQL
    Server-Version: 5.7.26-nmm1-log - (Ubuntu)
    Protokoll-Version: 10
    Server-Zeichensatz: cp1252 West European (latin1)

Webserver
    Apache
    Datenbank-Client Version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
    PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
    PHP-Version: 5.6.38-nmm2

phpMyAdmin
    Versionsinformationen: 4.9.0.1 


>Can you try the LOCK/UNLOCK table code from above? 
what exactly?
The first 4 SQL (CREAT INDEX ...) statements are executed correctly.

None of the 3 "ALTER TABLE ... CHANGE .." does not work:
e.g.
ALTER TABLE kimai2_projects_meta CHANGE project_id project_id INT NOT NULL, CHANGE visible visible TINYINT(1) DEFAULT '0' NOT NULL;

Fehler
SQL-Befehl:

MySQL meldet: Dokumentation
#1832 - Cannot change column 'project_id': used in a foreign key constraint 'FK_50536EF2166D1F9C'

**Comment by kevinpapst** [comment]
Found this one: https://bugs.mysql.com/bug.php?id=77591
Can you try if the first statements work on your database?

**Comment by kevinpapst** [comment]
> what exactly?

https://github.com/kevinpapst/kimai2/issues/991#issuecomment-516157923

**Comment by ralf-e** [comment]
> Found this one: https://bugs.mysql.com/bug.php?id=77591
> Can you try if the first statements work on your database?


Alter Tabel does not work:

Datenbank-Server
    Server-Typ: MySQL
    Server-Version: 5.7.26-nmm1-log - (Ubuntu)
    Protokoll-Version: 10
    Server-Zeichensatz: cp1252 West European (latin1)

mysql> create table instances(uuid varchar(36) default null,unique(uuid)) engine=innodb;

(ok) MySQL lieferte ein leeres Resultat zurück (d.h. null Datensätze). (Die Abfrage dauerte 0.8126 Sekunden.)

mysql> create table block_device_mapping(instance_uuid varchar(36) DEFAULT NULL, foreign key(instance_uuid) references instances(uuid)) engine=innodb;

(ok)  MySQL lieferte ein leeres Resultat zurück (d.h. null Datensätze). (Die Abfrage dauerte 0.2591 Sekunden.)

mysql> ALTER TABLE instances CHANGE COLUMN uuid uuid VARCHAR(36) NOT NULL; 

Fehler
SQL-Befehl: ALTER TABLE instances CHANGE COLUMN uuid uuid VARCHAR(36) NOT NULL
MySQL meldet: #1833 - Cannot change column 'uuid': used in a foreign key constraint 'block_device_mapping_ibfk_1' of table 'd02ed684.block_device_mapping'

**Comment by kevinpapst** [comment]
In that case its the database which has a bug, while the SQL is completely fine.
All you can do now is to delete the for lines which cause the problems (line 33, 37, 41, 45) in
https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20190706224211.php#L33 and then run the migrations again without them.

**Comment by ralf-e** [comment]
Done, thank you.
Waiting for the next update :-)

**Comment by kevinpapst** [comment]
Really glad we could solve it finally!
