### ISSUE TITLE
Import failes during activities

### ISSUE THREAD

**Issue by xentity** [kevinpapst/kimai2#999]
**Describe the bug**
During the import of 1.0 data, the import of activities fails:

> [ERROR] Failed to import activities: Notice: Undefined index: budget

**To Reproduce**
1. run sudo -u www-data bin/console doctrine:schema:drop --force && sudo -u www-data bin/console doctrine:schema:create && sudo -u www-data bin/console kimai:import-v1 "mysql://user:pw@127.0.0.1:3306/kimai?charset=utf8" "kimai_" "test1234" "DE" "EUR"
2. Users are imported, customers are imported, projects are imported, activities fails
3. Error msg:
` [ERROR] Failed to import activities: Notice: Undefined index: budget                                                   
         #0 /var/www/kimai2/src/Command/KimaiImporterCommand.php(767):                                                  
         App\Command\KimaiImporterCommand->createActivity(Object(Symfony\Component\Console\Style\SymfonyStyle),         
         Object(Doctrine\ORM\EntityManager), Array, Array, Array, NULL)                                                 
         #1 /var/www/kimai2/src/Command/KimaiImporterCommand.php(285):                                                  
         App\Command\KimaiImporterCommand->importActivities(Object(Symfony\Component\Console\Style\SymfonyStyle), Array,
         Array, Array, Array)                                                                                           
         #2 /var/www/kimai2/vendor/symfony/console/Command/Command.php(255):                                            
         App\Command\KimaiImporterCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),                   
         Object(Symfony\Component\Console\Output\ConsoleOutput))                                                        
         #3 /var/www/kimai2/vendor/symfony/console/Application.php(935):                                                
         Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),              
         Object(Symfony\Component\Console\Output\ConsoleOutput))                                                        
         #4 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(89):                                
         Symfony\Component\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),                  
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))     
         #5 /var/www/kimai2/vendor/symfony/console/Application.php(269):                                                
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),     
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))     
         #6 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(75):                                
         Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),                
         Object(Symfony\Component\Console\Output\ConsoleOutput))                                                        
         #7 /var/www/kimai2/vendor/symfony/console/Application.php(145):                                                
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),   
         Object(Symfony\Component\Console\Output\ConsoleOutput))                                                        
         #8 /var/www/kimai2/bin/console(39):                                                                            
         Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))                  
         #9 {main} `

**Logfile**
```
see above
```

**Additional context**
 - 2.0
 - PHP 7.2
 - Ubuntu Server 18.04.02

**Comment by kevinpapst** [comment]
Maybe you found a bug. Can you replace this line:
https://github.com/kevinpapst/kimai2/blob/master/src/Command/KimaiImporterCommand.php#L835
with this code:
```php
->setBudget(isset($oldActivity['budget']) ? $oldActivity['budget'] : 0)
```
and try again?

**Comment by xentity** [comment]
@kevinpapst works like a charm, thx.

(now I have just to find out, how to change the doc root for a specific location to finish the migration)

**Comment by kevinpapst** [comment]
Hm ??? Webserver?
https://www.kimai.org/documentation/webserver-configuration.html
https://www.kimai.org/documentation/fresh-ubuntu-18.html

**Comment by xentity** [comment]
> Docroot = Webserver?
> https://www.kimai.org/documentation/webserver-configuration.html
> https://www.kimai.org/documentation/fresh-ubuntu-18.html

Well, it's getting off-topic: I have no greenfield env and have to integrate kimai2 into a reverse proxy structure:
domain.de/rev-app1
domain.de/rev-app2
domain.de/rev-app3
domain.de/local-app1

**Comment by kevinpapst** [comment]
Absolutely! 
You might want to move the ENV values to your VHost instead of .env.
Otherwise everyone can read your DB credentials ... until you fix the docroot.
